/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.LinearRecurrence.Inequality
public import TauCeti.Algebra.Algebra.RelationDimension

/-!
# The Golod–Shafarevich inequality for finite-dimensional algebras

Let `A` be a finite-dimensional algebra over a field `k` and `I` a proper two-sided ideal of `A`,
generated as a left ideal by `x₁, …, x_d` with `d ≥ 1`. Suppose that every relation
`∑ aᵢ xᵢ = 0` is an `A`-linear combination of `r` vectors `y₁, …, y_r ∈ A^d` whose entries all
lie in `I`. Then

```text
d² < 4 r.
```

For a finite `p`-group `G` this applies to `A = 𝔽_p[G]`, its augmentation ideal, a minimal
generating tuple `gᵢ` of `G` with `xᵢ = gᵢ - 1`, and the relators of a minimal presentation of
`G`, and gives the Golod–Shafarevich inequality `d(G)² < 4 r(G)`.

The proof follows Roquette. Write `P m` for the left ideal generated by `I ^ m`, so that
`P 0 = A` and `P (m + 1) = P m * I`, and `c m = dim_k (A ⧸ P m)`. Left multiplication of the `xᵢ`
by a tuple of elements of `P m` has image `P (m + 1)`, and a combination of the `yⱼ` with
coefficients in `P m` has all its entries in `P (m + 1)`. Counting dimensions for the induced
linear maps

```text
(A ⧸ P m)^r → (A ⧸ P (m + 1))^d → P 1 ⧸ P (m + 2),
```

whose maps satisfy `ker d₁ ≤ range d₂`, gives
`c (m + 2) + r c m ≥ c 1 + d c (m + 1) ≥ 1 + d c (m + 1)`. The sequence `c` is bounded by
`dim_k A`, so `TauCeti.sq_lt_four_mul_of_forall_add_mul_le` forces `d² < 4 r`.

## Main results

* `TauCeti.card_sq_lt_four_mul_card`: **the Golod–Shafarevich inequality** `d² < 4 r` for a
  finite-dimensional algebra with a proper two-sided ideal generated by `d ≥ 1` elements whose
  relations lie in the span of `r` vectors with entries in the ideal.

## References

* E. S. Golod and I. R. Shafarevich, *On the class field tower*, Izv. Akad. Nauk SSSR Ser. Mat.
  28 (1964).
* P. Roquette, *On class field towers*, in J. W. S. Cassels and A. Fröhlich (eds.), *Algebraic
  Number Theory*, Chapter IX, §4.
* J. Neukirch, A. Schmidt and K. Wingberg, *Cohomology of Number Fields*, 2nd ed., (3.9.7).
-/

public section

namespace TauCeti

open Module Submodule

variable {A : Type*} [Ring A] {ι κ : Type*} [Fintype ι] [Fintype κ]

/-- **The Golod–Shafarevich inequality for finite-dimensional algebras.** Let `A` be a
finite-dimensional algebra over a field `k` and `I` a proper two-sided ideal of `A`, generated as
a left ideal by a nonempty finite family `x`. If every relation `∑ aᵢ xᵢ = 0` among the generators
is an `A`-linear combination of a finite family `y` of vectors in `A^ι` with all entries in `I`,
then `(#x)² < 4 · #y`. -/
theorem card_sq_lt_four_mul_card (k : Type*) [Field k] [Algebra k A] [FiniteDimensional k A]
    [Nonempty ι] (I : Ideal A) [I.IsTwoSided] (hI : I ≠ ⊤)
    (x : ι → A) (hx : span A (Set.range x) = I) (y : κ → ι → A) (hy : ∀ j i, y j i ∈ I)
    (hker : ∀ a : ι → A, ∑ i, a i * x i = 0 → a ∈ span A (Set.range y)) :
    Fintype.card ι ^ 2 < 4 * Fintype.card κ := by
  -- `P m` is the left ideal generated by `I ^ m`, as a `k`-subspace of `A`.
  let J : Submodule k A := I.restrictScalars k
  let P : ℕ → Submodule k A := fun m ↦ ⊤ * J ^ m
  have hP0 : P 0 = ⊤ := by simp [P]
  have hPsucc (m : ℕ) : P (m + 1) = P m * J := by simp only [P, pow_succ, mul_assoc]
  have hxI (i : ι) : x i ∈ I := hx ▸ subset_span ⟨i, rfl⟩
  have hmem (m : ℕ) {a b : A} (ha : a ∈ P m) (hb : b ∈ I) : a * b ∈ P (m + 1) :=
    hPsucc m ▸ mul_mem_mul ha hb
  -- Each `P m` is a right ideal, because `I` is.
  have hright (m : ℕ) {a : A} (ha : a ∈ P m) (b : A) : a * b ∈ P m := by
    induction m generalizing a with
    | zero => simp [hP0]
    | succ m ih =>
      rw [hPsucc] at ha ⊢
      induction ha using Submodule.mul_induction_on' with
      | mem_mul_mem u hu v hv => rw [mul_assoc u v b]; exact mul_mem_mul hu (I.mul_mem_right b hv)
      | add a _ a' _ ha ha' => rw [add_mul]; exact add_mem ha ha'
  have hanti : Antitone P := antitone_nat_of_succ_le fun m ↦
    hPsucc m ▸ mul_le.2 fun a ha _ _ ↦ hright m ha _
  -- Every element of `P (m + 1)` is a `P m`-combination of the generators.
  have hsurj (m : ℕ) (t : A) (ht : t ∈ P (m + 1)) :
      ∃ a : ι → A, (∀ i, a i ∈ P m) ∧ ∑ i, a i * x i = t := by
    rw [hPsucc] at ht
    induction ht using Submodule.mul_induction_on' with
    | mem_mul_mem u hu v hv =>
      obtain ⟨c, rfl⟩ := (mem_span_range_iff_exists_fun A).1 (by rw [hx]; exact hv)
      exact ⟨fun i ↦ u * c i, fun i ↦ hright m hu _, by simp [Finset.mul_sum, mul_assoc]⟩
    | add t _ t' _ ht ht' =>
      obtain ⟨a, ha, rfl⟩ := ht
      obtain ⟨a', ha', rfl⟩ := ht'
      exact ⟨a + a', fun i ↦ add_mem (ha i) (ha' i), by
        simp [add_mul, Finset.sum_add_distrib]⟩
  have hxP1 (a : ι → A) : ∑ i, a i * x i ∈ P 1 :=
    sum_mem fun i _ ↦ hmem 0 (hP0 ▸ mem_top) (hxI i)
  -- The codimensions `c m = dim (A ⧸ P m)` satisfy the Golod–Shafarevich recurrence.
  let c : ℕ → ℕ := fun m ↦ finrank k (A ⧸ P m)
  have hc (m : ℕ) : c m + finrank k (P m) = finrank k A := (P m).finrank_quotient_add_finrank
  have hc0 : c 0 = 0 := by have := hc 0; rw [hP0, finrank_top] at this; omega
  have hc1 : 1 ≤ c 1 := by
    have hP1 : P 1 ≠ ⊤ := by
      refine fun h ↦ hI ((I.eq_top_iff_one).2 ?_)
      have hle : P 1 ≤ J := hPsucc 0 ▸ mul_le.2 fun u _ v hv ↦ I.mul_mem_left u hv
      exact hle (h ▸ mem_top)
    have := Submodule.finrank_lt hP1
    have := hc 1
    omega
  refine sq_lt_four_mul_of_forall_add_mul_le Fintype.card_pos hc0
    ⟨finrank k A, by rintro _ ⟨m, rfl⟩; have := hc m; omega⟩ fun m ↦ ?_
  have := card_mul_finrank_quotient_add_le x y hker (W := P m) (U := P (m + 1)) (T := P (m + 2))
    (S := P 1) (fun w hw j i ↦ hmem m hw (hy j i)) (fun u hu i ↦ hmem (m + 1) hu (hxI i))
    (hanti (by omega)) hxP1 (hsurj (m + 1))
  simp only [c] at hc1 ⊢
  omega

end TauCeti
