/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Filtration
public import TauCeti.GroupTheory.Subgroup.FiniteFiltration
public import TauCeti.RingTheory.Ideal.Inertia

/-!
# Higher ramification groups in the lower numbering

Let a group `G` act on a commutative ring `B` and let `Q` be an ideal of `B`. The **`i`-th
ramification group** of `Q` is the group of elements acting trivially on `B ⧸ Q ^ (i + 1)`,

`G_i(Q) = {σ ∈ G | σ • x - x ∈ Q ^ (i + 1) for every x : B}`,

which is Mathlib's `Ideal.inertia` at the ideal `Q ^ (i + 1)`. At `i = 0` it is the inertia
group of `Q` itself. In the finite flat integral-closure/Galois setting, if `P` lies over a prime
`p` whose residue field is perfect, then
`Nat.card (P.inertia G) = p.ramificationIdxIn S`
(`Ideal.card_inertia_eq_ramificationIdxIn`). The higher groups refine inertia by order of contact;
this is the *lower numbering*.

The filtration decreases, sits inside the decomposition group `MulAction.stabilizer G Q`, is
normal there, and is conjugated by `σ` when `Q` is moved to `σ • Q`. Over a Noetherian domain,
for a proper `Q` and a faithful action, Krull's intersection theorem makes the groups meet in
the trivial group, so a finite `G` has `G_i(Q) = 1` from some index on.

When `B = A[x]` is generated by one element over a semiring `A` whose image `G` fixes, membership
in the filtration is readable from the single difference `σ • x - x`.

## Main definitions

* `Ideal.ramificationGroup`: the `i`-th ramification group of an ideal, in the lower numbering.

## Main results

* `Ideal.ramificationGroup_zero`: the `0`-th ramification group is the inertia group.
* `Ideal.ramificationGroup_antitone`, `Ideal.ramificationGroup_le_stabilizer`: the filtration
  decreases, inside the decomposition group.
* `Ideal.ramificationGroup_smul`: moving `Q` by `σ` conjugates the ramification groups by `σ`;
  consequently they are normal in the decomposition group.
* `Ideal.ramificationGroup_map_subtype`: the ramification groups of a subgroup `H ≤ G` are the
  traces on `H` of the ramification groups of `G`.
* `Ideal.iInf_ramificationGroup_eq_bot`, `Ideal.exists_ramificationGroup_eq_bot`: the
  ramification groups meet in the trivial group, and are trivial from some index on for a finite
  `G`.
* `Ideal.mem_ramificationGroup_iff_of_adjoin_singleton_eq_top`: membership is decided on a single
  generator of a monogenic algebra.

## References

* J.-P. Serre, *Corps Locaux*, Hermann, Paris, 1968, Chapter IV §1.
-/

public section

open MulAction

open scoped Pointwise

namespace Ideal

variable {B : Type*} [CommRing B] (G : Type*) [Group G]

section MulAction

variable [MulAction G B]

/-- **The `i`-th ramification group of an ideal `Q`, in the lower numbering**: the elements of
`G` that act trivially on `B ⧸ Q ^ (i + 1)`. It is `Ideal.inertia` at the ideal `Q ^ (i + 1)`,
and the index `i` records the order of contact, so that `G_0` is the inertia group of `Q`. -/
def ramificationGroup (Q : Ideal B) (i : ℕ) : Subgroup G := (Q ^ (i + 1)).inertia G

variable {G}

@[simp]
theorem mem_ramificationGroup_iff {Q : Ideal B} {i : ℕ} {σ : G} :
    σ ∈ Q.ramificationGroup G i ↔ ∀ x : B, σ • x - x ∈ Q ^ (i + 1) :=
  Ideal.mem_inertia

variable (G)

theorem ramificationGroup_eq_inertia_pow (Q : Ideal B) (i : ℕ) :
    Q.ramificationGroup G i = (Q ^ (i + 1)).inertia G :=
  (rfl)

/-- The zeroth ramification group is the inertia group. -/
@[simp]
theorem ramificationGroup_zero (Q : Ideal B) : Q.ramificationGroup G 0 = Q.inertia G := by
  rw [ramificationGroup_eq_inertia_pow, zero_add, pow_one]

/-- The lower-numbering ramification groups form a decreasing filtration. -/
theorem ramificationGroup_antitone (Q : Ideal B) : Antitone (Q.ramificationGroup G) := by
  intro i j hij σ hσ
  rw [mem_ramificationGroup_iff] at hσ ⊢
  exact fun x ↦ Ideal.pow_le_pow_right (by omega) (hσ x)

theorem ramificationGroup_le_inertia (Q : Ideal B) (i : ℕ) :
    Q.ramificationGroup G i ≤ Q.inertia G := by
  simpa using ramificationGroup_antitone G Q (Nat.zero_le i)

/-- Restricting a ramification group of `G` to a subgroup `H` gives the corresponding
ramification group of `H`. -/
@[simp]
theorem subgroupOf_ramificationGroup (H : Subgroup G) (Q : Ideal B) (i : ℕ) :
    (Q.ramificationGroup G i).subgroupOf H = Q.ramificationGroup H i :=
  AddSubgroup.subgroupOf_inertia _ H

/-- The ramification groups of a subgroup `H` of `G` are the ramification groups of `G`
intersected with `H`. -/
@[simp]
theorem ramificationGroup_map_subtype (H : Subgroup G) (Q : Ideal B) (i : ℕ) :
    (Q.ramificationGroup H i).map H.subtype = Q.ramificationGroup G i ⊓ H :=
  AddSubgroup.inertia_map_subtype _ H

/-- **The ramification groups of a proper ideal meet in the trivial group.** An element of all
of them moves every ring element by something in every power of `Q`, and Krull's intersection
theorem makes that difference zero. -/
theorem iInf_ramificationGroup_eq_bot [IsNoetherianRing B] [IsDomain B] [FaithfulSMul G B]
    (Q : Ideal B) (hQ : Q ≠ ⊤) : ⨅ i, Q.ramificationGroup G i = ⊥ := by
  rw [eq_bot_iff]
  intro σ hσ
  rw [Subgroup.mem_iInf] at hσ
  rw [Subgroup.mem_bot]
  refine eq_of_smul_eq_smul (α := B) fun x ↦ ?_
  have hmem : σ • x - x ∈ ⨅ i : ℕ, Q ^ i := by
    rw [Submodule.mem_iInf]
    exact fun i ↦ Ideal.pow_le_pow_right (Nat.le_succ i)
      (mem_ramificationGroup_iff.mp (hσ i) x)
  rw [Ideal.iInf_pow_eq_bot_of_isDomain Q hQ, Ideal.mem_bot, sub_eq_zero] at hmem
  rw [one_smul]
  exact hmem

/-- **The ramification groups of a proper ideal are trivial from some index on**, for a finite
group. -/
theorem exists_ramificationGroup_eq_bot [Finite G] [IsNoetherianRing B] [IsDomain B]
    [FaithfulSMul G B] (Q : Ideal B) (hQ : Q ≠ ⊤) :
    ∃ i, Q.ramificationGroup G i = ⊥ := by
  obtain ⟨N, hN⟩ := Subgroup.exists_forall_eq_bot_of_antitone_iInf_eq_bot
    (Q.ramificationGroup G) (ramificationGroup_antitone G Q)
    (iInf_ramificationGroup_eq_bot G Q hQ)
  exact ⟨N, hN N le_rfl⟩

end MulAction

section MulSemiringAction

variable [MulSemiringAction G B]

/-- Every ramification group is contained in the decomposition group stabilizing the ideal. -/
theorem ramificationGroup_le_stabilizer (Q : Ideal B) (i : ℕ) :
    Q.ramificationGroup G i ≤ stabilizer G Q :=
  (ramificationGroup_le_inertia G Q i).trans (Ideal.inertia_le_stabilizer (M := G) Q)

/-- **Moving `Q` by `σ` conjugates the ramification groups by `σ`.** -/
theorem ramificationGroup_smul (σ : G) (Q : Ideal B) (i : ℕ) :
    (σ • Q).ramificationGroup G i = (Q.ramificationGroup G i).map (MulAut.conj σ) := by
  rw [ramificationGroup_eq_inertia_pow, ramificationGroup_eq_inertia_pow, ← smul_pow',
    Ideal.inertia_smul]

/-- The ramification groups are normal in the decomposition group. -/
instance (Q : Ideal B) (i : ℕ) : (Q.ramificationGroup (stabilizer G Q) i).Normal := by
  simp_rw [Subgroup.normal_iff_map_conj_eq, ← ramificationGroup_smul]
  exact fun g ↦ congrArg (ramificationGroup _ · i) g.2

variable {G}

/-- **The ramification groups of a monogenic algebra are read off its generator.** -/
theorem mem_ramificationGroup_iff_of_adjoin_singleton_eq_top {A : Type*} [CommSemiring A]
    [Algebra A B] [SMulCommClass G A B] (Q : Ideal B) (i : ℕ) {x : B}
    (hx : Algebra.adjoin A ({x} : Set B) = ⊤) {σ : G} :
    σ ∈ Q.ramificationGroup G i ↔ σ • x - x ∈ Q ^ (i + 1) := by
  rw [ramificationGroup_eq_inertia_pow,
    mem_inertia_iff_of_adjoin_eq_top (A := A) _ hx]
  simp

end MulSemiringAction

end Ideal
