/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Analysis.Semigroups.Generator
public import TauCeti.Analysis.Semigroups.GrowthBound

/-!
# The identity strongly continuous semigroup

This file records the identity C₀-semigroup, equivalently the semigroup generated by the
zero bounded operator. It supplies the smallest concrete example for the bounded-generator
acceptance examples in the one-parameter-semigroups roadmap.

## References
This is the zero-generator case of the standard uniformly continuous semigroup
`S(t) = exp(tA)`.
-/

public section

noncomputable section

open scoped NNReal Topology

namespace TauCeti.Semigroups

variable (X : Type*) [NormedAddCommGroup X] [NormedSpace ℝ X]

namespace StronglyContinuousSemigroup

/-- The identity C₀-semigroup `S(t) = id`, generated by the zero operator. -/
def id : StronglyContinuousSemigroup X where
  toFun _ := ContinuousLinearMap.id ℝ X
  map_zero' := rfl
  map_add' _ _ := by
    ext x
    rfl
  continuousAt_zero' x := by
    simpa using (continuous_const : Continuous fun _ : ℝ≥0 => x).continuousAt

variable {X}

/-- The identity C₀-semigroup is constantly the identity operator. -/
@[simp]
theorem id_apply (t : ℝ≥0) :
    (StronglyContinuousSemigroup.id X) t = ContinuousLinearMap.id ℝ X :=
  by
    rw [StronglyContinuousSemigroup.id]
    rfl

/-- Pointwise form of `StronglyContinuousSemigroup.id_apply`. -/
theorem id_apply_apply (t : ℝ≥0) (x : X) :
    (StronglyContinuousSemigroup.id X) t x = x :=
  by
    rw [id_apply]
    rfl

/-- The identity semigroup has the contraction growth bound `(0, 1)`. -/
theorem id_hasGrowthBound :
    (StronglyContinuousSemigroup.id X).HasGrowthBound 0 1 :=
  StronglyContinuousSemigroup.hasGrowthBound_of_bound le_rfl (fun t ht => by
    have ht_coe : ((t.toNNReal : ℝ) = t) := Real.coe_toNNReal t ht
    rw [← ht_coe, StronglyContinuousSemigroup.realOperator_coe, id_apply]
    simpa using (ContinuousLinearMap.norm_id_le (𝕜 := ℝ) (E := X)))

variable [CompleteSpace X]

omit [CompleteSpace X] in
/-- Every vector lies in the generator domain of the identity semigroup. -/
theorem mem_id_domain (x : X) :
    x ∈ (StronglyContinuousSemigroup.id X).domain := by
  rw [(StronglyContinuousSemigroup.id X).mem_domain_iff_tendsto]
  refine ⟨0, ?_⟩
  refine (tendsto_const_nhds : Filter.Tendsto (fun _ : ℝ => (0 : X))
    (nhdsWithin 0 (Set.Ioi 0)) (nhds 0)).congr' ?_
  filter_upwards [self_mem_nhdsWithin] with t ht
  have ht_coe : ((t.toNNReal : ℝ) = t) := Real.coe_toNNReal t ht.le
  rw [← ht_coe, StronglyContinuousSemigroup.realOperator_coe, id_apply_apply, sub_self,
    smul_zero]

omit [CompleteSpace X] in
/-- The generator domain of the identity semigroup is all of the space. -/
@[simp]
theorem id_domain :
    (StronglyContinuousSemigroup.id X).domain = ⊤ := by
  ext x
  simp [mem_id_domain]

omit [CompleteSpace X] in
/-- The generator of the identity semigroup is the zero operator on its domain. -/
theorem id_generator_apply (x : (StronglyContinuousSemigroup.id X).domain) :
    (StronglyContinuousSemigroup.id X).generator
      ⟨(x : X), by
        rw [(StronglyContinuousSemigroup.id X).generator_domain]
        exact x.property⟩ = 0 := by
  refine (StronglyContinuousSemigroup.id X).generator_eq_of_tendsto x.property ?_
  refine (tendsto_const_nhds : Filter.Tendsto (fun _ : ℝ => (0 : X))
    (nhdsWithin 0 (Set.Ioi 0)) (nhds 0)).congr' ?_
  filter_upwards [self_mem_nhdsWithin] with t ht
  have ht_coe : ((t.toNNReal : ℝ) = t) := Real.coe_toNNReal t ht.le
  rw [← ht_coe, StronglyContinuousSemigroup.realOperator_coe, id_apply_apply, sub_self,
    smul_zero]

omit [CompleteSpace X] in
/-- The identity semigroup's generator sends every ambient vector to zero after coercing
through its all-space domain. -/
theorem id_generator_apply_of_mem (x : X) (hx : x ∈ (StronglyContinuousSemigroup.id X).domain) :
    (StronglyContinuousSemigroup.id X).generator
      ⟨x, by
        rw [(StronglyContinuousSemigroup.id X).generator_domain]
        exact hx⟩ = 0 :=
  id_generator_apply ⟨x, hx⟩

end StronglyContinuousSemigroup

namespace ContractionSemigroup

/-- The identity contraction semigroup. -/
def id : ContractionSemigroup X where
  toStronglyContinuousSemigroup := StronglyContinuousSemigroup.id X
  contracting _ := by
    change ‖ContinuousLinearMap.id ℝ X‖ ≤ 1
    exact ContinuousLinearMap.norm_id_le

/-- The identity contraction semigroup is constantly the identity operator. -/
@[simp]
theorem id_apply (t : ℝ≥0) :
    (ContractionSemigroup.id X) t = ContinuousLinearMap.id ℝ X :=
  by
    rw [ContractionSemigroup.id]
    rfl

/-- Pointwise form of `ContractionSemigroup.id_apply`. -/
theorem id_apply_apply (t : ℝ≥0) (x : X) :
    (ContractionSemigroup.id X) t x = x :=
  by
    rw [id_apply]
    rfl

/-- The C₀-semigroup underlying the identity contraction semigroup. -/
@[simp]
theorem id_toStronglyContinuousSemigroup :
    (ContractionSemigroup.id X).toStronglyContinuousSemigroup =
      StronglyContinuousSemigroup.id X :=
  by
    rw [ContractionSemigroup.id]

end ContractionSemigroup

end TauCeti.Semigroups

end
