/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.HighestWeight.Verma
public import TauCeti.LinearAlgebra.RootSystem.KostantPartition.Basic

-- Non-public: `TauCeti.lie_mem_weightSpace_of_mem_weightSpace`, the weight shift by a root vector.
import TauCeti.Algebra.Lie.Weights.Eigenvector

/-!
# The weights of a Verma module and their multiplicities

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over a field `K` of
characteristic zero, `H` a splitting Cartan subalgebra and `b` a base of its root system. The
Verma module `M(lam)` is a free `U(n⁻)`-module of rank one on its canonical generator `v_lam`
(`TauCeti.universalEnvelopingEquivVermaModule`), so a Poincaré--Birkhoff--Witt basis of `U(n⁻)`
gives a basis of `M(lam)`: the vectors

`f_{i₁} ⋯ f_{iₖ} · v_lam`,   `i₁ ≤ ⋯ ≤ iₖ`,

for an ordered basis `(f_i)` of the negative nilradical `n⁻`. When every `f_i` is an
`H`-eigenvector of weight `w_i`, the vector attached to the exponent `n` is an `H`-eigenvector of
weight `lam + ∑ᵢ nᵢ wᵢ`, so the weight space `M(lam)_mu` is spanned by the basis vectors of that
weight and its dimension is the number of exponents `n` with `lam + ∑ᵢ nᵢ wᵢ = mu`
(`TauCeti.finrank_weightSpace_vermaModule_eq_natCard`).

The negative nilradical has such a basis made of root vectors, one for each positive root `α`,
lying in the line `L_{-α}` (`TauCeti.negativeNilradicalBasis`). With it the count becomes the
number of ways of writing `lam - mu` as a sum of positive roots with multiplicity, which is the
Kostant partition function: **the weight multiplicities of a Verma module are**

`dim M(lam)_mu = P(lam - mu)`

(`TauCeti.finrank_weightSpace_vermaModule`). In particular the weights of `M(lam)` are exactly the
elements of `lam` minus the monoid generated by the positive roots
(`TauCeti.weightSpace_vermaModule_ne_bot_iff`), and `M(lam)` is the sum of its weight spaces
(`TauCeti.iSup_weightSpace_vermaModule_eq_top`).

## Main definitions

* `TauCeti.vermaBasis`: the basis of `M(lam)` obtained by applying the ordered monomials in a basis
  of `n⁻` to the canonical generator.

## Main results

* `TauCeti.vermaBasis_mem_weightSpace`: for a basis of `n⁻` made of weight vectors, every vector of
  the associated basis of `M(lam)` is a weight vector, of the weight read off its exponent.
* `TauCeti.weightSpace_vermaModule_eq_span` and
  `TauCeti.finrank_weightSpace_vermaModule_eq_natCard`: a weight space of `M(lam)` is spanned by
  the basis vectors of that weight, so its dimension counts the exponents of that weight.
* `TauCeti.finrank_weightSpace_vermaModule`: **`dim M(lam)_mu = P(lam - mu)`**, the Kostant
  partition function of `lam - mu`.
* `TauCeti.weightSpace_vermaModule_ne_bot_iff`: `mu` is a weight of `M(lam)` exactly when
  `lam - mu` is a sum of positive roots.
* `TauCeti.iSup_weightSpace_vermaModule_eq_top`: the Verma module is the sum of its weight spaces.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §20.3 and
  §24.1.
* J. E. Humphreys, *Representations of Semisimple Lie Algebras in the BGG Category `O`*, §1.3.
-/

public section

open UniversalEnvelopingAlgebra

namespace TauCeti

open LieAlgebra LieModule Module

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [LieRing L] [LieAlgebra K L]
  [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra] [IsTriangularizable K H L]

local notation "U" => _root_.UniversalEnvelopingAlgebra K L

/-! ### The Poincaré--Birkhoff--Witt basis of a Verma module -/

section VermaBasis

variable (b : (IsKilling.rootSystem H).Base) (lam : Dual K H) {σ : Type w} [LinearOrder σ]
  (B : Basis σ K (negativeNilradical H b))

/-- The canonical generator `v_lam` is a weight vector of weight `lam`. -/
private theorem vermaGenerator_mem_weightSpace :
    vermaGenerator b lam ∈ weightSpace (VermaModule b lam) (lam : H → K) := by
  rw [mem_weightSpace]
  intro h
  simp only [LieSubalgebra.coe_bracket_of_module, lie_vermaGenerator_eq_smul]

/-- A product of eigenvectors of the adjoint action, applied to `v_lam`, is a weight vector whose
weight is `lam` shifted by their eigenvalues. -/
private theorem prod_smul_vermaGenerator_mem_weightSpace {κ : Type*} {f : κ → L}
    {w : κ → Dual K H} (hf : ∀ i (h : H), ⁅(h : L), f i⁆ = w i h • f i) (word : List κ) :
    ((word.map fun i ↦ ι K (f i)).prod : U) • vermaGenerator b lam ∈
      weightSpace (VermaModule b lam) ((lam + (word.map w).sum : Dual K H) : H → K) := by
  induction word with
  | nil => simpa using vermaGenerator_mem_weightSpace b lam
  | cons i word ih =>
    simp only [List.map_cons, List.prod_cons, List.sum_cons]
    rw [mul_smul, vermaModule_ι_smul]
    convert lie_mem_weightSpace_of_mem_weightSpace (hf i) ih using 2
    ext h
    simp only [LinearMap.add_apply, Pi.add_apply]
    ring

/-- **The Poincaré--Birkhoff--Witt basis of the Verma module** attached to an ordered basis `B` of
the negative nilradical: the vector of exponent `n` is the ordered monomial of
`Module.Basis.pbwBasis` in `B`, with exponent `n`, applied to the canonical generator
`v_lam` (`TauCeti.vermaBasis_apply`). It is a basis because `M(lam)` is a free `U(n⁻)`-module of
rank one on `v_lam`. -/
noncomputable def vermaBasis : Basis (σ →₀ ℕ) K (VermaModule b lam) :=
  B.pbwBasis.map (universalEnvelopingEquivVermaModule b lam)

/-- The basis vector of exponent `n` is the ordered monomial of exponent `n` in `B`, applied to the
canonical generator. -/
theorem vermaBasis_apply (n : σ →₀ ℕ) :
    vermaBasis b lam B n =
      UniversalEnvelopingAlgebra.map K (negativeNilradical H b).incl (B.pbwBasis n) •
        vermaGenerator b lam := by
  rw [vermaBasis, Basis.map_apply, universalEnvelopingEquivVermaModule_apply]

/-- **The basis vectors of a Verma module are weight vectors.** If the Cartan subalgebra acts on
each vector `B i` of the basis of `n⁻` through `w i`, then the basis vector of exponent `n` has
weight `lam + ∑ᵢ nᵢ w i`. -/
theorem vermaBasis_mem_weightSpace {w : σ → Dual K H}
    (hB : ∀ i (h : H), ⁅(h : L), (B i : L)⁆ = w i h • (B i : L)) (n : σ →₀ ℕ) :
    vermaBasis b lam B n ∈ weightSpace (VermaModule b lam)
      ((lam + n.sum fun i k ↦ k • w i : Dual K H) : H → K) := by
  have hsum : ((n.toMultiset.sort (· ≤ ·)).map w).sum = n.sum fun i k ↦ k • w i := by
    rw [← Multiset.sum_coe, ← Multiset.map_coe, Multiset.sort_eq, Finsupp.toMultiset_map,
      Finsupp.sum_toMultiset, Finsupp.sum_mapDomain_index (h := fun a k ↦ k • a)
        (fun _ ↦ zero_nsmul _) fun _ _ _ ↦ add_nsmul _ _ _]
  rw [← hsum, vermaBasis_apply, Basis.pbwBasis_apply, UniversalEnvelopingAlgebra.pbwMonomial_def,
    map_list_prod,
    List.map_map, List.map_map]
  convert prod_smul_vermaGenerator_mem_weightSpace b lam hB (n.toMultiset.sort (· ≤ ·))
  simp [Function.comp_def]

/-- **A weight space of a Verma module is spanned by the basis vectors of that weight.** If the
Cartan subalgebra acts on each vector `B i` of the basis of `n⁻` through `w i`, the weight space
`M(lam)_mu` is spanned by the basis vectors whose exponent `n` satisfies `lam + ∑ᵢ nᵢ w i = mu`. -/
theorem weightSpace_vermaModule_eq_span {w : σ → Dual K H}
    (hB : ∀ i (h : H), ⁅(h : L), (B i : L)⁆ = w i h • (B i : L)) (mu : Dual K H) :
    (weightSpace (VermaModule b lam) (mu : H → K)).toSubmodule =
      Submodule.span K
        (vermaBasis b lam B '' {n | lam + (n.sum fun i k ↦ k • w i) = mu}) := by
  set V := vermaBasis b lam B
  have hV (n : σ →₀ ℕ) : V n ∈ weightSpace (VermaModule b lam)
      ((lam + n.sum fun i k ↦ k • w i : Dual K H) : H → K) :=
    vermaBasis_mem_weightSpace b lam B hB n
  -- the action of `h` is diagonal in the basis `V`, with the weights of the basis vectors
  have hcoord (n : σ →₀ ℕ) (h : H) (m : VermaModule b lam) :
      V.coord n ⁅(h : L), m⁆ = (lam + n.sum fun i k ↦ k • w i : Dual K H) h * V.coord n m := by
    have hcomp : (V.coord n).comp (toEnd K L (VermaModule b lam) (h : L)) =
        (lam + n.sum fun i k ↦ k • w i : Dual K H) h • V.coord n := by
      refine V.ext fun n' ↦ ?_
      have h' := (mem_weightSpace _ _).mp (hV n') h
      rw [LieSubalgebra.coe_bracket_of_module] at h'
      rw [LinearMap.comp_apply, toEnd_apply_apply, h', map_smul, LinearMap.smul_apply]
      by_cases hnn : n' = n
      · subst hnn
        rfl
      · simp [Basis.coord_apply, Basis.repr_self, hnn]
    simpa using LinearMap.congr_fun hcomp m
  refine le_antisymm (fun m hm ↦ ?_) (Submodule.span_le.mpr ?_)
  · rw [Basis.mem_span_image]
    intro n hn
    rw [Finset.mem_coe, Finsupp.mem_support_iff] at hn
    refine LinearMap.ext fun h ↦ ?_
    have hm' := (mem_weightSpace _ _).mp hm h
    rw [LieSubalgebra.coe_bracket_of_module] at hm'
    have := hcoord n h m
    rw [hm', map_smul, smul_eq_mul] at this
    exact (mul_right_cancel₀ hn this).symm
  · rintro _ ⟨n, hn, rfl⟩
    have := hV n
    rwa [Set.mem_ofPred_eq.mp hn] at this

/-- **The weight multiplicities of a Verma module count exponents.** If the Cartan subalgebra acts
on each vector `B i` of the basis of `n⁻` through `w i`, then the weight space `M(lam)_mu` has
dimension the number of exponents `n` with `lam + ∑ᵢ nᵢ w i = mu`. When there are infinitely many
such exponents both sides are `0`. -/
theorem finrank_weightSpace_vermaModule_eq_natCard {w : σ → Dual K H}
    (hB : ∀ i (h : H), ⁅(h : L), (B i : L)⁆ = w i h • (B i : L)) (mu : Dual K H) :
    finrank K (weightSpace (VermaModule b lam) (mu : H → K)) =
      Nat.card {n : σ →₀ ℕ // lam + (n.sum fun i k ↦ k • w i) = mu} := by
  have hli : LinearIndependent K
      fun n : ({n | lam + (n.sum fun i k ↦ k • w i) = mu} : Set (σ →₀ ℕ)) ↦ vermaBasis b lam B n :=
    (vermaBasis b lam B).linearIndependent.comp _ Subtype.val_injective
  -- a weight space and its underlying subspace have the same carrier
  have hfin : finrank K (weightSpace (VermaModule b lam) (mu : H → K)) =
      finrank K (weightSpace (VermaModule b lam) (mu : H → K)).toSubmodule := rfl
  rw [hfin, weightSpace_vermaModule_eq_span b lam B hB, Set.image_eq_range, Module.finrank,
    rank_span hli]
  exact Nat.card_range_of_injective hli.injective

/-- **The weights of a Verma module.** If the Cartan subalgebra acts on each vector `B i` of the
basis of `n⁻` through `w i`, then `mu` is a weight of `M(lam)` exactly when it is
`lam + ∑ᵢ nᵢ w i` for some exponent `n`. -/
theorem weightSpace_vermaModule_ne_bot_iff_exists {w : σ → Dual K H}
    (hB : ∀ i (h : H), ⁅(h : L), (B i : L)⁆ = w i h • (B i : L)) (mu : Dual K H) :
    weightSpace (VermaModule b lam) (mu : H → K) ≠ ⊥ ↔
      ∃ n : σ →₀ ℕ, lam + (n.sum fun i k ↦ k • w i) = mu := by
  rw [ne_eq, ← LieSubmodule.toSubmodule_eq_bot, weightSpace_vermaModule_eq_span b lam B hB,
    Submodule.span_eq_bot]
  simp only [Set.mem_image, Set.mem_ofPred_eq, forall_exists_index, and_imp,
    forall_apply_eq_imp_iff₂, (vermaBasis b lam B).ne_zero, imp_false, not_forall, not_not]

end VermaBasis

/-! ### The multiplicities are given by the Kostant partition function -/

section Kostant

variable (b : (IsKilling.rootSystem H).Base) (lam : Dual K H)

/-- `TauCeti.lie_negativeNilradicalBasis` in the form the results of the previous section consume:
the Cartan subalgebra acts on the root vector of index `α` through the linear form `-α`. -/
private theorem lie_negativeNilradicalBasis_eq_neg_root_smul
    (i : posRoots (IsKilling.rootSystem H) b) (h : H) :
    ⁅(h : L), (negativeNilradicalBasis H b i : L)⁆ =
      (-(IsKilling.rootSystem H).root i) h • (negativeNilradicalBasis H b i : L) := by
  rw [lie_negativeNilradicalBasis, LinearMap.neg_apply]

open Classical in
/-- An exponent on the positive roots, read as a multiplicity function on all roots, vanishing off
the positive ones. -/
private noncomputable def extendExponent (n : posRoots (IsKilling.rootSystem H) b →₀ ℕ) :
    H.root → ℕ :=
  fun i ↦ if hi : i ∈ posRoots (IsKilling.rootSystem H) b then n ⟨i, hi⟩ else 0

private theorem extendExponent_of_mem (n : posRoots (IsKilling.rootSystem H) b →₀ ℕ)
    (i : posRoots (IsKilling.rootSystem H) b) : extendExponent b n i = n i := by
  simp [extendExponent, i.2]

private theorem support_extendExponent_subset (n : posRoots (IsKilling.rootSystem H) b →₀ ℕ) :
    Function.support (extendExponent b n) ⊆ posRoots (IsKilling.rootSystem H) b := by
  intro i hi
  by_contra h
  simp [extendExponent, h] at hi

/-- A multiplicity function supported on the positive roots is the extension of its restriction. -/
private theorem extendExponent_equivFunOnFinite_symm {c : H.root → ℕ}
    (hc : Function.support c ⊆ posRoots (IsKilling.rootSystem H) b) :
    extendExponent b (Finsupp.equivFunOnFinite.symm fun i ↦ c i) = c := by
  ext i
  by_cases hi : i ∈ posRoots (IsKilling.rootSystem H) b
  · simp [extendExponent, hi]
  · have : c i = 0 := by
      by_contra h
      exact hi (hc (Function.mem_support.mpr h))
    simp [extendExponent, hi, this]

private theorem sum_extendExponent (n : posRoots (IsKilling.rootSystem H) b →₀ ℕ) :
    ∑ i ∈ posRootsFinset (IsKilling.rootSystem H) b,
        extendExponent b n i • (IsKilling.rootSystem H).root i =
      n.sum fun i k ↦ k • (IsKilling.rootSystem H).root i := by
  have := Fintype.ofFinite (posRoots (IsKilling.rootSystem H) b)
  rw [Finset.sum_subtype _ (mem_posRootsFinset _ b),
    Finsupp.sum_fintype n (fun i k ↦ k • (IsKilling.rootSystem H).root i) fun _ ↦ zero_nsmul _]
  exact Finset.sum_congr rfl fun i _ ↦ by rw [extendExponent_of_mem]

/-- The weight `lam + ∑ᵢ nᵢ (-αᵢ)` of a basis vector is `mu` exactly when `∑ᵢ nᵢ αᵢ = lam - mu`. -/
private theorem add_sum_smul_neg_eq_iff (n : posRoots (IsKilling.rootSystem H) b →₀ ℕ)
    (mu : Dual K H) :
    lam + (n.sum fun i k ↦ k • -(IsKilling.rootSystem H).root i) = mu ↔
      (n.sum fun i k ↦ k • (IsKilling.rootSystem H).root i) = lam - mu := by
  simp only [Finsupp.sum, smul_neg, Finset.sum_neg_distrib, ← sub_eq_add_neg]
  constructor
  · rintro rfl
    abel
  · intro h
    rw [h]
    abel

/-- The exponents on the positive roots whose basis vector of `M(lam)` has weight `mu` are the
Kostant partitions of `lam - mu`. -/
private noncomputable def exponentEquivKostantPartition (mu : Dual K H) :
    {n : posRoots (IsKilling.rootSystem H) b →₀ ℕ //
        lam + (n.sum fun i k ↦ k • -(IsKilling.rootSystem H).root i) = mu} ≃
      {c : H.root → ℕ // IsKostantPartition (IsKilling.rootSystem H) b (lam - mu) c} where
  toFun n := ⟨extendExponent b n.1, (isKostantPartition_iff _ _ _ _).mpr
    ⟨support_extendExponent_subset b n.1, by
      rw [sum_extendExponent]
      exact (add_sum_smul_neg_eq_iff b lam n.1 mu).mp n.2⟩⟩
  invFun c := ⟨Finsupp.equivFunOnFinite.symm fun i ↦ c.1 i, by
    obtain ⟨hsupp, hsum⟩ := (isKostantPartition_iff _ _ _ _).mp c.2
    rw [add_sum_smul_neg_eq_iff, ← sum_extendExponent, extendExponent_equivFunOnFinite_symm b hsupp]
    exact hsum⟩
  left_inv n := Subtype.ext <| Finsupp.ext fun i ↦ by
    simp [extendExponent_of_mem]
  right_inv c := Subtype.ext <|
    extendExponent_equivFunOnFinite_symm b ((isKostantPartition_iff _ _ _ _).mp c.2).1

/-- **The weight multiplicities of a Verma module are given by the Kostant partition function**:
the weight space `M(lam)_mu` has dimension `P(lam - mu)`, the number of ways of writing `lam - mu`
as a sum of positive roots with multiplicity. -/
theorem finrank_weightSpace_vermaModule (mu : Dual K H) :
    finrank K (weightSpace (VermaModule b lam) (mu : H → K)) =
      kostantPartition (IsKilling.rootSystem H) b (lam - mu) := by
  let : LinearOrder (posRoots (IsKilling.rootSystem H) b) :=
    LinearOrder.lift' (Finite.equivFin _) (Finite.equivFin _).injective
  rw [finrank_weightSpace_vermaModule_eq_natCard b lam (negativeNilradicalBasis H b)
    (lie_negativeNilradicalBasis_eq_neg_root_smul b) mu, kostantPartition_def]
  exact Nat.card_congr (exponentEquivKostantPartition b lam mu)

/-- **The weights of a Verma module**: `mu` is a weight of `M(lam)` exactly when `lam - mu` is a
sum of positive roots with multiplicity. -/
theorem weightSpace_vermaModule_ne_bot_iff (mu : Dual K H) :
    weightSpace (VermaModule b lam) (mu : H → K) ≠ ⊥ ↔
      ∃ c, IsKostantPartition (IsKilling.rootSystem H) b (lam - mu) c := by
  let : LinearOrder (posRoots (IsKilling.rootSystem H) b) :=
    LinearOrder.lift' (Finite.equivFin _) (Finite.equivFin _).injective
  rw [weightSpace_vermaModule_ne_bot_iff_exists b lam (negativeNilradicalBasis H b)
    (lie_negativeNilradicalBasis_eq_neg_root_smul b) mu]
  exact ⟨fun ⟨n, hn⟩ ↦ ⟨_, (exponentEquivKostantPartition b lam mu ⟨n, hn⟩).2⟩,
    fun ⟨c, hc⟩ ↦ ⟨_, ((exponentEquivKostantPartition b lam mu).symm ⟨c, hc⟩).2⟩⟩

/-- **A Verma module is the sum of its weight spaces.** -/
theorem iSup_weightSpace_vermaModule_eq_top :
    ⨆ mu : Dual K H, weightSpace (VermaModule b lam) (mu : H → K) = ⊤ := by
  let : LinearOrder (posRoots (IsKilling.rootSystem H) b) :=
    LinearOrder.lift' (Finite.equivFin _) (Finite.equivFin _).injective
  rw [← LieSubmodule.toSubmodule_inj, LieSubmodule.iSup_toSubmodule,
    LieSubmodule.top_toSubmodule, eq_top_iff,
    ← (vermaBasis b lam (negativeNilradicalBasis H b)).span_eq, Submodule.span_le]
  rintro _ ⟨n, rfl⟩
  exact Submodule.mem_iSup_of_mem _
    (vermaBasis_mem_weightSpace b lam _ (lie_negativeNilradicalBasis_eq_neg_root_smul b) n)

end Kostant

end TauCeti
