/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.DedekindDomain.AdicValuation.IntegralClosure
public import TauCeti.RingTheory.DiscreteValuationRing.Monogenic
import Mathlib.FieldTheory.Perfect

/-!
# Monogenicity of completed integer rings

Let `L/K` be an extension of fraction fields of Dedekind domains, and let `w` be a height-one
prime of the top ring above a height-one prime `v` of the base. When the residue fields are finite,
the ring of integers `𝒪_w` is generated by one element over `𝒪_v`. If in addition `K` has
characteristic zero, the completed extension `L_w/K_v` is separable.

The generator can simultaneously be viewed as an integral element which generates the local
field extension. This is the form needed to apply formulas for the different which use a
generator of both the integer ring and its fraction field.

## Main results

* `IsDedekindDomain.HeightOneSpectrum.adicCompletion_isSeparable`: the canonical extension of
  completions in characteristic zero is separable.
* `IsDedekindDomain.HeightOneSpectrum.exists_adicCompletionIntegers_generator`: there is one
  element which generates the completed integer ring and the completed field extension, and it
  is integral over the base completed integer ring.

## References

* [J.-P. Serre, *Corps locaux*][serre1968], Chapter III, §6, Proposition 12.
-/

public section
noncomputable section

open IsDedekindDomain
open scoped AdicCompletionExtension

namespace IsDedekindDomain.HeightOneSpectrum

variable {R : Type*} [CommRing R] [IsDedekindDomain R]
  {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]
  {B : Type*} [CommRing B] [IsDedekindDomain B] [Algebra R B]
  {L : Type*} [Field L] [Algebra K L] [Algebra R L] [IsScalarTower R K L]
  [Algebra B L] [IsFractionRing B L] [IsScalarTower R B L]
  (v : HeightOneSpectrum R) (w : HeightOneSpectrum B) [w.asIdeal.LiesOver v.asIdeal]
  [Finite (R ⧸ v.asIdeal)] [Finite (B ⧸ w.asIdeal)]

/-- A canonical extension of adic completions with finite residue fields and a
characteristic-zero base fraction field is separable. -/
theorem adicCompletion_isSeparable [CharZero K] :
    Algebra.IsSeparable (v.adicCompletion K) (w.adicCompletion L) := by
  infer_instance

scoped[AdicCompletionExtension] attribute [instance]
  IsDedekindDomain.HeightOneSpectrum.adicCompletion_isSeparable

/-- When both residue fields are finite, the completed integer ring `𝒪_w` is generated over
`𝒪_v` by an element which is also an integral generator of the field extension. -/
theorem exists_adicCompletionIntegers_generator :
    ∃ x : w.adicCompletionIntegers L,
      Algebra.adjoin (v.adicCompletionIntegers K) {x} = ⊤ ∧
      IsIntegral (v.adicCompletionIntegers K) x ∧
      Algebra.adjoin (v.adicCompletion K) {(x : w.adicCompletion L)} = ⊤ := by
  let _ : IsLocalHom (algebraMap (v.adicCompletionIntegers K)
      (w.adicCompletionIntegers L)) := adicCompletionIntegers_isLocalHom K L v w
  let _ : Finite (IsLocalRing.ResidueField (v.adicCompletionIntegers K)) :=
    Finite.of_equiv _ (v.residueFieldEquivAdicCompletionIntegers (K := K)).toEquiv
  let _ : Algebra.IsSeparable
      (IsLocalRing.ResidueField (v.adicCompletionIntegers K))
      (IsLocalRing.ResidueField (w.adicCompletionIntegers L)) := by
    infer_instance
  obtain ⟨pb, hfield⟩ :=
    TauCeti.IsDiscreteValuationRing.exists_powerBasis_intermediateField_adjoin_eq_top
      (R := v.adicCompletionIntegers K) (S := w.adicCompletionIntegers L)
      (v.adicCompletion K) (w.adicCompletion L)
  refine ⟨pb.gen, pb.adjoin_gen_eq_top, pb.isIntegral_gen, ?_⟩
  rw [← Algebra.algebraMap_ofSubsemiring_apply (w.adicCompletionIntegers L) pb.gen]
  exact Algebra.adjoin_eq_top_of_intermediateField
    (fun x _ ↦ Algebra.IsAlgebraic.isAlgebraic x) hfield

end IsDedekindDomain.HeightOneSpectrum
