/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.Algebra.Polynomial.Roots
import Mathlib.Data.Int.Interval
import Mathlib.Data.Set.Card
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import TauCeti.Algebra.Polynomial.CardRootSetUnion

/-!
# Counting simple intermediate fields generated by roots of bounded integer polynomials

Mathlib's proof of Hermite's finiteness theorem `NumberField.finite_of_discr_bdd` reduces
bounded-discriminant number fields in a fixed ambient extension to fields generated by elements of
a finite root set, via `NumberField.hermiteTheorem.finite_of_finite_generating_set`. The effective
Hermite--Minkowski target needs the corresponding cardinality step: if the admissible generators
lie in a finite set `T`, then the simple intermediate fields `ℚ⟮x⟯` generated by elements of `T`
are finite in number and no more numerous than `T`.

This file specializes that root-to-field image bound to the bounded-polynomial root set: the
bounded root set itself is counted in `TauCeti.Algebra.Polynomial.CardRootSetUnion`, and here we
only pass from roots to the simple intermediate fields they generate.

## Main results

* `TauCeti.IntermediateField.finite_setOf_exists_mem_eq_adjoin_simple_of_finite`:
  if `T` is finite, the simple intermediate fields generated by elements of `T` form a
  finite set.
* `TauCeti.IntermediateField.ncard_setOf_exists_mem_eq_adjoin_simple_le`:
  the number of simple intermediate fields generated by elements of a finite set `T` is
  at most `T.ncard`.
* `TauCeti.IntermediateField.finite_setOf_exists_adjoin_simple_eq_root_natDegree_le_abs_intCoeff`:
  the simple subfields generated by roots of integer polynomials of bounded degree and coefficient
  height form a finite set.
* `TauCeti.IntermediateField.ncard_setOf_exists_adjoin_simple_eq_root_natDegree_le_abs_intCoeff_le`:
  their number is at most `(2 * B + 1) ^ (d + 1) * d`.

No formal code is vendored. The proof reuses Mathlib's `IntermediateField.adjoin` and
`Polynomial.bUnion_roots_finite` APIs and Tau Ceti's explicit bounded-polynomial root count.
-/

open Polynomial
open scoped IntermediateField

namespace TauCeti

namespace IntermediateField

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- The simple intermediate fields generated by elements of a finite set `T` form a finite set.

This is the reusable finite-generator-to-simple-field counting step used before specializing to
bounded root sets. -/
theorem finite_setOf_exists_mem_eq_adjoin_simple_of_finite {T : Set L} (hT : T.Finite) :
    {E : IntermediateField K L | ∃ x ∈ T, E = K⟮x⟯}.Finite :=
  (hT.image (fun x => (K⟮x⟯ : IntermediateField K L))).subset
    (fun E hE => by
      obtain ⟨x, hx, rfl⟩ := hE
      exact ⟨x, hx, rfl⟩)

/-- The simple intermediate fields generated by elements of a finite set `T` are no more numerous
than the elements of `T`. -/
theorem ncard_setOf_exists_mem_eq_adjoin_simple_le {T : Set L} (hT : T.Finite) :
    {E : IntermediateField K L | ∃ x ∈ T, E = K⟮x⟯}.ncard ≤ T.ncard := by
  have hsub :
      {E : IntermediateField K L | ∃ x ∈ T, E = K⟮x⟯} ⊆
        (fun x => (K⟮x⟯ : IntermediateField K L)) '' T := by
    intro E hE
    obtain ⟨x, hx, rfl⟩ := hE
    exact ⟨x, hx, rfl⟩
  exact (Set.ncard_le_ncard hsub (hT.image _)).trans (Set.ncard_image_le hT)

variable (A : Type*) [Field A] [Algebra ℚ A] [DecidableEq A]

omit [Algebra ℚ A] in
/-- The root set in `A` of the integer polynomials of degree at most `d` whose coefficients all have
absolute value at most `B` is finite. -/
private theorem finite_boundedRoots (d B : ℕ) :
    (⋃ (f : ℤ[X]) (_ : f.natDegree ≤ d ∧ ∀ i, |f.coeff i| ≤ (B : ℤ)),
        (((f.map (algebraMap ℤ A)).roots.toFinset : Set A))).Finite := by
  have hpred : ∀ (f : ℤ[X]) (i : ℕ),
      |f.coeff i| ≤ (B : ℤ) ↔ f.coeff i ∈ Set.Icc (-(B : ℤ)) B := fun f i => by
    rw [Set.mem_Icc, abs_le]
  simpa only [hpred] using
    Polynomial.bUnion_roots_finite (algebraMap ℤ A) d
      (U := Set.Icc (-(B : ℤ)) B) (Set.finite_Icc (-(B : ℤ)) B)

/-- The simple subfields of an ambient field `A / ℚ` generated by roots of integer polynomials of
degree at most `d` and coefficient height at most `B` form a finite set.

This is the finiteness half of the root-to-field counting step used by the effective
Hermite--Minkowski target. -/
theorem finite_setOf_exists_adjoin_simple_eq_root_natDegree_le_abs_intCoeff (d B : ℕ) :
    {E : IntermediateField ℚ A |
      ∃ x ∈ (⋃ (f : ℤ[X]) (_ : f.natDegree ≤ d ∧ ∀ i, |f.coeff i| ≤ (B : ℤ)),
        (((f.map (algebraMap ℤ A)).roots.toFinset : Set A))), E = ℚ⟮x⟯}.Finite :=
  finite_setOf_exists_mem_eq_adjoin_simple_of_finite (finite_boundedRoots A d B)

/-- The simple subfields of an ambient field `A / ℚ` generated by roots of integer polynomials of
degree at most `d` and coefficient height at most `B` number at most `(2 * B + 1) ^ (d + 1) * d`.

This is the root-to-field counting step used by the effective Hermite--Minkowski target, after
`TauCeti.Polynomial.ncard_biUnion_roots_natDegree_le_abs_intCoeff_le` has counted the possible
generators. -/
theorem ncard_setOf_exists_adjoin_simple_eq_root_natDegree_le_abs_intCoeff_le (d B : ℕ) :
    {E : IntermediateField ℚ A |
      ∃ x ∈ (⋃ (f : ℤ[X]) (_ : f.natDegree ≤ d ∧ ∀ i, |f.coeff i| ≤ (B : ℤ)),
        (((f.map (algebraMap ℤ A)).roots.toFinset : Set A))), E = ℚ⟮x⟯}.ncard ≤
      (2 * B + 1) ^ (d + 1) * d := by
  let T : Set A := ⋃ (f : ℤ[X]) (_ : f.natDegree ≤ d ∧ ∀ i, |f.coeff i| ≤ (B : ℤ)),
    (((f.map (algebraMap ℤ A)).roots.toFinset : Set A))
  let S : Set (IntermediateField ℚ A) := {E | ∃ x ∈ T, E = ℚ⟮x⟯}
  have hS_le_T : S.ncard ≤ T.ncard :=
    ncard_setOf_exists_mem_eq_adjoin_simple_le (finite_boundedRoots A d B)
  exact hS_le_T.trans
    (TauCeti.Polynomial.ncard_biUnion_roots_natDegree_le_abs_intCoeff_le (algebraMap ℤ A) d B)

end IntermediateField

end TauCeti
