module

public import TauCeti.Probability.Process.Tail
public import TauCeti.Probability.Martingale.Reverse

/-!
# Reverse filtrations from process tails

This file packages the decreasing tail σ-algebras of a process as the finite-horizon
reverse filtrations used by the reverse-martingale infrastructure.  The main result is the
Exchangeability roadmap Layer 2 adapter
`tailProcess_eq_iInf_tailReverseFiltration_zero`: the process tail σ-algebra is the
infimum of the time-zero levels of these finite-horizon reverse filtrations.

The construction is a thin wrapper around `MeasureTheory.revFiltration` applied to
`tailFamily X`.  It is deliberately process-specific so later de Finetti martingale files
can invoke the generic reverse-martingale API without reassembling the `tailFamily`
antitonicity and ambient-sub-σ-algebra hypotheses each time.
-/

public section

noncomputable section

open MeasureTheory

namespace TauCeti

namespace Probability

variable {Ω : Type*} {β : ℕ → Type*} [MeasurableSpace Ω] [∀ k, MeasurableSpace (β k)]

/-- The finite-horizon reverse filtration attached to the tail σ-algebras of a measurable
process.  At horizon `N` and reverse time `n`, its level is `tailFamily X (N - n)`. -/
def tailReverseFiltration (X : (k : ℕ) → Ω → β k)
    (hX : ∀ k, Measurable (X k)) (N : ℕ) :
    Filtration ℕ (inferInstance : MeasurableSpace Ω) :=
  MeasureTheory.revFiltration (tailFamily X) (tailFamily_antitone X)
    (fun n => tailFamily_le_ambient n fun k _ => hX k) N

/-- Levels of the process-tail reverse filtration. -/
@[simp]
theorem tailReverseFiltration_apply (X : (k : ℕ) → Ω → β k)
    (hX : ∀ k, Measurable (X k)) (N n : ℕ) :
    tailReverseFiltration X hX N n = tailFamily X (N - n) := by
  simp only [tailReverseFiltration, MeasureTheory.revFiltration_apply]

/-- The initial level of the horizon-`N` reverse filtration is the future σ-algebra
`tailFamily X N`. -/
theorem tailReverseFiltration_zero (X : (k : ℕ) → Ω → β k)
    (hX : ∀ k, Measurable (X k)) (N : ℕ) :
    tailReverseFiltration X hX N 0 = tailFamily X N := by
  simp

/-- The horizon level of the horizon-`N` reverse filtration is the σ-algebra generated by all
coordinates of the process. -/
theorem tailReverseFiltration_self (X : (k : ℕ) → Ω → β k)
    (hX : ∀ k, Measurable (X k)) (N : ℕ) :
    tailReverseFiltration X hX N N = tailFamily X 0 := by
  simp

/-- Normal form for the process tail as the infimum of the time-zero levels of the
finite-horizon reverse filtrations attached to `tailFamily X`.  This is the process-tail
adapter requested by the Exchangeability roadmap under
`tailProcess_eq_iInf_revFiltration`. -/
theorem tailProcess_eq_iInf_tailReverseFiltration_zero (X : (k : ℕ) → Ω → β k)
    (hX : ∀ k, Measurable (X k)) :
    tailProcess X = ⨅ N : ℕ, tailReverseFiltration X hX N 0 := by
  simp [tailProcess_eq_iInf_tailFamily]

/-- Roadmap-named form of `tailProcess_eq_iInf_tailReverseFiltration_zero`, spelling out the
underlying generic `MeasureTheory.revFiltration`. -/
theorem tailProcess_eq_iInf_revFiltration (X : (k : ℕ) → Ω → β k)
    (hX : ∀ k, Measurable (X k)) :
    tailProcess X =
      ⨅ N : ℕ,
        (MeasureTheory.revFiltration (tailFamily X) (tailFamily_antitone X)
          (fun n => tailFamily_le_ambient n fun k _ => hX k) N :
          Filtration ℕ (inferInstance : MeasurableSpace Ω)) 0 := by
  exact tailProcess_eq_iInf_tailReverseFiltration_zero X hX

/-- The same tail identification phrased as a sub-σ-algebra bound into every finite-horizon
reverse filtration at time zero. -/
theorem tailProcess_le_tailReverseFiltration_zero (X : (k : ℕ) → Ω → β k)
    (hX : ∀ k, Measurable (X k)) (N : ℕ) :
    tailProcess X ≤ tailReverseFiltration X hX N 0 := by
  rw [tailProcess_eq_iInf_tailReverseFiltration_zero X hX]
  exact iInf_le _ N

/-- Any function measurable with respect to the process tail is measurable at the initial
level of every finite-horizon tail reverse filtration. -/
theorem Measurable.tailReverseFiltration_zero {X : (k : ℕ) → Ω → β k}
    {γ : Type*} [MeasurableSpace γ] {f : Ω → γ}
    (hf : Measurable[tailProcess X] f) (hX : ∀ k, Measurable (X k)) (N : ℕ) :
    Measurable[tailReverseFiltration X hX N 0] f :=
  hf.mono (tailProcess_le_tailReverseFiltration_zero X hX N) le_rfl

end Probability

end TauCeti
