module

public import Mathlib.Probability.Process.Filtration

/-!
# Tail σ-algebras of a process

This file provides the process-relative tail σ-algebra API requested in the Exchangeability
roadmap, Layer 2.  For a process `X : ℕ → Ω → α`, `tailFamily X n` is the σ-algebra generated
by the coordinates `X k` with `n ≤ k`, and `tailProcess X` is their intersection over all
cutoffs.  The same future σ-algebras are also bundled as a filtration indexed by `ℕᵒᵈ`, so later
reverse-martingale statements can consume Mathlib's `Filtration` interface.
-/

public section

noncomputable section

open MeasureTheory

namespace TauCeti

namespace Probability

variable {Ω α : Type*} [MeasurableSpace α]

/-- The σ-algebra generated by the future coordinates `X k` with `n ≤ k`. -/
@[reducible, expose]
def tailFamily (X : ℕ → Ω → α) (n : ℕ) : MeasurableSpace Ω :=
  ⨆ k : {k : ℕ // n ≤ k}, MeasurableSpace.comap (X k.1) inferInstance

/-- The tail σ-algebra of a process: the intersection of the future σ-algebras. -/
@[reducible, expose]
def tailProcess (X : ℕ → Ω → α) : MeasurableSpace Ω :=
  ⨅ n : ℕ, tailFamily X n

/-- Normal form for the future σ-algebra generated by coordinates from `n` onward. -/
theorem tailFamily_eq_iSup_comap (X : ℕ → Ω → α) (n : ℕ) :
    tailFamily X n =
      ⨆ k : {k : ℕ // n ≤ k}, MeasurableSpace.comap (X k.1) inferInstance :=
  rfl

/-- Normal form for the process-relative tail σ-algebra. -/
theorem tailProcess_eq_iInf_tailFamily (X : ℕ → Ω → α) :
    tailProcess X = ⨅ n : ℕ, tailFamily X n :=
  rfl

/-- A future coordinate is measurable with respect to the corresponding future σ-algebra. -/
theorem measurable_tailFamily_of_le {X : ℕ → Ω → α} {n k : ℕ}
    (hnk : n ≤ k) :
    Measurable[tailFamily X n] (X k) := by
  rw [measurable_iff_comap_le]
  exact le_iSup (fun k : {k : ℕ // n ≤ k} =>
    MeasurableSpace.comap (X k.1) inferInstance) ⟨k, hnk⟩

/-- The future σ-algebras of a process form a decreasing family. -/
theorem tailFamily_antitone (X : ℕ → Ω → α) :
    Antitone (tailFamily X) := by
  intro n m hnm
  rw [tailFamily_eq_iSup_comap, tailFamily_eq_iSup_comap]
  refine iSup_le ?_
  intro k
  exact le_iSup (fun k : {k : ℕ // n ≤ k} =>
    MeasurableSpace.comap (X k.1) inferInstance) ⟨k.1, hnm.trans k.2⟩

/-- The tail σ-algebra is contained in every future σ-algebra. -/
theorem tailProcess_le_tailFamily (X : ℕ → Ω → α) (n : ℕ) :
    tailProcess X ≤ tailFamily X n := by
  rw [tailProcess_eq_iInf_tailFamily]
  exact iInf_le _ n

variable [MeasurableSpace Ω]

/-- If all coordinates are ambient-measurable, then each future σ-algebra is a sub-σ-algebra of
the ambient one. -/
theorem tailFamily_le_ambient {X : ℕ → Ω → α} (hX : ∀ k, Measurable (X k)) (n : ℕ) :
    tailFamily X n ≤ (inferInstance : MeasurableSpace Ω) := by
  rw [tailFamily_eq_iSup_comap]
  exact iSup_le fun k => (hX k.1).comap_le

/-- If all coordinates are ambient-measurable, then the tail σ-algebra is a sub-σ-algebra of the
ambient one. -/
theorem tailProcess_le_ambient {X : ℕ → Ω → α} (hX : ∀ k, Measurable (X k)) :
    tailProcess X ≤ (inferInstance : MeasurableSpace Ω) :=
  (tailProcess_le_tailFamily X 0).trans (tailFamily_le_ambient hX 0)

/-- The future σ-algebras bundled as an increasing filtration over the reversed order `ℕᵒᵈ`.
This is the filtration consumed by reverse-martingale arguments. -/
@[expose]
def futureFiltration (X : ℕ → Ω → α) (hX : ∀ k, Measurable (X k)) :
    Filtration ℕᵒᵈ (inferInstance : MeasurableSpace Ω) where
  seq n := tailFamily X (OrderDual.ofDual n)
  mono' := by
    intro n m hnm
    exact tailFamily_antitone X hnm
  le' n := tailFamily_le_ambient hX (OrderDual.ofDual n)

@[simp]
theorem futureFiltration_apply (X : ℕ → Ω → α) (hX : ∀ k, Measurable (X k)) (n : ℕᵒᵈ) :
    futureFiltration X hX n = tailFamily X (OrderDual.ofDual n) :=
  rfl

/-- The process tail is the infimum of the reversed future filtration. -/
theorem tailProcess_eq_iInf_futureFiltration (X : ℕ → Ω → α) (hX : ∀ k, Measurable (X k)) :
    tailProcess X = ⨅ n : ℕᵒᵈ, futureFiltration X hX n := by
  rw [tailProcess_eq_iInf_tailFamily]
  simpa using (OrderDual.toDual.surjective.iInf_comp
    (fun n : ℕᵒᵈ => futureFiltration X hX n))

/-- Every coordinate from the future is measurable with respect to the reversed future
filtration at that cutoff. -/
theorem measurable_futureFiltration_of_le {X : ℕ → Ω → α} (hX : ∀ k, Measurable (X k))
    {n k : ℕ} (hnk : n ≤ k) :
    Measurable[futureFiltration X hX (OrderDual.toDual n)] (X k) :=
  measurable_tailFamily_of_le hnk

end Probability

end TauCeti
