/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.BaseChange
public import TauCeti.Algebra.Lie.F4.ChevalleyAction
public import TauCeti.Algebra.Lie.Weights.Root.IntegralBasis

/-!
# The integral and modular Chevalley lattice in type F₄

The full integral Chevalley lattice of the chosen rational F₄ Chevalley system is reduced
modulo two. Its root--simple-coroot basis retains the pinned root labels. This file supplies
root and coroot vectors and their bracket formulas before selecting the short-root ideal.

This full integral reduction need not equal the Lie algebra generated by the reduced simple
matrices in bad characteristic.

## References

* R. Steinberg, *Endomorphisms of linear algebraic groups*, Memoirs AMS 80 (1968), §11.
* R. W. Carter, *Simple Groups of Lie Type*, §12.3.
-/

public section

namespace TauCeti.DynkinType

open _root_.LieAlgebra _root_.LieAlgebra.IsKilling LieModule Module Set
open scoped TensorProduct

noncomputable section

/-- The base of the Killing root system selected by the distinguished F₄ Lie-algebra basis. -/
abbrev f4KillingBase := (F4.lieBasis valid_F4).base

/-- The integral Chevalley Lie lattice for the chosen F₄ root-vector system. -/
abbrev f4ChevalleyLieLattice : LieSubalgebra ℤ (F4.lieAlgebra valid_F4) :=
  f4ChevalleyRootVector_isChevalleySystem.chevalleyLieLattice

/-- Integral Chevalley coordinates: one coordinate for every root and one for every simple
coroot. -/
abbrev f4ChevalleyIndex :=
  (F4.cartanSubalgebra valid_F4).root ⊕ f4KillingBase.support

/-- The root-vector--simple-coroot basis of the integral F₄ Chevalley lattice. -/
noncomputable def f4ChevalleyBasis :
    Basis f4ChevalleyIndex ℤ f4ChevalleyLieLattice :=
  f4ChevalleyRootVector_isChevalleySystem.rootSimpleCorootBasis f4KillingBase

/-- The Chevalley lattice reduced modulo two. -/
abbrev f4ModularChevalleyLieAlgebra :=
  ZMod 2 ⊗[ℤ] f4ChevalleyLieLattice

/-- The integral root--simple-coroot coordinates, retained after reduction modulo two. -/
noncomputable def f4ModularChevalleyBasis :
    Basis f4ChevalleyIndex (ZMod 2) f4ModularChevalleyLieAlgebra :=
  f4ChevalleyBasis.baseChange (ZMod 2)

/-- A root vector as an element of the integral Chevalley lattice. -/
noncomputable def f4IntegralRootVector (i : Fin 48) : f4ChevalleyLieLattice :=
  f4ChevalleyBasis (Sum.inl (f4KillingRootLabel i))

/-- A root vector in the Chevalley lattice reduced modulo two. -/
noncomputable def f4ModularRootVector (i : Fin 48) :
    f4ModularChevalleyLieAlgebra :=
  f4ModularChevalleyBasis (Sum.inl (f4KillingRootLabel i))

/-- The coroot of a pinned root as an element of the integral Chevalley lattice. -/
noncomputable def f4IntegralCoroot (i : Fin 48) : f4ChevalleyLieLattice :=
  ⟨((coroot (f4KillingRoot i) : F4.cartanSubalgebra valid_F4) :
      F4.lieAlgebra valid_F4),
    f4ChevalleyRootVector_isChevalleySystem.coroot_mem_chevalleyLieLattice _⟩

/-- A simple coroot as a named integral Chevalley basis vector. -/
noncomputable def f4IntegralSimpleCoroot (i : Fin F4.rank) : f4ChevalleyLieLattice :=
  f4ChevalleyBasis (Sum.inr ((F4.lieBasis valid_F4).baseSupportEquiv i))

/-- A simple coroot basis vector after reduction modulo two. -/
noncomputable def f4ModularSimpleCoroot (i : Fin F4.rank) :
    f4ModularChevalleyLieAlgebra :=
  f4ModularChevalleyBasis (Sum.inr ((F4.lieBasis valid_F4).baseSupportEquiv i))

/-- An arbitrary coroot after reduction modulo two. -/
noncomputable def f4ModularCoroot (i : Fin 48) : f4ModularChevalleyLieAlgebra :=
  1 ⊗ₜ[ℤ] f4IntegralCoroot i

/-- A modular root vector is the Chevalley basis vector with its Killing-root label. -/
theorem f4ModularRootVector_eq_basis (i : Fin 48) :
    f4ModularRootVector i =
      f4ModularChevalleyBasis (Sum.inl (f4KillingRootLabel i)) := by rfl

/-- A modular simple coroot is the Chevalley basis vector with its simple-root support label. -/
theorem f4ModularSimpleCoroot_eq_basis (i : Fin F4.rank) :
    f4ModularSimpleCoroot i =
      f4ModularChevalleyBasis
        (Sum.inr ((F4.lieBasis valid_F4).baseSupportEquiv i)) := by rfl

/-- A simple-coroot basis label reduces to its named modular coroot. -/
@[simp] theorem f4ModularChevalleyBasis_inr_eq_simpleCoroot (j : f4KillingBase.support) :
    f4ModularChevalleyBasis (Sum.inr j) =
      f4ModularSimpleCoroot ((F4.lieBasis valid_F4).baseSupportEquiv.symm j) := by
  rw [f4ModularSimpleCoroot_eq_basis, Equiv.apply_symm_apply]

@[simp] theorem coe_f4IntegralRootVector (i : Fin 48) :
    (f4IntegralRootVector i : F4.lieAlgebra valid_F4) =
      f4ChevalleyRootVector (f4KillingRoot i) := by
  rw [f4IntegralRootVector, f4ChevalleyBasis,
    IsChevalleySystem.coe_rootSimpleCorootBasis_inl]

@[simp] theorem coe_f4IntegralCoroot (i : Fin 48) :
    (f4IntegralCoroot i : F4.lieAlgebra valid_F4) =
      ((coroot (f4KillingRoot i) : F4.cartanSubalgebra valid_F4) :
        F4.lieAlgebra valid_F4) := by rfl

@[simp] theorem coe_f4IntegralSimpleCoroot (i : Fin F4.rank) :
    (f4IntegralSimpleCoroot i : F4.lieAlgebra valid_F4) =
      ((coroot ((((F4.lieBasis valid_F4).baseSupportEquiv i :
        (F4.cartanSubalgebra valid_F4).root) :
          Weight ℚ (F4.cartanSubalgebra valid_F4) (F4.lieAlgebra valid_F4))) :
        F4.cartanSubalgebra valid_F4) : F4.lieAlgebra valid_F4) := by
  simp only [f4IntegralSimpleCoroot, f4ChevalleyBasis,
    IsChevalleySystem.coe_rootSimpleCorootBasis_inr]

theorem f4ModularRootVector_eq (i : Fin 48) :
    f4ModularRootVector i = 1 ⊗ₜ[ℤ] f4IntegralRootVector i := by
  rw [f4ModularRootVector, f4ModularChevalleyBasis, Basis.baseChange_apply]
  rfl

theorem f4ModularSimpleCoroot_eq (i : Fin F4.rank) :
    f4ModularSimpleCoroot i = 1 ⊗ₜ[ℤ] f4IntegralSimpleCoroot i := by
  simpa only [f4ModularSimpleCoroot, f4ModularChevalleyBasis,
    f4IntegralSimpleCoroot] using
      Module.Basis.baseChange_apply (ZMod 2) f4ChevalleyBasis
        (Sum.inr ((F4.lieBasis valid_F4).baseSupportEquiv i))

private theorem f4Integral_lie_eq_iff (x y z : f4ChevalleyLieLattice) :
    ⁅x, y⁆ = z ↔ ⁅(x : F4.lieAlgebra valid_F4), (y : F4.lieAlgebra valid_F4)⁆ =
      (z : F4.lieAlgebra valid_F4) := Subtype.ext_iff

private theorem f4Modular_lie_tmul (x y : f4ChevalleyLieLattice) :
    ⁅(1 : ZMod 2) ⊗ₜ[ℤ] x, (1 : ZMod 2) ⊗ₜ[ℤ] y⁆ = 1 ⊗ₜ[ℤ] ⁅x, y⁆ := by
  rw [LieAlgebra.ExtendScalars.bracket_tmul, one_mul]

private theorem one_tmul_zsmul (z : ℤ) (v : f4ChevalleyLieLattice) :
    (1 : ZMod 2) ⊗ₜ[ℤ] (z • v) = (z : ZMod 2) • ((1 : ZMod 2) ⊗ₜ[ℤ] v) := by
  rw [TensorProduct.tmul_smul, TensorProduct.smul_tmul']
  exact congrArg (· ⊗ₜ[ℤ] v) (Int.cast_smul_eq_zsmul (ZMod 2) z 1).symm

/-- A simple integral coroot acts on an integral root vector by the pinned Cartan integer. -/
theorem f4Integral_lie_simpleCoroot_rootVector (i : Fin F4.rank) (α : Fin 48) :
    ⁅f4IntegralSimpleCoroot i, f4IntegralRootVector α⁆ =
      f4SimplyConnectedRootDatum.pairing α (Fin.castAdd 44 (Fin.cast rank_F4 i)) •
        f4IntegralRootVector α := by
  simp only [f4Integral_lie_eq_iff, SetLike.val_smul, coe_f4IntegralSimpleCoroot,
    coe_f4IntegralRootVector]
  simpa only [f4RootCartanWeight_simple, Int.cast_smul_eq_zsmul] using
    f4ChevalleyRootVector_isChevalleySystem.toIsSl2System.lie_coroot_rootVector
      (((F4.lieBasis valid_F4).baseSupportEquiv i :
        (F4.cartanSubalgebra valid_F4).root) :
          Weight ℚ (F4.cartanSubalgebra valid_F4) (F4.lieAlgebra valid_F4))
      (f4KillingRoot α)

/-- A modular simple coroot acts on a modular root vector by the reduced pinned Cartan integer. -/
theorem f4Modular_lie_simpleCoroot_rootVector (i : Fin F4.rank) (α : Fin 48) :
    ⁅f4ModularSimpleCoroot i, f4ModularRootVector α⁆ =
      (f4SimplyConnectedRootDatum.pairing α
        (Fin.castAdd 44 (Fin.cast rank_F4 i)) : ZMod 2) • f4ModularRootVector α := by
  rw [f4ModularSimpleCoroot_eq, f4ModularRootVector_eq,
    f4Modular_lie_tmul, f4Integral_lie_simpleCoroot_rootVector, one_tmul_zsmul]

/-- Integral coroot coordinates in the Chevalley basis are the pinned coroot coordinates. -/
theorem f4IntegralCoroot_eq_sum_simple (β : Fin 48) :
    f4IntegralCoroot β = ∑ i : Fin F4.rank,
      f4Coroot β (Fin.cast rank_F4 i) • f4IntegralSimpleCoroot i := by
  -- Compare in the rational Lie algebra: include the integral lattice and Cartan subalgebra,
  -- then identify integral scalar multiplication with its rational scalar extension.
  apply Subtype.ext
  have h := congrArg
    (fun y : F4.cartanSubalgebra valid_F4 => (y : F4.lieAlgebra valid_F4))
    (f4KillingCoroot_eq_sum_simple β)
  convert h using 1
  · simp only [coe_f4IntegralCoroot, rootSystem_coroot_apply]
  · let u : Fin F4.rank → F4.lieAlgebra valid_F4 := fun i =>
      f4ChevalleyLieLattice.toSubmodule.subtype
        (f4Coroot β (Fin.cast rank_F4 i) • f4IntegralSimpleCoroot i)
    let v : Fin F4.rank → F4.lieAlgebra valid_F4 := fun i =>
      (F4.cartanSubalgebra valid_F4).incl
        ((F4.rationalRootSystem valid_F4).coroot (f4RootIndex β) i •
          (rootSystem (F4.cartanSubalgebra valid_F4)).coroot
            ((F4.lieBasis valid_F4).baseSupportEquiv i))
    have huv (i : Fin F4.rank) : u i = v i := by
      have hcoeff :
          (f4Coroot β (Fin.cast rank_F4 i) : ℚ) =
            (F4.rationalRootSystem valid_F4).coroot (f4RootIndex β) i := by
        rw [coroot_rationalRootSystem, simplyConnectedRootDatum_F4,
          f4SimplyConnectedRootDatum_coroot]
        congr 1
      dsimp only [u, v]
      -- Both subtype inclusions preserve scalar multiplication by definition.
      change f4Coroot β (Fin.cast rank_F4 i) •
          (f4IntegralSimpleCoroot i : F4.lieAlgebra valid_F4) =
        (F4.rationalRootSystem valid_F4).coroot (f4RootIndex β) i •
          (((rootSystem (F4.cartanSubalgebra valid_F4)).coroot
            ((F4.lieBasis valid_F4).baseSupportEquiv i) :
              F4.cartanSubalgebra valid_F4) : F4.lieAlgebra valid_F4)
      simp only [coe_f4IntegralSimpleCoroot, rootSystem_coroot_apply]
      let w : F4.lieAlgebra valid_F4 :=
        ((coroot (((F4.lieBasis valid_F4).baseSupportEquiv i :
          (F4.cartanSubalgebra valid_F4).root) :
            Weight ℚ (F4.cartanSubalgebra valid_F4) (F4.lieAlgebra valid_F4)) :
              F4.cartanSubalgebra valid_F4) : F4.lieAlgebra valid_F4)
      -- The local name w abbreviates the same coroot included in the rational Lie algebra.
      change f4Coroot β (Fin.cast rank_F4 i) • w =
        (F4.rationalRootSystem valid_F4).coroot (f4RootIndex β) i • w
      calc
        _ = (f4Coroot β (Fin.cast rank_F4 i) : ℚ) • w :=
          (Int.cast_smul_eq_zsmul ℚ _ _).symm
        _ = _ := congrArg (· • w) hcoeff
    -- Write the two subtype inclusions as linear maps so map_sum applies to each side.
    change f4ChevalleyLieLattice.toSubmodule.subtype
        (∑ i : Fin F4.rank,
          f4Coroot β (Fin.cast rank_F4 i) • f4IntegralSimpleCoroot i) =
      (F4.cartanSubalgebra valid_F4).incl
        (∑ i : Fin F4.rank,
          (F4.rationalRootSystem valid_F4).coroot (f4RootIndex β) i •
            (rootSystem (F4.cartanSubalgebra valid_F4)).coroot
              ((F4.lieBasis valid_F4).baseSupportEquiv i))
    calc
      _ = ∑ i : Fin F4.rank, u i :=
        map_sum f4ChevalleyLieLattice.toSubmodule.subtype _ Finset.univ
      _ = ∑ i : Fin F4.rank, v i := by
        apply Finset.sum_congr rfl
        intro i _
        exact huv i
      _ = _ := (map_sum (F4.cartanSubalgebra valid_F4).incl _ Finset.univ).symm

/-- Reduction modulo two preserves the pinned simple-coroot coordinate expansion. -/
theorem f4ModularCoroot_eq_sum_simple (β : Fin 48) :
    f4ModularCoroot β = ∑ i : Fin F4.rank,
      (f4Coroot β (Fin.cast rank_F4 i) : ZMod 2) • f4ModularSimpleCoroot i := by
  rw [f4ModularCoroot, f4IntegralCoroot_eq_sum_simple, TensorProduct.tmul_sum]
  apply Finset.sum_congr rfl
  intro i _
  rw [f4ModularSimpleCoroot_eq, one_tmul_zsmul]

/-- The modular coroot at a pinned simple-root index is the corresponding simple-coroot basis
vector. -/
@[simp] theorem f4ModularCoroot_castAdd (i : Fin 4) :
    f4ModularCoroot (Fin.castAdd 44 i) =
      f4ModularSimpleCoroot (Fin.cast rank_F4.symm i) := by
  rw [f4ModularCoroot_eq_sum_simple, f4Coroot_castAdd]
  simp only [Pi.single_apply]
  rw [Finset.sum_eq_single (Fin.cast rank_F4.symm i)]
  · simp
  · intro j _ hj
    have hcast : Fin.cast rank_F4 j ≠ i := by
      intro hij
      apply hj
      apply Fin.cast_injective rank_F4
      simpa using hij
    split_ifs with hji
    · exact (hcast hji).elim
    · rw [Int.cast_zero, zero_smul]
  · intro h
    have hm : Fin.cast rank_F4.symm i ∈ Finset.univ := Finset.mem_univ _
    exact (h hm).elim

/-- The exact integral root-edge bracket inherited by the Chevalley lattice. -/
theorem exists_f4Integral_lie_rootVector_eq_zsmul_of_add (α β γ : Fin 48)
    (h : f4SimplyConnectedRootDatum.root γ =
      f4SimplyConnectedRootDatum.root β + f4SimplyConnectedRootDatum.root α) :
    ∃ z : ℤ,
      z.natAbs = f4SimplyConnectedRootDatum.chainBotCoeff α β + 1 ∧
      ⁅f4IntegralRootVector α, f4IntegralRootVector β⁆ = z • f4IntegralRootVector γ := by
  obtain ⟨z, hz, hlie⟩ := exists_f4_lie_rootVector_eq_smul_of_add α β γ h
  refine ⟨z, hz, ?_⟩
  rw [f4Integral_lie_eq_iff, SetLike.val_smul,
    coe_f4IntegralRootVector, coe_f4IntegralRootVector, coe_f4IntegralRootVector]
  simpa only [Int.cast_smul_eq_zsmul] using hlie

/-- Every modular root-edge bracket is the reduction of its exact integral Chevalley
coefficient. -/
theorem exists_f4Modular_lie_rootVector_eq_smul_of_add (α β γ : Fin 48)
    (h : f4SimplyConnectedRootDatum.root γ =
      f4SimplyConnectedRootDatum.root β + f4SimplyConnectedRootDatum.root α) :
    ∃ z : ℤ,
      z.natAbs = f4SimplyConnectedRootDatum.chainBotCoeff α β + 1 ∧
      ⁅f4ModularRootVector α, f4ModularRootVector β⁆ =
        (z : ZMod 2) • f4ModularRootVector γ := by
  obtain ⟨z, hz, hlie⟩ := exists_f4Integral_lie_rootVector_eq_zsmul_of_add α β γ h
  refine ⟨z, hz, ?_⟩
  rw [f4ModularRootVector_eq, f4ModularRootVector_eq, f4ModularRootVector_eq,
    f4Modular_lie_tmul, hlie, one_tmul_zsmul]

/-- A root edge with zero descending coefficient has unit modular bracket coefficient; its
integral sign disappears modulo two. -/
theorem f4Modular_lie_rootVector_of_add_of_chainBotCoeff_eq_zero (α β γ : Fin 48)
    (h : f4SimplyConnectedRootDatum.root γ =
      f4SimplyConnectedRootDatum.root β + f4SimplyConnectedRootDatum.root α)
    (hbot : f4SimplyConnectedRootDatum.chainBotCoeff α β = 0) :
    ⁅f4ModularRootVector α, f4ModularRootVector β⁆ = f4ModularRootVector γ := by
  obtain ⟨z, hz, hlie⟩ := exists_f4Modular_lie_rootVector_eq_smul_of_add α β γ h
  rw [hbot] at hz
  have hzmod : (z : ZMod 2) = 1 := by
    rw [← ZMod.natAbs_mod_two, hz]
    norm_num
  rw [hlie, hzmod, one_smul]

/-- A root edge between two roots of equal length has unit modular bracket coefficient. -/
theorem f4Modular_lie_rootVector_of_add_of_length_eq (α β γ : Fin 48)
    (hβγ : f4Length β = f4Length γ)
    (h : f4SimplyConnectedRootDatum.root γ =
      f4SimplyConnectedRootDatum.root β + f4SimplyConnectedRootDatum.root α) :
    ⁅f4ModularRootVector α, f4ModularRootVector β⁆ = f4ModularRootVector γ := by
  exact f4Modular_lie_rootVector_of_add_of_chainBotCoeff_eq_zero α β γ h
    (f4_chainBotCoeff_eq_zero_of_add_of_length_eq α β γ hβγ h)

/-- Modular root vectors bracket to zero when their rational root-space sum is absent. -/
theorem f4Modular_lie_rootVector_eq_zero_of_rootSpace_add_eq_bot (α β : Fin 48)
    (hbot : rootSpace (F4.cartanSubalgebra valid_F4)
      ((f4KillingRoot α : (F4.cartanSubalgebra valid_F4) → ℚ) + f4KillingRoot β) = ⊥) :
    ⁅f4ModularRootVector α, f4ModularRootVector β⁆ = 0 := by
  have hlie : ⁅f4ChevalleyRootVector (f4KillingRoot α),
      f4ChevalleyRootVector (f4KillingRoot β)⁆ = 0 :=
    f4ChevalleyRootVector_isChevalleySystem.toIsSl2System
      |>.lie_eq_zero_of_rootSpace_add_eq_bot (f4KillingRoot α) (f4KillingRoot β) hbot
  have hlieIntegral :
      ⁅f4IntegralRootVector α, f4IntegralRootVector β⁆ = 0 := by
    simpa only [f4Integral_lie_eq_iff, coe_f4IntegralRootVector,
      ZeroMemClass.coe_zero] using hlie
  rw [f4ModularRootVector_eq, f4ModularRootVector_eq,
    f4Modular_lie_tmul, hlieIntegral,
    TensorProduct.tmul_zero]

/-- Recover the pinned integral root label of a Killing root. -/
abbrev f4PinnedRootIndex (α : (F4.cartanSubalgebra valid_F4).root) : Fin 48 :=
  Fin.cast numRoots_F4
    ((F4.rationalRootSystemEquiv valid_F4).indexEquiv.symm α)

@[simp] theorem f4KillingRootLabel_f4PinnedRootIndex
    (α : (F4.cartanSubalgebra valid_F4).root) :
    f4KillingRootLabel (f4PinnedRootIndex α) = α := by
  simp only [f4KillingRootLabel, f4PinnedRootIndex, f4RootIndex, Fin.cast_cast,
    Fin.cast_eq_self]
  exact Equiv.apply_symm_apply (F4.rationalRootSystemEquiv valid_F4).indexEquiv α

@[simp] theorem f4PinnedRootIndex_f4KillingRootLabel (i : Fin 48) :
    f4PinnedRootIndex (f4KillingRootLabel i) = i := by
  apply Fin.ext
  simp only [f4PinnedRootIndex, f4KillingRootLabel, f4RootIndex, Equiv.symm_apply_apply]
  rfl

@[simp] theorem f4ModularChevalleyBasis_inl_eq_rootVector
    (α : (F4.cartanSubalgebra valid_F4).root) :
    f4ModularChevalleyBasis (Sum.inl α) =
      f4ModularRootVector (f4PinnedRootIndex α) := by
  rw [f4ModularRootVector_eq_basis, f4KillingRootLabel_f4PinnedRootIndex]

/-- In the pinned F₄ table the root opposite to a simple root is the corresponding entry in the
second half of the table. -/
@[simp] theorem f4OppositeRootIndex_castAdd (i : Fin 4) :
    f4OppositeRootIndex (Fin.castAdd 44 i) =
      Fin.addNat (Fin.castAdd 20 i) 24 := by
  rw [f4OppositeRootIndex_eq_reflectionPerm, f4SimplyConnectedRootDatum_reflectionPerm]
  revert i
  decide

/-- The pinned root index of a positive or negative simple root. -/
def f4SignedSimpleRootIndex : Fin 4 ⊕ Fin 4 → Fin 48
  | .inl i => Fin.castAdd 44 i
  | .inr i => f4OppositeRootIndex (Fin.castAdd 44 i)

/-- A positive simple-root label is its pinned root index. -/
@[simp] theorem f4SignedSimpleRootIndex_inl (i : Fin 4) :
    f4SignedSimpleRootIndex (.inl i) = Fin.castAdd 44 i := (rfl)

/-- A negative simple-root label is the index opposite to the corresponding positive root. -/
@[simp] theorem f4SignedSimpleRootIndex_inr (i : Fin 4) :
    f4SignedSimpleRootIndex (.inr i) = f4OppositeRootIndex (Fin.castAdd 44 i) := (rfl)

/-- A pinned positive or negative simple root vector in the reduced Chevalley lattice. -/
noncomputable def f4ModularSignedSimpleRootVector (k : Fin 4 ⊕ Fin 4) :
    f4ModularChevalleyLieAlgebra :=
  f4ModularRootVector (f4SignedSimpleRootIndex k)

/-- A signed simple root vector is the modular root vector at its pinned root index. -/
@[simp] theorem f4ModularSignedSimpleRootVector_eq (k : Fin 4 ⊕ Fin 4) :
    f4ModularSignedSimpleRootVector k = f4ModularRootVector (f4SignedSimpleRootIndex k) := by
  rw [f4ModularSignedSimpleRootVector]

/-- Opposite roots have the same coroot after reduction modulo two. -/
@[simp] theorem f4ModularCoroot_f4OppositeRootIndex (α : Fin 48) :
    f4ModularCoroot (f4OppositeRootIndex α) = f4ModularCoroot α := by
  have hneg : f4IntegralCoroot (f4OppositeRootIndex α) = -f4IntegralCoroot α := by
    apply Subtype.ext
    simp only [f4IntegralCoroot, f4KillingRoot_f4OppositeRootIndex,
      coroot_neg]
    rfl
  rw [f4ModularCoroot, hneg, TensorProduct.tmul_neg, ← neg_one_smul (ZMod 2),
    CharTwo.neg_eq, one_smul]
  rfl

/-- Positive and negative simple-root labels have the same modular coroot. -/
theorem f4ModularCoroot_signedSimpleRootIndex_inr_eq_inl (i : Fin 4) :
    f4ModularCoroot (f4SignedSimpleRootIndex (.inr i)) =
      f4ModularCoroot (f4SignedSimpleRootIndex (.inl i)) := by
  rw [f4SignedSimpleRootIndex_inr, f4SignedSimpleRootIndex_inl,
    f4ModularCoroot_f4OppositeRootIndex]

/-- In characteristic two the negative of a pinned simple root has the same modular coroot. -/
@[simp] theorem f4ModularCoroot_addNat_castAdd (i : Fin 4) :
    f4ModularCoroot (Fin.addNat (Fin.castAdd 20 i) 24) =
      f4ModularSimpleCoroot (Fin.cast rank_F4.symm i) := by
  rw [← f4OppositeRootIndex_castAdd, f4ModularCoroot_f4OppositeRootIndex,
    f4ModularCoroot_castAdd]

/-- If the pinned root string from `β` in direction `α` has no positive step, then the
corresponding modular Chevalley bracket vanishes. -/
theorem f4Modular_lie_rootVector_eq_zero_of_chainTopCoeff_eq_zero (α β : Fin 48)
    (hne : α ≠ β) (hopp : α ≠ f4OppositeRootIndex β)
    (htop : f4SimplyConnectedRootDatum.chainTopCoeff α β = 0) :
    ⁅f4ModularRootVector α, f4ModularRootVector β⁆ = 0 := by
  let H := F4.cartanSubalgebra valid_F4
  let P := rootSystem H
  let E := F4.rationalRootSystemEquiv valid_F4
  let ia := E.indexEquiv (f4RootIndex α)
  let ib := E.indexEquiv (f4RootIndex β)
  let a : Weight ℚ H (F4.lieAlgebra valid_F4) := f4KillingRoot α
  let b : Weight ℚ H (F4.lieAlgebra valid_F4) := f4KillingRoot β
  have ha : a.IsNonZero := by
    simpa only [a, f4KillingRoot] using LieSubalgebra.isNonZero_coe_root ia
  have hiab : ia ≠ ib := by
    intro h
    apply hne
    apply f4KillingRoot_injective
    exact congrArg Subtype.val h
  have hneg : P.root ia ≠ -P.root ib := by
    intro h
    apply f4KillingRoot_add_ne_zero_of_ne_opposite α β hopp
    apply funext
    intro x
    have hx := DFunLike.congr_fun h x
    -- A root-system root evaluates as its underlying Killing weight; negation is pointwise.
    change (f4KillingRoot α : H → ℚ) x = -(f4KillingRoot β : H → ℚ) x at hx
    change (f4KillingRoot α : H → ℚ) x + (f4KillingRoot β : H → ℚ) x = 0
    rw [hx, neg_add_cancel]
  have hlinP : LinearIndependent ℚ ![P.root ia, P.root ib] :=
    RootPairing.IsReduced.linearIndependent P hiab hneg
  have hlin : LinearIndependent ℚ
      ![(a : Module.Dual ℚ H), (b : Module.Dual ℚ H)] := by
    simpa only [P, ia, ib, a, b, rootSystem_root_apply, Weight.toLinear_apply] using hlinP
  have hLieTop : chainTopCoeff (a : H → ℚ) b = 0 :=
    (f4_chainCoeffs_eq α β hlin).1.trans htop
  have hroot : rootSpace H ((a : H → ℚ) + b) = ⊥ := by
    by_contra hn
    have hc := (rootSpace_zsmul_add_ne_bot_iff a b ha 1).mp (by
      simpa only [one_zsmul] using hn)
    rw [hLieTop] at hc
    omega
  exact f4Modular_lie_rootVector_eq_zero_of_rootSpace_add_eq_bot α β (by
    simpa only [H, a, b] using hroot)

/-- Opposite integral root vectors bracket to the corresponding integral coroot. -/
theorem f4Integral_lie_rootVector_opposite (α : Fin 48) :
    ⁅f4IntegralRootVector α, f4IntegralRootVector (f4OppositeRootIndex α)⁆ =
      f4IntegralCoroot α := by
  simp only [f4Integral_lie_eq_iff, coe_f4IntegralRootVector,
    coe_f4IntegralCoroot, f4KillingRoot_f4OppositeRootIndex]
  exact f4ChevalleyRootVector_isChevalleySystem.toIsSl2System.lie_neg
    (f4KillingRoot α)
    ((F4.cartanSubalgebra valid_F4).isNonZero_coe_root (f4KillingRootLabel α))

/-- Opposite modular root vectors bracket to the corresponding modular coroot. -/
theorem f4Modular_lie_rootVector_opposite (α : Fin 48) :
    ⁅f4ModularRootVector α, f4ModularRootVector (f4OppositeRootIndex α)⁆ =
      f4ModularCoroot α := by
  rw [f4ModularRootVector_eq, f4ModularRootVector_eq,
    f4Modular_lie_tmul, f4Integral_lie_rootVector_opposite]
  rfl

/-- The pinned numbering of simple Killing-root support labels. -/
abbrev f4PinnedSimpleIndexEquiv : f4KillingBase.support ≃ Fin 4 :=
  (F4.lieBasis valid_F4).baseSupportEquiv.symm.trans (finCongr rank_F4)

/-- Recover the Bourbaki node number of a simple Killing root. -/
abbrev f4PinnedSimpleIndex (i : f4KillingBase.support) : Fin 4 :=
  f4PinnedSimpleIndexEquiv i

theorem f4PinnedSimpleIndex_baseSupportEquiv (i : Fin F4.rank) :
    f4PinnedSimpleIndex ((F4.lieBasis valid_F4).baseSupportEquiv i) =
      Fin.cast rank_F4 i := by
  change Fin.cast rank_F4
    ((F4.lieBasis valid_F4).baseSupportEquiv.symm
      ((F4.lieBasis valid_F4).baseSupportEquiv i)) = _
  rw [Equiv.symm_apply_apply]

/-- A pinned simple-index coordinate is the corresponding modular simple coroot. -/
theorem f4ModularChevalleyBasis_inr_f4PinnedSimpleIndexEquiv_symm (k : Fin 4) :
    f4ModularChevalleyBasis (Sum.inr (f4PinnedSimpleIndexEquiv.symm k)) =
      f4ModularSimpleCoroot (Fin.cast rank_F4.symm k) := by
  rw [f4ModularChevalleyBasis_inr_eq_simpleCoroot]
  congr 1
  simp only [f4PinnedSimpleIndexEquiv, Equiv.symm_trans_apply,
    Equiv.symm_symm, Equiv.symm_apply_apply, finCongr_symm, finCongr_apply]

/-- Modular simple coroots commute. -/
theorem f4Modular_lie_simpleCoroot_simpleCoroot_eq_zero (i j : Fin F4.rank) :
    ⁅f4ModularSimpleCoroot i, f4ModularSimpleCoroot j⁆ = 0 := by
  have hlieIntegral : ⁅f4IntegralSimpleCoroot i, f4IntegralSimpleCoroot j⁆ = 0 := by
    simp only [f4Integral_lie_eq_iff, coe_f4IntegralSimpleCoroot, ZeroMemClass.coe_zero]
    exact lie_coroot_coroot_eq_zero _ _
  rw [f4ModularSimpleCoroot_eq, f4ModularSimpleCoroot_eq,
    f4Modular_lie_tmul, hlieIntegral,
    TensorProduct.tmul_zero]

/-- The coordinate of a bracket is the sum of the bracket columns of the basis coordinates. -/
theorem f4ModularChevalleyBasis_repr_lie_eq_sum
    (X Y : f4ModularChevalleyLieAlgebra) (k : f4ChevalleyIndex) :
    f4ModularChevalleyBasis.repr ⁅X, Y⁆ k =
      ∑ i : f4ChevalleyIndex,
        f4ModularChevalleyBasis.repr X i *
          f4ModularChevalleyBasis.repr ⁅f4ModularChevalleyBasis i, Y⁆ k := by
  conv_lhs => rw [← f4ModularChevalleyBasis.sum_repr X]
  rw [sum_lie]
  simp only [smul_lie, map_sum, LinearEquiv.map_smul]
  simp only [Fintype.sum_sum_type, Finset.univ_eq_attach, Finsupp.coe_add,
    Finsupp.coe_finsetSum, Finsupp.coe_smul, Pi.add_apply, Finset.sum_apply,
    Pi.smul_apply, smul_eq_mul]

/-- A simple coroot has no root-vector coordinate. -/
theorem f4ModularChevalleyBasis_repr_simpleCoroot_inl
    (i : Fin F4.rank) (γ : Fin 48) :
    f4ModularChevalleyBasis.repr (f4ModularSimpleCoroot i)
      (Sum.inl (f4KillingRootLabel γ)) = 0 := by
  classical
  rw [f4ModularSimpleCoroot_eq_basis, f4ModularChevalleyBasis.repr_self]
  exact Finsupp.single_eq_of_ne (by simp)

/-- A modular coroot has no root-vector coordinate. -/
theorem f4ModularChevalleyBasis_repr_coroot_inl
    (β γ : Fin 48) :
    f4ModularChevalleyBasis.repr (f4ModularCoroot β)
      (Sum.inl (f4KillingRootLabel γ)) = 0 := by
  classical
  rw [f4ModularCoroot_eq_sum_simple, map_sum]
  simp only [Finsupp.coe_finsetSum, Finset.sum_apply]
  apply Finset.sum_eq_zero
  intro i _
  rw [map_smul, Finsupp.smul_apply,
    f4ModularChevalleyBasis_repr_simpleCoroot_inl, smul_zero]

/-- A root vector has zero coordinate at any different root label. -/
theorem f4ModularChevalleyBasis_repr_smul_rootVector_inl_eq_zero
    (c : ZMod 2) (ε γ : Fin 48) (hεγ : f4KillingRootLabel ε ≠ f4KillingRootLabel γ) :
    f4ModularChevalleyBasis.repr (c • f4ModularRootVector ε)
      (Sum.inl (f4KillingRootLabel γ)) = 0 := by
  classical
  have hindex : (Sum.inl (f4KillingRootLabel γ) : f4ChevalleyIndex) ≠
      Sum.inl (f4KillingRootLabel ε) := by
    intro h
    exact hεγ ((Sum.inl.inj h).symm)
  rw [map_smul, f4ModularRootVector_eq_basis,
    f4ModularChevalleyBasis.repr_self, Finsupp.smul_apply,
    Finsupp.single_eq_of_ne hindex, smul_zero]

/-- The coordinate of a scaled root vector at its own root label is its scalar. -/
theorem f4ModularChevalleyBasis_repr_smul_rootVector_self
    (c : ZMod 2) (β : Fin 48) :
    f4ModularChevalleyBasis.repr (c • f4ModularRootVector β)
      (Sum.inl (f4KillingRootLabel β)) = c := by
  rw [map_smul, f4ModularRootVector_eq_basis,
    f4ModularChevalleyBasis.repr_self, Finsupp.smul_apply,
    Finsupp.single_eq_same, smul_eq_mul, mul_one]

/-- A nonzero, present sum of two Killing roots has the corresponding pinned integral root
label. -/
theorem exists_f4Root_eq_add_of_rootSpace_ne_bot
    (δ β : Fin 48)
    (hsum : (f4KillingRoot δ : (F4.cartanSubalgebra valid_F4) → ℚ) +
      f4KillingRoot β ≠ 0)
    (hbot : rootSpace (F4.cartanSubalgebra valid_F4)
      ((f4KillingRoot δ : (F4.cartanSubalgebra valid_F4) → ℚ) +
        f4KillingRoot β) ≠ ⊥) :
    ∃ ε : Fin 48, f4SimplyConnectedRootDatum.root ε =
      f4SimplyConnectedRootDatum.root β + f4SimplyConnectedRootDatum.root δ := by
  have hsum' : (f4KillingRoot β : (F4.cartanSubalgebra valid_F4) → ℚ) +
      (1 : ℕ) • f4KillingRoot δ ≠ 0 := by
    rw [one_smul, add_comm]
    exact hsum
  have hbot' : rootSpace (F4.cartanSubalgebra valid_F4)
      ((f4KillingRoot β : (F4.cartanSubalgebra valid_F4) → ℚ) +
        (1 : ℕ) • f4KillingRoot δ) ≠ ⊥ := by
    rw [one_smul, add_comm]
    exact hbot
  simpa only [Nat.cast_one, one_zsmul] using
    exists_f4Root_eq_add_zsmul_of_rootSpace_ne_bot δ β 1 hsum' hbot'

/-- A nonzero root coordinate in a modular root-vector bracket has the expected integral root
label, even though the bracket itself is reduced modulo two. -/
theorem f4Root_eq_add_of_repr_lie_rootVector_ne_zero
    (δ β γ : Fin 48)
    (hne : f4ModularChevalleyBasis.repr
      ⁅f4ModularRootVector δ, f4ModularRootVector β⁆
        (Sum.inl (f4KillingRootLabel γ)) ≠ 0) :
    f4SimplyConnectedRootDatum.root γ =
      f4SimplyConnectedRootDatum.root β + f4SimplyConnectedRootDatum.root δ := by
  classical
  let H := F4.cartanSubalgebra valid_F4
  by_cases hsum :
      (f4KillingRoot δ : H → ℚ) + (f4KillingRoot β : H → ℚ) = 0
  · have hindex : δ = f4OppositeRootIndex β := by
      by_contra hopp
      exact f4KillingRoot_add_ne_zero_of_ne_opposite δ β hopp hsum
    rw [hindex, ← lie_skew, f4Modular_lie_rootVector_opposite, map_neg] at hne
    rw [Finsupp.neg_apply] at hne
    rw [f4ModularChevalleyBasis_repr_coroot_inl, neg_zero] at hne
    exact (hne rfl).elim
  by_cases hbot : rootSpace H
      ((f4KillingRoot δ : H → ℚ) + (f4KillingRoot β : H → ℚ)) = ⊥
  · have hlie : ⁅f4ModularRootVector δ, f4ModularRootVector β⁆ = 0 :=
      f4Modular_lie_rootVector_eq_zero_of_rootSpace_add_eq_bot δ β hbot
    have hz : f4ModularChevalleyBasis.repr
        ⁅f4ModularRootVector δ, f4ModularRootVector β⁆
          (Sum.inl (f4KillingRootLabel γ)) = 0 := by
      exact congrArg
        (fun Y => f4ModularChevalleyBasis.repr Y
          (Sum.inl (f4KillingRootLabel γ))) hlie |>.trans
            (congrArg (fun f => f (Sum.inl (f4KillingRootLabel γ)))
              (map_zero f4ModularChevalleyBasis.repr))
    exact (hne hz).elim
  · obtain ⟨ε, hε⟩ := exists_f4Root_eq_add_of_rootSpace_ne_bot δ β hsum hbot
    obtain ⟨z, _, hlie⟩ := exists_f4Modular_lie_rootVector_eq_smul_of_add δ β ε hε
    by_cases heq : f4KillingRootLabel ε = f4KillingRootLabel γ
    · have hεγ : ε = γ := by
        simpa only [f4PinnedRootIndex_f4KillingRootLabel] using
          congrArg f4PinnedRootIndex heq
      have hγε : γ = ε := hεγ.symm
      exact hγε ▸ hε
    · have hz : f4ModularChevalleyBasis.repr
          ⁅f4ModularRootVector δ, f4ModularRootVector β⁆
            (Sum.inl (f4KillingRootLabel γ)) = 0 :=
        congrArg
          (fun Y => f4ModularChevalleyBasis.repr Y
            (Sum.inl (f4KillingRootLabel γ))) hlie |>.trans
              (f4ModularChevalleyBasis_repr_smul_rootVector_inl_eq_zero
                (z : ZMod 2) ε γ heq)
      exact (hne hz).elim

/-- The root-vector coordinate of a simple-coroot bracket is its reduced Cartan integer. -/
theorem f4ModularChevalleyBasis_repr_lie_simpleCoroot_rootVector_self
    (i : Fin F4.rank) (β : Fin 48) :
    f4ModularChevalleyBasis.repr
      ⁅f4ModularSimpleCoroot i, f4ModularRootVector β⁆
      (Sum.inl (f4KillingRootLabel β)) =
      (f4Root β (Fin.cast rank_F4 i) : ZMod 2) := by
  let c : ZMod 2 := f4SimplyConnectedRootDatum.pairing β
    (Fin.castAdd 44 (Fin.cast rank_F4 i))
  have hlie : ⁅f4ModularSimpleCoroot i, f4ModularRootVector β⁆ =
      c • f4ModularRootVector β := f4Modular_lie_simpleCoroot_rootVector i β
  have hrepr := congrArg
    (fun Y => f4ModularChevalleyBasis.repr Y
      (Sum.inl (f4KillingRootLabel β))) hlie
  have hcoeff : f4SimplyConnectedRootDatum.pairing β
      (Fin.castAdd 44 (Fin.cast rank_F4 i)) = f4Root β (Fin.cast rank_F4 i) := by
    rw [f4SimplyConnectedRootDatum_pairing, f4Coroot_castAdd,
      dotProduct_single_one]
  exact hrepr.trans <| (f4ModularChevalleyBasis_repr_smul_rootVector_self c β).trans <|
    congrArg (fun z : ℤ => (z : ZMod 2)) hcoeff


/-- An edge labelled by a nonzero root changes the pinned root label. -/
theorem f4KillingRootLabel_ne_of_root_eq_add (α β γ : Fin 48)
    (hγ : f4SimplyConnectedRootDatum.root γ =
      f4SimplyConnectedRootDatum.root β + f4SimplyConnectedRootDatum.root α) :
    f4KillingRootLabel β ≠ f4KillingRootLabel γ := by
  intro heq
  have hindex : β = γ := by
    simpa only [f4PinnedRootIndex_f4KillingRootLabel] using
      congrArg f4PinnedRootIndex heq
  have hzero : f4SimplyConnectedRootDatum.root α = 0 := by
    apply add_left_cancel (a := f4SimplyConnectedRootDatum.root β)
    simpa only [add_zero, hindex] using hγ.symm
  exact f4SimplyConnectedRootDatum.ne_zero α hzero


end

end TauCeti.DynkinType
