/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.Profinite.ZHat.Decomposition
public import TauCeti.Topology.Algebra.Group.Profinite.ZHat.Pow

/-!
# Closed procyclic subgroups and prime parts

The closed subgroup generated by an element of a profinite group is precisely its set of
profinite powers. Thus it is a quotient of the profinite integers and is abelian. The idempotent
of a prime factor of the profinite integers extracts the corresponding prime part of an element:
its closed procyclic subgroup is pro-`p`, and extraction fixes elements whose closed procyclic
subgroup is already pro-`p`. The finite sums of all prime idempotents tend to `1`, so the prime
parts recover the original element as a limit of finite products.

The power operation is `TauCeti.zpowHat`, defined using `TauCeti.zHat.lift`; the prime
idempotents and their product decomposition are `TauCeti.zHat.idem` and
`TauCeti.zHat.ringEquivPiPadicInt`.

## References

* L. Ribes and P. Zalesskii, *Profinite Groups*, Sections 4.1 and 4.3.
-/

public section

namespace TauCeti

universe u v

open Additive Multiplicative
open scoped zHat

variable {G : Type v} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- The closed procyclic subgroup generated by `x`. -/
abbrev closedZpowers (x : G) : Subgroup G := (Subgroup.zpowers x).topologicalClosure

/-- An element belongs to its closed procyclic subgroup. -/
@[simp]
theorem mem_closedZpowers (x : G) : x ∈ closedZpowers x :=
  (Subgroup.zpowers x).le_topologicalClosure (Subgroup.mem_zpowers x)

/-- The canonical element topologically generates its closed procyclic subgroup. -/
theorem topologicallyGenerates_closedZpowers (x : G) :
    (Subgroup.zpowers (⟨x, mem_closedZpowers x⟩ : closedZpowers x)).topologicalClosure = ⊤ := by
  rw [← Subgroup.dense_iff_topologicalClosure_eq_top]
  have h := (Subgroup.dense_preimage_val_iff_le_topologicalClosure
    (Subgroup.zpowers x).le_topologicalClosure).mpr le_rfl
  have heq :
      (Subgroup.zpowers (⟨x, mem_closedZpowers x⟩ : closedZpowers x) : Set (closedZpowers x)) =
        (Subtype.val : closedZpowers x → G) ⁻¹' (Subgroup.zpowers x : Set G) := by
    ext y
    simp only [Set.mem_preimage, SetLike.mem_coe, Subgroup.mem_zpowers_iff,
      Subtype.ext_iff, Subgroup.coe_zpow]
  rwa [← heq] at h

variable [CompactSpace G] [TotallyDisconnectedSpace G]

/-- The canonical surjection from the profinite integers onto the closed procyclic subgroup. -/
noncomputable def closedZpowersLift (x : G) : zHat.{u} →ₜ* closedZpowers x :=
  zHat.lift ⟨x, mem_closedZpowers x⟩

/-- The canonical surjection is the existing lift, with its codomain restricted. -/
@[simp]
theorem coe_closedZpowersLift (x : G) (a : zHat.{u}) :
    (closedZpowersLift x a : G) = zHat.lift x a :=
  zHat.map_lift
    (⟨(closedZpowers x).subtype, continuous_subtype_val⟩ : closedZpowers x →ₜ* G)
    ⟨x, mem_closedZpowers x⟩ a

/-- Every element of the closed procyclic subgroup is reached by the canonical lift. -/
theorem closedZpowersLift_surjective (x : G) :
    Function.Surjective (closedZpowersLift.{u} x) :=
  zHat.lift_surjective _ (topologicallyGenerates_closedZpowers x)

/-- The closed procyclic subgroup consists exactly of the profinite powers of its generator. -/
theorem range_zpowHat (x : G) :
    Set.range (fun a : Additive zHat.{u} ↦ x ^ᶻ a) = (closedZpowers x : Set G) := by
  apply Set.Subset.antisymm
  · rintro y ⟨a, rfl⟩
    exact zpowHat_mem (Subgroup.isClosed_topologicalClosure _) (mem_closedZpowers x) a
  · intro y hy
    obtain ⟨a, ha⟩ := closedZpowersLift_surjective.{u} x ⟨y, hy⟩
    refine ⟨ofMul a, ?_⟩
    simpa only [zpowHat_def, toMul_ofMul] using
      (coe_closedZpowersLift x a).symm.trans (congrArg Subtype.val ha)

/-- Membership in the closed procyclic subgroup is existence of a profinite exponent. -/
theorem mem_closedZpowers_iff {x y : G} :
    y ∈ closedZpowers x ↔ ∃ a : Additive zHat.{u}, x ^ᶻ a = y :=
  (Set.ext_iff.mp (range_zpowHat.{u} x) y).symm

/-- A profinite power generates a subgroup of the original closed procyclic subgroup. -/
theorem closedZpowers_zpowHat_le (x : G) (a : Additive zHat.{u}) :
    closedZpowers (x ^ᶻ a) ≤ closedZpowers x :=
  Subgroup.topologicalClosure_minimal _
    (Subgroup.zpowers_le.mpr
      (zpowHat_mem (Subgroup.isClosed_topologicalClosure _) (mem_closedZpowers x) a))
    (Subgroup.isClosed_topologicalClosure _)

/-- In a pro-`p` group only the `p`-component of a profinite exponent matters. -/
theorem zpowHat_idem_mul {p : ℕ} [Fact p.Prime] (hG : IsProP p G) (x : G)
    (a : Additive zHat.{u}) : x ^ᶻ (zHat.idem p * a) = x ^ᶻ a := by
  simp only [zpowHat_eq_padicPow_component hG, map_mul, zHat.component_idem_self, one_mul]

/-- Extracting the `p`-part fixes an element of a pro-`p` group. -/
@[simp]
theorem zpowHat_idem {p : ℕ} [Fact p.Prime] (hG : IsProP p G) (x : G) :
    x ^ᶻ zHat.idem.{u} p = x := by
  rw [zpowHat_eq_padicPow_component hG, zHat.component_idem_self, hG.padicPow_one]

/-- Extracting the `p`-part fixes any element whose closed procyclic subgroup is pro-`p`,
even when the ambient group is not pro-`p`. -/
theorem zpowHat_idem_of_isProP_closedZpowers {p : ℕ} [Fact p.Prime] {x : G}
    (hx : IsProP p (closedZpowers x)) : x ^ᶻ zHat.idem.{u} p = x := by
  let y : closedZpowers x := ⟨x, mem_closedZpowers x⟩
  let f : closedZpowers x →ₜ* G := ⟨(closedZpowers x).subtype, continuous_subtype_val⟩
  have h := congrArg f (zpowHat_idem.{u} hx y)
  rw [map_zpowHat] at h
  exact h

/-- The closed subgroup generated by the `p`-part of an element is pro-`p`. -/
theorem isProP_closedZpowers_zpowHat_idem (p : ℕ) [Fact p.Prime] (x : G) :
    IsProP p (closedZpowers (x ^ᶻ zHat.idem.{u} p)) := by
  classical
  -- Embed the additive group of `ℤ_p` as the `p`-factor of the product decomposition.
  let i : Nat.Primes := ⟨p, Fact.out⟩
  let f : ℤ_[p] →+ Additive zHat.{u} :=
    zHat.ringEquivPiPadicInt.symm.toAddMonoidHom.comp
      (AddMonoidHom.single (fun q : Nat.Primes ↦ ℤ_[q]) i)
  -- Isolate the local bundled additive map's value before using its continuity.
  have hfapply (t : ℤ_[p]) : f t = zHat.ringEquivPiPadicInt.symm (Pi.single i t) := rfl
  have hf : Continuous f :=
    (zHat.continuous_ringEquivPiPadicInt_symm.{u}.comp
      (continuous_single (A := fun q : Nat.Primes ↦ ℤ_[q]) i)).congr
      fun t ↦ (hfapply t).symm
  have hf1 : f 1 = zHat.idem p := by
    apply zHat.ringEquivPiPadicInt.injective
    simp only [hfapply, RingEquiv.apply_symm_apply, zHat.ringEquivPiPadicInt_idem, i]
  let φ : Multiplicative ℤ_[p] →ₜ* zHat.{u} :=
    ⟨f.toMultiplicativeLeft, continuous_toMul.comp (hf.comp continuous_toAdd)⟩
  let ψ : Multiplicative ℤ_[p] →ₜ* G := (zHat.lift x).comp φ
  -- The local type-tag conversion expresses the additive embedding multiplicatively.
  have hφ (t : ℤ_[p]) : φ (ofAdd t) = (f t).toMul := rfl
  have hψ1 : ψ (ofAdd 1) = x ^ᶻ zHat.idem.{u} p := by
    simp only [ψ, ContinuousMonoidHom.coe_comp, Function.comp_apply, hφ, hf1, zpowHat_def]
  have hrange : IsProP p ψ.toMonoidHom.range :=
    (isProP_multiplicative_padicInt p).of_surjective ψ.toMonoidHom.rangeRestrict
      (continuous_induced_rng.mpr ψ.continuous) ψ.toMonoidHom.rangeRestrict_surjective
  have hclosed : IsClosed (ψ.toMonoidHom.range : Set G) :=
    (isCompact_range ψ.continuous).isClosed
  exact hrange.mono (Subgroup.topologicalClosure_minimal _
    (Subgroup.zpowers_le.mpr ⟨ofAdd 1, hψ1⟩) hclosed)

/-- An element is its own `p`-part exactly when its closed procyclic subgroup is pro-`p`. -/
theorem zpowHat_idem_eq_self_iff (p : ℕ) [Fact p.Prime] (x : G) :
    x ^ᶻ zHat.idem.{u} p = x ↔ IsProP p (closedZpowers x) := by
  constructor
  · intro h
    rw [← h]
    exact isProP_closedZpowers_zpowHat_idem p x
  · exact zpowHat_idem_of_isProP_closedZpowers

/-- Finite collections of prime parts recover the original element in the limit. -/
theorem tendsto_zpowHat_sum_idem (x : G) :
    Filter.Tendsto (fun s : Finset Nat.Primes ↦ x ^ᶻ (∑ p ∈ s, zHat.idem.{u} p))
      Filter.atTop (nhds x) := by
  simpa only [Function.comp_def, zpowHat_one] using
    (continuous_zpowHat.{u} x).continuousAt.tendsto.comp zHat.tendsto_sum_idem.{u}

end TauCeti
