/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.KnotTheory.SeifertMatrix.SEquivalence
public import TauCeti.KnotTheory.TristramLevine.Enlargement

/-!
# The Tristram--Levine signature under S-equivalence

The Tristram--Levine signature of an integral square matrix is constant on ambient S-equivalence
classes. This packages the existing congruence and enlargement calculations into the equivalence
relation generated by those moves, and therefore applies in particular to genuine Seifert
matrices.

The result is still algebraic: it does not construct a Seifert matrix from a knot or prove the
geometric theorem that different Seifert surfaces yield S-equivalent matrices. It is the descent
step needed before the signature can be attached to a geometric knot presentation.

## Main result

* `TauCeti.KnotTheory.IntegralSquareMatrix.SEquivalent.tristramLevineSignature_eq`:
  S-equivalent integral square matrices have the same Tristram--Levine signature at every complex
  parameter.

## References

* W. B. R. Lickorish, *An Introduction to Knot Theory*, Springer GTM 175 (1997), Chapter 8,
  Theorem 8.9.
-/

public section

open Matrix

namespace TauCeti.KnotTheory.IntegralSquareMatrix

namespace IsMove

/-- One elementary S-equivalence move preserves the Tristram--Levine signature. -/
theorem tristramLevineSignature_eq {V W : IntegralSquareMatrix} (h : IsMove V W) (omega : ℂ) :
    tristramLevineSignature (W.2.map ((↑) : ℤ → ℝ)) omega =
      tristramLevineSignature (V.2.map ((↑) : ℤ → ℝ)) omega := by
  -- Dependent elimination leaves the endpoints as sigma projections and elaborates the integer
  -- cast as a function. The `change` steps expose the constructor matrices and ascribe that cast
  -- as a ring homomorphism, after which the generic map and reindexing lemmas apply directly.
  cases h with
  | congr V P hP =>
      have hPReal : IsUnit (P.map (Int.castRingHom ℝ)).det :=
        RingHom.map_det (Int.castRingHom ℝ) P ▸ hP.map (Int.castRingHom ℝ)
      change tristramLevineSignature ((P * V * Pᵀ).map (Int.castRingHom ℝ)) omega =
        tristramLevineSignature (V.map (Int.castRingHom ℝ)) omega
      rw [Matrix.map_mul, Matrix.map_mul, transpose_map]
      exact tristramLevineSignature_congr hPReal (V.map (Int.castRingHom ℝ)) omega
  | enlargeColumn V xi =>
      change tristramLevineSignature ((enlargeColumnFin V xi).map (Int.castRingHom ℝ)) omega =
        tristramLevineSignature (V.map (Int.castRingHom ℝ)) omega
      rw [map_enlargeColumnFin]
      rw [enlargeColumnFin_def, tristramLevineSignature_submatrix_equiv_self,
        tristramLevineSignature_enlargeColumn]
  | enlargeRow V eta =>
      change tristramLevineSignature ((enlargeRowFin V eta).map (Int.castRingHom ℝ)) omega =
        tristramLevineSignature (V.map (Int.castRingHom ℝ)) omega
      rw [map_enlargeRowFin]
      rw [enlargeRowFin_def, tristramLevineSignature_submatrix_equiv_self,
        tristramLevineSignature_enlargeRow]

end IsMove

namespace SEquivalent

/-- **The Tristram--Levine signature is invariant under S-equivalence.** -/
theorem tristramLevineSignature_eq {V W : IntegralSquareMatrix} (h : SEquivalent V W) (omega : ℂ) :
    tristramLevineSignature (V.2.map ((↑) : ℤ → ℝ)) omega =
      tristramLevineSignature (W.2.map ((↑) : ℤ → ℝ)) omega := by
  apply Relation.EqvGen.eqvGen_le (r' := Setoid.ker fun X : IntegralSquareMatrix ↦
    tristramLevineSignature (X.2.map ((↑) : ℤ → ℝ)) omega) ?_ V W h
  intro X Y hmove
  exact (hmove.tristramLevineSignature_eq omega).symm

end SEquivalent

end TauCeti.KnotTheory.IntegralSquareMatrix
