/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.Profinite.ProP.LowerCentralSeries

/-!
# The Frattini series of a profinite group

The **Frattini series** `Φ_k = TauCeti.proPFrattiniSeries p G k` of a topological group is the
sequence of closed subgroups

```text
Φ₀ = G,   Φ_{k+1} = closure (Φ_kᵖ ⬝ [Φ_k, Φ_k]),
```

obtained by iterating the verbal form of the pro-`p` Frattini subgroup. One step of the recursion
is `TauCeti.proPFrattiniStep`, whose characteristic property
`TauCeti.proPFrattiniStep_le_iff` characterizes containment in a closed subgroup. For a prime `p`
and a closed subgroup `H` of a profinite group, the step is the honest Frattini subgroup of `H`,
transported to the ambient group along the inclusion
(`TauCeti.proPFrattiniStep_eq_map_proPFrattini`), so `Φ_{k+1} = Φ(Φ_k)`; in particular
`Φ_1 = proPFrattini p G`.

The Frattini series and the lower `p`-series `λ_k = TauCeti.pLowerCentralSeries p G k` of
`TauCeti.Topology.Algebra.Group.LowerCentralSeries` **interleave**: the two steps differ only in
that the Frattini step takes commutators inside the subgroup while the lower `p`-series step takes
them against the whole group, so `Φ_k ≤ λ_k` always; and in a topologically finitely generated
pro-`p` group every `Φ_k` is open, so conversely every `Φ_k` contains a `λ_j`. The two series are
therefore cofinal in one another, and both are neighbourhood bases of `1`; the arguments that run
level by level along one of them run equally along the other.

Cofinality of the Frattini series among the open normal subgroups of a pro-`p` group needs no
finite generation, because `Φ_k ≤ λ_k` and the lower `p`-series is already cofinal. So the `Φ_k`
have trivial intersection in any pro-`p` group and such a group is the inverse limit of its
quotients `G ⧸ Φ_k`. With finite generation the quotients are finite `p`-groups. Without finite
generation the terms need not be open: an infinite product of copies of `ℤ ⧸ p` has `Φ_1 = 1`.

## Main definitions

* `TauCeti.proPFrattiniStep`: one step `H ↦ closure (Hᵖ ⬝ [H, H])` of the recursion.
* `TauCeti.proPFrattiniSeries`: the Frattini series `Φ_k`.

## Main results

* `TauCeti.proPFrattiniStep_le_iff`: a closed subgroup contains `proPFrattiniStep p H` exactly
  when it contains the `p`-th powers of `H` and the commutators `⁅H, H⁆`.
* `TauCeti.proPFrattiniStep_eq_map_proPFrattini` and
  `TauCeti.proPFrattiniSeries_succ_eq_map_proPFrattini`: for a prime `p` and a closed subgroup of
  a profinite group the step is the pro-`p` Frattini subgroup of that subgroup, so the series is
  the iterated Frattini subgroup; `TauCeti.proPFrattiniSeries_one` is the case `Φ_1 = Φ(G)`.
* `TauCeti.proPFrattiniSeries_le_pLowerCentralSeries` and
  `TauCeti.IsProP.exists_pLowerCentralSeries_le_proPFrattiniSeries`: the interleaving of the
  Frattini series with the lower `p`-series.
* `TauCeti.IsTopologicallyFinitelyGenerated.isOpen_proPFrattiniSeries`: in a topologically
  finitely generated profinite group every `Φ_k` is open, so
  `TauCeti.IsTopologicallyFinitelyGenerated.finite_quotient_proPFrattiniSeries` and, for a pro-`p`
  group, `TauCeti.IsProP.isPGroup_quotient_proPFrattiniSeries`.
* `TauCeti.IsProP.exists_proPFrattiniSeries_le`: in a pro-`p` group every open normal subgroup
  contains a term of the Frattini series, so `TauCeti.IsProP.iInf_proPFrattiniSeries_eq_bot`.
* `TauCeti.IsProP.existsUnique_forall_mk_eq_proPFrattiniSeries`: a pro-`p` group is the inverse
  limit of its quotients `G ⧸ Φ_k`.
* `TauCeti.IsProP.hasAntitoneBasis_nhds_one_proPFrattiniSeries`: in a topologically finitely
  generated pro-`p` group the Frattini series is a neighbourhood basis of `1`.

## References

* L. Ribes and P. Zalesskii, *Profinite Groups*, Section 2.8, Proposition 2.8.13.
* J. D. Dixon, M. P. F. du Sautoy, A. Mann and D. Segal, *Analytic pro-`p` groups*, Section 1.2.
-/

public section

namespace TauCeti

open Subgroup
open scoped commutatorElement

/-! ### One step of the recursion -/

section Step

variable (p : ℕ) {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- One step of the **Frattini series**: `H ↦ closure (Hᵖ ⬝ [H, H])`, the topological closure of
the subgroup generated by the `p`-th powers of the elements of `H` and the commutators `⁅H, H⁆`.
For a prime `p` and a closed subgroup of a profinite group it is the pro-`p` Frattini subgroup of
`H`, viewed inside the ambient group (`TauCeti.proPFrattiniStep_eq_map_proPFrattini`). Its
characteristic property is `TauCeti.proPFrattiniStep_le_iff`. -/
def proPFrattiniStep (H : Subgroup G) : Subgroup G :=
  (Subgroup.closure ((· ^ p) '' (H : Set G)) ⊔ ⁅H, H⁆).topologicalClosure

/-- The defining equation `proPFrattiniStep p H = closure (Hᵖ ⬝ [H, H])`, with topological
closure, expresses the next Frattini step in terms of powers and commutators. -/
theorem proPFrattiniStep_def (H : Subgroup G) :
    proPFrattiniStep p H =
      (Subgroup.closure ((· ^ p) '' (H : Set G)) ⊔ ⁅H, H⁆).topologicalClosure := by
  rw [proPFrattiniStep]

variable {p}

/-- One step of the Frattini series is a closed subgroup. -/
theorem isClosed_proPFrattiniStep (H : Subgroup G) :
    IsClosed (proPFrattiniStep p H : Set G) := by
  rw [proPFrattiniStep_def]
  exact isClosed_topologicalClosure _

/-- The `p`-th power of an element of `H` lies in `proPFrattiniStep p H`. -/
theorem pow_mem_proPFrattiniStep {H : Subgroup G} {x : G} (hx : x ∈ H) :
    x ^ p ∈ proPFrattiniStep p H := by
  rw [proPFrattiniStep_def]
  exact le_topologicalClosure _ (mem_sup_left (Subgroup.subset_closure ⟨x, hx, rfl⟩))

/-- The commutators `⁅H, H⁆` lie in `proPFrattiniStep p H`. -/
theorem commutator_le_proPFrattiniStep (H : Subgroup G) :
    ⁅H, H⁆ ≤ proPFrattiniStep p H := by
  rw [proPFrattiniStep_def]
  exact le_sup_right.trans (le_topologicalClosure _)

/-- The commutator of two elements of `H` lies in `proPFrattiniStep p H`. -/
theorem commutator_mem_proPFrattiniStep {H : Subgroup G} {x y : G} (hx : x ∈ H) (hy : y ∈ H) :
    ⁅x, y⁆ ∈ proPFrattiniStep p H :=
  commutator_le_proPFrattiniStep H (commutator_mem_commutator hx hy)

/-- **The characteristic property of one step.** A closed subgroup contains
`proPFrattiniStep p H` exactly when it contains the `p`-th powers of the elements of `H` and the
commutators `⁅H, H⁆`. -/
theorem proPFrattiniStep_le_iff {H K : Subgroup G} (hK : IsClosed (K : Set G)) :
    proPFrattiniStep p H ≤ K ↔ (∀ x ∈ H, x ^ p ∈ K) ∧ ⁅H, H⁆ ≤ K := by
  refine ⟨fun h ↦ ⟨fun x hx ↦ h (pow_mem_proPFrattiniStep hx),
    (commutator_le_proPFrattiniStep H).trans h⟩, fun ⟨hpow, hcomm⟩ ↦ ?_⟩
  rw [proPFrattiniStep_def]
  refine topologicalClosure_minimal _ (sup_le ((Subgroup.closure_le _).mpr ?_) hcomm) hK
  rintro _ ⟨x, hx, rfl⟩
  exact hpow x hx

/-- One step of the Frattini series is monotone in the subgroup. -/
theorem proPFrattiniStep_mono {H K : Subgroup G} (h : H ≤ K) :
    proPFrattiniStep p H ≤ proPFrattiniStep p K :=
  (proPFrattiniStep_le_iff (isClosed_proPFrattiniStep K)).mpr
    ⟨fun _ hx ↦ pow_mem_proPFrattiniStep (h hx),
      (commutator_mono h h).trans (commutator_le_proPFrattiniStep K)⟩

/-- One step of the Frattini series lies in the corresponding step of the lower `p`-series: the
two differ only in that the latter takes commutators against the whole group. -/
theorem proPFrattiniStep_le_pLowerCentralStep (H : Subgroup G) :
    proPFrattiniStep p H ≤ pLowerCentralStep p H :=
  (proPFrattiniStep_le_iff (isClosed_pLowerCentralStep H)).mpr
    ⟨fun _ hx ↦ pow_mem_pLowerCentralStep hx,
      (commutator_mono le_rfl le_top).trans (commutator_le_pLowerCentralStep H)⟩

/-- One step of the Frattini series of a normal subgroup is normal. -/
instance proPFrattiniStep_normal (H : Subgroup G) [H.Normal] :
    (proPFrattiniStep p H).Normal := by
  rw [proPFrattiniStep_def]
  have : (Subgroup.closure ((· ^ p) '' (H : Set G))).Normal := by
    refine closure_normal_of_forall_conj_mem ?_
    rintro g _ ⟨x, hx, rfl⟩
    exact ⟨g * x * g⁻¹, Normal.conj_mem ‹H.Normal› x hx g, conj_pow⟩
  exact is_normal_topologicalClosure _

/-- One step of the Frattini series of a closed subgroup lies in that subgroup. -/
theorem proPFrattiniStep_le {H : Subgroup G} (hH : IsClosed (H : Set G)) :
    proPFrattiniStep p H ≤ H :=
  (proPFrattiniStep_le_iff hH).mpr ⟨fun _ hx ↦ H.pow_mem hx p, H.commutator_le_self⟩

variable {H : Type*} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

/-- A continuous homomorphism carries one step of the Frattini series of a subgroup into the
corresponding step for the image of that subgroup. -/
theorem _root_.MonoidHom.map_proPFrattiniStep_le (f : G →* H) (hf : Continuous f)
    (K : Subgroup G) : (proPFrattiniStep p K).map f ≤ proPFrattiniStep p (K.map f) := by
  rw [map_le_iff_le_comap]
  have hclosed : IsClosed ((proPFrattiniStep p (K.map f)).comap f : Set G) := by
    rw [coe_comap]
    exact (isClosed_proPFrattiniStep _).preimage hf
  refine (proPFrattiniStep_le_iff hclosed).mpr ⟨fun x hx ↦ ?_, ?_⟩
  · rw [mem_comap, map_pow]
    exact pow_mem_proPFrattiniStep (mem_map_of_mem f hx)
  · rw [← map_le_iff_le_comap, map_commutator]
    exact commutator_le_proPFrattiniStep _

/-- A continuous closed map (for instance a continuous homomorphism from a compact group to a
Hausdorff group, by `Continuous.isClosedMap`) carries one step of the Frattini series of a
subgroup onto the corresponding step for its image. Unlike for the lower `p`-series, no
surjectivity is needed: the Frattini step of `K` refers to `K` alone. -/
theorem _root_.MonoidHom.map_proPFrattiniStep_eq_of_isClosedMap (f : G →* H) (hf : Continuous f)
    (hfc : IsClosedMap f) (K : Subgroup G) :
    (proPFrattiniStep p K).map f = proPFrattiniStep p (K.map f) := by
  refine le_antisymm (f.map_proPFrattiniStep_le hf K) ?_
  have hclosed : IsClosed ((proPFrattiniStep p K).map f : Set H) := by
    rw [coe_map]
    exact hfc _ (isClosed_proPFrattiniStep K)
  refine (proPFrattiniStep_le_iff hclosed).mpr ⟨fun y hy ↦ ?_, ?_⟩
  · obtain ⟨x, hx, rfl⟩ := mem_map.mp hy
    exact ⟨x ^ p, pow_mem_proPFrattiniStep hx, map_pow f x p⟩
  · rw [← map_commutator]
    exact map_mono (commutator_le_proPFrattiniStep K)

end Step

/-! ### The series -/

section Series

variable (p : ℕ) (G : Type*) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- The **Frattini series** of a topological group, 0-based like the lower `p`-series:
`Φ₀ = G` and `Φ_{k+1} = closure (Φ_kᵖ ⬝ [Φ_k, Φ_k])`. For a prime `p` and a profinite group it
is the iterated pro-`p` Frattini subgroup
(`TauCeti.proPFrattiniSeries_succ_eq_map_proPFrattini`), and it interleaves with the lower
`p`-series (`TauCeti.proPFrattiniSeries_le_pLowerCentralSeries`). -/
def proPFrattiniSeries : ℕ → Subgroup G
  | 0 => ⊤
  | k + 1 => proPFrattiniStep p (proPFrattiniSeries k)

@[simp]
theorem proPFrattiniSeries_zero : proPFrattiniSeries p G 0 = ⊤ := by
  rw [proPFrattiniSeries]

@[simp]
theorem proPFrattiniSeries_succ (k : ℕ) :
    proPFrattiniSeries p G (k + 1) = proPFrattiniStep p (proPFrattiniSeries p G k) := by
  rw [proPFrattiniSeries]

variable {p G}

/-- Every term of the Frattini series is a normal subgroup. -/
instance proPFrattiniSeries_normal (k : ℕ) : (proPFrattiniSeries p G k).Normal := by
  induction k with
  | zero => rw [proPFrattiniSeries_zero]; infer_instance
  | succ k _ => rw [proPFrattiniSeries_succ]; infer_instance

/-- Every term of the Frattini series is closed. -/
theorem isClosed_proPFrattiniSeries (k : ℕ) :
    IsClosed (proPFrattiniSeries p G k : Set G) := by
  cases k with
  | zero => rw [proPFrattiniSeries_zero, coe_top]; exact isClosed_univ
  | succ k => rw [proPFrattiniSeries_succ]; exact isClosed_proPFrattiniStep _

/-- The Frattini series is descending. -/
theorem proPFrattiniSeries_succ_le (k : ℕ) :
    proPFrattiniSeries p G (k + 1) ≤ proPFrattiniSeries p G k := by
  rw [proPFrattiniSeries_succ]
  exact proPFrattiniStep_le (isClosed_proPFrattiniSeries k)

/-- The Frattini series is antitone. -/
theorem proPFrattiniSeries_antitone : Antitone (proPFrattiniSeries p G) :=
  antitone_nat_of_succ_le proPFrattiniSeries_succ_le

/-- The `p`-th power of an element of `Φ_k` lies in `Φ_{k+1}`. -/
theorem pow_mem_proPFrattiniSeries {k : ℕ} {x : G} (hx : x ∈ proPFrattiniSeries p G k) :
    x ^ p ∈ proPFrattiniSeries p G (k + 1) := by
  rw [proPFrattiniSeries_succ]
  exact pow_mem_proPFrattiniStep hx

/-- The commutators of `Φ_k` with itself lie in `Φ_{k+1}`. -/
theorem commutator_proPFrattiniSeries_le (k : ℕ) :
    ⁅proPFrattiniSeries p G k, proPFrattiniSeries p G k⁆ ≤ proPFrattiniSeries p G (k + 1) := by
  rw [proPFrattiniSeries_succ]
  exact commutator_le_proPFrattiniStep _

/-- **The Frattini series lies below the lower `p`-series**, term by term: the Frattini step takes
commutators inside the subgroup, the lower `p`-series step takes them against the whole group. -/
theorem proPFrattiniSeries_le_pLowerCentralSeries (k : ℕ) :
    proPFrattiniSeries p G k ≤ pLowerCentralSeries p G k := by
  induction k with
  | zero => rw [proPFrattiniSeries_zero, pLowerCentralSeries_zero]
  | succ k ih =>
    rw [proPFrattiniSeries_succ, pLowerCentralSeries_succ]
    exact (proPFrattiniStep_le_pLowerCentralStep _).trans (pLowerCentralStep_mono ih)

/-! ### Functoriality -/

variable {H : Type*} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

/-- A continuous homomorphism carries `Φ_k` into `Φ_k`. -/
theorem _root_.MonoidHom.map_proPFrattiniSeries_le (f : G →* H) (hf : Continuous f) (k : ℕ) :
    (proPFrattiniSeries p G k).map f ≤ proPFrattiniSeries p H k := by
  induction k with
  | zero => rw [proPFrattiniSeries_zero]; exact le_top
  | succ k ih =>
    rw [proPFrattiniSeries_succ, proPFrattiniSeries_succ]
    exact (f.map_proPFrattiniStep_le hf _).trans (proPFrattiniStep_mono ih)

/-- A continuous closed surjection (for instance a continuous surjection from a compact group onto
a Hausdorff group, by `Continuous.isClosedMap`) carries `Φ_k` onto `Φ_k`. -/
theorem _root_.MonoidHom.map_proPFrattiniSeries_eq_of_surjective (f : G →* H) (hf : Continuous f)
    (hfc : IsClosedMap f) (hsurj : Function.Surjective f) (k : ℕ) :
    (proPFrattiniSeries p G k).map f = proPFrattiniSeries p H k := by
  induction k with
  | zero =>
    rw [proPFrattiniSeries_zero, proPFrattiniSeries_zero]
    exact map_top_of_surjective f hsurj
  | succ k ih =>
    rw [proPFrattiniSeries_succ, proPFrattiniSeries_succ,
      f.map_proPFrattiniStep_eq_of_isClosedMap hf hfc, ih]

/-- A topological group isomorphism matches the Frattini series of its source and target term by
term. In particular, every term of the Frattini series is stable under continuous
automorphisms. -/
theorem _root_.ContinuousMulEquiv.map_proPFrattiniSeries_eq (e : G ≃ₜ* H) (k : ℕ) :
    (proPFrattiniSeries p G k).map e.toMulEquiv.toMonoidHom = proPFrattiniSeries p H k := by
  refine le_antisymm (MonoidHom.map_proPFrattiniSeries_le _ e.continuous k) fun x hx ↦ ?_
  have hsymm : e.symm x ∈ proPFrattiniSeries p G k :=
    e.symm.toMulEquiv.toMonoidHom.map_proPFrattiniSeries_le e.symm.continuous k
      (mem_map_of_mem _ hx)
  exact ⟨e.symm x, hsymm, e.apply_symm_apply x⟩

end Series

/-! ### The Frattini series of a profinite group -/

section Profinite

variable {p : ℕ} {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [CompactSpace G] [TotallyDisconnectedSpace G]

/-- **One step of the Frattini series is the pro-`p` Frattini subgroup.** For a prime `p` and a
closed subgroup `H` of a profinite group, `proPFrattiniStep p H` is the pro-`p` Frattini subgroup
of `H`, viewed inside the ambient group along the inclusion. -/
theorem proPFrattiniStep_eq_map_proPFrattini (hp : p.Prime) {H : Subgroup G}
    (hH : IsClosed (H : Set G)) :
    proPFrattiniStep p H = (proPFrattini p H).map H.subtype := by
  have : CompactSpace H := isCompact_iff_compactSpace.mp hH.isCompact
  -- The `p`-th powers of `H`, computed in `H` and transported, are the `p`-th powers of `H`.
  have himage : ⇑H.subtype '' (Set.range fun x : H ↦ x ^ p) = (· ^ p) '' (H : Set G) := by
    rw [← Set.range_comp]
    refine Set.ext fun x ↦ ⟨?_, ?_⟩
    · rintro ⟨y, rfl⟩
      exact ⟨y, y.2, by simp⟩
    · rintro ⟨y, hy, rfl⟩
      exact ⟨⟨y, hy⟩, by simp⟩
  rw [proPFrattini_eq_topologicalClosure hp,
    H.subtype.map_topologicalClosure continuous_subtype_val _
      (isClosed_topologicalClosure _).isCompact,
    Subgroup.map_sup, MonoidHom.map_closure, himage, H.map_subtype_commutator,
    proPFrattiniStep_def]

/-- **The Frattini series is the iterated pro-`p` Frattini subgroup.** For a prime `p` and a
profinite group, `Φ_{k+1}` is the pro-`p` Frattini subgroup of `Φ_k`, viewed inside the ambient
group along the inclusion. -/
theorem proPFrattiniSeries_succ_eq_map_proPFrattini (hp : p.Prime) (k : ℕ) :
    proPFrattiniSeries p G (k + 1) =
      (proPFrattini p (proPFrattiniSeries p G k)).map (proPFrattiniSeries p G k).subtype := by
  rw [proPFrattiniSeries_succ,
    proPFrattiniStep_eq_map_proPFrattini hp (isClosed_proPFrattiniSeries k)]

/-- The first term of the Frattini series of a profinite group is its pro-`p` Frattini
subgroup. -/
theorem proPFrattiniSeries_one (hp : p.Prime) :
    proPFrattiniSeries p G 1 = proPFrattini p G := by
  -- At the whole group the two steps are the same closure: `⁅⊤, ⊤⁆` on both sides.
  rw [← pLowerCentralSeries_one_eq_proPFrattini hp, proPFrattiniSeries_succ,
    proPFrattiniSeries_zero, pLowerCentralSeries_succ, pLowerCentralSeries_zero,
    proPFrattiniStep_def, pLowerCentralStep_def]

/-- **Openness of the Frattini series.** For a prime `p`, in a topologically finitely generated
profinite group every term of the Frattini series is open. -/
theorem IsTopologicallyFinitelyGenerated.isOpen_proPFrattiniSeries
    (hG : IsTopologicallyFinitelyGenerated G) (hp : p.Prime) (k : ℕ) :
    IsOpen (proPFrattiniSeries p G k : Set G) := by
  induction k with
  | zero => rw [proPFrattiniSeries_zero, coe_top]; exact isOpen_univ
  | succ k ih =>
    let U : OpenSubgroup G := ⟨proPFrattiniSeries p G k, ih⟩
    have : CompactSpace U.toSubgroup :=
      isCompact_iff_compactSpace.mp (isClosed_proPFrattiniSeries k).isCompact
    -- The Frattini subgroup of the open subgroup `Φ_k` is open in it, hence open in `G`.
    have hopen : IsOpen (proPFrattini p U.toSubgroup : Set U.toSubgroup) :=
      (hG.of_openSubgroup U).isOpen_proPFrattini p
    rw [proPFrattiniSeries_succ_eq_map_proPFrattini hp, coe_map, coe_subtype]
    exact ih.isOpenMap_subtype_val _ hopen

/-- For a prime `p`, in a topologically finitely generated profinite group every quotient
`G ⧸ Φ_k` is finite. -/
theorem IsTopologicallyFinitelyGenerated.finite_quotient_proPFrattiniSeries
    (hG : IsTopologicallyFinitelyGenerated G) (hp : p.Prime) (k : ℕ) :
    Finite (G ⧸ proPFrattiniSeries p G k) :=
  quotient_finite_of_isOpen _ (hG.isOpen_proPFrattiniSeries hp k)

/-- For a prime `p`, in a topologically finitely generated pro-`p` group every quotient `G ⧸ Φ_k`
is a finite `p`-group. -/
theorem IsProP.isPGroup_quotient_proPFrattiniSeries (hG : IsProP p G)
    (hfg : IsTopologicallyFinitelyGenerated G) (hp : p.Prime) (k : ℕ) :
    IsPGroup p (G ⧸ proPFrattiniSeries p G k) :=
  isProP_iff.mp hG ⟨⟨proPFrattiniSeries p G k, hfg.isOpen_proPFrattiniSeries hp k⟩,
    inferInstance⟩

/-! ### Cofinality of the Frattini series in a pro-`p` group -/

open Filter Topology

omit [TotallyDisconnectedSpace G] in
/-- **Cofinality of the Frattini series.** In a compact pro-`p` group every open normal subgroup
contains a term of the Frattini series. No finite generation is needed. -/
theorem IsProP.exists_proPFrattiniSeries_le (hG : IsProP p G) (hp : p.Prime)
    (U : OpenNormalSubgroup G) : ∃ k, proPFrattiniSeries p G k ≤ U.toSubgroup := by
  obtain ⟨k, hk⟩ := hG.exists_pLowerCentralSeries_le hp U
  exact ⟨k, (proPFrattiniSeries_le_pLowerCentralSeries k).trans hk⟩

/-- In a pro-`p` group the terms of the Frattini series have trivial intersection. -/
theorem IsProP.iInf_proPFrattiniSeries_eq_bot (hG : IsProP p G) (hp : p.Prime) :
    ⨅ k, proPFrattiniSeries p G k = ⊥ := by
  refine le_bot_iff.mp ?_
  rw [← hG.iInf_pLowerCentralSeries_eq_bot hp]
  exact le_iInf fun k ↦ iInf_le_of_le k (proPFrattiniSeries_le_pLowerCentralSeries k)

/-- **The interleaving of the two series.** For a prime `p`, in a topologically finitely generated
pro-`p` group every term of the Frattini series contains a term of the lower `p`-series. Together
with `TauCeti.proPFrattiniSeries_le_pLowerCentralSeries` this makes the two series cofinal in one
another. -/
theorem IsProP.exists_pLowerCentralSeries_le_proPFrattiniSeries (hG : IsProP p G)
    (hfg : IsTopologicallyFinitelyGenerated G) (hp : p.Prime) (k : ℕ) :
    ∃ j, pLowerCentralSeries p G j ≤ proPFrattiniSeries p G k :=
  hG.exists_pLowerCentralSeries_le hp
    ⟨⟨proPFrattiniSeries p G k, hfg.isOpen_proPFrattiniSeries hp k⟩, inferInstance⟩

/-- **A pro-`p` group is the inverse limit of its quotients by the Frattini series.** A sequence
of cosets of the `Φ_k`, compatible along the quotient maps, is realized by a unique element. -/
theorem IsProP.existsUnique_forall_mk_eq_proPFrattiniSeries (hG : IsProP p G) (hp : p.Prime)
    (x : ∀ k, G ⧸ proPFrattiniSeries p G k)
    (hcompat : ∀ (k : ℕ) (g : G), (g : G ⧸ proPFrattiniSeries p G (k + 1)) = x (k + 1) →
      (g : G ⧸ proPFrattiniSeries p G k) = x k) :
    ∃! g : G, ∀ k, (g : G ⧸ proPFrattiniSeries p G k) = x k :=
  existsUnique_forall_mk_eq_of_iInf_eq_bot isClosed_proPFrattiniSeries
    (hG.iInf_proPFrattiniSeries_eq_bot hp) x hcompat

/-- **The Frattini series is a neighbourhood basis of `1`** in a topologically finitely generated
pro-`p` group. -/
theorem IsProP.hasAntitoneBasis_nhds_one_proPFrattiniSeries (hG : IsProP p G)
    (hfg : IsTopologicallyFinitelyGenerated G) (hp : p.Prime) :
    (𝓝 (1 : G)).HasAntitoneBasis fun k ↦ (proPFrattiniSeries p G k : Set G) :=
  hasAntitoneBasis_nhds_one_of_iInf_eq_bot proPFrattiniSeries_antitone
    (hfg.isOpen_proPFrattiniSeries hp) (hG.iInf_proPFrattiniSeries_eq_bot hp)

end Profinite

end TauCeti
