/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AddCircle
public import TauCeti.Algebra.CrossedProduct.TwoTorsion
public import TauCeti.NumberTheory.ClassFieldTheory.Brauer.CentralSimple
public import TauCeti.NumberTheory.ClassFieldTheory.Brauer.Invariant
public import TauCeti.NumberTheory.LocalField.Quaternion.Subgroup

/-!
# Quaternion classes and the local invariant

Let `K` be a nonarchimedean local field. The local invariant
`TauCeti.ClassFieldTheory.invMap K : Br K ≃+ ℚ/ℤ` of class field theory, read on Brauer classes
of central simple algebras through `TauCeti.ClassFieldTheory.brauerGroupEquivBr K`, identifies the
`2`-torsion `Br(K)[2]` with the two-element group `(½ℤ)/ℤ`: the nontrivial class of `Br(K)[2]`
has invariant `1/2`.

When two is invertible in `K`, the subgroup `Q(K)` generated by the quaternion classes already has
two elements, so the two subgroups coincide:

```text
Q(K) = Br(K)[2],
```

and every Brauer class of order dividing two is the class of a quaternion algebra. The canonical
sign `TauCeti.BrauerGroup.quaternionSubgroupSignEquiv : Q(K) ≃* ℤˣ` is therefore the local
invariant read in `{±1}`: the class of the quaternion division algebra, the one class of sign
`-1`, has invariant `1/2`, and on a quaternion symbol `[(a, b)]` the invariant is `1/2` exactly
when the Hilbert symbol `(a, b)_K` is `-1`.

## Main results

* `TauCeti.BrauerGroup.natCard_twoTorsion`: `Br(K)[2]` has two elements.
* `TauCeti.BrauerGroup.invMap_brauerGroupEquivBr_eq_half_iff`: a class of `Br(K)[2]` has local
  invariant `1/2` exactly when it is nontrivial.
* `TauCeti.BrauerGroup.quaternionSubgroup_eq_twoTorsion`: `Q(K) = Br(K)[2]`.
* `TauCeti.BrauerGroup.invMap_brauerGroupEquivBr_quaternionClass_eq_half_iff`: the quaternion
  class `[(a, b)]` has local invariant `1/2` exactly when `(a, b)_K = -1`.

## References

* J.-P. Serre, *Local Fields*, Chapter XIII, §3 and Chapter XIV, §2.
* T. Y. Lam, *Introduction to Quadratic Forms over Fields*, Chapter VI, §2.
-/

public section

noncomputable section

namespace TauCeti.BrauerGroup

open ClassFieldTheory

variable (K : Type) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-- A Brauer class is `2`-torsion exactly when its local invariant is killed by `2`. -/
private theorem mem_twoTorsion_iff_two_nsmul_invMap (x : BrauerGroup K) :
    x ∈ twoTorsion K ↔ 2 • invMap K (brauerGroupEquivBr K (Additive.ofMul x)) = 0 := by
  rw [← map_nsmul, ← map_nsmul, AddEquiv.map_eq_zero_iff, AddEquiv.map_eq_zero_iff,
    ← ofMul_pow, ofMul_eq_zero, mem_twoTorsion]

/-- **The `2`-torsion of the Brauer group of a local field has two elements**, because the local
invariant identifies it with the `2`-torsion `(½ℤ)/ℤ` of `ℚ/ℤ`. -/
theorem natCard_twoTorsion : Nat.card (twoTorsion K) = 2 := by
  let e : BrauerGroup K ≃ AddCircle (1 : ℚ) :=
    Additive.ofMul.trans ((brauerGroupEquivBr K).trans (invMap K)).toEquiv
  rw [← AddCircle.natCard_torsionBy (1 : ℚ) two_pos]
  exact Nat.card_congr <| e.subtypeEquiv fun x ↦ by
    rw [mem_twoTorsion_iff_two_nsmul_invMap, AddSubgroup.torsionBy.nsmul_iff]
    simp [e]

/-- **The nontrivial `2`-torsion Brauer class has local invariant `1/2`.** A class of `Br(K)[2]`
has invariant `1/2` exactly when it is nontrivial; the trivial class has invariant `0`. -/
theorem invMap_brauerGroupEquivBr_eq_half_iff {x : BrauerGroup K} (hx : x ∈ twoTorsion K) :
    invMap K (brauerGroupEquivBr K (Additive.ofMul x)) = ((1 / 2 : ℚ) : AddCircle (1 : ℚ)) ↔
      x ≠ 1 := by
  have half : ((1 / 2 : ℚ) : AddCircle (1 : ℚ)) ≠ 0 := by
    intro h
    have := AddCircle.addOrderOf_period_div_of_ne_zero (1 : ℚ) (n := 2) two_pos
    rw [Nat.cast_ofNat, h, addOrderOf_zero] at this
    exact absurd this (by norm_num)
  have hzero : invMap K (brauerGroupEquivBr K (Additive.ofMul x)) = 0 ↔ x = 1 := by
    rw [AddEquiv.map_eq_zero_iff, AddEquiv.map_eq_zero_iff, ofMul_eq_zero]
  have h2 : (2 : ℤ) • invMap K (brauerGroupEquivBr K (Additive.ofMul x)) = 0 := by
    rw [two_zsmul, ← two_nsmul]
    exact (mem_twoTorsion_iff_two_nsmul_invMap K x).1 hx
  rcases AddCircle.eq_zero_or_eq_coe_period_div_two (1 : ℚ) two_ne_zero h2 with h | h
  · rw [ne_eq, ← hzero, h]
    exact iff_of_false half.symm (not_not.2 rfl)
  · rw [ne_eq, ← hzero, h]
    exact iff_of_true rfl half

variable [Invertible (2 : K)]

/-- **Every `2`-torsion Brauer class of a local field is a quaternion class**: the subgroup
`Q(K)` generated by the quaternion classes is `Br(K)[2]`. -/
theorem quaternionSubgroup_eq_twoTorsion : quaternionSubgroup K = twoTorsion K := by
  have hle : quaternionSubgroup K ≤ twoTorsion K := by
    rw [quaternionSubgroup, Subgroup.closure_le]
    rintro _ ⟨ab, rfl⟩
    exact mem_twoTorsion.2 (quaternionClass_sq ab.1 ab.2)
  have : Finite (twoTorsion K) :=
    Nat.finite_of_card_ne_zero (by rw [natCard_twoTorsion]; exact two_ne_zero)
  exact Subgroup.eq_of_le_of_card_ge hle (by rw [natCard_twoTorsion, natCard_quaternionSubgroup])

/-- **The quaternion division class has local invariant `1/2`.** The local invariant of the
quaternion class `[(a, b)]` is `1/2` exactly when the Hilbert symbol `(a, b)_K` is `-1`;
otherwise `ℍ[K, a, b]` is split and the invariant is `0`. -/
theorem invMap_brauerGroupEquivBr_quaternionClass_eq_half_iff (a b : Kˣ) :
    invMap K (brauerGroupEquivBr K (Additive.ofMul (quaternionClass a b))) =
        ((1 / 2 : ℚ) : AddCircle (1 : ℚ)) ↔
      hilbertSymbol a b = -1 := by
  rw [invMap_brauerGroupEquivBr_eq_half_iff K (mem_twoTorsion.2 (quaternionClass_sq a b)), ne_eq,
    quaternionClass_eq_one_iff, ← hilbertSymbol_eq_one_iff_nonempty_algEquiv_matrix]
  rcases Int.units_eq_one_or (hilbertSymbol a b) with h | h <;> simp [h]

end TauCeti.BrauerGroup
