/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Perm.TransitiveGroupLabel.Basic
public import TauCeti.GroupTheory.SpecificGroups.Dihedral.Basic
import TauCeti.GroupTheory.Perm.OrbitCount.FinRotate

/-!
# The dihedral reference permutation group in degree four

The reference subgroup `4T3` acts as the symmetry group of a square. Its four-cycle is the
rotation, and the transposition of opposite vertices is a reflection. We identify it with
`DihedralGroup 4` using the recognition theorem for groups generated by two involutions.
-/

public section

open Equiv Equiv.Perm

namespace TauCeti

private abbrev D4 : Subgroup (Perm (Fin 4)) := referenceSubgroup 4 ⟨2, by simp⟩

private def reflection : D4 := ⟨swap 0 2, by
  rw [D4, referenceSubgroup_four_two]
  exact Subgroup.subset_closure (Set.mem_insert_of_mem _ (Set.mem_singleton _))⟩

private def secondReflection : D4 := ⟨finRotate 4 * swap 0 2, by
  rw [D4, referenceSubgroup_four_two]
  exact (Subgroup.closure {finRotate 4, swap 0 2}).mul_mem
    (Subgroup.subset_closure (Set.mem_insert _ _))
    (Subgroup.subset_closure (Set.mem_insert_of_mem _ (Set.mem_singleton _)))⟩

/-- The reference subgroup `4T3` is the dihedral group of the square, of order eight. -/
noncomputable def referenceSubgroupFourTwoMulEquivDihedralGroup :
    referenceSubgroup 4 ⟨2, by simp⟩ ≃* DihedralGroup 4 := by
  let s : D4 := reflection
  let t : D4 := secondReflection
  have hs : s * s = 1 := by ext x; fin_cases x <;> decide
  have ht : t * t = 1 := by ext x; fin_cases x <;> decide
  have hs1 : s ≠ 1 := by decide
  have ht1 : t ≠ 1 := by decide
  have hn : orderOf (s * t) = 4 := by
    have hst : s * t = (⟨(finRotate 4)⁻¹, by
      rw [D4, referenceSubgroup_four_two]
      exact (Subgroup.closure {finRotate 4, swap 0 2}).inv_mem
        (Subgroup.subset_closure (Set.mem_insert _ _))⟩ : D4) := by
      ext x
      fin_cases x <;> decide
    rw [hst, Subgroup.orderOf_mk, orderOf_inv, orderOf_finRotate (by decide)]
  have hgen : Subgroup.closure ({s, t} : Set D4) = ⊤ := by
    let H : Subgroup D4 := Subgroup.closure {s, t}
    have hr : t * s = (⟨finRotate 4, by
        rw [D4, referenceSubgroup_four_two]
        exact Subgroup.subset_closure (Set.mem_insert _ _)⟩ : D4) := by
      ext x
      fin_cases x <;> decide
    have hle : D4 ≤ H.map D4.subtype := by
      have hD : D4 = Subgroup.closure ({finRotate 4, swap 0 2} : Set (Perm (Fin 4))) := by
        exact referenceSubgroup_four_two
      calc
        D4 = Subgroup.closure ({finRotate 4, swap 0 2} : Set (Perm (Fin 4))) := hD
        _ ≤ H.map D4.subtype := by
          apply (Subgroup.closure_le _).mpr
          intro x hx
          rcases Set.mem_insert_iff.mp hx with rfl | hx
          · exact ⟨t * s, H.mul_mem
              (Subgroup.subset_closure (Set.mem_insert_of_mem _ (Set.mem_singleton _)))
              (Subgroup.subset_closure (Set.mem_insert _ _)),
              congrArg Subtype.val hr⟩
          · have : x = swap 0 2 := Set.mem_singleton_iff.mp hx
            subst this
            exact ⟨s, Subgroup.subset_closure (Set.mem_insert _ _), rfl⟩
    apply eq_top_iff.mpr
    intro g _
    obtain ⟨h, hh, heq⟩ := hle g.property
    have : h = g := Subtype.ext heq
    exact this ▸ hh
  exact (dihedralGroupMulEquiv hs ht hs1 ht1 hn hgen).symm

/-- The standard dihedral reflection gives the diagonal swap in the reference action. -/
@[simp]
theorem referenceSubgroupFourTwoMulEquivDihedralGroup_symm_apply_sr_zero :
    referenceSubgroupFourTwoMulEquivDihedralGroup.symm (.sr 0) =
      (⟨swap 0 2, by
        rw [referenceSubgroup_four_two]
        exact Subgroup.subset_closure
          (Set.mem_insert_of_mem _ (Set.mem_singleton _))⟩ :
        referenceSubgroup 4 ⟨2, by simp⟩) := by
  simp [referenceSubgroupFourTwoMulEquivDihedralGroup, dihedralGroupMulEquiv_apply,
    dihedralHom_sr, reflection]

/-- The inverse standard dihedral rotation gives the four-cycle in the reference action. -/
@[simp]
theorem referenceSubgroupFourTwoMulEquivDihedralGroup_symm_apply_r_three :
    referenceSubgroupFourTwoMulEquivDihedralGroup.symm (.r (3 : ZMod 4)) =
      (⟨finRotate 4, by
        rw [referenceSubgroup_four_two]
        exact Subgroup.subset_closure (Set.mem_insert _ _)⟩ :
        referenceSubgroup 4 ⟨2, by simp⟩) := by
  simp only [referenceSubgroupFourTwoMulEquivDihedralGroup,
    MulEquiv.symm_symm, dihedralGroupMulEquiv_apply, dihedralHom_r]
  ext x
  fin_cases x <;> decide

/-- The concrete reflection maps to the standard dihedral reflection. -/
@[simp]
theorem referenceSubgroupFourTwoMulEquivDihedralGroup_apply_swap :
    referenceSubgroupFourTwoMulEquivDihedralGroup
      (⟨swap 0 2, by
        rw [referenceSubgroup_four_two]
        exact Subgroup.subset_closure
          (Set.mem_insert_of_mem _ (Set.mem_singleton _))⟩ :
        referenceSubgroup 4 ⟨2, by simp⟩) = .sr 0 := by
  apply referenceSubgroupFourTwoMulEquivDihedralGroup.symm.injective
  simp

/-- The concrete four-cycle maps to the inverse of the standard dihedral rotation. -/
@[simp]
theorem referenceSubgroupFourTwoMulEquivDihedralGroup_apply_finRotate :
    referenceSubgroupFourTwoMulEquivDihedralGroup
      (⟨finRotate 4, by
        rw [referenceSubgroup_four_two]
        exact Subgroup.subset_closure (Set.mem_insert _ _)⟩ :
        referenceSubgroup 4 ⟨2, by simp⟩) = .r (3 : ZMod 4) := by
  apply referenceSubgroupFourTwoMulEquivDihedralGroup.symm.injective
  simp

/-- Every permutation subgroup with label `4T3` is abstractly the dihedral group of the
square. The isomorphism depends on the conjugating permutation used to read the label. -/
theorem TransitiveGroupLabel.nonempty_mulEquiv_dihedralGroup_four_two
    {G : Subgroup (Perm (Fin 4))}
    (h : TransitiveGroupLabel (⟨2, by simp⟩ : TransitiveGroupIndex 4) G) :
    Nonempty (G ≃* DihedralGroup 4) := by
  obtain ⟨e⟩ := h.nonempty_mulEquiv_referenceSubgroup
  exact ⟨e.trans referenceSubgroupFourTwoMulEquivDihedralGroup⟩

end TauCeti
