/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.CommonKernel.Reduced
public import TauCeti.RingTheory.TensorProduct.Reduced
import TauCeti.Algebra.AlgebraicGroup.Smooth.GeometricallyReduced
import TauCeti.RingTheory.Ideal.Quotient.Nilpotent

/-!
# Smooth generated subgroups over perfect fields

A finite-type closed subgroup generated by reduced affine group schemes over a perfect
field is smooth over that field.

This concerns the generated subgroup over the original perfect field. Smoothness therefore
persists on the scalar extension of that same subgroup, independently of whether its
scalar extension is generated by the extended family.

## References

* W. C. Waterhouse, *Introduction to Affine Group Schemes*, §11.4.
* J. S. Milne, *Algebraic Groups* (2017), Proposition 1.26 and Corollary 1.27.

-/

public section

namespace TauCeti.CommHopfAlgCat

universe u v w

/-- A finite-type subgroup generated by reduced affine group schemes over a perfect
field is smooth. The generator algebras need not be finitely generated. -/
theorem smoothCommHopfAlgProperty_quotient_commonKernelHopfIdeal_of_perfectField
    {k : Type u} [Field k] [PerfectField k]
    {H : _root_.CommHopfAlgCat.{v} k}
    {ι : Type w} {K : ι → _root_.CommHopfAlgCat.{v} k}
    (f : ∀ i, H ⟶ K i) [∀ i, IsReduced (K i)]
    [Algebra.FiniteType k (quotient H (commonKernelHopfIdeal f))] :
    smoothCommHopfAlgProperty k (quotient H (commonKernelHopfIdeal f)) := by
  -- The reduced tensor-square criterion makes the nilradical a Hopf ideal. Maximality of
  -- the common-kernel defining ideal kills that nilradical, as supplied by the lemma below.
  -- Reduced algebras over perfect fields then remain reduced after every field extension.
  let : IsReduced (quotient H (commonKernelHopfIdeal f)) :=
    isReduced_quotient_commonKernelHopfIdeal_of_isReduced_tensorProduct f
  apply smoothCommHopfAlgProperty_of_geometricallyReduced
  rw [geometricallyReducedCommHopfAlgProperty_iff]
  intro L _ _
  infer_instance

end TauCeti.CommHopfAlgCat
