/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.Finite.Basic
public import Mathlib.FieldTheory.Galois.Basic
public import Mathlib.GroupTheory.Coset.Card
public import Mathlib.GroupTheory.SpecificGroups.Cyclic.Basic

/-!
# Artin–Schreier extensions

A root of `X ^ p - X - u` in characteristic `p` generates a Galois extension whose
automorphisms translate the root by elements of the prime field. If `u` is not of the
form `w ^ p - w` in the base field, the extension has degree `p` and its Galois group
is the additive group of `ZMod p`. This supplies the field-theoretic input for the
ramification theory of Artin–Schreier covers.

## References

* H. Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., GTM 254, Springer, 2009,
  Proposition 3.7.8.
* Mathlib: `Subfield.splits_bot` and `IsGalois.card_aut_eq_finrank`.
-/

public section

open Polynomial
open scoped IntermediateField

namespace TauCeti.ArtinSchreier

variable {K L : Type*} [Field K] [Field L] [Algebra K L]
variable {p : ℕ} [Fact p.Prime] [CharP K p]
variable {u : K} {y : L}

omit [CharP K p] in
private theorem monic_polynomial (u : K) : (X ^ p - X - C u : K[X]).Monic := by
  have h := monic_X_pow_sub (R := K) (p := X + C u) (n := p) (by
    rw [degree_X_add_C]
    exact_mod_cast (Fact.out : p.Prime).one_lt)
  convert h using 1; ring

omit [CharP K p] in
private theorem integral_root (hy : y ^ p - y = algebraMap K L u) : IsIntegral K y := by
  refine ⟨X ^ p - X - C u, monic_polynomial u, ?_⟩
  simp [hy]

/-- An Artin–Schreier polynomial splits in any field containing one of its roots. -/
theorem splits (hy : y ^ p - y = algebraMap K L u) :
    ((X ^ p - X - C u).map (algebraMap K L)).Splits := by
  have : CharP L p := charP_of_injective_algebraMap (algebraMap K L).injective p
  have h0 : (X ^ p - X : L[X]).Splits := by
    simpa using (Subfield.splits_bot L p).map (Subfield.subtype _)
  have he : (X ^ p - X : L[X]).comp (X - C y) =
      (X ^ p - X - C u).map (algebraMap K L) := by
    simp only [sub_comp, pow_comp, X_comp, Polynomial.map_sub, Polynomial.map_pow,
      Polynomial.map_X, Polynomial.map_C]
    rw [sub_pow_char, ← C_pow, ← hy, map_sub]
    ring
  rw [← he]
  exact h0.comp_X_sub_C y

/-- A field generated by an Artin–Schreier root is its polynomial's splitting field. -/
theorem isSplittingField (hy : y ^ p - y = algebraMap K L u) (hgen : K⟮y⟯ = ⊤) :
    IsSplittingField K L (X ^ p - X - C u) := by
  have hint := integral_root hy
  have htop : Algebra.adjoin K {y} = ⊤ := by
    rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic hint.isAlgebraic,
      hgen, IntermediateField.top_toSubalgebra]
  refine ⟨splits hy, top_unique ?_⟩
  rw [← htop]
  apply Algebra.adjoin_mono
  rw [Set.singleton_subset_iff, mem_rootSet_of_ne (monic_polynomial u).ne_zero]
  simp [hy]

/-- A generated Artin–Schreier extension is Galois, including the trivial case. -/
theorem isGalois (hy : y ^ p - y = algebraMap K L u) (hgen : K⟮y⟯ = ⊤) :
    IsGalois K L := by
  let := isSplittingField hy hgen
  apply IsGalois.of_separable_splitting_field (p := X ^ p - X - C u)
  simpa [sub_eq_add_neg] using
    separable_C_mul_X_pow_add_C_mul_X_add_C' p p (1 : K) (-1) (-u) dvd_rfl (by simp)

private theorem exists_translation (hy : y ^ p - y = algebraMap K L u) (σ : Gal(L/K)) :
    ∃ c : ZMod p, (ZMod.cast c : L) = σ y - y := by
  have : CharP L p := charP_of_injective_algebraMap (algebraMap K L).injective p
  have hp : (σ y - y) ^ p = σ y - y := by
    rw [sub_pow_char, ← map_pow]
    have hs := congrArg σ hy
    simp only [map_sub, AlgEquiv.commutes] at hs
    linear_combination hs - hy
  have hm := (Subfield.mem_bot_iff_pow_eq_self L p).mpr hp
  rw [← ZMod.fieldRange_castHom_eq_bot p] at hm
  exact hm

private noncomputable def translation (hy : y ^ p - y = algebraMap K L u)
    (σ : Gal(L/K)) : ZMod p := (exists_translation hy σ).choose

private theorem translation_spec (hy : y ^ p - y = algebraMap K L u) (σ : Gal(L/K)) :
    (ZMod.cast (translation hy σ) : L) = σ y - y :=
  (exists_translation hy σ).choose_spec

/-- The translation character sends an automorphism to the prime-field displacement of
the chosen Artin–Schreier root. The multiplicative type tag matches composition in `Gal`. -/
noncomputable def translationHom (hy : y ^ p - y = algebraMap K L u) :
    Gal(L/K) →* Multiplicative (ZMod p) where
  toFun σ := Multiplicative.ofAdd (translation hy σ)
  map_one' := by
    have : CharP L p := charP_of_injective_algebraMap (algebraMap K L).injective p
    apply congrArg Multiplicative.ofAdd
    apply (ZMod.castHom (m := p) dvd_rfl L).injective
    simp [translation_spec]
  map_mul' σ τ := by
    have : CharP L p := charP_of_injective_algebraMap (algebraMap K L).injective p
    apply congrArg Multiplicative.ofAdd
    apply (ZMod.castHom (m := p) dvd_rfl L).injective
    simp only [map_add, ZMod.castHom_apply, toAdd_ofAdd, translation_spec]
    have hfix : σ ((ZMod.cast (translation hy τ) : L)) =
        (ZMod.cast (translation hy τ) : L) := by
      obtain ⟨n, hn⟩ := ZMod.intCast_surjective (translation hy τ)
      rw [← hn]
      simp
    rw [translation_spec] at hfix
    simp only [AlgEquiv.mul_apply, map_sub] at hfix ⊢
    linear_combination hfix

/-- The translation character computes the action on the chosen root. -/
theorem aut_apply_eq_add_translationHom (hy : y ^ p - y = algebraMap K L u)
    (σ : Gal(L/K)) :
    σ y = y + (ZMod.cast (translationHom hy σ).toAdd : L) := by
  simp [translationHom, translation_spec]

/-- An automorphism of a generated Artin–Schreier extension is determined by its
translation of the generator. -/
theorem translationHom_injective (hy : y ^ p - y = algebraMap K L u)
    (hgen : K⟮y⟯ = ⊤) : Function.Injective (translationHom hy) := by
  intro σ τ h
  apply AlgEquiv.coe_toAlgHom_injective
  apply (PowerBasis.ofAdjoinSimpleEqTop (integral_root hy) hgen).algHom_ext
  simp only [PowerBasis.ofAdjoinSimpleEqTop_gen, AlgEquiv.coe_toAlgHom]
  rw [aut_apply_eq_add_translationHom hy σ, aut_apply_eq_add_translationHom hy τ, h]

/-- Every generated Artin–Schreier extension has a cyclic Galois group. -/
theorem isCyclic (hy : y ^ p - y = algebraMap K L u) (hgen : K⟮y⟯ = ⊤) :
    IsCyclic Gal(L/K) :=
  isCyclic_of_injective (translationHom hy) (translationHom_injective hy hgen)

/-- A nontrivial Artin–Schreier class gives an extension of degree exactly `p`. -/
theorem finrank_eq (hy : y ^ p - y = algebraMap K L u) (hgen : K⟮y⟯ = ⊤)
    (hu : ∀ w : K, w ^ p - w ≠ u) : Module.finrank K L = p := by
  let := isSplittingField hy hgen
  have := IsSplittingField.finiteDimensional L (X ^ p - X - C u)
  have := isGalois hy hgen
  have hd := Subgroup.card_dvd_of_injective (translationHom hy)
    (translationHom_injective hy hgen)
  have hc : Nat.card (Multiplicative (ZMod p)) = p := by
    rw [Nat.card_congr Multiplicative.toAdd, Nat.card_zmod]
  rw [hc, IsGalois.card_aut_eq_finrank] at hd
  rcases (Fact.out : p.Prime).eq_one_or_self_of_dvd _ hd with h | h
  · obtain ⟨w, hw⟩ := (Algebra.finrank_eq_one_iff_bijective_algebraMap.mp h).2 y
    apply False.elim
    apply hu w
    apply (algebraMap K L).injective
    simpa [hw] using hy
  · exact h

/-- For a nontrivial Artin–Schreier class, every prime-field translation occurs as a
unique automorphism. -/
noncomputable def autEquivZmod (hy : y ^ p - y = algebraMap K L u) (hgen : K⟮y⟯ = ⊤)
    (hu : ∀ w : K, w ^ p - w ≠ u) : Gal(L/K) ≃* Multiplicative (ZMod p) := by
  let := isSplittingField hy hgen
  have := IsSplittingField.finiteDimensional L (X ^ p - X - C u)
  have := isGalois hy hgen
  exact MulEquiv.ofBijective (translationHom hy)
    ((Nat.bijective_iff_injective_and_card _).mpr ⟨translationHom_injective hy hgen, by
      rw [IsGalois.card_aut_eq_finrank, finrank_eq hy hgen hu,
        Nat.card_congr Multiplicative.toAdd, Nat.card_zmod]⟩)

/-- The Galois-group equivalence is the translation character of the chosen root. -/
@[simp]
theorem autEquivZmod_apply (hy : y ^ p - y = algebraMap K L u) (hgen : K⟮y⟯ = ⊤)
    (hu : ∀ w : K, w ^ p - w ≠ u) (σ : Gal(L/K)) :
    autEquivZmod hy hgen hu σ = translationHom hy σ := (rfl)

/-- The inverse Galois-group equivalence translates the generator by its argument. -/
@[simp]
theorem autEquivZmod_symm_apply (hy : y ^ p - y = algebraMap K L u) (hgen : K⟮y⟯ = ⊤)
    (hu : ∀ w : K, w ^ p - w ≠ u) (c : Multiplicative (ZMod p)) :
    (autEquivZmod hy hgen hu).symm c y = y + (ZMod.cast c.toAdd : L) := by
  rw [aut_apply_eq_add_translationHom hy, ← autEquivZmod_apply hy hgen hu,
    MulEquiv.apply_symm_apply]

end TauCeti.ArtinSchreier
