/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.FreeAlgebra
public import Mathlib.Algebra.Algebra.Opposite
public import Mathlib.RingTheory.Noetherian.Basic

/-!
# Finite algebras of operators detected by a pairing

Suppose a module embeds into functionals on a finite module, and a family of operators is
adjoint to integral operators on that finite module. Then the algebra generated by the first
family is finite over the base ring. This transfers an integral structure on cycles to an
algebra of operators on functions, without choosing a lattice in the function space.

The symbol-side evaluation takes values in the opposite endomorphism ring. Precomposition
reverses products, so this convention extends generator equivariance to the free algebra
without any commutativity assumption on the operators.
-/

public section

open MulOpposite

namespace TauCeti

variable {R K M V ι : Type*} [CommRing R] [CommRing K] [Algebra R K]
  [AddCommGroup M] [Module R M] [AddCommGroup V] [Module K V]
  [Module R V] [IsScalarTower R K V]

/-- An adjointness identity on generators extends to the free algebra, with the adjoint
operators evaluated in the opposite endomorphism ring. -/
theorem pairing_freeAlgebra_lift
    (P : V →ₗ[K] M →ₗ[R] K) (t : ι → Module.End K V) (u : ι → Module.End R M)
    (h : ∀ i v x, P (t i v) x = P v (u i x)) (a : FreeAlgebra R ι) (v : V) (x : M) :
    P (FreeAlgebra.lift R t a v) x =
      P v ((FreeAlgebra.lift R (fun i ↦ op (u i)) a).unop x) := by
  induction a using FreeAlgebra.induction generalizing v x with
  | grade0 r =>
      simp [Algebra.algebraMap_eq_smul_one, map_smul]
  | grade1 i => simpa only [FreeAlgebra.lift_ι_apply, unop_op] using h i v x
  | mul a b ha hb =>
      simp only [map_mul, Module.End.mul_apply, ha, hb, unop_mul]
  | add a b ha hb =>
      simp only [map_add, LinearMap.add_apply, unop_add, ha, hb]

/-- If an injective pairing detects a family of operators by adjoint operators on a finite
module over a Noetherian ring, its generated algebra is finite over that ring. The operators
need not commute, and the module carrying the first family need not be finite. -/
theorem finite_adjoin_of_injective_pairing [IsNoetherianRing R] [Module.Finite R M]
    (P : V →ₗ[K] M →ₗ[R] K) (hP : Function.Injective P)
    (t : ι → Module.End K V) (u : ι → Module.End R M)
    (h : ∀ i v x, P (t i v) x = P v (u i x)) :
    Module.Finite R (Algebra.adjoin R (Set.range t)) := by
  let s := (FreeAlgebra.lift R t).toLinearMap
  let m := (FreeAlgebra.lift R (fun i ↦ op (u i))).toLinearMap
  let e := s.prod m
  -- The joint image remembers both evaluations. Its second projection is injective because
  -- vanishing of the adjoint evaluation forces vanishing of the first evaluation.
  let q := (LinearMap.snd R (Module.End K V) (Module.End R M)ᵐᵒᵖ).comp e.range.subtype
  have hq : Function.Injective q := by
    intro y z hyz
    obtain ⟨a, ha⟩ := y.property
    obtain ⟨b, hb⟩ := z.property
    have hab : m a = m b := by
      simpa only [q, LinearMap.comp_apply, Submodule.subtype_apply, ← ha, ← hb,
        e, LinearMap.prod_apply, Function.prod_apply, LinearMap.snd_apply] using hyz
    apply Subtype.ext
    rw [← ha, ← hb]
    apply Prod.ext
    · ext v
      apply hP
      ext x
      simpa only [e, LinearMap.prod_apply, Function.prod_apply, s, m, AlgHom.toLinearMap_apply,
        pairing_freeAlgebra_lift P t u h] using
        congrArg (fun z : (Module.End R M)ᵐᵒᵖ ↦ P v (z.unop x)) hab
    · exact hab
  let : IsNoetherian R (Module.End R M) := inferInstance
  let : IsNoetherian R (Module.End R M)ᵐᵒᵖ :=
    isNoetherian_of_injective (opLinearEquiv R (M := Module.End R M)).symm.toLinearMap
      (opLinearEquiv R (M := Module.End R M)).symm.injective
  let : Module.Finite R e.range := Module.Finite.of_injective q hq
  let p : e.range →ₗ[R] s.range :=
    (LinearMap.fst R (Module.End K V) (Module.End R M)ᵐᵒᵖ).comp e.range.subtype |>.codRestrict
      s.range (by rintro ⟨_, a, rfl⟩; exact ⟨a, rfl⟩)
  have hp : Function.Surjective p := by
    rintro ⟨_, a, rfl⟩
    exact ⟨⟨e a, ⟨a, rfl⟩⟩, rfl⟩
  have : Module.Finite R s.range := Module.Finite.of_surjective p hp
  rw [Algebra.adjoin_range_eq_range_freeAlgebra_lift]
  let j : s.range →ₗ[R] (FreeAlgebra.lift R t).range := {
    toFun y := ⟨y.1, y.2⟩
    map_add' _ _ := rfl
    map_smul' _ _ := rfl }
  exact Module.Finite.of_surjective j (by
    rintro ⟨y, hy⟩
    exact ⟨⟨y, hy⟩, rfl⟩)

end TauCeti
