/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.LocalField.Different.Monogenic
public import TauCeti.NumberTheory.LocalField.Eisenstein.PowerBasis
public import TauCeti.NumberTheory.LocalField.NatCastValuation
import TauCeti.RingTheory.Polynomial.Eisenstein.Minpoly

/-!
# The different of an Eisenstein extension

For an extension whose integer ring is generated by a root of an Eisenstein polynomial,
the different exponent is the least valuation of the terms of the polynomial derivative.
The powers of the root have distinct valuation residues, so these terms cannot cancel.

## Main results

* `TauCeti.natCast_differentExponent_eq_iInf_of_eisenstein_adjoin_eq_top` gives the exact
  derivative-term formula for the different exponent.
* The upper-bound theorem
  `differentExponent_le_ramificationIndex_sub_one_add_natCastValuation_of_eisenstein_adjoin_eq_top`
  proves `d(L/K) ≤ e - 1 + v_L(e)`, where `e = e(L/K)` and `v_L` is the normalized valuation,
  provided `(e : L) ≠ 0`.

## References

* J.-P. Serre, *Local Fields*, Chapter III, §6, Proposition 13.
-/

public section
noncomputable section

open ValuativeRel IsLocalRing Polynomial IsDiscreteValuationRing

namespace TauCeti

variable {K L : Type*} [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [Field L] [ValuativeRel L] [TopologicalSpace L]
  [IsNonarchimedeanLocalField L] [Algebra K L] [ValuativeExtension K L]
  [Module.Finite K L] [Algebra.IsSeparable K L]

/-- For an Eisenstein integral generator, the different exponent is the least valuation of the
terms of its polynomial derivative. -/
theorem natCast_differentExponent_eq_iInf_of_eisenstein_adjoin_eq_top
    (f : Polynomial 𝒪[K])
    (hf : f.IsEisensteinAt 𝓂[K]) (ξ : 𝒪[L])
    (hroot : (f.map (algebraMap 𝒪[K] 𝒪[L])).IsRoot ξ)
    (hgen : Algebra.adjoin 𝒪[K] {ξ} = ⊤) :
    (differentExponent K L : ℕ∞) =
      ⨅ i : Fin f.natDegree,
        ramificationIndex K L • IsDiscreteValuationRing.addVal 𝒪[K]
          (f.coeff (i + 1) * (i + 1)) + (i : ℕ) := by
  have he : ramificationIndex K L = f.natDegree :=
    ramificationIndex_eq_natDegree_of_eisenstein_adjoin_eq_top f hf ξ hroot hgen
  have hdeg : 0 < f.natDegree := he ▸ ramificationIndex_pos (K := K) (L := L)
  have hassoc : Associated (minpoly 𝒪[K] ξ) f :=
    associated_minpoly_of_eisenstein_isRoot ξ f hf hroot
  have hscale : f = Polynomial.C f.leadingCoeff * minpoly 𝒪[K] ξ :=
    Polynomial.eq_leadingCoeff_mul_of_monic_of_dvd_of_natDegree_le
      (minpoly.monic (IsIntegral.of_finite 𝒪[K] ξ)) hassoc.dvd
      (Polynomial.natDegree_le_natDegree
        (Polynomial.degree_eq_degree_of_associated hassoc).symm.le)
  have hlc : IsUnit f.leadingCoeff := notMem_maximalIdeal.mp hf.leading
  have hval := natCast_differentExponent_eq_addVal_aeval_derivative_minpoly K L hgen
  have hval' : (differentExponent K L : ℕ∞) =
      addVal 𝒪[L] (aeval ξ (derivative f)) := by
    calc
      (differentExponent K L : ℕ∞) =
          addVal 𝒪[L] (aeval ξ (derivative (minpoly 𝒪[K] ξ))) := hval
      _ = addVal 𝒪[L] (aeval ξ (derivative f)) := by
        rw [hscale, Polynomial.derivative_C_mul, map_mul, Polynomial.aeval_C,
          addVal_mul, (addVal_eq_zero_iff).mpr (hlc.map (algebraMap 𝒪[K] 𝒪[L])), zero_add]
  let c : Fin f.natDegree → 𝒪[K] := fun i => f.coeff (i + 1) * (i + 1)
  have hsum : aeval ξ (derivative f) =
      ∑ i : Fin f.natDegree, algebraMap 𝒪[K] 𝒪[L] (c i) * ξ ^ (i : ℕ) := by
    rw [Polynomial.aeval_eq_sum_range'
      (Polynomial.natDegree_derivative_lt (Nat.ne_of_gt hdeg)) ξ]
    simp only [← Fin.sum_univ_eq_sum_range, Polynomial.coeff_derivative,
      Algebra.smul_def, c]
  rw [hval', hsum, addVal_sum_eisenstein_powerBasis f hf ξ hroot hgen c]

/-- For an extension whose integer ring is generated by an Eisenstein root, the different
exponent is at most `e - 1 + v_L(e)`, provided `e` is nonzero in the extension field. -/
theorem
    differentExponent_le_ramificationIndex_sub_one_add_natCastValuation_of_eisenstein_adjoin_eq_top
    (f : Polynomial 𝒪[K])
    (hf : f.IsEisensteinAt 𝓂[K]) (ξ : 𝒪[L])
    (hroot : (f.map (algebraMap 𝒪[K] 𝒪[L])).IsRoot ξ)
    (hgen : Algebra.adjoin 𝒪[K] {ξ} = ⊤)
    (he0 : (ramificationIndex K L : L) ≠ 0) :
    differentExponent K L ≤ ramificationIndex K L - 1 +
      natCastValuation L (ramificationIndex K L) he0 := by
  have hformula := natCast_differentExponent_eq_iInf_of_eisenstein_adjoin_eq_top
    f hf ξ hroot hgen
  let c : Fin f.natDegree → 𝒪[K] := fun i => f.coeff (i + 1) * (i + 1)
  have he : ramificationIndex K L = f.natDegree :=
    ramificationIndex_eq_natDegree_of_eisenstein_adjoin_eq_top f hf ξ hroot hgen
  have hdeg : 0 < f.natDegree := he ▸ ramificationIndex_pos (K := K) (L := L)
  let j : Fin f.natDegree := ⟨f.natDegree - 1, by omega⟩
  have hc : c j = f.leadingCoeff * (f.natDegree : 𝒪[K]) := by
    have hsub : f.natDegree - 1 + 1 = f.natDegree := by omega
    simp only [c, j, hsub, Polynomial.coeff_natDegree]
    exact congrArg (f.leadingCoeff * ·)
      (by exact_mod_cast congrArg (fun n : ℕ => (n : 𝒪[K])) hsub)
  have hlc : addVal 𝒪[K] f.leadingCoeff = 0 :=
    (addVal_eq_zero_iff).mpr (notMem_maximalIdeal.mp hf.leading)
  have h : (differentExponent K L : ℕ∞) ≤
      (ramificationIndex K L : ℕ) - 1 +
        ramificationIndex K L • addVal 𝒪[K] (ramificationIndex K L : 𝒪[K]) := by
    calc
      (differentExponent K L : ℕ∞) ≤
          ramificationIndex K L • addVal 𝒪[K] (c j) + (j : ℕ) := by
        rw [hformula]
        exact iInf_le _ j
      _ = (ramificationIndex K L : ℕ) - 1 +
          ramificationIndex K L • addVal 𝒪[K] (ramificationIndex K L : 𝒪[K]) := by
        have hj : (j : ℕ) = ramificationIndex K L - 1 := by simp [j, he]
        have hcast : (f.natDegree : 𝒪[K]) = (ramificationIndex K L : 𝒪[K]) :=
          congrArg (fun n : ℕ => (n : 𝒪[K])) he.symm
        rw [hc, addVal_mul, hlc, zero_add, hcast, hj, add_comm]
        norm_cast
  have hv : ramificationIndex K L •
      addVal 𝒪[K] (ramificationIndex K L : 𝒪[K]) =
        (natCastValuation L (ramificationIndex K L) he0 : ℕ∞) := by
    rw [← addVal_algebraMap (K := K) (L := L), map_natCast,
      TauCeti.IsDiscreteValuationRing.addVal_natCast L (ramificationIndex K L) he0]
  rw [hv] at h
  exact_mod_cast h

end TauCeti

end
