/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.LocalField.Different.Basic
import TauCeti.RingTheory.DedekindDomain.Different.Monogenic
import TauCeti.RingTheory.DiscreteValuationRing.Basic

/-!
# The different exponent of a monogenic local extension

The different exponent is the additive valuation of the derivative of a generator's minimal
polynomial when the integer ring of the extension is generated by that element.

## Main result

* `TauCeti.natCast_differentExponent_eq_addVal_aeval_derivative_minpoly` gives this valuation
  formula.
-/

public section
noncomputable section

open ValuativeRel IsLocalRing

namespace TauCeti

variable (K L : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [Field L] [ValuativeRel L] [TopologicalSpace L]
  [IsNonarchimedeanLocalField L] [Algebra K L] [ValuativeExtension K L]
  [Algebra.IsSeparable K L]

/-- For an integral generator `x`, the different exponent is the additive valuation of the
derivative of its minimal polynomial at `x`. -/
theorem natCast_differentExponent_eq_addVal_aeval_derivative_minpoly [Module.Finite K L]
    {x : 𝒪[L]}
    (hx : Algebra.adjoin 𝒪[K] {x} = ⊤) :
    (differentExponent K L : ℕ∞) =
      IsDiscreteValuationRing.addVal 𝒪[L]
        (Polynomial.aeval x (Polynomial.derivative (minpoly 𝒪[K] x))) := by
  have hdifferent := differentIdeal_eq_span_aeval_derivative_minpoly 𝒪[K] K L 𝒪[L] x hx
  have hderiv0 : Polynomial.aeval x (Polynomial.derivative (minpoly 𝒪[K] x)) ≠ 0 := by
    intro h
    exact differentIdeal_ne_bot (A := 𝒪[K]) (B := 𝒪[L])
      (by rw [hdifferent, h, Ideal.span_singleton_eq_bot])
  rw [differentExponent_def, hdifferent,
    ← TauCeti.IsDiscreteValuationRing.addVal_eq_multiplicity_span_singleton hderiv0]

end TauCeti
