/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.WorkedExamples.GaussianRationals.Invariants
public import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import Mathlib.RingTheory.Polynomial.Cyclotomic.Roots

/-!
# The units of `ℚ(i)`

For `K` generated over `ℚ` by an algebraic integer `θ` with `minpoly ℤ θ = X² + 1`: the
signature `(0, 1)` gives unit rank `0 + 1 − 1 = 0`, so every unit is a root of unity. The
generator `θ` is a primitive fourth root of unity, and it generates `K`, so `K` is a fourth
cyclotomic extension of `ℚ`; Mathlib's count of the roots of unity in a cyclotomic field then
gives torsion of order `4`: the units of `ℤ[i]` are `±1` and `±θ`.

## Main results

* `TauCeti.NumberField.GaussianRationals.isPrimitiveRoot_four`: `θ` is a primitive fourth root
  of unity.
* `TauCeti.NumberField.GaussianRationals.isCyclotomicExtension_four`:
  `IsCyclotomicExtension {4} ℚ K`.
* `TauCeti.NumberField.GaussianRationals.units_rank_eq_zero`, `torsionOrder_eq_four`: the unit
  group is finite, of order `4`.
-/

public section

open Polynomial NumberField NumberField.InfinitePlace NumberField.Units
open scoped NumberField

namespace TauCeti.NumberField.GaussianRationals

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K}

/-- `θ` is a primitive fourth root of unity: it is a root of `Φ₄ = X² + 1`. -/
theorem isPrimitiveRoot_four (hmin : minpoly ℤ θ = X ^ 2 + 1) : IsPrimitiveRoot (θ : K) 4 := by
  have hsq : (θ : K) ^ 2 = -1 := by
    have h := congrArg (algebraMap (𝓞 K) K) (sq_eq_neg_one hmin)
    simpa using h
  -- Mathlib evaluates `Φ_{p^(k+1)}` as a geometric sum; `Φ₄` is the case `p = 2`, `k = 1`, where
  -- the sum is `1 + X²`.
  have hfour : (4 : ℕ) = 2 ^ (1 + 1) := by norm_num
  rw [← isRoot_cyclotomic_iff_charZero (by norm_num), hfour,
    cyclotomic_prime_pow_eq_geom_sum Nat.prime_two]
  simp [Finset.sum_range_succ, hsq]

/-- `ℚ(i)` is the fourth cyclotomic field: it is generated by a primitive fourth root of
unity. -/
theorem isCyclotomicExtension_four (hmin : minpoly ℤ θ = X ^ 2 + 1)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) : IsCyclotomicExtension {4} ℚ K := by
  rw [IsCyclotomicExtension.iff_singleton]
  refine ⟨⟨θ, isPrimitiveRoot_four hmin⟩, fun x ↦ ?_⟩
  have h : Algebra.adjoin ℚ {(θ : K)} ≤ Algebra.adjoin ℚ {b : K | b ^ 4 = 1} :=
    Algebra.adjoin_mono (Set.singleton_subset_iff.mpr (isPrimitiveRoot_four hmin).pow_eq_one)
  rw [hgen] at h
  exact h Algebra.mem_top

/-- The unit group of `ℚ(i)` has rank `r₁ + r₂ − 1 = 0`. -/
theorem units_rank_eq_zero (hmin : minpoly ℤ θ = X ^ 2 + 1)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) : Units.rank K = 0 := by
  rw [Units.rank, card_eq_nrRealPlaces_add_nrComplexPlaces, nrRealPlaces_eq_zero hmin,
    nrComplexPlaces_eq_one hmin hgen]

/-- The roots of unity in `ℚ(i)` are the fourth roots of unity: the torsion subgroup of the
unit group has order `4`. -/
theorem torsionOrder_eq_four (hmin : minpoly ℤ θ = X ^ 2 + 1)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) : torsionOrder K = 4 := by
  have := isCyclotomicExtension_four hmin hgen
  rw [IsCyclotomicExtension.Rat.torsionOrder_eq (n := 4)]
  decide

end TauCeti.NumberField.GaussianRationals
