/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.Profinite.Free.Graded

/-!
# Infinitesimal basis modifications of a free pro-p relator

Let `F = freeProP p X`, with `X` finite and linearly ordered, and let
`rbar : gr_1(F)`. The standard basis of `gr_1(F)` writes `rbar` uniquely as

`sum_i c_i pi(x_i) + sum_{i < j} a_ij [x_i, x_j]`.

This file packages the coefficients `c_i` and the alternating coefficient matrix `a_ij`, its
contraction `partial_i rbar` with the `i`-th generator, and Labute's infinitesimal
basis-modification operator

`delta_{k+1}(w) = sum_i [w_i, partial_i rbar] + sum_i c_i pi(w_i)`.

Here `w_i` has degree `k`, so both summands have degree `k + 1`. In positive degree the operator
is linear. In degree zero at `p = 2` it need not be linear; its polarization is the diagonal
bracket form `sum_i c_i [v_i, w_i]`. The subspace generated by the iterated powers of
generators with `c_i = 0` is the dyadic tail used alongside the image of `delta` in
successive-approximation arguments.

The signs in `relatorBracketCoeff` make the coefficient matrix alternating. Thus
`relatorPartial rbar i = sum_j a_ij xbar_j`; this is independent of the chosen order even though
the standard basis stores only the entries with `i < j`.

## Main definitions

* `TauCeti.freeProP.relatorPowCoeff`: the coefficient `c_i` of `pi(x_i)`.
* `TauCeti.freeProP.relatorBracketCoeff`: the alternating coefficient `a_ij`.
* `TauCeti.freeProP.relatorPartial`: the contraction `partial_i rbar` in `gr_0(F)`.
* `TauCeti.freeProP.basisModification`: the map `delta_{k+1}`.
* `TauCeti.freeProP.basisModificationLinear`: its linear form for `k >= 1`.
* `TauCeti.freeProP.dyadicTail`: the tail subspace `T_j` for `p = 2`.

## References

* J. Labute, *Classification of Demushkin groups*, Canadian J. Math. 19 (1967), Proposition 5.
-/

public section

namespace TauCeti

open Submodule

universe u

namespace freeProP

variable {p : ℕ} [Fact p.Prime] {X : Type u} [Fintype X] [LinearOrder X]

/-- The coefficient `c_i` of `pi(x_i)` in the standard-basis expansion of a class in
`gr_1(freeProP p X)`. -/
noncomputable def relatorPowCoeff (rbar : gradedPiece p (freeProP p X) 1) (i : X) : ZMod p :=
  (degreeOneBasis p X).repr rbar (Sum.inl i)

/-- The power coefficient is the coordinate at the power-class part of the standard basis. -/
@[simp]
theorem relatorPowCoeff_def (rbar : gradedPiece p (freeProP p X) 1) (i : X) :
    relatorPowCoeff rbar i = (degreeOneBasis p X).repr rbar (Sum.inl i) :=
  (rfl)

/-- The alternating coefficient `a_ij` of `[x_i, x_j]` in a degree-one relator class. The
standard basis records the coefficient for `i < j`; reversing the indices negates it, and the
diagonal coefficient is zero. -/
noncomputable def relatorBracketCoeff (rbar : gradedPiece p (freeProP p X) 1) (i j : X) :
    ZMod p :=
  if hij : i < j then (degreeOneBasis p X).repr rbar (Sum.inr ⟨(i, j), hij⟩)
  else if hji : j < i then -(degreeOneBasis p X).repr rbar (Sum.inr ⟨(j, i), hji⟩)
  else 0

@[simp]
theorem relatorBracketCoeff_of_lt (rbar : gradedPiece p (freeProP p X) 1) {i j : X}
    (hij : i < j) :
    relatorBracketCoeff rbar i j = (degreeOneBasis p X).repr rbar (Sum.inr ⟨(i, j), hij⟩) := by
  simp [relatorBracketCoeff, hij]

@[simp]
theorem relatorBracketCoeff_of_gt (rbar : gradedPiece p (freeProP p X) 1) {i j : X}
    (hji : j < i) :
    relatorBracketCoeff rbar i j =
      -(degreeOneBasis p X).repr rbar (Sum.inr ⟨(j, i), hji⟩) := by
  simp [relatorBracketCoeff, hji, hji.not_gt]

@[simp]
theorem relatorBracketCoeff_self (rbar : gradedPiece p (freeProP p X) 1) (i : X) :
    relatorBracketCoeff rbar i i = 0 := by
  simp [relatorBracketCoeff]

/-- The commutator coefficients form an alternating matrix. -/
theorem relatorBracketCoeff_swap (rbar : gradedPiece p (freeProP p X) 1) (i j : X) :
    relatorBracketCoeff rbar j i = -relatorBracketCoeff rbar i j := by
  rcases lt_trichotomy i j with hij | rfl | hji
  · simp [relatorBracketCoeff, hij, hij.not_gt]
  · simp
  · simp [relatorBracketCoeff, hji, hji.not_gt]

/-- The power and commutator coefficients recover the degree-one relator class. -/
theorem sum_relatorCoeff (rbar : gradedPiece p (freeProP p X) 1) :
    (∑ i, relatorPowCoeff rbar i •
        gradedPow p (freeProP p X) 0 (gradedMkZero p (freeProP p X) (of i))) +
      ∑ ij : {ij : X × X // ij.1 < ij.2},
        relatorBracketCoeff rbar ij.1.1 ij.1.2 •
          gradedBracket p (freeProP p X) 0 0
            (gradedMkZero p (freeProP p X) (of ij.1.1))
            (gradedMkZero p (freeProP p X) (of ij.1.2)) = rbar := by
  have hcoeff (ij : {ij : X × X // ij.1 < ij.2}) :
      relatorBracketCoeff rbar ij.1.1 ij.1.2 =
        (degreeOneBasis p X).repr rbar (Sum.inr ij) := by
    simpa only using relatorBracketCoeff_of_lt rbar ij.2
  simp_rw [hcoeff]
  have h := (degreeOneBasis p X).sum_repr rbar
  rw [Fintype.sum_sum_type] at h
  simpa only [relatorPowCoeff, degreeOneBasis_apply,
    degreeOneFamily_inl, degreeOneFamily_inr] using h

/-- The contraction `partial_i rbar` of the commutator part of a degree-one relator class with
the `i`-th generator. If the commutator part is `sum_{i < j} a_ij [x_i, x_j]`, this is
`sum_j a_ij xbar_j`. -/
noncomputable def relatorPartial (rbar : gradedPiece p (freeProP p X) 1) (i : X) :
    gradedPiece p (freeProP p X) 0 :=
  ∑ j, relatorBracketCoeff rbar i j • gradedMkZero p (freeProP p X) (of j)

/-- The contraction of a relator class is the indicated sum of its alternating commutator
coefficients. -/
@[simp]
theorem relatorPartial_def (rbar : gradedPiece p (freeProP p X) 1) (i : X) :
    relatorPartial rbar i =
      ∑ j, relatorBracketCoeff rbar i j • gradedMkZero p (freeProP p X) (of j) :=
  (rfl)

/-- **Labute's infinitesimal basis-modification map.** For `w_i` of degree `k`, this is
`delta_{k+1}(w) = sum_i [w_i, partial_i rbar] + sum_i c_i pi(w_i)` in degree `k + 1`.

At `k = 0` and `p = 2` this need not be linear; its polarization is
`TauCeti.freeProP.basisModification_add_zero_dyadic`. -/
noncomputable def basisModification (rbar : gradedPiece p (freeProP p X) 1) (k : ℕ)
    (w : X → gradedPiece p (freeProP p X) k) :
    gradedPiece p (freeProP p X) (k + 1) :=
  ∑ i, gradedBracket p (freeProP p X) k 0 (w i) (relatorPartial rbar i) +
    ∑ i, relatorPowCoeff rbar i • gradedPow p (freeProP p X) k (w i)

/-- The defining formula for the basis-modification map. -/
-- Not `@[simp]`: unfolding every `delta_{k+1}` into its two sums makes `simp` prove
-- `basisModification_zero`, so `simpNF` reports that simp lemma as redundant.
theorem basisModification_eq_sum (rbar : gradedPiece p (freeProP p X) 1) (k : ℕ)
    (w : X → gradedPiece p (freeProP p X) k) :
    basisModification rbar k w =
      ∑ i, gradedBracket p (freeProP p X) k 0 (w i) (relatorPartial rbar i) +
        ∑ i, relatorPowCoeff rbar i • gradedPow p (freeProP p X) k (w i) :=
  (rfl)

@[simp]
theorem basisModification_zero (rbar : gradedPiece p (freeProP p X) 1) (k : ℕ) :
    basisModification rbar k 0 = 0 := by
  simp [basisModification]

/-- The basis-modification map is additive when its inputs have positive degree. -/
theorem basisModification_add_of_one_le (rbar : gradedPiece p (freeProP p X) 1) {k : ℕ}
    (hk : 1 ≤ k) (v w : X → gradedPiece p (freeProP p X) k) :
    basisModification rbar k (v + w) =
      basisModification rbar k v + basisModification rbar k w := by
  simp only [basisModification, Pi.add_apply, map_add, AddMonoidHom.add_apply,
    gradedPow_add_of_one_le hk, smul_add, Finset.sum_add_distrib]
  abel

/-- The basis-modification map commutes with scalars when its inputs have positive degree. -/
theorem basisModification_smul_of_one_le (rbar : gradedPiece p (freeProP p X) 1) {k : ℕ}
    (hk : 1 ≤ k) (c : ZMod p) (w : X → gradedPiece p (freeProP p X) k) :
    basisModification rbar k (c • w) = c • basisModification rbar k w := by
  simp only [basisModification, Pi.smul_apply, ZMod.map_smul, gradedPow_smul_of_one_le hk,
    smul_smul, Finset.smul_sum, smul_add, mul_comm, AddMonoidHom.smul_apply]

/-- **The linear basis-modification map `delta_{k+1}` for `k >= 1`.** -/
noncomputable def basisModificationLinear (rbar : gradedPiece p (freeProP p X) 1) (k : ℕ)
    (hk : 1 ≤ k) :
    (X → gradedPiece p (freeProP p X) k) →ₗ[ZMod p]
      gradedPiece p (freeProP p X) (k + 1) where
  toFun := basisModification rbar k
  map_add' := basisModification_add_of_one_le rbar hk
  map_smul' := basisModification_smul_of_one_le rbar hk

@[simp]
theorem basisModificationLinear_apply (rbar : gradedPiece p (freeProP p X) 1) {k : ℕ}
    (hk : 1 ≤ k) (w : X → gradedPiece p (freeProP p X) k) :
    basisModificationLinear rbar k hk w = basisModification rbar k w :=
  (rfl)

/-- **Polarization of `delta_1` in the dyadic case.** The bracket part of the operator is
linear, while the defect of additivity of each power term is `[v_i, w_i]`. -/
theorem basisModification_add_zero_dyadic
    (rbar : gradedPiece 2 (freeProP 2 X) 1)
    (v w : X → gradedPiece 2 (freeProP 2 X) 0) :
    basisModification rbar 0 (v + w) - basisModification rbar 0 v -
        basisModification rbar 0 w =
      ∑ i, relatorPowCoeff rbar i •
        gradedBracket 2 (freeProP 2 X) 0 0 (v i) (w i) := by
  simp only [basisModification, Pi.add_apply, map_add, AddMonoidHom.add_apply,
    gradedPow_add_zero_of_two rfl, smul_add, Finset.sum_add_distrib]
  abel

/-- **The dyadic tail `T_j`.** It is spanned by `pi^j(x_i)` over precisely the generators whose
power coefficient `c_i` in the relator class is zero. -/
noncomputable def dyadicTail (rbar : gradedPiece 2 (freeProP 2 X) 1) (j : ℕ) :
    Submodule (ZMod 2) (gradedPiece 2 (freeProP 2 X) j) :=
  span (ZMod 2) {x | ∃ i, relatorPowCoeff rbar i = 0 ∧
    iteratedGradedPow 2 (freeProP 2 X) j (gradedMkZero 2 (freeProP 2 X) (of i)) = x}

/-- The dyadic tail is the span of the iterated powers of the zero-coefficient generators. -/
@[simp]
theorem dyadicTail_eq_span (rbar : gradedPiece 2 (freeProP 2 X) 1) (j : ℕ) :
    dyadicTail rbar j = span (ZMod 2) {x | ∃ i, relatorPowCoeff rbar i = 0 ∧
      iteratedGradedPow 2 (freeProP 2 X) j (gradedMkZero 2 (freeProP 2 X) (of i)) = x} :=
  (rfl)

/-- Every iterated power `pi^j(xbar_i)` of a generator whose power coefficient `c_i` vanishes lies
in the dyadic tail `T_j`. -/
theorem iteratedGradedPow_gradedGenerator_mem_dyadicTail
    (rbar : gradedPiece 2 (freeProP 2 X) 1) (j : ℕ) {i : X}
    (hi : relatorPowCoeff rbar i = 0) :
    iteratedGradedPow 2 (freeProP 2 X) j (gradedMkZero 2 (freeProP 2 X) (of i)) ∈
      dyadicTail rbar j :=
  subset_span ⟨i, hi, rfl⟩

end freeProP

end TauCeti
