/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Ideal.Quotient.Defs
public import Mathlib.RingTheory.Ideal.Span

/-!
# Annihilators in the quotient by a principal ideal `(f * g)`

Let `S` be a commutative ring and `f, g : S` with `f` not a zero-divisor. In `S ⧸ (f * g)` the
annihilator of `f` is the principal ideal generated by `g`. If `g` is not a zero-divisor either,
the same holds with `f` and `g` exchanged, so the classes of `f` and `g` annihilate each other
exactly; this is what makes the free resolutions of `S ⧸ (f * g) ⧸ (f)` two-periodic.

## Main results

* `TauCeti.Ideal.Quotient.mk_mul_eq_zero_iff`: in `S ⧸ (f * g)` with `f` left regular, `f * s = 0`
  exactly when `s` is a multiple of `g`.
-/

public section

namespace TauCeti.Ideal.Quotient

variable {S : Type*} [CommRing S] {f g : S}

/-- **The annihilator of `f` in `S ⧸ (f * g)` is generated by `g`**, provided `f` is not a
zero-divisor in `S`: an element `s` satisfies `f * s = 0` exactly when it is a multiple of `g`. -/
theorem mk_mul_eq_zero_iff (hf : IsLeftRegular f) (s : S ⧸ _root_.Ideal.span {f * g}) :
    _root_.Ideal.Quotient.mk _ f * s = 0 ↔ ∃ t, _root_.Ideal.Quotient.mk _ g * t = s := by
  obtain ⟨r, rfl⟩ := _root_.Ideal.Quotient.mk_surjective s
  refine ⟨fun h ↦ ?_, fun ⟨t, ht⟩ ↦ ?_⟩
  · rw [← map_mul, _root_.Ideal.Quotient.eq_zero_iff_mem, _root_.Ideal.mem_span_singleton] at h
    obtain ⟨c, hc⟩ := h
    exact ⟨_root_.Ideal.Quotient.mk _ c, by rw [← map_mul, hf (hc.trans (mul_assoc f g c))]⟩
  · rw [← ht, ← mul_assoc, ← map_mul, _root_.Ideal.Quotient.eq_zero_iff_mem.mpr
      (_root_.Ideal.mem_span_singleton_self _), zero_mul]

end TauCeti.Ideal.Quotient
