/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial
public import TauCeti.AlgebraicGeometry.IdealSheaf.OfIdealTop

/-!
# Affine descriptions of pullback ideal sheaves

Restricting ideal sheaf data to an affine open subscheme `U`, or pulling it back along
`Spec Γ(X, U) ⟶ X`, gives the ideal sheaf generated by its ideal of sections on that open. This
file records both equalities, and their combination with an inverse image along a morphism
mapping one affine open into another, so local equations can be transported using Mathlib's
actual closed subscheme construction.
-/

public section

open CategoryTheory TopologicalSpace

universe u

namespace AlgebraicGeometry.Scheme.IdealSheafData

variable {X : Scheme.{u}}

/-- Restricting an ideal sheaf to an affine open gives the ideal sheaf generated by its
ideal on that open, transported to the global sections of the open subscheme. -/
@[simp]
theorem comap_ι_eq_ofIdealTop (I : X.IdealSheafData) (U : X.affineOpens) :
    I.comap U.1.ι = ofIdealTop ((I.ideal U).map U.1.topIso.inv.hom) := by
  apply ext_of_isAffine
  rw [ideal_comap_of_isOpenImmersion]
  rw [Scheme.Opens.ι_appIso]
  -- The inclusion's section isomorphism is the identity on the sections of its image.
  -- Restate its inverse ring homomorphism to remove the categorical coercions.
  change (I.ideal ⟨U.1.ι ''ᵁ ⊤, _⟩).comap (RingHom.id _) = _
  rw [Ideal.comap_id]
  simp only [ofIdealTop_ideal, homOfLE_refl, op_id, CategoryTheory.Functor.map_id,
    CommRingCat.hom_id, Ideal.map_id]
  exact (I.map_ideal (U := ⟨U.1.ι ''ᵁ ⊤, _⟩) (V := U) U.1.ι_image_top.le).symm

/-- Pulling an ideal sheaf back along `Spec Γ(X, U) ⟶ X` for an affine open `U` gives the ideal
sheaf generated by its ideal on `U`, read in the global sections of `Spec Γ(X, U)`. -/
@[simp]
theorem comap_fromSpec_eq_ofIdealTop (I : X.IdealSheafData) {U : X.Opens} (hU : IsAffineOpen U) :
    I.comap hU.fromSpec =
      ofIdealTop ((I.ideal ⟨U, hU⟩).map (Scheme.ΓSpecIso Γ(X, U)).inv.hom) := by
  rw [← hU.isoSpec_inv_ι, comap_comp, comap_ι_eq_ofIdealTop I ⟨U, hU⟩, comap_ofIdealTop,
    Ideal.map_map, ← CommRingCat.hom_comp, IsAffineOpen.isoSpec_inv_appTop,
    ← Category.assoc, Iso.inv_hom_id, Category.id_comp]

/-- Let `f : Y ⟶ X` map an affine open `V` of `Y` into an affine open `U` of `X`. Pulling the
inverse image `I.comap f` back along `Spec Γ(Y, V) ⟶ Y` gives the ideal sheaf generated by the
extension of `I(U)` along `f.appLE U V`, read in the global sections of `Spec Γ(Y, V)`. -/
theorem comap_comap_fromSpec_eq_ofIdealTop {Y : Scheme.{u}} (I : X.IdealSheafData) (f : Y ⟶ X)
    {U : X.Opens} {V : Y.Opens} (hU : IsAffineOpen U) (hV : IsAffineOpen V) (e : V ≤ f ⁻¹ᵁ U) :
    (I.comap f).comap hV.fromSpec = ofIdealTop (((I.ideal ⟨U, hU⟩).map (f.appLE U V e).hom).map
      (Scheme.ΓSpecIso Γ(Y, V)).inv.hom) := by
  rw [← comap_comp, ← IsAffineOpen.SpecMap_appLE_fromSpec f hU hV e, comap_comp,
    comap_fromSpec_eq_ofIdealTop, comap_ofIdealTop, Ideal.map_map, Ideal.map_map,
    ← CommRingCat.hom_comp, ← CommRingCat.hom_comp, Scheme.ΓSpecIso_inv_naturality]

end AlgebraicGeometry.Scheme.IdealSheafData
