/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial

/-!
# Affine descriptions of pullback ideal sheaves

Restricting ideal sheaf data to an affine open subscheme gives the ideal sheaf generated by
its ideal of sections on that open. This file records the equality, so local equations can
be transported using Mathlib's actual closed subscheme construction.
-/

public section

open CategoryTheory TopologicalSpace

universe u

namespace AlgebraicGeometry.Scheme.IdealSheafData

variable {X : Scheme.{u}}

/-- Restricting an ideal sheaf to an affine open gives the ideal sheaf generated by its
ideal on that open, transported to the global sections of the open subscheme. -/
@[simp]
theorem comap_ι_eq_ofIdealTop (I : X.IdealSheafData) (U : X.affineOpens) :
    I.comap U.1.ι = ofIdealTop ((I.ideal U).map U.1.topIso.inv.hom) := by
  apply ext_of_isAffine
  rw [ideal_comap_of_isOpenImmersion]
  rw [Scheme.Opens.ι_appIso]
  -- The inclusion's section isomorphism is the identity on the sections of its image.
  -- Restate its inverse ring homomorphism to remove the categorical coercions.
  change (I.ideal ⟨U.1.ι ''ᵁ ⊤, _⟩).comap (RingHom.id _) = _
  rw [Ideal.comap_id]
  simp only [ofIdealTop_ideal, homOfLE_refl, op_id, CategoryTheory.Functor.map_id,
    CommRingCat.hom_id, Ideal.map_id]
  exact (I.map_ideal (U := ⟨U.1.ι ''ᵁ ⊤, _⟩) (V := U) U.1.ι_image_top.le).symm

end AlgebraicGeometry.Scheme.IdealSheafData
