/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.IdealSheaf.Locality
public import TauCeti.AlgebraicGeometry.IdealSheaf.OfIdealTop

/-!
# Inverse images of products of ideal sheaves

For a morphism of schemes `f : X ⟶ Y`, the inverse image `I.comap f` of an ideal sheaf `I` on `Y`
is the ideal sheaf `f⁻¹I·𝒪_X`. This file shows that it is multiplicative:
`(I * J).comap f = I.comap f * J.comap f`. Mathlib already has `comap_sup`, `comap_bot` and
`comap_top`. With multiplicativity, taking inverse images respects all the semiring operations on
ideal sheaves.

Products of ideal sheaves represent sums of effective Cartier divisors, so this says that the
divisor `D₁ + ⋯ + Dₙ` pulls back to the sum of the pulled-back divisors. In particular, a sum of
relative effective Cartier divisors commutes with arbitrary base change.

The proof is local on `X`. Over an open immersion, the inverse image is restriction of the ideals
along ring isomorphisms. Over an affine target, every ideal sheaf is generated by global sections
and `AlgebraicGeometry.Scheme.IdealSheafData.comap_ofIdealTop` applies.

## Main results

* `AlgebraicGeometry.Scheme.IdealSheafData.comap_mul`: `(I * J).comap f = I.comap f * J.comap f`.
* `AlgebraicGeometry.Scheme.IdealSheafData.comap_pow`: `(I ^ n).comap f = I.comap f ^ n`.
* `AlgebraicGeometry.Scheme.IdealSheafData.comap_prod`: the inverse image of a finite product is
  the product of the inverse images.
-/

public section

open CategoryTheory Limits

universe u

namespace AlgebraicGeometry.Scheme.IdealSheafData

variable {X Y : Scheme.{u}}

/-- Along an open immersion, the inverse image of a product of ideal sheaves is the product of the
inverse images: on each affine open, both are pulled back along the same ring isomorphism. -/
private lemma comap_mul_of_isOpenImmersion (I J : Y.IdealSheafData) (f : X ⟶ Y)
    [IsOpenImmersion f] : (I * J).comap f = I.comap f * J.comap f := by
  ext U : 2
  simp only [ideal_comap_of_isOpenImmersion, ideal_mul, Pi.mul_apply]
  -- Pulling back along the inverse of a ring isomorphism is pushing forward along it.
  have h (K : Ideal Γ(Y, f ''ᵁ U)) :
      K.comap (f.appIso U).inv.hom = K.map (f.appIso U).hom.hom :=
    Ideal.comap_symm (f.appIso U).commRingCatIsoToRingEquiv
  rw [h, h, h, Ideal.map_mul]

/-- Over an affine target, the inverse image of a product of ideal sheaves is the product of the
inverse images, since every ideal sheaf there is generated by its global sections. -/
private lemma comap_mul_of_isAffine [IsAffine Y] (I J : Y.IdealSheafData) (f : X ⟶ Y) :
    (I * J).comap f = I.comap f * J.comap f := by
  rw [← equivOfIsAffine.symm_apply_apply I, ← equivOfIsAffine.symm_apply_apply J, ← map_mul,
    equivOfIsAffine_symm_apply, equivOfIsAffine_symm_apply, equivOfIsAffine_symm_apply,
    comap_ofIdealTop, comap_ofIdealTop, comap_ofIdealTop, Ideal.map_mul, ofIdealTop_mul]

/-- **Inverse images of ideal sheaves are multiplicative.** For every morphism `f : X ⟶ Y`, the
inverse image of `I * J` is `I.comap f * J.comap f`: the pullback of a sum of effective Cartier
divisors is the sum of their pullbacks. -/
@[simp]
theorem comap_mul (I J : Y.IdealSheafData) (f : X ⟶ Y) :
    (I * J).comap f = I.comap f * J.comap f := by
  -- Compare both sides on the pullback to `X` of the affine open cover of `Y`. On each member,
  -- `f` restricts to a morphism into an affine open of `Y`.
  refine ext_of_comap_openCover (Y.affineCover.pullback₁ f) fun (i : Y.affineCover.I₀) ↦ ?_
  have : IsOpenImmersion ((Y.affineCover.pullback₁ f).f i) :=
    Scheme.Cover.map_prop (𝒰 := Y.affineCover.pullback₁ f) i
  rw [comap_mul_of_isOpenImmersion _ _ ((Y.affineCover.pullback₁ f).f i), ← comap_comp,
    ← comap_comp, ← comap_comp, ← Scheme.Cover.pullbackHom_map Y.affineCover f i, comap_comp,
    comap_comp, comap_comp, comap_mul_of_isOpenImmersion, comap_mul_of_isAffine]

/-- The inverse image of a power of an ideal sheaf is the power of the inverse image: the pullback
of a multiple `n • D` of an effective Cartier divisor is `n` times its pullback. -/
@[simp]
theorem comap_pow (I : Y.IdealSheafData) (f : X ⟶ Y) (n : ℕ) :
    (I ^ n).comap f = I.comap f ^ n := by
  induction n with
  | zero => simp
  | succ n hn => rw [pow_succ, pow_succ, comap_mul, hn]

/-- The inverse image of a finite product of ideal sheaves is the product of the inverse images:
the pullback of a finite sum of effective Cartier divisors is the sum of their pullbacks. -/
@[simp]
theorem comap_prod {ι : Type*} (s : Finset ι) (I : ι → Y.IdealSheafData) (f : X ⟶ Y) :
    (∏ i ∈ s, I i).comap f = ∏ i ∈ s, (I i).comap f := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert i s hi hs => rw [Finset.prod_insert hi, Finset.prod_insert hi, comap_mul, hs]

end AlgebraicGeometry.Scheme.IdealSheafData
