/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.TrivialFp
public import TauCeti.RepresentationTheory.Homological.ContCohomology.H1ZMod
public import TauCeti.RepresentationTheory.Homological.ContCohomology.TrivialFp.Explicit
public import TauCeti.Topology.Algebra.Group.Profinite.ZHat.Basic
import Mathlib.Topology.Compactness.Compact

/-!
# First cohomology of the profinite integers

The profinite integers `TauCeti.zHat` are topologically generated by `TauCeti.zHat.gen`.
Consequently, when `n ≠ 0`, a continuous character `zHat → ZMod n` is determined by its value
at the generator, and every value occurs. This gives a linear equivalence
`continuousZModDual n zHat ≃ₗ[ZMod n] ZMod n`.

For trivial coefficients, continuous `H¹` is the continuous character group. Composing with
evaluation at the generator computes
`H¹(zHat, ZMod n) ≃ₗ[ZMod n] ZMod n`. For prime `p`, the same calculation on Mathlib's
canonical continuous-cohomology carrier shows that `H¹(zHat, 𝔽_p)` is nonzero. Thus the
`p`-cohomological dimension of `zHat` is at least one.

## Main results

* `TauCeti.zHat.continuousZModDualEquivZMod`: evaluation at the generator identifies the
  continuous `ZMod n`-dual of `zHat` with `ZMod n`.
* `TauCeti.zHat.h1EquivZMod`: `H¹(zHat, ZMod n) ≃ₗ[ZMod n] ZMod n` for a trivial action.
* `TauCeti.zHat.cohomFpOneEquivZMod`: the corresponding equivalence on canonical continuous
  cohomology with `𝔽_p` coefficients.
* `TauCeti.zHat.one_le_cohomologicalDimensionAt`: `1 ≤ cd_p(zHat)` for prime `p`.

## References

* J.-P. Serre, *Local Fields*, Chapter XIII, §1, Propositions 1–2.
* J. Neukirch, A. Schmidt and K. Wingberg, *Cohomology of Number Fields*, 2nd ed., (1.7.7).
-/

public section

namespace TauCeti

open ContCohomology

universe u

namespace zHat

variable (n : ℕ) [NeZero n]

/-- **Evaluation at the canonical generator identifies the continuous `ZMod n`-dual of `zHat`
with `ZMod n`.** The inverse sends `a` to the unique continuous character taking `gen` to `a`.
-/
noncomputable def continuousZModDualEquivZMod :
    continuousZModDual n zHat.{u} ≃ₗ[ZMod n] ZMod n :=
  LinearEquiv.ofBijective (continuousZModDual.evalₗ gen) <| by
    convert (Additive.toMul.trans ((liftEquiv (Multiplicative (ZMod n))).symm.trans
      Multiplicative.toAdd)).bijective using 1
    ext χ
    simp

/-- Evaluation under `continuousZModDualEquivZMod` is evaluation at `zHat.gen`. -/
@[simp]
theorem continuousZModDualEquivZMod_apply (χ : continuousZModDual n zHat.{u}) :
    continuousZModDualEquivZMod n χ = Multiplicative.toAdd (Additive.toMul χ gen) := by
  simp [continuousZModDualEquivZMod]

/-- The inverse of evaluation sends `a : ZMod n` to the lift taking `zHat.gen` to `a`. -/
@[simp]
theorem continuousZModDualEquivZMod_symm_apply (a : ZMod n) :
    (continuousZModDualEquivZMod n).symm a =
      Additive.ofMul (lift (Multiplicative.ofAdd a)) := by
  apply (continuousZModDualEquivZMod n).injective
  simp

section Explicit

variable [DistribMulAction zHat.{u} (ZMod n)] [ContinuousSMul zHat.{u} (ZMod n)]
  (htriv : ∀ (g : zHat.{u}) (a : ZMod n), g • a = a)

/-- **`H¹(zHat, ZMod n) ≃ ZMod n` for trivial coefficients**, by evaluating the character
represented by a cocycle at the canonical generator of `zHat`. -/
noncomputable def h1EquivZMod : H1 zHat.{u} (ZMod n) ≃ₗ[ZMod n] ZMod n :=
  (h1EquivContinuousZModDual htriv).trans (continuousZModDualEquivZMod n)

/-- The equivalence `h1EquivZMod` sends the class of a cocycle to its value at `zHat.gen`. -/
@[simp]
theorem h1EquivZMod_apply_mk (f : Z1 zHat.{u} (ZMod n)) :
    h1EquivZMod n htriv (f : H1 zHat.{u} (ZMod n)) =
      (f : zHat.{u} → ZMod n) gen := by
  simp [h1EquivZMod]

/-- The inverse of `h1EquivZMod` sends `a` to the class of the unique continuous character of
`zHat` taking the canonical generator to `a`. -/
@[simp]
theorem h1EquivZMod_symm_apply (a : ZMod n) :
    (h1EquivZMod n htriv).symm a =
      ((Z1EquivOfSmulEqSelf htriv).symm
        (Additive.ofMul (lift (Multiplicative.ofAdd a))) : H1 zHat.{u} (ZMod n)) := by
  simp [h1EquivZMod]

end Explicit

section Canonical

variable (p : ℕ)

/-- **Canonical continuous `H¹(zHat, 𝔽_p)` is one-dimensional.** More precisely, evaluation
of the corresponding continuous character at `zHat.gen` gives a linear equivalence with
`ZMod p`. -/
noncomputable def cohomFpOneEquivZMod [NeZero p] :
    cohomFp p zHat.{u} 1 ≃ₗ[ZMod p] ZMod p :=
  (cohomFpLinearEquivContinuousZModDual p zHat.{u}).trans
    (continuousZModDualEquivZMod p)

/-- The canonical equivalence evaluates the continuous character attached to a cohomology class
at `zHat.gen`. -/
@[simp]
theorem cohomFpOneEquivZMod_apply [NeZero p] (x : cohomFp p zHat.{u} 1) :
    cohomFpOneEquivZMod p x = Multiplicative.toAdd
      (Additive.toMul (cohomFpLinearEquivContinuousZModDual p zHat.{u} x) gen) := by
  simp [cohomFpOneEquivZMod]

/-- The inverse of `cohomFpOneEquivZMod` sends `a` to the class attached to the unique continuous
character of `zHat` taking the canonical generator to `a`. -/
@[simp]
theorem cohomFpOneEquivZMod_symm_apply [NeZero p] (a : ZMod p) :
    (cohomFpOneEquivZMod p).symm a = (cohomFpLinearEquivContinuousZModDual p zHat.{u}).symm
      (Additive.ofMul (lift (Multiplicative.ofAdd a))) := by
  simp [cohomFpOneEquivZMod]

/-- Canonical continuous `H¹(zHat, 𝔽_p)` has dimension one for prime `p`. -/
@[simp]
theorem finrank_cohomFp_one [Fact p.Prime] :
    Module.finrank (ZMod p) (cohomFp p zHat.{u} 1) = 1 := by
  simpa using (cohomFpOneEquivZMod p).finrank_eq

/-- Canonical continuous `H¹(zHat, 𝔽_p)` is nontrivial for prime `p`. -/
theorem nontrivial_cohomFp_one [Fact p.Prime] : Nontrivial (cohomFp p zHat.{u} 1) :=
  (cohomFpOneEquivZMod p).toEquiv.nontrivial

/-- **The `p`-cohomological dimension of the profinite integers is at least one.** The nonzero
class in `H¹(zHat, 𝔽_p)` is detected by evaluation at the canonical generator. -/
theorem one_le_cohomologicalDimensionAt [Fact p.Prime] :
    (1 : ℕ∞) ≤ cohomologicalDimensionAt.{u} p zHat.{u} :=
  le_cohomologicalDimensionAt_of_nontrivial_cohomFp (nontrivial_cohomFp_one p)

end Canonical

end zHat

end TauCeti
