/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.RamifiedPrimes
import TauCeti.NumberTheory.NumberField.Quadratic.Different
import TauCeti.NumberTheory.NumberField.Quadratic.Norm
import TauCeti.NumberTheory.NumberField.Quadratic.RingOfIntegers
import TauCeti.NumberTheory.NumberField.Quadratic.TotalRamification

/-!
# The dyadic different of `ℚ(√2)`

For `K` generated over `ℚ` by an algebraic integer `θ` with `minpoly ℤ θ = X² − 2`, the radicand
`2` is squarefree and not `1` modulo `4`, so `𝓞 K = ℤ[θ]` and `discr K = 8`. The prime `2`
ramifies: `𝔭 = (θ)` is the only prime of `𝓞 K` above it, and `2 𝓞 K = 𝔭²` since `θ² = 2`.

The different of `ℤ[θ]` is generated by `f'(θ) = 2θ = θ³`, so `𝔡 = 𝔭³`. With `e = 2` and
`v_𝔭(e) = v_𝔭(2) = 2`, the different exponent `v_𝔭(𝔡) = 3` equals `e − 1 + v_𝔭(e)`: at this wildly
ramified prime the upper bound of Dedekind's different theorem is attained, and the exponent
strictly exceeds the lower bound `e`. In `ℚ(i)` the opposite happens, `v_𝔭(𝔡) = e = 2 < 3`
(`GaussianRationals.multiplicity_differentIdeal_lt_ramificationIdx_sub_one_add`), so neither
bound determines the wild different exponent.

## Main results

* `TauCeti.NumberField.Sqrt2.adjoin_eq_top`: `𝓞 K = ℤ[θ]`, and `discr_eq_eight`: `discr K = 8`.
* `TauCeti.NumberField.Sqrt2.eq_span_gen`: the prime above `2` is `(θ)`, with
  `ramificationIdx_eq_two` and `map_span_two_eq_sq`: `e = 2` and `2 𝓞 K = 𝔭²`.
* `TauCeti.NumberField.Sqrt2.differentIdeal_eq_pow_three` and
  `multiplicity_differentIdeal_eq_three`: `𝔡 = 𝔭³`, that is `v_𝔭(𝔡) = 3`.
* `TauCeti.NumberField.Sqrt2.multiplicity_span_two_eq_two`: `v_𝔭(2) = 2`.
* `TauCeti.NumberField.Sqrt2.multiplicity_differentIdeal_eq_ramificationIdx_sub_one_add`:
  `v_𝔭(𝔡) = e − 1 + v_𝔭(e)`, and
  `ramificationIdx_lt_multiplicity_differentIdeal`: `e < v_𝔭(𝔡)`.

## References

* J. Neukirch, *Algebraic Number Theory*, Chapter III, Theorem 2.6.
* J.-P. Serre, *Local Fields*, Chapter III, §6, Proposition 13.
-/

public section

open Polynomial NumberField Ideal
open scoped NumberField

namespace TauCeti.NumberField.Sqrt2

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K}

omit [NumberField K] in
/-- The minimal polynomial `X² − 2` in the radicand form `X² − C 2` of the quadratic-field
theory. -/
theorem minpoly_eq_X_sq_sub_C (hmin : minpoly ℤ θ = X ^ 2 - 2) :
    minpoly ℤ θ = X ^ 2 - C 2 := by
  rw [hmin, map_ofNat]

omit [NumberField K] in
/-- The defining identity `θ² = 2`. -/
@[simp]
theorem sq_eq_two (hmin : minpoly ℤ θ = X ^ 2 - 2) : θ ^ 2 = 2 := by
  rw [gen_sq (minpoly_eq_X_sq_sub_C hmin), map_ofNat]

/-- `ℚ(√2)` has degree `2`. -/
theorem finrank_eq_two (hmin : minpoly ℤ θ = X ^ 2 - 2)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) : Module.finrank ℚ K = 2 :=
  finrank_rat_eq_two (minpoly_eq_X_sq_sub_C hmin) hgen

/-- **The ring of integers of `ℚ(√2)` is `ℤ[θ]`**: the radicand `2` is squarefree and not `1`
modulo `4`. -/
@[simp]
theorem adjoin_eq_top (hmin : minpoly ℤ θ = X ^ 2 - 2)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) : Algebra.adjoin ℤ {θ} = ⊤ :=
  adjoin_gen_eq_top_of_mod_four_ne_one (minpoly_eq_X_sq_sub_C hmin) hgen
    Int.prime_two.squarefree (by decide)

/-- **The discriminant of `ℚ(√2)` is `8`.** -/
theorem discr_eq_eight (hmin : minpoly ℤ θ = X ^ 2 - 2)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) : discr K = 8 :=
  discr_eq_four_mul_of_mod_four_ne_one (minpoly_eq_X_sq_sub_C hmin) hgen
    Int.prime_two.squarefree (by decide)

/-- `2` ramifies in `ℚ(√2)`: it divides the discriminant `8`. -/
theorem two_mem_ramifiedPrimes (hmin : minpoly ℤ θ = X ^ 2 - 2)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) : 2 ∈ ramifiedPrimes K := by
  rw [mem_ramifiedPrimes_iff_dvd_discr Nat.prime_two, discr_eq_eight hmin hgen]
  norm_num

/-- The ideal `(θ)` has absolute norm `2`: `N(θ) = 0² − 2 · 1² = −2`. -/
theorem absNorm_span_gen (hmin : minpoly ℤ θ = X ^ 2 - 2)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) : absNorm (span {θ}) = 2 := by
  have h := norm_int_add_mul_gen (minpoly_eq_X_sq_sub_C hmin) hgen 1 0
  norm_num at h
  rw [absNorm_span_singleton, h]
  rfl

/-- **The different of `ℚ(√2)` is `(θ³)`**: the different of `ℤ[θ]` is generated by
`f'(θ) = 2θ`, and `2θ = θ³`. -/
theorem differentIdeal_eq_span_pow_three (hmin : minpoly ℤ θ = X ^ 2 - 2)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) : differentIdeal ℤ (𝓞 K) = span {θ ^ 3} := by
  rw [differentIdeal_eq_span_two_mul_gen (minpoly_eq_X_sq_sub_C hmin) (adjoin_eq_top hmin hgen),
    ← sq_eq_two hmin, ← pow_succ]

variable (hmin : minpoly ℤ θ = X ^ 2 - 2) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
  (𝔭 : Ideal (𝓞 K)) [𝔭.IsPrime] [𝔭.LiesOver (span {(2 : ℤ)})]

include hmin hgen

/-- **The prime above `2` in `ℚ(√2)` is `(θ)`.** -/
theorem eq_span_gen : 𝔭 = span {θ} :=
  (eq_of_absNorm_eq_of_mem_ramifiedPrimes (p := 2) (finrank_eq_two hmin hgen)
    (two_mem_ramifiedPrimes hmin hgen) 𝔭 _ (absNorm_span_gen hmin hgen)).symm

/-- **`2` is totally ramified in `ℚ(√2)`**: `e(𝔭 ∣ 2) = 2`. -/
theorem ramificationIdx_eq_two : 𝔭.ramificationIdx ℤ = 2 :=
  ramificationIdx_eq_two_of_mem_ramifiedPrimes (p := 2) (finrank_eq_two hmin hgen)
    (two_mem_ramifiedPrimes hmin hgen) 𝔭

/-- **`2 𝓞 K = 𝔭²`** in `ℚ(√2)`. -/
theorem map_span_two_eq_sq : (span {(2 : ℤ)}).map (algebraMap ℤ (𝓞 K)) = 𝔭 ^ 2 := by
  rw [eq_span_gen hmin hgen 𝔭, span_singleton_pow, sq_eq_two hmin, map_span,
    Set.image_singleton, map_ofNat]

/-- **The different of `ℚ(√2)` is `𝔭³`.** -/
theorem differentIdeal_eq_pow_three : differentIdeal ℤ (𝓞 K) = 𝔭 ^ 3 := by
  rw [differentIdeal_eq_span_pow_three hmin hgen, eq_span_gen hmin hgen 𝔭, span_singleton_pow]

/-- **The different exponent of `ℚ(√2)` at the dyadic prime is `3`**: `v_𝔭(𝔡) = 3`. -/
theorem multiplicity_differentIdeal_eq_three :
    multiplicity 𝔭 (differentIdeal ℤ (𝓞 K)) = 3 := by
  have htwo : span {(2 : ℤ)} ≠ ⊥ := span_singleton_eq_bot.not.mpr two_ne_zero
  have h𝔭 : 𝔭 ≠ ⊥ := ne_bot_of_liesOver_of_ne_bot htwo 𝔭
  rw [differentIdeal_eq_pow_three hmin hgen 𝔭]
  exact multiplicity_pow_self_of_prime (Ideal.prime_of_isPrime h𝔭 ‹_›) 3

/-- **The dyadic valuation of `2` in `ℚ(√2)` is `2`**: `v_𝔭(2) = 2`. -/
theorem multiplicity_span_two_eq_two : multiplicity 𝔭 (span {(2 : 𝓞 K)}) = 2 := by
  have htwo : (span {(2 : ℤ)}).map (algebraMap ℤ (𝓞 K)) ≠ ⊥ :=
    map_ne_bot_of_ne_bot (span_singleton_eq_bot.not.mpr two_ne_zero)
  rw [← map_ofNat (algebraMap ℤ (𝓞 K)) 2, ← Set.image_singleton, ← map_span,
    ← IsDedekindDomain.ramificationIdx_eq_multiplicity _ 𝔭 htwo, ramificationIdx_eq_two hmin hgen 𝔭]

/-- **The wild upper bound is attained in `ℚ(√2)`**: at the dyadic prime,
`v_𝔭(𝔡) = e − 1 + v_𝔭(e)`, with `e = 2` and both sides equal to `3`. -/
theorem multiplicity_differentIdeal_eq_ramificationIdx_sub_one_add :
    multiplicity 𝔭 (differentIdeal ℤ (𝓞 K)) =
      𝔭.ramificationIdx ℤ - 1 + multiplicity 𝔭 (span {((𝔭.ramificationIdx ℤ : ℕ) : 𝓞 K)}) := by
  rw [multiplicity_differentIdeal_eq_three hmin hgen 𝔭, ramificationIdx_eq_two hmin hgen 𝔭,
    Nat.cast_ofNat, multiplicity_span_two_eq_two hmin hgen 𝔭]

/-- **The wild lower bound is strict in `ℚ(√2)`**: at the dyadic prime, `e = 2 < 3 = v_𝔭(𝔡)`. -/
theorem ramificationIdx_lt_multiplicity_differentIdeal :
    𝔭.ramificationIdx ℤ < multiplicity 𝔭 (differentIdeal ℤ (𝓞 K)) := by
  rw [multiplicity_differentIdeal_eq_three hmin hgen 𝔭, ramificationIdx_eq_two hmin hgen 𝔭]
  norm_num

end TauCeti.NumberField.Sqrt2
