/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.Profinite.ProP.PadicInt.Basic
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.Rank

/-!
# The Frattini subgroup of `ℤ_p`

The pro-`p` Frattini subgroup of the additive group of the `p`-adic integers, written
multiplicatively as `Multiplicative ℤ_[p]`, is `p ℤ_p`: the group is commutative, so its pro-`p`
Frattini subgroup is the subgroup of `p`-th powers (`TauCeti.proPFrattini_eq_range_powMonoidHom`),
which additively is the ideal generated by `p`, the maximal ideal of `ℤ_[p]`. Its index is `p`,
as the Frattini quotient of a pro-`p` group of topological generator rank one must be.

## Main results

* `TauCeti.mem_proPFrattini_multiplicative_padicInt_iff`: `x ∈ Φ(ℤ_p)` exactly when `p ∣ x`.
* `TauCeti.proPFrattini_multiplicative_padicInt`: `Φ(ℤ_p) = p ℤ_p`, as subgroups.
* `TauCeti.index_proPFrattini_multiplicative_padicInt`: `[ℤ_p : Φ(ℤ_p)] = p`.

## References

* L. Ribes and P. Zalesskii, *Profinite Groups*, Sections 2.8 and 4.3.
-/

public section

namespace TauCeti

variable (p : ℕ) [Fact p.Prime]

/-- An element of `ℤ_p` lies in the pro-`p` Frattini subgroup exactly when it is divisible by
`p`. -/
@[simp]
theorem mem_proPFrattini_multiplicative_padicInt_iff {x : Multiplicative ℤ_[p]} :
    x ∈ proPFrattini p (Multiplicative ℤ_[p]) ↔ (p : ℤ_[p]) ∣ x.toAdd := by
  rw [mem_proPFrattini_iff_exists_pow Fact.out]
  constructor
  · rintro ⟨b, rfl⟩
    exact ⟨b.toAdd, by rw [toAdd_pow, nsmul_eq_mul]⟩
  · rintro ⟨c, hc⟩
    refine ⟨Multiplicative.ofAdd c, ?_⟩
    rw [← ofAdd_nsmul, nsmul_eq_mul, ← hc, ofAdd_toAdd]

/-- **`Φ(ℤ_p) = p ℤ_p`.** The pro-`p` Frattini subgroup of the additive group of `ℤ_[p]` is the
ideal generated by `p`, which is the maximal ideal (`PadicInt.maximalIdeal_eq_span_p`), viewed as
a subgroup of `Multiplicative ℤ_[p]`. -/
theorem proPFrattini_multiplicative_padicInt :
    proPFrattini p (Multiplicative ℤ_[p]) =
      AddSubgroup.toSubgroup (Ideal.span {(p : ℤ_[p])}).toAddSubgroup := by
  ext x
  rw [mem_proPFrattini_multiplicative_padicInt_iff, Multiplicative.mem_toSubgroup,
    Submodule.mem_toAddSubgroup, Ideal.mem_span_singleton]

/-- **`[ℤ_p : p ℤ_p] = p`.** The pro-`p` Frattini subgroup of the additive group of `ℤ_[p]` has
index `p`, so the Frattini quotient of `ℤ_p` is `𝔽_p`. -/
@[simp]
theorem index_proPFrattini_multiplicative_padicInt :
    (proPFrattini p (Multiplicative ℤ_[p])).index = p := by
  rw [Subgroup.index_eq_card, (isProP_multiplicative_padicInt p).natCard_quotient_proPFrattini
    (isTopologicallyFinitelyGenerated_multiplicative_padicInt p),
    topologicalGeneratorRankNat_multiplicative_padicInt, pow_one]

end TauCeti
