/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Separation
public import TauCeti.Algebra.AlgebraicGroup.Symplectic.BaseChange
public import TauCeti.Algebra.AlgebraicGroup.Symplectic.Smooth
public import TauCeti.Algebra.Lie.Symplectic.StandardCarrier.BaseChange
public import TauCeti.Algebra.Lie.Symplectic.StandardCarrier.Generation

/-!
# The type C carrier over a field

The full-weight type `C_(n+1)` Kostant carrier is constructed over `ℤ` as the closed subgroup of
`GL_(2n+2)` generated by the numbered root subgroups and its weight torus. After extension to a
field, its matrix points are already known to be exactly the matrices preserving the standard
alternating form. This file upgrades that pointwise statement to an equality of defining Hopf
ideals over every field:

```text
  baseChangeDefiningIdeal n k = Symplectic.definingHopfIdeal k (n + 1).
```

The resulting quotient isomorphism identifies the base-changed explicit carrier with the coordinate
Hopf algebra of `Sp_(2n+2)`. Only the equality needs a field: the containment of the symplectic
ideal in the transported carrier ideal, equivalently the statement that every carrier point
preserves the standard alternating form, holds over every commutative ring.

## Main declarations

* `TauCeti.SpStd.symplecticDefiningHopfIdeal_le_baseChangeDefiningIdeal`: over every commutative
  ring, the symplectic defining ideal is contained in the transported carrier ideal.
* `TauCeti.SpStd.baseChangeDefiningIdeal_eq_symplecticDefiningHopfIdeal`: over every field, the
  transported carrier and symplectic defining ideals agree.
* `TauCeti.SpStd.baseChangeCoordinateSymplecticIso`: the induced coordinate Hopf-algebra
  isomorphism with `Sp_(2n+2)`.

## References

* J. E. Humphreys, *Linear Algebraic Groups*, §§26--27.
* R. Steinberg, *Lectures on Chevalley Groups*, §§3--4.
-/

public section

open CategoryTheory Matrix WithConv
open TauCeti.UniversalEnvelopingAlgebra
open scoped TensorProduct

namespace TauCeti.SpStd

universe u v

noncomputable section

attribute [local instance high] Algebra.toModule

variable (n : ℕ)

/-- The symplectic ideal is contained in the transported defining ideal of the full-weight
type `C_(n+1)` carrier over every commutative ring. Equivalently, every point of the transported
carrier preserves the standard alternating form. -/
theorem symplecticDefiningHopfIdeal_le_baseChangeDefiningIdeal
    (A : Type u) [CommRing A] :
    Symplectic.definingHopfIdeal A (n + 1) ≤ baseChangeDefiningIdeal n A := by
  rw [← HopfIdeal.toIdeal_le_toIdeal,
    ConstantForm.definingHopfIdeal_toIdeal, Ideal.span_le]
  intro x hx
  obtain ⟨i, j, rfl⟩ :=
    (ConstantForm.mem_relationSet_iff A ((n + 1) + (n + 1)) (JFin (n + 1) A)).mp hx
  have hgenerator :
      Symplectic.relationMatrix ℤ (n + 1) i j ∈ definingIdeal n := by
    apply symplecticDefiningHopfIdeal_le_definingIdeal n
    have hmem : Symplectic.relationMatrix ℤ (n + 1) i j ∈
        (Symplectic.definingHopfIdeal ℤ (n + 1)).toIdeal := by
      rw [ConstantForm.definingHopfIdeal_toIdeal]
      exact Ideal.subset_span
        (ConstantForm.relationMatrix_mem_relationSet ℤ ((n + 1) + (n + 1))
          (JFin (n + 1) ℤ) i j)
    exact HopfIdeal.mem_toIdeal.mpr hmem
  have hmap := map_tmul_mem_baseChangeDefiningIdeal_of_mem n A (1 : A) hgenerator
  rwa [Symplectic.coordinateHopfAlgebraBaseChangeIso_hom_relationMatrix ℤ A (n + 1) i j]
    at hmap

/- The proof is adapted from the type-`A` carrier comparison in
`TauCeti.Algebra.Lie.SpecialLinear.StandardCarrier.SpecialLinear`. -/

/-- **Over a field, the transported defining ideal of the full-weight
type `C_(n+1)` carrier is the symplectic ideal.** Thus the explicit carrier obtained from the
Kostant construction is scheme-theoretically `Sp_(2n+2)`, not merely equal to it on field-valued
points. -/
theorem baseChangeDefiningIdeal_eq_symplecticDefiningHopfIdeal
    (k : Type u) [Field k] :
    baseChangeDefiningIdeal n k = Symplectic.definingHopfIdeal k (n + 1) := by
  let _ : IsReduced (Symplectic.coordinateHopfAlgebra k (n + 1)) :=
    isReduced_of_smooth k _
  apply le_antisymm
  · apply HopfIdeal.le_of_quotientPointsSubgroup_le (K := AlgebraicClosure k)
    intro g hg
    rw [mem_baseChangeDefiningPointsSubgroup_iff_mem_points,
      points_eq_GLSymplecticFin]
    rw [GLSymplecticFin.mem_iff]
    rw [ConstantForm.mem_definingPointsSubgroup_iff, JFin_map] at hg
    exact hg
  · exact symplecticDefiningHopfIdeal_le_baseChangeDefiningIdeal n k

/-- Over a field, the coordinate Hopf algebra of the base-changed
full-weight type `C_(n+1)` carrier is canonically the coordinate Hopf algebra of `Sp_(2n+2)`. -/
noncomputable def baseChangeCoordinateSymplecticIso
    (k : Type u) [Field k] :
    CommHopfAlgCat.quotient
        (GeneralLinear.coordinateHopfAlgebra k ((n + 1) + (n + 1)))
        (baseChangeDefiningIdeal n k) ≅
      Symplectic.coordinateHopfAlgebra k (n + 1) :=
  eqToIso (congrArg (CommHopfAlgCat.quotient
    (GeneralLinear.coordinateHopfAlgebra k ((n + 1) + (n + 1))))
      (baseChangeDefiningIdeal_eq_symplecticDefiningHopfIdeal n k))

/-- The carrier--symplectic coordinate isomorphism is compatible with their quotient maps from
`O(GL_(2n+2)/k)`. -/
@[simp]
theorem mkQuotient_comp_baseChangeCoordinateSymplecticIso_hom
    (k : Type u) [Field k] :
    CommHopfAlgCat.mkQuotient
          (GeneralLinear.coordinateHopfAlgebra k ((n + 1) + (n + 1)))
          (baseChangeDefiningIdeal n k) ≫
        (baseChangeCoordinateSymplecticIso n k).hom =
      Symplectic.coordinateMap k (n + 1) := by
  rw [Symplectic.coordinateMap_def]
  exact CommHopfAlgCat.mkQuotient_comp_eqToHom
    (baseChangeDefiningIdeal_eq_symplecticDefiningHopfIdeal n k).symm

end

end TauCeti.SpStd
