/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Global.Orders.Discriminant
import Mathlib.LinearAlgebra.Unimodular

/-!
# The conductor form of quadratic orders

Every order `O` in a quadratic number field has the form `ℤ + f 𝓞 K`, where
`f = [𝓞 K : O]`, and its conductor is the principal ideal `f 𝓞 K`. This is the
arithmetic description used to express the Picard group of a quadratic order as a
congruence quotient of maximal-order ideals.

The results apply to real and imaginary quadratic fields alike. The degree-two
hypothesis is essential: orders in higher-degree fields need not have this form.

## References

* D. A. Cox, *Primes of the Form x² + ny²*, §7, Proposition 7.2.
-/

public section
noncomputable section

open NumberField

namespace TauCeti.GlobalNumberFields.NumberFieldOrder

variable {K : Type*} [Field K] [NumberField K] (O : NumberFieldOrder K)

-- With first basis vector `1`, the second coordinate determines membership in the order.
private theorem mem_iff_coord_mem (b : Module.Basis (Fin 2) ℤ (𝓞 K)) (hb : b 0 = 1)
    (x : 𝓞 K) :
    x ∈ O.toRingOfIntegers ↔
      b.coord 1 x ∈ O.toRingOfIntegers.toSubmodule.map (b.coord 1) := by
  constructor
  · intro hx
    exact Submodule.mem_map.mpr ⟨x, hx, rfl⟩
  · rintro ⟨y, hy, hxy⟩
    have hdecomp (z : 𝓞 K) : z = (b.coord 0 z : 𝓞 K) + b.coord 1 z • b 1 := by
      simpa [Fin.sum_univ_two, hb, Algebra.smul_def] using (b.sum_repr z).symm
    have heq : x = y + ((b.coord 0 x - b.coord 0 y : ℤ) : 𝓞 K) := by
      conv_lhs => rw [hdecomp x]
      conv_rhs => lhs; rw [hdecomp y]
      rw [hxy]
      push_cast
      ring
    rw [heq]
    exact O.toRingOfIntegers.add_mem hy (O.toRingOfIntegers.algebraMap_mem _)

-- The quotient by the order is the quotient of the second-coordinate ideal in `ℤ`.
private theorem exists_basis_coord_index (hK : Module.finrank ℚ K = 2) :
    ∃ b : Module.Basis (Fin 2) ℤ (𝓞 K), b 0 = 1 ∧
      ∀ x : 𝓞 K, x ∈ O.toRingOfIntegers ↔ (O.index : ℤ) ∣ b.coord 1 x := by
  classical
  obtain ⟨b, hb⟩ := (Module.Free.isUnimodular_one (R := ℤ) (A := 𝓞 K)).exists_basis_zero_eq
    (by rw [RingOfIntegers.rank, hK])
  let J : Ideal ℤ := O.toRingOfIntegers.toSubmodule.map (b.coord 1)
  let q : 𝓞 K →ₗ[ℤ] ℤ ⧸ J := J.mkQ.comp (b.coord 1)
  have hq : Function.Surjective q := by
    intro z
    obtain ⟨a, rfl⟩ := J.mkQ_surjective z
    refine ⟨a • b 1, ?_⟩
    simp only [q, LinearMap.comp_apply, map_smul]
    simp [Module.Basis.coord_apply]
  have hker : q.ker = O.toRingOfIntegers.toSubmodule := by
    ext x
    simp only [LinearMap.mem_ker, q, LinearMap.comp_apply, Submodule.mkQ_apply,
      Submodule.Quotient.mk_eq_zero]
    exact (O.mem_iff_coord_mem b hb x).symm
  have hindex : O.index = J.absNorm := by
    rw [O.index_def, ← hker]
    exact Nat.card_congr (q.quotKerEquivOfSurjective hq).toEquiv
  -- The positive generator of an integer ideal is its absolute norm.
  have hJ : O.toRingOfIntegers.toSubmodule.map (b.coord 1) =
      Ideal.span {(O.index : ℤ)} := by
    rw [hindex]
    exact (Int.ideal_span_absNorm_eq_self J).symm
  refine ⟨b, hb, fun x ↦ ?_⟩
  rw [O.mem_iff_coord_mem b hb x, hJ, Ideal.mem_span_singleton]

/-- An element of the maximal order lies in a quadratic order exactly when it is an integer
plus the index of the order times an algebraic integer: `O = ℤ + [𝓞 K : O] 𝓞 K`. -/
theorem mem_toRingOfIntegers_iff_exists_int_add_index_mul (hK : Module.finrank ℚ K = 2)
    (x : 𝓞 K) :
    x ∈ O.toRingOfIntegers ↔ ∃ a : ℤ, ∃ y : 𝓞 K, x = a + O.index * y := by
  obtain ⟨b, hb, hmem⟩ := O.exists_basis_coord_index hK
  constructor
  · intro hx
    obtain ⟨c, hc⟩ := (hmem x).mp hx
    refine ⟨b.coord 0 x, c • b 1, ?_⟩
    have h : x = (b.coord 0 x : 𝓞 K) + b.coord 1 x • b 1 := by
      simpa [Fin.sum_univ_two, hb, Algebra.smul_def] using (b.sum_repr x).symm
    calc
      x = (b.coord 0 x : 𝓞 K) + b.coord 1 x • b 1 := h
      _ = (b.coord 0 x : 𝓞 K) + O.index * (c • b 1) := by
        rw [hc]
        simp [Algebra.smul_def, mul_assoc]
  · rintro ⟨a, y, rfl⟩
    exact O.toRingOfIntegers.add_mem (O.toRingOfIntegers.algebraMap_mem a)
      (O.conductor_le_toRingOfIntegers (O.conductor.mul_mem_right y O.natCast_index_mem_conductor))

/-- The conductor of a quadratic order is generated by its index in the maximal order. -/
@[simp] theorem conductor_eq_span_index (hK : Module.finrank ℚ K = 2) :
    O.conductor = Ideal.span {(O.index : 𝓞 K)} := by
  obtain ⟨b, hb, hmem⟩ := O.exists_basis_coord_index hK
  apply le_antisymm
  · intro x hx
    have hxO := O.conductor_le_toRingOfIntegers hx
    obtain ⟨c, hc⟩ := (hmem x).mp hxO
    have hdecomp : x = (b.coord 0 x : 𝓞 K) + b.coord 1 x • b 1 := by
      simpa [Fin.sum_univ_two, hb, Algebra.smul_def] using (b.sum_repr x).symm
    have hmul : x * b 1 ∈ O.toRingOfIntegers :=
      O.mem_toRingOfIntegers.mpr ((O.mem_conductor_iff x).mp hx (b 1))
    have ha : (O.index : ℤ) ∣ b.coord 0 x := by
      have h := (hmem (x * b 1)).mp hmul
      have heq : b.coord 1 (x * b 1) =
          b.coord 0 x + b.coord 1 x * b.coord 1 (b 1 * b 1) := by
        have heq₀ : x * b 1 = b.coord 0 x • b 1 + b.coord 1 x • (b 1 * b 1) := by
          calc
            x * b 1 = ((b.coord 0 x : 𝓞 K) + b.coord 1 x • b 1) * b 1 :=
              congrArg (fun z ↦ z * b 1) hdecomp
            _ = _ := by simp [Algebra.smul_def, add_mul, mul_assoc]
        rw [heq₀, map_add, map_smul, map_smul]
        simp [Module.Basis.coord_apply]
      rw [heq] at h
      exact (dvd_add_left (((hmem x).mp hxO).mul_right _)).mp h
    obtain ⟨a, ha⟩ := ha
    rw [Ideal.mem_span_singleton]
    refine ⟨(a : 𝓞 K) + c • b 1, ?_⟩
    rw [hdecomp, hc, ha]
    simp [Algebra.smul_def, mul_add, mul_assoc]
  · exact Ideal.span_le.mpr (Set.singleton_subset_iff.mpr O.natCast_index_mem_conductor)

end TauCeti.GlobalNumberFields.NumberFieldOrder
