/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.AlgebraicGeometry.WeilDivisor
public import Mathlib.Algebra.Group.Subgroup.Lattice
public import Mathlib.Algebra.Group.Finsupp
import Mathlib.Tactic.Abel

/-!
# Point differences generate the degree-zero divisor group

For a fixed base point `x₀`, this file proves that the degree-zero Weil divisors are exactly the
integer combinations of the point differences `[x] - [x₀]`, and records the underlying closed
form: every divisor `D` satisfies

`D - (degree D) • [x₀] = Σ_x D(x) • ([x] - [x₀])`,

so a divisor of degree zero is `Σ_x D(x) • ([x] - [x₀])`. Taking the subgroup generated by the
point differences, this says

`degreeZeroSubgroup X = AddSubgroup.closure { [x] - [x₀] | x }`.

The weighted analogue, using the degree-corrected point divisors `[x] - w(x) • [x₀]` of
`WeilDivisor.weightedPointBaseDifference`, holds whenever the base point has weight one:

`weightedDegreeZeroSubgroup w = AddSubgroup.closure { [x] - w(x) • [x₀] | x }`.

This is the formal-divisor shadow of the geometric fact that, over a field with a chosen rational
point `x₀`, the Abel-Jacobi map on symmetric powers surjects onto `Pic⁰`: a degree-zero divisor
class is a sum of the classes of `[x] - [x₀]`. It is the combinatorial input to that surjectivity,
available at the free Weil-divisor level before line bundles, principal divisors, the Picard
scheme, or the Jacobian variety exist.

This advances `TauCetiRoadmap/JacobianChallenge/README.md`, Layer A, "Divisors on a curve: Weil
divisors `⊕_x ℤ`", "Degree", and "`Pic⁰ X = ker deg` (as an abstract group)", and feeds the
Layer D/F Abel-map prerequisite `D ↦ 𝒪_X(D - d·x₀)`. No external mathematics is vendored; the
proofs reuse Tau Ceti's `WeilDivisor` API and Mathlib's finitely-supported induction and subgroup
`closure` machinery.
-/

public section

namespace TauCeti

namespace AlgebraicGeometry

namespace WeilDivisor

variable {X : Type*}

noncomputable section

private lemma ofPoint_eq_single_one (x : X) : ofPoint x = Finsupp.single x (1 : ℤ) := by
  ext y
  by_cases hy : y = x
  · subst y
    rw [coeff_ofPoint_self, coeff, Finsupp.single_eq_same]
  · rw [coeff_ofPoint_of_ne hy, coeff, Finsupp.single_eq_of_ne hy]

private lemma single_eq_zsmul_ofPoint (a : X) (b : ℤ) :
    (Finsupp.single a b : WeilDivisor X) = b • ofPoint a := by
  rw [ofPoint_eq_single_one, Finsupp.smul_single_one]

private lemma pointDifference_eq_sub (x y : X) :
    pointDifference x y = ofPoint x - ofPoint y := rfl

/-- The closed form for the base-point correction: subtracting `(degree D) • [x₀]` from `D`
expresses it as the finite sum of `D(x) • ([x] - [x₀])`.  Because the coefficients of `D` sum to
`degree D`, the base-point contributions collapse to a single `(degree D) • [x₀]` term. -/
lemma sum_zsmul_pointDifference (x₀ : X) (D : WeilDivisor X) :
    (D.sum fun x n => n • pointDifference x x₀) = D - degree D • ofPoint x₀ := by
  induction D using Finsupp.induction_linear with
  | zero => simp
  | add f g hf hg =>
    rw [Finsupp.sum_add_index' (fun a => by simp) (fun a b₁ b₂ => add_smul b₁ b₂ _),
      hf, hg, degree_add, add_smul]
    abel
  | single a b =>
    rw [Finsupp.sum_single_index (by simp), pointDifference_eq_sub, single_eq_zsmul_ofPoint,
      map_zsmul, degree_ofPoint, smul_eq_mul, mul_one, smul_sub]

/-- A divisor of degree zero is the finite integer combination `Σ_x D(x) • ([x] - [x₀])` of point
differences based at `x₀`.  This is the closed form of the Abel-Jacobi expansion of a degree-zero
divisor. -/
lemma eq_sum_zsmul_pointDifference {D : WeilDivisor X} (hD : degree D = 0) (x₀ : X) :
    D = D.sum fun x n => n • pointDifference x x₀ := by
  rw [sum_zsmul_pointDifference, hD, zero_smul, sub_zero]

private lemma sub_degree_zsmul_ofPoint_mem_closure (x₀ : X) (D : WeilDivisor X) :
    D - degree D • ofPoint x₀ ∈
      AddSubgroup.closure (Set.range fun x => pointDifference x x₀) := by
  induction D using Finsupp.induction_linear with
  | zero => simp
  | add f g hf hg =>
    have hfg : f + g - degree (f + g) • ofPoint x₀ =
        (f - degree f • ofPoint x₀) + (g - degree g • ofPoint x₀) := by
      rw [degree_add, add_smul]; abel
    rw [hfg]
    exact add_mem hf hg
  | single a b =>
    rw [single_eq_zsmul_ofPoint, map_zsmul, degree_ofPoint, smul_eq_mul, mul_one, ← smul_sub,
      ← pointDifference_eq_sub]
    refine zsmul_mem ?_ b
    exact AddSubgroup.subset_closure ⟨a, rfl⟩

/-- **The degree-zero divisors are generated by the point differences `[x] - [x₀]`.**  For any base
point `x₀`, the unweighted degree-zero subgroup is the subgroup generated by all point differences
based at `x₀`.  This is the formal-divisor form of Abel-Jacobi surjectivity onto the degree-zero
Picard group. -/
theorem degreeZeroSubgroup_eq_closure_pointDifference (x₀ : X) :
    degreeZeroSubgroup X = AddSubgroup.closure (Set.range fun x => pointDifference x x₀) := by
  apply le_antisymm
  · intro D hD
    have h := sub_degree_zsmul_ofPoint_mem_closure x₀ D
    rwa [(mem_degreeZeroSubgroup D).mp hD, zero_smul, sub_zero] at h
  · rw [AddSubgroup.closure_le]
    rintro _ ⟨x, rfl⟩
    exact pointDifference_mem_degreeZeroSubgroup x x₀

/-! ### Weighted version -/

/-- The weighted closed form: subtracting `(weightedDegree w D) • [x₀]` from `D` expresses it as
the finite sum of the degree-corrected point divisors `D(x) • ([x] - w(x) • [x₀])`. -/
lemma sum_zsmul_weightedPointBaseDifference (w : X → ℤ) (x₀ : X) (D : WeilDivisor X) :
    (D.sum fun x n => n • weightedPointBaseDifference w x₀ x) =
      D - weightedDegree w D • ofPoint x₀ := by
  induction D using Finsupp.induction_linear with
  | zero => simp
  | add f g hf hg =>
    rw [Finsupp.sum_add_index' (fun a => by simp) (fun a b₁ b₂ => add_smul b₁ b₂ _),
      hf, hg, weightedDegree_add, add_smul]
    abel
  | single a b =>
    rw [Finsupp.sum_single_index (by simp), weightedPointBaseDifference_eq_ofPoint_sub_zsmul,
      single_eq_zsmul_ofPoint, map_zsmul, weightedDegree_ofPoint, smul_eq_mul, mul_smul,
      smul_sub]

/-- A divisor of weighted degree zero is the finite integer combination
`Σ_x D(x) • ([x] - w(x) • [x₀])` of degree-corrected point divisors based at `x₀`. -/
lemma eq_sum_zsmul_weightedPointBaseDifference (w : X → ℤ) {D : WeilDivisor X}
    (hD : weightedDegree w D = 0) (x₀ : X) :
    D = D.sum fun x n => n • weightedPointBaseDifference w x₀ x := by
  rw [sum_zsmul_weightedPointBaseDifference, hD, zero_smul, sub_zero]

private lemma sub_weightedDegree_zsmul_ofPoint_mem_closure (w : X → ℤ) (x₀ : X)
    (D : WeilDivisor X) :
    D - weightedDegree w D • ofPoint x₀ ∈
      AddSubgroup.closure (Set.range fun x => weightedPointBaseDifference w x₀ x) := by
  induction D using Finsupp.induction_linear with
  | zero => simp
  | add f g hf hg =>
    have hfg : f + g - weightedDegree w (f + g) • ofPoint x₀ =
        (f - weightedDegree w f • ofPoint x₀) + (g - weightedDegree w g • ofPoint x₀) := by
      rw [weightedDegree_add, add_smul]; abel
    rw [hfg]
    exact add_mem hf hg
  | single a b =>
    rw [single_eq_zsmul_ofPoint, map_zsmul, weightedDegree_ofPoint, smul_eq_mul, mul_smul,
      ← smul_sub, ← weightedPointBaseDifference_eq_ofPoint_sub_zsmul]
    refine zsmul_mem ?_ b
    exact AddSubgroup.subset_closure ⟨a, rfl⟩

/-- **The weighted degree-zero divisors are generated by the degree-corrected point divisors
`[x] - w(x) • [x₀]`.**  When the base point has weight one (the residue-field degree of a
`k`-rational point is one), the weighted degree-zero subgroup is generated by all the
`weightedPointBaseDifference w x₀ x`.  The weight-one hypothesis is what puts the generators inside
the subgroup; without it the generators need not have weighted degree zero. -/
theorem weightedDegreeZeroSubgroup_eq_closure_weightedPointBaseDifference
    (w : X → ℤ) {x₀ : X} (hx₀ : w x₀ = 1) :
    weightedDegreeZeroSubgroup w =
      AddSubgroup.closure (Set.range fun x => weightedPointBaseDifference w x₀ x) := by
  apply le_antisymm
  · intro D hD
    have h := sub_weightedDegree_zsmul_ofPoint_mem_closure w x₀ D
    rwa [(mem_weightedDegreeZeroSubgroup w D).mp hD, zero_smul, sub_zero] at h
  · rw [AddSubgroup.closure_le]
    rintro _ ⟨x, rfl⟩
    exact weightedPointBaseDifference_mem_weightedDegreeZeroSubgroup hx₀ x

end

end WeilDivisor

end AlgebraicGeometry

end TauCeti
