/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.MonoidAlgebra.Module
public import Mathlib.GroupTheory.OrderOfElement
public import Mathlib.LinearAlgebra.Quotient.Defs
public import Mathlib.LinearAlgebra.Span.Basic
public import Mathlib.RingTheory.Ideal.Span

/-!
# The quotient of a monoid algebra by the left ideal of two eigenvalue relations

For two elements `σ, τ` of a monoid `G` and two scalars `a, b` of a commutative ring `R`, consider
the left ideal `J = R[G]·(σ - a) + R[G]·(τ - b)` of the monoid algebra `R[G]` and the left
`R[G]`-module `R[G] ⧸ J`. Its elements are the classes `[x]`, and right multiplication by `σ` and
`τ` acts on them as the scalars `a` and `b`: `[x σ] = a [x]` and `[x τ] = b [x]`.

Consequently the quotient is killed by `b ^ orderOf τ - 1`, and when `σ, τ` generate a finite
group `G` every class is an `R`-multiple of the class of `1`: the quotient is a cyclic
`R`-module. It is the largest quotient of `R[G]` on which `σ` and `τ` act through the scalars
`a` and `b`.

In the computation of the generator rank of the absolute Galois group of a `p`-adic field
(NSW (7.4.1)), `R = ℤ_p`, `G` is the group of a tamely ramified finite Galois layer `L/K`
generated by a Frobenius lift `σ` and a generator `τ` of tame inertia, and `a, b` are exponents
through which they act on the `p`-power roots of unity of `L`; the cyclicity of the quotient is
what makes it no larger than the roots of unity themselves.

## Main statements

* `TauCeti.MonoidAlgebra.mk_mul_single_eq_smul_of_sub_mem`: if a left ideal `I` contains
  `g - c`, right multiplication by `g` acts on `R[G] ⧸ I` as `c`.
* `TauCeti.MonoidAlgebra.pow_orderOf_sub_one_smul_eq_zero_of_sub_mem`: such a quotient is killed
  by `c ^ orderOf g - 1`.
* `TauCeti.MonoidAlgebra.surjective_toSpanSingleton_mk_one`: when `σ, τ` generate a finite group,
  the quotient is generated over `R` by the class of `1`.

## References

* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, proof of (7.4.1).
-/

public section

namespace TauCeti.MonoidAlgebra

open _root_.MonoidAlgebra

variable {R : Type*} [CommRing R] {G : Type*}

section Eigenvalue

variable [Monoid G] {I : Ideal (MonoidAlgebra R G)} {g : G} {c : R}

/-- If the left ideal `I` contains `g - c`, then right multiplication by `g` acts on `R[G] ⧸ I` as
the scalar `c`. -/
theorem mk_mul_single_eq_smul_of_sub_mem (h : single g (1 : R) - single 1 c ∈ I)
    (x : MonoidAlgebra R G) :
    (Submodule.Quotient.mk (x * single g (1 : R)) : MonoidAlgebra R G ⧸ I) =
      c • Submodule.Quotient.mk x := by
  rw [← Submodule.Quotient.mk_smul, Submodule.Quotient.eq]
  convert I.mul_mem_left x h using 1
  rw [mul_sub]
  congr 1
  ext
  simp [coeff_mul_single_one, mul_comm]

/-- If the left ideal `I` contains `g - c`, then right multiplication by `g ^ m` acts on
`R[G] ⧸ I` as the scalar `c ^ m`. -/
theorem mk_mul_single_pow_eq_pow_smul_of_sub_mem (h : single g (1 : R) - single 1 c ∈ I)
    (x : MonoidAlgebra R G) (m : ℕ) :
    (Submodule.Quotient.mk (x * single (g ^ m) (1 : R)) : MonoidAlgebra R G ⧸ I) =
      c ^ m • Submodule.Quotient.mk x := by
  induction m with
  | zero => rw [pow_zero, pow_zero, one_smul, ← one_def, mul_one]
  | succ m ih =>
    rw [pow_succ, show single (g ^ m * g) (1 : R) = single (g ^ m) 1 * single g 1 by simp,
      ← mul_assoc, mk_mul_single_eq_smul_of_sub_mem h, ih,
      smul_smul, pow_succ, mul_comm]

/-- If the left ideal `I` contains `g - c`, then `R[G] ⧸ I` is killed by `c ^ orderOf g - 1`,
since `g` acts on it as `c` and `g ^ orderOf g = 1`. -/
theorem pow_orderOf_sub_one_smul_eq_zero_of_sub_mem (h : single g (1 : R) - single 1 c ∈ I)
    (y : MonoidAlgebra R G ⧸ I) : (c ^ orderOf g - 1) • y = 0 := by
  induction y using Submodule.Quotient.induction_on with
  | H x =>
    rw [sub_smul, one_smul, ← mk_mul_single_pow_eq_pow_smul_of_sub_mem h x, pow_orderOf_eq_one,
      ← one_def, mul_one, sub_self]

end Eigenvalue

variable [Group G] {σ τ : G} {a b : R}

/-- When `σ, τ` generate a finite group `G`, the quotient `R[G] ⧸ R[G]·(σ - a, τ - b)` is a cyclic
`R`-module generated by the class of `1`: the class of every group element is a word in `a, b`
times the class of `1`. -/
theorem surjective_toSpanSingleton_mk_one [Finite G] (hgen : Subgroup.closure {σ, τ} = ⊤) :
    Function.Surjective (LinearMap.toSpanSingleton R
      (MonoidAlgebra R G ⧸ Ideal.span {single σ (1 : R) - single 1 a, single τ 1 - single 1 b})
      (Submodule.Quotient.mk 1)) := by
  rw [← LinearMap.range_eq_top, eq_top_iff]
  rintro y -
  induction y using Submodule.Quotient.induction_on with
  | H x =>
  -- The class of every group element is an `R`-multiple of the class of `1`.
  have hsingle (g : G) : (Submodule.Quotient.mk (single g (1 : R)) :
      MonoidAlgebra R G ⧸ Ideal.span {single σ (1 : R) - single 1 a, single τ 1 - single 1 b}) ∈
      LinearMap.range (LinearMap.toSpanSingleton R _ (Submodule.Quotient.mk 1)) := by
    have hg : g ∈ Submonoid.closure {σ, τ} := by
      rw [← Subgroup.closure_toSubmonoid_of_finite, hgen]
      exact Subgroup.mem_top g
    induction hg using Submonoid.closure_induction_right with
    | one => exact ⟨1, by simp [one_def]⟩
    | mul_right g _ s hs ih =>
      rw [show single (g * s) (1 : R) = single g 1 * single s 1 by simp]
      rcases hs with rfl | rfl
      · rw [mk_mul_single_eq_smul_of_sub_mem (c := a) (Ideal.subset_span (by simp))]
        exact Submodule.smul_mem _ a ih
      · rw [mk_mul_single_eq_smul_of_sub_mem (c := b) (Ideal.subset_span (by simp))]
        exact Submodule.smul_mem _ b ih
  induction x using induction_linear with
  | zero => exact Submodule.zero_mem _
  | add x y hx hy => rw [Submodule.Quotient.mk_add]; exact Submodule.add_mem _ hx hy
  | single g r =>
    rw [← mul_one r, ← smul_eq_mul, ← smul_single, Submodule.Quotient.mk_smul]
    exact Submodule.smul_mem _ r (hsingle g)

end TauCeti.MonoidAlgebra
