/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.NumberField.PrimeDiscriminantSplitting

/-!
# Prime-discriminant splitting criteria for the first genus-field examples

The multiquadratic roadmap's genus-field worked examples begin with
`ℚ(√-5)`, whose prime-discriminant generators are `-4` and `5`, and
`ℚ(√-21)`, whose prime-discriminant generators are `-4`, `-3`, and `-7`.
The general prime-discriminant splitting theorem already gives the splitting condition in a
uniform dependent form. This file records the corresponding concrete character criteria, so
later worked-example code can consume the familiar conditions directly.

The prime-discriminant convention follows Cox's *Primes of the Form x² + ny²* and
Lemmermeyer's *Reciprocity Laws*, as in the prime-discriminant splitting API this file reuses.

## Main results

* `TauCeti.NumberField.forall_legendreSym_neg_four_five_eq_one_iff`: the `-5` genus-field
  character list `[-4, 5]` is trivial at an odd prime `p` exactly when
  `p ≡ 1 (mod 4)` and `(p / 5) = 1`.
* `TauCeti.NumberField.forall_legendreSym_neg_four_neg_three_neg_seven_eq_one_iff`: the
  `-21` genus-field character list `[-4, -3, -7]` is trivial exactly when
  `p ≡ 1 (mod 4)`, `(p / 3) = 1`, and `(p / 7) = 1`.
* `TauCeti.NumberField.ncard_primesOver_neg_four_five_iff` and
  `TauCeti.NumberField.ncard_primesOver_neg_four_neg_three_neg_seven_iff`: complete-splitting
  forms for fields generated by square roots of the associated radicands.
-/

public section

open Ideal Module NumberField

namespace TauCeti.NumberField

variable {K : Type*} [Field K] [NumberField K]

/-- The prime-discriminant list `[-4, 5]` for the genus-field generators of `ℚ(√-5)`. -/
abbrev negFourFivePrimeDiscriminants : Fin 2 → ℤ :=
  ![(-4 : ℤ), 5]

/-- The prime-discriminant list `[-4, -3, -7]` for the genus-field generators of
`ℚ(√-21)`. -/
abbrev negFourNegThreeNegSevenPrimeDiscriminants : Fin 3 → ℤ :=
  ![(-4 : ℤ), -3, -7]

private theorem not_intCast_prime_dvd_neg_four {p : ℕ} [Fact p.Prime] (hodd : p ≠ 2) :
    ¬ (p : ℤ) ∣ (-4 : ℤ) := by
  intro h
  have hp_dvd_four : p ∣ 4 := by exact_mod_cast (Int.dvd_neg.mp h)
  have hp_dvd_two : p ∣ 2 := by
    have hpow : p ∣ 2 ^ 2 := by simpa using hp_dvd_four
    exact Nat.Prime.dvd_of_dvd_pow Fact.out hpow
  exact hodd ((Nat.prime_dvd_prime_iff_eq Fact.out Nat.prime_two).mp hp_dvd_two)

private theorem not_intCast_prime_dvd_natPrime {p l : ℕ} [Fact p.Prime]
    (hl : l.Prime) (hne : p ≠ l) : ¬ (p : ℤ) ∣ (l : ℤ) := by
  intro h
  have hp_dvd_l : p ∣ l := by exact_mod_cast h
  exact hne ((Nat.prime_dvd_prime_iff_eq Fact.out hl).mp hp_dvd_l)

/-- The two prime discriminants `-4` and `5` are unramified at an odd prime
different from `5`. -/
theorem forall_not_dvd_negFourFivePrimeDiscriminants {p : ℕ} [Fact p.Prime]
    (hodd : p ≠ 2) (hfive : p ≠ 5) :
    ∀ i, ¬ (p : ℤ) ∣ negFourFivePrimeDiscriminants i := by
  intro i
  fin_cases i
  · exact not_intCast_prime_dvd_neg_four hodd
  · exact not_intCast_prime_dvd_natPrime (by decide : Nat.Prime 5) hfive

/-- The three prime discriminants `-4`, `-3`, and `-7` are unramified at an odd prime
different from `3` and `7`. -/
theorem forall_not_dvd_negFourNegThreeNegSevenPrimeDiscriminants {p : ℕ} [Fact p.Prime]
    (hodd : p ≠ 2) (hthree : p ≠ 3) (hseven : p ≠ 7) :
    ∀ i, ¬ (p : ℤ) ∣ negFourNegThreeNegSevenPrimeDiscriminants i := by
  intro i
  fin_cases i
  · exact not_intCast_prime_dvd_neg_four hodd
  · simpa using not_intCast_prime_dvd_natPrime (by decide : Nat.Prime 3) hthree
  · simpa using not_intCast_prime_dvd_natPrime (by decide : Nat.Prime 7) hseven

/-- **The `ℚ(√-5)` genus-field character condition.** For an odd prime `p`, the Legendre
symbols of the prime-discriminant list `[-4, 5]` are all `1` exactly when
`p ≡ 1 (mod 4)` and the reciprocal symbol `(p / 5)` is `1`. -/
theorem forall_legendreSym_neg_four_five_eq_one_iff {p : ℕ} [Fact p.Prime] (hodd : p ≠ 2) :
    (∀ i, legendreSym p (negFourFivePrimeDiscriminants i) = 1) ↔
      p % 4 = 1 ∧ @legendreSym 5 ⟨by decide⟩ (p : ℤ) = 1 := by
  haveI : Fact (Nat.Prime 5) := ⟨by decide⟩
  constructor
  · intro h
    constructor
    · have h0 := h 0
      simpa using
        (TauCeti.Multiquadratic.legendreSym_evenPrimeDiscriminant_neg_four_eq_one_iff
          (q := p) hodd).mp h0
    · have h1 := h 1
      simpa [TauCeti.Multiquadratic.oddPrimeDiscriminant] using
        (TauCeti.Multiquadratic.legendreSym_oddPrimeDiscriminant_eq_one_iff
          (p := 5) (q := p) (by norm_num) hodd).mp h1
  · rintro ⟨hfour, hfive⟩ i
    fin_cases i
    · exact
        (TauCeti.Multiquadratic.legendreSym_evenPrimeDiscriminant_neg_four_eq_one_iff
          (q := p) hodd).mpr hfour
    · simpa [TauCeti.Multiquadratic.oddPrimeDiscriminant] using
        (TauCeti.Multiquadratic.legendreSym_oddPrimeDiscriminant_eq_one_iff
          (p := 5) (q := p) (by norm_num) hodd).mpr hfive

/-- **The `ℚ(√-21)` genus-field character condition.** For an odd prime `p`, the Legendre
symbols of the prime-discriminant list `[-4, -3, -7]` are all `1` exactly when
`p ≡ 1 (mod 4)`, `(p / 3) = 1`, and `(p / 7) = 1`. -/
theorem forall_legendreSym_neg_four_neg_three_neg_seven_eq_one_iff {p : ℕ}
    [Fact p.Prime] (hodd : p ≠ 2) :
    (∀ i, legendreSym p (negFourNegThreeNegSevenPrimeDiscriminants i) = 1) ↔
      p % 4 = 1 ∧ @legendreSym 3 ⟨by decide⟩ (p : ℤ) = 1 ∧
        @legendreSym 7 ⟨by decide⟩ (p : ℤ) = 1 := by
  haveI : Fact (Nat.Prime 3) := ⟨by decide⟩
  haveI : Fact (Nat.Prime 7) := ⟨by decide⟩
  constructor
  · intro h
    constructor
    · have h0 := h 0
      simpa using
        (TauCeti.Multiquadratic.legendreSym_evenPrimeDiscriminant_neg_four_eq_one_iff
          (q := p) hodd).mp h0
    · constructor
      · have h1 := h 1
        simpa [TauCeti.Multiquadratic.oddPrimeDiscriminant] using
          (TauCeti.Multiquadratic.legendreSym_oddPrimeDiscriminant_eq_one_iff
            (p := 3) (q := p) (by norm_num) hodd).mp h1
      · have h2 := h 2
        simpa [TauCeti.Multiquadratic.oddPrimeDiscriminant] using
          (TauCeti.Multiquadratic.legendreSym_oddPrimeDiscriminant_eq_one_iff
            (p := 7) (q := p) (by norm_num) hodd).mp h2
  · rintro ⟨hfour, hthree, hseven⟩ i
    fin_cases i
    · exact
        (TauCeti.Multiquadratic.legendreSym_evenPrimeDiscriminant_neg_four_eq_one_iff
          (q := p) hodd).mpr hfour
    · simpa [TauCeti.Multiquadratic.oddPrimeDiscriminant] using
        (TauCeti.Multiquadratic.legendreSym_oddPrimeDiscriminant_eq_one_iff
          (p := 3) (q := p) (by norm_num) hodd).mpr hthree
    · simpa [TauCeti.Multiquadratic.oddPrimeDiscriminant] using
        (TauCeti.Multiquadratic.legendreSym_oddPrimeDiscriminant_eq_one_iff
          (p := 7) (q := p) (by norm_num) hodd).mpr hseven

/-- **Complete splitting for the `ℚ(√-5)` genus-field generator list.** Let `K` be generated
by square roots of the radicands attached to `[-4, 5]`, namely `-1` and `5`. An odd prime
`p ≠ 5` splits completely in `K` exactly under the two character conditions
`p ≡ 1 (mod 4)` and `(p / 5) = 1`. -/
theorem ncard_primesOver_neg_four_five_iff (r : Fin 2 → K)
    (hr : ∀ i, r i ^ 2 = algebraMap ℤ K
      (TauCeti.Multiquadratic.primeDiscriminantRadicand
        (negFourFivePrimeDiscriminants i)))
    (htop : IntermediateField.adjoin ℚ (Set.range r) = ⊤)
    {p : ℕ} [Fact p.Prime] (hodd : p ≠ 2) (hfive : p ≠ 5) :
    (primesOver (span {(p : ℤ)}) (RingOfIntegers K)).ncard = finrank ℚ K ↔
      p % 4 = 1 ∧ @legendreSym 5 ⟨by decide⟩ (p : ℤ) = 1 :=
  (ncard_primesOver_primeDiscriminantRadicands_iff negFourFivePrimeDiscriminants r hr htop
    hodd (forall_not_dvd_negFourFivePrimeDiscriminants hodd hfive)).trans
      (forall_legendreSym_neg_four_five_eq_one_iff hodd)

/-- **Complete splitting for the `ℚ(√-21)` genus-field generator list.** Let `K` be generated
by square roots of the radicands attached to `[-4, -3, -7]`, namely `-1`, `-3`, and `-7`.
An odd prime `p` not among `3` and `7` splits completely in `K` exactly under the three
character conditions `p ≡ 1 (mod 4)`, `(p / 3) = 1`, and `(p / 7) = 1`. -/
theorem ncard_primesOver_neg_four_neg_three_neg_seven_iff (r : Fin 3 → K)
    (hr : ∀ i, r i ^ 2 = algebraMap ℤ K
      (TauCeti.Multiquadratic.primeDiscriminantRadicand
        (negFourNegThreeNegSevenPrimeDiscriminants i)))
    (htop : IntermediateField.adjoin ℚ (Set.range r) = ⊤)
    {p : ℕ} [Fact p.Prime] (hodd : p ≠ 2) (hthree : p ≠ 3) (hseven : p ≠ 7) :
    (primesOver (span {(p : ℤ)}) (RingOfIntegers K)).ncard = finrank ℚ K ↔
      p % 4 = 1 ∧ @legendreSym 3 ⟨by decide⟩ (p : ℤ) = 1 ∧
        @legendreSym 7 ⟨by decide⟩ (p : ℤ) = 1 :=
  (ncard_primesOver_primeDiscriminantRadicands_iff
    negFourNegThreeNegSevenPrimeDiscriminants r hr htop hodd
      (forall_not_dvd_negFourNegThreeNegSevenPrimeDiscriminants hodd hthree hseven)).trans
        (forall_legendreSym_neg_four_neg_three_neg_seven_eq_one_iff hodd)

end TauCeti.NumberField
