/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.Multiquadratic.LegendrePrimeDiscriminants
public import TauCeti.NumberTheory.NumberField.MultiquadraticSplitting

/-!
# Prime-discriminant splitting in multiquadratic fields

The genus-field layer indexes the quadratic factors by prime discriminants `D`, while the
multiquadratic splitting theorem is stated for the corresponding squarefree radicands
`primeDiscriminantRadicand D`. This file records the small bridge between those conventions.

The prime-discriminant convention follows the standard genus-theory convention in Cox's
*Primes of the Form x² + ny²* and Lemmermeyer's *Reciprocity Laws*.

## Main results

* `TauCeti.NumberField.ncard_primesOver_primeDiscriminantRadicands_iff`: the multiquadratic
  splitting law for a field generated by roots of prime-discriminant radicands, stated in
  terms of Legendre symbols of the prime discriminants themselves.
-/

public section

open Ideal Module NumberField

namespace TauCeti.NumberField

variable {K : Type*} [Field K] [NumberField K]

/-- **Prime-discriminant-radicand multiquadratic splitting law.** Let `K` be generated over
`ℚ` by square roots of the radicands attached to a finite family of integers `D`. For an odd
prime `p` dividing none of the `D i`, `p` splits completely in `K` exactly when every `D i` is
a quadratic residue modulo `p`. -/
theorem ncard_primesOver_primeDiscriminantRadicands_iff {ι : Type*} [Finite ι]
    (D : ι → ℤ) (r : ι → K)
    (hr : ∀ i, r i ^ 2 =
      algebraMap ℤ K (TauCeti.Multiquadratic.primeDiscriminantRadicand (D i)))
    (htop : IntermediateField.adjoin ℚ (Set.range r) = ⊤)
    {p : ℕ} [Fact p.Prime] (hodd : p ≠ 2) (hcop : ∀ i, ¬ (p : ℤ) ∣ D i) :
    (primesOver (span {(p : ℤ)}) (𝓞 K)).ncard = finrank ℚ K ↔
      ∀ i, legendreSym p (D i) = 1 := by
  have hcop_rad : ∀ i, ¬ (p : ℤ) ∣ TauCeti.Multiquadratic.primeDiscriminantRadicand (D i) :=
    (TauCeti.Multiquadratic.forall_not_dvd_primeDiscriminant_iff_radicand D hodd).mp hcop
  exact (ncard_primesOver_multiquadratic_iff
    (d := fun i => TauCeti.Multiquadratic.primeDiscriminantRadicand (D i))
    (r := r) hr htop hodd hcop_rad).trans
      (TauCeti.Multiquadratic.forall_legendreSym_primeDiscriminant_eq_one_iff_radicand
        D hodd).symm

end TauCeti.NumberField
