/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.RamifiedPrimes
public import TauCeti.NumberTheory.NumberField.WorkedExamples.GaussianRationals.Invariants
import TauCeti.NumberTheory.NumberField.Quadratic.Different
import TauCeti.NumberTheory.NumberField.Quadratic.Norm
import TauCeti.NumberTheory.NumberField.Quadratic.TotalRamification

/-!
# The dyadic ramification of `ℚ(i)`

For `K` generated over `ℚ` by an algebraic integer `θ` with `minpoly ℤ θ = X² + 1`, the prime
`2` divides the discriminant `−4`, so it ramifies: the prime `𝔭 = (1 + θ)` is the only prime of
`𝓞 K` above `2`, with `e = 2`, `f = 1` and `2 𝓞 K = 𝔭²`. The different of the monogenic ring
`𝓞 K = ℤ[θ]` is generated by `f'(θ) = 2θ`, and `θ` is a unit, so `𝔡 = (2) = 𝔭²`: the different
exponent `v_𝔭(𝔡) = 2` equals the ramification index. This is the wild dyadic case, where the
lower bound `e` of the different exponent is attained and the tame formula `e − 1` fails. Since
`v_𝔭(e) = v_𝔭(2) = 2`, the upper bound `e − 1 + v_𝔭(e) = 3` of Dedekind's different theorem is
strict here; it is attained in `ℚ(√2)`
(`TauCeti.NumberField.Sqrt2.multiplicity_differentIdeal_eq_ramificationIdx_sub_one_add`).

## Main results

* `TauCeti.NumberField.GaussianRationals.two_mem_ramifiedPrimes`: `2` ramifies, and
  `ncard_primesOver_two_eq_one`: there is one prime above it.
* `TauCeti.NumberField.GaussianRationals.eq_span_one_add`: the prime above `2` is `(1 + θ)`.
* `TauCeti.NumberField.GaussianRationals.ramificationIdx_eq_two`, `ramificationIdxIn_two_eq_two`,
  `inertiaDeg_eq_one`, `map_span_two_eq_sq`: `e = 2`, `f = 1`, and `2 𝓞 K = 𝔭²`.
* `TauCeti.NumberField.GaussianRationals.differentIdeal_eq_span_two`: `𝔡 = (2)`.
* `TauCeti.NumberField.GaussianRationals.differentIdeal_eq_sq` and
  `multiplicity_differentIdeal_eq_two`: `𝔡 = 𝔭²`, that is `v_𝔭(𝔡) = 2`.
* `TauCeti.NumberField.GaussianRationals.multiplicity_span_two_eq_two`: `v_𝔭(2) = 2`, and
  `multiplicity_differentIdeal_lt_ramificationIdx_sub_one_add`: `v_𝔭(𝔡) < e − 1 + v_𝔭(e)`.
-/

public section

open Polynomial NumberField Ideal
open scoped NumberField

namespace TauCeti.NumberField.GaussianRationals

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K}

/-- `2` ramifies in `ℚ(i)`: it divides the discriminant `−4`. -/
theorem two_mem_ramifiedPrimes (hmin : minpoly ℤ θ = X ^ 2 + 1)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) : 2 ∈ ramifiedPrimes K := by
  rw [mem_ramifiedPrimes_iff_dvd_discr Nat.prime_two, discr_eq_neg_four hmin hgen]
  norm_num

/-- The ideal `(1 + θ)` has absolute norm `2`: `N(1 + θ) = 1² − (−1) · 1²`. -/
theorem absNorm_span_one_add (hmin : minpoly ℤ θ = X ^ 2 + 1)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) : absNorm (span {1 + θ}) = 2 := by
  have h := norm_int_add_mul_gen (minpoly_eq_X_sq_sub_C hmin) hgen 1 1
  norm_num at h
  rw [absNorm_span_singleton, h]
  rfl

/-- There is a single prime of `𝓞 K` above `2`. -/
theorem ncard_primesOver_two_eq_one (hmin : minpoly ℤ θ = X ^ 2 + 1)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) :
    (primesOver (span {(2 : ℤ)}) (𝓞 K)).ncard = 1 :=
  ncard_primesOver_eq_one_of_mem_ramifiedPrimes (p := 2) (finrank_eq_two hmin hgen)
    (two_mem_ramifiedPrimes hmin hgen)

/-- **The ramification index of `2` in `ℚ(i)` is `2`**, in the form that does not name a prime
above `2`. -/
theorem ramificationIdxIn_two_eq_two (hmin : minpoly ℤ θ = X ^ 2 + 1)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) : (span {(2 : ℤ)}).ramificationIdxIn (𝓞 K) = 2 :=
  ramificationIdxIn_eq_two_of_mem_ramifiedPrimes (p := 2) (finrank_eq_two hmin hgen)
    (two_mem_ramifiedPrimes hmin hgen)

/-- **The different of `ℚ(i)` is `(2)`**: the different of `ℤ[θ]` is generated by
`f'(θ) = 2θ`, and `θ` is a unit. -/
theorem differentIdeal_eq_span_two (hmin : minpoly ℤ θ = X ^ 2 + 1)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) : differentIdeal ℤ (𝓞 K) = span {2} := by
  rw [differentIdeal_eq_span_two_mul_gen (minpoly_eq_X_sq_sub_C hmin) (adjoin_eq_top hmin hgen),
    span_singleton_mul_right_unit (isUnit hmin)]

variable (hmin : minpoly ℤ θ = X ^ 2 + 1) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
  (𝔭 : Ideal (𝓞 K)) [𝔭.IsPrime] [𝔭.LiesOver (span {(2 : ℤ)})]

include hmin hgen

/-- **The prime above `2` in `ℚ(i)` is `(1 + θ)`.** -/
theorem eq_span_one_add : 𝔭 = span {1 + θ} :=
  (eq_of_absNorm_eq_of_mem_ramifiedPrimes (p := 2) (finrank_eq_two hmin hgen)
    (two_mem_ramifiedPrimes hmin hgen) 𝔭 _ (absNorm_span_one_add hmin hgen)).symm

/-- **`2` is totally ramified in `ℚ(i)`**: `e(𝔭 ∣ 2) = 2`. -/
theorem ramificationIdx_eq_two : 𝔭.ramificationIdx ℤ = 2 :=
  ramificationIdx_eq_two_of_mem_ramifiedPrimes (p := 2) (finrank_eq_two hmin hgen)
    (two_mem_ramifiedPrimes hmin hgen) 𝔭

/-- The prime above `2` in `ℚ(i)` has residue degree `1`. -/
theorem inertiaDeg_eq_one : 𝔭.inertiaDeg ℤ = 1 :=
  inertiaDeg_eq_one_of_mem_ramifiedPrimes (p := 2) (finrank_eq_two hmin hgen)
    (two_mem_ramifiedPrimes hmin hgen) 𝔭

/-- **`2 𝓞 K = 𝔭²`** in `ℚ(i)`. -/
theorem map_span_two_eq_sq : (span {(2 : ℤ)}).map (algebraMap ℤ (𝓞 K)) = 𝔭 ^ 2 :=
  map_span_eq_sq_of_mem_ramifiedPrimes (p := 2) (finrank_eq_two hmin hgen)
    (two_mem_ramifiedPrimes hmin hgen) 𝔭

/-- **The different of `ℚ(i)` is `𝔭²`**: `𝔡 = (2) = 𝔭²`. -/
theorem differentIdeal_eq_sq : differentIdeal ℤ (𝓞 K) = 𝔭 ^ 2 := by
  rw [differentIdeal_eq_span_two hmin hgen, ← map_span_two_eq_sq hmin hgen 𝔭, map_span,
    Set.image_singleton, map_ofNat]

/-- **The different exponent at the dyadic prime is `2 = e`**: `v_𝔭(𝔡) = 2`, the wild lower
bound attained. -/
theorem multiplicity_differentIdeal_eq_two : multiplicity 𝔭 (differentIdeal ℤ (𝓞 K)) = 2 := by
  have htwo : span {(2 : ℤ)} ≠ ⊥ := span_singleton_eq_bot.not.mpr two_ne_zero
  have h𝔭 : 𝔭 ≠ ⊥ := ne_bot_of_liesOver_of_ne_bot htwo 𝔭
  rw [differentIdeal_eq_sq hmin hgen 𝔭]
  exact multiplicity_pow_self_of_prime (Ideal.prime_of_isPrime h𝔭 ‹_›) 2

/-- **The dyadic valuation of `2` in `ℚ(i)` is `2`**: `v_𝔭(2) = 2`. -/
theorem multiplicity_span_two_eq_two : multiplicity 𝔭 (span {(2 : 𝓞 K)}) = 2 := by
  rw [← differentIdeal_eq_span_two hmin hgen,
    multiplicity_differentIdeal_eq_two hmin hgen 𝔭]

/-- **The wild upper bound is strict in `ℚ(i)`**: at the dyadic prime,
`v_𝔭(𝔡) = 2 < 3 = e − 1 + v_𝔭(e)`. -/
theorem multiplicity_differentIdeal_lt_ramificationIdx_sub_one_add :
    multiplicity 𝔭 (differentIdeal ℤ (𝓞 K)) <
      𝔭.ramificationIdx ℤ - 1 + multiplicity 𝔭 (span {((𝔭.ramificationIdx ℤ : ℕ) : 𝓞 K)}) := by
  rw [multiplicity_differentIdeal_eq_two hmin hgen 𝔭, ramificationIdx_eq_two hmin hgen 𝔭,
    Nat.cast_ofNat, multiplicity_span_two_eq_two hmin hgen 𝔭]
  norm_num

end TauCeti.NumberField.GaussianRationals
