/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.CharacterTable.Values
public import Mathlib.FieldTheory.Galois.Basic
import Mathlib.NumberTheory.Cyclotomic.Basic

/-!
# Fields of character values

The field of values of a representation is the intermediate field generated by its character
values. It records the arithmetic of the character, rather than a field over which the
representation can be realized: these can differ because of the Schur index.

This file characterizes the field by its generators and identifies it with the fixed field of
the automorphisms fixing the character. The latter description works inside any finite Galois
extension containing the values. For a complex representation of a finite group, the
cyclotomic field generated by a primitive root of order the group exponent supplies such an
extension, without any field-of-definition assumption on the representation.

The fixed-field identification uses Mathlib's `IsGalois.fixedField_fixingSubgroup` and
`IntermediateField.forall_mem_adjoin_smul_eq_self_iff`.

## References

* J.-P. Serre, *Linear Representations of Finite Groups*, Section 12.4.
* I. M. Isaacs, *Character Theory of Finite Groups*, Chapter 9.
-/

public section

namespace FDRep

universe u v w

variable {k : Type u} [Field k] {G : Type v} [Monoid G]

/-- The intermediate field generated over `F` by the character values of `X`. This is a field
of values, without an assertion that `X` has a model over this field. -/
noncomputable def characterField (X : FDRep k G) (F : Type w) [Field F] [Algebra F k] :
    IntermediateField F k :=
  IntermediateField.adjoin F (Set.range X.character)

/-- Every character value belongs to the character field. -/
@[simp]
theorem character_mem_characterField (X : FDRep k G) (F : Type w) [Field F] [Algebra F k]
    (g : G) : X.character g ∈ X.characterField F :=
  IntermediateField.subset_adjoin F _ (Set.mem_range_self g)

/-- The character field is the smallest intermediate field containing all character values. -/
@[simp]
theorem characterField_le_iff (X : FDRep k G) (F : Type w) [Field F] [Algebra F k]
    (L : IntermediateField F k) : X.characterField F ≤ L ↔ ∀ g, X.character g ∈ L := by
  simp [characterField, IntermediateField.adjoin_le_iff, Set.range_subset_iff]

/-- Isomorphic representations have the same field of character values. -/
theorem characterField_eq_of_iso (X Y : FDRep k G) (e : X ≅ Y) (F : Type w) [Field F]
    [Algebra F k] : X.characterField F = Y.characterField F := by
  simp only [characterField, char_iso e]

/-- An automorphism fixes the character field pointwise exactly when it fixes the character. -/
@[simp]
theorem forall_mem_characterField_apply_eq_self_iff (X : FDRep k G) (F : Type w) [Field F]
    [Algebra F k] (σ : k ≃ₐ[F] k) :
    (∀ x ∈ X.characterField F, σ x = x) ↔ ∀ g, σ (X.character g) = X.character g := by
  simpa [characterField, Set.forall_mem_range] using
    (IntermediateField.forall_mem_adjoin_smul_eq_self_iff F
      (S := Set.range X.character) σ)

/-- Inside any finite Galois extension containing the character values, their pointwise
stabilizer has fixed field equal to the field of values, viewed in the original coefficient
field through the inclusion of the extension. -/
theorem lift_fixedField_fixingSubgroup_character (X : FDRep k G) (F : Type w) [Field F]
    [Algebra F k] (L : IntermediateField F k) [FiniteDimensional F L] [IsGalois F L]
    (hL : ∀ g, X.character g ∈ L) :
    IntermediateField.lift (F := L)
      (IntermediateField.fixedField (_root_.fixingSubgroup (L ≃ₐ[F] L)
        {x : L | (x : k) ∈ Set.range X.character})) = X.characterField F := by
  let S : Set L := {x : L | (x : k) ∈ Set.range X.character}
  have hfix : _root_.fixingSubgroup (L ≃ₐ[F] L) S =
      (IntermediateField.adjoin F S).fixingSubgroup := by
    ext σ
    rw [_root_.mem_fixingSubgroup_iff, IntermediateField.mem_fixingSubgroup_iff]
    exact (IntermediateField.forall_mem_adjoin_smul_eq_self_iff F σ).symm
  rw [hfix, IsGalois.fixedField_fixingSubgroup, IntermediateField.lift_adjoin]
  have himage : Subtype.val '' S = Set.range X.character :=
    Set.image_preimage_eq_of_subset <| by
      rintro _ ⟨g, rfl⟩
      exact ⟨⟨X.character g, hL g⟩, rfl⟩
  rw [himage]
  rfl

section FiniteGroup

variable {G : Type v} [Group G] [Finite G] [Algebra ℚ k]

/-- The field of values of a finite-group character in characteristic zero is a finite
extension of `ℚ`. -/
instance finiteDimensional_characterField (X : FDRep k G) :
    FiniteDimensional ℚ (X.characterField ℚ) := by
  let : Finite (Set.range X.character) := Set.finite_range X.character |>.to_subtype
  exact IntermediateField.finiteDimensional_adjoin fun _ ⟨g, hg⟩ ↦
    hg ▸ (X.isIntegral_character g).tower_top

end FiniteGroup

section Complex

variable {G : Type v} [Group G] [Finite G]

/-- The field of a complex character lies in the cyclotomic field of the group exponent. -/
theorem characterField_le_adjoin_of_isPrimitiveRoot (X : FDRep ℂ G) {ζ : ℂ}
    (hζ : IsPrimitiveRoot ζ (Monoid.exponent G)) :
    X.characterField ℚ ≤ IntermediateField.adjoin ℚ {ζ} := by
  rw [characterField_le_iff]
  intro g
  apply Representation.char_mem_of_forall_pow_eq_one_mem X.ρ (IsAlgClosed.splits _)
    (Monoid.pow_exponent_eq_one g)
  intro μ hμ
  exact hζ.mem_adjoin_of_pow_eq_one hμ

/-- The field of values of a complex character is the fixed field of its stabilizer in the
cyclotomic Galois group, embedded back into `ℂ`. -/
theorem lift_fixedField_fixingSubgroup_character_of_isPrimitiveRoot (X : FDRep ℂ G) {ζ : ℂ}
    (hζ : IsPrimitiveRoot ζ (Monoid.exponent G)) :
    IntermediateField.lift (F := IntermediateField.adjoin ℚ {ζ})
      (IntermediateField.fixedField (_root_.fixingSubgroup
        ((IntermediateField.adjoin ℚ {ζ}) ≃ₐ[ℚ] (IntermediateField.adjoin ℚ {ζ}))
        {x : IntermediateField.adjoin ℚ {ζ} | (x : ℂ) ∈ Set.range X.character})) =
      X.characterField ℚ := by
  let n := Monoid.exponent G
  let : NeZero n := ⟨Monoid.exponent_ne_zero_of_finite⟩
  let L := IntermediateField.adjoin ℚ {ζ}
  let : IsCyclotomicExtension {n} ℚ L :=
    (IntermediateField.isCyclotomicExtension_singleton_iff_eq_adjoin n ℚ ℂ L hζ).2 rfl
  let : FiniteDimensional ℚ L := IsCyclotomicExtension.finiteDimensional {n} ℚ L
  let : IsGalois ℚ L := IsCyclotomicExtension.isGalois {n} ℚ L
  exact X.lift_fixedField_fixingSubgroup_character ℚ L
    ((X.characterField_le_iff ℚ L).1 (X.characterField_le_adjoin_of_isPrimitiveRoot hζ))

end Complex

end FDRep
