/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.LinearAlgebra.Finsupp.LinearCombination
public import Mathlib.Topology.Algebra.Module.Basic
public import Mathlib.Topology.Compactness.Compact

/-!
# Finite spans over compact scalar rings

A submodule generated by finitely many elements over a compact scalar ring is closed in a
Hausdorff topological module. Indeed, it is the image of a finite power of the scalar ring under
the corresponding linear-combination map, hence is compact.

This elementary observation lets algebraic and topological finite generation be compared in
compact modules without any metrizability assumption.
-/

public section

namespace Set.Finite

variable {R M : Type*} [Semiring R] [TopologicalSpace R] [CompactSpace R]
  [AddCommGroup M] [Module R M] [TopologicalSpace M] [IsTopologicalAddGroup M]
  [T2Space M] [ContinuousSMul R M]

/-- The span of a finite set over a compact scalar ring is closed in a Hausdorff topological
module. -/
theorem isClosed_span {s : Set M} (hs : s.Finite) : IsClosed (Submodule.span R s : Set M) := by
  let _ := hs.fintype
  let f : (s → R) →ₗ[R] M := Fintype.linearCombination R ((↑) : s → M)
  have hf : Continuous f := by
    rw [show (f : (s → R) → M) = fun c ↦ ∑ i : s, c i • (i : M) by
      funext c
      exact Fintype.linearCombination_apply R ((↑) : s → M) c]
    fun_prop
  have hrange : IsClosed (Set.range f) := (isCompact_range hf).isClosed
  rw [← LinearMap.coe_range, Fintype.range_linearCombination,
    Subtype.range_coe_subtype, Set.ofPred_mem_eq] at hrange
  exact hrange

end Set.Finite
