/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Global.Orders.Basic

/-!
# The conductor of a number-field order

The conductor of an order `O` is the largest ideal of the maximal order contained in `O`.
Equivalently, it consists of the algebraic integers `x` for which `x * y` belongs to `O` for
every algebraic integer `y`. This ideal controls the primes where extension and contraction of
ideals between `O` and the maximal order can fail to be inverse.

The conductor here belongs to an arbitrary order. Mathlib's `conductor ℤ x` describes only the
monogenic order generated by one element.

## References

* G. S. Kopp and J. C. Lagarias, *Class Field Theory for Orders of Number Fields*, §2.
-/

public section
noncomputable section

open NumberField

namespace TauCeti.GlobalNumberFields

namespace NumberFieldOrder

variable {K : Type*} [Field K] [NumberField K]

/-- The largest ideal of `𝓞 K` whose elements all lie in the order `O`. -/
def conductor (O : NumberFieldOrder K) : Ideal (𝓞 K) where
  carrier := {x | ∀ y : 𝓞 K, (x : K) * (y : K) ∈ O.toSubalgebra}
  zero_mem' y := by simp
  add_mem' {x z} hx hz y := by
    have heq : (((x + z : 𝓞 K) : K) * (y : K)) =
        (x : K) * (y : K) + (z : K) * (y : K) := by push_cast; ring
    rw [heq]
    exact O.toSubalgebra.add_mem (hx y) (hz y)
  smul_mem' a x hx y := by
    have heq : (((a • x : 𝓞 K) : K) * (y : K)) =
        (x : K) * ((a * y : 𝓞 K) : K) := by
      push_cast
      rw [Algebra.smul_def]
      ring
    rw [heq]
    exact hx (a * y)

/-- An algebraic integer is in the conductor exactly when all of its multiples by algebraic
integers lie in the order. -/
@[simp]
theorem mem_conductor_iff (O : NumberFieldOrder K) (x : 𝓞 K) :
    x ∈ O.conductor ↔ ∀ y : 𝓞 K, (x : K) * (y : K) ∈ O.toSubalgebra := Iff.rfl

/-- The conductor is contained in the order. -/
theorem conductor_le_order (O : NumberFieldOrder K) {x : 𝓞 K}
    (hx : x ∈ O.conductor) : (x : K) ∈ O.toSubalgebra := by
  simpa using (O.mem_conductor_iff x).mp hx 1

/-- Every maximal-order ideal contained in an order lies in its conductor. -/
theorem le_conductor_iff (O : NumberFieldOrder K) (I : Ideal (𝓞 K)) :
    I ≤ O.conductor ↔ ∀ x : 𝓞 K, x ∈ I → (x : K) ∈ O.toSubalgebra := by
  constructor
  · intro h x hx
    exact O.conductor_le_order (h hx)
  · intro h x hx
    rw [O.mem_conductor_iff]
    intro y
    exact h (x * y) (I.mul_mem_right y hx)

/-- Enlarging an order enlarges its conductor ideal in the maximal order. -/
theorem conductor_mono {O O' : NumberFieldOrder K}
    (h : O.toSubalgebra ≤ O'.toSubalgebra) : O.conductor ≤ O'.conductor := by
  rw [O'.le_conductor_iff]
  intro x hx
  exact h (O.conductor_le_order hx)

/-- The conductor of the maximal order is the unit ideal. -/
@[simp]
theorem conductor_maximal : (maximalNumberFieldOrder K).conductor = ⊤ := by
  apply (maximalNumberFieldOrder K).conductor.eq_top_iff_one.mpr
  rw [mem_conductor_iff]
  intro y
  rw [maximalNumberFieldOrder_toSubalgebra]
  simpa only [map_one, one_mul] using
    ((mem_integralClosure_iff (R := ℤ) (A := K)).mpr y.isIntegral_coe :
      (y : K) ∈ integralClosure ℤ K)

/-- An order is maximal exactly when its conductor is the unit ideal. -/
@[simp]
theorem conductor_eq_top_iff (O : NumberFieldOrder K) :
    O.conductor = ⊤ ↔ O = maximalNumberFieldOrder K := by
  constructor
  · intro h
    apply ext
    rw [maximalNumberFieldOrder_toSubalgebra]
    apply le_antisymm O.le_ringOfIntegers
    intro x hx
    have hmem : (⟨x, hx⟩ : 𝓞 K) ∈ O.conductor := by
      rw [h]
      trivial
    exact O.conductor_le_order hmem
  · rintro rfl
    exact conductor_maximal

end NumberFieldOrder

end TauCeti.GlobalNumberFields
