/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Index.DedekindCubic.Basic
public import TauCeti.NumberTheory.NumberField.Index.PowerBasis
import TauCeti.NumberTheory.NumberField.Minpoly
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.LinearCombination

/-!
# The order in Dedekind's cubic field

For an integral generator `θ` with minimal polynomial `X³ - X² - 2X - 8`, the
extra integer `β = (θ² - θ)/2` enlarges the power order. The algebra generated by
`θ` and `β` has integral basis `(1, θ, β)` and discriminant `−503`.
This explicit order is the input to the index–discriminant argument identifying
the full ring of integers and to the computation of its primes above `2`.

The construction follows Neukirch, *Algebraic Number Theory*, III §2, Exercise 1.
The discriminant calculation uses Mathlib's `Algebra.discr_of_matrix_vecMul`
and the power-basis discriminant comparison.
-/

public section
noncomputable section

open Polynomial NumberField Module Matrix
open scoped NumberField

namespace TauCeti.NumberField

section Order

variable {K : Type*} [Field K] [CharZero K] {θ : 𝓞 K}

/-- The order generated by `θ` and the extra integer `(θ² - θ)/2`. -/
def dedekindOrder (hθ : θ ^ 3 - θ ^ 2 - 2 * θ - 8 = 0) : Subalgebra ℤ (𝓞 K) :=
  Algebra.adjoin ℤ {θ, dedekindBeta hθ}

/-- The generators of Dedekind's order. -/
theorem dedekindOrder_def (hθ : θ ^ 3 - θ ^ 2 - 2 * θ - 8 = 0) :
    dedekindOrder hθ = Algebra.adjoin ℤ {θ, dedekindBeta hθ} := by rfl

/-- Elements of Dedekind's order are exactly the integer linear combinations of
`1`, `θ`, and `β`. -/
@[simp] theorem mem_dedekindOrder_iff (hθ : θ ^ 3 - θ ^ 2 - 2 * θ - 8 = 0) (x : 𝓞 K) :
    x ∈ dedekindOrder hθ ↔ ∃ a b c : ℤ,
      x = a + b * θ + c * dedekindBeta hθ := by
  constructor
  · intro hx
    induction hx using Algebra.adjoin_induction with
    | mem y hy =>
      rcases Set.mem_insert_iff.mp hy with rfl | hy
      · exact ⟨0, 1, 0, by simp⟩
      · obtain rfl := Set.mem_singleton_iff.mp hy
        exact ⟨0, 0, 1, by simp⟩
    | algebraMap a => exact ⟨a, 0, 0, by simp⟩
    | add x y _ _ hx hy =>
      obtain ⟨a, b, c, rfl⟩ := hx
      obtain ⟨d, e, f, rfl⟩ := hy
      exact ⟨a + d, b + e, c + f, by push_cast; ring⟩
    | mul x y _ _ hx hy =>
      obtain ⟨a, b, c, rfl⟩ := hx
      obtain ⟨d, e, f, rfl⟩ := hy
      refine ⟨a * d + 4 * b * f + 4 * c * e - 2 * c * f,
        a * e + b * d + b * e + b * f + c * e + 2 * c * f,
        a * f + c * d + 2 * b * e + c * f, ?_⟩
      push_cast
      linear_combination (b * e : 𝓞 K) * dedekindCubic_theta_sq hθ +
        (b * f + c * e : 𝓞 K) * dedekindCubic_theta_mul_beta hθ +
        (c * f : 𝓞 K) * dedekindCubic_beta_sq hθ
  · rintro ⟨a, b, c, rfl⟩
    exact add_mem (add_mem (Subalgebra.algebraMap_mem _ a)
      (mul_mem (Subalgebra.algebraMap_mem _ b) (Algebra.subset_adjoin (by simp))))
      (mul_mem (Subalgebra.algebraMap_mem _ c) (Algebra.subset_adjoin (by simp)))

/-- The underlying module of Dedekind's order is the span of `(1, θ, β)`. -/
theorem dedekindOrder_eq_span (hθ : θ ^ 3 - θ ^ 2 - 2 * θ - 8 = 0) :
    (dedekindOrder hθ).toSubmodule =
      Submodule.span ℤ (Set.range ![1, θ, dedekindBeta hθ]) := by
  ext x
  rw [Subalgebra.mem_toSubmodule, mem_dedekindOrder_iff,
    Submodule.mem_span_range_iff_exists_fun]
  constructor
  · rintro ⟨a, b, c, rfl⟩
    exact ⟨![a, b, c], by simp [Fin.sum_univ_succ, zsmul_eq_mul, add_assoc]⟩
  · rintro ⟨a, ha⟩
    exact ⟨a 0, a 1, a 2, by simpa [Fin.sum_univ_succ, zsmul_eq_mul, add_assoc] using ha.symm⟩

end Order

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K}

/-- The discriminant of the displayed basis of Dedekind's order is `−503`.
This does not assume that the order is the full ring of integers. -/
theorem discr_dedekindOrder
    (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 - C 2 * X - C 8)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) :
    Algebra.discr ℚ ![1, (θ : K), (dedekindBeta (dedekindCubic_relation hmin) : K)] =
      -503 := by
  let t : IntegralPrimitiveElement K := ⟨θ, hgen⟩
  have hdim : t.powerBasis.dim = 3 := by
    rw [← t.powerBasis.natDegree_minpoly, IntegralPrimitiveElement.powerBasis_gen,
      RingOfIntegers.minpoly_rat_coe,
      Polynomial.Monic.natDegree_map (minpoly.monic θ.isIntegral), hmin]
    compute_degree <;> norm_num
  let b : Basis (Fin 3) ℚ K := t.powerBasis.basis.reindex (finCongr hdim)
  have hb (i : Fin 3) : b i = (θ : K) ^ (i : ℕ) := by
    dsimp only [b]
    rw [Basis.reindex_apply, PowerBasis.basis_eq_pow, t.powerBasis_gen]
    rfl
  have hb_discr : Algebra.discr ℚ b = -2012 := by
    rw [Basis.coe_reindex, Algebra.discr_reindex,
      t.discr_powerBasis_eq_minpoly_discr]
    simp only [t, hmin]
    rw [Polynomial.discr_of_degree_eq_three (by compute_degree <;> norm_num)]
    norm_num [coeff_sub, coeff_mul, coeff_X_pow, coeff_C, coeff_X]
  let P : Matrix (Fin 3) (Fin 3) ℚ := !![1, 0, 0; 0, 1, -1 / 2; 0, 0, 1 / 2]
  have hP : P.det = 1 / 2 := by norm_num [P, Matrix.det_fin_three]
  have hvec : ![1, (θ : K), (dedekindBeta (dedekindCubic_relation hmin) : K)] =
      b ᵥ* P.map (algebraMap ℚ K) := by
    ext i
    fin_cases i <;>
      simp [Matrix.vecMul, dotProduct, Fin.sum_univ_succ, P, hb]
    ring
  rw [hvec, Algebra.discr_of_matrix_vecMul, hP, hb_discr]
  norm_num

/-- The three displayed integers in Dedekind's order are linearly independent over `ℤ`. -/
theorem linearIndependent_dedekindOrder
    (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 - C 2 * X - C 8)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) :
    LinearIndependent ℤ ![1, θ, dedekindBeta (dedekindCubic_relation hmin)] := by
  have hli : LinearIndependent ℚ
      ![1, (θ : K), (dedekindBeta (dedekindCubic_relation hmin) : K)] := by
    by_contra h
    have hz := Algebra.discr_zero_of_not_linearIndependent ℚ h
    rw [discr_dedekindOrder hmin hgen] at hz
    norm_num at hz
  have hcomp : (IsScalarTower.toAlgHom ℤ (𝓞 K) K).toLinearMap ∘
      ![1, θ, dedekindBeta (dedekindCubic_relation hmin)] =
      ![1, (θ : K), (dedekindBeta (dedekindCubic_relation hmin) : K)] := by
    ext i
    fin_cases i <;> simp
  rw [← hcomp] at hli
  exact (hli.restrict_scalars' ℤ).of_comp _

/-- The integral basis `(1, θ, β)` of Dedekind's order. -/
def dedekindOrderBasis
    (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 - C 2 * X - C 8)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) :
    Basis (Fin 3) ℤ (dedekindOrder (dedekindCubic_relation hmin)) :=
  (Basis.span (linearIndependent_dedekindOrder hmin hgen)).map
    ((LinearEquiv.ofEq _ _ (dedekindOrder_eq_span _).symm).trans
      (Subalgebra.toSubmoduleEquiv _))

/-- The basis vectors of Dedekind's order, viewed as algebraic integers. -/
@[simp] theorem coe_dedekindOrderBasis
    (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 - C 2 * X - C 8)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (i : Fin 3) :
    (dedekindOrderBasis hmin hgen i : 𝓞 K) =
      ![1, θ, dedekindBeta (dedekindCubic_relation hmin)] i := by
  simp only [dedekindOrderBasis, Basis.map_apply, LinearEquiv.trans_apply,
    Subalgebra.toSubmoduleEquiv, Basis.span_apply]
  exact LinearEquiv.coe_ofEq_apply _ _

end TauCeti.NumberField
