/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.Fibers
public import TauCeti.AlgebraicGeometry.IdealSheaf.OfIdealTop

/-!
# The special fibre as the zero scheme of the maximal ideal

Let `X → Spec R` be a scheme over a local ring `R` with maximal ideal `𝔪`. Its special fibre is the
base change `X ×_{Spec R} Spec (R ⧸ 𝔪)`, a closed subscheme of `X`. This file identifies that closed
subscheme: its ideal sheaf is the quasi-coherent ideal sheaf `𝔪·𝒪_X` generated by the pullbacks of
the elements of `𝔪`. When `𝔪 = (π)` is principal, for instance when `R` is a discrete valuation
ring and `π` a uniformizer, the special fibre is therefore the zero scheme `V(π)` of the single
global function `π` pulled back to `X`.

The identification `X_s = V(π)` holds for every scheme over `R`: this file places no hypothesis on
`X`. Whether `V(π)` is an effective Cartier divisor is a separate question, which depends on `X`:
it is one exactly when the pullback of `π` is a non-zero-divisor locally on `X`, as it is when `π`
is a non-zero-divisor of `R` (for instance a uniformizer of a discrete valuation ring) and `X` is
flat over `R`, and it fails for instance for `X = Spec (R ⧸ 𝔪)`, where `π` pulls back to zero and
`X_s = X`. For a discrete valuation ring and an integral, locally Noetherian `X` flat over
`R`, this file and `TauCeti.AlgebraicGeometry.SpecialFiber.Components` give the two halves of
`X_s = div_X(π)`: the Weil divisor of `π` is supported on the components of `X_s` with their
multiplicities, and the closed subscheme cut out by the equation `π` is `X_s` itself.
`TauCeti.AlgebraicGeometry.SpecialFiber.EffectiveCartier` proves that, for `X` flat over `R` and
`π` a nonzerodivisor, `X_s` is an effective Cartier divisor with trivial ideal sheaf. Comparing
this effective Cartier divisor with the Weil divisor of `π` is not done here.

## Main results

* `TauCeti.ker_specialFiberι`: the ideal sheaf of the special fibre is `𝔪·𝒪_X`;
* `TauCeti.ker_specialFiberι_eq_ofIdealTop_span`: when `𝔪 = (π)`, it is the ideal sheaf generated
  by the pullback of `π`;
* `TauCeti.specialFiberIsoSubscheme`: the special fibre is isomorphic over `X` to the zero scheme
  of `𝔪·𝒪_X`, and `TauCeti.isPullback_subschemeι_specialFiber` records the resulting pullback
  square.

## References

* [The Stacks Project, Section 55.9](https://stacks.math.columbia.edu/tag/0C9U), the special fibre
  of a regular model as the divisor of a uniformizer.
-/

public section

noncomputable section

open CategoryTheory Limits AlgebraicGeometry IsLocalRing

namespace TauCeti

universe u

variable (R : Type u) [CommRing R] [IsLocalRing R] {X : Scheme.{u}} (toBase : X ⟶ Spec (.of R))

/-- **The special fibre is cut out by the maximal ideal.** The ideal sheaf of the special fibre of
a scheme over a local ring is the ideal sheaf `𝔪·𝒪_X` generated by the pullbacks of the elements of
the maximal ideal `𝔪` of the base. -/
theorem ker_specialFiberι :
    (specialFiberι R toBase).ker =
      Scheme.IdealSheafData.ofIdealTop
        ((maximalIdeal R).map (toBase.appTop.hom.comp (Scheme.ΓSpecIso (.of R)).inv.hom)) := by
  have := isClosedImmersion_Spec_map_residue R
  rw [specialFiberι, Scheme.Hom.ker_pullback_fst_Spec_map, CommRingCat.hom_ofHom,
    ResidueField.algebraMap_eq, ker_residue]

variable {R}

/-- **The special fibre is the zero scheme of a uniformizer.** If the maximal ideal of the base is
generated by `π`, the ideal sheaf of the special fibre is generated by the pullback of `π`: the
special fibre is the zero scheme `V(π)` of the pullback of `π` to the total space. -/
theorem ker_specialFiberι_eq_ofIdealTop_span {π : R} (hπ : maximalIdeal R = Ideal.span {π}) :
    (specialFiberι R toBase).ker =
      Scheme.IdealSheafData.ofIdealTop
        (Ideal.span {toBase.appTop ((Scheme.ΓSpecIso (.of R)).inv π)}) := by
  rw [ker_specialFiberι, hπ, Ideal.map_span, Set.image_singleton, RingHom.comp_apply]

variable (R)

/-- The special fibre of a scheme over a local ring is isomorphic, as a closed subscheme of the
total space, to the zero scheme of the ideal sheaf `𝔪·𝒪_X` generated by the maximal ideal of the
base. -/
noncomputable def specialFiberIsoSubscheme :
    (specialFiber R toBase).left ≅
      (Scheme.IdealSheafData.ofIdealTop
        ((maximalIdeal R).map
          (toBase.appTop.hom.comp (Scheme.ΓSpecIso (.of R)).inv.hom))).subscheme :=
  haveI := isClosedImmersion_specialFiberι R toBase
  have h := (Scheme.IdealSheafData.ker_subschemeι _).trans (ker_specialFiberι R toBase).symm
  haveI := IsClosedImmersion.isIso_lift _ (specialFiberι R toBase) h
  asIso (IsClosedImmersion.lift _ (specialFiberι R toBase) h.le)

/-- The identification of the special fibre with the zero scheme of `𝔪·𝒪_X` is compatible with the
inclusions into the total space. -/
@[reassoc (attr := simp)]
lemma specialFiberIsoSubscheme_hom_subschemeι :
    (specialFiberIsoSubscheme R toBase).hom ≫
        (Scheme.IdealSheafData.ofIdealTop
          ((maximalIdeal R).map
            (toBase.appTop.hom.comp (Scheme.ΓSpecIso (.of R)).inv.hom))).subschemeι =
      specialFiberι R toBase :=
  IsClosedImmersion.lift_fac _ _ _

/-- The inverse identification of the zero scheme of `𝔪·𝒪_X` with the special fibre is compatible
with the inclusions into the total space. -/
@[reassoc (attr := simp)]
lemma specialFiberIsoSubscheme_inv_specialFiberι :
    (specialFiberIsoSubscheme R toBase).inv ≫ specialFiberι R toBase =
      (Scheme.IdealSheafData.ofIdealTop
        ((maximalIdeal R).map
          (toBase.appTop.hom.comp (Scheme.ΓSpecIso (.of R)).inv.hom))).subschemeι := by
  rw [Iso.inv_comp_eq, specialFiberIsoSubscheme_hom_subschemeι]

/-- The zero scheme of `𝔪·𝒪_X`, with its inclusion into the total space and its induced morphism
to the spectrum of the residue field, is a pullback of `X → Spec R` and `Spec (R ⧸ 𝔪) → Spec R`:
it is the special fibre. -/
theorem isPullback_subschemeι_specialFiber :
    IsPullback
      (Scheme.IdealSheafData.ofIdealTop
        ((maximalIdeal R).map
          (toBase.appTop.hom.comp (Scheme.ΓSpecIso (.of R)).inv.hom))).subschemeι
      ((specialFiberIsoSubscheme R toBase).inv ≫ (specialFiber R toBase).hom)
      toBase (Spec.map (CommRingCat.ofHom (algebraMap R (ResidueField R)))) :=
  (isPullback_specialFiber R toBase).of_iso (specialFiberIsoSubscheme R toBase) (Iso.refl _)
    (Iso.refl _) (Iso.refl _)
    ((Category.comp_id _).trans (specialFiberIsoSubscheme_hom_subschemeι R toBase).symm)
    (by rw [Iso.refl_hom, Category.comp_id, Iso.hom_inv_id_assoc]) (by simp) (by simp)

end TauCeti
