/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.Sl2
public import TauCeti.Algebra.Lie.Orthogonal.TypeD.SpinCarrier.Basic
import TauCeti.Algebra.Lie.Sl2.Basic
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Coroot

/-!
# Generation of the type-D spin weight torus by root subgroups

The full-weight type-`D_n` spin carrier is defined from its positive and negative numbered
simple-root subgroups together with its split weight torus. This file proves that, over every
commutative ring, the torus is already contained in the elementary subgroup generated by those
root subgroups.

The full spin representation retains both half-spin summands, and its represented generators at
each node form an `sl_2` triple. Every row of the simply-laced type-`D` Cartan matrix contains an
entry `-1`; explicit Bezout coefficients therefore make every simple root a primitive character
of the weight torus. The generic Kostant coroot-generation theorem then makes the torus redundant
in the pointwise generating family.

The conclusion concerns subgroups of the automorphism group of the base-changed admissible
lattice. Identifying these generated points with all points of the toral-closure group scheme is a
separate scheme-theoretic comparison.

## Main results

* `TauCeti.TypeDSpinCarrier.weightTorusSubgroup_le_elementarySubgroup`: the weight torus lies in
  the elementary subgroup over every commutative ring.
* `TauCeti.TypeDSpinCarrier.weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup`: adjoining
  the weight torus to all numbered root subgroups gives exactly the elementary subgroup.

## References

* R. Steinberg, *Lectures on Chevalley Groups*, Section 3.
* R. W. Carter, *Simple Groups of Lie Type*, Sections 6.4 and 7.1.
-/

public section

open scoped Matrix TensorProduct

universe v

namespace TauCeti.TypeDSpinCarrier

open TauCeti.UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

variable (n : ℕ) (hn : 4 ≤ n)

private theorem rep_serreH_ne_zero (i : Fin n) :
    rep n hn (_root_.UniversalEnvelopingAlgebra.ι ℚ
      (TauCeti.serreH ℚ (CartanMatrix.D n) i)) ≠ 0 := by
  intro hzero
  by_cases hnext : (i : ℕ) + 1 < n
  · have hweight :=
      (isCartanWeightVector_iff
        (TauCeti.serreH ℚ (CartanMatrix.D n)) (rep n hn)).1
        ((polarization n).isCartanWeightVector_typeDSpinRep_exteriorBasis
          (polarizationBasis n) hn {i}) i
    rw [hzero, LinearMap.zero_apply] at hweight
    simp only [TauCeti.DynkinType.typeDSpinWeight_apply, dite_eq_left hnext,
      Finset.mem_singleton, ↓reduceIte] at hweight
    have hne : (⟨(i : ℕ) + 1, hnext⟩ : Fin n) ≠ i := by
      intro h
      have hval : (i : ℕ) + 1 = i := congrArg Fin.val h
      omega
    rw [ite_eq_right hne] at hweight
    simp only [sub_zero, Int.cast_one, one_smul] at hweight
    exact (polarizationBasis n).ExteriorAlgebra.ne_zero {i} hweight.symm
  · have hweight :=
      (isCartanWeightVector_iff
        (TauCeti.serreH ℚ (CartanMatrix.D n)) (rep n hn)).1
        ((polarization n).isCartanWeightVector_typeDSpinRep_exteriorBasis
          (polarizationBasis n) hn ∅) i
    rw [hzero, LinearMap.zero_apply] at hweight
    simp only [TauCeti.DynkinType.typeDSpinWeight_apply, dite_eq_right hnext,
      Finset.notMem_empty, ↓reduceIte, zero_add, zero_sub, Int.cast_neg, Int.cast_one,
      neg_smul, one_smul] at hweight
    exact (polarizationBasis n).ExteriorAlgebra.ne_zero ∅ (neg_eq_zero.mp hweight.symm)

/-- The represented positive and negative simple generators at a common type-`D` node, together
with the represented Cartan generator, form an `sl_2` triple. -/
theorem isSl2Triple_rep_rootGenerator (i : Fin n) :
    _root_.IsSl2Triple
      (rep n hn (_root_.UniversalEnvelopingAlgebra.ι ℚ
        (TauCeti.serreH ℚ (CartanMatrix.D n) i)))
      (rep n hn (_root_.UniversalEnvelopingAlgebra.ι ℚ
        (TauCeti.serreRootGenerator (CartanMatrix.D n) (.inl i))))
      (rep n hn (_root_.UniversalEnvelopingAlgebra.ι ℚ
        (TauCeti.serreRootGenerator (CartanMatrix.D n) (.inr i)))) := by
  let φ := (polarization n).typeDSpinSerreRepresentation (polarizationBasis n) hn
  have hh : φ (TauCeti.serreH ℚ (CartanMatrix.D n) i) ≠ 0 := by
    simpa only [φ, rep,
      (polarization n).typeDSpinRep_ι (polarizationBasis n) hn] using
      rep_serreH_ne_zero n hn i
  have hsource :
      _root_.IsSl2Triple
        (TauCeti.serreH ℚ (CartanMatrix.D n) i)
        (TauCeti.serreE ℚ (CartanMatrix.D n) i)
        (TauCeti.serreF ℚ (CartanMatrix.D n) i) := {
    h_ne_zero := fun hzero ↦ hh (by simp [hzero])
    lie_e_f := TauCeti.lie_serreE_serreF_self ℚ (CartanMatrix.D n) i
    lie_h_e_nsmul := by
      rw [TauCeti.lie_serreH_serreE, CartanMatrix.D_diag]
      rfl
    lie_h_f_nsmul := by
      rw [TauCeti.lie_serreH_serreF, CartanMatrix.D_diag]
      rfl
  }
  have htriple := hsource.map φ hh
  simpa only [φ, rep, TauCeti.serreRootGenerator_inl,
    TauCeti.serreRootGenerator_inr,
    (polarization n).typeDSpinRep_ι (polarizationBasis n) hn] using htriple

private def cartanNeighbor (i : Fin n) : Fin n :=
  ⟨if (i : ℕ) + 2 < n then (i : ℕ) + 1 else n - 3, by split_ifs <;> omega⟩

@[simp]
private theorem cartanNeighbor_val (i : Fin n) :
    (cartanNeighbor n hn i : ℕ) =
      if (i : ℕ) + 2 < n then (i : ℕ) + 1 else n - 3 := rfl

private def cartanBezout (i j : Fin n) : ℤ :=
  if j = cartanNeighbor n hn i then -1 else 0

private theorem cartan_sum_mul_bezout (i : Fin n) :
    ∑ j, CartanMatrix.D n i j * cartanBezout n hn i j = 1 := by
  classical
  rw [Finset.sum_eq_single (cartanNeighbor n hn i)]
  · have hentry : CartanMatrix.D n i (cartanNeighbor n hn i) = -1 := by
      simp only [CartanMatrix.D, Matrix.of_apply, Fin.ext_iff, cartanNeighbor_val]
      split_ifs <;> omega
    simp [cartanBezout, hentry]
  · intro j _ hj
    simp [cartanBezout, hj]
  · simp

private theorem rootWeight_sum_mul_bezout (i : Fin n) :
    ∑ j, TypeDStd.rootGeneratorWeight n (.inl i) j * cartanBezout n hn i j = 1 := by
  simpa only [TypeDStd.rootGeneratorWeight_inl] using cartan_sum_mul_bezout n hn i

private theorem rootWeight_inr_eq_neg_inl (i : Fin n) :
    TypeDStd.rootGeneratorWeight n (.inr i) =
      -TypeDStd.rootGeneratorWeight n (.inl i) := by
  funext j
  simp

/-- Over every commutative ring, the type-`D` full-spin weight torus on the base-changed
admissible lattice is contained in the elementary group generated by the positive and negative
numbered simple root subgroups. -/
theorem weightTorusSubgroup_le_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubgroup (lattice n).toAddSubgroup
        (latticeBasis n) (basisWeight n) A ≤
      kostantElementarySubgroup (TauCeti.serreRootGenerator (CartanMatrix.D n))
        (TauCeti.serreH ℚ (CartanMatrix.D n)) (rep n hn)
        (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n hn)
        (isNilpotent_rep_rootGenerator n hn) A := by
  exact kostantTorusSubgroup_le_kostantElementarySubgroup
    (TauCeti.serreRootGenerator (CartanMatrix.D n))
    (TauCeti.serreH ℚ (CartanMatrix.D n)) (rep n hn)
    (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n hn)
    (isNilpotent_rep_rootGenerator n hn) (latticeBasis n) (basisWeight n)
    (isCartanWeightVector_latticeBasis n hn) (TypeDStd.rootGeneratorWeight n)
    (TypeDStd.lie_serreH_serreRootGenerator n) Sum.inl Sum.inr
    (isSl2Triple_rep_rootGenerator n hn) (rootWeight_inr_eq_neg_inl n)
    (cartanBezout n hn) (rootWeight_sum_mul_bezout n hn) A

/-- Over every commutative ring, adjoining the type-`D` full-spin weight torus to all positive and
negative numbered simple root subgroups does not enlarge their elementary subgroup. -/
theorem weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubsystemSubgroup (TauCeti.serreRootGenerator (CartanMatrix.D n))
        (TauCeti.serreH ℚ (CartanMatrix.D n)) (rep n hn)
        (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n hn)
        (isNilpotent_rep_rootGenerator n hn) (latticeBasis n) (basisWeight n) Set.univ A =
      kostantElementarySubgroup (TauCeti.serreRootGenerator (CartanMatrix.D n))
        (TauCeti.serreH ℚ (CartanMatrix.D n)) (rep n hn)
        (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n hn)
        (isNilpotent_rep_rootGenerator n hn) A := by
  exact kostantTorusSubsystemSubgroup_univ_eq_kostantElementarySubgroup
    (TauCeti.serreRootGenerator (CartanMatrix.D n))
    (TauCeti.serreH ℚ (CartanMatrix.D n)) (rep n hn)
    (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n hn)
    (isNilpotent_rep_rootGenerator n hn) (latticeBasis n) (basisWeight n)
    (isCartanWeightVector_latticeBasis n hn) (TypeDStd.rootGeneratorWeight n)
    (TypeDStd.lie_serreH_serreRootGenerator n) Sum.inl Sum.inr
    (isSl2Triple_rep_rootGenerator n hn) (rootWeight_inr_eq_neg_inl n)
    (cartanBezout n hn) (rootWeight_sum_mul_bezout n hn) A

end TauCeti.TypeDSpinCarrier
