/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.PolynomialFamily
public import TauCeti.LinearAlgebra.Matrix.GeneralLinearGroup.Transvection
public import TauCeti.RepresentationTheory.ClassicalGroups.Weight.Decomposition
public import TauCeti.RepresentationTheory.ClassicalGroups.Weight.Weyl

/-!
# Highest weight vectors of a rational representation of `GL n`

A rational representation of `GL n ℂ` is the internal direct sum of its weight spaces
(`TauCeti.IsRationalRep.isInternal_weightSpace`), so it has only finitely many weights. This file
produces a **highest weight vector** out of them: a nonzero weight vector, of a *dominant* weight,
annihilated by the raising operators in the sense that every transvection `xᵢⱼ(c)` with `i < j`
fixes it.

That is the group-level form of a vector killed by the positive nilradical, and it is the step the
highest-weight classification of the irreducible rational representations of `GL n` rests on: the
line it produces is the line a highest weight module is generated by.

## Transvections raise weights

Everything rests on one computation. Conjugating the transvection `xᵢⱼ(c)` by a diagonal matrix
rescales its parameter by the value `tᵢ tⱼ⁻¹` of the root `εᵢ - εⱼ`
(`TauCeti.diagGL_mul_transvectionUnit_mul_inv`), so if `w` has weight `l` then `xᵢⱼ(c) w`
transforms under the torus exactly as an expansion in the weights `l + m (εᵢ - εⱼ)` does.

Turning that into an identification of the individual terms needs the dependence on `c` to be
*polynomial*, and this is where rationality enters and cannot be dropped: the transvection has
determinant one and entries affine in `c`, so each matrix entry of `ρ (xᵢⱼ(c))` is a polynomial in
`c` (`TauCeti.IsRationalRep.exists_forall_transvectionUnit_eq_sum_smul`), and the coefficients of
a polynomial identity over an infinite field are determined
(`TauCeti.eq_of_forall_sum_range_pow_smul_eq`). The `m`-th coefficient then lands in the weight
space of `l + m (εᵢ - εⱼ)`. Only nonnegative `m` occur, and that is exactly what a rational — as
opposed to merely torus-eigen — representation buys: the negative powers a Laurent expansion would
allow are what would break the argument.

Consequently a weight vector all of whose raised weight spaces vanish is fixed by the whole root
subgroup, and maximizing the height `∑ᵢ (n - i) lᵢ` over the finitely many weights produces such a
weight. The maximizer is weakly decreasing, since transposing two out-of-order entries raises the
height while permutations of a weight are again weights
(`TauCeti.weightSpace_eq_bot_comp_perm_iff`).

## Main results

* `TauCeti.weightChar_add_nsmul_single_sub_single`: a multiple of the root `εᵢ - εⱼ` translates a
  weight character by a power of `tᵢ tⱼ⁻¹`.
* `TauCeti.IsRationalRep.exists_forall_transvectionUnit_eq_sum_smul`: the action along a root
  subgroup is polynomial in the parameter.
* `TauCeti.apply_mem_weightSpace_of_forall_transvectionUnit_eq_sum_smul`: the `m`-th coefficient
  of that expansion carries a vector of weight `l` into the weight space of `l + m (εᵢ - εⱼ)`.
* `TauCeti.IsRationalRep.apply_transvectionUnit_eq_self`: a weight vector all of whose raised
  weight spaces vanish is fixed by the root subgroup.
* `TauCeti.IsRationalRep.finite_setOf_weightSpace_ne_bot`: a rational representation has only
  finitely many weights.
* `TauCeti.IsRationalRep.exists_highestWeightVector`: **a nonzero rational representation has a
  highest weight vector**, of a dominant weight.

## References

* W. Fulton and J. Harris, *Representation Theory: A First Course* (1991), Lecture 15.
* R. Goodman and N. R. Wallach, *Symmetry, Representations, and Invariants* (2009), Chapter 3.
-/

public section

open Matrix

universe u

namespace TauCeti

variable {n : ℕ}

/-! ## The character of a multiple of a root -/

/-- **A multiple of the root `εᵢ - εⱼ` translates a weight character by a power of `tᵢ tⱼ⁻¹`.**
This is the only property of that root the raising computation below uses. -/
theorem weightChar_add_nsmul_single_sub_single {R : Type*} [CommRing R] {i j : Fin n}
    (hij : i ≠ j) (l : Fin n → ℤ) (m : ℕ) (t : Fin n → Rˣ) :
    weightChar R (l + m • (Pi.single i 1 - Pi.single j 1)) t
      = weightChar R l t * (t i * (t j)⁻¹) ^ m := by
  classical
  have hi : (Pi.single i 1 - Pi.single j 1 : Fin n → ℤ) i = 1 := by
    rw [Pi.sub_apply, Pi.single_eq_same, Pi.single_eq_of_ne hij, sub_zero]
  have hj : (Pi.single i 1 - Pi.single j 1 : Fin n → ℤ) j = -1 := by
    rw [Pi.sub_apply, Pi.single_eq_same, Pi.single_eq_of_ne hij.symm, zero_sub]
  have hvanish : ∀ a : Fin n, a ∉ ({i, j} : Finset (Fin n)) →
      t a ^ ((m • (Pi.single i 1 - Pi.single j 1) : Fin n → ℤ) a) = 1 := by
    intro a ha
    simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at ha
    rw [Pi.smul_apply, Pi.sub_apply, Pi.single_eq_of_ne ha.1, Pi.single_eq_of_ne ha.2]
    simp
  have hprod : ∏ a ∈ ({i, j} : Finset (Fin n)),
        t a ^ ((m • (Pi.single i 1 - Pi.single j 1) : Fin n → ℤ) a)
      = ∏ a : Fin n, t a ^ ((m • (Pi.single i 1 - Pi.single j 1) : Fin n → ℤ) a) :=
    Finset.prod_subset (Finset.subset_univ _) fun a _ ha ↦ hvanish a ha
  rw [weightChar_add, MonoidHom.mul_apply]
  refine congrArg (weightChar R l t * ·) ?_
  rw [weightChar_apply, torusCharacter_def, ← hprod, Finset.prod_pair hij, Pi.smul_apply,
    Pi.smul_apply, hi, hj]
  simp [zpow_neg, mul_pow, inv_pow]

/-! ## The action along a root subgroup is polynomial -/

variable {W : Type u} [AddCommGroup W] [Module ℂ W] {ρ : Representation ℂ (GL (Fin n) ℂ) W}

/-- **The action along a root subgroup is polynomial in its parameter.** The transvection
`xᵢⱼ(c)` has determinant one and entries affine in `c`, so for a rational representation each
matrix entry of `ρ (xᵢⱼ(c))` is a polynomial in `c`, and the action is a finite sum
`∑ m < d, c ^ m • A m` whose coefficients do not depend on `c`. -/
theorem IsRationalRep.exists_forall_transvectionUnit_eq_sum_smul (h : IsRationalRep ρ)
    {i j : Fin n} (hij : i ≠ j) :
    ∃ (d : ℕ) (A : ℕ → Module.End ℂ W),
      ∀ c : ℂ, ρ (transvectionUnit hij c) = ∑ m ∈ Finset.range d, c ^ m • A m := by
  classical
  obtain ⟨b, P, N, hP⟩ := (isRationalRep_iff ρ).mp h
  set E : Fin n × Fin n → Polynomial ℂ := fun q ↦
    (Matrix.transvection i j (Polynomial.X : Polynomial ℂ)) q.1 q.2 with hE
  have hEeval : ∀ (c : ℂ) (q : Fin n × Fin n),
      Polynomial.eval c (E q) = (transvectionUnit hij c : Matrix (Fin n) (Fin n) ℂ) q.1 q.2 := by
    intro c q
    rw [hE, coe_transvectionUnit]
    simp only [Matrix.transvection, Matrix.single, Matrix.add_apply, Matrix.of_apply,
      Matrix.one_apply, Polynomial.eval_add, apply_ite (Polynomial.eval c),
      Polynomial.eval_one, Polynomial.eval_zero, Polynomial.eval_X]
  refine exists_forall_eq_sum_pow_smul_of_toMatrix_eq_eval b
    (fun c ↦ ρ (transvectionUnit hij c)) (fun a a' ↦ MvPolynomial.aeval E (P a a'))
    (fun c a a' ↦ ?_)
  have hdet : ((transvectionUnit hij c : GL (Fin n) ℂ) :
      Matrix (Fin n) (Fin n) ℂ).det = 1 := by
    rw [coe_transvectionUnit]
    exact Matrix.det_transvection_of_ne i j hij c
  have hcomp : Polynomial.eval c (MvPolynomial.aeval E (P a a'))
      = MvPolynomial.eval (fun q ↦ Polynomial.eval c (E q)) (P a a') := by
    simpa only [Polynomial.coe_aeval_eq_eval, MvPolynomial.aeval_eq_eval] using
      MvPolynomial.comp_aeval_apply (f := E) (Polynomial.aeval (R := ℂ) c) (P a a')
  rw [hP (transvectionUnit hij c) a a', hdet, one_pow, inv_one, one_mul, hcomp]
  exact congrArg (fun g ↦ MvPolynomial.eval g (P a a')) (funext fun q ↦ (hEeval c q).symm)

/-! ## Transvections raise weights -/

/-- **The coefficients of the root-subgroup expansion raise the weight.** If the action along the
root subgroup of `εᵢ - εⱼ` expands as `∑ m < d, c ^ m • A m`, then `A m` carries a vector of
weight `l` into the weight space of `l + m (εᵢ - εⱼ)`. -/
theorem apply_mem_weightSpace_of_forall_transvectionUnit_eq_sum_smul
    {i j : Fin n} (hij : i ≠ j) {d : ℕ} {A : ℕ → Module.End ℂ W}
    (hA : ∀ c : ℂ, ρ (transvectionUnit hij c) = ∑ m ∈ Finset.range d, c ^ m • A m)
    {l : Fin n → ℤ} {w : W} (hw : w ∈ weightSpace ρ l) {m : ℕ} (hm : m < d) :
    A m w ∈ weightSpace ρ (l + m • (Pi.single i 1 - Pi.single j 1)) := by
  rw [mem_weightSpace_iff]
  intro t
  have hexpand : ∀ e : ℂ, ρ (transvectionUnit hij e) w
      = ∑ m' ∈ Finset.range d, e ^ m' • A m' w := by
    intro e
    rw [hA e, LinearMap.sum_apply]
    exact Finset.sum_congr rfl fun m' _ ↦ rfl
  refine eq_of_forall_sum_range_pow_smul_eq (K := ℂ)
    (u := fun m' ↦ ρ (diagGL t) (A m' w))
    (v := fun m' ↦ ((weightChar ℂ (l + m' • (Pi.single i 1 - Pi.single j 1)) t : ℂˣ) : ℂ) •
      A m' w) (fun c ↦ ?_) hm
  have hconj : (diagGL t : GL (Fin n) ℂ) * transvectionUnit hij c
      = transvectionUnit hij (((t i * (t j)⁻¹ : ℂˣ) : ℂ) * c) * diagGL t := by
    rw [show (((t i * (t j)⁻¹ : ℂˣ) : ℂ) * c) = (t i : ℂ) * c * (((t j)⁻¹ : ℂˣ) : ℂ) by
        push_cast; ring,
      ← diagGL_mul_transvectionUnit_mul_inv hij t c]
    group
  have hlhs : ∑ m' ∈ Finset.range d, c ^ m' • ρ (diagGL t) (A m' w)
      = ((weightChar ℂ l t : ℂˣ) : ℂ) •
        ∑ m' ∈ Finset.range d, (((t i * (t j)⁻¹ : ℂˣ) : ℂ) * c) ^ m' • A m' w := by
    rw [← hexpand, ← map_smul, ← apply_of_mem_weightSpace hw t, ← Module.End.mul_apply,
      ← map_mul, ← hconj, map_mul, Module.End.mul_apply, hexpand, map_sum]
    exact Finset.sum_congr rfl fun m' _ ↦ (map_smul _ _ _).symm
  have hrhs : ∑ m' ∈ Finset.range d,
      c ^ m' • (((weightChar ℂ (l + m' • (Pi.single i 1 - Pi.single j 1)) t : ℂˣ) : ℂ) • A m' w)
      = ((weightChar ℂ l t : ℂˣ) : ℂ) •
        ∑ m' ∈ Finset.range d, (((t i * (t j)⁻¹ : ℂˣ) : ℂ) * c) ^ m' • A m' w := by
    rw [Finset.smul_sum]
    refine Finset.sum_congr rfl fun m' _ ↦ ?_
    rw [weightChar_add_nsmul_single_sub_single hij l m' t, smul_smul, smul_smul]
    refine congrArg (· • A m' w) ?_
    push_cast
    ring
  rw [hlhs, hrhs]

/-- **A weight vector all of whose raised weight spaces vanish is fixed by the root subgroup.**
This is the group-level form of a vector annihilated by a raising operator. -/
theorem IsRationalRep.apply_transvectionUnit_eq_self (h : IsRationalRep ρ) {i j : Fin n}
    (hij : i ≠ j) {l : Fin n → ℤ} {w : W} (hw : w ∈ weightSpace ρ l)
    (hbot : ∀ m : ℕ, 0 < m → weightSpace ρ (l + m • (Pi.single i 1 - Pi.single j 1)) = ⊥)
    (c : ℂ) : ρ (transvectionUnit hij c) w = w := by
  obtain ⟨d, A, hA⟩ := h.exists_forall_transvectionUnit_eq_sum_smul hij
  have hexpand : ∀ e : ℂ, ρ (transvectionUnit hij e) w
      = ∑ m ∈ Finset.range d, e ^ m • A m w := by
    intro e
    rw [hA e, LinearMap.sum_apply]
    exact Finset.sum_congr rfl fun m _ ↦ rfl
  rcases Nat.eq_zero_or_pos d with rfl | hd
  · have hw0 : w = 0 := by
      have h1 := hexpand 0
      rw [transvectionUnit_zero, map_one, Module.End.one_apply, Finset.range_zero,
        Finset.sum_empty] at h1
      exact h1
    rw [hw0, map_zero]
  · have hzero : ∀ m ∈ Finset.range d, m ≠ 0 → c ^ m • A m w = 0 := by
      intro m hm hm0
      rw [(Submodule.eq_bot_iff _).mp (hbot m (Nat.pos_of_ne_zero hm0)) _
        (apply_mem_weightSpace_of_forall_transvectionUnit_eq_sum_smul hij hA hw
          (Finset.mem_range.mp hm)), smul_zero]
    have hA0 : A 0 w = w := by
      have h1 := hexpand 0
      rw [transvectionUnit_zero, map_one, Module.End.one_apply,
        Finset.sum_eq_single_of_mem 0 (Finset.mem_range.mpr hd)
          (fun m _ hm ↦ by rw [zero_pow hm, zero_smul]), pow_zero, one_smul] at h1
      exact h1.symm
    rw [hexpand c, Finset.sum_eq_single_of_mem 0 (Finset.mem_range.mpr hd) hzero, pow_zero,
      one_smul, hA0]

/-! ## Finitely many weights, and the highest one -/

/-- **A rational representation has only finitely many weights.** Its weight spaces are
independent and its carrier is finite dimensional, so only finitely many of them are nonzero. -/
theorem IsRationalRep.finite_setOf_weightSpace_ne_bot (h : IsRationalRep ρ) :
    {l : Fin n → ℤ | weightSpace ρ l ≠ ⊥}.Finite := by
  have _ : Module.Finite ℂ W := h.finite
  have hfin : Finite { l : Fin n → ℤ // weightSpace ρ l ≠ ⊥ } :=
    @Fintype.finite _
      (iSupIndep_weightSpace (k := ℂ) weightChar_injective ρ).fintypeNeBotOfFiniteDimensional
  exact Set.finite_coe_iff.mp hfin

/-- The height of a weight: the linear functional that strictly increases along every positive
root `εᵢ - εⱼ` with `i < j`. It is a device for selecting a maximal weight, not part of the weight
theory, so it stays private to this file. -/
private def weightHeight (l : Fin n → ℤ) : ℤ := ∑ a : Fin n, ((n : ℤ) - (a : ℕ)) * l a

private theorem weightHeight_add_nsmul_single_sub_single (l : Fin n → ℤ) {i j : Fin n}
    (hij : i ≠ j) (m : ℕ) :
    weightHeight (l + m • (Pi.single i 1 - Pi.single j 1))
      = weightHeight l + m * (((j : ℕ) : ℤ) - ((i : ℕ) : ℤ)) := by
  classical
  have hi : (Pi.single i 1 - Pi.single j 1 : Fin n → ℤ) i = 1 := by
    rw [Pi.sub_apply, Pi.single_eq_same, Pi.single_eq_of_ne hij, sub_zero]
  have hj : (Pi.single i 1 - Pi.single j 1 : Fin n → ℤ) j = -1 := by
    rw [Pi.sub_apply, Pi.single_eq_same, Pi.single_eq_of_ne hij.symm, zero_sub]
  have hvanish : ∀ a : Fin n, a ∉ ({i, j} : Finset (Fin n)) →
      ((n : ℤ) - (a : ℕ)) * ((m • (Pi.single i 1 - Pi.single j 1) : Fin n → ℤ) a) = 0 := by
    intro a ha
    simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at ha
    rw [Pi.smul_apply, Pi.sub_apply, Pi.single_eq_of_ne ha.1, Pi.single_eq_of_ne ha.2]
    simp
  have hsum : ∑ a ∈ ({i, j} : Finset (Fin n)),
        ((n : ℤ) - (a : ℕ)) * ((m • (Pi.single i 1 - Pi.single j 1) : Fin n → ℤ) a)
      = ∑ a : Fin n,
        ((n : ℤ) - (a : ℕ)) * ((m • (Pi.single i 1 - Pi.single j 1) : Fin n → ℤ) a) :=
    Finset.sum_subset (Finset.subset_univ _) fun a _ ha ↦ hvanish a ha
  have hsplit : weightHeight (l + m • (Pi.single i 1 - Pi.single j 1))
      = weightHeight l
        + ∑ a : Fin n, ((n : ℤ) - (a : ℕ)) *
            ((m • (Pi.single i 1 - Pi.single j 1) : Fin n → ℤ) a) := by
    rw [weightHeight, weightHeight, ← Finset.sum_add_distrib]
    exact Finset.sum_congr rfl fun a _ ↦ by rw [Pi.add_apply, mul_add]
  rw [hsplit, ← hsum, Finset.sum_pair hij, Pi.smul_apply, Pi.smul_apply, hi, hj]
  ring

private theorem weightHeight_comp_swap (l : Fin n → ℤ) {a b : Fin n} (hab : a ≠ b) :
    weightHeight (l ∘ ⇑(Equiv.swap a b))
      = weightHeight l + (((b : ℕ) : ℤ) - ((a : ℕ) : ℤ)) * (l b - l a) := by
  classical
  have hvanish : ∀ x : Fin n, x ∉ ({a, b} : Finset (Fin n)) →
      ((n : ℤ) - (x : ℕ)) * (l ∘ ⇑(Equiv.swap a b)) x - ((n : ℤ) - (x : ℕ)) * l x = 0 := by
    intro x hx
    simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at hx
    rw [Function.comp_apply, Equiv.swap_apply_of_ne_of_ne hx.1 hx.2, sub_self]
  have hsum : ∑ x ∈ ({a, b} : Finset (Fin n)),
        (((n : ℤ) - (x : ℕ)) * (l ∘ ⇑(Equiv.swap a b)) x - ((n : ℤ) - (x : ℕ)) * l x)
      = ∑ x : Fin n,
        (((n : ℤ) - (x : ℕ)) * (l ∘ ⇑(Equiv.swap a b)) x - ((n : ℤ) - (x : ℕ)) * l x) :=
    Finset.sum_subset (Finset.subset_univ _) fun x _ hx ↦ hvanish x hx
  have key : weightHeight (l ∘ ⇑(Equiv.swap a b)) - weightHeight l
      = (((b : ℕ) : ℤ) - ((a : ℕ) : ℤ)) * (l b - l a) := by
    rw [weightHeight, weightHeight, ← Finset.sum_sub_distrib, ← hsum, Finset.sum_pair hab,
      Function.comp_apply, Function.comp_apply, Equiv.swap_apply_left, Equiv.swap_apply_right]
    ring
  linarith [key]

/-- **A nonzero rational representation of `GL n ℂ` has a highest weight vector.** There is a
dominant weight `l` and a nonzero vector `w` of weight `l` that every transvection `xᵢⱼ(c)` with
`i < j` fixes.

The weight is dominant, and the fixed vector nonzero, so this is the input to the highest-weight
classification: the subrepresentation generated by `w` is a highest weight module of weight `l`. -/
theorem IsRationalRep.exists_highestWeightVector [Nontrivial W] (h : IsRationalRep ρ) :
    ∃ (l : DominantWeight n) (w : W), w ≠ 0 ∧ w ∈ weightSpace ρ (l : Fin n → ℤ) ∧
      ∀ (i j : Fin n) (hij : i < j) (c : ℂ), ρ (transvectionUnit hij.ne c) w = w := by
  classical
  have hfin := h.finite_setOf_weightSpace_ne_bot
  have hne : {l : Fin n → ℤ | weightSpace ρ l ≠ ⊥}.Nonempty := by
    by_contra hemp
    rw [Set.not_nonempty_iff_eq_empty] at hemp
    have htop : (⊤ : Submodule ℂ W) = ⊥ := by
      rw [← h.iSup_weightSpace_eq_top]
      refine iSup_eq_bot.mpr fun l ↦ ?_
      by_contra hl
      have hmem : l ∈ {l : Fin n → ℤ | weightSpace ρ l ≠ ⊥} := hl
      rw [hemp] at hmem
      exact Set.notMem_empty l hmem
    exact absurd htop top_ne_bot
  obtain ⟨l0, hl0mem, hl0max⟩ := Finset.exists_max_image hfin.toFinset weightHeight
    (by simpa [Set.Finite.toFinset_nonempty] using hne)
  rw [Set.Finite.mem_toFinset] at hl0mem
  have hmax : ∀ l : Fin n → ℤ, weightSpace ρ l ≠ ⊥ → weightHeight l ≤ weightHeight l0 :=
    fun l hl ↦ hl0max l ((Set.Finite.mem_toFinset hfin).mpr hl)
  have hanti : Antitone l0 := by
    intro a b hab
    by_contra hlt
    rw [not_le] at hlt
    have hne' : a ≠ b := fun hh ↦ absurd (hh ▸ hlt) (lt_irrefl _)
    have hl0ne : weightSpace ρ l0 ≠ ⊥ := hl0mem
    have hswap : weightSpace ρ (l0 ∘ ⇑(Equiv.swap a b)) ≠ ⊥ := fun hh ↦
      hl0ne ((weightSpace_eq_bot_comp_perm_iff ρ (Equiv.swap a b) l0).mp hh)
    have hgt : weightHeight l0 < weightHeight (l0 ∘ ⇑(Equiv.swap a b)) := by
      rw [weightHeight_comp_swap l0 hne']
      have hab' : ((a : ℕ) : ℤ) < ((b : ℕ) : ℤ) := by
        exact_mod_cast Fin.lt_def.mp (lt_of_le_of_ne hab hne')
      nlinarith [sub_pos.mpr hab', sub_pos.mpr hlt]
    exact absurd (hmax _ hswap) (not_le.mpr hgt)
  obtain ⟨w, hw, hw0⟩ := (Submodule.ne_bot_iff _).mp hl0mem
  refine ⟨⟨l0, hanti⟩, w, hw0, hw, fun i j hij c ↦ ?_⟩
  refine h.apply_transvectionUnit_eq_self hij.ne hw (fun m hm ↦ ?_) c
  by_contra hbot
  have hgt : weightHeight l0
      < weightHeight (l0 + m • (Pi.single i 1 - Pi.single j 1)) := by
    rw [weightHeight_add_nsmul_single_sub_single l0 hij.ne m]
    have hij' : ((i : ℕ) : ℤ) < ((j : ℕ) : ℤ) := by
      exact_mod_cast Fin.lt_def.mp hij
    have hm' : (0 : ℤ) < (m : ℤ) := by exact_mod_cast hm
    nlinarith [sub_pos.mpr hij']
  exact absurd (hmax _ hbot) (not_le.mpr hgt)

end TauCeti
