/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Group.Subgroup.TwoTorsionClosure
public import TauCeti.NumberTheory.DirichletCharacter.Conductor
public import TauCeti.NumberTheory.Multiquadratic.Legendre.PrimeDiscriminant.Dirichlet.Character
public import Mathlib.Data.Fintype.Sets

/-!
# The character group of a prime-discriminant family

Let `s` be a finite family of distinct prime discriminants, with at most one even member, and put
`N = |∏ P ∈ s, P|`. Each quadratic character belonging to a factor `P` can be lifted to level
`N`. The products of these lifted characters are indexed by subsets of `s`: multiplication of
characters corresponds to symmetric difference of subsets, and the conductor of the character
indexed by `t` is `|∏ P ∈ t, P|`.

Consequently the subgroup generated by the factor characters has exactly `2 ^ #s` elements. This
is the character-group counterpart of the degree-`2 ^ #s` prime-discriminant compositum. It is
the input for combining the individual quadratic character fixed fields inside one cyclotomic
field.

The prime-discriminant description is classical; see K. Ireland and M. Rosen, *A Classical
Introduction to Modern Number Theory*, Chapter 6, and D. A. Cox, *Primes of the Form x² + ny²*,
§§3.B and 6.A.

## Main definitions and results

* `primeDiscriminantCharAt`: the character of one factor, lifted to the common level.
* `genusCharAt`: the product character indexed by a subset of the factors.
* `genusCharAt_symmDiff`: multiplication corresponds to symmetric difference.
* `conductor_genusCharAt`: the conductor is the product of the factor conductors.
* `genusCharacterGroup`: the subgroup consisting of all subset characters.
* `genusCharAtEquiv`: the subsets of `s` are in bijection with that subgroup.
-/

public section

open scoped symmDiff

namespace TauCeti.Multiquadratic

open DirichletCharacter

variable (s : Finset ℤ) (hs : ∀ P ∈ s, IsPrimeDiscriminant P)

private lemma prod_ne_zero (hs : ∀ P ∈ s, IsPrimeDiscriminant P) : ∏ P ∈ s, P ≠ 0 :=
  Finset.prod_ne_zero_iff.mpr fun P hP ↦ (hs P hP).ne_zero

private theorem prodNatAbsNeZero (hs : ∀ P ∈ s, IsPrimeDiscriminant P) :
    NeZero (∏ P ∈ s, P).natAbs :=
  ⟨Int.natAbs_ne_zero.mpr (prod_ne_zero s hs)⟩

/-- The character of a prime-discriminant factor, lifted to the common level
`|∏ P ∈ s, P|`. -/
noncomputable def primeDiscriminantCharAt (P : s) :
    DirichletCharacter ℤ (∏ Q ∈ s, Q).natAbs :=
  changeLevel (Int.natAbs_dvd_natAbs.mpr (Finset.dvd_prod_of_mem id P.property))
    (primeDiscriminantChar P (hs P P.property))

/-- At an integer coprime to the common level, a lifted prime-discriminant character agrees with
the character attached to its factor. -/
theorem primeDiscriminantCharAt_apply_int (P : s) (n : ℤ)
    (hn : IsCoprime n (∏ Q ∈ s, Q).natAbs) :
    primeDiscriminantCharAt s hs P n = primeDiscriminantChar P (hs P P.property) n := by
  rw [primeDiscriminantCharAt, changeLevel_eq_cast_of_dvd' _ _ hn]

/-- The conductor of a lifted prime-discriminant character is the absolute value of its factor. -/
@[simp] theorem conductor_primeDiscriminantCharAt (P : s) :
    (primeDiscriminantCharAt s hs P).conductor = P.val.natAbs := by
  let _ := prodNatAbsNeZero s hs
  rw [primeDiscriminantCharAt, conductor_changeLevel]
  exact isPrimitive_primeDiscriminantChar P (hs P P.property)

/-- A lifted prime-discriminant character is quadratic. -/
theorem isQuadratic_primeDiscriminantCharAt (P : s) :
    (primeDiscriminantCharAt s hs P).IsQuadratic := by
  apply MulChar.isQuadratic_iff_sq_eq_one.mpr
  have hquad := isQuadratic_primeDiscriminantChar P (hs P P.property)
  rw [primeDiscriminantCharAt, ← map_pow, hquad.sq_eq_one, map_one]

/-- A lifted prime-discriminant character is an involution. -/
@[simp] theorem primeDiscriminantCharAt_sq (P : s) :
    primeDiscriminantCharAt s hs P ^ 2 = 1 :=
  (isQuadratic_primeDiscriminantCharAt s hs P).sq_eq_one

/-- The common-level genus character indexed by a subset of the prime-discriminant factors. -/
noncomputable def genusCharAt (t : Finset s) :
    DirichletCharacter ℤ (∏ P ∈ s, P).natAbs :=
  ∏ P ∈ t, primeDiscriminantCharAt s hs P

@[simp] theorem genusCharAt_empty : genusCharAt s hs ∅ = 1 := by
  simp [genusCharAt]

@[simp] theorem genusCharAt_singleton (P : s) :
    genusCharAt s hs {P} = primeDiscriminantCharAt s hs P := by
  simp [genusCharAt]

/-- Inserting a new factor multiplies its character into the subset character. -/
@[simp] theorem genusCharAt_insert {P : s} {t : Finset s} (hP : P ∉ t) :
    genusCharAt s hs (insert P t) =
      primeDiscriminantCharAt s hs P * genusCharAt s hs t := by
  simp [genusCharAt, hP]

/-- Multiplication of subset characters corresponds to symmetric difference of the subsets. -/
@[simp] theorem genusCharAt_symmDiff (t u : Finset s) :
    genusCharAt s hs (t ∆ u) = genusCharAt s hs t * genusCharAt s hs u := by
  rw [genusCharAt, genusCharAt, genusCharAt, Finset.symmDiff_def]
  exact TauCeti.prod_sdiff_union_sdiff _ fun P _ ↦ primeDiscriminantCharAt_sq s hs P

/-- Every subset character is quadratic. -/
theorem isQuadratic_genusCharAt (t : Finset s) : (genusCharAt s hs t).IsQuadratic := by
  rw [MulChar.isQuadratic_iff_sq_eq_one, genusCharAt, ← Finset.prod_pow]
  exact Finset.prod_eq_one fun P _ ↦ primeDiscriminantCharAt_sq s hs P

/-- The conductor of a subset character is the product of the absolute values of its factors. -/
theorem conductor_genusCharAt
    (t : Finset s)
    (heven : ∀ P ∈ t, ∀ Q ∈ t,
      IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant Q → P = Q) :
    (genusCharAt s hs t).conductor = ∏ P ∈ t, P.val.natAbs := by
  let _ := prodNatAbsNeZero s hs
  rw [genusCharAt, TauCeti.conductor_prod_eq_prod_of_pairwise_coprime]
  · simp
  · intro P hPt Q hQt hPQ
    simp only [conductor_primeDiscriminantCharAt]
    exact Int.isCoprime_iff_nat_coprime.mp
      (isCoprime_primeDiscriminant_of_ne_of_not_both_even
        (hs P P.property) (hs Q Q.property) (fun h ↦ hPQ (Subtype.ext h))
        (fun h ↦ hPQ (heven P hPt Q hQt h.1 h.2)))
  · exact Or.inr (NeZero.ne _)

private theorem one_lt_natAbs (hs : ∀ P ∈ s, IsPrimeDiscriminant P) (P : s) :
    1 < P.val.natAbs := by
  rcases isPrimeDiscriminant_iff.mp (hs P P.property) with hP | ⟨p, hp, _, hP⟩
  · rcases hP with hP | hP | hP <;> rw [hP] <;> norm_num
  · rw [hP, oddPrimeDiscriminant_natAbs]
    exact hp.one_lt

/-- Different subsets of a prime-discriminant factorization give different common-level
characters. The conductor detects a nonempty symmetric difference. -/
theorem genusCharAt_injective
    (heven : ∀ P ∈ s, ∀ Q ∈ s,
      IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant Q → P = Q) :
    Function.Injective (genusCharAt s hs) := by
  let _ := prodNatAbsNeZero s hs
  intro t u htu
  apply Finset.symmDiff_eq_empty.mp
  by_contra hne
  have hchar : genusCharAt s hs (t ∆ u) = 1 := by
    rw [genusCharAt_symmDiff, htu, ← pow_two,
      (isQuadratic_genusCharAt s hs u).sq_eq_one]
  have hcond := congrArg conductor hchar
  have heven' : ∀ P ∈ t ∆ u, ∀ Q ∈ t ∆ u,
      IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant Q → P = Q :=
    fun P _ Q _ hP hQ ↦ Subtype.ext (heven P P.property Q Q.property hP hQ)
  rw [conductor_genusCharAt s hs (t ∆ u) heven', conductor_one] at hcond
  obtain ⟨P, hP⟩ := Finset.nonempty_iff_ne_empty.mpr hne
  have hpos : 0 < ∏ Q ∈ t ∆ u, Q.val.natAbs :=
    Finset.prod_pos fun Q _ ↦ Int.natAbs_pos.mpr (hs Q Q.property).ne_zero
  have hlt : 1 < ∏ Q ∈ t ∆ u, Q.val.natAbs :=
    (one_lt_natAbs s hs P).trans_le
      (Nat.le_of_dvd hpos (Finset.dvd_prod_of_mem (fun Q : s ↦ Q.val.natAbs) hP))
  omega

/-- The subgroup of common-level Dirichlet characters obtained by taking products over subsets of
the prime-discriminant factors. -/
noncomputable def genusCharacterGroup :
    Subgroup (DirichletCharacter ℤ (∏ P ∈ s, P).natAbs) where
  carrier := Set.range (genusCharAt s hs)
  one_mem' := ⟨∅, genusCharAt_empty s hs⟩
  mul_mem' := by
    rintro _ _ ⟨t, rfl⟩ ⟨u, rfl⟩
    exact ⟨t ∆ u, genusCharAt_symmDiff s hs t u⟩
  inv_mem' := by
    rintro _ ⟨t, rfl⟩
    refine ⟨t, ?_⟩
    exact (isQuadratic_genusCharAt s hs t).inv.symm

/-- Membership in the prime-discriminant character group means being the character of a subset. -/
@[simp] theorem mem_genusCharacterGroup_iff {chi : DirichletCharacter ℤ (∏ P ∈ s, P).natAbs} :
    chi ∈ genusCharacterGroup s hs ↔ ∃ t : Finset s, genusCharAt s hs t = chi :=
  Iff.rfl

/-- The subset characters are exactly the subgroup generated by the individual
prime-discriminant characters. -/
theorem genusCharacterGroup_eq_closure :
    genusCharacterGroup s hs =
      Subgroup.closure (primeDiscriminantCharAt s hs ''
        ((Finset.univ : Finset s) : Set s)) := by
  apply SetLike.coe_injective
  rw [TauCeti.closure_image_eq_image_powerset (Finset.univ : Finset s)
    (primeDiscriminantCharAt s hs) (fun P _ ↦ primeDiscriminantCharAt_sq s hs P)]
  ext chi
  simp only [Set.mem_image, Finset.mem_coe, Finset.mem_powerset, Finset.subset_univ, true_and]
  rfl

/-- The subsets of a prime-discriminant family are in bijection with its character group. -/
noncomputable def genusCharAtEquiv
    (heven : ∀ P ∈ s, ∀ Q ∈ s,
      IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant Q → P = Q) :
    Finset s ≃ genusCharacterGroup s hs :=
  Equiv.ofInjective (genusCharAt s hs) (genusCharAt_injective s hs heven)

/-- The character group of `s` has one element for each subset of `s`. -/
theorem natCard_genusCharacterGroup
    (heven : ∀ P ∈ s, ∀ Q ∈ s,
      IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant Q → P = Q) :
    Nat.card (genusCharacterGroup s hs) = 2 ^ s.card := by
  rw [Nat.card_congr (genusCharAtEquiv s hs heven).symm, Nat.card_eq_fintype_card,
    Fintype.card_finset, Fintype.card_coe]

end TauCeti.Multiquadratic
