/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.QuasiIdempotent
public import TauCeti.RepresentationTheory.Symmetric.Specht.Comparison
public import TauCeti.RepresentationTheory.Symmetric.Specht.Ideal.Idempotent

/-!
# The Specht character from the coefficients of a Young symmetrizer

Let `t` be a tableau of shape `μ` with `n` cells, `c_t` its Young symmetrizer, `χ^μ` the character
of the Specht module `S^μ` and `f^μ = dim S^μ`. Averaging the coefficients of `c_t` over a
conjugacy class of `Sₙ` gives the character value there:

`n! · χ^μ(g) = f^μ · ∑_{σ ∈ Sₙ} c_t(σ g σ⁻¹)`.

Equivalently, pairing `c_t` with a class function `φ` of `Sₙ` is pairing `χ^μ` with it, up to the
factor `f^μ`:

`∑_g χ^μ(g) φ(g) = f^μ · ∑_g c_t(g) φ(g)`.

The second form is how this enters the character theory of the Weyl modules `c_t · V^{⊗n}`: their
characters are sums `(f^μ/n!) ∑_g c_t(g) φ(g)` with `φ(g)` the power sum of the cycle type of `g`,
and the identity turns these into the class-function expansion `(1/n!) ∑_g χ^μ(g) φ(g)` that
Frobenius's formula identifies with the Schur polynomial `s_μ`.

The proof reads `S^μ` as the left ideal `ℚ[Sₙ] c_t`
(`TauCeti.YoungTableau.character_spechtIdeal_eq_spechtSubrepresentation`) and applies the
character formula for the left ideal of a quasi-idempotent,
`Representation.mul_char_ofModule'_span_singleton`, to `c_t * c_t = (n! / f^μ) • c_t`
(`TauCeti.YoungTableau.youngSymmetrizer_sq`). That formula sums the coefficients over the
conjugates of `g⁻¹`; in `Sₙ` every element is conjugate to its inverse, which turns them into the
conjugates of `g`.

## Main results

* `TauCeti.YoungTableau.factorial_mul_char_spechtSubrepresentation`: `n! · χ^μ(g)` is `f^μ` times
  the sum of the coefficients of `c_t` over the conjugates `σ g σ⁻¹`.
* `TauCeti.YoungTableau.sum_char_spechtSubrepresentation_smul`: pairing `χ^μ` with a class
  function is `f^μ` times pairing `c_t` with it.

## References

* W. Fulton and J. Harris, *Representation Theory: A First Course* (1991), Lecture 4.
* I. G. Macdonald, *Symmetric Functions and Hall Polynomials*, 2nd ed., Chapter I, Section 7.
-/

public section

namespace TauCeti

namespace YoungTableau

open Module

variable {μ : YoungDiagram}

/-- **The Specht character from the Young symmetrizer.** For a tableau `t` of shape `μ` with `n`
cells, `n!` times the character of `S^μ` at `g` is `dim S^μ` times the sum of the coefficients of
the Young symmetrizer `c_t` over the conjugates `σ g σ⁻¹`. -/
theorem factorial_mul_char_spechtSubrepresentation (t : YoungTableau μ)
    (g : Equiv.Perm (Fin μ.card)) :
    (μ.card.factorial : ℚ) * (spechtSubrepresentation μ).toRepresentation.character g =
      finrank ℚ (spechtSubrepresentation μ).toSubmodule *
        ∑ σ, (youngSymmetrizer t).coeff (σ * g * σ⁻¹) := by
  have hf : (finrank ℚ (spechtIdeal t) : ℚ) ≠ 0 := by
    exact_mod_cast (finrank_spechtIdeal_pos t).ne'
  -- `g⁻¹` is conjugate to `g`, so the coefficient sums over their conjugates agree
  obtain ⟨τ, hτ⟩ := isConj_iff.mp
    (Equiv.Perm.isConj_iff_cycleType_eq.mpr (Equiv.Perm.cycleType_inv g).symm)
  have hsum : ∑ σ, (youngSymmetrizer t).coeff (σ⁻¹ * g⁻¹ * σ) =
      ∑ σ, (youngSymmetrizer t).coeff (σ * g * σ⁻¹) :=
    Fintype.sum_equiv ((Equiv.inv _).trans (Equiv.mulRight τ)) _ _ fun σ => by
      simp [← hτ, mul_assoc]
  -- the Specht ideal representation is left multiplication on the ideal generated by `c_t`
  have hI : spechtIdeal t = Ideal.span {youngSymmetrizer t} :=
    Submodule.ext fun x => (mem_spechtIdeal_iff t x).trans Ideal.mem_span_singleton'.symm
  have hχ : (spechtIdealRep t).ρ.character g = (Representation.ofModule' (k := ℚ)
      (Ideal.span {youngSymmetrizer t} :
        Ideal (MonoidAlgebra ℚ (Equiv.Perm (Fin μ.card))))).character g :=
    congrArg (fun I : Ideal (MonoidAlgebra ℚ (Equiv.Perm (Fin μ.card))) =>
      (Representation.ofModule' (k := ℚ) I).character g) hI
  have h := Representation.mul_char_ofModule'_span_singleton (youngSymmetrizer_sq t) g
  rw [hsum, ← hχ] at h
  rw [← character_spechtIdeal_eq_spechtSubrepresentation t,
    ← finrank_spechtIdeal_eq_spechtSubrepresentation t, ← h]
  field_simp

/-- **Pairing a class function with the Young symmetrizer.** For a tableau `t` of shape `μ` and a
function `φ` on the permutations that is constant on conjugacy classes, pairing `φ` with the
character of `S^μ` gives `dim S^μ` times pairing it with the coefficients of `c_t`. -/
theorem sum_char_spechtSubrepresentation_smul (t : YoungTableau μ) {M : Type*} [AddCommGroup M]
    [Module ℚ M] (φ : Equiv.Perm (Fin μ.card) → M) (hφ : ∀ g σ, φ (σ * g * σ⁻¹) = φ g) :
    ∑ g, (spechtSubrepresentation μ).toRepresentation.character g • φ g =
      (finrank ℚ (spechtSubrepresentation μ).toSubmodule : ℚ) •
        ∑ g, (youngSymmetrizer t).coeff g • φ g := by
  have hn : (μ.card.factorial : ℚ) ≠ 0 := by positivity
  -- each conjugating element `σ` contributes the same sum, after reindexing by `g ↦ σ g σ⁻¹`
  have hσ (σ : Equiv.Perm (Fin μ.card)) :
      ∑ g, (youngSymmetrizer t).coeff (σ * g * σ⁻¹) • φ g =
        ∑ g, (youngSymmetrizer t).coeff g • φ g :=
    Fintype.sum_equiv (MulAut.conj σ).toEquiv _ _ fun g => by simp [hφ]
  refine smul_right_injective M hn ?_
  dsimp only
  simp_rw [Finset.smul_sum, smul_smul, factorial_mul_char_spechtSubrepresentation t,
    Finset.mul_sum, Finset.sum_smul]
  rw [Finset.sum_comm]
  simp_rw [← smul_smul, ← Finset.smul_sum, hσ]
  simp [Finset.card_univ, Fintype.card_perm, smul_comm (μ.card.factorial : ℚ),
    Nat.cast_smul_eq_nsmul]

end YoungTableau

end TauCeti
