/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.FarguesFontaine.Window
public import TauCeti.Topology.Algebra.ConstMulAction

import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic
import TauCeti.RingTheory.Huber.Adic

/-!
# The Frobenius orbit space

The Witt-vector Frobenius restricts to a homeomorphism of `𝒴 = D(p) ∩ D([ϖ])` when the
coefficient ring is perfect of characteristic `p` and the Witt vectors carry the
`(p, [ϖ])`-adic topology. Its cyclic subgroup acts continuously on `𝒴`. The orbit space
`spaX` carries the quotient topology, and its projection is open.

The wandering Frobenius windows embed openly into this orbit space. The images of `U₀` and
`V₀` cover it, so it is quasi-compact and `T0`. These topological charts are the inputs for
constructing the quotient sheaf and identifying its affinoid charts.

## References

* K. S. Kedlaya, *Sheaves, stacks, and shtukas*, Arizona Winter School 2017 notes,
  Remark 3.1.9.
* L. Fargues and J.-M. Fontaine, *Courbes et fibrés vectoriels en théorie de Hodge p-adique*,
  Astérisque 406 (2018).
-/

public section

noncomputable section

namespace TauCeti.FarguesFontaine

open TauCeti.ValuationSpectrum _root_.WittVector Topology

variable {p : ℕ} [Fact p.Prime] {R : Type*} [CommRing R] [CharP R p] [PerfectRing R p]
  [TopologicalSpace (WittVector p R)] {ϖ : R}

/-- Pullback along Witt Frobenius, as a homeomorphism of `𝒴`. -/
def frobeniusHomeomorph
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) :
    spaY p ϖ ≃ₜ spaY p ϖ := by
  let e := frobeniusEquiv p R
  let h : Spv (WittVector p R) ≃ₜ Spv (WittVector p R) :=
    { toFun := comap (e : WittVector p R →+* WittVector p R)
      invFun := comap (e.symm : WittVector p R →+* WittVector p R)
      left_inv := fun v ↦ by
        rw [← Function.comp_apply (f := comap _) (g := comap _), ← comap_comp]
        simp
      right_inv := fun v ↦ by
        rw [← Function.comp_apply (f := comap _) (g := comap _), ← comap_comp]
        simp
      continuous_toFun := continuous_comap _
      continuous_invFun := continuous_comap _ }
  exact h.subtype fun v ↦ (comap_frobenius_mem_spaY_iff hI v).symm

/-- On underlying valuations, the Frobenius homeomorphism is pullback along Frobenius. -/
@[simp]
theorem frobeniusHomeomorph_apply_val
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (v : spaY p ϖ) :
    (frobeniusHomeomorph hI v).val = comap frobenius v.val := (rfl)

/-- The inverse Frobenius homeomorphism is pullback along inverse Witt Frobenius. -/
@[simp]
theorem frobeniusHomeomorph_symm_apply_val
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (v : spaY p ϖ) :
    ((frobeniusHomeomorph hI).symm v).val =
      comap ((frobeniusEquiv p R).symm : WittVector p R →+* WittVector p R) v.val := (rfl)

/-- Positive powers of the Frobenius homeomorphism are the usual Frobenius iterates. -/
theorem frobeniusHomeomorph_pow_apply_val
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (k : ℕ)
    (v : spaY p ϖ) :
    ((frobeniusHomeomorph hI ^ k) v).val = (comap frobenius)^[k] v.val := by
  induction k with
  | zero => rfl
  | succ k ih =>
    rw [pow_succ', Function.iterate_succ_apply']
    exact congrArg (comap frobenius) ih

/-- The topological orbit space `𝒳 = 𝒴 / φ^ℤ`. The acting group is the cyclic subgroup
of homeomorphisms generated by Frobenius, so no representative valuation or value group is
chosen. -/
abbrev spaX (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) :=
  Quotient (MulAction.orbitRel (Subgroup.zpowers (frobeniusHomeomorph hI)) (spaY p ϖ))

/-- The projection of `𝒴` to its Frobenius orbit space. -/
def quotientMap (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) :
    spaY p ϖ → spaX hI := Quotient.mk _

/-- Two points have the same image precisely when one is an integer Frobenius translate of
the other. -/
theorem quotientMap_eq_iff
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (v w : spaY p ϖ) :
    quotientMap hI v = quotientMap hI w ↔ ∃ n : ℤ, (frobeniusHomeomorph hI ^ n) w = v := by
  rw [quotientMap, Quotient.eq, MulAction.orbitRel_apply, MulAction.mem_orbit_iff,
    Subgroup.exists_zpowers]
  rfl

/-- The Frobenius orbit projection is an open quotient map. -/
theorem isOpenQuotientMap_quotientMap
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) :
    IsOpenQuotientMap (quotientMap hI) :=
  MulAction.isOpenQuotientMap_quotientMk

/-- Integer Frobenius translates have the same image in the quotient. -/
@[simp]
theorem quotientMap_zpow
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (n : ℤ)
    (v : spaY p ϖ) : quotientMap hI ((frobeniusHomeomorph hI ^ n) v) = quotientMap hI v :=
  (quotientMap_eq_iff hI _ _).mpr ⟨n, rfl⟩

private theorem injOn_quotientMap_of_disjoint_iterates
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ}))
    (S : Set (Spv (WittVector p R)))
    (hS : ∀ k : ℕ, k ≠ 0 → Disjoint ((comap frobenius)^[k] '' S) S) :
    Set.InjOn (quotientMap hI) (Subtype.val ⁻¹' S) := by
  intro v hv w hw heq
  obtain ⟨n, hn⟩ := (quotientMap_eq_iff hI v w).mp heq
  obtain ⟨k, rfl | rfl⟩ := n.eq_nat_or_neg
  · rw [zpow_natCast] at hn
    by_cases hk : k = 0
    · simpa [hk] using hn.symm
    · exact ((hS k hk).notMem_of_mem_left
        ⟨w.val, hw, (frobeniusHomeomorph_pow_apply_val hI k w).symm.trans
          (congrArg Subtype.val hn)⟩ hv).elim
  · rw [zpow_neg, zpow_natCast] at hn
    have hn' : (frobeniusHomeomorph hI ^ k) v = w := by
      rw [← hn]
      exact (frobeniusHomeomorph hI ^ k).apply_symm_apply w
    by_cases hk : k = 0
    · simpa [hk] using hn'
    · exact ((hS k hk).notMem_of_mem_left
        ⟨v.val, hv, (frobeniusHomeomorph_pow_apply_val hI k v).symm.trans
          (congrArg Subtype.val hn')⟩ hw).elim

/-- The orbit projection is injective on every `U` window. -/
theorem injOn_quotientMap_windowU
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (n : ℤ) :
    Set.InjOn (quotientMap hI) (Subtype.val ⁻¹' windowU p ϖ n) :=
  injOn_quotientMap_of_disjoint_iterates hI _ fun _ hk ↦
    disjoint_image_iterate_comap_frobenius_windowU hI n hk

/-- The orbit projection is injective on every `V` window. -/
theorem injOn_quotientMap_windowV
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (n : ℤ) :
    Set.InjOn (quotientMap hI) (Subtype.val ⁻¹' windowV p ϖ n) :=
  injOn_quotientMap_of_disjoint_iterates hI _ fun _ hk ↦
    disjoint_image_iterate_comap_frobenius_windowV hI n hk

omit [CharP R p] [PerfectRing R p] in
/-- Each `U` window is open in `𝒴`. -/
theorem isOpen_val_preimage_windowU
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (n : ℤ) :
    IsOpen (Subtype.val ⁻¹' windowU p ϖ n : Set (spaY p ϖ)) := by
  have : IsTopologicalRing (WittVector p R) :=
    hI ▸ (Ideal.span _).nonarchimedean.toIsTopologicalRing
  have : Huber.IsHuberRing (WittVector p R) :=
    Huber.isHuberRing_of_isAdic _ hI (Submodule.fg_span (by simp))
  let j : spaY p ϖ → spa (⊤ : Subring (WittVector p R)) := fun v ↦
    ⟨v.val, ((mem_spaY_iff p ϖ v.val).mp v.property).1⟩
  exact ((isTopologicalBasis_spaRationalFamily _).isOpen
    (val_preimage_windowU_mem_spaRationalFamily ϖ hI n)).preimage
      (continuous_subtype_val.subtype_mk _ : Continuous j)

omit [CharP R p] [PerfectRing R p] in
/-- Each `V` window is open in `𝒴`. -/
theorem isOpen_val_preimage_windowV
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (n : ℤ) :
    IsOpen (Subtype.val ⁻¹' windowV p ϖ n : Set (spaY p ϖ)) := by
  have : IsTopologicalRing (WittVector p R) :=
    hI ▸ (Ideal.span _).nonarchimedean.toIsTopologicalRing
  have : Huber.IsHuberRing (WittVector p R) :=
    Huber.isHuberRing_of_isAdic _ hI (Submodule.fg_span (by simp))
  let j : spaY p ϖ → spa (⊤ : Subring (WittVector p R)) := fun v ↦
    ⟨v.val, ((mem_spaY_iff p ϖ v.val).mp v.property).1⟩
  exact ((isTopologicalBasis_spaRationalFamily _).isOpen
    (val_preimage_windowV_mem_spaRationalFamily ϖ hI n)).preimage
      (continuous_subtype_val.subtype_mk _ : Continuous j)

/-- The restriction of the orbit projection to a `U` window is an open embedding. -/
theorem isOpenEmbedding_quotientMap_windowU
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (n : ℤ) :
    IsOpenEmbedding (fun v : (Subtype.val ⁻¹' windowU p ϖ n : Set (spaY p ϖ)) ↦
      quotientMap hI v.val) := by
  have hq := isOpenQuotientMap_quotientMap hI
  exact .of_continuous_injective_isOpenMap (hq.continuous.comp continuous_subtype_val)
    (injOn_quotientMap_windowU hI n).injective
    (hq.isOpenMap.comp (isOpen_val_preimage_windowU hI n).isOpenEmbedding_subtypeVal.isOpenMap)

/-- The restriction of the orbit projection to a `V` window is an open embedding. -/
theorem isOpenEmbedding_quotientMap_windowV
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (n : ℤ) :
    IsOpenEmbedding (fun v : (Subtype.val ⁻¹' windowV p ϖ n : Set (spaY p ϖ)) ↦
      quotientMap hI v.val) := by
  have hq := isOpenQuotientMap_quotientMap hI
  exact .of_continuous_injective_isOpenMap (hq.continuous.comp continuous_subtype_val)
    (injOn_quotientMap_windowV hI n).injective
    (hq.isOpenMap.comp (isOpen_val_preimage_windowV hI n).isOpenEmbedding_subtypeVal.isOpenMap)

private theorem frobeniusHomeomorph_zpow_mem_window
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ}))
    (W : ℤ → Set (Spv (WittVector p R)))
    (hW : ∀ v n, comap frobenius v ∈ W (n + 1) ↔ v ∈ W n)
    (n m : ℤ) (v : spaY p ϖ) :
    ((frobeniusHomeomorph hI ^ n) v).val ∈ W (m + n) ↔ v.val ∈ W m := by
  induction n using Int.induction_on generalizing m v with
  | zero => simp
  | succ n ih =>
    rw [zpow_add, zpow_one, Homeomorph.mul_apply]
    have h := (ih (m + 1) (frobeniusHomeomorph hI v)).trans (hW v.val m)
    have he : m + (n + 1) = m + 1 + n := by omega
    rw [he]
    exact h
  | pred n ih =>
    rw [zpow_sub, zpow_one, Homeomorph.mul_apply]
    have h := (ih (m - 1) ((frobeniusHomeomorph hI).symm v)).trans
      (hW (((frobeniusHomeomorph hI).symm v).val) (m - 1)).symm
    have hh : comap frobenius (((frobeniusHomeomorph hI).symm v).val) = v.val :=
      (frobeniusHomeomorph_apply_val hI _).symm.trans
        (congrArg Subtype.val ((frobeniusHomeomorph hI).apply_symm_apply v))
    simp only [Homeomorph.inv_apply]
    simpa only [sub_add_cancel, hh, sub_add_eq_add_sub, add_sub_assoc] using h

/-- An integer Frobenius translate shifts the index of a `U` window by that integer. -/
theorem frobeniusHomeomorph_zpow_mem_windowU_iff
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ}))
    (n m : ℤ) (v : spaY p ϖ) :
    ((frobeniusHomeomorph hI ^ n) v).val ∈ windowU p ϖ (m + n) ↔ v.val ∈ windowU p ϖ m :=
  frobeniusHomeomorph_zpow_mem_window hI _ (comap_frobenius_mem_windowU_iff hI) n m v

/-- An integer Frobenius translate shifts the index of a `V` window by that integer. -/
theorem frobeniusHomeomorph_zpow_mem_windowV_iff
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ}))
    (n m : ℤ) (v : spaY p ϖ) :
    ((frobeniusHomeomorph hI ^ n) v).val ∈ windowV p ϖ (m + n) ↔ v.val ∈ windowV p ϖ m :=
  frobeniusHomeomorph_zpow_mem_window hI _ (comap_frobenius_mem_windowV_iff hI) n m v

/-- The images of the two windows of index zero cover the Frobenius orbit space. -/
theorem image_windowU_zero_union_image_windowV_zero
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) :
    quotientMap hI '' (Subtype.val ⁻¹' windowU p ϖ 0) ∪
      quotientMap hI '' (Subtype.val ⁻¹' windowV p ϖ 0) = Set.univ := by
  apply Set.eq_univ_of_forall
  intro x
  obtain ⟨v, rfl⟩ := (isOpenQuotientMap_quotientMap hI).surjective x
  have hv := (Set.ext_iff.mp (iUnion_windowU_union_windowV hI) v.val).mpr v.property
  obtain ⟨n, hn | hn⟩ := Set.mem_iUnion.mp hv
  · exact Or.inl ⟨(frobeniusHomeomorph hI ^ (-n)) v, by
      simpa using (frobeniusHomeomorph_zpow_mem_windowU_iff hI (-n) n v).mpr hn,
        quotientMap_zpow hI (-n) v⟩
  · exact Or.inr ⟨(frobeniusHomeomorph hI ^ (-n)) v, by
      simpa using (frobeniusHomeomorph_zpow_mem_windowV_iff hI (-n) n v).mpr hn,
        quotientMap_zpow hI (-n) v⟩

omit [CharP R p] [PerfectRing R p] in
private theorem isCompact_val_preimage_of_mem_spaRationalFamily
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ}))
    (S : Set (Spv (WittVector p R))) (hS : S ⊆ spaY p ϖ)
    (hSrat : (Subtype.val ⁻¹' S : Set (spa (⊤ : Subring (WittVector p R)))) ∈
      spaRationalFamily ⊤) : IsCompact (Subtype.val ⁻¹' S : Set (spaY p ϖ)) := by
  have : IsTopologicalRing (WittVector p R) :=
    hI ▸ (Ideal.span _).nonarchimedean.toIsTopologicalRing
  have : Huber.IsHuberRing (WittVector p R) :=
    Huber.isHuberRing_of_isAdic _ hI (Submodule.fg_span (by simp))
  let j : spaY p ϖ → spa (⊤ : Subring (WittVector p R)) := fun v ↦
    ⟨v.val, ((mem_spaY_iff p ϖ v.val).mp v.property).1⟩
  have hc : Continuous j := continuous_subtype_val.subtype_mk _
  have hj : IsInducing j := .of_comp hc continuous_subtype_val .subtypeVal
  exact hj.isCompact_preimage' (isCompact_of_mem_spaRationalFamily hSrat)
    (fun v hv ↦ ⟨⟨v.val, hS hv⟩, Subtype.ext rfl⟩)

omit [CharP R p] [PerfectRing R p] in
/-- Each `U` window is quasi-compact as a subset of `𝒴`. -/
theorem isCompact_val_preimage_windowU
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (n : ℤ) :
    IsCompact (Subtype.val ⁻¹' windowU p ϖ n : Set (spaY p ϖ)) :=
  isCompact_val_preimage_of_mem_spaRationalFamily hI _ (windowU_subset_spaY n)
    (val_preimage_windowU_mem_spaRationalFamily ϖ hI n)

omit [CharP R p] [PerfectRing R p] in
/-- Each `V` window is quasi-compact as a subset of `𝒴`. -/
theorem isCompact_val_preimage_windowV
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (n : ℤ) :
    IsCompact (Subtype.val ⁻¹' windowV p ϖ n : Set (spaY p ϖ)) :=
  isCompact_val_preimage_of_mem_spaRationalFamily hI _ (windowV_subset_spaY n)
    (val_preimage_windowV_mem_spaRationalFamily ϖ hI n)

/-- The Frobenius orbit space is quasi-compact: its two charts of index zero are images of
quasi-compact rational windows. -/
instance compactSpace_spaX
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) :
    CompactSpace (spaX hI) := by
  have hc := ((isCompact_val_preimage_windowU hI 0).image
    (isOpenQuotientMap_quotientMap hI).continuous).union
      ((isCompact_val_preimage_windowV hI 0).image
        (isOpenQuotientMap_quotientMap hI).continuous)
  rw [image_windowU_zero_union_image_windowV_zero hI] at hc
  exact ⟨hc⟩

/-- The Frobenius orbit space is `T0`, since its open window charts are subspaces of the
valuation spectrum. -/
instance t0Space_spaX
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) :
    T0Space (spaX hI) := by
  apply T0Space.of_open_cover
  intro x
  have hx : x ∈ quotientMap hI '' (Subtype.val ⁻¹' windowU p ϖ 0) ∪
      quotientMap hI '' (Subtype.val ⁻¹' windowV p ϖ 0) := by
    rw [image_windowU_zero_union_image_windowV_zero hI]
    trivial
  rcases hx with ⟨v, hv, rfl⟩ | ⟨v, hv, rfl⟩
  · let f := fun v : (Subtype.val ⁻¹' windowU p ϖ 0 : Set (spaY p ϖ)) ↦ quotientMap hI v.val
    have he := isOpenEmbedding_quotientMap_windowU hI 0
    exact ⟨Set.range f, ⟨⟨v, hv⟩, rfl⟩, he.isOpen_range, he.isEmbedding.toHomeomorph.t0Space⟩
  · let f := fun v : (Subtype.val ⁻¹' windowV p ϖ 0 : Set (spaY p ϖ)) ↦ quotientMap hI v.val
    have he := isOpenEmbedding_quotientMap_windowV hI 0
    exact ⟨Set.range f, ⟨⟨v, hv⟩, rfl⟩, he.isOpen_range, he.isEmbedding.toHomeomorph.t0Space⟩

end TauCeti.FarguesFontaine
