/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.ODE.Linear

/-!
# Exponential dichotomy for symmetric linear flows

A finite-dimensional symmetric operator has negative and positive spectral subspaces.  For the
flow generated by its negative, a vector of the positive subspace has norm at most
`exp (-α t) * ‖v‖` in forward time, and a vector of the negative subspace has norm at most
`exp (α t) * ‖v‖` in backward time, where `α` is any lower bound on the relevant absolute
eigenvalues.  These bounds decay — that is, they are genuine contractions — exactly when `α` is
positive, and since the nonzero spectrum is finite one common positive rate always exists.  When
the kernel is zero, the two subspaces are complementary and these estimates form an exponential
dichotomy.

These estimates are the quantitative counterpart of the asymptotic description in
`TauCeti.Analysis.ODE.Linear`.  They are the linear input to the Lyapunov--Perron construction of
local stable and unstable manifolds near a hyperbolic equilibrium.

## Main declarations

* `LinearMap.IsSymmetric.norm_flow_neg_le_exp_neg_mul_of_mem_positiveSpectralSubspace`:
  the forward exponential norm bound on the positive spectral subspace.
* `LinearMap.IsSymmetric.norm_flow_neg_le_exp_mul_of_mem_negativeSpectralSubspace`:
  the backward exponential norm bound on the negative spectral subspace.
* `LinearMap.IsSymmetric.exists_exponential_bounds_spectralSubspaces`: a symmetric operator has
  a common positive contraction rate on its two strict spectral subspaces.

## References

* M. Audin and M. Damian, *Morse Theory and Floer Homology*, Springer Universitext, 2014,
  Chapter 2.
-/

public section

open NormedSpace
open scoped InnerProductSpace

noncomputable section

namespace LinearMap.IsSymmetric

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
  [FiniteDimensional ℝ E] {n : ℕ} {T : E →L[ℝ] E}

/-- Parseval in the ordered orthonormal eigenbasis: a uniform bound `c` on the coordinate
factors `exp (-(t * λᵢ))` of the flow, over the eigencoordinates that `v` actually occupies,
bounds `‖(-T).flow t v‖` by `c * ‖v‖`. -/
private theorem norm_flow_neg_le_mul_of_forall_exp_le (hT : (T : E →ₗ[ℝ] E).IsSymmetric)
    (hn : Module.finrank ℝ E = n) {c t : ℝ} (hc : 0 ≤ c) {v : E}
    (h : ∀ i : Fin n, (hT.eigenvectorBasis hn).toBasis.repr v i ≠ 0 →
      Real.exp (-(t * hT.eigenvalues hn i)) ≤ c) :
    ‖(-T).flow t v‖ ≤ c * ‖v‖ := by
  let b := hT.eigenvectorBasis hn
  rw [← sq_le_sq₀ (norm_nonneg _) (mul_nonneg hc (norm_nonneg _)),
    mul_pow, ← b.repr.norm_map, ← b.repr.norm_map, EuclideanSpace.real_norm_sq_eq,
    EuclideanSpace.real_norm_sq_eq, Finset.mul_sum]
  refine Finset.sum_le_sum fun i _ ↦ ?_
  simp only [← b.coe_toBasis_repr_apply]
  rw [eigenvectorBasis_repr_flow_neg_apply hT hn]
  by_cases hi : (b.toBasis.repr v) i = 0
  · dsimp only [b] at hi ⊢
    simp [hi]
  dsimp only [b] at hi ⊢
  rw [mul_pow]
  exact mul_le_mul_of_nonneg_right
    (pow_le_pow_left₀ (Real.exp_nonneg _) (h i hi) 2) (sq_nonneg _)

/-- For the flow generated by `-T`, a vector of the positive spectral subspace has norm at most
`exp (-α t) * ‖v‖` in forward time, for any `α` below all the positive eigenvalues.  The bound
decays exactly when `α` is positive. -/
theorem norm_flow_neg_le_exp_neg_mul_of_mem_positiveSpectralSubspace
    (hT : (T : E →ₗ[ℝ] E).IsSymmetric) (hn : Module.finrank ℝ E = n)
    {alpha t : ℝ}
    (halpha : ∀ i : Fin n, 0 < hT.eigenvalues hn i → alpha ≤ hT.eigenvalues hn i)
    (ht : 0 ≤ t) {v : E} (hv : v ∈ hT.positiveSpectralSubspace hn) :
    ‖(-T).flow t v‖ ≤ Real.exp (-alpha * t) * ‖v‖ := by
  refine hT.norm_flow_neg_le_mul_of_forall_exp_le hn (Real.exp_nonneg _) fun i hi ↦ ?_
  have hpos : 0 < hT.eigenvalues hn i :=
    (hT.mem_positiveSpectralSubspace_iff hn).mp hv i (Finsupp.mem_support_iff.mpr hi)
  rw [Real.exp_le_exp]
  nlinarith [halpha i hpos]

/-- For the flow generated by `-T`, a vector of the negative spectral subspace has norm at most
`exp (α t) * ‖v‖` in backward time, for any `α` below the absolute values of the negative
eigenvalues.  The bound decays exactly when `α` is positive. -/
theorem norm_flow_neg_le_exp_mul_of_mem_negativeSpectralSubspace
    (hT : (T : E →ₗ[ℝ] E).IsSymmetric) (hn : Module.finrank ℝ E = n)
    {alpha t : ℝ}
    (halpha : ∀ i : Fin n, hT.eigenvalues hn i < 0 →
      alpha ≤ -hT.eigenvalues hn i)
    (ht : t ≤ 0) {v : E} (hv : v ∈ hT.negativeSpectralSubspace hn) :
    ‖(-T).flow t v‖ ≤ Real.exp (alpha * t) * ‖v‖ := by
  refine hT.norm_flow_neg_le_mul_of_forall_exp_le hn (Real.exp_nonneg _) fun i hi ↦ ?_
  have hneg : hT.eigenvalues hn i < 0 :=
    (hT.mem_negativeSpectralSubspace_iff hn).mp hv i (Finsupp.mem_support_iff.mpr hi)
  rw [Real.exp_le_exp]
  nlinarith [halpha i hneg]

/-- A symmetric operator has a common positive exponential contraction rate on its positive
subspace in forward time and on its negative subspace in backward time.  Zero eigenvalues are
irrelevant because neither strict spectral subspace contains their eigendirections.  The estimate
has multiplicative constant one because the two subspaces are orthogonal sums of eigendirections. -/
theorem exists_exponential_bounds_spectralSubspaces
    (hT : (T : E →ₗ[ℝ] E).IsSymmetric) (hn : Module.finrank ℝ E = n) :
    ∃ alpha > 0,
      (∀ (t : ℝ), 0 ≤ t → ∀ v ∈ hT.positiveSpectralSubspace hn,
        ‖(-T).flow t v‖ ≤ Real.exp (-alpha * t) * ‖v‖) ∧
      (∀ (t : ℝ), t ≤ 0 → ∀ v ∈ hT.negativeSpectralSubspace hn,
        ‖(-T).flow t v‖ ≤ Real.exp (alpha * t) * ‖v‖) := by
  classical
  let s := Finset.univ.filter fun i : Fin n ↦ hT.eigenvalues hn i ≠ 0
  by_cases hs : s.Nonempty
  · let alpha := s.inf' hs
      (fun i : Fin n ↦ |hT.eigenvalues hn i|)
    have halpha_pos : 0 < alpha := by
      obtain ⟨i, hi_mem, hi⟩ := Finset.exists_mem_eq_inf' hs
        (fun i : Fin n ↦ |hT.eigenvalues hn i|)
      dsimp only [alpha]
      rw [hi, abs_pos]
      exact (Finset.mem_filter.mp hi_mem).2
    have halpha_le (i : Fin n) (hi : hT.eigenvalues hn i ≠ 0) :
        alpha ≤ |hT.eigenvalues hn i| := by
      exact Finset.inf'_le _ (Finset.mem_filter.mpr ⟨Finset.mem_univ i, hi⟩)
    refine ⟨alpha, halpha_pos, ?_, ?_⟩
    · intro t ht v hv
      exact hT.norm_flow_neg_le_exp_neg_mul_of_mem_positiveSpectralSubspace hn
        (fun i hi ↦ by simpa [abs_of_pos hi] using halpha_le i hi.ne') ht hv
    · intro t ht v hv
      exact hT.norm_flow_neg_le_exp_mul_of_mem_negativeSpectralSubspace hn
        (fun i hi ↦ by simpa [abs_of_neg hi] using halpha_le i hi.ne) ht hv
  · refine ⟨1, one_pos, ?_, ?_⟩
    · intro t ht v hv
      exact hT.norm_flow_neg_le_exp_neg_mul_of_mem_positiveSpectralSubspace hn
        (fun i hi ↦ (hs ⟨i, Finset.mem_filter.mpr ⟨Finset.mem_univ i, hi.ne'⟩⟩).elim) ht hv
    · intro t ht v hv
      exact hT.norm_flow_neg_le_exp_mul_of_mem_negativeSpectralSubspace hn
        (fun i hi ↦ (hs ⟨i, Finset.mem_filter.mpr ⟨Finset.mem_univ i, hi.ne⟩⟩).elim) ht hv

end LinearMap.IsSymmetric

end
