/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Cyclotomic.Basic
import Mathlib.NumberTheory.NumberField.Cyclotomic.Basic

/-!
# The image of exact cyclotomic integers

The distinguished complex embedding of `TauCeti.Cyclotomic e` has image `ℤ[ζₑ]`.
Every algebraic integer in the field `ℚ(ζₑ)` therefore has an exact coefficient-vector
representative. This permits integral central-character values, which are initially expressed
as quotients of ordinary character values, to enter exact cyclotomic computations.

The integral-closure step uses Mathlib's
`IsCyclotomicExtension.Rat.isIntegralClosure_adjoin_singleton`.
-/

public section

namespace TauCeti.Cyclotomic

variable {e : ℕ} [NeZero e]

/-- The image of the distinguished complex embedding is the ring generated by its primitive
root over the integers. -/
theorem mem_range_complexEmbedding_iff {z : ℂ} :
    z ∈ Set.range (complexEmbedding (e := e)) ↔
      z ∈ Algebra.adjoin ℤ {complexRoot e} := by
  constructor
  · rintro ⟨x, rfl⟩
    rw [complexEmbedding_apply]
    exact Polynomial.aeval_mem_adjoin_singleton _ _
  · intro hz
    have hle : Algebra.adjoin ℤ {complexRoot e} ≤
        (complexEmbedding (e := e)).toIntAlgHom.range := by
      apply Algebra.adjoin_le
      rintro x (rfl : x = complexRoot e)
      exact ⟨zeta e, complexEmbedding_zeta⟩
    exact hle hz

/-- Every algebraic integer in the cyclotomic field has an exact cyclotomic representative
under the distinguished complex embedding. -/
theorem mem_range_complexEmbedding_of_isIntegral {z : ℂ}
    (hz : z ∈ IntermediateField.adjoin ℚ {complexRoot e}) (hint : IsIntegral ℤ z) :
    z ∈ Set.range (complexEmbedding (e := e)) := by
  rw [mem_range_complexEmbedding_iff]
  let K := IntermediateField.adjoin ℚ {complexRoot e}
  let ζ : K := ⟨complexRoot e, IntermediateField.subset_adjoin ℚ _ (Set.mem_singleton _)⟩
  have hζ : IsPrimitiveRoot ζ e :=
    IsPrimitiveRoot.coe_submonoidClass_iff.mp isPrimitiveRoot_complexRoot
  have : IsCyclotomicExtension {e} ℚ K :=
    (IntermediateField.isCyclotomicExtension_singleton_iff_eq_adjoin e ℚ ℂ K
      isPrimitiveRoot_complexRoot).mpr rfl
  have hz' : IsIntegral ℤ (⟨z, hz⟩ : K) :=
    (isIntegral_algHom_iff K.val.toIntAlgHom Subtype.val_injective).mp hint
  obtain ⟨a, ha⟩ :=
    (IsCyclotomicExtension.Rat.isIntegralClosure_adjoin_singleton hζ).isIntegral_iff.mp hz'
  let A := (Algebra.adjoin ℤ ({ζ} : Set K)).map K.val.toIntAlgHom
  have : z ∈ A := ⟨a, a.property, congrArg Subtype.val ha⟩
  simpa [A, AlgHom.map_adjoin_singleton, ζ] using this

end TauCeti.Cyclotomic
