/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.Profinite.Free.Peripheral.Topology
public import TauCeti.Topology.Algebra.Group.Profinite.Procyclic
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.PadicUnits

/-!
# A section of the peripheral exponent over the principal units

Let `F` be a free pro-`p` group of positive rank with a marked basis. The exponent character
`exponent : peripheralAut hF (basis e) →* ℤ_[p]ˣ` is continuous and surjective. This file shows
that it splits continuously and homomorphically over every principal unit group
`U^(k) = 1 + p ^ k ℤ_p` with `k ≥ 1`, and `k ≥ 2` when `p = 2`.

The group `peripheralAut hF (basis e)` is profinite, but for odd `p` it is not pro-`p`, since its
exponent maps it onto `ℤ_[p]ˣ`, which contains the roots of unity of order `p - 1`. So `p`-adic
powers are not available in it directly. Instead, choose a peripheral automorphism `φ` whose
exponent is a unit `w` of exact level `k`, and pass to its `p`-part `q = φ ^ᶻ e_p`, a profinite
power by the `p`-adic idempotent of the profinite integers. The closed subgroup generated by `q` is
pro-`p`, and `q` still has exponent `w`, because `w` lies in the pro-`p` group `U^(k)`. The section
sends `v ∈ U^(k)` to the `p`-adic power `q ^ λ(v)`, where `λ` is the inverse of the topological
isomorphism `principalUnitsEquiv : Multiplicative ℤ_[p] ≃ₜ* U^(k)`, `l ↦ w ^ l`. Two continuous
homomorphisms out of `ℤ_p` agreeing at `1` coincide, so the exponent of `q ^ l` is `w ^ l`, and the
exponent of the section at `v` is `w ^ λ(v) = v`.

No section is claimed over all of `ℤ_[p]ˣ`. Over the roots of unity a section would be a peripheral
automorphism of finite order with prescribed exponent, and nothing here constructs one compatibly.

## Main results

* `TauCeti.Peripheral.exists_isProP_closedZpowers_and_exponent_eq_iff`: the exponents of the
  peripheral automorphisms generating a pro-`p` closed subgroup are exactly the units in
  `1 + pℤ_p`.
* `TauCeti.Peripheral.exists_section_principalUnits`: the exponent character has a continuous
  homomorphic section over `U^(k)`.

## References

* Y. Ihara, "Braids, Galois groups, and some arithmetic functions", Proc. ICM Kyoto 1990,
  99–120, for peripheral automorphisms of free pro-`p` groups and their common exponent.
* L. Ribes and P. Zalesskii, *Profinite Groups*, Sections 4.1 and 4.3, for the prime parts of
  elements of a profinite group.
-/

public section

namespace TauCeti.Peripheral

open scoped zHat

variable {p r : ℕ} [Fact p.Prime] {F : Type*} [Group F] [TopologicalSpace F]
  [IsTopologicalGroup F] [CompactSpace F] [TotallyDisconnectedSpace F]
  (hF : IsProP p F) (e : F ≃ₜ* freeProP p (Fin r)) (hr : 0 < r)

/-- The exponent character, bundled as a continuous homomorphism. -/
private noncomputable def exponentHom : peripheralAut hF (basis e) →ₜ* ℤ_[p]ˣ :=
  ⟨exponent hF e hr, continuous_exponent hF e hr⟩

private theorem exponentHom_apply (φ : peripheralAut hF (basis e)) :
    exponentHom hF e hr φ = exponent hF e hr φ :=
  (rfl)

/-- **The exponents of pro-`p` procyclic peripheral automorphisms are the principal units.**
A unit `w` is the exponent of a peripheral automorphism `q` whose closed procyclic subgroup is
pro-`p` exactly when `w ∈ 1 + pℤ_p`. -/
theorem exists_isProP_closedZpowers_and_exponent_eq_iff (w : ℤ_[p]ˣ) :
    (∃ q : peripheralAut hF (basis e), IsProP p (closedZpowers q) ∧ exponent hF e hr q = w) ↔
      w ∈ unitsPrincipal p 1 := by
  constructor
  · rintro ⟨q, hQ, rfl⟩
    -- the exponent restricted to the pro-`p` group `closedZpowers q`, evaluated at `q`
    exact hQ.mem_unitsPrincipal_one ((exponentHom hF e hr).comp
      ⟨(closedZpowers q).subtype, continuous_subtype_val⟩) ⟨q, mem_closedZpowers q⟩
  · intro hw
    -- the `p`-part of a peripheral automorphism of exponent `w` still has exponent `w`
    obtain ⟨φ, hφ⟩ := exponent_surjective hF e hr w
    refine ⟨φ ^ᶻ zHat.idem.{0} p, isProP_closedZpowers_zpowHat_idem p φ, ?_⟩
    -- the closed subgroup generated by `w` lies in the pro-`p` group `1 + pℤ_p`
    have hw' : IsProP p (closedZpowers w) := (isProP_iff_le_unitsPrincipal_one _).mpr
      ((closedZpowers_le (isClosed_unitsPrincipal p 1)).mpr hw)
    have h := map_zpowHat (exponentHom hF e hr) φ (zHat.idem.{0} p)
    rwa [exponentHom_apply, exponentHom_apply, hφ, zpowHat_idem_of_isProP_closedZpowers hw'] at h

/-- **The section of the exponent over the principal units.** Let `F` be a marked free pro-`p`
group of positive rank, and let `k ≥ 1`, with `k ≥ 2` when `p = 2`. Then the exponent character
of the peripheral automorphism group has a continuous homomorphic section over the principal
units `U^(k) = 1 + p ^ k ℤ_p`: a continuous homomorphism `s : U^(k) →ₜ* peripheralAut hF (basis e)`
with `exponent (s v) = v` for every `v`. -/
theorem exists_section_principalUnits {k : ℕ} (hk : 0 < k) (hk₂ : p = 2 → 2 ≤ k) :
    ∃ s : unitsPrincipal p k →ₜ* peripheralAut hF (basis e),
      ∀ v, exponent hF e hr (s v) = v := by
  obtain ⟨w, hw, hw'⟩ := exists_mem_unitsPrincipal_and_notMem_succ_of_pos p hk
  obtain ⟨q, hQ, hq⟩ := (exists_isProP_closedZpowers_and_exponent_eq_iff hF e hr w).mpr
    (unitsPrincipal_antitone p hk hw)
  let ρ := principalUnitsEquiv hk hk₂ hw hw'
  let ι : unitsPrincipal p k →ₜ* ℤ_[p]ˣ := ⟨(unitsPrincipal p k).subtype, continuous_subtype_val⟩
  let j : closedZpowers q →ₜ* peripheralAut hF (basis e) :=
    ⟨(closedZpowers q).subtype, continuous_subtype_val⟩
  -- the bundled inclusions evaluate as coercions
  have hι (v : unitsPrincipal p k) : ι v = v := rfl
  have hj (x : closedZpowers q) : j x = x := rfl
  -- `l ↦ q ^ l`, computed in the pro-`p` group `closedZpowers q`, then included back
  let ψ := j.comp (hQ.padicPowHom ⟨q, mem_closedZpowers q⟩)
  -- the exponent of `q ^ l` is `w ^ l`: both sides are continuous in `l` and agree at `1`
  have hexp : (exponentHom hF e hr).comp ψ = ι.comp ρ :=
    continuousMonoidHom_ext_multiplicative_padicInt (by
      simp only [ContinuousMonoidHom.comp_toFun, ψ, ContinuousMonoidHom.coe_coe,
        IsProP.padicPowHom_ofAdd_one, hj, hι, ρ, principalUnitsEquiv_ofAdd_one, exponentHom_apply,
        hq])
  refine ⟨ψ.comp ρ.symm, fun v ↦ ?_⟩
  have h := DFunLike.congr_fun hexp (ρ.symm v)
  simp only [ContinuousMonoidHom.comp_toFun, exponentHom_apply, ContinuousMonoidHom.coe_coe,
    ContinuousMulEquiv.apply_symm_apply, hι] at h
  exact h

end TauCeti.Peripheral
