/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Perm.SylowFour
public import TauCeti.GroupTheory.SpecificGroups.Dihedral.Basic
public import TauCeti.Algebra.Group.Subgroup.Map
import TauCeti.GroupTheory.Perm.OrbitCount.FinRotate

/-!
# The dihedral group of the square and the two-by-two wreath product

The `4T3` reference subgroup is generated by a reflection of the square and a second
reflection whose product is its four-cycle. The dihedral recognition theorem identifies this
subgroup with `DihedralGroup 4`. The faithful imprimitive action of `C₂ ≀ S₂` has the same label,
and hence gives an isomorphism from the wreath product to `DihedralGroup 4`.
-/

public section

open Equiv

namespace TauCeti

private abbrev squareGroup : Subgroup (Perm (Fin 4)) :=
  referenceSubgroup 4 ⟨2, by simp⟩

private def squareRotation : squareGroup :=
  ⟨finRotate 4, by
    simpa [squareGroup, referenceSubgroup_four_two] using
      (Subgroup.subset_closure (by simp) :
        finRotate 4 ∈ Subgroup.closure {finRotate 4, swap 0 2})⟩

private def squareReflection : squareGroup :=
  ⟨swap 0 2, by
    simpa [squareGroup, referenceSubgroup_four_two] using
      (Subgroup.subset_closure (by simp) :
        swap (0 : Fin 4) 2 ∈ Subgroup.closure {finRotate 4, swap 0 2})⟩

private def secondSquareReflection : squareGroup := squareReflection * squareRotation

private theorem squareReflection_sq : squareReflection * squareReflection = 1 := by
  apply Subtype.ext
  -- The subtype equality becomes a concrete permutation equality after exposing its carrier.
  change swap (0 : Fin 4) 2 * swap 0 2 = 1
  decide

private theorem secondSquareReflection_sq :
    secondSquareReflection * secondSquareReflection = 1 := by
  apply Subtype.ext
  -- The subgroup coercion hides the two explicit permutations from finite decision.
  change (swap (0 : Fin 4) 2 * finRotate 4) * (swap 0 2 * finRotate 4) = 1
  decide

private theorem squareReflection_ne_one : squareReflection ≠ 1 := by
  intro h
  have h' := congrArg (fun x : squareGroup => (x : Perm (Fin 4))) h
  -- Read the subtype equality as the concrete permutation equality it asserts.
  change swap (0 : Fin 4) 2 = 1 at h'
  exact (by decide : swap (0 : Fin 4) 2 ≠ 1) h'

private theorem secondSquareReflection_ne_one : secondSquareReflection ≠ 1 := by
  intro h
  have h' := congrArg (fun x : squareGroup => (x : Perm (Fin 4))) h
  -- Read the subtype equality as the concrete permutation equality it asserts.
  change swap (0 : Fin 4) 2 * finRotate 4 = 1 at h'
  exact (by decide : swap (0 : Fin 4) 2 * finRotate 4 ≠ 1) h'

private theorem orderOf_reflections_mul :
    orderOf (squareReflection * secondSquareReflection) = 4 := by
  have heq : squareReflection * secondSquareReflection = squareRotation := by
    rw [secondSquareReflection, ← mul_assoc, squareReflection_sq, one_mul]
  rw [heq, ← Subgroup.orderOf_coe]
  -- The order of an element of a subgroup is the order of its underlying permutation.
  change orderOf (finRotate 4 : Perm (Fin 4)) = 4
  exact orderOf_finRotate (by decide : 4 ≠ 0)

private theorem closure_reflections_eq_top :
    Subgroup.closure ({squareReflection, secondSquareReflection} : Set squareGroup) = ⊤ := by
  let K := Subgroup.closure ({squareReflection, secondSquareReflection} : Set squareGroup)
  have hs : squareReflection ∈ K := Subgroup.subset_closure (by simp)
  have ht : secondSquareReflection ∈ K := Subgroup.subset_closure (by simp)
  have hr : squareRotation ∈ K := by
    have h : squareReflection⁻¹ * secondSquareReflection ∈ K := mul_mem (inv_mem hs) ht
    simpa [secondSquareReflection] using h
  have hle :
      Subgroup.closure (((↑) : squareGroup → Perm (Fin 4)) ⁻¹'
        ({finRotate 4, swap 0 2} : Set (Perm (Fin 4)))) ≤ K := by
    apply (Subgroup.closure_le _).2
    intro g hg
    simp only [Set.mem_preimage, Set.mem_insert_iff, Set.mem_singleton_iff] at hg
    rcases hg with h | h
    · have heq : g = squareRotation := Subtype.ext h
      simpa [heq] using hr
    · have heq : g = squareReflection := Subtype.ext h
      simpa [heq] using hs
  have htop :
      Subgroup.closure (((↑) : squareGroup → Perm (Fin 4)) ⁻¹'
        ({finRotate 4, swap 0 2} : Set (Perm (Fin 4)))) = ⊤ := by
    have h : squareGroup =
        Subgroup.closure ({finRotate 4, swap 0 2} : Set (Perm (Fin 4))) := by
      simpa only [squareGroup] using referenceSubgroup_four_two
    rw [h]
    exact Subgroup.closure_closure_coe_preimage
  exact eq_top_iff.mpr (by simpa only [htop] using hle)

/-- The `4T3` reference subgroup is the dihedral group of the square. The four-cycle
`finRotate 4` corresponds to `r 1`, and the reflection `swap 0 2` to `sr 0`. -/
noncomputable def referenceSubgroupFourMulEquivDihedralGroupFour :
    referenceSubgroup 4 ⟨2, by simp⟩ ≃* DihedralGroup 4 :=
  (dihedralGroupMulEquiv squareReflection_sq secondSquareReflection_sq
    squareReflection_ne_one secondSquareReflection_ne_one orderOf_reflections_mul
    closure_reflections_eq_top).symm

/-- The generator of the dihedral rotation subgroup acts as the four-cycle of the square. -/
@[simp]
theorem coe_referenceSubgroupFourMulEquivDihedralGroupFour_symm_r_one :
    (referenceSubgroupFourMulEquivDihedralGroupFour.symm (DihedralGroup.r 1) : Perm (Fin 4)) =
      finRotate 4 := by
  rw [referenceSubgroupFourMulEquivDihedralGroupFour, MulEquiv.symm_symm,
    dihedralGroupMulEquiv_apply, dihedralHom_r]
  have hcast : (ZMod.cast (1 : ZMod 4) : ℤ) = 1 := by decide
  rw [hcast, zpow_one]
  have heq : squareReflection * secondSquareReflection = squareRotation := by
    rw [secondSquareReflection, ← mul_assoc, squareReflection_sq, one_mul]
  exact congrArg Subtype.val heq

/-- The distinguished dihedral reflection swaps opposite vertices `0` and `2`. -/
@[simp]
theorem coe_referenceSubgroupFourMulEquivDihedralGroupFour_symm_sr_zero :
    (referenceSubgroupFourMulEquivDihedralGroupFour.symm (DihedralGroup.sr 0) : Perm (Fin 4)) =
      swap 0 2 := by
  rw [referenceSubgroupFourMulEquivDihedralGroupFour, MulEquiv.symm_symm,
    dihedralGroupMulEquiv_apply, dihedralHom_sr]
  simp
  rfl

/-- The four-cycle in `4T3` maps to the standard dihedral rotation. -/
@[simp]
theorem referenceSubgroupFourMulEquivDihedralGroupFour_finRotate :
    referenceSubgroupFourMulEquivDihedralGroupFour
      (⟨finRotate 4, by
        simpa [referenceSubgroup_four_two] using
          (Subgroup.subset_closure (by simp) :
            finRotate 4 ∈ Subgroup.closure {finRotate 4, swap 0 2})⟩ :
        referenceSubgroup 4 ⟨2, by simp⟩) =
        DihedralGroup.r 1 := by
  apply referenceSubgroupFourMulEquivDihedralGroupFour.symm.injective
  apply Subtype.ext
  simpa only [MulEquiv.symm_apply_apply] using
    coe_referenceSubgroupFourMulEquivDihedralGroupFour_symm_r_one.symm

/-- The swap of opposite vertices in `4T3` maps to the standard dihedral reflection. -/
@[simp]
theorem referenceSubgroupFourMulEquivDihedralGroupFour_swap :
    referenceSubgroupFourMulEquivDihedralGroupFour
      (⟨swap 0 2, by
        simpa [referenceSubgroup_four_two] using
          (Subgroup.subset_closure (by simp) :
            swap (0 : Fin 4) 2 ∈ Subgroup.closure {finRotate 4, swap 0 2})⟩ :
        referenceSubgroup 4 ⟨2, by simp⟩) =
        DihedralGroup.sr 0 := by
  apply referenceSubgroupFourMulEquivDihedralGroupFour.symm.injective
  apply Subtype.ext
  simpa only [MulEquiv.symm_apply_apply] using
    coe_referenceSubgroupFourMulEquivDihedralGroupFour_symm_sr_zero.symm

/-- A conjugator from the wreath product's four-point permutation image to `4T3`. -/
noncomputable def wreathTwoFourConjugator : Perm (Fin 4) :=
  Classical.choose ((transitiveGroupLabel_iff _ _).mp transitiveGroupLabel_wreathTwoToPermFour)

/-- The chosen conjugator carries the wreath product's permutation image onto `4T3`. -/
theorem wreathTwoToPermFour_range_map_conj_eq_referenceSubgroup :
    Subgroup.map (MulAut.conj wreathTwoFourConjugator).toMonoidHom
      wreathTwoToPermFour.range = referenceSubgroup 4 ⟨2, by simp⟩ :=
  Classical.choose_spec
    ((transitiveGroupLabel_iff _ _).mp transitiveGroupLabel_wreathTwoToPermFour)

/-- The two-by-two cyclic wreath product is dihedral of order eight. The isomorphism uses a
conjugation of its faithful four-point action onto the `4T3` reference subgroup. -/
noncomputable def wreathTwoMulEquivDihedralGroupFour :
    WreathProduct (Multiplicative (ZMod 2)) (Fin 2) ≃* DihedralGroup 4 := by
  let e₁ : WreathProduct (Multiplicative (ZMod 2)) (Fin 2) ≃*
      wreathTwoToPermFour.range :=
    wreathTwoSylowFourEquiv.trans (MulEquiv.subgroupCongr wreathTwoSylowFour_toSubgroup)
  let e₂ : wreathTwoToPermFour.range ≃* squareGroup :=
    Subgroup.congrOfMapEq (MulAut.conj wreathTwoFourConjugator)
      wreathTwoToPermFour_range_map_conj_eq_referenceSubgroup
  exact (e₁.trans e₂).trans referenceSubgroupFourMulEquivDihedralGroupFour

/-- The wreath-product isomorphism transports the four-point action by the chosen conjugator. -/
@[simp]
theorem coe_referenceSubgroupFourMulEquivDihedralGroupFour_symm_wreathTwoMulEquivDihedralGroupFour
    (w : WreathProduct (Multiplicative (ZMod 2)) (Fin 2)) :
    (referenceSubgroupFourMulEquivDihedralGroupFour.symm
      (wreathTwoMulEquivDihedralGroupFour w) : Perm (Fin 4)) =
        (MulAut.conj wreathTwoFourConjugator) (wreathTwoToPermFour w) := by
  simp only [wreathTwoMulEquivDihedralGroupFour, MulEquiv.trans_apply,
    MulEquiv.symm_apply_apply]
  calc
    _ = (MulAut.conj wreathTwoFourConjugator)
        ((MulEquiv.subgroupCongr wreathTwoSylowFour_toSubgroup)
          (wreathTwoSylowFourEquiv w) : Perm (Fin 4)) :=
      Subgroup.coe_congrOfMapEq_apply _ _ _
    _ = _ := by
      -- The remaining subgroup equivalence only changes the subtype of the permutation.
      change (MulAut.conj wreathTwoFourConjugator)
        (wreathTwoSylowFourEquiv w : Perm (Fin 4)) = _
      rw [coe_wreathTwoSylowFourEquiv, MulAut.conj_apply]

end TauCeti
