/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Perm.OrbitCount
import Mathlib.Dynamics.PeriodicPts.Lemmas

/-!
# Transpositions and the number of orbits

Multiplying a permutation `σ` of a finite type by the transposition `Equiv.swap a b` either merges
the orbit of `a` with the orbit of `b`, or splits the single orbit carrying both of them in two.
The number of orbits therefore changes by exactly one, and which way is decided by
`Equiv.Perm.SameCycle σ a b`:

* `TauCeti.orbitCount_swap_mul_add_one_of_not_sameCycle`, the merging step;
* `TauCeti.orbitCount_swap_mul_of_sameCycle`, the splitting step.

Iterating the two steps measures how many transpositions it takes to build `σ`: every
factorization of `σ` into transpositions has at least `Nat.card α - TauCeti.orbitCount σ` factors
(`TauCeti.card_le_orbitCount_add_length`), and one with exactly that many exists
(`TauCeti.exists_isSwap_list_prod_eq`), so that number is the reflection length of `σ`
(`TauCeti.isLeast_length_isSwap_list`).

Both steps rest on a description of the orbits of the product:
`TauCeti.sameCycle_or_of_sameCycle_swap_mul` says that two points sharing an orbit of
`Equiv.swap a b * σ` either shared an orbit of `σ` already, or were attached one to `a` and the
other to `b`. That containment needs no finiteness; what does need it is the merging statement
`TauCeti.sameCycle_swap_mul_of_not_sameCycle`, proved by walking right round the finite `σ`-orbit
of `b` to the single step that `Equiv.swap a b` diverts to `a`.

⚠ Finiteness is essential there rather than a convenience. For the shift on two disjoint copies of
`ℤ`, with `a` and `b` the two origins, the product `Equiv.swap a b * σ` cuts both lines and
reconnects them into two lines again, so the two orbits do not merge.

`TauCeti.orbitCount_mul_swap_add_one` in `TauCeti/GroupTheory/Perm/OrbitCount.lean` is a different
statement, not a special case of the ones here: it compares permutations of two different types and
asks for nothing beyond finitely many orbits.
-/

public section

namespace TauCeti

open Equiv Equiv.Perm

-- The two transposition steps are the step lemma of Layer 0.5 of the Tau Ceti `BelyiMaps`
-- roadmap, whose formal prototype `Suggested.lean` states them as one equation in the deferred
-- `cycleCount` of a permutation; here they are stated for `TauCeti.orbitCount`, and in the two
-- directions rather than through a `Nat` subtraction. The minimal factorization is what the
-- induction for the Euler-characteristic bound of that roadmap's Layer 0.6 walks along.

variable {α : Type*} [DecidableEq α] {σ : Perm α} {a b x y : α}

/-- The orbits of `σ`, with the orbit of `a` and the orbit of `b` merged into one. This is the orbit
relation of the group generated by `σ` and `Equiv.swap a b`, which is what
`TauCeti.sameCycle_or_of_sameCycle_swap_mul` and `TauCeti.sameCycle_swap_mul_of_not_sameCycle`
prove between them for the single element `Equiv.swap a b * σ` of that group. -/
private def MergeRel (σ : Perm α) (a b : α) : α → α → Prop := fun x y =>
  σ.SameCycle x y ∨ ((σ.SameCycle x a ∨ σ.SameCycle x b) ∧ (σ.SameCycle y a ∨ σ.SameCycle y b))

omit [DecidableEq α] in
private theorem mergeRel_attach (hxy : σ.SameCycle x y)
    (hy : σ.SameCycle y a ∨ σ.SameCycle y b) : σ.SameCycle x a ∨ σ.SameCycle x b :=
  hy.imp hxy.trans hxy.trans

omit [DecidableEq α] in
private theorem equivalence_mergeRel (σ : Perm α) (a b : α) : Equivalence (MergeRel σ a b) := by
  refine ⟨fun u => Or.inl (SameCycle.refl σ u), ?_, ?_⟩
  · rintro u v (huv | ⟨hu, hv⟩)
    · exact Or.inl huv.symm
    · exact Or.inr ⟨hv, hu⟩
  · rintro u v w (huv | ⟨hu, hv⟩) (hvw | ⟨hv', hw⟩)
    · exact Or.inl (huv.trans hvw)
    · exact Or.inr ⟨mergeRel_attach huv hv', hw⟩
    · exact Or.inr ⟨hu, mergeRel_attach hvw.symm hv⟩
    · exact Or.inr ⟨hu, hw⟩

/-- Every element of the group generated by `σ` and `Equiv.swap a b` moves each point inside its
class for `TauCeti.MergeRel σ a b`: the generator `σ` does so because it preserves its own orbits,
and the generator `Equiv.swap a b` does so because the classes of `a` and of `b` have been
merged. -/
private theorem mergeRel_apply_of_mem_closure (σ : Perm α) (a b : α) {g : Perm α}
    (hg : g ∈ Subgroup.closure {σ, Equiv.swap a b}) (z : α) : MergeRel σ a b z (g z) := by
  have heq := equivalence_mergeRel σ a b
  let H : Subgroup (Perm α) :=
    { carrier := {g | ∀ z, MergeRel σ a b z (g z)}
      one_mem' := fun z => heq.refl z
      mul_mem' := fun {g h} hg hh z => heq.trans (hh z) (hg (h z))
      inv_mem' := fun {g} hg z => heq.symm (by simpa using hg (g⁻¹ z)) }
  have hclosure : Subgroup.closure {σ, Equiv.swap a b} ≤ H := by
    rw [Subgroup.closure_le]
    intro f hf
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hf
    rcases hf with rfl | rfl
    · exact fun z => Or.inl ⟨1, by simp⟩
    · intro z
      rcases eq_or_ne z a with rfl | hza
      · rw [Equiv.swap_apply_left]
        exact Or.inr ⟨Or.inl (SameCycle.refl σ z), Or.inr (SameCycle.refl σ b)⟩
      rcases eq_or_ne z b with rfl | hzb
      · rw [Equiv.swap_apply_right]
        exact Or.inr ⟨Or.inr (SameCycle.refl σ z), Or.inl (SameCycle.refl σ a)⟩
      · rw [Equiv.swap_apply_of_ne_of_ne hza hzb]
        exact Or.inl (SameCycle.refl σ z)
  exact hclosure hg z

/-- **Multiplying by a transposition can only merge the orbits of its two points.** Two points in
one orbit of `Equiv.swap a b * σ` either lie in one orbit of `σ` already, or one of them is joined
to `a` and the other to `b`. -/
theorem sameCycle_or_of_sameCycle_swap_mul (h : (Equiv.swap a b * σ).SameCycle x y) :
    σ.SameCycle x y ∨
      ((σ.SameCycle x a ∨ σ.SameCycle x b) ∧ (σ.SameCycle y a ∨ σ.SameCycle y b)) := by
  obtain ⟨i, rfl⟩ := h
  refine mergeRel_apply_of_mem_closure σ a b (zpow_mem (mul_mem ?_ ?_) i) x
  · exact Subgroup.subset_closure (by simp)
  · exact Subgroup.subset_closure (by simp)

/-- Once `a` and `b` share an orbit of `Equiv.swap a b * σ`, every orbit of `σ` is contained in an
orbit of the product. -/
theorem sameCycle_swap_mul_of_sameCycle (hab : (Equiv.swap a b * σ).SameCycle a b)
    (h : σ.SameCycle x y) : (Equiv.swap a b * σ).SameCycle x y := by
  have h' : (Equiv.swap a b * (Equiv.swap a b * σ)).SameCycle x y := by
    rwa [Equiv.swap_mul_self_mul]
  rcases sameCycle_or_of_sameCycle_swap_mul h' with hxy | ⟨hx, hy⟩
  · exact hxy
  · exact SameCycle.trans (hx.elim id fun h => h.trans hab.symm)
      (SameCycle.symm (hy.elim id fun h => h.trans hab.symm))

/-- The walk along the orbit of `c`: as long as the powers of `σ` have carried `c` neither to `a`
nor to `b`, the product `Equiv.swap a b * σ` has moved `c` exactly as `σ` does. -/
private theorem pow_swap_mul_apply_of_lt {c : α} {j : ℕ}
    (h : ∀ i, 0 < i → i < j → (σ ^ i) c ≠ a ∧ (σ ^ i) c ≠ b) :
    ∀ i < j, ((Equiv.swap a b * σ) ^ i) c = (σ ^ i) c := by
  intro i
  induction i with
  | zero => exact fun _ => by simp
  | succ i ih =>
    intro hi
    have hne := h (i + 1) (by omega) hi
    have h1 : σ ((σ ^ i) c) ≠ a := by
      rw [← Equiv.Perm.mul_apply, ← pow_succ']; exact hne.1
    have h2 : σ ((σ ^ i) c) ≠ b := by
      rw [← Equiv.Perm.mul_apply, ← pow_succ']; exact hne.2
    rw [pow_succ', Equiv.Perm.mul_apply, ih (by omega), Equiv.Perm.mul_apply,
      Equiv.swap_apply_of_ne_of_ne h1 h2, pow_succ' σ, Equiv.Perm.mul_apply]

/-- The last step of the walk: when the `j`-th power of `σ` is the first to carry `c` to `b`, the
`j`-th power of `Equiv.swap a b * σ` carries `c` to `a` instead. -/
private theorem pow_swap_mul_apply_eq {c : α} {j : ℕ} (hj : 0 < j)
    (h : ∀ i, 0 < i → i < j → (σ ^ i) c ≠ a ∧ (σ ^ i) c ≠ b) (hjb : (σ ^ j) c = b) :
    ((Equiv.swap a b * σ) ^ j) c = a := by
  obtain ⟨j, rfl⟩ : ∃ k, j = k + 1 := ⟨j - 1, by omega⟩
  have hstep : σ ((σ ^ j) c) = b := by rw [← Equiv.Perm.mul_apply, ← pow_succ']; exact hjb
  rw [pow_succ', Equiv.Perm.mul_apply, pow_swap_mul_apply_of_lt h j (by omega),
    Equiv.Perm.mul_apply, hstep, Equiv.swap_apply_right]

/-- **Multiplying by a transposition merges the orbits of its two points.** If `a` and `b` lie in
different orbits of `σ`, they lie in one orbit of `Equiv.swap a b * σ`: following the finite
`σ`-orbit of `b` right round, the product diverts its closing step to `a`. -/
theorem sameCycle_swap_mul_of_not_sameCycle [Finite α] (h : ¬ σ.SameCycle a b) :
    (Equiv.swap a b * σ).SameCycle a b := by
  obtain ⟨m, hmpos, hmb, hmin⟩ : ∃ m : ℕ, 0 < m ∧ (σ ^ m) b = b ∧
      ∀ i, 0 < i → i < m → (σ ^ i) b ≠ b :=
    ⟨Function.minimalPeriod (⇑σ) b,
      Function.minimalPeriod_pos_of_mem_periodicPts (σ.injective.mem_periodicPts b),
      Function.isPeriodicPt_minimalPeriod (⇑σ) b,
      fun i hi him => Function.not_isPeriodicPt_of_pos_of_lt_minimalPeriod hi.ne' him⟩
  have hna : ∀ i : ℕ, (σ ^ i) b ≠ a := fun i hcon =>
    h (SameCycle.symm (⟨(i : ℤ), by simpa using hcon⟩ : σ.SameCycle b a))
  refine SameCycle.symm (⟨(m : ℤ), ?_⟩ : (Equiv.swap a b * σ).SameCycle b a)
  simpa using pow_swap_mul_apply_eq hmpos (fun i hi him => ⟨hna i, hmin i hi him⟩) hmb

/-- **Multiplying by a transposition splits the orbit of its two points.** If `a ≠ b` lie in one
orbit of `σ`, they lie in different orbits of `Equiv.swap a b * σ`: the product closes the arc from
`a` to `b` into an orbit of its own, which `b` is not on. -/
theorem not_sameCycle_swap_mul_of_sameCycle [Finite α] (hab : a ≠ b) (h : σ.SameCycle a b) :
    ¬ (Equiv.swap a b * σ).SameCycle a b := by
  classical
  obtain ⟨j, hjpos, hja, hjmin⟩ : ∃ j : ℕ, 0 < j ∧ (σ ^ j) a = b ∧
      ∀ i, 0 < i → i < j → (σ ^ i) a ≠ b := by
    have hex : ∃ j, 0 < j ∧ (σ ^ j) a = b := by
      obtain ⟨i, hipos, -, hi⟩ := h.exists_pow_eq''
      exact ⟨i, hipos, hi⟩
    exact ⟨Nat.find hex, (Nat.find_spec hex).1, (Nat.find_spec hex).2,
      fun i hi hij hcon => Nat.find_min hex hij ⟨hi, hcon⟩⟩
  -- Before reaching `b`, the powers of `σ` cannot return to `a` either.
  have hwalk : ∀ i, 0 < i → i < j → (σ ^ i) a ≠ a ∧ (σ ^ i) a ≠ b := by
    refine fun i hi hij => ⟨fun hcon => hjmin (j - i) (by omega) (by omega) ?_, hjmin i hi hij⟩
    have hgo : (σ ^ (j - i)) ((σ ^ i) a) = b := by
      rw [← Equiv.Perm.mul_apply, ← pow_add, show j - i + i = j by omega]
      exact hja
    rwa [hcon] at hgo
  have hfix : ((Equiv.swap a b * σ) ^ j) a = a := pow_swap_mul_apply_eq hjpos hwalk hja
  rintro ⟨k, hk⟩
  -- The orbit of `a` under the product is spanned by the powers below `j`, and none of them is `b`.
  have hz : ∀ q : ℤ, ((Equiv.swap a b * σ) ^ ((j : ℤ) * q)) a = a := by
    intro q
    rw [zpow_mul, zpow_natCast]
    exact Equiv.Perm.zpow_apply_eq_self_of_apply_eq_self hfix q
  have hr : ((Equiv.swap a b * σ) ^ (k % (j : ℤ))) a = b := by
    have e1 : (((Equiv.swap a b * σ) ^ (k % (j : ℤ))) *
        ((Equiv.swap a b * σ) ^ ((j : ℤ) * (k / j)))) a = b := by
      rw [← zpow_add, Int.emod_add_mul_ediv]
      exact hk
    rwa [Equiv.Perm.mul_apply, hz (k / j)] at e1
  have h0 : 0 ≤ k % (j : ℤ) := Int.emod_nonneg k (by exact_mod_cast hjpos.ne')
  have h1 : k % (j : ℤ) < j := Int.emod_lt_of_pos k (by exact_mod_cast hjpos)
  obtain ⟨r, hrj⟩ : ∃ r : ℕ, (r : ℤ) = k % (j : ℤ) := ⟨(k % (j : ℤ)).toNat, by omega⟩
  rw [← hrj, zpow_natCast] at hr
  rcases Nat.eq_zero_or_pos r with rfl | hrpos
  · rw [pow_zero] at hr
    exact hab (by simpa using hr)
  · rw [pow_swap_mul_apply_of_lt hwalk r (by omega)] at hr
    exact hjmin r hrpos (by omega) hr

/-- **The transposition step lemma, merging.** If `a` and `b` lie in different orbits of `σ`, then
`Equiv.swap a b * σ` has one orbit fewer than `σ`: its orbits are those of `σ`, with the orbit of
`a` and the orbit of `b` merged. -/
theorem orbitCount_swap_mul_add_one_of_not_sameCycle [Finite α] (h : ¬ σ.SameCycle a b) :
    orbitCount (Equiv.swap a b * σ) + 1 = orbitCount σ :=
  have hab := sameCycle_swap_mul_of_not_sameCycle h
  orbitCount_add_one_of_merge (fun huv => sameCycle_swap_mul_of_sameCycle hab huv)
    (fun huv => sameCycle_or_of_sameCycle_swap_mul huv) hab h

/-- **The transposition step lemma, splitting.** If `a ≠ b` lie in one orbit of `σ`, then
`Equiv.swap a b * σ` has one orbit more than `σ`: that orbit has been cut in two. -/
theorem orbitCount_swap_mul_of_sameCycle [Finite α] (hab : a ≠ b) (h : σ.SameCycle a b) :
    orbitCount (Equiv.swap a b * σ) = orbitCount σ + 1 := by
  have h' := orbitCount_swap_mul_add_one_of_not_sameCycle
    (not_sameCycle_swap_mul_of_sameCycle hab h)
  rw [Equiv.swap_mul_self_mul] at h'
  exact h'.symm

/-- Multiplying by a transposition removes at most one orbit, whichever of the two steps applies. -/
theorem orbitCount_le_orbitCount_swap_mul_add_one [Finite α] (σ : Perm α) (a b : α) :
    orbitCount σ ≤ orbitCount (Equiv.swap a b * σ) + 1 := by
  rcases eq_or_ne a b with rfl | hab
  · rw [Equiv.swap_self, show (Equiv.refl α : Perm α) = 1 from rfl, one_mul]
    omega
  by_cases h : σ.SameCycle a b
  · rw [orbitCount_swap_mul_of_sameCycle hab h]
    omega
  · exact (orbitCount_swap_mul_add_one_of_not_sameCycle h).symm.le

/-- **The transposition step lemma on the other side, merging.** -/
theorem orbitCount_mul_swap_add_one_of_not_sameCycle [Finite α] (h : ¬ σ.SameCycle a b) :
    orbitCount (σ * Equiv.swap a b) + 1 = orbitCount σ := by
  rw [show σ * Equiv.swap a b = Equiv.swap (σ a) (σ b) * σ by rw [Equiv.swap_apply_apply]; group]
  refine orbitCount_swap_mul_add_one_of_not_sameCycle ?_
  rwa [sameCycle_apply_left, sameCycle_apply_right]

/-- **The transposition step lemma on the other side, splitting.** -/
theorem orbitCount_mul_swap_of_sameCycle [Finite α] (hab : a ≠ b) (h : σ.SameCycle a b) :
    orbitCount (σ * Equiv.swap a b) = orbitCount σ + 1 := by
  rw [show σ * Equiv.swap a b = Equiv.swap (σ a) (σ b) * σ by rw [Equiv.swap_apply_apply]; group]
  refine orbitCount_swap_mul_of_sameCycle (σ.injective.ne hab) ?_
  rwa [sameCycle_apply_left, sameCycle_apply_right]

omit [DecidableEq α] in
/-- A permutation other than the identity has fewer orbits than there are points: the two ends of
one of its nontrivial steps share an orbit. -/
theorem orbitCount_lt_card_of_ne_one [Finite α] (h : σ ≠ 1) : orbitCount σ < Nat.card α := by
  classical
  obtain ⟨x, hx⟩ : ∃ x, σ x ≠ x := by
    by_contra hcon
    refine h (Equiv.ext fun x => ?_)
    simpa using not_not.mp (not_exists.mp hcon x)
  have hsplit := orbitCount_swap_mul_of_sameCycle (Ne.symm hx)
    (⟨1, by simp⟩ : σ.SameCycle x (σ x))
  have hle := orbitCount_le_card (Equiv.swap x (σ x) * σ)
  omega

/-- **No factorization into transpositions is shorter than the reflection length.** Every
factorization of a permutation into transpositions has at least `Nat.card α - orbitCount` factors,
because each factor removes at most one orbit from the `Nat.card α` orbits of the identity. -/
theorem card_le_orbitCount_add_length [Finite α] {L : List (Perm α)} (hL : ∀ g ∈ L, g.IsSwap) :
    Nat.card α ≤ orbitCount L.prod + L.length := by
  induction L with
  | nil => simp
  | cons t L ih =>
    obtain ⟨u, v, -, rfl⟩ := hL t (by simp)
    have hih := ih fun g hg => hL g (List.mem_cons_of_mem _ hg)
    have hstep := orbitCount_le_orbitCount_swap_mul_add_one L.prod u v
    rw [List.prod_cons, List.length_cons]
    omega

/-- **A factorization into transpositions of exactly the reflection length exists.** Splitting off
the transposition `Equiv.swap x (σ x)` adds one orbit, so after `Nat.card α - orbitCount σ` such
steps the identity is reached. -/
theorem exists_isSwap_list_prod_eq [Finite α] (σ : Perm α) :
    ∃ L : List (Perm α), (∀ g ∈ L, g.IsSwap) ∧ L.prod = σ ∧
      orbitCount σ + L.length = Nat.card α := by
  suffices H : ∀ k (σ : Perm α), Nat.card α - orbitCount σ ≤ k →
      ∃ L : List (Perm α), (∀ g ∈ L, g.IsSwap) ∧ L.prod = σ ∧
        orbitCount σ + L.length = Nat.card α from H _ σ le_rfl
  intro k
  induction k with
  | zero =>
    intro σ hσ
    have h1 : σ = 1 := by
      by_contra h1
      have := orbitCount_lt_card_of_ne_one h1
      omega
    subst h1
    exact ⟨[], by simp, by simp, by simp⟩
  | succ k ih =>
    intro σ hσ
    by_cases h1 : σ = 1
    · subst h1
      exact ⟨[], by simp, by simp, by simp⟩
    obtain ⟨x, hx⟩ : ∃ x, σ x ≠ x := by
      by_contra hcon
      refine h1 (Equiv.ext fun x => ?_)
      simpa using not_not.mp (not_exists.mp hcon x)
    have hsplit : orbitCount (Equiv.swap x (σ x) * σ) = orbitCount σ + 1 :=
      orbitCount_swap_mul_of_sameCycle (Ne.symm hx) ⟨1, by simp⟩
    obtain ⟨L, hL, hprod, hlen⟩ := ih (Equiv.swap x (σ x) * σ) (by omega)
    refine ⟨Equiv.swap x (σ x) :: L, ?_, ?_, ?_⟩
    · intro g hg
      rcases List.mem_cons.mp hg with rfl | hg
      · exact ⟨x, σ x, Ne.symm hx, rfl⟩
      · exact hL g hg
    · rw [List.prod_cons, hprod, Equiv.swap_mul_self_mul]
    · rw [List.length_cons]
      omega

/-- **The reflection length of a permutation of a finite type.** The least number of transpositions
whose product is `σ` is `Nat.card α - orbitCount σ`. -/
theorem isLeast_length_isSwap_list [Finite α] (σ : Perm α) :
    IsLeast {m : ℕ | ∃ L : List (Perm α), (∀ g ∈ L, g.IsSwap) ∧ L.prod = σ ∧ L.length = m}
      (Nat.card α - orbitCount σ) := by
  obtain ⟨L, hL, hprod, hlen⟩ := exists_isSwap_list_prod_eq σ
  refine ⟨⟨L, hL, hprod, by omega⟩, ?_⟩
  rintro m ⟨M, hM, hprod', rfl⟩
  have hbound := card_le_orbitCount_add_length hM
  rw [hprod'] at hbound
  omega

end TauCeti
