/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.AddCommGrp
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.LaurentCover.Restrict
public import TauCeti.CategoryTheory.Sites.SheafCohomology.Cech.AddCommGrp

import TauCeti.CategoryTheory.Sites.IsSheafFor

/-!
# The Čech complex of the Laurent cover of a rational subset

Let `A` be a strongly noetherian Tate ring, `A⁺` a subring of power-bounded elements, `W` a
rational subset of `X = Spa(A, A⁺)` and `f ∈ A`. This file proves that the augmented Čech complex
of the structure presheaf of `X`, as a presheaf of abelian groups, for the Laurent cover
`W ∩ {|f| ≤ 1}`, `W ∩ {|f| ≥ 1}` of `W` is exact in every degree. This is Wedhorn's Lemma 8.33
in all degrees, on an arbitrary rational subset; it is the base case of the induction in his proof
of Lemma 8.34(i), the acyclicity of the Laurent cover generated by finitely many elements.

The covers of `W` are taken in the meet-semilattice `Set.Iic W` of opens contained in `W`, whose
greatest element is `W`, and the structure presheaf is restricted to it
(`presentationLimitAddCommGrpPresheaf`). For a two-member cover, exactness of the augmented Čech
complex in every degree follows from statements in degrees `0` and `1`
(`TauCeti.CategoryTheory.quasiIso_cechAugmentation_fin_two_iff_isSheafFor_and_surjective`), and
those are Lemma 8.33 on a rational subset: `injective_presentationLimitMap_inf_laurentCoverOpen`,
`exists_presentationLimitMap_eq_of_inf_laurentCoverOpen` and
`surjective_presentationLimitMap_sub_inf_laurentCoverOpen`.

## Main results

* `TauCeti.ValuationSpectrum.quasiIso_cechAugmentation_inf_laurentCoverOpen`: over a strongly
  noetherian Tate ring, the augmented Čech complex of the structure presheaf for the Laurent cover
  of a rational subset is exact.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Definition A.1, Lemma 8.33 and
  Lemma 8.34(i).
-/

public section

open CategoryTheory Limits TopologicalSpace Opposite TauCeti.Huber TauCeti.CategoryTheory

universe v

namespace TauCeti.ValuationSpectrum

/-! ### Lemma 8.33 in all degrees on a rational subset -/

section Rational

variable {A : Type v} [CommRing A] [UniformSpace A] [IsTopologicalRing A] [IsTateRing A]
  [IsStronglyNoetherian A] (P : PairOfDefinition A) {Aplus : Subring A}

/-- **Wedhorn's Lemma 8.33 on a rational subset, in every degree.** Let `A` be a strongly noetherian
Tate ring, `A⁺` a subring of power-bounded elements, `W` a rational subset of `Spa(A, A⁺)` and
`f ∈ A`. The augmented Čech complex of the structure presheaf, as a presheaf of abelian groups on
the opens contained in `W`, for the Laurent cover `W ⊓ laurentCoverOpen Aplus f true`,
`W ⊓ laurentCoverOpen Aplus f false` of `W` (that is, `W ∩ {|f| ≤ 1}` and `W ∩ {|f| ≥ 1}`) is
exact: the cover is acyclic for the structure presheaf. `A` itself need not be complete. -/
theorem quasiIso_cechAugmentation_inf_laurentCoverOpen
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {W : Opens ↥(spa Aplus)}
    (hW : W ∈ spaRationalOpens Aplus) (f : A) :
    QuasiIso (cechAugmentation
      ![⟨W ⊓ laurentCoverOpen Aplus f true, Set.mem_Iic.2 inf_le_left⟩,
        ⟨W ⊓ laurentCoverOpen Aplus f false, Set.mem_Iic.2 inf_le_left⟩]
      isTerminalTop (presentationLimitAddCommGrpPresheaf P Aplus W)) := by
  obtain ⟨T, s, hT, rfl⟩ := mem_spaRationalOpens_iff_exists_spaBasicOpen.mp hW
  rw [quasiIso_cechAugmentation_fin_two_iff_isSheafFor_and_surjective,
    Presieve.isSheafFor_arrows_iff]
  -- the sections of `presentationLimitAddCommGrpPresheaf` over `V` are the elements of
  -- `presentationLimit Aplus V` under `e`, which takes its restriction maps to the
  -- `presentationLimitMap`s, so Lemma 8.33 applies to them after transport along `e`
  set e := presentationLimitAddCommGrpPresheafObjEquiv P Aplus (W := spaBasicOpen Aplus T s)
  refine ⟨fun x hx ↦ ?_, fun z ↦ ?_⟩
  · -- a compatible family is one agreeing on the overlap of the two pieces, so it glues
    have h01 := congrArg (e _) <|
      (Presieve.Arrows.compatible_homOfLE_iff (fun _ ↦ le_top) x).1 hx 0 1
    simp only [Functor.comp_map, TypeCat.ofHom_apply,
      presentationLimitAddCommGrpPresheafObjEquiv_map_apply, e] at h01
    obtain ⟨a, ha⟩ := exists_presentationLimitMap_eq_of_inf_laurentCoverOpen P hAplus hT f
      (fun | true => e _ (x 0) | false => e _ (x 1)) h01
    obtain ⟨a, rfl⟩ := (e ⊤).surjective a
    refine ⟨a, fun i ↦ (e _).injective ?_, fun a' ha' ↦ (e ⊤).injective
      (injective_presentationLimitMap_inf_laurentCoverOpen P hAplus hT f (funext fun b ↦ ?_))⟩
    · simp only [Functor.comp_map, TypeCat.ofHom_apply,
        presentationLimitAddCommGrpPresheafObjEquiv_map_apply, e]
      fin_cases i
      exacts [ha true, ha false]
    · have h0 := congrArg (e _) (ha' 0)
      have h1 := congrArg (e _) (ha' 1)
      simp only [Functor.comp_map, TypeCat.ofHom_apply,
        presentationLimitAddCommGrpPresheafObjEquiv_map_apply, e] at h0 h1
      cases b
      exacts [h1.trans (ha false).symm, h0.trans (ha true).symm]
  · obtain ⟨⟨a, b⟩, hab⟩ :=
      surjective_presentationLimitMap_sub_inf_laurentCoverOpen P hAplus hT f (e _ z)
    refine ⟨((e _).symm a, (e _).symm b), (e _).injective ?_⟩
    simp only [map_sub, presentationLimitAddCommGrpPresheafObjEquiv_map_apply, e] at hab ⊢
    rw [← hab]
    exact congrArg₂ (· - ·) (congrArg _ (AddEquiv.apply_symm_apply _ _))
      (congrArg _ (AddEquiv.apply_symm_apply _ _))

end Rational

end TauCeti.ValuationSpectrum
