/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.LaurentCover.Topology
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.LaurentCover.Sheaf
public import TauCeti.Topology.Category.TopCommRingCat.Sheaf

import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.IsSheafFor

/-!
# Continuous gluing for finite Laurent covers

For a strongly noetherian Tate ring, sections on a rational open carry the topology induced
by restriction to the sieve of any finite Laurent cover. Consequently, Laurent gluing is valid
for continuous ring homomorphisms, not just for elements: compatible continuous homomorphisms
into the rings of sections glue to a unique continuous homomorphism.

This is the topological form of finite Laurent gluing needed to pass from Laurent covers to
standard rational covers. Neither completeness nor Hausdorffness of the original ring is
required; the rings of sections are complete and separated by construction.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Lemma 8.34(i) and
  Remark 8.20.
* S. Bosch, U. Güntzer, R. Remmert, *Non-Archimedean Analysis*, §8.2.2, Lemma 2.
-/

public section

open CategoryTheory TopologicalSpace Topology Opposite TauCeti.Huber

universe v

namespace TauCeti.ValuationSpectrum

variable {A : Type v} [CommRing A] [UniformSpace A] [IsTopologicalRing A] [IsTateRing A]
  [IsStronglyNoetherian A] (P : PairOfDefinition A) {Aplus : Subring A}

private theorem isInducing_presheafMap_inf_laurentCoverOpen
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {W : Opens ↥(spa Aplus)}
    (hW : W ∈ spaRationalOpens Aplus) (f : A) :
    IsInducing fun x : (presentationLimitPresheaf P Aplus).obj (op W) ↦
      (((presentationLimitPresheaf P Aplus).map
          (homOfLE (inf_le_left : W ⊓ laurentCoverOpen Aplus f true ≤ W)).op).hom.1 x,
        ((presentationLimitPresheaf P Aplus).map
          (homOfLE (inf_le_left : W ⊓ laurentCoverOpen Aplus f false ≤ W)).op).hom.1 x) := by
  let G := TopCommRingCat.isCompleteSeparated.ι ⋙ forget₂ _root_.TopCommRingCat TopCat
  let e (V : Opens ↥(spa Aplus)) : (presentationLimitPresheaf P Aplus).obj (op V) ≃ₜ
      presentationLimit (P := P) Aplus V := TopCat.homeoOfIso
    (G.mapIso (eqToIso (presentationLimitPresheaf_obj P Aplus (op V))))
  have h := (isClosedEmbedding_presentationLimitMap_inf_laurentCoverOpen P hAplus hW f).toIsInducing
    |>.comp (e W).isInducing
  apply ((e (W ⊓ laurentCoverOpen Aplus f true)).prodCongr
    (e (W ⊓ laurentCoverOpen Aplus f false))).isInducing.of_comp_iff.mp
  convert h using 1
  funext x
  apply Prod.ext
  all_goals
    exact eqToHom_apply_presentationLimitPresheaf_map_apply P _ x

/-- Sections on a rational open have the topology induced by their restrictions to the sieve
of a finite Laurent cover. This is the topological assertion in finite Laurent gluing. -/
theorem isInducing_presentationLimitPresheafMap_laurentSieve
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) (T : Finset A)
    {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus) :
    IsInducing fun (x : (presentationLimitPresheaf P Aplus).obj (op W))
      (g : (V : Opens ↥(spa Aplus)) × { f : V ⟶ W // laurentSieve Aplus T W f }) ↦
        ((presentationLimitPresheaf P Aplus).map g.2.1.op).hom.1 x := by
  classical
  let F := presentationLimitPresheaf P Aplus
  have hc {V : Opens ↥(spa Aplus)} (S : Sieve V) : Continuous
      (fun (x : F.obj (op V)) (g : (U : Opens ↥(spa Aplus)) × { f : U ⟶ V // S f }) ↦
        (F.map g.2.1.op).hom.1 x) :=
    continuous_pi fun g ↦ (F.map g.2.1.op).hom.2
  induction T using Finset.induction_on generalizing W with
  | empty =>
    let g : (V : Opens ↥(spa Aplus)) × { f : V ⟶ W // laurentSieve Aplus ∅ W f } :=
      ⟨W, 𝟙 W, by simp⟩
    apply IsInducing.of_comp (hc _) (continuous_apply g)
    convert (IsInducing.id : IsInducing (id : F.obj (op W) → F.obj (op W))) using 1
    funext x
    exact ConcreteCategory.congr_hom (F.map_id (op W)) x
  | insert a T _ ih =>
    let Y (b : Bool) := W ⊓ laurentCoverOpen Aplus a b
    have hY (b : Bool) : Y b ∈ spaRationalOpens Aplus :=
      inf_mem_spaRationalOpens hW (laurentCoverOpen_mem_spaRationalOpens Aplus a b)
    -- On either half, the remaining Laurent cover is the cover generated by T. Its arrows
    -- compose with Y b → W to give arrows of the full cover generated by insert a T.
    let j (b : Bool)
        (g : (V : Opens ↥(spa Aplus)) × { f : V ⟶ Y b // laurentSieve Aplus T (Y b) f }) :
        (V : Opens ↥(spa Aplus)) × { f : V ⟶ W // laurentSieve Aplus (insert a T) W f } :=
      ⟨g.1, g.2.1 ≫ homOfLE inf_le_left, by
        rw [laurentSieve_apply]
        intro t ht
        rcases Finset.mem_insert.mp ht with rfl | ht
        · exact ⟨b, g.2.1.le.trans inf_le_right⟩
        · exact (laurentSieve_apply g.2.1).mp g.2.2 t ht⟩
    let q (b : Bool) := fun z :
        (g : (V : Opens ↥(spa Aplus)) ×
          { f : V ⟶ W // laurentSieve Aplus (insert a T) W f }) → F.obj (op g.1) ↦
      fun g ↦ z (j b g)
    have hq (b : Bool) : Continuous (q b) := continuous_pi fun g ↦ continuous_apply (j b g)
    have h := ((ih (hY true)).prodMap (ih (hY false))).comp
      (isInducing_presheafMap_inf_laurentCoverOpen P hAplus hW a)
    apply IsInducing.of_comp (hc _) ((hq true).prodMk (hq false))
    convert h using 1
    funext x
    apply Prod.ext <;> funext g
    all_goals
      simp only [Function.comp_apply, Prod.map_apply, q, j, Functor.map_comp,
        op_comp, ObjectProperty.FullSubcategory.comp_hom]
      -- Evaluate composition in TopCommRingCat, whose morphisms are continuous ring homs.
      rfl

/-- The presentation-limit presheaf, viewed as a presheaf of topological commutative rings,
satisfies the sheaf condition for every finite Laurent cover of a rational open. Equivalently,
compatible continuous ring homomorphisms from any topological commutative ring into the
sections on the cover glue uniquely to a continuous ring homomorphism into sections on the
original open. -/
theorem isSheafFor_laurentSieve_topCommRingCat
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) (T : Finset A)
    {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus)
    (E : _root_.TopCommRingCat.{v}) :
    (laurentSieve Aplus T W).arrows.IsSheafFor
      (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
        coyoneda.obj (op E)) := by
  exact TopCommRingCat.isSheafFor_of_isSheafFor_forget
    (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι)
    (laurentSieve Aplus T W) (isSheafFor_laurentSieve P hAplus T hW)
    (isInducing_presentationLimitPresheafMap_laurentSieve P hAplus T hW) E

end TauCeti.ValuationSpectrum
