/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.RationalSubset.Laurent.Sieve
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.LaurentCover.Restrict
public import TauCeti.CategoryTheory.Sites.IsSheafForTrans

import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.IsSheafFor

/-!
# The sheaf condition for Laurent covers

Let `X = Spa(A, A⁺)`, let `W` be an open subset of `X` and let `T ⊆ A` be finite. The Laurent
cover of `W` generated by `T` consists of the pieces

```text
W ∩ {v | v(t) ≤ 1 for t ∈ T \ J, v(t) ≥ 1 for t ∈ J},    J ⊆ T,
```

and the sieve it generates is `laurentSieve Aplus T W`: the opens `V ≤ W` on which every `t ∈ T`
has a fixed sign, that is, `V ≤ {|t| ≤ 1}` or `V ≤ {|t| ≥ 1}`. Phrasing the cover as a sieve
avoids indexing its pieces by sign sets, and restricting it to an open `V ≤ W` gives the Laurent
sieve of `V` (`laurentSieve_pullback`).

When `A` is a strongly noetherian Tate ring, `A⁺` consists of power-bounded elements and `W` is a
rational subset, the presentation-limit presheaf satisfies the sheaf condition for this sieve
(`isSheafFor_laurentSieve`): sections over the pieces of the Laurent cover that agree on overlaps
glue uniquely to a section over `W`. This is the degree-zero part of Wedhorn's Lemma 8.34(i), that
Laurent covers are acyclic.

The sheaf condition passes from the two-piece Laurent covers of rational subsets (Lemma 8.33)
to finite Laurent covers using `TauCeti.TopologicalSpace.Opens.isSheafFor_trans`.

## Main definitions

* `TauCeti.ValuationSpectrum.laurentSieve` : the sieve of the Laurent cover generated by `T`.

## Main results

* `TauCeti.ValuationSpectrum.isSheafFor_laurentSieve` : the presentation-limit presheaf, as a
  presheaf of sets, satisfies the sheaf condition for the Laurent sieve of a rational subset.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Lemma 8.33 and Lemma 8.34(i).
* S. Bosch, U. Güntzer, R. Remmert, *Non-Archimedean Analysis*, §8.2.2, Lemma 2, the
  rigid-analytic original of the induction.
-/

public section

open CategoryTheory TopologicalSpace TauCeti.Huber

universe v

namespace TauCeti.ValuationSpectrum

/-! ### The sheaf condition -/

section Sheaf

variable {A : Type v} [CommRing A] [UniformSpace A] [IsTopologicalRing A] [IsTateRing A]
  [IsStronglyNoetherian A] (P : PairOfDefinition A) {Aplus : Subring A}

-- Wedhorn's Lemma 8.33 on a rational subset, as the sheaf condition for the two-piece Laurent
-- cover `W ∩ {|f| ≤ 1}`, `W ∩ {|f| ≥ 1}`: compatibility on the overlap gives a gluing, which is
-- unique by injectivity of restriction.
private theorem isSheafFor_ofArrows_inf_laurentCoverOpen
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {W : Opens ↥(spa Aplus)}
    (hW : W ∈ spaRationalOpens Aplus) (f : A) :
    (Presieve.ofArrows (fun b ↦ W ⊓ laurentCoverOpen Aplus f b)
      fun _ ↦ homOfLE inf_le_left).IsSheafFor
        (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
          forget _root_.TopCommRingCat) := by
  obtain ⟨T, s, hT, hWT⟩ := mem_spaRationalFamily_iff.mp (mem_spaRationalOpens.mp hW)
  obtain rfl : W = spaBasicOpen Aplus T s :=
    Opens.ext (hWT.trans (Set.ext fun _ ↦ mem_spaBasicOpen.symm))
  -- `τ V` reads a section of the presheaf of sets as an element of `presentationLimit V`
  let τ (V : Opens ↥(spa Aplus)) := (eqToHom (presentationLimitPresheaf_obj P Aplus
    (Opposite.op V))).hom.1
  have hτ (V : Opens ↥(spa Aplus)) : Function.Injective (τ V) :=
    Function.LeftInverse.injective
      (eqToIso (presentationLimitPresheaf_obj P Aplus (Opposite.op V))).hom_inv_id_apply
  rw [Presieve.isSheafFor_arrows_iff]
  intro x hx
  have hover : (presentationLimitMap (P := P) inf_le_left).hom.1 (τ _ (x true)) =
      (presentationLimitMap (P := P) inf_le_right).hom.1 (τ _ (x false)) := by
    rw [← eqToHom_apply_presentationLimitPresheaf_map_apply,
      ← eqToHom_apply_presentationLimitPresheaf_map_apply]
    exact congrArg (τ _)
      (hx true false _ (homOfLE inf_le_left) (homOfLE inf_le_right) (Subsingleton.elim _ _))
  obtain ⟨a, ha⟩ := exists_presentationLimitMap_eq_of_inf_laurentCoverOpen P hAplus hT f
    (fun b ↦ τ _ (x b)) hover
  -- the gluing is `a`, transported back to the presheaf of sets
  let e := presentationLimitPresheaf_obj P Aplus (Opposite.op (spaBasicOpen Aplus T s))
  have hτa : τ _ ((eqToHom e.symm).hom.1 a) = a :=
    (eqToIso e.symm).hom_inv_id_apply a
  refine ⟨(eqToHom e.symm).hom.1 a, fun b ↦ hτ _ ?_, fun a' ha' ↦ hτ _ ?_⟩
  · rw [eqToHom_apply_presentationLimitPresheaf_map_apply, hτa, ha b]
  · refine Eq.trans ?_ hτa.symm
    refine injective_presentationLimitMap_inf_laurentCoverOpen P hAplus hT f (funext fun b ↦ ?_)
    dsimp only
    rw [← eqToHom_apply_presentationLimitPresheaf_map_apply, ha' b, ha b]

/-- **Wedhorn's Lemma 8.34(i) in degree zero: the sheaf condition for Laurent covers.** Let `A` be
a strongly noetherian Tate ring, `A⁺` a subring of power-bounded elements, `W` a rational subset
of `Spa(A, A⁺)` and `T ⊆ A` finite. The presentation-limit presheaf, as a presheaf of sets,
satisfies the sheaf condition for the Laurent cover of `W` generated by `T`: sections over the
opens of `laurentSieve Aplus T W` that are compatible under restriction glue uniquely to a section
over `W`. `A` itself need not be complete. -/
theorem isSheafFor_laurentSieve (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) (T : Finset A)
    {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus) :
    (laurentSieve Aplus T W).arrows.IsSheafFor
      (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
        forget _root_.TopCommRingCat) := by
  -- Wedhorn's induction: the cover generated by `insert a T` refines the two-piece cover
  -- `W ∩ {|a| ≤ 1}`, `W ∩ {|a| ≥ 1}`. On both pieces and their overlap, its restriction is
  -- the cover generated by `T`. All these opens are rational.
  classical
  induction T using Finset.induction_on generalizing W with
  | empty =>
    rw [laurentSieve_empty]
    exact Presieve.isSheafFor_top _
  | insert a T _ ih =>
    -- refine the two-piece Laurent cover of `a`, on whose rational pieces and overlap the
    -- Laurent sieve of `insert a T` is that of `T`
    have hY (b : Bool) : W ⊓ laurentCoverOpen Aplus a b ∈ spaRationalOpens Aplus :=
      inf_mem_spaRationalOpens hW (laurentCoverOpen_mem_spaRationalOpens Aplus a b)
    refine TopologicalSpace.Opens.isSheafFor_trans (fun b ↦ W ⊓ laurentCoverOpen Aplus a b)
      (fun _ ↦ inf_le_left) _ (isSheafFor_ofArrows_inf_laurentCoverOpen P hAplus hW a)
      (fun b ↦ ?_) (fun b b' ↦ ?_) fun V g hg ↦ ?_
    · rw [laurentSieve_pullback, laurentSieve_insert_of_le inf_le_right]
      exact ih (hY b)
    · rw [laurentSieve_pullback, laurentSieve_insert_of_le (inf_le_left.trans inf_le_right)]
      exact (ih (inf_mem_spaRationalOpens (hY b) (hY b'))).isSeparatedFor
    · obtain ⟨b, hb⟩ := (laurentSieve_apply g).mp hg a (Finset.mem_insert_self a T)
      exact ⟨b, le_inf g.le hb⟩

end Sheaf

end TauCeti.ValuationSpectrum
