/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.RationalSubset.Laurent.Sieve
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.LaurentCover.Restrict
public import TauCeti.CategoryTheory.Sites.IsSheafForTrans

import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.IsSheafFor
import TauCeti.RingTheory.Huber.LocalizationTopology.StronglyNoetherian

/-!
# The sheaf condition for Laurent covers

Let `X = Spa(A, A⁺)`, let `W` be an open subset of `X` and let `T ⊆ A` be finite. The Laurent
cover of `W` generated by `T` consists of the pieces

```text
W ∩ {v | v(t) ≤ 1 for t ∈ T \ J, v(t) ≥ 1 for t ∈ J},    J ⊆ T,
```

and the sieve it generates is `laurentSieve Aplus T W`: the opens `V ≤ W` on which every `t ∈ T`
has a fixed sign, that is, `V ≤ {|t| ≤ 1}` or `V ≤ {|t| ≥ 1}`. Phrasing the cover as a sieve
avoids indexing its pieces by sign sets, and restricting it to an open `V ≤ W` gives the Laurent
sieve of `V` (`laurentSieve_pullback`).

A presheaf of sets on `X` that satisfies the sheaf condition for the two-piece Laurent covers
`W ∩ {|f| ≤ 1}`, `W ∩ {|f| ≥ 1}` of every rational subset `W` satisfies it for the Laurent cover
of every rational subset generated by a finite set (`isSheafFor_laurentSieve_of_isSheafFor`).
This is the induction of Wedhorn's Lemma 8.34(i), which uses
`TauCeti.TopologicalSpace.Opens.isSheafFor_trans`.

When `A` is a strongly noetherian Tate ring, `A⁺` consists of power-bounded elements and `W` is a
rational subset, the presentation-limit presheaf satisfies the sheaf condition for the two-piece
cover (`isSheafFor_ofArrows_inf_laurentCoverOpen`, Lemma 8.33), hence for the Laurent sieve
(`isSheafFor_laurentSieve`): sections over the pieces of the Laurent cover that agree on overlaps
glue uniquely to a section over `W`. This is the degree-zero part of Wedhorn's Lemma 8.34(i), that
Laurent covers are acyclic.

The rest of Wedhorn's proof of Lemma 8.34 passes to rational localisations, so it applies to any
class of Tate rings that is stable under rational localisation and satisfies Lemma 8.33 on rational
subsets. `LaurentGluing` packages these two hypotheses on a predicate on Tate rings, and strong
noetherianness satisfies them (`laurentGluing_isStronglyNoetherian`).

## Main definitions

* `TauCeti.ValuationSpectrum.LaurentGluing` : the hypotheses on a predicate on Tate rings under
  which Wedhorn's reduction of Lemma 8.34 to Laurent covers runs.

## Main results

* `TauCeti.ValuationSpectrum.isSheafFor_laurentSieve_of_isSheafFor` : a presheaf of sets
  satisfying the sheaf condition for two-piece Laurent covers of rational subsets satisfies it for
  every Laurent sieve of a rational subset.
* `TauCeti.ValuationSpectrum.isSheafFor_ofArrows_inf_laurentCoverOpen` : over a strongly
  noetherian Tate ring, the presentation-limit presheaf satisfies the sheaf condition for the
  two-piece Laurent cover of a rational subset.
* `TauCeti.ValuationSpectrum.isSheafFor_laurentSieve` : the presentation-limit presheaf, as a
  presheaf of sets, satisfies the sheaf condition for the Laurent sieve of a rational subset.
* `TauCeti.ValuationSpectrum.laurentGluing_isStronglyNoetherian` : strong noetherianness satisfies
  `LaurentGluing`.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Lemma 8.33 and Lemma 8.34(i).
* S. Bosch, U. Güntzer, R. Remmert, *Non-Archimedean Analysis*, §8.2.2, Lemma 2, the
  rigid-analytic original of the induction.
-/

public section

open CategoryTheory TopologicalSpace TauCeti.Huber

universe v w

namespace TauCeti.ValuationSpectrum

/-! ### The induction over the generators -/

section Induction

variable {A : Type v} [CommRing A] [UniformSpace A] [IsTopologicalRing A] [IsHuberRing A]
  {Aplus : Subring A}

/-- **The induction of Wedhorn's Lemma 8.34(i).** Let `F` be a presheaf of sets on `Spa(A, A⁺)`
that satisfies the sheaf condition for the two-piece Laurent cover `W ∩ {|f| ≤ 1}`,
`W ∩ {|f| ≥ 1}` of every rational subset `W` and every `f ∈ A`. Then `F` satisfies the sheaf
condition for the Laurent cover of every rational subset generated by a finite set `T ⊆ A`. -/
theorem isSheafFor_laurentSieve_of_isSheafFor {F : (Opens ↥(spa Aplus))ᵒᵖ ⥤ Type w}
    (hF : ∀ {W : Opens ↥(spa Aplus)}, W ∈ spaRationalOpens Aplus → ∀ f : A,
      (Presieve.ofArrows (fun b ↦ W ⊓ laurentCoverOpen Aplus f b)
        fun _ ↦ homOfLE inf_le_left).IsSheafFor F)
    (T : Finset A) {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus) :
    (laurentSieve Aplus T W).arrows.IsSheafFor F := by
  -- Wedhorn's induction: the cover generated by `insert a T` refines the two-piece cover
  -- `W ∩ {|a| ≤ 1}`, `W ∩ {|a| ≥ 1}`. On both pieces and their overlap, its restriction is
  -- the cover generated by `T`. All these opens are rational.
  classical
  induction T using Finset.induction_on generalizing W with
  | empty =>
    rw [laurentSieve_empty]
    exact Presieve.isSheafFor_top _
  | insert a T _ ih =>
    -- refine the two-piece Laurent cover of `a`, on whose rational pieces and overlap the
    -- Laurent sieve of `insert a T` is that of `T`
    have hY (b : Bool) : W ⊓ laurentCoverOpen Aplus a b ∈ spaRationalOpens Aplus :=
      inf_mem_spaRationalOpens hW (laurentCoverOpen_mem_spaRationalOpens Aplus a b)
    refine TopologicalSpace.Opens.isSheafFor_trans (fun b ↦ W ⊓ laurentCoverOpen Aplus a b)
      (fun _ ↦ inf_le_left) _ (hF hW a) (fun b ↦ ?_) (fun b b' ↦ ?_) fun V g hg ↦ ?_
    · rw [laurentSieve_pullback, laurentSieve_insert_of_le inf_le_right]
      exact ih (hY b)
    · rw [laurentSieve_pullback, laurentSieve_insert_of_le (inf_le_left.trans inf_le_right)]
      exact (ih (inf_mem_spaRationalOpens (hY b) (hY b'))).isSeparatedFor
    · obtain ⟨b, hb⟩ := (laurentSieve_apply g).mp hg a (Finset.mem_insert_self a T)
      exact ⟨b, le_inf g.le hb⟩

end Induction

/-! ### The strongly noetherian case -/

section StronglyNoetherian

variable {A : Type v} [CommRing A] [UniformSpace A] [IsTopologicalRing A] [IsTateRing A]
  [IsStronglyNoetherian A] (P : PairOfDefinition A) {Aplus : Subring A}

/-- **Wedhorn's Lemma 8.33 on a rational subset, as a sheaf condition.** Let `A` be a strongly
noetherian Tate ring, `A⁺` a subring of power-bounded elements, `W` a rational subset of
`Spa(A, A⁺)` and `f ∈ A`. The presentation-limit presheaf, as a presheaf of sets, satisfies the
sheaf condition for the two-piece Laurent cover `W ∩ {|f| ≤ 1}`, `W ∩ {|f| ≥ 1}` of `W`. -/
theorem isSheafFor_ofArrows_inf_laurentCoverOpen
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {W : Opens ↥(spa Aplus)}
    (hW : W ∈ spaRationalOpens Aplus) (f : A) :
    (Presieve.ofArrows (fun b ↦ W ⊓ laurentCoverOpen Aplus f b)
      fun _ ↦ homOfLE inf_le_left).IsSheafFor
        (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
          forget _root_.TopCommRingCat) := by
  obtain ⟨T, s, hT, hWT⟩ := mem_spaRationalFamily_iff.mp (mem_spaRationalOpens.mp hW)
  obtain rfl : W = spaBasicOpen Aplus T s :=
    Opens.ext (hWT.trans (Set.ext fun _ ↦ mem_spaBasicOpen.symm))
  -- `τ V` reads a section of the presheaf of sets as an element of `presentationLimit V`
  let τ (V : Opens ↥(spa Aplus)) := (eqToHom (presentationLimitPresheaf_obj P Aplus
    (Opposite.op V))).hom.1
  have hτ (V : Opens ↥(spa Aplus)) : Function.Injective (τ V) :=
    Function.LeftInverse.injective
      (eqToIso (presentationLimitPresheaf_obj P Aplus (Opposite.op V))).hom_inv_id_apply
  rw [Presieve.isSheafFor_arrows_iff]
  intro x hx
  have hover : (presentationLimitMap (P := P) inf_le_left).hom.1 (τ _ (x true)) =
      (presentationLimitMap (P := P) inf_le_right).hom.1 (τ _ (x false)) := by
    rw [← eqToHom_apply_presentationLimitPresheaf_map_apply,
      ← eqToHom_apply_presentationLimitPresheaf_map_apply]
    exact congrArg (τ _)
      (hx true false _ (homOfLE inf_le_left) (homOfLE inf_le_right) (Subsingleton.elim _ _))
  obtain ⟨a, ha⟩ := exists_presentationLimitMap_eq_of_inf_laurentCoverOpen P hAplus hT f
    (fun b ↦ τ _ (x b)) hover
  -- the gluing is `a`, transported back to the presheaf of sets
  let e := presentationLimitPresheaf_obj P Aplus (Opposite.op (spaBasicOpen Aplus T s))
  have hτa : τ _ ((eqToHom e.symm).hom.1 a) = a :=
    (eqToIso e.symm).hom_inv_id_apply a
  refine ⟨(eqToHom e.symm).hom.1 a, fun b ↦ hτ _ ?_, fun a' ha' ↦ hτ _ ?_⟩
  · rw [eqToHom_apply_presentationLimitPresheaf_map_apply, hτa, ha b]
  · refine Eq.trans ?_ hτa.symm
    refine injective_presentationLimitMap_inf_laurentCoverOpen P hAplus hT f (funext fun b ↦ ?_)
    dsimp only
    rw [← eqToHom_apply_presentationLimitPresheaf_map_apply, ha' b, ha b]

/-- **Wedhorn's Lemma 8.34(i) in degree zero: the sheaf condition for Laurent covers.** Let `A` be
a strongly noetherian Tate ring, `A⁺` a subring of power-bounded elements, `W` a rational subset
of `Spa(A, A⁺)` and `T ⊆ A` finite. The presentation-limit presheaf, as a presheaf of sets,
satisfies the sheaf condition for the Laurent cover of `W` generated by `T`: sections over the
opens of `laurentSieve Aplus T W` that are compatible under restriction glue uniquely to a section
over `W`. `A` itself need not be complete. -/
theorem isSheafFor_laurentSieve (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) (T : Finset A)
    {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus) :
    (laurentSieve Aplus T W).arrows.IsSheafFor
      (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
        forget _root_.TopCommRingCat) :=
  isSheafFor_laurentSieve_of_isSheafFor (isSheafFor_ofArrows_inf_laurentCoverOpen P hAplus) T hW

end StronglyNoetherian

/-! ### Predicates on Tate rings admitting Laurent gluing -/

open TauCeti.Huber.PairOfDefinition in
/-- **The hypotheses of Wedhorn's reduction to Laurent covers**, on a predicate `C` on Tate rings.

* `C` passes from a Tate ring `A` to each completed rational localisation `A⟨T/s⟩` for which `T`
  spans an open ideal, with the topology `locUniformSpace` built from a pair of definition.
* On every Tate ring `A` satisfying `C`, and for every subring `A⁺` of power-bounded elements,
  the presentation-limit presheaf of sets of `Spa(A, A⁺)` satisfies the sheaf condition for the
  two-piece Laurent cover `W ∩ {|f| ≤ 1}`, `W ∩ {|f| ≥ 1}` of every rational subset `W` and every
  `f ∈ A`. This is Wedhorn's Lemma 8.33 on rational subsets, in degree zero.

For such a `C`, Wedhorn's proof of Lemma 8.34 shows that over a Tate ring satisfying `C` every
cover of a rational subset by rational subsets satisfies the sheaf condition
(`isSheafFor_ofArrows_spaRationalOpens_of_iSup_eq_of_laurentGluing`). Strong noetherianness is an
example (`laurentGluing_isStronglyNoetherian`). -/
structure LaurentGluing
    (C : ∀ (A : Type v) [CommRing A] [UniformSpace A] [IsTopologicalRing A] [IsTateRing A],
      Prop) : Prop where
  /-- `C` passes to completed rational localisations. -/
  completion_localization {A : Type v} [CommRing A] [UniformSpace A] [IsTopologicalRing A]
    [IsTateRing A] (P : PairOfDefinition A) (T : Finset A) (s : A)
    (hT : IsOpen (Ideal.span (T : Set A) : Set A)) : C A →
    let hden := hasDenominatorPower_of_isOpen_span P T s (Localization.Away s) hT
    letI := locUniformSpace P T s (Localization.Away s) hden
    letI := isUniformAddGroup_locUniformSpace P T s (Localization.Away s) hden
    letI := isTopologicalRing_locUniformSpace P T s (Localization.Away s) hden
    letI := isTateRing_completion_locTopology_of_isTateRing P T s (Localization.Away s) hden
    C (UniformSpace.Completion (Localization.Away s))
  /-- Over a Tate ring satisfying `C`, two-piece Laurent covers of rational subsets glue. -/
  isSheafFor_ofArrows_inf_laurentCoverOpen {A : Type v} [CommRing A] [UniformSpace A]
    [IsTopologicalRing A] [IsTateRing A] (P : PairOfDefinition A) {Aplus : Subring A} : C A →
    (∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) → ∀ {W : Opens ↥(spa Aplus)},
    W ∈ spaRationalOpens Aplus → ∀ f : A,
    (Presieve.ofArrows (fun b ↦ W ⊓ laurentCoverOpen Aplus f b)
      fun _ ↦ homOfLE inf_le_left).IsSheafFor
        (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
          forget _root_.TopCommRingCat)

open TauCeti.Huber.PairOfDefinition in
/-- **Strong noetherianness admits Laurent gluing.** A completed rational localisation of a
strongly noetherian Tate ring is strongly noetherian
(`TauCeti.Huber.PairOfDefinition.isStronglyNoetherian_completion`), and over a strongly noetherian
Tate ring two-piece Laurent covers of rational subsets glue
(`isSheafFor_ofArrows_inf_laurentCoverOpen`). -/
theorem laurentGluing_isStronglyNoetherian :
    LaurentGluing.{v} fun A _ _ _ _ ↦ IsStronglyNoetherian A where
  completion_localization P T s hT _ :=
    isStronglyNoetherian_completion P T s _ _
      (eq_top_mono (Ideal.span_mono (Set.subset_insert _ _)) (IsTateRing.eq_top_of_isOpen hT))
  isSheafFor_ofArrows_inf_laurentCoverOpen P _ _ hAplus _ hW f :=
    isSheafFor_ofArrows_inf_laurentCoverOpen P hAplus hW f

end TauCeti.ValuationSpectrum
