/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.GaloisCohomology.Inflation
public import TauCeti.RepresentationTheory.Homological.GroupCohomology.FiniteCyclic
public import TauCeti.RingTheory.Norm.Units
public import Mathlib.FieldTheory.Galois.Basic
import Mathlib.RepresentationTheory.Homological.GroupCohomology.Hilbert90

/-!
# The second cohomology of a cyclic Galois extension

Let `L/K` be a finite Galois extension whose Galois group is cyclic, generated by `g`. The
cohomology of a finite cyclic group is two-periodic, and in degree `2` it is the quotient of the
`g`-fixed coefficients by the image of the norm
(`Rep.FiniteCyclicGroup.groupCohomologyπEven`). For the coefficients `Lˣ` the fixed part is `Kˣ`
and the image of the norm is the norm group `N_{L/K}(Lˣ)`, so

`H²(Gal(L/K), Lˣ) ≃ Kˣ / N_{L/K}(Lˣ)`.

This file writes `TauCeti.cyclicClass hg a` for the class of `a ∈ Kˣ` under this identification at
the generator `g`. It is represented by the carry cocycle
`(gⁱ, gʲ) ↦ a` if `i + j ≥ [L : K]` and `1` otherwise, for `0 ≤ i, j < [L : K]`
(`TauCeti.H2π_eq_cyclicClass`), so the identification depends on the choice of generator. This
explicit representative is what connects the norm quotient to crossed products: classically, the
crossed product of the carry cocycle of `a` is the cyclic algebra `(L/K, g, a)`.

Along a tower `K ⊆ L ⊆ M` of cyclic Galois extensions whose generators are compatible, inflation
sends the class of `a` to the class of `a ^ [M : L]` (`TauCeti.map_cyclicClass`).

## Main definitions

* `TauCeti.cyclicClass`: the class in `H²(Gal(L/K), Lˣ)` of an element of `Kˣ`, by
  two-periodicity at a generator of `Gal(L/K)`.
* `TauCeti.cyclicNormQuotientEquiv`: the identification
  `Kˣ / N_{L/K}(Lˣ) ≃ H²(Gal(L/K), Lˣ)` it induces.

## Main results

* `TauCeti.cyclicClass_surjective`: every class in `H²(Gal(L/K), Lˣ)` is the class of an element
  of `Kˣ`.
* `TauCeti.cyclicClass_eq_zero_iff`: the class of `a` vanishes exactly when `a` is a norm from
  `L`.
* `TauCeti.H2π_eq_cyclicClass`: a `2`-cocycle with the values of the carry cocycle of `a`
  represents the class of `a`.
* `TauCeti.map_cyclicClass`: inflation along a tower of cyclic Galois extensions sends the class of
  `a` to the class of `a ^ [M : L]`.

## References

* J.-P. Serre, *Local Fields*, Graduate Texts in Mathematics 67, Springer (1979), Chapter VIII,
  §4, and Chapter XIV, §1.
* P. Gille and T. Szamuely, *Central Simple Algebras and Galois Cohomology* (2006), §4.7.
-/

public section

noncomputable section

open CategoryTheory Rep.FiniteCyclicGroup groupCohomology

namespace TauCeti

variable {K L : Type} [Field K] [Field L] [Algebra K L] [FiniteDimensional K L] [IsGalois K L]
  [IsCyclic (L ≃ₐ[K] L)] {g : L ≃ₐ[K] L} (hg : ∀ σ, σ ∈ Subgroup.zpowers g)

section Periodic

attribute [local instance] IsCyclic.commGroup

variable (g) in
/-- The `g`-fixed part of `Lˣ`, the degree-`2` cycles of the periodic complex at `g`. -/
private abbrev fixedUnits :=
  LinearMap.ker (Rep.applyAsHom (Rep.ofMulDistribMulAction (L ≃ₐ[K] L) Lˣ) g - 𝟙 _).hom.toLinearMap

omit [FiniteDimensional K L] [IsGalois K L] in
private theorem mem_fixedUnits_iff (x : Rep.ofMulDistribMulAction (L ≃ₐ[K] L) Lˣ) :
    x ∈ fixedUnits g ↔ g • (Rep.toAdditive x).toMul = (Rep.toAdditive x).toMul := by
  refine LinearMap.mem_ker.trans ?_
  simp only [Rep.sub_hom, Representation.IntertwiningMap.sub_toLinearMap, LinearMap.sub_apply,
    sub_eq_zero]
  -- The representation acts on `Additive Lˣ` through the Galois action on `Lˣ`
  -- (`Rep.ofMulDistribMulAction_ρ_apply_apply`, which holds by `rfl`).
  rfl

variable (g) in
/-- The inclusion `Kˣ → Lˣ`, landing in the `g`-fixed part. -/
private def unitsToFixedUnits : Additive Kˣ →+ fixedUnits g :=
  AddMonoidHom.codRestrict
    ((Rep.toAdditive.symm.toAddMonoidHom :
        Additive Lˣ →+ Rep.ofMulDistribMulAction (L ≃ₐ[K] L) Lˣ).comp
      (Units.map (algebraMap K L : K →* L)).toAdditive) (fixedUnits g) fun _ ↦
    (mem_fixedUnits_iff _).2 <| Units.ext <| AlgEquiv.commutes _ _

omit [FiniteDimensional K L] [IsGalois K L] in
/-- The value of `unitsToFixedUnits`: the image of `a` in `Lˣ`, written additively. -/
private theorem coe_unitsToFixedUnits (a : Kˣ) :
    (unitsToFixedUnits g (Additive.ofMul a) : Rep.ofMulDistribMulAction (L ≃ₐ[K] L) Lˣ) =
      Rep.toAdditive.symm (Additive.ofMul (Units.map (algebraMap K L : K →* L) a)) :=
  (rfl)

include hg in
/-- A `g`-fixed element of `Lˣ` lies in `Kˣ`, since `g` generates `Gal(L/K)`. -/
private theorem unitsToFixedUnits_surjective : Function.Surjective (unitsToFixedUnits g) := by
  rintro ⟨x, hx⟩
  have hfix : ∀ σ : L ≃ₐ[K] L,
      σ ((Rep.toAdditive x).toMul : L) = (Rep.toAdditive x).toMul := by
    intro σ
    obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.1 (hg σ)
    have h : (g ^ k) • (Rep.toAdditive x).toMul = (Rep.toAdditive x).toMul :=
      (MulAction.stabilizer _ (Rep.toAdditive x).toMul).zpow_mem
        ((mem_fixedUnits_iff x).1 hx) k
    exact congr(((($h : Lˣ)) : L))
  obtain ⟨b, hb⟩ := (IsGalois.mem_range_algebraMap_iff_fixed (F := K) _).2 hfix
  have hb0 : b ≠ 0 := by
    rintro rfl
    exact (Additive.toMul (Rep.toAdditive x)).ne_zero (by simpa using hb.symm)
  refine ⟨Additive.ofMul (Units.mk0 b hb0), Subtype.ext ?_⟩
  apply Rep.toAdditive.injective
  apply Additive.toMul.injective
  apply Units.ext
  exact hb

omit [IsCyclic (L ≃ₐ[K] L)] in
/-- The image of `a ∈ Kˣ` in `Lˣ` is a norm for the action of `Gal(L/K)` exactly when `a` is a
norm from `L`. -/
private theorem mem_range_norm_iff (a : Kˣ) :
    (Rep.toAdditive.symm (Additive.ofMul (Units.map (algebraMap K L : K →* L) a)) :
        Rep.ofMulDistribMulAction (L ≃ₐ[K] L) Lˣ) ∈
        LinearMap.range (Rep.ofMulDistribMulAction (L ≃ₐ[K] L) Lˣ).norm.hom.toLinearMap ↔
      a ∈ normGroup K L := by
  rw [mem_normGroup_iff]
  constructor
  · rintro ⟨y, hy⟩
    refine ⟨(Rep.toAdditive y).toMul, (algebraMap K L).injective ?_⟩
    rw [← norm_ofAlgebraAutOnUnits_eq]
    exact congr(((Additive.toMul (Rep.toAdditive $hy) : Lˣ) : L)).trans (by simp)
  · rintro ⟨y, hy⟩
    refine ⟨Rep.toAdditive.symm (Additive.ofMul y), ?_⟩
    apply Rep.toAdditive.injective
    apply Additive.toMul.injective
    apply Units.ext
    have := norm_ofAlgebraAutOnUnits_eq (K := K) y
    simp only [hy] at this
    exact this

/-- **The class in `H²(Gal(L/K), Lˣ)` of an element of `Kˣ`**, for a cyclic Galois extension with
generator `g`: the image of `a`, which is fixed by `g`, under two-periodicity of the cohomology of
the cyclic group `Gal(L/K)` at `g`. It is represented by the carry cocycle of `a` at `g`. -/
def cyclicClass : Additive Kˣ →+ H2 (Rep.ofMulDistribMulAction (L ≃ₐ[K] L) Lˣ) :=
  (groupCohomologyπEven (Rep.ofMulDistribMulAction (L ≃ₐ[K] L) Lˣ) g hg 2
    even_two).hom.toAddMonoidHom.comp (unitsToFixedUnits g)

/-- Every class in `H²(Gal(L/K), Lˣ)` is the class of an element of `Kˣ`. -/
theorem cyclicClass_surjective : Function.Surjective (cyclicClass hg) := by
  intro y
  obtain ⟨x, rfl⟩ := groupCohomologyπEven_surjective _ _ hg 2 even_two y
  obtain ⟨a, rfl⟩ := unitsToFixedUnits_surjective hg x
  exact ⟨a, rfl⟩

/-- The class of `a ∈ Kˣ` in `H²(Gal(L/K), Lˣ)` vanishes exactly when `a` is a norm from `L`. -/
@[simp]
theorem cyclicClass_eq_zero_iff {a : Kˣ} :
    cyclicClass hg (Additive.ofMul a) = 0 ↔ a ∈ normGroup K L :=
  (groupCohomologyπEven_eq_zero_iff (Rep.ofMulDistribMulAction (L ≃ₐ[K] L) Lˣ) g hg 2 even_two
    (unitsToFixedUnits g (Additive.ofMul a))).trans (mem_range_norm_iff a)

/-! ### Inflation along a tower of cyclic Galois extensions -/

section Inflation

variable {M : Type} [Field M] [Algebra K M] [Algebra L M] [IsScalarTower K L M]
  [FiniteDimensional K M] [IsGalois K M] [IsCyclic (M ≃ₐ[K] M)] {g' : M ≃ₐ[K] M}
  (hg' : ∀ σ, σ ∈ Subgroup.zpowers g')

/-- **Inflation of cyclic classes.** For cyclic Galois extensions `K ⊆ L ⊆ M` whose generators
are compatible, `g'|_L = g`, inflation `H²(Gal(L/K), Lˣ) → H²(Gal(M/K), Mˣ)` sends the class of
`a ∈ Kˣ` to the class of `a ^ [M : L]`. -/
theorem map_cyclicClass (hgg' : AlgEquiv.restrictNormalHom L g' = g) (a : Kˣ) :
    groupCohomology.map (AlgEquiv.restrictNormalHom L) (unitsInflationHom K L M) 2
        (cyclicClass hg (Additive.ofMul a)) =
      cyclicClass hg' (Additive.ofMul (a ^ Module.finrank L M)) := by
  refine map_groupCohomologyπEven_two _ _ hg' _ hg hgg' _ (Module.finrank L M) ?_
    (unitsToFixedUnits g (Additive.ofMul a))
    (unitsToFixedUnits g' (Additive.ofMul (a ^ Module.finrank L M))) ?_
  · rw [IsGalois.card_aut_eq_finrank, IsGalois.card_aut_eq_finrank,
      ← Module.finrank_mul_finrank K L M, mul_comm]
  · -- Both sides are images of `a ^ [M : L]` in `Mˣ`, through `Lˣ` on the right.
    rw [coe_unitsToFixedUnits, coe_unitsToFixedUnits]
    refine Eq.trans ?_ (congrArg (Module.finrank L M • ·) (unitsInflationHom_apply K L M _)).symm
    have hmap : Units.map (algebraMap L M : L →* M) (Units.map (algebraMap K L : K →* L) a) =
        Units.map (algebraMap K M : K →* M) a :=
      Units.ext (IsScalarTower.algebraMap_apply K L M _).symm
    rw [hmap, map_pow, ofMul_pow, map_nsmul]

end Inflation

end Periodic

/-- The classes of `a` and `b` agree exactly when `a / b` is a norm from `L`. -/
theorem cyclicClass_eq_iff {a b : Kˣ} :
    cyclicClass hg (Additive.ofMul a) = cyclicClass hg (Additive.ofMul b) ↔
      a / b ∈ normGroup K L := by
  rw [← sub_eq_zero, ← map_sub, ← ofMul_div, cyclicClass_eq_zero_iff]

omit [IsGalois K L] in
/-- **The class of `a` is the class of its carry cocycle.** A `2`-cocycle `z` of `Gal(L/K)` with
values in `Lˣ` whose values at `(gⁱ, gʲ)`, for `0 ≤ i, j < n` with `n` the order of `g`, are `a` if
`i + j ≥ n` and `1` otherwise represents `cyclicClass hg a`. -/
theorem H2π_eq_cyclicClass (z : cocycles₂ (Rep.ofMulDistribMulAction (L ≃ₐ[K] L) Lˣ)) (a : Kˣ)
    (hz : ∀ i j, i < orderOf g → j < orderOf g →
      Additive.toMul (z (g ^ i, g ^ j)) =
        if orderOf g ≤ i + j then Units.map (algebraMap K L : K →* L) a else 1) :
    H2π _ z = cyclicClass hg (Additive.ofMul a) := by
  classical
  let := IsCyclic.commGroup (α := L ≃ₐ[K] L)
  refine Eq.trans ?_ (groupCohomologyπEven_two_apply _ g hg _).symm
  congr 1
  refine cocycles₂_ext fun x y ↦ ?_
  obtain ⟨i, hi, rfl⟩ := Finset.mem_image.1 (mem_zpowers_iff_mem_range_orderOf.1 (hg x))
  obtain ⟨j, hj, rfl⟩ := Finset.mem_image.1 (mem_zpowers_iff_mem_range_orderOf.1 (hg y))
  rw [Finset.mem_range] at hi hj
  rw [carryCocycle_apply_pow _ g hg _ hi hj]
  apply Additive.toMul.injective
  rw [hz i j hi hj]
  -- Both values are read in `Additive Lˣ`, where `0` is `1` and the fixed element `a` is the
  -- image of `a` under `Rep.toAdditive.symm`, the identity.
  split_ifs <;> rfl

/-- **`H²` of a cyclic Galois extension is the norm quotient**:
`Kˣ / N_{L/K}(Lˣ) ≃ H²(Gal(L/K), Lˣ)`, sending the class of `a` to `cyclicClass hg a`
(`cyclicNormQuotientEquiv_mk`). It depends on the generator `g`. -/
def cyclicNormQuotientEquiv :
    Additive (Kˣ ⧸ normGroup K L) ≃+ H2 (Rep.ofMulDistribMulAction (L ≃ₐ[K] L) Lˣ) :=
  MulEquiv.toAdditiveLeft <|
    (QuotientGroup.quotientMulEquivOfEq (by
      ext a
      rw [MonoidHom.mem_ker, AddMonoidHom.coe_toMultiplicativeRight, Function.comp_apply,
        Function.comp_apply, ofAdd_eq_one, cyclicClass_eq_zero_iff])).trans <|
      QuotientGroup.quotientKerEquivOfSurjective
        (AddMonoidHom.toMultiplicativeRight (cyclicClass hg)) (cyclicClass_surjective hg)

/-- `cyclicNormQuotientEquiv` sends the class of `a ∈ Kˣ` to `cyclicClass hg a`. -/
@[simp]
theorem cyclicNormQuotientEquiv_mk (a : Kˣ) :
    cyclicNormQuotientEquiv hg (Additive.ofMul (a : Kˣ ⧸ normGroup K L)) =
      cyclicClass hg (Additive.ofMul a) :=
  (rfl)


end TauCeti
