/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Probability.Exchangeability.Arrays.Strip.Independence
public import TauCeti.Probability.Kernel.ConditionalRandomization

/-!
# Independent coding of crossing array strips

Split the rows and columns of a separately exchangeable array into visible and hidden parts. The
row strips meeting a set `T` of columns and the column strips meeting a set `S` of rows are
conditionally independent given their intersection `S ×ˢ T`, provided one of `S` and `T` is
infinite. Consequently their joint law can be generated from the intersection block and two
separate independent uniform variables.

This is the functional form of the strip factorization used in the separate Aldous--Hoover
representation. One uniform carries the randomness of all row strips and the other carries the
randomness of all column strips. Subsequent steps resolve these two families into coordinatewise
row and column variables and couple them with the local cell kernels.

## Main result

* `TauCeti.Probability.SeparatelyExchangeable.exists_independent_strip_coding` — crossing row and
  column strips are jointly generated from their intersection by separate uniform noises.

## References

* D. Aldous, "Representations for partially exchangeable arrays of random variables",
  *Journal of Multivariate Analysis* 11 (1981), 581–598.
* O. Kallenberg, *Probabilistic Symmetries and Invariance Principles*, Springer, 2005, Chapter 7.
-/

public section

noncomputable section

open MeasureTheory ProbabilityTheory unitInterval

namespace TauCeti.Probability

variable {α : Type*} [MeasurableSpace α] [StandardBorelSpace α] [Nonempty α]
  {ρ : Measure (ℕ × ℕ → α)} [IsFiniteMeasure ρ]

/-- **Crossing strips are generated by separate independent noises given their intersection.**
The first coding function generates the restriction to all rows and the columns in `T`; the
second generates the restriction to the rows in `S` and all columns. Their only common input is
the intersection block `S ×ˢ T`, while their uniform inputs are independent. -/
theorem SeparatelyExchangeable.exists_independent_strip_coding
    (hρ : SeparatelyExchangeable ρ fun p x ↦ x p) (S : Set ℕ)
    {T : Set ℕ} (hST : S.Infinite ∨ T.Infinite) :
    ∃ f : ((S ×ˢ T) → α) → I → ((Set.univ ×ˢ T) → α),
      ∃ g : ((S ×ˢ T) → α) → I → ((S ×ˢ Set.univ) → α),
        Measurable (Function.uncurry f) ∧ Measurable (Function.uncurry g) ∧
          (ρ.prod ((volume : Measure I).prod (volume : Measure I))).map
              (fun p => ((S ×ˢ T).domRestrict p.1,
                f ((S ×ˢ T).domRestrict p.1) p.2.1,
                g ((S ×ˢ T).domRestrict p.1) p.2.2)) =
            ρ.map fun x => ((S ×ˢ T).domRestrict x,
              (Set.univ ×ˢ T).domRestrict x, (S ×ˢ Set.univ).domRestrict x) := by
  exact ProbabilityTheory.CondIndepFun.exists_independent_coding
    (hZ := Set.measurable_restrict _)
    (hρ.condIndepFun_rowStrip_colStrip S hST)
    (Set.measurable_restrict _) (Set.measurable_restrict _)

end TauCeti.Probability

end

end
