/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Probability.Exchangeability.Arrays.Basic
public import TauCeti.Probability.Kernel.Randomization
import TauCeti.Probability.Exchangeability.Arrays.Strip.Independence
import TauCeti.Probability.Exchangeability.Arrays.Strip.DirectingMeasure
import TauCeti.Probability.DeFinetti.Coding
import TauCeti.Probability.Kernel.ConditionalRandomization

/-!
# Vertex noise for the crossing strips of an exchangeable array

Fix injective enumerations `e` and `f` of hidden rows and hidden columns of a separately
exchangeable array, and injective enumerations `g` and `g'` of visible rows and visible columns,
disjoint from the hidden ones. The *hidden block* is `(x (e a, f b))_{a,b}`; the row strip of the
visible row `g i` is `(x (g i, f b))_b`, and the column strip of the visible column `g' j` is
`(x (e a, g' j))_a`.

Given the hidden block, the row strips are i.i.d., the column strips are i.i.d., and the two
families are conditionally independent. Consequently the hidden block together with all visible
row and column strips is generated from the hidden block by two measurable maps fed with
**one uniform variable per visible row and one per visible column**, all independent:

```text
(H, (x (g i, f ·))ᵢ, (x (e ·, g' j))ⱼ) =ᵈ (H, (r H Uᵢ)ᵢ, (c H Vⱼ)ⱼ).
```

These are the row and column noises of the Aldous–Hoover representation of a separately
exchangeable array. The row strip and column strip of a visible cell, together with the hidden
block, form its `cellContext`, from which the cell itself is generated by a common kernel.

## Main result

* `TauCeti.Probability.SeparatelyExchangeable.exists_vertex_strip_coding` — the visible row and
  column strips are coded from the hidden block by independent i.i.d. uniform row and column noise.

## References

* D. Aldous, "Representations for partially exchangeable arrays of random variables",
  *Journal of Multivariate Analysis* 11 (1981), 581–598.
* O. Kallenberg, *Probabilistic Symmetries and Invariance Principles*, Springer, 2005, Chapter 7.
-/

public section

noncomputable section

open MeasureTheory ProbabilityTheory unitInterval

namespace TauCeti.Probability

variable {α : Type*} [MeasurableSpace α] [StandardBorelSpace α] [Nonempty α]
  {ρ : Measure (ℕ × ℕ → α)} [IsFiniteMeasure ρ]

/-- **The crossing strips are coded by i.i.d. vertex noise given the hidden block.** Let `e`, `f`
enumerate hidden rows and columns and `g`, `g'` visible rows and columns, all injectively, with
visible and hidden indices disjoint on each axis. There are jointly measurable `r` and `c` such
that the hidden block, the visible row strips along `f`, and the visible column strips along `e`
are jointly distributed as the hidden block, `r` applied to one fresh uniform variable per visible
row, and `c` applied to one fresh uniform variable per visible column, all these uniforms being
independent of each other and of the hidden block. -/
theorem SeparatelyExchangeable.exists_vertex_strip_coding
    (hρ : SeparatelyExchangeable ρ fun p x ↦ x p) {e f g g' : ℕ → ℕ}
    (he : Function.Injective e) (hf : Function.Injective f) (hg : Function.Injective g)
    (hg' : Function.Injective g') (heg : Disjoint (Set.range e) (Set.range g))
    (hfg' : Disjoint (Set.range f) (Set.range g')) :
    ∃ r c : (ℕ × ℕ → α) → I → (ℕ → α),
      Measurable (Function.uncurry r) ∧ Measurable (Function.uncurry c) ∧
        ((ρ.map fun x q ↦ x (e q.1, f q.2)).prod
            ((Measure.infinitePi fun _ : ℕ ↦ (volume : Measure I)).prod
              (Measure.infinitePi fun _ : ℕ ↦ (volume : Measure I)))).map
            (fun p ↦ (p.1, fun i ↦ r p.1 (p.2.1 i), fun j ↦ c p.1 (p.2.2 j))) =
          ρ.map fun x ↦ (fun q ↦ x (e q.1, f q.2), fun i b ↦ x (g i, f b),
            fun j a ↦ x (e a, g' j)) := by
  -- Code the row strips and the column strips separately by the sequence coding theorem, using
  -- directing laws `R` and `C` that are measurable functions of the hidden block. The two codings
  -- are then glued by the conditional independence of the strip families given the block.
  have hX (p : ℕ × ℕ) : AEMeasurable (fun x : ℕ × ℕ → α ↦ x p) ρ :=
    (measurable_pi_apply p).aemeasurable
  obtain ⟨R, hR, hRiid⟩ := hρ.exists_rowStrip_directing_of_injective hX he
    fun i j ↦ measurable_pi_apply (e i, f j)
  obtain ⟨C, hC, hCiid⟩ := hρ.exists_colStrip_directing_of_injective hX hf
    fun i j ↦ measurable_pi_apply (e i, f j)
  have hrow := hRiid.map_comp_eq_map_unitIntervalCoding_of_ae_eq hg heg
    (φ := fun z q ↦ z q.1 q.2) (Measurable.of_eval fun q ↦
      (measurable_pi_apply q.2).comp (measurable_pi_apply q.1)) hR (ae_of_all _ fun _ ↦ rfl)
  have hcol := hCiid.map_comp_eq_map_unitIntervalCoding_of_ae_eq hg' hfg'
    (φ := fun z q ↦ z q.2 q.1) (Measurable.of_eval fun q ↦
      (measurable_pi_apply q.1).comp (measurable_pi_apply q.2)) hC (ae_of_all _ fun _ ↦ rfl)
  beta_reduce at hrow hcol
  -- The crossing strips are conditionally independent given the hidden block.
  have hH : Measurable fun (x : ℕ × ℕ → α) (q : ℕ × ℕ) ↦ x (e q.1, f q.2) :=
    Measurable.of_eval fun q ↦ measurable_pi_apply (e q.1, f q.2)
  have hci := hρ.condIndepFun_rowStrip_colStrip_of_enum (f := f)
    (Or.inl (Set.infinite_range_of_injective he)) g g'
  have hr : Measurable (Function.uncurry fun (h : ℕ × ℕ → α) (t : I) ↦
      unitIntervalCoding (ℕ → α) (R h) t) :=
    (measurable_uncurry_unitIntervalCoding (ℕ → α)).comp (hR.prodMap measurable_id)
  have hc : Measurable (Function.uncurry fun (h : ℕ × ℕ → α) (t : I) ↦
      unitIntervalCoding (ℕ → α) (C h) t) :=
    (measurable_uncurry_unitIntervalCoding (ℕ → α)).comp (hC.prodMap measurable_id)
  refine ⟨_, _, hr, hc, ?_⟩
  exact hci.map_prod_prod_eq_of_map_prod_eq hH
    (f := fun h (u : ℕ → I) b ↦ unitIntervalCoding (ℕ → α) (R h) (u b))
    (g := fun h (u : ℕ → I) b ↦ unitIntervalCoding (ℕ → α) (C h) (u b))
    (Measurable.of_eval fun _ ↦ Measurable.of_eval fun _ ↦ measurable_pi_apply _)
    (Measurable.of_eval fun _ ↦ Measurable.of_eval fun _ ↦ measurable_pi_apply _)
    (measurable_pi_uncurry_prod hr) (measurable_pi_uncurry_prod hc) hrow.symm hcol.symm

end TauCeti.Probability

end

end
