/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Probability.Exchangeability.Arrays.Basic
public import TauCeti.Probability.Kernel.Randomization
import TauCeti.Probability.Exchangeability.Arrays.Strip.Independence
import TauCeti.Probability.Exchangeability.Arrays.Strip.DirectingMeasure
import TauCeti.Probability.DeFinetti.Coding
import TauCeti.Probability.Kernel.ConditionalRandomization
import TauCeti.GroupTheory.Perm.Basic

/-!
# Vertex noise for the strips of an exchangeable array

Fix injective enumerations `e` and `f` of hidden rows and hidden columns of a separately
exchangeable array, and injective enumerations `g` and `g'` of visible rows and visible columns,
disjoint from the hidden ones. The *hidden block* is `(x (e a, f b))_{a,b}`; the row strip of the
visible row `g i` is `(x (g i, f b))_b`, and the column strip of the visible column `g' j` is
`(x (e a, g' j))_a`.

Given the hidden block, the row strips are i.i.d., the column strips are i.i.d., and the two
families are conditionally independent. Consequently the hidden block together with all visible
row and column strips is generated from the hidden block by two measurable maps fed with
**one uniform variable per visible row and one per visible column**, all independent:

```text
(H, (x (g i, f ·))ᵢ, (x (e ·, g' j))ⱼ) =ᵈ (H, (r H Uᵢ)ᵢ, (c H Vⱼ)ⱼ).
```

These are the row and column noises of the Aldous–Hoover representation of a separately
exchangeable array. The row strip and column strip of a visible cell, together with the hidden
block, form its `cellContext`, from which the cell itself is generated by a common kernel.

For a jointly exchangeable array the rows and columns share one set of vertices, and the hidden
data is the *hidden square* `(x (e a, e b))_{a,b}`. The data of a vertex `k` consist of both
orientations of its entries against the hidden vertices, `(x (k, e b), x (e b, k))_b`, together
with its diagonal entry `x (k, k)`. Unlike a hidden row of a separately exchangeable array, the
data of a hidden vertex `e a` overlap the hidden square, so they need not have the law of a visible
vertex and cannot serve as an identically distributed observed sample. So a second infinite set of
vertices, enumerated by `d`, is kept as a *reservoir*: its vertex data have the law of the visible
ones and recover their directing law. A relabelling of the reservoir and visible vertices fixing
the hidden ones leaves the hidden square unchanged, so the visible strips and diagonal entries are
coded from the hidden square and the reservoir data `R` by **one uniform variable per visible
vertex**:

```text
((H, R), ((x (g i, e ·), x (e ·, g i)), x (g i, g i))ᵢ)
  =ᵈ ((H, R), (v (H, R) Uᵢ)ᵢ).
```

## Main results

* `TauCeti.Probability.SeparatelyExchangeable.exists_vertex_strip_coding` — the visible row and
  column strips are coded from the hidden block by independent i.i.d. uniform row and column noise.
* `TauCeti.Probability.JointlyExchangeable.exists_vertex_strip_diagonal_coding` — the visible
  vertex strips and diagonal entries of a jointly exchangeable array are coded from the hidden
  square and a reservoir of vertex data by independent i.i.d. uniform vertex noise.

## References

* D. Aldous, "Representations for partially exchangeable arrays of random variables",
  *Journal of Multivariate Analysis* 11 (1981), 581–598.
* O. Kallenberg, *Probabilistic Symmetries and Invariance Principles*, Springer, 2005, Chapter 7.
-/

public section

noncomputable section

open MeasureTheory ProbabilityTheory unitInterval

namespace TauCeti.Probability

variable {α : Type*} [MeasurableSpace α] [StandardBorelSpace α] [Nonempty α]
  {ρ : Measure (ℕ × ℕ → α)} [IsFiniteMeasure ρ]

/-- **The crossing strips are coded by i.i.d. vertex noise given the hidden block.** Let `e`, `f`
enumerate hidden rows and columns and `g`, `g'` visible rows and columns, all injectively, with
visible and hidden indices disjoint on each axis. There are jointly measurable `r` and `c` such
that the hidden block, the visible row strips along `f`, and the visible column strips along `e`
are jointly distributed as the hidden block, `r` applied to one fresh uniform variable per visible
row, and `c` applied to one fresh uniform variable per visible column, all these uniforms being
independent of each other and of the hidden block. -/
theorem SeparatelyExchangeable.exists_vertex_strip_coding
    (hρ : SeparatelyExchangeable ρ fun p x ↦ x p) {e f g g' : ℕ → ℕ}
    (he : Function.Injective e) (hf : Function.Injective f) (hg : Function.Injective g)
    (hg' : Function.Injective g') (heg : Disjoint (Set.range e) (Set.range g))
    (hfg' : Disjoint (Set.range f) (Set.range g')) :
    ∃ r c : (ℕ × ℕ → α) → I → (ℕ → α),
      Measurable (Function.uncurry r) ∧ Measurable (Function.uncurry c) ∧
        ((ρ.map fun x q ↦ x (e q.1, f q.2)).prod
            ((Measure.infinitePi fun _ : ℕ ↦ (volume : Measure I)).prod
              (Measure.infinitePi fun _ : ℕ ↦ (volume : Measure I)))).map
            (fun p ↦ (p.1, fun i ↦ r p.1 (p.2.1 i), fun j ↦ c p.1 (p.2.2 j))) =
          ρ.map fun x ↦ (fun q ↦ x (e q.1, f q.2), fun i b ↦ x (g i, f b),
            fun j a ↦ x (e a, g' j)) := by
  -- Code the row strips and the column strips separately by the sequence coding theorem, using
  -- directing laws `R` and `C` that are measurable functions of the hidden block. The two codings
  -- are then glued by the conditional independence of the strip families given the block.
  have hX (p : ℕ × ℕ) : AEMeasurable (fun x : ℕ × ℕ → α ↦ x p) ρ :=
    (measurable_pi_apply p).aemeasurable
  obtain ⟨R, hR, hRiid⟩ := hρ.exists_rowStrip_directing_of_injective hX he
    fun i j ↦ measurable_pi_apply (e i, f j)
  obtain ⟨C, hC, hCiid⟩ := hρ.exists_colStrip_directing_of_injective hX hf
    fun i j ↦ measurable_pi_apply (e i, f j)
  have hrow := hRiid.map_comp_eq_map_unitIntervalCoding_of_ae_eq hg heg
    (φ := fun z q ↦ z q.1 q.2) (Measurable.of_eval fun q ↦
      (measurable_pi_apply q.2).comp (measurable_pi_apply q.1)) hR (ae_of_all _ fun _ ↦ rfl)
  have hcol := hCiid.map_comp_eq_map_unitIntervalCoding_of_ae_eq hg' hfg'
    (φ := fun z q ↦ z q.2 q.1) (Measurable.of_eval fun q ↦
      (measurable_pi_apply q.1).comp (measurable_pi_apply q.2)) hC (ae_of_all _ fun _ ↦ rfl)
  beta_reduce at hrow hcol
  -- The crossing strips are conditionally independent given the hidden block.
  have hH : Measurable fun (x : ℕ × ℕ → α) (q : ℕ × ℕ) ↦ x (e q.1, f q.2) :=
    Measurable.of_eval fun q ↦ measurable_pi_apply (e q.1, f q.2)
  have hci := hρ.condIndepFun_rowStrip_colStrip_of_enum (f := f)
    (Or.inl (Set.infinite_range_of_injective he)) g g'
  have hr : Measurable (Function.uncurry fun (h : ℕ × ℕ → α) (t : I) ↦
      unitIntervalCoding (ℕ → α) (R h) t) :=
    (measurable_uncurry_unitIntervalCoding (ℕ → α)).comp (hR.prodMap measurable_id)
  have hc : Measurable (Function.uncurry fun (h : ℕ × ℕ → α) (t : I) ↦
      unitIntervalCoding (ℕ → α) (C h) t) :=
    (measurable_uncurry_unitIntervalCoding (ℕ → α)).comp (hC.prodMap measurable_id)
  refine ⟨_, _, hr, hc, ?_⟩
  exact hci.map_prod_prod_eq_of_map_prod_eq hH
    (f := fun h (u : ℕ → I) b ↦ unitIntervalCoding (ℕ → α) (R h) (u b))
    (g := fun h (u : ℕ → I) b ↦ unitIntervalCoding (ℕ → α) (C h) (u b))
    (Measurable.of_eval fun _ ↦ Measurable.of_eval fun _ ↦ measurable_pi_apply _)
    (Measurable.of_eval fun _ ↦ Measurable.of_eval fun _ ↦ measurable_pi_apply _)
    (measurable_pi_uncurry_prod hr) (measurable_pi_uncurry_prod hc) hrow.symm hcol.symm

/-- **The vertex strips and diagonal are coded by i.i.d. vertex noise.** Let `e` enumerate hidden
vertices, `d` a reservoir of further vertices and `g` visible vertices, all injectively and with
pairwise disjoint ranges. The data of a vertex `k` consist of the two-oriented strip
`(x (k, e b), x (e b, k))_b` and the diagonal entry `x (k, k)`. There is a jointly measurable `v`
such that the hidden square, the reservoir vertex data and the visible vertex data are jointly
distributed as the hidden square, the reservoir data, and `v` applied to them and to one fresh
uniform variable per visible vertex. The uniforms are independent of each other and of the hidden
data. Producing the diagonal from the same noise as its vertex strip supplies the contexts required
by the off-diagonal-pair coding. -/
theorem JointlyExchangeable.exists_vertex_strip_diagonal_coding
    (hρ : JointlyExchangeable ρ fun p x ↦ x p) {e d g : ℕ → ℕ}
    (he : Function.Injective e) (hd : Function.Injective d) (hg : Function.Injective g)
    (hed : Disjoint (Set.range e) (Set.range d)) (heg : Disjoint (Set.range e) (Set.range g))
    (hdg : Disjoint (Set.range d) (Set.range g)) :
    ∃ v : (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α) → I → ((ℕ → α × α) × α),
      Measurable (Function.uncurry v) ∧
        ρ.map (fun x ↦
            ((fun q ↦ x (e q.1, e q.2),
                fun k ↦ (fun b ↦ (x (d k, e b), x (e b, d k)), x (d k, d k))),
              fun i ↦ (fun b ↦ (x (g i, e b), x (e b, g i)), x (g i, g i)))) =
          ((ρ.map fun x ↦ (fun q ↦ x (e q.1, e q.2),
              fun k ↦ (fun b ↦ (x (d k, e b), x (e b, d k)), x (d k, d k)))).prod
              (Measure.infinitePi fun _ : ℕ ↦ (volume : Measure I))).map
            (fun p ↦ (p.1, fun i ↦ v p.1 (p.2 i))) := by
  -- Interleave the reservoir and the visible vertices into one injective enumeration `w`.
  set w : ℕ → ℕ := Sum.elim d g ∘ Equiv.natSumNatEquivNat.symm with hw_def
  have hw : Function.Injective w :=
    (hd.sumElim hg fun a b hab ↦ Set.disjoint_left.mp hdg ⟨a, rfl⟩ ⟨b, hab.symm⟩).comp
      Equiv.natSumNatEquivNat.symm.injective
  have hew : Disjoint (Set.range e) (Set.range w) := by
    rw [Set.disjoint_right]
    rintro _ ⟨k, rfl⟩
    rcases h : Equiv.natSumNatEquivNat.symm k with a | a
    · simpa [hw_def, h] using Set.disjoint_right.mp hed ⟨a, rfl⟩
    · simpa [hw_def, h] using Set.disjoint_right.mp heg ⟨a, rfl⟩
  have hwd (a : ℕ) : w (Equiv.natSumNatEquivNat (Sum.inl a)) = d a := by simp [hw_def]
  have hwg (a : ℕ) : w (Equiv.natSumNatEquivNat (Sum.inr a)) = g a := by simp [hw_def]
  -- The hidden square paired with the vertex data of `w k` is exchangeable in `k`: a permutation
  -- of the vertices `w k` extends to a permutation of `ℕ` fixing every hidden vertex.
  have hvertex (k : ℕ) : Measurable fun (x : ℕ × ℕ → α) ↦
      (fun b ↦ (x (k, e b), x (e b, k)), x (k, k)) :=
    (Measurable.of_eval fun b ↦ (measurable_pi_apply _).prodMk (measurable_pi_apply _)).prodMk
      (measurable_pi_apply _)
  have hsquare : Measurable fun (x : ℕ × ℕ → α) (q : ℕ × ℕ) ↦ x (e q.1, e q.2) :=
    Measurable.of_eval fun q ↦ measurable_pi_apply _
  have hexch : Exchangeable ρ fun k (x : ℕ × ℕ → α) ↦
      (fun q : ℕ × ℕ ↦ x (e q.1, e q.2),
        (fun b ↦ (x (w k, e b), x (e b, w k)), x (w k, w k))) := by
    refine FullyExchangeable.exchangeable (fun π ↦ ?_)
      fun k ↦ (hsquare.prodMk (hvertex (w k))).aemeasurable
    obtain ⟨τ, hτe, hτw⟩ := exists_perm_apply_eq_of_disjoint_range he hw hew 1 π
    have key := hρ.map_comp (fun p ↦ (measurable_pi_apply p).aemeasurable) τ
      (Measurable.of_eval fun k ↦ hsquare.prodMk (hvertex (w k)))
    simp only [hτe, hτw, Equiv.Perm.coe_one, id] at key
    rwa [pathLaw_def]
  obtain ⟨v, hv, hcode⟩ := hexch.exists_map_comp_eq_map_coding_of_prodMk
    hsquare.aemeasurable (fun k ↦ (hvertex (w k)).aemeasurable)
    (Equiv.natSumNatEquivNat.injective.comp Sum.inl_injective)
    (Equiv.natSumNatEquivNat.injective.comp Sum.inr_injective)
    (Set.disjoint_left.mpr fun _ ⟨a, ha⟩ ⟨b, hb⟩ ↦
      Sum.inl_ne_inr (Equiv.natSumNatEquivNat.injective (ha.trans hb.symm)))
  simp only [Function.comp_apply, hwd, hwg] at hcode
  exact ⟨v, hv, hcode⟩

end TauCeti.Probability

end

end
