/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.GaloisGroups.Stabilizer
public import TauCeti.GroupTheory.Perm.Blocks
public import Mathlib.FieldTheory.Galois.IsGaloisGroup

/-!
# Blocks of a polynomial Galois action

For an irreducible separable polynomial, the blocks of the Galois action that contain a chosen
root correspond contravariantly to the intermediate fields of the simple extension generated by
that root. A block is sent to the field fixed by its setwise stabilizer; in the other direction,
an intermediate field is sent to the orbit of the root under its fixing subgroup. Equivalently,
that orbit consists of the roots of the root's minimal polynomial over the intermediate field.

The correspondence identifies primitivity of the root action with the absence of proper
intermediate fields in the simple extension.

## Main results

* `TauCeti.rootBlockIntermediateFieldOrderIso`: blocks containing a root are order anti-isomorphic
  to intermediate fields contained in the field generated by that root.
* `TauCeti.coe_rootBlockIntermediateFieldOrderIso_symm_apply_eq_preimage_rootSet_minpoly`: the
  block attached to an intermediate field is the set of roots of the corresponding minimal
  polynomial.
* `TauCeti.isPreprimitive_iff_adjoin_simple_isAtom`: the root action is primitive exactly when
  the generated simple extension is an atom in the lattice of intermediate fields.
* `TauCeti.isPreprimitive_of_irreducible_of_prime_natDegree`: an irreducible separable polynomial
  of prime degree has a primitive root action.

## References

* H. Wielandt, *Finite Permutation Groups*, Theorem 7.5
* J. D. Dixon and B. Mortimer, *Permutation Groups*, Section 1.5
-/

public section

namespace TauCeti

open scoped Pointwise

open IntermediateField MulAction Polynomial

universe u

variable {F : Type u} [Field F] {p : F[X]}

private theorem gal_smul_eq_apply (σ : p.Gal) (y : p.SplittingField) : σ • y = σ y :=
  (rfl)

private theorem galSMulCommClass : SMulCommClass p.Gal F p.SplittingField :=
  ⟨fun σ a y ↦ by
    rw [gal_smul_eq_apply, gal_smul_eq_apply, Algebra.smul_def, Algebra.smul_def, map_mul]
    exact congrArg (· * σ y) (σ.commutes a)⟩

private theorem galIsGaloisGroup [IsGalois F p.SplittingField]
    [SMulCommClass p.Gal F p.SplittingField] :
    IsGaloisGroup p.Gal F p.SplittingField :=
  { faithful := ⟨fun {σ τ} h ↦ @Gal.ext F _ p σ τ fun y _ ↦ h y⟩
    commutes := inferInstance
    isInvariant := ⟨fun y hy ↦
      (IsGalois.mem_range_algebraMap_iff_fixed y).2 fun σ ↦ hy σ⟩ }

private theorem fixingSubgroup_adjoin_simple_eq_stabilizer
    (x : p.rootSet p.SplittingField) :
    fixingSubgroup p.Gal (F⟮(x : p.SplittingField)⟯ : Set p.SplittingField) =
      stabilizer p.Gal x := by
  let _ : SMulCommClass p.Gal F p.SplittingField := galSMulCommClass
  ext σ
  rw [_root_.mem_fixingSubgroup_iff, mem_stabilizer_iff, Subtype.ext_iff, Gal.coe_smul]
  simpa [gal_smul_eq_apply] using
    forall_mem_adjoin_smul_eq_self_iff F (S := {(x : p.SplittingField)}) σ

/-- **Blocks containing a root correspond to intermediate fields of its simple extension.**

The correspondence sends a block `B` to the field fixed by its setwise stabilizer. Its inverse
sends an intermediate field `E ⊆ F⟨x⟩` to the orbit of `x` under `Gal(L/E)`, where
`L = p.SplittingField`. The codomain is order-dual because larger blocks have larger stabilizers
and hence smaller fixed fields. -/
noncomputable def rootBlockIntermediateFieldOrderIso
    (hp : Irreducible p) (hsep : p.Separable)
    (x : p.rootSet p.SplittingField) :
    BlockMem p.Gal x ≃o (Set.Iic F⟮(x : p.SplittingField)⟯)ᵒᵈ := by
  letI : IsGalois F p.SplittingField := IsGalois.of_separable_splitting_field hsep
  letI : IsPretransitive p.Gal (p.rootSet p.SplittingField) :=
    isPretransitive_of_irreducible hp
  letI : SMulCommClass p.Gal F p.SplittingField := galSMulCommClass
  letI : IsGaloisGroup p.Gal F p.SplittingField := galIsGaloisGroup
  refine
    { toFun := fun B ↦ OrderDual.toDual
        ⟨FixedPoints.intermediateField (stabilizer p.Gal
          (B : Set (p.rootSet p.SplittingField))), ?_⟩
      invFun := fun E ↦
        ⟨orbit (fixingSubgroup p.Gal (E.ofDual.1 : Set p.SplittingField)) x,
          mem_orbit_self x,
          @IsBlock.of_orbit p.Gal _ (p.rootSet p.SplittingField) (Gal.galActionAux p)
            (fixingSubgroup p.Gal (E.ofDual.1 : Set p.SplittingField)) x ?_⟩
      left_inv := fun B ↦ ?_
      right_inv := fun E ↦ ?_
      map_rel_iff' := fun {B C} ↦ ?_ }
  · -- Expose the field containment required by the codomain interval.
    change FixedPoints.intermediateField
        (stabilizer p.Gal (B : Set (p.rootSet p.SplittingField))) ≤ F⟮(x : p.SplittingField)⟯
    exact (IsGaloisGroup.fixedPoints_le_of_le p.Gal F p.SplittingField _ _
      (B.property.2.stabilizer_le B.property.1)).trans <| by
      rw [← fixingSubgroup_adjoin_simple_eq_stabilizer x,
        IsGaloisGroup.fixedPoints_fixingSubgroup p.Gal F p.SplittingField]
  · rw [← fixingSubgroup_adjoin_simple_eq_stabilizer x]
    exact IsGaloisGroup.fixingSubgroup_le_of_le p.Gal F p.SplittingField _ _ E.ofDual.2
  · apply Subtype.ext
    -- Expose both structure maps so the Galois fixed-point identity can rewrite the goal.
    change orbit (fixingSubgroup p.Gal
      ((FixedPoints.intermediateField
        (stabilizer p.Gal (B : Set (p.rootSet p.SplittingField))) :
          IntermediateField F p.SplittingField) : Set p.SplittingField)) x = B
    rw [IsGaloisGroup.fixingSubgroup_fixedPoints p.Gal F p.SplittingField,
      B.property.2.orbit_stabilizer_eq B.property.1]
  · apply Subtype.ext
    -- Expose both structure maps so the orbit-stabilizer identity can rewrite the goal.
    change FixedPoints.intermediateField
      (stabilizer p.Gal (orbit (fixingSubgroup p.Gal
        (E.ofDual.1 : Set p.SplittingField)) x)) = E.ofDual.1
    rw [stabilizer_orbit_eq,
      IsGaloisGroup.fixedPoints_fixingSubgroup p.Gal F p.SplittingField]
    rw [← fixingSubgroup_adjoin_simple_eq_stabilizer x]
    exact IsGaloisGroup.fixingSubgroup_le_of_le p.Gal F p.SplittingField _ _ E.ofDual.2
  · constructor
    · intro h
      -- Expose the fixed fields represented by the two order-dual subtype values.
      change (FixedPoints.intermediateField
        (stabilizer p.Gal (C : Set (p.rootSet p.SplittingField))) :
          IntermediateField F p.SplittingField) ≤
        FixedPoints.intermediateField
          (stabilizer p.Gal (B : Set (p.rootSet p.SplittingField))) at h
      have := IsGaloisGroup.fixingSubgroup_le_of_le p.Gal F p.SplittingField _ _ h
      have hstab : stabilizer p.Gal (B : Set (p.rootSet p.SplittingField)) ≤
          stabilizer p.Gal (C : Set (p.rootSet p.SplittingField)) := by
        simpa only [IsGaloisGroup.fixingSubgroup_fixedPoints
          p.Gal F p.SplittingField] using this
      intro y hy
      rw [← B.property.2.orbit_stabilizer_eq B.property.1] at hy
      rw [← C.property.2.orbit_stabilizer_eq C.property.1]
      obtain ⟨g, rfl⟩ := hy
      exact ⟨⟨g, hstab g.2⟩, rfl⟩
    · intro h
      -- Expose the fixed fields represented by the two order-dual subtype values.
      change (FixedPoints.intermediateField
        (stabilizer p.Gal (C : Set (p.rootSet p.SplittingField))) :
          IntermediateField F p.SplittingField) ≤
        FixedPoints.intermediateField
          (stabilizer p.Gal (B : Set (p.rootSet p.SplittingField)))
      apply IsGaloisGroup.fixedPoints_le_of_le p.Gal F p.SplittingField
      intro g hg
      apply C.property.2.smul_eq_of_mem C.property.1
      exact h (hg.symm ▸ Set.smul_mem_smul_set B.property.1)

/-- A block is sent to the field fixed by its setwise stabilizer: an element belongs to the
corresponding intermediate field exactly when every element of the stabilizer fixes it. -/
@[simp]
theorem mem_rootBlockIntermediateFieldOrderIso_apply_iff
    (hp : Irreducible p) (hsep : p.Separable)
    (x : p.rootSet p.SplittingField) (B : BlockMem p.Gal x) (y : p.SplittingField) :
    y ∈ ((rootBlockIntermediateFieldOrderIso hp hsep x B).ofDual :
      IntermediateField F p.SplittingField) ↔
      ∀ g ∈ stabilizer p.Gal (B : Set (p.rootSet p.SplittingField)), g • y = y :=
  by
    let _ : SMulCommClass p.Gal F p.SplittingField := galSMulCommClass
    -- Expose the fixed-field definition in the left side of the equivalence.
    change y ∈ (FixedPoints.intermediateField
      (stabilizer p.Gal (B : Set (p.rootSet p.SplittingField))) :
        IntermediateField F p.SplittingField) ↔ _
    rw [FixedPoints.mem_intermediateField_iff]
    exact ⟨fun h g hg ↦ h ⟨g, hg⟩, fun h g ↦ h g g.2⟩

/-- The singleton block corresponds to the whole simple extension, confirming the orientation of
`rootBlockIntermediateFieldOrderIso`. -/
@[simp]
theorem rootBlockIntermediateFieldOrderIso_apply_bot
    (hp : Irreducible p) (hsep : p.Separable)
    (x : p.rootSet p.SplittingField) :
    ((rootBlockIntermediateFieldOrderIso hp hsep x
      (⊥ : BlockMem p.Gal x)).ofDual.1 : IntermediateField F p.SplittingField) =
      F⟮(x : p.SplittingField)⟯ := by
  exact congrArg (fun E ↦ (E.ofDual.1 : IntermediateField F p.SplittingField))
    (rootBlockIntermediateFieldOrderIso hp hsep x).map_bot

/-- The block of all roots corresponds to the base field, confirming the orientation of
`rootBlockIntermediateFieldOrderIso`. -/
@[simp]
theorem rootBlockIntermediateFieldOrderIso_apply_top
    (hp : Irreducible p) (hsep : p.Separable)
    (x : p.rootSet p.SplittingField) :
    ((rootBlockIntermediateFieldOrderIso hp hsep x
      (⊤ : BlockMem p.Gal x)).ofDual.1 : IntermediateField F p.SplittingField) = ⊥ := by
  exact congrArg (fun E ↦ (E.ofDual.1 : IntermediateField F p.SplittingField))
    (rootBlockIntermediateFieldOrderIso hp hsep x).map_top

/-- The underlying set of the block attached to an intermediate field is the orbit of the chosen
root under the field's fixing subgroup. -/
@[simp]
theorem coe_rootBlockIntermediateFieldOrderIso_symm_apply
    (hp : Irreducible p) (hsep : p.Separable)
    (x : p.rootSet p.SplittingField) (E : Set.Iic F⟮(x : p.SplittingField)⟯) :
    (((rootBlockIntermediateFieldOrderIso hp hsep x).symm (OrderDual.toDual E) :
      BlockMem p.Gal x) : Set (p.rootSet p.SplittingField)) =
      orbit (fixingSubgroup p.Gal (E.1 : Set p.SplittingField)) x :=
  (rfl)

/-- The block attached to an intermediate field is the fibre, among the roots of `p`, of the
minimal polynomial of the chosen root over that field. -/
theorem coe_rootBlockIntermediateFieldOrderIso_symm_apply_eq_preimage_rootSet_minpoly
    (hp : Irreducible p) (hsep : p.Separable)
    (x : p.rootSet p.SplittingField) (E : Set.Iic F⟮(x : p.SplittingField)⟯) :
    (((rootBlockIntermediateFieldOrderIso hp hsep x).symm (OrderDual.toDual E) :
      BlockMem p.Gal x) : Set (p.rootSet p.SplittingField)) =
      Subtype.val ⁻¹' (minpoly E.1 (x : p.SplittingField)).rootSet p.SplittingField := by
  let _ : IsGalois F p.SplittingField := IsGalois.of_separable_splitting_field hsep
  let _ : SMulCommClass p.Gal F p.SplittingField := galSMulCommClass
  let _ : IsGaloisGroup p.Gal F p.SplittingField := galIsGaloisGroup
  let H := fixingSubgroup p.Gal (E.1 : Set p.SplittingField)
  have horbit (y : p.rootSet p.SplittingField) :
      y ∈ orbit H x ↔
        (y : p.SplittingField) ∈ orbit Gal(p.SplittingField/E.1) (x : p.SplittingField) := by
    constructor
    · rintro ⟨g, rfl⟩
      refine ⟨IsGaloisGroup.mulEquivCongr H Gal(p.SplittingField/E.1) E.1
        p.SplittingField g, ?_⟩
      simpa only [Subgroup.smul_def, Gal.coe_smul, gal_smul_eq_apply] using
        IsGaloisGroup.mulEquivCongr_apply_smul H Gal(p.SplittingField/E.1) E.1
          p.SplittingField g (x : p.SplittingField)
    · rintro ⟨σ, hσ⟩
      obtain ⟨g, rfl⟩ :=
        (IsGaloisGroup.mulEquivCongr H Gal(p.SplittingField/E.1) E.1
          p.SplittingField).surjective σ
      refine ⟨g, Subtype.ext ?_⟩
      rw [← hσ]
      simpa only [Subgroup.smul_def, Gal.coe_smul, gal_smul_eq_apply] using
        (IsGaloisGroup.mulEquivCongr_apply_smul H Gal(p.SplittingField/E.1) E.1
          p.SplittingField g (x : p.SplittingField)).symm
  rw [coe_rootBlockIntermediateFieldOrderIso_symm_apply]
  ext y
  rw [Set.mem_preimage, horbit, ← Normal.minpoly_eq_iff_mem_orbit p.SplittingField]
  have hint : IsIntegral E.1 (x : p.SplittingField) := IsIntegral.of_finite E.1 _
  rw [mem_rootSet]
  refine ⟨fun h ↦ ⟨minpoly.ne_zero hint, h ▸ minpoly.aeval E.1 (y : p.SplittingField)⟩,
    fun h ↦ ?_⟩
  exact (minpoly.eq_of_irreducible_of_monic (minpoly.irreducible hint) h.2
    (minpoly.monic hint)).symm

/-- **The Galois action on the roots is primitive exactly when the simple extension generated by
a root has no proper intermediate fields.** The degree assumption excludes the one-point action,
for which Mathlib's definition of primitivity is deliberately nontrivial. -/
theorem isPreprimitive_iff_adjoin_simple_isAtom
    (hp : Irreducible p) (hsep : p.Separable) (hdeg : 1 < p.natDegree)
    (x : p.rootSet p.SplittingField) :
    IsPreprimitive p.Gal (p.rootSet p.SplittingField) ↔
      IsAtom F⟮(x : p.SplittingField)⟯ := by
  let _ : IsPretransitive p.Gal (p.rootSet p.SplittingField) :=
    isPretransitive_of_irreducible hp
  have hcard : Fintype.card (p.rootSet p.SplittingField) = p.natDegree :=
    card_rootSet_eq_natDegree hsep (SplittingField.splits p)
  let _ : Nontrivial (p.rootSet p.SplittingField) :=
    Fintype.one_lt_card_iff_nontrivial.mp (by simpa only [hcard] using hdeg)
  rw [← isSimpleOrder_blockMem_iff_isPreprimitive p.Gal x,
    (rootBlockIntermediateFieldOrderIso hp hsep x).isSimpleOrder_iff,
    ← isSimpleOrder_iff_isSimpleOrder_orderDual, Set.isSimpleOrder_Iic_iff_isAtom]

/-- An irreducible separable polynomial of prime degree has a primitive Galois action on its
roots. -/
theorem isPreprimitive_of_irreducible_of_prime_natDegree
    (hp : Irreducible p) (hsep : p.Separable) (hprime : p.natDegree.Prime) :
    IsPreprimitive p.Gal (p.rootSet p.SplittingField) := by
  let _ : IsPretransitive p.Gal (p.rootSet p.SplittingField) :=
    isPretransitive_of_irreducible hp
  apply IsPreprimitive.of_prime_card
  rw [Nat.card_eq_fintype_card,
    card_rootSet_eq_natDegree hsep (SplittingField.splits p)]
  exact hprime

end TauCeti
