/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Polynomial.Tschirnhaus
public import Mathlib.FieldTheory.PolynomialGaloisGroup

/-!
# Tschirnhaus transforms and the Galois group

A Tschirnhaus transform `Polynomial.tschirnhausPolynomial f T` replaces the roots `α` of `f` by
the values `T(α)`. The coefficient-side construction and the root correspondence are developed in
`TauCeti/RingTheory/Polynomial/Tschirnhaus.lean`. This file shows that for a monic separable `f`
an *admissible* transform — one that separates the roots of `f` — changes neither the splitting
field nor the Galois group.

Separability of `f` is assumed by the two splitting-field results. The Galois correspondence
enters in one place only, the splitting-field argument
`Polynomial.TschirnhausAdmissible.isSplittingField`, which computes the fixing subgroup of the
field generated by the values `T(α)`. The conjugacy of the Galois images needs monicity and
admissibility only.

For a monic `f` and any domain extension `E` in which `f` splits, the roots of the transform are
exactly the values of `T` at the roots of `f`, with multiplicity, so the transform splits in `E`
as well.
Admissibility is `Polynomial.TschirnhausAdmissible f T`: injectivity of `α ↦ T(α)` on the root set
of `f` in its splitting field. Under it, a monic separable `f` has a separable transform and its
splitting field *is* a splitting field of the transform; and for a monic `f`, separable or not, the
Galois groups are isomorphic and their images inside the permutations of their respective root
sets are conjugate along `α ↦ T(α)`.

That last statement is what carries information back: a constraint on the Galois image of the
transform — typically an upper bound read off a resolvent that became separable after the
substitution — is a constraint on the Galois image of `f`.

## Main results

* `Polynomial.TschirnhausAdmissible.isSplittingField` and
  `Polynomial.TschirnhausAdmissible.nonempty_algEquiv_splittingField`: the splitting fields agree.
* `Polynomial.TschirnhausAdmissible.nonempty_galMulEquiv`: the Galois groups are isomorphic.
* `Polynomial.TschirnhausAdmissible.exists_equiv_range_galActionHom_eq`: the two Galois images are
  conjugate along the bijection `α ↦ T(α)` of root sets.

## References

* H. Cohen, *A Course in Computational Algebraic Number Theory*, §6.3.
-/

public section

noncomputable section

open Polynomial

namespace Polynomial

variable {F : Type*} [Field F] {f T : F[X]}

/-- **The splitting field of `f` is a splitting field of an admissible transform.** For a monic
separable `f` and an admissible `T`, the transform splits in `f.SplittingField` and its roots
generate that field over `F`. -/
theorem TschirnhausAdmissible.isSplittingField (h : TschirnhausAdmissible f T) (hf : f.Monic)
    (hsep : f.Separable) :
    IsSplittingField F f.SplittingField (f.tschirnhausPolynomial T) := by
  have hsp : (f.map (algebraMap F f.SplittingField)).Splits := SplittingField.splits f
  have : IsGalois F f.SplittingField := IsGalois.of_separable_splitting_field hsep
  have hTsp : ((f.tschirnhausPolynomial T).map
      (algebraMap F f.SplittingField)).Splits := by
    rw [map_tschirnhausPolynomial hf]
    exact splits_tschirnhausPolynomial (hf.map _) hsp _
  refine ⟨hTsp, ?_⟩
  rw [← IntermediateField.adjoin_eq_top_iff]
  set M := IntermediateField.adjoin F ((f.tschirnhausPolynomial T).rootSet f.SplittingField) with hM
  have hfix : M.fixingSubgroup = ⊥ := by
    rw [eq_bot_iff]
    intro ϕ hϕ
    have hEq : Set.EqOn ϕ.toAlgHom (AlgHom.id F f.SplittingField)
        (f.rootSet f.SplittingField) := by
      intro α hα
      have hmem : aeval α T ∈ (f.tschirnhausPolynomial T).rootSet f.SplittingField := by
        rw [rootSet_tschirnhausPolynomial hf hsp]
        exact ⟨α, hα, rfl⟩
      have h1 : ϕ (aeval α T) = aeval α T :=
        (mem_fixingSubgroup_iff Gal(f.SplittingField/F)).mp hϕ _
          (hM ▸ IntermediateField.subset_adjoin F _ hmem)
      have h2 : aeval (ϕ α) T = aeval α T := by
        rw [aeval_algHom_apply ϕ α T, h1]
      exact (tschirnhausAdmissible_iff_injOn hsp).mp h
        ((rootSet_mapsTo ϕ.toAlgHom) hα) hα h2
    have := AlgHom.ext_of_adjoin_eq_top
      (IsSplittingField.adjoin_rootSet (L := f.SplittingField) f) hEq
    exact Subgroup.mem_bot.mpr (AlgEquiv.ext fun x ↦ DFunLike.congr_fun this x)
  rw [← IsGalois.fixedField_fixingSubgroup M, hfix, IntermediateField.fixedField_bot]

/-- The splitting field of `f` is a splitting field of an admissible transform, so the two
splitting fields agree up to an `F`-algebra equivalence. -/
theorem TschirnhausAdmissible.nonempty_algEquiv_splittingField (h : TschirnhausAdmissible f T)
    (hf : f.Monic) (hsep : f.Separable) :
    Nonempty (f.SplittingField ≃ₐ[F] (f.tschirnhausPolynomial T).SplittingField) :=
  haveI := h.isSplittingField hf hsep
  ⟨IsSplittingField.algEquiv f.SplittingField (f.tschirnhausPolynomial T)⟩

/-- **An admissible Tschirnhaus transform of a monic polynomial has the same Galois group as the
original polynomial.** -/
theorem TschirnhausAdmissible.nonempty_galMulEquiv (h : TschirnhausAdmissible f T) (hf : f.Monic) :
    Nonempty ((f.tschirnhausPolynomial T).Gal ≃* f.Gal) := by
  have hsp : (f.map (algebraMap F f.SplittingField)).Splits := SplittingField.splits f
  let _ : Fact (((f.tschirnhausPolynomial T).map
      (algebraMap F f.SplittingField)).Splits) := ⟨by
    rw [map_tschirnhausPolynomial hf]
    exact splits_tschirnhausPolynomial (hf.map _) hsp _⟩
  let _ : Normal F f.SplittingField := Normal.of_isSplittingField f
  refine ⟨(MulEquiv.ofBijective (Gal.restrict (f.tschirnhausPolynomial T) f.SplittingField)
    ⟨?_, Gal.restrict_surjective (f.tschirnhausPolynomial T) f.SplittingField⟩).symm⟩
  intro φ ψ hφψ
  change f.Gal at φ ψ
  apply Gal.ext
  intro x hx
  apply (tschirnhausAdmissible_iff_injOn hsp).mp h
  · exact (rootSet_mapsTo φ.toAlgHom) hx
  · exact (rootSet_mapsTo ψ.toAlgHom) hx
  · change aeval (φ x) T = aeval (ψ x) T
    rw [aeval_algHom_apply φ, aeval_algHom_apply ψ]
    let y : (f.tschirnhausPolynomial T).rootSet f.SplittingField :=
      ⟨aeval (x : f.SplittingField) T, by
      rw [rootSet_tschirnhausPolynomial hf hsp]
      exact ⟨x, hx, rfl⟩⟩
    calc
      φ (aeval (x : f.SplittingField) T) =
          (Gal.galActionHom (f.tschirnhausPolynomial T) f.SplittingField)
            ((Gal.restrict (f.tschirnhausPolynomial T) f.SplittingField) φ) y :=
        (Gal.galActionHom_restrict (f.tschirnhausPolynomial T) f.SplittingField φ y).symm
      _ = (Gal.galActionHom (f.tschirnhausPolynomial T) f.SplittingField)
          ((Gal.restrict (f.tschirnhausPolynomial T) f.SplittingField) ψ) y := by rw [hφψ]
      _ = ψ (aeval (x : f.SplittingField) T) :=
        Gal.galActionHom_restrict (f.tschirnhausPolynomial T) f.SplittingField ψ y

section GaloisImage

/-- A polynomial splits in its splitting field, recorded as the `Fact` that
`Polynomial.Gal.galActionHom` asks for. It stays local: as a global instance it would give
`f.rootSet f.SplittingField` the action `Polynomial.Gal.galAction` in addition to Mathlib's
intrinsic `Polynomial.Gal.galActionAux`, and the two are different actions. -/
local instance factSplitsSplittingField (p : F[X]) :
    Fact ((p.map (algebraMap F p.SplittingField)).Splits) := ⟨SplittingField.splits p⟩

/-- **The Galois images of `f` and of an admissible transform are conjugate.** They are conjugate
along the bijection `α ↦ T(α)` of root sets in the splitting field of `f`, which is where both
polynomials split. The caller supplies no `Fact` witnessing that the transform splits there. -/
theorem TschirnhausAdmissible.exists_equiv_range_galActionHom_eq (h : TschirnhausAdmissible f T)
    (hf : f.Monic) :
    have : Fact (((f.tschirnhausPolynomial T).map (algebraMap F f.SplittingField)).Splits) :=
      ⟨by
        rw [map_tschirnhausPolynomial hf]
        exact splits_tschirnhausPolynomial (hf.map _) (SplittingField.splits f) _⟩
    ∃ e : f.rootSet f.SplittingField ≃ (f.tschirnhausPolynomial T).rootSet f.SplittingField,
      (∀ x, (e x : f.SplittingField) = aeval (x : f.SplittingField) T) ∧
        (Gal.galActionHom (f.tschirnhausPolynomial T) f.SplittingField).range =
          (Gal.galActionHom f f.SplittingField).range.map
            (Equiv.permCongrHom e).toMonoidHom := by
  have hsp : (f.map (algebraMap F f.SplittingField)).Splits := SplittingField.splits f
  have : Fact (((f.tschirnhausPolynomial T).map (algebraMap F f.SplittingField)).Splits) :=
    ⟨by
      rw [map_tschirnhausPolynomial hf]
      exact splits_tschirnhausPolynomial (hf.map _) hsp _⟩
  set g := f.tschirnhausPolynomial T
  set E := f.SplittingField
  obtain ⟨e, hcoe⟩ : ∃ e : f.rootSet E ≃ g.rootSet E, ∀ x, (e x : E) = aeval (x : E) T := by
    have hrs : g.rootSet E = (fun α : E ↦ aeval α T) '' f.rootSet E :=
      rootSet_tschirnhausPolynomial hf hsp T
    have hbij : Set.BijOn (fun α : E ↦ aeval α T) (f.rootSet E) (g.rootSet E) := by
      rw [hrs]
      exact ((tschirnhausAdmissible_iff_injOn hsp).mp h).bijOn_image
    refine ⟨Equiv.ofBijective _ hbij.bijective, fun x ↦ ?_⟩
    rw [Equiv.coe_ofBijective, hbij.mapsTo.val_restrict_apply]
  refine ⟨e, hcoe, ?_⟩
  have : Normal F E := Normal.of_isSplittingField f
  have hequiv (phi : E ≃ₐ[F] E) (x : f.rootSet E) :
      (Gal.galActionHom g E) ((Gal.restrict g E) phi) (e x) =
        e ((Gal.galActionHom f E) ((Gal.restrict f E) phi) x) := by
    apply Subtype.ext
    rw [Gal.galActionHom_restrict, hcoe x, hcoe _, Gal.galActionHom_restrict,
      aeval_algHom_apply phi _ T]
  have hcomp : (Gal.galActionHom g E).comp (Gal.restrict g E) =
      (Equiv.permCongrHom e).toMonoidHom.comp
        ((Gal.galActionHom f E).comp (Gal.restrict f E)) := by
    refine MonoidHom.ext fun phi ↦ Equiv.ext fun y ↦ ?_
    simpa using hequiv phi (e.symm y)
  have hg : (Gal.galActionHom g E).range =
      ((Gal.galActionHom g E).comp (Gal.restrict g E)).range := by
    rw [MonoidHom.range_comp, MonoidHom.range_eq_top.mpr (Gal.restrict_surjective g E),
      ← MonoidHom.range_eq_map]
  rw [hg, hcomp, MonoidHom.range_comp, MonoidHom.range_comp,
    MonoidHom.range_eq_top.mpr (Gal.restrict_surjective f E), ← MonoidHom.range_eq_map]

end GaloisImage

end Polynomial
