/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.NumberTheory.Padics.ProperSpace
public import Mathlib.RingTheory.PowerSeries.Inverse
public import TauCeti.NumberTheory.Padics.MonoidAlgebra
public import TauCeti.RingTheory.PowerSeries.Evaluation
public import TauCeti.Topology.Algebra.Group.Profinite.CompletedGroupAlgebra.Basic
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.PadicInt
public import TauCeti.Topology.Algebra.Module.Compact
public import TauCeti.Topology.Algebra.Nonarchimedean.Profinite

/-!
# Power series in the completed group algebra of a pro-`p` group

Let `Γ` be a pro-`p` group and `Λ = ℤ_p[[Γ]]` its completed group algebra over the `p`-adic
integers, a compact totally disconnected topological ring. For every `γ ∈ Γ` the element
`γ - 1` of `Λ` is topologically nilpotent: at each finite level `ℤ_p[Γ ⧸ U]` the class of `γ` has
`p`-power order, so the coefficients of `(γ - 1) ^ n` tend to zero
(`TauCeti.PadicInt.tendsto_coeff_single_sub_one_pow`). When `Γ` is moreover compact and
commutative, `Λ` is a complete linearly topologized commutative ring, and Mathlib's
`PowerSeries.aeval` evaluates every power series `ψ ∈ ℤ_p⟦X⟧` at `γ - 1`, giving the continuous
`ℤ_p`-algebra homomorphism

  `ℤ_p⟦X⟧ → ℤ_p[[Γ]]`, `X ↦ γ - 1`, `1 + X ↦ γ`.

When `γ` topologically generates `Γ` this homomorphism is surjective: its range is compact, hence
closed, it contains `γ` and `γ⁻¹`, hence every element of the closed subgroup generated by `γ`,
which is all of `Γ`, and the span of the group elements is dense
(`TauCeti.completedGroupAlgebra.dense_span_range_of`). So the completed group algebra of a
procyclic pro-`p` group is a quotient of the power-series ring; for `Γ ≅ ℤ_p` this is the
classical description `ℤ_p[[Γ]] ≅ ℤ_p⟦T⟧` of the Iwasawa algebra, whose injectivity half is the
remaining step. The concrete instance `Γ = Multiplicative ℤ_[p]` with
`γ = Multiplicative.ofAdd (1 : ℤ_[p])` is recorded.

## Main results

* `TauCeti.completedGroupAlgebra.isTopologicallyNilpotent_of_sub_one`: `γ - 1` is topologically
  nilpotent in `ℤ_p[[Γ]]` for a pro-`p` group `Γ`; as this is `PowerSeries.HasEval`, the
  evaluation `PowerSeries.aeval` of power series at `γ - 1` is available.
* `TauCeti.completedGroupAlgebra.aeval_one_add_X`: the evaluation sends `1 + X` to `γ`.
* `TauCeti.completedGroupAlgebra.aeval_surjective`: the evaluation is surjective when `γ`
  topologically generates `Γ`.
* `TauCeti.completedGroupAlgebra.aeval_surjective_multiplicative_padicInt`: the case of the
  Iwasawa algebra `ℤ_p[[ℤ_p]]`.

## References

* L. C. Washington, *Introduction to Cyclotomic Fields*, 2nd ed., Theorem 7.1.
* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), Section 1.5.
-/

public section

open Filter Topology PowerSeries.WithPiTopology

namespace TauCeti.completedGroupAlgebra

variable {p : ℕ} [Fact p.Prime] {Γ : Type*} [Group Γ] [TopologicalSpace Γ]

/-- **`γ - 1` is topologically nilpotent** in the completed group algebra `ℤ_p[[Γ]]` of a pro-`p`
group `Γ`. As `PowerSeries.HasEval` is this predicate, power series over `ℤ_[p]` can be evaluated
at `γ - 1` by `PowerSeries.aeval` once `ℤ_p[[Γ]]` is a complete linearly topologized commutative
ring, which it is for `Γ` compact and commutative. -/
theorem isTopologicallyNilpotent_of_sub_one (hΓ : IsProP p Γ) (γ : Γ) :
    IsTopologicallyNilpotent (of ℤ_[p] Γ γ - 1) := by
  refine (isInducing_coeffFamily ℤ_[p] Γ).tendsto_nhds_iff.mpr
    (tendsto_pi_nhds.mpr fun U ↦ tendsto_pi_nhds.mpr fun g ↦ ?_)
  obtain ⟨k, hk⟩ := (isProP_iff.mp hΓ) U (γ : Γ ⧸ U.toSubgroup)
  simp only [Function.comp_def, coeffFamily_apply, map_pow, map_sub, map_one, proj_of, map_zero,
    MonoidAlgebra.coeff_zero, Finsupp.coe_zero, Pi.zero_apply]
  exact PadicInt.tendsto_coeff_single_sub_one_pow hk g

section

variable [SeparatelyContinuousMul Γ] [CompactSpace Γ] [IsMulCommutative Γ]

/-- Evaluation of power series at `γ - 1` sends `1 + X` to the group element `γ`. -/
@[simp]
theorem aeval_one_add_X (hΓ : IsProP p Γ) (γ : Γ) :
    PowerSeries.aeval (isTopologicallyNilpotent_of_sub_one hΓ γ)
      (1 + PowerSeries.X : PowerSeries ℤ_[p]) = of ℤ_[p] Γ γ := by
  rw [map_add, map_one, PowerSeries.aeval_X, add_sub_cancel]

end

variable [IsTopologicalGroup Γ] [CompactSpace Γ] [IsMulCommutative Γ]

/-- **The completed group algebra of a procyclic pro-`p` group is a quotient of `ℤ_p⟦X⟧`.** If `γ`
topologically generates the commutative pro-`p` group `Γ`, evaluation of power series at `γ - 1`
is a surjection `ℤ_p⟦X⟧ → ℤ_p[[Γ]]`. -/
theorem aeval_surjective (hΓ : IsProP p Γ) {γ : Γ}
    (hγ : (Subgroup.closure ({γ} : Set Γ)).topologicalClosure = ⊤) :
    Function.Surjective
      (PowerSeries.aeval (R := ℤ_[p]) (isTopologicallyNilpotent_of_sub_one hΓ γ)) := by
  set ε := PowerSeries.aeval (R := ℤ_[p]) (isTopologicallyNilpotent_of_sub_one hΓ γ) with hε
  -- The range of `ε` is the continuous image of the compact space `ℤ_p⟦X⟧`, hence closed.
  have hclosed : IsClosed (ε.range : Set (completedGroupAlgebra ℤ_[p] Γ)) := by
    have : CompactSpace (PowerSeries ℤ_[p]) := inferInstanceAs (CompactSpace ((Unit →₀ ℕ) → ℤ_[p]))
    rw [AlgHom.coe_range]
    exact (isCompact_range (PowerSeries.continuous_aeval _)).isClosed
  -- The range contains `γ`, as the image of `1 + X`, and `γ⁻¹`, as the image of `(1 + X)⁻¹`.
  have hγ_mem : of ℤ_[p] Γ γ ∈ ε.range := (AlgHom.mem_range ε).mpr ⟨_, aeval_one_add_X hΓ γ⟩
  have hγ_inv_mem : of ℤ_[p] Γ γ⁻¹ ∈ ε.range := by
    obtain ⟨u, hu⟩ := PowerSeries.isUnit_iff_constantCoeff.mpr
      (by simp : IsUnit (PowerSeries.constantCoeff (1 + PowerSeries.X : PowerSeries ℤ_[p])))
    refine (AlgHom.mem_range ε).mpr ⟨↑u⁻¹, left_inv_eq_right_inv (a := of ℤ_[p] Γ γ) ?_ ?_⟩
    · rw [← aeval_one_add_X hΓ γ, ← hu, ← hε, ← map_mul, Units.inv_mul, map_one]
    · rw [← map_mul, mul_inv_cancel, map_one]
  -- Hence it contains every element of the closed subgroup generated by `γ`, which is `Γ`.
  have hall : ∀ g : Γ, of ℤ_[p] Γ g ∈ ε.range := by
    have hsub : (Subgroup.closure ({γ} : Set Γ) : Set Γ) ⊆ of ℤ_[p] Γ ⁻¹' ε.range := by
      intro g hg
      refine (Subgroup.closure_induction
        (p := fun g _ ↦ of ℤ_[p] Γ g ∈ ε.range ∧ of ℤ_[p] Γ g⁻¹ ∈ ε.range) ?_ ?_ ?_ ?_ hg).1
      · rintro g (rfl : g = γ)
        exact ⟨hγ_mem, hγ_inv_mem⟩
      · rw [inv_one, map_one]
        exact ⟨one_mem _, one_mem _⟩
      · rintro g h _ _ ⟨hg, hg'⟩ ⟨hh, hh'⟩
        rw [map_mul, mul_inv_rev, map_mul]
        exact ⟨mul_mem hg hh, mul_mem hh' hg'⟩
      · rintro g _ ⟨hg, hg'⟩
        rw [inv_inv]
        exact ⟨hg', hg⟩
    intro g
    have hg : g ∈ closure (Subgroup.closure ({γ} : Set Γ) : Set Γ) := by
      rw [← Subgroup.topologicalClosure_coe, hγ]
      exact Set.mem_univ g
    exact closure_minimal hsub (hclosed.preimage (continuous_of ℤ_[p] Γ)) hg
  -- The dense span of the group elements lies in the closed range, which is therefore everything.
  have hspan : (Submodule.span ℤ_[p] (Set.range (of ℤ_[p] Γ)) : Set (completedGroupAlgebra ℤ_[p] Γ))
      ⊆ ε.range :=
    Submodule.span_le (p := Subalgebra.toSubmodule ε.range).mpr (Set.range_subset_iff.mpr hall)
  intro x
  have hx : x ∈ (ε.range : Set (completedGroupAlgebra ℤ_[p] Γ)) := by
    rw [← hclosed.closure_eq]
    exact closure_mono hspan ((dense_span_range_of ℤ_[p] Γ).closure_eq ▸ Set.mem_univ x)
  exact hx

/-- **The Iwasawa algebra `ℤ_p[[ℤ_p]]` is a quotient of `ℤ_p⟦X⟧`**: evaluation at `γ - 1`, for
`γ = Multiplicative.ofAdd (1 : ℤ_[p])` the topological generator of `Multiplicative ℤ_[p]`, is
surjective. -/
theorem aeval_surjective_multiplicative_padicInt (p : ℕ) [Fact p.Prime] :
    Function.Surjective (PowerSeries.aeval (R := ℤ_[p]) (isTopologicallyNilpotent_of_sub_one
      (isProP_multiplicative_padicInt p) (Multiplicative.ofAdd (1 : ℤ_[p])))) :=
  aeval_surjective (isProP_multiplicative_padicInt p) (topologicallyGenerates_ofAdd_one_padicInt p)

end TauCeti.completedGroupAlgebra
