/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.NumberTheory.NumberField.Basic
public import Mathlib.RingTheory.DedekindDomain.Different
import TauCeti.RingTheory.DedekindDomain.Different.Monogenic

/-!
# The different of a monogenic quadratic field

For a number field `K` with an algebraic integer `θ` such that `minpoly ℤ θ = X² − d` and
`𝓞 K = ℤ[θ]`, the different of `𝓞 K` over `ℤ` is generated by the derivative `f'(θ) = 2θ` of
the minimal polynomial: `𝔡 = (2θ)`. This is the monogenic different formula in the quadratic
case, uniform in the radicand `d`; the generation hypothesis `𝓞 K = ℤ[θ]` holds for instance
when `d` is squarefree and not `1` modulo `4` (`adjoin_gen_eq_top_of_mod_four_ne_one`).

## Main results

* `TauCeti.NumberField.differentIdeal_eq_span_two_mul_gen`: `differentIdeal ℤ (𝓞 K) = (2θ)`.
-/

public section

open Polynomial Ideal
open scoped NumberField

namespace TauCeti.NumberField

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K} {d : ℤ}

/-- **The different of `ℤ[θ]` is generated by `f'(θ) = 2θ`** when `𝓞 K = ℤ[θ]` and
`minpoly ℤ θ = X² − d`. -/
theorem differentIdeal_eq_span_two_mul_gen (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hadj : Algebra.adjoin ℤ {θ} = ⊤) : differentIdeal ℤ (𝓞 K) = span {2 * θ} := by
  rw [TauCeti.differentIdeal_eq_span_aeval_derivative_minpoly ℤ ℚ K (𝓞 K) θ hadj, hmin]
  simp [map_ofNat]

end TauCeti.NumberField
