/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Category.FGModuleCat.Basic
public import Mathlib.Algebra.Category.ModuleCat.Algebra
public import Mathlib.LinearAlgebra.Quotient.Basic
public import Mathlib.RingTheory.Ideal.Span

/-!
# Cyclic modules and maps out of them

Let `A` be a ring and let `a : A`. The cyclic right `A`-module `A ⧸ aA` is represented as the
quotient of the regular module `Aᵐᵒᵖ` by the left ideal generated by `op a`, which is `op (aA)`:
right `A`-modules are left `Aᵐᵒᵖ`-modules.

A map of right `A`-modules out of `A ⧸ aA` is determined by the image `m` of the generator, which
can be any element with `m * a = 0`, written `op a • m = 0`. When `A` is an algebra over a field
`k`, evaluation at the generator is a `k`-linear equivalence; the `k`-vector space structure on
morphisms is Mathlib's `ModuleCat.linearOverField`.

## Main definitions

* `TauCeti.FGModuleCat.cyclicModule`: the cyclic right module `A ⧸ aA`.
* `TauCeti.FGModuleCat.cyclicModuleLift`: the map `A ⧸ aA ⟶ M` sending the generator to an
  element `m` with `op a • m = 0`.
* `TauCeti.FGModuleCat.cyclicModuleHomEquiv`: the `k`-linear equivalence between maps
  `A ⧸ aA ⟶ M` and elements of `M` killed by `op a`.

## Main results

* `TauCeti.FGModuleCat.cyclicModule_hom_ext`: maps out of `A ⧸ aA` agree when they agree on the
  generator.
* `TauCeti.FGModuleCat.smul_cyclicModule_hom_mk_one_eq_zero`: the image of the generator under a
  map out of `A ⧸ aA` is killed by `op a`.
-/

public section

namespace TauCeti

open CategoryTheory MulOpposite

universe w u

namespace FGModuleCat

variable {A : Type u} [Ring A]

/-- The cyclic right `A`-module `A ⧸ aA`, as a finitely generated `Aᵐᵒᵖ`-module: the quotient of
the regular module `Aᵐᵒᵖ` by the left ideal generated by `op a`, which is `op (aA)`. -/
noncomputable abbrev cyclicModule (a : A) : FGModuleCat.{u} Aᵐᵒᵖ :=
  FGModuleCat.of Aᵐᵒᵖ (Aᵐᵒᵖ ⧸ Ideal.span {op a})

/-! ### Maps out of a cyclic module -/

section Hom

variable {M : Type u} [AddCommGroup M] [Module Aᵐᵒᵖ M] [Module.Finite Aᵐᵒᵖ M]

/-- The map of right `A`-modules `A ⧸ aA ⟶ M` sending the class of `c` to `c • m`, for an element
`m` with `op a • m = 0`. -/
noncomputable def cyclicModuleLift (a : A) (m : M) (hm : op a • m = 0) :
    cyclicModule a ⟶ FGModuleCat.of Aᵐᵒᵖ M :=
  FGModuleCat.ofHom <| Submodule.liftQSpanSingleton (op a) (LinearMap.toSpanSingleton Aᵐᵒᵖ M m) <|
    (LinearMap.toSpanSingleton_apply _ _ _ _).trans hm

@[simp]
theorem cyclicModuleLift_mk (a : A) (m : M) (hm : op a • m = 0) (c : Aᵐᵒᵖ) :
    (cyclicModuleLift a m hm).hom.hom (Submodule.Quotient.mk c) = c • m :=
  (rfl)

/-- Two maps out of the cyclic module `A ⧸ aA` agree when they agree on the generator. -/
@[ext]
theorem cyclicModule_hom_ext {a : A} {N : FGModuleCat.{u} Aᵐᵒᵖ} {f g : cyclicModule a ⟶ N}
    (h : f.hom.hom (Submodule.Quotient.mk 1) = g.hom.hom (Submodule.Quotient.mk 1)) : f = g :=
  FGModuleCat.hom_ext <| Submodule.linearMap_qext _ <| LinearMap.ext_ring h

/-- The image of the generator under a map out of `A ⧸ aA` is killed by `op a`. -/
theorem smul_cyclicModule_hom_mk_one_eq_zero {a : A} {N : FGModuleCat.{u} Aᵐᵒᵖ}
    (f : cyclicModule a ⟶ N) : op a • f.hom.hom (Submodule.Quotient.mk 1) = 0 := by
  rw [← LinearMap.map_smul, ← Submodule.Quotient.mk_smul, smul_eq_mul, mul_one,
    (Submodule.Quotient.mk_eq_zero _).2 (Ideal.mem_span_singleton_self _), map_zero]

variable (k : Type w) [Field k] [Algebra k A] [Module k M] [IsScalarTower k Aᵐᵒᵖ M]

/-- **Maps out of a cyclic module.** Evaluation at the generator is a `k`-linear equivalence
between maps of right `A`-modules `A ⧸ aA ⟶ M` and elements of `M` killed by `op a`. -/
noncomputable def cyclicModuleHomEquiv (a : A) :
    (cyclicModule a ⟶ FGModuleCat.of Aᵐᵒᵖ M) ≃ₗ[k]
      LinearMap.ker (DistribSMul.toLinearMap k M (op a)) where
  toFun f := ⟨f.hom.hom (Submodule.Quotient.mk 1), by
    rw [LinearMap.mem_ker, DistribSMul.toLinearMap_apply]
    exact smul_cyclicModule_hom_mk_one_eq_zero f⟩
  invFun m := cyclicModuleLift a m <| by
    rw [← DistribSMul.toLinearMap_apply k M (op a), ← LinearMap.mem_ker]
    exact m.2
  map_add' _ _ := rfl
  map_smul' c f := Subtype.ext (algebraMap_smul Aᵐᵒᵖ c _)
  left_inv f := cyclicModule_hom_ext <| by
    dsimp only
    rw [cyclicModuleLift_mk, one_smul]
  right_inv m := Subtype.ext <| by
    dsimp only
    rw [cyclicModuleLift_mk, one_smul]

@[simp]
theorem cyclicModuleHomEquiv_apply_coe (a : A) (f : cyclicModule a ⟶ FGModuleCat.of Aᵐᵒᵖ M) :
    (cyclicModuleHomEquiv k a f : M) = f.hom.hom (Submodule.Quotient.mk 1) :=
  (rfl)

@[simp]
theorem cyclicModuleHomEquiv_symm_apply (a : A)
    (m : LinearMap.ker (DistribSMul.toLinearMap k M (op a))) :
    (cyclicModuleHomEquiv k a).symm m = cyclicModuleLift a (m : M)
      ((DistribSMul.toLinearMap_apply k M (op a) m).symm.trans (LinearMap.mem_ker.1 m.2)) :=
  (rfl)

end Hom

end FGModuleCat

end TauCeti
