/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.SpecificGroups.CFSG.Suzuki.Center
public import TauCeti.GroupTheory.SpecificGroups.CFSG.Suzuki.Generation
public import TauCeti.GroupTheory.SpecificGroups.CFSG.Suzuki.Perfect

/-!
# The Suzuki candidate group is the generated Suzuki group

A valid Suzuki index `²B₂(2^(2m+1))`, `m ≥ 1`, has two realizations in this library. The
fixed-point construction `TauCeti.SuzukiLieIndex.Group` is the derived subgroup of the Steinberg
fixed points of the rank-two symplectic carrier, modulo the centre of that derived subgroup. The
generated group `TauCeti.suzukiGroup m` is the subgroup of `GL₄(𝔽_(2^(2m+1)))` generated by
Suzuki's unipotent matrices `u(a, b)` and the Weyl element `w`. This file identifies them.

The identification composes three facts already available. The Steinberg fixed points are the
generated group, `TauCeti.SuzukiLieIndex.suzukiGroupEquivFixedPoints`; the generated group is
perfect for `m ≠ 0`, `TauCeti.Suzuki.isPerfect_suzukiGroup`, and validity of the index is exactly
`m ≥ 1`; and its centre is trivial, `TauCeti.Suzuki.center_suzukiGroup_eq_bot`. Transporting the
last two along the first, the fixed points are perfect with trivial centre, so the derived central
quotient returns them unchanged, `TauCeti.DerivedCentralQuotient.mulEquivOfCenterEqBot`.

On the fixed-point side the generated group is reached through `TauCeti.SuzukiLieIndex.of`, the
introduction form of a valid Suzuki index at parameter `m`; the perfectness and centre statements
are made for an arbitrary Suzuki index, every one of which is of that form.

Nothing here asserts that either group is finite or simple; the identification says that the two
constructions name the same group, and nothing about that group.

## Main definitions

* `TauCeti.SuzukiLieIndex.groupEquivFixedPoints`: the candidate group of a Suzuki index is its
  Steinberg fixed-point group, the derived central quotient doing nothing.
* `TauCeti.SuzukiLieIndex.groupEquivSuzukiGroup`: the candidate group of the valid Suzuki index at
  parameter `m` is the generated Suzuki group `TauCeti.suzukiGroup m`.

## Main results

* `TauCeti.SuzukiLieIndex.instIsPerfectFixedPoints` and
  `TauCeti.SuzukiLieIndex.center_fixedPoints_eq_bot`: the Steinberg fixed points of a Suzuki
  index are perfect and have trivial centre.
* `TauCeti.SuzukiLieIndex.generatorEmbedding_groupEquivSuzukiGroup_mk`: on underlying matrices,
  the identification is the scalar extension of the generator model, so a class in the candidate
  group and its image in the generated group are the same matrix over the algebraic closure.

## References

* M. Suzuki, *On a class of doubly transitive groups*, Annals of Mathematics **75** (1962),
  105--145.
* R. A. Wilson, *The Finite Simple Groups*, Springer GTM 251 (2009), §4.2.
-/

public section

noncomputable section

open Subgroup

namespace TauCeti.SuzukiLieIndex

variable (d : SuzukiLieIndex)

/-! ## The fixed points are perfect with trivial centre -/

/-- The Steinberg fixed points of a Suzuki index are perfect: they are the generated Suzuki group
at a nonzero parameter, and that group is its own derived subgroup. -/
instance instIsPerfectFixedPoints : Group.IsPerfect d.FixedPoints := by
  obtain ⟨m, hvalid, rfl⟩ := d.exists_eq_of
  have hm : m ≠ 0 := by
    have h := hvalid
    rw [LieTypeIndex.valid_iff, LieTypeIndex.inStandardRange_iff] at h
    omega
  have := Suzuki.isPerfect_suzukiGroup hm
  exact Group.IsPerfect.ofSurjective (f := (suzukiGroupEquivFixedPoints m hvalid).toMonoidHom)
    (suzukiGroupEquivFixedPoints m hvalid).surjective

/-- The centre of the Steinberg fixed points of a Suzuki index is trivial. -/
@[simp]
theorem center_fixedPoints_eq_bot : center d.FixedPoints = ⊥ := by
  obtain ⟨m, hvalid, rfl⟩ := d.exists_eq_of
  rw [← map_center_eq (suzukiGroupEquivFixedPoints m hvalid), Suzuki.center_suzukiGroup_eq_bot,
    Subgroup.map_bot]

/-! ## The candidate group is the fixed-point group -/

/-- **The candidate group of a Suzuki index is its Steinberg fixed-point group.** The fixed
points are perfect with trivial centre, so taking the derived subgroup and then its central
quotient changes nothing. -/
def groupEquivFixedPoints : d.Group ≃* d.FixedPoints :=
  DerivedCentralQuotient.mulEquivOfCenterEqBot d.center_fixedPoints_eq_bot

/-- The identification sends the class of an element of the derived subgroup of the fixed points
to that element itself. -/
@[simp]
theorem groupEquivFixedPoints_mk (x : ↥(commutator d.FixedPoints)) :
    d.groupEquivFixedPoints (x : d.Group) = (x : d.FixedPoints) :=
  DerivedCentralQuotient.mulEquivOfCenterEqBot_mk d.center_fixedPoints_eq_bot x

/-- The inverse identification sends a fixed point to its class; every fixed point is in the
derived subgroup, the fixed points being perfect. -/
@[simp]
theorem groupEquivFixedPoints_symm_apply (y : d.FixedPoints) :
    d.groupEquivFixedPoints.symm y =
      ((⟨y, Group.IsPerfect.mem_commutator⟩ : ↥(commutator d.FixedPoints)) : d.Group) := by
  rw [MulEquiv.symm_apply_eq, groupEquivFixedPoints_mk]

/-! ## The candidate group is the generated Suzuki group -/

variable (m : ℕ) (hvalid : (LieTypeIndex.suzuki m).Valid)

/-- **The Suzuki candidate group is the generated Suzuki group**: for every valid parameter `m`,
which is to say every `m ≥ 1`, the derived central quotient of the Steinberg fixed points of
`²B₂(2^(2m+1))` is isomorphic to the group generated by Suzuki's four-by-four matrices over
`𝔽_(2^(2m+1))`. -/
def groupEquivSuzukiGroup : (of m hvalid).Group ≃* suzukiGroup m :=
  (of m hvalid).groupEquivFixedPoints.trans (suzukiGroupEquivFixedPoints m hvalid).symm

/-- The identification with the generated Suzuki group sends the class of an element of the
derived subgroup of the fixed points to the element of `suzukiGroup m` that the generation
theorem names it by. -/
@[simp]
theorem groupEquivSuzukiGroup_mk (x : ↥(commutator (of m hvalid).FixedPoints)) :
    groupEquivSuzukiGroup m hvalid (x : (of m hvalid).Group) =
      (suzukiGroupEquivFixedPoints m hvalid).symm (x : (of m hvalid).FixedPoints) := by
  simp only [groupEquivSuzukiGroup, MulEquiv.trans_apply, groupEquivFixedPoints_mk]

/-- The inverse identification carries an element of the generated Suzuki group to the fixed
point the generation theorem names by it, and then to its class in the candidate group. -/
@[simp]
theorem groupEquivSuzukiGroup_symm_apply (g : suzukiGroup m) :
    (groupEquivSuzukiGroup m hvalid).symm g =
      (of m hvalid).groupEquivFixedPoints.symm (suzukiGroupEquivFixedPoints m hvalid g) := by
  simp only [groupEquivSuzukiGroup, MulEquiv.symm_trans_apply, MulEquiv.symm_symm]

/-- On underlying matrices the identification is the scalar extension of the generator model: the
image in the generated Suzuki group of the class of a fixed point is the matrix whose scalar
extension along the generator embedding is that fixed point. -/
@[simp]
theorem generatorEmbedding_groupEquivSuzukiGroup_mk
    (x : ↥(commutator (of m hvalid).FixedPoints)) :
    generatorEmbedding m hvalid (groupEquivSuzukiGroup m hvalid (x : (of m hvalid).Group)) =
      (((x : (of m hvalid).FixedPoints) : (of m hvalid).toRankTwoBLieIndex.AmbientGroup) :
        GL (Fin 4) (of m hvalid).1.Closure) := by
  rw [groupEquivSuzukiGroup_mk, ← coe_coe_suzukiGroupEquivFixedPoints_apply,
    MulEquiv.apply_symm_apply]

end TauCeti.SuzukiLieIndex
