/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.LocalRing.Quotient
public import Mathlib.RingTheory.Unramified.LocalRing

/-!
# Unramifiedness of a local algebra at its maximal ideal

`Algebra.IsUnramifiedAt R q` is formal unramifiedness over `R` of the localization of the ambient
algebra at the prime `q`. When the ambient algebra `S` is already local and `q` is its maximal
ideal, that localization is `S` itself, because every element outside the maximal ideal is
already a unit. This file records the resulting equivalence, which is what lets a formal
unramifiedness statement about a local ring be read by Mathlib's unramified-locus API, and
conversely.

When the maximal ideal of `S` is generated by that of `R` — as it is for a formally unramified
extension, by `Algebra.FormallyUnramified.map_maximalIdeal` — reduction modulo it loses no
generators: the residues of a subset of `S` span the residue field of `S` over that of `R`
exactly when the subset spans `S` over `R`. This is Mathlib's
`IsLocalRing.quotient_span_eq_top_iff_span_eq_top` read through that generation, and the
module-level companion of Mathlib's `IsLocalRing.adjoin_residue_eq_top_iff_adjoin_eq_top`, which
says the same for generation as an algebra by a single element.

## Main results

* `TauCeti.isUnramifiedAt_maximalIdeal_iff`: a local `R`-algebra is unramified at its maximal
  ideal exactly when it is formally unramified over `R`.
* `TauCeti.IsLocalRing.span_residue_image_eq_top_iff_span_eq_top`: if the maximal ideal of a
  module-finite local extension is generated by that of the base, then the residues of a subset
  span the residue extension exactly when the subset spans.
-/

public section

namespace TauCeti

variable (R S : Type*) [CommRing R] [CommRing S] [Algebra R S] [IsLocalRing S]

/-- A local `R`-algebra is unramified at its maximal ideal exactly when it is formally unramified
over `R`: localizing a local ring at its maximal ideal inverts only units. -/
theorem isUnramifiedAt_maximalIdeal_iff :
    Algebra.IsUnramifiedAt R (IsLocalRing.maximalIdeal S) ↔ Algebra.FormallyUnramified R S :=
  have primeCompl_le : (IsLocalRing.maximalIdeal S).primeCompl ≤ IsUnit.submonoid S :=
    fun x hx ↦ (IsUnit.mem_submonoid_iff x).2
      (IsLocalRing.notMem_maximalIdeal.1 (Ideal.mem_primeCompl_iff.1 hx))
  (Algebra.FormallyUnramified.iff_of_equiv
    ((IsLocalization.atUnits S (IsLocalRing.maximalIdeal S).primeCompl
      primeCompl_le).restrictScalars R)).symm

section ResidueSpan

variable {R S} [IsLocalRing R] [IsLocalHom (algebraMap R S)] [Module.Finite R S]

/-- **A subset of a finite local extension spans it exactly when its residues span the residue
extension**, provided the maximal ideal of `S` is generated by the maximal ideal of `R` — as it is
when `S` is formally unramified over `R`, by `Algebra.FormallyUnramified.map_maximalIdeal`. -/
theorem IsLocalRing.span_residue_image_eq_top_iff_span_eq_top
    (h : (IsLocalRing.maximalIdeal R).map (algebraMap R S) = IsLocalRing.maximalIdeal S)
    {s : Set S} :
    Submodule.span (IsLocalRing.ResidueField R) (IsLocalRing.residue S '' s) = ⊤ ↔
      Submodule.span R s = ⊤ := by
  -- This is Mathlib's `IsLocalRing.quotient_span_eq_top_iff_span_eq_top` read through `h`.
  -- Both spans descend to `R`-spans, since `R → ResidueField R` is surjective. That removes the
  -- ideal from the scalars, so the hypothesis can be rewritten in the ideal indexing the quotient.
  have H := IsLocalRing.quotient_span_eq_top_iff_span_eq_top (R := R) s
  rw [← Submodule.restrictScalars_eq_top_iff (S := R),
    Submodule.restrictScalars_span R _ Ideal.Quotient.mk_surjective] at H
  rw [h] at H
  rwa [← Submodule.restrictScalars_eq_top_iff (S := R),
    Submodule.restrictScalars_span R (IsLocalRing.ResidueField R)
      (by exact IsLocalRing.residue_surjective)]

end ResidueSpan

end TauCeti
