/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Localization.Basic
public import Mathlib.RingTheory.Unramified.LocalRing
public import Mathlib.RingTheory.Unramified.Locus

/-!
# Unramifiedness of a local algebra at its maximal ideal

`Algebra.IsUnramifiedAt R q` is formal unramifiedness over `R` of the localization of the ambient
algebra at the prime `q`. When the ambient algebra `S` is already local and `q` is its maximal
ideal, that localization is `S` itself, because every element outside the maximal ideal is
already a unit. This file records the resulting equivalence, which is what lets a formal
unramifiedness statement about a local ring be read by Mathlib's unramified-locus API, and
conversely.

A module-finite formally unramified extension of local rings has its maximal ideal generated by
the maximal ideal of the base, by `Algebra.FormallyUnramified.map_maximalIdeal`. Reduction modulo
that ideal therefore loses no generators: a subset of `S` spans `S` over `R` exactly when its
residues span the residue field of `S` over that of `R`. This is the module-level companion of
Mathlib's `IsLocalRing.adjoin_residue_eq_top_iff_adjoin_eq_top`, which says the same for
generation as an algebra by a single element.

## Main results

* `TauCeti.isUnramifiedAt_maximalIdeal_iff`: a local `R`-algebra is unramified at its maximal
  ideal exactly when it is formally unramified over `R`.
* `TauCeti.IsLocalRing.span_eq_top_iff_span_residue_image_eq_top`: a subset of a module-finite
  formally unramified extension of local rings spans it exactly when its residues span the
  residue extension.
-/

public section

namespace TauCeti

variable (R S : Type*) [CommRing R] [CommRing S] [Algebra R S] [IsLocalRing S]

/-- A local `R`-algebra is unramified at its maximal ideal exactly when it is formally unramified
over `R`: localizing a local ring at its maximal ideal inverts only units. -/
theorem isUnramifiedAt_maximalIdeal_iff :
    Algebra.IsUnramifiedAt R (IsLocalRing.maximalIdeal S) ↔ Algebra.FormallyUnramified R S :=
  have primeCompl_le : (IsLocalRing.maximalIdeal S).primeCompl ≤ IsUnit.submonoid S :=
    fun x hx ↦ (IsUnit.mem_submonoid_iff x).2
      (IsLocalRing.notMem_maximalIdeal.1 (Ideal.mem_primeCompl_iff.1 hx))
  (Algebra.FormallyUnramified.iff_of_equiv
    ((IsLocalization.atUnits S (IsLocalRing.maximalIdeal S).primeCompl
      primeCompl_le).restrictScalars R)).symm

section ResidueSpan

variable {R S} [IsLocalRing R] [IsLocalHom (algebraMap R S)] [Module.Finite R S]
  [Algebra.FormallyUnramified R S]

/-- **Spanning a formally unramified finite local extension is spanning its residue extension.**
A subset of `S` spans `S` over `R` exactly when its residues span the residue field of `S` over
the residue field of `R`. Only the direction that lifts generators uses unramifiedness; the other
holds over any local base. -/
theorem IsLocalRing.span_eq_top_iff_span_residue_image_eq_top {s : Set S} :
    Submodule.span R s = ⊤ ↔
      Submodule.span (IsLocalRing.ResidueField R) (IsLocalRing.residue S '' s) = ⊤ := by
  constructor
  · intro hs
    refine Submodule.eq_top_iff'.2 fun z ↦ ?_
    obtain ⟨y, rfl⟩ := IsLocalRing.residue_surjective (R := S) z
    have hy : y ∈ Submodule.span R s := hs.symm ▸ Submodule.mem_top
    induction hy using Submodule.span_induction with
    | mem x hx => exact Submodule.subset_span ⟨x, hx, rfl⟩
    | zero => simp
    | add x y _ _ hx hy => rw [map_add]; exact Submodule.add_mem _ hx hy
    | smul a x _ hx =>
      rw [Algebra.smul_def, map_mul, ← IsLocalRing.ResidueField.algebraMap_residue,
        ← Algebra.smul_def]
      exact Submodule.smul_mem _ _ hx
  · intro hs
    refine eq_top_iff.2 <| Submodule.le_of_le_smul_of_le_jacobson_bot
      (Module.finite_def.mp inferInstance) (IsLocalRing.maximalIdeal_le_jacobson ⊥) fun y _ ↦ ?_
    -- Write the residue of `y` as a combination of residues of elements `w i` of `s`, and lift
    -- its coefficients along `R → ResidueField R`.
    obtain ⟨n, c, g, hg⟩ :=
      Submodule.mem_span_set'.1 (hs ▸ Submodule.mem_top (x := IsLocalRing.residue S y))
    choose w hw hwr using fun i ↦ (g i).2
    choose a ha using fun i ↦ IsLocalRing.residue_surjective (R := R) (c i)
    refine Submodule.mem_sup.mpr ⟨∑ i, a i • w i, Submodule.sum_mem _ fun i _ ↦
      Submodule.smul_mem _ _ (Submodule.subset_span (hw i)), y - ∑ i, a i • w i, ?_, by ring⟩
    rw [Ideal.smul_top_eq_map, Algebra.FormallyUnramified.map_maximalIdeal,
      Submodule.restrictScalars_mem, ← IsLocalRing.residue_eq_zero_iff, map_sub, sub_eq_zero,
      ← hg]
    simp only [map_sum, Algebra.smul_def, map_mul, ← ha, ← hwr,
      ← IsLocalRing.ResidueField.algebraMap_residue]

end ResidueSpan

end TauCeti
