/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.HighestWeight.Character
public import TauCeti.Algebra.Lie.HighestWeight.FiniteDimensional
public import TauCeti.Algebra.Lie.HighestWeight.Trivial
public import TauCeti.LinearAlgebra.RootSystem.Weyl.Group

/-!
# Minuscule weights

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over an algebraically
closed field of characteristic zero, let `H` be a Cartan subalgebra and `b` a base of its root
system. A dominant integral weight `mu` is **minuscule** when every weight of the irreducible
module `L(mu)` is Weyl-conjugate to `mu`, that is, when the weights of `L(mu)` form a single orbit
of the Weyl group. This file defines `TauCeti.IsMinuscule`, the prerequisite of the minuscule
Pieri rule, and proves the dimension count that the orbit hypothesis buys: a highest weight module
whose weights lie in one Weyl orbit has

`dim M = |W · lam|`,

the dimension being the size of a Weyl orbit — a purely combinatorial count, with no Weyl
character formula in sight.

## Why the orbit hypothesis does all the work

Two facts about the formal character of `TauCeti/Algebra/Lie/Weights/FormalCharacter.lean` combine
to give everything. Its coefficient at the highest weight of a highest weight module is `1`
(`TauCeti.formalCharacter_coeff_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top`, the top weight
space being the line spanned by the generator); and it is Weyl-invariant
(`TauCeti.formalCharacter_coeff_weylGroup_smul`, the Weyl invariance of weight multiplicities,
proved from the rank-one theory and not from the character formula). So *every* weight in the orbit
of the highest weight already has multiplicity `1`, whatever the module; the minuscule hypothesis
is exactly the statement that there are no other weights, and the dimension is then the number of
coefficients, all of them `1`.

Accordingly the substance of the file is stated for an arbitrary finite-dimensional module
generated by a highest weight vector whose weights lie in one orbit
(`TauCeti.finrank_eq_card_orbit_of_isHighestWeightVector`). That statement is unconditional: it
assumes a highest weight vector and produces the dimension of its orbit.

## The named carrier, and what is deliberately *not* claimed here

`TauCeti.irreducibleQuotient` is built from the Verma module, and `L(mu)` is the zero module
exactly when `M(mu)` is (`TauCeti.subsingleton_irreducibleQuotient_iff`). That `M(mu) ≠ 0` for a
dominant integral `mu` is the freeness half of Poincaré--Birkhoff--Witt, the separate sub-project
of `TauCeti/Algebra/Lie/UniversalEnveloping/PBW/`, and it is not available in this repository; the
situation is the one already recorded in `TauCeti/Algebra/Lie/HighestWeight/Verma.lean` and
`TauCeti/Algebra/Lie/HighestWeight/Dual.lean`.

`TauCeti.IsMinuscule` is therefore exactly the dominance-and-orbit condition the roadmap pins, with
nothing bundled into it, and this file states about the named carrier only what follows from that
condition *unconditionally*. A zero `L(mu)` has no weights, so the orbit condition holds there
vacuously; what survives that degenerate case is the inequality
`TauCeti.IsMinuscule.finrank_irreducibleQuotient_le`, `dim L(mu) ≤ |W · mu|`, which is an equality
as soon as `L(mu)` is nonzero. Turning it into the unconditional equality `dim L(mu) = |W · mu|` is
precisely the missing Poincaré--Birkhoff--Witt input, so it is left for the PR that supplies it:
the general theorem it will be read off, `TauCeti.finrank_eq_card_orbit_of_isHighestWeightVector`,
is already here, and the equality is one line from it.

At the one weight where the nonvanishing *is* available unconditionally this file takes it all the
way: `TauCeti.isMinuscule_zero` proves `0` minuscule and
`TauCeti.finrank_irreducibleQuotient_zero` reads off `dim L(0) = 1`, both with every hypothesis
discharged.

## Main definitions

* `TauCeti.IsMinuscule`: `mu` is dominant integral and every weight of `L(mu)` is Weyl-conjugate to
  `mu`, with `TauCeti.isMinuscule_iff` the introduction rule its unexposed body needs.

## Main results

* `TauCeti.finrank_eq_card_orbit_of_isHighestWeightVector`: **a highest weight module whose weights
  lie in one Weyl orbit has the dimension of that orbit**, the substance of the file. It rests on
  two statements that hold in *every* highest weight module along the orbit of its highest weight:
  that the orbit consists of weights, all of them simple
  (`TauCeti.formalCharacter_coeff_weylGroup_smul_eq_one_of_isHighestWeightVector`), and hence that
  the orbit hypothesis makes the weights exactly the orbit
  (`TauCeti.genWeightSpace_ne_bot_iff_mem_orbit_of_isHighestWeightVector`).
* `TauCeti.IsMinuscule.finrank_irreducibleQuotient_le`: **`dim L(mu) ≤ |W · mu|`**, the part of the
  dimension count at the named carrier that needs no Verma-module nonvanishing.
* `TauCeti.isMinuscule_zero`: **the zero weight is minuscule**, so the notion is not empty, and
  `TauCeti.finrank_irreducibleQuotient_zero`: the module it names is one-dimensional, the orbit of
  `0` being a point. Both are unconditional.

## Implementation notes

The Weyl group acts here as `(LieAlgebra.IsKilling.rootSystem H).weylGroup` acting on
`Module.Dual K H`, which is the action the invariance of weight multiplicities
(`TauCeti.formalCharacter_coeff_weylGroup_smul`) is stated for; the orbit is Mathlib's
`MulAction.orbit`, counted with `Nat.card`. The roadmap spells the orbit condition with an
explicit `∃ w ∈ weylGroup`, which is the same statement read through the subgroup's own action.

That a trivial module has no weight other than `0` is proved here as a `private` lemma: it is a
general fact about trivial modules with no consumer outside the proof of
`TauCeti.isMinuscule_zero`, and giving it a home of its own is a relocation decision that should
wait for a second consumer.

## References

This builds the `IsMinuscule` item of Layer 7 (the isotypic decomposition toolkit) of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`, whose `Suggested.lean` pins the
definition; the minuscule Pieri rule it is wanted for is not proved here.

* N. Bourbaki, *Groupes et algèbres de Lie*, Ch. VIII, §7.3, where minuscule weights are
  introduced.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §13 and §21.2.
-/

public section

namespace TauCeti

open LieAlgebra LieModule Module

universe u v w

section General

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [IsAlgClosed K]
  [LieRing L] [LieAlgebra K L] [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  [FiniteDimensional K M]
  {b : (IsKilling.rootSystem H).Base} {lam : Dual K H} {v : M}

/-- **Every Weyl translate of the highest weight is again a weight, with multiplicity one.** The
coefficient of the formal character at the highest weight of a highest weight module is `1`, and
the character is Weyl-invariant, so the whole orbit of the highest weight carries the coefficient
`1`. No minuscule hypothesis is involved: this holds in every highest weight module. -/
theorem formalCharacter_coeff_weylGroup_smul_eq_one_of_isHighestWeightVector
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    (w : (IsKilling.rootSystem H).weylGroup) :
    (formalCharacter K H M).coeff (w • lam) = 1 := by
  rw [formalCharacter_coeff_weylGroup_smul]
  exact formalCharacter_coeff_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen

/-- **The weight spaces along the orbit of the highest weight are lines.** This is the previous
result read as a dimension, through `TauCeti.formalCharacter_coeff`. -/
theorem finrank_genWeightSpace_weylGroup_smul_eq_one_of_isHighestWeightVector
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    (w : (IsKilling.rootSystem H).weylGroup) :
    finrank K (genWeightSpace M ((w • lam : Dual K H) : H → K)) = 1 := by
  have h := formalCharacter_coeff_weylGroup_smul_eq_one_of_isHighestWeightVector hv hgen w
  rw [formalCharacter_coeff] at h
  exact_mod_cast h

/-- **A Weyl translate of the highest weight is a weight.** In particular the orbit of the highest
weight is contained in the set of weights of any highest weight module. -/
theorem genWeightSpace_weylGroup_smul_ne_bot_of_isHighestWeightVector
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    (w : (IsKilling.rootSystem H).weylGroup) :
    genWeightSpace M ((w • lam : Dual K H) : H → K) ≠ ⊥ := fun hbot ↦ by
  have h := formalCharacter_coeff_weylGroup_smul_eq_one_of_isHighestWeightVector hv hgen w
  rw [formalCharacter_coeff_eq_zero_iff.mpr hbot] at h
  exact zero_ne_one h

/-- **The weights of a highest weight module whose weights lie in one Weyl orbit are exactly that
orbit.** One inclusion is the hypothesis; the other holds in every highest weight module, by
`TauCeti.genWeightSpace_weylGroup_smul_ne_bot_of_isHighestWeightVector`. -/
theorem genWeightSpace_ne_bot_iff_mem_orbit_of_isHighestWeightVector
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    (horb : ∀ chi : Dual K H, genWeightSpace M (chi : H → K) ≠ ⊥ →
      ∃ w : (IsKilling.rootSystem H).weylGroup, w • lam = chi)
    (chi : Dual K H) :
    genWeightSpace M (chi : H → K) ≠ ⊥ ↔
      chi ∈ MulAction.orbit (IsKilling.rootSystem H).weylGroup lam := by
  refine ⟨fun h ↦ MulAction.mem_orbit_iff.mpr (horb chi h), ?_⟩
  rintro ⟨w, rfl⟩
  exact genWeightSpace_weylGroup_smul_ne_bot_of_isHighestWeightVector hv hgen w

/-- **A highest weight module whose weights lie in a single Weyl orbit has the dimension of that
orbit.** Every weight has multiplicity one, by
`TauCeti.formalCharacter_coeff_weylGroup_smul_eq_one_of_isHighestWeightVector`, so the dimension —
the sum of the coefficients of the formal character,
`TauCeti.sum_formalCharacter_coeff_eq_finrank` — counts the weights, and the hypothesis says the
weights are the orbit of the highest weight. This is the content of the minuscule case, stated
before `TauCeti.IsMinuscule` names it. -/
theorem finrank_eq_card_orbit_of_isHighestWeightVector
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    (horb : ∀ chi : Dual K H, genWeightSpace M (chi : H → K) ≠ ⊥ →
      ∃ w : (IsKilling.rootSystem H).weylGroup, w • lam = chi) :
    finrank K M = Nat.card (MulAction.orbit (IsKilling.rootSystem H).weylGroup lam) := by
  classical
  have hone : ∀ chi ∈ (formalCharacter K H M).coeff.support,
      (formalCharacter K H M).coeff chi = 1 := by
    intro chi hchi
    rw [Finsupp.mem_support_iff] at hchi
    obtain ⟨w, rfl⟩ := horb chi ((not_congr formalCharacter_coeff_eq_zero_iff).mp hchi)
    exact formalCharacter_coeff_weylGroup_smul_eq_one_of_isHighestWeightVector hv hgen w
  have hsupp : (((formalCharacter K H M).coeff.support : Finset (Dual K H)) : Set (Dual K H)) =
      MulAction.orbit (IsKilling.rootSystem H).weylGroup lam := by
    ext chi
    rw [Finset.mem_coe, Finsupp.mem_support_iff,
      ← genWeightSpace_ne_bot_iff_mem_orbit_of_isHighestWeightVector hv hgen horb chi]
    exact not_congr formalCharacter_coeff_eq_zero_iff
  have hsum := sum_formalCharacter_coeff_eq_finrank K H M
  rw [Finsupp.sum, Finset.sum_congr rfl hone, Finset.sum_const, nsmul_eq_mul, mul_one] at hsum
  have hcard : Nat.card (MulAction.orbit (IsKilling.rootSystem H).weylGroup lam) =
      (formalCharacter K H M).coeff.support.card := by
    rw [← hsupp, Nat.card_coe_set_eq, Set.ncard_coe_finset]
  rw [hcard]
  exact_mod_cast hsum.symm

end General

section Minuscule

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [IsAlgClosed K]
  [LieRing L] [LieAlgebra K L] [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra]

variable (b : (IsKilling.rootSystem H).Base) (mu : Dual K H)

/-- **A minuscule weight**: a dominant integral weight `mu` all of whose companion weights in
`L(mu)` are Weyl-conjugate to it, so that the weights of `L(mu)` form exactly one Weyl orbit.

This is the condition the roadmap pins, with nothing else bundled into it. In the classical theory
`L(mu)` is nonzero for every dominant integral `mu` — that is the freeness half of
Poincaré--Birkhoff--Witt — and the condition then says the weights of a nonzero module are one
orbit. That nonvanishing is not available here (see
`TauCeti.subsingleton_irreducibleQuotient_iff` and the module docstring), so the condition holds
vacuously at a weight where `L(mu)` vanishes, and the results below are exactly those unaffected
by that. -/
def IsMinuscule : Prop :=
  IsDominantIntegral b mu ∧
    ∀ nu : Dual K H, genWeightSpace (irreducibleQuotient b mu) (nu : H → K) ≠ ⊥ →
      ∃ w : (IsKilling.rootSystem H).weylGroup, w • mu = nu

variable {b mu}

/-- The defining condition on a minuscule weight, matching
`TauCeti.isDominantIntegral_iff` beside it: the body of `TauCeti.IsMinuscule` is not exposed, so
this is how the predicate is introduced from outside this file. -/
theorem isMinuscule_iff :
    IsMinuscule b mu ↔ IsDominantIntegral b mu ∧
      ∀ nu : Dual K H, genWeightSpace (irreducibleQuotient b mu) (nu : H → K) ≠ ⊥ →
        ∃ w : (IsKilling.rootSystem H).weylGroup, w • mu = nu :=
  Iff.rfl

/-- A minuscule weight is dominant integral. -/
theorem IsMinuscule.isDominantIntegral (h : IsMinuscule b mu) : IsDominantIntegral b mu :=
  h.1

/-- Every weight of a minuscule `L(mu)` is Weyl-conjugate to `mu`. -/
theorem IsMinuscule.exists_weylGroup_smul_eq (h : IsMinuscule b mu) {nu : Dual K H}
    (hnu : genWeightSpace (irreducibleQuotient b mu) (nu : H → K) ≠ ⊥) :
    ∃ w : (IsKilling.rootSystem H).weylGroup, w • mu = nu :=
  h.2 nu hnu

/-- **The dimension of a minuscule module is at most the size of the Weyl orbit of its highest
weight.** This is the dimension count of
`TauCeti.finrank_eq_card_orbit_of_isHighestWeightVector` at the named carrier, in the form that
needs no nonvanishing input: when `M(mu) ≠ 0` the canonical generator of `L(mu)` is a highest
weight vector (`TauCeti.isHighestWeightVector_irreducibleQuotientGenerator`) and the general count
applies verbatim, giving equality; and when `M(mu) = 0` the module `L(mu)` vanishes
(`TauCeti.subsingleton_irreducibleQuotient_iff`) and the left side is `0`. The unconditional
equality `dim L(mu) = |W · mu|` is therefore equivalent to that nonvanishing, which is the
Poincaré--Birkhoff--Witt input this repository does not yet have. -/
theorem IsMinuscule.finrank_irreducibleQuotient_le (h : IsMinuscule b mu) :
    finrank K (irreducibleQuotient b mu) ≤
      Nat.card (MulAction.orbit (IsKilling.rootSystem H).weylGroup mu) := by
  have _ := finiteDimensional_irreducibleQuotient_of_isDominantIntegral h.isDominantIntegral
  by_cases h0 : vermaGenerator b mu = 0
  · have _ : Subsingleton (irreducibleQuotient b mu) :=
      (subsingleton_irreducibleQuotient_iff b mu).mpr h0
    rw [finrank_zero_of_subsingleton]
    exact Nat.zero_le _
  · exact le_of_eq (finrank_eq_card_orbit_of_isHighestWeightVector
      (isHighestWeightVector_irreducibleQuotientGenerator b mu h0)
      (lieSpan_irreducibleQuotientGenerator_eq_top b mu) h.2)

end Minuscule

section Zero

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [IsAlgClosed K]
  [LieRing L] [LieAlgebra K L] [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]

/-- **A trivial module has no weight but zero.** The weight spaces of a Cartan subalgebra on a
finite-dimensional module are honest eigenspaces (`TauCeti.genWeightSpace_eq_weightSpace`), and a
nonzero vector on which every element of `H` acts both by zero and by the scalar `chi x` forces
`chi` to vanish. -/
private theorem eq_zero_of_genWeightSpace_ne_bot_of_isTrivial [FiniteDimensional K M]
    [LieModule.IsTrivial L M] {chi : Dual K H}
    (hchi : genWeightSpace M (chi : H → K) ≠ ⊥) : chi = 0 := by
  rw [genWeightSpace_eq_weightSpace, ne_eq, ← LieSubmodule.toSubmodule_eq_bot] at hchi
  obtain ⟨m, hm, hmne⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hchi
  rw [LieSubmodule.mem_toSubmodule] at hm
  refine LinearMap.ext fun x ↦ ?_
  have hx : ⁅x, m⁆ = (chi : H → K) x • m := (mem_weightSpace _ _).mp hm x
  have hx0 : ((chi : H → K) x) • m = 0 := by
    rw [← hx]
    exact LieModule.IsTrivial.trivial (L := L) (x : L) m
  rcases smul_eq_zero.mp hx0 with h | h
  · simpa using h
  · exact absurd h hmne

variable (b : (IsKilling.rootSystem H).Base)

/-- The orbit of the zero weight is the point `{0}`, the Weyl group acting linearly. -/
private theorem orbit_weylGroup_zero :
    MulAction.orbit (IsKilling.rootSystem H).weylGroup (0 : Dual K H) = {0} := by
  ext chi
  rw [MulAction.mem_orbit_iff, Set.mem_singleton_iff]
  exact ⟨fun ⟨w, hw⟩ ↦ by rw [← hw, smul_zero], fun hchi ↦ ⟨1, by rw [hchi, smul_zero]⟩⟩

/-- **The zero weight is minuscule.** Its module `L(0)` is the trivial one-dimensional module, so
its only weight is `0`, which is its own Weyl orbit. Unlike a general dominant integral weight this
needs no Poincaré--Birkhoff--Witt input: `M(0) ≠ 0` holds unconditionally, by
`TauCeti.isHighestWeightVector_vermaGenerator_zero`. This is what keeps `TauCeti.IsMinuscule` from
being an empty condition. -/
theorem isMinuscule_zero : IsMinuscule b (0 : Dual K H) := by
  have h : vermaGenerator b (0 : Dual K H) ≠ 0 :=
    (isHighestWeightVector_vermaGenerator_zero b).ne_zero
  have hw := isHighestWeightVector_irreducibleQuotientGenerator b (0 : Dual K H) h
  have _ := finiteDimensional_irreducibleQuotient_of_isDominantIntegral
    (isDominantIntegral_zero (b := b))
  have _ : LieModule.IsTrivial L (irreducibleQuotient b (0 : Dual K H)) :=
    isTrivial_of_isHighestWeightVector_weight_zero_of_lieSpan_eq_top hw
      (lieSpan_irreducibleQuotientGenerator_eq_top b 0)
  refine ⟨isDominantIntegral_zero, fun nu hnu ↦ ⟨1, ?_⟩⟩
  rw [one_smul, eq_comm]
  exact eq_zero_of_genWeightSpace_ne_bot_of_isTrivial (L := L) hnu

/-- **`L(0)` is one-dimensional.** The zero weight is minuscule and the Weyl group acts linearly,
so its orbit is the point `{0}` and the dimension count of
`TauCeti.finrank_eq_card_orbit_of_isHighestWeightVector` returns `1`. Here the nonvanishing of
`M(0)` is unconditional, so this is the dimension of a minuscule module in full, with nothing
assumed. -/
theorem finrank_irreducibleQuotient_zero :
    finrank K (irreducibleQuotient b (0 : Dual K H)) = 1 := by
  have h : vermaGenerator b (0 : Dual K H) ≠ 0 :=
    (isHighestWeightVector_vermaGenerator_zero b).ne_zero
  have _ := finiteDimensional_irreducibleQuotient_of_isDominantIntegral
    (isDominantIntegral_zero (b := b))
  rw [finrank_eq_card_orbit_of_isHighestWeightVector
    (isHighestWeightVector_irreducibleQuotientGenerator b (0 : Dual K H) h)
    (lieSpan_irreducibleQuotientGenerator_eq_top b 0) (isMinuscule_zero b).2,
    orbit_weylGroup_zero]
  simp

end Zero

end TauCeti
