/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.RingTheory.Finiteness.Ideal
public import Mathlib.Topology.Algebra.Nonarchimedean.Completion
public import TauCeti.RingTheory.Huber.Basic

/-!
# The completion of a Huber ring

The Hausdorff completion `Â` of a Huber ring `A` is again a Huber ring. If `(A₀, I)` is a pair of
definition for `A`, then the closure `Â₀` of the image of `A₀` is an open subring of `Â`, and the
ideal `Î` of `Â₀` generated by the image of `I` is an ideal of definition for it.

Everything rests on one identity: the `n`-th power `Îⁿ` is *exactly* the closure of the image of
`Iⁿ` (`TauCeti.Huber.PairOfDefinition.completionIdeal_pow`). Those closures are a neighbourhood
basis of zero in `Â`, so the identity gives both halves of `IsAdic Î` at once.

The inclusion `Îⁿ ⊆ closure (Iⁿ)` is formal. The reverse inclusion is the substantial point, and
it is the only place where finite generation of `I` is used: fixing a finite family `G` generating
`Iⁿ`, an element of the closure is approximated to order `n + k`, for every `k`, by a combination
of the *same* family `G` with coefficients in `Iᵏ`. The coefficients accumulate to series which
converge because `Â` is complete, and their sums exhibit the element as a combination of `G`.

## Main definitions

* `TauCeti.Huber.PairOfDefinition.completionRingOfDefinition` and
  `TauCeti.Huber.PairOfDefinition.completionIdeal`: the ring and the ideal of definition of `Â`.
* `TauCeti.Huber.PairOfDefinition.completionIdealImage`: the closure in `Â` of the image of `Iⁿ`.
* `TauCeti.Huber.PairOfDefinition.completion`: the pair of definition of `Â` they assemble into.

## Main results

* `TauCeti.Huber.isOpen_topologicalClosure_map_coeRingHom`: the closure of the image of an open
  subring of `A` is open in `Â`.
* `TauCeti.Huber.PairOfDefinition.hasBasis_nhds_zero_completion`: the closures of the images of
  the powers `Iⁿ` are a neighbourhood basis of zero in `Â`.
* `TauCeti.Huber.PairOfDefinition.completionIdeal_pow`: `Îⁿ` is the closure of the image of `Iⁿ`.
* `TauCeti.Huber.IsHuberRing.completion`: the completion of a Huber ring is a Huber ring, and
  `TauCeti.Huber.IsTateRing.completion`: the completion of a Tate ring is a Tate ring.
* `TauCeti.Huber.ker_coeRingHom`: the kernel of `A → Â` is the closure of the zero ideal.

## References

* [Wedhorn, *Adic Spaces*][wedhorn_adic], Remark 6.8.
-/

@[expose] public section

open Filter Topology UniformSpace

namespace TauCeti.Huber

section SpanMul

variable {R : Type*} [CommRing R]

/-- The `K`-linear combinations of a fixed finite family `G`, as an ideal of `R`. -/
private def sumIdeal (G : Finset R) (K : Ideal R) : Ideal R where
  carrier := {b | ∃ c : R → R, (∀ z, c z ∈ K) ∧ ∑ z ∈ G, z * c z = b}
  add_mem' := by
    rintro _ _ ⟨c₁, hc₁, rfl⟩ ⟨c₂, hc₂, rfl⟩
    exact ⟨c₁ + c₂, fun z ↦ K.add_mem (hc₁ z) (hc₂ z), by
      simp [mul_add, Finset.sum_add_distrib]⟩
  zero_mem' := ⟨0, fun _ ↦ K.zero_mem, by simp⟩
  smul_mem' r := by
    rintro _ ⟨c, hc, rfl⟩
    exact ⟨fun z ↦ r * c z, fun z ↦ K.mul_mem_left _ (hc z), by
      simp [Finset.mul_sum, mul_left_comm, smul_eq_mul]⟩

/-- An element of `(G) * K` is a `K`-linear combination of the finite family `G`.

This is where finite generation of the ideal of definition enters the proof of Wedhorn Remark
6.8: it bounds, uniformly in `k`, the number of terms needed to write an element of
`Iⁿ⁺ᵏ = Iⁿ * Iᵏ` over generators of `Iⁿ`. -/
private theorem exists_sum_eq_of_mem_span_mul (G : Finset R) (K : Ideal R) {b : R}
    (hb : b ∈ Ideal.span (G : Set R) * K) :
    ∃ c : R → R, (∀ z, c z ∈ K) ∧ ∑ z ∈ G, z * c z = b := by
  classical
  suffices h : Ideal.span (G : Set R) * K ≤ sumIdeal G K from h hb
  refine Ideal.mul_le.mpr fun u hu v hv ↦ ?_
  induction hu using Submodule.span_induction with
  | mem z hz => exact ⟨fun w ↦ if w = z then v else 0, fun w ↦ by
      by_cases h : w = z <;> simp [h, hv, K.zero_mem], by
        simp [mul_ite, Finset.mem_coe.mp hz]⟩
  | zero => rw [zero_mul]; exact (sumIdeal G K).zero_mem
  | add p q _ _ hp hq => rw [add_mul]; exact (sumIdeal G K).add_mem hp hq
  | smul a p _ hp => rw [smul_eq_mul, mul_assoc]; exact (sumIdeal G K).mul_mem_left a hp

end SpanMul

variable {A : Type*} [CommRing A] [UniformSpace A] [IsUniformAddGroup A] [IsTopologicalRing A]

/-- The closure in `Â` of the image of an open additive subgroup of `A` is open: it is a subgroup,
and it is a neighbourhood of zero because `A → Â` is dense inducing. -/
private theorem isOpen_closure_image_coe {G : AddSubgroup A} (hG : IsOpen (G : Set A)) :
    IsOpen (closure (((↑) : A → Completion A) '' (G : Set A))) := by
  have hmem := Completion.isDenseInducing_coe.closure_image_mem_nhds (hG.mem_nhds G.zero_mem)
  rw [Completion.coe_zero] at hmem
  exact AddSubgroup.isOpen_of_mem_nhds ((G.map Completion.toCompl).topologicalClosure) hmem

/-- The closure in `Â` of the image of an open subring of `A` is an open subring. This is the
first step of Wedhorn Remark 6.8: it produces the ring of definition of the completion. -/
theorem isOpen_topologicalClosure_map_coeRingHom {S : Subring A} (hS : IsOpen (S : Set A)) :
    IsOpen (((S.map (Completion.coeRingHom)).topologicalClosure :
      Subring (Completion A)) : Set (Completion A)) :=
  isOpen_closure_image_coe (G := S.toAddSubgroup) hS

namespace PairOfDefinition

/-- The ring of definition of the completion: the closure in `Â` of the image of `A₀`. -/
noncomputable def completionRingOfDefinition (P : PairOfDefinition A) :
    Subring (Completion A) :=
  (P.ringOfDefinition.map Completion.coeRingHom).topologicalClosure

/-- The ring of definition of the completion is open. -/
theorem isOpen_completionRingOfDefinition (P : PairOfDefinition A) :
    IsOpen (P.completionRingOfDefinition : Set (Completion A)) :=
  isOpen_topologicalClosure_map_coeRingHom P.isOpen_ringOfDefinition

/-- The closure in `Â` of the image of `Iⁿ`, as an additive subgroup. These closures are the
neighbourhood basis of zero of the completion, and they turn out to be the powers of the ideal of
definition of the completion (`completionIdeal_pow`). -/
noncomputable def completionIdealImage (P : PairOfDefinition A) (n : ℕ) :
    AddSubgroup (Completion A) :=
  ((P.idealImage n).map Completion.toCompl).topologicalClosure

/-- `completionIdealImage` is the closure of the image of `Iⁿ`, by definition. -/
theorem coe_completionIdealImage (P : PairOfDefinition A) (n : ℕ) :
    (P.completionIdealImage n : Set (Completion A))
      = closure (((↑) : A → Completion A) '' (P.idealImage n : Set A)) := rfl

/-- The closure of the image of `Iⁿ` is open in `Â`. -/
theorem isOpen_completionIdealImage (P : PairOfDefinition A) (n : ℕ) :
    IsOpen (P.completionIdealImage n : Set (Completion A)) :=
  isOpen_closure_image_coe (P.isOpen_idealImage n)

/-- The image of `Iⁿ` lies in its closure. -/
theorem coe_mem_completionIdealImage (P : PairOfDefinition A) {n : ℕ} {a : A}
    (ha : a ∈ P.idealImage n) : (a : Completion A) ∈ P.completionIdealImage n :=
  subset_closure ⟨a, ha, rfl⟩

/-- The closures of the images of the `Iⁿ` decrease with `n`. -/
theorem completionIdealImage_mono (P : PairOfDefinition A) {m n : ℕ} (h : m ≤ n) :
    P.completionIdealImage n ≤ P.completionIdealImage m := by
  refine fun x hx ↦ closure_mono (Set.image_mono ?_) hx
  exact Set.image_mono fun z hz ↦ Ideal.pow_le_pow_right h hz

/-- The closure of the image of `Iⁿ` lies in the ring of definition of the completion. -/
theorem completionIdealImage_le (P : PairOfDefinition A) (n : ℕ) :
    (P.completionIdealImage n : Set (Completion A))
      ⊆ (P.completionRingOfDefinition : Set (Completion A)) := by
  refine closure_mono (Set.image_mono ?_)
  rintro _ ⟨z, -, rfl⟩
  exact z.2

/-- Wedhorn Remark 6.8: the closures of the images of the powers of the ideal of definition are a
neighbourhood basis of zero in the completion.

Cofinality uses that `Â` is a regular space, so a neighbourhood of zero contains a closed one,
whose preimage in `A` then contains some `Iⁿ`. -/
theorem hasBasis_nhds_zero_completion (P : PairOfDefinition A) :
    (𝓝 (0 : Completion A)).HasBasis (fun _ : ℕ ↦ True)
      fun n ↦ (P.completionIdealImage n : Set (Completion A)) := by
  refine Filter.hasBasis_iff.mpr fun U ↦ ⟨fun hU ↦ ?_, ?_⟩
  · obtain ⟨C, ⟨hC, hCclosed⟩, hCU⟩ := (closed_nhds_basis (0 : Completion A)).mem_iff.mp hU
    have hpre : ((↑) : A → Completion A) ⁻¹' C ∈ 𝓝 (0 : A) :=
      (Completion.continuous_coe A).continuousAt.preimage_mem_nhds (by rwa [Completion.coe_zero])
    obtain ⟨n, -, hn⟩ := P.hasBasis_nhds_zero.mem_iff.mp hpre
    refine ⟨n, trivial, fun x hx ↦ hCU ?_⟩
    have hx' : x ∈ closure C := closure_mono (Set.image_subset_iff.mpr hn) hx
    rwa [hCclosed.closure_eq] at hx'
  · rintro ⟨n, -, hn⟩
    exact Filter.mem_of_superset
      ((P.isOpen_completionIdealImage n).mem_nhds (P.completionIdealImage n).zero_mem) hn

/-- The closure of the image of `Iⁿ` absorbs multiplication by the ring of definition of the
completion, because `Iⁿ` is an ideal of `A₀` and multiplication is continuous. -/
theorem mul_mem_completionIdealImage (P : PairOfDefinition A) {n : ℕ} {t y : Completion A}
    (ht : t ∈ P.completionRingOfDefinition) (hy : y ∈ P.completionIdealImage n) :
    t * y ∈ P.completionIdealImage n := by
  have key : ∀ a ∈ P.idealImage n, t * (a : Completion A) ∈ P.completionIdealImage n := by
    intro a ha
    rw [← SetLike.mem_coe, P.coe_idealImage] at ha
    obtain ⟨b, hb, rfl⟩ := ha
    have h1 : t * ((b : A) : Completion A) ∈
        closure ((fun u : Completion A ↦ u * ((b : A) : Completion A)) ''
          (((↑) : A → Completion A) '' (P.ringOfDefinition : Set A))) :=
      image_closure_subset_closure_image (by fun_prop) ⟨t, ht, rfl⟩
    refine closure_mono ?_ h1
    rintro _ ⟨_, ⟨s, hs, rfl⟩, rfl⟩
    exact ⟨s * (b : A), ⟨⟨s, hs⟩ * b, Ideal.mul_mem_left _ _ hb, rfl⟩,
      Completion.coe_mul s (b : A)⟩
  have h2 : t * y ∈ closure ((fun u : Completion A ↦ t * u) ''
      (((↑) : A → Completion A) '' (P.idealImage n : Set A))) :=
    image_closure_subset_closure_image (by fun_prop) ⟨y, hy, rfl⟩
  refine closure_minimal ?_ isClosed_closure h2
  rintro _ ⟨_, ⟨a, ha, rfl⟩, rfl⟩
  exact key a ha

/-- The closure of the image of `Iⁿ`, viewed as an ideal of the ring of definition of the
completion. -/
noncomputable def completionIdealImageIdeal (P : PairOfDefinition A) (n : ℕ) :
    Ideal P.completionRingOfDefinition where
  carrier := {y | (y : Completion A) ∈ P.completionIdealImage n}
  add_mem' hx hy := by simpa using AddSubgroup.add_mem _ hx hy
  zero_mem' := (P.completionIdealImage n).zero_mem
  smul_mem' c x hx := by simpa [smul_eq_mul] using P.mul_mem_completionIdealImage c.2 hx

/-- The completion map, restricted to a ring of definition and corestricted to the ring of
definition of the completion. -/
noncomputable def toCompletionRingOfDefinition (P : PairOfDefinition A) :
    P.ringOfDefinition →+* P.completionRingOfDefinition :=
  (Completion.coeRingHom.comp P.ringOfDefinition.subtype).codRestrict _ fun x ↦
    Subring.le_topologicalClosure _ ⟨x, x.2, rfl⟩

/-- The corestricted completion map agrees with the completion map on `A₀`. -/
@[simp] theorem coe_toCompletionRingOfDefinition (P : PairOfDefinition A)
    (x : P.ringOfDefinition) : (P.toCompletionRingOfDefinition x : Completion A) = (x : A) := rfl

/-- The ideal of definition of the completion: the ideal of `Â₀` generated by the image of `I`. -/
noncomputable def completionIdeal (P : PairOfDefinition A) :
    Ideal P.completionRingOfDefinition :=
  P.ideal.map P.toCompletionRingOfDefinition

/-- The ideal of definition of the completion is finitely generated. -/
theorem fg_completionIdeal (P : PairOfDefinition A) : P.completionIdeal.FG :=
  P.fg_ideal.map _

/-- The formal half of `completionIdeal_pow`: `Îⁿ` is generated by the image of `Iⁿ`, which lies
in its closure. -/
private theorem completionIdeal_pow_le (P : PairOfDefinition A) (n : ℕ) :
    P.completionIdeal ^ n ≤ P.completionIdealImageIdeal n := by
  rw [completionIdeal, ← Ideal.map_pow, Ideal.map_le_iff_le_comap]
  intro x hx
  exact P.coe_mem_completionIdealImage (a := (x : A)) ⟨x, hx, rfl⟩

/-- A finite `A₀`-combination of elements of `A₀` maps to the corresponding combination in `Â`. -/
private theorem coe_sum_mul (P : PairOfDefinition A) (G : Finset P.ringOfDefinition)
    (c : P.ringOfDefinition → P.ringOfDefinition) :
    ∑ z ∈ G, ((z : A) : Completion A) * ((c z : A) : Completion A)
      = (((∑ z ∈ G, z * c z : P.ringOfDefinition) : A) : Completion A) := by
  classical
  induction G using Finset.induction with
  | empty => simp [Completion.coe_zero]
  | insert z G' hz ih =>
      rw [Finset.sum_insert hz, Finset.sum_insert hz, ih, Subring.coe_add, Completion.coe_add,
        Subring.coe_mul, Completion.coe_mul]

/-- One step of the successive approximation behind Wedhorn Remark 6.8: an element of the closure
of the image of `Iⁿ⁺ᵏ` agrees, modulo the closure of the image of `Iⁿ⁺ᵏ⁺¹`, with a combination of
the fixed generators `G` of `Iⁿ` whose coefficients lie in `Iᵏ`.

The statement is unconditional in `x` — the conclusion is guarded by the hypothesis instead — so
that the coefficients can be chosen simultaneously for all `x` and iterated. -/
private theorem exists_sub_sum_mem (P : PairOfDefinition A) {n : ℕ}
    (G : Finset P.ringOfDefinition) (hG : Ideal.span (G : Set P.ringOfDefinition) = P.ideal ^ n)
    (k : ℕ) (x : Completion A) :
    ∃ c : P.ringOfDefinition → P.ringOfDefinition, (∀ z, c z ∈ P.ideal ^ k) ∧
      (x ∈ P.completionIdealImage (n + k) →
        x - ∑ z ∈ G, ((z : A) : Completion A) * ((c z : A) : Completion A)
          ∈ P.completionIdealImage (n + k + 1)) := by
  by_cases hx : x ∈ P.completionIdealImage (n + k)
  · have hVopen : IsOpen ((fun w : Completion A ↦ w - x) ⁻¹'
        (P.completionIdealImage (n + k + 1) : Set (Completion A))) :=
      (P.isOpen_completionIdealImage _).preimage (by fun_prop)
    have hxV : x ∈ (fun w : Completion A ↦ w - x) ⁻¹'
        (P.completionIdealImage (n + k + 1) : Set (Completion A)) := by simp
    rw [← SetLike.mem_coe, P.coe_completionIdealImage] at hx
    obtain ⟨w, hwV, a, ha, rfl⟩ := mem_closure_iff_nhds.mp hx _ (hVopen.mem_nhds hxV)
    rw [P.coe_idealImage] at ha
    obtain ⟨b, hb, rfl⟩ := ha
    have hb' : b ∈ Ideal.span (G : Set P.ringOfDefinition) * P.ideal ^ k := by
      rw [hG, ← pow_add]; exact hb
    obtain ⟨c, hc, hcsum⟩ := exists_sum_eq_of_mem_span_mul G (P.ideal ^ k) hb'
    refine ⟨c, hc, fun _ ↦ ?_⟩
    rw [P.coe_sum_mul, hcsum, ← neg_sub]
    exact (P.completionIdealImage (n + k + 1)).neg_mem hwV
  · exact ⟨0, fun _ ↦ Ideal.zero_mem _, fun h ↦ absurd h hx⟩

/-- Partial sums whose `k`-th term lies in the image of `Iᵏ` are a Cauchy sequence in `Â`: past
the `j`-th term every increment stays inside the subgroup `completionIdealImage j`. -/
private theorem cauchySeq_sum_coe (P : PairOfDefinition A) (d : ℕ → A)
    (hd : ∀ k, d k ∈ P.idealImage k) :
    CauchySeq fun m ↦ ∑ k ∈ Finset.range m, ((d k : A) : Completion A) := by
  have hsub : ∀ j m, j ≤ m → (∑ k ∈ Finset.range m, ((d k : A) : Completion A))
      - ∑ k ∈ Finset.range j, ((d k : A) : Completion A) ∈ P.completionIdealImage j := by
    intro j m hjm
    induction m, hjm using Nat.le_induction with
    | base => simp
    | succ m hjm ih =>
        rw [Finset.sum_range_succ, add_sub_right_comm]
        exact (P.completionIdealImage j).add_mem ih
          (P.completionIdealImage_mono hjm (P.coe_mem_completionIdealImage (hd m)))
  refine P.hasBasis_nhds_zero_completion.uniformity_of_nhds_zero.cauchySeq_iff.mpr fun j _ ↦ ?_
  refine ⟨j, fun m hm p hp ↦ ?_⟩
  have h := (P.completionIdealImage j).sub_mem (hsub j p hp) (hsub j m hm)
  rw [sub_sub_sub_cancel_right] at h
  exact h

/-- Iterating `exists_sub_sum_mem` along an element `x` of the closure of the image of `Iⁿ`:
coefficients `d k z ∈ Iᵏ` and errors `u k` in the closure of the image of `Iⁿ⁺ᵏ` with
`x - u m = ∑_{z ∈ G} z * ∑_{k < m} d k z`. -/
private theorem exists_approx_seq (P : PairOfDefinition A) {n : ℕ}
    (G : Finset P.ringOfDefinition) (hG : Ideal.span (G : Set P.ringOfDefinition) = P.ideal ^ n)
    {x : Completion A} (hx : x ∈ P.completionIdealImage n) :
    ∃ (d : ℕ → P.ringOfDefinition → P.ringOfDefinition) (u : ℕ → Completion A),
      (∀ k z, d k z ∈ P.ideal ^ k) ∧ (∀ k, u k ∈ P.completionIdealImage (n + k)) ∧
        ∀ m, x - u m = ∑ z ∈ G, ((z : A) : Completion A)
          * ∑ k ∈ Finset.range m, ((d k z : A) : Completion A) := by
  choose c hc1 hc2 using P.exists_sub_sum_mem G hG
  obtain ⟨u, hu0, hurec⟩ : ∃ u : ℕ → Completion A, u 0 = x ∧ ∀ k,
      u (k + 1) = u k - ∑ z ∈ G, ((z : A) : Completion A) * ((c k (u k) z : A) : Completion A) :=
    ⟨fun m ↦ Nat.rec (motive := fun _ ↦ Completion A) x
      (fun k v ↦ v - ∑ z ∈ G, ((z : A) : Completion A) * ((c k v z : A) : Completion A)) m,
      rfl, fun _ ↦ rfl⟩
  have huK : ∀ k, u k ∈ P.completionIdealImage (n + k) := by
    intro k
    induction k with
    | zero => rw [hu0]; exact hx
    | succ k ih => rw [hurec k]; exact hc2 k (u k) ih
  refine ⟨fun k ↦ c k (u k), u, fun k z ↦ hc1 k (u k) z, huK, fun m ↦ ?_⟩
  induction m with
  | zero => simp [hu0]
  | succ m ih =>
      have hstep : x - u (m + 1) = (x - u m)
          + ∑ z ∈ G, ((z : A) : Completion A) * ((c m (u m) z : A) : Completion A) := by
        rw [hurec m]; ring
      rw [hstep, ih, ← Finset.sum_add_distrib]
      exact Finset.sum_congr rfl fun z _ ↦ by rw [Finset.sum_range_succ, mul_add]

/-- The substantial half of Wedhorn Remark 6.8: the closure of the image of `Iⁿ` is contained in
`Îⁿ`.

Fix a finite family `G` generating `Iⁿ`. By `exists_approx_seq`, an element `x` of the closure is
`∑_{z ∈ G} z * ∑_{k < m} d k z` up to an error tending to zero, with `d k z ∈ Iᵏ`. For each `z`
the series `∑ₖ d k z` is Cauchy, hence converges in `Â` to an element of `Â₀`, and `x` is the
corresponding combination of `G`. -/
private theorem completionIdealImageIdeal_le (P : PairOfDefinition A) (n : ℕ) :
    P.completionIdealImageIdeal n ≤ P.completionIdeal ^ n := by
  classical
  obtain ⟨G, hG⟩ := P.fg_ideal.pow (n := n)
  intro y hy
  obtain ⟨d, u, hd, huK, hpartial⟩ := P.exists_approx_seq G hG hy
  have hcauchy : ∀ z : P.ringOfDefinition, CauchySeq fun m ↦ ∑ k ∈ Finset.range m,
      ((d k z : A) : Completion A) :=
    fun z ↦ P.cauchySeq_sum_coe _ fun k ↦ ⟨d k z, hd k z, rfl⟩
  choose L hL using fun z ↦ cauchySeq_tendsto_of_complete (hcauchy z)
  have hLmem : ∀ z, L z ∈ P.completionRingOfDefinition := fun z ↦
    (Subring.isClosed_topologicalClosure _).mem_of_tendsto (hL z) (.of_forall fun m ↦
      Subring.sum_mem _ fun k _ ↦ Subring.le_topologicalClosure _
        ⟨((d k z : P.ringOfDefinition) : A), (d k z).2, rfl⟩)
  have hulim : Tendsto u atTop (𝓝 0) := by
    refine P.hasBasis_nhds_zero_completion.tendsto_right_iff.mpr fun j _ ↦ ?_
    filter_upwards [eventually_ge_atTop j] with k hk
    exact P.completionIdealImage_mono (hk.trans (Nat.le_add_left k n)) (huK k)
  have hyeq : (y : Completion A) = ∑ z ∈ G, ((z : A) : Completion A) * L z := by
    have h := tendsto_nhds_unique
      (((tendsto_const_nhds (x := (y : Completion A))).sub hulim).congr hpartial)
      (tendsto_finsetSum G fun z _ ↦ (hL z).const_mul _)
    rwa [sub_zero] at h
  have hsum : y = ∑ z ∈ G, P.toCompletionRingOfDefinition z
      * (⟨L z, hLmem z⟩ : P.completionRingOfDefinition) := by
    apply Subtype.ext
    push_cast
    exact hyeq
  rw [hsum]
  refine Submodule.sum_mem _ fun z hz ↦ Ideal.mul_mem_right _ _ ?_
  rw [completionIdeal, ← Ideal.map_pow]
  exact Ideal.mem_map_of_mem _ (hG ▸ Ideal.subset_span (Finset.mem_coe.mpr hz))

/-- Wedhorn Remark 6.8: the `n`-th power of the ideal of definition of the completion is exactly
the closure of the image of `Iⁿ`. -/
theorem completionIdeal_pow (P : PairOfDefinition A) (n : ℕ) :
    P.completionIdeal ^ n = P.completionIdealImageIdeal n :=
  le_antisymm (P.completionIdeal_pow_le n) (P.completionIdealImageIdeal_le n)

/-- Wedhorn Remark 6.8: the subspace topology on the ring of definition of the completion is the
adic topology of the ideal of definition of the completion. -/
theorem isAdic_completionIdeal (P : PairOfDefinition A) : IsAdic P.completionIdeal := by
  refine isAdic_iff.mpr ⟨fun n ↦ ?_, fun s hs ↦ ?_⟩
  · rw [P.completionIdeal_pow]
    exact (P.isOpen_completionIdealImage n).preimage continuous_subtype_val
  · rw [mem_nhds_subtype] at hs
    obtain ⟨V, hV, hVs⟩ := hs
    obtain ⟨n, -, hn⟩ := P.hasBasis_nhds_zero_completion.mem_iff.mp hV
    exact ⟨n, by rw [P.completionIdeal_pow]; exact (Set.preimage_mono hn).trans hVs⟩

/-- Wedhorn Remark 6.8: a pair of definition of `A` induces one of the completion of `A`, with the
closure of the image of `A₀` as ring of definition and the ideal generated by the image of `I` as
ideal of definition. -/
noncomputable def completion (P : PairOfDefinition A) : PairOfDefinition (Completion A) where
  ringOfDefinition := P.completionRingOfDefinition
  isOpen_ringOfDefinition := P.isOpen_completionRingOfDefinition
  ideal := P.completionIdeal
  fg_ideal := P.fg_completionIdeal
  isAdic_ideal := P.isAdic_completionIdeal

end PairOfDefinition

/-- Wedhorn Remark 6.8: the completion of a Huber ring is a Huber ring. -/
instance IsHuberRing.completion [IsHuberRing A] : IsHuberRing (Completion A) :=
  ⟨IsHuberRing.nonempty_pairOfDefinition.elim fun P ↦ ⟨P.completion⟩⟩

/-- Wedhorn Remark 6.8: the completion of a Tate ring is a Tate ring, the image of a
pseudouniformiser being one. -/
instance IsTateRing.completion [IsTateRing A] : IsTateRing (Completion A) where
  exists_isPseudoUniformizer := by
    obtain ⟨a, ha, hnil⟩ := IsTateRing.exists_isPseudoUniformizer (A := A)
    exact ⟨(a : Completion A), ha.map Completion.coeRingHom,
      hnil.map Completion.continuous_coeRingHom⟩

/-- The kernel of the completion map `A → Â` is the closure of the zero ideal: two elements of `A`
have the same image in `Â` exactly when they are topologically indistinguishable. In particular
the completion map is injective precisely when `A` is separated. -/
theorem ker_coeRingHom :
    RingHom.ker (Completion.coeRingHom : A →+* Completion A) = (⊥ : Ideal A).closure := by
  ext x
  rw [RingHom.mem_ker, ← SetLike.mem_coe, Ideal.coe_closure]
  calc (Completion.coeRingHom x = 0)
      ↔ ((x : Completion A) = ((0 : A) : Completion A)) := by rw [Completion.coe_zero]; rfl
    _ ↔ Inseparable ((x : Completion A)) (((0 : A) : Completion A)) := inseparable_iff_eq.symm
    _ ↔ Inseparable x (0 : A) := Completion.isDenseInducing_coe.isInducing.inseparable_iff
    _ ↔ x - 0 ∈ closure ({0} : Set A) := addGroup_inseparable_iff
    _ ↔ x ∈ closure ((⊥ : Ideal A) : Set A) := by rw [sub_zero]; simp

end TauCeti.Huber
