/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.E6.Minuscule.PositiveSubsystem.Basic
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Subsystem.BaseChange
public import TauCeti.Algebra.AlgebraicGroup.AdditiveGroup.CoordinateBaseChange
public import TauCeti.Algebra.AlgebraicGroup.DiagonalizableGroup.BaseChange
public import TauCeti.AlgebraicGeometry.AffineGroupScheme.BaseChange.Coordinate

/-!
# Base change of the positive E6 minuscule subsystem

The positive subsystem of the integral type-`E₆` minuscule carrier is generated by its six
positive simple-root subgroups and its weight torus. This file transports that coordinate
presentation along `ℤ → A` for an arbitrary commutative ring `A`.

The resulting quotient coordinate Hopf algebra is canonically the scalar extension of the
integral positive subsystem. The factored positive root-subgroup maps and weight-torus map are
transported through the same comparison, so the carrier and the data intended for its pinning
base-change together.

## Main definitions

* `TauCeti.E6Minuscule.positiveRootSubgroupIntegralCoordinateMap` and
  `TauCeti.E6Minuscule.positiveWeightTorusIntegralCoordinateMap`: the integral factored
  generator maps.
* `TauCeti.E6Minuscule.positiveSubsystemBaseChangeGroupScheme`: the scheme-theoretic base change
  of the integral positive subsystem.
* `TauCeti.E6Minuscule.positiveSubsystemBaseChangePresentationIso`: its identification with the
  generic transported quotient presentation.
* `TauCeti.E6Minuscule.positiveRootSubgroupBaseChange` and
  `TauCeti.E6Minuscule.positiveWeightTorusBaseChange`: the base changes of the integral pinning
  morphisms.

## References

* The type-`E₇` base-change construction in
  `TauCeti.Algebra.Lie.E7.Minuscule.PositiveSubsystem.BaseChange` for the interface specialized
  here.
* R. W. Carter, *Simple Groups of Lie Type*, §4.4.
* B. Conrad, *Reductive Group Schemes*, §1.
-/

public section

open CategoryTheory
open TauCeti.DynkinType
open TauCeti.UniversalEnvelopingAlgebra

namespace TauCeti.E6Minuscule

universe v

noncomputable section

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

local notation "CM" => weightTable.cartanMatrix
local notation "rootGen" => TauCeti.serreRootGenerator CM
local notation "cartanGen" => TauCeti.serreH ℚ CM
local notation "Λ" => TauCeti.coordinateLattice (Fin 27)
local notation "𝒷" => TauCeti.coordinateLatticeBasis (Fin 27)

variable (A : Type v) [CommRing A]

/-- The coordinate Hopf algebra of the integral positive subsystem, in its generated-subsystem
presentation. -/
public noncomputable abbrev positiveSubsystemCoordinateHopfAlgebra :=
  CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ 27)
    (kostantTorusSubsystemDefiningIdeal rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
      weightTable.rep_kostantForm_mem_lattice 𝒷 weightTable.weight positiveSimpleRoots
      (fun i => weightTable.isNilpotent_rep_serreRootGenerator i.1))

/-- The generated-subsystem presentation uses the named positive-subsystem defining ideal. -/
theorem positiveSubsystemCoordinateHopfAlgebra_eq :
    positiveSubsystemCoordinateHopfAlgebra =
      CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ 27)
        positiveSubsystemDefiningIdeal := by
  rw [positiveSubsystemDefiningIdeal_def]

/-! ## Positive simple-root subgroups -/

/-- The coordinate map of the `i`th positive simple-root subgroup factored through the integral
positive subsystem. -/
noncomputable def positiveRootSubgroupIntegralCoordinateMap (i : Fin 6) :
    positiveSubsystemCoordinateHopfAlgebra ⟶ AdditiveGroup.coordinateHopfAlgebra ℤ :=
  kostantRootSubgroupTorusSubsystemCoordinateMap rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
    weightTable.rep_kostantForm_mem_lattice 𝒷 weightTable.weight positiveSimpleRoots
    (fun k => weightTable.isNilpotent_rep_serreRootGenerator k.1) (inl_mem_positiveSimpleRoots i)

/-- The integral factored positive root-subgroup map recovers its represented coordinate map in
`GL₂₇`. -/
@[simp]
theorem mkQuotient_comp_positiveRootSubgroupIntegralCoordinateMap (i : Fin 6) :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ 27)
          (kostantTorusSubsystemDefiningIdeal rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
            weightTable.rep_kostantForm_mem_lattice 𝒷 weightTable.weight positiveSimpleRoots
            (fun k => weightTable.isNilpotent_rep_serreRootGenerator k.1)) ≫
        positiveRootSubgroupIntegralCoordinateMap i =
      kostantRootSubgroupCoordinateMap rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
        weightTable.rep_kostantForm_mem_lattice (.inl i)
        (weightTable.isNilpotent_rep_serreRootGenerator (.inl i)) 𝒷 :=
  mkQuotient_comp_kostantRootSubgroupTorusSubsystemCoordinateMap rootGen cartanGen weightTable.rep
    (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝒷 weightTable.weight
    positiveSimpleRoots (fun k => weightTable.isNilpotent_rep_serreRootGenerator k.1)
    (inl_mem_positiveSimpleRoots i)

/-- The integral factored coordinate map represents the existing `i`th positive simple-root
subgroup of the positive subsystem. -/
theorem hopfSpec_map_positiveRootSubgroupIntegralCoordinateMap_op (i : Fin 6) :
    (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
        (positiveRootSubgroupIntegralCoordinateMap i).op =
      eqToHom (AdditiveGroup.groupScheme_def ℤ).symm ≫
        positiveRootSubgroup i ≫ eqToHom positiveSubsystemGroupScheme_def := by
  rw [positiveRootSubgroupIntegralCoordinateMap, positiveRootSubgroup_def,
    kostantRootSubgroupToTorusSubsystem_def]
  simp

/-! ## The positive weight torus -/

/-- The coordinate map of the weight torus factored through the integral positive subsystem. -/
noncomputable def positiveWeightTorusIntegralCoordinateMap :
    positiveSubsystemCoordinateHopfAlgebra ⟶
      (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup (Fin 6))).obj :=
  kostantWeightTorusTorusSubsystemCoordinateMap rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
    weightTable.rep_kostantForm_mem_lattice 𝒷 weightTable.weight positiveSimpleRoots
    (fun k => weightTable.isNilpotent_rep_serreRootGenerator k.1)

/-- The integral factored positive weight-torus map recovers its represented coordinate map in
`GL₂₇`. -/
@[simp]
theorem mkQuotient_comp_positiveWeightTorusIntegralCoordinateMap :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ 27)
          (kostantTorusSubsystemDefiningIdeal rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
            weightTable.rep_kostantForm_mem_lattice 𝒷 weightTable.weight positiveSimpleRoots
            (fun k => weightTable.isNilpotent_rep_serreRootGenerator k.1)) ≫
        positiveWeightTorusIntegralCoordinateMap =
      GeneralLinear.weightTorusCoordinateMap weightTable.weight :=
  mkQuotient_comp_kostantWeightTorusTorusSubsystemCoordinateMap rootGen cartanGen weightTable.rep
    (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝒷 weightTable.weight
    positiveSimpleRoots (fun k => weightTable.isNilpotent_rep_serreRootGenerator k.1)

/-- The integral factored coordinate map represents the existing weight torus of the positive
subsystem. -/
theorem hopfSpec_map_positiveWeightTorusIntegralCoordinateMap_op :
    (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
        positiveWeightTorusIntegralCoordinateMap.op =
      eqToHom (DiagonalizableGroup.groupScheme_def ℤ
          (SplitTorus.characterGroup (Fin 6))).symm ≫
        positiveWeightTorus ≫ eqToHom positiveSubsystemGroupScheme_def := by
  rw [positiveWeightTorusIntegralCoordinateMap, positiveWeightTorus_def,
    kostantWeightTorusToTorusSubsystem_def]
  simp

end

/-! ## Scheme morphisms over the new base -/

noncomputable section

-- The current `hopfSpec` bridge requires the base ring and all coordinate rings to inhabit the
-- same universe. The concrete pinning uses `Fin 6` and `Fin 27`, so its scheme-level packaging is
-- correspondingly stated in the base universe; the coordinate-level API above remains universe
-- polymorphic.
variable (B : Type) [CommRing B]

local notation "rootGen" => TauCeti.serreRootGenerator weightTable.cartanMatrix
local notation "cartanGen" => TauCeti.serreH ℚ weightTable.cartanMatrix
local notation "Λ" => TauCeti.coordinateLattice (Fin 27)
local notation "𝒷" => TauCeti.coordinateLatticeBasis (Fin 27)

/-- The scheme-theoretic base change of the integral positive subsystem to `B`. -/
noncomputable abbrev positiveSubsystemBaseChangeGroupScheme :
    Grp (Over (AlgebraicGeometry.Spec (CommRingCat.of B))) :=
  (Over.pullback (AlgebraicGeometry.Spec.map
    (CommRingCat.ofHom (algebraMap ℤ B)))).mapGrp.obj positiveSubsystemGroupScheme

/-- The generic transported quotient presentation of the positive subsystem over `B`. -/
noncomputable abbrev positiveSubsystemBaseChangePresentation :
    Grp (Over (AlgebraicGeometry.Spec (CommRingCat.of B))) :=
  CommHopfAlgCat.quotientSpec
    (CommHopfAlgCat.baseChange (K := B) (GeneralLinear.coordinateHopfAlgebra ℤ 27))
    (kostantTorusSubsystemBaseChangeIdeal rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
      weightTable.rep_kostantForm_mem_lattice 𝒷 weightTable.weight positiveSimpleRoots
      (fun i => weightTable.isNilpotent_rep_serreRootGenerator i.1) B)

/-- The scheme-theoretic base change of the positive subsystem is represented by the generic
transported quotient presentation. -/
noncomputable def positiveSubsystemBaseChangePresentationIso :
    positiveSubsystemBaseChangeGroupScheme B ≅ positiveSubsystemBaseChangePresentation B :=
  (Over.pullback (AlgebraicGeometry.Spec.map
      (CommRingCat.ofHom (algebraMap ℤ B)))).mapGrp.mapIso
      (eqToIso positiveSubsystemGroupScheme_def) ≪≫
    AffineGroupSchemeCat.hopfSpecBaseChangeGrpIso positiveSubsystemCoordinateHopfAlgebra ≪≫
    (AlgebraicGeometry.hopfSpec (CommRingCat.of B)).mapIso
      (kostantTorusSubsystemBaseChangeIso rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
        weightTable.rep_kostantForm_mem_lattice 𝒷 weightTable.weight positiveSimpleRoots
        (fun i => weightTable.isNilpotent_rep_serreRootGenerator i.1) B).op

/-- The canonical comparison from the scheme-theoretic base change of the integral additive group
to the additive group constructed over `B`. -/
noncomputable def positiveRootSubgroupDomainBaseChangeIso :
    (Over.pullback (AlgebraicGeometry.Spec.map
        (CommRingCat.ofHom (algebraMap ℤ B)))).mapGrp.obj
        (AdditiveGroup.groupScheme ℤ) ≅ AdditiveGroup.groupScheme B :=
  (Over.pullback (AlgebraicGeometry.Spec.map
      (CommRingCat.ofHom (algebraMap ℤ B)))).mapGrp.mapIso
      (eqToIso (AdditiveGroup.groupScheme_def ℤ)) ≪≫
    AffineGroupSchemeCat.hopfSpecBaseChangeGrpIso (AdditiveGroup.coordinateHopfAlgebra ℤ) ≪≫
    (AlgebraicGeometry.hopfSpec (CommRingCat.of B)).mapIso
      (AdditiveGroup.coordinateHopfAlgebraBaseChangeIso ℤ B).symm.op ≪≫
    eqToIso (AdditiveGroup.groupScheme_def B).symm

/-- The canonical comparison from the scheme-theoretic base change of the integral split torus
to the split torus constructed over `B`. -/
noncomputable def positiveWeightTorusDomainBaseChangeIso :
    (Over.pullback (AlgebraicGeometry.Spec.map
        (CommRingCat.ofHom (algebraMap ℤ B)))).mapGrp.obj
        (SplitTorus.groupScheme ℤ (Fin 6)) ≅ SplitTorus.groupScheme B (Fin 6) :=
  (Over.pullback (AlgebraicGeometry.Spec.map
      (CommRingCat.ofHom (algebraMap ℤ B)))).mapGrp.mapIso
      (eqToIso (DiagonalizableGroup.groupScheme_def ℤ
        (SplitTorus.characterGroup (Fin 6)))) ≪≫
    AffineGroupSchemeCat.hopfSpecBaseChangeGrpIso
      (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup (Fin 6))).obj ≪≫
    (AlgebraicGeometry.hopfSpec (CommRingCat.of B)).mapIso
      (DiagonalizableGroup.baseChangeCoordinateHopfAlgebraIso ℤ B
        (SplitTorus.characterGroup (Fin 6))).symm.op ≪≫
    eqToIso (DiagonalizableGroup.groupScheme_def B
      (SplitTorus.characterGroup (Fin 6))).symm

/-- The `i`th positive simple-root morphism after scheme-theoretic base change to `B`. -/
noncomputable def positiveRootSubgroupBaseChange (i : Fin 6) :
    AdditiveGroup.groupScheme B ⟶ positiveSubsystemBaseChangeGroupScheme B :=
  (positiveRootSubgroupDomainBaseChangeIso B).inv ≫
    (Over.pullback (AlgebraicGeometry.Spec.map
      (CommRingCat.ofHom (algebraMap ℤ B)))).mapGrp.map (positiveRootSubgroup i)

/-- The quotient-presentation comparison identifies the scheme-theoretic base change of the
`i`th positive simple-root morphism with scalar extension of its integral coordinate map. -/
theorem positiveRootSubgroupBaseChange_comp_presentationIso (i : Fin 6) :
    (positiveRootSubgroupDomainBaseChangeIso B).hom ≫
      positiveRootSubgroupBaseChange B i ≫
        (positiveSubsystemBaseChangePresentationIso B).hom =
      (Over.pullback (AlgebraicGeometry.Spec.map
          (CommRingCat.ofHom (algebraMap ℤ B)))).mapGrp.map
          (eqToHom (AdditiveGroup.groupScheme_def ℤ)) ≫
        (AffineGroupSchemeCat.hopfSpecBaseChangeGrpIso
          (R := ℤ) (S := B) (AdditiveGroup.coordinateHopfAlgebra ℤ)).hom ≫
        (AlgebraicGeometry.hopfSpec (CommRingCat.of B)).map
          ((kostantTorusSubsystemBaseChangeIso rootGen cartanGen weightTable.rep
            (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝒷
            weightTable.weight positiveSimpleRoots
            (fun k => weightTable.isNilpotent_rep_serreRootGenerator k.1) B).hom ≫
          CommHopfAlgCat.baseChangeMap
            (kostantRootSubgroupTorusSubsystemCoordinateMap rootGen cartanGen weightTable.rep
              (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝒷 weightTable.weight
              positiveSimpleRoots
              (fun k => weightTable.isNilpotent_rep_serreRootGenerator k.1)
              (inl_mem_positiveSimpleRoots i))).op := by
  simp [positiveRootSubgroupBaseChange, positiveSubsystemBaseChangePresentationIso,
    positiveRootSubgroup_def, kostantRootSubgroupToTorusSubsystem_def]
  have h := congrArg (fun f =>
      (Over.pullback (AlgebraicGeometry.Spec.map
        (CommRingCat.ofHom (algebraMap ℤ B)))).mapGrp.map
          (eqToHom (AdditiveGroup.groupScheme_def ℤ)) ≫ f ≫
        (AlgebraicGeometry.hopfSpec (CommRingCat.of B)).map
          (kostantTorusSubsystemBaseChangeIso rootGen cartanGen weightTable.rep
            (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝒷
            weightTable.weight positiveSimpleRoots
            (fun k => weightTable.isNilpotent_rep_serreRootGenerator k.1) B).hom.op)
    (AffineGroupSchemeCat.hopfSpecBaseChangeGrpIso_hom_naturality
      (R := ℤ) (S := B)
      (kostantRootSubgroupTorusSubsystemCoordinateMap rootGen cartanGen weightTable.rep
        (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝒷 weightTable.weight
        positiveSimpleRoots (fun k => weightTable.isNilpotent_rep_serreRootGenerator k.1)
        (inl_mem_positiveSimpleRoots i)))
  simpa using h

/-- The positive weight-torus morphism after scheme-theoretic base change to `B`. -/
noncomputable def positiveWeightTorusBaseChange :
    SplitTorus.groupScheme B (Fin 6) ⟶ positiveSubsystemBaseChangeGroupScheme B :=
  (positiveWeightTorusDomainBaseChangeIso B).inv ≫
    (Over.pullback (AlgebraicGeometry.Spec.map
      (CommRingCat.ofHom (algebraMap ℤ B)))).mapGrp.map positiveWeightTorus

/-- Under the quotient-presentation comparison, the base-changed positive weight torus is the
generic transported factorization. -/
theorem positiveWeightTorusBaseChange_comp_presentationIso :
    (positiveWeightTorusDomainBaseChangeIso B).hom ≫
      positiveWeightTorusBaseChange B ≫
        (positiveSubsystemBaseChangePresentationIso B).hom =
      (Over.pullback (AlgebraicGeometry.Spec.map
          (CommRingCat.ofHom (algebraMap ℤ B)))).mapGrp.map
          (eqToHom (DiagonalizableGroup.groupScheme_def ℤ
            (SplitTorus.characterGroup (Fin 6)))) ≫
        (AffineGroupSchemeCat.hopfSpecBaseChangeGrpIso
          (R := ℤ) (S := B)
          (DiagonalizableGroup.coordinateRing ℤ
            (SplitTorus.characterGroup (Fin 6))).obj).hom ≫
        (AlgebraicGeometry.hopfSpec (CommRingCat.of B)).map
          ((kostantTorusSubsystemBaseChangeIso rootGen cartanGen weightTable.rep
            (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝒷
            weightTable.weight positiveSimpleRoots
            (fun k => weightTable.isNilpotent_rep_serreRootGenerator k.1) B).hom ≫
          CommHopfAlgCat.baseChangeMap
            (kostantWeightTorusTorusSubsystemCoordinateMap rootGen cartanGen weightTable.rep
              (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝒷 weightTable.weight
              positiveSimpleRoots
              (fun k => weightTable.isNilpotent_rep_serreRootGenerator k.1))).op := by
  simp [positiveWeightTorusBaseChange, positiveSubsystemBaseChangePresentationIso,
    positiveWeightTorus_def, kostantWeightTorusToTorusSubsystem_def]
  have h := congrArg (fun f =>
      (Over.pullback (AlgebraicGeometry.Spec.map
        (CommRingCat.ofHom (algebraMap ℤ B)))).mapGrp.map
          (eqToHom (DiagonalizableGroup.groupScheme_def ℤ
            (SplitTorus.characterGroup (Fin 6)))) ≫ f ≫
        (AlgebraicGeometry.hopfSpec (CommRingCat.of B)).map
          (kostantTorusSubsystemBaseChangeIso rootGen cartanGen weightTable.rep
            (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝒷
            weightTable.weight positiveSimpleRoots
            (fun k => weightTable.isNilpotent_rep_serreRootGenerator k.1) B).hom.op)
    (AffineGroupSchemeCat.hopfSpecBaseChangeGrpIso_hom_naturality
      (R := ℤ) (S := B)
      (kostantWeightTorusTorusSubsystemCoordinateMap rootGen cartanGen weightTable.rep
        (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝒷 weightTable.weight
        positiveSimpleRoots (fun k => weightTable.isNilpotent_rep_serreRootGenerator k.1)))
  simpa using h

end

end TauCeti.E6Minuscule
