/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.GaloisGroups.Reduction
public import TauCeti.FieldTheory.GaloisGroups.Resolvent.Quintic.Basic

import Mathlib.Algebra.Polynomial.Eval.Irreducible
import Mathlib.Tactic.ComputeDegree

/-!
# Evidence for quintic Galois-group certificates

A factorization of a monic integral polynomial at a prime not dividing its discriminant gives
lower-bound evidence for its Galois group: the factor degrees are the full cycle type of an
element of the Galois image. A root of a separable resolvent gives upper-bound evidence. This
module packages those two kinds of evidence, together with the condition that a polynomial has a
second root in the field generated by one root.

The predicates contain only finite data. They do not search for a suitable prime, resolvent root,
or second root. Their elimination lemmas expose the mathematical consequences used by quintic
certificates, while keeping the proof of primality bundled with the factor-degree computation.

## Main definitions

* `TauCeti.IsGoodPrime`: a prime candidate does not divide the polynomial discriminant.
* `TauCeti.HasFactorDegrees`: a good prime with specified factor degrees.
* `TauCeti.HasSexticRoot`: an integral root of a separable quintic resolvent sextic.
* `TauCeti.HasSecondRootInRootField`: a second root represented modulo the polynomial.

## Main results

* `TauCeti.HasFactorDegrees.exists_fullCycleType`: factor-degree evidence produces an element of
  the Galois image with that full cycle type.
* `TauCeti.HasFactorDegrees.irreducible_map_rat`: singleton evidence proves irreducibility over
  `ℚ`.
* `TauCeti.HasFactorDegrees.exists_orderOf_eq_two` and
  `TauCeti.HasFactorDegrees.exists_orderOf_eq_six`: the two factor types used by the dihedral and
  symmetric certificate routes produce elements of the required orders.
* `TauCeti.HasSexticRoot.isRoot_specialize_rat` and
  `TauCeti.HasSexticRoot.separable_specialize_rat`: the two consequences of resolvent evidence in
  the rational specialization used by quintic labels.
* `TauCeti.hasSecondRootInRootField_cyclicQuintic`: the second-root evidence used by the cyclic
  quintic example.
-/

public section
noncomputable section

open Equiv Equiv.Perm Polynomial

namespace TauCeti

attribute [local instance] Polynomial.Gal.splits_ℚ_ℂ

/-- A prime candidate is good for an integral polynomial when it does not divide the polynomial
discriminant. Primality is carried separately by `HasFactorDegrees`. -/
def IsGoodPrime (f : ℤ[X]) (p : ℕ) : Prop :=
  ¬ (p : ℤ) ∣ f.discr

/-- The defining characterization of a good prime. -/
@[simp]
theorem isGoodPrime_iff (f : ℤ[X]) (p : ℕ) : IsGoodPrime f p ↔ ¬ (p : ℤ) ∣ f.discr :=
  Iff.rfl

/-- A good-prime factorization item: `p` is prime, does not divide the discriminant of `f`, and
the irreducible factors of `f` modulo `p` have degrees `t`, with multiplicity. -/
def HasFactorDegrees (f : ℤ[X]) (p : ℕ) (t : Multiset ℕ) : Prop :=
  ∃ hp : p.Prime, IsGoodPrime f p ∧ @Polynomial.factorDegrees f p ⟨hp⟩ = t

/-- Construct factor-degree evidence from a prime instance, goodness, and the factor degrees. -/
theorem HasFactorDegrees.mk {f : ℤ[X]} {p : ℕ} [hp : Fact p.Prime] {t : Multiset ℕ}
    (hgood : IsGoodPrime f p) (hfac : f.factorDegrees p = t) : HasFactorDegrees f p t :=
  ⟨hp.out, hgood, hfac⟩

/-- Eliminate factor-degree evidence while retaining a local primality instance. -/
theorem HasFactorDegrees.exists_fact {f : ℤ[X]} {p : ℕ} {t : Multiset ℕ}
    (h : HasFactorDegrees f p t) :
    ∃ hp : Fact p.Prime, IsGoodPrime f p ∧ @Polynomial.factorDegrees f p hp = t := by
  obtain ⟨hp, hgood, hfac⟩ := h
  exact ⟨⟨hp⟩, hgood, hfac⟩

/-- Factor-degree evidence produces an element of the Galois image whose full cycle type is the
specified multiset. -/
theorem HasFactorDegrees.exists_fullCycleType {f : ℤ[X]} {p : ℕ} {t : Multiset ℕ}
    (h : HasFactorDegrees f p t) (hf : f.Monic) :
    ∃ σ ∈ (Polynomial.Gal.galActionHom (f.map (Int.castRingHom ℚ)) ℂ).range,
      σ.fullCycleType = t := by
  obtain ⟨hp, hgood, hfac⟩ := h.exists_fact
  let _ := hp
  obtain ⟨σ, hσ, htype⟩ :=
    exists_mem_range_galActionHom_fullCycleType_eq_factorDegrees hf p hgood
  exact ⟨σ, hσ, htype.trans hfac⟩

/-- Factor degrees `(1,2,2)` exhibit an element of order two in the Galois image. This is the
lower-bound evidence that distinguishes the dihedral quintic label from the cyclic one. -/
theorem HasFactorDegrees.exists_orderOf_eq_two {f : ℤ[X]} {p : ℕ}
    (h : HasFactorDegrees f p {1, 2, 2}) (hf : f.Monic) :
    ∃ σ ∈ (Polynomial.Gal.galActionHom (f.map (Int.castRingHom ℚ)) ℂ).range,
      orderOf σ = 2 := by
  obtain ⟨σ, hσ, htype⟩ := h.exists_fullCycleType hf
  refine ⟨σ, hσ, ?_⟩
  rw [← Equiv.Perm.lcm_cycleType, ← filter_fullCycleType_eq_cycleType, htype]
  decide

/-- Factor degrees `(2,3)` exhibit an element of order six in the Galois image. In degree five,
this is the lower-bound evidence for the full symmetric label. -/
theorem HasFactorDegrees.exists_orderOf_eq_six {f : ℤ[X]} {p : ℕ}
    (h : HasFactorDegrees f p {2, 3}) (hf : f.Monic) :
    ∃ σ ∈ (Polynomial.Gal.galActionHom (f.map (Int.castRingHom ℚ)) ℂ).range,
      orderOf σ = 6 := by
  obtain ⟨σ, hσ, htype⟩ := h.exists_fullCycleType hf
  refine ⟨σ, hσ, ?_⟩
  rw [← Equiv.Perm.lcm_cycleType, ← filter_fullCycleType_eq_cycleType, htype]
  decide

/-- Singleton factor-degree evidence proves that the reduction is irreducible and records its
degree. -/
theorem HasFactorDegrees.irreducible_map {f : ℤ[X]} {p n : ℕ}
    (h : HasFactorDegrees f p {n}) :
    ∃ _hp : Fact p.Prime,
      Irreducible (f.map (Int.castRingHom (ZMod p))) ∧
        (f.map (Int.castRingHom (ZMod p))).natDegree = n := by
  obtain ⟨hp, -, hfac⟩ := h.exists_fact
  let _ := hp
  exact ⟨hp, Polynomial.factorDegrees_eq_singleton_iff.mp hfac⟩

/-- If a monic polynomial has its degree as its sole factor degree at a good prime, then its
image over `ℚ` is irreducible. -/
theorem HasFactorDegrees.irreducible_map_rat {f : ℤ[X]} {p : ℕ}
    (h : HasFactorDegrees f p {f.natDegree}) (hf : f.Monic) :
    Irreducible (f.map (Int.castRingHom ℚ)) := by
  obtain ⟨hp, hirr, -⟩ := h.irreducible_map
  let _ := hp
  exact (IsPrimitive.Int.irreducible_iff_irreducible_map_cast hf.isPrimitive).mp
    (Monic.irreducible_of_irreducible_map (Int.castRingHom (ZMod p)) f hf hirr)

/-- A resolvent item: `a` is an integral root of the quintic resolvent sextic and the sextic has
nonzero discriminant. The latter condition is precisely the separation evidence needed to read
the root as an upper bound on the Galois image. -/
def HasSexticRoot (f : ℤ[X]) (a : ℤ) : Prop :=
  (resolventSextic f).eval a = 0 ∧ (resolventSextic f).discr ≠ 0

/-- The integer carried by resolvent evidence is a root of the resolvent sextic. -/
theorem HasSexticRoot.isRoot {f : ℤ[X]} {a : ℤ} (h : HasSexticRoot f a) :
    (resolventSextic f).IsRoot a :=
  h.1

/-- The resolvent sextic in a resolvent item becomes separable over `ℚ`. -/
theorem HasSexticRoot.separable_map_rat {f : ℤ[X]} {a : ℤ} (h : HasSexticRoot f a) :
    ((resolventSextic f).map (Int.castRingHom ℚ)).Separable :=
  (monic_resolventSextic f).discr_ne_zero_iff_separable_map ℚ |>.mp h.2

/-- Resolvent evidence remains a root after mapping the sextic and its root to any field. -/
theorem HasSexticRoot.isRoot_map {F : Type*} [Field F] {f : ℤ[X]} {a : ℤ}
    (h : HasSexticRoot f a) :
    ((resolventSextic f).map (Int.castRingHom F)).IsRoot (a : F) :=
  h.isRoot.map

/-- Resolvent evidence gives a root of the rational specialization of the quintic
`F₂₀`-resolvent. -/
theorem HasSexticRoot.isRoot_specialize_rat {f : ℤ[X]} {a : ℤ} (h : HasSexticRoot f a) :
    (quinticF20Spec.specialize ℚ (f.map (Int.castRingHom ℚ))).IsRoot (a : ℚ) := by
  rw [← ResolventSpec.specialize_map, ← resolventSextic_def]
  exact h.isRoot_map

/-- The rational specialization of the quintic `F₂₀`-resolvent in a resolvent item is
separable. -/
theorem HasSexticRoot.separable_specialize_rat {f : ℤ[X]} {a : ℤ}
    (h : HasSexticRoot f a) :
    (quinticF20Spec.specialize ℚ (f.map (Int.castRingHom ℚ))).Separable := by
  rw [← ResolventSpec.specialize_map, ← resolventSextic_def]
  exact h.separable_map_rat

/-- A normality item: `b` represents, modulo `f`, a root of `f` other than the class of `X` in
the field generated by one root. -/
def HasSecondRootInRootField (f : ℤ[X]) (b : ℚ[X]) : Prop :=
  ((f.map (Int.castRingHom ℚ)).comp b) %ₘ (f.map (Int.castRingHom ℚ)) = 0 ∧
    b %ₘ (f.map (Int.castRingHom ℚ)) ≠ X

/-- The polynomial represented by a second-root item vanishes after substitution, modulo `f`. -/
theorem HasSecondRootInRootField.comp_modByMonic_eq_zero {f : ℤ[X]} {b : ℚ[X]}
    (h : HasSecondRootInRootField f b) :
    ((f.map (Int.castRingHom ℚ)).comp b) %ₘ (f.map (Int.castRingHom ℚ)) = 0 :=
  h.1

/-- The polynomial represented by a second-root item is not the distinguished root `X`, modulo
`f`. -/
theorem HasSecondRootInRootField.modByMonic_ne_X {f : ℤ[X]} {b : ℚ[X]}
    (h : HasSecondRootInRootField f b) :
    b %ₘ (f.map (Int.castRingHom ℚ)) ≠ X :=
  h.2

/-- The cyclic quintic `X⁵ + X⁴ - 4X³ - 3X² + 3X + 1` has the second root represented by
`X² - 2` in the field generated by one root. -/
theorem hasSecondRootInRootField_cyclicQuintic :
    HasSecondRootInRootField (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1)
      (X ^ 2 - 2) := by
  unfold HasSecondRootInRootField
  norm_num only [Polynomial.map_add, Polynomial.map_sub, Polynomial.map_mul,
    Polynomial.map_pow, Polynomial.map_X, Polynomial.map_one, Polynomial.map_ofNat]
  let f : ℚ[X] := X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1
  have hf : f.Monic := by
    dsimp [f]
    monicity!
  -- Name the mapped polynomial so the two modular-reduction arguments share the same monicity
  -- witness; `norm_num` above has already reduced the coefficient map to this expression.
  change (f.comp (X ^ 2 - 2)) %ₘ f = 0 ∧ (X ^ 2 - 2) %ₘ f ≠ X
  constructor
  · rw [modByMonic_eq_zero_iff_dvd hf]
    refine ⟨X ^ 5 - X ^ 4 - 4 * X ^ 3 + 3 * X ^ 2 + 3 * X - 1, ?_⟩
    dsimp [f]
    simp
    ring_nf
  · have hb : (X ^ 2 - 2 : ℚ[X]) %ₘ f = X ^ 2 - 2 :=
      (modByMonic_eq_self_iff hf).mpr (by
        have hfdeg : f.degree = 5 := by dsimp [f]; compute_degree!
        have hbdeg : (X ^ 2 - 2 : ℚ[X]).degree = 2 := by compute_degree!
        rw [hfdeg, hbdeg]
        decide)
    rw [hb]
    intro h
    have := congrArg (fun q : ℚ[X] ↦ q.coeff 0) h
    norm_num at this

end TauCeti
