/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.GaloisGroups.Certificate.Routes

import Mathlib.Tactic.ComputeDegree
import TauCeti.FieldTheory.GaloisGroups.FactorDegrees

/-!
# Examples of quintic Galois-group certificate evidence

This module records an explicit modular second-root witness for
`X⁵ + X⁴ - 4X³ - 3X² + 3X + 1`. This witness supplies the extra datum that distinguishes its
cyclic Galois group from the dihedral possibility. It also reads the label `5T5` of `X⁵ - X - 1`
off its factorizations modulo `5` and `2` through the symmetric route.

## Main results

* `TauCeti.hasSecondRootInRootField_cyclicQuintic`: the second-root evidence used by the cyclic
  quintic example.
* `TauCeti.hasGaloisLabel_X_pow_five_sub_X_sub_one`: `X⁵ - X - 1` has label `5T5`.
-/

public section
noncomputable section

open Polynomial

namespace TauCeti

-- The exact polynomial and witness below are specified by the worked cyclic certificate in
-- Layer 6 of the PolynomialGaloisGroups roadmap:
-- https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/PolynomialGaloisGroups/README.md
/-- The polynomial `X² - 2` supplies formal second-root evidence for the cyclic quintic
`X⁵ + X⁴ - 4X³ - 3X² + 3X + 1`. For this monic irreducible quintic, it represents a second
root in the field generated by one root. -/
theorem hasSecondRootInRootField_cyclicQuintic :
    HasSecondRootInRootField (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1)
      (X ^ 2 - 2) := by
  rw [hasSecondRootInRootField_iff]
  norm_num only [Polynomial.map_add, Polynomial.map_sub, Polynomial.map_mul,
    Polynomial.map_pow, Polynomial.map_X, Polynomial.map_one, Polynomial.map_ofNat]
  let f : ℚ[X] := X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1
  have hf : f.Monic := by
    dsimp [f]
    monicity!
  have hsecond : (f.comp (X ^ 2 - 2)) %ₘ f = 0 ∧ (X ^ 2 - 2) %ₘ f ≠ X %ₘ f := by
    constructor
    · rw [modByMonic_eq_zero_iff_dvd hf]
      refine ⟨X ^ 5 - X ^ 4 - 4 * X ^ 3 + 3 * X ^ 2 + 3 * X - 1, ?_⟩
      dsimp [f]
      simp
      ring_nf
    · have hb : (X ^ 2 - 2 : ℚ[X]) %ₘ f = X ^ 2 - 2 :=
        (modByMonic_eq_self_iff hf).mpr (by
          have hfdeg : f.degree = 5 := by dsimp [f]; compute_degree!
          have hbdeg : (X ^ 2 - 2 : ℚ[X]).degree = 2 := by compute_degree!
          rw [hfdeg, hbdeg]
          decide)
      have hX : (X : ℚ[X]) %ₘ f = X :=
        (modByMonic_eq_self_iff hf).mpr (by
          have hfdeg : f.degree = 5 := by dsimp [f]; compute_degree!
          have hXdeg : (X : ℚ[X]).degree = 1 := by compute_degree!
          rw [hfdeg, hXdeg]
          decide)
      rw [hb, hX]
      intro h
      have := congrArg (fun q : ℚ[X] ↦ q.coeff 0) h
      norm_num at this
  simpa only [f] using hsecond

/-- **`X⁵ - X - 1` has label `5T5`.** It is irreducible modulo `5` and has factor degrees `(2,3)`
modulo `2`, so the symmetric route applies. -/
theorem hasGaloisLabel_X_pow_five_sub_X_sub_one :
    HasGaloisLabel ((X ^ 5 - X - 1 : ℤ[X]).map (Int.castRingHom ℚ))
      (⟨4, by simp⟩ : TransitiveGroupIndex 5) := by
  have : Fact (Nat.Prime 5) := ⟨Nat.prime_five⟩
  have : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  have hf := monic_X_pow_five_sub_X_sub_one
  have hirr := (factorDegrees_eq_singleton_iff.mp factorDegrees_X_pow_five_sub_X_sub_one_five).1
  have hgood5 : IsGoodPrime (X ^ 5 - X - 1) 5 := (isGoodPrime_iff _ 5).mpr <|
    (hf.separable_map_zmod_iff_not_dvd_discr 5).mp (PerfectField.separable_of_irreducible hirr)
  have hgood2 : IsGoodPrime (X ^ 5 - X - 1) 2 :=
    (isGoodPrime_iff _ 2).mpr not_two_dvd_discr_X_pow_five_sub_X_sub_one
  have h5 := HasFactorDegrees.mk hgood5 factorDegrees_X_pow_five_sub_X_sub_one_five
  refine hasGaloisLabel_five_four_of_hasFactorDegrees hf (h5.irreducible_map_rat hf)
    (HasFactorDegrees.mk hgood2 ?_)
  rw [factorDegrees_X_pow_five_sub_X_sub_one_two]
  decide

end TauCeti
