/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.Curves.StableReduction.Picard.Basic
import Mathlib.LinearAlgebra.Isomorphisms

/-!
# The Picard group of a weighted two-component numerical type

For the numerical type with two components of multiplicity one and weight two, meeting
twice, the weighted intersection relations are generated by `(-1, 1)`. Thus its Picard
group is infinite cyclic. The unweighted intersection relations are generated by
`(-2, 2)`, and their cokernel has nonzero two-torsion. This calculation distinguishes
the weighted Picard group from the raw intersection cokernel in the numerical argument
for stable reduction.
-/

public section

namespace TauCeti

namespace NumericalType

open Matrix

private lemma weightedExample_weightedIntersection :
    weightedExample.weightedIntersection = !![-1, 1; 1, -1] := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [weightedIntersection_apply, weightedExample]

/-- The principal multidegrees in the weight-two example are exactly the pairs with sum zero. -/
theorem weightedExample_mem_principalDivisors_iff (d : Fin 2 → ℤ) :
    d ∈ weightedExample.principalDivisors ↔ d 0 + d 1 = 0 := by
  rw [weightedExample.mem_principalDivisors_iff]
  constructor
  · rintro ⟨v, rfl⟩
    rw [weightedExample_weightedIntersection]
    simp [Matrix.vecMul_apply_eq_sum, Fin.sum_univ_two]
    omega
  · intro hd
    refine ⟨![0, d 0], ?_⟩
    funext i
    fin_cases i
    · simp [weightedExample_weightedIntersection, Matrix.vecMul_apply_eq_sum,
        Fin.sum_univ_two]
    · simp [weightedExample_weightedIntersection, Matrix.vecMul_apply_eq_sum,
        Fin.sum_univ_two]
      omega

private def weightedExampleSum : (Fin 2 → ℤ) →ₗ[ℤ] ℤ :=
  (LinearMap.proj 0 : (Fin 2 → ℤ) →ₗ[ℤ] ℤ) + LinearMap.proj 1

private lemma weightedExampleSum_surjective : Function.Surjective weightedExampleSum :=
  fun n ↦ ⟨![n, 0], by simp [weightedExampleSum]⟩

private lemma weightedExample_ker_sum :
    LinearMap.ker weightedExampleSum = weightedExample.principalDivisors := by
  ext d
  simpa [weightedExampleSum, LinearMap.mem_ker] using
    (weightedExample_mem_principalDivisors_iff d).symm

/-- The weighted Picard group of the two-component example is infinite cyclic, with a
multidegree sent to the sum of its two coordinates. -/
noncomputable def weightedExample_picEquivInt : weightedExample.Pic ≃ₗ[ℤ] ℤ :=
  (Submodule.quotEquivOfEq _ _ weightedExample_ker_sum.symm) |>.trans
    (weightedExampleSum.quotKerEquivOfSurjective weightedExampleSum_surjective)

/-- The Picard-class isomorphism is the sum of multidegrees. -/
@[simp]
theorem weightedExample_picEquivInt_mk (d : Fin 2 → ℤ) :
    weightedExample_picEquivInt (Submodule.Quotient.mk d) = d 0 + d 1 := by
  simp only [weightedExample_picEquivInt, LinearEquiv.trans_apply,
    Submodule.quotEquivOfEq_mk]
  rw [LinearMap.quotKerEquivOfSurjective_apply_mk]
  simp [weightedExampleSum]

/-- The weighted Picard group has no nonzero two-torsion. -/
theorem weightedExample_pic_no_two_torsion (x : weightedExample.Pic) (hx : (2 : ℤ) • x = 0) :
    x = 0 := by
  apply weightedExample_picEquivInt.injective
  have h := congrArg weightedExample_picEquivInt hx
  simp only [map_smul, map_zero, smul_eq_mul] at h
  have hz : weightedExample_picEquivInt x = 0 := by omega
  simpa using hz

/-- The raw intersection cokernel of the weight-two example contains nonzero two-torsion:
the class of `(1, -1)` has order two. -/
theorem weightedExample_coker_has_two_torsion :
    ∃ x : weightedExample.Coker, x ≠ 0 ∧ (2 : ℤ) • x = 0 := by
  let x : weightedExample.Coker := Submodule.Quotient.mk (![1, -1] : Fin 2 → ℤ)
  refine ⟨x, ?_, ?_⟩
  · intro hx
    have hmem : (![1, -1] : Fin 2 → ℤ) ∈ weightedExample.intersectionRelations :=
      (Submodule.Quotient.mk_eq_zero _).mp hx
    obtain ⟨v, hv⟩ := weightedExample.mem_intersectionRelations_iff.mp hmem
    have h0 := congrFun hv 0
    simp [Matrix.vecMul_apply_eq_sum, Fin.sum_univ_two] at h0
    omega
  · rw [show x = Submodule.Quotient.mk (![1, -1] : Fin 2 → ℤ) from rfl,
      ← Submodule.Quotient.mk_smul]
    apply (Submodule.Quotient.mk_eq_zero _).mpr
    refine weightedExample.mem_intersectionRelations_iff.mpr ⟨![0, 1], ?_⟩
    funext i
    fin_cases i <;>
      simp [Matrix.vecMul_apply_eq_sum, Fin.sum_univ_two, Pi.smul_apply]

private noncomputable abbrev unequalWeights : NumericalType.{0} :=
  { weightedExample with
    weight := ![1, 2]
    weight_dvd := by
      intro i j
      fin_cases i <;> fin_cases j <;> decide }

/-- In the unevenly weighted example, division is by the destination weight: the first
relation is `(-2, 1)`. -/
example : unequalWeights.weightedIntersection 0 0 = -2 ∧
    unequalWeights.weightedIntersection 0 1 = 1 := by
  constructor <;> norm_num [weightedIntersection_apply, unequalWeights, weightedExample]

end NumericalType

end TauCeti
