/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.CommutativeAlgebra.MatrixFactorization.BaseChange
public import TauCeti.CommutativeAlgebra.MatrixFactorization.Polynomial.Basic
public import TauCeti.RingTheory.AdjoinRoot.Basic
public import Mathlib.Algebra.Homology.ShortComplex.ModuleCat

/-!
# Polynomial matrix factorizations modulo their potential

The rank-one factorization of `X ^ n` with maps `X ^ i` and `X ^ (n - i)` reduces modulo
`X ^ n` to the two-periodic complex of free rank-one modules with maps given by multiplication by
the corresponding powers of the residue class `x` of `X`. This file constructs that complex,
proves it is exact in both parities, and identifies it with the generic reduction of
`MatrixFactorization.powerXOfLE`.

Thus the matrix factorization supplies the unaugmented exact periodic complex underlying the free
resolution of the cyclic module `k[x]/(x ^ i)`. The augmentation and cokernel identification are
separate from this construction. The exactness argument works over every commutative base ring:
the annihilator of `x ^ i` in `R[X]/(X ^ n)` is generated by `x ^ (n - i)`.

## References

* D. Eisenbud, *Homological algebra on a complete intersection, with an application to group
  representations*, Trans. Amer. Math. Soc. **260** (1980), Section 5.
-/

public section

noncomputable section

universe u

namespace TauCeti.MatrixFactorization

open CategoryTheory Polynomial

variable (R : Type u) [CommRing R] {i n : ℕ}

/-- Multiplication by the `j`th power of the residue class of `X` on the regular module over
`R[X]/(X ^ n)`. -/
@[expose]
def rootPowHom (n j : ℕ) :
    ModuleCat.of (AdjoinRoot (X ^ n : R[X])) (AdjoinRoot (X ^ n : R[X])) ⟶
      ModuleCat.of (AdjoinRoot (X ^ n : R[X])) (AdjoinRoot (X ^ n : R[X])) :=
  ModuleCat.ofHom (LinearMap.mulLeft _ (AdjoinRoot.root (X ^ n : R[X]) ^ j))

/-- Multiplication by `x ^ j` sends `a` to `x ^ j * a`. -/
@[simp]
theorem rootPowHom_apply (n j : ℕ) (a : AdjoinRoot (X ^ n : R[X])) :
    rootPowHom R n j a = AdjoinRoot.root (X ^ n : R[X]) ^ j * a := rfl

/-- Multiplication by `x ^ j` is scalar multiplication of the identity by `x ^ j`. -/
theorem rootPowHom_eq_smul_id (n j : ℕ) :
    rootPowHom R n j = AdjoinRoot.root (X ^ n : R[X]) ^ j •
      𝟙 (ModuleCat.of (AdjoinRoot (X ^ n : R[X])) (AdjoinRoot (X ^ n : R[X]))) := by
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  intro a
  simp [rootPowHom, ModuleCat.hom_id]

/-- The square-zero duplex of free rank-one `R[X]/(X ^ n)`-modules with differentials
`x ^ i` and `x ^ (n - i)`. -/
@[expose]
def powerXPeriodicDuplex (hi : i ≤ n) :
    CurvedDuplex (ModuleCat.{u} (AdjoinRoot (X ^ n : R[X]))) (0 : AdjoinRoot (X ^ n : R[X])) where
  X₀ := ModuleCat.of _ (AdjoinRoot (X ^ n : R[X]))
  X₁ := ModuleCat.of _ (AdjoinRoot (X ^ n : R[X]))
  d₀ := rootPowHom R n i
  d₁ := rootPowHom R n (n - i)
  d₀_comp_d₁ := by
    apply ModuleCat.hom_ext
    apply LinearMap.ext
    intro a
    simp only [ModuleCat.hom_comp, LinearMap.coe_comp, Function.comp_apply, rootPowHom,
      ModuleCat.hom_ofHom, LinearMap.mulLeft_apply, zero_smul, ModuleCat.hom_zero,
      LinearMap.zero_apply]
    rw [← mul_assoc, ← pow_add, Nat.sub_add_cancel hi, ← AdjoinRoot.mk_X, ← map_pow,
      AdjoinRoot.mk_self, zero_mul]
  d₁_comp_d₀ := by
    apply ModuleCat.hom_ext
    apply LinearMap.ext
    intro a
    simp only [ModuleCat.hom_comp, LinearMap.coe_comp, Function.comp_apply, rootPowHom,
      ModuleCat.hom_ofHom, LinearMap.mulLeft_apply, zero_smul, ModuleCat.hom_zero,
      LinearMap.zero_apply]
    rw [← mul_assoc, ← pow_add, Nat.add_sub_cancel' hi, ← AdjoinRoot.mk_X, ← map_pow,
      AdjoinRoot.mk_self, zero_mul]

/-- The zero-to-one differential is multiplication by `x ^ i`. -/
@[simp]
theorem powerXPeriodicDuplex_d₀ (hi : i ≤ n) :
    (powerXPeriodicDuplex R hi).d₀ = rootPowHom R n i := rfl

/-- The one-to-zero differential is multiplication by `x ^ (n - i)`. -/
@[simp]
theorem powerXPeriodicDuplex_d₁ (hi : i ≤ n) :
    (powerXPeriodicDuplex R hi).d₁ = rootPowHom R n (n - i) := rfl

/-- The explicit two-periodic free complex over `R[X]/(X ^ n)` associated to the factorization
`X ^ i · X ^ (n - i) = X ^ n`. -/
@[expose]
def powerXPeriodicComplex (hi : i ≤ n) :
    HomologicalComplex (ModuleCat.{u} (AdjoinRoot (X ^ n : R[X])))
      (ComplexShape.up (ZMod 2)) :=
  (CurvedDuplex.toPeriodicComplex _ _).obj (powerXPeriodicDuplex R hi)

/-- The even term of `powerXPeriodicComplex` is the free rank-one module. -/
@[simp]
theorem powerXPeriodicComplex_X_zero (hi : i ≤ n) :
    (powerXPeriodicComplex R hi).X 0 =
      ModuleCat.of _ (AdjoinRoot (X ^ n : R[X])) := rfl

/-- The odd term of `powerXPeriodicComplex` is the free rank-one module. -/
@[simp]
theorem powerXPeriodicComplex_X_one (hi : i ≤ n) :
    (powerXPeriodicComplex R hi).X 1 =
      ModuleCat.of _ (AdjoinRoot (X ^ n : R[X])) := rfl

/-- The differential from parity zero to parity one is multiplication by `x ^ i`. -/
@[simp]
theorem powerXPeriodicComplex_d_zero_one (hi : i ≤ n) :
    (powerXPeriodicComplex R hi).d 0 1 = rootPowHom R n i := rfl

/-- The differential from parity one to parity zero is multiplication by `x ^ (n - i)`. -/
@[simp]
theorem powerXPeriodicComplex_d_one_zero (hi : i ≤ n) :
    (powerXPeriodicComplex R hi).d 1 0 = rootPowHom R n (n - i) := rfl

private theorem exact_mulRootPow_mulRootPow (hi : i ≤ n) :
    Function.Exact
      (LinearMap.mulLeft (AdjoinRoot (X ^ n : R[X]))
        (AdjoinRoot.root (X ^ n : R[X]) ^ (n - i)))
      (LinearMap.mulLeft (AdjoinRoot (X ^ n : R[X]))
        (AdjoinRoot.root (X ^ n : R[X]) ^ i)) := by
  rw [LinearMap.exact_iff]
  apply Submodule.ext
  intro a
  simp only [LinearMap.mem_ker, LinearMap.mem_range, LinearMap.mulLeft_apply]
  change AdjoinRoot.root (X ^ n : R[X]) ^ i * a = 0 ↔
    ∃ b, AdjoinRoot.root (X ^ n : R[X]) ^ (n - i) * b = a
  rw [AdjoinRoot.root_X_pow_pow_mul_eq_zero_iff hi]
  constructor <;> rintro ⟨b, rfl⟩ <;> exact ⟨b, rfl⟩

private theorem exact_mulRootPow_mulRootPow_complement (hi : i ≤ n) :
    Function.Exact
      (LinearMap.mulLeft (AdjoinRoot (X ^ n : R[X]))
        (AdjoinRoot.root (X ^ n : R[X]) ^ i))
      (LinearMap.mulLeft (AdjoinRoot (X ^ n : R[X]))
        (AdjoinRoot.root (X ^ n : R[X]) ^ (n - i))) := by
  rw [LinearMap.exact_iff]
  apply Submodule.ext
  intro a
  simp only [LinearMap.mem_ker, LinearMap.mem_range, LinearMap.mulLeft_apply]
  change AdjoinRoot.root (X ^ n : R[X]) ^ (n - i) * a = 0 ↔
    ∃ b, AdjoinRoot.root (X ^ n : R[X]) ^ i * b = a
  rw [AdjoinRoot.root_X_pow_pow_mul_eq_zero_iff (R := R) (Nat.sub_le n i),
    Nat.sub_sub_self hi]
  constructor <;> rintro ⟨b, rfl⟩ <;> exact ⟨b, rfl⟩

/-- The two-periodic complex with alternating maps `x ^ i` and `x ^ (n - i)` is exact in every
degree. No field or positivity hypothesis is needed. -/
theorem powerXPeriodicComplex_acyclic (hi : i ≤ n) :
    (powerXPeriodicComplex R hi).Acyclic := by
  intro j
  rcases (by decide : ∀ j : ZMod 2, j = 0 ∨ j = 1) j with rfl | rfl
  · rw [HomologicalComplex.exactAt_iff' _ 1 0 1
        ((ComplexShape.up (ZMod 2)).prev_eq'
          (ComplexShape.up_mk 1 0 (by decide)))
        ((ComplexShape.up (ZMod 2)).next_eq'
          (ComplexShape.up_mk 0 1 (by decide))),
      ShortComplex.moduleCat_exact_iff_range_eq_ker]
    change (LinearMap.mulLeft (AdjoinRoot (X ^ n : R[X]))
        (AdjoinRoot.root (X ^ n : R[X]) ^ (n - i))).range =
      (LinearMap.mulLeft (AdjoinRoot (X ^ n : R[X]))
        (AdjoinRoot.root (X ^ n : R[X]) ^ i)).ker
    exact (LinearMap.exact_iff.mp (exact_mulRootPow_mulRootPow R hi)).symm
  · rw [HomologicalComplex.exactAt_iff' _ 0 1 0
        ((ComplexShape.up (ZMod 2)).prev_eq'
          (ComplexShape.up_mk 0 1 (by decide)))
        ((ComplexShape.up (ZMod 2)).next_eq'
          (ComplexShape.up_mk 1 0 (by decide))),
      ShortComplex.moduleCat_exact_iff_range_eq_ker]
    change (LinearMap.mulLeft (AdjoinRoot (X ^ n : R[X]))
        (AdjoinRoot.root (X ^ n : R[X]) ^ i)).range =
      (LinearMap.mulLeft (AdjoinRoot (X ^ n : R[X]))
        (AdjoinRoot.root (X ^ n : R[X]) ^ (n - i))).ker
    exact (LinearMap.exact_iff.mp (exact_mulRootPow_mulRootPow_complement R hi)).symm

/-! ### Comparison with reduction of the matrix factorization -/

/-- Extending the regular `R[X]`-module to `R[X]/(X ^ n)` gives the regular module over the
quotient. This is the component isomorphism in the comparison with `powerXOfLE`. -/
noncomputable def powerXRegularBaseChangeIso (n : ℕ) :
    (ModuleCat.extendScalars (AdjoinRoot.mk (X ^ n : R[X]))).obj
        (ModuleCat.of (Polynomial R) (Polynomial R)) ≅
      ModuleCat.of (AdjoinRoot (X ^ n : R[X])) (AdjoinRoot (X ^ n : R[X])) := by
  letI : Algebra (Polynomial R) (AdjoinRoot (X ^ n : R[X])) :=
    ((algebraMap (AdjoinRoot (X ^ n : R[X])) (AdjoinRoot (X ^ n : R[X]))).comp
      (AdjoinRoot.mk (X ^ n : R[X]))).toAlgebra
  exact LinearEquiv.toModuleIso
    (TensorProduct.AlgebraTensorModule.rid (Polynomial R)
      (AdjoinRoot (X ^ n : R[X])) (AdjoinRoot (X ^ n : R[X])))

private theorem powerXRegularBaseChangeIso_naturality (n j : ℕ) :
    (powerXRegularBaseChangeIso R n).hom ≫ rootPowHom R n j =
      (ModuleCat.extendScalars (AdjoinRoot.mk (X ^ n : R[X]))).map
          ((X ^ j : Polynomial R) • 𝟙 (ModuleCat.of (Polynomial R) (Polynomial R))) ≫
        (powerXRegularBaseChangeIso R n).hom := by
  rw [rootPowHom_eq_smul_id, ModuleCat.extendScalars_map_smul_id]
  simp [← AdjoinRoot.mk_X, ← map_pow]

/-- Reducing `powerXOfLE` along `R[X] → R[X]/(X ^ n)` gives the explicit square-zero duplex
with alternating differentials `x ^ i` and `x ^ (n - i)`. -/
noncomputable def powerXOfLEBaseChangeDuplexIso (hi : i ≤ n) :
    (baseChangeToCurvedDuplex (AdjoinRoot.mk (X ^ n : R[X])) AdjoinRoot.mk_self).obj
        (powerXOfLE R hi) ≅ powerXPeriodicDuplex R hi :=
  CurvedDuplex.isoMk (powerXRegularBaseChangeIso R n) (powerXRegularBaseChangeIso R n)
    (by
      change (powerXRegularBaseChangeIso R n).hom ≫ rootPowHom R n i =
        (ModuleCat.extendScalars (AdjoinRoot.mk (X ^ n : R[X]))).map
            ((X ^ i : Polynomial R) • 𝟙 (ModuleCat.of (Polynomial R) (Polynomial R))) ≫
          (powerXRegularBaseChangeIso R n).hom
      exact powerXRegularBaseChangeIso_naturality R n i)
    (by
      change (powerXRegularBaseChangeIso R n).hom ≫ rootPowHom R n (n - i) =
        (ModuleCat.extendScalars (AdjoinRoot.mk (X ^ n : R[X]))).map
            ((X ^ (n - i) : Polynomial R) •
              𝟙 (ModuleCat.of (Polynomial R) (Polynomial R))) ≫
          (powerXRegularBaseChangeIso R n).hom
      exact powerXRegularBaseChangeIso_naturality R n (n - i))

/-- The canonical base change of `powerXOfLE` is isomorphic to the explicit two-periodic free
complex `powerXPeriodicComplex`. -/
noncomputable def powerXOfLEBaseChangePeriodicIso (hi : i ≤ n) :
    (toPeriodicComplex (AdjoinRoot.mk (X ^ n : R[X])) AdjoinRoot.mk_self).obj
        (powerXOfLE R hi) ≅ powerXPeriodicComplex R hi :=
  (CurvedDuplex.toPeriodicComplex _ _).mapIso (powerXOfLEBaseChangeDuplexIso R hi)

/-- The two-periodic complex obtained by reducing `powerXOfLE` modulo `X ^ n` is exact in every
degree. -/
theorem powerXOfLE_baseChange_acyclic (hi : i ≤ n) :
    ((toPeriodicComplex (AdjoinRoot.mk (X ^ n : R[X])) AdjoinRoot.mk_self).obj
      (powerXOfLE R hi)).Acyclic := by
  intro j
  exact (powerXPeriodicComplex_acyclic R hi j).of_iso
    (powerXOfLEBaseChangePeriodicIso R hi).symm

end TauCeti.MatrixFactorization
