/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Valuation.Continuous.Basic
public import TauCeti.Topology.Algebra.Nonarchimedean.Completion.Basic

/-!
# Proper ideals supplied by continuous valuations survive completion

Let `v` be a continuous valuation on a topological ring `A`. Its support is closed: after
restricting `v` to its value group, continuity in Wedhorn's sense is ordinary continuity into
Mathlib's `WithZeroTopology`, and the support is the inverse image of the closed point `0`.

This closedness has an algebraic consequence needed for rational covers. The ideal generated by
the image of `supp v` in the separated completion `Â` is proper. Indeed, the quotient
`A / supp v` is separated, so the map from `A` to its completion factors through a nonzero
completion of that quotient. The induced map `Â → (A / supp v)̂` kills the extended support
but not `1`.

## Main results

* `Valuation.IsContinuous.isClosed_supp`: the support of a continuous valuation is closed.
* `Valuation.IsContinuous.map_supp_completion_ne_top`: the support remains proper after extension
  to the separated completion.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic], Definition 7.7 and Corollary 8.32.

## Provenance

AINTLIB (`github.com/CBirkbeck/AINTLIB`, Apache-2.0), branch `dev/adic-spaces` at commit
`37bbdaeb9ad9e3bc9f0d660feadc2779e455a91c`, file
`projects/AdicSpaces/Adic spaces/IdealLocalizationCompletion.lean`, was consulted to compare the
completion prerequisites used by its conditional approach to Corollary 8.32. It does not contain
the closed-support argument here; no code is ported.
-/

public section

open scoped WithZeroTopology

namespace Valuation.IsContinuous

open Set Topology UniformSpace

section Support

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]
  {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀] {v : Valuation A Γ₀}

/-- **The support of a continuous valuation is closed.**

The topology on the value group is `WithZeroTopology`. Restricting to the value group makes every
nonzero radius a ratio of attained values, so `Valuation.isContinuous_iff_continuous` turns
Wedhorn-continuity into ordinary continuity. The result is then the closed fiber over `0`. -/
theorem isClosed_supp (hv : v.IsContinuous) : IsClosed (v.supp : Set A) := by
  have hv' : v.restrict.IsContinuous :=
    v.isEquiv_restrict.isContinuous_iff.mp hv
  have hcoinitial : ∀ gamma : MonoidWithZeroHom.ValueGroup₀ (.ofClass v), gamma ≠ 0 →
      ∃ b c : A, v.restrict b ≠ 0 ∧ v.restrict c ≠ 0 ∧
        v.restrict b / v.restrict c ≤ gamma := by
    intro gamma hgamma
    obtain ⟨b, c, hb, hc, hbc⟩ := v.exists_div_eq_of_unit (Units.mk0 gamma hgamma)
    exact ⟨b, c, (zero_lt_iff.mp ((v.restrict_pos_iff b).mpr hb)),
      (zero_lt_iff.mp ((v.restrict_pos_iff c).mpr hc)), hbc.le⟩
  have hcontinuous : Continuous v.restrict :=
    (Valuation.isContinuous_iff_continuous hcoinitial).mp hv'
  have hsupp : (v.supp : Set A) = v.restrict ⁻¹' {0} := by
    ext x
    exact (v.mem_supp_iff x).trans v.restrict_eq_zero_iff.symm
  rw [hsupp]
  exact isClosed_singleton.preimage hcontinuous

end Support

section Completion

variable {A : Type*} [CommRing A] [UniformSpace A] [IsUniformAddGroup A] [IsTopologicalRing A]
  {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀] {v : Valuation A Γ₀}

/-- **The support of a continuous valuation remains proper in the separated completion.**

More precisely, the ideal generated by the image of `supp v` under the completion map is not the
unit ideal. The proof factors through the completion of `A / supp v`; closedness of the support
ensures that `1` remains nonzero there. -/
theorem map_supp_completion_ne_top (hv : v.IsContinuous) :
    Ideal.map (Completion.coeRingHom : A →+* Completion A) v.supp ≠ ⊤ := by
  let q : A →+* A ⧸ v.supp := Ideal.Quotient.mk v.supp
  let _ : UniformSpace (A ⧸ v.supp) := IsTopologicalAddGroup.rightUniformSpace _
  have _ : IsUniformAddGroup (A ⧸ v.supp) := isUniformAddGroup_of_addCommGroup
  let f : A →+* Completion (A ⧸ v.supp) := Completion.coeRingHom.comp q
  let F : Completion A →+* Completion (A ⧸ v.supp) :=
    Completion.extensionHom f (Completion.continuous_coeRingHom.comp continuous_quotient_mk')
  have hsupp : IsClosed (v.supp : Set A) := hv.isClosed_supp
  have honeQuotient : (1 : A ⧸ v.supp) ∉ closure ({0} : Set (A ⧸ v.supp)) := by
    intro hone
    have hpre : q ⁻¹' ({0} : Set (A ⧸ v.supp)) = (v.supp : Set A) := by
      ext a
      simp [q, Ideal.Quotient.eq_zero_iff_mem]
    have hopen := (QuotientRing.isOpenMap_coe v.supp).preimage_closure_eq_closure_preimage
      continuous_quotient_mk' ({0} : Set (A ⧸ v.supp))
    rw [hpre] at hopen
    have honeSupp : (1 : A) ∈ closure (v.supp : Set A) := by
      rw [← hopen]
      change Ideal.Quotient.mk v.supp 1 ∈ closure ({0} : Set (A ⧸ v.supp))
      rw [map_one]
      exact hone
    rw [hsupp.closure_eq] at honeSupp
    exact one_ne_zero ((map_one v).symm.trans ((v.mem_supp_iff 1).mp honeSupp))
  have honeCompletion : (1 : Completion (A ⧸ v.supp)) ≠ 0 := by
    intro hone
    have honeKer : (1 : A ⧸ v.supp) ∈
        RingHom.ker (Completion.coeRingHom : (A ⧸ v.supp) →+* Completion (A ⧸ v.supp)) := by
      rw [RingHom.mem_ker]
      exact hone
    rw [Completion.ker_coeRingHom, ← SetLike.mem_coe, Ideal.coe_closure] at honeKer
    exact honeQuotient honeKer
  have hle : Ideal.map (Completion.coeRingHom : A →+* Completion A) v.supp ≤
      RingHom.ker F := by
    rw [Ideal.map_le_iff_le_comap]
    intro a ha
    rw [Ideal.mem_comap, RingHom.mem_ker]
    change Completion.extensionHom f
      (Completion.continuous_coeRingHom.comp continuous_quotient_mk')
        (a : Completion A) = 0
    rw [Completion.extensionHom_coe]
    simp [f, q, Ideal.Quotient.eq_zero_iff_mem, ha]
  intro htop
  have honeKer : (1 : Completion A) ∈ RingHom.ker F := by
    apply hle
    rw [htop]
    exact Submodule.mem_top
  rw [RingHom.mem_ker] at honeKer
  exact honeCompletion (by simpa using honeKer)

end Completion

end Valuation.IsContinuous

end
