/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.IntermediateField.Quadratic
public import Mathlib.Analysis.Real.Sqrt

/-!
# Square-class descent in multiquadratic towers

For a sequence of chosen square roots `root : ℕ → L` over a base field `K`, the tower
`sqrtTower root n = K(root₀, …, rootₙ₋₁)` is the intermediate field generated by the first
`n` roots. This file proves **square-class descent** in characteristic not two: if an
element `y` whose square is `r : K` lies in `sqrtTower root n`, then `r` is a square times
a subset product of the corresponding radicands. The descent is proved for the roots indexed
by an arbitrary finite set, and specialized to the tower and to a finite index type. The
rational-real specialization only
requires the nonnegativity hypotheses needed for `Real.sqrt` to supply the chosen roots.

This is the engine behind the degree computation
`[K(√d₀, …, √dₙ₋₁) : K] = 2ⁿ` for square-class-independent radicands, and hence behind
the structure theory of multiquadratic fields.

## Main definitions and results

* `TauCeti.Multiquadratic.sqrtTower`: the tower `K(root₀, …, rootₙ₋₁)`.
* `TauCeti.Multiquadratic.sqrtTower_def`: the defining adjoin restatement.
* `TauCeti.Multiquadratic.mem_sqrtTower_iff`: membership in the defining adjoin.
* `TauCeti.Multiquadratic.sqrtTower_succ`: the one-step recursion.
* `TauCeti.Multiquadratic.sqrtTower_le_iff`: the universal property of the tower.
* `TauCeti.Multiquadratic.sqrtTower_eq_adjoin_fin_range`: the bridge to a `Fin n` index.
* `TauCeti.Multiquadratic.sqrtTower_root_mem`: the listed roots lie in the tower.
* `TauCeti.Multiquadratic.squareClass_of_sq_mem_finset`: square-class descent for the roots
  indexed by a finite set.
* `TauCeti.Multiquadratic.squareClass_of_sq_mem`: square-class descent in the tower.
* `TauCeti.Multiquadratic.squareClass_of_sq_mem_fintype`: finite-index square-class descent.
* `TauCeti.Multiquadratic.squareClass_of_sqrt_mem`: rational-real square-class descent.

## Provenance

This material is migrated from
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance), the
formalization of L. Alpöge's disproof of the uniform-constant Erdős unit-distance
conjecture, where it was developed for one specific CM field. Here it is stated over an
arbitrary base field of characteristic not two.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- Iterated multiquadratic tower `K(root₀, …, rootₙ₋₁) ⊆ L`. -/
noncomputable def sqrtTower (root : ℕ → L) (n : ℕ) : IntermediateField K L :=
  IntermediateField.adjoin K (root '' Set.Iio n)

/-- The defining adjoin presentation of `sqrtTower`. -/
theorem sqrtTower_def (root : ℕ → L) (n : ℕ) :
    sqrtTower (K := K) root n = IntermediateField.adjoin K (root '' Set.Iio n) :=
  (rfl)

/-- Membership in `sqrtTower` in terms of the defining adjoin. -/
theorem mem_sqrtTower_iff (root : ℕ → L) (n : ℕ) (x : L) :
    x ∈ sqrtTower (K := K) root n ↔
      x ∈ IntermediateField.adjoin K (root '' Set.Iio n) := by
  rw [sqrtTower_def]

/-- The zeroth multiquadratic tower is the base field. -/
@[simp]
theorem sqrtTower_zero (root : ℕ → L) : sqrtTower (K := K) root 0 = ⊥ := by
  simp [sqrtTower]

/-- Adjoining the next square root gives the successor stage of `sqrtTower`. -/
@[simp]
theorem sqrtTower_succ (root : ℕ → L) (n : ℕ) :
    sqrtTower (K := K) root (n + 1)
      = (sqrtTower (K := K) root n) ⊔ IntermediateField.adjoin K {root n} := by
  rw [sqrtTower, sqrtTower, ← Order.succ_eq_add_one, Order.Iio_succ_eq_insert,
    Set.image_insert_eq, Set.insert_eq, IntermediateField.adjoin_union, sup_comm]

/-- The universal property of `sqrtTower`: it is the smallest intermediate field containing
the first `n` chosen roots. -/
@[simp]
theorem sqrtTower_le_iff (root : ℕ → L) (n : ℕ) (F : IntermediateField K L) :
    sqrtTower (K := K) root n ≤ F ↔ ∀ j, j < n → root j ∈ F := by
  simp [sqrtTower, IntermediateField.adjoin_le_iff, Set.subset_def]

/-- The first `n` roots may equivalently be indexed by `Fin n`. -/
theorem sqrtTower_eq_adjoin_fin_range (root : ℕ → L) (n : ℕ) :
    sqrtTower (K := K) root n =
      IntermediateField.adjoin K (Set.range fun j : Fin n => root j) := by
  rw [sqrtTower, ← Fin.range_val, ← Set.range_comp, Function.comp_def]

/-- The universal property of `sqrtTower` using the finite index type `Fin n`. -/
theorem sqrtTower_le_iff_fin (root : ℕ → L) (n : ℕ) (F : IntermediateField K L) :
    sqrtTower (K := K) root n ≤ F ↔ ∀ j : Fin n, root j ∈ F := by
  simp [sqrtTower_le_iff, Fin.forall_iff]

/-- A chosen root indexed before `n` lies in `sqrtTower root n`. -/
theorem sqrtTower_root_mem (root : ℕ → L) {j n : ℕ} (hj : j < n) :
    root j ∈ sqrtTower (K := K) root n :=
  IntermediateField.mem_adjoin_of_mem K ⟨j, hj, rfl⟩

/-- The square of a listed root lies in `sqrtTower root n` as soon as it is in the base
field. -/
theorem sqrtTower_sq_mem {root : ℕ → L} {j : ℕ} {a : K}
    (hroot : root j ^ 2 = algebraMap K L a) (n : ℕ) :
    root j ^ 2 ∈ sqrtTower (K := K) root n :=
  hroot ▸ (sqrtTower (K := K) root n).algebraMap_mem a

/-- **Square-class descent over a finite set of indices.** In characteristic not two, if
`y² = r` over `K` and `y ∈ K(root i | i ∈ S)`, where `root i` is a chosen square root of
`d i`, then `r` is a square times a subset product of the `d i` with `i ∈ S`. -/
theorem squareClass_of_sq_mem_finset {ι : Type*} (d : ι → K) (root : ι → L)
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i)) [NeZero (2 : K)] (S : Finset ι)
    {r : K} {y : L} (hy : y ^ 2 = algebraMap K L r)
    (hmem : y ∈ IntermediateField.adjoin K (root '' S)) :
    ∃ T ⊆ S, ∃ s : K, r = s ^ 2 * ∏ i ∈ T, d i := by
  classical
  have : NeZero (2 : L) :=
    NeZero.nat_of_injective (n := 2) (f := algebraMap K L) (algebraMap K L).injective
  induction S using Finset.induction_on generalizing r y with
  | empty =>
      rw [Finset.coe_empty, Set.image_empty, IntermediateField.adjoin_empty,
        IntermediateField.mem_bot] at hmem
      obtain ⟨s, rfl⟩ := hmem
      refine ⟨∅, Finset.empty_subset _, s, ?_⟩
      rw [Finset.prod_empty, mul_one]
      exact (algebraMap K L).injective (by rw [map_pow, hy])
  | insert i S hiS ih =>
      set F := IntermediateField.adjoin K (root '' S)
      rw [Finset.coe_insert, Set.image_insert_eq, Set.insert_eq,
        IntermediateField.adjoin_union, sup_comm] at hmem
      by_cases hnext : root i ∈ F
      · rw [sup_eq_left.mpr (IntermediateField.adjoin_simple_le_iff.mpr hnext)] at hmem
        obtain ⟨T, hT, s, hs⟩ := ih hy hmem
        exact ⟨T, hT.trans (Finset.subset_insert i S), s, hs⟩
      · have hx2 : root i ^ 2 ∈ F := hroot i ▸ F.algebraMap_mem (d i)
        obtain ⟨a, b, ha, hb, rfl⟩ :=
          TauCeti.IntermediateField.exists_add_mul_of_mem_sup_adjoin_sq hx2 hmem
        -- `(a + b * root i)² = r` lies in `F` while `root i ∉ F`, so the cross term vanishes.
        rcases mul_eq_zero.mp (TauCeti.mul_eq_zero_of_add_mul_sq_mem hx2 hnext ha hb
          (hy ▸ F.algebraMap_mem r)) with rfl | rfl
        · -- `y = b * root i`: then `y * root i = b * d i` lies in `F` and squares to `r * d i`.
          rw [zero_add] at hy
          have hdi : d i ≠ 0 := by
            rintro hdi
            have hroot0 : root i = 0 :=
              (pow_eq_zero_iff two_ne_zero).mp (by rw [hroot, hdi, map_zero])
            exact hnext (hroot0 ▸ zero_mem F)
          have hmul : (b * root i * root i) ^ 2 = algebraMap K L (r * d i) := by
            rw [map_mul, ← hy, ← hroot]
            ring
          have hmul_mem : b * root i * root i ∈ F := by
            rw [mul_assoc, ← sq, hroot]
            exact mul_mem hb (F.algebraMap_mem _)
          obtain ⟨T, hT, s, hs⟩ := ih hmul hmul_mem
          refine ⟨insert i T, Finset.insert_subset_insert i hT, s / d i, ?_⟩
          rw [Finset.prod_insert fun h => hiS (hT h)]
          field_simp
          linear_combination hs
        · rw [zero_mul, add_zero] at hy
          obtain ⟨T, hT, s, hs⟩ := ih hy ha
          exact ⟨T, hT.trans (Finset.subset_insert i S), s, hs⟩

/-- **Square-class descent.** In characteristic not two, if `y² = r` over `K` and
`y ∈ K(root₀, …, rootₙ₋₁)`, where `root j` is a chosen square root of `d j`, then `r` is a
square times a subset product of the `d j` with `j < n`. -/
theorem squareClass_of_sq_mem (d : ℕ → K) (root : ℕ → L)
    (hroot : ∀ j, root j ^ 2 = algebraMap K L (d j)) [NeZero (2 : K)]
    {n : ℕ} {r : K} {y : L} (hy : y ^ 2 = algebraMap K L r)
    (hmem : y ∈ sqrtTower (K := K) root n) :
    ∃ (T : Finset ℕ) (s : K), ↑T ⊆ Set.Iio n ∧ r = s ^ 2 * ∏ j ∈ T, d j := by
  rw [sqrtTower_def, ← Finset.coe_range] at hmem
  obtain ⟨T, hT, s, hs⟩ := squareClass_of_sq_mem_finset d root hroot _ hy hmem
  exact ⟨T, s, by simpa [← Finset.coe_range] using hT, hs⟩

/-- **Finite-index square-class descent.** If `y² = r` over `K` and
`y ∈ K(root i | i : ι)` for a finite index type `ι`, where `root i` is a chosen square
root of `d i`, then `r` is a square times a subset product of the `d i`. -/
theorem squareClass_of_sq_mem_fintype {ι : Type*} [Finite ι] (d : ι → K) (root : ι → L)
    (hroot : ∀ j, root j ^ 2 = algebraMap K L (d j)) [NeZero (2 : K)]
    {r : K} {y : L} (hy : y ^ 2 = algebraMap K L r)
    (hmem : y ∈ IntermediateField.adjoin K (Set.range root)) :
    ∃ (T : Finset ι) (s : K), r = s ^ 2 * ∏ j ∈ T, d j := by
  have := Fintype.ofFinite ι
  obtain ⟨T, -, s, hs⟩ :=
    squareClass_of_sq_mem_finset d root hroot Finset.univ hy (by simpa using hmem)
  exact ⟨T, s, hs⟩

/-- **Square-class descent for real rational square roots.** If `r` is a nonnegative
rational with `√r ∈ ℚ(√c₀, …, √cₙ₋₁)` and every `c j` is nonnegative, then `r` is a
rational square times a subset product of the `c j`. -/
theorem squareClass_of_sqrt_mem (c : ℕ → ℚ) (hc : ∀ j, 0 ≤ c j) {n : ℕ} {r : ℚ} (hr : 0 ≤ r)
    (hmem : (Real.sqrt r : ℝ) ∈ sqrtTower (K := ℚ) (fun j => Real.sqrt (c j)) n) :
    ∃ (T : Finset ℕ) (s : ℚ), ↑T ⊆ Set.Iio n ∧ r = s ^ 2 * ∏ j ∈ T, c j :=
  squareClass_of_sq_mem c _ (fun j => by simpa using Real.sq_sqrt (Rat.cast_nonneg.mpr (hc j)))
    (by simpa using Real.sq_sqrt (Rat.cast_nonneg.mpr hr)) hmem

/-- The real square root of a nonnegative integer squares back to its rational value, in the form
`(√n)² = algebraMap ℚ ℝ n`. This supplies the `hroot` hypothesis of the degree theorem for the real
square roots of integer radicands; `sq_sqrt_natCast` is its natural-number counterpart. -/
theorem sq_sqrt_intCast {n : ℤ} (hn : 0 ≤ n) : (Real.sqrt n) ^ 2 = algebraMap ℚ ℝ (n : ℚ) := by
  rw [Real.sq_sqrt (by exact_mod_cast hn), map_intCast]

end TauCeti.Multiquadratic
