/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import Mathlib.FieldTheory.IsAlgClosed.Basic
public import Mathlib.GroupTheory.Solvable
public import TauCeti.Algebra.AlgebraicGroup.Derived.Basic
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Vanishing
import TauCeti.RingTheory.FiniteType.PointSeparation
import TauCeti.RingTheory.TensorProduct.PointSeparation

/-!
# The derived subgroup is the closure of the point commutator subgroup

For a reduced affine group of finite type over an algebraically closed field, its derived
defining ideal consists exactly of the functions vanishing on the abstract commutator
subgroup of its rational points. Thus its scheme-theoretic derived subgroup is the reduced
closed subgroup generated by those commutators. This comparison is needed to pass between
the geometric derived subgroup and abstract solvability in the Lie--Kolchin induction.

Since commutators of closures lie in the closure of the commutator
(`TauCeti.HopfIdeal.commutator_quotientPointsSubgroup_vanishingIdeal_le`), the rational points of
the derived subgroup have strictly smaller derived length than those of the ambient group. This is
the measure the Lie--Kolchin induction decreases.

## Main declarations

* `TauCeti.CommHopfAlgCat.derivedDefiningIdeal_eq_vanishingIdeal_commutator`: the derived
  subgroup is the closure of the abstract commutator subgroup of rational points.
* `TauCeti.CommHopfAlgCat.derivedSeries_points_derived_eq_bot`: if the rational points have
  derived length at most `n + 1`, those of the derived subgroup have derived length at most `n`.

## References

* J. S. Milne, *Algebraic Groups* (2017), §6d.
* A. Borel, *Linear Algebraic Groups*, §2.3 and §10.5.
-/

public section

open WithConv
open scoped commutatorElement

namespace TauCeti.CommHopfAlgCat

variable {k H : Type*} [Field k] [IsAlgClosed k] [CommRing H] [HopfAlgebra k H]
  [Algebra.FiniteType k H] [IsReduced H]

/-- The derived subgroup is the reduced closed subgroup generated by the abstract
commutator subgroup of rational points. -/
theorem derivedDefiningIdeal_eq_vanishingIdeal_commutator :
    derivedDefiningIdeal (R := k) H =
      HopfIdeal.vanishingIdeal (commutator (WithConv (H →ₐ[k] k))) := by
  apply le_antisymm
  · exact (HopfIdeal.le_vanishingIdeal_iff _ _).mpr
      (commutator_le_quotientPointsSubgroup_of_le_derivedDefiningIdeal
        (_root_.CommHopfAlgCat.of k H) _ le_rfl (CommAlgCat.of k k))
  · apply (le_derivedDefiningIdeal_iff H _).mpr
    intro x hx
    apply RingHom.mem_ker.mpr
    apply tensor_eq_zero_of_forall_productMap_eq_zero
      (fun f : H →ₐ[k] k ↦ f) (fun f : H →ₐ[k] k ↦ f)
      (fun a ha ↦ eq_of_forall_algHom_apply_eq (k := k) (K := k)
        (fun f ↦ (ha f).trans (map_zero f).symm))
      (fun a ha ↦ eq_of_forall_algHom_apply_eq (k := k) (K := k)
        (fun f ↦ (ha f).trans (map_zero f).symm))
    intro g h
    simp only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe]
    rw [← AlgHom.comp_apply, HopfAlgebra.productMap_comp_commutatorAlgHom
      (toConv g) (toConv h)]
    exact (HopfIdeal.mem_vanishingIdeal _ x).mp hx
      ⟨⁅toConv g, toConv h⁆,
        Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)⟩

/-- A function vanishes on the derived subgroup exactly when it vanishes on every
element of the abstract commutator subgroup of rational points. -/
@[simp] theorem mem_derivedDefiningIdeal_iff_forall_commutator_apply_eq_zero (x : H) :
    x ∈ derivedDefiningIdeal (R := k) H ↔
      ∀ g : commutator (WithConv (H →ₐ[k] k)), g.val.ofConv x = 0 := by
  rw [derivedDefiningIdeal_eq_vanishingIdeal_commutator, HopfIdeal.mem_vanishingIdeal]

/-- **The derived subgroup has strictly shorter derived length.** If the rational points of a
reduced finite-type affine group over an algebraically closed field have derived length at most
`n + 1`, then the rational points of its scheme-theoretic derived subgroup have derived length at
most `n`. -/
theorem derivedSeries_points_derived_eq_bot {n : ℕ}
    (hn : derivedSeries (WithConv (H →ₐ[k] k)) (n + 1) = ⊥) :
    derivedSeries (WithConv (quotient (_root_.CommHopfAlgCat.of k H)
      (derivedDefiningIdeal (R := k) H) →ₐ[k] k)) n = ⊥ := by
  let A := _root_.CommHopfAlgCat.of k H
  let cl (S : Subgroup (WithConv (H →ₐ[k] k))) :=
    quotientPointsSubgroup A (HopfIdeal.vanishingIdeal S) (CommAlgCat.of k k)
  let φ := (quotientPointsHom A (derivedDefiningIdeal H) (CommAlgCat.of k k)).hom
  -- The `i`-th derived subgroup of the derived points lies in the closure of the `(i + 1)`-st
  -- derived subgroup of the ambient points.
  have hle (i : ℕ) : (derivedSeries _ i).map φ ≤ cl (derivedSeries _ (i + 1)) := by
    induction i with
    | zero =>
      rw [derivedSeries_zero, ← MonoidHom.range_eq_map, derivedSeries_one]
      -- `quotientPointsSubgroup` is defined as the range of `quotientPointsHom`.
      exact (congrArg (fun I ↦ quotientPointsSubgroup A I (CommAlgCat.of k k))
        derivedDefiningIdeal_eq_vanishingIdeal_commutator).le
    | succ i ih =>
      rw [derivedSeries_succ, Subgroup.map_commutator, derivedSeries_succ _ (i + 1)]
      exact (Subgroup.commutator_mono ih ih).trans
        (HopfIdeal.commutator_quotientPointsSubgroup_vanishingIdeal_le _ _)
  have hmap : (derivedSeries _ n).map φ = ⊥ := by
    have h := hle n
    rw [hn] at h
    exact le_bot_iff.mp (h.trans HopfIdeal.quotientPointsSubgroup_vanishingIdeal_bot.le)
  exact (Subgroup.map_eq_bot_iff_of_injective _
    (quotientPointsHom_injective A _ (CommAlgCat.of k k))).mp hmap

end TauCeti.CommHopfAlgCat
