/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.DiscreteValuationRing.Basic
public import Mathlib.RingTheory.PowerBasis
public import TauCeti.FieldTheory.IntermediateField.Adjoin.EqTop
public import TauCeti.RingTheory.LocalRing.Monogenic
import Mathlib.Algebra.Polynomial.Lifts
import Mathlib.FieldTheory.Minpoly.IsIntegrallyClosed
import Mathlib.FieldTheory.PrimitiveElement
-- for `UniqueFactorizationMonoid.instIsIntegrallyClosed`, which `PowerBasis.ofAdjoinEqTop'` needs
import Mathlib.RingTheory.Polynomial.RationalRoot

/-!
# Monogenicity of a finite extension of discrete valuation rings

Let `S` be a discrete valuation ring, finite over a discrete valuation subring `R`, and assume
the residue extension `𝓀(S)/𝓀(R)` is separable.  This file proves that `S = R[β]` for a single
`β : S`.  Both the ramified and the unramified case are covered; Mathlib's
`IsLocalRing.exists_adjoin_eq_top` covers only the unramified (finite étale) case, where the
generator may be taken to be any lift of a primitive element of the residue extension.

The proof is Serre's: pick a lift `a` of a primitive element of the residue extension and a
polynomial `g : R[X]` lifting its minimal polynomial.  Then `g(a)` lies in the maximal ideal and
`g'(a)` is a unit, so one Newton step, replacing `a` by `a + π` for a uniformizer `π` when it is
needed, arranges
that `g(β)` *generates* the maximal ideal.  The subring `R[β]` then meets every residue class
modulo `𝓂(S)` and contains a uniformizer, hence meets every residue class modulo `𝓂(S) ^ n`;
taking `n` large enough that `𝓂(S) ^ n ⊆ 𝓂(R) S`, Nakayama's lemma gives `R[β] = S`.

Only the existence of the generator needs the two rings to be discrete valuation rings. The
generation criterion and the steps it is assembled from hold for a module-finite extension of
local rings and are developed in `TauCeti.RingTheory.LocalRing.Monogenic`.

## Main results

* `TauCeti.IsDiscreteValuationRing.exists_adjoin_eq_top`: a finite extension of discrete
  valuation rings with separable residue extension is monogenic.
* `TauCeti.IsDiscreteValuationRing.nonempty_powerBasis`: the integral basis a generator produces,
  via Mathlib's `PowerBasis.ofAdjoinEqTop'`.
* `TauCeti.IsDiscreteValuationRing.exists_adjoin_eq_top_and_intermediateField_adjoin_eq_top`: a
  generator of `S` over `R` also generates the fraction field of `S` over that of `R`.

## References

* [J.-P. Serre, *Corps locaux*][serre1968], Chapter III, §6, Proposition 12.
-/

public section

open IsLocalRing Polynomial

namespace TauCeti

namespace IsDiscreteValuationRing

variable {R S : Type*} [CommRing R] [CommRing S] [IsDomain R] [IsDomain S]
  [IsDiscreteValuationRing R] [IsDiscreteValuationRing S] [Algebra R S] [Module.Finite R S]
  [FaithfulSMul R S]

private theorem residue_comp_algebraMap :
    (algebraMap (ResidueField R) (ResidueField S)).comp (residue R) =
      (residue S).comp (algebraMap R S) :=
  RingHom.ext fun x => ResidueField.algebraMap_residue x

/-- **Local monogenicity.**  A finite extension of discrete valuation rings whose residue
extension is separable is generated by a single element.  Completeness of `R` is not needed: it
enters the classical statement only to guarantee that the integral closure of `R` in a finite
field extension is again a discrete valuation ring, which is here a hypothesis on `S`. -/
theorem exists_adjoin_eq_top [Algebra.IsSeparable (ResidueField R) (ResidueField S)] :
    ∃ β : S, Algebra.adjoin R {β} = ⊤ := by
  obtain ⟨α, hα⟩ := Field.exists_primitive_element (ResidueField R) (ResidueField S)
  obtain ⟨a, rfl⟩ := residue_surjective (R := S) α
  obtain ⟨π, hπ⟩ := _root_.IsDiscreteValuationRing.exists_irreducible S
  -- A lift `g : R[X]` of the minimal polynomial of the residue of `a`.
  obtain ⟨g, hg⟩ := (mem_lifts _).mp
    (mem_lifts_of_surjective residue_surjective (minpoly (ResidueField R) (residue S a)))
  have hbridge : ∀ x : S, residue S (aeval x g) =
      aeval (residue S x) (minpoly (ResidueField R) (residue S a)) := fun x => by
    rw [map_aeval_eq_aeval_map residue_comp_algebraMap, hg]
  have hbridge' : ∀ x : S, residue S (aeval x (derivative g)) =
      aeval (residue S x) (derivative (minpoly (ResidueField R) (residue S a))) := fun x => by
    rw [map_aeval_eq_aeval_map residue_comp_algebraMap, ← derivative_map, hg]
  -- `g` has a simple root at `a` modulo the maximal ideal, so a Newton step applies.
  have hval : (g.map (algebraMap R S)).eval a ∈ maximalIdeal S := by
    rw [eval_map, ← aeval_def, ← residue_eq_zero_iff]
    exact (hbridge a).trans (minpoly.aeval _ _)
  have hder : IsUnit ((derivative (g.map (algebraMap R S))).eval a) := by
    rw [derivative_map, eval_map, ← aeval_def, ← residue_ne_zero_iff_isUnit, hbridge' a]
    exact (Algebra.IsSeparable.isSeparable _ _).aeval_derivative_ne_zero (minpoly.aeval _ _)
  obtain ⟨β, hβa, hβ⟩ := TauCeti.IsLocalRing.exists_span_eval_eq_maximalIdeal
    hπ.maximalIdeal_eq.symm hval hder
  have hres : residue S β = residue S a := by
    rw [← sub_eq_zero, ← map_sub, residue_eq_zero_iff]; exact hβa
  refine ⟨β, TauCeti.IsLocalRing.adjoin_eq_top_of_span_eval_eq_maximalIdeal (g := g) ?_ ?_⟩
  · exact hres ▸ Algebra.adjoin_eq_top_of_primitive_element (IsAlgebraic.of_finite _ _) hα
  · rwa [aeval_def, ← eval_map]

/-- A finite extension of discrete valuation rings with separable residue extension admits a
power basis: the integral basis `1, β, …, β ^ (n - 1)` attached to a generator `β`. -/
theorem nonempty_powerBasis [Algebra.IsSeparable (ResidueField R) (ResidueField S)] :
    Nonempty (PowerBasis R S) :=
  let ⟨β, h⟩ := exists_adjoin_eq_top (R := R) (S := S)
  ⟨PowerBasis.ofAdjoinEqTop' (IsIntegral.of_finite R β) h⟩

/-- A generator of `S` over `R` also generates the fraction field of `S` over that of `R`, so the
power basis of `TauCeti.IsDiscreteValuationRing.nonempty_powerBasis` is built from a primitive
element of the extension of fraction fields. -/
theorem exists_adjoin_eq_top_and_intermediateField_adjoin_eq_top
    [Algebra.IsSeparable (ResidueField R) (ResidueField S)] (K L : Type*) [Field K] [Field L]
    [Algebra R K] [Algebra R L] [Algebra S L] [Algebra K L] [IsScalarTower R S L]
    [IsScalarTower R K L] [IsFractionRing S L] :
    ∃ β : S, Algebra.adjoin R {β} = ⊤ ∧ IntermediateField.adjoin K {algebraMap S L β} = ⊤ :=
  let ⟨β, h⟩ := exists_adjoin_eq_top (R := R) (S := S)
  ⟨β, h, TauCeti.IntermediateField.adjoin_eq_top_of_algebra_adjoin_eq_top h⟩

/-- **The totally ramified case.**  If the residue extension is trivial, every uniformizer of `S`
generates `S` over `R`.  This is the direction of the Eisenstein description of a totally ramified
extension that produces an integral power basis. -/
theorem adjoin_eq_top_of_residue_surjective_of_irreducible
    (hsurj : Function.Surjective (algebraMap (ResidueField R) (ResidueField S)))
    {π : S} (hπ : Irreducible π) : Algebra.adjoin R {π} = ⊤ :=
  TauCeti.IsLocalRing.adjoin_eq_top_of_residue_surjective_of_span_eq_maximalIdeal hsurj
    hπ.maximalIdeal_eq.symm

end IsDiscreteValuationRing

end TauCeti
