/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Analysis.Complex.Basic
public import Mathlib.Analysis.Normed.Field.UnitBall
public import Mathlib.Analysis.Normed.Group.BallSphere
public import Mathlib.CategoryTheory.SingleObj
public import TauCeti.AlgebraicTopology.FundamentalGroupoid.Pushout

import Mathlib.Analysis.Complex.Convex
import Mathlib.Analysis.Convex.PathConnected
import Mathlib.Analysis.Normed.Module.Ball.Action
import Mathlib.Topology.Order.IntermediateValue
import TauCeti.AlgebraicTopology.Sphere.Puncture
import TauCeti.Analysis.Normed.Module.Normalize
import TauCeti.CategoryTheory.Groupoid.SingleObj
import TauCeti.Topology.Homotopy.Path

/-!
# Van Kampen for the circle covered by two arcs

This file checks the two-set van Kampen theorem for fundamental groupoids on a set of basepoints,
`TauCeti.isPushout_fundamentalGroupoidOn`, on the simplest cover whose intersection is not path
connected. The unit circle `S¹ = sphere (0 : ℂ) 1` is covered by the two open arcs
`upper = S¹ ∖ {-i}` and `lower = S¹ ∖ {i}`. Each arc is contractible, but their intersection
`S¹ ∖ {i, -i}` has two path components, the right and the left open half circles, and `1` and `-1`
cannot be joined inside it (`TauCeti.CircleArcs.not_joinedIn_one_neg_one`). The based theorem
`TauCeti.isPushout_fundamentalGroup` therefore does not apply with any basepoint, while the
groupoid theorem applies with the two basepoints `{1, -1}`.

The pushout square on `{1, -1}` is computed as follows. The fundamental groupoids of the arcs on
`{1, -1}` are indiscrete, since the arcs are simply connected, and that of the intersection is
discrete. A group-valued consequence is that a functor out of the fundamental groupoid of `S¹` on
`{1, -1}` to a group `K` may send the classes of a path from `1` to `-1` in `upper` and of one in
`lower` to arbitrary elements of `K` (`TauCeti.CircleArcs.lift`), and is determined by these two
values (`TauCeti.CircleArcs.functor_ext`).

Only after choosing the basepoint does the familiar based statement follow: if `γ₊` runs from `1`
to `-1` in `upper` and `γ₋` does so in `lower`, then the class of the loop `γ₊ · γ₋⁻¹` generates
`π₁(S¹, 1)` freely (`TauCeti.CircleArcs.zpowersHom_bijective`). Writing `ℤ` additively, the
loop is sent to `1` by the `ℤ`-valued functor with values `0` on `γ₊` and `-1` on `γ₋`, which gives
injectivity, and every loop is a power of it because conjugating by `γ₊` retracts the groupoid onto
`π₁(S¹, 1)` and that retraction agrees with the `π₁(S¹, 1)`-valued functor with values the identity
on `γ₊` and `(γ₊ · γ₋⁻¹)⁻¹` on `γ₋`. The covering-space computation of the same group is
`Circle.fundamentalGroupMulEquiv`.

## Main declarations

* `TauCeti.CircleArcs.upper`, `TauCeti.CircleArcs.lower`, `TauCeti.CircleArcs.basepoints`: the
  two arcs and the two basepoints.
* `TauCeti.CircleArcs.not_joinedIn_one_neg_one`: the intersection of the arcs is not path
  connected.
* `TauCeti.CircleArcs.isPushout`: the van Kampen pushout square of the cover on `{1, -1}`.
* `TauCeti.CircleArcs.lift`, `TauCeti.CircleArcs.lift_map_upper`,
  `TauCeti.CircleArcs.lift_map_lower`, `TauCeti.CircleArcs.functor_ext`: the group-valued
  lift-and-uniqueness property for one arrow `1 ⟶ -1` in each arc.
* `TauCeti.CircleArcs.zpowersHom_bijective`: the based consequence, `π₁(S¹, 1) ≅ ℤ` generated by
  the loop through the two arcs.

## References

* R. Brown, *Topology and Groupoids*, 3rd ed., Section 6.7 and Section 6.8 (the circle).
* A. Hatcher, *Algebraic Topology*, Cambridge University Press, 2002, Section 1.2.
-/

public section

noncomputable section

open CategoryTheory Complex Metric Set

namespace TauCeti.CircleArcs

/-! ### The cover of the circle by two arcs -/

/-- The unit circle with the point `-i` removed: an open arc containing the closed upper half
circle. -/
def upper : Set (sphere (0 : ℂ) 1) := {z | (z : ℂ) ≠ -I}

/-- The unit circle with the point `i` removed: an open arc containing the closed lower half
circle. -/
def lower : Set (sphere (0 : ℂ) 1) := {z | (z : ℂ) ≠ I}

/-- The two basepoints `1` and `-1`, one in each path component of `upper ∩ lower`. -/
def basepoints : Set (sphere (0 : ℂ) 1) := {1, -1}

@[simp]
theorem mem_upper {z : sphere (0 : ℂ) 1} : z ∈ upper ↔ (z : ℂ) ≠ -I := Iff.rfl

@[simp]
theorem mem_lower {z : sphere (0 : ℂ) 1} : z ∈ lower ↔ (z : ℂ) ≠ I := Iff.rfl

@[simp]
theorem mem_basepoints {z : sphere (0 : ℂ) 1} : z ∈ basepoints ↔ z = 1 ∨ z = -1 := Iff.rfl

theorem isOpen_upper : IsOpen upper :=
  isOpen_ne_fun continuous_subtype_val continuous_const

theorem isOpen_lower : IsOpen lower :=
  isOpen_ne_fun continuous_subtype_val continuous_const

/-- The two arcs cover the circle. -/
theorem upper_union_lower : upper ∪ lower = univ := by
  refine eq_univ_of_forall fun z ↦ ?_
  by_contra h
  simp only [mem_union, mem_upper, mem_lower, not_or, not_not] at h
  have h' := h.1.symm.trans h.2
  simp [Complex.ext_iff] at h'
  norm_num at h'

private theorem upper_eq : upper = {-⟨I, by simp⟩}ᶜ := by
  ext z
  simp [Subtype.ext_iff]

private theorem lower_eq : lower = {⟨I, by simp⟩}ᶜ := by
  ext z
  simp [Subtype.ext_iff]

instance contractibleSpace_upper : ContractibleSpace upper := by
  rw [upper_eq]
  exact contractibleSpace_sphere_compl_singleton _

instance contractibleSpace_lower : ContractibleSpace lower := by
  rw [lower_eq]
  exact contractibleSpace_sphere_compl_singleton _

/-- A point of both arcs is not `±i`, so its real part is nonzero. -/
theorem re_ne_zero_of_mem_inter {z : sphere (0 : ℂ) 1} (hz : z ∈ upper ∩ lower) :
    (z : ℂ).re ≠ 0 := by
  intro h0
  have hsq : (z : ℂ).im * (z : ℂ).im = 1 := by
    have h := Complex.sq_norm (z : ℂ)
    rw [norm_eq_of_mem_sphere z, normSq_apply, h0] at h
    linarith
  rcases mul_self_eq_one_iff.mp hsq with h | h
  · exact hz.2 (Complex.ext (by simp [h0]) (by simp [h]))
  · exact hz.1 (Complex.ext (by simp [h0]) (by simp [h]))

/-- A point of the circle with nonzero real part lies in both arcs. -/
private theorem mem_inter_of_re_ne_zero {z : sphere (0 : ℂ) 1} (hz : (z : ℂ).re ≠ 0) :
    z ∈ upper ∩ lower := by
  refine ⟨fun h ↦ hz ?_, fun h ↦ hz ?_⟩ <;> simp [h]

/-- The open right half circle is path connected: it is the radial projection of the open right
half plane. -/
private theorem isPathConnected_re_pos :
    IsPathConnected {z : sphere (0 : ℂ) 1 | 0 < (z : ℂ).re} := by
  let H : Set ℂ := {w | 0 < w.re}
  have : PathConnectedSpace H := isPathConnected_iff_pathConnectedSpace.mp
    ((convex_halfSpace_re_gt 0).isPathConnected ⟨1, by simp⟩)
  have hne : ∀ w : H, (w : ℂ) ≠ 0 := fun w h ↦ by
    have hw : 0 < (w : ℂ).re := w.2
    simp [h] at hw
  let f := normalizeToSphere (fun w : H ↦ (w : ℂ)) continuous_subtype_val hne
  convert isPathConnected_range f.continuous
  ext z
  constructor
  · intro hz
    exact ⟨⟨z, hz⟩, Subtype.ext (by
      simpa [f] using NormedSpace.normalize_eq_self_of_norm_eq_one (norm_eq_of_mem_sphere z))⟩
  · rintro ⟨w, rfl⟩
    have hw : 0 < (w : ℂ).re := w.2
    simp only [mem_ofPred_eq, f, coe_normalizeToSphere_apply, NormedSpace.normalize,
      Complex.real_smul, re_ofReal_mul]
    exact mul_pos (inv_pos.mpr (norm_pos_iff.mpr (hne w))) hw

/-- Every point of `upper ∩ lower` is joined inside `upper ∩ lower` to one of the basepoints. -/
private theorem exists_joinedIn_inter {z : sphere (0 : ℂ) 1} (hz : z ∈ upper ∩ lower) :
    ∃ y ∈ basepoints, JoinedIn (upper ∩ lower) z y := by
  have hsub : {z : sphere (0 : ℂ) 1 | 0 < (z : ℂ).re} ⊆ upper ∩ lower :=
    fun z hz ↦ mem_inter_of_re_ne_zero (ne_of_gt hz)
  rcases (re_ne_zero_of_mem_inter hz).lt_or_gt with h | h
  · refine ⟨-1, Or.inr rfl, ?_⟩
    have hj := isPathConnected_re_pos.joinedIn (-z) (by simpa using h) 1 (by simp)
    have hj' := hj.map (f := fun x : sphere (0 : ℂ) 1 ↦ -x) continuous_neg.continuousOn
    simp only [neg_neg] at hj'
    refine hj'.mono ?_
    rintro _ ⟨x, hx, rfl⟩
    exact mem_inter_of_re_ne_zero (by simpa using (ne_of_gt hx))
  · exact ⟨1, Or.inl rfl, (isPathConnected_re_pos.joinedIn z h 1 (by simp)).mono hsub⟩

/-- Inside `upper ∩ lower` the sign of the real part is constant along paths. -/
private theorem re_pos_iff_of_joinedIn {x y : sphere (0 : ℂ) 1} (h : JoinedIn (upper ∩ lower) x y) :
    0 < (x : ℂ).re ↔ 0 < (y : ℂ).re := by
  obtain ⟨γ, hγ⟩ := h
  let f : unitInterval → ℝ := fun t ↦ ((γ t : sphere (0 : ℂ) 1) : ℂ).re
  have hf : Continuous f := continuous_re.comp (continuous_subtype_val.comp γ.continuous)
  have hne : ∀ t, f t ≠ 0 := fun t ↦ re_ne_zero_of_mem_inter (hγ t)
  have h0 : f 0 = (x : ℂ).re := by simp [f]
  have h1 : f 1 = (y : ℂ).re := by simp [f]
  constructor <;> intro hpos <;> by_contra hneg
  · obtain ⟨t, ht⟩ := intermediate_value_univ 1 0 hf
      ⟨(h1 ▸ not_lt.mp hneg), h0 ▸ hpos.le⟩
    exact hne t ht
  · obtain ⟨t, ht⟩ := intermediate_value_univ 0 1 hf
      ⟨(h0 ▸ not_lt.mp hneg), h1 ▸ hpos.le⟩
    exact hne t ht

/-- **The intersection of the two arcs is not path connected**: `1` and `-1` cannot be joined
inside it. -/
theorem not_joinedIn_one_neg_one : ¬ JoinedIn (upper ∩ lower) 1 (-1) := fun h ↦
  absurd ((re_pos_iff_of_joinedIn h).mp (by simp)) (by simp)

/-- Two basepoints joined inside `upper ∩ lower` are equal. -/
private theorem eq_of_joinedIn_inter {a b : sphere (0 : ℂ) 1} (ha : a ∈ basepoints)
    (hb : b ∈ basepoints) (h : JoinedIn (upper ∩ lower) a b) : a = b := by
  rcases ha with rfl | rfl <;> rcases hb with rfl | rfl
  · rfl
  · exact absurd h not_joinedIn_one_neg_one
  · exact absurd h.symm not_joinedIn_one_neg_one
  · rfl

private theorem joinedIn_basepoint (T : Set (sphere (0 : ℂ) 1)) [PathConnectedSpace T]
    (h1 : (1 : sphere (0 : ℂ) 1) ∈ T) {z : sphere (0 : ℂ) 1} (hz : z ∈ T) :
    ∃ y ∈ basepoints, JoinedIn T z y :=
  ⟨1, Or.inl rfl, (isPathConnected_iff_pathConnectedSpace.mpr ‹_›).joinedIn z hz 1 h1⟩

private theorem one_mem_upper : (1 : sphere (0 : ℂ) 1) ∈ upper := by
  simp [Complex.ext_iff]

private theorem one_mem_lower : (1 : sphere (0 : ℂ) 1) ∈ lower := by
  simp [Complex.ext_iff]

/-- **The van Kampen square of the circle covered by two arcs**, on the basepoints `{1, -1}`. The
intersection of the arcs has two path components, so a single basepoint would not do. -/
theorem isPushout :
    IsPushout (C := Grpd.{0, 0})
      (Z := Grpd.of (FundamentalGroupoidOn (Subtype.val ⁻¹' basepoints : Set ↥(upper ∩ lower))))
      (X := Grpd.of (FundamentalGroupoidOn (Subtype.val ⁻¹' basepoints : Set upper)))
      (Y := Grpd.of (FundamentalGroupoidOn (Subtype.val ⁻¹' basepoints : Set lower)))
      (P := Grpd.of (FundamentalGroupoidOn basepoints))
      (FundamentalGroupoidOn.map (ContinuousMap.inclusion inter_subset_left) fun _ h ↦ h)
      (FundamentalGroupoidOn.map (ContinuousMap.inclusion inter_subset_right) fun _ h ↦ h)
      (FundamentalGroupoidOn.map (ContinuousMap.subtypeVal upper) fun _ h ↦ h)
      (FundamentalGroupoidOn.map (ContinuousMap.subtypeVal lower) fun _ h ↦ h) :=
  isPushout_fundamentalGroupoidOn (fun _ hz ↦ joinedIn_basepoint upper one_mem_upper hz)
    (fun _ hz ↦ joinedIn_basepoint lower one_mem_lower hz) (fun _ hz ↦ exists_joinedIn_inter hz)
    (by rw [isOpen_upper.interior_eq, isOpen_lower.interior_eq, upper_union_lower])

/-! ### The fundamental groupoid on the two basepoints is free on the two arcs -/

/-- The basepoint `1`, as an object of the fundamental groupoid of the circle on `basepoints`. -/
abbrev one : FundamentalGroupoidOn basepoints := ⟨1, mem_basepoints.mpr (Or.inl rfl)⟩

/-- The basepoint `-1`, as an object of the fundamental groupoid of the circle on `basepoints`. -/
abbrev negOne : FundamentalGroupoidOn basepoints := ⟨-1, mem_basepoints.mpr (Or.inr rfl)⟩

private theorem neg_one_ne_one : (-1 : sphere (0 : ℂ) 1) ≠ 1 :=
  (ne_neg_of_mem_unit_sphere ℝ (1 : sphere (0 : ℂ) 1)).symm

variable {T : Set (sphere (0 : ℂ) 1)}

/-- The basepoint `1` of an arc `T`, as an object of the fundamental groupoid of `T` on the
basepoints. -/
private abbrev oneIn (h1 : (1 : sphere (0 : ℂ) 1) ∈ T) :
    FundamentalGroupoidOn (Subtype.val ⁻¹' basepoints : Set T) :=
  ⟨⟨1, h1⟩, mem_basepoints.mpr (Or.inl rfl)⟩

/-- The morphism of the fundamental groupoid of the arc `T` on the basepoints given by a path from
`1` to `-1` in `T`. -/
private def arcHom (γ : Path (1 : sphere (0 : ℂ) 1) (-1)) (hγ : ∀ t, γ t ∈ T) :
    oneIn (T := T) (γ.source ▸ hγ 0) ⟶ ⟨⟨-1, γ.target ▸ hγ 1⟩, mem_basepoints.mpr (Or.inr rfl)⟩ :=
  InducedCategory.homMk (Path.Homotopic.Quotient.mk
    (Path.codRestrict (x := ⟨1, γ.source ▸ hγ 0⟩) (y := ⟨-1, γ.target ▸ hγ 1⟩) γ hγ))

/-- Including the arc into the circle sends `arcHom γ hγ` to the class of `γ`. -/
private theorem map_arcHom (γ : Path (1 : sphere (0 : ℂ) 1) (-1)) (hγ : ∀ t, γ t ∈ T) :
    (FundamentalGroupoidOn.map (ContinuousMap.subtypeVal T) fun _ h ↦ h).map (arcHom γ hγ) =
      (InducedCategory.homMk (Path.Homotopic.Quotient.mk γ) : one ⟶ negOne) := by
  ext
  exact congrArg Path.Homotopic.Quotient.mk
    (Path.map_codRestrict (x := ⟨1, γ.source ▸ hγ 0⟩) (y := ⟨-1, γ.target ▸ hγ 1⟩) γ hγ)

/-- On a simply connected arc `T` containing a path from `1` to `-1`, two functors to
`SingleObj K` agree once they agree on that path. -/
private theorem functor_ext_arc [SimplyConnectedSpace T] (γ : Path (1 : sphere (0 : ℂ) 1) (-1))
    (hγ : ∀ t, γ t ∈ T) {K : Type*} [Monoid K]
    {F G : FundamentalGroupoidOn (Subtype.val ⁻¹' basepoints : Set T) ⥤ SingleObj K}
    (h : F.map (arcHom γ hγ) = G.map (arcHom γ hγ)) : F = G := by
  refine Groupoid.functor_singleObj_ext_of_map_eq (oneIn (γ.source ▸ hγ 0)) (fun x ↦ ?_)
    fun x f ↦ ?_
  · exact ⟨InducedCategory.homMk (Path.Homotopic.Quotient.mk (PathConnectedSpace.somePath _ _))⟩
  · -- The only morphisms out of `1` are the identity and the class of `γ`.
    obtain ⟨⟨z, hzT⟩, hz⟩ := x
    obtain rfl | rfl := mem_basepoints.mp hz
    · rw [Subsingleton.elim f (𝟙 _), F.map_id, G.map_id]
      rfl
    · rwa [Subsingleton.elim f (arcHom γ hγ)]

/-- The functor out of the fundamental groupoid of an arc `T` on the basepoints which sends every
morphism from `1` to `-1` to `k`. -/
private def arcFunctor (T : Set (sphere (0 : ℂ) 1)) {K : Type*} [Group K] (k : K) :
    FundamentalGroupoidOn (Subtype.val ⁻¹' basepoints : Set T) ⥤ SingleObj K :=
  open scoped Classical in
  SingleObj.differenceFunctor fun x ↦ if (x.1 : sphere (0 : ℂ) 1) = 1 then 1 else k

private theorem arcFunctor_map_arcHom {K : Type*} [Group K] (k : K)
    (γ : Path (1 : sphere (0 : ℂ) 1) (-1)) (hγ : ∀ t, γ t ∈ T) :
    (arcFunctor T k).map (arcHom γ hγ) = k := by
  simp [arcFunctor, neg_one_ne_one]

/-- The two arc functors agree on the fundamental groupoid of `upper ∩ lower` on the basepoints:
there, every morphism joins a basepoint to itself. -/
private theorem arcFunctor_comp_eq {K : Type*} [Group K] (kA kB : K) :
    FundamentalGroupoidOn.map (S := (Subtype.val ⁻¹' basepoints : Set ↥(upper ∩ lower)))
        (ContinuousMap.inclusion inter_subset_left) (fun _ h ↦ h) ⋙ arcFunctor upper kA =
      FundamentalGroupoidOn.map (S := (Subtype.val ⁻¹' basepoints : Set ↥(upper ∩ lower)))
        (ContinuousMap.inclusion inter_subset_right) (fun _ h ↦ h) ⋙ arcFunctor lower kB := by
  refine CategoryTheory.Functor.ext (fun _ ↦ rfl) fun a b f ↦ ?_
  obtain ⟨γ, -⟩ := Quotient.exists_rep f.hom
  have hab : (a.1 : sphere (0 : ℂ) 1) = b.1 := eq_of_joinedIn_inter a.2 b.2
    ⟨γ.map continuous_subtype_val, fun t ↦ (γ t).2⟩
  rw [Functor.comp_map, Functor.comp_map, arcFunctor, arcFunctor,
    SingleObj.differenceFunctor_map, SingleObj.differenceFunctor_map]
  simp [FundamentalGroupoidOn.map, hab]

variable {K : Type} [Group K]

/-- The functor out of the fundamental groupoid of the circle on `{1, -1}` which sends the class of
a path from `1` to `-1` in `upper` to `kA`, and that of one in `lower` to `kB`. It exists by the
van Kampen pushout `TauCeti.CircleArcs.isPushout`. -/
def lift (kA kB : K) : FundamentalGroupoidOn basepoints ⥤ SingleObj K :=
  isPushout.desc (W := Grpd.of (SingleObj K)) (arcFunctor upper kA) (arcFunctor lower kB)
    (arcFunctor_comp_eq kA kB)

/-- `TauCeti.CircleArcs.lift` sends the class of a path from `1` to `-1` in `upper` to `kA`. -/
@[simp]
theorem lift_map_upper (kA kB : K) (γ : Path (1 : sphere (0 : ℂ) 1) (-1))
    (hγ : ∀ t, γ t ∈ upper) :
    (lift kA kB).map (InducedCategory.homMk (Path.Homotopic.Quotient.mk γ) : one ⟶ negOne) =
      kA := by
  have h : FundamentalGroupoidOn.map (ContinuousMap.subtypeVal upper) (fun _ h ↦ h) ⋙
      lift kA kB = arcFunctor upper kA :=
    isPushout.inl_desc (W := Grpd.of (SingleObj K)) _ _ _
  rw [← map_arcHom γ hγ]
  exact (congrArg (fun E ↦ (E.map (arcHom γ hγ) : K)) h).trans (arcFunctor_map_arcHom kA γ hγ)

/-- `TauCeti.CircleArcs.lift` sends the class of a path from `1` to `-1` in `lower` to `kB`. -/
@[simp]
theorem lift_map_lower (kA kB : K) (γ : Path (1 : sphere (0 : ℂ) 1) (-1))
    (hγ : ∀ t, γ t ∈ lower) :
    (lift kA kB).map (InducedCategory.homMk (Path.Homotopic.Quotient.mk γ) : one ⟶ negOne) =
      kB := by
  have h : FundamentalGroupoidOn.map (ContinuousMap.subtypeVal lower) (fun _ h ↦ h) ⋙
      lift kA kB = arcFunctor lower kB :=
    isPushout.inr_desc (W := Grpd.of (SingleObj K)) _ _ _
  rw [← map_arcHom γ hγ]
  exact (congrArg (fun E ↦ (E.map (arcHom γ hγ) : K)) h).trans (arcFunctor_map_arcHom kB γ hγ)

/-- A functor out of the fundamental groupoid of the circle on `{1, -1}` to a group is determined
by its values on the class of a path from `1` to `-1` in `upper` and on that of one in `lower`. -/
theorem functor_ext {F G : FundamentalGroupoidOn basepoints ⥤ SingleObj K}
    (γA : Path (1 : sphere (0 : ℂ) 1) (-1)) (hγA : ∀ t, γA t ∈ upper)
    (γB : Path (1 : sphere (0 : ℂ) 1) (-1)) (hγB : ∀ t, γB t ∈ lower)
    (hA : F.map (InducedCategory.homMk (Path.Homotopic.Quotient.mk γA) : one ⟶ negOne) =
      G.map (InducedCategory.homMk (Path.Homotopic.Quotient.mk γA) : one ⟶ negOne))
    (hB : F.map (InducedCategory.homMk (Path.Homotopic.Quotient.mk γB) : one ⟶ negOne) =
      G.map (InducedCategory.homMk (Path.Homotopic.Quotient.mk γB) : one ⟶ negOne)) :
    F = G := by
  refine isPushout.hom_ext (W := Grpd.of (SingleObj K)) ?_ ?_
  · exact functor_ext_arc γA hγA (((congrArg F.map (map_arcHom γA hγA)).trans hA).trans
      (congrArg G.map (map_arcHom γA hγA)).symm)
  · exact functor_ext_arc γB hγB (((congrArg F.map (map_arcHom γB hγB)).trans hB).trans
      (congrArg G.map (map_arcHom γB hγB)).symm)

/-! ### The based consequence -/

section Based

variable (γA γB : Path (1 : sphere (0 : ℂ) 1) (-1))

/-- The class of the loop `γA · γB⁻¹`, as a morphism of the fundamental groupoid on the
basepoints. -/
private theorem homMk_loop :
    (InducedCategory.homMk (Path.Homotopic.Quotient.mk (γA.trans γB.symm)) : one ⟶ one) =
      InducedCategory.homMk (Path.Homotopic.Quotient.mk γA) ≫
        inv (InducedCategory.homMk (Path.Homotopic.Quotient.mk γB) : one ⟶ negOne) := by
  refine (IsIso.eq_comp_inv _).mpr (InducedCategory.hom_ext ?_)
  simp [FundamentalGroupoid.comp_eq, Path.Homotopic.Quotient.mk_trans,
    Path.Homotopic.Quotient.mk_symm]

/-- The homomorphism `π₁(S¹, 1) →* ℤ` induced by the functor `lift` with values `0` on `upper` and
`-1` on `lower`, written multiplicatively. -/
private def loopHom : FundamentalGroup (sphere (0 : ℂ) 1) 1 →* Multiplicative ℤ :=
  MonoidHom.mk' (fun g ↦ (lift 1 (Multiplicative.ofAdd (-1))).map
    (InducedCategory.homMk g : one ⟶ one)) fun g h ↦ by
    rw [End.mul_def, ← SingleObj.comp_as_mul, ← Functor.map_comp]
    -- Composition in `FundamentalGroupoidOn` is composition of the underlying morphisms.
    rfl

private theorem loopHom_fromPath (γ : Path (1 : sphere (0 : ℂ) 1) 1) :
    loopHom (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk γ)) =
      (lift 1 (Multiplicative.ofAdd (-1))).map
        (InducedCategory.homMk (Path.Homotopic.Quotient.mk γ) : one ⟶ one) :=
  rfl

private theorem loopHom_trans_symm :
    loopHom (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk (γA.trans γB.symm))) =
      (lift 1 (Multiplicative.ofAdd (-1))).map
          (InducedCategory.homMk (Path.Homotopic.Quotient.mk γA) : one ⟶ negOne) ≫
        inv ((lift 1 (Multiplicative.ofAdd (-1))).map
          (InducedCategory.homMk (Path.Homotopic.Quotient.mk γB) : one ⟶ negOne)) := by
  rw [loopHom_fromPath, homMk_loop, Functor.map_comp, Functor.map_inv]

private theorem loopHom_loop (hγA : ∀ t, γA t ∈ upper) (hγB : ∀ t, γB t ∈ lower) :
    loopHom (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk (γA.trans γB.symm))) =
      Multiplicative.ofAdd 1 := by
  rw [loopHom_trans_symm, SingleObj.inv_as_inv, SingleObj.comp_as_mul,
    lift_map_upper _ _ γA hγA, lift_map_lower _ _ γB hγB]
  exact (by simp : (Multiplicative.ofAdd (-1 : ℤ))⁻¹ * 1 = Multiplicative.ofAdd 1)

/-- The morphism `one ⟶ y` in the fundamental groupoid on the basepoints given by the identity
for `y = 1` and by the class of `γA` for `y = -1`. -/
private def conn (γA : Path (1 : sphere (0 : ℂ) 1) (-1)) (y : FundamentalGroupoidOn basepoints) :
    one ⟶ y := by
  classical
  exact if h : (y.1 : sphere (0 : ℂ) 1) = 1 then eqToHom (Subtype.ext h.symm)
    else (InducedCategory.homMk (Path.Homotopic.Quotient.mk γA) : one ⟶ negOne) ≫
      eqToHom (Subtype.ext ((mem_basepoints.mp y.2).resolve_left h).symm)

private theorem conn_one : conn γA one = 𝟙 one := by
  simp [conn]

private theorem conn_negOne :
    conn γA negOne = InducedCategory.homMk (Path.Homotopic.Quotient.mk γA) := by
  simp [conn, neg_one_ne_one]

/-- Conjugation by `conn γA` retracts the fundamental groupoid on the basepoints onto
`π₁(S¹, 1)`. -/
private def retraction (γA : Path (1 : sphere (0 : ℂ) 1) (-1)) :
    FundamentalGroupoidOn basepoints ⥤ SingleObj (FundamentalGroup (sphere (0 : ℂ) 1) 1) :=
  Groupoid.functorOfEndHom one (conn γA) ((FundamentalGroupoidOn.incl basepoints).mapEnd one)

private theorem retraction_map {y : FundamentalGroupoidOn basepoints} (x : one ⟶ y) :
    (retraction γA).map x = (x ≫ inv (conn γA y)).hom := by
  rw [retraction, Groupoid.functorOfEndHom_map, conn_one, Category.id_comp]
  -- `mapEnd` of the inclusion takes the underlying morphism.
  rfl

/-- The retraction agrees with the functor with values `1` on `upper` and `(γA · γB⁻¹)⁻¹` on
`lower`, since it does so on the classes of `γA` and `γB`. -/
private theorem retraction_eq (hγA : ∀ t, γA t ∈ upper) (hγB : ∀ t, γB t ∈ lower) :
    retraction γA = lift 1 (Multiplicative.ofAdd (-1)) ⋙ SingleObj.mapHom _ _ (zpowersHom _
      (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk (γA.trans γB.symm)))) := by
  let ℓ := FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk (γA.trans γB.symm))
  refine functor_ext γA hγA γB hγB ?_ ?_
  · have h : @Eq (FundamentalGroup (sphere (0 : ℂ) 1) 1) ((retraction γA).map
        (InducedCategory.homMk (Path.Homotopic.Quotient.mk γA) : one ⟶ negOne)) 1 := by
      rw [retraction_map, conn_negOne, IsIso.hom_inv_id]
      -- The identity of `FundamentalGroupoidOn` has the identity as underlying morphism.
      rfl
    exact h.trans ((congrArg (zpowersHom _ ℓ)
      (lift_map_upper (1 : Multiplicative ℤ) (Multiplicative.ofAdd (-1)) γA hγA)).trans
      (map_one _)).symm
  · have h : @Eq (FundamentalGroup (sphere (0 : ℂ) 1) 1) ((retraction γA).map
        (InducedCategory.homMk (Path.Homotopic.Quotient.mk γB) : one ⟶ negOne)) ℓ⁻¹ := by
      rw [retraction_map, conn_negOne]
      refine eq_inv_of_mul_eq_one_left ?_
      have h : (InducedCategory.homMk ℓ : one ⟶ one) ≫
          InducedCategory.homMk (Path.Homotopic.Quotient.mk γB) ≫
            inv (InducedCategory.homMk (Path.Homotopic.Quotient.mk γA) : one ⟶ negOne) = 𝟙 one := by
        rw [homMk_loop]
        simp
      -- Multiplication in `π₁(S¹, 1)` is composition, which is composition of the underlying
      -- morphisms in `FundamentalGroupoidOn`.
      calc _ = ((InducedCategory.homMk ℓ : one ⟶ one) ≫
            InducedCategory.homMk (Path.Homotopic.Quotient.mk γB) ≫
              inv (InducedCategory.homMk (Path.Homotopic.Quotient.mk γA) : one ⟶ negOne)).hom :=
            rfl
        _ = 1 := by rw [h]; rfl
    refine h.trans ((congrArg (zpowersHom _ ℓ)
      (lift_map_lower (1 : Multiplicative ℤ) (Multiplicative.ofAdd (-1)) γB hγB)).trans ?_).symm
    rw [zpowersHom_apply, toAdd_ofAdd, zpow_neg_one]

end Based

/-- **The fundamental group of the circle, by van Kampen.** If `γA` runs from `1` to `-1` in
`upper` and `γB` does so in `lower`, then `n ↦ (γA · γB⁻¹)ⁿ` is an isomorphism from `ℤ` onto
`π₁(S¹, 1)`. -/
theorem zpowersHom_bijective (γA : Path (1 : sphere (0 : ℂ) 1) (-1)) (hγA : ∀ t, γA t ∈ upper)
    (γB : Path (1 : sphere (0 : ℂ) 1) (-1)) (hγB : ∀ t, γB t ∈ lower) :
    Function.Bijective (zpowersHom (FundamentalGroup (sphere (0 : ℂ) 1) 1)
      (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk (γA.trans γB.symm)))) := by
  -- `loopHom` is a left inverse, since it sends the loop to the generator `1` of `ℤ`.
  have hleft : Function.LeftInverse loopHom (zpowersHom _
      (FundamentalGroup.fromPath (Path.Homotopic.Quotient.mk (γA.trans γB.symm)))) :=
    DFunLike.congr_fun (MonoidHom.ext_mint (f := loopHom.comp (zpowersHom _ _))
      (g := MonoidHom.id _) (by
        rw [MonoidHom.comp_apply, zpowersHom_apply, toAdd_ofAdd, zpow_one, MonoidHom.id_apply]
        exact loopHom_loop γA γB hγA hγB))
  -- It is a right inverse, since the retraction onto `π₁(S¹, 1)` factors through it.
  refine ⟨hleft.injective, Function.LeftInverse.surjective (g := loopHom) fun g ↦ ?_⟩
  have h := congrArg (fun E : FundamentalGroupoidOn basepoints ⥤
    SingleObj (FundamentalGroup (sphere (0 : ℂ) 1) 1) ↦
      (E.map (InducedCategory.homMk g : one ⟶ one) : FundamentalGroup (sphere (0 : ℂ) 1) 1))
    (retraction_eq γA γB hγA hγB)
  refine h.symm.trans ((retraction_map γA _).trans ?_)
  rw [conn_one, IsIso.inv_id, Category.comp_id]
  -- The underlying morphism of `InducedCategory.homMk g` is `g`.
  rfl

end TauCeti.CircleArcs
