/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.StandardCover.Basic
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.LaurentCover.FiniteTopology

import Mathlib.CategoryTheory.Sites.Coverage
import TauCeti.AlgebraicGeometry.AdicSpace.Spa.Localization.OpenEmbedding
import TauCeti.AlgebraicGeometry.AdicSpace.Spa.Localization.Units
import TauCeti.RingTheory.Huber.LocalizationTopology.Basic
import TauCeti.RingTheory.Huber.LocalizationTopology.StronglyNoetherian
import TauCeti.Topology.Homeomorph.Inducing

/-!
# Continuous gluing for standard rational covers

On a rational open of the adic spectrum of a strongly noetherian Tate ring, the topology on
sections is induced by restriction to a standard rational cover generated by units. Compatible
continuous ring homomorphisms into the sections on the pieces therefore glue continuously.

The Laurent cover generated by all ratios of the generators refines the standard cover. Its
restriction maps factor continuously through those of the standard cover, so the inducing
property for Laurent covers implies the inducing property here. This supplies the unit-generated
case of the topological reduction from Laurent covers to rational covers. No completeness or
Hausdorffness assumption on the original ring is needed.

More generally, suppose the generators vanish nowhere on a rational open `W`. They become units
in the completed coordinate ring of `W`. Wedhorn's Remark 8.4 identifies sections on rational
subsets of `W` with sections over that coordinate ring as topological rings, compatibly with
restriction. Transporting the unit-generated case along these isomorphisms shows that restriction
to the original standard cover of `W` is inducing, and hence gives continuous gluing there as well.

Finally, if the generators span the unit ideal, Wedhorn's Laurent-cover reduction decomposes the
standard cover into covers whose nonempty generators vanish nowhere. Continuous gluing first on
those pieces and then on the Laurent cover gives continuous gluing for the original standard
cover.

The general reduction from all arrows of a generated sieve to its generating arrows is provided by
`TauCeti.TopCommRingCat.isInducing_restrictionMap_ofArrows_iff`.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Lemma 8.34(iii) and
  Remark 8.20.
* S. Bosch, U. Güntzer, R. Remmert, *Non-Archimedean Analysis*, §8.2.2, Lemma 3.
-/

public section

open CategoryTheory TopologicalSpace Topology Opposite TauCeti.Huber TauCeti.Huber.PairOfDefinition

universe v

namespace TauCeti.ValuationSpectrum

variable {A : Type v} [CommRing A] [UniformSpace A] [IsTopologicalRing A] [IsTateRing A]
  [IsStronglyNoetherian A] (P : PairOfDefinition A) {Aplus : Subring A}

/-- Sections on a rational open carry the topology induced by restriction to the sieve of a
standard rational cover generated by a nonempty finite set of units. -/
theorem isInducing_presentationLimitPresheafMap_standardSieve_of_isUnit
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {T : Finset A} (hT : T.Nonempty)
    (hu : ∀ t ∈ T, IsUnit t) {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus) :
    let S := Sieve.ofArrows (fun t : T ↦ W ⊓ spaBasicOpen Aplus T t)
      fun _ ↦ homOfLE inf_le_left
    IsInducing fun (x : (presentationLimitPresheaf P Aplus).obj (op W))
      (g : (V : Opens ↥(spa Aplus)) × { f : V ⟶ W // S f }) ↦
        ((presentationLimitPresheaf P Aplus).map g.2.1.op).hom.1 x := by
  classical
  let F := presentationLimitPresheaf P Aplus
  let S := Sieve.ofArrows (fun t : T ↦ W ⊓ spaBasicOpen Aplus T t)
    fun _ ↦ homOfLE inf_le_left
  let f : T × T → A := fun p ↦ (p.1 : A) * Ring.inverse (p.2 : A)
  let R : Finset A := Finset.univ.image f
  -- Each arrow of the refining Laurent sieve also belongs to the standard sieve.
  have hRS : laurentSieve Aplus R W ≤ S :=
    laurentSieve_mul_inverse_le_ofArrows_inf_spaBasicOpen hT hu W
  let j (g : (V : Opens ↥(spa Aplus)) × { f : V ⟶ W // laurentSieve Aplus R W f }) :
      (V : Opens ↥(spa Aplus)) × { f : V ⟶ W // S f } :=
    ⟨g.1, g.2.1, hRS g.2.1 g.2.2⟩
  -- Projection to the Laurent coordinates is continuous for the product topologies.
  let q := fun z : (g : (V : Opens ↥(spa Aplus)) × { f : V ⟶ W // S f }) → F.obj (op g.1) ↦
    fun g ↦ z (j g)
  apply IsInducing.of_comp (g := q) (continuous_pi fun g ↦ (F.map g.2.1.op).hom.2)
    (continuous_pi fun g ↦ continuous_apply (j g))
  exact isInducing_presentationLimitPresheafMap_laurentSieve P hAplus R hW

/-- The presentation-limit presheaf of topological commutative rings satisfies the sheaf
condition for every standard rational cover of a rational open generated by units. Compatible
continuous ring homomorphisms from any topological commutative ring into sections on the pieces
glue to a unique continuous ring homomorphism into sections on the original open. -/
theorem isSheafFor_ofArrows_inf_spaBasicOpen_of_isUnit_topCommRingCat
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {T : Finset A} (hT : T.Nonempty)
    (hu : ∀ t ∈ T, IsUnit t) {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus)
    (E : _root_.TopCommRingCat.{v}) :
    (Presieve.ofArrows (fun t : T ↦ W ⊓ spaBasicOpen Aplus T t)
      fun _ ↦ homOfLE inf_le_left).IsSheafFor
        (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
          coyoneda.obj (op E)) := by
  rw [Presieve.isSheafFor_iff_generate]
  exact TopCommRingCat.isSheafFor_of_isSheafFor_forget
    (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι)
    (Sieve.ofArrows _ _)
    ((Presieve.isSheafFor_iff_generate _).mp
      (isSheafFor_ofArrows_inf_spaBasicOpen_of_isUnit P hAplus hT hu hW))
    (isInducing_presentationLimitPresheafMap_standardSieve_of_isUnit P hAplus hT hu hW) E

/-- Sections on a rational open carry the topology induced by restriction to a standard rational
cover whose generators vanish nowhere on that open. -/
theorem isInducing_presentationLimitPresheafMap_standardSieve (hP : P.ringOfDefinition ≤ Aplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {T : Finset A} (hT : T.Nonempty)
    {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus)
    (hTW : ∀ t ∈ T, ∀ v ∈ W, t ∉ supp (v : Spv A)) :
    let S := Sieve.ofArrows (fun t : T ↦ W ⊓ spaBasicOpen Aplus T t)
      fun _ ↦ homOfLE inf_le_left
    IsInducing fun (x : (presentationLimitPresheaf P Aplus).obj (op W))
      (g : (V : Opens ↥(spa Aplus)) × { f : V ⟶ W // S f }) ↦
        ((presentationLimitPresheaf P Aplus).map g.2.1.op).hom.1 x := by
  classical
  have _ : IsHuberRing A := ⟨⟨P⟩⟩
  -- Write `W` as a rational open `R(U / s)` and equip its completed coordinate ring `B`.
  obtain ⟨U, s, hU, hWU⟩ := mem_spaRationalFamily_iff.mp (mem_spaRationalOpens.mp hW)
  obtain rfl : W = spaBasicOpen Aplus U s :=
    Opens.ext (hWU.trans (Set.ext fun _ ↦ mem_spaBasicOpen.symm))
  have hden := hasDenominatorPower_of_isOpen_span P U s (Localization.Away s) hU
  let _ := locUniformSpace P U s _ hden
  have _ := isUniformAddGroup_locUniformSpace P U s _ hden
  have _ := isTopologicalRing_locUniformSpace P U s _ hden
  have _ := isTateRing_completion_locTopology_of_isTateRing P U s _ hden
  have _ := isStronglyNoetherian_completion P U s _ hden
    (eq_top_mono (Ideal.span_mono (Set.subset_insert _ _)) (IsTateRing.eq_top_of_isOpen hU))
  let ρ := toCompletionLoc P U s _ hden
  let Bplus := completedPlusSubring P Aplus U s _ hden
  let Q := completionLocalization P U s _ hden
  let F := presentationLimitPresheaf P Aplus
  let FB := presentationLimitPresheaf Q Bplus
  -- The generators become units in `B`, and the standard cover pulls back to the
  -- unit-generated standard cover of `Spa B`, whose pieces are rational in `Spa A`.
  have hu : ∀ t' ∈ T.image ρ, IsUnit t' := by
    simp only [Finset.mem_image]
    rintro _ ⟨t, ht, rfl⟩
    exact (isUnit_toCompletionLoc_iff_forall_notMem_supp P Aplus hP hAplus U s _ hden t).2
      fun v hv ↦ hTW t ht ⟨v, rationalSubset_subset_spa Aplus U s hv⟩ (mem_spaBasicOpen.mpr hv)
  obtain ⟨t₀, ht₀⟩ := hT.image ρ
  have hpull (t : T) : locOpensComap P Aplus U s _ hden
      (spaBasicOpen Aplus U s ⊓ spaBasicOpen Aplus T t) =
        locOpensComap P Aplus U s _ hden (spaBasicOpen Aplus U s) ⊓
          spaBasicOpen Bplus (T.image ρ) (ρ t) := by
    rw [locOpensComap_inf, locOpensComap_spaBasicOpen P Aplus U s _ hden T]
  have hrat (t : T) : spaBasicOpen Aplus U s ⊓ spaBasicOpen Aplus T t ∈
      spaRationalOpens Aplus := by
    rw [← spaComapLoc_functor_obj_locOpensComap P Aplus hP U s _ hden inf_le_left]
    refine spaComapLoc_functor_obj_mem_spaRationalOpens P Aplus hP U s _ hden hU _ ?_
    rw [hpull]
    exact inf_mem_spaRationalOpens
      (locOpensComap_mem_spaRationalOpens P Aplus U s _ hden
        (spaBasicOpen_mem_spaRationalOpens hU))
      (spaBasicOpen_mem_spaRationalOpens <| by
        rw [Ideal.eq_top_of_isUnit_mem _ (Ideal.subset_span ht₀) (hu t₀ ht₀)]
        exact isOpen_univ)
  let a : T → T.image ρ := fun t ↦ ⟨ρ t, Finset.mem_image_of_mem ρ t.2⟩
  have ha : Function.Surjective a := by
    rintro ⟨b, hb⟩
    obtain ⟨t, ht, htb⟩ := Finset.mem_image.mp hb
    exact ⟨⟨t, ht⟩, Subtype.ext htb⟩
  -- Apply the unit-generated case over `B` and reindex its generators by `T`.
  have hB := isInducing_presentationLimitPresheafMap_standardSieve_of_isUnit Q
    (isPowerBounded_of_mem_completedPlusSubring P Aplus hAplus U s _ hden) (hT.image ρ) hu
    (W := locOpensComap P Aplus U s _ hden (spaBasicOpen Aplus U s))
    (locOpensComap_mem_spaRationalOpens P Aplus U s _ hden hW)
  dsimp only at hB
  have hs : Sieve.ofArrows
      (fun t : T ↦ locOpensComap P Aplus U s _ hden
        (spaBasicOpen Aplus U s ⊓ spaBasicOpen Aplus T t))
      (fun t ↦ homOfLE (locOpensComap_mono P Aplus U s _ hden
        (inf_le_left : spaBasicOpen Aplus U s ⊓ spaBasicOpen Aplus T t ≤ _))) =
      Sieve.ofArrows
      (fun t : T.image ρ ↦ locOpensComap P Aplus U s _ hden (spaBasicOpen Aplus U s) ⊓
        spaBasicOpen Bplus (T.image ρ) t) (fun _ ↦ homOfLE inf_le_left) := by
    ext V g
    simp only [Sieve.mem_ofArrows_iff]
    constructor
    · rintro ⟨t, e, rfl⟩
      exact ⟨a t, e ≫ eqToHom (hpull t), Subsingleton.elim _ _⟩
    · rintro ⟨t, e, rfl⟩
      obtain ⟨t, rfl⟩ := ha t
      exact ⟨t, e ≫ eqToHom (hpull t).symm, Subsingleton.elim _ _⟩
  rw [← hs] at hB
  have hB₁ : IsInducing fun (x : FB.obj (op (locOpensComap P Aplus U s _ hden
      (spaBasicOpen Aplus U s)))) (t : T) ↦
      (FB.map (homOfLE (locOpensComap_mono P Aplus U s _ hden
        (inf_le_left : spaBasicOpen Aplus U s ⊓ spaBasicOpen Aplus T t ≤ _))).op).hom.1 x :=
    (TopCommRingCat.isInducing_restrictionMap_ofArrows_iff
      (FB ⋙ TopCommRingCat.isCompleteSeparated.ι) _ _).mp hB
  let G := TopCommRingCat.isCompleteSeparated.ι ⋙ forget₂ _root_.TopCommRingCat TopCat
  let eA (V : Opens ↥(spa Aplus)) : F.obj (op V) ≃ₜ presentationLimit (P := P) Aplus V :=
    TopCat.homeoOfIso (G.mapIso (eqToIso (presentationLimitPresheaf_obj P Aplus (op V))))
  let eB (V : Opens ↥(spa Bplus)) : FB.obj (op V) ≃ₜ presentationLimit (P := Q) Bplus V :=
    TopCat.homeoOfIso (G.mapIso (eqToIso (presentationLimitPresheaf_obj Q Bplus (op V))))
  let σ (V : Opens ↥(spa Aplus)) (hV : V ∈ spaRationalOpens Aplus)
      (hVW : V ≤ spaBasicOpen Aplus U s) :
      presentationLimit (P := P) Aplus V ≃ₜ
        presentationLimit (P := Q) Bplus (locOpensComap P Aplus U s _ hden V) :=
    TopCat.homeoOfIso (G.mapIso
      (presentationLimitLocIso P Aplus U s _ hden hAplus hU V hV hVW))
  let pieces (t : T) := spaBasicOpen Aplus U s ⊓ spaBasicOpen Aplus T t
  have eA_apply (V : Opens ↥(spa Aplus)) (x : F.obj (op V)) :
      eA V x = (eqToHom (presentationLimitPresheaf_obj P Aplus (op V))).hom.1 x := rfl
  have eB_apply (V : Opens ↥(spa Bplus)) (x : FB.obj (op V)) :
      eB V x = (eqToHom (presentationLimitPresheaf_obj Q Bplus (op V))).hom.1 x := rfl
  have σ_apply (V : Opens ↥(spa Aplus)) (hV : V ∈ spaRationalOpens Aplus)
      (hVW : V ≤ spaBasicOpen Aplus U s) (x : presentationLimit (P := P) Aplus V) :
      σ V hV hVW x =
        (presentationLimitLocIso P Aplus U s _ hden hAplus hU V hV hVW).hom.hom.1 x := rfl
  -- Transport the generating restriction maps from the presheaf over `Q` to the presentation
  -- limits over `Q`, then along Remark 8.4 to those over `P`, then back to the presheaf over `P`.
  have hBpl : IsInducing fun
      (x : presentationLimit (P := Q) Bplus
        (locOpensComap P Aplus U s _ hden (spaBasicOpen Aplus U s))) (t : T) ↦
      (presentationLimitMap (P := Q)
        (locOpensComap_mono P Aplus U s _ hden
          (inf_le_left : pieces t ≤ spaBasicOpen Aplus U s))).hom.1 x :=
    ((eB _).isInducing_pi_iff_of_homeomorph (fun t ↦ eB (locOpensComap P Aplus U s _ hden
      (pieces t))) fun x t ↦ by
        rw [eB_apply, eB_apply]
        exact eqToHom_apply_presentationLimitPresheaf_map_apply Q
          (locOpensComap_mono P Aplus U s _ hden inf_le_left) x).mp hB₁
  have hApl : IsInducing fun
      (x : presentationLimit (P := P) Aplus (spaBasicOpen Aplus U s)) (t : T) ↦
      (presentationLimitMap (P := P) (inf_le_left : pieces t ≤ _)).hom.1 x :=
    ((σ (spaBasicOpen Aplus U s) (spaBasicOpen_mem_spaRationalOpens hU)
      le_rfl).isInducing_pi_iff_of_homeomorph
      (fun t ↦ σ (pieces t) (hrat t) inf_le_left) fun x t ↦ by
        rw [σ_apply, σ_apply]
        exact presentationLimitLocIso_hom_presentationLimitMap_apply P Aplus U s _ hden hAplus
          hU (spaBasicOpen_mem_spaRationalOpens hU) (hrat t) le_rfl inf_le_left x).mpr hBpl
  have hA₀ : IsInducing fun (x : F.obj (op (spaBasicOpen Aplus U s))) (t : T) ↦
      (F.map (homOfLE inf_le_left : pieces t ⟶ spaBasicOpen Aplus U s).op).hom.1 x :=
    ((eA _).isInducing_pi_iff_of_homeomorph (fun t ↦ eA (pieces t)) fun x t ↦ by
      rw [eA_apply, eA_apply]
      exact eqToHom_apply_presentationLimitPresheaf_map_apply P
        (inf_le_left : pieces t ≤ spaBasicOpen Aplus U s) x).mpr hApl
  -- Recover the full standard sieve from its generating arrows.
  exact (TopCommRingCat.isInducing_restrictionMap_ofArrows_iff
    (F ⋙ TopCommRingCat.isCompleteSeparated.ι) _ _).mpr hA₀

/-- The presentation-limit presheaf of topological commutative rings satisfies the sheaf
condition for a standard rational cover whose generators vanish nowhere on the rational open. -/
theorem isSheafFor_ofArrows_inf_spaBasicOpen_topCommRingCat
    (hP : P.ringOfDefinition ≤ Aplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {T : Finset A} (hT : T.Nonempty)
    {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus)
    (hTW : ∀ t ∈ T, ∀ v ∈ W, t ∉ supp (v : Spv A))
    (E : _root_.TopCommRingCat.{v}) :
    (Presieve.ofArrows (fun t : T ↦ W ⊓ spaBasicOpen Aplus T t)
      fun _ ↦ homOfLE inf_le_left).IsSheafFor
        (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
          coyoneda.obj (op E)) := by
  rw [Presieve.isSheafFor_iff_generate]
  exact TopCommRingCat.isSheafFor_of_isSheafFor_forget
    (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι)
    (Sieve.ofArrows _ _)
    ((Presieve.isSheafFor_iff_generate _).mp
      (isSheafFor_ofArrows_inf_spaBasicOpen P hP hAplus hT hW hTW))
    (isInducing_presentationLimitPresheafMap_standardSieve P hP hAplus hT hW hTW) E

/-! ### Standard covers generated by the unit ideal -/

private theorem isSheafFor_ofArrows_inf_spaBasicOpen_of_subset_laurentPiece_topCommRingCat
    (hP : P.ringOfDefinition ≤ Aplus) (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
    {T : Finset A} (hT : T.Nonempty) {ϖ : Aˣ}
    (hϖ : ∀ v ∈ spa Aplus, ∃ t ∈ T, v.toValuativeRel.vlt (ϖ : A) t) {J : Set T}
    {V : Opens ↥(spa Aplus)} (hV : V ∈ spaRationalOpens Aplus)
    (hVJ : (V : Set ↥(spa Aplus)) ⊆
      Subtype.val ⁻¹' laurentPiece Aplus (fun t : T ↦ (ϖ⁻¹ : Aˣ) * (t : A)) J)
    (E : _root_.TopCommRingCat.{v}) :
    (Presieve.ofArrows (fun t : T ↦ V ⊓ spaBasicOpen Aplus T t)
      fun _ ↦ homOfLE inf_le_left).IsSheafFor
        (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
          coyoneda.obj (op E)) := by
  classical
  let TJ : Finset A := T.filter fun a ↦ ∃ h : a ∈ T, (⟨a, h⟩ : T) ∈ J
  have hmemTJ {a : A} : a ∈ TJ ↔ ∃ h : a ∈ T, (⟨a, h⟩ : T) ∈ J := by
    simp only [TJ, Finset.mem_filter]
    exact ⟨fun h ↦ h.2, fun h ↦ ⟨h.1, h⟩⟩
  have hempty (t : T) (ht : t ∉ J) : V ⊓ spaBasicOpen Aplus T t = ⊥ :=
    eq_bot_iff.mpr fun x hx ↦ (Set.eq_empty_iff_forall_notMem.mp
      (rationalSubset_inter_laurentPiece_inv_mul_eq_empty hϖ ht) x.1
        ⟨mem_spaBasicOpen.mp hx.2, hVJ hx.1⟩).elim
  have hpiece (t : T) (ht : t ∈ J) :
      V ⊓ spaBasicOpen Aplus T t = V ⊓ spaBasicOpen Aplus TJ t := by
    refine SetLike.ext fun x ↦ ?_
    simp only [Opens.mem_inf, mem_spaBasicOpen]
    refine and_congr_right fun hx ↦ ⟨fun h ↦ rationalSubset_subset_rationalSubset_of_subset Aplus
      (Finset.filter_subset _ T) t h, fun h ↦ ?_⟩
    exact (mem_rationalSubset_iff_of_mem_laurentPiece_inv_mul ϖ ht (hVJ hx)).mpr fun t' ht' ↦
      ((mem_rationalSubset_iff _ _ _ _).mp h).2.1 t' (hmemTJ.mpr ⟨t'.2, ht'⟩)
  rw [Presieve.isSheafFor_iff_generate]
  rcases TJ.eq_empty_or_nonempty with hTJ | hTJ
  · obtain ⟨t₀, ht₀⟩ := hT
    have hV₀ : V ≤ V ⊓ spaBasicOpen Aplus T t₀ := fun x hx ↦ by
      obtain ⟨t, ht, hlt⟩ := hϖ x.1 x.2
      have htJ : (⟨t, ht⟩ : T) ∉ J := fun h ↦ by simpa [hTJ] using hmemTJ.mpr ⟨ht, h⟩
      exact (hlt (@TauCeti.ValuativeRel.vle_of_inv_mul_vle A _ x.1.toValuativeRel ϖ t
        ((((mem_laurentPiece_iff _ _ _ _).mp (hVJ hx)).2 ⟨t, ht⟩).2 htJ))).elim
    rw [(Sieve.id_mem_iff_eq_top (S := Sieve.generate _)).mp
      ⟨_, homOfLE hV₀, _, Presieve.ofArrows.mk (⟨t₀, ht₀⟩ : T), rfl⟩]
    exact Presieve.isSheafFor_top _
  · have h := isSheafFor_ofArrows_inf_spaBasicOpen_topCommRingCat P hP hAplus hTJ hV
      (fun a ha x hx hsupp ↦ by
        obtain ⟨haT, haJ⟩ := hmemTJ.mp ha
        exact not_vle_zero_of_mem_laurentPiece_inv_mul ϖ haJ (hVJ hx)
          ((mem_supp_iff _ _).mp hsupp)) E
    rw [Presieve.isSheafFor_iff_generate] at h
    refine (congrArg (fun S : Sieve V ↦ S.arrows.IsSheafFor _) (Sieve.ext fun U g ↦ ?_)).mp h
    simp only [Sieve.mem_ofArrows_iff]
    constructor
    · rintro ⟨⟨a, ha⟩, e, -⟩
      obtain ⟨haT, haJ⟩ := hmemTJ.mp ha
      exact ⟨⟨a, haT⟩, homOfLE (e.le.trans (hpiece _ haJ).symm.le), rfl⟩
    · rintro ⟨t, e, -⟩
      by_cases ht : t ∈ J
      · exact ⟨⟨t, hmemTJ.mpr ⟨t.2, ht⟩⟩, homOfLE (e.le.trans (hpiece t ht).le), rfl⟩
      · obtain ⟨a, ha⟩ := hTJ
        exact ⟨⟨a, ha⟩, homOfLE (e.le.trans ((hempty t ht).le.trans bot_le)), rfl⟩

/-- **Wedhorn's Lemma 8.34(ii), with topology.** The presentation-limit presheaf of topological
commutative rings satisfies the sheaf condition for a standard rational cover generated by a
nonempty finite set spanning the unit ideal. Thus compatible continuous ring homomorphisms into
the rings of sections on the cover glue uniquely and continuously. -/
theorem isSheafFor_ofArrows_inf_spaBasicOpen_of_span_eq_top_topCommRingCat
    (hP : P.ringOfDefinition ≤ Aplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {T : Finset A} (hT : T.Nonempty)
    (hspan : Ideal.span (T : Set A) = ⊤) {W : Opens ↥(spa Aplus)}
    (hW : W ∈ spaRationalOpens Aplus) (E : _root_.TopCommRingCat.{v}) :
    (Presieve.ofArrows (fun t : T ↦ W ⊓ spaBasicOpen Aplus T t)
      fun _ ↦ homOfLE inf_le_left).IsSheafFor
        (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
          coyoneda.obj (op E)) := by
  classical
  have _ : IsHuberRing A := ⟨⟨P⟩⟩
  obtain ⟨ϖ, hϖ⟩ := exists_unit_forall_mem_spa_exists_vlt Aplus hspan
  let f : T → A := fun t ↦ (ϖ⁻¹ : Aˣ) * (t : A)
  let Y (J : Set T) : Opens ↥(spa Aplus) := W ⊓
    ⟨_, (isTopologicalBasis_spaRationalFamily Aplus).isOpen
      (val_preimage_laurentPiece_mem_spaRationalFamily Aplus f J)⟩
  have hY (J : Set T) : Y J ∈ spaRationalOpens Aplus :=
    inf_mem_spaRationalOpens hW
      (mem_spaRationalOpens.mpr (val_preimage_laurentPiece_mem_spaRationalFamily Aplus f J))
  let R : Finset A := Finset.univ.image f
  have hRY {U V : Opens ↥(spa Aplus)} (g : U ⟶ V) (hVW : V ≤ W)
      (hg : laurentSieve Aplus R V g) : ∃ J, U ≤ Y J :=
    ((laurentSieve_image_apply_iff_exists_laurentPiece f g).mp hg).imp fun _ hJ ↦
      le_inf (g.le.trans hVW) hJ
  let S : Sieve W :=
    { arrows U _ := (∃ J, U ≤ Y J) ∧ ∃ t ∈ T, U ≤ spaBasicOpen Aplus T t
      downward_closed := fun ⟨⟨J, hJ⟩, t, ht, hUt⟩ g ↦
        ⟨⟨J, g.le.trans hJ⟩, t, ht, g.le.trans hUt⟩ }
  have hSV (J : Set T) {V : Opens ↥(spa Aplus)} (hV : V ∈ spaRationalOpens Aplus)
      (hVJ : V ≤ Y J) :
      (S.pullback (homOfLE (hVJ.trans inf_le_left))).arrows.IsSheafFor
        (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
          coyoneda.obj (op E)) := by
    have h :=
      isSheafFor_ofArrows_inf_spaBasicOpen_of_subset_laurentPiece_topCommRingCat P hP hAplus hT
        hϖ hV (fun x hx ↦ (hVJ hx).2) E
    rw [Presieve.isSheafFor_iff_generate] at h
    refine (congrArg (fun S' : Sieve V ↦ S'.arrows.IsSheafFor _) (Sieve.ext fun U g ↦ ?_)).mp h
    simp only [Sieve.mem_ofArrows_iff, Sieve.pullback_apply]
    constructor
    · rintro ⟨t, e, -⟩
      exact ⟨⟨J, e.le.trans (inf_le_left.trans hVJ)⟩, t, t.2, e.le.trans inf_le_right⟩
    · rintro ⟨-, t, ht, hUt⟩
      exact ⟨⟨t, ht⟩, homOfLE (le_inf g.le hUt), rfl⟩
  have hS : S.arrows.IsSheafFor
      (presentationLimitPresheaf P Aplus ⋙ TopCommRingCat.isCompleteSeparated.ι ⋙
        coyoneda.obj (op E)) := by
    refine TopologicalSpace.Opens.isSheafFor_trans Y (fun _ ↦ inf_le_left) S ?_
      (fun J ↦ hSV J (hY J) le_rfl)
      (fun J J' ↦ (hSV J (inf_mem_spaRationalOpens (hY J) (hY J')) inf_le_left).isSeparatedFor)
      fun _ _ hg ↦ hg.1
    refine Presieve.isSheafFor_of_factorsThru _ (S := (laurentSieve Aplus R W).arrows)
      (fun U g hg ↦ ?_) (isSheafFor_laurentSieve_topCommRingCat P hAplus R hW E)
      fun Z e he ↦ ?_
    · obtain ⟨J, hJ⟩ := hRY g le_rfl hg
      exact ⟨Y J, homOfLE hJ, homOfLE inf_le_left, Presieve.ofArrows.mk J, rfl⟩
    · obtain ⟨J⟩ := he
      refine ⟨(laurentSieve Aplus R _).arrows,
        (isSheafFor_laurentSieve_topCommRingCat P hAplus R (hY J) E).isSeparatedFor,
        fun U g hg ↦ ⟨U, 𝟙 U, g ≫ homOfLE inf_le_left,
          (laurentSieve_apply _).mpr ((laurentSieve_apply g).mp hg), Category.id_comp _⟩⟩
  have hTopen : IsOpen (Ideal.span (T : Set A) : Set A) := by
    rw [hspan]
    exact isOpen_univ
  refine Presieve.isSheafFor_of_factorsThru _ (S := S.arrows) (fun U g hg ↦ ?_) hS
    fun Z e he ↦ ?_
  · obtain ⟨-, t, ht, hUt⟩ := hg
    exact ⟨W ⊓ spaBasicOpen Aplus T t, homOfLE (le_inf g.le hUt), homOfLE inf_le_left,
      Presieve.ofArrows.mk (⟨t, ht⟩ : T), rfl⟩
  · obtain ⟨t⟩ := he
    refine ⟨(laurentSieve Aplus R _).arrows,
      (isSheafFor_laurentSieve_topCommRingCat P hAplus R
        (inf_mem_spaRationalOpens hW (spaBasicOpen_mem_spaRationalOpens hTopen)) E).isSeparatedFor,
      fun U g hg ↦ ⟨U, 𝟙 U, g ≫ homOfLE inf_le_left,
        ⟨hRY g inf_le_left hg, t, t.2, g.le.trans inf_le_right⟩, Category.id_comp _⟩⟩

end TauCeti.ValuationSpectrum
