/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.G2.ShortRoot.IntegralToralClosure.Basic
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Generation
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Coroot
import TauCeti.LinearAlgebra.Matrix.Cartan.TypeG2

/-!
# Generation of the short-root type-G2 carrier by root subgroups

The integral toral closure of the seven-dimensional module `V(ϖ₁)` of type `G₂` is defined from its
four numbered positive and negative simple root subgroups together with its rank-two split weight
torus. This file proves that the torus is redundant: over every commutative ring it already lies in
the elementary subgroup generated by those root subgroups, and the integral carrier is therefore
the root-generated Kostant group scheme.

The represented generators at each node form an `sl₂` triple by
`TauCeti.G2ShortRoot.isSl2Triple_rep_serreRootGenerator`, and the two rows of the Bourbaki type-`G₂`
Cartan matrix are primitive integer vectors by
`TauCeti.sum_transpose_cartanMatrixG2_mul_typeG2CartanBezout`, the long row `(-3, 2)` through the
Bezout coefficients `(-1, -1)` rather than through an entry `-1`. So each simple root is a primitive
character of the weight torus, and the generic Kostant coroot-generation theorem writes every
coordinate cocharacter, hence the whole torus, as a product of root-subgroup elements.

Testing that pointwise containment on the universal point of the torus, over the coordinate ring of
the split torus itself, makes the torus redundant scheme-theoretically as well: the toral-closure
defining Hopf ideal over `ℤ` equals the ideal cut out by the numbered root subgroups alone. This is
an equality of integral carriers; it does not say that the subgroup generated anew over a base that
is not flat over `ℤ` is the base change of the integral carrier, and in particular it does not
identify the companion carrier generated over `𝔽₃`.

## Main results

* `TauCeti.G2ShortRoot.weightTorusSubgroup_le_elementarySubgroup`: the weight torus lies in the
  elementary subgroup over every commutative ring.
* `TauCeti.G2ShortRoot.weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup`: adjoining the
  weight torus to all four numbered root subgroups gives exactly the elementary subgroup.
* `TauCeti.G2ShortRoot.IntegralToralClosure.definingIdeal_eq_kostantGeneratedDefiningIdeal`: the
  integral toral closure is already cut out by the root subgroups alone.
* `TauCeti.G2ShortRoot.IntegralToralClosure.groupScheme_eq_kostantGeneratedGroupScheme` and
  `TauCeti.G2ShortRoot.IntegralToralClosure.isIso_kostantGeneratedToToral`: the carrier is the
  root-generated Kostant group scheme, and the canonical comparison between them is an
  isomorphism.

## References

* R. Steinberg, *Lectures on Chevalley Groups*, Section 3.
* R. W. Carter, *Simple Groups of Lie Type*, Sections 6.4 and 7.1.

This file follows the formal template of `TauCeti.Algebra.Lie.E7.Minuscule.Generation`, with the
type-`G₂` Cartan rows and short-root weights in place of the type-`E₇` data.
-/

public section

open scoped Matrix

universe v

namespace TauCeti.G2ShortRoot

open TauCeti.DynkinType TauCeti.UniversalEnvelopingAlgebra

local notation "CM" => CartanMatrix.G₂
local notation "rootGen" => TauCeti.serreRootGenerator CM
local notation "cartanGen" => TauCeti.serreH ℚ CM
local notation "rootWeight" => DynkinType.G2.rootGeneratorWeight DynkinType.valid_G2

private theorem rootWeight_sum_mul_bezout (i : Fin 2) :
    ∑ j, rootWeight (.inl i) j * typeG2CartanBezout i j = 1 := by
  have hweight (j : Fin 2) : rootWeight (.inl i) j = CMᵀ i j := by
    simpa only [DynkinType.rank_G2, DynkinType.cartanMatrix_G2] using
      (DynkinType.rootGeneratorWeight_inl (t := DynkinType.G2)
        (ht := DynkinType.valid_G2) i j)
  calc
    ∑ j, rootWeight (.inl i) j * typeG2CartanBezout i j =
        ∑ j, CMᵀ i j * typeG2CartanBezout i j :=
      Finset.sum_congr rfl fun j _ => by rw [hweight j]
    _ = 1 := sum_transpose_cartanMatrixG2_mul_typeG2CartanBezout i

private theorem rootWeight_inr_eq_neg_inl (i : Fin 2) :
    rootWeight (.inr i) = -rootWeight (.inl i) := by
  simpa only [DynkinType.rank_G2] using
    (DynkinType.rootGeneratorWeight_inr_eq_neg_root_simpleIndex
      (t := DynkinType.G2) (ht := DynkinType.valid_G2) i).trans
    (congrArg Neg.neg (DynkinType.rootGeneratorWeight_inl_eq_root_simpleIndex
      (t := DynkinType.G2) (ht := DynkinType.valid_G2) i).symm)

/-- Over every commutative ring, the rank-two weight torus of the short-root type-`G₂` module on
the base-changed admissible lattice is contained in the elementary group generated by the four
positive and negative numbered simple root subgroups. -/
theorem weightTorusSubgroup_le_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubgroup lattice.toAddSubgroup latticeBasis weight A ≤
      kostantElementarySubgroup rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator A :=
  kostantTorusSubgroup_le_kostantElementarySubgroup
    rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis weight
    isCartanWeightVector_latticeBasis rootWeight lie_cartanGenerator_rootGenerator
    Sum.inl Sum.inr isSl2Triple_rep_serreRootGenerator rootWeight_inr_eq_neg_inl
    typeG2CartanBezout rootWeight_sum_mul_bezout A

/-- Over every commutative ring, adjoining the rank-two weight torus of the short-root type-`G₂`
module to all four numbered simple root subgroups does not enlarge their elementary subgroup. -/
theorem weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubsystemSubgroup rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis weight
        Set.univ A =
      kostantElementarySubgroup rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator A :=
  kostantTorusSubsystemSubgroup_univ_eq_kostantElementarySubgroup
    rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis weight
    isCartanWeightVector_latticeBasis rootWeight lie_cartanGenerator_rootGenerator
    Sum.inl Sum.inr isSl2Triple_rep_serreRootGenerator rootWeight_inr_eq_neg_inl
    typeG2CartanBezout rootWeight_sum_mul_bezout A

namespace IntegralToralClosure

/-! ## Scheme-theoretic generation -/

private theorem universalWeightTorus_mem_elementarySubgroup :
    let T := (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup (Fin 2))).obj
    let A := CommAlgCat.of ℤ T
    let q : HopfAlgebra.points
        (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ
          (SplitTorus.characterGroup (Fin 2))) A :=
      WithConv.toConv (AlgHom.id ℤ T)
    kostantTorusPoints lattice.toAddSubgroup latticeBasis weight A
        (SplitTorus.pointsMulEquiv q) ∈
      kostantElementarySubgroup rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator A := by
  dsimp only
  apply weightTorusSubgroup_le_elementarySubgroup _
  rw [kostantTorusSubgroup_eq_range]
  exact ⟨_, rfl⟩

/-- **The short-root type-`G₂` integral toral closure is already generated scheme-theoretically by
its four numbered root subgroups.** Equivalently, adjoining the represented weight torus does not
change the integral defining Hopf ideal. -/
theorem definingIdeal_eq_kostantGeneratedDefiningIdeal :
    definingIdeal =
      kostantGeneratedDefiningIdeal rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis := by
  rw [definingIdeal_def]
  exact
    kostantToralDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary
      rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
      isNilpotent_rep_serreRootGenerator latticeBasis weight
      universalWeightTorus_mem_elementarySubgroup

/-- The short-root type-`G₂` integral toral closure is the group scheme generated by its four
numbered simple root subgroups. -/
theorem groupScheme_eq_kostantGeneratedGroupScheme :
    groupScheme =
      kostantGeneratedGroupScheme rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis :=
  kostantToralGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary
    rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis weight
    universalWeightTorus_mem_elementarySubgroup

/-- The canonical inclusion of the root-generated short-root type-`G₂` carrier into its toral
closure is an isomorphism. -/
instance isIso_kostantGeneratedToToral :
    CategoryTheory.IsIso (kostantGeneratedToToral rootGen cartanGen rep lattice.toAddSubgroup
      rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis weight) :=
  isIso_kostantGeneratedToToral_of_universal_torus_mem_elementary rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator
    latticeBasis weight universalWeightTorus_mem_elementarySubgroup

end IntegralToralClosure

end TauCeti.G2ShortRoot
