/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.Fourier.Pontryagin.Measure
public import TauCeti.RepresentationTheory.Continuous.Unitary.Basic
import TauCeti.Analysis.CStarAlgebra.CharacterSpaceMeasure
import TauCeti.RepresentationTheory.Continuous.Integrated.Algebra
import TauCeti.RepresentationTheory.Continuous.Pontryagin
import Mathlib.MeasureTheory.Measure.Haar.Unique

/-!
# Matrix coefficients of strongly continuous unitary representations

Let `π` be a strongly continuous unitary representation of a locally compact abelian group `G`
on a complex Hilbert space `H`, and let `ξ ∈ H`. The
diagonal matrix coefficient `g ↦ ⟪ξ, π(g) ξ⟫` is the Fourier–Stieltjes transform of a finite
positive measure on the Pontryagin dual of `G`. This is the cyclic form of the
Stone–Naimark–Ambrose–Godement spectral theorem.

The operators `π(g)` are only strongly continuous, so the spectral measure is built from the
integrated operators `π(f)`, `f ∈ L¹(G)`, taken with respect to a Haar measure. They generate a
unital commutative C⋆-algebra `A`, and the vector functional `a ↦ ⟪ξ, a ξ⟫` is integration
against a finite measure `ν` on the character space of `A`. A character `ω` that does not vanish
on every integrated operator determines a continuous group character `χ_ω` with
`ω(π(g) π(f)) = χ_ω(g) ω(π(f))`; this assignment is continuous on the open set of such
characters, and the image of `ν` under it is the required measure. The characters annihilating
every integrated operator do not contribute: since `π(f) ξ` approximates `ξ`, the identity
`∫ |ω(π(f)) - 1|² dν = ‖π(f) ξ - ξ‖²` forces `ω(π(f)) ≈ 1` in `L²(ν)`.

No second countability of `G` and no separability of `H` is needed: the integrated form is defined
for the Haar measure through its inner regularity for compact sets.

## Main declarations

* `ContRepresentation.exists_pontryaginMeasureTransform_eq_inner`: a diagonal matrix coefficient
  of a strongly continuous unitary representation of a locally compact abelian group is the
  Fourier–Stieltjes transform of a finite measure on the dual group.

## References

* G. B. Folland, *A Course in Abstract Harmonic Analysis*, 2nd ed., CRC Press (2016), §§3.2,
  4.4 and Theorem 4.44.
-/

public section

noncomputable section

open MeasureTheory WeakDual
open scoped InnerProductSpace

namespace TauCeti.StronglyContinuousSpectral

variable {G : Type*} [AddCommGroup G] {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [TopologicalSpace G] [IsTopologicalAddGroup G] [LocallyCompactSpace G]
  [MeasurableSpace G] [BorelSpace G] [CompleteSpace H]
  (π : ContRepresentation ℂ (Multiplicative G) H)
  (hcont : ∀ v, Continuous fun g : G ↦ π (.ofAdd g) v)
  (hπ : ContRepresentation.IsUnitary π)

/-- The closed star algebra generated by the integrated operators, for a Haar measure. -/
private abbrev algebra : StarSubalgebra ℂ (H →L[ℂ] H) :=
  π.integratedAlgebra hcont hπ.exists_norm_le Measure.addHaar

private instance : IsMulCommutative (algebra π hcont hπ) :=
  ContRepresentation.isMulCommutative_integratedAlgebra hπ

open scoped IsMulCommutative in
private noncomputable instance : CommCStarAlgebra (algebra π hcont hπ) where

/-- An integrated operator, as an element of the integrated algebra. -/
private abbrev op (f : G →₁[Measure.addHaar] ℂ) : algebra π hcont hπ :=
  π.integratedOperatorL1ToAlgebra hcont hπ.exists_norm_le Measure.addHaar f

/-- A translated integrated operator `π(g) π(f)`, as an element of the integrated algebra. -/
private abbrev translate (f : G →₁[Measure.addHaar] ℂ) (g : G) : algebra π hcont hπ :=
  π.translatedIntegratedOperatorL1 hcont hπ.exists_norm_le Measure.addHaar f g

private lemma translate_eq (f : G →₁[Measure.addHaar] ℂ) (g : G) :
    translate π hcont hπ f g =
      op π hcont hπ (Lp.compMeasurePreserving (fun x ↦ -g + x)
        (measurePreserving_add_left Measure.addHaar (-g)) f) :=
  π.translatedIntegratedOperatorL1_eq hcont _ _ f g

/-- The characters of the integrated algebra that do not annihilate every integrated
operator. -/
private def support : Set (characterSpace ℂ (algebra π hcont hπ)) :=
  {ω | ∃ f, ω (op π hcont hπ f) ≠ 0}

private lemma isOpen_support : IsOpen (support π hcont hπ) := by
  have : support π hcont hπ = ⋃ f, (fun ω ↦ ω (op π hcont hπ f)) ⁻¹' {0}ᶜ := by
    ext ω
    simp [support]
  rw [this]
  exact isOpen_iUnion fun f ↦ isOpen_compl_singleton.preimage
    (gelfandTransform ℂ (algebra π hcont hπ) (op π hcont hπ f)).continuous

/-- A character in the support satisfies the translation equation for some continuous group
character. -/
private lemma exists_dual_of_mem_support {ω : characterSpace ℂ (algebra π hcont hπ)}
    (hω : ω ∈ support π hcont hπ) :
    ∃ χ : PontryaginDual (Multiplicative G), ∀ g f,
      ω (translate π hcont hπ f g) = (χ (.ofAdd g) : ℂ) * ω (op π hcont hπ f) := by
  have hA (f : G →₁[Measure.addHaar] ℂ) :
      π.integratedOperatorL1 hcont hπ.exists_norm_le Measure.addHaar f ∈
        algebra π hcont hπ :=
    π.integratedOperatorL1_mem_integratedAlgebra hcont _ _ f
  have hop (f : G →₁[Measure.addHaar] ℂ) : op π hcont hπ f = ⟨_, hA f⟩ :=
    Subtype.ext (π.coe_integratedOperatorL1ToAlgebra hcont _ _ f)
  obtain ⟨f₀, hf₀⟩ := hω
  obtain ⟨χ, hχ, -⟩ := π.existsUnique_pontryaginDual_of_integratedOperatorL1 (μ := Measure.addHaar)
    hπ (algebra π hcont hπ) hA ω ⟨f₀, by rwa [← hop]⟩
  refine ⟨χ, fun g f ↦ ?_⟩
  rw [translate_eq, hop, hop]
  exact hχ g f

open Classical in
/-- The continuous group character attached to a character of the integrated algebra, and `1`
for a character annihilating every integrated operator. -/
private def dual (ω : characterSpace ℂ (algebra π hcont hπ)) :
    PontryaginDual (Multiplicative G) :=
  if hω : ω ∈ support π hcont hπ then (exists_dual_of_mem_support π hcont hπ hω).choose else 1

/-- **The translation equation.** Every character of the integrated algebra multiplies a
translated integrated operator by its group character. -/
private lemma apply_translate (ω : characterSpace ℂ (algebra π hcont hπ)) (g : G)
    (f : G →₁[Measure.addHaar] ℂ) :
    ω (translate π hcont hπ f g) = (dual π hcont hπ ω (.ofAdd g) : ℂ) * ω (op π hcont hπ f) := by
  by_cases hω : ω ∈ support π hcont hπ
  · simp only [dual, hω, ↓reduceDIte]
    exact (exists_dual_of_mem_support π hcont hπ hω).choose_spec g f
  · have h0 (f : G →₁[Measure.addHaar] ℂ) : ω (op π hcont hπ f) = 0 := by
      by_contra hf
      exact hω ⟨f, hf⟩
    rw [translate_eq, h0, h0, mul_zero]

/-- Where a character is nonzero on `π(f₀)`, its group character is the quotient
`ω(π(g) π(f₀)) / ω(π(f₀))`. -/
private lemma coe_dual_apply_eq_div {ω : characterSpace ℂ (algebra π hcont hπ)}
    {f₀ : G →₁[Measure.addHaar] ℂ} (hf₀ : ω (op π hcont hπ f₀) ≠ 0) (g : G) :
    (dual π hcont hπ ω (.ofAdd g) : ℂ) = ω (translate π hcont hπ f₀ g) / ω (op π hcont hπ f₀) := by
  rw [apply_translate, mul_div_cancel_right₀ _ hf₀]

/-- The group character of a character of the integrated algebra depends continuously on it, on
the open set of characters that do not annihilate every integrated operator. -/
private lemma continuousOn_dual : ContinuousOn (dual π hcont hπ) (support π hcont hπ) := by
  intro ω₀ hω₀
  obtain ⟨f₀, hf₀⟩ := hω₀
  set V := {ω : characterSpace ℂ (algebra π hcont hπ) | ω (op π hcont hπ f₀) ≠ 0}
  have hcV : Continuous fun ω : characterSpace ℂ (algebra π hcont hπ) ↦ ω (op π hcont hπ f₀) :=
    (gelfandTransform ℂ (algebra π hcont hπ) (op π hcont hπ f₀)).continuous
  have hV : IsOpen V := isOpen_compl_singleton.preimage hcV
  -- On `V`, the group character is a quotient of jointly continuous functions.
  have hnum : Continuous fun p : characterSpace ℂ (algebra π hcont hπ) × G ↦
      p.1 (translate π hcont hπ f₀ p.2) :=
    continuous_eval.comp
      ((((gelfandTransform_isometry (algebra π hcont hπ)).continuous.comp
        (π.continuous_translatedIntegratedOperatorL1 hcont _ _ f₀)).comp continuous_snd).prodMk
        continuous_fst)
  have hVcont : ContinuousOn (dual π hcont hπ) V := by
    rw [continuousOn_iff_continuous_domRestrict]
    refine ContinuousMonoidHom.continuous_of_continuous_uncurry _ (continuous_induced_rng.2 ?_)
    refine ((hnum.comp ((continuous_subtype_val.comp continuous_fst).prodMk
      (continuous_toAdd.comp continuous_snd))).div
      (hcV.comp (continuous_subtype_val.comp continuous_fst)) fun p ↦ p.1.2).congr fun p ↦ ?_
    exact (coe_dual_apply_eq_div π hcont hπ p.1.2 p.2.toAdd).symm
  exact (hVcont.continuousAt (hV.mem_nhds hf₀)).continuousWithinAt

/-- If `ν` represents the positive vector functional of `ξ`, then integrating `ω ↦ ω a` against
a weight bounded by `1` costs at most `δ ν(Δ) + ‖a ξ‖² / δ`, for every `δ > 0`. This is the
bound of an `L¹` norm by an `L²` norm, through `‖z‖ ≤ δ + ‖z‖² / δ`. -/
private lemma norm_integral_mul_apply_le [MeasurableSpace (characterSpace ℂ (algebra π hcont hπ))]
    [BorelSpace (characterSpace ℂ (algebra π hcont hπ))]
    {ν : Measure (characterSpace ℂ (algebra π hcont hπ))} [IsFiniteMeasure ν] {ξ : H}
    (hrep : ∀ a : algebra π hcont hπ, ⟪ξ, (a : H →L[ℂ] H) ξ⟫_ℂ = ∫ ω, ω a ∂ν)
    {w : characterSpace ℂ (algebra π hcont hπ) → ℂ}
    (hw₁ : ∀ ω, ‖w ω‖ ≤ 1) (a : algebra π hcont hπ) {δ : ℝ} (hδ : 0 < δ) :
    ‖∫ ω, w ω * ω a ∂ν‖ ≤ δ * ν.real Set.univ + ‖(a : H →L[ℂ] H) ξ‖ ^ 2 / δ := by
  have hint : Integrable (fun ω : characterSpace ℂ (algebra π hcont hπ) ↦ ‖ω a‖ ^ 2 / δ) ν :=
    (((gelfandTransform ℂ _ a).continuous.norm.pow 2).div_const δ).integrable_of_hasCompactSupport
      (.of_compactSpace _)
  calc _ ≤ ∫ ω, (δ + ‖ω a‖ ^ 2 / δ) ∂ν := by
        refine norm_integral_le_of_norm_le ((integrable_const δ).add hint)
          (.of_forall fun ω ↦ ?_)
        rw [norm_mul, add_div' _ _ _ hδ.ne', le_div_iff₀ hδ]
        nlinarith [sq_nonneg (‖ω a‖ - δ), norm_nonneg (ω a), norm_nonneg (w ω), hw₁ ω]
    _ = δ * ν.real Set.univ + ‖(a : H →L[ℂ] H) ξ‖ ^ 2 / δ := by
        rw [integral_add (integrable_const δ) hint, integral_const, integral_div,
          (algebra π hcont hπ).integral_norm_sq_eq_norm_apply_sq hrep a, smul_eq_mul, mul_comm]

variable [MeasurableSpace (PontryaginDual (Multiplicative G))]
  [BorelSpace (PontryaginDual (Multiplicative G))]

/-- The group character of a character of the integrated algebra depends measurably on it. -/
private lemma measurable_dual [MeasurableSpace (characterSpace ℂ (algebra π hcont hπ))]
    [BorelSpace (characterSpace ℂ (algebra π hcont hπ))] : Measurable (dual π hcont hπ) := by
  classical
  have : (support π hcont hπ).piecewise (dual π hcont hπ) (fun _ ↦ 1) = dual π hcont hπ := by
    funext ω
    by_cases hω : ω ∈ support π hcont hπ
    · simp [hω]
    · simp [hω, dual]
  rw [← this]
  exact (continuousOn_dual π hcont hπ).measurable_piecewise continuousOn_const
    (isOpen_support π hcont hπ).measurableSet

/-- **The matrix coefficient is the integral of the group characters.** If `ν` represents the
positive vector functional of `ξ` on the integrated algebra, then
`⟪ξ, π(g) ξ⟫ = ∫ χ_ω(g) dν(ω)`. -/
private lemma inner_eq_integral_dual [MeasurableSpace (characterSpace ℂ (algebra π hcont hπ))]
    [BorelSpace (characterSpace ℂ (algebra π hcont hπ))]
    {ν : Measure (characterSpace ℂ (algebra π hcont hπ))} [IsFiniteMeasure ν] {ξ : H}
    (hrep : ∀ a : algebra π hcont hπ, ⟪ξ, (a : H →L[ℂ] H) ξ⟫_ℂ = ∫ ω, ω a ∂ν) (g : G) :
    ⟪ξ, π (.ofAdd g) ξ⟫_ℂ = ∫ ω, (dual π hcont hπ ω (.ofAdd g) : ℂ) ∂ν := by
  set A := algebra π hcont hπ
  have hint (a : A) : Integrable (fun ω : characterSpace ℂ A ↦ ω a) ν :=
    (gelfandTransform ℂ A a).continuous.integrable_of_hasCompactSupport (.of_compactSpace _)
  have hχ : Integrable (fun ω ↦ (dual π hcont hπ ω (.ofAdd g) : ℂ)) ν :=
    .of_bound ((PontryaginDual.continuous_coe_eval_const _).measurable.comp
      (measurable_dual π hcont hπ)).aestronglyMeasurable 1 (.of_forall fun ω ↦ by simp)
  -- Approximate `ξ` by `π(f) ξ` to within `δ`, where `δ` is scaled to the target accuracy `ε`.
  set C := ‖ξ‖ + ν.real Set.univ + 1
  have hC : 0 < C := by positivity
  refine eq_of_forall_dist_le fun ε hε ↦ ?_
  set δ := ε / C
  have hδ : 0 < δ := div_pos hε hC
  obtain ⟨_, ⟨f, rfl⟩, hf⟩ := Metric.mem_closure_iff.mp
    (π.mem_closure_range_integratedOperatorL1_apply (hcont := hcont)
      (hbdd := hπ.exists_norm_le) (μ := Measure.addHaar) ξ) δ hδ
  set a : A := op π hcont hπ f - 1
  have ha : (a : H →L[ℂ] H) ξ =
      π.integratedOperatorL1 hcont hπ.exists_norm_le Measure.addHaar f ξ - ξ := by
    simp [a]
  have had : ‖(a : H →L[ℂ] H) ξ‖ ≤ δ := by
    rw [ha, ← dist_eq_norm, dist_comm]
    exact hf.le
  -- Through `π(f)`, the matrix coefficient is an integral by the translation equation.
  have hf' : ⟪ξ, π (.ofAdd g)
      (π.integratedOperatorL1 hcont hπ.exists_norm_le Measure.addHaar f ξ)⟫_ℂ =
      ∫ ω, (dual π hcont hπ ω (.ofAdd g) : ℂ) * ω (op π hcont hπ f) ∂ν := by
    rw [← integral_congr_ae (.of_forall fun ω ↦ apply_translate π hcont hπ ω g f), ← hrep]
    simp
  have hsplit : ⟪ξ, π (.ofAdd g) ξ⟫_ℂ - ∫ ω, (dual π hcont hπ ω (.ofAdd g) : ℂ) ∂ν =
      ∫ ω, (dual π hcont hπ ω (.ofAdd g) : ℂ) * ω a ∂ν -
        ⟪ξ, π (.ofAdd g) ((a : H →L[ℂ] H) ξ)⟫_ℂ := by
    have hωa (ω : characterSpace ℂ A) : ω a = ω (op π hcont hπ f) - 1 := by simp [a]
    simp_rw [hωa, mul_sub, mul_one]
    rw [integral_sub ((hint _).bdd_mul hχ.aestronglyMeasurable (c := 1)
      (.of_forall fun ω ↦ by simp)) hχ, ← hf', ha, map_sub, inner_sub_right]
    ring
  -- Each error term is at most a multiple of `δ`.
  have hL1 : ‖∫ ω, (dual π hcont hπ ω (.ofAdd g) : ℂ) * ω a ∂ν‖ ≤
      δ * ν.real Set.univ + δ := by
    refine (norm_integral_mul_apply_le π hcont hπ hrep (fun ω ↦ by simp) a hδ).trans ?_
    gcongr
    rw [div_le_iff₀ hδ, sq]
    exact mul_le_mul had had (norm_nonneg _) hδ.le
  have hinner : ‖⟪ξ, π (.ofAdd g) ((a : H →L[ℂ] H) ξ)⟫_ℂ‖ ≤ ‖ξ‖ * δ := by
    refine (norm_inner_le_norm _ _).trans ?_
    rw [hπ.norm_map]
    gcongr
  calc dist _ _ ≤ (δ * ν.real Set.univ + δ) + ‖ξ‖ * δ := by
        rw [dist_eq_norm, hsplit]
        exact (norm_sub_le _ _).trans (add_le_add hL1 hinner)
    _ = ε := by
        simp only [δ, C]
        field_simp
        ring

end TauCeti.StronglyContinuousSpectral

open TauCeti.StronglyContinuousSpectral

variable {G : Type*} [AddCommGroup G] [TopologicalSpace G] [IsTopologicalAddGroup G]
  [LocallyCompactSpace G]
  [MeasurableSpace (PontryaginDual (Multiplicative G))]
  [BorelSpace (PontryaginDual (Multiplicative G))]
  {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- **Spectral theorem for strongly continuous unitary representations**, cyclic form. For a
strongly continuous unitary representation `π` of a locally compact abelian group `G` on a
Hilbert space `H` and a vector `ξ`, the matrix coefficient `g ↦ ⟪ξ, π(g) ξ⟫` is the
Fourier–Stieltjes transform of a finite measure on the Pontryagin dual of `G`. -/
theorem ContRepresentation.exists_pontryaginMeasureTransform_eq_inner
    (π : ContRepresentation ℂ (Multiplicative G) H)
    (hcont : ∀ v, Continuous fun g : G ↦ π (.ofAdd g) v)
    (hπ : TauCeti.ContRepresentation.IsUnitary π) (ξ : H) :
    ∃ μ : FiniteMeasure (PontryaginDual (Multiplicative G)),
      ∀ g, μ.pontryaginMeasureTransform g = ⟪ξ, π (.ofAdd g) ξ⟫_ℂ := by
  borelize G
  set A := algebra π hcont hπ
  borelize ↥(characterSpace ℂ A)
  obtain ⟨ν, hν, hrep⟩ := A.exists_isFiniteMeasure_integral_characterSpace_eq_inner ξ
  have hθ := measurable_dual π hcont hπ
  let νf : FiniteMeasure (characterSpace ℂ A) := ⟨ν, hν⟩
  refine ⟨νf.map (dual π hcont hπ), fun g ↦ ?_⟩
  rw [FiniteMeasure.pontryaginMeasureTransform_apply, FiniteMeasure.toMeasure_map,
    integral_map hθ.aemeasurable
      (TauCeti.PontryaginDual.continuous_coe_eval_const _).aestronglyMeasurable,
    FiniteMeasure.toMeasure_mk, inner_eq_integral_dual π hcont hπ hrep]
