/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Group.Subgroup.Ker
public import TauCeti.Algebra.Group.Subgroup.ModularLaw

/-!
# Kernels, ranges and equality loci of group homomorphisms

This file supplies the characteristic membership equation for the subgroup equality locus, the
invariance of the range of a group homomorphism under precomposition with a surjection, and
describes the kernel of a homomorphism `f : G →* M` from a subgroup `N ≤ ker f` and a subgroup `H`
normalizing `N` with `H ⊔ N = ⊤`: by Dedekind's modular law `ker f = (ker f ⊓ H) ⊔ N`, so
`ker f = N` as soon as `f` is injective on `H`. This is how the kernel of a character is read
off its values on generators: `N` is the normal closure of the generators the character kills,
and `H` is the subgroup generated by the remaining ones.

## Main results

* `MonoidHom.mem_eqLocus`: membership in the equality locus is pointwise equality.
* `MonoidHom.range_comp_of_surjective`: precomposition with a surjection preserves the range.
* `MonoidHom.ker_eq_ker_inf_sup_of_sup_eq_top`: `ker f = (ker f ⊓ H) ⊔ N` for `N ≤ ker f`
  normalized by `H` and `H ⊔ N = ⊤`.
* `MonoidHom.ker_eq_of_sup_eq_top_of_inf_ker_eq_bot`: `ker f = N` when moreover
  `H ⊓ ker f = ⊥`.
-/

public section

namespace MonoidHom

variable {G M : Type*} [Group G] [Monoid M]

/-- Membership in the equality locus of two group homomorphisms is pointwise equality. -/
@[to_additive (attr := simp)]
theorem mem_eqLocus {f g : G →* M} {x : G} : x ∈ f.eqLocus g ↔ f x = g x :=
  Iff.rfl

/-- Precomposition with a surjective group homomorphism does not change the range. -/
@[to_additive /-- Precomposition with a surjective additive group homomorphism does not change the
range. -/]
theorem range_comp_of_surjective {N P : Type*} [Group N] [Group P] (g : N →* P) (f : G →* N)
    (hf : Function.Surjective f) : (g.comp f).range = g.range := by
  rw [range_comp, range_eq_top_of_surjective f hf, ← range_eq_map]

/-- The kernel of `f` is cut out by a subgroup `N ≤ ker f` and a subgroup `H` normalizing `N`
with `H ⊔ N = ⊤`: `ker f = (ker f ⊓ H) ⊔ N`, by Dedekind's modular law. -/
@[to_additive /-- The kernel of `f` is cut out by an additive subgroup `N ≤ ker f` and an additive
subgroup `H` normalizing `N` with `H ⊔ N = ⊤`: `ker f = (ker f ⊓ H) ⊔ N`, by Dedekind's modular
law. -/]
theorem ker_eq_ker_inf_sup_of_sup_eq_top {f : G →* M} {H N : Subgroup G}
    (hHN : H ≤ Subgroup.normalizer (N : Set G)) (hN : N ≤ f.ker) (hsup : H ⊔ N = ⊤) :
    f.ker = (f.ker ⊓ H) ⊔ N := by
  rw [Subgroup.inf_sup_assoc_of_le hHN hN, hsup, inf_top_eq]

/-- If a subgroup `N ≤ ker f` and a subgroup `H` normalizing `N` on which `f` is injective satisfy
`H ⊔ N = ⊤`, then `ker f = N`. -/
@[to_additive /-- If an additive subgroup `N ≤ ker f` and an additive subgroup `H` normalizing `N`
on which `f` is injective satisfy `H ⊔ N = ⊤`, then `ker f = N`. -/]
theorem ker_eq_of_sup_eq_top_of_inf_ker_eq_bot {f : G →* M} {H N : Subgroup G}
    (hHN : H ≤ Subgroup.normalizer (N : Set G)) (hN : N ≤ f.ker) (hsup : H ⊔ N = ⊤)
    (hH : H ⊓ f.ker = ⊥) : f.ker = N := by
  rw [ker_eq_ker_inf_sup_of_sup_eq_top hHN hN hsup, inf_comm, hH, bot_sup_eq]

end MonoidHom
