/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.OrderOfElement

/-!
# When a cyclic subgroup of a product meets a factor trivially

For `σ : G` and `τ : H`, the cyclic subgroup generated by `(σ, τ)` meets the first factor
`G × 1` trivially as soon as `orderOf σ ∣ orderOf τ`.

The two factors behave differently: the meet with `1 × H` is trivial under the *reverse*
divisibility, so the two statements are not interchangeable and the direction matters at every
call site.

No finiteness is assumed. `orderOf x = 0` for an element of infinite order, so the hypothesis is
also meaningful there, and covers the case of `σ` of infinite order.

## References

The proof skeleton is adapted from `cyclic_subgroup_meets_G_times_one_trivially` in
`CebotarevDensity/Abelian.lean` of
[CBirkbeck/chebotarev-density](https://github.com/CBirkbeck/chebotarev-density) (Apache-2.0,
Birkbeck--Brasca) at commit `8575c9df1ae0a61120ab5c964c7911414254bec7`. That version assumes
`Nat.card G ∣ orderOf τ` with both groups finite; the hypothesis here is weaker.

## Main results

* `Subgroup.zpowers_inf_top_prod_bot_eq_bot_of_orderOf_dvd`
-/

public section

namespace Subgroup

/-- **A cyclic subgroup of a product meets the first factor trivially**, whenever the order of
the first coordinate divides that of the second: `⟨(σ, τ)⟩ ⊓ (G × 1) = 1`.

For the meet with the second factor `1 × H`, the divisibility runs the other way. -/
theorem zpowers_inf_top_prod_bot_eq_bot_of_orderOf_dvd {G H : Type*} [Group G] [Group H]
    (σ : G) (τ : H) (hστ : orderOf σ ∣ orderOf τ) :
    zpowers ((σ, τ) : G × H) ⊓ (⊤ : Subgroup G).prod (⊥ : Subgroup H) = ⊥ := by
  rw [eq_bot_iff]
  rintro ⟨g, h⟩ hmem
  rw [mem_inf, mem_prod, mem_bot] at hmem
  obtain ⟨⟨k, hk⟩, -, (hh : h = 1)⟩ := hmem
  have hτ : τ ^ k = 1 := by simpa [hh] using congrArg Prod.snd hk
  have hσ : σ ^ k = 1 :=
    orderOf_dvd_iff_zpow_eq_one.mp (hστ.natCast.trans (orderOf_dvd_iff_zpow_eq_one.mpr hτ))
  rw [mem_bot, Prod.mk_eq_one]
  exact ⟨by simpa [hσ] using (congrArg Prod.fst hk).symm, hh⟩

end Subgroup
