/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Geometry.Lie.Exponential.Smoothness
import Mathlib.Analysis.Calculus.MeanValue

/-!
# Derivative of the Lie-group exponential

In identity-chart coordinates, the invariant vector field generated by `v` has the form
`A(y) v`, where `A` is continuous and `A(1) = id`. A uniform local flow and the mean-value
inequality therefore show that its time-one endpoint differs from the straight line `v` by
`o(‖v‖)`.

## Main results

* `hasFDerivAt_mulInvariantExp_modelSpace_zero`: in model-space identity coordinates, the
  tangent-space exponential has derivative the identity at zero.
* `contDiffAt_mulInvariantExp_modelSpace_zero`: the coordinate exponential is smooth at zero.
* `hasStrictFDerivAt_mulInvariantExp_modelSpace_zero`: the same derivative is strict.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 0, "The exponential map".
-/

public section

open Asymptotics Function Manifold Set
open scoped ContDiff Manifold Topology

noncomputable section

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]
  [IsManifold I 1 G] [IsManifold I 2 G]

local instance lieGroupMinSmoothnessDerivative [LieGroup I ∞ G] :
    LieGroup I (minSmoothness ℝ 3) G := by
  simpa using (inferInstance : LieGroup I (3 : ℕ∞ω) G)

omit [IsManifold I 2 G] in
/-- In model-space identity coordinates, the tangent-space exponential has derivative the identity
at zero. -/
theorem hasFDerivAt_mulInvariantExp_modelSpace_zero
    [FiniteDimensional ℝ E] [LieGroup I ∞ G] [T2Space G] [BoundarylessManifold I G] :
    HasFDerivAt
      (fun v : E => extChartAt I (1 : G)
        (mulInvariantExp (I := I) (G := G) (v : GroupLieAlgebra I G)))
      (ContinuousLinearMap.id ℝ E) 0 := by
  let _ : CompleteSpace E := FiniteDimensional.complete ℝ E
  let center : E := extChartAt I (1 : G) (1 : G)
  let F : E → E := fun v => extChartAt I (1 : G)
    (mulInvariantExp (I := I) (G := G) (v : GroupLieAlgebra I G))
  let A : E → E →L[ℝ] E := mulInvariantCoordinateLinearMap (I := I) (G := G)
  obtain ⟨α, U, δ, hU, hδ, hαlocal, hαeq⟩ :=
    exists_local_coordinate_representation_mulInvariantIntegralCurve (I := I) (G := G)
  have hzeroU : (0 : E) ∈ U := mem_of_mem_nhds hU
  have htimeZero : (0 : ℝ) ∈ Set.Ioo (-δ) δ := by constructor <;> linarith
  have hFzero : F 0 = center := by
    change extChartAt I (1 : G)
      (mulInvariantExp (I := I) (G := G) (0 : GroupLieAlgebra I G)) =
        extChartAt I (1 : G) (1 : G)
    rw [mulInvariantExp_zero]
  rw [show (fun v : E => extChartAt I (1 : G)
      (mulInvariantExp (I := I) (G := G) (v : GroupLieAlgebra I G))) = F from rfl]
  rw [hasFDerivAt_iff_isLittleO_nhds_zero, isLittleO_iff]
  intro ε hε
  have hAcont : ContinuousAt A center := by
    exact (contDiffAt_mulInvariantCoordinateLinearMap_identity
      (I := I) (G := G) BoundarylessManifold.isInteriorPoint).continuousAt
  have hAcenter : A center = ContinuousLinearMap.id ℝ E := by
    dsimp only [A, center]
    change mulInvariantCoordinateLinearMap (I := I) (G := G)
      (I (chartAt H (1 : G) (1 : G))) = ContinuousLinearMap.id ℝ E
    exact mulInvariantCoordinateLinearMap_identity (I := I) (G := G)
  let S : Set E := {y | ‖A y - ContinuousLinearMap.id ℝ E‖ ≤ ε}
  have hS : S ∈ 𝓝 center := by
    have hnorm : ContinuousAt (fun y => ‖A y - ContinuousLinearMap.id ℝ E‖) center :=
      (hAcont.sub continuousAt_const).norm
    have hlt : Set.Iio ε ∈ 𝓝 ‖A center - ContinuousLinearMap.id ℝ E‖ := by
      rw [hAcenter, sub_self, norm_zero]
      exact Iio_mem_nhds hε
    apply Filter.mem_of_superset (hnorm.preimage_mem_nhds hlt)
    intro y hy
    change ‖A y - ContinuousLinearMap.id ℝ E‖ < ε at hy
    exact hy.le
  let β : (E × E) × ℝ → E := fun xt => (α xt).2
  have hβcont : ContinuousAt β (((0 : E), center), 0) :=
    continuousAt_snd.comp' (hαlocal 0 hzeroU 0 htimeZero).1
  have hβcenter : β (((0 : E), center), 0) = center := by
    exact congrArg Prod.snd (hαlocal 0 hzeroU 0 htimeZero).2.2.1
  have hnear : β ⁻¹' S ∈ 𝓝 (((0 : E), center), 0) := by
    apply hβcont.preimage_mem_nhds
    rw [hβcenter]
    exact hS
  rw [nhds_prod_eq] at hnear
  obtain ⟨W, hW, T, hT, hWT⟩ := Filter.mem_prod_iff.mp hnear
  obtain ⟨η, hη, hηT⟩ := Metric.mem_nhds_iff.mp hT
  let c : ℝ := min δ η / 2
  have hc : 0 < c := by dsimp only [c]; positivity
  have hcδ : c < δ := by dsimp only [c]; linarith [min_le_left δ η]
  have hcη : c < η := by dsimp only [c]; linarith [min_le_right δ η]
  have hcflow : c ∈ Set.Ioo (-δ) δ := ⟨by linarith, hcδ⟩
  have hc0 : c ≠ 0 := hc.ne'
  let q : E → E × E := fun v => (c⁻¹ • v, center)
  have hq : ContinuousAt q (0 : E) := by fun_prop
  have hqzero : q 0 = ((0 : E), center) := by simp only [q, smul_zero]
  have hqW : q ⁻¹' W ∈ 𝓝 (0 : E) :=
    hq.preimage_mem_nhds (by simpa only [hqzero] using hW)
  have hrescale : ContinuousAt (fun v : E => c⁻¹ • v) 0 := by fun_prop
  have hrescaleU : (fun v : E => c⁻¹ • v) ⁻¹' U ∈ 𝓝 0 :=
    hrescale.preimage_mem_nhds (by simpa only [smul_zero] using hU)
  filter_upwards [hqW, hrescaleU] with v hvW hvU
  let w : E := c⁻¹ • v
  let z : ℝ → E := fun t => (α (((w, center), t))).2
  let e : ℝ → E := fun t => z t - center - t • w
  have htflow (t : ℝ) (ht : t ∈ Set.Icc (0 : ℝ) c) : t ∈ Set.Ioo (-δ) δ :=
    ⟨by linarith [ht.1], lt_of_le_of_lt ht.2 hcδ⟩
  have htT (t : ℝ) (ht : t ∈ Set.Icc (0 : ℝ) c) : t ∈ T := by
    apply hηT
    rw [Metric.mem_ball, dist_zero_right, Real.norm_eq_abs, abs_of_nonneg ht.1]
    exact lt_of_le_of_lt ht.2 hcη
  have hzderiv (t : ℝ) (ht : t ∈ Set.Icc (0 : ℝ) c) :
      HasDerivAt z (A (z t) w) t := by
    have hlocal := hαlocal w hvU t (htflow t ht)
    have hfull := hlocal.2.1
    have hsnd := (ContinuousLinearMap.snd ℝ E E).hasFDerivAt.comp_hasDerivAt t hfull
    have hpair : α (((w, center), t)) = (w, z t) := by
      exact Prod.ext hlocal.2.2.2.1 rfl
    rw [hpair] at hsnd
    change HasDerivAt (fun s => (α (((w, center), s))).2)
      (mulInvariantCoordinateVectorField (I := I) (G := G) (w, z t)) t at hsnd
    simpa only [z, A, mulInvariantCoordinateLinearMap_apply] using hsnd
  have hAbound (t : ℝ) (ht : t ∈ Set.Icc (0 : ℝ) c) :
      ‖A (z t) - ContinuousLinearMap.id ℝ E‖ ≤ ε := by
    have hmem : (q v, t) ∈ β ⁻¹' S := hWT ⟨hvW, htT t ht⟩
    simpa only [β, q, z, w, S, Set.mem_preimage, Set.mem_ofPred_eq] using hmem
  have hederiv (t : ℝ) (ht : t ∈ Set.Icc (0 : ℝ) c) :
      HasDerivAt e ((A (z t) - ContinuousLinearMap.id ℝ E) w) t := by
    have h := ((hzderiv t ht).sub_const center).sub ((hasDerivAt_id t).smul_const w)
    apply h.congr_deriv
    simp only [one_smul, sub_apply, ContinuousLinearMap.id_apply]
  have heBound (t : ℝ) (ht : t ∈ Set.Icc (0 : ℝ) c) :
      ‖(A (z t) - ContinuousLinearMap.id ℝ E) w‖ ≤ ε * ‖w‖ :=
    (ContinuousLinearMap.le_opNorm _ _).trans
      (mul_le_mul_of_nonneg_right (hAbound t ht) (norm_nonneg w))
  have herr : ‖e c - e 0‖ ≤ (ε * ‖w‖) * (c - 0) :=
    norm_image_sub_le_of_norm_deriv_le_segment'
      (fun t ht => (hederiv t ht).hasDerivWithinAt)
      (fun t ht => heBound t (Set.Ico_subset_Icc_self ht)) c ⟨hc.le, le_rfl⟩
  have hzzero : z 0 = center := by
    exact congrArg Prod.snd (hαlocal w hvU 0 htimeZero).2.2.1
  have hcw : c • w = v := by
    simp only [w, smul_smul, mul_inv_cancel₀ hc0, one_smul]
  have hexp : (extChartAt I (1 : G)).symm (z c) =
      mulInvariantExp (I := I) (G := G) (v : GroupLieAlgebra I G) := by
    calc
      (extChartAt I (1 : G)).symm (z c) =
          mulInvariantIntegralCurve (I := I) (G := G)
            (w : GroupLieAlgebra I G) 1 c := hαeq w hvU hcflow
      _ = mulInvariantExp (I := I) (G := G)
          (c • (w : GroupLieAlgebra I G)) :=
        (mulInvariantExp_smul (I := I) (G := G) (w : GroupLieAlgebra I G) c).symm
      _ = mulInvariantExp (I := I) (G := G) (v : GroupLieAlgebra I G) := by rw [hcw]
  have hF : F v = z c := by
    change extChartAt I (1 : G)
      (mulInvariantExp (I := I) (G := G) (v : GroupLieAlgebra I G)) = z c
    rw [← hexp]
    exact (extChartAt I (1 : G)).right_inv
      (Set.mem_of_mem_of_subset (hαlocal w hvU c hcflow).2.2.2.2 interior_subset)
  calc
    ‖F (0 + v) - F 0 - (ContinuousLinearMap.id ℝ E) v‖ = ‖e c - e 0‖ := by
      rw [zero_add, hF, hFzero, ContinuousLinearMap.id_apply]
      change ‖z c - center - v‖ =
        ‖(z c - center - c • w) - (z 0 - center - 0 • w)‖
      rw [hzzero, zero_smul, sub_self, hcw, sub_zero, sub_zero]
    _ ≤ (ε * ‖w‖) * (c - 0) := herr
    _ = ε * ‖v‖ := by
      dsimp only [w]
      rw [sub_zero, norm_smul, Real.norm_eq_abs, abs_inv, abs_of_pos hc]
      field_simp

omit [IsManifold I 2 G] in
/-- The tangent-space exponential is smooth at zero in model-space identity coordinates. -/
theorem contDiffAt_mulInvariantExp_modelSpace_zero
    [FiniteDimensional ℝ E] [LieGroup I ∞ G] [T2Space G] [BoundarylessManifold I G] :
    ContDiffAt ℝ ∞
      (fun v : E => extChartAt I (1 : G)
        (mulInvariantExp (I := I) (G := G) (v : GroupLieAlgebra I G))) 0 := by
  let _ : CompleteSpace E := FiniteDimensional.complete ℝ E
  have hsmooth := contMDiffAt_mulInvariantExp_zero (I := I) (G := G)
  have hzero : mulInvariantExp (I := I) (G := G)
      (0 : GroupLieAlgebra I G) = 1 := mulInvariantExp_zero
  rw [contMDiffAt_iff_target_of_mem_source (y := (1 : G)) (by
    convert mem_chart_source H (1 : G) using 1
    exact hzero)] at hsmooth
  simpa only [Function.comp_def] using hsmooth.2.contDiffAt

omit [IsManifold I 2 G] in
/-- In model-space identity coordinates, the tangent-space exponential has strict derivative the
identity at zero. -/
theorem hasStrictFDerivAt_mulInvariantExp_modelSpace_zero
    [FiniteDimensional ℝ E] [LieGroup I ∞ G] [T2Space G] [BoundarylessManifold I G] :
    HasStrictFDerivAt
      (fun v : E => extChartAt I (1 : G)
        (mulInvariantExp (I := I) (G := G) (v : GroupLieAlgebra I G)))
      (ContinuousLinearMap.id ℝ E) 0 := by
  let _ : CompleteSpace E := FiniteDimensional.complete ℝ E
  have hderiv := hasFDerivAt_mulInvariantExp_modelSpace_zero (I := I) (G := G)
  have hcoord := contDiffAt_mulInvariantExp_modelSpace_zero (I := I) (G := G)
  exact hcoord.hasStrictFDerivAt' hderiv (by simp)
