/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.LinearAlgebra.QuadraticForm.CartanDieudonne.Basic
import Mathlib.GroupTheory.OrderOfElement

/-!
# Generation of the special orthogonal group by pairs of reflections

For a finite-dimensional nondegenerate quadratic space in characteristic different from two,
the special orthogonal group is generated, even as a monoid, by products of two reflections.
This is the determinant-one form of the Cartan--Dieudonné theorem. It reduces questions about
all special orthogonal transformations to reflection pairs, as needed when proving connectedness
by putting those pairs in the identity component.

The proof reuses `TauCeti.QuadraticMap.subgroup_eq_top_of_reflection_mem`. Reflections are
involutions, so their monoid closure is already the orthogonal group. Left induction on that
closure keeps track of the two possible determinants and groups adjacent reflections into pairs.

## References

* H. B. Lawson and M.-L. Michelsohn, *Spin Geometry* (1989), Chapter I, §2.
-/

public section

namespace TauCeti.QuadraticMap

universe u v

variable {K : Type u} {V : Type v} [Field K] [AddCommGroup V] [Module K V]
  [FiniteDimensional K V] [NeZero (2 : K)]

private theorem monoidClosure_reflections_eq_top
    (Q : QuadraticForm K V) (hQ : Q.Nondegenerate) :
    Submonoid.closure {g : orthogonalGroup Q |
      ∃ (v : V) (_ : Invertible (Q v)), reflectionOrthogonal Q v = g} = ⊤ := by
  let S : Set (orthogonalGroup Q) :=
    {g | ∃ (v : V) (_ : Invertible (Q v)), reflectionOrthogonal Q v = g}
  have hfin : ∀ g ∈ S, IsOfFinOrder g := by
    rintro _ ⟨v, hv, rfl⟩
    exact isOfFinOrder_iff_pow_eq_one.mpr
      ⟨2, by decide, by rw [pow_two, reflectionOrthogonal_mul_self]⟩
  rw [← Subgroup.closure_toSubmonoid_of_isOfFinOrder hfin]
  have htop : Subgroup.closure S = ⊤ :=
    subgroup_eq_top_of_reflection_mem Q hQ (Subgroup.closure S)
      (fun v hv ↦ Subgroup.subset_closure ⟨v, hv, rfl⟩)
  rw [htop]
  rfl

/-- Every determinant-one orthogonal transformation belongs to any submonoid containing all
products of two reflections. No nonzero-dimensional hypothesis is required. -/
theorem specialOrthogonalGroup_le_of_reflection_mul_mem
    (Q : QuadraticForm K V) (hQ : Q.Nondegenerate)
    (M : Submonoid (V ≃ₗ[K] V))
    (hM : ∀ (v w : V) [Invertible (Q v)] [Invertible (Q w)],
      reflection Q v * reflection Q w ∈ M) :
    (specialOrthogonalGroup Q).toSubmonoid ≤ M := by
  have hind (g : orthogonalGroup Q) :
      (LinearEquiv.det g.val = 1 → g.val ∈ M) ∧
      (LinearEquiv.det g.val = -1 →
        ∀ (v : V) [Invertible (Q v)], reflection Q v * g.val ∈ M) := by
    refine Submonoid.induction_of_closure_eq_top_left
      (motive := fun g : orthogonalGroup Q ↦
        (LinearEquiv.det g.val = 1 → g.val ∈ M) ∧
        (LinearEquiv.det g.val = -1 →
          ∀ (v : V) [Invertible (Q v)], reflection Q v * g.val ∈ M))
      (monoidClosure_reflections_eq_top Q hQ) g ?_ ?_
    · refine ⟨fun _ ↦ M.one_mem, ?_⟩
      intro h
      have hneg : (1 : K) = -1 := by simpa using congrArg Units.val h
      have htwo : (2 : K) = 0 := by linear_combination hneg
      exact (NeZero.ne (2 : K) htwo).elim
    · rintro _ ⟨w, hw, rfl⟩ y ih
      simp only [Subgroup.coe_mul, coe_reflectionOrthogonal, map_mul, det_reflection]
      constructor
      · intro h
        apply ih.2
        exact (neg_eq_iff_eq_neg.mp (by simpa using h))
      · intro h v hv
        have hy : LinearEquiv.det y.val = 1 := by
          simpa using h
        simpa only [mul_assoc] using M.mul_mem (hM v w) (ih.1 hy)
  intro g hg
  have hg' := mem_specialOrthogonalGroup_iff.mp hg
  exact (hind ⟨g, hg'.1⟩).1 hg'.2

/-- The monoid generated by pairs of reflections is exactly the special orthogonal group of
a finite-dimensional nondegenerate quadratic space in characteristic different from two. -/
theorem closure_reflection_mul_eq_specialOrthogonalGroup
    (Q : QuadraticForm K V) (hQ : Q.Nondegenerate) :
    Submonoid.closure {g : V ≃ₗ[K] V |
      ∃ (v w : V) (_ : Invertible (Q v)) (_ : Invertible (Q w)),
        reflection Q v * reflection Q w = g} =
      (specialOrthogonalGroup Q).toSubmonoid := by
  apply le_antisymm
  · apply Submonoid.closure_le.mpr
    rintro _ ⟨v, w, hv, hw, rfl⟩
    apply mem_specialOrthogonalGroup_iff.mpr
    exact ⟨(orthogonalGroup Q).mul_mem
      (reflection_mem_orthogonalGroup Q v) (reflection_mem_orthogonalGroup Q w), by simp⟩
  · exact specialOrthogonalGroup_le_of_reflection_mul_mem Q hQ _
      (fun v w hv hw ↦ Submonoid.subset_closure ⟨v, w, hv, hw, rfl⟩)

end TauCeti.QuadraticMap
