/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Algebra.AlgebraicGroup.Center.Basic
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.BaseChange

/-!
# Base change of the center of an affine group scheme

For a field extension `k → K` and a commutative Hopf `k`-algebra `H`, this file proves the
coordinate identity

```text
  baseChangeHopfIdeal (centerDefiningIdeal H) = centerDefiningIdeal (baseChange H).
```

Together with `TauCeti.CommHopfAlgCat.quotientBaseChangeIso`, this identifies the quotient
coordinate Hopf algebras of the base change of the center and the center after base change. One
containment follows because the base change of a central closed subgroup is central. For the
other, the universal point of the center after base change restricts to a universally central
point of `H`, so it kills every equation of the original center.

## Main results

* `TauCeti.CommHopfAlgCat.baseChangeHopfIdeal_centerDefiningIdeal`: the defining ideal of the
  center commutes with extension of the ground field.
* `TauCeti.CommHopfAlgCat.centerDefiningIdeal_baseChange_eq_augmentation_iff`: a field extension
  preserves and reflects triviality of the center.

## References

* J. S. Milne, *Algebraic Groups* (2017), §1.k and §2.
* W. C. Waterhouse, *Introduction to Affine Group Schemes*, Chapters 2 and 16.

This supplies the base-change compatibility of the center `Z(G)` required in Layer 6,
"Reductive and semisimple groups", of the ReductiveGroups roadmap.
-/

public section

open WithConv

namespace TauCeti.CommHopfAlgCat

universe u v

variable {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]

/-- **Formation of the center commutes with extension of the ground field.** The ideal of
`K ⊗[k] H` generated by the center equations of `H` is exactly the ideal defining the center
after base change. -/
@[simp]
theorem baseChangeHopfIdeal_centerDefiningIdeal
    (H : _root_.CommHopfAlgCat.{v} k) :
    baseChangeHopfIdeal (K := K) (centerDefiningIdeal H) =
      centerDefiningIdeal (baseChange (K := K) H) := by
  apply le_antisymm
  · intro y hy
    let B := baseChange (K := K) H
    let I := centerDefiningIdeal B
    let A : CommAlgCat.{v} K := CommAlgCat.of K (B ⧸ I.toIdeal)
    let q : HopfAlgebra.points (R := K) (H := B) A :=
      quotientPointsHom B I A (toConv (AlgHom.id K _))
    have hqmem : q ∈ centerPointsSubgroup B A :=
      quotientPointsHom_mem_quotientPointsSubgroup B I A _
    have hqcentral : HopfAlgebra.IsCentralPoint q :=
      (mem_centerPointsSubgroup_iff B A q).mp hqmem
    have hrestrictCentral :=
      (isCentralPoint_baseChangePointsMulEquiv_iff H A q).mpr hqcentral
    have hrestrictMem : baseChangePointsMulEquiv (K := K) A H q ∈
        centerPointsSubgroup H
          (_root_.TauCeti.CommAlgCat.restrictScalarsObj (algebraMap k K) A) :=
      (mem_centerPointsSubgroup_iff H _ _).mpr hrestrictCentral
    exact HopfIdeal.mem_toIdeal.mpr ((mkQuotient_eq_zero_iff B I y).mp
      ((mem_quotientPointsSubgroup_iff B
        (baseChangeHopfIdeal (K := K) (centerDefiningIdeal H)) A q).mp
          ((mem_quotientPointsSubgroup_baseChangeHopfIdeal_iff
            (K := K) A (centerDefiningIdeal H) q).mpr hrestrictMem) y hy))
  · exact (centerDefiningIdeal_le_iff _ _).mpr
      (isCentral_baseChangeHopfIdeal (isCentral_centerDefiningIdeal H))

/-- A field extension preserves and reflects triviality of the scheme-theoretic center.

The statement uses the augmentation ideal, which cuts out the identity subgroup. Thus it detects
the full center scheme, including infinitesimal structure invisible on field-valued points. -/
@[simp]
theorem centerDefiningIdeal_baseChange_eq_augmentation_iff
    (H : _root_.CommHopfAlgCat.{v} k) :
    centerDefiningIdeal (baseChange (K := K) H) =
        HopfIdeal.augmentation K (baseChange (K := K) H) ↔
      centerDefiningIdeal H = HopfIdeal.augmentation k H := by
  rw [← baseChangeHopfIdeal_centerDefiningIdeal,
    ← baseChangeHopfIdeal_augmentation]
  exact baseChangeHopfIdeal_injective.eq_iff

end TauCeti.CommHopfAlgCat
