/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.LocalRing.Etale
public import TauCeti.FieldTheory.IntermediateField.Adjoin.EqTop
public import TauCeti.NumberTheory.LocalField.Different.Basic
public import TauCeti.NumberTheory.LocalField.FiniteExtension.Basic

/-!
# Base change and composita of unramified extensions of local fields

This file proves that unramifiedness of extensions of nonarchimedean local fields is stable under
base change and under composita. Let `L/K` be unramified, and let `M/F/K` be a tower in which `M`
is generated over `F` by the image of a `K`-embedding `ι : L →ₐ[K] M`. Then `M/F` is unramified.
Combined with transitivity in towers, this shows that the compositum, inside any extension `M` of
`K`, of two unramified extensions of `K` is unramified over `K`. These are the
facts that make the unramified subextensions of an algebraic closure a directed family, whose
union is the maximal unramified extension.

Both results rest on a criterion by generators: if `M = F(b)` for an integral element `b` which
is a root of a polynomial `p` over `𝒪[F]` whose derivative `p'(b)` is a unit, then `M/F` is
unramified. Conversely every unramified extension is of this form: `𝒪[L]` is generated over
`𝒪[K]` by one element at which its minimal polynomial has unit derivative.

## Main results

* `TauCeti.isUnramified_of_isUnit_aeval_derivative`: `M = F(b)` is unramified over `F` when `b`
  is a root of a polynomial over `𝒪[F]` whose derivative at `b` is a unit.
* `TauCeti.isUnramified_iff_exists_isUnit_aeval_derivative_minpoly`: `L/K` is unramified exactly
  when `𝒪[L]` is generated over `𝒪[K]` by an element at which its minimal polynomial has unit
  derivative.
* `TauCeti.IsUnramified.of_adjoin_range_eq_top`: **base change**; if `L/K` is unramified and `M`
  is generated over `F` by the image of `L`, then `M/F` is unramified.
* `TauCeti.IsUnramified.of_fieldRange_sup_fieldRange_eq_top`: **composita**; if `M` is the
  compositum of the images of two unramified extensions of `K`, then `M/K` is unramified.

## References

* [J.-P. Serre, *Corps Locaux*][serre1968], Chapter III, §5.
* J. Neukirch, *Algebraic Number Theory*, Chapter II, §7.
-/

public section

open ValuativeRel IsLocalRing Polynomial

namespace TauCeti

section Criterion

variable {K L : Type*} [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [Field L] [ValuativeRel L] [TopologicalSpace L]
  [IsNonarchimedeanLocalField L] [Algebra K L] [ValuativeExtension K L]

/-- **A simple root of an integral polynomial generates an unramified extension.** If `L = K(b)`
for an element `b` of `𝒪[L]` which is a root of a polynomial `p` over `𝒪[K]` whose derivative
`p'(b)` is a unit of `𝒪[L]`, then `L/K` is unramified. -/
theorem isUnramified_of_isUnit_aeval_derivative {b : 𝒪[L]}
    (hb : IntermediateField.adjoin K {algebraMap 𝒪[L] L b} = ⊤) {p : 𝒪[K][X]}
    (hp : aeval b p = 0) (hu : IsUnit (aeval b (derivative p))) : IsUnramified K L := by
  have := finite_of_valuativeExtension K L
  have hbint : IsIntegral 𝒪[K] b := .of_finite 𝒪[K] b
  -- The derivative of the minimal polynomial of `b` over `𝒪[K]` divides `p'(b)` at `b`.
  have hu' : IsUnit (aeval b (derivative (minpoly 𝒪[K] b))) := by
    obtain ⟨q, rfl⟩ := minpoly.isIntegrallyClosed_dvd hbint hp
    rw [derivative_mul, map_add, map_mul, map_mul, minpoly.aeval, zero_mul, add_zero] at hu
    exact isUnit_of_mul_isUnit_left hu
  -- So `b` is separable over `K`, and hence so is `L = K(b)`.
  have : Algebra.IsSeparable K L := by
    have hsep : IsSeparable K (algebraMap 𝒪[L] L b) := by
      rw [IsSeparable, separable_iff_derivative_ne_zero
        (minpoly.irreducible (Algebra.IsIntegral.isIntegral _))]
      intro h0
      have h1 : aeval (algebraMap 𝒪[L] L b) (derivative (minpoly K (algebraMap 𝒪[L] L b))) = 0 :=
        by rw [h0, map_zero]
      rw [minpoly.isIntegrallyClosed_eq_field_fractions K L hbint, derivative_map,
        aeval_map_algebraMap, aeval_algebraMap_apply] at h1
      exact hu'.ne_zero (FaithfulSMul.algebraMap_injective 𝒪[L] L (by rw [h1, map_zero]))
    rw [← separableClosure.eq_top_iff, eq_top_iff, ← hb, IntermediateField.adjoin_simple_le_iff]
    exact mem_separableClosure_iff.2 hsep
  -- The unit `f'(b)` lies in the different ideal, which is therefore trivial.
  have hK : Algebra.adjoin K {algebraMap 𝒪[L] L b} = ⊤ := by
    rwa [← IntermediateField.adjoin_eq_top_iff_of_isAlgebraic
      (fun y _ ↦ IsAlgebraic.of_finite K y)]
  have hd := conductor_mul_differentIdeal 𝒪[K] K L b hK
  rw [Ideal.span_singleton_eq_top.2 hu'] at hd
  exact (differentIdeal_eq_top_iff K L).1 (eq_top_iff.2 (hd ▸ Ideal.mul_le_right))

/-- **Unramified extensions are generated by simple roots of integral polynomials.** An extension
`L/K` of nonarchimedean local fields is unramified exactly when `𝒪[L]` is generated as an
`𝒪[K]`-algebra by an element `b` at which the derivative of its minimal polynomial over `𝒪[K]` is
a unit. -/
theorem isUnramified_iff_exists_isUnit_aeval_derivative_minpoly :
    IsUnramified K L ↔ ∃ b : 𝒪[L], Algebra.adjoin 𝒪[K] {b} = ⊤ ∧
      IsUnit (aeval b (derivative (minpoly 𝒪[K] b))) := by
  refine ⟨fun h ↦ ?_, fun ⟨b, hb, hu⟩ ↦ isUnramified_of_isUnit_aeval_derivative
    (TauCeti.IntermediateField.adjoin_eq_top_of_algebra_adjoin_eq_top hb) (minpoly.aeval _ _) hu⟩
  have := (isUnramified_iff_etale K L).1 h
  obtain ⟨b, hb⟩ := IsLocalRing.exists_adjoin_eq_top (R := 𝒪[K]) (S := 𝒪[L])
  exact ⟨b, hb, IsLocalRing.isUnit_aeval_derivative_minpoly_of_adjoin_eq_top hb⟩

end Criterion

section BaseChange

variable {K L F M : Type*} [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [Field L] [ValuativeRel L] [TopologicalSpace L]
  [IsNonarchimedeanLocalField L] [Algebra K L] [ValuativeExtension K L]
  [Field F] [ValuativeRel F] [TopologicalSpace F] [IsNonarchimedeanLocalField F]
  [Algebra K F] [ValuativeExtension K F]
  [Field M] [ValuativeRel M] [TopologicalSpace M] [IsNonarchimedeanLocalField M]
  [Algebra F M] [ValuativeExtension F M] [Algebra K M] [IsScalarTower K F M]

/-- **Base change of an unramified extension.** Let `L/K` be an unramified extension and `M/F/K`
a tower of nonarchimedean local fields. If `M` is generated over `F` by the image of a
`K`-embedding `ι : L →ₐ[K] M`, then `M/F` is unramified. -/
theorem IsUnramified.of_adjoin_range_eq_top [IsUnramified K L] (ι : L →ₐ[K] M)
    (h : IntermediateField.adjoin F (Set.range ι) = ⊤) : IsUnramified F M := by
  have : ValuativeExtension K M := ValuativeExtension.trans K F M
  have := finite_of_valuativeExtension K L
  have := finite_of_valuativeExtension K M
  -- A generator `a` of `𝒪[L]` over `𝒪[K]` at which `g = minpoly 𝒪[K] a` has unit derivative.
  obtain ⟨a, ha, hu⟩ := (isUnramified_iff_exists_isUnit_aeval_derivative_minpoly (K := K)).1 ‹_›
  obtain ⟨c, hc⟩ := hu.exists_right_inv
  let b : 𝒪[M] := ι.integerRingHom a
  -- Evaluating a polynomial over `𝒪[K]` at `b` is applying `ι` to its evaluation at `a`.
  have heval (r : 𝒪[K][X]) :
      aeval b (r.map (algebraMap 𝒪[K] 𝒪[F])) = ι.integerRingHom (aeval a r) := by
    refine (map_aeval_eq_aeval_map (ψ := ι.integerRingHom.toRingHom) ?_ r a).symm
    ext x
    simp [IsScalarTower.algebraMap_apply K F M]
  refine isUnramified_of_isUnit_aeval_derivative (b := b)
    (p := (minpoly 𝒪[K] a).map (algebraMap 𝒪[K] 𝒪[F])) ?_ ?_ ?_
  · -- `M = F(b)`, because `L = K(a)`.
    have hKa : IntermediateField.adjoin K {algebraMap 𝒪[L] L a} = ⊤ :=
      TauCeti.IntermediateField.adjoin_eq_top_of_algebra_adjoin_eq_top ha
    rw [← h, ← AlgHom.coe_fieldRange, AlgHom.fieldRange_eq_map, ← hKa,
      IntermediateField.adjoin_map, Set.image_singleton, IntermediateField.adjoin_adjoin_right]
    -- `algebraMap 𝒪[L] L` is the subring inclusion, and `b` is the image of `a`.
    rw [Algebra.algebraMap_ofSubsemiring_apply, Algebra.algebraMap_ofSubsemiring_apply,
      AlgHom.coe_integerRingHom_apply]
  · rw [heval, minpoly.aeval, map_zero]
  · -- `g'(b)` is a unit of `𝒪[M]`, with inverse the image of `c`.
    refine IsUnit.of_mul_eq_one (ι.integerRingHom c) ?_
    rw [derivative_map, heval, ← map_mul, hc, map_one]

end BaseChange

section Compositum

variable {K L₁ L₂ M : Type*} [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]
  [Field L₁] [ValuativeRel L₁] [TopologicalSpace L₁] [IsNonarchimedeanLocalField L₁]
  [Algebra K L₁] [ValuativeExtension K L₁]
  [Field L₂] [ValuativeRel L₂] [TopologicalSpace L₂] [IsNonarchimedeanLocalField L₂]
  [Algebra K L₂] [ValuativeExtension K L₂]
  [Field M] [ValuativeRel M] [TopologicalSpace M] [IsNonarchimedeanLocalField M]
  [Algebra K M] [ValuativeExtension K M]

/-- **The compositum of unramified extensions is unramified.** If a finite extension `M` of a
nonarchimedean local field `K` is the compositum of the images of two `K`-embeddings of unramified
extensions `L₁/K` and `L₂/K`, then `M/K` is unramified. -/
theorem IsUnramified.of_fieldRange_sup_fieldRange_eq_top [IsUnramified K L₁] [IsUnramified K L₂]
    (ι₁ : L₁ →ₐ[K] M) (ι₂ : L₂ →ₐ[K] M) (h : ι₁.fieldRange ⊔ ι₂.fieldRange = ⊤) :
    IsUnramified K M := by
  have := finite_of_valuativeExtension K L₂
  -- View `M` as an extension of `L₂` through `ι₂`.
  let _ := ι₂.toAlgebra
  have : IsScalarTower K L₂ M := .of_algebraMap_eq fun x ↦ (ι₂.commutes x).symm
  have : ValuativeExtension L₂ M := ι₂.valuativeExtension
  -- `L₂(ι₁ L₁)` contains both images, hence their compositum `M`.
  have hle : ι₁.fieldRange ⊔ ι₂.fieldRange ≤
      (IntermediateField.adjoin L₂ (Set.range ι₁)).restrictScalars K :=
    sup_le (fun y hy ↦ IntermediateField.subset_adjoin L₂ _ hy)
      (by rintro _ ⟨z, rfl⟩; exact IntermediateField.algebraMap_mem _ z)
  -- So `M/L₂` is unramified by base change, and `M/K` by transitivity.
  have := IsUnramified.of_adjoin_range_eq_top (F := L₂) ι₁
    (eq_top_iff.2 fun x _ ↦ hle (h ▸ IntermediateField.mem_top))
  exact IsUnramified.trans K L₂ M

end Compositum

end TauCeti
