/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Group.Subgroup.Finite
public import TauCeti.GroupTheory.SpecificGroups.CFSG.BasicProperties.Mathieu.M12LowerBound
public import TauCeti.GroupTheory.Subgroup.GeneratorCover
import all TauCeti.GroupTheory.SpecificGroups.CFSG.BasicProperties.Mathieu.Permutation

/-!
# The order of the M12 permutation image

A five-level Schreier cover bounds the subgroup generated by the checked degree-12
permutations. The representative counts are `12, 11, 10, 9, 8`; the terminal subgroup
is trivial. Each permutation is specified by its twelve point images and a checked
inverse. Two generators at each level require only 200 signed transitions. Each
Schreier residue is checked against a word in the next level's generators.

The finite-cover argument bounds the image by `95040`, and `M12LowerBound` supplies
the matching lower bound. No finiteness or order claim about the presented group follows
from the finite image. All table entries are checked by kernel reduction; neither the
point-orbit calculation nor its interpretation as a stabilizer chain is assumed.
-/

public section

namespace TauCeti.Sporadic.Mathieu

/-- Permutations from point-image tables with explicitly checked two-sided inverses. -/
private def tablePerms {n : ℕ} (p q : Vector (Vector (Fin 12) 12) n)
    (h : ∀ (i : Fin n) (x : Fin 12), p[i][q[i][x]] = x ∧ q[i][p[i][x]] = x)
    (i : Fin n) : Equiv.Perm (Fin 12) where
  toFun x := p[i][x]
  invFun x := q[i][x]
  left_inv x := (h i x).2
  right_inv x := (h i x).1

/-- The first half of the alphabet consists of generators, and the second of their inverses. -/
private def signedGenerator {n : ℕ} (s : Fin n → Equiv.Perm (Fin 12))
    (i : Fin (n + n)) : Equiv.Perm (Fin 12) :=
  if h : i.val < n then s ⟨i.val, h⟩ else (s ⟨i.val - n, by omega⟩)⁻¹

private theorem signedGenerator_castAdd {n : ℕ} (s : Fin n → Equiv.Perm (Fin 12))
    (i : Fin n) : signedGenerator s (Fin.castAdd n i) = s i := by
  simp [signedGenerator, i.isLt]

private theorem signedGenerator_natAdd {n : ℕ} (s : Fin n → Equiv.Perm (Fin 12))
    (i : Fin n) : signedGenerator s (Fin.natAdd n i) = (s i)⁻¹ := by
  simp [signedGenerator]

/-- Evaluate a signed word as a product, with permutation composition acting right to left. -/
private def evalWord {n : ℕ} (s : Fin n → Equiv.Perm (Fin 12))
    (w : List (Fin (n + n))) : Equiv.Perm (Fin 12) :=
  (w.map (signedGenerator s)).prod

private theorem evalWord_mem {n : ℕ} (s : Fin n → Equiv.Perm (Fin 12))
    (w : List (Fin (n + n))) : evalWord s w ∈ Subgroup.closure (Set.range s) := by
  apply Subgroup.list_prod_mem
  intro g hg
  obtain ⟨i, _, rfl⟩ := List.mem_map.mp hg
  unfold signedGenerator
  split
  · exact Subgroup.subset_closure ⟨_, rfl⟩
  · exact Subgroup.inv_mem _ (Subgroup.subset_closure ⟨_, rfl⟩)

/-- Point images of the level-0 generators. -/
private def generatorImages0 : Vector (Vector (Fin 12) 12) 2 :=
  #v[
    #v[4, 0, 1, 6, 7, 10, 5, 2, 3, 9, 8, 11],
    #v[5, 6, 4, 3, 11, 8, 1, 10, 0, 7, 2, 9]]

/-- Point images of the inverses of the level-0 generators. -/
private def generatorInverseImages0 : Vector (Vector (Fin 12) 12) 2 :=
  #v[
    #v[1, 2, 7, 8, 0, 6, 3, 4, 10, 9, 5, 11],
    #v[8, 6, 10, 3, 2, 0, 1, 9, 5, 11, 7, 4]]

/-- The level-0 generators with checked two-sided inverses. -/
private def generators0 : Fin 2 → Equiv.Perm (Fin 12) :=
  tablePerms generatorImages0 generatorInverseImages0 (by decide +kernel)

/-- The 12 representatives in the level-0 cover. -/
private def transversalImages0 : Vector (Vector (Fin 12) 12) 12 :=
  #v[
    #v[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    #v[1, 2, 7, 8, 0, 6, 3, 4, 10, 9, 5, 11],
    #v[2, 7, 4, 10, 1, 3, 8, 0, 5, 9, 6, 11],
    #v[3, 5, 8, 6, 1, 4, 0, 9, 10, 11, 2, 7],
    #v[4, 0, 1, 6, 7, 10, 5, 2, 3, 9, 8, 11],
    #v[5, 6, 4, 3, 11, 8, 1, 10, 0, 7, 2, 9],
    #v[6, 4, 10, 0, 5, 1, 3, 11, 2, 7, 8, 9],
    #v[7, 4, 0, 5, 2, 8, 10, 1, 6, 9, 3, 11],
    #v[8, 6, 10, 3, 2, 0, 1, 9, 5, 11, 7, 4],
    #v[9, 8, 1, 6, 2, 4, 0, 11, 3, 10, 5, 7],
    #v[10, 5, 7, 6, 11, 3, 0, 8, 4, 2, 1, 9],
    #v[11, 5, 6, 1, 10, 2, 8, 4, 3, 7, 0, 9]]

/-- Point images of the inverses of the level-0 representatives. -/
private def transversalInverseImages0 : Vector (Vector (Fin 12) 12) 12 :=
  #v[
    #v[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    #v[4, 0, 1, 6, 7, 10, 5, 2, 3, 9, 8, 11],
    #v[7, 4, 0, 5, 2, 8, 10, 1, 6, 9, 3, 11],
    #v[6, 4, 10, 0, 5, 1, 3, 11, 2, 7, 8, 9],
    #v[1, 2, 7, 8, 0, 6, 3, 4, 10, 9, 5, 11],
    #v[8, 6, 10, 3, 2, 0, 1, 9, 5, 11, 7, 4],
    #v[3, 5, 8, 6, 1, 4, 0, 9, 10, 11, 2, 7],
    #v[2, 7, 4, 10, 1, 3, 8, 0, 5, 9, 6, 11],
    #v[5, 6, 4, 3, 11, 8, 1, 10, 0, 7, 2, 9],
    #v[6, 2, 4, 8, 5, 10, 3, 11, 1, 0, 9, 7],
    #v[6, 10, 9, 5, 8, 1, 3, 2, 7, 11, 0, 4],
    #v[10, 3, 5, 8, 7, 1, 2, 9, 6, 11, 4, 0]]

/-- The level-0 representatives with checked two-sided inverses. -/
private def transversal0 : Fin 12 → Equiv.Perm (Fin 12) :=
  tablePerms transversalImages0 transversalInverseImages0
    (by decide +kernel)

private theorem transversal0_zero : transversal0 0 = 1 := by
  decide +kernel

/-- Representative indices after each signed generator step at level 0. -/
private def targetIndices0 : Vector (Vector (Fin 12) 12) 4 :=
  #v[
    #v[4, 0, 1, 6, 7, 10, 5, 2, 3, 9, 8, 11],
    #v[5, 6, 4, 3, 11, 8, 1, 10, 0, 7, 2, 9],
    #v[1, 2, 7, 8, 0, 6, 3, 4, 10, 9, 5, 11],
    #v[8, 6, 10, 3, 2, 0, 1, 9, 5, 11, 7, 4]]

/-- Signed words in level-1 generators for the level-0 residues. -/
private def residueWords0 :
    Vector (Vector (List (Fin 4)) 12) 4 :=
  #v[
    #v[
      [],
      [],
      [],
      [3, 3, 3, 3, 0, 1, 0, 1, 1, 1, 1, 1, 1, 2, 3, 3, 3, 0, 3, 3, 3, 2, 1, 2, 1, 1, 2, 3, 2, 3],
      [],
      [],
      [1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 3, 3, 0, 1, 0, 3, 3, 3, 3, 3, 2, 1, 1, 1],
      [],
      [],
      [3, 3, 0, 3, 3, 3, 2, 1, 1, 0, 1, 0, 3, 3, 3, 2, 1, 2, 1, 1, 2, 3, 2, 3],
      [3, 3, 3, 3, 3, 2, 1, 2, 1, 2, 3, 2, 3, 3, 3, 3, 2, 1, 1, 1, 1, 1, 2, 3, 2, 3],
      [2, 1, 2, 3, 2, 3, 2, 1, 1, 2, 3, 2, 3, 0, 3, 3, 3, 2, 1, 2, 1, 1, 2, 3, 2, 3]],
    #v[
      [],
      [],
      [3],
      [3, 3, 3, 3, 0, 1, 0, 1, 1, 1, 1, 1, 1, 2, 3, 3, 3, 0, 3, 3, 3, 2, 1, 2, 1, 1, 2, 3, 2, 3],
      [],
      [2],
      [2, 3, 3, 3, 3, 3, 3, 3, 2, 1, 2, 3, 2, 3, 3, 3, 3, 2, 1, 2, 1, 2, 3],
      [2, 1, 2, 3, 2, 3, 3, 3, 3, 2, 1, 2, 1, 1, 2, 3, 2, 3],
      [],
      [3, 3, 3, 2, 3, 3, 2, 3, 3, 3, 3, 2, 1, 2, 1, 1, 0, 3, 2, 1, 1, 0, 3, 3, 3, 3, 3],
      [3, 3, 2, 1, 1, 1, 0, 3, 0, 1, 1, 1, 2, 3, 2, 3, 2, 1, 0, 3, 0, 3, 0, 1, 1, 1, 1, 0, 1],
      []],
    #v[
      [],
      [],
      [],
      [],
      [],
      [3, 3, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 3, 3, 3, 0, 3, 3, 3, 2, 1, 2, 1, 1, 2, 3, 2, 3],
      [2, 3, 2, 3, 2, 3, 2, 1, 1, 2, 3, 3, 3, 2, 1, 0, 3, 0, 3, 0, 1, 1, 1, 1, 0, 1],
      [],
      [3, 3, 2, 3, 2, 1, 0, 1, 0, 3, 3, 0, 3, 0, 1, 1, 1, 2],
      [1, 2, 1, 2, 3, 2, 1, 1, 1, 1, 1, 2, 3, 3, 0, 1, 0, 3, 3, 3, 3, 3, 2, 1, 1, 1],
      [],
      [3, 3, 3, 2, 3, 3, 2, 3, 3, 3, 0, 3, 2, 3, 3, 2, 1, 2, 1, 2, 3]],
    #v[
      [],
      [3, 3, 3, 3, 0, 1, 1, 1, 0, 3, 3, 0, 3, 0, 1, 1, 1, 2],
      [2, 3, 3, 3, 0, 1, 1, 2, 3, 3, 2, 3, 3, 3, 3, 2, 1, 2, 1, 2, 3],
      [2, 3, 2, 3, 2, 3, 2, 1, 1, 2, 3, 3, 3, 2, 1, 0, 3, 0, 3, 0, 1, 1, 1, 1, 0, 1],
      [1],
      [],
      [],
      [2, 1, 2, 3, 2, 1, 2, 3, 3, 2, 3, 3, 3, 2, 1, 1, 1, 1, 1, 2, 3, 2, 3],
      [2],
      [],
      [3, 3, 3, 2, 3, 0, 1, 0, 3, 0, 1, 1, 1, 2, 3, 2, 3, 3, 3, 3, 2, 1, 2, 1, 1, 2, 3, 2, 3],
      []]]

/-- Point images of the level-1 generators. -/
private def generatorImages1 : Vector (Vector (Fin 12) 12) 2 :=
  #v[
    #v[0, 6, 9, 3, 7, 5, 1, 4, 8, 2, 11, 10],
    #v[0, 6, 10, 4, 9, 1, 7, 3, 5, 11, 8, 2]]

/-- Point images of the inverses of the level-1 generators. -/
private def generatorInverseImages1 : Vector (Vector (Fin 12) 12) 2 :=
  #v[
    #v[0, 6, 9, 3, 7, 5, 1, 4, 8, 2, 11, 10],
    #v[0, 5, 11, 7, 3, 8, 1, 6, 10, 4, 2, 9]]

/-- The level-1 generators with checked two-sided inverses. -/
private def generators1 : Fin 2 → Equiv.Perm (Fin 12) :=
  tablePerms generatorImages1 generatorInverseImages1 (by decide +kernel)

/-- The 11 representatives in the level-1 cover. -/
private def transversalImages1 : Vector (Vector (Fin 12) 12) 11 :=
  #v[
    #v[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    #v[0, 2, 11, 4, 10, 5, 6, 8, 9, 7, 3, 1],
    #v[0, 3, 11, 7, 9, 2, 8, 5, 1, 4, 10, 6],
    #v[0, 4, 1, 10, 6, 3, 8, 9, 2, 5, 7, 11],
    #v[0, 5, 11, 7, 3, 8, 1, 6, 10, 4, 2, 9],
    #v[0, 6, 9, 3, 7, 5, 1, 4, 8, 2, 11, 10],
    #v[0, 7, 11, 4, 3, 1, 6, 9, 5, 10, 2, 8],
    #v[0, 8, 1, 10, 4, 2, 6, 7, 5, 3, 11, 9],
    #v[0, 9, 5, 2, 7, 8, 1, 4, 6, 10, 3, 11],
    #v[0, 10, 6, 11, 3, 5, 1, 2, 4, 8, 7, 9],
    #v[0, 11, 1, 10, 3, 5, 6, 9, 7, 8, 4, 2]]

/-- Point images of the inverses of the level-1 representatives. -/
private def transversalInverseImages1 : Vector (Vector (Fin 12) 12) 11 :=
  #v[
    #v[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    #v[0, 11, 1, 10, 3, 5, 6, 9, 7, 8, 4, 2],
    #v[0, 8, 5, 1, 9, 7, 11, 3, 6, 4, 10, 2],
    #v[0, 2, 8, 5, 1, 9, 4, 10, 6, 7, 3, 11],
    #v[0, 6, 10, 4, 9, 1, 7, 3, 5, 11, 8, 2],
    #v[0, 6, 9, 3, 7, 5, 1, 4, 8, 2, 11, 10],
    #v[0, 5, 10, 4, 3, 8, 6, 1, 11, 7, 9, 2],
    #v[0, 2, 5, 9, 4, 8, 6, 7, 1, 11, 3, 10],
    #v[0, 6, 3, 10, 7, 2, 8, 4, 5, 1, 9, 11],
    #v[0, 6, 7, 4, 8, 5, 2, 10, 9, 11, 1, 3],
    #v[0, 2, 11, 4, 10, 5, 6, 8, 9, 7, 3, 1]]

/-- The level-1 representatives with checked two-sided inverses. -/
private def transversal1 : Fin 11 → Equiv.Perm (Fin 12) :=
  tablePerms transversalImages1 transversalInverseImages1
    (by decide +kernel)

private theorem transversal1_zero : transversal1 0 = 1 := by
  decide +kernel

/-- Representative indices after each signed generator step at level 1. -/
private def targetIndices1 : Vector (Vector (Fin 11) 11) 4 :=
  #v[
    #v[5, 8, 2, 6, 4, 0, 3, 7, 1, 10, 9],
    #v[5, 9, 3, 8, 0, 6, 2, 4, 10, 7, 1],
    #v[5, 8, 2, 6, 4, 0, 3, 7, 1, 10, 9],
    #v[4, 10, 6, 2, 7, 0, 5, 9, 3, 1, 8]]

/-- Signed words in level-2 generators for the level-1 residues. -/
private def residueWords1 :
    Vector (Vector (List (Fin 4)) 11) 4 :=
  #v[
    #v[
      [],
      [3, 3, 2, 3, 0, 1, 1, 0, 3, 2, 2, 3, 2, 3],
      [2, 3, 3, 3, 3, 2],
      [3, 3, 2, 2, 3, 3, 2, 3, 2],
      [2, 3, 2, 2, 3, 2],
      [],
      [0, 1, 2],
      [3, 2, 3, 2, 3, 0, 3, 2, 1, 2, 1, 0],
      [3, 3, 3, 0, 1, 0, 3, 2, 1, 2, 1, 0],
      [],
      []],
    #v[
      [2, 2, 2, 3, 2, 3, 0, 1, 2, 1, 2, 3, 3],
      [2, 3, 2, 2, 3, 3, 2, 3, 2],
      [2, 3, 2, 2, 2, 3, 2, 3, 0, 3, 2, 1, 2, 1, 0],
      [2, 3, 2, 2, 2, 3, 3, 2, 2, 3, 2, 3],
      [],
      [],
      [3, 3, 3, 3, 2, 2, 3],
      [2, 2, 3, 2, 3, 2, 3, 0, 3, 0, 1, 2],
      [],
      [2, 2, 3, 3, 2, 2, 3, 2, 3],
      [3]],
    #v[
      [],
      [3, 3, 2, 3, 0, 1, 1, 0, 3, 2, 2, 3, 2, 3],
      [2, 3, 3, 3, 3, 2],
      [3, 3, 2, 2, 3, 3, 2, 3, 2],
      [2, 3, 2, 2, 3, 2],
      [],
      [0, 1, 2],
      [3, 2, 3, 2, 3, 0, 3, 2, 1, 2, 1, 0],
      [3, 3, 3, 0, 1, 0, 3, 2, 1, 2, 1, 0],
      [],
      []],
    #v[
      [],
      [1],
      [2, 2, 3],
      [2, 2, 3, 2, 3, 2, 3, 3, 2, 3, 2],
      [2, 2, 3, 2, 1, 0, 3, 2, 2, 3, 2, 3],
      [3, 2, 2, 2, 3, 3, 2, 3, 2],
      [],
      [3, 3, 3, 3, 2, 2, 3, 2, 3],
      [3, 2, 3, 0, 1, 2, 3, 0, 3, 0, 1, 2],
      [2, 1, 1, 1, 0, 3, 0],
      []]]

/-- Point images of the level-2 generators. -/
private def generatorImages2 : Vector (Vector (Fin 12) 12) 2 :=
  #v[
    #v[0, 1, 6, 3, 10, 8, 11, 2, 4, 9, 5, 7],
    #v[0, 1, 7, 4, 11, 9, 2, 3, 10, 6, 8, 5]]

/-- Point images of the inverses of the level-2 generators. -/
private def generatorInverseImages2 : Vector (Vector (Fin 12) 12) 2 :=
  #v[
    #v[0, 1, 7, 3, 8, 10, 2, 11, 5, 9, 4, 6],
    #v[0, 1, 6, 7, 3, 11, 9, 2, 10, 5, 8, 4]]

/-- The level-2 generators with checked two-sided inverses. -/
private def generators2 : Fin 2 → Equiv.Perm (Fin 12) :=
  tablePerms generatorImages2 generatorInverseImages2 (by decide +kernel)

/-- The 10 representatives in the level-2 cover. -/
private def transversalImages2 : Vector (Vector (Fin 12) 12) 10 :=
  #v[
    #v[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    #v[0, 1, 3, 11, 4, 9, 8, 7, 5, 6, 2, 10],
    #v[0, 1, 4, 7, 6, 8, 5, 3, 10, 11, 9, 2],
    #v[0, 1, 5, 10, 9, 2, 6, 8, 7, 4, 3, 11],
    #v[0, 1, 6, 3, 10, 8, 11, 2, 4, 9, 5, 7],
    #v[0, 1, 7, 3, 8, 10, 2, 11, 5, 9, 4, 6],
    #v[0, 1, 8, 9, 11, 4, 5, 10, 3, 6, 7, 2],
    #v[0, 1, 9, 4, 11, 2, 6, 5, 3, 7, 10, 8],
    #v[0, 1, 10, 2, 4, 8, 9, 7, 6, 5, 11, 3],
    #v[0, 1, 11, 7, 2, 6, 4, 3, 5, 10, 8, 9]]

/-- Point images of the inverses of the level-2 representatives. -/
private def transversalInverseImages2 : Vector (Vector (Fin 12) 12) 10 :=
  #v[
    #v[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    #v[0, 1, 10, 2, 4, 8, 9, 7, 6, 5, 11, 3],
    #v[0, 1, 11, 7, 2, 6, 4, 3, 5, 10, 8, 9],
    #v[0, 1, 5, 10, 9, 2, 6, 8, 7, 4, 3, 11],
    #v[0, 1, 7, 3, 8, 10, 2, 11, 5, 9, 4, 6],
    #v[0, 1, 6, 3, 10, 8, 11, 2, 4, 9, 5, 7],
    #v[0, 1, 11, 8, 5, 6, 9, 10, 2, 3, 7, 4],
    #v[0, 1, 5, 8, 3, 7, 6, 9, 11, 2, 10, 4],
    #v[0, 1, 3, 11, 4, 9, 8, 7, 5, 6, 2, 10],
    #v[0, 1, 4, 7, 6, 8, 5, 3, 10, 11, 9, 2]]

/-- The level-2 representatives with checked two-sided inverses. -/
private def transversal2 : Fin 10 → Equiv.Perm (Fin 12) :=
  tablePerms transversalImages2 transversalInverseImages2
    (by decide +kernel)

private theorem transversal2_zero : transversal2 0 = 1 := by
  decide +kernel

/-- Representative indices after each signed generator step at level 2. -/
private def targetIndices2 : Vector (Vector (Fin 10) 10) 4 :=
  #v[
    #v[4, 1, 8, 6, 9, 0, 2, 7, 3, 5],
    #v[5, 2, 9, 7, 0, 1, 8, 4, 6, 3],
    #v[5, 1, 6, 8, 0, 9, 3, 7, 2, 4],
    #v[4, 5, 1, 9, 7, 0, 8, 3, 6, 2]]

/-- Signed words in level-3 generators for the level-2 residues. -/
private def residueWords2 :
    Vector (Vector (List (Fin 4)) 10) 4 :=
  #v[
    #v[
      [],
      [3, 2, 2, 2, 1],
      [3, 3, 2],
      [2, 3, 3, 3, 2, 2, 2, 1],
      [1, 0, 3, 3],
      [],
      [3, 3, 3, 2, 3, 2, 2],
      [3, 0, 3, 3],
      [2, 3, 3, 3, 2, 2, 2, 1],
      [2, 3, 2, 1, 0, 3]],
    #v[
      [3],
      [2, 3, 3, 2, 2],
      [3, 2, 3, 2, 2],
      [3, 3, 2, 1],
      [2, 3, 3, 2, 2, 2, 1],
      [2, 2, 1, 0, 3],
      [1, 0, 3, 2, 2],
      [2, 3, 0, 3, 3],
      [3, 3, 3, 2],
      [3, 2, 2, 1]],
    #v[
      [],
      [3, 2, 1],
      [2, 2, 1, 0, 3],
      [2, 3, 3, 2],
      [],
      [1, 0, 3, 3],
      [2, 3, 3, 2],
      [3, 3, 2, 1],
      [0, 3, 3],
      [2, 3, 2, 1, 0, 3]],
    #v[
      [3, 3, 0, 3, 3, 2, 3, 2, 2],
      [3, 3, 3, 2, 3, 2, 2],
      [3, 3, 3, 2, 2, 2, 1],
      [3, 2, 2, 1],
      [3, 0, 3, 3, 2],
      [1],
      [0, 3],
      [3, 0, 3, 3],
      [3, 0, 3, 2, 2],
      [3, 3, 0]]]

/-- Point images of the level-3 generators. -/
private def generatorImages3 : Vector (Vector (Fin 12) 12) 2 :=
  #v[
    #v[0, 1, 2, 5, 3, 7, 10, 4, 8, 11, 9, 6],
    #v[0, 1, 2, 7, 10, 8, 6, 4, 11, 5, 3, 9]]

/-- Point images of the inverses of the level-3 generators. -/
private def generatorInverseImages3 : Vector (Vector (Fin 12) 12) 2 :=
  #v[
    #v[0, 1, 2, 4, 7, 3, 11, 5, 8, 10, 6, 9],
    #v[0, 1, 2, 10, 7, 9, 6, 3, 5, 11, 4, 8]]

/-- The level-3 generators with checked two-sided inverses. -/
private def generators3 : Fin 2 → Equiv.Perm (Fin 12) :=
  tablePerms generatorImages3 generatorInverseImages3 (by decide +kernel)

/-- The 9 representatives in the level-3 cover. -/
private def transversalImages3 : Vector (Vector (Fin 12) 12) 9 :=
  #v[
    #v[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    #v[0, 1, 2, 4, 7, 3, 11, 5, 8, 10, 6, 9],
    #v[0, 1, 2, 5, 3, 7, 10, 4, 8, 11, 9, 6],
    #v[0, 1, 2, 6, 11, 7, 5, 3, 4, 8, 10, 9],
    #v[0, 1, 2, 7, 10, 8, 6, 4, 11, 5, 3, 9],
    #v[0, 1, 2, 8, 5, 7, 4, 6, 9, 10, 3, 11],
    #v[0, 1, 2, 9, 6, 5, 8, 3, 11, 10, 7, 4],
    #v[0, 1, 2, 10, 7, 9, 6, 3, 5, 11, 4, 8],
    #v[0, 1, 2, 11, 4, 10, 7, 3, 9, 5, 8, 6]]

/-- Point images of the inverses of the level-3 representatives. -/
private def transversalInverseImages3 : Vector (Vector (Fin 12) 12) 9 :=
  #v[
    #v[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    #v[0, 1, 2, 5, 3, 7, 10, 4, 8, 11, 9, 6],
    #v[0, 1, 2, 4, 7, 3, 11, 5, 8, 10, 6, 9],
    #v[0, 1, 2, 7, 8, 6, 3, 5, 9, 11, 10, 4],
    #v[0, 1, 2, 10, 7, 9, 6, 3, 5, 11, 4, 8],
    #v[0, 1, 2, 10, 6, 4, 7, 5, 3, 8, 9, 11],
    #v[0, 1, 2, 7, 11, 5, 4, 10, 6, 3, 9, 8],
    #v[0, 1, 2, 7, 10, 8, 6, 4, 11, 5, 3, 9],
    #v[0, 1, 2, 7, 4, 9, 11, 6, 10, 8, 5, 3]]

/-- The level-3 representatives with checked two-sided inverses. -/
private def transversal3 : Fin 9 → Equiv.Perm (Fin 12) :=
  tablePerms transversalImages3 transversalInverseImages3
    (by decide +kernel)

private theorem transversal3_zero : transversal3 0 = 1 := by
  decide +kernel

/-- Representative indices after each signed generator step at level 3. -/
private def targetIndices3 : Vector (Vector (Fin 9) 9) 4 :=
  #v[
    #v[2, 0, 4, 7, 1, 5, 8, 6, 3],
    #v[4, 7, 5, 3, 1, 8, 2, 0, 6],
    #v[1, 4, 0, 8, 2, 5, 7, 3, 6],
    #v[7, 4, 6, 3, 0, 2, 8, 1, 5]]

/-- Signed words in level-4 generators for the level-3 residues. -/
private def residueWords3 :
    Vector (Vector (List (Fin 4)) 9) 4 :=
  #v[
    #v[
      [],
      [],
      [3, 2],
      [3, 3],
      [3, 0],
      [2],
      [2],
      [3, 0],
      [1]],
    #v[
      [],
      [0],
      [2],
      [3, 0],
      [2],
      [0],
      [3, 0],
      [],
      [3, 2]],
    #v[
      [],
      [3, 2],
      [],
      [3],
      [3, 0],
      [0],
      [3, 2],
      [3, 3],
      [0]],
    #v[
      [],
      [0],
      [3, 2],
      [3, 2],
      [],
      [0],
      [3, 0],
      [2],
      [2]]]

/-- Point images of the level-4 generators. -/
private def generatorImages4 : Vector (Vector (Fin 12) 12) 2 :=
  #v[
    #v[0, 1, 2, 3, 10, 4, 5, 11, 9, 7, 6, 8],
    #v[0, 1, 2, 3, 7, 11, 8, 6, 4, 5, 9, 10]]

/-- Point images of the inverses of the level-4 generators. -/
private def generatorInverseImages4 : Vector (Vector (Fin 12) 12) 2 :=
  #v[
    #v[0, 1, 2, 3, 5, 6, 10, 9, 11, 8, 4, 7],
    #v[0, 1, 2, 3, 8, 9, 7, 4, 6, 10, 11, 5]]

/-- The level-4 generators with checked two-sided inverses. -/
private def generators4 : Fin 2 → Equiv.Perm (Fin 12) :=
  tablePerms generatorImages4 generatorInverseImages4 (by decide +kernel)

/-- The 8 representatives in the level-4 cover. -/
private def transversalImages4 : Vector (Vector (Fin 12) 12) 8 :=
  #v[
    #v[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    #v[0, 1, 2, 3, 5, 6, 10, 9, 11, 8, 4, 7],
    #v[0, 1, 2, 3, 6, 10, 4, 8, 7, 11, 5, 9],
    #v[0, 1, 2, 3, 7, 11, 8, 6, 4, 5, 9, 10],
    #v[0, 1, 2, 3, 8, 9, 7, 4, 6, 10, 11, 5],
    #v[0, 1, 2, 3, 9, 7, 11, 10, 5, 6, 8, 4],
    #v[0, 1, 2, 3, 10, 4, 5, 11, 9, 7, 6, 8],
    #v[0, 1, 2, 3, 11, 8, 9, 5, 10, 4, 7, 6]]

/-- Point images of the inverses of the level-4 representatives. -/
private def transversalInverseImages4 : Vector (Vector (Fin 12) 12) 8 :=
  #v[
    #v[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    #v[0, 1, 2, 3, 10, 4, 5, 11, 9, 7, 6, 8],
    #v[0, 1, 2, 3, 6, 10, 4, 8, 7, 11, 5, 9],
    #v[0, 1, 2, 3, 8, 9, 7, 4, 6, 10, 11, 5],
    #v[0, 1, 2, 3, 7, 11, 8, 6, 4, 5, 9, 10],
    #v[0, 1, 2, 3, 11, 8, 9, 5, 10, 4, 7, 6],
    #v[0, 1, 2, 3, 5, 6, 10, 9, 11, 8, 4, 7],
    #v[0, 1, 2, 3, 9, 7, 11, 10, 5, 6, 8, 4]]

/-- The level-4 representatives with checked two-sided inverses. -/
private def transversal4 : Fin 8 → Equiv.Perm (Fin 12) :=
  tablePerms transversalImages4 transversalInverseImages4
    (by decide +kernel)

private theorem transversal4_zero : transversal4 0 = 1 := by
  decide +kernel

/-- Representative indices after each signed generator step at level 4. -/
private def targetIndices4 : Vector (Vector (Fin 8) 8) 4 :=
  #v[
    #v[6, 0, 1, 7, 5, 3, 2, 4],
    #v[3, 7, 4, 2, 0, 1, 5, 6],
    #v[1, 2, 6, 5, 7, 4, 0, 3],
    #v[4, 5, 3, 0, 2, 6, 7, 1]]

/-- Signed words in level-5 generators for the level-4 residues. -/
private def residueWords4 :
    Vector (Vector (List (Fin 0)) 8) 4 :=
  #v[
    #v[
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      []],
    #v[
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      []],
    #v[
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      []],
    #v[
      [],
      [],
      [],
      [],
      [],
      [],
      [],
      []]]

/-- There are no generators after the fifth cover. -/
private def generators5 : Fin 0 → Equiv.Perm (Fin 12) := Fin.elim0

private theorem step0 (a : Fin 4) (i : Fin 12) :
    ∃ j, (transversal0 j)⁻¹ * signedGenerator generators0 a *
      transversal0 i ∈ Subgroup.closure (Set.range generators1) := by
  have h : ∀ (a : Fin 4) (i : Fin 12) (x : Fin 12),
      signedGenerator generators0 a (transversal0 i x) =
        transversal0 targetIndices0[a][i]
          (evalWord generators1 residueWords0[a][i] x) := by
    decide +kernel
  have heq : signedGenerator generators0 a * transversal0 i =
      transversal0 targetIndices0[a][i] *
        evalWord generators1 residueWords0[a][i] := Equiv.ext (h a i)
  refine ⟨targetIndices0[a][i], ?_⟩
  rw [mul_assoc, heq, inv_mul_cancel_left]
  exact evalWord_mem _ _

private theorem bound0 : Nat.card (Subgroup.closure (Set.range generators0)) ≤
    12 * Nat.card (Subgroup.closure (Set.range generators1)) := by
  have h := Subgroup.natCard_closure_le_mul generators0 transversal0
    (Subgroup.closure (Set.range generators1))
    ⟨0, transversal0_zero⟩ ?_ ?_
  · simpa only [Nat.card_fin] using h
  · intro a i
    simpa only [signedGenerator_castAdd] using step0 (Fin.castAdd 2 a) i
  · intro a i
    simpa only [signedGenerator_natAdd] using step0 (Fin.natAdd 2 a) i

private theorem step1 (a : Fin 4) (i : Fin 11) :
    ∃ j, (transversal1 j)⁻¹ * signedGenerator generators1 a *
      transversal1 i ∈ Subgroup.closure (Set.range generators2) := by
  have h : ∀ (a : Fin 4) (i : Fin 11) (x : Fin 12),
      signedGenerator generators1 a (transversal1 i x) =
        transversal1 targetIndices1[a][i]
          (evalWord generators2 residueWords1[a][i] x) := by
    decide +kernel
  have heq : signedGenerator generators1 a * transversal1 i =
      transversal1 targetIndices1[a][i] *
        evalWord generators2 residueWords1[a][i] := Equiv.ext (h a i)
  refine ⟨targetIndices1[a][i], ?_⟩
  rw [mul_assoc, heq, inv_mul_cancel_left]
  exact evalWord_mem _ _

private theorem bound1 : Nat.card (Subgroup.closure (Set.range generators1)) ≤
    11 * Nat.card (Subgroup.closure (Set.range generators2)) := by
  have h := Subgroup.natCard_closure_le_mul generators1 transversal1
    (Subgroup.closure (Set.range generators2))
    ⟨0, transversal1_zero⟩ ?_ ?_
  · simpa only [Nat.card_fin] using h
  · intro a i
    simpa only [signedGenerator_castAdd] using step1 (Fin.castAdd 2 a) i
  · intro a i
    simpa only [signedGenerator_natAdd] using step1 (Fin.natAdd 2 a) i

private theorem step2 (a : Fin 4) (i : Fin 10) :
    ∃ j, (transversal2 j)⁻¹ * signedGenerator generators2 a *
      transversal2 i ∈ Subgroup.closure (Set.range generators3) := by
  have h : ∀ (a : Fin 4) (i : Fin 10) (x : Fin 12),
      signedGenerator generators2 a (transversal2 i x) =
        transversal2 targetIndices2[a][i]
          (evalWord generators3 residueWords2[a][i] x) := by
    decide +kernel
  have heq : signedGenerator generators2 a * transversal2 i =
      transversal2 targetIndices2[a][i] *
        evalWord generators3 residueWords2[a][i] := Equiv.ext (h a i)
  refine ⟨targetIndices2[a][i], ?_⟩
  rw [mul_assoc, heq, inv_mul_cancel_left]
  exact evalWord_mem _ _

private theorem bound2 : Nat.card (Subgroup.closure (Set.range generators2)) ≤
    10 * Nat.card (Subgroup.closure (Set.range generators3)) := by
  have h := Subgroup.natCard_closure_le_mul generators2 transversal2
    (Subgroup.closure (Set.range generators3))
    ⟨0, transversal2_zero⟩ ?_ ?_
  · simpa only [Nat.card_fin] using h
  · intro a i
    simpa only [signedGenerator_castAdd] using step2 (Fin.castAdd 2 a) i
  · intro a i
    simpa only [signedGenerator_natAdd] using step2 (Fin.natAdd 2 a) i

private theorem step3 (a : Fin 4) (i : Fin 9) :
    ∃ j, (transversal3 j)⁻¹ * signedGenerator generators3 a *
      transversal3 i ∈ Subgroup.closure (Set.range generators4) := by
  have h : ∀ (a : Fin 4) (i : Fin 9) (x : Fin 12),
      signedGenerator generators3 a (transversal3 i x) =
        transversal3 targetIndices3[a][i]
          (evalWord generators4 residueWords3[a][i] x) := by
    decide +kernel
  have heq : signedGenerator generators3 a * transversal3 i =
      transversal3 targetIndices3[a][i] *
        evalWord generators4 residueWords3[a][i] := Equiv.ext (h a i)
  refine ⟨targetIndices3[a][i], ?_⟩
  rw [mul_assoc, heq, inv_mul_cancel_left]
  exact evalWord_mem _ _

private theorem bound3 : Nat.card (Subgroup.closure (Set.range generators3)) ≤
    9 * Nat.card (Subgroup.closure (Set.range generators4)) := by
  have h := Subgroup.natCard_closure_le_mul generators3 transversal3
    (Subgroup.closure (Set.range generators4))
    ⟨0, transversal3_zero⟩ ?_ ?_
  · simpa only [Nat.card_fin] using h
  · intro a i
    simpa only [signedGenerator_castAdd] using step3 (Fin.castAdd 2 a) i
  · intro a i
    simpa only [signedGenerator_natAdd] using step3 (Fin.natAdd 2 a) i

private theorem step4 (a : Fin 4) (i : Fin 8) :
    ∃ j, (transversal4 j)⁻¹ * signedGenerator generators4 a *
      transversal4 i ∈ Subgroup.closure (Set.range generators5) := by
  have h : ∀ (a : Fin 4) (i : Fin 8) (x : Fin 12),
      signedGenerator generators4 a (transversal4 i x) =
        transversal4 targetIndices4[a][i]
          (evalWord generators5 residueWords4[a][i] x) := by
    decide +kernel
  have heq : signedGenerator generators4 a * transversal4 i =
      transversal4 targetIndices4[a][i] *
        evalWord generators5 residueWords4[a][i] := Equiv.ext (h a i)
  refine ⟨targetIndices4[a][i], ?_⟩
  rw [mul_assoc, heq, inv_mul_cancel_left]
  exact evalWord_mem _ _

private theorem bound4 : Nat.card (Subgroup.closure (Set.range generators4)) ≤
    8 * Nat.card (Subgroup.closure (Set.range generators5)) := by
  have h := Subgroup.natCard_closure_le_mul generators4 transversal4
    (Subgroup.closure (Set.range generators5))
    ⟨0, transversal4_zero⟩ ?_ ?_
  · simpa only [Nat.card_fin] using h
  · intro a i
    simpa only [signedGenerator_castAdd] using step4 (Fin.castAdd 2 a) i
  · intro a i
    simpa only [signedGenerator_natAdd] using step4 (Fin.natAdd 2 a) i

private theorem generators5_closure :
    Subgroup.closure (Set.range generators5) = ⊥ := by
  simp only [Set.range_eq_empty, Subgroup.closure_empty]

private theorem image_le_closure :
    m12PermutationHom.range ≤ Subgroup.closure (Set.range generators0) := by
  have hgen := PresentedGroup.closure_range_of m12Presentation.relatorSet
  have hmap := congrArg (Subgroup.map m12PermutationHom) hgen
  rw [MonoidHom.map_closure, Subgroup.map_top, ← Set.range_comp] at hmap
  rw [← hmap, Subgroup.closure_le]
  rintro _ ⟨i, rfl⟩
  rw [Function.comp_apply, m12PermutationHom_of]
  have hi : i.val < 2 := by simpa [GroupPresentation.generatorCount] using i.isLt
  have h : ∀ j : Fin 2,
      m12GeneratorImages ⟨j.val, by simpa [GroupPresentation.generatorCount] using j.isLt⟩ =
        generators0 j := by
    decide +kernel
  exact Subgroup.subset_closure ⟨⟨i.val, hi⟩, (h ⟨i.val, hi⟩).symm⟩

/-- The checked Schreier cover bounds the concrete M12 permutation image by 95040. -/
theorem m12PermutationHom_range_natCard_le : Nat.card m12PermutationHom.range ≤ 95040 := by
  have h := Nat.card_le_card_of_injective
    (Subgroup.inclusion image_le_closure) (Subgroup.inclusion_injective image_le_closure)
  have h5 : Nat.card (Subgroup.closure (Set.range generators5)) = 1 := by
    rw [generators5_closure]
    exact Subgroup.card_bot
  have h0 := bound0
  have h1 := bound1
  have h2 := bound2
  have h3 := bound3
  have h4 := bound4
  omega

/-- The image of the exact M12 presentation in the checked degree-12 action has order 95040. -/
theorem m12PermutationHom_range_natCard : Nat.card m12PermutationHom.range = 95040 :=
  le_antisymm m12PermutationHom_range_natCard_le m12PermutationHom_range_natCard_ge

end TauCeti.Sporadic.Mathieu
