/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Subgroup.GeneratorCover
public import TauCeti.GroupTheory.SpecificGroups.CFSG.BasicProperties.Mathieu.M23LowerBound
import Mathlib.Algebra.Group.Subgroup.Finite
import Mathlib.Tactic.FinCases
import all TauCeti.GroupTheory.SpecificGroups.CFSG.BasicProperties.Mathieu.M23Cover
import all TauCeti.GroupTheory.SpecificGroups.CFSG.BasicProperties.Mathieu.Permutation

/-!
# The order of the M23 permutation image

The checked transition tables in `M23Cover` provide six finite covers with sizes
23, 22, 21, 20, 16, and 3. The generic finite-cover theorem bounds the subgroup
cardinalities successively, giving an upper bound of 10200960 for the exact
permutation image. The independent word-based lower bound then gives equality.

No presentation finiteness, faithfulness, or simplicity assertion is made. The
representatives need not lie in the image or form transversals of identified
stabilizers: the upper bound uses only their checked generator transitions.
-/

public section

namespace TauCeti.Sporadic.Mathieu

open M23Cover

/-- The subgroup generated by a level of the certificate. -/
private def levelSubgroup (level : Fin 7) : Subgroup (Equiv.Perm (Fin 23)) :=
  Subgroup.closure (Set.range (strongGenerators level))

private theorem inverse_generator (level : Fin 6)
    (i : Fin (generatorSize level.castSucc)) :
    ∃ j, strongGenerators level.castSucc j = (strongGenerators level.castSucc i)⁻¹ := by
  have h : ∀ (k : Fin 6) (a : Fin (generatorSize k.castSucc)),
      ∃ b, strongGenerators k.castSucc b = (strongGenerators k.castSucc a)⁻¹ := by
    decide +kernel
  exact h level i

private theorem representative_one (level : Fin 6) :
    ∃ i, representatives level i = 1 := by
  fin_cases level <;> refine ⟨⟨0, by decide⟩, Equiv.ext ?_⟩ <;> decide +kernel

private theorem step (level : Fin 6) (a : Fin (generatorSize level.castSucc))
    (i : Fin (transversalSize level)) :
    ∃ j, (representatives level j)⁻¹ * strongGenerators level.castSucc a *
      representatives level i ∈ levelSubgroup level.succ := by
  refine ⟨(transitions level a i).1, ?_⟩
  rw [mul_assoc, transitions_valid, inv_mul_cancel_left]
  apply Subgroup.list_prod_mem
  intro x hx
  obtain ⟨j, _, rfl⟩ := List.mem_map.mp hx
  exact Subgroup.subset_closure ⟨j, rfl⟩

private theorem level_bound (level : Fin 6) :
    Nat.card (levelSubgroup level.castSucc) ≤
      transversalSize level * Nat.card (levelSubgroup level.succ) := by
  have h := Subgroup.natCard_closure_le_mul (strongGenerators level.castSucc)
    (representatives level) (levelSubgroup level.succ) (representative_one level)
    (step level) ?_
  · simpa only [levelSubgroup, Nat.card_fin] using h
  · intro a i
    obtain ⟨b, hb⟩ := inverse_generator level a
    obtain ⟨j, hj⟩ := step level b i
    exact ⟨j, by simpa only [hb] using hj⟩

private theorem terminal_subgroup : levelSubgroup 6 = ⊥ := by
  simp [levelSubgroup, strongGenerators, generatorSize]

private theorem image_le_closure : m23PermutationHom.range ≤ levelSubgroup 0 := by
  have hgen := PresentedGroup.closure_range_of m23Presentation.relatorSet
  have hmap := congrArg (Subgroup.map m23PermutationHom) hgen
  rw [MonoidHom.map_closure, Subgroup.map_top, ← Set.range_comp] at hmap
  rw [← hmap, Subgroup.closure_le]
  rintro _ ⟨i, rfl⟩
  rw [Function.comp_apply, m23PermutationHom_of]
  have hi : i.val < 2 := by simpa [GroupPresentation.generatorCount] using i.isLt
  have h : ∀ (j : Fin 2) (x : Fin 23),
      m23GeneratorImages ⟨j.val, by simpa [GroupPresentation.generatorCount] using j.isLt⟩ x =
        generators0 (Fin.castLE (by decide) j) x := by
    decide +kernel
  exact Subgroup.subset_closure
    ⟨Fin.castLE (by decide) ⟨i.val, hi⟩, (Equiv.ext (h ⟨i.val, hi⟩)).symm⟩

/-- The checked finite covers bound the degree-23 permutation image by 10200960. -/
theorem m23PermutationHom_range_natCard_le :
    Nat.card m23PermutationHom.range ≤ 10200960 := by
  apply (Subgroup.card_le_of_le image_le_closure).trans
  have h0 := level_bound 0
  have h1 := level_bound 1
  have h2 := level_bound 2
  have h3 := level_bound 3
  have h4 := level_bound 4
  have h5 := level_bound 5
  change Nat.card (levelSubgroup 0) ≤ 23 * Nat.card (levelSubgroup 1) at h0
  change Nat.card (levelSubgroup 1) ≤ 22 * Nat.card (levelSubgroup 2) at h1
  change Nat.card (levelSubgroup 2) ≤ 21 * Nat.card (levelSubgroup 3) at h2
  change Nat.card (levelSubgroup 3) ≤ 20 * Nat.card (levelSubgroup 4) at h3
  change Nat.card (levelSubgroup 4) ≤ 16 * Nat.card (levelSubgroup 5) at h4
  change Nat.card (levelSubgroup 5) ≤ 3 * Nat.card (levelSubgroup 6) at h5
  rw [terminal_subgroup, Subgroup.card_bot] at h5
  exact h0.trans (Nat.mul_le_mul_left 23
    (h1.trans (Nat.mul_le_mul_left 22
      (h2.trans (Nat.mul_le_mul_left 21
        (h3.trans (Nat.mul_le_mul_left 20
          (h4.trans (Nat.mul_le_mul_left 16 h5)))))))))

/-- The image of the exact M23 presentation in the checked action has order 10200960. -/
theorem m23PermutationHom_range_natCard : Nat.card m23PermutationHom.range = 10200960 :=
  le_antisymm m23PermutationHom_range_natCard_le m23PermutationHom_range_natCard_ge

end TauCeti.Sporadic.Mathieu
