/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RepresentationTheory.Homological.GroupCohomology.FiniteCyclic
public import Mathlib.RepresentationTheory.Homological.GroupHomology.FiniteCyclic
public import TauCeti.RepresentationTheory.Invariants
public import TauCeti.RepresentationTheory.Homological.TateCohomology.LowDegree

/-!
# Tate cohomology of a finite cyclic group is two-periodic

For a finite cyclic group `G` generated by `g`, the standard periodic resolution alternates the
norm map `N` with `ρ(g) - 𝟙`. Consequently the whole two-sided family of Tate groups of a
representation `M` collapses onto just two modules: every even Tate degree is the homology of

`M --N--> M --(ρ(g) - 𝟙)--> M`,

and every odd Tate degree is the homology of the same two maps in the opposite order.

Mathlib supplies this periodic resolution and its two homology calculations for ordinary group
cohomology in positive degrees and for ordinary group homology, together with the comparisons of
Tate cohomology with ordinary cohomology in degrees `≥ 1` and with ordinary homology in degrees
`≤ -2`. This file assembles those comparisons over all of `ℤ`. The four degree ranges are treated
separately, because the two middle degrees are not ordinary (co)homology at all: degree `0` is
`Mᴳ / N M` and degree `-1` is `ker N / I_G M`, and they are matched with the same two periodic
models through the low-degree identifications of
`TauCeti.RepresentationTheory.Homological.TateCohomology.LowDegree`.

The parities line up across the splice: for `n ≥ 1` an even degree is ordinary cohomology in an
even degree, while for `n = -(i + 1) ≤ -2` an even degree is ordinary homology in an *odd*
degree, and Mathlib's homology calculation in odd degrees produces exactly the model that its
cohomology calculation produces in even degrees.

## Provenance

The corresponding all-degree construction is `Rep.periodicTateCohomology` in
`ClassFieldTheory/Cohomology/FiniteCyclic/UpDown.lean` from `kbuzzard/ClassFieldTheory`, commit
`ccc3323c6750abca25b49b35106f54eb3a398509`. That development builds a periodic complex of its
own; the construction below instead reads the periodicity off Mathlib's imported Tate groups,
through the periodic-resolution calculations `Rep.FiniteCyclicGroup.groupCohomologyIsoEven`,
`groupCohomologyIsoOdd`, `groupHomologyIsoEven` and `groupHomologyIsoOdd`.

## Main definitions

* `Rep.FiniteCyclicGroup.tateCohomologyIso₀`: degree zero is the homology of
  `M --N--> M --(ρ(g) - 𝟙)--> M`.
* `Rep.FiniteCyclicGroup.tateCohomologyIsoNegOne`: degree `-1` is the homology of
  `M --(ρ(g) - 𝟙)--> M --N--> M`.
* `Rep.FiniteCyclicGroup.tateCohomologyIsoEven`: the common explicit model for every even
  integer degree.
* `Rep.FiniteCyclicGroup.tateCohomologyIsoOdd`: the common explicit model for every odd integer
  degree.
* `Rep.FiniteCyclicGroup.periodicIso`: **two-periodicity**, an isomorphism between any two Tate
  degrees congruent modulo two. Taking `n` and `n + 2` gives the usual statement.

## Main results

* `Rep.FiniteCyclicGroup.natCard_tateCohomology_eq_of_modEq`: Tate degrees congruent modulo two
  have the same cardinality. This is the form the Herbrand quotient is computed with.

## References

* K. S. Brown, *Cohomology of Groups*, Chapter VI, §9.
* J.-P. Serre, *Local Fields*, Chapter VIII, §4.
-/

public noncomputable section

universe u

open CategoryTheory LinearMap Rep

namespace Rep.FiniteCyclicGroup

section Generator

variable {R G : Type u} [CommRing R] [Group G] [Fintype G] (M : Rep R G) (g : G)

/-- Degree-zero Tate cohomology of a finite cyclic group generated by `g` is the homology of
`M --N--> M --(ρ(g) - 𝟙)--> M`.

Both sides are `Mᴳ / N M`: the left-hand side by the low-degree identification of degree zero,
the right-hand side because `g` generates, so the kernel of `ρ(g) - 𝟙` is the invariants. -/
def tateCohomologyIso₀ (hg : ∀ x, x ∈ Subgroup.zpowers g) :
    let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
      ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
    let _ : CommGroup G := IsCyclic.commGroup
    tateCohomology M 0 ≅ (normHomCompSub M g).homology := by
  letI : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
    ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
  letI : CommGroup G := IsCyclic.commGroup
  exact calc
  tateCohomology M 0 ≅ ModuleCat.of R
      (M.ρ.invariants ⧸ (range M.ρ.norm).submoduleOf M.ρ.invariants) :=
    TauCeti.TateCohomology.H0IsoNormQuotient M
  _ ≅ (normHomCompSub M g).moduleCatLeftHomologyData.H := by
    refine (Submodule.Quotient.equiv _ _
      (LinearEquiv.ofEq _ _ (by simpa [sub_hom, applyAsHom] using
        invariants_eq_ker_apply_sub M g hg)) ?_).toModuleIso
    refine Submodule.ext fun ⟨x, hx⟩ ↦ ⟨?_, ?_⟩
    · rintro ⟨⟨y, hy⟩, ⟨z, hz⟩, hw⟩
      exact ⟨z, Subtype.ext (hz.trans congr(Subtype.val $hw))⟩
    · rintro ⟨z, hz⟩
      refine ⟨⟨M.ρ.norm z, fun γ ↦ M.ρ.self_norm_apply γ z⟩, ⟨z, rfl⟩, Subtype.ext ?_⟩
      exact congr(Subtype.val $hz)
  _ ≅ (normHomCompSub M g).homology := (ShortComplex.moduleCatHomologyIso _).symm

/-- Degree `-1` Tate cohomology of a finite cyclic group generated by `g` is the homology of
`M --(ρ(g) - 𝟙)--> M --N--> M`.

Both sides are `ker N / I_G M`: the left-hand side by the low-degree identification of degree
`-1`, the right-hand side because `g` generates, so the augmentation submodule is the image of
`ρ(g) - 𝟙`. -/
def tateCohomologyIsoNegOne (hg : ∀ x, x ∈ Subgroup.zpowers g) :
    let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
      ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
    let _ : CommGroup G := IsCyclic.commGroup
    tateCohomology M (-1) ≅ (subCompNormHom M g).homology := by
  letI : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
    ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
  letI : CommGroup G := IsCyclic.commGroup
  exact calc
  tateCohomology M (-1) ≅ ModuleCat.of R
      (ker M.ρ.norm ⧸ (Representation.Coinvariants.ker M.ρ).submoduleOf (ker M.ρ.norm)) :=
    TauCeti.TateCohomology.HNegOneIsoNormKernelQuotient M
  _ ≅ (subCompNormHom M g).moduleCatLeftHomologyData.H := by
    refine (Submodule.Quotient.equiv _ _ (LinearEquiv.refl R _) ?_).toModuleIso
    rw [Representation.FiniteCyclicGroup.coinvariantsKer_eq_range M.ρ g hg]
    refine Submodule.ext fun ⟨x, hx⟩ ↦ ⟨?_, ?_⟩
    · rintro ⟨⟨y, hy⟩, ⟨z, hz⟩, hw⟩
      have hyx : y = x := congr(Subtype.val $hw)
      exact ⟨z, Subtype.ext (by
        simpa [ShortComplex.moduleCatToCycles, sub_hom, applyAsHom, hyx] using hz)⟩
    · rintro ⟨z, hz⟩
      refine ⟨⟨x, hx⟩, ⟨z, ?_⟩, rfl⟩
      simpa [ShortComplex.moduleCatToCycles, sub_hom, applyAsHom] using congr(Subtype.val $hz)
  _ ≅ (subCompNormHom M g).homology := (ShortComplex.moduleCatHomologyIso _).symm

/-- In every even integer degree, Tate cohomology of a finite cyclic group generated by `g` is
the homology of `M --N--> M --(ρ(g) - 𝟙)--> M`.

Positive even degrees are ordinary cohomology in an even degree, degree zero is
`tateCohomologyIso₀`, and a degree `-(i + 1) ≤ -2` is even exactly when `i` is odd, where it is
ordinary homology in an odd degree. -/
def tateCohomologyIsoEven (hg : ∀ x, x ∈ Subgroup.zpowers g) (n : ℤ) (hn : Even n) :
    let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
      ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
    let _ : CommGroup G := IsCyclic.commGroup
    tateCohomology M n ≅ (normHomCompSub M g).homology := by
  letI : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
    ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
  letI : CommGroup G := IsCyclic.commGroup
  classical
  rcases n with k | k
  · rcases k with _ | k
    · exact tateCohomologyIso₀ M g hg
    · have hk : Even (k + 1) := by
        rw [Nat.even_iff]
        rw [Int.even_iff, Int.ofNat_eq_natCast] at hn
        omega
      exact (TateCohomology.isoGroupCohomology (k + 1)).app M ≪≫
        groupCohomologyIsoEven M g hg (k + 1) hk
  · have hk : Odd k := by
      rw [Nat.odd_iff]
      rw [Int.even_iff, Int.negSucc_eq] at hn
      omega
    have : NeZero k := ⟨hk.pos.ne'⟩
    exact (TateCohomology.isoGroupHomology (Int.negSucc k) k
        (by rw [Int.negSucc_eq])).app M ≪≫
      groupHomologyIsoOdd M g hg k hk

/-- In every odd integer degree, Tate cohomology of a finite cyclic group generated by `g` is the
homology of `M --(ρ(g) - 𝟙)--> M --N--> M`.

Positive odd degrees are ordinary cohomology in an odd degree, degree `-1` is
`tateCohomologyIsoNegOne`, and a degree `-(i + 1) ≤ -2` is odd exactly when `i` is even and
nonzero, where it is ordinary homology in a nonzero even degree. -/
def tateCohomologyIsoOdd (hg : ∀ x, x ∈ Subgroup.zpowers g) (n : ℤ) (hn : Odd n) :
    let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
      ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
    let _ : CommGroup G := IsCyclic.commGroup
    tateCohomology M n ≅ (subCompNormHom M g).homology := by
  letI : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
    ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
  letI : CommGroup G := IsCyclic.commGroup
  classical
  rcases n with k | k
  · have hk : Odd k := by
      rw [Nat.odd_iff]
      rw [Int.odd_iff, Int.ofNat_eq_natCast] at hn
      omega
    have : NeZero k := ⟨hk.pos.ne'⟩
    exact (TateCohomology.isoGroupCohomology k).app M ≪≫ groupCohomologyIsoOdd M g hg k hk
  · rcases k with _ | j
    · exact tateCohomologyIsoNegOne M g hg
    · have hj : Even (j + 1) := by
        rw [Nat.even_iff]
        rw [Int.odd_iff, Int.negSucc_eq] at hn
        omega
      exact (TateCohomology.isoGroupHomology (Int.negSucc (j + 1)) (j + 1)
          (by rw [Int.negSucc_eq])).app M ≪≫ groupHomologyIsoEven M g hg (j + 1) hj

/-- In degree zero, the all-degree even comparison is `tateCohomologyIso₀`. -/
@[simp]
theorem tateCohomologyIsoEven_zero (hg : ∀ x, x ∈ Subgroup.zpowers g) (h0 : Even (0 : ℤ)) :
    tateCohomologyIsoEven M g hg 0 h0 = tateCohomologyIso₀ M g hg := by
  rfl

/-- In a positive even degree, the all-degree comparison is the composite through ordinary
group cohomology. -/
@[simp]
theorem tateCohomologyIsoEven_ofNat_succ (hg : ∀ x, x ∈ Subgroup.zpowers g) (k : ℕ)
    (hk : Even (k + 1)) :
    let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
      ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
    let _ : CommGroup G := IsCyclic.commGroup
    tateCohomologyIsoEven M g hg ((k : ℤ) + 1) hk.natCast =
      (TateCohomology.isoGroupCohomology (k + 1)).app M ≪≫
        groupCohomologyIsoEven M g hg (k + 1) hk := by
  let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
    ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
  let _ : CommGroup G := IsCyclic.commGroup
  rfl

/-- In a degree at most `-2`, the all-degree even comparison is the composite through ordinary
group homology in the corresponding odd degree. -/
@[simp]
theorem tateCohomologyIsoEven_negSucc (hg : ∀ x, x ∈ Subgroup.zpowers g) (k : ℕ)
    (hk : Odd k) :
    let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
      ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
    let _ : CommGroup G := IsCyclic.commGroup
    tateCohomologyIsoEven M g hg (Int.negSucc k) (by
      rcases hk with ⟨a, ha⟩
      refine ⟨-(a + 1 : ℤ), ?_⟩
      norm_num [Int.negSucc_eq, ha]
      ring) =
      (let _ : NeZero k := ⟨hk.pos.ne'⟩
       let _ := Classical.decEq G
       (TateCohomology.isoGroupHomology (Int.negSucc k) k (by
          rw [Int.negSucc_eq])).app M ≪≫ groupHomologyIsoOdd M g hg k hk) := by
  let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
    ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
  let _ : CommGroup G := IsCyclic.commGroup
  rfl

/-- In a positive odd degree, the all-degree comparison is the composite through ordinary group
cohomology. -/
@[simp]
theorem tateCohomologyIsoOdd_ofNat (hg : ∀ x, x ∈ Subgroup.zpowers g) (k : ℕ)
    (hk : Odd k) :
    let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
      ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
    let _ : CommGroup G := IsCyclic.commGroup
    tateCohomologyIsoOdd M g hg (k : ℤ) hk.natCast =
      (let _ : NeZero k := ⟨hk.pos.ne'⟩
       (TateCohomology.isoGroupCohomology k).app M ≪≫
         groupCohomologyIsoOdd M g hg k hk) := by
  let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
    ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
  let _ : CommGroup G := IsCyclic.commGroup
  rfl

/-- In degree `-1`, the all-degree odd comparison is `tateCohomologyIsoNegOne`. -/
@[simp]
theorem tateCohomologyIsoOdd_negOne (hg : ∀ x, x ∈ Subgroup.zpowers g)
    (hneg : Odd (-1 : ℤ)) :
    tateCohomologyIsoOdd M g hg (-1) hneg = tateCohomologyIsoNegOne M g hg := by
  rfl

/-- In a degree at most `-2`, the all-degree odd comparison is the composite through ordinary
group homology in the corresponding nonzero even degree. -/
@[simp]
theorem tateCohomologyIsoOdd_negSucc_succ (hg : ∀ x, x ∈ Subgroup.zpowers g) (j : ℕ)
    (hj : Even (j + 1)) :
    let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
      ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
    let _ : CommGroup G := IsCyclic.commGroup
    tateCohomologyIsoOdd M g hg (Int.negSucc (j + 1)) (by
      rcases hj with ⟨a, ha⟩
      refine ⟨-(a : ℤ) - 1, ?_⟩
      norm_num [Int.negSucc_eq, ha]
      ring) =
      (let _ := Classical.decEq G
       (TateCohomology.isoGroupHomology (Int.negSucc (j + 1)) (j + 1) (by
          rw [Int.negSucc_eq])).app M ≪≫ groupHomologyIsoEven M g hg (j + 1) hj) := by
  let _ : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
    ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
  let _ : CommGroup G := IsCyclic.commGroup
  rfl

/-- The generator-dependent comparison underlying two-periodicity. It compares two degrees of the
same parity with the same homology object of the standard periodic resolution, using the even
model or the odd model according to that common parity. -/
def periodicIsoOfGenerator (hg : ∀ x, x ∈ Subgroup.zpowers g) (m n : ℤ)
    (hmn : m ≡ n [ZMOD 2]) : tateCohomology M m ≅ tateCohomology M n := by
  letI : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr
    ⟨g, (Subgroup.zpowers g).eq_top_iff'.mpr hg⟩
  letI : CommGroup G := IsCyclic.commGroup
  have hpar : Even m ↔ Even n := by
    have h : m % 2 = n % 2 := hmn
    rw [Int.even_iff, Int.even_iff, h]
  by_cases hm : Even m
  · exact (tateCohomologyIsoEven M g hg m hm).trans
      (tateCohomologyIsoEven M g hg n (hpar.mp hm)).symm
  · exact (tateCohomologyIsoOdd M g hg m (Int.not_even_iff_odd.mp hm)).trans
      (tateCohomologyIsoOdd M g hg n (Int.not_even_iff_odd.mp (hpar.not.mp hm))).symm

/-- In even degrees, `periodicIsoOfGenerator` is the comparison obtained by identifying both Tate
groups with the even homology object of the periodic resolution. -/
@[simp, reassoc]
theorem periodicIsoOfGenerator_hom_comp_tateCohomologyIsoEven_hom
    (hg : ∀ x, x ∈ Subgroup.zpowers g) (m n : ℤ) (hmn : m ≡ n [ZMOD 2])
    (hm : Even m) (hn : Even n) :
    (periodicIsoOfGenerator M g hg m n hmn).hom ≫ (tateCohomologyIsoEven M g hg n hn).hom =
      (tateCohomologyIsoEven M g hg m hm).hom := by
  simp [periodicIsoOfGenerator, hm]

/-- In odd degrees, `periodicIsoOfGenerator` is the comparison obtained by identifying both Tate
groups with the odd homology object of the periodic resolution. -/
@[simp, reassoc]
theorem periodicIsoOfGenerator_hom_comp_tateCohomologyIsoOdd_hom
    (hg : ∀ x, x ∈ Subgroup.zpowers g) (m n : ℤ) (hmn : m ≡ n [ZMOD 2])
    (hm : Odd m) (hn : Odd n) :
    (periodicIsoOfGenerator M g hg m n hmn).hom ≫ (tateCohomologyIsoOdd M g hg n hn).hom =
      (tateCohomologyIsoOdd M g hg m hm).hom := by
  simp [periodicIsoOfGenerator, Int.not_even_iff_odd.mpr hm]

end Generator

section IsCyclic

variable {R G : Type u} [CommRing R] [Group G] [Fintype G]

/-- **Two-periodicity for Tate cohomology of a finite cyclic group.** Tate degrees congruent
modulo two are isomorphic; the case `n` and `n + 2` is the usual periodicity statement. -/
def periodicIso (M : Rep R G) [IsCyclic G] (m n : ℤ) (hmn : m ≡ n [ZMOD 2]) :
    tateCohomology M m ≅ tateCohomology M n := by
  let hgen := isCyclic_iff_exists_zpowers_eq_top.mp (inferInstance : IsCyclic G)
  let g := hgen.choose
  exact periodicIsoOfGenerator M g (fun x ↦ hgen.choose_spec.ge (Subgroup.mem_top x)) m n hmn

/-- Tate cohomology groups of a finite cyclic group in degrees congruent modulo two have the same
cardinality. This is the form used in Herbrand-quotient computations. -/
theorem natCard_tateCohomology_eq_of_modEq (M : Rep R G) [IsCyclic G] (m n : ℤ)
    (hmn : m ≡ n [ZMOD 2]) :
    Nat.card (tateCohomology M m) = Nat.card (tateCohomology M n) :=
  Nat.card_congr (periodicIso M m n hmn).toLinearEquiv.toEquiv

end IsCyclic

end Rep.FiniteCyclicGroup
