/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.FundamentalDiscriminant.OfSquarefree
public import TauCeti.NumberTheory.NumberField.Quadratic.RingOfIntegers
import TauCeti.NumberTheory.NumberField.IntegralSqrt

/-!
# The discriminant of a quadratic field is its fundamental discriminant

For a quadratic number field `K = ℚ(√d)` — presented by an algebraic integer `θ : 𝓞 K` with
`minpoly ℤ θ = X² - d` and `Algebra.adjoin ℚ {θ} = ⊤` — with `d` squarefree, the field
discriminant equals the fundamental discriminant of `d`:

`NumberField.discr K = fundamentalDiscriminant d` (`= d` for `d ≡ 1 mod 4`, else `4d`).

This ties the ring-of-integers discriminant computations
(`NumberField.discr_eq_four_mul_of_mod_four_ne_one` and
`NumberField.discr_eq_of_squarefree_of_mod_four_eq_one`) to the integer-level
`TauCeti.Multiquadratic.fundamentalDiscriminant`.

## Main results

* `TauCeti.Multiquadratic.discr_eq_fundamentalDiscriminant`.
* `TauCeti.Multiquadratic.discr_adjoin_singleton_eq_fundamentalDiscriminant`: the same formula
  for the intermediate field generated by a square root in a characteristic-zero ambient field.
-/

public section

open Polynomial
open scoped NumberField

namespace TauCeti.Multiquadratic

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K} {d : ℤ}

/-- **The discriminant of a quadratic field `ℚ(√d)` (squarefree `d`) is the fundamental
discriminant of `d`.** -/
theorem discr_eq_fundamentalDiscriminant (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hsf : Squarefree d) :
    NumberField.discr K = fundamentalDiscriminant d := by
  rw [fundamentalDiscriminant_def]
  split_ifs with h
  · exact NumberField.discr_eq_of_squarefree_of_mod_four_eq_one hmin hgen hsf h
  · exact NumberField.discr_eq_four_mul_of_mod_four_ne_one hmin hgen hsf h

/-- **Discriminant of a quadratic intermediate field.** If `x` is a square root of a squarefree
integer `d` which is not a rational square, then the intermediate field `ℚ(x)` has discriminant
`fundamentalDiscriminant d`.

The ambient field need only have characteristic zero: `x` is automatically integral, so the
statement supplies the resulting `NumberField` instance on `ℚ(x)` and the caller need not assume
one on `L`. -/
theorem discr_adjoin_singleton_eq_fundamentalDiscriminant {L : Type*} [Field L] [CharZero L]
    {d : ℤ} (hsf : Squarefree d) {x : L} (hx : x ^ 2 = algebraMap ℤ L d)
    (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) :
    let hxint : IsIntegral ℚ x := IsIntegral.of_pow (n := 2) (by norm_num) (by
      rw [hx, IsScalarTower.algebraMap_apply ℤ ℚ L]
      exact isIntegral_algebraMap)
    letI : NumberField (IntermediateField.adjoin ℚ {x}) :=
      { to_finiteDimensional := IntermediateField.adjoin.finiteDimensional hxint }
    NumberField.discr (IntermediateField.adjoin ℚ {x}) = fundamentalDiscriminant d := by
  have hxint : IsIntegral ℚ x := IsIntegral.of_pow (n := 2) (by norm_num) (by
    rw [hx, IsScalarTower.algebraMap_apply ℤ ℚ L]
    exact isIntegral_algebraMap)
  let _ : NumberField (IntermediateField.adjoin ℚ {x}) :=
    { to_finiteDimensional := IntermediateField.adjoin.finiteDimensional hxint }
  let pb : PowerBasis ℚ (IntermediateField.adjoin ℚ {x}) :=
    IntermediateField.adjoin.powerBasis hxint
  have hpbsq : pb.gen ^ 2 = algebraMap ℤ (IntermediateField.adjoin ℚ {x}) d := by
    apply Subtype.ext
    simpa [pb, IntermediateField.adjoin.powerBasis_gen] using hx
  let theta : 𝓞 (IntermediateField.adjoin ℚ {x}) := NumberField.integralSqrt hpbsq
  apply discr_eq_fundamentalDiscriminant (θ := theta) (d := d) _ _ hsf
  · exact NumberField.minpoly_integralSqrt hpbsq hnsq
  · rw [NumberField.RingOfIntegers.coe_eq_algebraMap,
      NumberField.algebraMap_integralSqrt]
    exact pb.adjoin_gen_eq_top

end TauCeti.Multiquadratic
