/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/

module

public import TauCeti.RepresentationTheory.Spin.Polarization.TypeD.ForkWeights

/-!
# The positive simple-root span in type D

This file packages the Lie subalgebra generated by the simple positive root
vectors and records the resulting annihilator statements for the two standard
half-spin vectors.
-/

open CliffordAlgebra
open TauCeti

public section

namespace TauCeti.TypeDStd

/-- The Lie subalgebra generated by the positive simple-root vectors of type D. -/
noncomputable def positiveSimpleRootLieSpan (n : ℕ) :
    LieSubalgebra ℚ (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n)) :=
  LieSubalgebra.lieSpan ℚ _
    (Set.range (fun i : Fin n => TauCeti.serreE ℚ (CartanMatrix.D n) i))

@[simp]
theorem serreE_mem_positiveSimpleRootLieSpan (n : ℕ) (i : Fin n) :
    TauCeti.serreE ℚ (CartanMatrix.D n) i ∈ positiveSimpleRootLieSpan n := by
  exact LieSubalgebra.subset_lieSpan (Set.mem_range_self i)

end TauCeti.TypeDStd

namespace TauCeti.SpinPolarizationData

attribute [local instance 100] LieRing.ofAssociativeRing

variable {V : Type*} [AddCommGroup V] [Module ℚ V] {Q : QuadraticForm ℚ V}
  (P : SpinPolarizationData Q) {n : ℕ} (b : Module.Basis (Fin n) ℚ P.W)

theorem typeDSpinSerreRepresentation_positiveSimpleRootLieSpan_le_lieAnnihilator
    (hn : 4 ≤ n) {v : ExteriorAlgebra ℚ P.W}
    (hv : ∀ i : Fin n,
      P.typeDSpinSerreRepresentation b hn
          (TauCeti.serreE ℚ (CartanMatrix.D n) i) v = 0) :
    letI : LieRingModule (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieRingModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    letI : LieModule ℚ (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    TauCeti.TypeDStd.positiveSimpleRootLieSpan n ≤
      TauCeti.lieAnnihilator ℚ _ v := by
  let _ : LieRingModule (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
      (ExteriorAlgebra ℚ P.W) :=
    LieRingModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
  let _ : LieModule ℚ (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
      (ExteriorAlgebra ℚ P.W) :=
    LieModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
  rw [TauCeti.TypeDStd.positiveSimpleRootLieSpan, LieSubalgebra.lieSpan_le]
  rintro _ ⟨i, rfl⟩
  apply (TauCeti.mem_lieAnnihilator ℚ _).mpr
  exact by simpa [LieRingModule.compLieHom_apply] using hv i

theorem typeDSpinSerreRepresentation_positiveSimpleRootLieSpan_le_lieAnnihilator_univ
    (hn : 4 ≤ n) :
    letI : LieRingModule (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieRingModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    letI : LieModule ℚ (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    TauCeti.TypeDStd.positiveSimpleRootLieSpan n ≤
      TauCeti.lieAnnihilator ℚ _
        (b.ExteriorAlgebra (Finset.univ : Finset (Fin n))) := by
  apply P.typeDSpinSerreRepresentation_positiveSimpleRootLieSpan_le_lieAnnihilator b hn
  intro i
  rw [P.typeDSpinSerreRepresentation_serreE b hn]
  rw [← P.typeDSpinRep_serreE_eq_spinAction b hn]
  exact P.typeDSpinRep_serreE_exteriorBasis_univ_eq_zero b hn i

theorem typeDSpinSerreRepresentation_positiveSimpleRootLieSpan_le_lieAnnihilator_univ_erase_last
    (hn : 4 ≤ n) :
    letI : LieRingModule (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieRingModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    letI : LieModule ℚ (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    TauCeti.TypeDStd.positiveSimpleRootLieSpan n ≤
      TauCeti.lieAnnihilator ℚ _
        (b.ExteriorAlgebra
          ((Finset.univ : Finset (Fin n)).erase (⟨n - 1, by omega⟩ : Fin n))) := by
  apply P.typeDSpinSerreRepresentation_positiveSimpleRootLieSpan_le_lieAnnihilator b hn
  intro i
  rw [P.typeDSpinSerreRepresentation_serreE b hn]
  rw [← P.typeDSpinRep_serreE_eq_spinAction b hn]
  exact P.typeDSpinRep_serreE_exteriorBasis_univ_erase_last_eq_zero b hn i

end TauCeti.SpinPolarizationData
