/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Spin.HalfSpin
public import TauCeti.RepresentationTheory.Spin.Polarization.TypeD.KostantLattice

/-!
# The fork-weight vectors in the type-D spin representation

The two spin fundamental weights of type `Dₙ` occur at the fork of its Dynkin diagram. In the
exterior model they are represented by the basis vector with every coordinate occupied and the
basis vector obtained from it by erasing the final coordinate. This file proves the three facts
that identify those vectors in the pinned Serre representation:

* every positive simple generator annihilates each vector;
* their Cartan weights are respectively the final and penultimate fundamental coordinates;
* their membership in the even and odd half-spin summands is determined by the parity of `n`.

Thus the convention is explicit: the final fork weight belongs to `spinPlus` in even rank and to
`spinMinus` in odd rank, while the penultimate fork weight has the opposite assignment. These are
the generator-level inputs for a highest-weight identification. A promotion to
`IsHighestWeightVector` additionally requires a compatible Borel and the proof that its positive
nilradical is generated by the displayed positive root spaces; no such Borel is asserted here.

## Main results

* `TauCeti.SpinPolarizationData.typeDSpinRep_serreE_exteriorBasis_univ` and
  `TauCeti.SpinPolarizationData.typeDSpinRep_serreE_exteriorBasis_univ_erase_last`: the two
  vectors are annihilated by every positive simple generator.
* `TauCeti.SpinPolarizationData.isCartanWeightVector_typeDSpinRep_exteriorBasis_univ` and its
  `univ_erase_last` counterpart: their exact fork fundamental weights.
* `TauCeti.exteriorBasis_univ_mem_spinPlus_of_even` and the other three
  parity variants: their assignments to the two half-spin summands.

## References

* N. Bourbaki, *Lie Groups and Lie Algebras, Chapters 4--6*, Plate IV.
* W. Fulton and J. Harris, *Representation Theory: A First Course* (1991), Section 20.2.
-/

public section

open CliffordAlgebra

namespace TauCeti.SpinPolarizationData

universe u

variable {V : Type u} [AddCommGroup V] [Module ℚ V] {Q : QuadraticForm ℚ V}
  (P : SpinPolarizationData Q) {n : ℕ} (b : Module.Basis (Fin n) ℚ P.W)

/-! ## Positive-generator annihilation -/

/-- **Every positive simple type-`D` generator annihilates the all-coordinate exterior-basis
vector.** Along the chain, contraction removes the next coordinate and creation repeats the
still-present current coordinate. At the fork, creation immediately repeats a final coordinate. -/
theorem typeDSpinRep_serreE_exteriorBasis_univ (hn : 4 ≤ n) (i : Fin n) :
    P.typeDSpinRep b hn
        (_root_.UniversalEnvelopingAlgebra.ι ℚ
          (TauCeti.serreE ℚ (CartanMatrix.D n) i))
        (b.ExteriorAlgebra (Finset.univ : Finset (Fin n))) = 0 := by
  rw [P.typeDSpinRep_ι b hn, P.typeDSpinSerreRepresentation_serreE b hn,
    P.typeDSimpleRootBivector_def b]
  by_cases hnext : (i : ℕ) + 1 < n
  · rw [dite_eq_left hnext, map_mul, Module.End.mul_apply, TauCeti.spinAction_ι_wedge,
      TauCeti.spinAction_ι_contract, P.pairingEquiv_dualVector,
      TauCeti.ExteriorAlgebra.contractLeft_coord_basis, ite_eq_left (Finset.mem_univ _),
      mul_smul_comm, TauCeti.ExteriorAlgebra.ι_mul_basis,
      ite_eq_left (by simp [Fin.ext_iff]), smul_zero]
  · rw [dite_eq_right hnext, map_mul, Module.End.mul_apply, TauCeti.spinAction_ι_wedge,
      TauCeti.spinAction_ι_wedge, TauCeti.ExteriorAlgebra.ι_mul_basis,
      ite_eq_left (Finset.mem_univ _), mul_zero]

/-- **Every positive simple type-`D` generator annihilates the exterior-basis vector obtained by
erasing the final coordinate.** This is the fork companion of
`typeDSpinRep_serreE_exteriorBasis_univ`. -/
theorem typeDSpinRep_serreE_exteriorBasis_univ_erase_last (hn : 4 ≤ n) (i : Fin n) :
    P.typeDSpinRep b hn
        (_root_.UniversalEnvelopingAlgebra.ι ℚ
          (TauCeti.serreE ℚ (CartanMatrix.D n) i))
        (b.ExteriorAlgebra
          ((Finset.univ : Finset (Fin n)).erase (⟨n - 1, by omega⟩ : Fin n))) = 0 := by
  rw [P.typeDSpinRep_ι b hn, P.typeDSpinSerreRepresentation_serreE b hn,
    P.typeDSimpleRootBivector_def b]
  by_cases hnext : (i : ℕ) + 1 < n
  · rw [dite_eq_left hnext, map_mul, Module.End.mul_apply, TauCeti.spinAction_ι_wedge,
      TauCeti.spinAction_ι_contract, P.pairingEquiv_dualVector,
      TauCeti.ExteriorAlgebra.contractLeft_coord_basis]
    by_cases hlast : (⟨(i : ℕ) + 1, hnext⟩ : Fin n) = ⟨n - 1, by omega⟩
    · rw [ite_eq_right (by simp [hlast]), mul_zero]
    · rw [ite_eq_left (by simp [hlast]), mul_smul_comm,
        TauCeti.ExteriorAlgebra.ι_mul_basis,
        ite_eq_left (by simp [Fin.ext_iff]; omega), smul_zero]
  · rw [dite_eq_right hnext, map_mul, Module.End.mul_apply, TauCeti.spinAction_ι_wedge,
      TauCeti.spinAction_ι_wedge, TauCeti.ExteriorAlgebra.ι_mul_basis,
      ite_eq_right (by simp), mul_smul_comm, TauCeti.ExteriorAlgebra.ι_mul_basis,
      ite_eq_left (by simp), smul_zero]

/-! ## Exact fork weights -/

/-- The all-coordinate exterior-basis vector has the terminal fork fundamental weight for the
type-`D` Serre Cartan action. -/
@[simp 1100] theorem isCartanWeightVector_typeDSpinRep_exteriorBasis_univ (hn : 4 ≤ n) :
    TauCeti.UniversalEnvelopingAlgebra.IsCartanWeightVector
      (TauCeti.serreH ℚ (CartanMatrix.D n)) (P.typeDSpinRep b hn)
      (Pi.single (⟨n - 1, by omega⟩ : Fin n) 1)
      (b.ExteriorAlgebra (Finset.univ : Finset (Fin n))) := by
  simpa only [TauCeti.DynkinType.typeDSpinWeight_univ (n := n) (by omega)] using
    P.isCartanWeightVector_typeDSpinRep_exteriorBasis b hn
      (Finset.univ : Finset (Fin n))

/-- The exterior-basis vector obtained by erasing the final coordinate has the penultimate fork
fundamental weight for the type-`D` Serre Cartan action. -/
@[simp 1100] theorem isCartanWeightVector_typeDSpinRep_exteriorBasis_univ_erase_last (hn : 4 ≤ n) :
    TauCeti.UniversalEnvelopingAlgebra.IsCartanWeightVector
      (TauCeti.serreH ℚ (CartanMatrix.D n)) (P.typeDSpinRep b hn)
      (Pi.single (⟨n - 2, by omega⟩ : Fin n) 1)
      (b.ExteriorAlgebra
        ((Finset.univ : Finset (Fin n)).erase (⟨n - 1, by omega⟩ : Fin n))) := by
  simpa only [TauCeti.DynkinType.typeDSpinWeight_univ_erase_last (n := n) (by omega)] using
    P.isCartanWeightVector_typeDSpinRep_exteriorBasis b hn
      ((Finset.univ : Finset (Fin n)).erase (⟨n - 1, by omega⟩ : Fin n))

end TauCeti.SpinPolarizationData
