/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Group.Submonoid.BigOperators

/-!
# Integer combinations in the additive closure of a family

This file records when an integer combination `∑ i, c i • v i` of a finite family `v` lies in the
additive submonoid generated by the family: when all coefficients are nonnegative, and, up to sign,
when all coefficients have the same sign. These are the integer-coefficient companions of
`AddSubmonoid.mem_closure_range_iff_of_fintype`, which describes the closure through natural
coefficients.

## Main results

* `TauCeti.sum_smul_mem_closure`: a combination with nonnegative integer coefficients lies in the
  additive closure of the family.
* `TauCeti.sum_smul_mem_or_neg_mem_closure`: a combination whose coefficients all have the same sign
  lies in the additive closure of the family, or its negative does.
-/

public section

namespace TauCeti

open Set

variable {κ M : Type*} [Fintype κ] [SubtractionCommMonoid M] (v : κ → M)

/-- A combination of a finite family with nonnegative integer coefficients lies in the additive
closure of the family. -/
theorem sum_smul_mem_closure (c : κ → ℤ) (hc : ∀ i, 0 ≤ c i) :
    (∑ i, c i • v i) ∈ AddSubmonoid.closure (range v) := by
  refine AddSubmonoid.sum_mem _ fun i _ => ?_
  lift c i to ℕ using hc i with m
  rw [natCast_zsmul]
  exact AddSubmonoid.nsmul_mem _ (AddSubmonoid.subset_closure (mem_range_self i)) m

/-- A combination of a finite family whose integer coefficients all have the same sign lies in the
additive closure of the family, or its negative does. -/
theorem sum_smul_mem_or_neg_mem_closure (c : κ → ℤ) (hc : (∀ i, 0 ≤ c i) ∨ (∀ i, c i ≤ 0)) :
    (∑ i, c i • v i) ∈ AddSubmonoid.closure (range v) ∨
      -(∑ i, c i • v i) ∈ AddSubmonoid.closure (range v) := by
  refine hc.imp (sum_smul_mem_closure v c) fun h => ?_
  rw [← Finset.sum_neg_distrib]
  simp only [← neg_zsmul]
  exact sum_smul_mem_closure v (-c) fun i => Int.neg_nonneg_of_nonpos (h i)

end TauCeti
