/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Module.ZMod

import Mathlib.GroupTheory.FiniteAbelian.Duality
import TauCeti.Algebra.Group.TypeTags.Hom
import TauCeti.Algebra.Module.ZMod.Extend
import TauCeti.Algebra.Module.ZMod.Injective
import TauCeti.RingTheory.RootsOfUnity.ZMod

/-!
# The `ℤ/n`-dual of an additive group killed by `n`

An additive commutative group `M` killed by `n ≠ 0` is a `ℤ/n`-module, and its additive
homomorphisms to `ZMod n` are its `ℤ/n`-linear functionals. Written multiplicatively they are the
characters of `Multiplicative M` with values in `Multiplicative (ZMod n)`, a group with enough
roots of unity for the exponent of `M`, so Mathlib's duality theory for finite abelian groups
applies to them. This file records the two consequences that the duality of finite `ℤ/n[G]`-modules
rests on, phrased on `M →+ ZMod n` so that no module instance has to be installed by the caller:
for finite `M` there are exactly as many homomorphisms `M →+ ZMod n` as elements of `M`, and the
homomorphisms to `ZMod n` separate the points of `M`, finite or not. The count is also recorded for
`ℤ/n`-linear maps, for callers that already carry the module structures. The separation statement is
first proved on the finite cyclic subgroup generated by a point, and then extended to `M` along the
inclusion, using that `ZMod n` is an injective `ℤ/n`-module. The case `n = p` prime is the linear
algebra of the `𝔽_p`-vector space `M`.

## Main results

* `TauCeti.natCard_addMonoidHom_zmod`: `Nat.card (M →+ ZMod n) = Nat.card M` for finite `M` killed
  by `n`, and `AddEquiv.natCard_addMonoidHom_zmod`: the same count for the homomorphisms
  into any additive group `N ≃+ ZMod n`; `AddEquiv.natCard_linearMap_zmod`: the same count for the
  `ℤ/n`-linear maps of a finite `ℤ/n`-module.
* `TauCeti.exists_addMonoidHom_zmod_apply_ne_zero`: for `a ≠ 0` in `M` killed by `n`, some
  `f : M →+ ZMod n` has `f a ≠ 0`.
-/

public section

variable {n : ℕ} [NeZero n] {M : Type*} [AddCommGroup M]

namespace TauCeti

/-- A finite additive commutative group killed by `n ≠ 0` has as many additive homomorphisms to
`ZMod n` as elements. -/
theorem natCard_addMonoidHom_zmod [Finite M] (hM : ∀ x : M, n • x = 0) :
    Nat.card (M →+ ZMod n) = Nat.card M := by
  have := hasEnoughRootsOfUnity_multiplicative_zmod_exponent hM
  rw [Nat.card_congr AddMonoidHom.toMultiplicativeUnits,
    CommGroup.card_monoidHom_of_hasEnoughRootsOfUnity, Nat.card_congr Multiplicative.toAdd]

/-- Additive homomorphisms to `ZMod n` detect every nonzero element of an additive commutative
group killed by `n ≠ 0`. The group need not be finite. -/
theorem exists_addMonoidHom_zmod_apply_ne_zero (hM : ∀ x : M, n • x = 0) {a : M} (ha : a ≠ 0) :
    ∃ f : M →+ ZMod n, f a ≠ 0 := by
  let S := AddSubgroup.zmultiples a
  have hS : ∀ x : S, n • x = 0 := fun x => Subtype.ext (hM x)
  have : Finite S := (isOfFinAddOrder_iff_nsmul_eq_zero.2
    ⟨n, NeZero.pos n, hM a⟩).finite_zmultiples
  have := hasEnoughRootsOfUnity_multiplicative_zmod_exponent hS
  obtain ⟨φ, hφ⟩ := CommGroup.exists_apply_ne_one_of_hasEnoughRootsOfUnity (Multiplicative S)
    (Multiplicative (ZMod n)) (a := Multiplicative.ofAdd ⟨a, AddSubgroup.mem_zmultiples a⟩)
    (by simpa [← Subtype.coe_ne_coe] using ha)
  obtain ⟨f, hf⟩ := AddMonoidHom.exists_comp_eq_of_injective_of_baer (Module.Baer.zmod_self n) hM
    S.subtype_injective (AddMonoidHom.toMultiplicativeUnits.symm φ)
  refine ⟨f, fun h => hφ ?_⟩
  have := DFunLike.congr_fun hf ⟨a, AddSubgroup.mem_zmultiples a⟩
  simpa [h, ← Units.val_eq_one, ← toAdd_eq_zero] using this.symm

end TauCeti

/-- For `e : N ≃+ ZMod n` with `n ≠ 0`, a finite additive commutative group killed by `n` has
as many additive homomorphisms to `N` as elements. -/
theorem AddEquiv.natCard_addMonoidHom_zmod {N : Type*} [AddCommGroup N] (e : N ≃+ ZMod n)
    [Finite M] (hM : ∀ x : M, n • x = 0) : Nat.card (M →+ N) = Nat.card M := by
  rw [Nat.card_congr (AddEquiv.addMonoidHomCongrRight (M := M) e).toEquiv,
    TauCeti.natCard_addMonoidHom_zmod hM]

/-- For `e : N ≃+ ZMod n` with `n ≠ 0`, a finite `ℤ/n`-module has as many `ℤ/n`-linear maps to
`N` as elements. -/
theorem AddEquiv.natCard_linearMap_zmod {N : Type*} [AddCommGroup N] [Module (ZMod n) N]
    (e : N ≃+ ZMod n) [Module (ZMod n) M] [Finite M] :
    Nat.card (M →ₗ[ZMod n] N) = Nat.card M := by
  rw [← Nat.card_congr (AddMonoidHom.toZModLinearMapEquiv n).toEquiv,
    e.natCard_addMonoidHom_zmod fun x => by
      rw [← Nat.cast_smul_eq_nsmul (ZMod n), ZMod.natCast_self, zero_smul]]
