/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.EuclideanDomain.Int
public import Mathlib.Algebra.Module.Injective
public import Mathlib.RingTheory.PrincipalIdealDomain
public import TauCeti.Data.ZMod.Divisibility

/-!
# `ℤ/nℤ` is an injective module over itself

For `n ≠ 0` the ring `ℤ/nℤ` is self-injective: every `ℤ/nℤ`-linear map from an ideal of `ℤ/nℤ`
to `ℤ/nℤ` extends to the whole ring, which is Baer's criterion (`Module.Baer`) for the module
`ℤ/nℤ` over itself. Consequently `Hom(-, ℤ/nℤ)` is exact on the abelian groups killed by `n`, which
is what makes the dual `M ↦ Hom(M, ℤ/nℤ)` of a finite abelian group of exponent dividing `n` behave
like the dual of a vector space; the duality statements for the finite `ℤ/pⁱ[G]`-modules of a
profinite group rest on this.

The proof is the usual one, and adapts Mathlib's `Module.Baer.of_divisible`
(`Mathlib/Algebra/Category/Grp/Injective.lean`, Baer's criterion for a divisible group over `ℤ`)
from `ℤ` to `ℤ/nℤ`. An ideal of `ℤ/nℤ` is generated by one element `d`, and a linear map on it is
determined by the image `x` of `d`, which is killed by every `r` killing `d`. In `ℤ/nℤ` that forces
`d ∣ x` (`ZMod.dvd_of_forall_mul_eq_zero`, which replaces the division `DivisibleBy.div` of the
divisible case): if `g = gcd(d, n)`, then `n/g` kills `d`, hence `x`, so `g` divides `x`, and `g`
is a multiple of `d` by Bézout. Writing `x = d y`, the map `r ↦ r y` is the required extension. The
hypothesis `n ≠ 0` is necessary: `ℤ` is not injective over itself, since the map `2ℤ → ℤ`,
`2 ↦ 1`, does not extend.

## Main results

* `Module.Baer.zmod_self`: `ℤ/nℤ` satisfies Baer's criterion over itself, for `n ≠ 0`.
-/

public section

/-- **`ℤ/nℤ` is self-injective**, in the form of Baer's criterion: for `n ≠ 0`, every
`ZMod n`-linear map from an ideal of `ZMod n` to `ZMod n` extends to a linear map on `ZMod n`.
By `Module.Baer.extension_property`, every `ZMod n`-linear map into `ZMod n` then extends along
any injective linear map of `ZMod n`-modules. The proof follows Mathlib's `Module.Baer.of_divisible`
with `ZMod.dvd_of_forall_mul_eq_zero` in place of `DivisibleBy.div`. -/
theorem Module.Baer.zmod_self (n : ℕ) [NeZero n] : Module.Baer (ZMod n) (ZMod n) := by
  have : IsPrincipalIdealRing (ZMod n) :=
    IsPrincipalIdealRing.of_surjective (Int.castRingHom (ZMod n)) ZMod.intCast_surjective
  intro I g
  obtain ⟨d, rfl⟩ : ∃ d, I = Ideal.span {d} := ⟨_, (Ideal.span_singleton_generator I).symm⟩
  have hd : d ∈ Ideal.span {d} := Ideal.mem_span_singleton_self d
  -- the image of the generator is a multiple of the generator
  obtain ⟨y, hy⟩ : d ∣ g ⟨d, hd⟩ := ZMod.dvd_of_forall_mul_eq_zero fun r hr => by
    have : r • (⟨d, hd⟩ : Ideal.span {d}) = 0 := Subtype.ext (by simpa using hr)
    rw [← smul_eq_mul, ← map_smul, this, map_zero]
  refine ⟨LinearMap.toSpanSingleton (ZMod n) (ZMod n) y, fun r hr => ?_⟩
  obtain ⟨s, rfl⟩ := Ideal.mem_span_singleton'.1 hr
  have : (⟨s * d, hr⟩ : Ideal.span {d}) = s • ⟨d, hd⟩ := Subtype.ext (by simp)
  rw [this, map_smul, LinearMap.toSpanSingleton_apply, smul_eq_mul, smul_eq_mul, hy, mul_assoc]
