/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Basic
public import TauCeti.NumberTheory.Multiquadratic.MinusTwentyOne.Examples

/-!
# The genus field of `ℚ(√-21)`

The fundamental discriminant of `ℚ(√-21)` is `-84 = (-4) · (-3) · (-7)`. Its
prime-discriminant radicands are therefore `-1`, `-3`, and `-7`. This file identifies the
canonical prime-discriminant compositum with the explicit field

`ℚ(i, i√3, i√7) = ℚ(√-1, √-3, √-7)`.

Together with `TauCeti.Multiquadratic.isGenusField_candidateGenusField`, this proves that the
explicit compositum is the genus field of `ℚ(√-21)`. The relative degree over the quadratic
subfield generated by the product of the three roots is computed in
`TauCeti.NumberTheory.Multiquadratic.MinusTwentyOne.RelativeDegree`.

The prime-discriminant description follows D. A. Cox, *Primes of the Form x² + ny²*, Section
6.A, and F. Lemmermeyer, *Reciprocity Laws: From Euler to Eisenstein*, Section 2.2.

## Main results

* `TauCeti.Multiquadratic.genusPrimeDiscriminants_neg_twenty_one`: the canonical factors of
  the discriminant are `{-4, -3, -7}`.
* `TauCeti.Multiquadratic.candidateGenusField_neg_twenty_one_eq`: the canonical candidate genus
  field is the explicit compositum `ℚ(i, i√3, i√7)`.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

/-- The canonical prime-discriminant factorization of the fundamental discriminant of
`ℚ(√-21)` is `-84 = (-4) · (-3) · (-7)`. -/
@[simp] theorem genusPrimeDiscriminants_neg_twenty_one (hd : Squarefree (-21 : ℤ)) :
    genusPrimeDiscriminants hd = {-4, -3, -7} := by
  apply genusPrimeDiscriminants_eq hd
  · intro P hP
    fin_cases hP
    · exact isPrimeDiscriminant_neg_four
    · simpa [oddPrimeDiscriminant_of_mod_four_eq_three (by norm_num : 3 % 4 = 3)]
        using isPrimeDiscriminant_oddPrimeDiscriminant (p := 3) (by decide) (by decide)
    · simpa [oddPrimeDiscriminant_of_mod_four_eq_three (by norm_num : 7 % 4 = 3)]
        using isPrimeDiscriminant_oddPrimeDiscriminant (p := 7) (by decide) (by decide)
  · rw [Finset.prod_insert (by decide : (-4 : ℤ) ∉ ({-3, -7} : Finset ℤ)),
      Finset.prod_insert (by decide : (-3 : ℤ) ∉ ({-7} : Finset ℤ)),
      Finset.prod_singleton,
      fundamentalDiscriminant_of_mod_four_ne_one (by decide : (-21 : ℤ) % 4 ≠ 1)]
    ring

/-- **The genus-field compositum for `ℚ(√-21)`.** The canonical compositum of the square
roots of the prime-discriminant radicands is exactly
`ℚ(i, i√3, i√7) = ℚ(√-1, √-3, √-7)`.

The canonical roots and the displayed roots need not be definitionally equal, because the former
are chosen using algebraic closure. Their squares agree, so each differs from the corresponding
displayed root by at most a sign; adjoining either family therefore gives the same field. -/
@[simp] theorem candidateGenusField_neg_twenty_one_eq (hd : Squarefree (-21 : ℤ)) :
    candidateGenusField hd =
      (adjoin ℚ ({Complex.I, sqrtNegThree, sqrtNegSeven} : Set ℂ) : IntermediateField ℚ ℂ) := by
  let F : IntermediateField ℚ ℂ :=
    adjoin ℚ ({Complex.I, sqrtNegThree, sqrtNegSeven} : Set ℂ)
  have hfac : genusPrimeDiscriminants hd = {-4, -3, -7} :=
    genusPrimeDiscriminants_neg_twenty_one hd
  have mem_of_sq_eq (E : IntermediateField ℚ ℂ) {x y : ℂ}
      (hxy : x ^ 2 = y ^ 2) (hy : y ∈ E) : x ∈ E := by
    rcases sq_eq_sq_iff_eq_or_eq_neg.mp hxy with h | h
    · simpa [h] using hy
    · simpa [h] using E.neg_mem hy
  apply le_antisymm
  · rw [candidateGenusField_le_iff]
    intro P
    have hP : P.val ∈ ({-4, -3, -7} : Finset ℤ) := by
      rw [← hfac]
      exact P.property
    simp only [Finset.mem_insert, Finset.mem_singleton] at hP
    rcases hP with hP | hP | hP
    · apply mem_of_sq_eq F (y := Complex.I)
      · rw [genusFieldRoot_sq, hP]
        norm_num [primeDiscriminantRadicand, Complex.I_sq]
      · exact subset_adjoin ℚ _ (by simp)
    · apply mem_of_sq_eq F (y := sqrtNegThree)
      · rw [genusFieldRoot_sq, hP, sqrtNegThree_sq]
        norm_num [primeDiscriminantRadicand]
      · exact subset_adjoin ℚ _ (by simp)
    · apply mem_of_sq_eq F (y := sqrtNegSeven)
      · rw [genusFieldRoot_sq, hP, sqrtNegSeven_sq]
        norm_num [primeDiscriminantRadicand]
      · exact subset_adjoin ℚ _ (by simp)
  · rw [adjoin_le_iff]
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl | rfl
    · let P : {P // P ∈ genusPrimeDiscriminants hd} :=
        ⟨-4, by rw [hfac]; simp⟩
      apply mem_of_sq_eq (candidateGenusField hd)
        (x := Complex.I) (y := genusFieldRoot hd P)
      · rw [genusFieldRoot_sq]
        norm_num [P, primeDiscriminantRadicand, Complex.I_sq]
      · exact genusFieldRoot_mem_candidateGenusField hd P
    · let P : {P // P ∈ genusPrimeDiscriminants hd} :=
        ⟨-3, by rw [hfac]; simp⟩
      apply mem_of_sq_eq (candidateGenusField hd)
        (x := sqrtNegThree) (y := genusFieldRoot hd P)
      · rw [sqrtNegThree_sq, genusFieldRoot_sq]
        norm_num [P, primeDiscriminantRadicand]
      · exact genusFieldRoot_mem_candidateGenusField hd P
    · let P : {P // P ∈ genusPrimeDiscriminants hd} :=
        ⟨-7, by rw [hfac]; simp⟩
      apply mem_of_sq_eq (candidateGenusField hd)
        (x := sqrtNegSeven) (y := genusFieldRoot hd P)
      · rw [sqrtNegSeven_sq, genusFieldRoot_sq]
        norm_num [P, primeDiscriminantRadicand]
      · exact genusFieldRoot_mem_candidateGenusField hd P

end TauCeti.Multiquadratic
