/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.RationalSubset.Laurent.Basic
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.LaurentCover.Basic
public import Mathlib.CategoryTheory.Sites.Sieves.Basic

/-!
# The sieve of a finite Laurent cover

For a finite set `T ⊆ A` and an open `W` of `Spa(A, A⁺)`, `laurentSieve Aplus T W`
consists of the opens inside a piece of the Laurent cover of `W` generated by `T`.
The membership, empty-cover, pullback, and insert lemmas describe this sieve independently
of the sheaf condition. For unit generators, the Laurent sieve of all ratios refines the
standard rational sieve (`laurentSieve_mul_inverse_le_ofArrows_inf_spaBasicOpen`).

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Lemma 8.34(iii).
* S. Bosch, U. Güntzer, R. Remmert, *Non-Archimedean Analysis*, §8.2.2, Lemma 3.
-/

public section

open CategoryTheory TopologicalSpace TauCeti.Huber

namespace TauCeti.ValuationSpectrum

/-! ### The Laurent sieve -/

section Sieve

variable {A : Type*} [CommRing A] [UniformSpace A] (Aplus : Subring A)

/-- **The sieve of the Laurent cover** of an open `W ⊆ Spa(A, A⁺)` generated by a finite set `T`:
the opens `V ≤ W` on which every `t ∈ T` has a fixed sign, `V ≤ {|t| ≤ 1}` or `V ≤ {|t| ≥ 1}`
(`laurentCoverOpen Aplus t true` and `laurentCoverOpen Aplus t false`). Equivalently, these are
the opens `V ≤ W` contained in one of the pieces `laurentPiece Aplus (↑) J`, `J ⊆ T`, of the
Laurent cover (`laurentSieve_apply_iff_exists_laurentPiece`). -/
def laurentSieve (T : Finset A) (W : Opens ↥(spa Aplus)) : Sieve W where
  arrows V _ := ∀ t ∈ T, ∃ b, V ≤ laurentCoverOpen Aplus t b
  downward_closed hV g t ht := (hV t ht).imp fun _ h ↦ g.le.trans h

variable {Aplus}

/-- Membership in the Laurent sieve. -/
@[simp]
theorem laurentSieve_apply {T : Finset A} {W V : Opens ↥(spa Aplus)} (g : V ⟶ W) :
    laurentSieve Aplus T W g ↔ ∀ t ∈ T, ∃ b, V ≤ laurentCoverOpen Aplus t b :=
  Iff.rfl

/-- **The Laurent sieve of a finite family consists of the opens inside a piece of its Laurent
cover**: for a family `f : ι → A` indexed by a finite type, an open `V ≤ W` lies in the Laurent
sieve generated by the values of `f` exactly when it is contained in the piece
`laurentPiece Aplus f J` for some set `J ⊆ ι` of indices of sign `≥ 1`. -/
theorem laurentSieve_image_apply_iff_exists_laurentPiece [DecidableEq A] {ι : Type*} [Fintype ι]
    (f : ι → A) {W V : Opens ↥(spa Aplus)} (g : V ⟶ W) :
    laurentSieve Aplus (Finset.univ.image f) W g ↔
      ∃ J : Set ι, (V : Set ↥(spa Aplus)) ⊆ Subtype.val ⁻¹' laurentPiece Aplus f J := by
  classical
  simp_rw [val_preimage_laurentPiece_eq_iInter, Set.subset_iInter_iff, laurentSieve_apply,
    Finset.forall_mem_image, Finset.mem_univ, true_implies]
  constructor
  · intro h
    choose b hb using fun i ↦ @h i
    refine ⟨{i | b i = false}, fun i v hv ↦ ?_⟩
    have hv := mem_spaBasicOpen.mp (hb i hv)
    split_ifs with hi <;> simp_all
  · rintro ⟨J, hJ⟩ i
    refine ⟨decide (i ∉ J), fun v hv ↦ mem_spaBasicOpen.mpr ?_⟩
    have hv := hJ i hv
    split_ifs at hv with hiJ <;> simpa [hiJ] using hv

/-- **The Laurent sieve consists of the opens inside a piece of the Laurent cover**: an open
`V ≤ W` lies in `laurentSieve Aplus T W` exactly when it is contained in the piece
`laurentPiece Aplus (↑) J` for some set `J ⊆ T` of generators of sign `≥ 1`. -/
theorem laurentSieve_apply_iff_exists_laurentPiece {T : Finset A} {W V : Opens ↥(spa Aplus)}
    (g : V ⟶ W) : laurentSieve Aplus T W g ↔
      ∃ J : Set T, (V : Set ↥(spa Aplus)) ⊆ Subtype.val ⁻¹' laurentPiece Aplus (↑) J := by
  classical
  simpa using laurentSieve_image_apply_iff_exists_laurentPiece ((↑) : T → A) g

/-- The Laurent cover generated by the empty set is the trivial cover. -/
@[simp]
theorem laurentSieve_empty (W : Opens ↥(spa Aplus)) : laurentSieve Aplus ∅ W = ⊤ := by
  ext
  simp

/-- The Laurent sieve of `W` restricts to the Laurent sieve of any `V ≤ W`. -/
@[simp]
theorem laurentSieve_pullback (T : Finset A) {W V : Opens ↥(spa Aplus)} (g : V ⟶ W) :
    (laurentSieve Aplus T W).pullback g = laurentSieve Aplus T V :=
  Sieve.ext fun _ _ ↦ Iff.rfl

/-- On an open where `a` has a fixed sign, adding `a` to the generators does not change the Laurent
sieve. -/
theorem laurentSieve_insert_of_le [DecidableEq A] {T : Finset A} {a : A}
    {V : Opens ↥(spa Aplus)} {b : Bool} (h : V ≤ laurentCoverOpen Aplus a b) :
    laurentSieve Aplus (insert a T) V = laurentSieve Aplus T V := by
  ext Z g
  simp only [laurentSieve_apply, Finset.forall_mem_insert, and_iff_right_iff_imp]
  exact fun _ ↦ ⟨b, g.le.trans h⟩

end Sieve

/-- The Laurent sieve generated by all ratios of a nonempty finite set of units refines the
standard rational sieve on any open, as in Wedhorn's Lemma 8.34(iii). -/
theorem laurentSieve_mul_inverse_le_ofArrows_inf_spaBasicOpen
    {A : Type*} [CommRing A] [UniformSpace A] [DecidableEq A] {Aplus : Subring A}
    {T : Finset A} (hT : T.Nonempty) (hu : ∀ t ∈ T, IsUnit t) (W : Opens ↥(spa Aplus)) :
    laurentSieve Aplus
      (Finset.univ.image fun p : T × T ↦ (p.1 : A) * Ring.inverse (p.2 : A)) W ≤
        Sieve.ofArrows (fun t : T ↦ W ⊓ spaBasicOpen Aplus T t)
          fun _ ↦ homOfLE inf_le_left := by
  classical
  intro V g hg
  obtain ⟨J, hJ⟩ := (laurentSieve_image_apply_iff_exists_laurentPiece _ g).mp hg
  obtain ⟨t, ht, hsub⟩ := exists_rationalSubset_superset_laurentPiece_mul_inverse Aplus hT hu J
  exact ⟨W ⊓ spaBasicOpen Aplus T t,
    homOfLE (le_inf g.le fun v hv ↦ mem_spaBasicOpen.mpr (hsub (hJ hv))), homOfLE inf_le_left,
    Presieve.ofArrows.mk (⟨t, ht⟩ : T), rfl⟩

end TauCeti.ValuationSpectrum
