/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.F4.ShortRoot.DerivationGradeBlock00
public import TauCeti.Algebra.Lie.F4.ShortRoot.DerivationGradeBlock01
public import TauCeti.Algebra.Lie.F4.ShortRoot.DerivationGradeBlock02
public import TauCeti.Algebra.Lie.F4.ShortRoot.DerivationGradeBlock03
public import TauCeti.Algebra.Lie.F4.ShortRoot.DerivationGradeBlock04
public import TauCeti.Algebra.Lie.F4.ShortRoot.DerivationGradeBlock05
public import TauCeti.Algebra.Lie.F4.ShortRoot.DerivationGradeBlock06
public import TauCeti.Algebra.Lie.F4.ShortRoot.DerivationGradeBlock07
public import TauCeti.Algebra.Lie.F4.ShortRoot.DerivationGradeBlock08
public import TauCeti.Algebra.Lie.F4.ShortRoot.DerivationGradeBlock09
public import TauCeti.Algebra.Lie.F4.ShortRoot.DerivationGradeBlock10
public import TauCeti.Algebra.Lie.F4.ShortRoot.DerivationGradeBlock11
public import TauCeti.Algebra.Lie.F4.ShortRoot.DerivationZeroGrade

/-! # Classification of homogeneous type-F4 derivations -/

public section
namespace TauCeti.F4ShortRoot
open TauCeti.DynkinType
universe u
variable {R : Type u} [CommRing R] [CharP R 2]

/-- The homogeneous component through an entry is determined by the selected coordinates. -/
theorem eq_zero_of_isHomogeneous_entryDegree (i j : Fin 26)
    {X : Matrix (Fin 26) (Fin 26) R} (hX : IsDerivation X)
    (hhom : IsHomogeneous (entryDegree i j) X)
    (hq : ∀ p, quotientCoordinate p X = 0)
    (hi : ∀ a, X (idealRow a) (idealCol a) = 0) : X = 0 := by
  fin_cases i <;> fin_cases j
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock080 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock068 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock043 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock135 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock033 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock125 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock030 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock100 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock122 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock088 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock097 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock084 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock084 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock072 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock081 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock047 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock069 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock139 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock044 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock136 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock034 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock126 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock101 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock089 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock085 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock087 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock071 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock046 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock138 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock036 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock128 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock033 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock103 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock125 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock091 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock100 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock088 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock088 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock074 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock084 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock049 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock072 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock141 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock047 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock139 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock037 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock129 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock104 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock092 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock089 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock099 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock096 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock053 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock145 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock046 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock138 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock043 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock109 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock135 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock103 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock107 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock100 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock100 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock088 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock097 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock056 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock084 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock148 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock054 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock146 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock047 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock139 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock110 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock104 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock101 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock124 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock121 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock114 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock158 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock071 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock153 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock068 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock138 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock151 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock128 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock135 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock125 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock125 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock117 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock122 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock088 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock115 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock161 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock084 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock159 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock072 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock154 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock139 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock129 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock126 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock032 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock029 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock022 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock009 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock004 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock071 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock002 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock046 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock068 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock036 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock043 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock033 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock033 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock025 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock030 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock012 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock023 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock088 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock010 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock084 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock005 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock072 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock047 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock037 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock034 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock134 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock131 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock121 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock096 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock163 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock158 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock080 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock145 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock156 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock138 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock143 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock135 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock135 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock125 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock132 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock100 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock122 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock166 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock097 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock164 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock084 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock159 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock146 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock139 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock136 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock042 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock039 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock029 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock014 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock096 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock009 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock007 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock053 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock080 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock046 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock051 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock043 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock043 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock033 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock040 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock017 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock030 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock100 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock015 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock097 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock010 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock084 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock054 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock047 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock044 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock137 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock134 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock124 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock099 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock165 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock087 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock160 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock147 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock158 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock140 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock145 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock138 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock138 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock128 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock135 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock103 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock125 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock167 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock100 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock166 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock088 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock161 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock148 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock141 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock139 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock067 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock064 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock058 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock029 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock121 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock022 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock114 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock020 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock112 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock071 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock080 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock068 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock068 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock061 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock065 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock033 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock059 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock125 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock030 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock122 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock023 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock115 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock084 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock072 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock069 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock045 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock042 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock032 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock016 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock099 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock011 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock087 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock009 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock055 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock048 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock053 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock046 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock046 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock036 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock043 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock018 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock033 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock103 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock017 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock100 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock012 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock088 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock056 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock049 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock047 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock079 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock076 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock064 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock039 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock131 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock029 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock121 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock027 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock096 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock119 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock094 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock080 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock080 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock068 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock077 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock043 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock065 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock135 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock040 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock132 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock030 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock122 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock097 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock084 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock081 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock070 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock067 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock060 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock032 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock124 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock024 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock116 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock022 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock087 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock114 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock073 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock071 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock071 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock062 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock068 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock036 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock061 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock128 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock033 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock125 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock025 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock117 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock088 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock074 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock072 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock083 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock079 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock067 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock042 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock134 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock032 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock124 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock029 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock099 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock121 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock087 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock096 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock071 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock080 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock046 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock068 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock138 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock043 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock135 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock033 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock125 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock100 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock088 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock084 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock083 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock079 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock067 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock042 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock134 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock032 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock124 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock029 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock099 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock121 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock087 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock096 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock071 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock080 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock046 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock068 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock138 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock043 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock135 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock033 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock125 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock100 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock088 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock084 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock095 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock093 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock079 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock050 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock142 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock042 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock134 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock039 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock106 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock131 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock099 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock105 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock096 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock096 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock094 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock053 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock080 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock145 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock051 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock143 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock043 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock135 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock107 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock100 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock097 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock086 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock083 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock070 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock045 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock137 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock035 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock127 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock032 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock102 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock124 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock090 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock099 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock087 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock087 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock073 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock048 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock071 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock140 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock046 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock138 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock036 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock128 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock103 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock091 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock088 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock120 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock118 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock111 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock079 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock155 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock067 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock150 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock064 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock134 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock149 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock124 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock131 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock121 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock121 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock114 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock119 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock112 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock158 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock080 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock156 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock068 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock151 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock135 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock125 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock122 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock098 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock095 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock083 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock052 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock144 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock045 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock137 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock042 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock108 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock134 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock102 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock106 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock099 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock099 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock087 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock096 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock055 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock147 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock053 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock145 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock046 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock138 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock109 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock103 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock100 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock028 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock026 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock019 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock006 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock079 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock001 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock067 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock000 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock042 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock064 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock032 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock039 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock029 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock029 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock022 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock027 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock009 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock020 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock007 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock080 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock002 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock068 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock043 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock033 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock030 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock123 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock120 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock113 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock083 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock157 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock070 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock152 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock067 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock137 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock150 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock127 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock134 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock124 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock124 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock116 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock121 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock087 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock114 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock160 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock158 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock071 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock153 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock138 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock128 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock125 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock031 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock028 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock021 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock008 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock083 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock003 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock070 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock001 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock045 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock067 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock035 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock042 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock032 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock032 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock024 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock029 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock011 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock022 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock087 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock009 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock004 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock071 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock046 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock036 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock033 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock133 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock130 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock120 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock095 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock162 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock083 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock157 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock079 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock144 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock155 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock137 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock142 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock134 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock134 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock124 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock131 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock099 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock121 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock165 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock096 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock163 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock158 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock145 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock138 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock135 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock041 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock038 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock028 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock013 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock095 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock008 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock083 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock006 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock052 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock079 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock045 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock050 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock042 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock042 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock032 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock039 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock016 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock029 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock099 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock014 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock096 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock009 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock053 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock046 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock043 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock066 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock063 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock057 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock028 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock120 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock021 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock113 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock019 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock083 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock111 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock070 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock079 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock067 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock067 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock060 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock064 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock032 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock058 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock124 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock029 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock121 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock022 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock114 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock071 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock068 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock078 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock075 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock063 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock038 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock130 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock028 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock120 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock026 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock095 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock118 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock083 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock093 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock079 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock079 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock067 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock076 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock042 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock064 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock134 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock039 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock131 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock029 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock121 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock096 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock080 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock082 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock078 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock066 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock041 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock133 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock031 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock123 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock028 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock098 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock120 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock086 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock095 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock083 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock083 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock070 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock079 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock045 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock067 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock137 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock042 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock134 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock032 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock124 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock099 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_gradeBlock087 hX (by convert hhom using 1; decide +kernel) hq hi
  · exact eq_zero_of_isHomogeneous_zero hX (by convert hhom using 1; decide +kernel) hq hi

end TauCeti.F4ShortRoot
