/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Points
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Generated
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Borel

/-!
# Points of toral Kostant subsystems

For a set `S` of root indices, the closed group scheme `kostantToralSubsystemGroupScheme` is
generated inside `GLₙ` by the represented Kostant root subgroups indexed by `S` together with
the represented weight torus. This file identifies the corresponding formal inclusion on
algebra-valued points. Its point subgroup contains the selected root subgroups and the represented
torus, and hence contains their join.

Write `B_S(A)` for the pointwise subgroup generated by the root subgroups indexed by `S` and the
torus. After passing from automorphisms of the base-changed lattice to matrices in its chosen
basis, the main theorem gives

```text
B_S(A) ≤ kostantToralSubsystemPointsSubgroup(S, A).
```

Taking `S = Set.univ` places the full torus--elementary subgroup assembled in
`TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Borel` inside the points of the
assembled full carrier. Equality over an algebraically closed field is a separate generation
theorem and is not asserted here.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantToralSubsystemPointsSubgroup`: the algebra-valued
  points of a toral-subsystem carrier, viewed in `GLₙ`.
* `TauCeti.UniversalEnvelopingAlgebra.kostantToralSubsystemPointsSubgroup_mono`: inclusion of root
  index sets induces inclusion of the corresponding point subgroups.
* `TauCeti.UniversalEnvelopingAlgebra.kostantGeneratedPointsSubgroup_le_toralSubsystemPoints_univ`:
  the full root-generated point subgroup is contained in the full toral point subgroup.
* `TauCeti.UniversalEnvelopingAlgebra.kostantTorusMatrix_mem_toralSubsystemPoints`: every
  represented weight-torus point lies in each toral-subsystem carrier.
* `TauCeti.UniversalEnvelopingAlgebra.map_kostantTorusSubsystemSubgroup_le_toralSubsystemPoints`:
  each pointwise torus--root-subgroup join lies in the corresponding scheme's points.

## References

The construction is the pointwise face of the split torus and root-subgroup carrier in the
Chevalley--Demazure construction; see J. E. Humphreys, *Linear Algebraic Groups*, §26, and
R. W. Carter, *Simple Groups of Lie Type*, §§4.4 and 7.1. It advances "The
Chevalley--Demazure construction" and "Points over an algebraically closed field" targets in
Layer 9 of `TauCetiRoadmap/ReductiveGroups/README.md`.
-/

public section

open CategoryTheory TensorProduct WithConv

namespace TauCeti.UniversalEnvelopingAlgebra

universe u v w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type}
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (wt : Fin n → κ → ℤ)

section Finite

variable [Finite κ]

/-- The algebra-valued points of a toral Kostant subsystem, embedded in `GLₙ` through its
Hopf-ideal quotient presentation. -/
noncomputable def kostantToralSubsystemPointsSubgroup (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (A : Type v) [CommRing A] : Subgroup (Matrix.GeneralLinearGroup (Fin n) A) :=
  GeneralLinear.hopfIdealPointsSubgroup n
    (kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil) A

/-- The toral-subsystem points are the general-linear point subgroup cut out by the subsystem's
defining Hopf ideal. -/
theorem kostantToralSubsystemPointsSubgroup_def (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (A : Type v) [CommRing A] :
    kostantToralSubsystemPointsSubgroup e h ρ M hM b wt S hnil A =
      GeneralLinear.hopfIdealPointsSubgroup n
        (kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil) A := by
  rw [kostantToralSubsystemPointsSubgroup]

/-- Enlarging the selected root-index set enlarges the corresponding algebra-valued point
subgroup. -/
theorem kostantToralSubsystemPointsSubgroup_mono {S T : Set I}
    (hnil : ∀ i ∈ T, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (hST : S ⊆ T) (A : Type v) [CommRing A] :
    kostantToralSubsystemPointsSubgroup e h ρ M hM b wt S
        (fun i hi ↦ hnil i (hST hi)) A ≤
      kostantToralSubsystemPointsSubgroup e h ρ M hM b wt T hnil A := by
  simpa only [kostantToralSubsystemPointsSubgroup_def] using
    GeneralLinear.hopfIdealPointsSubgroup_le_of_le n
      (kostantToralSubsystemDefiningIdeal_anti e h ρ M hM b wt hnil hST) A

/-- Membership in the points of a toral subsystem is vanishing on its defining Hopf ideal. -/
@[simp]
theorem mem_kostantToralSubsystemPointsSubgroup_iff (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (A : Type v) [CommRing A] (g : Matrix.GeneralLinearGroup (Fin n) A) :
    g ∈ kostantToralSubsystemPointsSubgroup e h ρ M hM b wt S hnil A ↔
      ∀ x ∈ kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil,
        ((GeneralLinear.pointsMulEquiv (R := ℤ) n).symm g).ofConv x = 0 := by
  rw [kostantToralSubsystemPointsSubgroup_def]
  exact GeneralLinear.mem_hopfIdealPointsSubgroup_iff n
    (kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil) A g

/-- Adjoining the weight torus can only enlarge the algebra-valued point subgroup cut out by the
full root-generated defining ideal. -/
theorem kostantGeneratedPointsSubgroup_le_toralSubsystemPoints_univ
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (A : Type v) [CommRing A] :
    kostantGeneratedPointsSubgroup e h ρ M hM hnil b A ≤
      kostantToralSubsystemPointsSubgroup e h ρ M hM b wt Set.univ
        (fun i _ ↦ hnil i) A := by
  simpa only [kostantGeneratedPointsSubgroup_def, kostantToralSubsystemPointsSubgroup_def] using
    GeneralLinear.hopfIdealPointsSubgroup_le_of_le n
      (kostantToralSubsystemDefiningIdeal_univ_le_kostantGeneratedDefiningIdeal
        e h ρ M hM hnil b wt) A

/-- Every selected represented Kostant root-subgroup matrix belongs to the algebra-valued points
of the corresponding toral-subsystem carrier. -/
theorem kostantRootSubgroupMatrix_mem_toralSubsystemPoints (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (A : Type v) [CommRing A] (i : S)
    (q : HopfAlgebra.points (R := ℤ) (H := AdditiveGroup.coordinateHopfAlgebra ℤ)
      (CommAlgCat.of ℤ A)) :
    kostantRootSubgroupMatrix e h ρ M hM i.1 (hnil i.1 i.2) b q ∈
      kostantToralSubsystemPointsSubgroup e h ρ M hM b wt S hnil A := by
  rw [kostantToralSubsystemPointsSubgroup_def]
  exact kostantRootSubgroupMatrix_mem_hopfIdealPointsSubgroup e h ρ M hM b i.1
    (hnil i.1 i.2) (kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil)
    (kostantToralSubsystemDefiningIdeal_toIdeal_le_root_ker e h ρ M hM b wt S hnil i) A q

end Finite

section Fintype

variable [Fintype κ]

/-- Every represented weight-torus matrix is a point of every toral-subsystem carrier. -/
theorem kostantTorusMatrix_mem_toralSubsystemPoints (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (A : Type v) [CommRing A] (s : κ → Aˣ) :
    kostantTorusMatrix M b wt s ∈
      kostantToralSubsystemPointsSubgroup e h ρ M hM b wt S hnil A := by
  let p := (SplitTorus.pointsMulEquiv (R := ℤ) (A := A) (σ := κ)).symm s
  let q : HopfAlgebra.points
      (R := ℤ) (H := GeneralLinear.coordinateHopfAlgebra ℤ n) (CommAlgCat.of ℤ A) :=
    (CommHopfAlgCat.mapPointsFunctor
      (GeneralLinear.weightTorusCoordinateMap wt)).app (CommAlgCat.of ℤ A) p
  have hq_matrix :
      GeneralLinear.pointsMulEquiv n q = kostantTorusMatrix M b wt s := by
    dsimp only [q]
    rw [GeneralLinear.mapPointsFunctor_weightTorusCoordinateMap_app,
      GeneralLinear.pointsMulEquiv_diagonalTorusPoints, kostantTorusMatrix_apply]
    congr 1
    funext i
    rw [GeneralLinear.diagonalTorusCoordinates_pointsMap_weightCharacterMap
      wt (CommAlgCat.of ℤ A) p i]
    simp only [p, MulEquiv.apply_symm_apply]
  rw [kostantToralSubsystemPointsSubgroup_def, ← hq_matrix]
  exact GeneralLinear.pointsMulEquiv_mapPointsFunctor_mem_hopfIdealPointsSubgroup n
    (kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil)
    (GeneralLinear.weightTorusCoordinateMap wt)
    (kostantToralSubsystemDefiningIdeal_toIdeal_le_torus_ker e h ρ M hM b wt S hnil) A p

/-- After writing automorphisms in the basis `b`, the subgroup generated by a set of represented
root subgroups together with the weight torus lies in the points of the corresponding
toral-subsystem carrier. -/
theorem map_kostantTorusSubsystemSubgroup_le_toralSubsystemPoints
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (S : Set I) (A : Type v) [CommRing A] :
    (kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S (CommAlgCat.of ℤ A)).map
        (Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMulEquiv) ≤
      kostantToralSubsystemPointsSubgroup e h ρ M hM b wt S (fun i _ ↦ hnil i) A := by
  rw [Subgroup.map_le_iff_le_comap]
  apply (kostantTorusSubsystemSubgroup_le_iff e h ρ M hM hnil b wt).2
  constructor
  · intro i hi t
    rw [Subgroup.mem_comap]
    rw [basisMatrix_kostantRootSubgroupParam]
    exact kostantRootSubgroupMatrix_mem_toralSubsystemPoints e h ρ M hM b wt S
      (fun j _ ↦ hnil j) A ⟨i, hi⟩
      ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm t)
  · intro s
    rw [Subgroup.mem_comap]
    rw [basisMatrix_kostantTorusPoints]
    exact kostantTorusMatrix_mem_toralSubsystemPoints e h ρ M hM b wt S
      (fun i _ ↦ hnil i) A s

end Fintype

end TauCeti.UniversalEnvelopingAlgebra
