/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.WeightTorus
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.CommonKernel
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Scheme.Basic
public import TauCeti.AlgebraicGeometry.GroupScheme.ClosedSubgroup
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Basic

/-!
# Closed group schemes generated by root subsystems and the Kostant torus

Fix the represented Kostant root subgroups `xᵢ : 𝔾ₐ ⟶ GLₙ`, a represented split torus, and a set
`S` of root indices. This file constructs the closed subgroup scheme of `GLₙ` containing the split
torus and the root subgroups indexed by `S`. On coordinate Hopf algebras its defining ideal is the
largest Hopf ideal killed by the torus coordinate map and by every root coordinate map with index
in `S`.

The construction is monotone: an inclusion `S ⊆ T` induces a closed immersion from the carrier
generated by `S` into the carrier generated by `T`. The full toral closure is the `S = Set.univ`
case. Each selected root subgroup and the split torus factor through the new carrier, and the
root-subgroup factorization remains a closed immersion under the same root-step hypotheses used
for the full generated carrier; those results are collected in `ToralClosure.RootInSubsystem`.

When `S` is the set of positive roots, the points of this carrier contain the pointwise group
`kostantTorusSubsystemSubgroup` (see
`map_kostantTorusSubsystemSubgroup_le_toralSubsystemPoints`); equality is not asserted. That
pointwise group is solvable under the bounded-height and grading hypotheses together with the
Cartan-weight and torus-character hypotheses of `isSolvable_kostantTorusSubsystemSubgroup`. No
maximal-solvability or Borel assertion is made here; those geometric statements remain necessary
before this carrier can be used as the Borel component of a pinning.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantToralSubsystemDefiningIdeal`: the common-kernel Hopf
  ideal for the selected root subgroups and the torus.
* `TauCeti.UniversalEnvelopingAlgebra.le_kostantToralSubsystemDefiningIdeal_iff`: the universal
  property of that defining ideal.
* `TauCeti.UniversalEnvelopingAlgebra.kostantToralSubsystemGroupScheme`: the corresponding closed
  subgroup scheme of `GLₙ`.
* `TauCeti.UniversalEnvelopingAlgebra.kostantToralSubsystemMapOfSubset`: the closed immersion
  induced by an inclusion of index sets.
* `TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToToralSubsystem` and
  `TauCeti.UniversalEnvelopingAlgebra.kostantWeightTorusToToralSubsystem`: the selected root and
  torus factorizations.

## References

The construction is the scheme-theoretic positive-root-and-torus step in the construction of a
pinned Chevalley--Demazure group; see R. W. Carter, *Simple Groups of Lie Type*, §§8.2 and 8.5,
and J. E. Humphreys, *Linear Algebraic Groups*, §§26--28. It advances the pinning and explicit
Chevalley--Demazure group-scheme targets of Layer 9 of the reductive-groups roadmap. Milestone L0
of the CFSGStatement roadmap consumes that pinned carrier and its root-subgroup maps.

The factorization and closed-immersion arguments are adapted from the formal templates in
`TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Generated.Basic` and
`TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.RootInGenerated`.
-/

public section

open AlgebraicGeometry CategoryTheory

namespace TauCeti.UniversalEnvelopingAlgebra

universe u w

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type} [Finite κ]
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (wt : Fin n → κ → ℤ)

/-- The coordinate Hopf algebra receiving a selected root-subgroup or weight-torus generator
map. -/
private noncomputable def kostantToralSubsystemGeneratorCodomain (S : Set I)
    (j : Sum S Unit) : _root_.CommHopfAlgCat ℤ :=
  match j with
  | .inl _ => AdditiveGroup.coordinateHopfAlgebra ℤ
  | .inr _ => (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)).obj

/-- The family consisting of every selected root-subgroup coordinate map and the weight-torus
map. -/
private noncomputable def kostantToralSubsystemGeneratorMap (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (j : Sum S Unit) :
    GeneralLinear.coordinateHopfAlgebra ℤ n ⟶
      kostantToralSubsystemGeneratorCodomain (I := I) (κ := κ) S j :=
  match j with
  | .inl i => kostantRootSubgroupCoordinateMap e h ρ M hM i.1 (hnil i.1 i.2) b
  | .inr _ => GeneralLinear.weightTorusCoordinateMap wt

/-- The common-kernel Hopf ideal for the represented weight torus and the represented Kostant root
subgroups indexed by `S`. It is the largest Hopf ideal killed by the weight-torus coordinate map
and by every root-subgroup coordinate map with index in `S` (see
`le_kostantToralSubsystemDefiningIdeal_iff`). -/
noncomputable def kostantToralSubsystemDefiningIdeal (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)))) :
    HopfIdeal ℤ (GeneralLinear.coordinateHopfAlgebra ℤ n) :=
  CommHopfAlgCat.commonKernelHopfIdeal
    (kostantToralSubsystemGeneratorMap e h ρ M hM b wt S hnil)

/-- A Hopf ideal lies in the toral-subsystem defining ideal exactly when the torus coordinate map
and every selected root-subgroup coordinate map kill it. This is the coordinate universal
property of the generated closed subgroup scheme. -/
theorem le_kostantToralSubsystemDefiningIdeal_iff (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (J : HopfIdeal ℤ (GeneralLinear.coordinateHopfAlgebra ℤ n)) :
    J ≤ kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil ↔
      (∀ i (hi : i ∈ S), J.toIdeal ≤ RingHom.ker
        (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i hi) b).hom.toAlgHom.toRingHom) ∧
      J.toIdeal ≤ RingHom.ker
        (GeneralLinear.weightTorusCoordinateMap wt).hom.toAlgHom.toRingHom := by
  rw [kostantToralSubsystemDefiningIdeal, CommHopfAlgCat.le_commonKernelHopfIdeal_iff]
  constructor
  · intro hJ
    exact ⟨fun i hi ↦ hJ (.inl ⟨i, hi⟩), hJ (.inr ())⟩
  · rintro ⟨hroot, htorus⟩ (i | _)
    · exact hroot i.1 i.2
    · exact htorus

/-- Every selected root-subgroup coordinate map kills the toral-subsystem defining ideal. -/
theorem kostantToralSubsystemDefiningIdeal_toIdeal_le_root_ker (S : Set I)
    (hnil : ∀ j ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e j)))) (i : S) :
    (kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil).toIdeal ≤
      RingHom.ker
        (kostantRootSubgroupCoordinateMap e h ρ M hM i.1
          (hnil i.1 i.2) b).hom.toAlgHom.toRingHom :=
  CommHopfAlgCat.commonKernelHopfIdeal_toIdeal_le_ker
    (kostantToralSubsystemGeneratorMap e h ρ M hM b wt S hnil) (.inl i)

/-- The represented weight-torus coordinate map kills every toral-subsystem defining ideal. -/
theorem kostantToralSubsystemDefiningIdeal_toIdeal_le_torus_ker (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)))) :
    (kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil).toIdeal ≤
      RingHom.ker (GeneralLinear.weightTorusCoordinateMap wt).hom.toAlgHom.toRingHom :=
  CommHopfAlgCat.commonKernelHopfIdeal_toIdeal_le_ker
    (kostantToralSubsystemGeneratorMap e h ρ M hM b wt S hnil) (.inr ())

/-- Enlarging the root-index set shrinks the defining ideal, equivalently enlarging the generated
closed subgroup scheme. -/
theorem kostantToralSubsystemDefiningIdeal_anti {S T : Set I}
    (hnil : ∀ i ∈ T, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (hST : S ⊆ T) :
    kostantToralSubsystemDefiningIdeal e h ρ M hM b wt T hnil ≤
      kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S (fun i hi ↦ hnil i (hST hi)) := by
  rw [le_kostantToralSubsystemDefiningIdeal_iff]
  exact ⟨fun i hi ↦ kostantToralSubsystemDefiningIdeal_toIdeal_le_root_ker
      e h ρ M hM b wt T hnil ⟨i, hST hi⟩,
    kostantToralSubsystemDefiningIdeal_toIdeal_le_torus_ker e h ρ M hM b wt T hnil⟩

/-- The affine group scheme generated jointly by the represented weight torus and the root
subgroups indexed by `S`. -/
noncomputable abbrev kostantToralSubsystemGroupScheme (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)))) :
    Grp (Over (Spec (CommRingCat.of ℤ))) :=
  CommHopfAlgCat.quotientSpec (GeneralLinear.coordinateHopfAlgebra ℤ n)
    (kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil)

/-- The toral-subsystem carrier as a closed subgroup scheme of `GLₙ`. -/
noncomputable def kostantToralSubsystemGroupSchemeι (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)))) :
    kostantToralSubsystemGroupScheme e h ρ M hM b wt S hnil ⟶
      GeneralLinear.groupScheme ℤ n :=
  CommHopfAlgCat.quotientSpecι (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil) ≫
    eqToHom (GeneralLinear.groupScheme_def ℤ n).symm

/-- The inclusion of a toral-subsystem carrier is the quotient-spectrum inclusion transported
across the named presentation of `GLₙ`. -/
theorem kostantToralSubsystemGroupSchemeι_def (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)))) :
    kostantToralSubsystemGroupSchemeι e h ρ M hM b wt S hnil =
      CommHopfAlgCat.quotientSpecι (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil) ≫
        eqToHom (GeneralLinear.groupScheme_def ℤ n).symm := by
  rfl

/-- Every toral-subsystem carrier is a closed subgroup scheme of `GLₙ`. -/
instance isClosedImmersion_kostantToralSubsystemGroupSchemeι (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)))) :
    IsClosedImmersion
      (kostantToralSubsystemGroupSchemeι e h ρ M hM b wt S hnil).hom.hom.left := by
  rw [kostantToralSubsystemGroupSchemeι_def, CommHopfAlgCat.quotientSpecι_def]
  apply (CommHopfAlgCat.isClosedImmersion_hopfSpec_map_comp_eqToHom_iff
    (GeneralLinear.groupScheme_def ℤ n)
    (CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil))).mpr
  exact Ideal.Quotient.mkₐ_surjective ℤ
    (kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil).toIdeal

/-- An inclusion `S ⊆ T` induces the corresponding closed immersion between the generated
toral-subsystem carriers. -/
noncomputable def kostantToralSubsystemMapOfSubset {S T : Set I}
    (hnil : ∀ i ∈ T, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (hST : S ⊆ T) :
    kostantToralSubsystemGroupScheme e h ρ M hM b wt S (fun i hi ↦ hnil i (hST hi)) ⟶
      kostantToralSubsystemGroupScheme e h ρ M hM b wt T hnil :=
  CommHopfAlgCat.quotientSpecMapOfLe (GeneralLinear.coordinateHopfAlgebra ℤ n)
    (kostantToralSubsystemDefiningIdeal_anti e h ρ M hM b wt hnil hST)

/-- Every map induced by inclusion of root-index sets is a closed immersion. -/
instance isClosedImmersion_kostantToralSubsystemMapOfSubset {S T : Set I}
    (hnil : ∀ i ∈ T, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (hST : S ⊆ T) :
    IsClosedImmersion
      (kostantToralSubsystemMapOfSubset e h ρ M hM b wt hnil hST).hom.hom.left := by
  unfold kostantToralSubsystemMapOfSubset
  infer_instance

/-- The subsystem inclusion followed by the inclusion of the larger carrier into `GLₙ` is the
inclusion of the smaller carrier. -/
@[simp]
theorem kostantToralSubsystemMapOfSubset_comp_ι {S T : Set I}
    (hnil : ∀ i ∈ T, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (hST : S ⊆ T) :
    kostantToralSubsystemMapOfSubset e h ρ M hM b wt hnil hST ≫
        kostantToralSubsystemGroupSchemeι e h ρ M hM b wt T hnil =
      kostantToralSubsystemGroupSchemeι e h ρ M hM b wt S (fun i hi ↦ hnil i (hST hi)) := by
  rw [kostantToralSubsystemMapOfSubset, kostantToralSubsystemGroupSchemeι_def,
    kostantToralSubsystemGroupSchemeι_def, ← Category.assoc,
    CommHopfAlgCat.quotientSpecMapOfLe_comp_quotientSpecι]

/-- The map induced by a reflexive inclusion is the identity. -/
@[simp]
theorem kostantToralSubsystemMapOfSubset_refl (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)))) :
    kostantToralSubsystemMapOfSubset e h ρ M hM b wt hnil (Set.Subset.rfl : S ⊆ S) =
      𝟙 (kostantToralSubsystemGroupScheme e h ρ M hM b wt S hnil) := by
  rw [kostantToralSubsystemMapOfSubset]
  exact CommHopfAlgCat.quotientSpecMapOfLe_refl _ _

/-- Subsystem inclusions compose according to composition of inclusions. -/
@[simp]
theorem kostantToralSubsystemMapOfSubset_comp {S T U : Set I}
    (hnil : ∀ i ∈ U, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (hST : S ⊆ T) (hTU : T ⊆ U) :
    kostantToralSubsystemMapOfSubset e h ρ M hM b wt (fun i hi ↦ hnil i (hTU hi)) hST ≫
        kostantToralSubsystemMapOfSubset e h ρ M hM b wt hnil hTU =
      kostantToralSubsystemMapOfSubset e h ρ M hM b wt hnil (hST.trans hTU) := by
  rw [kostantToralSubsystemMapOfSubset, kostantToralSubsystemMapOfSubset,
    kostantToralSubsystemMapOfSubset]
  exact CommHopfAlgCat.quotientSpecMapOfLe_comp _ _ _

/-- The coordinate map through which a selected root subgroup factors into its toral-subsystem
carrier. -/
noncomputable def kostantRootSubgroupToralSubsystemCoordinateMap (S : Set I)
    (hnil : ∀ j ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e j)))) (i : S) :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
        (kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil) ⟶
      AdditiveGroup.coordinateHopfAlgebra ℤ :=
  CommHopfAlgCat.commonKernelLift
    (kostantToralSubsystemGeneratorMap e h ρ M hM b wt S hnil) (.inl i)

/-- Composing the quotient morphism with a selected factored root coordinate map recovers the
represented root-subgroup coordinate map. -/
@[simp]
theorem mkQuotient_comp_kostantRootSubgroupToralSubsystemCoordinateMap (S : Set I)
    (hnil : ∀ j ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e j)))) (i : S) :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil) ≫
        kostantRootSubgroupToralSubsystemCoordinateMap e h ρ M hM b wt S hnil i =
      kostantRootSubgroupCoordinateMap e h ρ M hM i.1 (hnil i.1 i.2) b :=
  CommHopfAlgCat.mkQuotient_comp_commonKernelLift
    (kostantToralSubsystemGeneratorMap e h ρ M hM b wt S hnil) (.inl i)

/-- A selected represented root subgroup, factored through its toral-subsystem carrier. -/
noncomputable def kostantRootSubgroupToToralSubsystem (S : Set I)
    (hnil : ∀ j ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e j)))) (i : S) :
    AdditiveGroup.groupScheme ℤ ⟶
      kostantToralSubsystemGroupScheme e h ρ M hM b wt S hnil :=
  eqToHom (AdditiveGroup.groupScheme_def ℤ) ≫
    (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
      (kostantRootSubgroupToralSubsystemCoordinateMap e h ρ M hM b wt S hnil i).op

/-- The selected root-subgroup morphism into a toral-subsystem carrier is the spectrum map of its
factored coordinate morphism, after the canonical identification of the additive group scheme. -/
theorem kostantRootSubgroupToToralSubsystem_def (S : Set I)
    (hnil : ∀ j ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e j)))) (i : S) :
    kostantRootSubgroupToToralSubsystem e h ρ M hM b wt S hnil i =
      eqToHom (AdditiveGroup.groupScheme_def ℤ) ≫
        (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
          (kostantRootSubgroupToralSubsystemCoordinateMap e h ρ M hM b wt S hnil i).op := by
  rw [kostantRootSubgroupToToralSubsystem]

/-- Factoring a selected root subgroup through its toral-subsystem carrier and then including
into `GLₙ` recovers the represented root-subgroup morphism. -/
@[simp]
theorem kostantRootSubgroupToToralSubsystem_comp_ι (S : Set I)
    (hnil : ∀ j ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e j)))) (i : S) :
    kostantRootSubgroupToToralSubsystem e h ρ M hM b wt S hnil i ≫
        kostantToralSubsystemGroupSchemeι e h ρ M hM b wt S hnil =
      kostantRootSubgroup e h ρ M hM i.1 (hnil i.1 i.2) b := by
  rw [kostantRootSubgroupToToralSubsystem, kostantToralSubsystemGroupSchemeι_def,
    CommHopfAlgCat.quotientSpecι_def, kostantRootSubgroup_def]
  slice_lhs 2 3 =>
    rw [← (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map_comp, ← op_comp,
      mkQuotient_comp_kostantRootSubgroupToralSubsystemCoordinateMap]

/-- Factoring a selected root subgroup is compatible with enlarging the selected index set. -/
@[simp]
theorem kostantRootSubgroupToToralSubsystem_comp_mapOfSubset {S T : Set I}
    (hnil : ∀ j ∈ T, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e j))))
    (hST : S ⊆ T) (i : S) :
    kostantRootSubgroupToToralSubsystem e h ρ M hM b wt S
          (fun j hj ↦ hnil j (hST hj)) i ≫
        kostantToralSubsystemMapOfSubset e h ρ M hM b wt hnil hST =
      kostantRootSubgroupToToralSubsystem e h ρ M hM b wt T hnil ⟨i.1, hST i.2⟩ := by
  apply (cancel_mono (kostantToralSubsystemGroupSchemeι e h ρ M hM b wt T hnil)).1
  rw [Category.assoc, kostantToralSubsystemMapOfSubset_comp_ι,
    kostantRootSubgroupToToralSubsystem_comp_ι,
    kostantRootSubgroupToToralSubsystem_comp_ι]

/-- The coordinate map through which the represented weight torus factors into a toral-subsystem
carrier. -/
noncomputable def kostantWeightTorusToralSubsystemCoordinateMap (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)))) :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
        (kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil) ⟶
      (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)).obj :=
  CommHopfAlgCat.commonKernelLift
    (kostantToralSubsystemGeneratorMap e h ρ M hM b wt S hnil) (.inr ())

/-- Composing the quotient morphism with the factored torus coordinate map recovers the represented
weight-torus coordinate map. -/
@[simp]
theorem mkQuotient_comp_kostantWeightTorusToralSubsystemCoordinateMap (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)))) :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantToralSubsystemDefiningIdeal e h ρ M hM b wt S hnil) ≫
        kostantWeightTorusToralSubsystemCoordinateMap e h ρ M hM b wt S hnil =
      GeneralLinear.weightTorusCoordinateMap wt :=
  CommHopfAlgCat.mkQuotient_comp_commonKernelLift
    (kostantToralSubsystemGeneratorMap e h ρ M hM b wt S hnil) (.inr ())

/-- The represented weight torus, factored through a toral-subsystem carrier. -/
noncomputable def kostantWeightTorusToToralSubsystem (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)))) :
    SplitTorus.groupScheme ℤ κ ⟶
      kostantToralSubsystemGroupScheme e h ρ M hM b wt S hnil :=
  eqToHom (DiagonalizableGroup.groupScheme_def ℤ (SplitTorus.characterGroup κ)) ≫
    (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
      (kostantWeightTorusToralSubsystemCoordinateMap e h ρ M hM b wt S hnil).op

/-- The weight-torus morphism into a toral-subsystem carrier is the spectrum map of its factored
coordinate morphism, after the canonical presentation of the split torus. -/
theorem kostantWeightTorusToToralSubsystem_def (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)))) :
    kostantWeightTorusToToralSubsystem e h ρ M hM b wt S hnil =
      eqToHom (DiagonalizableGroup.groupScheme_def ℤ (SplitTorus.characterGroup κ)) ≫
        (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
          (kostantWeightTorusToralSubsystemCoordinateMap e h ρ M hM b wt S hnil).op := by
  rw [kostantWeightTorusToToralSubsystem]

/-- Factoring the weight torus through a toral-subsystem carrier and then including into `GLₙ`
recovers the represented weight-torus morphism. -/
@[simp]
theorem kostantWeightTorusToToralSubsystem_comp_ι (S : Set I)
    (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)))) :
    kostantWeightTorusToToralSubsystem e h ρ M hM b wt S hnil ≫
        kostantToralSubsystemGroupSchemeι e h ρ M hM b wt S hnil =
      GeneralLinear.weightTorus (R := ℤ) wt := by
  rw [kostantWeightTorusToToralSubsystem, kostantToralSubsystemGroupSchemeι_def,
    CommHopfAlgCat.quotientSpecι_def, GeneralLinear.weightTorus_def]
  slice_lhs 2 3 =>
    rw [← (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map_comp, ← op_comp,
      mkQuotient_comp_kostantWeightTorusToralSubsystemCoordinateMap]

/-- The torus factorization is compatible with enlarging the selected root-index set. -/
@[simp]
theorem kostantWeightTorusToToralSubsystem_comp_mapOfSubset {S T : Set I}
    (hnil : ∀ i ∈ T, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (hST : S ⊆ T) :
    kostantWeightTorusToToralSubsystem e h ρ M hM b wt S (fun i hi ↦ hnil i (hST hi)) ≫
        kostantToralSubsystemMapOfSubset e h ρ M hM b wt hnil hST =
      kostantWeightTorusToToralSubsystem e h ρ M hM b wt T hnil := by
  apply (cancel_mono (kostantToralSubsystemGroupSchemeι e h ρ M hM b wt T hnil)).1
  rw [Category.assoc, kostantToralSubsystemMapOfSubset_comp_ι,
    kostantWeightTorusToToralSubsystem_comp_ι,
    kostantWeightTorusToToralSubsystem_comp_ι]

end TauCeti.UniversalEnvelopingAlgebra
