/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.InformationTheory.Coding.GeneratorParityCheck

/-!
# Removing redundant parity checks

A parity-check matrix may contain redundant equations. Deleting a row preserves its kernel
exactly when that row is in the span of the remaining rows. Thus a matrix has no redundant
checks exactly when its rows are linearly independent. Every given parity-check matrix admits
a submatrix with independent rows checking the same code; the number of retained checks is
the code's codimension.

The reduction retains actual rows of the input matrix, rather than choosing a new basis of
the dual code. The row indices are arbitrary finite types, and the alphabet is any field.

## Main results

* `Matrix.checkedBy_deleteRow_eq_iff` characterizes redundant checks.
* `Matrix.linearIndependent_rows_iff_forall_checkedBy_deleteRow_ne` characterizes matrices
  without redundant checks.
* `Matrix.exists_linearIndependent_checkedBy_submatrix` removes all redundant checks.
* `TauCeti.LinearCode.IsParityCheckMatrix.exists_submatrix` reduces a parity-check
  presentation to exactly one check per dimension of the dual code.

## References

* W. C. Huffman and V. Pless, *Fundamentals of Error-Correcting Codes*, Cambridge University
  Press, 2003, §§1.2–1.4.
-/

public section

namespace TauCeti

variable {F ι ρ : Type*} [Field F] [Fintype ι]

/-- Deleting a check can only enlarge the checked code. -/
theorem _root_.Matrix.checkedBy_le_deleteRow (H : Matrix ρ ι F) (r : ρ) :
    H.checkedBy ≤ (H.deleteRow r).checkedBy := by
  intro x hx
  rw [Matrix.mem_checkedBy_iff] at hx ⊢
  ext s
  simpa [Matrix.mulVec_apply] using congrFun hx s.val

open scoped Classical in
/-- Deleting a check preserves the checked code exactly when its row is generated by the
remaining rows. -/
theorem _root_.Matrix.checkedBy_deleteRow_eq_iff [Fintype ρ]
    (H : Matrix ρ ι F) (r : ρ) :
    (H.deleteRow r).checkedBy = H.checkedBy ↔
      H.row r ∈ (H.deleteRow r).generatedBy := by
  rw [Matrix.checkedBy_eq_iff_generatedBy_eq, Matrix.generatedBy_deleteRow_eq_iff]

/-- A matrix has independent rows exactly when deleting any single check changes its kernel. -/
theorem _root_.Matrix.linearIndependent_rows_iff_forall_checkedBy_deleteRow_ne
    [Finite ρ] (H : Matrix ρ ι F) :
    LinearIndependent F H.row ↔ ∀ r, (H.deleteRow r).checkedBy ≠ H.checkedBy := by
  classical
  let _ := Fintype.ofFinite ρ
  rw [linearIndependent_iff_notMem_span]
  apply forall_congr'
  intro r
  rw [ne_eq, Matrix.checkedBy_deleteRow_eq_iff, Matrix.generatedBy_eq_span_rows]
  have hrange : H.row '' (Set.univ \ {r}) = Set.range (H.deleteRow r).row := by
    rw [← Set.compl_eq_univ_sdiff, Set.image_eq_range]
    congr 1
    funext s
    exact (H.row_deleteRow r s).symm
  rw [hrange]

open scoped Classical in
/-- Deleting a redundant row of a parity-check matrix leaves a parity-check matrix for the
same code. -/
theorem LinearCode.IsParityCheckMatrix.deleteRow [Fintype ρ]
    {C : LinearCode F ι}
    {H : Matrix ρ ι F} (hH : C.IsParityCheckMatrix H) (r : ρ)
    (hr : H.row r ∈ (H.deleteRow r).generatedBy) :
    C.IsParityCheckMatrix (H.deleteRow r) := by
  rw [LinearCode.isParityCheckMatrix_def, (H.checkedBy_deleteRow_eq_iff r).mpr hr]
  exact (LinearCode.isParityCheckMatrix_def C H).mp hH

/-- A dependent row family has a check that can be deleted without changing the checked code. -/
theorem _root_.Matrix.exists_deleteRow_checkedBy_eq_of_not_linearIndependent
    [Finite ρ] (H : Matrix ρ ι F) (hH : ¬LinearIndependent F H.row) :
    ∃ r, (H.deleteRow r).checkedBy = H.checkedBy := by
  simpa only [H.linearIndependent_rows_iff_forall_checkedBy_deleteRow_ne, not_forall,
    not_not] using hH

/-- Every matrix has a submatrix with independent rows checking the same code. -/
theorem _root_.Matrix.exists_linearIndependent_checkedBy_submatrix [Finite ρ]
    (H : Matrix ρ ι F) :
    ∃ s : Finset ρ, LinearIndependent F (H.submatrix ((↑) : s → ρ) id).row ∧
      (H.submatrix ((↑) : s → ρ) id).checkedBy = H.checkedBy := by
  classical
  let _ := Fintype.ofFinite ρ
  obtain ⟨s, hs, hspan⟩ := H.exists_linearIndependent_generatedBy_submatrix
  exact ⟨s, hs, Matrix.checkedBy_eq_of_generatedBy_eq hspan⟩

/-- A given parity-check presentation can be reduced by retaining an independent set of
exactly `length - dimension` rows. -/
theorem LinearCode.IsParityCheckMatrix.exists_submatrix [Finite ρ] {C : LinearCode F ι}
    {H : Matrix ρ ι F} (hH : C.IsParityCheckMatrix H) :
    ∃ s : Finset ρ, LinearIndependent F (H.submatrix ((↑) : s → ρ) id).row ∧
      C.IsParityCheckMatrix (H.submatrix ((↑) : s → ρ) id) ∧
      s.card = Fintype.card ι - Module.finrank F C := by
  obtain ⟨s, hs, hker⟩ := H.exists_linearIndependent_checkedBy_submatrix
  have hcheck : C.IsParityCheckMatrix (H.submatrix ((↑) : s → ρ) id) := by
    rw [LinearCode.isParityCheckMatrix_def, hker]
    exact (LinearCode.isParityCheckMatrix_def C H).mp hH
  refine ⟨s, hs, hcheck, ?_⟩
  simpa only [Fintype.card_coe] using
    LinearCode.card_eq_card_sub_finrank_of_isParityCheckMatrix_of_linearIndependent hcheck hs

end TauCeti
