/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Global.RayClass.Integral

import TauCeti.NumberTheory.NumberField.NarrowClassGroup.CoprimeRepresentative

/-!
# The exact sequence from ray classes to ordinary ideal classes

For a modulus `m` of a number field `K`, forgetting its congruence and sign conditions sends a ray
class to an ordinary ideal class.  This file constructs that homomorphism and proves the exact tail

`primeToSubgroup m → RayClassGroup m → ClassGroup (RingOfIntegers K) → 1`.

The first map sends an element of `Kˣ` that is a unit at the finite part to the ray class of its
principal ideal.  The second map is surjective, and its kernel is exactly the range of the first.
The surjectivity proof chooses an integral representative coprime to the finite part; this is the
same moving argument that ensures every ordinary ideal class has a representative on which a ray
class can be evaluated.

This is the right-hand part of the ray-class exact sequence.  The left-hand part further presents
the kernel as residue units and signs modulo the image of the integer units, and yields the ray
class-number formula.

## Main definitions

* `TauCeti.GlobalNumberFields.principalRayClass`: the ray class of a principal fractional ideal
  whose generator is a unit at the finite part.
* `TauCeti.GlobalNumberFields.rayClassToClassGroup`: the ordinary ideal class underlying a ray
  class.

## Main results

* `TauCeti.GlobalNumberFields.rayClassToClassGroup_surjective`: every ordinary ideal class lifts
  to a ray class.
* `TauCeti.GlobalNumberFields.ker_rayClassToClassGroup`: the kernel consists exactly of ray
  classes of principal ideals generated by elements in `primeToSubgroup m`.
* `TauCeti.GlobalNumberFields.mulExact_principalRayClass_rayClassToClassGroup`: the corresponding
  multiplicative exactness statement.
* `TauCeti.GlobalNumberFields.classMap_one_surjective`: transition to the trivial modulus is
  surjective.

## References

* J. Neukirch, *Algebraic Number Theory*, Chapter VI, §1.
* S. Lang, *Algebraic Number Theory*, Chapter VI, §1.
-/

public section

open IsDedekindDomain NumberField
open scoped nonZeroDivisors NumberField

namespace TauCeti.GlobalNumberFields

variable {K : Type*} [Field K] [NumberField K]

/-- The ray class of the principal ideal generated by an element that is a unit at every prime
dividing the finite part of `m`. -/
noncomputable def principalRayClass (m : Modulus K) :
    primeToSubgroup m →* RayClassGroup m :=
  (rayClassMk m).comp (principalIdealPrimeTo m)

/-- The principal ray class is represented by the corresponding principal fractional ideal. -/
@[simp] theorem principalRayClass_apply (m : Modulus K) (x : primeToSubgroup m) :
    principalRayClass m x = rayClassMk m (principalIdealPrimeTo m x) :=
  (rfl)

/-- A generator congruent to one modulo `m` has trivial principal ray class. -/
theorem principalRayClass_eq_one_of_isCongrOne {m : Modulus K} {x : primeToSubgroup m}
    (hx : IsCongrOne m (x : Kˣ)) : principalRayClass m x = 1 := by
  rw [principalRayClass_apply, rayClassMk_eq_one_iff, mem_ray_iff]
  exact ⟨(x : Kˣ), hx, coe_principalIdealPrimeTo m x |>.symm⟩

/-- The map from a ray class to its underlying ordinary ideal class. -/
noncomputable def rayClassToClassGroup (m : Modulus K) :
    RayClassGroup m →* ClassGroup (RingOfIntegers K) :=
  rayClassLift (idealsPrimeToClassGroup m) fun I hI ↦ by
    rw [MonoidHom.mem_ker]
    obtain ⟨x, _, hx⟩ := mem_ray_iff.mp hI
    rw [idealsPrimeToClassGroup_apply, ← hx]
    exact ClassGroup.mk_toPrincipalIdeal x

/-- The ordinary class underlying the ray class of a fractional ideal is its usual ideal class. -/
@[simp] theorem rayClassToClassGroup_rayClassMk (m : Modulus K) (I : idealsPrimeTo m) :
    rayClassToClassGroup m (rayClassMk m I) =
      ClassGroup.mk K (I : (FractionalIdeal (RingOfIntegers K)⁰ K)ˣ) := by
  rw [rayClassToClassGroup, rayClassLift_rayClassMk, idealsPrimeToClassGroup_apply]

/-- Forgetting the modulus agrees with transition to the trivial modulus followed by the canonical
identification of its ray class group with the ordinary class group. -/
theorem rayClassToClassGroup_eq_oneEquivClassGroup_comp_classMap (m : Modulus K) :
    rayClassToClassGroup m =
      oneEquivClassGroup.toMonoidHom.comp (classMap (Modulus.one_dvd m)) := by
  refine MonoidHom.ext fun c ↦ ?_
  obtain ⟨I, rfl⟩ := rayClassMk_surjective m c
  rw [rayClassToClassGroup_rayClassMk, MonoidHom.comp_apply, classMap_rayClassMk,
    MulEquiv.coe_toMonoidHom, oneEquivClassGroup_rayClassMk,
    NumberFieldArithmetic.coe_idealsAwayInclusion]

/-- Every ordinary ideal class is represented by a ray class. -/
theorem rayClassToClassGroup_surjective (m : Modulus K) :
    Function.Surjective (rayClassToClassGroup m) := by
  intro C
  obtain ⟨D, hDC⟩ := NarrowClassGroup.toClassGroup_surjective C
  let M : (Ideal (RingOfIntegers K))⁰ :=
    ⟨m.finitePart, mem_nonZeroDivisors_iff_ne_zero.mpr m.finitePart_ne_zero⟩
  obtain ⟨J, hJD, hcop⟩ := NarrowClassGroup.exists_mk0_eq_and_isCoprime D M
  have hJ0 : (J : Ideal (RingOfIntegers K)) ≠ ⊥ := by
    simpa only [Ideal.zero_eq_bot] using mem_nonZeroDivisors_iff_ne_zero.mp J.2
  have hJmem : (J : Ideal (RingOfIntegers K)) ∈ integralIdealsPrimeTo m :=
    Modulus.mem_integralIdealsPrimeTo.mpr <|
      Modulus.isCoprimeTo_iff_sup_eq_top.mpr
        ⟨hJ0, Ideal.isCoprime_iff_sup_eq.mp hcop⟩
  let I : integralIdealsPrimeTo m := ⟨J, hJmem⟩
  refine ⟨idealClass m I, ?_⟩
  rw [idealClass_apply, rayClassToClassGroup_rayClassMk]
  calc
    ClassGroup.mk K
        (NumberFieldArithmetic.integralIdealsAwayHom m.support I :
          (FractionalIdeal (RingOfIntegers K)⁰ K)ˣ) =
        ClassGroup.mk K (FractionalIdeal.mk0 K J) := by
      congr 1
      exact Units.ext (NumberFieldArithmetic.coe_integralIdealsAwayHom m.support I)
    _ = ClassGroup.mk0 J := ClassGroup.mk_mk0 K J
    _ = NarrowClassGroup.toClassGroup (NarrowClassGroup.mk0 J) :=
      (NarrowClassGroup.toClassGroup_mk0 J).symm
    _ = C := by rw [hJD, hDC]

/-- The ray classes with trivial ordinary ideal class are exactly the principal ray classes.  This
is exactness at `RayClassGroup m` in the ray-class exact sequence. -/
theorem ker_rayClassToClassGroup (m : Modulus K) :
    (rayClassToClassGroup m).ker = (principalRayClass m).range := by
  ext c
  rw [MonoidHom.mem_ker, MonoidHom.mem_range]
  constructor
  · intro hc
    obtain ⟨I, rfl⟩ := rayClassMk_surjective m c
    rw [rayClassToClassGroup_rayClassMk] at hc
    have hI : I ∈ (principalIdealPrimeTo m).range := by
      rw [range_principalIdealPrimeTo, MonoidHom.mem_ker, idealsPrimeToClassGroup_apply]
      exact hc
    obtain ⟨x, hx⟩ := hI
    exact ⟨x, by rw [principalRayClass_apply, hx]⟩
  · rintro ⟨x, rfl⟩
    rw [principalRayClass_apply, rayClassToClassGroup_rayClassMk,
      coe_principalIdealPrimeTo, ClassGroup.mk_toPrincipalIdeal]

/-- The principal-ray-class map followed by forgetting the modulus is exact. -/
theorem mulExact_principalRayClass_rayClassToClassGroup (m : Modulus K) :
    Function.MulExact (principalRayClass m) (rayClassToClassGroup m) :=
  MonoidHom.mulExact_iff.mpr (ker_rayClassToClassGroup m)

/-- Transition from a modulus to the trivial modulus is surjective. -/
theorem classMap_one_surjective (m : Modulus K) :
    Function.Surjective (classMap (Modulus.one_dvd m)) := by
  intro c
  obtain ⟨d, hd⟩ := rayClassToClassGroup_surjective m (oneEquivClassGroup c)
  refine ⟨d, oneEquivClassGroup.injective ?_⟩
  rw [← hd]
  have h := DFunLike.congr_fun
    (rayClassToClassGroup_eq_oneEquivClassGroup_comp_classMap m) d
  simpa only [MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom] using h.symm

end TauCeti.GlobalNumberFields
