/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Global.RayClass.Integral

/-!
# The ideals of a ray class, through the generators of their complements

Fix a modulus `𝔪` of a number field `K` and an auxiliary nonzero integral ideal `𝔞` prime to `𝔪`.
An integral ideal `J` prime to `𝔪` satisfies `idealClass 𝔪 𝔞 * idealClass 𝔪 J = 1` exactly when
the integral ideal `𝔞 · J` is generated by an algebraic integer congruent to one modulo `𝔪`; such
a generator lies in `𝔞`, and conversely every element of `𝔞` congruent to one modulo `𝔪` arises
this way, from a single ideal `J`.

So, for a ray class `c`, choosing `𝔞` in the class `c⁻¹` turns the ideals of the class `c` into
the elements of

`rayGenerators 𝔪 𝔞 = {a ∈ 𝔞 | a is congruent to one modulo 𝔪}`,

counted up to multiplication by the units of `𝓞 K` congruent to one modulo `𝔪`.  The two
directions of that correspondence are `idealClass_eq_iff_exists_mem_rayGenerators` and
`existsUnique_mul_eq_span_singleton_of_mem_rayGenerators`, and its fibres are identified by
`span_singleton_eq_span_singleton_iff_exists_mem_unitsCongruenceSubgroup`.
Together they replace the ideals of a fixed ray class by the algebraic integers of `𝔞` subject to
a congruence.  Taking `𝔞 = ⊤` recovers the integral triviality criterion
`idealClass_eq_one_iff_exists_isCongrOne_span_eq`, so what is proved here is that criterion with
the trivial class replaced by an arbitrary one; every statement stays in the language of moduli,
`idealClass` and `unitsCongruenceSubgroup`.  A count of the ideals of a fixed ray class is the
intended consumer.

The auxiliary ideal cannot be dispensed with: an arbitrary ideal in a nontrivial ray class need
not be principal.  Multiplying by the auxiliary inverse-class ideal makes the product principal
with a generator congruent to one.  Such an auxiliary ideal always exists, by the moving lemma
`idealClass_surjective` together with `exists_idealClass_mul_eq_one`.

## Main definitions

* `TauCeti.GlobalNumberFields.rayGenerators`: the elements of an ideal whose image in `Kˣ` is
  congruent to one modulo the modulus.

## Main results

* `TauCeti.GlobalNumberFields.rayGenerators_nonempty`: an ideal prime to `𝔪` contains such an
  element.
* `TauCeti.GlobalNumberFields.mul_mem_rayGenerators`: the units of `𝓞 K` congruent to one modulo
  `𝔪` act on those elements.
* `TauCeti.GlobalNumberFields.idealClass_mul_eq_one_iff_exists_mem_rayGenerators`, and its form
  `TauCeti.GlobalNumberFields.idealClass_eq_iff_exists_mem_rayGenerators` for a fixed ray class:
  the ideals whose class inverts that of `𝔞` are exactly the complements of the generators.
* `TauCeti.GlobalNumberFields.existsUnique_mul_eq_span_singleton_of_mem_rayGenerators`: each
  generator has exactly one complementary ideal, and it is prime to `𝔪`.
* `span_singleton_eq_span_singleton_iff_exists_mem_unitsCongruenceSubgroup`:
  two elements congruent to one span the same ideal exactly when they differ by a unit congruent
  to one.

## References

* J. Neukirch, *Algebraic Number Theory*, Chapter VI, §1.
* S. Lang, *Algebraic Number Theory*, Chapter VI, §3, where the same correspondence precedes the
  count of the ideals of bounded norm in a ray class.
-/

public section

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum NumberField
open scoped nonZeroDivisors NumberField

namespace TauCeti.GlobalNumberFields

variable {K : Type*} [Field K] [NumberField K]

/-! ### The generators attached to an ideal and a modulus -/

/-- The elements of the ideal `𝔞` whose image in `Kˣ` is congruent to one modulo `𝔪`.  Asking for
a preimage in `Kˣ` rather than for a separate nonvanishing hypothesis is what makes `IsCongrOne`,
a predicate on `Kˣ`, available. -/
def rayGenerators (𝔪 : Modulus K) (𝔞 : Ideal (𝓞 K)) : Set (𝓞 K) :=
  {a | a ∈ 𝔞 ∧ ∃ x : Kˣ, (x : K) = a ∧ IsCongrOne 𝔪 x}

@[simp] theorem mem_rayGenerators {𝔪 : Modulus K} {𝔞 : Ideal (𝓞 K)} {a : 𝓞 K} :
    a ∈ rayGenerators 𝔪 𝔞 ↔ a ∈ 𝔞 ∧ ∃ x : Kˣ, (x : K) = a ∧ IsCongrOne 𝔪 x :=
  Iff.rfl

theorem ne_zero_of_mem_rayGenerators {𝔪 : Modulus K} {𝔞 : Ideal (𝓞 K)} {a : 𝓞 K}
    (ha : a ∈ rayGenerators 𝔪 𝔞) : a ≠ 0 := by
  obtain ⟨-, x, hxa, -⟩ := ha
  exact fun h ↦ x.ne_zero (by rw [hxa, h]; simp)

/-- **An ideal prime to the modulus has a generator-candidate.**  This is
`exists_mem_isCongrOne` in the language of `rayGenerators`, and it is what makes the count of
`rayGenerators 𝔪 𝔞` a count in a nonempty congruence-and-sign locus. -/
theorem rayGenerators_nonempty {𝔪 : Modulus K} {𝔞 : Ideal (𝓞 K)}
    (h𝔞 : 𝔞 ∈ integralIdealsPrimeTo 𝔪) : (rayGenerators 𝔪 𝔞).Nonempty := by
  obtain ⟨hbot, hsup⟩ :=
    Modulus.isCoprimeTo_iff_sup_eq_top.mp (Modulus.mem_integralIdealsPrimeTo.mp h𝔞)
  obtain ⟨a, x, ha𝔞, hxa, hx⟩ := exists_mem_isCongrOne hbot hsup
  exact ⟨a, ha𝔞, x, hxa, hx⟩

/-- **The units congruent to one act on the generators.**  This is the action whose orbits the
correspondence with ideals collapses; see
`span_singleton_eq_span_singleton_iff_exists_mem_unitsCongruenceSubgroup`. -/
theorem mul_mem_rayGenerators {𝔪 : Modulus K} {𝔞 : Ideal (𝓞 K)} {a : 𝓞 K} {u : (𝓞 K)ˣ}
    (hu : u ∈ unitsCongruenceSubgroup 𝔪) (ha : a ∈ rayGenerators 𝔪 𝔞) :
    (u : 𝓞 K) * a ∈ rayGenerators 𝔪 𝔞 := by
  obtain ⟨ha𝔞, x, hxa, hx⟩ := ha
  refine ⟨Ideal.mul_mem_left _ _ ha𝔞, Units.map (algebraMap (𝓞 K) K).toMonoidHom u * x, ?_, ?_⟩
  · rw [Units.val_mul, hxa, Units.coe_map]
    simp
  · exact mem_congruenceSubgroup.mp ((congruenceSubgroup 𝔪).mul_mem
      (mem_congruenceSubgroup.mpr (mem_unitsCongruenceSubgroup.mp hu))
      (mem_congruenceSubgroup.mpr hx))

/-! ### The correspondence with the ideals of a ray class -/

/-- **The complementary ideal of a generator.**  An element `a` of `𝔞` congruent to one modulo `𝔪`
has exactly one integral ideal `J` with `𝔞 · J = (a)`, and that ideal is again prime to `𝔪`:
`a` is a unit at every prime dividing the finite part, so no such prime divides `J`. -/
theorem existsUnique_mul_eq_span_singleton_of_mem_rayGenerators {𝔪 : Modulus K}
    {𝔞 : Ideal (𝓞 K)} {a : 𝓞 K} (ha : a ∈ rayGenerators 𝔪 𝔞) :
    ∃! J : integralIdealsPrimeTo 𝔪, 𝔞 * (J : Ideal (𝓞 K)) = Ideal.span {a} := by
  have h𝔞 : 𝔞 ≠ ⊥ := fun h ↦
    ne_zero_of_mem_rayGenerators ha (by simpa [h] using ha.1)
  obtain ⟨ha𝔞, x, hxa, hx⟩ := ha
  obtain ⟨J, hJ⟩ := Ideal.dvd_iff_le.mpr ((Ideal.span_singleton_le_iff_mem (I := 𝔞)).mpr ha𝔞)
  refine ⟨⟨J, Modulus.mem_integralIdealsPrimeTo.mpr (Modulus.isCoprimeTo_of_dvd_span_singleton
    hxa hx ⟨𝔞, by rw [hJ, mul_comm]⟩)⟩, hJ.symm, fun J' hJ' ↦ ?_⟩
  exact Subtype.ext (mul_left_cancel₀ h𝔞 (hJ'.trans hJ))

/-- **The ideals inverting the class of `𝔞` are the complements of its generators.**  One
direction is the integral triviality criterion `idealClass_eq_one_iff_exists_isCongrOne_span_eq`
applied to the product `𝔞 · J`, whose generator automatically lies in `𝔞`; the other is
`idealClass_mul_eq_one_of_span_eq_mul`. -/
theorem idealClass_mul_eq_one_iff_exists_mem_rayGenerators {𝔪 : Modulus K}
    (𝔞 J : integralIdealsPrimeTo 𝔪) :
    idealClass 𝔪 𝔞 * idealClass 𝔪 J = 1 ↔
      ∃ a ∈ rayGenerators 𝔪 (𝔞 : Ideal (𝓞 K)),
        (𝔞 : Ideal (𝓞 K)) * (J : Ideal (𝓞 K)) = Ideal.span {a} := by
  refine ⟨fun h ↦ ?_, ?_⟩
  · rw [← map_mul, idealClass_eq_one_iff_exists_isCongrOne_span_eq] at h
    obtain ⟨a, x, hxa, hx, ha⟩ := h
    rw [Submonoid.coe_mul] at ha
    exact ⟨a, ⟨Ideal.mul_le_left (ha ▸ Ideal.mem_span_singleton_self a), x, hxa, hx⟩, ha.symm⟩
  · rintro ⟨a, ⟨-, x, hxa, hx⟩, hJ⟩
    exact idealClass_mul_eq_one_of_span_eq_mul hxa hx hJ.symm

/-- **The ideals of a fixed ray class, through an auxiliary ideal of the inverse class.**  This is
the form the counting argument uses: the ideals of the class `c` are indexed by the elements of
`𝔞` congruent to one modulo `𝔪`, once `𝔞` has been chosen in the class `c⁻¹`. -/
theorem idealClass_eq_iff_exists_mem_rayGenerators {𝔪 : Modulus K}
    {c : RayClassGroup 𝔪} {𝔞 : integralIdealsPrimeTo 𝔪} (h𝔞 : idealClass 𝔪 𝔞 = c⁻¹)
    (J : integralIdealsPrimeTo 𝔪) :
    idealClass 𝔪 J = c ↔
      ∃ a ∈ rayGenerators 𝔪 (𝔞 : Ideal (𝓞 K)),
        (𝔞 : Ideal (𝓞 K)) * (J : Ideal (𝓞 K)) = Ideal.span {a} := by
  rw [← idealClass_mul_eq_one_iff_exists_mem_rayGenerators, h𝔞, inv_mul_eq_one]
  exact eq_comm

/-- **Two generators span the same ideal exactly when they differ by a unit congruent to one.**
Equal principal ideals give an associated pair, and the associating unit of `𝓞 K` is congruent to
one modulo `𝔪` because the two generators are: its image in `Kˣ` is `y * x⁻¹`.

Applied to two elements of `rayGenerators 𝔪 𝔞`, this identifies the fibres of the correspondence
of `idealClass_eq_iff_exists_mem_rayGenerators` with the orbits of `unitsCongruenceSubgroup 𝔪`. -/
theorem span_singleton_eq_span_singleton_iff_exists_mem_unitsCongruenceSubgroup {𝔪 : Modulus K}
    {a b : 𝓞 K} {x y : Kˣ} (hxa : (x : K) = a) (hx : IsCongrOne 𝔪 x) (hyb : (y : K) = b)
    (hy : IsCongrOne 𝔪 y) :
    (Ideal.span {a} : Ideal (𝓞 K)) = Ideal.span {b} ↔
      ∃ u ∈ unitsCongruenceSubgroup 𝔪, b = (u : 𝓞 K) * a := by
  have hane : ((a : 𝓞 K) : K) ≠ 0 := by rw [← hxa]; exact x.ne_zero
  refine ⟨fun h ↦ ?_, ?_⟩
  · obtain ⟨u, hu⟩ := Ideal.span_singleton_eq_span_singleton.mp h
    have hab : ((b : 𝓞 K) : K) = ((a : 𝓞 K) : K) * ((u : 𝓞 K) : K) := by
      rw [← hu]; push_cast; ring
    have hfield : algebraMap (𝓞 K) K (u : 𝓞 K) = (y : K) * (x : K)⁻¹ := by
      rw [hxa, hyb, hab]
      field_simp
    have hval : Units.map (algebraMap (𝓞 K) K).toMonoidHom u = y * x⁻¹ := by
      apply Units.ext
      simpa using hfield
    refine ⟨u, mem_unitsCongruenceSubgroup.mpr ?_, by rw [← hu]; ring⟩
    rw [hval]
    exact mem_congruenceSubgroup.mp ((congruenceSubgroup 𝔪).mul_mem
      (mem_congruenceSubgroup.mpr hy)
      ((congruenceSubgroup 𝔪).inv_mem (mem_congruenceSubgroup.mpr hx)))
  · rintro ⟨u, -, rfl⟩
    exact Ideal.span_singleton_eq_span_singleton.mpr ⟨u, mul_comm a (u : 𝓞 K)⟩

end TauCeti.GlobalNumberFields
