/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Global.RayClass.Basic

/-!
# Integral representatives of ray classes

Every ray class of a modulus `𝔪` of a number field is the class of a nonzero *integral* ideal
prime to `𝔪`, and a ray class is trivial exactly when the ideal is generated by an algebraic
integer congruent to one modulo `𝔪`.  The construction behind the first is that inside a nonzero
ideal `D` comaximal with the finite part `𝔪₀` there is an algebraic integer congruent to one
modulo `𝔪₀` and positive at every real place (`exists_mem_isCongrOne`).  Its existence combines
the comaximality, which supplies an element of `D` congruent to one, with
`NumberField.exists_isTotallyPositive_sub_mem`, which corrects the archimedean signs without
leaving the residue class modulo `D · 𝔪₀`.

Applying that construction to an integral ideal `I` prime to `𝔪` produces a principal ideal
`(α) = I · J` generated by an element congruent to one, so `J` is again prime to `𝔪` and the ray
class of `J` inverts the ray class of `I`.  The image of `idealClass 𝔪` is therefore a *subgroup*
of the ray class group, and since it contains the class of every prime not dividing `𝔪` it is
everything: this is the moving lemma, `idealClass_surjective`.

The second needs no construction at all: an ideal whose own ray class is trivial is generated as a
fractional ideal by an element congruent to one, and that element is an algebraic integer because
the ideal it generates is integral.

## Main results

* `TauCeti.GlobalNumberFields.exists_mem_isCongrOne`: an ideal comaximal with the finite part of
  `𝔪` contains a nonzero element whose image in `Kˣ` is congruent to one modulo `𝔪`.
* `TauCeti.GlobalNumberFields.Modulus.isCoprimeTo_of_dvd_span_singleton`: a divisor of a principal
  ideal whose generator is congruent to one modulo `𝔪` is prime to `𝔪`.
* `TauCeti.GlobalNumberFields.exists_isCongrOne_span_eq_mul`: an integral ideal prime to `𝔪`
  divides a principal ideal whose generator is congruent to one modulo `𝔪`, with complementary
  ideal again prime to `𝔪`.
* `TauCeti.GlobalNumberFields.exists_idealClass_mul_eq_one`: the ray class of an integral ideal
  prime to `𝔪` is inverted by the ray class of another such ideal.
* `TauCeti.GlobalNumberFields.idealClass_surjective`: **the moving lemma**, that every ray class is
  the class of a nonzero integral ideal prime to the modulus.
* `TauCeti.GlobalNumberFields.idealClass_eq_one_iff_exists_isCongrOne_span_eq`: the integral form
  of `idealClass_eq_one_iff`, a single generator in `𝓞 K` congruent to one modulo `𝔪`.

## References

* J. Neukirch, *Algebraic Number Theory*, Chapter VI, §1.
* S. Lang, *Algebraic Number Theory*, Chapter VI, §1.
-/

public section

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum NumberField
open scoped nonZeroDivisors NumberField

namespace TauCeti.GlobalNumberFields

variable {K : Type*} [Field K] [NumberField K]

/-! ### Generators congruent to one modulo a modulus -/

/-- **An algebraic integer in `1 + 𝔪₀` is congruent to one modulo `𝔪`.**  Membership of `a - 1` in
the finite part gives the valuation bound at *every* finite place, since the prime power prescribed
by the exponent divides the finite part (`Modulus.pow_exponent_dvd_finitePart`); the real
conditions are carried over unchanged. -/
theorem isCongrOne_of_sub_one_mem {𝔪 : Modulus K} {x : Kˣ} {a : 𝓞 K} (hxa : (x : K) = a)
    (hmem : a - 1 ∈ 𝔪.finitePart)
    (hpos : ∀ w ∈ 𝔪.infinitePart, 0 < InfinitePlace.embedding_of_isReal w.2 (x : K)) :
    IsCongrOne 𝔪 x := by
  refine isCongrOne_iff.mpr ⟨fun v _ ↦ ?_, hpos⟩
  have hsub : (x : K) - 1 = algebraMap (𝓞 K) K (a - 1) := by rw [map_sub, map_one, hxa]
  rw [hsub, valuation_of_algebraMap, intValuation_le_pow_iff_mem]
  exact Ideal.le_of_dvd (Modulus.pow_exponent_dvd_finitePart 𝔪 v) hmem

/-- **A generator congruent to one inside an ideal comaximal with the finite part.**  For a nonzero
ideal `D` with `D ⊔ 𝔪₀ = ⊤` there is an algebraic integer `a ∈ D` whose image in `Kˣ` is congruent
to one modulo `𝔪`.

Comaximality produces an element of `D` congruent to one modulo `𝔪₀`, and
`NumberField.exists_isTotallyPositive_sub_mem` moves it inside `D * 𝔪₀` — hence without changing
either condition — to make it nonzero and positive at every real place. -/
theorem exists_mem_isCongrOne {𝔪 : Modulus K} {D : Ideal (𝓞 K)} (hD : D ≠ ⊥)
    (hcop : D ⊔ 𝔪.finitePart = ⊤) :
    ∃ (a : 𝓞 K) (x : Kˣ), a ∈ D ∧ (x : K) = a ∧ IsCongrOne 𝔪 x := by
  obtain ⟨u, hu, t, ht, hut⟩ :=
    Submodule.mem_sup.mp (hcop ▸ Submodule.mem_top : (1 : 𝓞 K) ∈ D ⊔ 𝔪.finitePart)
  have hH : D * 𝔪.finitePart ≠ ⊥ := fun h ↦
    (Ideal.mul_eq_bot.mp h).elim hD 𝔪.finitePart_ne_bot
  obtain ⟨b, hb0, hbu, hbpos⟩ := NumberField.exists_isTotallyPositive_sub_mem hH u
  have hbD : b ∈ D := by
    simpa only [sub_add_cancel] using D.add_mem (Ideal.mul_le_left hbu) hu
  have hb1 : b - 1 ∈ 𝔪.finitePart := by
    have hu1 : u - 1 ∈ 𝔪.finitePart := by
      rw [← hut, sub_add_eq_sub_sub, sub_self, zero_sub]
      exact 𝔪.finitePart.neg_mem ht
    simpa only [sub_add_sub_cancel] using
      𝔪.finitePart.add_mem (Ideal.mul_le_right hbu) hu1
  exact ⟨b, Units.mk0 (b : K) (RingOfIntegers.coe_ne_zero_iff.mpr hb0), hbD, rfl,
    isCongrOne_of_sub_one_mem rfl hb1 fun w _ ↦ isTotallyPositive_iff.mp hbpos w.1 w.2⟩

/-- **A divisor of a principal ideal with a generator congruent to one is prime to the
modulus.**  A prime of the support dividing `J` would contain the generator `a`, whose valuation
there is one because `a` is congruent to one. -/
theorem Modulus.isCoprimeTo_of_dvd_span_singleton {𝔪 : Modulus K} {J : Ideal (𝓞 K)} (hJ : J ≠ ⊥)
    {a : 𝓞 K} {x : Kˣ} (hxa : (x : K) = a) (hx : IsCongrOne 𝔪 x)
    (hdvd : J ∣ Ideal.span {a}) : 𝔪.IsCoprimeTo J := by
  refine Modulus.isCoprimeTo_iff.mpr ⟨hJ, fun v hv hvJ ↦ ?_⟩
  have hmem : a ∈ v.asIdeal := Ideal.dvd_span_singleton.mp (hvJ.trans hdvd)
  have hlt : v.valuation K (x : K) < 1 := by
    rw [hxa]
    exact (valuation_lt_one_iff_mem (K := K) v a).mpr hmem
  exact absurd (hx.valuation_eq_one ((Modulus.mem_support_iff 𝔪 v).mp hv)) hlt.ne

/-! ### The moving lemma -/

/-- **An integral ideal prime to `𝔪` divides a principal ideal with a generator congruent to
one.**  Because the generator `a` is a unit at every prime dividing the finite part of `𝔪`, the
complementary ideal `J` with `(a) = I · J` is again prime to `𝔪`.

This is the ideal-level statement behind `exists_idealClass_mul_eq_one`; it is the analogue, for a
ray-class modulus, of `NumberField.exists_isTotallyPositive_span_eq_mul_isCoprime`. -/
theorem exists_isCongrOne_span_eq_mul {𝔪 : Modulus K} (I : integralIdealsPrimeTo 𝔪) :
    ∃ (J : integralIdealsPrimeTo 𝔪) (a : 𝓞 K) (x : Kˣ), (x : K) = a ∧ IsCongrOne 𝔪 x ∧
      Ideal.span {a} = (I : Ideal (𝓞 K)) * (J : Ideal (𝓞 K)) := by
  obtain ⟨hIbot, hsup⟩ :=
    Modulus.isCoprimeTo_iff_sup_eq_top.mp (Modulus.mem_integralIdealsPrimeTo.mp I.2)
  obtain ⟨a, x, haI, hxa, hx⟩ := exists_mem_isCongrOne hIbot hsup
  have ha0 : a ≠ 0 := fun h ↦ x.ne_zero (by rw [hxa, h]; simp)
  obtain ⟨J, hJ⟩ :=
    Ideal.dvd_iff_le.mpr ((Ideal.span_singleton_le_iff_mem (I := (I : Ideal (𝓞 K)))).mpr haI)
  have hJbot : J ≠ ⊥ := by
    rintro rfl
    rw [Ideal.mul_bot] at hJ
    exact ha0 (Ideal.span_singleton_eq_bot.mp hJ)
  exact ⟨⟨J, Modulus.mem_integralIdealsPrimeTo.mpr (Modulus.isCoprimeTo_of_dvd_span_singleton
    hJbot hxa hx ⟨I, by rw [hJ, mul_comm]⟩)⟩, a, x, hxa, hx, hJ⟩

/-- **A product of integral ideals generated by an element congruent to one lies in the ray.** -/
theorem idealClass_mul_eq_one_of_span_eq_mul {𝔪 : Modulus K} {I J : integralIdealsPrimeTo 𝔪}
    {a : 𝓞 K} {x : Kˣ} (hxa : (x : K) = a) (hx : IsCongrOne 𝔪 x)
    (hJ : Ideal.span {a} = (I : Ideal (𝓞 K)) * (J : Ideal (𝓞 K))) :
    idealClass 𝔪 I * idealClass 𝔪 J = 1 := by
  rw [← map_mul, idealClass_eq_one_iff]
  exact ⟨x, hx, by
    rw [Submonoid.coe_mul, ← hJ,
      FractionalIdeal.coeIdeal_span_singleton, hxa]⟩

/-- **Every ray class of an integral ideal prime to `𝔪` is inverted by another one.**  The
principal ideal `I · J` of `exists_isCongrOne_span_eq_mul` has a generator congruent to one modulo
`𝔪`, so it lies in the ray.  This is what makes the image of `idealClass 𝔪` a subgroup. -/
theorem exists_idealClass_mul_eq_one {𝔪 : Modulus K} (I : integralIdealsPrimeTo 𝔪) :
    ∃ J : integralIdealsPrimeTo 𝔪, idealClass 𝔪 I * idealClass 𝔪 J = 1 := by
  obtain ⟨J, a, x, hxa, hx, hJ⟩ := exists_isCongrOne_span_eq_mul I
  exact ⟨J, idealClass_mul_eq_one_of_span_eq_mul hxa hx hJ⟩

/-- **The moving lemma.**  Every ray class of `𝔪` is the class of a nonzero integral ideal prime to
`𝔪`: the image of `idealClass 𝔪` is a subgroup of the ray class group by
`exists_idealClass_mul_eq_one`, and it contains the class of every prime not dividing the finite
part, which generate the ideals prime to `𝔪`. -/
theorem idealClass_surjective (𝔪 : Modulus K) : Function.Surjective (idealClass 𝔪) := by
  classical
  -- The image of `idealClass 𝔪`; inversion is what needs an argument.
  let G : Subgroup (RayClassGroup 𝔪) :=
    { carrier := Set.range (idealClass 𝔪)
      one_mem' := ⟨1, map_one _⟩
      mul_mem' := by
        rintro _ _ ⟨I, rfl⟩ ⟨J, rfl⟩
        exact ⟨I * J, map_mul _ _ _⟩
      inv_mem' := by
        rintro _ ⟨I, rfl⟩
        obtain ⟨J, hJ⟩ := exists_idealClass_mul_eq_one I
        exact ⟨J, (inv_eq_of_mul_eq_one_right hJ).symm⟩ }
  -- The fractional ideals prime to `𝔪` whose ray class lies in `G`, viewed in the ambient group.
  let T : Subgroup (FractionalIdeal (𝓞 K)⁰ K)ˣ :=
    (G.comap (rayClassMk 𝔪)).map (idealsPrimeTo 𝔪).subtype
  have hT : NumberFieldArithmetic.idealsAway (K := K) 𝔪.support ≤ T := by
    rw [NumberFieldArithmetic.idealsAway_eq_closure_primes 𝔪.support]
    refine (Subgroup.closure_le _).mpr ?_
    rintro P ⟨v, hv, hPv⟩
    have hvmem : v.asIdeal ∈ integralIdealsPrimeTo 𝔪 := by
      refine NumberFieldArithmetic.mem_integralIdealsAway_iff.mpr ⟨v.ne_bot, fun w hw hdvd ↦ ?_⟩
      -- A prime dividing `v` equals `v`, by maximality; so it cannot lie in the support.
      exact hv (HeightOneSpectrum.ext
        (v.isMaximal.eq_of_le w.isPrime.ne_top (Ideal.le_of_dvd hdvd)) ▸ hw)
    refine ⟨NumberFieldArithmetic.integralIdealsAwayHom 𝔪.support ⟨v.asIdeal, hvmem⟩,
      ⟨⟨v.asIdeal, hvmem⟩, idealClass_apply 𝔪 ⟨v.asIdeal, hvmem⟩⟩, Units.ext ?_⟩
    rw [Subgroup.coe_subtype, NumberFieldArithmetic.coe_integralIdealsAwayHom, hPv]
  intro c
  obtain ⟨I, rfl⟩ := rayClassMk_surjective 𝔪 c
  obtain ⟨I', hI', hI'I⟩ := Subgroup.mem_map.mp (hT I.2)
  obtain ⟨J, hJ⟩ := hI'
  exact ⟨J, by rw [hJ]; congr 1; exact Subtype.ext hI'I⟩

/-! ### The integral triviality criterion -/

/-- **The integral form of the triviality criterion.**  An integral ideal prime to `𝔪` has trivial
ray class exactly when it is generated, as an ideal of `𝓞 K`, by an algebraic integer whose image
in `Kˣ` is congruent to one modulo `𝔪`.

The fractional criterion `idealClass_eq_one_iff` is the primary one; here the generator is an
algebraic integer, which is what a count of integral ideals in a ray class needs.  No denominator
is left behind: a generator of a fractional ideal that happens to be integral already lies in
`𝓞 K`. -/
theorem idealClass_eq_one_iff_exists_isCongrOne_span_eq {𝔪 : Modulus K}
    (I : integralIdealsPrimeTo 𝔪) :
    idealClass 𝔪 I = 1 ↔ ∃ (a : 𝓞 K) (x : Kˣ), (x : K) = a ∧ IsCongrOne 𝔪 x ∧
      Ideal.span {a} = (I : Ideal (𝓞 K)) := by
  refine ⟨fun hI ↦ ?_, ?_⟩
  · obtain ⟨x, hx, hxI⟩ := (idealClass_eq_one_iff I).mp hI
    -- The generator lies in the integral ideal `I`, hence is an algebraic integer.
    obtain ⟨a, _, ha⟩ := (FractionalIdeal.mem_coeIdeal (𝓞 K)⁰).mp
      (hxI ▸ FractionalIdeal.mem_spanSingleton_self (𝓞 K)⁰ (x : K))
    have hcoe : ((Ideal.span {a} : Ideal (𝓞 K)) : FractionalIdeal (𝓞 K)⁰ K) =
        ((I : Ideal (𝓞 K)) : FractionalIdeal (𝓞 K)⁰ K) := by
      rw [FractionalIdeal.coeIdeal_span_singleton, ha, hxI]
    exact ⟨a, x, ha.symm, hx, FractionalIdeal.coeIdeal_injective (K := K) hcoe⟩
  · rintro ⟨a, x, hxa, hx, ha⟩
    refine (idealClass_eq_one_iff I).mpr ⟨x, hx, ?_⟩
    rw [← ha, FractionalIdeal.coeIdeal_span_singleton, hxa]

end TauCeti.GlobalNumberFields
