/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Data.ZMod.QuotientRing
public import Mathlib.RingTheory.Ideal.Norm.AbsNorm
public import TauCeti.NumberTheory.NumberField.Global.RayClass.Exact

import Mathlib.NumberTheory.NumberField.Units.Basic
import TauCeti.NumberTheory.NumberField.Global.RayClass.Integral
import TauCeti.NumberTheory.NumberField.Ideal.IntegersRat

/-!
# The ray class group of `ℚ` modulo `(n)·∞`

For a positive integer `n`, the modulus `(n)·∞` of `ℚ` has finite part the ideal generated by `n`
and infinite part the unique real place.  Its ray class group is `(ZMod n)ˣ`: a fractional ideal
of `ℚ` prime to `n` has exactly one positive generator, and the class of the ideal is the residue
of that generator modulo `n`.  In particular the ray class of a nonzero integral ideal prime to
`n` is its absolute norm modulo `n`.

The real place is essential.  For the modulus `(n)` without it, both `a` and `-a` generate the
same ideal, so the ray class group is only `(ZMod n)ˣ ⧸ {±1}`.

The equivalence is read off from the ray class exact sequence.  The class group of `ℚ` is
trivial, so every ray class is the class of a residue unit modulo `n` and a sign at the real
place.  The only integer units are `±1`, so the sign of a class can be absorbed into its residue
and a class with positive sign is determined by its residue.

## Main definitions

* `TauCeti.GlobalNumberFields.ratModulus`: the modulus `(n)·∞` of `ℚ`.
* `TauCeti.GlobalNumberFields.ratModulusResidueEquiv`: the residue ring of `𝓞 ℚ` modulo the finite
  part of `ratModulus n hn` is `ZMod n`.
* `TauCeti.GlobalNumberFields.ratModulusEquivZMod`: the ray class group of `ratModulus n hn` is
  `(ZMod n)ˣ`.

## Main results

* `TauCeti.GlobalNumberFields.ratModulusEquivZMod_symm_apply`: a unit `u` modulo `n` corresponds to
  the principal ray class of a positive rational number with residue `u`.
* `TauCeti.GlobalNumberFields.coe_ratModulusEquivZMod_idealClass`: the ray class of a nonzero
  integral ideal prime to `n` is its absolute norm modulo `n`.

## References

* J. Neukirch, *Algebraic Number Theory*, Chapter VI, §1.
-/

public section

open IsDedekindDomain NumberField
open scoped nonZeroDivisors NumberField

namespace TauCeti.GlobalNumberFields

/-- **The modulus `(n)·∞` of `ℚ`**: its finite part is the ideal of `𝓞 ℚ` generated by `n`, and
its infinite part is the real place of `ℚ`. -/
noncomputable def ratModulus (n : ℕ) (hn : n ≠ 0) : Modulus ℚ where
  finitePart := Ideal.span {(n : 𝓞 ℚ)}
  finitePart_ne_bot := by
    rw [Ne, Ideal.span_singleton_eq_bot]
    exact_mod_cast hn
  infinitePart := {⟨Rat.infinitePlace, Rat.isReal_infinitePlace⟩}

variable (n : ℕ) (hn : n ≠ 0)

@[simp] theorem ratModulus_finitePart :
    (ratModulus n hn).finitePart = Ideal.span {(n : 𝓞 ℚ)} := (rfl)

@[simp] theorem ratModulus_infinitePart :
    (ratModulus n hn).infinitePart = {⟨Rat.infinitePlace, Rat.isReal_infinitePlace⟩} := (rfl)

/-- **Reduction modulo the finite part of `ratModulus n hn` is reduction modulo `n`**, transported
along `Rat.ringOfIntegersEquiv : 𝓞 ℚ ≃+* ℤ`. -/
noncomputable def ratModulusResidueEquiv : 𝓞 ℚ ⧸ (ratModulus n hn).finitePart ≃+* ZMod n :=
  (Ideal.quotientEquiv _ (Ideal.span {(n : ℤ)}) Rat.ringOfIntegersEquiv (by
      rw [ratModulus_finitePart, Ideal.map_span, Set.image_singleton, map_natCast])).trans
    (Int.quotientSpanNatEquivZMod n)

@[simp] theorem ratModulusResidueEquiv_mk (a : 𝓞 ℚ) :
    ratModulusResidueEquiv n hn (Ideal.Quotient.mk _ a) = (Rat.ringOfIntegersEquiv a : ZMod n) := by
  rw [ratModulusResidueEquiv, RingEquiv.trans_apply, Ideal.quotientEquiv_mk]
  exact RingHom.congr_fun (Int.quotientSpanNatEquivZMod_comp_Quotient_mk n) _

/-- The ray class of a unit modulo `n`: the principal ray class of an element with that residue
and positive sign. -/
private noncomputable def zmodUnitsToRayClass : (ZMod n)ˣ →* RayClassGroup (ratModulus n hn) :=
  (residueSignRayClass (ratModulus n hn)).comp <| (MonoidHom.inl _ _).comp
    (Units.mapEquiv (ratModulusResidueEquiv n hn).symm.toMulEquiv).toMonoidHom

private theorem zmodUnitsToRayClass_apply (u : (ZMod n)ˣ) :
    zmodUnitsToRayClass n hn u = residueSignRayClass (ratModulus n hn)
      (Units.mapEquiv (ratModulusResidueEquiv n hn).symm.toMulEquiv u, 1) :=
  (rfl)

variable {n hn}

/-- **The ray class of an integral ideal of `𝓞 ℚ` prime to `n`.**  Its absolute norm is a positive
generator, so the class is that of the residue of the norm together with the trivial sign. -/
private theorem exists_zmodUnitsToRayClass_eq_idealClass
    (I : integralIdealsPrimeTo (ratModulus n hn)) :
    ∃ u : (ZMod n)ˣ, (u : ZMod n) = Ideal.absNorm (I : Ideal (𝓞 ℚ)) ∧
      zmodUnitsToRayClass n hn u = idealClass (ratModulus n hn) I := by
  set a := Ideal.absNorm (I : Ideal (𝓞 ℚ)) with ha_def
  have ha : (a : ℚ) ≠ 0 := by
    rw [Nat.cast_ne_zero, ha_def, Ne, Ideal.absNorm_eq_zero_iff]
    exact (Modulus.isCoprimeTo_iff.mp (Modulus.mem_integralIdealsPrimeTo.mp I.2)).1
  let x : ℚˣ := Units.mk0 a ha
  -- The principal ideal of the norm is `I` itself.
  have hI : toPrincipalIdeal (𝓞 ℚ) ℚ x =
      (NumberFieldArithmetic.integralIdealsAwayHom (ratModulus n hn).support I :
        (FractionalIdeal (𝓞 ℚ)⁰ ℚ)ˣ) := by
    refine Units.ext ?_
    rw [coe_toPrincipalIdeal, NumberFieldArithmetic.coe_integralIdealsAwayHom]
    conv_rhs => rw [← Rat.RingOfIntegers.ideal_span_absNorm_eq_self (I : Ideal (𝓞 ℚ))]
    rw [FractionalIdeal.coeIdeal_span_singleton, map_natCast, Units.val_mk0]
  have hx : x ∈ primeToSubgroup (ratModulus n hn) :=
    toPrincipalIdeal_mem_idealsPrimeTo_iff.mp
      (hI ▸ (NumberFieldArithmetic.integralIdealsAwayHom (ratModulus n hn).support I).2)
  set r := residueHom (ratModulus n hn) ⟨x, hx⟩
  refine ⟨Units.mapEquiv (ratModulusResidueEquiv n hn).toMulEquiv r, ?_, ?_⟩
  · rw [Units.coe_mapEquiv, RingEquiv.toMulEquiv_eq_coe, RingEquiv.coe_toMulEquiv, coe_residueHom,
      residue_eq (a := (a : 𝓞 ℚ)) (b := 1) _ (by simp) (by simp [x]),
      ratModulusResidueEquiv_mk, map_natCast, Int.cast_natCast]
  · -- The norm is positive at the real place, so the class is that of its residue alone.
    have hsign : modulusSignHom (ratModulus n hn) x = 1 :=
      (modulusSignHom_eq_one_iff x).mpr fun w _ ↦ by
        rw [Units.val_mk0, map_natCast]
        exact Nat.cast_pos.mpr (Nat.pos_of_ne_zero (by exact_mod_cast ha))
    have hJ : NumberFieldArithmetic.integralIdealsAwayHom (ratModulus n hn).support I =
        principalIdealPrimeTo (ratModulus n hn) ⟨x, hx⟩ :=
      Subtype.ext (by rw [coe_principalIdealPrimeTo]; exact hI.symm)
    rw [idealClass_apply, hJ, ← principalRayClass_apply, ← residueSignRayClass_residueSignHom,
      zmodUnitsToRayClass_apply]
    refine congrArg _ (Prod.ext (Units.ext ?_) ((residueSignHom_snd _ _).trans hsign).symm)
    simp [r]

private theorem zmodUnitsToRayClass_injective : Function.Injective (zmodUnitsToRayClass n hn) := by
  rw [injective_iff_map_eq_one]
  intro u hu
  -- A residue with positive sign and trivial ray class comes from a positive integer unit.
  have hmem : (Units.mapEquiv (ratModulusResidueEquiv n hn).symm.toMulEquiv u,
      (1 : (ratModulus n hn).infinitePart → ℤˣ)) ∈ (residueSignRayClass (ratModulus n hn)).ker :=
    hu
  rw [ker_residueSignRayClass] at hmem
  obtain ⟨v, hv⟩ := hmem
  rw [unitsResidueSignHom_apply, Prod.ext_iff, residueSignHom_fst, residueSignHom_snd,
    coe_unitsToPrimeToSubgroup] at hv
  have hpos := (modulusSignHom_eq_one_iff _).mp hv.2 ⟨Rat.infinitePlace, Rat.isReal_infinitePlace⟩
    (by rw [ratModulus_infinitePart]; exact Finset.mem_singleton_self _)
  -- The only positive integer unit of `ℚ` is `1`.
  have hv1 : v = 1 := by
    rcases Rat.RingOfIntegers.isUnit_iff.mp v.isUnit with h | h
    · exact Units.ext (RingOfIntegers.ext h)
    · -- The real embedding of `ℚ` is the identity on rationals, so `hpos` reads `0 < v`.
      rw [RingOfIntegers.coe_eq_algebraMap] at h
      norm_num at hpos
      linarith
  rw [hv1, map_one, map_one] at hv
  exact (Units.mapEquiv _).injective (hv.1.symm.trans (map_one _).symm)

private theorem zmodUnitsToRayClass_surjective :
    Function.Surjective (zmodUnitsToRayClass n hn) := by
  intro c
  obtain ⟨I, rfl⟩ := idealClass_surjective _ c
  obtain ⟨u, -, hu⟩ := exists_zmodUnitsToRayClass_eq_idealClass I
  exact ⟨u, hu⟩

variable (n hn)

/-- **The ray class group of `ℚ` modulo `(n)·∞` is `(ZMod n)ˣ`.**  A ray class corresponds to the
residue modulo `n` of the positive generator of any fractional ideal in it. -/
noncomputable def ratModulusEquivZMod : RayClassGroup (ratModulus n hn) ≃* (ZMod n)ˣ :=
  (MulEquiv.ofBijective (zmodUnitsToRayClass n hn)
    ⟨zmodUnitsToRayClass_injective, zmodUnitsToRayClass_surjective⟩).symm

/-- A unit `u` modulo `n` corresponds to the principal ray class of an element with residue `u`
and positive sign at the real place. -/
theorem ratModulusEquivZMod_symm_apply (u : (ZMod n)ˣ) :
    (ratModulusEquivZMod n hn).symm u = residueSignRayClass (ratModulus n hn)
      (Units.mapEquiv (ratModulusResidueEquiv n hn).symm.toMulEquiv u, 1) := by
  rfl

/-- **The ray class of a nonzero integral ideal prime to `n` is its absolute norm modulo `n`.**
Since `idealClass` is surjective, this characterizes `ratModulusEquivZMod`. -/
@[simp]
theorem coe_ratModulusEquivZMod_idealClass (I : integralIdealsPrimeTo (ratModulus n hn)) :
    ((ratModulusEquivZMod n hn (idealClass (ratModulus n hn) I) : (ZMod n)ˣ) : ZMod n) =
      Ideal.absNorm (I : Ideal (𝓞 ℚ)) := by
  obtain ⟨u, hu, hcl⟩ := exists_zmodUnitsToRayClass_eq_idealClass I
  have h : (ratModulusEquivZMod n hn).symm u = idealClass (ratModulus n hn) I := by
    rw [ratModulusEquivZMod_symm_apply, ← zmodUnitsToRayClass_apply, hcl]
  rw [← hu, ← h, MulEquiv.apply_symm_apply]

end TauCeti.GlobalNumberFields
