/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.GaloisGroups.FrobeniusOrbits
public import TauCeti.NumberTheory.NumberField.Frobenius
public import TauCeti.NumberTheory.NumberField.SplittingField
public import TauCeti.RingTheory.Polynomial.FactorDegrees
public import TauCeti.RingTheory.Polynomial.Resultant.Discriminant
import Mathlib.Algebra.CharP.Basic
import Mathlib.FieldTheory.Perfect

/-!
# Dedekind's theorem: the cycle type of a Frobenius is the factorization type

Let `f` be a monic integer polynomial and `p` a prime modulo which `f` is squarefree. Let `M` be
a number field in which `f` splits, and let `σ ∈ Gal(M/ℚ)` be an arithmetic Frobenius at a prime
`Q` of `𝓞 M` over `p`. **Dedekind's theorem** says that the permutation `σ` induces on the roots
of `f` in `M` has, counting fixed points, cycle lengths the degrees of the irreducible factors of
`f` modulo `p`.

The proof reduces the roots modulo `Q`. The roots of `f` are algebraic integers, and reduction
modulo `Q` maps them bijectively onto the roots of `f mod p` in the residue field `𝓞 M ⧸ Q`:
their images are all the roots of `f mod p`, counted with multiplicity, and these are distinct
because `f mod p` is squarefree over the perfect field `𝔽_p`. The Frobenius congruence
`σ x ≡ x ^ p (mod Q)` makes this bijection carry `σ` to the `p`-th power map, whose cycle type on
the roots of a squarefree polynomial over `𝔽_p` is its factorization type
(`TauCeti.FiniteField.fullCycleType_eq_map_natDegree_normalizedFactors`). Neither the index of
`ℤ[θ]` nor the ramification of `p` in the field generated by a root enters the argument.

Since `p ∤ disc f` makes `f mod p` squarefree, the theorem applies at every such prime to the
splitting field of `f` over `ℚ`, where Frobenius elements exist. Moving from that splitting field
to `ℂ` does not change the cycle type of a Galois automorphism, which gives the statement in the
vocabulary of `Polynomial.Gal`.

## Main results

* `TauCeti.NumberField.fullCycleType_galActionHom_restrict_eq_factorDegrees`: Dedekind's theorem
  for a Frobenius element of a number field in which `f` splits.
* `TauCeti.NumberField.exists_gal_fullCycleType_eq_factorizationType`: for monic `f` and a prime
  `p ∤ disc f`, some element of the Galois group of `f` over `ℚ` acts on the complex roots of `f`
  with full cycle type the factor degrees of `f` modulo `p`.

## References

* [J. Neukirch, *Algebraic Number Theory*][Neukirch1992], Chapter I, §8, Exercises 4 and 5.
* D. A. Marcus, *Number Fields*, 2nd edition, Springer 2018, Chapter 4.
-/

public section

open Polynomial Ideal
open scoped NumberField

namespace TauCeti.NumberField

variable {M : Type*} [Field M] [NumberField M] {f : ℤ[X]} {p : ℕ} [Fact p.Prime]

/-- The two ways of viewing an integer polynomial over a number field agree. -/
private theorem map_map_intCast_rat (f : ℤ[X]) :
    (f.map (Int.castRingHom ℚ)).map (algebraMap ℚ M) =
      (f.map (algebraMap ℤ (𝓞 M))).map (algebraMap (𝓞 M) M) := by
  rw [Polynomial.map_map, Polynomial.map_map,
    RingHom.ext_int ((algebraMap ℚ M).comp (Int.castRingHom ℚ))
      ((algebraMap (𝓞 M) M).comp (algebraMap ℤ (𝓞 M)))]

/-- A root of a monic integer polynomial is an algebraic integer. -/
private theorem isIntegral_of_aeval_eq_zero (hf : f.Monic) {x : M}
    (hx : aeval x (f.map (Int.castRingHom ℚ)) = 0) : IsIntegral ℤ x :=
  ⟨f, hf, by
    rwa [aeval_def, eval₂_map,
      RingHom.ext_int ((algebraMap ℚ M).comp (Int.castRingHom ℚ)) (algebraMap ℤ M)] at hx⟩

/-- **Reducing the roots of `f` modulo a prime.** Let `f` be monic, split in `M`, and squarefree
modulo `p`, and let `ρ : 𝓞 M →+* k` be a ring homomorphism to a field `k` over `𝔽_p`. Then
`f mod p` splits in `k`, and reduction along `ρ` is a bijection from the roots of `f` in `M` onto
the roots of `f mod p` in `k`. -/
private theorem exists_rootSet_equiv (hf : f.Monic)
    (hsq : Squarefree (f.map (Int.castRingHom (ZMod p))))
    (hsplit : ((f.map (Int.castRingHom ℚ)).map (algebraMap ℚ M)).Splits)
    {k : Type*} [Field k] [Algebra (ZMod p) k] (ρ : 𝓞 M →+* k) :
    ((f.map (Int.castRingHom (ZMod p))).map (algebraMap (ZMod p) k)).Splits ∧
      ∃ e : (f.map (Int.castRingHom ℚ)).rootSet M ≃
          (f.map (Int.castRingHom (ZMod p))).rootSet k,
        ∀ (x : (f.map (Int.castRingHom ℚ)).rootSet M) (y : 𝓞 M),
          algebraMap (𝓞 M) M y = x → (e x : k) = ρ y := by
  classical
  set fM := (f.map (Int.castRingHom ℚ)).map (algebraMap ℚ M) with hfM
  -- The roots of `f` in `M` are algebraic integers, so they form a multiset `t` of `𝓞 M`.
  have hint : ∀ x ∈ fM.roots, IsIntegral ℤ x := fun x hx =>
    isIntegral_of_aeval_eq_zero hf (by rw [← eval_map_algebraMap]; exact (mem_roots'.mp hx).2)
  obtain ⟨t, ht⟩ : ∃ t : Multiset (𝓞 M), t.map (algebraMap (𝓞 M) M) = fM.roots :=
    ⟨fM.roots.attach.map fun x => IsIntegralClosure.mk' (𝓞 M) x.1 (hint x.1 x.2), by
      simp [Multiset.map_map, IsIntegralClosure.algebraMap_mk']⟩
  have hfO : f.map (algebraMap ℤ (𝓞 M)) = (t.map fun a => X - C a).prod := by
    refine Polynomial.map_injective _ (FaithfulSMul.algebraMap_injective (𝓞 M) M) ?_
    rw [← map_map_intCast_rat, ← hfM]
    conv_lhs => rw [hsplit.eq_prod_roots_of_monic ((hf.map _).map _)]
    rw [← ht, Polynomial.map_multiset_prod, Multiset.map_map, Multiset.map_map]
    simp
  -- Reducing, `f mod p` is the product of the `X - ρ a` over `a ∈ t`.
  have hk : (f.map (Int.castRingHom (ZMod p))).map (algebraMap (ZMod p) k) =
      ((t.map ρ).map fun a => X - C a).prod := by
    rw [Polynomial.map_map,
      RingHom.ext_int ((algebraMap (ZMod p) k).comp (Int.castRingHom (ZMod p)))
        (ρ.comp (algebraMap ℤ (𝓞 M))),
      ← Polynomial.map_map, hfO, Polynomial.map_multiset_prod, Multiset.map_map,
      Multiset.map_map]
    simp
  have hroots : ((f.map (Int.castRingHom (ZMod p))).map (algebraMap (ZMod p) k)).roots =
      t.map ρ := by
    rw [hk, roots_multiset_prod_X_sub_C]
  -- `f mod p` is separable, so the reductions of the roots are distinct.
  have hnodup : (t.map ρ).Nodup :=
    hroots ▸ nodup_roots ((PerfectField.separable_iff_squarefree.mpr hsq).map)
  have hmem : ∀ x, x ∈ (f.map (Int.castRingHom ℚ)).rootSet M ↔
      ∃ a ∈ t, algebraMap (𝓞 M) M a = x := fun x => by
    rw [rootSet_def, Finset.mem_coe, Multiset.mem_toFinset, aroots_def, ← hfM, ← ht,
      Multiset.mem_map]
  have hmemk : ∀ z, z ∈ (f.map (Int.castRingHom (ZMod p))).rootSet k ↔ z ∈ t.map ρ :=
    fun z => by rw [rootSet_def, Finset.mem_coe, Multiset.mem_toFinset, aroots_def, hroots]
  -- Reduction of a root, as a map of root sets.
  let red (x : (f.map (Int.castRingHom ℚ)).rootSet M) :
      (f.map (Int.castRingHom (ZMod p))).rootSet k :=
    ⟨ρ ((hmem x).mp x.2).choose,
      (hmemk _).mpr (Multiset.mem_map_of_mem _ ((hmem x).mp x.2).choose_spec.1)⟩
  have hred (x : (f.map (Int.castRingHom ℚ)).rootSet M) (y : 𝓞 M)
      (hy : algebraMap (𝓞 M) M y = x) : (red x : k) = ρ y := by
    obtain rfl : ((hmem x).mp x.2).choose = y :=
      FaithfulSMul.algebraMap_injective (𝓞 M) M (((hmem x).mp x.2).choose_spec.2.trans hy.symm)
    rfl
  have hbij : Function.Bijective red := by
    refine ⟨fun x y hxy => ?_, fun z => ?_⟩
    · have h := Multiset.inj_on_of_nodup_map hnodup _ ((hmem x).mp x.2).choose_spec.1 _
        ((hmem y).mp y.2).choose_spec.1 (congrArg Subtype.val hxy)
      exact Subtype.ext (((hmem x).mp x.2).choose_spec.2.symm.trans
        ((congrArg (algebraMap (𝓞 M) M) h).trans ((hmem y).mp y.2).choose_spec.2))
    · obtain ⟨a, ha, hz⟩ := Multiset.mem_map.mp ((hmemk z).mp z.2)
      refine ⟨⟨_, (hmem _).mpr ⟨a, ha, rfl⟩⟩, Subtype.ext ?_⟩
      rw [hred _ a rfl, hz]
  refine ⟨hk ▸ Splits.multisetProd fun g hg => ?_, Equiv.ofBijective red hbij, hred⟩
  obtain ⟨a, -, rfl⟩ := Multiset.mem_map.mp hg
  exact Splits.X_sub_C a

/-- **Dedekind's theorem.** Let `f` be a monic integer polynomial which is squarefree modulo the
prime `p`, and let `M` be a number field in which `f` splits. If `σ ∈ Gal(M/ℚ)` is an arithmetic
Frobenius at a prime `Q` of `𝓞 M` over `p`, then the permutation of the roots of `f` in `M`
induced by `σ` has, counting fixed points, cycle lengths the degrees of the irreducible factors
of `f` modulo `p`, with multiplicity. -/
theorem fullCycleType_galActionHom_restrict_eq_factorDegrees [DecidableEq M] (hf : f.Monic)
    (hsq : Squarefree (f.map (Int.castRingHom (ZMod p))))
    [Fact (((f.map (Int.castRingHom ℚ)).map (algebraMap ℚ M)).Splits)]
    (Q : Ideal (𝓞 M)) [Q.IsPrime] [Q.LiesOver (span {(p : ℤ)})]
    {σ : M ≃ₐ[ℚ] M} (hσ : IsArithFrobAt ℤ σ Q) :
    (Gal.galActionHom (f.map (Int.castRingHom ℚ)) M
      (Gal.restrict (f.map (Int.castRingHom ℚ)) M σ)).fullCycleType = f.factorDegrees p := by
  classical
  have hp : (span {(p : ℤ)} : Ideal ℤ) ≠ ⊥ := by
    rw [Ne, span_singleton_eq_bot]
    exact_mod_cast (Fact.out : p.Prime).ne_zero
  have hQ : Q ≠ ⊥ := ne_bot_of_liesOver_of_ne_bot hp Q
  have : Q.IsMaximal := Ring.DimensionLEOne.maximalOfPrime hQ inferInstance
  let := Quotient.field Q
  have : Finite (𝓞 M ⧸ Q) := Ring.HasFiniteQuotients.finiteQuotient hQ
  have hpQ : (p : 𝓞 M) ∈ Q := by
    have h : ((p : ℤ) : 𝓞 M) ∈ Q := mem_of_liesOver Q (span {(p : ℤ)}) _ |>.mp
      (mem_span_singleton_self _)
    exact_mod_cast h
  have : CharP (𝓞 M ⧸ Q) p := (CharP.charP_iff_prime_eq_zero Fact.out).mpr <| by
    rw [← map_natCast (Ideal.Quotient.mk Q), Quotient.eq_zero_iff_mem]
    exact hpQ
  let := ZMod.algebra (𝓞 M ⧸ Q) p
  have : Algebra.IsAlgebraic (ZMod p) (𝓞 M ⧸ Q) := Algebra.IsAlgebraic.of_finite _ _
  obtain ⟨hsplit, e, he⟩ := exists_rootSet_equiv hf hsq Fact.out (Ideal.Quotient.mk Q)
  have : Fact _ := ⟨hsplit⟩
  rw [factorDegrees_def, ← Equiv.Perm.fullCycleType_permCongr e]
  refine FiniteField.fullCycleType_eq_map_natDegree_normalizedFactors _ hsq _ fun z => ?_
  obtain ⟨x, rfl⟩ := e.surjective z
  have hx : IsIntegral ℤ (x : M) :=
    isIntegral_of_aeval_eq_zero hf (aeval_eq_zero_of_mem_rootSet x.2)
  obtain ⟨y, hy⟩ : ∃ y : 𝓞 M, algebraMap (𝓞 M) M y = x :=
    ⟨_, IsIntegralClosure.algebraMap_mk' _ _ hx⟩
  have hσy : algebraMap (𝓞 M) M (σ • y) =
      (Gal.galActionHom _ M (Gal.restrict _ M σ) x : M) := by
    rw [NumberField.algebraMap_smul_eq_apply, hy, Gal.galActionHom_restrict]
  rw [Equiv.permCongr_apply, e.symm_apply_apply, he _ _ hσy, he x y hy, ZMod.card,
    ← map_pow, Ideal.Quotient.eq]
  have h := hσ y
  rwa [← LiesOver.over (P := Q) (p := span {(p : ℤ)}), Int.card_ideal_quot] at h

attribute [local instance] Gal.splits_ℚ_ℂ

open scoped Classical in
/-- **The polynomial form of Dedekind's theorem.** Let `f` be a monic integer polynomial and `p`
a prime not dividing the discriminant of `f`. Then some element of the Galois group of `f` over
`ℚ` acts on the complex roots of `f` with full cycle type (cycle lengths counted together with
fixed points) equal to the multiset of degrees of the irreducible factors of `f` modulo `p`.

The statement allows reducible `f`: the factor degrees of all the irreducible factors of `f`
are read off from a single Galois automorphism. -/
theorem exists_gal_fullCycleType_eq_factorizationType (f : ℤ[X]) (hf : f.Monic) (p : ℕ)
    [Fact p.Prime] (hp : ¬ (p : ℤ) ∣ f.discr) :
    ∃ σ : (f.map (Int.castRingHom ℚ)).Gal,
      (Gal.galActionHom (f.map (Int.castRingHom ℚ)) ℂ σ).fullCycleType = f.factorDegrees p := by
  set g := f.map (Int.castRingHom ℚ)
  set M := g.SplittingField
  have : Fact ((g.map (algebraMap ℚ M)).Splits) := ⟨SplittingField.splits g⟩
  have hsq : Squarefree (f.map (Int.castRingHom (ZMod p))) :=
    ((hf.separable_map_zmod_iff_not_dvd_discr p).mpr hp).squarefree
  have : IsGalois ℚ M := IsGalois.of_separable_splitting_field
    ((hf.discr_ne_zero_iff_separable_map ℚ).mp fun h => hp (h ▸ dvd_zero _))
  have : (span {(p : ℤ)} : Ideal ℤ).IsPrime :=
    (span_singleton_prime (by exact_mod_cast (Fact.out : p.Prime).ne_zero)).mpr
      (Nat.prime_iff_prime_int.mp Fact.out)
  obtain ⟨⟨Q, _, _⟩⟩ := (span {(p : ℤ)}).nonempty_primesOver (S := 𝓞 M)
  obtain ⟨σ, hσ⟩ := NumberField.exists_isArithFrobAt_int_of_liesOver (K := M) (p := p) Q
  refine ⟨Gal.restrict g M σ, ?_⟩
  rw [← fullCycleType_galActionHom_restrict_eq_factorDegrees hf hsq Q hσ,
    Gal.galActionHom_eq_permCongr g M ℂ, Equiv.Perm.fullCycleType_permCongr]

end TauCeti.NumberField
