/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Frobenius
public import TauCeti.NumberTheory.NumberField.Quadratic.Basic

/-!
# Frobenius in a quadratic number field

For a quadratic field generated by an integral square root of `d`, an arithmetic
Frobenius at an odd prime away from `d` is the identity exactly when `d` is a
quadratic residue at that prime. This identifies the automorphism, rather than
only its action on the chosen square root.

The square-root calculation is `NumberField.isArithFrobAt_apply_sqrt_eq_self_iff`;
generation of the field turns fixing the root into equality with the identity.

The splitting interpretation is the quadratic case of the Frobenius splitting
law in Neukirch, *Algebraic Number Theory*, Chapter I, §10.
-/

public section
noncomputable section

open Polynomial
open scoped NumberField

namespace TauCeti.NumberField

variable {K : Type*} [Field K] [NumberField K]
  {θ : 𝓞 K} {d : ℤ} {p : ℕ} [Fact p.Prime]

/-- Mathlib's coherently chosen arithmetic Frobenius at a prime of a
quadratic number field is trivial exactly at the quadratic residues. -/
theorem arithFrobAt_eq_one_iff_legendreSym [IsGalois ℚ K]
    (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hodd : p ≠ 2) (hd : ¬ (p : ℤ) ∣ d)
    (Q : Ideal (𝓞 K)) [Q.IsPrime] [Q.LiesOver (Ideal.span {(p : ℤ)})]
    [Finite (𝓞 K ⧸ Q)] :
    arithFrobAt ℤ (K ≃ₐ[ℚ] K) Q = 1 ↔ legendreSym p d = 1 := by
  let σ := arithFrobAt ℤ (K ≃ₐ[ℚ] K) Q
  have hσ : IsArithFrobAt ℤ σ Q := IsArithFrobAt.arithFrobAt ℤ (K ≃ₐ[ℚ] K) Q
  change σ = 1 ↔ legendreSym p d = 1
  rw [← NumberField.isArithFrobAt_apply_sqrt_eq_self_iff hodd hd
    (NumberField.coe_gen_sq hmin) Q hσ]
  constructor
  · intro h
    rw [h]
    rfl
  · intro h
    have heq : σ.toAlgHom = (1 : K ≃ₐ[ℚ] K).toAlgHom := by
      apply AlgHom.ext_of_adjoin_eq_top hgen
      rintro x rfl
      simpa using h
    exact AlgEquiv.ext (AlgHom.ext_iff.mp heq)

end TauCeti.NumberField

end
end
