/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.RatFunc.IntermediateField

/-!
# Automorphisms of the rational function field are its generators

A `k`-algebra homomorphism out of `k(X)` is determined by the image of `X`, because `k(X)` is the
fraction field of `k[X]`. For an automorphism that image is a transcendental element generating
`k(X)` over `k`, and conversely every such element is the image of `X` under an automorphism. So
the automorphisms of `k(X)` over `k` correspond to the generators of `k(X)` over `k`.

This is the computational form of `Aut(k(x)/k)`, and the starting point for identifying it with
the group of linear fractional transformations: a generator is a quotient of two linear
polynomials.

## Main definitions

* `RatFunc.algEquivOfAdjoinEqTop`: the automorphism of `k(X)` sending `X` to a given transcendental
  generator.
* `RatFunc.autEquivGenerator`: the resulting bijection between the automorphisms of `k(X)` over `k`
  and the transcendental generators of `k(X)` over `k`.

## Main results

* `RatFunc.algHom_ext`: a `k`-algebra homomorphism out of `k(X)` is determined by the image of `X`.
* `RatFunc.transcendental_apply_X` and `RatFunc.adjoin_apply_X_eq_top`: the image of `X` under an
  automorphism is a transcendental generator.

## Provenance

`algEquivOfAdjoinEqTop` composes Mathlib's `RatFunc.algEquivOfTranscendental`, which identifies
`k(X)` with `k⟮f⟯` for a transcendental `f`, with the identification of `k⟮f⟯ = ⊤` with `k(X)`.
Mathlib's `RatFunc.Luroth.algEquiv` composes the same two steps for an arbitrary nontrivial
intermediate field of `k(X)`, where no element plays the role of `X`; what is added here is the
evaluation `algEquivOfAdjoinEqTop_X` at `X`, which is what makes the correspondence with the
generators a bijection.

## References

* H. Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., GTM 254, Springer, 2009,
  Exercise 1.2.
-/

public section

namespace RatFunc

section AlgHom

variable {K : Type*} [CommRing K] [IsDomain K] {L : Type*} [CommRing L] [Algebra K L]

/-- **A homomorphism out of `k(X)` is determined by the image of `X`**: the polynomials `k[X]` are
generated by `X`, and `k(X)` is their fraction field. -/
@[ext]
theorem algHom_ext {σ τ : RatFunc K →ₐ[K] L} (h : σ X = τ X) : σ = τ := by
  have hpoly : (σ : RatFunc K →+* L).comp (algebraMap (Polynomial K) (RatFunc K)) =
      (τ : RatFunc K →+* L).comp (algebraMap (Polynomial K) (RatFunc K)) :=
    congrArg AlgHom.toRingHom (Polynomial.algHom_ext
      (f := σ.comp (IsScalarTower.toAlgHom K (Polynomial K) (RatFunc K)))
      (g := τ.comp (IsScalarTower.toAlgHom K (Polynomial K) (RatFunc K))) (by simpa using h))
  exact AlgHom.toRingHom_injective
    (IsLocalization.ringHom_ext (nonZeroDivisors (Polynomial K)) hpoly)

/-- The image of `X` under an injective homomorphism is transcendental. -/
theorem transcendental_apply_X (σ : RatFunc K →ₐ[K] L) (hσ : Function.Injective σ) :
    Transcendental K (σ X) := fun h ↦ transcendental_X ((isAlgebraic_algHom_iff σ hσ).mp h)

end AlgHom

variable {K : Type*} [Field K]

/-- **The image of `X` under an automorphism generates `k(X)`**: the image of `k⟮X⟯ = ⊤` under a
surjective map is everything. -/
theorem adjoin_apply_X_eq_top (σ : RatFunc K ≃ₐ[K] RatFunc K) :
    IntermediateField.adjoin K {σ X} = ⊤ := by
  have hmap : IntermediateField.adjoin K {σ X} =
      (IntermediateField.adjoin K {(X : RatFunc K)}).map (σ : RatFunc K →ₐ[K] RatFunc K) := by
    rw [IntermediateField.adjoin_map, Set.image_singleton]
    rfl
  rw [hmap, adjoin_X, ← AlgHom.fieldRange_eq_map, AlgEquiv.fieldRange_eq_top]

/-- **The automorphism of `k(X)` sending `X` to a transcendental generator `f`**: the
identification of `k(X)` with `k⟮f⟯ = ⊤` provided by transcendence of `f`. -/
noncomputable def algEquivOfAdjoinEqTop {f : RatFunc K} (hf : Transcendental K f)
    (htop : IntermediateField.adjoin K {f} = ⊤) : RatFunc K ≃ₐ[K] RatFunc K :=
  (algEquivOfTranscendental f hf).trans
    ((IntermediateField.equivOfEq htop).trans IntermediateField.topEquiv)

/-- **The automorphism of a generator sends `X` to it**, which is what identifies the
automorphisms with the generators. -/
@[simp]
theorem algEquivOfAdjoinEqTop_X {f : RatFunc K} (hf : Transcendental K f)
    (htop : IntermediateField.adjoin K {f} = ⊤) : algEquivOfAdjoinEqTop hf htop X = f := by
  rw [algEquivOfAdjoinEqTop]
  simp [IntermediateField.equivOfEq_apply, algEquivOfTranscendental_X f hf]

/-- **The automorphisms of `k(X)` over `k` are its transcendental generators**: an automorphism
is determined by, and determines, the image of `X`. -/
noncomputable def autEquivGenerator : (RatFunc K ≃ₐ[K] RatFunc K) ≃
    {f : RatFunc K // Transcendental K f ∧ IntermediateField.adjoin K {f} = ⊤} where
  toFun σ := ⟨σ X, transcendental_apply_X (σ : RatFunc K →ₐ[K] RatFunc K) σ.injective,
    adjoin_apply_X_eq_top σ⟩
  invFun f := algEquivOfAdjoinEqTop f.2.1 f.2.2
  left_inv σ := AlgEquiv.coe_toAlgHom_injective (algHom_ext (by simp))
  right_inv f := Subtype.ext (algEquivOfAdjoinEqTop_X f.2.1 f.2.2)

@[simp]
theorem autEquivGenerator_apply (σ : RatFunc K ≃ₐ[K] RatFunc K) :
    (autEquivGenerator σ : RatFunc K) = σ X := by
  rfl

@[simp]
theorem autEquivGenerator_symm_apply
    (f : {f : RatFunc K // Transcendental K f ∧ IntermediateField.adjoin K {f} = ⊤}) :
    autEquivGenerator.symm f = algEquivOfAdjoinEqTop f.2.1 f.2.2 := by
  rfl

end RatFunc
