/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.KnotTheory.Grid.TorusLink.Rectangle
public import TauCeti.KnotTheory.Grid.TorusLink.Alexander
public import TauCeti.KnotTheory.Grid.Homology.NonTorsion

/-!
# The non-torsion class of a torus knot grid

The `X`-marking state of the standard torus link grid `torusLink p q` is a cycle of the unblocked
grid complex `GC⁻`, and every grid state has an even number of counted rectangles into it
(`even_card_unblockedRectangles_torusLink_X`). By the parity criterion of
`Homology/NonTorsion.lean`, no monomial in the grid variables kills its class
`XMarkingClass` in `GH⁻` (`X_pow_smul_XMarkingClass_torusLink_ne_zero`), for every torus link
grid.

When `p + 1` and `q + 1` are coprime the diagram is a knot grid, `GH⁻` is a module over `K[U]`,
and the class is homogeneous of Alexander degree `p q / 2`, the largest Alexander grading of any
grid state (`alexanderTwoℤ_le_torusLink_X`). Hence `GH⁻` of a torus knot grid is not a torsion
module (`not_isTorsion_unblockedHomology_torusLink`): it contains a free `K[U]`-submodule of
rank one, the tower generated by the class of the `X`-marking state, and the largest Alexander
degree of a homogeneous non-torsion class is `p q / 2` (`two_mul_supNonTorsionDegree_torusLink`).
This is the diagram-level input to the concordance invariant `τ` of Ozsváth--Stipsicz--Szabó,
minus the maximal Alexander grading of a homogeneous non-torsion element of `GH⁻`; neither `τ`
nor any statement about the knot presented by the grid is made here. The two smallest knot
instances are the `5 × 5` trefoil grid, with maximal non-torsion degree `1`
(`supNonTorsionDegree_torusLink_one_two`), and the `7 × 7` grid of the `(3, 4)` torus knot, with
maximal non-torsion degree `3` (`supNonTorsionDegree_torusLink_two_three`).

The results here are statements about the grid diagram. Reading them as invariants of the knot it
presents requires the stabilization and commutation invariance of `GH⁻`, which is not established
here.

## Main results

* `TauCeti.GridDiagram.X_pow_smul_XMarkingClass_torusLink_ne_zero`: no power of a grid variable
  kills the class of the `X`-marking state of a torus link grid.
* `TauCeti.GridDiagram.alexanderℤ_X_mem_nonTorsionDegrees_torusLink` and
  `TauCeti.GridDiagram.not_isTorsion_unblockedHomology_torusLink`: on a torus knot grid the class
  is a homogeneous non-torsion element, so `GH⁻` is not torsion.
* `TauCeti.GridDiagram.two_mul_supNonTorsionDegree_torusLink`: the maximal non-torsion Alexander
  degree of `GH⁻` of a torus knot grid is `p q / 2`.

## References

The computation follows Ozsváth--Stipsicz--Szabó, *Grid Homology for Knots and Links*,
Chapter 6, where the class of this state is shown to generate the tower of `GH⁻` of a torus
knot; the parity argument replaces the appeal to the structure of `GH⁻` made there.
-/

public section

namespace TauCeti

namespace GridDiagram

variable (p q : ℕ)

/-- No power of a grid variable kills the class of the `X`-marking state in the unblocked grid
homology of a torus link grid. -/
theorem X_pow_smul_XMarkingClass_torusLink_ne_zero (R : Type*) [CommRing R] [CharP R 2]
    [Nontrivial R] (i : Fin (p + 1 + (q + 1))) (k : ℕ) :
    (MvPolynomial.X i ^ k : MvPolynomial (Fin (p + 1 + (q + 1))) R) •
      (torusLink p q).XMarkingClass R ≠ 0 :=
  (torusLink p q).X_pow_smul_XMarkingClass_ne_zero R
    (even_card_unblockedRectangles_torusLink_X) i k

variable {p q} (h : (p + 1).Coprime (q + 1)) (K : Type*) [Field K] [CharP K 2]

/-- On a torus knot grid the Alexander grading `p q / 2` of the `X`-marking state is a
non-torsion degree of the `K[U]`-module `GH⁻`: the class of that state is a homogeneous element
that no power of `U` kills. -/
theorem alexanderℤ_X_mem_nonTorsionDegrees_torusLink :
    letI := ((isKnot_torusLink_iff p q).mpr h).unblockedHomologyModule K
    ((isKnot_torusLink_iff p q).mpr h).toOddComponentGridDiagram.alexanderℤ (torusLink p q).X ∈
      (((isKnot_torusLink_iff p q).mpr h).alexanderUnblockedHomologyGrading K).nonTorsionDegrees :=
  ((isKnot_torusLink_iff p q).mpr h).alexanderℤ_X_mem_nonTorsionDegrees
    (even_card_unblockedRectangles_torusLink_X)

/-- **The unblocked grid homology of a torus knot grid is not torsion**: it contains the tower
generated by the class of the `X`-marking state. -/
theorem not_isTorsion_unblockedHomology_torusLink :
    letI := ((isKnot_torusLink_iff p q).mpr h).unblockedHomologyModule K
    ¬Module.IsTorsion (Polynomial K) ((torusLink p q).unblockedHomology K) :=
  ((isKnot_torusLink_iff p q).mpr h).not_isTorsion_unblockedHomology
    (even_card_unblockedRectangles_torusLink_X)

/-- **The maximal non-torsion Alexander degree of a torus knot grid is `p q / 2`**: twice the
supremum of the Alexander degrees of homogeneous non-torsion classes of `GH⁻` is `p q`. -/
theorem two_mul_supNonTorsionDegree_torusLink :
    letI := ((isKnot_torusLink_iff p q).mpr h).unblockedHomologyModule K
    2 * (((isKnot_torusLink_iff p q).mpr h).alexanderUnblockedHomologyGrading K).supNonTorsionDegree
      = p * q := by
  let _ := ((isKnot_torusLink_iff p q).mpr h).unblockedHomologyModule K
  rw [((isKnot_torusLink_iff p q).mpr h).supNonTorsionDegree_alexanderUnblockedHomologyGrading_eq
    (even_card_unblockedRectangles_torusLink_X) (alexanderℤ_le_torusLink_X h)]
  exact two_mul_alexanderℤ_torusLink_X h

/-- On the `5 × 5` trefoil grid the maximal non-torsion Alexander degree of `GH⁻` is `1`. -/
theorem supNonTorsionDegree_torusLink_one_two :
    letI := ((isKnot_torusLink_iff 1 2).mpr (by decide)).unblockedHomologyModule K
    (((isKnot_torusLink_iff 1 2).mpr (by decide)).alexanderUnblockedHomologyGrading K
      ).supNonTorsionDegree = 1 := by
  have h := two_mul_supNonTorsionDegree_torusLink (p := 1) (q := 2) (by decide) K
  omega

/-- On the `7 × 7` grid of the `(3, 4)` torus knot the maximal non-torsion Alexander degree of
`GH⁻` is `3`. -/
theorem supNonTorsionDegree_torusLink_two_three :
    letI := ((isKnot_torusLink_iff 2 3).mpr (by decide)).unblockedHomologyModule K
    (((isKnot_torusLink_iff 2 3).mpr (by decide)).alexanderUnblockedHomologyGrading K
      ).supNonTorsionDegree = 3 := by
  have h := two_mul_supNonTorsionDegree_torusLink (p := 2) (q := 3) (by decide) K
  omega

end GridDiagram

end TauCeti
