/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Node.Differential

/-!
# The Jacobian locus of a nodal chart

For the equation `xy = a`, the first Fitting ideal of the relative differentials is generated
by `x` and `y`. Its quotient is the base ring modulo `a`. Thus the closed subscheme cut out
by the Jacobian ideal is precisely the zero locus of the smoothing parameter, with no
assumption that the base is reduced or that `a` is a non-zero-divisor.

## References

* Stacks Project, Example 55.14.1, Tag 0CDC.
-/

public section

noncomputable section

namespace TauCeti.NodeAlgebra

variable {R : Type*} [CommRing R] (a : R)

/-- The ideal generated by the two coordinates in the nodal equation `xy = a`. -/
def jacobianIdeal : Ideal (NodeAlgebra R a) := Ideal.span {coord a 0, coord a 1}

private lemma coord_mem_jacobianIdeal (i : Fin 2) : coord a i ∈ jacobianIdeal a := by
  fin_cases i <;> exact Ideal.subset_span (by simp)

private lemma algebraMap_a_mem_jacobianIdeal :
    algebraMap R (NodeAlgebra R a) a ∈ jacobianIdeal a := by
  rw [← coord_zero_mul_coord_one]
  exact Ideal.mul_mem_right _ _ (coord_mem_jacobianIdeal a 0)

private def toBaseQuotient :
    (NodeAlgebra R a ⧸ jacobianIdeal a) →ₐ[R] R ⧸ Ideal.span {a} := by
  let e : NodeAlgebra R a →ₐ[R] R ⧸ Ideal.span {a} :=
    lift a 0 0 (by simp)
  refine Ideal.Quotient.liftₐ _ e ?_
  intro z hz
  have h : jacobianIdeal a ≤ RingHom.ker e.toRingHom := by
    apply Ideal.span_le.mpr
    rintro z (rfl | rfl) <;> simp [e]
  exact RingHom.mem_ker.mp (h hz)

private def fromBaseQuotient :
    (R ⧸ Ideal.span {a}) →ₐ[R] NodeAlgebra R a ⧸ jacobianIdeal a := by
  refine Ideal.Quotient.liftₐ _ (Algebra.ofId R _) ?_
  intro z hz
  have ha : (Algebra.ofId R (NodeAlgebra R a ⧸ jacobianIdeal a)) a = 0 := by
    rw [Algebra.ofId_apply, ← Ideal.Quotient.mk_algebraMap]
    exact (Ideal.Quotient.eq_zero_iff_mem).mpr (algebraMap_a_mem_jacobianIdeal a)
  have h : Ideal.span {a} ≤ RingHom.ker (Algebra.ofId R _).toRingHom :=
    (Ideal.span_singleton_le_iff_mem _).mpr (RingHom.mem_ker.mpr ha)
  exact RingHom.mem_ker.mp (h hz)

/-- The Jacobian quotient of `R[x,y]/(xy-a)` is canonically `R/(a)`. -/
def jacobianQuotientEquiv :
    (NodeAlgebra R a ⧸ jacobianIdeal a) ≃ₐ[R] R ⧸ Ideal.span {a} := by
  refine AlgEquiv.ofAlgHom (toBaseQuotient a) (fromBaseQuotient a) ?_ ?_
  · apply (AlgHom.cancel_right (Ideal.Quotient.mkₐ_surjective R (Ideal.span {a}))).mp
    ext
  · apply (AlgHom.cancel_right (Ideal.Quotient.mkₐ_surjective R (jacobianIdeal a))).mp
    apply hom_ext a
    · have h : Ideal.Quotient.mk (jacobianIdeal a) (coord a 0) = 0 :=
        Ideal.Quotient.eq_zero_iff_mem.mpr (coord_mem_jacobianIdeal a 0)
      simp [h]
    · have h : Ideal.Quotient.mk (jacobianIdeal a) (coord a 1) = 0 :=
        Ideal.Quotient.eq_zero_iff_mem.mpr (coord_mem_jacobianIdeal a 1)
      simp [h]

/-- The closed subscheme cut out by the first Fitting ideal of the relative differentials
has coordinate ring `R/(a)`. -/
def differentialFittingQuotientEquiv :
    (NodeAlgebra R a ⧸ fittingIdeal (NodeAlgebra R a) Ω[NodeAlgebra R a⁄R] 1) ≃ₐ[R]
      R ⧸ Ideal.span {a} :=
  (Ideal.quotientEquivAlgOfEq R (fittingIdeal_differential_one a)).trans
    (jacobianQuotientEquiv a)

/-- Both coordinates vanish in the Jacobian quotient. -/
@[simp]
theorem jacobianQuotientEquiv_coord (i : Fin 2) :
    jacobianQuotientEquiv a (Ideal.Quotient.mk (jacobianIdeal a) (coord a i)) = 0 := by
  rw [Ideal.Quotient.eq_zero_iff_mem.mpr (coord_mem_jacobianIdeal a i)]
  exact map_zero _

/-- The inverse equivalence sends a base class to its image in the Jacobian quotient. -/
@[simp]
theorem jacobianQuotientEquiv_symm_mk (r : R) :
    (jacobianQuotientEquiv a).symm (Ideal.Quotient.mk (Ideal.span {a}) r) =
      Ideal.Quotient.mk (jacobianIdeal a) (algebraMap R (NodeAlgebra R a) r) := by
  simp [jacobianQuotientEquiv, fromBaseQuotient]

end TauCeti.NodeAlgebra
