/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.Two.Even.Basic
public import TauCeti.Topology.Algebra.Group.Profinite.Free.SuccessiveApproximation.Tail

/-!
# Labute's intermediate form for the dyadic relators of even rank

Let `F = freeProP 2 (Fin n)` be the free pro-`2` group on an even number `n ≥ 2` of generators and
let `r ∈ λ_1(F)` be a relator with the class of `x₁² (x₁, x₂) (x₃, x₄) ⋯ (x_{n-1}, x_n)` in
`gr_1(F)`, which is the normal form modulo `λ_2(F)` of the relators with `q = 2` of even rank. The
dyadic span statement `gr_{m+1}(F) = Im δ_ρ + ⟨π^{m+1} ξ_i : i ≠ 2⟩` of
`TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.Two.Even.Basic`, whose tails are
spanned by the `2`-powers of every generator but `x₂`, feeds the successive approximation with
tails (`TauCeti.freeProP.exists_continuousMulEquiv_apply_eq_of_range_sup_gradedPowIterSpan_eq_top`)
at the index set `{i | i ≠ 2}`: a continuous automorphism of `F` carries `r` exactly to

  `t₁ * x₁² (x₁, x₂) (x₃, x₄) ⋯ (x_{n-1}, x_n) * t₃ ⋯ t_n`,

with `t_i` in the closed procyclic subgroup generated by `x_i` and in `λ_2(F)`. Writing the tails
as `2`-adic powers `x_i ^ a_i` with `4 ∣ a_i` and merging the tail of `x₁` into the square, this is
the intermediate form

  `x₁^{2+α} (x₁, x₂) * (x₃, x₄) ⋯ (x_{n-1}, x_n) x₃^{α₃} ⋯ x_n^{α_n}`

of Labute's proof of Theorem 3 for `q = 2` and even rank, with `2`-adic exponents `α, α₃, …, α_n`
divisible by `4`. The theorems of this module assume only the degree-one class of `r`; they do not
assume that `r` is the relator of a Demushkin group. Unlike the odd-rank case, the generator `x₁`
carrying the square occurs in a bracket, so its tail cannot be absorbed and is placed in front of
the word, where it changes the exponent `2` of `x₁` into `2 + α`; the tails of `x₃, …, x_n` are
placed behind the word, where they form, together with `(x₃, x₄) ⋯ (x_{n-1}, x_n)`, a tail relator
in the generators `x₃, …, x_n` alone. In Labute's proof, where `r` is the relator of a Demushkin
group, this tail relator is again the relator of a Demushkin group on `n - 2` generators, with
`q`-invariant `2^f` for some `f ≥ 2` or `f = ∞`, and its normalisation to
`x₃^{2^f} (x₃, x₄) ⋯ (x_{n-1}, x_n)` is the case `q ≠ 2` of the normal-form theorem. Neither of
these two facts is proved here.

## Main results

* `exists_continuousMulEquiv_apply_eq_padicPow_mul_demushkinWordNeTwo_mul_padicPow`, in the
  namespace `TauCeti.freeProP`: the relator is carried to
  `x₁ ^ a₁ * x₁² (x₁, x₂) ⋯ (x_{n-1}, x_n) * x₃ ^ a₃ ⋯ x_n ^ a_n`, with `2`-adic exponents `a_i`
  divisible by `4`.
* `TauCeti.freeProP.exists_continuousMulEquiv_apply_eq_padicPow_mul_labuteComm_mul`: **Labute's
  intermediate form** `x₁^{2+α} (x₁, x₂) * ((x₃, x₄) ⋯ (x_{n-1}, x_n) x₃^{α₃} ⋯ x_n^{α_n})`, the
  same equation with the square merged into the tail of `x₁` and the tail relator on `x₃, …, x_n`
  split off.

## References

* J. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), 106–132, §3,
  proof of Theorem 3, case (3).
-/

public section

namespace TauCeti

namespace freeProP

variable {n : ℕ}

/-- **The even-rank dyadic relators, up to tails.** Let `n ≥ 2` be even and let `r ∈ λ_1(F)` be a
relator of the free pro-`2` group `F` on `n` generators with the class of
`x₁² (x₁, x₂) (x₃, x₄) ⋯ (x_{n-1}, x_n)` in `gr_1(F)`. Then a continuous automorphism carries `r`
to that word preceded by a `2`-adic power `x₁ ^ a₁` of the first generator and followed by `2`-adic
powers `x_i ^ a_i` of the generators `x₃, …, x_n`, where every exponent `a_i` is divisible by
`4`. -/
theorem exists_continuousMulEquiv_apply_eq_padicPow_mul_demushkinWordNeTwo_mul_padicPow
    (hn : Even n) (hn0 : 0 < n) (r : pLowerCentralSeries 2 (freeProP 2 (Fin n)) 1)
    (h : gradedMk 2 (freeProP 2 (Fin n)) 1 r = gradedMk 2 (freeProP 2 (Fin n)) 1
      ⟨demushkinWordNeTwo 2 n (freeProPGen 2 n),
        demushkinWordNeTwo_mem_pLowerCentralSeries_one dvd_rfl n _⟩) :
    ∃ (e : freeProP 2 (Fin n) ≃ₜ* freeProP 2 (Fin n)) (a : Fin n → ℤ_[2]),
      (∀ i, (4 : ℤ_[2]) ∣ a i) ∧
        e r = (isProP_freeProP 2 (Fin n)).padicPow (of ⟨0, hn0⟩) (a ⟨0, hn0⟩) *
          demushkinWordNeTwo 2 n (freeProPGen 2 n) *
          (((List.finRange n).drop 2).map fun i ↦
            (isProP_freeProP 2 (Fin n)).padicPow (of i) (a i)).prod := by
  have : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  have hn2 : 2 ≤ n := by
    obtain ⟨k, hk⟩ := hn
    omega
  -- The class of `r` is also the class of the even word at `a = 0` and `f = 2`, at which the span
  -- statement is stated.
  have hcls : gradedMk 2 (freeProP 2 (Fin n)) 1 r = gradedMk 2 (freeProP 2 (Fin n)) 1
      ⟨demushkinWordTwoEven 0 2 n (freeProPGen 2 n),
        demushkinWordTwoEven_mem_pLowerCentralSeries_one (dvd_zero 2) two_pos n _⟩ :=
    h.trans
      (gradedMk_demushkinWordTwoEven_eq_gradedMk_demushkinWordNeTwo (dvd_zero 2) le_rfl hn2 _).symm
  have hspan : ∀ k (hk : 1 ≤ k), LinearMap.range (basisModificationDelta 2 (Fin n) hk
      (gradedMk 2 (freeProP 2 (Fin n)) 1 r)) ⊔
        gradedPowIterSpan 2 (Fin n) {i | (i : ℕ) ≠ 1} (k + 1) = ⊤ := by
    intro k hk
    rw [hcls]
    exact range_basisModificationDelta_sup_gradedPowIterSpan_eq_top_demushkinWordTwoEven hn hn0
      (dvd_zero 4) le_rfl hk
  -- The tails sit on `x₁`, placed in front, and on `x₃, …, x_n`, placed behind: the entries of
  -- the list of generators after the first two.
  obtain ⟨k, rfl⟩ : ∃ k, n = k + 2 := ⟨n - 2, by omega⟩
  have hdrop : (List.finRange (k + 2)).drop 2 = (List.finRange k).map (Fin.succ ∘ Fin.succ) := by
    simp only [List.finRange_succ, List.map_cons, List.drop_succ_cons, List.drop_zero,
      List.map_map]
  have hnd : ([(⟨0, hn0⟩ : Fin (k + 2))] ++ (List.finRange (k + 2)).drop 2).Nodup := by
    rw [hdrop, List.singleton_append, List.nodup_cons]
    refine ⟨fun hmem ↦ ?_, (List.nodup_finRange k).map
      ((Fin.succ_injective _).comp (Fin.succ_injective _))⟩
    obtain ⟨j, -, hj⟩ := List.mem_map.mp hmem
    exact Fin.succ_ne_zero _ hj
  have hl : ∀ i ∈ ({i | (i : ℕ) ≠ 1} : Set (Fin (k + 2))),
      i ∈ [(⟨0, hn0⟩ : Fin (k + 2))] ++ (List.finRange (k + 2)).drop 2 := by
    intro i hi
    rw [Set.mem_ofPred_eq] at hi
    rw [hdrop, List.singleton_append, List.mem_cons, List.mem_map]
    rcases Nat.lt_or_ge (i : ℕ) 2 with hi2 | hi2
    · exact Or.inl (Fin.eq_mk_iff_val_eq.mpr (by omega))
    · exact Or.inr ⟨⟨i - 2, by omega⟩, List.mem_finRange _,
        Fin.ext (by simp only [Function.comp_apply, Fin.val_succ]; omega)⟩
  obtain ⟨e, t, ht, ht2, he⟩ :=
    exists_continuousMulEquiv_apply_eq_of_range_sup_gradedPowIterSpan_eq_top r _ h _
      [⟨0, hn0⟩] ((List.finRange (k + 2)).drop 2) hnd hl hspan
  choose a hdiv ha using fun i ↦
    (mem_topologicalClosure_closure_singleton_inf_pLowerCentralSeries_iff i (t i) 2).1
      ⟨ht i, ht2 i⟩
  refine ⟨e, a, fun i ↦ ?_, ?_⟩
  · have hi := hdiv i
    norm_num at hi ⊢
    exact hi
  · simpa only [List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one, ha] using he

/-- **Labute's intermediate form for the dyadic relators of even rank.** Let `n ≥ 2` be even and
let `r ∈ λ_1(F)` be a relator of the free pro-`2` group `F` on `n` generators with the class of
`x₁² (x₁, x₂) (x₃, x₄) ⋯ (x_{n-1}, x_n)` in `gr_1(F)`. Then a continuous automorphism carries `r`
to `x₁^{2+α} (x₁, x₂) * ((x₃, x₄) ⋯ (x_{n-1}, x_n) * x₃^{α₃} ⋯ x_n^{α_n})`, with `2`-adic exponents
`α, α₃, …, α_n` divisible by `4`; the second factor is a word in the generators `x₃, …, x_n`,
written on the tuple of generators shifted by two. -/
theorem exists_continuousMulEquiv_apply_eq_padicPow_mul_labuteComm_mul
    (hn : Even n) (hn0 : 0 < n) (r : pLowerCentralSeries 2 (freeProP 2 (Fin n)) 1)
    (h : gradedMk 2 (freeProP 2 (Fin n)) 1 r = gradedMk 2 (freeProP 2 (Fin n)) 1
      ⟨demushkinWordNeTwo 2 n (freeProPGen 2 n),
        demushkinWordNeTwo_mem_pLowerCentralSeries_one dvd_rfl n _⟩) :
    ∃ (e : freeProP 2 (Fin n) ≃ₜ* freeProP 2 (Fin n)) (α : ℤ_[2]) (a : Fin n → ℤ_[2]),
      (4 : ℤ_[2]) ∣ α ∧ (∀ i, (4 : ℤ_[2]) ∣ a i) ∧
        e r = (isProP_freeProP 2 (Fin n)).padicPow (freeProPGen 2 n 0) (2 + α) *
          labuteComm (freeProPGen 2 n 0) (freeProPGen 2 n 1) *
          (demushkinWordNeTwo 0 (n - 2) (fun i ↦ freeProPGen 2 n (i + 2)) *
            (((List.finRange n).drop 2).map fun i ↦
              (isProP_freeProP 2 (Fin n)).padicPow (of i) (a i)).prod) := by
  have : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  have hn2 : 2 ≤ n := by
    obtain ⟨k, hk⟩ := hn
    omega
  obtain ⟨e, a, hdiv, he⟩ :=
    exists_continuousMulEquiv_apply_eq_padicPow_mul_demushkinWordNeTwo_mul_padicPow hn hn0 r h
  refine ⟨e, a ⟨0, hn0⟩, a, hdiv _, hdiv, ?_⟩
  rw [he, demushkinWordNeTwo_eq_pow_mul_labuteComm_mul 2 hn2, freeProPGen_of_lt 2 hn0, add_comm,
    (isProP_freeProP 2 (Fin n)).padicPow_add, (isProP_freeProP 2 (Fin n)).padicPow_ofNat]
  simp only [mul_assoc]

end freeProP

end TauCeti
