/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.KernelSpan
public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.Prescription
public import TauCeti.Topology.Algebra.Group.Profinite.Free.Prescription
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.CrossedHom

/-!
# The span statement and the graded functionals at `x₁² (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯`

Let `F = freeProP 2 (Fin n)` with `n ≥ 4` even, let
`r = x₁² (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (x_{n-1}, x_n)` be the normal-form word
`TauCeti.demushkinWordTwoEven 0 f n` with `f ≥ 2` on the generators of `F`, and let `ρ ∈ gr_1(F)`
be its class. Its orientation is the character `χ : F → ℤ_2ˣ` with `χ(x₂) = -1`,
`χ(x₄) = (1 - 2^f)⁻¹` and `χ(x_i) = 1` otherwise, whose image is `{±1} × U^(f)`. Throughout,
indices in the Lean statements are the `0`-based indices of `Fin n`: `x₂` is `of ⟨1, _⟩` and `x₄`
is `of ⟨3, _⟩`.

For `f ≥ 2` the factor `x₃^{2^f}` lies in `λ_2(F)`, so `ρ` is also the class of the `q ≠ 2` word
`x₁² (x₁, x₂)(x₃, x₄) ⋯` (`TauCeti.gradedMk_demushkinWordTwoEven_eq_gradedMk_demushkinWordNeTwo`),
and the basis-modification map `δ_ρ` is the one of that word. What changes is the kernel of the
orientation. Its intersection with `λ_1(F)` is the intersection with `λ_1(F)` of the kernel `X` of
the exponent sum at `x₄`, because `χ(x₂) = -1` has order two and `λ_1(F)` is generated by squares
and commutators
(`ContinuousMonoidHom.apply_eq_one_of_mem_exponentSumKer_of_mem_pLowerCentralSeries_one`). In
`gr(X)` the generator class `ξ₂` is reached only through the derivative `∂₁ ρ = ξ₁ + ξ₂` at the
`2`-power generator `x₁`, so it is the exceptional generator of the constrained span statement of
`Free/ExponentSumKernel.lean`: Labute's Lemma 3 for this family reads, for every `m ≥ 1`,

  `gr_{m+1}(X) = δ_ρ(gr_m(X)^n) + ⟨π^{m+1} ξ_j : j ≠ 2, 4⟩ + 𝔽_2 π^m [ξ₂, ξ₄]`

(`gradedPieceOf_exponentSumKer_demushkinWordTwoEven_eq_map_basisModificationDelta_sup` in
`TauCeti.freeProP`). The extra spanning vector `π^m [ξ₂, ξ₄]` is the class of `(x₂, x₄)^{2^m}`; it
is not in the image of `δ_ρ`, because the graded functional `Δ_{m+1}(D₄)` of the crossed
homomorphism `D₄` for `χ` with `D₄(x_j) = δ_{4j}` takes the value `1` on it
(`TauCeti.freeProP.gradedFunctional_crossedHom_gradedPowIterBracket_of_apply_eq_neg_one`), while
every graded functional of a crossed homomorphism for `χ` vanishes on `δ_ρ(gr_m(X)^n)`
(`TauCeti.freeProP.gradedFunctional_basisModificationDelta_demushkinWordTwoEven_eq_zero`). Hence a
class of `gr_{m+1}(X)` lies in `δ_ρ(gr_m(X)^n)` exactly when it is killed by every `Δ_{m+1}(D_i)`
with `i ≠ 2`
(`mem_map_basisModificationDelta_demushkinWordTwoEven_iff_forall_gradedFunctional_eq_zero` in
`TauCeti.freeProP`). This is Labute's Lemma 4 for the second even-rank dyadic family, the finite
step of the successive approximation showing that a Demushkin group at `p = 2` of even rank whose
orientation has image `{±1} × U^(f)` is presented by this word: the deviation of its relator from
the word, once it lies in `gr_{m+1}(X)` and is killed by all crossed homomorphisms for `χ`, is
removed by a basis correction inside `X`.

## Main results

All results are in the namespace `TauCeti.freeProP`.

* `gradedPieceOf_exponentSumKer_demushkinWordTwoEven_eq_map_basisModificationDelta_sup`: **the
  constrained span statement at this normal form**, with the exceptional spanning vector
  `π^m [ξ₂, ξ₄]`.
* `gradedFunctional_basisModificationDelta_demushkinWordTwoEven_eq_zero`: the graded functional of
  a crossed homomorphism for the orientation vanishes on `δ_ρ(gr_m(X)^n)`.
* `gradedFunctional_crossedHom_gradedPowIterBracket_of_apply_eq_neg_one`: the graded functionals
  `Δ_{m+1}(D_i)`, `i ≠ 2`, read off the coefficient of `π^m [ξ₂, ξ₄]`.
* `mem_map_basisModificationDelta_demushkinWordTwoEven_iff_forall_gradedFunctional_eq_zero`: **a
  class of `gr_{m+1}(X)` lies in `δ_ρ(gr_m(X)^n)` exactly when the graded functionals of the `D_i`,
  `i ≠ 2`, kill it.**

## References

* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), 106–132, §4.2,
  Lemmas 1–4 and the proof of Theorem 6.
-/

public section

namespace TauCeti

open Subgroup Submodule
open scoped commutatorElement

namespace freeProP

variable {n : ℕ}

/-! ### The constrained span statement -/

/-- **The constrained span statement at the normal form `x₁² (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯`**
(Labute, §4.2, Lemma 3). For `n ≥ 4` even, `f ≥ 2`, the class `ρ` of the word, `X` the kernel of
the exponent sum at the generator `x_3` (in the `0`-based indexing of `Fin n`) and every `m ≥ 1`,

  `gr_{m+1}(X) = δ_ρ(gr_m(X)^n) + ⟨π^{m+1} ξ_j : j ≠ 1, 3⟩ + 𝔽_2 π^m [ξ_1, ξ_3]`.

This is the span statement on which the uniqueness argument for the dyadic even-rank Demushkin
groups with orientation image `{±1} × U^(f)` runs: the basis corrections must be taken inside the
kernel of the orientation, which meets `λ_1(F)` in `X ∩ λ_1(F)`. -/
theorem gradedPieceOf_exponentSumKer_demushkinWordTwoEven_eq_map_basisModificationDelta_sup
    (hn : Even n) (hn3 : 3 < n) {f : ℕ} (hf : 2 ≤ f) {m : ℕ} (hm : 1 ≤ m) :
    gradedPieceOf 2 (exponentSumKer 2 (Fin n) ⟨3, hn3⟩) (m + 1) =
      (Submodule.pi Set.univ
          fun _ : Fin n ↦ gradedPieceOf 2 (exponentSumKer 2 (Fin n) ⟨3, hn3⟩) m).map
        (basisModificationDelta 2 (Fin n) hm (gradedMk 2 (freeProP 2 (Fin n)) 1
          ⟨demushkinWordTwoEven 0 f n (freeProPGen 2 n),
            demushkinWordTwoEven_mem_pLowerCentralSeries_one (dvd_zero 2) (by omega) n _⟩)) ⊔
      span (ZMod 2) (Set.range fun a : {a : Fin n // a ≠ ⟨3, hn3⟩ ∧ a ≠ ⟨1, by omega⟩} ↦
        gradedPowIter 2 (freeProP 2 (Fin n)) (m + 1)
          (gradedMkZero 2 (freeProP 2 (Fin n)) (of a))) ⊔
      span (ZMod 2) {(gradedPowIterBracket 2 (freeProP 2 (Fin n)) m (of ⟨1, by omega⟩)
        (of ⟨3, hn3⟩))} := by
  classical
  -- For `f ≥ 2` the class of the word is that of `x₁² (x₁, x₂)(x₃, x₄) ⋯`.
  have hρ : gradedMk 2 (freeProP 2 (Fin n)) 1
      ⟨demushkinWordTwoEven 0 f n (freeProPGen 2 n),
        demushkinWordTwoEven_mem_pLowerCentralSeries_one (dvd_zero 2) (by omega) n _⟩ =
      gradedMk 2 (freeProP 2 (Fin n)) 1 ⟨demushkinWordNeTwo 2 n (freeProPGen 2 n),
        demushkinWordNeTwo_mem_pLowerCentralSeries_one dvd_rfl n _⟩ :=
    gradedMk_demushkinWordTwoEven_eq_gradedMk_demushkinWordNeTwo (dvd_zero 2) hf (by omega) _
  rw [hρ]
  -- `∂_0 ρ = ξ_0 + ξ_1` and `∂_1 ρ = -ξ_0`, so `ξ_1 = ∂_0 ρ + ∂_1 ρ`.
  have hd0 := degreeOneDeriv_gradedMk_demushkinWordNeTwo_zero (p := 2) (n := n) dvd_rfl (by omega)
  have hd1 : degreeOneDeriv 2 (Fin n) ⟨1, by omega⟩ (gradedMk 2 (freeProP 2 (Fin n)) 1
      ⟨demushkinWordNeTwo 2 n (freeProPGen 2 n),
        demushkinWordNeTwo_mem_pLowerCentralSeries_one dvd_rfl n _⟩) =
      -gradedMkZero 2 (freeProP 2 (Fin n)) (of ⟨0, by omega⟩) := by
    have hn0 : 0 < n := by omega
    have h := degreeOneDeriv_gradedMk_demushkinWordNeTwo_odd (p := 2) (n := n) dvd_rfl (a := 0)
      (by omega)
    simpa only [Nat.mul_zero, Nat.zero_add, freeProPGen_of_lt 2 hn0] using h
  rw [Nat.div_self two_pos, Nat.choose_self, one_nsmul, one_nsmul] at hd0
  -- The implicit arguments are supplied explicitly: inferring them by unification is slow.
  refine gradedPieceOf_exponentSumKer_eq_map_basisModificationDelta_sup_gradedPowIterBracket_of_ne
    (p := 2) (X := Fin n) (i₀ := ⟨0, by omega⟩) (i₁ := ⟨3, hn3⟩) (i₂ := ⟨1, by omega⟩)
    (ρ := gradedMk 2 (freeProP 2 (Fin n)) 1 ⟨demushkinWordNeTwo 2 n (freeProPGen 2 n),
      demushkinWordNeTwo_mem_pLowerCentralSeries_one dvd_rfl n _⟩) hm
    ((span_range_degreeOneDeriv_eq_top_iff_nondegenerate_degreeOneForm _).2
      (nondegenerate_degreeOneForm_demushkinWordNeTwo hn dvd_rfl))
    (fun k hk ↦ by
      rw [degreeOneBasis_repr_gradedMk_demushkinWordNeTwo_inl dvd_rfl k,
        ite_eq_right fun h ↦ hk (Fin.ext h)])
    (fun j _ hj ↦ exists_sum_smul_degreeOneDeriv_gradedMk_demushkinWordNeTwo_eq hn dvd_rfl
      (by omega) j hj)
    ⟨Pi.single ⟨0, by omega⟩ 1 + Pi.single ⟨1, by omega⟩ 1, ?_, ?_⟩
    (Fin.ne_of_val_ne (by norm_num))
  · simp only [Pi.add_apply, add_smul, Finset.sum_add_distrib, Pi.single_apply, ite_smul, one_smul,
      zero_smul, Finset.sum_ite_eq', Finset.mem_univ, ite_true, hd0, hd1]
    abel
  · rw [degreeOneBasis_repr_gradedMk_demushkinWordNeTwo_inl dvd_rfl]
    simp

/-! ### The graded functionals of the orientation -/

variable {χ : freeProP 2 (Fin n) →ₜ* ℤ_[2]ˣ}

/-- **A crossed homomorphism for the orientation kills the relator moved by a basis modification
inside the kernel of the character.** For `n ≥ 4`, `χ` with `χ(x₂) = -1`, `χ(x₄) (1 - 2^f) = 1` and
`χ(x_i) = 1` for `i ≠ 2, 4`, a crossed homomorphism `F` for `χ`, and a family `w` of elements of
`λ_m(F)` on which `χ` is trivial, `F (r⁻¹ · θ_w(r)) = 0` for `r = x₁² (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯`:
the character takes the same values on the modified tuple `(x_i w_i)` as on `(x_i)`, and at those
values a crossed homomorphism kills the word. -/
theorem _root_.TauCeti.IsCrossedHom.map_inv_mul_basisModification_demushkinWordTwoEven_eq_zero
    (hn3 : 3 < n) {f : ℕ} (h₁ : χ (of ⟨1, by omega⟩) = -1)
    (h₃ : (χ (of ⟨3, hn3⟩) : ℤ_[2]) * (1 - 2 ^ f) = 1)
    (h : ∀ j : Fin n, j ≠ ⟨1, by omega⟩ → j ≠ ⟨3, hn3⟩ → χ (of j) = 1)
    {F : freeProP 2 (Fin n) → ℤ_[2]} (hF : IsCrossedHom χ F) {m : ℕ}
    (w : Fin n → pLowerCentralSeries 2 (freeProP 2 (Fin n)) m) (hw : ∀ i, χ (w i) = 1) :
    F ((demushkinWordTwoEven 0 f n (freeProPGen 2 n))⁻¹ *
      basisModification w (demushkinWordTwoEven 0 f n (freeProPGen 2 n))) = 0 := by
  -- The values of `χ` on the generator tuple and on the modified tuple.
  have hgen : ∀ i, i ≠ 1 → i ≠ 3 → χ (freeProPGen 2 n i) = 1 := fun i hi₁ hi₃ ↦ by
    by_cases hi' : i < n
    · rw [freeProPGen_of_lt 2 hi']
      exact h _ (fun e ↦ hi₁ (congrArg Fin.val e)) fun e ↦ hi₃ (congrArg Fin.val e)
    · rw [freeProPGen_eq_one_of_le 2 (not_lt.1 hi'), _root_.map_one]
  have hgen₁ : (χ (freeProPGen 2 n 1) : ℤ_[2]) * (1 + ((0 : ℕ) : ℤ_[2])) = -1 := by
    rw [freeProPGen_of_lt 2 (by omega), h₁]
    simp
  have hgen₃ : (χ (freeProPGen 2 n 3) : ℤ_[2]) * (1 - 2 ^ f) = 1 := by
    rw [freeProPGen_of_lt 2 hn3]
    exact h₃
  have hθ : ∀ i, χ (basisModification w (freeProPGen 2 n i)) = χ (freeProPGen 2 n i) := fun i ↦ by
    by_cases hi' : i < n
    · rw [freeProPGen_of_lt 2 hi', basisModification_of, _root_.map_mul, hw, mul_one]
    · rw [freeProPGen_eq_one_of_le 2 (not_lt.1 hi'), _root_.map_one]
  have hr : F (demushkinWordTwoEven 0 f n (freeProPGen 2 n)) = 0 :=
    hF.map_demushkinWordTwoEven_eq_zero (by omega) hgen₁ hgen₃ hgen
  have hθr : F (basisModification w (demushkinWordTwoEven 0 f n (freeProPGen 2 n))) = 0 := by
    rw [TauCeti.map_demushkinWordTwoEven]
    exact hF.map_demushkinWordTwoEven_eq_zero (by omega)
      (x := ⇑(basisModification w) ∘ freeProPGen 2 n)
      (by rw [Function.comp_apply, hθ]; exact hgen₁) (by rw [Function.comp_apply, hθ]; exact hgen₃)
      fun i hi₁ hi₃ ↦ by rw [Function.comp_apply, hθ]; exact hgen i hi₁ hi₃
  rw [hF.map_mul, hθr, mul_zero, zero_add, hF.map_inv, hr, mul_zero]

/-- **The graded functional of a crossed homomorphism for the orientation vanishes on
`δ_ρ(gr_m(X)^n)`** (Labute, §4.2, Lemma 4 (2)). For `n ≥ 4`, `f ≥ 1`, `χ` with `χ(x₂) = -1`,
`χ(x₄) (1 - 2^f) = 1` and `χ(x_i) = 1` for `i ≠ 2, 4`, a continuous crossed homomorphism `F` for
`χ`, the class `ρ` of `r = x₁² (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯` and a family `v` of classes in
`gr_m(X)`, where `X` is the kernel of the exponent sum at `x₄`, `Δ_{m+1}(F) (δ_ρ(v)) = 0`:
`δ_ρ(v)` is the class of `r⁻¹ · θ_w(r)` for a basis modification `θ_w` by elements of
`X ∩ λ_m(F) ≤ ker χ`, which `F` kills. -/
@[simp]
theorem gradedFunctional_basisModificationDelta_demushkinWordTwoEven_eq_zero (hn3 : 3 < n)
    {f : ℕ} (hf : 0 < f) {m : ℕ} (hm : 1 ≤ m) (h₁ : χ (of ⟨1, by omega⟩) = -1)
    (h₃ : (χ (of ⟨3, hn3⟩) : ℤ_[2]) * (1 - 2 ^ f) = 1)
    (h : ∀ j : Fin n, j ≠ ⟨1, by omega⟩ → j ≠ ⟨3, hn3⟩ → χ (of j) = 1)
    {F : freeProP 2 (Fin n) → ℤ_[2]} (hF : IsCrossedHom χ F) (hFc : Continuous F)
    {v : Fin n → gradedPiece 2 (freeProP 2 (Fin n)) m}
    (hv : ∀ i, v i ∈ gradedPieceOf 2 (exponentSumKer 2 (Fin n) ⟨3, hn3⟩) m) :
    hF.gradedFunctional ((isProP_freeProP 2 (Fin n)).mem_unitsPrincipal_one χ) hFc (m + 1)
      (basisModificationDelta 2 (Fin n) hm (gradedMk 2 (freeProP 2 (Fin n)) 1
        ⟨demushkinWordTwoEven 0 f n (freeProPGen 2 n),
          demushkinWordTwoEven_mem_pLowerCentralSeries_one (dvd_zero 2) (by omega) n _⟩) v) =
      0 := by
  choose w hwX hwv using fun i ↦ mem_gradedPieceOf_iff.1 (hv i)
  have hv' : v = fun i ↦ gradedMk 2 (freeProP 2 (Fin n)) m (w i) := funext fun i ↦ (hwv i).symm
  -- `χ` is trivial on `X ∩ λ_m(F)`: its values at the generators other than `x₄` are `±1`.
  have hw (i : Fin n) : χ (w i) = 1 := by
    refine χ.apply_eq_one_of_mem_exponentSumKer_of_mem_pLowerCentralSeries_one (fun j hj ↦ ?_)
      (hwX i) (pLowerCentralSeries_antitone hm (w i).2)
    by_cases hj₁ : j = ⟨1, by omega⟩
    · rw [hj₁, h₁, neg_one_sq]
    · rw [h j hj₁ hj, one_pow]
  rw [hv', ← gradedMk_inv_mul_basisModification hm w, hF.gradedFunctional_gradedMk _ _ _ _ (c := 0)
    (by
      rw [mul_zero]
      exact hF.map_inv_mul_basisModification_demushkinWordTwoEven_eq_zero hn3 h₁ h₃ h w hw),
    map_zero]

/-- **The graded functionals of the orientation on the exceptional class `π^m [ξ₂, ξ₄]`** (Labute,
§4.2, Lemma 4 (3)). For `χ` with `χ(x₂) = -1`, `χ(x₄) (1 - 2^f) = 1` and the crossed homomorphism
`D_i` for `χ` with `D_i(x_j) = δ_{ij}`, `i ≠ 2`, the value of `Δ_{m+1}(D_i)` on `π^m [ξ₂, ξ₄]`, the
class of `(x₂, x₄)^{2^m}`, is `1` for `i = 4` and `0` otherwise: `D_i (x₂, x₄) = -2 D_i(x₄)` up to
a unit, because `χ(x₂) - 1 = -2`. -/
theorem gradedFunctional_crossedHom_gradedPowIterBracket_of_apply_eq_neg_one (hn3 : 3 < n)
    (h₁ : χ (of ⟨1, by omega⟩) = -1) (m : ℕ) {i : Fin n} (hi : i ≠ ⟨1, by omega⟩) :
    (isCrossedHom_crossedHom χ (Pi.single i 1)).gradedFunctional
        ((isProP_freeProP 2 (Fin n)).mem_unitsPrincipal_one χ) (continuous_crossedHom χ _) (m + 1)
        (gradedPowIterBracket 2 (freeProP 2 (Fin n)) m (of ⟨1, by omega⟩) (of ⟨3, hn3⟩)) =
      if i = ⟨3, hn3⟩ then 1 else 0 := by
  classical
  have hD : crossedHom χ (Pi.single i 1) ⁅(of ⟨1, by omega⟩ : freeProP 2 (Fin n)), of ⟨3, hn3⟩⁆ =
      (2 : ℤ_[2]) ^ 1 * -(if i = ⟨3, hn3⟩ then 1 else 0) := by
    rw [(isCrossedHom_crossedHom χ _).map_commutatorElement, crossedHom_of, crossedHom_of, h₁,
      Pi.single_apply, Pi.single_apply, ite_eq_right (Ne.symm hi), mul_zero, sub_zero,
      Units.val_neg, Units.val_one, pow_one]
    by_cases h3 : i = ⟨3, hn3⟩
    · rw [ite_eq_left h3.symm, ite_eq_left h3]
      ring
    · rw [ite_eq_right (Ne.symm h3), ite_eq_right h3]
      ring
  rw [IsCrossedHom.gradedFunctional_gradedPowIterBracket, gradedBracket_gradedMkZero,
    (isCrossedHom_crossedHom χ _).gradedFunctional_gradedMk _ _ 1 _ hD]
  by_cases h3 : i = ⟨3, hn3⟩
  · rw [ite_eq_left h3, ite_eq_left h3, map_neg, map_one]
    decide
  · rw [ite_eq_right h3, ite_eq_right h3, neg_zero, map_zero]

/-- **The image of `δ_ρ` on `gr_m(X)^n` is the common kernel in `gr_{m+1}(X)` of the graded
functionals of the orientation** (Labute, §4.2, Lemma 4 (4)). Let `n ≥ 4` be even, `f ≥ 2`, `ρ`
the class of `x₁² (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯`, `χ` a continuous character with `χ(x₂) = -1`,
`χ(x₄) (1 - 2^f) = 1` and `χ(x_i) = 1` for `i ≠ 2, 4`, and `X` the kernel of the exponent sum at
`x₄`. For `m ≥ 1`, a class `ε ∈ gr_{m+1}(X)` lies in `δ_ρ(gr_m(X)^n)` exactly when
`Δ_{m+1}(D_i) ε = 0` for every `i ≠ 2`, where `D_i` is the crossed homomorphism for `χ` with
`D_i(x_j) = δ_{ij}`: the functionals `Δ_{m+1}(D_i)`, `i ≠ 2, 4`, read off the coefficients of the
tail `π^{m+1} ξ_i`, and `Δ_{m+1}(D₄)` that of the exceptional class `π^m [ξ₂, ξ₄]`. -/
theorem mem_map_basisModificationDelta_demushkinWordTwoEven_iff_forall_gradedFunctional_eq_zero
    (hn : Even n) (hn3 : 3 < n) {f : ℕ} (hf : 2 ≤ f) {m : ℕ} (hm : 1 ≤ m)
    (h₁ : χ (of ⟨1, by omega⟩) = -1) (h₃ : (χ (of ⟨3, hn3⟩) : ℤ_[2]) * (1 - 2 ^ f) = 1)
    (h : ∀ j : Fin n, j ≠ ⟨1, by omega⟩ → j ≠ ⟨3, hn3⟩ → χ (of j) = 1)
    {ε : gradedPiece 2 (freeProP 2 (Fin n)) (m + 1)}
    (hε : ε ∈ gradedPieceOf 2 (exponentSumKer 2 (Fin n) ⟨3, hn3⟩) (m + 1)) :
    ε ∈ (Submodule.pi Set.univ
        fun _ : Fin n ↦ gradedPieceOf 2 (exponentSumKer 2 (Fin n) ⟨3, hn3⟩) m).map
      (basisModificationDelta 2 (Fin n) hm (gradedMk 2 (freeProP 2 (Fin n)) 1
        ⟨demushkinWordTwoEven 0 f n (freeProPGen 2 n),
          demushkinWordTwoEven_mem_pLowerCentralSeries_one (dvd_zero 2) (by omega) n _⟩)) ↔
      ∀ i : Fin n, i ≠ ⟨1, by omega⟩ →
        (isCrossedHom_crossedHom χ (Pi.single i 1)).gradedFunctional
          ((isProP_freeProP 2 (Fin n)).mem_unitsPrincipal_one χ) (continuous_crossedHom χ _)
          (m + 1) ε = 0 := by
  classical
  constructor
  · rintro ⟨v, hv, rfl⟩ i -
    exact gradedFunctional_basisModificationDelta_demushkinWordTwoEven_eq_zero hn3 (by omega) hm
      h₁ h₃ h _ _ fun j ↦ Submodule.mem_pi.1 hv j (Set.mem_univ j)
  · intro hΔ
    -- By the constrained span statement,
    -- `ε = δ_ρ(v) + Σ_{a ≠ 2, 4} c_a π^{m+1} ξ_a + d π^m [ξ₂, ξ₄]`.
    rw [gradedPieceOf_exponentSumKer_demushkinWordTwoEven_eq_map_basisModificationDelta_sup hn hn3
      hf hm] at hε
    obtain ⟨_, hyz, _, hb, rfl⟩ := Submodule.mem_sup.1 hε
    obtain ⟨y, hy, z, hz, rfl⟩ := Submodule.mem_sup.1 hyz
    obtain ⟨c, rfl⟩ := (mem_span_range_iff_exists_fun (ZMod 2)).1 hz
    obtain ⟨d, rfl⟩ := mem_span_singleton.1 hb
    obtain ⟨v, hv, rfl⟩ := Submodule.mem_map.1 hy
    -- The value of `Δ_{m+1}(D_i)` on the three summands.
    have hΔv (i : Fin n) : (isCrossedHom_crossedHom χ (Pi.single i 1)).gradedFunctional
        ((isProP_freeProP 2 (Fin n)).mem_unitsPrincipal_one χ) (continuous_crossedHom χ _) (m + 1)
        (basisModificationDelta 2 (Fin n) hm (gradedMk 2 (freeProP 2 (Fin n)) 1
          ⟨demushkinWordTwoEven 0 f n (freeProPGen 2 n),
            demushkinWordTwoEven_mem_pLowerCentralSeries_one (dvd_zero 2) (by omega) n _⟩) v) = 0 :=
      gradedFunctional_basisModificationDelta_demushkinWordTwoEven_eq_zero hn3 (by omega) hm h₁ h₃
        h _ _ fun j ↦ Submodule.mem_pi.1 hv j (Set.mem_univ j)
    have hΔT (i : Fin n) : (isCrossedHom_crossedHom χ (Pi.single i 1)).gradedFunctional
        ((isProP_freeProP 2 (Fin n)).mem_unitsPrincipal_one χ) (continuous_crossedHom χ _) (m + 1)
        (∑ a : {a : Fin n // a ≠ ⟨3, hn3⟩ ∧ a ≠ ⟨1, by omega⟩}, c a •
          gradedPowIter 2 (freeProP 2 (Fin n)) (m + 1)
            (gradedMkZero 2 (freeProP 2 (Fin n)) (of a))) =
        ∑ a : {a : Fin n // a ≠ ⟨3, hn3⟩ ∧ a ≠ ⟨1, by omega⟩},
          c a * if (a : Fin n) = i then 1 else 0 := by
      rw [map_sum]
      refine Finset.sum_congr rfl fun a _ ↦ ?_
      rw [map_smul, IsCrossedHom.gradedFunctional_gradedPowIter_gradedMkZero _ _ _ _
        (h a a.2.2 a.2.1), crossedHom_of, Pi.single_apply, smul_eq_mul]
      split_ifs <;> simp
    -- `Δ_{m+1}(D₄)` reads off `d`.
    have hd : d = 0 := by
      have h4 := hΔ ⟨3, hn3⟩ (Fin.ne_of_val_ne (by norm_num))
      rw [map_add, map_add, hΔv, hΔT, map_smul,
        gradedFunctional_crossedHom_gradedPowIterBracket_of_apply_eq_neg_one hn3 h₁ m
          (Fin.ne_of_val_ne (by norm_num)), ite_eq_left rfl, smul_eq_mul, mul_one, zero_add,
        Finset.sum_eq_zero fun a _ ↦ by rw [ite_eq_right a.2.1, mul_zero], zero_add] at h4
      exact h4
    -- `Δ_{m+1}(D_a)` reads off `c_a` for `a ≠ 2, 4`.
    have hc (a : {a : Fin n // a ≠ ⟨3, hn3⟩ ∧ a ≠ ⟨1, by omega⟩}) : c a = 0 := by
      have ha := hΔ a a.2.2
      rw [map_add, map_add, hΔv, hΔT, map_smul,
        gradedFunctional_crossedHom_gradedPowIterBracket_of_apply_eq_neg_one hn3 h₁ m a.2.2,
        ite_eq_right a.2.1, smul_zero, add_zero, zero_add,
        Finset.sum_eq_single a
          (fun b _ hb ↦ by rw [ite_eq_right fun e ↦ hb (Subtype.ext e), mul_zero])
          fun hb ↦ (hb (Finset.mem_univ _)).elim,
        ite_eq_left rfl, mul_one] at ha
      exact ha
    simp only [hc, zero_smul, Finset.sum_const_zero, add_zero, hd]
    exact Submodule.mem_map_of_mem hv

end freeProP

end TauCeti
