/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.CliffordAlgebra.Spin.SpinorNorm.Range
public import TauCeti.NumberTheory.HilbertSymbol.NormSubgroup
import TauCeti.LinearAlgebra.QuadraticForm.Binary

/-!
# The spinor norm of a binary quadratic space

Let `Q` be a nondegenerate binary quadratic form over a field `K` of characteristic different
from two, isometric to the diagonal form `⟨a, b⟩`, and let `E = K(√(-a b))` be its discriminant
algebra. The nonzero values of `Q` form the coset `a N` of the norm group `N = N_{E/K}(Eˣ)`
(`TauCeti.mem_unitValueSet_binary_iff_mul_mem_quadraticNormSubgroup`), so the products of two
nonzero values of `Q` are exactly the norms. The image of the spinor norm on `SO(Q)` is generated
by such products (`CliffordAlgebra.range_spinorNorm_eq_closure`), hence it is the image of `N` in
the square-class group `Kˣ/(Kˣ)²`. The image on `O(Q)` is that subgroup joined with `[a]`.

When `Q` is isotropic, `-a b` is a square and every unit is a norm from the split algebra `E`.
When `Q` is anisotropic, `E` is a quadratic field and `Q` is `a` times its norm form; over a
nonarchimedean local field the norm group then has index two, which is where surjectivity of the
local spinor norm fails.

## Main results

* `CliffordAlgebra.range_spinorNorm_of_equivalent_binary`: the image of the spinor norm on
  `SO(⟨a, b⟩)` is the image of the norm group of `K(√(-a b))`.
* `CliffordAlgebra.range_orthogonalSpinorNorm_of_equivalent_binary`: the image on `O(⟨a, b⟩)` is
  that subgroup joined with the class of `a`.

## References

* O. T. O'Meara, *Introduction to Quadratic Forms*, §55.
-/

public section

namespace CliffordAlgebra

open TauCeti QuadraticMap

universe u v

variable {K : Type u} {V : Type v} [Field K] [AddCommGroup V] [Module K V]
  [FiniteDimensional K V] [Invertible (2 : K)]

/-- The image of the spinor norm on the special orthogonal group of a binary form `⟨a, b⟩` is the
image in `Kˣ/(Kˣ)²` of the norm group of the discriminant algebra `K(√(-a b))`. -/
theorem range_spinorNorm_of_equivalent_binary (Q : QuadraticForm K V) (hQ : Q.Nondegenerate)
    {a b : Kˣ} (h : Q.Equivalent (weightedSumSquares K ![(a : K), (b : K)])) :
    (spinorNorm Q hQ).range =
      ((quadraticNormSubgroup (-(a * b : K))).map squareClassHom :
        Subgroup (Multiplicative (SquareClassGroup K))) := by
  rw [range_spinorNorm_eq_closure, h.unitValueSet_eq]
  apply le_antisymm
  · rw [Subgroup.closure_le]
    rintro _ ⟨_, ⟨c, hc, d, hd, rfl⟩, rfl⟩
    rw [mem_unitValueSet_binary_iff_mul_mem_quadraticNormSubgroup] at hc hd
    refine ⟨c * d, ?_, rfl⟩
    -- `c d = (a c) (a d) (a⁻¹)²`, and the square `(a⁻¹)²` is a norm.
    have hsq : a⁻¹ * a⁻¹ ∈ quadraticNormSubgroup (-(a * b : K)) :=
      square_le_quadraticNormSubgroup _ (Subgroup.mem_square.mpr ⟨a⁻¹, rfl⟩)
    have hcd : c * d = a * c * (a * d) * (a⁻¹ * a⁻¹) := by
      ext
      push_cast
      field_simp
    rw [hcd]
    exact mul_mem (mul_mem hc hd) hsq
  · rintro _ ⟨n, hn, rfl⟩
    -- A norm `n` is the product of the two values `a` and `a⁻¹ n` of `⟨a, b⟩`.
    have hmem : a⁻¹ * n ∈ unitValueSet (weightedSumSquares K ![(a : K), (b : K)]) := by
      rwa [mem_unitValueSet_binary_iff_mul_mem_quadraticNormSubgroup, mul_inv_cancel_left]
    refine Subgroup.subset_closure ⟨a * (a⁻¹ * n), ?_, by rw [mul_inv_cancel_left]⟩
    exact Set.mul_mem_mul (mem_unitValueSet_binary_left a (b : K)) hmem

/-- The image of the spinor norm on the orthogonal group of a binary form `⟨a, b⟩` is generated by
the image of the norm group of the discriminant algebra `K(√(-a b))` and the class of `a`. -/
theorem range_orthogonalSpinorNorm_of_equivalent_binary (Q : QuadraticForm K V)
    (hQ : Q.Nondegenerate) {a b : Kˣ}
    (h : Q.Equivalent (weightedSumSquares K ![(a : K), (b : K)])) :
    (orthogonalSpinorNorm Q hQ).range =
      ((quadraticNormSubgroup (-(a * b : K))).map squareClassHom ⊔
        Subgroup.zpowers (squareClassHom a) : Subgroup (Multiplicative (SquareClassGroup K))) := by
  obtain ⟨e⟩ := h
  -- The vector corresponding to the first coordinate has norm `a`.
  have hv : Q (e.symm (Pi.single 0 1)) = a := by
    rw [e.symm.map_app]
    simp [weightedSumSquares_apply, Fin.sum_univ_two]
  let _ : Invertible (Q (e.symm (Pi.single 0 1))) :=
    invertibleOfNonzero (by rw [hv]; exact a.ne_zero)
  rw [spinorNorm_range_orthogonal_eq_sup Q hQ (e.symm (Pi.single 0 1)),
    range_spinorNorm_of_equivalent_binary Q hQ ⟨e⟩]
  congr 3
  exact Units.ext hv

end CliffordAlgebra
