/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Localization.Integer
public import Mathlib.RingTheory.Ideal.Maps
import Mathlib.Algebra.Algebra.Tower

/-!
# Clearing a finite family of denominators in a localization

Mathlib's `IsLocalization.finsetIntegerMultiple` simultaneously clears the denominators of a
finite family in a localization. This file records how those cleared elements map back into the
localization and the resulting identity between the ideals generated before and after clearing.

## Main results

* `TauCeti.IsLocalization.algebraMap_integerMultiple`: the cleared representative maps to the
  original element multiplied by the common denominator.
* `TauCeti.IsLocalization.finsetIntegerMultiple_image_algebraMap`: the image of the finite family
  of cleared representatives is the original family multiplied by the common denominator.
* `TauCeti.IsLocalization.map_span_finsetIntegerMultiple`: the ideal generated by the cleared
  representatives maps to the ideal generated by the original family.
-/

public section

namespace TauCeti.IsLocalization

variable {A S : Type*} [CommRing A] [CommRing S] [Algebra A S]

/-- The image of an integer multiple used to clear a finite family of denominators is the
original element multiplied by the image of the common denominator. -/
lemma algebraMap_integerMultiple (M : Submonoid A) [IsLocalization M S] (T : Finset S)
    (x : T) : algebraMap A S (IsLocalization.integerMultiple M T id x) =
      (x : S) * algebraMap A S (IsLocalization.commonDenomOfFinset M T : A) := by
  rw [IsLocalization.map_integerMultiple, Submonoid.smul_def, Algebra.smul_def]
  exact mul_comm _ _

/-- The image of the finite family obtained by clearing denominators is the original family
multiplied by the image of its common denominator. -/
lemma finsetIntegerMultiple_image_algebraMap (M : Submonoid A) [IsLocalization M S]
    [DecidableEq A] [DecidableEq S] (T : Finset S) :
    (IsLocalization.finsetIntegerMultiple M T).image (algebraMap A S) =
      T.image fun x ↦ x * algebraMap A S (IsLocalization.commonDenomOfFinset M T : A) := by
  apply Finset.coe_injective
  rw [Finset.coe_image, Finset.coe_image, IsLocalization.finsetIntegerMultiple_image,
    ← Set.image_smul]
  exact Set.image_congr' fun x ↦ by rw [Submonoid.smul_def, Algebra.smul_def, mul_comm]

open scoped Pointwise in
/-- Clearing the denominators of a finite family does not change the ideal it generates after
mapping to the localization. -/
lemma map_span_finsetIntegerMultiple (M : Submonoid A) [IsLocalization M S]
    [DecidableEq A] (T : Finset S) :
    Ideal.map (algebraMap A S) (Ideal.span (IsLocalization.finsetIntegerMultiple M T : Set A)) =
      Ideal.span (T : Set S) := by
  rw [Ideal.map_span, IsLocalization.finsetIntegerMultiple_image, Submonoid.smul_def,
    ← IsScalarTower.algebraMap_smul S]
  exact Submodule.span_smul_eq_of_isUnit _ _ (IsLocalization.map_units S _)

end TauCeti.IsLocalization

end
