/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.LinearAlgebra.Basis.Defs
public import Mathlib.RingTheory.Localization.Integer
public import Mathlib.RingTheory.Ideal.Maps
import Mathlib.Algebra.Algebra.Tower

/-!
# Clearing a finite family of denominators in a localization

Mathlib's `IsLocalization.finsetIntegerMultiple` simultaneously clears the denominators of a
finite family in a localization. This file records how those cleared elements map back into the
localization and the resulting identity between the ideals generated before and after clearing.
The same clearing, applied to the coordinates of an element in a basis over a localization,
puts a multiple of it by an element of the localizing submonoid in the span of integral lifts of
the basis.

## Main results

* `TauCeti.IsLocalization.algebraMap_integerMultiple`: the cleared representative maps to the
  original element multiplied by the common denominator.
* `TauCeti.IsLocalization.finsetIntegerMultiple_image_algebraMap`: the image of the finite family
  of cleared representatives is the original family multiplied by the common denominator.
* `TauCeti.IsLocalization.map_span_finsetIntegerMultiple`: the ideal generated by the cleared
  representatives maps to the ideal generated by the original family.
* `TauCeti.exists_smul_mem_span_basis`: clearing the denominators of the coordinates in a basis
  of `L` over a localization `K` of `A` at `M`, every element of an `A`-algebra `B` embedded in
  `L` has a multiple by an element of `M` in the `A`-span of lifts of the basis to `B`.
-/

public section

namespace TauCeti.IsLocalization

variable {A S : Type*} [CommSemiring A] [CommSemiring S] [Algebra A S]

/-- The image of an integer multiple used to clear a finite family of denominators is the
original element multiplied by the image of the common denominator. -/
lemma algebraMap_integerMultiple (M : Submonoid A) [IsLocalization M S] (T : Finset S)
    (x : T) : algebraMap A S (IsLocalization.integerMultiple M T id x) =
      (x : S) * algebraMap A S (IsLocalization.commonDenomOfFinset M T : A) := by
  rw [IsLocalization.map_integerMultiple, Submonoid.smul_def, Algebra.smul_def]
  exact mul_comm _ _

/-- The image of the finite family obtained by clearing denominators is the original family
multiplied by the image of its common denominator. -/
lemma finsetIntegerMultiple_image_algebraMap (M : Submonoid A) [IsLocalization M S]
    [DecidableEq A] [DecidableEq S] (T : Finset S) :
    (IsLocalization.finsetIntegerMultiple M T).image (algebraMap A S) =
      T.image fun x ↦ x * algebraMap A S (IsLocalization.commonDenomOfFinset M T : A) := by
  apply Finset.coe_injective
  rw [Finset.coe_image, Finset.coe_image, IsLocalization.finsetIntegerMultiple_image,
    ← Set.image_smul]
  exact Set.image_congr' fun x ↦ by rw [Submonoid.smul_def, Algebra.smul_def, mul_comm]

open scoped Pointwise in
/-- Clearing the denominators of a finite family does not change the ideal it generates after
mapping to the localization. -/
lemma map_span_finsetIntegerMultiple (M : Submonoid A) [IsLocalization M S]
    [DecidableEq A] (T : Finset S) :
    Ideal.map (algebraMap A S) (Ideal.span (IsLocalization.finsetIntegerMultiple M T : Set A)) =
      Ideal.span (T : Set S) := by
  rw [Ideal.map_span, IsLocalization.finsetIntegerMultiple_image, Submonoid.smul_def,
    ← IsScalarTower.algebraMap_smul S]
  exact Submodule.span_smul_eq_of_isUnit _ _ (IsLocalization.map_units S _)

end TauCeti.IsLocalization

namespace TauCeti

variable {A K L B : Type*} [CommSemiring A] [CommSemiring K] [CommSemiring B] [Semiring L]
  [Algebra A K] [Algebra B L] [Algebra A B] [Algebra K L] [Algebra A L]
  [IsScalarTower A K L] [IsScalarTower A B L]

/-- If `B` embeds in `L` and `K` is a localization of `A` at `M`, every element of `B` has a
multiple by an element of `M` in the `A`-span of lifts in `B` of a `K`-basis of `L`. -/
theorem exists_smul_mem_span_basis (M : Submonoid A) [IsLocalization M K] {ι : Type*} [Finite ι]
    (b : Module.Basis ι K L) (b' : ι → B)
    (hb' : ∀ i, algebraMap B L (b' i) = b i)
    (hinj : Function.Injective (algebraMap B L)) (x : B) :
    ∃ a ∈ M, a • x ∈ Submodule.span A (Set.range b') := by
  classical
  have := Fintype.ofFinite ι
  have hsmul (r : A) (y : B) : algebraMap B L (r • y) = algebraMap A K r • algebraMap B L y := by
    rw [Algebra.smul_def, map_mul, ← IsScalarTower.algebraMap_apply,
      IsScalarTower.algebraMap_apply A K L, ← Algebra.smul_def]
  obtain ⟨⟨a, ha⟩, hint⟩ := IsLocalization.exist_integer_multiples M Finset.univ
    fun i ↦ b.repr (algebraMap B L x) i
  choose c hc using fun i ↦ hint i (Finset.mem_univ i)
  refine ⟨a, ha, ?_⟩
  have hx : a • x = ∑ i, c i • b' i := by
    apply hinj
    rw [hsmul, map_sum, ← b.sum_repr (algebraMap B L x), Finset.smul_sum]
    refine Finset.sum_congr rfl fun i _ ↦ ?_
    rw [hsmul, hb', hc i, smul_smul, Algebra.smul_def (a : A)]
  rw [hx]
  exact Submodule.sum_mem _ fun i _ ↦ Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)

end TauCeti

end
