/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.IsSepClosed
public import TauCeti.LinearAlgebra.Matrix.PinPlusPlane.Basic
import TauCeti.LinearAlgebra.Matrix.SpecialOrthogonalGroup.Generation
import TauCeti.LinearAlgebra.Matrix.SpecialOrthogonalGroup.Reflection

/-!
# Every orthogonal matrix of the plane has a `Pin⁺` lift

Over a separably closed field `F` of characteristic not two, every orthogonal matrix `P ∈ O₂(F)`
has a `Pin⁺` lift in the Clifford model `M₂(F)` of the plane (`TauCeti.exists_isPinLift`). By the
Cartan–Dieudonné theorem, in the matrix form
`TauCeti.closure_reflection_mul_eq_matrixSpecialOrthogonalGroup`, a special orthogonal `P` is a
product of pairs of reflections in anisotropic vectors `v`. Since `F` contains a square root `s`
of `v ⬝ᵥ v`, the reflection in `v` is the reflection in the unit vector `s⁻¹ v`, which lifts its
own reflection (`TauCeti.isPinLift_pinVec`). An orthogonal `P` of determinant `−1` is
`P diag(−1, 1) · diag(−1, 1)`, and `diag(−1, 1)` is lifted by `e₁`.

Together with `TauCeti.IsPinLift.eq_or_eq_neg` this says that over such a field the lift exists
and is unique up to sign: it is the input that lets a cocycle valued in `O₂` be compared with one
valued in the `Pin⁺` model, as in Serre's computation of the Evens norm of a Kummer class.

## Main results

* `TauCeti.exists_isPinLift`: every orthogonal `2 × 2` matrix over a separably closed field of
  characteristic not two has a `Pin⁺` lift.

## References

* J.-P. Serre, *L'invariant de Witt de la forme Tr(x²)*, Comment. Math. Helv. **59** (1984),
  651–676, §1.
* H. B. Lawson and M.-L. Michelsohn, *Spin Geometry* (1989), Chapter I, §2.
-/

public section

namespace TauCeti

open Matrix

variable {F : Type*} [Field F] [IsSepClosed F] [NeZero (2 : F)]

/-- The reflection of the standard quadratic form in an anisotropic vector `v` has a `Pin⁺` lift,
the unit vector `s⁻¹ v` for a square root `s` of `v ⬝ᵥ v`. -/
private theorem exists_isPinLift_toMatrix'_reflection (v : Fin 2 → F)
    [Invertible (toQuadraticForm' (1 : Matrix (Fin 2) (Fin 2) F) v)] :
    ∃ x, IsPinLift x (LinearMap.toMatrix' (QuadraticMap.reflection
      (toQuadraticForm' (1 : Matrix (Fin 2) (Fin 2) F)) v).toLinearMap) := by
  obtain ⟨s, hs⟩ :=
    IsSepClosed.exists_eq_mul_self (toQuadraticForm' (1 : Matrix (Fin 2) (Fin 2) F) v)
  have hv : v 0 * v 0 + v 1 * v 1 = s * s := by
    rw [← hs, toQuadraticForm'_one_apply, dotProduct, Fin.sum_univ_two]
  have hs0 : s ≠ 0 := by
    rintro rfl
    have := isUnit_of_invertible (toQuadraticForm' (1 : Matrix (Fin 2) (Fin 2) F) v)
    rw [hs, mul_zero] at this
    exact not_isUnit_zero this
  have hu : (fun i => s⁻¹ * v i) ⬝ᵥ (fun i => s⁻¹ * v i) = 1 := by
    rw [dotProduct, Fin.sum_univ_two]
    field_simp
    linear_combination hv
  refine ⟨pinVec fun i => s⁻¹ * v i, ?_⟩
  convert isPinLift_pinVec hu using 1
  rw [toMatrix'_reflection, invOf_eq_inv, hs]
  ext i j
  simp only [reflectionMatrix_apply, Matrix.sub_apply, one_apply, Matrix.smul_apply,
    vecMulVec_apply, smul_eq_mul, mul_inv]
  ring

/-- **Every orthogonal matrix of the plane has a `Pin⁺` lift** over a separably closed field of
characteristic not two. The lift is unique up to sign (`TauCeti.IsPinLift.eq_or_eq_neg`). -/
theorem exists_isPinLift {P : Matrix (Fin 2) (Fin 2) F} (hP : P ∈ orthogonalGroup (Fin 2) F) :
    ∃ x, IsPinLift x P := by
  -- The matrices that have a lift form a submonoid.
  let M : Submonoid (Matrix (Fin 2) (Fin 2) F) :=
    { carrier := {w | ∃ x, IsPinLift x w}
      mul_mem' := fun ⟨x, hx⟩ ⟨x', hx'⟩ => ⟨x * x', hx.mul hx'⟩
      one_mem' := ⟨1, IsPinLift.one⟩ }
  -- It contains the special orthogonal group, which is generated by pairs of reflections.
  have hSO : specialOrthogonalGroup (Fin 2) F ≤ M := by
    rw [← closure_reflection_mul_eq_matrixSpecialOrthogonalGroup, Submonoid.closure_le]
    rintro _ ⟨v, w, _, _, rfl⟩
    obtain ⟨x, hx⟩ := exists_isPinLift_toMatrix'_reflection v
    obtain ⟨y, hy⟩ := exists_isPinLift_toMatrix'_reflection w
    exact ⟨x * y, hx.mul hy⟩
  have hdet : P.det * P.det = 1 := by
    simpa using congrArg det ((mem_orthogonalGroup_iff' _ _).1 hP)
  rcases mul_self_eq_one_iff.1 hdet with h1 | h1
  · exact hSO (mem_specialOrthogonalGroup_iff.2 ⟨hP, h1⟩)
  -- Of determinant `−1`, `P = P diag(−1, 1) · diag(−1, 1)` with `P diag(−1, 1)` special orthogonal.
  have hDD : diagonal ![(-1 : F), 1] * diagonal ![-1, 1] = 1 := by
    rw [diagonal_mul_diagonal, ← diagonal_one]
    congr 1
    ext i; fin_cases i <;> simp
  have hD : diagonal ![(-1 : F), 1] ∈ orthogonalGroup (Fin 2) F := by
    rw [mem_orthogonalGroup_iff, diagonal_transpose, hDD]
  obtain ⟨x, hx⟩ := hSO (mem_specialOrthogonalGroup_iff.2
    ⟨mul_mem hP hD, by simp [h1, det_diagonal, Fin.prod_univ_two]⟩)
  have h := hx.mul isPinLift_pinE1
  rw [Matrix.mul_assoc, hDD, Matrix.mul_one] at h
  exact ⟨_, h⟩

end TauCeti
