/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Homological.ContCohomology.LowDegree

import TauCeti.Data.Nat.Carry

/-!
# Second cohomology of finite cyclic groups

For a finite cyclic group `G = ⟨g⟩` acting on an additive group `M`, second continuous
cohomology is the quotient of the invariant subgroup by the image of the group norm:

```text
H²(G, M) ≃ Mᴳ / N(M),       N(m) = ∑ x : G, x • m.
```

The isomorphism sends the class of a two-cocycle `f` to the class of
`∑ x : G, f (x, g)`.  The coefficient group may have an arbitrary topology: discreteness of
the finite group makes every cochain continuous.  This avoids the universe restriction in the
comparison with Mathlib's bundled `Rep ℤ G` computation.

The proof uses the classical carry cocycle for surjectivity.  For injectivity it constructs a
primitive recursively around the cycle generated by `g`; the condition that its values close up
is exactly that the displayed sum is a norm.

## Main definitions and results

* `TauCeti.groupNorm`: the norm of a finite group action.
* `TauCeti.ContCohomology.sum_cocycle_mem_H0`: the sum attached to a two-cocycle is invariant.
* `TauCeti.ContCohomology.explicitH2CyclicEquiv`: the cyclic `H²` computation.
* `TauCeti.ContCohomology.explicitH2CyclicEquiv_mk`: its formula on cocycle classes.

## References

* J.-P. Serre, *Local Fields*, Springer GTM 67 (1979), Chapter VIII, §4.
* K. S. Brown, *Cohomology of Groups*, Springer GTM 87 (1982), Chapter VI, §2.
-/

public section

namespace TauCeti

universe u v

/-- The norm of a finite group action, `m ↦ ∑ g, g • m`. -/
def groupNorm (G : Type u) [Group G] [Fintype G] (M : Type v) [AddCommGroup M]
    [DistribMulAction G M] : M →+ M where
  toFun m := ∑ g : G, g • m
  map_zero' := by simp
  map_add' m n := by simp only [smul_add, Finset.sum_add_distrib]

@[simp]
theorem groupNorm_apply (G : Type u) [Group G] [Fintype G] (M : Type v) [AddCommGroup M]
    [DistribMulAction G M] (m : M) : groupNorm G M m = ∑ g : G, g • m :=
  (rfl)

namespace ContCohomology

open groupCohomology

variable {G : Type u} [Group G] [TopologicalSpace G] [Fintype G]
  {M : Type v} [AddCommGroup M] [TopologicalSpace M] [IsTopologicalAddGroup M]
  [DistribMulAction G M]

section Cyclic

variable [DiscreteTopology G] [ContinuousSMul G M]
  (g : G) (hg : ∀ x : G, x ∈ Subgroup.zpowers g)

private noncomputable def cyclicLog (x : G) : ℕ :=
  ((finEquivZPowers (isOfFinOrder_of_finite g)).symm ⟨x, hg x⟩ : ℕ)

omit [TopologicalSpace G] [DiscreteTopology G] in
private theorem pow_cyclicLog (x : G) : g ^ cyclicLog g hg x = x :=
  pow_finEquivZPowers_symm_apply (isOfFinOrder_of_finite g) ⟨x, hg x⟩

omit [TopologicalSpace G] [DiscreteTopology G] in
private theorem cyclicLog_lt (x : G) : cyclicLog g hg x < orderOf g :=
  ((finEquivZPowers (isOfFinOrder_of_finite g)).symm ⟨x, hg x⟩).2

omit [TopologicalSpace G] [DiscreteTopology G] in
private theorem cyclicLog_pow (i : ℕ) : cyclicLog g hg (g ^ i) = i % orderOf g :=
  congrArg Fin.val (finEquivZPowers_symm_apply (isOfFinOrder_of_finite g) i)

omit [TopologicalSpace G] [DiscreteTopology G] in
private theorem cyclicLog_mul (x y : G) :
    cyclicLog g hg (x * y) = (cyclicLog g hg x + cyclicLog g hg y) % orderOf g := by
  rw [← cyclicLog_pow, pow_add, pow_cyclicLog, pow_cyclicLog]

private noncomputable def finEquivCyclic : Fin (orderOf g) ≃ G where
  toFun i := g ^ (i : ℕ)
  invFun x := ⟨cyclicLog g hg x, cyclicLog_lt g hg x⟩
  left_inv i := Fin.ext (by simp only [cyclicLog_pow, Nat.mod_eq_of_lt i.2])
  right_inv := pow_cyclicLog g hg

include hg in
omit [TopologicalSpace G] [DiscreteTopology G] [TopologicalSpace M]
  [IsTopologicalAddGroup M] [ContinuousSMul G M] in
private theorem sum_range_pow_smul (m : M) :
    ∑ i ∈ Finset.range (orderOf g), g ^ i • m = groupNorm G M m := by
  rw [← Fin.sum_univ_eq_sum_range]
  exact (finEquivCyclic g hg).sum_comp (fun x ↦ x • m)

include hg in
omit [DiscreteTopology G] [ContinuousSMul G M] in
private theorem sum_range_cocycle (f : Z2 G M) :
    ∑ i ∈ Finset.range (orderOf g), (f : G × G → M) (g ^ i, g) =
      (sumCocycle f g : M) := by
  rw [← Fin.sum_univ_eq_sum_range, sumCocycle_val]
  exact (finEquivCyclic g hg).sum_comp (fun x ↦ (f : G × G → M) (x, g))

private noncomputable def carryCocycle (a : H0 G M) : Z2 G M :=
  ⟨fun p ↦ if orderOf g ≤ cyclicLog g hg p.1 + cyclicLog g hg p.2 then a.1 else 0,
    mem_Z2_iff.mpr ⟨continuous_of_discreteTopology, by
      intro x y z
      have hcarry := TauCeti.Nat.carry_add_carry (cyclicLog_lt g hg x) (cyclicLog_lt g hg y)
        (cyclicLog_lt g hg z)
      have hfix : x • (a : M) = a := (FixedPoints.mem_addSubgroup G M a).mp a.property x
      simp only [cyclicLog_mul]
      split_ifs at hcarry ⊢ <;> simp_all⟩⟩

omit [ContinuousSMul G M] in
private theorem carryCocycle_apply (a : H0 G M) (x y : G) :
    (carryCocycle g hg a : G × G → M) (x, y) =
      if orderOf g ≤ cyclicLog g hg x + cyclicLog g hg y then a else 0 :=
  by
    simp only [carryCocycle]
    split_ifs <;> rfl

private def cyclicZ2Map : Z2 G M →+
    H0 G M ⧸ (groupNorm G M).range.addSubgroupOf (H0 G M) :=
  (QuotientAddGroup.mk' _).comp
    { toFun := fun f ↦ sumCocycle f g
      map_zero' := Subtype.ext (by
        simp only [sumCocycle_val, AddSubgroup.coe_zero, Pi.zero_apply,
          Finset.sum_const_zero])
      map_add' := fun f f' ↦ Subtype.ext (by
        simp only [sumCocycle_val, AddSubgroup.coe_add, Pi.add_apply,
          Finset.sum_add_distrib]) }

omit [DiscreteTopology G] [ContinuousSMul G M] in
private theorem cyclicZ2Map_apply (f : Z2 G M) :
    cyclicZ2Map g f = QuotientAddGroup.mk (sumCocycle f g) :=
  rfl

omit [DiscreteTopology G] [ContinuousSMul G M] in
private theorem B2_le_ker_cyclicZ2Map :
    (B2 G M).addSubgroupOf (Z2 G M) ≤ (cyclicZ2Map g).ker := by
  intro f hf
  rw [AddSubgroup.mem_addSubgroupOf] at hf
  obtain ⟨c, hc, hcf⟩ := mem_B2_iff.mp hf
  rw [AddMonoidHom.mem_ker]
  rw [cyclicZ2Map_apply]
  rw [QuotientAddGroup.eq_zero_iff, AddSubgroup.mem_addSubgroupOf]
  refine ⟨c g, ?_⟩
  simp only [sumCocycle_val, groupNorm_apply]
  rw [← hcf]
  simp only [d1_apply]
  rw [Finset.sum_add_distrib, Finset.sum_sub_distrib,
    Fintype.sum_bijective _ (Group.mulRight_bijective g) _ _ (fun _ ↦ rfl)]
  abel

private def cyclicH2Map : H2 G M →+
    H0 G M ⧸ (groupNorm G M).range.addSubgroupOf (H0 G M) :=
  QuotientAddGroup.lift _ (cyclicZ2Map g) (B2_le_ker_cyclicZ2Map g)

private theorem cyclicH2Map_mk (f : Z2 G M) :
    cyclicH2Map g (H2pi G M f) =
      QuotientAddGroup.mk (s := (groupNorm G M).range.addSubgroupOf (H0 G M))
        (sumCocycle f g) :=
  QuotientAddGroup.lift_mk _ _ _

private noncomputable def cyclicPrimitive (f : Z2 G M) (b : M) (x : G) : M :=
  (f : G × G → M) (1, 1) +
    ∑ i ∈ Finset.range (cyclicLog g hg x),
      (g ^ i • b - (f : G × G → M) (g ^ i, g))

omit [DiscreteTopology G] [ContinuousSMul G M] in
private theorem cyclicPrimitive_mul (f : Z2 G M) (b : M)
    (hb : groupNorm G M b = (sumCocycle f g : M)) (x : G) :
    cyclicPrimitive g hg f b (x * g) =
      x • b + cyclicPrimitive g hg f b x - (f : G × G → M) (x, g) := by
  let k := cyclicLog g hg x
  have hk : k < orderOf g := cyclicLog_lt g hg x
  have hx : g ^ k = x := pow_cyclicLog g hg x
  have hxg : x * g = g ^ (k + 1) := by rw [← hx, pow_succ]
  rw [cyclicPrimitive, cyclicPrimitive, hxg, cyclicLog_pow]
  by_cases hnext : k + 1 < orderOf g
  · rw [Nat.mod_eq_of_lt hnext, Finset.sum_range_succ]
    rw [hx]
    abel
  · have hkn : k + 1 = orderOf g := by omega
    rw [hkn, Nat.mod_self, Finset.sum_range_zero, add_zero]
    have htotal :
        ∑ i ∈ Finset.range (orderOf g),
            (g ^ i • b - (f : G × G → M) (g ^ i, g)) = 0 := by
      rw [Finset.sum_sub_distrib, sum_range_pow_smul g hg,
        sum_range_cocycle g hg, hb, sub_self]
    rw [← hkn] at htotal
    rw [Finset.sum_range_succ] at htotal
    dsimp only [k] at htotal ⊢
    rw [hx] at htotal
    calc
      (f : G × G → M) (1, 1) = 0 + (f : G × G → M) (1, 1) :=
        (zero_add _).symm
      _ = ((∑ i ∈ Finset.range k,
          (g ^ i • b - (f : G × G → M) (g ^ i, g))) +
            (x • b - (f : G × G → M) (x, g))) +
          (f : G × G → M) (1, 1) := congrArg (fun z ↦ z + _) htotal.symm
      _ = x • b + ((f : G × G → M) (1, 1) +
          ∑ i ∈ Finset.range k,
            (g ^ i • b - (f : G × G → M) (g ^ i, g))) -
          (f : G × G → M) (x, g) := by abel

include hg in
omit [TopologicalSpace G] [DiscreteTopology G] [Fintype G] [TopologicalSpace M]
  [IsTopologicalAddGroup M] [ContinuousSMul G M] in
/-- A `2`-cocycle that vanishes whenever its second argument is a cyclic generator vanishes
identically. -/
private theorem cocycle_eq_zero_of_eq_zero_on_generator [Finite G] (q : G × G → M)
    (hq : IsCocycle₂ q) (hqg : ∀ x : G, q (x, g) = 0) (x y : G) : q (x, y) = 0 := by
  let _ := Fintype.ofFinite G
  have hqpow : ∀ (n : ℕ) (x : G), q (x, g ^ n) = 0 := by
    intro n
    induction n with
    | zero =>
        intro x
        rw [pow_zero]
        have h11 : q (1, 1) = 0 := by
          rw [← map_one_fst_of_isCocycle₂ hq g]
          exact hqg 1
        rw [map_one_snd_of_isCocycle₂ hq x, h11, smul_zero]
    | succ n ih =>
        intro x
        have h := hq x (g ^ n) g
        rw [hqg, ih, hqg, zero_add, smul_zero, zero_add] at h
        simpa only [pow_succ] using h.symm
  rw [← pow_cyclicLog g hg y]
  exact hqpow (cyclicLog g hg y) x

include hg in
omit [ContinuousSMul G M] in
private theorem mem_B2_of_cyclicZ2Map_eq_zero (f : Z2 G M)
    (hfzero : cyclicZ2Map g f = 0) : (f : G × G → M) ∈ B2 G M := by
  have hsum : sumCocycle f g ∈ (groupNorm G M).range.addSubgroupOf (H0 G M) := by
    rw [← QuotientAddGroup.eq_zero_iff]
    exact hfzero
  rw [AddSubgroup.mem_addSubgroupOf] at hsum
  obtain ⟨b, hb⟩ := hsum
  let c : G → M := cyclicPrimitive g hg f b
  have hrec (x : G) :
      c (x * g) = x • b + c x - (f : G × G → M) (x, g) :=
    cyclicPrimitive_mul g hg f b hb x
  have hfg := (mem_Z2_iff.mp f.property).2
  have hcg : c g = b := by
    have h := hrec 1
    rw [one_mul, one_smul] at h
    have hone := map_one_fst_of_isCocycle₂ hfg g
    have hc1 : c 1 = (f : G × G → M) (1, 1) := by
      dsimp only [c, cyclicPrimitive]
      have hlog : cyclicLog g hg 1 = 0 := by
        simpa only [pow_zero, Nat.zero_mod] using cyclicLog_pow g hg 0
      rw [hlog, Finset.sum_range_zero, add_zero]
    rw [hc1, hone] at h
    simpa using h
  let q : G × G → M := fun p ↦
    (f : G × G → M) p - d1 G M c p
  have hd : IsCocycle₂ (d1 G M c) :=
    d2_apply_eq_zero_iff.mp (d2_comp_d1_apply c)
  have hq : IsCocycle₂ q := by
    intro x y z
    dsimp only [q]
    calc
      ((f : G × G → M) (x * y, z) - d1 G M c (x * y, z)) +
          ((f : G × G → M) (x, y) - d1 G M c (x, y)) =
          ((f : G × G → M) (x * y, z) + (f : G × G → M) (x, y)) -
            (d1 G M c (x * y, z) + d1 G M c (x, y)) := by abel
      _ = (x • (f : G × G → M) (y, z) + (f : G × G → M) (x, y * z)) -
          (x • d1 G M c (y, z) + d1 G M c (x, y * z)) := by
        rw [hfg x y z, hd x y z]
      _ = x • ((f : G × G → M) (y, z) - d1 G M c (y, z)) +
          ((f : G × G → M) (x, y * z) - d1 G M c (x, y * z)) := by
        rw [smul_sub]
        abel
  have hqg (x : G) : q (x, g) = 0 := by
    dsimp only [q]
    rw [d1_apply, hcg, hrec]
    abel
  rw [mem_B2_iff']
  refine ⟨c, continuous_of_discreteTopology, fun x y ↦ ?_⟩
  have hzero := cocycle_eq_zero_of_eq_zero_on_generator g hg q hq hqg x y
  dsimp only [q] at hzero
  rw [d1_apply] at hzero
  exact (sub_eq_zero.mp hzero).symm

omit [ContinuousSMul G M] in
private theorem sumCocycle_carryCocycle (a : H0 G M) (hn : 1 < orderOf g) :
    sumCocycle (carryCocycle g hg a) g = a := by
  apply Subtype.ext
  rw [sumCocycle_val, Fintype.sum_eq_single (g ^ (orderOf g - 1))]
  · rw [carryCocycle_apply, cyclicLog_pow]
    have hlogg : cyclicLog g hg g = 1 := by
      simpa only [pow_one, Nat.mod_eq_of_lt hn] using cyclicLog_pow g hg 1
    rw [hlogg, Nat.mod_eq_of_lt (by omega), ite_eq_left (by omega)]
  · intro x hx
    rw [carryCocycle_apply]
    split_ifs with hcarry
    · exfalso
      apply hx
      have hlogg : cyclicLog g hg g = 1 := by
        simpa only [pow_one, Nat.mod_eq_of_lt hn] using cyclicLog_pow g hg 1
      rw [hlogg] at hcarry
      have hlogx : cyclicLog g hg x = orderOf g - 1 := by
        have := cyclicLog_lt g hg x
        omega
      rw [← pow_cyclicLog g hg x, hlogx]
    · rfl

include hg in
private theorem cyclicH2Map_surjective : Function.Surjective (cyclicH2Map g :
    H2 G M → H0 G M ⧸ (groupNorm G M).range.addSubgroupOf (H0 G M)) := by
  intro q
  induction q using QuotientAddGroup.induction_on with
  | H a =>
      by_cases hn : orderOf g = 1
      · refine ⟨0, ?_⟩
        rw [map_zero]
        symm
        rw [QuotientAddGroup.eq_zero_iff, AddSubgroup.mem_addSubgroupOf]
        refine ⟨(a : M), ?_⟩
        rw [← sum_range_pow_smul g hg, hn]
        simp
      · have hn' : 1 < orderOf g := by
          have := orderOf_pos g
          omega
        refine ⟨H2pi G M (carryCocycle g hg a), ?_⟩
        rw [cyclicH2Map_mk, sumCocycle_carryCocycle g hg a hn']

include hg in
private theorem cyclicH2Map_injective : Function.Injective (cyclicH2Map g :
    H2 G M → H0 G M ⧸ (groupNorm G M).range.addSubgroupOf (H0 G M)) := by
  rw [← AddMonoidHom.ker_eq_bot_iff]
  ext x
  constructor
  · intro hx
    rw [AddSubgroup.mem_bot]
    rw [AddMonoidHom.mem_ker] at hx
    induction x using QuotientAddGroup.induction_on with
    | H f =>
        have hx' : cyclicH2Map g (H2pi G M f) = 0 := hx
        rw [cyclicH2Map_mk] at hx'
        apply H2pi_eq_zero_iff.mpr
        apply mem_B2_of_cyclicZ2Map_eq_zero g hg f
        exact hx'
  · rintro rfl
    exact (cyclicH2Map g).map_zero

/-- For a finite cyclic group generated by `g`, second continuous cohomology is the quotient of
the invariant subgroup by the image of the group norm. The coefficient topology is arbitrary. -/
noncomputable def explicitH2CyclicEquiv (G' : Type u) [Group G'] [TopologicalSpace G']
    [DiscreteTopology G'] [Fintype G'] (M' : Type v) [AddCommGroup M'] [TopologicalSpace M']
    [IsTopologicalAddGroup M'] [DistribMulAction G' M'] [ContinuousSMul G' M'] (g' : G')
    (hg' : ∀ x : G', x ∈ Subgroup.zpowers g') :
    H2 G' M' ≃+ H0 G' M' ⧸ (groupNorm G' M').range.addSubgroupOf (H0 G' M') :=
  AddEquiv.ofBijective (cyclicH2Map g')
    ⟨cyclicH2Map_injective g' hg', cyclicH2Map_surjective g' hg'⟩

/-- The cyclic `H²` equivalence sends a cocycle class to the class of the sum of its values
`f (x, g)` over the first variable. -/
@[simp]
theorem explicitH2CyclicEquiv_mk (G' : Type u) [Group G'] [TopologicalSpace G']
    [DiscreteTopology G'] [Fintype G'] (M' : Type v) [AddCommGroup M'] [TopologicalSpace M']
    [IsTopologicalAddGroup M'] [DistribMulAction G' M'] [ContinuousSMul G' M'] (g' : G')
    (hg' : ∀ x : G', x ∈ Subgroup.zpowers g') (f : Z2 G' M') :
    explicitH2CyclicEquiv G' M' g' hg' (f : H2 G' M') =
      QuotientAddGroup.mk (s := (groupNorm G' M').range.addSubgroupOf (H0 G' M'))
        ⟨∑ x : G', (f : G' × G' → M') (x, g'), sum_cocycle_mem_H0 G' M' f g'⟩ := by
  calc
    explicitH2CyclicEquiv G' M' g' hg' (f : H2 G' M') =
        QuotientAddGroup.mk (sumCocycle f g') := cyclicH2Map_mk g' f
    _ = QuotientAddGroup.mk
        ⟨∑ x : G', (f : G' × G' → M') (x, g'), sum_cocycle_mem_H0 G' M' f g'⟩ :=
      congrArg QuotientAddGroup.mk (Subtype.ext (sumCocycle_val f g'))

end Cyclic

end ContCohomology

end TauCeti
