/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Homological.ContCohomology.LowDegree

/-!
# First cohomology of finite cyclic groups with topological coefficients

For a cyclic group generated by `g`, a continuous one-cocycle is a coboundary exactly when its
value at `g` has the form `g • m - m`. On a finite group this value is killed by the group norm
`TauCeti.groupNorm G M`. Consequently `H¹` vanishes if every element killed by the norm has the form
`g • m - m`.

The coefficients need not be discrete. In particular, the criterion applies to a finite discrete
quotient acting on a profinite abelian group, where the comparison with discrete group cohomology
over `Rep ℤ G` does not cover coefficients and groups in arbitrary universes.

The sufficient condition is not unconditional: for a nontrivial finite cyclic group acting
trivially on a cyclic group of the same order, the norm is zero and `H¹` is nonzero.

## References

* J.-P. Serre, *Local Fields*, Springer GTM 67 (1979), Chapter VIII, §4, the cyclic-group
  description `H¹ = ker(N) / (g - 1)M`.
* Mathlib's `Rep.FiniteCyclicGroup.groupCohomologyIsoOdd` is the periodic-resolution version
  for linear representations. Here the criterion is proved directly on continuous cocycles.
-/

public section

namespace TauCeti.ContCohomology

open groupCohomology

universe u v

variable {G : Type u} [Group G] [TopologicalSpace G]
  {M : Type v} [AddCommGroup M] [TopologicalSpace M] [IsTopologicalAddGroup M]
  [DistribMulAction G M] [ContinuousSMul G M]
  (g : G) (hg : ∀ x : G, x ∈ Subgroup.zpowers g)

include hg

omit [ContinuousSMul G M] in
/-- A continuous one-cocycle on a cyclic group represents zero exactly when its value at the
chosen generator is a `(g - 1)`-image. This characterization also holds for infinite cyclic
groups and for nondiscrete coefficients. -/
theorem H1pi_eq_zero_iff_exists_smul_sub_eq (f : Z1 G M) :
    (f : H1 G M) = 0 ↔ ∃ m : M, g • m - m = f.val g := by
  rw [H1pi_eq_zero_iff, mem_B1_iff]
  constructor
  · rintro ⟨m, hm⟩
    exact ⟨m, hm g⟩
  · rintro ⟨m, hm⟩
    refine ⟨m, fun x ↦ ?_⟩
    have heq := isCocycle₁_ext_of_forall_mem_zpowers g hg
      (mem_Z1_iff.mp f.property).2
      (d1_apply_eq_zero_iff.mp (d1_comp_d0_apply m))
      (by simpa using hm.symm)
    simpa only [d0_apply] using (congrFun heq x).symm

/-- A finite cyclic group has vanishing first continuous cohomology if the kernel of the group
norm consists of `(g - 1)`-images. No discreteness assumption on the coefficient group is
required. -/
theorem subsingleton_H1_of_forall_mem_zpowers [Fintype G]
    (h : ∀ m : M, groupNorm G M m = 0 → ∃ b : M, g • b - b = m) :
    Subsingleton (H1 G M) := by
  suffices hz : ∀ x : H1 G M, x = 0 from ⟨fun x y ↦ (hz x).trans (hz y).symm⟩
  intro x
  induction x using QuotientAddGroup.induction_on with
  | H f =>
    exact (H1pi_eq_zero_iff_exists_smul_sub_eq g hg f).mpr
      (h (f.val g) (by
        simpa only [groupNorm_apply] using
          sum_smul_apply_eq_zero_of_isCocycle₁ g (mem_Z1_iff.mp f.property).2))

end TauCeti.ContCohomology
