/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.E6.Minuscule.GroupScheme
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Coroot

/-!
# Generation of the E₆ minuscule weight torus by root subgroups

The type-`E₆` minuscule carrier is defined from twelve numbered simple root subgroups together
with its rank-six weight torus. Over every commutative ring, this file proves that the represented
weight torus is already contained in the elementary group generated by those root subgroups.

The proof combines two concrete features of the minuscule carrier. The positive and negative
generators at every node form an `sl₂` triple after passing to the represented rational module.
Also, every row of the type-`E₆` Cartan matrix contains `-1`, giving an explicit integral Bézout
witness for the corresponding root character. The generic coroot-generation theorem therefore
puts every coordinate cocharacter, and hence every point of the weight torus, in the elementary
group.

The result concerns subgroups of the automorphism group of the base-changed admissible lattice.
It does not identify the elementary subgroup with all points of the toral-closure group scheme;
that is a separate scheme-theoretic comparison.

## Main results

* `TauCeti.E6Minuscule.elementarySubgroup`: the subgroup of carrier points generated by the
  ranges of the twelve named root-subgroup maps.
* `TauCeti.E6Minuscule.weightTorusPoints_range_le_elementarySubgroup`: the range of the named
  weight-torus map lies in the elementary subgroup over every commutative ring.
* `TauCeti.E6Minuscule.weightTorusPoints_range_sup_elementarySubgroup`: adjoining the named
  weight-torus range to the elementary subgroup does not enlarge it.

## References

* R. Steinberg, *Lectures on Chevalley Groups*, §3.
* R. W. Carter, *Simple Groups of Lie Type*, §§6.4 and 7.1.
-/

public section

open scoped TensorProduct

universe v

namespace TauCeti.E6Minuscule

open TauCeti.DynkinType TauCeti.UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

local notation "Λ" => TauCeti.coordinateLattice (Fin 27)
local notation "𝓑" => TauCeti.coordinateLatticeBasis (Fin 27)
local notation "rootGen" => TauCeti.serreRootGenerator weightTable.cartanMatrix
local notation "cartanGen" => TauCeti.serreH ℚ weightTable.cartanMatrix

private def cartanNeighbor : Fin 6 → Fin 6 :=
  ![2, 3, 0, 1, 3, 4]

private def cartanBezout (i j : Fin 6) : ℤ :=
  if j = cartanNeighbor i then -1 else 0

private theorem cartan_sum_mul_bezout (i : Fin 6) :
    ∑ j, CartanMatrix.E 6 i j * cartanBezout i j = 1 := by
  fin_cases i <;> decide

private theorem rootGeneratorWeight_sum_mul_bezout (i : Fin 6) :
    ∑ j, rootGeneratorWeight (.inl i) j * cartanBezout i j = 1 := by
  simpa only [rootGeneratorWeight_inl] using cartan_sum_mul_bezout i

private theorem rootGeneratorWeight_inr_eq_neg_inl (i : Fin 6) :
    rootGeneratorWeight (.inr i) = -rootGeneratorWeight (.inl i) := by
  ext j
  simp

/-- The elementary subgroup of the type-`E₆` minuscule carrier points, generated by the
ranges of its twelve named positive and negative simple-root subgroup maps. -/
noncomputable def elementarySubgroup (A : Type v) [CommRing A] : Subgroup (points A) :=
  ⨆ k, (rootSubgroupPoints k A).range

private theorem map_kostantElementarySubgroup_le_map_elementarySubgroup
    (A : Type v) [CommRing A] :
    (kostantElementarySubgroup rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
        weightTable.rep_kostantForm_mem_lattice
        weightTable.isNilpotent_rep_serreRootGenerator (CommAlgCat.of ℤ A)).map
          (Units.map (LinearMap.toMatrixAlgEquiv ((𝓑).baseChange A)).toMulEquiv) ≤
      (elementarySubgroup A).map (points A).subtype := by
  rw [kostantElementarySubgroup_eq_closure, MonoidHom.map_closure]
  rw [Subgroup.closure_le]
  rintro _ ⟨x, hx, rfl⟩
  obtain ⟨k, hx⟩ := Set.mem_iUnion.1 hx
  obtain ⟨t, rfl⟩ := hx
  refine ⟨rootSubgroupPoints k A t, ?_, ?_⟩
  · exact (le_iSup (fun k ↦ (rootSubgroupPoints k A).range) k) ⟨t, rfl⟩
  · change (rootSubgroupPoints k A t : _root_.Matrix.GeneralLinearGroup (Fin 27) A) = _
    rw [coe_rootSubgroupPoints]
    exact (basisMatrix_kostantRootSubgroupParam
      rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
      weightTable.rep_kostantForm_mem_lattice weightTable.isNilpotent_rep_serreRootGenerator
      𝓑 A k t).symm

/-- Over every commutative ring, the range of the named type-`E₆` minuscule weight-torus map
is contained in the elementary subgroup generated by the named root-subgroup maps. -/
theorem weightTorusPoints_range_le_elementarySubgroup (A : Type v) [CommRing A] :
    (weightTorusPoints A).range ≤ elementarySubgroup A := by
  rintro _ ⟨s, rfl⟩
  have htorus :
      kostantTorusPoints (Λ).toAddSubgroup 𝓑 weightTable.weight A s ∈
        kostantTorusSubgroup (Λ).toAddSubgroup 𝓑 weightTable.weight
          (CommAlgCat.of ℤ A) := by
    rw [kostantTorusSubgroup_eq_range]
    exact ⟨s, rfl⟩
  have helementary :=
    (kostantTorusSubgroup_le_kostantElementarySubgroup
      rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
      weightTable.rep_kostantForm_mem_lattice weightTable.isNilpotent_rep_serreRootGenerator
      𝓑 weightTable.weight weightTable.isCartanWeightVector_coordinateLatticeBasis
      rootGeneratorWeight lie_serreH_rootGenerator Sum.inl Sum.inr
      (fun i ↦ weightTable.isSl2Triple_rep_serreRootGenerator i
        (by
          obtain ⟨a, ha⟩ := exists_e6MinusculeWeight_apply_eq_neg_one i
          exact ⟨a, by simp only [weightTable_weight, ha]; omega⟩))
      rootGeneratorWeight_inr_eq_neg_inl cartanBezout rootGeneratorWeight_sum_mul_bezout
      (CommAlgCat.of ℤ A)) htorus
  have hmatrix :
      Units.map (LinearMap.toMatrixAlgEquiv ((𝓑).baseChange A)).toMulEquiv
          (kostantTorusPoints (Λ).toAddSubgroup 𝓑 weightTable.weight A s) ∈
        (elementarySubgroup A).map (points A).subtype :=
    map_kostantElementarySubgroup_le_map_elementarySubgroup A
      ⟨_, helementary, rfl⟩
  obtain ⟨g, hg, hg_eq⟩ := hmatrix
  have hpoint : weightTorusPoints A s = g := by
    apply Subtype.ext
    rw [coe_weightTorusPoints, ← basisMatrix_kostantTorusPoints]
    exact hg_eq.symm
  rwa [hpoint]

/-- Adjoining the range of the named type-`E₆` minuscule weight-torus map to the elementary
subgroup generated by the named root-subgroup maps does not enlarge that subgroup. -/
theorem weightTorusPoints_range_sup_elementarySubgroup (A : Type v) [CommRing A] :
    (weightTorusPoints A).range ⊔ elementarySubgroup A = elementarySubgroup A :=
  sup_eq_right.2 (weightTorusPoints_range_le_elementarySubgroup A)

end TauCeti.E6Minuscule
