/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Probability.Independence.Basic

/-!
# Independence under a pushforward

Two functions are independent under the pushforward of a measure along a measurable map exactly
when their composites with that map are independent under the measure: the events generated by
the composites are the preimages of the events generated by the functions.

## Main results

* `ProbabilityTheory.indepFun_map_iff_comp`
-/

public section

open MeasureTheory

namespace ProbabilityTheory

variable {Ω Ω' β γ : Type*} [MeasurableSpace Ω] [MeasurableSpace Ω'] [MeasurableSpace β]
  [MeasurableSpace γ] {μ : Measure Ω}

/-- Independence of two functions under a pushforward is independence of their composites. -/
theorem indepFun_map_iff_comp {m : Ω → Ω'} (hm : Measurable m) {f : Ω' → β} {g : Ω' → γ}
    (hf : Measurable f) (hg : Measurable g) :
    IndepFun f g (μ.map m) ↔ IndepFun (f ∘ m) (g ∘ m) μ := by
  rw [IndepFun_iff, IndepFun_iff]
  constructor
  · intro h t1 t2 ht1 ht2
    obtain ⟨s1, hs1, rfl⟩ := MeasurableSpace.measurableSet_comap.1 ht1
    obtain ⟨s2, hs2, rfl⟩ := MeasurableSpace.measurableSet_comap.1 ht2
    have := h (f ⁻¹' s1) (g ⁻¹' s2) (MeasurableSpace.measurableSet_comap.2 ⟨s1, hs1, rfl⟩)
      (MeasurableSpace.measurableSet_comap.2 ⟨s2, hs2, rfl⟩)
    rw [Measure.map_apply hm (hf hs1), Measure.map_apply hm (hg hs2),
      Measure.map_apply hm ((hf hs1).inter (hg hs2)), Set.preimage_inter] at this
    simpa only [Set.preimage_comp] using this
  · intro h t1 t2 ht1 ht2
    obtain ⟨s1, hs1, rfl⟩ := MeasurableSpace.measurableSet_comap.1 ht1
    obtain ⟨s2, hs2, rfl⟩ := MeasurableSpace.measurableSet_comap.1 ht2
    have := h ((f ∘ m) ⁻¹' s1) ((g ∘ m) ⁻¹' s2)
      (MeasurableSpace.measurableSet_comap.2 ⟨s1, hs1, rfl⟩)
      (MeasurableSpace.measurableSet_comap.2 ⟨s2, hs2, rfl⟩)
    rw [Measure.map_apply hm (hf hs1), Measure.map_apply hm (hg hs2),
      Measure.map_apply hm ((hf hs1).inter (hg hs2)), Set.preimage_inter]
    simpa only [Set.preimage_comp] using this

end ProbabilityTheory
