/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Padics.PadicIntegers
public import TauCeti.Topology.Algebra.Group.Profinite.CompletedGroupAlgebra.PowerSeries
public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.Orientation
public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.RelatorClass
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.BinomialSeries

/-!
# The basis correction for the dyadic even-rank Demushkin relator in Labute's module

Let `G` be a pro-`2` group, `χ : G →ₜ* ℤ_2ˣ` a continuous character, `X = ker χ`, and let
`E = X^{ab} = X ⧸ (X, X)` be its topological abelianization, a compact module over the completed
group algebra `Λ = ℤ_2[[G ⧸ X]]` through the conjugation action `[g] • [x] = [g x g⁻¹]`
(`TauCeti.IsProP.completedGroupAlgebraModule`). For a tuple `x` with `χ (x_i) = 1` off the marked
generators `x₂`, `x₄`, the class of the `q = 2`, `n` even normal-form relator
`x₁^{2+a} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (x_{n-1}, x_n)` in `E` is

```text
(1 + a + [x₂]⁻¹) • [x₁] + (2^f - 1 + [x₄]⁻¹) • [x₃]
```

(`TauCeti.IsProP.ofMul_mk_demushkinWordTwoEven_ker`). Labute's computation on p. 122 corrects the
generators so that the relator class becomes a single multiple: when the marked values are the
standard ones, `χ(x₂) (1 + a) = -1` and `χ(x₄) (1 - 2^f) = 1`, and `χ(x₄)` is a `2`-adic power
`χ(x₂) ^ l` of `χ(x₂)`, the second coefficient is a multiple of the first,

```text
(1 + a + [x₂]⁻¹) ∣ (2^f - 1 + [x₄]⁻¹)   in Λ,
```

and the relator class is `(1 + a + [x₂]⁻¹) • ([x₁] + φ • [x₃])` for the quotient `φ`
(`TauCeti.IsProP.exists_ofMul_mk_demushkinWordTwoEven_ker_eq_smul`).

The divisibility is the division criterion for power series over `ℤ_2`. Writing `γ = [x₂]⁻¹`, the
relation `χ(x₄) = χ(x₂) ^ l` descends to `[x₄]⁻¹ = γ ^ l` in `G ⧸ X`
(`TauCeti.IsProP.mk_eq_padicPow_mk_of_apply_eq_padicPow`), so the two coefficients are the values
at `γ - 1` of the power series `X - c` and `(2^f - 1) + (1 + X) ^ l`, where `c = χ(x₂)⁻¹ - 1`
satisfies `1 + c = -(1 + a)`. The second series vanishes at `c`, because `(1 + c) ^ l` is the
`2`-adic power `χ(x₂)⁻ˡ = χ(x₄)⁻¹ = 1 - 2^f` (`TauCeti.IsProP.aeval_binomialSeries`), so `X - c`
divides it (`PadicInt.X_sub_C_dvd_iff_aeval_eq_zero`), and evaluation at `γ - 1` carries the
divisibility into `Λ`
(`TauCeti.completedGroupAlgebra.of_sub_algebraMap_dvd_algebraMap_add_of_padicPow`).

The power relation `χ(x₄) = χ(x₂) ^ l` is a hypothesis here; the tuple `x` need not generate `G`,
and nothing is assumed about the image of `χ`. For the standard orientation
`TauCeti.orientationTwoEven` of the normal form, which takes the value `1` off the marked
generators and the marked values `χ(x₂) = v`, `v (1 + a) = -1`, and `χ(x₄) = u`, `u (1 - 2^f) = 1`,
the relation holds in the branch `4 ∣ a`, `2^f ∤ a` of the classification, in which the closed
subgroup generated by `v` and `u` is the procyclic subgroup `U^[g]` of `ℤ_2ˣ` generated by `v`
alone (`TauCeti.exists_topologicalClosure_zpowers_sup_zpowers_eq_of_not_dvd`; Labute, Theorem 5):
`u` lies in the closed subgroup generated by `v`
(`TauCeti.mem_topologicalClosure_zpowers_of_not_dvd`), hence is a `2`-adic power of `v`
(`TauCeti.exists_padicPow_eq_of_not_dvd`). Pulled back to the free pro-`2` group on `x₁, …, x_n`,
the correction for this orientation therefore holds under the marked-value equations
`v (1 + a) = -1`, `u (1 - 2^f) = 1`, the rank bound `3 < n` and the arithmetic hypotheses `4 ∣ a`,
`2^f ∤ a`, with no power relation assumed
(`TauCeti.exists_ofMul_mk_demushkinWordTwoEven_ker_orientationTwoEven_comp_mk_eq_smul`); there
`X^{ab}` is Labute's module `E`. In the other even-rank branch, `2^f ∣ a` with `2 ≤ f`, the closed
subgroup generated by `v` and `u` is `{±1} × U^(f)`
(`TauCeti.topologicalClosure_zpowers_sup_zpowers_eq_unitsPlusMinus_of_dvd`), which is not
procyclic (`TauCeti.not_exists_topologicalClosure_zpowers_eq_unitsPlusMinus`), so no such `l`
exists there. The bound `2 ≤ f` matters: at `f = 1` the marked value is `u = -1`, and for `a = 0`
it is the power `v ^ 1` of `v = -1`.

**Conventions.** Labute lets `Γ = G ⧸ X` act by `[y] · [x] = [y⁻¹ x y]`, the inverse of the
conjugation action used here (`TopologicalAbelianization.mk_inv_smul_mk`), so every group element
in a coefficient below carries an inverse where Labute writes the element itself. In his letters the
multiplier reads `1 + a + (1 + T)^a`, where the summand `a` is the exponent of the word and the
exponent `a` of `1 + T` is his name for the image of `x₂` in `Γ`, written as a power of the
topological generator `1 + T`.

## Main results

* `TauCeti.IsProP.one_add_add_of_inv_dvd_two_pow_sub_one_add_of_inv`: the coefficient
  `1 + a + [x₂]⁻¹` divides `2^f - 1 + [x₄]⁻¹` in `ℤ_2[[G ⧸ ker χ]]` when `χ(x₂) (1 + a) = -1`,
  `χ(x₄) (1 - 2^f) = 1` and `χ(x₄)` is a `2`-adic power of `χ(x₂)`.
* `TauCeti.IsProP.exists_ofMul_mk_demushkinWordTwoEven_ker_eq_smul`: **the basis correction**,
  the class of the `q = 2`, `n` even relator in `X^{ab}` is `(1 + a + [x₂]⁻¹) • ([x₁] + φ • [x₃])`
  for some `φ ∈ ℤ_2[[G ⧸ X]]`, under the same hypotheses and `3 < n`.
* `TauCeti.exists_ofMul_mk_demushkinWordTwoEven_ker_orientationTwoEven_comp_mk_eq_smul`: **the
  basis correction in Labute's module**, for the standard orientation of the `q = 2`, `n` even
  normal form on the free pro-`2` group, with marked values `v (1 + a) = -1`, `u (1 - 2^f) = 1`,
  for `3 < n`, in the branch `4 ∣ a`, `2^f ∤ a`.

## References

* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), §4, p. 122, and
  Theorem 5.
-/

public section

namespace TauCeti

namespace IsProP

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G] [CompactSpace G]
  [TotallyDisconnectedSpace G] (hG : IsProP 2 G) (χ : G →ₜ* ℤ_[2]ˣ)
include hG

/-- **The second coefficient of the dyadic even-rank relator class is a multiple of the first.**
For a continuous character `χ` of a pro-`2` group `G` into `ℤ_2ˣ` and elements `x`, `y` with
`χ x (1 + a) = -1`, `χ y (1 - 2^f) = 1` and `χ y = (χ x) ^ l` for a `2`-adic exponent `l`, the
element `1 + a + [x]⁻¹` of `ℤ_2[[G ⧸ ker χ]]` divides `2^f - 1 + [y]⁻¹`: in the power-series
coordinate `T = [x]⁻¹ - 1` the two elements are `T - c` and `(2^f - 1) + (1 + T) ^ l` with
`1 + c = -(1 + a)`, and the second vanishes at `c` because `(1 + c) ^ l = (χ x)⁻ˡ = (χ y)⁻¹`. -/
theorem one_add_add_of_inv_dvd_two_pow_sub_one_add_of_inv (a f : ℕ) {x y : G}
    (hx : (χ x : ℤ_[2]) * (1 + a) = -1) (hy : (χ y : ℤ_[2]) * (1 - 2 ^ f) = 1) (l : ℤ_[2])
    (hl : χ y = isProP_units_padicInt_two.padicPow (χ x) l) :
    haveI := χ.isClosed_ker
    1 + (a : completedGroupAlgebra ℤ_[2] (G ⧸ χ.toMonoidHom.ker)) +
        completedGroupAlgebra.of ℤ_[2] (G ⧸ χ.toMonoidHom.ker) (x : G ⧸ χ.toMonoidHom.ker)⁻¹ ∣
      (2 : completedGroupAlgebra ℤ_[2] (G ⧸ χ.toMonoidHom.ker)) ^ f - 1 +
        completedGroupAlgebra.of ℤ_[2] (G ⧸ χ.toMonoidHom.ker) (y : G ⧸ χ.toMonoidHom.ker)⁻¹ := by
  have := χ.isClosed_ker
  have : IsMulCommutative (G ⧸ χ.toMonoidHom.ker) :=
    Subgroup.Normal.quotient_commutative_iff_commutator_le.mpr
      (Abelianization.commutator_subset_ker _)
  have hΓ := hG.quotient χ.toMonoidHom.ker
  -- The marked values: `χ x = -(1 + a)⁻¹` and `χ y = (1 - 2^f)⁻¹`.
  have hx' : (((χ x)⁻¹ : ℤ_[2]ˣ) : ℤ_[2]) = -(1 + a) :=
    Units.inv_eq_of_mul_eq_one_right (by rw [mul_neg, hx, neg_neg])
  have hy' : (((χ y)⁻¹ : ℤ_[2]ˣ) : ℤ_[2]) = 1 - 2 ^ f := Units.inv_eq_of_mul_eq_one_right hy
  -- The relation `χ y = (χ x) ^ l` descends to `[y]⁻¹ = ([x]⁻¹) ^ l` in `G ⧸ ker χ`.
  have hq : (y : G ⧸ χ.toMonoidHom.ker)⁻¹ = hΓ.padicPow (x : G ⧸ χ.toMonoidHom.ker)⁻¹ l := by
    rw [hΓ.inv_padicPow, hG.mk_eq_padicPow_mk_of_apply_eq_padicPow isProP_units_padicInt_two χ hl]
  -- The binomial series `(1 + X) ^ l` takes the value `(χ x)⁻ˡ = (χ y)⁻¹ = 1 - 2^f` at
  -- `c = (χ x)⁻¹ - 1`.
  have hc : (2 : ℤ_[2]) ∣ ((χ x⁻¹ : ℤ_[2]ˣ) : ℤ_[2]) - 1 :=
    TauCeti.Huber.PadicInt.isTopologicallyNilpotent_iff_dvd.mp (hG.hasEval_coe_apply_sub_one χ x⁻¹)
  have hb : PowerSeries.aeval (TauCeti.Huber.PadicInt.isTopologicallyNilpotent_iff_dvd.mpr hc)
      (PowerSeries.binomialSeries ℤ_[2] l) = -((2 : ℤ_[2]) ^ f - 1) := by
    have hmap : χ (hG.padicPow x l) = isProP_units_padicInt_two.padicPow (χ x) l :=
      hG.map_padicPow isProP_units_padicInt_two (χ : G →* ℤ_[2]ˣ) χ.continuous x l
    rw [hG.aeval_binomialSeries χ x⁻¹ l, hG.inv_padicPow, map_inv χ, hmap, ← hl, hy']
    ring
  -- Division by `X - c` in `ℤ_2⟦X⟧`, read in `ℤ_2[[G ⧸ ker χ]]` at `γ = [x]⁻¹`.
  have hdvd := completedGroupAlgebra.of_sub_algebraMap_dvd_algebraMap_add_of_padicPow hΓ
    (x : G ⧸ χ.toMonoidHom.ker)⁻¹ hc hb
  have h1c : (1 : ℤ_[2]) + (((χ x⁻¹ : ℤ_[2]ˣ) : ℤ_[2]) - 1) = -(1 + a) := by
    rw [map_inv χ x, hx']
    ring
  rw [hq]
  convert hdvd using 2
  · rw [h1c, map_neg, map_add, map_one, map_natCast]
    ring
  · rw [map_sub, map_pow, map_ofNat, map_one]

/-- **The basis correction for the dyadic even-rank Demushkin relator** (Labute, p. 122). For a
continuous character `χ` of a pro-`2` group `G` into `ℤ_2ˣ` and a tuple `x` with `χ (x i) = 1` for
`i ≠ 1`, `i ≠ 3`, `i < 2 * (n / 2)`, whose marked values satisfy `χ(x₂) (1 + a) = -1` and
`χ(x₄) (1 - 2^f) = 1` with `χ(x₄)` a `2`-adic power `χ(x₂) ^ l` of `χ(x₂)`, the class of
`x₁^{2+a} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (x_{n-1}, x_n)`, for `3 < n`, in `X^{ab}`, `X = ker χ`, is
the single multiple `(1 + a + [x₂]⁻¹) • ([x₁] + φ • [x₃])` over `ℤ_2[[G ⧸ X]]`, for some `φ`. -/
theorem exists_ofMul_mk_demushkinWordTwoEven_ker_eq_smul (a f : ℕ) {n : ℕ} (hn : 3 < n)
    {x : ℕ → G} (hx : ∀ i, i ≠ 1 → i ≠ 3 → i < 2 * (n / 2) → χ (x i) = 1)
    (h₁ : (χ (x 1) : ℤ_[2]) * (1 + a) = -1) (h₃ : (χ (x 3) : ℤ_[2]) * (1 - 2 ^ f) = 1) (l : ℤ_[2])
    (hl : χ (x 3) = isProP_units_padicInt_two.padicPow (χ (x 1)) l) :
    haveI := χ.isClosed_ker
    letI := (hG.topologicalAbelianization χ.toMonoidHom.ker).completedGroupAlgebraModule
      (G ⧸ χ.toMonoidHom.ker)
    ∃ φ : completedGroupAlgebra ℤ_[2] (G ⧸ χ.toMonoidHom.ker),
      Additive.ofMul ((⟨_, demushkinWordTwoEven_mem_ker χ.toMonoidHom a f n
          ((congrArg (· ^ (2 + a)) (hx 0 zero_ne_one (by decide) (by omega))).trans (one_pow _))
          ((congrArg (· ^ 2 ^ f) (hx 2 (by decide) (by decide) (by omega))).trans (one_pow _))⟩ :
            χ.toMonoidHom.ker) :
            TopologicalAbelianization χ.toMonoidHom.ker) =
        (1 + (a : completedGroupAlgebra ℤ_[2] (G ⧸ χ.toMonoidHom.ker)) +
            completedGroupAlgebra.of ℤ_[2] (G ⧸ χ.toMonoidHom.ker)
              (x 1 : G ⧸ χ.toMonoidHom.ker)⁻¹) •
          (Additive.ofMul ((⟨x 0, MonoidHom.mem_ker.mpr
              (hx 0 zero_ne_one (by decide) (by omega))⟩ : χ.toMonoidHom.ker) :
              TopologicalAbelianization χ.toMonoidHom.ker) +
            φ • Additive.ofMul ((⟨x 2, MonoidHom.mem_ker.mpr
              (hx 2 (by decide) (by decide) (by omega))⟩ : χ.toMonoidHom.ker) :
              TopologicalAbelianization χ.toMonoidHom.ker)) := by
  have := χ.isClosed_ker
  let _ := (hG.topologicalAbelianization χ.toMonoidHom.ker).completedGroupAlgebraModule
    (G ⧸ χ.toMonoidHom.ker)
  obtain ⟨φ, hφ⟩ := hG.one_add_add_of_inv_dvd_two_pow_sub_one_add_of_inv χ a f h₁ h₃ l hl
  refine ⟨φ, (hG.ofMul_mk_demushkinWordTwoEven_ker χ a f hn hx).trans ?_⟩
  rw [hφ, smul_add, mul_smul]

end IsProP

/-- **The basis correction in Labute's module** (Labute, p. 122, and Theorem 5). Let `χ` be the
standard orientation `TauCeti.orientationTwoEven` of the `q = 2`, `n` even normal form, with
marked values `χ(x₂) = v`, `v (1 + a) = -1`, and `χ(x₄) = u`, `u (1 - 2^f) = 1`, pulled back to
the free pro-`2` group `F` on `x₁, …, x_n` along the quotient map, and let `E = X^{ab}`,
`X = ker χ ≤ F`, be Labute's module over `ℤ_2[[F ⧸ X]]`. For `3 < n`, in the branch `4 ∣ a`,
`2^f ∤ a`, where `v` and `u` generate a procyclic closed subgroup, the class of the relator
`x₁^{2+a} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (x_{n-1}, x_n)` in `E` is the single multiple
`(1 + a + [x₂]⁻¹) • ([x₁] + φ • [x₃])` for some `φ`. -/
theorem exists_ofMul_mk_demushkinWordTwoEven_ker_orientationTwoEven_comp_mk_eq_smul (a f : ℕ)
    {n : ℕ} (hn : 3 < n) (v u : ℤ_[2]ˣ) (hv : (v : ℤ_[2]) * (1 + (a : ℤ_[2])) = -1)
    (hu : (u : ℤ_[2]) * (1 - (2 : ℤ_[2]) ^ f) = 1) (ha₄ : 4 ∣ (a : ℤ_[2]))
    (ha : ¬ (2 : ℤ_[2]) ^ f ∣ (a : ℤ_[2])) :
    let χ := (orientationTwoEven a f n v u).comp (presentedProP.mk 2 _)
    haveI := χ.isClosed_ker
    letI := ((isProP_freeProP 2 (Fin n)).topologicalAbelianization
      χ.toMonoidHom.ker).completedGroupAlgebraModule (freeProP 2 (Fin n) ⧸ χ.toMonoidHom.ker)
    ∃ φ : completedGroupAlgebra ℤ_[2] (freeProP 2 (Fin n) ⧸ χ.toMonoidHom.ker),
      Additive.ofMul ((⟨_, demushkinWordTwoEven_mem_ker χ.toMonoidHom a f n
          ((congrArg (· ^ (2 + a)) ((presentedProP.comp_mk_freeProPGen _ _ _ _ 0).trans
            (orientationTwoEven_presentedProPGen_of_ne a f n v u zero_ne_one
              (by decide)))).trans (one_pow _))
          ((congrArg (· ^ 2 ^ f) ((presentedProP.comp_mk_freeProPGen _ _ _ _ 2).trans
            (orientationTwoEven_presentedProPGen_of_ne a f n v u (by decide)
              (by decide)))).trans (one_pow _))⟩ : χ.toMonoidHom.ker) :
            TopologicalAbelianization χ.toMonoidHom.ker) =
        (1 + (a : completedGroupAlgebra ℤ_[2] (freeProP 2 (Fin n) ⧸ χ.toMonoidHom.ker)) +
            completedGroupAlgebra.of ℤ_[2] (freeProP 2 (Fin n) ⧸ χ.toMonoidHom.ker)
              (freeProPGen 2 n 1 : freeProP 2 (Fin n) ⧸ χ.toMonoidHom.ker)⁻¹) •
          (Additive.ofMul ((⟨freeProPGen 2 n 0, MonoidHom.mem_ker.mpr
              ((presentedProP.comp_mk_freeProPGen _ _ _ _ 0).trans
                (orientationTwoEven_presentedProPGen_of_ne a f n v u zero_ne_one (by decide)))⟩ :
              χ.toMonoidHom.ker) : TopologicalAbelianization χ.toMonoidHom.ker) +
            φ • Additive.ofMul ((⟨freeProPGen 2 n 2, MonoidHom.mem_ker.mpr
              ((presentedProP.comp_mk_freeProPGen _ _ _ _ 2).trans
                (orientationTwoEven_presentedProPGen_of_ne a f n v u (by decide) (by decide)))⟩ :
              χ.toMonoidHom.ker) : TopologicalAbelianization χ.toMonoidHom.ker)) := by
  intro χ
  have hx : ∀ i, i ≠ 1 → i ≠ 3 → i < 2 * (n / 2) → χ (freeProPGen 2 n i) = 1 := fun i hi₁ hi₃ _ ↦
    (presentedProP.comp_mk_freeProPGen _ _ _ _ i).trans
      (orientationTwoEven_presentedProPGen_of_ne a f n v u hi₁ hi₃)
  have h₁ : χ (freeProPGen 2 n 1) = v :=
    (presentedProP.comp_mk_freeProPGen _ _ _ _ 1).trans
      (orientationTwoEven_presentedProPGen_one a f n v u (by omega))
  have h₃ : χ (freeProPGen 2 n 3) = u :=
    (presentedProP.comp_mk_freeProPGen _ _ _ _ 3).trans
      (orientationTwoEven_presentedProPGen_three a f n v u hn)
  obtain ⟨l, hl⟩ := exists_padicPow_eq_of_not_dvd hv hu ha₄ ha
  exact (isProP_freeProP 2 (Fin n)).exists_ofMul_mk_demushkinWordTwoEven_ker_eq_smul χ a f hn hx
    (h₁ ▸ hv) (h₃ ▸ hu) l (by rw [h₁, h₃, hl])

end TauCeti
