/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.Character
public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.NeTwo
public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.Two.Odd.Image
public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.Two.Even.Twisted
public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.CupSquare

/-!
# Marked normal forms of Demushkin groups

The normal form of a Demushkin group records more than its abstract isomorphism type: the
isomorphism can be chosen so that the canonical character takes Labute's prescribed values on the
marked generators. This file states the marked classification for the `q ≠ 2` family, for the
dyadic family of odd rank, and for the dyadic family of even rank whose orientation image is a
twisted subgroup `U^[g]` of `ℤ_2ˣ`.

For `q ≠ 2` the relator is

`x₁ ^ q (x₁, x₂) (x₃, x₄) ⋯ (xₙ₋₁, xₙ)`,

the canonical character takes the value `(1 - q)⁻¹` on `x₂`, and it is trivial on the other
generators. The equation is stated without choosing an inverse, as
`χ(x₂) * (1 - q) = 1` in `ℤ_p`.

For odd rank `n`, where `p = 2` and `q = 2`, the relator is

`x₁² x₂^{2^f} (x₂, x₃) (x₄, x₅) ⋯ (xₙ₋₁, xₙ)`, `2 ≤ f < ∞`, or `x₁² (x₂, x₃) ⋯ (xₙ₋₁, xₙ)`, `f = ∞`,

the canonical character takes the value `-1` on `x₁`, the value `(1 - 2^f)⁻¹` on `x₃` at a finite
level, and is trivial on the other generators. The level `f` is an invariant of the group, the
level of the image `{±1} × U^(f)` of its canonical character, with `f = ∞` the image `{±1}`; the
statements take the image as a hypothesis, which is what pins `f`, and the finite-level statement
assumes `n ≥ 3`, since at rank one the marking clause on the third generator would read
`1 - 2^f = 1` (`TauCeti.not_marked_of_demushkinRank_le`). The standard dyadic group `D₀` is the
case `n = 3`, `f = 2`.

For even rank `n`, where `p = 2` and `q = 2`, with the image of the canonical character the twisted
subgroup `U^[g]`, the closed subgroup generated by `-1 + 2^g`, `2 ≤ g < ∞`, the relator is

`x₁^{2 + 2^g} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (xₙ₋₁, xₙ)` for `n ≥ 4` and any finite `f > g`, or
`x₁^{2 + 2^g} (x₁, x₂)` for `n = 2`,

the canonical character takes the value `-(1 + 2^g)⁻¹` on `x₂`, the value `(1 - 2^f)⁻¹` on `x₄`
when `n ≥ 4`, and is trivial on the other generators. Here the image pins `g = v₂(α)` but not the
level `f`, which is free above `g`
(`TauCeti.nonempty_continuousMulEquiv_presentedProP_demushkinWordTwoEven_two_pow`); the statement
at rank `n ≥ 4` therefore holds for every finite `f > g`, and the rank-two word carries no level.
The fourth-generator clause is stated only for `n ≥ 4`: at rank two it would read `1 - 2^f = 1`
(`TauCeti.not_marked_of_demushkinRank_le`), although the other hypotheses are met there, by
`⟨x₁, x₂ ∣ x₁⁶ (x₁, x₂)⟩` with `g = 2`.

## Main results

* `TauCeti.isDemushkin_marked_of_q_ne_two`: the marked classification of a Demushkin group whose
  `q`-invariant is not `2`.
* `TauCeti.isDemushkin_marked_of_q_two_odd`, `TauCeti.isDemushkin_marked_of_q_two_odd_top`: the
  marked classification of a Demushkin group of odd rank, at a finite level and at level `f = ∞`.
* `TauCeti.isDemushkin_marked_of_q_two_even_twisted`,
  `TauCeti.isDemushkin_marked_of_q_two_rank_two_twisted`: the marked classification of a Demushkin
  group of even rank whose orientation image is a twisted subgroup `U^[g]`, at rank `n ≥ 4` and at
  rank `2`.

## References

* J. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), 106--132,
  Theorems 3, 4 and 5.
-/

public section

namespace TauCeti

open Subgroup

universe u

variable {p : ℕ} [Fact p.Prime] {G : Type u} [Group G] [TopologicalSpace G]
  [IsTopologicalGroup G] [CompactSpace G] [TotallyDisconnectedSpace G]

/-- **The marked classification at `q ≠ 2`.** A Demushkin group with `q`-invariant different
from `2` is isomorphic to the standard one-relator presentation on its generator rank. Under this
isomorphism the canonical character takes the value `(1 - q)⁻¹` on the second marked generator
and is trivial on every other marked generator. -/
theorem isDemushkin_marked_of_q_ne_two (hG : IsDemushkin p G) (hq : demushkinQ hG ≠ 2) :
    ∃ e : G ≃ₜ* presentedProP p (Fin (demushkinRank hG))
        {demushkinWordNeTwo (demushkinQ hG) (demushkinRank hG)
          (freeProPGen p (demushkinRank hG))},
      ((demushkinCharacter hG
          (e.symm (presentedProPGen p (demushkinRank hG) _ 1)) : ℤ_[p])
          * (1 - (demushkinQ hG : ℤ_[p])) = 1) ∧
        ∀ i : ℕ, i ≠ 1 → i < demushkinRank hG →
          demushkinCharacter hG
            (e.symm (presentedProPGen p (demushkinRank hG) _ i)) = 1 := by
  obtain ⟨e⟩ := hG.exists_continuousMulEquiv_presentedProP_demushkinWordNeTwo_of_demushkinQ_ne_two
    hq
  refine ⟨e, ?_⟩
  have heven : Even (demushkinRank hG) := by
    by_cases hp : p = 2
    · subst p
      exact hG.even_demushkinRank_of_demushkinQ_ne_two hq
    · exact hG.even_demushkinRank_of_ne_two hp
  have hn : 1 < demushkinRank hG := by
    obtain ⟨k, hk⟩ := heven
    have := hG.demushkinRank_pos
    omega
  obtain ⟨hvalue, htrivial⟩ :=
    demushkinCharacter_apply_equiv_symm_of_equiv_demushkinWordNeTwo hG
      hG.prime_dvd_demushkinQ heven hn e
  exact ⟨hvalue, fun i hi _ ↦ htrivial i hi⟩

/-- **The marked classification at `q = 2` with `n` odd, finite level.** A Demushkin group at
`p = 2` of odd rank `n ≥ 3` whose canonical character has image `{±1} × U^(f)`, with `f ≥ 2`, is
isomorphic to `⟨x₁, …, xₙ ∣ x₁² x₂^{2^f} (x₂, x₃) ⋯ (xₙ₋₁, xₙ)⟩`. Under this isomorphism the
canonical character takes the value `-1` on the first marked generator, the value `(1 - 2^f)⁻¹` on
the third, and is trivial on every other marked generator. -/
theorem isDemushkin_marked_of_q_two_odd (hG : IsDemushkin 2 G) (hodd : Odd (demushkinRank hG))
    (hn : 3 ≤ demushkinRank hG) {f : ℕ} (hf : 2 ≤ f)
    (hrange : (demushkinCharacter hG).toMonoidHom.range = unitsPlusMinus f) :
    ∃ e : G ≃ₜ* presentedProP 2 (Fin (demushkinRank hG))
        {demushkinWordTwoOdd f (demushkinRank hG) (freeProPGen 2 (demushkinRank hG))},
      demushkinCharacter hG (e.symm (presentedProPGen 2 (demushkinRank hG) _ 0)) = -1 ∧
        ((demushkinCharacter hG (e.symm (presentedProPGen 2 (demushkinRank hG) _ 2)) : ℤ_[2])
          * (1 - 2 ^ f) = 1) ∧
        ∀ i : ℕ, i ≠ 0 → i ≠ 2 → i < demushkinRank hG →
          demushkinCharacter hG (e.symm (presentedProPGen 2 (demushkinRank hG) _ i)) = 1 := by
  obtain ⟨e⟩ :=
    hG.nonempty_continuousMulEquiv_presentedProP_demushkinWordTwoOdd_of_range_eq hodd hn hf hrange
  obtain ⟨hfirst, hthird, htrivial⟩ :=
    demushkinCharacter_apply_equiv_symm_of_equiv_demushkinWordTwoOdd hG (by omega) hodd (by omega) e
  exact ⟨e, hfirst, hthird, fun i hi hi' _ ↦ htrivial i hi hi'⟩

/-- **The marked classification at `q = 2` with `n` odd, level `f = ∞`.** A Demushkin group at
`p = 2` of odd rank `n` whose canonical character has image `{±1}` is isomorphic to
`⟨x₁, …, xₙ ∣ x₁² (x₂, x₃) ⋯ (xₙ₋₁, xₙ)⟩`. Under this isomorphism the canonical character takes
the value `-1` on the first marked generator and is trivial on every other marked generator. At
rank one this is `ℤ/2 = ⟨x₁ ∣ x₁²⟩` with `χ(x₁) = -1`. -/
theorem isDemushkin_marked_of_q_two_odd_top (hG : IsDemushkin 2 G) (hodd : Odd (demushkinRank hG))
    (hrange : (demushkinCharacter hG).toMonoidHom.range = zpowers (-1 : ℤ_[2]ˣ)) :
    ∃ e : G ≃ₜ* presentedProP 2 (Fin (demushkinRank hG))
        {demushkinWordTwoOddTop (demushkinRank hG) (freeProPGen 2 (demushkinRank hG))},
      demushkinCharacter hG (e.symm (presentedProPGen 2 (demushkinRank hG) _ 0)) = -1 ∧
        ∀ i : ℕ, i ≠ 0 → i < demushkinRank hG →
          demushkinCharacter hG (e.symm (presentedProPGen 2 (demushkinRank hG) _ i)) = 1 := by
  obtain ⟨e⟩ :=
    hG.nonempty_continuousMulEquiv_presentedProP_demushkinWordTwoOddTop_of_range_eq hodd hrange
  obtain ⟨hfirst, htrivial⟩ :=
    demushkinCharacter_apply_equiv_symm_of_equiv_demushkinWordTwoOddTop hG hodd e
  exact ⟨e, hfirst, fun i hi _ ↦ htrivial i hi⟩

/-- **The marked classification at `q = 2` with `n ≥ 4` even and twisted orientation image.** A
Demushkin group at `p = 2` of even rank `n ≥ 4` whose canonical character has image the twisted
subgroup `U^[g]`, the closed subgroup generated by `-1 + 2^g`, with `g ≥ 2`, is isomorphic to
`⟨x₁, …, xₙ ∣ x₁^{2 + 2^g} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (xₙ₋₁, xₙ)⟩` for every finite level
`f > g`. Under this isomorphism the canonical character takes the value `-(1 + 2^g)⁻¹` on the
second marked generator, the value `(1 - 2^f)⁻¹` on the fourth, and is trivial on every other
marked generator. -/
theorem isDemushkin_marked_of_q_two_even_twisted (hG : IsDemushkin 2 G)
    (heven : Even (demushkinRank hG)) (hn : 4 ≤ demushkinRank hG) {g f : ℕ} (hg : 2 ≤ g)
    (hgf : g < f) {w : ℤ_[2]ˣ} (hw : (w : ℤ_[2]) = -1 + (2 : ℤ_[2]) ^ g)
    (hrange : (demushkinCharacter hG).toMonoidHom.range = (zpowers w).topologicalClosure) :
    ∃ e : G ≃ₜ* presentedProP 2 (Fin (demushkinRank hG))
        {demushkinWordTwoEven (2 ^ g) f (demushkinRank hG) (freeProPGen 2 (demushkinRank hG))},
      ((demushkinCharacter hG (e.symm (presentedProPGen 2 (demushkinRank hG) _ 1)) : ℤ_[2])
          * (1 + 2 ^ g) = -1) ∧
        ((demushkinCharacter hG (e.symm (presentedProPGen 2 (demushkinRank hG) _ 3)) : ℤ_[2])
          * (1 - 2 ^ f) = 1) ∧
        ∀ i : ℕ, i ≠ 1 → i ≠ 3 → i < demushkinRank hG →
          demushkinCharacter hG (e.symm (presentedProPGen 2 (demushkinRank hG) _ i)) = 1 := by
  obtain ⟨e₁⟩ :=
    hG.exists_continuousMulEquiv_presentedProP_demushkinWordNeTwo_of_range_eq heven hg hw hrange
  obtain ⟨e₂⟩ :=
    nonempty_continuousMulEquiv_presentedProP_demushkinWordTwoEven_two_pow heven (by omega) hg hgf
  obtain ⟨hsecond, hfourth, htrivial⟩ :=
    demushkinCharacter_apply_equiv_symm_of_equiv_demushkinWordTwoEven hG (dvd_pow_self 2 (by omega))
      (by omega) heven (by omega) (e₁.trans e₂.symm)
  exact ⟨e₁.trans e₂.symm, by exact_mod_cast hsecond, hfourth, fun i hi hi' _ ↦ htrivial i hi hi'⟩

/-- **The marked classification at `q = 2` and rank two with twisted orientation image.** A
Demushkin group at `p = 2` of rank `2` whose canonical character has image the twisted subgroup
`U^[g]`, the closed subgroup generated by `-1 + 2^g`, with `g ≥ 2`, is isomorphic to
`⟨x₁, x₂ ∣ x₁^{2 + 2^g} (x₁, x₂)⟩`. Under this isomorphism the canonical character is trivial on
the first marked generator and takes the value `-(1 + 2^g)⁻¹` on the second. -/
theorem isDemushkin_marked_of_q_two_rank_two_twisted (hG : IsDemushkin 2 G)
    (hn : demushkinRank hG = 2) {g : ℕ} (hg : 2 ≤ g) {w : ℤ_[2]ˣ}
    (hw : (w : ℤ_[2]) = -1 + (2 : ℤ_[2]) ^ g)
    (hrange : (demushkinCharacter hG).toMonoidHom.range = (zpowers w).topologicalClosure) :
    ∃ e : G ≃ₜ* presentedProP 2 (Fin 2) {demushkinWordTwoRankTwo (2 ^ g) (freeProPGen 2 2)},
      demushkinCharacter hG (e.symm (presentedProPGen 2 2 _ 0)) = 1 ∧
        (demushkinCharacter hG (e.symm (presentedProPGen 2 2 _ 1)) : ℤ_[2]) * (1 + 2 ^ g) = -1 := by
  obtain ⟨e₁⟩ := hG.exists_continuousMulEquiv_presentedProP_demushkinWordNeTwo_of_range_eq
    (by rw [hn]; exact even_two) hg hw hrange
  rw [hn] at e₁
  have e : G ≃ₜ* presentedProP 2 (Fin 2) {demushkinWordTwoRankTwo (2 ^ g) (freeProPGen 2 2)} := by
    rw [demushkinWordTwoRankTwo_eq_demushkinWordNeTwo]
    exact e₁
  obtain ⟨hfirst, hsecond⟩ :=
    demushkinCharacter_apply_equiv_symm_of_equiv_demushkinWordTwoRankTwo hG
      (dvd_pow_self 2 (by omega)) e
  exact ⟨e, hfirst, by exact_mod_cast hsecond⟩

end TauCeti
