/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.Presentation.MinusculeWeightTable.Rational
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.CoordinateLattice
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.Serre
import TauCeti.Algebra.Lie.Sl2.Basic
import TauCeti.LinearAlgebra.Matrix.MulVec

/-!
# The admissible lattice of a minuscule weight table

The rational representation of a minuscule weight table acts on the rational coordinate space of
its index type, and the Kostant form of its Serre generators carries the integral lattice of that
space into itself.

Two properties of the table make that so. Each root generator is square-zero: the raising
operator at a node carries a weight of coordinate `-1` to its reflection, whose coordinate is
`1`, and kills every weight of coordinate `1`. And each root generator has integer entries, so it
carries integral coordinate vectors to integral coordinate vectors. The Cartan generators are
diagonal with the table's weights on the diagonal, so every standard coordinate vector is a
weight vector with an integral weight. Divided powers of a square-zero operator and binomial
coefficients of an operator with integral eigenvalues are what the Kostant form is generated by.

## Main declarations

* `TauCeti.MinusculeWeightTable.rep`: the rational representation extended to the universal
  enveloping algebra.

## Main results

* `TauCeti.MinusculeWeightTable.rep_serreRootGenerator_pow_two` and
  `isNilpotent_rep_serreRootGenerator`: the represented root generators are square-zero.
* `TauCeti.MinusculeWeightTable.isCartanWeightVector_single`: each standard coordinate vector is a
  Cartan weight vector with its weight in the table.
* `TauCeti.MinusculeWeightTable.isSl2Triple_rep_serreRootGenerator`: the represented positive,
  negative, and Cartan generators at a node form an `sl₂` triple.
* `TauCeti.MinusculeWeightTable.rep_serreKostantForm_mem_lattice`: the Serre Kostant form carries
  `TauCeti.coordinateLattice` into itself.
* `TauCeti.MinusculeWeightTable.Symmetry.moduleEquiv_rep_ι_serreRootGenerator`: the coordinate
  permutation `TauCeti.MinusculeWeightTable.Symmetry.moduleEquiv` of a table symmetry intertwines
  the represented root generators along `TauCeti.MinusculeWeightTable.Symmetry.rootPerm`, and it
  preserves the coordinate lattice by `moduleEquiv_mem_coordinateLattice_iff`. These are the
  module-level inputs for descending a table symmetry to a Kostant toral-closure carrier.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1--2.
-/

public section

open scoped Matrix

namespace TauCeti.MinusculeWeightTable

attribute [local instance 100] LieRing.ofAssociativeRing

namespace Symmetry

variable {B ι : Type*} {T : MinusculeWeightTable B ι} (S : T.Symmetry)

/-- The coordinate permutation of a symmetry preserves the integral coordinate lattice, in both
directions. -/
theorem moduleEquiv_mem_coordinateLattice_iff [Finite ι] (v : ι → ℚ) :
    S.moduleEquiv v ∈ TauCeti.coordinateLattice ι ↔ v ∈ TauCeti.coordinateLattice ι := by
  simp only [TauCeti.mem_coordinateLattice_iff, moduleEquiv_apply]
  exact ⟨fun h a => by simpa only [Equiv.symm_apply_apply] using h (S.indexPerm a),
    fun h a => h (S.indexPerm.symm a)⟩

end Symmetry

variable {B ι : Type*} [Fintype ι] [DecidableEq ι] (T : MinusculeWeightTable B ι)
variable [DecidableEq B]

/-! ## The enveloping-algebra representation -/

/-- The rational representation extended to the universal enveloping algebra. -/
noncomputable def rep :
    _root_.UniversalEnvelopingAlgebra ℚ (Matrix.ToLieAlgebra ℚ T.cartanMatrix) →ₐ[ℚ]
      Module.End ℚ (ι → ℚ) :=
  _root_.UniversalEnvelopingAlgebra.lift ℚ
    ((Matrix.toLinAlgEquiv (Pi.basisFun ℚ ι)).toAlgHom.toLieHom.comp
      T.rationalSerreRepresentation)

/-- The enveloping-algebra representation acts on an included Lie element by matrix-vector
multiplication. -/
theorem rep_ι_apply (x : Matrix.ToLieAlgebra ℚ T.cartanMatrix) (v : ι → ℚ) :
    T.rep (_root_.UniversalEnvelopingAlgebra.ι ℚ x) v = T.rationalSerreRepresentation x *ᵥ v := by
  rw [rep, _root_.UniversalEnvelopingAlgebra.lift_ι_apply, LieHom.comp_apply,
    AlgHom.toLieHom_apply, AlgEquiv.toAlgHom_apply, Matrix.toLinAlgEquiv_apply]
  exact (Pi.basisFun ℚ ι).sum_repr (T.rationalSerreRepresentation x *ᵥ v)

/-- Every represented positive or negative Serre root generator is square-zero. -/
theorem rep_serreRootGenerator_pow_two (k : B ⊕ B) :
    T.rep (_root_.UniversalEnvelopingAlgebra.ι ℚ
      (TauCeti.serreRootGenerator T.cartanMatrix k)) ^ 2 = 0 := by
  apply LinearMap.ext
  intro v
  rw [pow_two, Module.End.mul_apply]
  cases k with
  | inl i =>
      simpa only [TauCeti.serreRootGenerator_inl, T.rep_ι_apply,
        T.rationalSerreRepresentation_serreE, LinearMap.zero_apply] using
        mulVec_mulVec_eq_zero_of_pow_two_eq_zero (T.raisingMatrixQ_pow_two i) v
  | inr i =>
      simpa only [TauCeti.serreRootGenerator_inr, T.rep_ι_apply,
        T.rationalSerreRepresentation_serreF, LinearMap.zero_apply] using
        mulVec_mulVec_eq_zero_of_pow_two_eq_zero (T.loweringMatrixQ_pow_two i) v

/-- Every represented positive or negative Serre root generator acts nilpotently. -/
theorem isNilpotent_rep_serreRootGenerator (k : B ⊕ B) :
    IsNilpotent (T.rep (_root_.UniversalEnvelopingAlgebra.ι ℚ
      (TauCeti.serreRootGenerator T.cartanMatrix k))) :=
  ⟨2, T.rep_serreRootGenerator_pow_two k⟩

/-- The represented Cartan, positive, and negative Serre generators at a node form an `sl₂`
triple whenever the weight table contains a weight of nonzero coordinate at that node. -/
theorem isSl2Triple_rep_serreRootGenerator (i : B) (hi : ∃ a, T.weight a i ≠ 0) :
    _root_.IsSl2Triple
      (T.rep (_root_.UniversalEnvelopingAlgebra.ι ℚ (TauCeti.serreH ℚ T.cartanMatrix i)))
      (T.rep (_root_.UniversalEnvelopingAlgebra.ι ℚ
        (TauCeti.serreRootGenerator T.cartanMatrix (.inl i))))
      (T.rep (_root_.UniversalEnvelopingAlgebra.ι ℚ
        (TauCeti.serreRootGenerator T.cartanMatrix (.inr i)))) := by
  obtain ⟨a, ha⟩ := hi
  let toEnd : Matrix ι ι ℚ →ₗ⁅ℚ⁆ Module.End ℚ (ι → ℚ) :=
    (Matrix.toLinAlgEquiv' (R := ℚ) (n := ι)).toAlgHom.toLieHom
  have hEnd : toEnd (T.cartanGeneratorMatrixQ i) ≠ 0 := by
    intro hzero
    have hz := DFunLike.congr_fun hzero (Pi.single a 1)
    have hza := congrFun hz a
    simp [toEnd, Matrix.mulVec, dotProduct, Pi.single_apply, ha] at hza
  have h := (T.isSl2TripleQ i ⟨a, ha⟩).map toEnd hEnd
  -- `IsSl2Triple.map` retains the bundled Lie-hom application; expose the equivalent matrix
  -- action so the three representation equations below can rewrite it.
  change _root_.IsSl2Triple
    (Matrix.toLinAlgEquiv' (T.cartanGeneratorMatrixQ i))
    (Matrix.toLinAlgEquiv' (T.raisingMatrixQ i))
    (Matrix.toLinAlgEquiv' (T.loweringMatrixQ i)) at h
  have hH : Matrix.toLinAlgEquiv' (T.cartanGeneratorMatrixQ i) =
      T.rep (_root_.UniversalEnvelopingAlgebra.ι ℚ (TauCeti.serreH ℚ T.cartanMatrix i)) := by
    apply LinearMap.ext
    intro v
    rw [T.rep_ι_apply, T.rationalSerreRepresentation_serreH, Matrix.toLinAlgEquiv'_apply]
  have hE : Matrix.toLinAlgEquiv' (T.raisingMatrixQ i) =
      T.rep (_root_.UniversalEnvelopingAlgebra.ι ℚ
        (TauCeti.serreRootGenerator T.cartanMatrix (.inl i))) := by
    apply LinearMap.ext
    intro v
    rw [TauCeti.serreRootGenerator_inl, T.rep_ι_apply,
      T.rationalSerreRepresentation_serreE, Matrix.toLinAlgEquiv'_apply]
  have hF : Matrix.toLinAlgEquiv' (T.loweringMatrixQ i) =
      T.rep (_root_.UniversalEnvelopingAlgebra.ι ℚ
        (TauCeti.serreRootGenerator T.cartanMatrix (.inr i))) := by
    apply LinearMap.ext
    intro v
    rw [TauCeti.serreRootGenerator_inr, T.rep_ι_apply,
      T.rationalSerreRepresentation_serreF, Matrix.toLinAlgEquiv'_apply]
  rwa [hH, hE, hF] at h

/-! ## Stability of the coordinate lattice -/

/-- Every represented Serre root generator preserves the coordinate lattice. -/
theorem rep_serreRootGenerator_mem_lattice (k : B ⊕ B) {v : ι → ℚ}
    (hv : v ∈ TauCeti.coordinateLattice ι) :
    T.rep (_root_.UniversalEnvelopingAlgebra.ι ℚ
      (TauCeti.serreRootGenerator T.cartanMatrix k)) v ∈ TauCeti.coordinateLattice ι := by
  rw [T.rep_ι_apply]
  cases k with
  | inl i =>
      rw [TauCeti.serreRootGenerator_inl, T.rationalSerreRepresentation_serreE]
      have hmatrix : T.raisingMatrixQ i = TauCeti.matrixIntCastLieHom ℚ (T.raisingMatrix i) := by
        ext a b
        rw [T.raisingMatrixQ_apply, TauCeti.matrixIntCastLieHom_apply, T.raisingMatrix_apply]
        split_ifs <;> norm_num
      rw [hmatrix]
      exact Matrix.intCastLieHom_mulVec_mem_coordinateLattice (T.raisingMatrix i) hv
  | inr i =>
      rw [TauCeti.serreRootGenerator_inr, T.rationalSerreRepresentation_serreF]
      have hmatrix : T.loweringMatrixQ i = TauCeti.matrixIntCastLieHom ℚ (T.loweringMatrix i) := by
        ext a b
        rw [T.loweringMatrixQ_apply, TauCeti.matrixIntCastLieHom_apply, T.loweringMatrix_apply]
        split_ifs <;> norm_num
      rw [hmatrix]
      exact Matrix.intCastLieHom_mulVec_mem_coordinateLattice (T.loweringMatrix i) hv

/-- Each standard coordinate vector is a Cartan weight vector with its weight in the table. -/
theorem isCartanWeightVector_single (a : ι) :
    TauCeti.UniversalEnvelopingAlgebra.IsCartanWeightVector
      (TauCeti.serreH ℚ T.cartanMatrix) T.rep (T.weight a) (Pi.single a 1) := by
  refine (TauCeti.UniversalEnvelopingAlgebra.isCartanWeightVector_iff
    (TauCeti.serreH ℚ T.cartanMatrix) T.rep).mpr fun i ↦ ?_
  rw [T.rep_ι_apply, T.rationalSerreRepresentation_serreH]
  ext b
  simp [Matrix.mulVec, dotProduct, Pi.single_apply]

/-- Every coordinate-lattice basis vector is a Cartan weight vector with its weight in the
table. -/
theorem isCartanWeightVector_coordinateLatticeBasis (a : ι) :
    TauCeti.UniversalEnvelopingAlgebra.IsCartanWeightVector
      (TauCeti.serreH ℚ T.cartanMatrix) T.rep (T.weight a)
      ((TauCeti.coordinateLatticeBasis ι a : TauCeti.coordinateLattice ι) : ι → ℚ) := by
  rw [TauCeti.coe_coordinateLatticeBasis, Pi.basisFun_apply]
  exact T.isCartanWeightVector_single a

/-- **The coordinate lattice is admissible for the Serre Kostant form of a minuscule weight
table.** -/
theorem rep_serreKostantForm_mem_lattice
    {u : _root_.UniversalEnvelopingAlgebra ℚ (Matrix.ToLieAlgebra ℚ T.cartanMatrix)}
    (hu : u ∈ TauCeti.serreKostantForm T.cartanMatrix) {v : ι → ℚ}
    (hv : v ∈ TauCeti.coordinateLattice ι) :
    T.rep u v ∈ TauCeti.coordinateLattice ι := by
  rw [TauCeti.serreKostantForm_def] at hu
  exact TauCeti.UniversalEnvelopingAlgebra.kostantForm_apply_mem_coordinateLattice
    (TauCeti.serreRootGenerator T.cartanMatrix) (TauCeti.serreH ℚ T.cartanMatrix) T.rep
    (wt := T.weight) T.rep_serreRootGenerator_pow_two
    (fun k _ hw ↦ T.rep_serreRootGenerator_mem_lattice k hw) T.isCartanWeightVector_single hu hv

/-- The coordinate lattice is stable under the generic Kostant form built from the Serre
generators. This is the form consumed by the carrier and base-change APIs. -/
theorem rep_kostantForm_mem_lattice
    (u : _root_.UniversalEnvelopingAlgebra ℚ (Matrix.ToLieAlgebra ℚ T.cartanMatrix))
    (hu : u ∈ TauCeti.UniversalEnvelopingAlgebra.kostantForm
      (TauCeti.serreRootGenerator T.cartanMatrix) (TauCeti.serreH ℚ T.cartanMatrix))
    (v : ι → ℚ) (hv : v ∈ TauCeti.coordinateLattice ι) :
    T.rep u v ∈ TauCeti.coordinateLattice ι :=
  T.rep_serreKostantForm_mem_lattice (by
    rw [TauCeti.serreKostantForm_def]
    exact hu) hv

/-! ## Symmetries on the rational module -/

namespace Symmetry

variable {T} (S : T.Symmetry)

/-- **The coordinate permutation of a table symmetry intertwines the represented positive and
negative simple-root generators along the induced root permutation.** -/
theorem moduleEquiv_rep_ι_serreRootGenerator (k : B ⊕ B) (v : ι → ℚ) :
    S.moduleEquiv
        (T.rep (_root_.UniversalEnvelopingAlgebra.ι ℚ
          (TauCeti.serreRootGenerator T.cartanMatrix k)) v) =
      T.rep (_root_.UniversalEnvelopingAlgebra.ι ℚ
          (TauCeti.serreRootGenerator T.cartanMatrix (S.rootPerm k))) (S.moduleEquiv v) := by
  have hcoe : ⇑S.moduleEquiv = fun w => w ∘ S.indexPerm.symm := by
    funext w a
    exact S.moduleEquiv_apply w a
  simp only [hcoe, T.rep_ι_apply]
  cases k with
  | inl i =>
    have hY : T.raisingMatrixQ (S.nodePerm i) =
        (T.raisingMatrixQ i).submatrix S.indexPerm.symm S.indexPerm.symm := by
      rw [← S.raisingMatrixQ_submatrix i, Matrix.submatrix_submatrix, Equiv.self_comp_symm,
        Matrix.submatrix_id_id]
    rw [TauCeti.serreRootGenerator_inl, rootPerm_inl, TauCeti.serreRootGenerator_inl,
      T.rationalSerreRepresentation_serreE, T.rationalSerreRepresentation_serreE, hY,
      Matrix.submatrix_mulVec_equiv, Equiv.symm_symm, Function.comp_assoc, Equiv.symm_comp_self,
      Function.comp_id]
  | inr i =>
    have hY : T.loweringMatrixQ (S.nodePerm i) =
        (T.loweringMatrixQ i).submatrix S.indexPerm.symm S.indexPerm.symm := by
      rw [← S.loweringMatrixQ_submatrix i, Matrix.submatrix_submatrix, Equiv.self_comp_symm,
        Matrix.submatrix_id_id]
    rw [TauCeti.serreRootGenerator_inr, rootPerm_inr, TauCeti.serreRootGenerator_inr,
      T.rationalSerreRepresentation_serreF, T.rationalSerreRepresentation_serreF, hY,
      Matrix.submatrix_mulVec_equiv, Equiv.symm_symm, Function.comp_assoc, Equiv.symm_comp_self,
      Function.comp_id]

end Symmetry

end TauCeti.MinusculeWeightTable
