/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.E7.Minuscule.Carrier
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Coroot

/-!
# Generation of the E₇ minuscule weight torus by root subgroups

The type-`E₇` minuscule carrier is defined using both its fourteen numbered simple root
subgroups and its rank-seven weight torus. This file proves that, on the underlying
base-changed lattice over any commutative ring, the torus is already contained in the elementary
group generated by the root subgroups.

The represented simple generators at each node form an `sl₂` triple by
`TauCeti.E7Minuscule.isSl2Triple_rep_serreRootGenerator`. The remaining concrete input is
supplied here: every row of the type-`E₇` Cartan matrix contains `-1`, so its entries have an
explicit integral linear combination equal to one. The generic coroot-generation theorem then
puts every coordinate cocharacter, and hence the whole weight torus, in the elementary group.

The conclusion concerns subgroups of the automorphism group of the base-changed admissible
lattice. Identifying those generated points with all points of the toral-closure group scheme is
a separate scheme-theoretic comparison.

## Main results

* `TauCeti.E7Minuscule.weightTorusSubgroup_le_elementarySubgroup`: the weight torus lies in the
  elementary subgroup over every commutative ring.
* `TauCeti.E7Minuscule.weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup`: adjoining the
  weight torus to all numbered root subgroups gives exactly the elementary subgroup.
-/

public section

open scoped Matrix TensorProduct

universe v

namespace TauCeti.E7Minuscule

open TauCeti.DynkinType TauCeti.UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

local notation "CM" => CartanMatrix.E 7
local notation "rootGen" => TauCeti.serreRootGenerator CM
local notation "cartanGen" => TauCeti.serreH ℚ CM

private def rootCharacter : Fin 7 ⊕ Fin 7 → Fin 7 → ℤ
  | .inl i => CM i
  | .inr i => -CM i

private theorem lie_cartanGenerator_rootGenerator' (k : Fin 7 ⊕ Fin 7) (j : Fin 7) :
    ⁅cartanGen j, rootGen k⁆ = ((rootCharacter k j : ℤ) : ℚ) • rootGen k := by
  cases k with
  | inl i =>
      rw [rootCharacter, TauCeti.serreRootGenerator_inl, TauCeti.lie_serreH_serreE,
        (CartanMatrix.E_isSymm 7).apply]
      simp only [Int.cast_smul_eq_zsmul]
  | inr i =>
      rw [rootCharacter, TauCeti.serreRootGenerator_inr, TauCeti.lie_serreH_serreF,
        (CartanMatrix.E_isSymm 7).apply]
      simp only [Pi.neg_apply, Int.cast_neg, neg_smul, Int.cast_smul_eq_zsmul]

private def cartanNeighbor : Fin 7 → Fin 7 :=
  ![2, 3, 0, 1, 3, 4, 5]

private def cartanBezout (i j : Fin 7) : ℤ :=
  if j = cartanNeighbor i then -1 else 0

private theorem cartan_sum_mul_bezout (i : Fin 7) :
    ∑ j, CM i j * cartanBezout i j = 1 := by
  fin_cases i <;> decide

private theorem rootWeight_sum_mul_bezout (i : Fin 7) :
    ∑ j, rootCharacter (.inl i) j * cartanBezout i j = 1 := by
  simpa only [rootCharacter] using cartan_sum_mul_bezout i

private theorem rootWeight_inr_eq_neg_inl (i : Fin 7) :
    rootCharacter (.inr i) = -rootCharacter (.inl i) := by
  rfl

/-- Over every commutative ring, the type-`E₇` minuscule weight torus on the base-changed
admissible lattice is contained in the elementary group generated by the fourteen positive and
negative numbered simple root subgroups. -/
theorem weightTorusSubgroup_le_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubgroup lattice.toAddSubgroup
        latticeBasis e7MinusculeWeight A ≤
      kostantElementarySubgroup rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator A := by
  exact kostantTorusSubgroup_le_kostantElementarySubgroup
    rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight
    isCartanWeightVector_latticeBasis rootCharacter lie_cartanGenerator_rootGenerator'
    Sum.inl Sum.inr isSl2Triple_rep_serreRootGenerator rootWeight_inr_eq_neg_inl cartanBezout
    rootWeight_sum_mul_bezout A

/-- Over every commutative ring, adjoining the type-`E₇` minuscule weight torus to all fourteen
numbered simple root subgroups does not enlarge their elementary subgroup. -/
theorem weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubsystemSubgroup rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight Set.univ A =
      kostantElementarySubgroup rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator A := by
  exact
    kostantTorusSubsystemSubgroup_univ_eq_kostantElementarySubgroup
      rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
      isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight
      isCartanWeightVector_latticeBasis rootCharacter lie_cartanGenerator_rootGenerator'
      Sum.inl Sum.inr isSl2Triple_rep_serreRootGenerator rootWeight_inr_eq_neg_inl cartanBezout
      rootWeight_sum_mul_bezout A

end TauCeti.E7Minuscule
