/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.ResidueDegree
public import TauCeti.NumberTheory.Multiquadratic.Quadratic.Ramification
import TauCeti.Algebra.Squarefree
import TauCeti.FieldTheory.Galois.FixedField
import TauCeti.FieldTheory.IntermediateField.Adjoin.EqTop
import TauCeti.NumberTheory.NumberField.Inertia
import TauCeti.NumberTheory.RamificationInertia.Galois

/-!
# Inertia and ramification index above `2` in a multiquadratic field

Let `K = ℚ(√d₁, …, √dₙ)` be a number field generated over `ℚ` by square roots `r i` of integers
`d i` not divisible by `4` (for instance squarefree), and let `Q` be a prime of `𝓞 K` above `2`.
When every `dᵢ` is `1` modulo `4` the prime `2` is unramified
(`TauCeti.Multiquadratic.inertia_eq_bot_of_forall_mod_four_eq_one`). This file computes the
ramification index `e` of `Q` in general. Unlike at an odd prime, it can be `4`:

* `e = 4` exactly when some `dᵢ` is `3` modulo `4` and some `dⱼ` is even, or some `dᵢ` is `2` and
  some `dⱼ` is `6` modulo `8`;
* otherwise `e = 2` if some `dᵢ` is not `1` modulo `4`, and `e = 1` if every `dᵢ` is.

Behind the case split are the square classes of `ℚ₂`. Modulo squares and the unramified class of
`5`, an integer not divisible by `4` falls into one of four classes, according to whether it is
`1` or `3` modulo `4` when odd, and `2` or `6` modulo `8` when even; these classes form a group of
order `4`, and `e` is the order of the subgroup generated by the classes of the `dᵢ`. The proofs
below do not use `ℚ₂`, and work with the action of inertia on square roots in `K` instead.

* **Upper bound.** An inertia element `τ` fixes every square root of an integer that is `1`
  modulo `4` (`TauCeti.Multiquadratic.apply_eq_self_of_mem_inertia_of_mod_four_eq_one`). Applied
  to `rᵢ rⱼ`, `rᵢ rⱼ / 2` and `rᵢ rⱼ rₖ / 2` for suitable radicands, this shows that `τ` is
  determined by its signs on at most two of the `rᵢ`, so the inertia group has at most four
  elements, and at most two outside the first case above.
* **Lower bound.** A square root `x` of an integer that is `2` or `3` modulo `4` generates a
  quadratic field ramified at `2`, so some inertia element negates `x`
  (`TauCeti.Multiquadratic.exists_mem_inertia_apply_eq_neg_of_mod_four`). In the first case above
  there are two such roots `y`, `z` whose product, up to a factor `2`, is a third. A group of
  exponent `2` with at most four elements that negates each of `y`, `z` and `y z` has exactly four
  elements.

## Main results

* `TauCeti.Multiquadratic.exists_mem_inertia_apply_eq_neg`: in a Galois number field, if a prime
  `p` ramifies in the quadratic field generated by a square root `x` of a rational number, then
  every prime above `p` has an inertia element negating `x`.
* `TauCeti.Multiquadratic.exists_mem_inertia_apply_eq_neg_of_mod_four`: every prime above `2` has
  an inertia element negating a given square root of an integer that is `2` or `3` modulo `4`.
* `TauCeti.Multiquadratic.card_inertia_le_four` and
  `TauCeti.Multiquadratic.ramificationIdx_le_four`: the inertia group above `2` has at most four
  elements.
* `TauCeti.Multiquadratic.ramificationIdx_eq_four_iff`: the criterion for `e = 4` above.
* `TauCeti.Multiquadratic.ramificationIdx_eq_two_iff_of_two`: the criterion for `e = 2` above.

## References

* D. A. Cox, *Primes of the Form x² + ny²*, §5.B.
* J. Neukirch, *Algebraic Number Theory*, Chapter I, §9 and Chapter II, §5.
-/

public section

open NumberField Ideal Module
open scoped NumberField

namespace TauCeti.Multiquadratic

variable {K : Type*} [Field K] [NumberField K] {ι : Type*} {d : ι → ℤ} {r : ι → K}

/-! ### Inertia elements negating a ramified square root -/

/-- **Inertia negates a square root generating a ramified quadratic field.** Let `K / ℚ` be
Galois, let `x ∈ K` square to a rational number, and let `p` be a prime ramifying in `ℚ(x)`. Then
the inertia group of every prime `Q` of `𝓞 K` above `p` contains an automorphism `τ` with
`τ x = -x`.

Some prime `P` above `p` has an inertia element moving `x`
(`NumberField.notMem_ramifiedPrimes_iff_forall_inertia_le`). The prime `Q` is a Galois translate
`g • P`, its inertia group contains the conjugate `g σ g⁻¹`, and conjugation preserves the sign by
which an automorphism acts on `x`, since every automorphism sends `x` to `± x`. -/
theorem exists_mem_inertia_apply_eq_neg [IsGalois ℚ K] {x : K} {c : ℚ}
    (hx : x ^ 2 = algebraMap ℚ K c) {p : ℕ}
    (hp : p ∈ ramifiedPrimes (IntermediateField.adjoin ℚ {x} : IntermediateField ℚ K))
    (Q : Ideal (𝓞 K)) [Q.IsPrime] [Q.LiesOver (span {(p : ℤ)})] :
    ∃ τ ∈ Q.inertia (K ≃ₐ[ℚ] K), τ x = -x := by
  have hpp : p.Prime := NumberField.prime_of_mem_ramifiedPrimes hp
  let _ : NumberField (IntermediateField.adjoin ℚ {x} : IntermediateField ℚ K) :=
    NumberField.of_intermediateField _
  have hpm (σ : K ≃ₐ[ℚ] K) : σ x = x ∨ σ x = -x :=
    sq_eq_sq_iff_eq_or_eq_neg.mp (by rw [← map_pow, hx]; simp)
  obtain ⟨P, hP, hPp, hPx⟩ : ∃ P : Ideal (𝓞 K), P.IsPrime ∧ P.LiesOver (span {(p : ℤ)}) ∧
      ¬ P.inertia (K ≃ₐ[ℚ] K) ≤ fixingSubgroup (K ≃ₐ[ℚ] K)
        ((IntermediateField.adjoin ℚ {x} : IntermediateField ℚ K) : Set K) := by
    by_contra hcon
    push Not at hcon
    exact (NumberField.notMem_ramifiedPrimes_iff_forall_inertia_le (K := K)
      (F := IntermediateField.adjoin ℚ {x}) _ hpp).mpr hcon hp
  obtain ⟨σ, hσI, hσx⟩ := IsConcreteLE.not_le_iff_exists.mp hPx
  -- `IntermediateField.fixingSubgroup` is by definition the fixing subgroup of the carrier.
  replace hσx : σ ∉ (IntermediateField.adjoin ℚ {x}).fixingSubgroup := hσx
  rw [IntermediateField.fixingSubgroup_adjoin_simple, MulAction.mem_stabilizer_iff,
    AlgEquiv.smul_def] at hσx
  have hσneg : σ x = -x := (hpm σ).resolve_left hσx
  have : P.IsPrime := hP
  have : P.LiesOver (span {(p : ℤ)}) := hPp
  obtain ⟨g, rfl⟩ := Ideal.exists_smul_eq_of_isGaloisGroup (span {(p : ℤ)}) P Q (K ≃ₐ[ℚ] K)
  refine ⟨g * σ * g⁻¹, ?_, ?_⟩
  · rw [Ideal.mem_inertia_pointwise_smul_iff]
    simpa [mul_assoc] using hσI
  · have hy : σ (g⁻¹ x) = -g⁻¹ x := by
      rcases hpm g⁻¹ with h | h <;> rw [h] <;> simp [hσneg]
    rw [AlgEquiv.mul_apply, AlgEquiv.mul_apply, hy, map_neg, ← AlgEquiv.mul_apply,
      mul_inv_cancel, AlgEquiv.one_apply]

/-- **Inertia above `2` negates the square roots of integers that are `2` or `3` modulo `4`.** Let
`K / ℚ` be Galois, let `x ∈ K` square to an integer `c ≡ 2` or `3 (mod 4)`, and let `Q` be a prime
of `𝓞 K` above `2`. Then some element `τ` of the inertia group of `Q` satisfies `τ x = -x`.

Writing `c = s e²` with `s` squarefree, `e` is odd, so `s ≡ c (mod 4)`, and `2` ramifies in the
quadratic field generated by `x / e`, a square root of `s`. -/
theorem exists_mem_inertia_apply_eq_neg_of_mod_four [IsGalois ℚ K] {x : K} {c : ℤ}
    (hx : x ^ 2 = algebraMap ℤ K c) (hc : c % 4 = 2 ∨ c % 4 = 3) (Q : Ideal (𝓞 K))
    [Q.IsPrime] [Q.LiesOver (span {(2 : ℤ)})] :
    ∃ τ ∈ Q.inertia (K ≃ₐ[ℚ] K), τ x = -x := by
  obtain ⟨s, e, hs, he, rfl⟩ := Int.exists_squarefree_mul_sq (n := c) (by omega)
  -- `e` is odd, so `e ^ 2 ≡ 1 (mod 4)` and `s ≡ c (mod 4)`.
  have hsc : s % 4 = 2 ∨ s % 4 = 3 := by
    obtain ⟨k, rfl | rfl⟩ := Int.even_or_odd' e
    · have h4 : s * (2 * k) ^ 2 = 4 * (s * k ^ 2) := by ring
      rw [h4] at hc
      omega
    · have h4 : s * (2 * k + 1) ^ 2 = s + 4 * (s * (k ^ 2 + k)) := by ring
      rw [h4] at hc
      omega
  have he' : (e : K) ≠ 0 := by exact_mod_cast he
  have hx' : (x / e) ^ 2 = algebraMap ℤ K s := by
    rw [div_pow, hx, eq_intCast, eq_intCast, Int.cast_mul, Int.cast_pow,
      mul_div_cancel_right₀ _ (pow_ne_zero 2 he')]
  have h2 : 2 ∈ ramifiedPrimes (IntermediateField.adjoin ℚ {x / e} : IntermediateField ℚ K) := by
    rw [mem_ramifiedPrimes_adjoin_iff_dvd_fundamentalDiscriminant hs hx' Nat.prime_two,
      Nat.cast_ofNat]
    by_contra h
    have := (two_not_dvd_fundamentalDiscriminant_iff_mod_four_eq_one s).mp h
    omega
  have : Q.LiesOver (span {((2 : ℕ) : ℤ)}) := by rwa [Nat.cast_ofNat]
  obtain ⟨τ, hτ, hτx⟩ := exists_mem_inertia_apply_eq_neg (c := s) (by rw [hx']; simp) h2 Q
  refine ⟨τ, hτ, ?_⟩
  rw [map_div₀, map_intCast, div_eq_iff he'] at hτx
  rw [hτx, neg_mul, div_mul_cancel₀ _ he']

/-! ### Inertia elements fixing products of roots -/

section Fixing

variable (hr : ∀ i, r i ^ 2 = algebraMap ℤ K (d i)) (hd : ∀ i, ¬ (4 : ℤ) ∣ d i)
  (Q : Ideal (𝓞 K)) [Q.LiesOver (span {(2 : ℤ)})] {τ : K ≃ₐ[ℚ] K}
  (hτ : τ ∈ Q.inertia (K ≃ₐ[ℚ] K))
include hr hd hτ

omit hr hd in
/-- Inertia above `2` fixes `w` when `w / 2` squares to an integer that is `1` modulo `4`. -/
private theorem apply_eq_self_of_div_two {w : K} {c : ℤ} (hw : (w / 2) ^ 2 = algebraMap ℤ K c)
    (hc : c % 4 = 1) : τ w = w := by
  have h := apply_eq_self_of_mem_inertia_of_mod_four_eq_one hw hc Q hτ
  rwa [map_div₀, map_ofNat, div_left_inj' two_ne_zero] at h

omit hd in
/-- Inertia above `2` fixes `rᵢ rⱼ` when `dᵢ` and `dⱼ` are both `3` modulo `4`. -/
private theorem apply_mul_eq_mul_of_mod_four_eq_three {i j : ι} (hi : d i % 4 = 3)
    (hj : d j % 4 = 3) : τ (r i * r j) = r i * r j :=
  apply_eq_self_of_mem_inertia_of_mod_four_eq_one (c := d i * d j)
    (by rw [mul_pow, hr i, hr j, map_mul]) (by rw [Int.mul_emod, hi, hj]; norm_num) Q hτ

/-- Inertia above `2` fixes `rᵢ rⱼ` when `dᵢ` and `dⱼ` are even and congruent modulo `8`: then
`rᵢ rⱼ / 2` squares to the product of two odd integers congruent modulo `4`. -/
private theorem apply_mul_eq_mul_of_mod_eight_eq {i j : ι} (hi : 2 ∣ d i) (hj : 2 ∣ d j)
    (hij : d i % 8 = d j % 8) : τ (r i * r j) = r i * r j := by
  obtain ⟨u, hu⟩ := hi
  obtain ⟨v, hv⟩ := hj
  have hi4 := hd i
  rw [hu, hv] at hij
  rw [hu] at hi4
  refine apply_eq_self_of_div_two Q hτ (c := u * v) ?_ ?_
  · rw [div_pow, mul_pow, hr i, hr j, hu, hv]
    simp only [eq_intCast, Int.cast_mul, Int.cast_ofNat]
    ring
  · rcases (by omega : u % 4 = 1 ∨ u % 4 = 3) with h | h <;>
      rw [Int.mul_emod, h, (by omega : v % 4 = u % 4), h] <;> norm_num

/-- Inertia above `2` fixes `r_b r_c rᵢ` when `d_b` is `3` modulo `4` and `d_c`, `dᵢ` are even and
incongruent modulo `8`: then `r_b r_c rᵢ / 2` squares to the product of three odd integers, two of
them `3` and one `1` modulo `4`. -/
private theorem apply_mul_mul_eq_mul_mul {b c i : ι} (hb : d b % 4 = 3) (hc : 2 ∣ d c)
    (hi : 2 ∣ d i) (hci : d c % 8 ≠ d i % 8) :
    τ (r b * r c * r i) = r b * r c * r i := by
  obtain ⟨u, hu⟩ := hc
  obtain ⟨v, hv⟩ := hi
  have hc4 := hd c
  have hi4 := hd i
  rw [hu, hv] at hci
  rw [hu] at hc4
  rw [hv] at hi4
  refine apply_eq_self_of_div_two Q hτ (c := d b * u * v) ?_ ?_
  · rw [div_pow, mul_pow, mul_pow, hr b, hr c, hr i, hu, hv]
    simp only [eq_intCast, Int.cast_mul, Int.cast_ofNat]
    ring
  · rcases (by omega : u % 4 = 1 ∧ v % 4 = 3 ∨ u % 4 = 3 ∧ v % 4 = 1) with ⟨h, h'⟩ | ⟨h, h'⟩ <;>
      rw [Int.mul_emod, Int.mul_emod (d b), hb, h, h'] <;> norm_num

omit hr hd hτ in
/-- A square root of a nonzero integer is nonzero. -/
private theorem ne_zero_of_sq_eq {x : K} {c : ℤ} (hx : x ^ 2 = algebraMap ℤ K c) (hc : c ≠ 0) :
    x ≠ 0 := by
  rintro rfl
  apply hc
  simpa [eq_comm] using hx

omit hτ in
private theorem root_ne_zero (i : ι) : r i ≠ 0 :=
  ne_zero_of_sq_eq (hr i) fun h => hd i (h ▸ dvd_zero 4)

omit hr hd hτ [Q.LiesOver (span {(2 : ℤ)})] in
/-- Cancel a fixed nonzero factor. -/
private theorem apply_eq_self_of_apply_mul_eq_mul {x y : K} (hx : x ≠ 0) (hτx : τ x = x)
    (h : τ (x * y) = x * y) : τ y = y := by
  rw [map_mul, hτx] at h
  exact mul_left_cancel₀ hx h

end Fixing

/-! ### Counting inertia elements -/

/-- A subgroup of `Gal(K/ℚ)` in which only the identity fixes each of `n` square roots of integers
has at most `2ⁿ` elements: an element is determined by the signs by which it acts on them. -/
private theorem card_le_two_pow_of_forall_apply_eq_self {n : ℕ} {y : Fin n → K} {c : Fin n → ℤ}
    (hy : ∀ k, y k ^ 2 = algebraMap ℤ K (c k)) (H : Subgroup (K ≃ₐ[ℚ] K))
    (h : ∀ τ ∈ H, (∀ k, τ (y k) = y k) → τ = 1) : Nat.card H ≤ 2 ^ n := by
  classical
  have hpm (σ : K ≃ₐ[ℚ] K) (k : Fin n) : σ (y k) = y k ∨ σ (y k) = -y k :=
    sq_eq_sq_iff_eq_or_eq_neg.mp (by rw [← map_pow, hy k]; simp)
  let f : H → Fin n → Bool := fun τ k => decide ((τ : K ≃ₐ[ℚ] K) (y k) = y k)
  have hf : Function.Injective f := by
    intro σ τ hστ
    have hk (k : Fin n) : (σ : K ≃ₐ[ℚ] K) (y k) = (τ : K ≃ₐ[ℚ] K) (y k) := by
      have h := congrFun hστ k
      simp only [f, decide_eq_decide] at h
      rcases hpm σ k with h1 | h1 <;> rcases hpm τ k with h2 | h2 <;> simp_all
    have h1 := h ((τ : K ≃ₐ[ℚ] K)⁻¹ * σ) (mul_mem (inv_mem τ.2) σ.2) fun k => by
      rw [AlgEquiv.mul_apply, hk k, ← AlgEquiv.mul_apply, inv_mul_cancel, AlgEquiv.one_apply]
    exact Subtype.ext (inv_mul_eq_one.mp h1).symm
  simpa using Nat.card_le_card_of_injective f hf

/-- A subgroup of `Gal(K/ℚ)` of exponent `2` with at most four elements, containing elements that
negate `y`, `z` and `y z` for nonzero `y`, `z`, has exactly four elements: it is nontrivial, has no
element of order `3`, and a group of order `2` would have a single nonidentity element, which
cannot negate all three. -/
private theorem card_eq_four_of_exists_apply_eq_neg (H : Subgroup (K ≃ₐ[ℚ] K))
    (hexp : ∀ σ : K ≃ₐ[ℚ] K, σ ^ 2 = 1) (hle : Nat.card H ≤ 4) {y z : K} (hy : y ≠ 0)
    (hz : z ≠ 0) (h₁ : ∃ τ ∈ H, τ y = -y) (h₂ : ∃ τ ∈ H, τ z = -z)
    (h₃ : ∃ τ ∈ H, τ (y * z) = -(y * z)) : Nat.card H = 4 := by
  obtain ⟨τ₁, hτ₁, hτ₁y⟩ := h₁
  obtain ⟨τ₂, hτ₂, hτ₂z⟩ := h₂
  obtain ⟨τ₃, hτ₃, hτ₃yz⟩ := h₃
  have hne {τ : K ≃ₐ[ℚ] K} {w : K} (hw : w ≠ 0) (h : τ w = -w) : τ ≠ 1 := by
    rintro rfl
    exact hw (CharZero.eq_neg_self_iff.mp h)
  have hpos : 0 < Nat.card H := Nat.card_pos
  interval_cases hc : Nat.card H
  · have : Subsingleton H := (Nat.card_eq_one_iff_unique.mp hc).1
    exact absurd (congrArg Subtype.val (Subsingleton.elim (⟨τ₁, hτ₁⟩ : H) 1)) (hne hy hτ₁y)
  · obtain ⟨u, -, hu⟩ := (Nat.card_eq_two_iff' (1 : H)).mp hc
    have heq {τ : K ≃ₐ[ℚ] K} (hτ : τ ∈ H) (hτ1 : τ ≠ 1) : τ = u :=
      congrArg Subtype.val (hu ⟨τ, hτ⟩ fun h => hτ1 (congrArg Subtype.val h))
    have h12 : τ₃ = τ₁ := (heq hτ₃ (hne (mul_ne_zero hy hz) hτ₃yz)).trans
      (heq hτ₁ (hne hy hτ₁y)).symm
    have h22 : τ₃ = τ₂ := (heq hτ₃ (hne (mul_ne_zero hy hz) hτ₃yz)).trans
      (heq hτ₂ (hne hz hτ₂z)).symm
    rw [h12, map_mul, hτ₁y, h12.symm.trans h22, hτ₂z, neg_mul_neg,
      CharZero.eq_neg_self_iff] at hτ₃yz
    exact absurd hτ₃yz (mul_ne_zero hy hz)
  · obtain ⟨g, hg⟩ := exists_prime_orderOf_dvd_card' (G := H) 3 (hp := ⟨Nat.prime_three⟩)
      (by simp [hc])
    have h2 : g ^ 2 = 1 := Subtype.ext (hexp g)
    have := orderOf_dvd_of_pow_eq_one h2
    rw [hg] at this
    norm_num at this
  · rfl

/-! ### The ramification index above `2` -/

section Inertia

variable (hr : ∀ i, r i ^ 2 = algebraMap ℤ K (d i))
  (htop : IntermediateField.adjoin ℚ (Set.range r) = ⊤) (hd : ∀ i, ¬ (4 : ℤ) ∣ d i)
  (Q : Ideal (𝓞 K)) [Q.IsPrime] [Q.LiesOver (span {(2 : ℤ)})]
include hr htop hd

omit [Q.IsPrime] in
/-- An inertia element above `2` that fixes the roots of all radicands `3` modulo `4` and of all
even radicands is the identity, since it fixes the roots of the radicands `1` modulo `4` anyway. -/
private theorem eq_one_of_mem_inertia {τ : K ≃ₐ[ℚ] K} (hτ : τ ∈ Q.inertia (K ≃ₐ[ℚ] K))
    (hB : ∀ i, d i % 4 = 3 → τ (r i) = r i) (hC : ∀ i, 2 ∣ d i → τ (r i) = r i) : τ = 1 := by
  refine TauCeti.IntermediateField.algEquiv_eq_one_of_adjoin_eq_top htop ?_
  rintro _ ⟨i, rfl⟩
  have h4 := hd i
  rcases (by omega : d i % 4 = 1 ∨ d i % 4 = 3 ∨ 2 ∣ d i) with h | h | h
  · exact apply_eq_self_of_mem_inertia_of_mod_four_eq_one (hr i) h Q hτ
  · exact hB i h
  · exact hC i h

omit [Q.IsPrime] in
/-- The inertia group above `2` has at most four elements when some radicand is `3` modulo `4` and
another is even: an inertia element is determined by its signs on their roots. -/
private theorem card_inertia_le_four_of_mod_four_eq_three {b c : ι} (hb : d b % 4 = 3)
    (hc : 2 ∣ d c) : Nat.card (Q.inertia (K ≃ₐ[ℚ] K)) ≤ 4 := by
  refine (card_le_two_pow_of_forall_apply_eq_self (y := ![r b, r c]) (c := ![d b, d c])
    (fun k => by fin_cases k <;> simp [hr]) _ fun τ hτ hfix => ?_).trans (by norm_num)
  have hτb : τ (r b) = r b := hfix 0
  have hτc : τ (r c) = r c := hfix 1
  refine eq_one_of_mem_inertia hr htop hd Q hτ (fun i hi => ?_) fun i hi => ?_
  · exact apply_eq_self_of_apply_mul_eq_mul (root_ne_zero hr hd b) hτb
      (apply_mul_eq_mul_of_mod_four_eq_three hr Q hτ hb hi)
  · by_cases hci : d c % 8 = d i % 8
    · exact apply_eq_self_of_apply_mul_eq_mul (root_ne_zero hr hd c) hτc
        (apply_mul_eq_mul_of_mod_eight_eq hr hd Q hτ hc hi hci)
    · exact apply_eq_self_of_apply_mul_eq_mul
        (mul_ne_zero (root_ne_zero hr hd b) (root_ne_zero hr hd c)) (by rw [map_mul, hτb, hτc])
        (apply_mul_mul_eq_mul_mul hr hd Q hτ hb hc hi hci)

omit [Q.IsPrime] in
/-- The inertia group above `2` has at most four elements when two radicands are `2` and `6`
modulo `8`: an inertia element is determined by its signs on their roots. -/
private theorem card_inertia_le_four_of_mod_eight {c₂ c₆ : ι} (h₂ : d c₂ % 8 = 2)
    (h₆ : d c₆ % 8 = 6) : Nat.card (Q.inertia (K ≃ₐ[ℚ] K)) ≤ 4 := by
  refine (card_le_two_pow_of_forall_apply_eq_self (y := ![r c₂, r c₆]) (c := ![d c₂, d c₆])
    (fun k => by fin_cases k <;> simp [hr]) _ fun τ hτ hfix => ?_).trans (by norm_num)
  have hτ₂ : τ (r c₂) = r c₂ := hfix 0
  have hτ₆ : τ (r c₆) = r c₆ := hfix 1
  have hd₂ : 2 ∣ d c₂ := by omega
  have hd₆ : 2 ∣ d c₆ := by omega
  refine eq_one_of_mem_inertia hr htop hd Q hτ (fun i hi => ?_) fun i hi => ?_
  · have h := apply_mul_mul_eq_mul_mul hr hd Q hτ hi hd₂ hd₆ (by omega)
    rw [show r i * r c₂ * r c₆ = r c₂ * r c₆ * r i by ring] at h
    exact apply_eq_self_of_apply_mul_eq_mul
      (mul_ne_zero (root_ne_zero hr hd c₂) (root_ne_zero hr hd c₆))
      (by rw [map_mul, hτ₂, hτ₆]) h
  · have h4 := hd i
    by_cases hi₂ : d i % 8 = 2
    · exact apply_eq_self_of_apply_mul_eq_mul (root_ne_zero hr hd c₂) hτ₂
        (apply_mul_eq_mul_of_mod_eight_eq hr hd Q hτ hd₂ hi (by omega))
    · exact apply_eq_self_of_apply_mul_eq_mul (root_ne_zero hr hd c₆) hτ₆
        (apply_mul_eq_mul_of_mod_eight_eq hr hd Q hτ hd₆ hi (by omega))

omit [Q.IsPrime] in
/-- Outside the cases of ramification index `4`, the inertia group above `2` has at most two
elements: an inertia element is determined by its sign on a single root. -/
private theorem card_inertia_le_two
    (hcond : ¬ ((∃ i j, d i % 4 = 3 ∧ 2 ∣ d j) ∨ ∃ i j, d i % 8 = 2 ∧ d j % 8 = 6)) :
    Nat.card (Q.inertia (K ≃ₐ[ℚ] K)) ≤ 2 := by
  by_cases hB : ∃ b, d b % 4 = 3
  · obtain ⟨b, hb⟩ := hB
    refine (card_le_two_pow_of_forall_apply_eq_self (y := ![r b]) (c := ![d b])
      (fun k => by fin_cases k; simp [hr]) _ fun τ hτ hfix => ?_).trans (by norm_num)
    have hτb : τ (r b) = r b := hfix 0
    exact eq_one_of_mem_inertia hr htop hd Q hτ
      (fun i hi => apply_eq_self_of_apply_mul_eq_mul (root_ne_zero hr hd b) hτb
        (apply_mul_eq_mul_of_mod_four_eq_three hr Q hτ hb hi))
      fun i hi => absurd (Or.inl ⟨b, i, hb, hi⟩) hcond
  by_cases hC : ∃ c, 2 ∣ d c
  · obtain ⟨c, hc⟩ := hC
    refine (card_le_two_pow_of_forall_apply_eq_self (y := ![r c]) (c := ![d c])
      (fun k => by fin_cases k; simp [hr]) _ fun τ hτ hfix => ?_).trans (by norm_num)
    have hτc : τ (r c) = r c := hfix 0
    refine eq_one_of_mem_inertia hr htop hd Q hτ (fun i hi => absurd ⟨i, hi⟩ hB) fun i hi => ?_
    refine apply_eq_self_of_apply_mul_eq_mul (root_ne_zero hr hd c) hτc
      (apply_mul_eq_mul_of_mod_eight_eq hr hd Q hτ hc hi ?_)
    have hc4 := hd c
    have hi4 := hd i
    by_contra hne
    rcases (by omega : d c % 8 = 2 ∧ d i % 8 = 6 ∨ d c % 8 = 6 ∧ d i % 8 = 2) with
      ⟨h1, h2⟩ | ⟨h1, h2⟩
    · exact hcond (Or.inr ⟨c, i, h1, h2⟩)
    · exact hcond (Or.inr ⟨i, c, h2, h1⟩)
  push Not at hB hC
  rw [inertia_eq_bot_of_forall_mod_four_eq_one hr htop
    (fun i => by have := hd i; have := hB i; have := hC i; omega) Q,
    Subgroup.card_bot]
  norm_num

/-- In the cases of ramification index `4`, the inertia group above `2` has exactly four
elements: it negates the roots `y`, `z` tested in the upper bound, and `y z`, each of which
generates a quadratic field ramified at `2`. -/
private theorem card_inertia_eq_four [Finite ι]
    (hcond : (∃ i j, d i % 4 = 3 ∧ 2 ∣ d j) ∨ ∃ i j, d i % 8 = 2 ∧ d j % 8 = 6) :
    Nat.card (Q.inertia (K ≃ₐ[ℚ] K)) = 4 := by
  have := isGalois_rat hr htop
  have hexp (σ : K ≃ₐ[ℚ] K) : σ ^ 2 = 1 :=
    aut_pow_two_eq_one_of_adjoin_eq_top (d := fun i => (d i : ℚ))
      (fun i => by rw [hr i]; simp) htop σ
  rcases hcond with ⟨b, c, hb, hc⟩ | ⟨c₂, c₆, h₂, h₆⟩
  · have hc4 := hd c
    refine card_eq_four_of_exists_apply_eq_neg _ hexp
      (card_inertia_le_four_of_mod_four_eq_three hr htop hd Q hb hc) (root_ne_zero hr hd b)
      (root_ne_zero hr hd c) (exists_mem_inertia_apply_eq_neg_of_mod_four (hr b) (Or.inr hb) Q)
      (exists_mem_inertia_apply_eq_neg_of_mod_four (hr c) (Or.inl (by omega)) Q)
      (exists_mem_inertia_apply_eq_neg_of_mod_four (c := d b * d c)
        (by rw [mul_pow, hr b, hr c, map_mul]) (Or.inl ?_) Q)
    -- `d b * d c = 2 (d b * u)` with `d b * u` odd.
    obtain ⟨u, hu⟩ := hc
    rw [hu] at hc4 ⊢
    have hodd : d b * u % 2 = 1 := by
      rw [Int.mul_emod, (by omega : d b % 2 = 1), (by omega : u % 2 = 1)]
      norm_num
    rw [show d b * (2 * u) = 2 * (d b * u) by ring]
    omega
  · have hd₂ : 2 ∣ d c₂ := by omega
    have hd₆ : 2 ∣ d c₆ := by omega
    refine card_eq_four_of_exists_apply_eq_neg _ hexp
      (card_inertia_le_four_of_mod_eight hr htop hd Q h₂ h₆) (root_ne_zero hr hd c₂)
      (root_ne_zero hr hd c₆)
      (exists_mem_inertia_apply_eq_neg_of_mod_four (hr c₂) (Or.inl (by omega)) Q)
      (exists_mem_inertia_apply_eq_neg_of_mod_four (hr c₆) (Or.inl (by omega)) Q) ?_
    -- `r c₂ * r c₆ / 2` squares to `u v ≡ 3 (mod 4)`, where `d c₂ = 2 u` and `d c₆ = 2 v`.
    obtain ⟨u, hu⟩ := hd₂
    obtain ⟨v, hv⟩ := hd₆
    rw [hu] at h₂
    rw [hv] at h₆
    obtain ⟨τ, hτ, hτx⟩ := exists_mem_inertia_apply_eq_neg_of_mod_four
      (x := r c₂ * r c₆ / 2) (c := u * v)
      (by
        rw [div_pow, mul_pow, hr c₂, hr c₆, hu, hv]
        simp only [eq_intCast, Int.cast_mul, Int.cast_ofNat]
        ring)
      (Or.inr (by rw [Int.mul_emod, (by omega : u % 4 = 1), (by omega : v % 4 = 3)]; norm_num)) Q
    refine ⟨τ, hτ, ?_⟩
    rw [map_div₀, map_ofNat, div_eq_iff two_ne_zero] at hτx
    rw [hτx, neg_mul, div_mul_cancel₀ _ two_ne_zero]

/-- **The inertia group above `2` has at most four elements.** Let `K` be generated over `ℚ` by
square roots `r i` of integers `d i` not divisible by `4`, and let `Q` be a prime of `𝓞 K` above
`2`. Then the inertia group of `Q` in `Gal(K/ℚ)` has at most four elements, however many radicands
there are. -/
theorem card_inertia_le_four [Finite ι] : Nat.card (Q.inertia (K ≃ₐ[ℚ] K)) ≤ 4 := by
  by_cases hcond : (∃ i j, d i % 4 = 3 ∧ 2 ∣ d j) ∨ ∃ i j, d i % 8 = 2 ∧ d j % 8 = 6
  · exact (card_inertia_eq_four hr htop hd Q hcond).le
  · exact (card_inertia_le_two hr htop hd Q hcond).trans (by norm_num)

/-- **The ramification index above `2` is at most `4`.** Let `K` be generated over `ℚ` by square
roots of integers not divisible by `4`, and let `Q` be a prime of `𝓞 K` above `2`. Then the
ramification index of `Q` over `2` is at most `4`. -/
theorem ramificationIdx_le_four [Finite ι] : Q.ramificationIdx ℤ ≤ 4 := by
  have := isGalois_rat hr htop
  rw [← Ideal.card_inertia_eq_ramificationIdx ℤ (K ≃ₐ[ℚ] K) Q]
  exact card_inertia_le_four hr htop hd Q

/-- **Ramification index `4` above `2`.** Let `K` be generated over `ℚ` by square roots of
integers `d i` not divisible by `4`, and let `Q` be a prime of `𝓞 K` above `2`. Then the
ramification index of `Q` over `2` is `4` exactly when some `d i` is `3` modulo `4` and some
`d j` is even, or some `d i` is `2` and some `d j` is `6` modulo `8`. -/
theorem ramificationIdx_eq_four_iff [Finite ι] :
    Q.ramificationIdx ℤ = 4 ↔
      (∃ i j, d i % 4 = 3 ∧ 2 ∣ d j) ∨ ∃ i j, d i % 8 = 2 ∧ d j % 8 = 6 := by
  have := isGalois_rat hr htop
  rw [← Ideal.card_inertia_eq_ramificationIdx ℤ (K ≃ₐ[ℚ] K) Q]
  refine ⟨fun h => ?_, card_inertia_eq_four hr htop hd Q⟩
  by_contra hcond
  have := card_inertia_le_two hr htop hd Q hcond
  omega

/-- **Ramification index `2` above `2`.** Let `K` be generated over `ℚ` by square roots of
integers `d i` not divisible by `4`, and let `Q` be a prime of `𝓞 K` above `2`. Then the
ramification index of `Q` over `2` is `2` exactly when some `d i` is not `1` modulo `4` (so
that `2` ramifies) but the criterion of `TauCeti.Multiquadratic.ramificationIdx_eq_four_iff`
fails. -/
theorem ramificationIdx_eq_two_iff_of_two [Finite ι] :
    Q.ramificationIdx ℤ = 2 ↔ (∃ i, d i % 4 ≠ 1) ∧
      ¬ ((∃ i j, d i % 4 = 3 ∧ 2 ∣ d j) ∨ ∃ i j, d i % 8 = 2 ∧ d j % 8 = 6) := by
  have := isGalois_rat hr htop
  rw [← Ideal.card_inertia_eq_ramificationIdx ℤ (K ≃ₐ[ℚ] K) Q]
  constructor
  · intro h
    refine ⟨?_, fun hcond => by have := card_inertia_eq_four hr htop hd Q hcond; omega⟩
    by_contra hall
    push Not at hall
    rw [inertia_eq_bot_of_forall_mod_four_eq_one hr htop hall Q, Subgroup.card_bot] at h
    exact absurd h (by decide)
  · rintro ⟨⟨i, hi⟩, hcond⟩
    have h4 := hd i
    obtain ⟨τ, hτ, hτi⟩ := exists_mem_inertia_apply_eq_neg_of_mod_four (hr i) (by omega) Q
    have hτ1 : τ ≠ 1 := by
      rintro rfl
      exact root_ne_zero hr hd i (CharZero.eq_neg_self_iff.mp hτi)
    have hne : Q.inertia (K ≃ₐ[ℚ] K) ≠ ⊥ := fun h =>
      hτ1 ((Subgroup.eq_bot_iff_forall _).mp h τ hτ)
    have := (Subgroup.one_lt_card_iff_ne_bot _).mpr hne
    have := card_inertia_le_two hr htop hd Q hcond
    omega

end Inertia

end TauCeti.Multiquadratic
