/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.GaloisGroup
public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.InfinitePlace
public import TauCeti.NumberTheory.Multiquadratic.Unramified.Maximality
import TauCeti.FieldTheory.Minpoly

/-!
# The genus field of an imaginary quadratic field

This file gives an intrinsic characterization of the genus field and proves that the
prime-discriminant compositum `candidateGenusField hd` has that characterization when `d < 0`.

For a chosen square root `y² = d` in an abelian extension `L / ℚ`, the predicate
`TauCeti.Multiquadratic.IsGenusField d L y` says that:

* `y` generates a quadratic subfield of `L`;
* `L` is unramified over that subfield at every finite and infinite place; and
* every other abelian extension of `ℚ` with these properties embeds into `L` over `ℚ`, carrying
  its chosen square root to `y`.

The last clause is the maximality in the classical definition. It is stated by a universal
property, rather than by choosing a maximal element of a collection of fields. The theorem
`IsGenusField.exists_algEquiv_apply_eq` makes the resulting root-preserving uniqueness explicit.

For squarefree negative `d`, `isGenusField_candidateGenusField` assembles the existing arithmetic
and archimedean inputs. The finite-prime theorem is `isUnramifiedIn_candidateGenusField`, the
infinite-place theorem is
`isUnramifiedAtInfinitePlaces_candidateGenusField`, and maximality is
`nonempty_algHom_candidateGenusField`.

This completes the definition and maximality part of Layer 3 of the Multiquadratic roadmap in the
imaginary quadratic case. Identifying the relative Galois group with the elementary-two quotient
of the class group still requires the Artin map.

## References

* D. A. Cox, *Primes of the Form x² + ny²*, Section 6.A.
* F. Lemmermeyer, *Reciprocity Laws: From Euler to Eisenstein*, Section 2.2.
-/

public section

open IntermediateField NumberField
open scoped NumberField

namespace TauCeti.Multiquadratic

universe u v

/-- An abelian extension `L / ℚ`, with a chosen quadratic subfield generated by `y² = d`, is a
**genus field** when it is unramified over that subfield at every place and is maximal among
abelian extensions with those properties.

This predicate is the ordinary, all-places notion. A narrow genus-field predicate for real
quadratic fields, imposing only the finite-place condition, remains future work. -/
structure IsGenusField (d : ℤ) (L : Type u) [Field L] [NumberField L] (y : L) : Prop where
  /-- The chosen element is a square root of the radicand. -/
  root_sq : y ^ 2 = algebraMap ℤ L d
  /-- The chosen root generates a quadratic subfield. -/
  finrank_adjoin : Module.finrank ℚ (adjoin ℚ {y} : IntermediateField ℚ L) = 2
  /-- The ambient extension is abelian and Galois over `ℚ`. -/
  isAbelianGalois : IsAbelianGalois ℚ L
  /-- The extension is unramified at every finite prime over its quadratic subfield. -/
  isUnramifiedAtFinitePlaces :
    ∀ q : Ideal (𝓞 (adjoin ℚ {y} : IntermediateField ℚ L)),
      q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 L) q
  /-- The extension is unramified at every infinite place over its quadratic subfield. -/
  isUnramifiedAtInfinitePlaces :
    IsUnramifiedAtInfinitePlaces (adjoin ℚ {y} : IntermediateField ℚ L) L
  /-- Root-preserving maximality among abelian extensions unramified at every place over
  `ℚ(√d)`. -/
  maximal :
    ∀ {M : Type v} [Field M] [NumberField M] [IsAbelianGalois ℚ M] {z : M},
      z ^ 2 = algebraMap ℤ M d →
      (∀ q : Ideal (𝓞 (adjoin ℚ {z} : IntermediateField ℚ M)),
        q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 M) q) →
      IsUnramifiedAtInfinitePlaces (adjoin ℚ {z} : IntermediateField ℚ M) M →
      ∃ φ : M →ₐ[ℚ] L, φ z = y

namespace IsGenusField

variable {d : ℤ}
variable {L : Type u} [Field L] [NumberField L]
variable {M : Type v} [Field M] [NumberField M]
variable {y : L} {z : M}

/-- Any two genus fields for the same radicand are isomorphic as `ℚ`-algebras by an equivalence
carrying one chosen square root to the other. -/
theorem exists_algEquiv_apply_eq (hL : IsGenusField.{u, v} d L y)
    (hM : IsGenusField.{v, u} d M z) :
    ∃ e : L ≃ₐ[ℚ] M, e y = z := by
  let _ : IsAbelianGalois ℚ L := hL.isAbelianGalois
  let _ : IsAbelianGalois ℚ M := hM.isAbelianGalois
  obtain ⟨φ, hφ⟩ := hM.maximal hL.root_sq
    hL.isUnramifiedAtFinitePlaces hL.isUnramifiedAtInfinitePlaces
  obtain ⟨ψ, _⟩ := hL.maximal hM.root_sq
    hM.isUnramifiedAtFinitePlaces hM.isUnramifiedAtInfinitePlaces
  have hLM : Module.finrank ℚ L ≤ Module.finrank ℚ M :=
    LinearMap.finrank_le_finrank_of_injective (f := φ.toLinearMap) φ.injective
  have hML : Module.finrank ℚ M ≤ Module.finrank ℚ L :=
    LinearMap.finrank_le_finrank_of_injective (f := ψ.toLinearMap) ψ.injective
  have hrank : Module.finrank ℚ L = Module.finrank ℚ M := le_antisymm hLM hML
  refine ⟨TauCeti.algEquivOfFinrankEq φ hrank, ?_⟩
  simpa using hφ

end IsGenusField

private theorem exists_algHom_apply_eq_of_sq_eq {d : ℤ} {L : Type u} [Field L]
    [NumberField L] [IsGalois ℚ L] {y : L}
    (hy : y ^ 2 = algebraMap ℤ L d)
    (hydegree : Module.finrank ℚ (adjoin ℚ {y} : IntermediateField ℚ L) = 2)
    {M : Type v} [Field M] [NumberField M] {z : M}
    (hz : z ^ 2 = algebraMap ℤ M d) (hφ : Nonempty (M →ₐ[ℚ] L)) :
    ∃ φ : M →ₐ[ℚ] L, φ z = y := by
  obtain ⟨φ⟩ := hφ
  have hyQ : y ^ 2 = algebraMap ℚ L ((d : ℤ) : ℚ) := by
    rw [hy, IsScalarTower.algebraMap_apply ℤ ℚ L]
    norm_num
  have hzQ : z ^ 2 = algebraMap ℚ M ((d : ℤ) : ℚ) := by
    rw [hz, IsScalarTower.algebraMap_apply ℤ ℚ M]
    norm_num
  have hyint : IsIntegral ℚ y := IsIntegral.of_finite ℚ y
  have hmin : minpoly ℚ y = Polynomial.X ^ 2 - Polynomial.C ((d : ℤ) : ℚ) := by
    apply TauCeti.Algebra.minpoly_eq_X_sq_sub_C_of_sq_eq_of_natDegree_eq_two hyQ
    rw [← adjoin.finrank hyint, hydegree]
  have hroot : Polynomial.aeval (φ z) (minpoly ℚ y) = 0 := by
    have hφz : (φ z) ^ 2 = algebraMap ℚ L ((d : ℤ) : ℚ) := by
      rw [← map_pow, hzQ, φ.commutes]
    simp [hmin, hφz]
  obtain ⟨σ, hσ⟩ := minpoly.exists_algEquiv_of_root (IsAlgebraic.of_finite ℚ y) hroot
  exact ⟨σ.toAlgHom.comp φ, hσ⟩

/-- **The prime-discriminant compositum is the genus field in the imaginary quadratic case.**
For a squarefree negative integer `d`, `candidateGenusField hd` is abelian over `ℚ`, is unramified
at every place over its embedded copy of `ℚ(√d)`, and admits a root-preserving embedding from
every other abelian extension with those properties. -/
theorem isGenusField_candidateGenusField {d : ℤ} (hd : Squarefree d) (hneg : d < 0) :
    IsGenusField.{0, v} d (candidateGenusField hd) (candidateGenusFieldBaseRoot hd) := by
  have hnsq : ¬ IsSquare ((d : ℤ) : ℚ) := not_isSquare_of_neg (by exact_mod_cast hneg)
  refine
    { root_sq := ?_
      finrank_adjoin := ?_
      isAbelianGalois := inferInstance
      isUnramifiedAtFinitePlaces := ?_
      isUnramifiedAtInfinitePlaces := ?_
      maximal := ?_ }
  · rw [candidateGenusFieldBaseRoot_sq hd, IsScalarTower.algebraMap_apply ℤ ℚ]
    norm_num
  · rw [← candidateGenusFieldBase_def hd]
    exact finrank_candidateGenusFieldBase hd hnsq
  · rw [← candidateGenusFieldBase_def hd]
    exact fun q hq _ ↦ isUnramifiedIn_candidateGenusField hd hnsq q
  · rw [← candidateGenusFieldBase_def hd]
    exact isUnramifiedAtInfinitePlaces_candidateGenusField hd hneg
  · intro M _ _ _ z hz hfinite _
    apply exists_algHom_apply_eq_of_sq_eq
      (by
        rw [candidateGenusFieldBaseRoot_sq hd, IsScalarTower.algebraMap_apply ℤ ℚ]
        norm_num)
      (by
        rw [← candidateGenusFieldBase_def hd]
        exact finrank_candidateGenusFieldBase hd hnsq)
      hz
    exact nonempty_algHom_candidateGenusField hd hnsq hz hfinite

end TauCeti.Multiquadratic
