/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.Multiquadratic.PrimeSubfieldLattice
public import TauCeti.NumberTheory.Multiquadratic.SubfieldDegree

/-!
# Degrees in prime-radicand multiquadratic subfield lattices

The file `TauCeti.NumberTheory.Multiquadratic.PrimeSubfieldLattice` specializes the
multiquadratic subfield/subspace dictionary to fields `ℚ(√p₁, …, √pₙ)` generated by square
roots of a finite family of distinct primes. This file records the matching degree readings:
the degree of an intermediate field times the size of its attached `𝔽₂`-subspace is `2ⁿ`, and
the quadratic subfields are exactly the hyperplanes.

These are the prime-radicand consumer forms of the field-generic results in
`TauCeti.NumberTheory.Multiquadratic.SubfieldDegree`, using
`TauCeti.Multiquadratic.not_isSquare_prod_primes_of_injective` for square-class independence.
They support the Layer 0 multiquadratic roadmap target identifying subfields with
`𝔽₂`-subspaces, with the degree interpretation needed to organize quadratic subfields.

The point of the specializations is that their statements mention the public prime-radicand
dictionary `intermediateFieldEquivSubmoduleSqrtPrimes`. A consumer working in
`ℚ(√p₁, …, √pₙ)` should not have to expose the private square-root equation or repeat the
prime-family square-class-independence witness just to state a degree fact. The proofs below
therefore remain thin rewrites to the generic API rather than new degree arguments.

## Main results

* `TauCeti.Multiquadratic.finrank_mul_card_intermediateFieldEquivSubmoduleSqrtPrimes`:
  `[F : ℚ] · |U| = 2ⁿ` for the subspace `U` attached to `F`.
* `TauCeti.Multiquadratic.finrank_intermediateField_sqrtPrimes_eq_two_pow`:
  `[F : ℚ] = 2 ^ (n - dim U)`.
* `TauCeti.Multiquadratic.finrank_intermediateField_sqrtPrimes_eq_two_iff`:
  the quadratic intermediate fields are exactly those whose attached subspace is a hyperplane.
-/

public section

open IntermediateField Module

namespace TauCeti.Multiquadratic

variable {ι : Type*}

section PrimeFamily

variable [Finite ι] (p : ι → ℕ) (hp : ∀ i, (p i).Prime) (hinj : Function.Injective p)

omit [Finite ι] in
/-- The square roots `√(p i)` of a prime family satisfy the radicand equation `√(p i)² = p i`.
This is the `hroot` input used by the field-generic subfield-degree results. -/
private theorem sqrtPrime_sq (i : ι) : Real.sqrt (p i) ^ 2 = algebraMap ℚ ℝ (p i : ℚ) :=
  sq_sqrt_natCast (p i)

include hp hinj

/-- The subspace attached by the public prime-radicand dictionary is extensionally the same as
the generic dictionary fed the prime-family square-class independence proof. -/
private theorem intermediateFieldEquivSubmoduleSqrtPrimes_apply_ofDual_eq
    (F : IntermediateField ℚ (adjoin ℚ (Set.range fun i => (Real.sqrt (p i) : ℝ)))) :
    (intermediateFieldEquivSubmoduleSqrtPrimes p hp hinj F).ofDual =
      (intermediateFieldEquivSubmodule (sqrtPrime_sq p)
        (not_isSquare_prod_primes_of_injective p hp hinj) F).ofDual := by
  ext v
  rw [mem_intermediateFieldEquivSubmoduleSqrtPrimes_apply_ofDual_iff,
    mem_intermediateFieldEquivSubmodule_apply_ofDual_iff]
  rfl

/-- **Degree/subspace-size relation for prime-radicand subfields.** For an intermediate field
`F` of `ℚ(√p₁, …, √pₙ)`, `[F : ℚ]` times the size of its attached subspace under
`intermediateFieldEquivSubmoduleSqrtPrimes` is `2 ^ |ι|`. -/
theorem finrank_mul_card_intermediateFieldEquivSubmoduleSqrtPrimes
    (F : IntermediateField ℚ (adjoin ℚ (Set.range fun i => (Real.sqrt (p i) : ℝ)))) :
    Module.finrank ℚ F
        * Nat.card (intermediateFieldEquivSubmoduleSqrtPrimes p hp hinj F).ofDual
      = 2 ^ Nat.card ι :=
by
  rw [intermediateFieldEquivSubmoduleSqrtPrimes_apply_ofDual_eq p hp hinj F]
  exact finrank_mul_card_intermediateFieldEquivSubmodule (sqrtPrime_sq p)
    (not_isSquare_prod_primes_of_injective p hp hinj) F

/-- **Degree/subspace-dimension relation for prime-radicand subfields.** For an intermediate
field `F` of `ℚ(√p₁, …, √pₙ)`, `[F : ℚ] · 2 ^ dim U = 2 ^ |ι|`, where `U` is the attached
subspace under `intermediateFieldEquivSubmoduleSqrtPrimes`. -/
theorem finrank_mul_two_pow_finrank_intermediateFieldEquivSubmoduleSqrtPrimes
    (F : IntermediateField ℚ (adjoin ℚ (Set.range fun i => (Real.sqrt (p i) : ℝ)))) :
    Module.finrank ℚ F
        * 2 ^ Module.finrank (ZMod 2) (intermediateFieldEquivSubmoduleSqrtPrimes p hp hinj F).ofDual
      = 2 ^ Nat.card ι :=
by
  rw [intermediateFieldEquivSubmoduleSqrtPrimes_apply_ofDual_eq p hp hinj F]
  exact finrank_mul_two_pow_finrank_intermediateFieldEquivSubmodule (sqrtPrime_sq p)
    (not_isSquare_prod_primes_of_injective p hp hinj) F

/-- **Degree of a prime-radicand intermediate field.** For an intermediate field `F` of
`ℚ(√p₁, …, √pₙ)`, its degree is `2` to the codimension of the attached subspace. -/
theorem finrank_intermediateField_sqrtPrimes_eq_two_pow
    (F : IntermediateField ℚ (adjoin ℚ (Set.range fun i => (Real.sqrt (p i) : ℝ)))) :
    Module.finrank ℚ F =
      2 ^ (Nat.card ι
        - Module.finrank (ZMod 2) (intermediateFieldEquivSubmoduleSqrtPrimes p hp hinj F).ofDual) :=
by
  rw [intermediateFieldEquivSubmoduleSqrtPrimes_apply_ofDual_eq p hp hinj F]
  exact finrank_intermediateField_eq_two_pow (sqrtPrime_sq p)
    (not_isSquare_prod_primes_of_injective p hp hinj) F

/-- **Quadratic subfields in the prime-radicand dictionary.** An intermediate field of
`ℚ(√p₁, …, √pₙ)` has degree `2` over `ℚ` exactly when its attached subspace is a hyperplane. -/
theorem finrank_intermediateField_sqrtPrimes_eq_two_iff
    (F : IntermediateField ℚ (adjoin ℚ (Set.range fun i => (Real.sqrt (p i) : ℝ)))) :
    Module.finrank ℚ F = 2 ↔
      Module.finrank (ZMod 2) (intermediateFieldEquivSubmoduleSqrtPrimes p hp hinj F).ofDual + 1
        = Nat.card ι :=
by
  rw [intermediateFieldEquivSubmoduleSqrtPrimes_apply_ofDual_eq p hp hinj F]
  exact finrank_intermediateField_eq_two_iff (sqrtPrime_sq p)
    (not_isSquare_prod_primes_of_injective p hp hinj) F

end PrimeFamily

end TauCeti.Multiquadratic
