/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.Multiquadratic.GaloisGroup

/-!
# Sign-change automorphisms of a multiquadratic field

The equivalence `TauCeti.Multiquadratic.galoisGroupEquiv` identifies the Galois group of a
square-class independent multiquadratic field with the sign-pattern group `Multiplicative
(ι → ZMod 2)`. This file packages the inverse direction of that equivalence as named
automorphisms: for a vector `ε : ι → ZMod 2`, `signChangeAut hroot hindep ε` is the
automorphism sending the generator `root i` to `(-1)^(ε i) root i`.

The coordinate sign changes are the standard generators used in the Galois-group and
prime-splitting layers: `coordinateSignChangeAut hroot hindep j` negates the `j`-th generator and
fixes all the others.

## Main results

* `TauCeti.Multiquadratic.signChangeAut`: the automorphism attached to a sign vector.
* `TauCeti.Multiquadratic.signChangeAut_apply_gen`: its action on each generator.
* `TauCeti.Multiquadratic.coordinateSignChangeAut`: the coordinate sign-change automorphism.
* `TauCeti.Multiquadratic.coordinateSignChangeAut_apply_gen_self` and
  `TauCeti.Multiquadratic.coordinateSignChangeAut_apply_gen_of_ne`: the generator rules.
* `TauCeti.Multiquadratic.signChangeAut_mem_closure_coordinateSignChangeAut`: every sign
  change lies in the subgroup generated by the coordinate sign changes.

## Provenance

This file is a thin named API around the already-credited `GaloisGroup` construction, which
generalises the sign-change automorphisms analysed in
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance), the formalization
of L. Alpöge's disproof of the uniform-constant Erdős unit-distance conjecture.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

variable {K L : Type*} [Field K] [Field L] [Algebra K L] {ι : Type*}
  [Finite ι] [NeZero (2 : K)] {d : ι → K} {root : ι → L}

/-- The sign-change automorphism with sign vector `ε`.

It is the inverse image of `ε` under the multiquadratic Galois-group equivalence, so it sends
`gen root i` to `(-1) ^ (ε i).val * gen root i`. -/
noncomputable def signChangeAut
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i))
    (ε : ι → ZMod 2) :
    adjoin K (Set.range root) ≃ₐ[K] adjoin K (Set.range root) :=
  (galoisGroupEquiv hroot hindep).symm (Multiplicative.ofAdd ε)

/-- The sign-change automorphism has the prescribed image under `galoisGroupEquiv`. -/
@[simp] theorem galoisGroupEquiv_signChangeAut
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i))
    (ε : ι → ZMod 2) :
    galoisGroupEquiv hroot hindep (signChangeAut hroot hindep ε) =
      Multiplicative.ofAdd ε := by
  simp [signChangeAut]

/-- The sign pattern of `signChangeAut hroot hindep ε` is exactly `ε`. -/
@[simp] theorem signPattern_signChangeAut
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i))
    (ε : ι → ZMod 2) :
    signPattern root (signChangeAut hroot hindep ε) = ε := by
  have h := galoisGroupEquiv_signChangeAut hroot hindep ε
  rw [galoisGroupEquiv_apply] at h
  exact Multiplicative.ofAdd.injective h

/-- The action of a sign-change automorphism on a generator. -/
@[simp] theorem signChangeAut_apply_gen
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i))
    (ε : ι → ZMod 2) (i : ι) :
    signChangeAut hroot hindep ε (gen root i) =
      (-1) ^ (ε i).val * gen root i :=
  galoisGroupEquiv_symm_apply_gen hroot hindep ε i

/-- The zero sign vector gives the identity automorphism. -/
@[simp] theorem signChangeAut_zero
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i)) :
    signChangeAut hroot hindep 0 = 1 := by
  apply (galoisGroupEquiv hroot hindep).injective
  simp

/-- Sign-change automorphisms multiply by adding their sign vectors. -/
@[simp] theorem signChangeAut_add
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i))
    (ε η : ι → ZMod 2) :
    signChangeAut hroot hindep (ε + η) =
      signChangeAut hroot hindep ε * signChangeAut hroot hindep η := by
  apply (galoisGroupEquiv hroot hindep).injective
  rw [galoisGroupEquiv_signChangeAut, map_mul, galoisGroupEquiv_signChangeAut,
    galoisGroupEquiv_signChangeAut, ofAdd_add]

/-- The automorphism that changes the sign of the `j`-th generator and fixes the others. -/
noncomputable def coordinateSignChangeAut
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i))
    (j : ι) [DecidableEq ι] :
    adjoin K (Set.range root) ≃ₐ[K] adjoin K (Set.range root) :=
  signChangeAut hroot hindep (Pi.single j 1)

/-- The coordinate sign-change automorphism negates its own generator. -/
@[simp] theorem coordinateSignChangeAut_apply_gen_self
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i))
    (j : ι) [DecidableEq ι] :
    coordinateSignChangeAut hroot hindep j (gen root j) = -gen root j := by
  rw [coordinateSignChangeAut, signChangeAut_apply_gen, Pi.single_eq_same]
  rw [ZMod.val_one, pow_one, neg_one_mul]

/-- A coordinate sign-change automorphism fixes the other generators. -/
@[simp] theorem coordinateSignChangeAut_apply_gen_of_ne
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i))
    {i j : ι} [DecidableEq ι] (hij : i ≠ j) :
    coordinateSignChangeAut hroot hindep j (gen root i) = gen root i := by
  rw [coordinateSignChangeAut, signChangeAut_apply_gen, Pi.single_eq_of_ne hij]
  simp

/-- The sign pattern of a coordinate sign-change automorphism is the corresponding
`Pi.single` vector. -/
@[simp] theorem signPattern_coordinateSignChangeAut
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i))
    (j : ι) [DecidableEq ι] :
    signPattern root (coordinateSignChangeAut hroot hindep j) = Pi.single j 1 := by
  simp [coordinateSignChangeAut]

/-- Every sign-change automorphism lies in the subgroup generated by the coordinate sign
changes. -/
theorem signChangeAut_mem_closure_coordinateSignChangeAut [DecidableEq ι]
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i))
    (ε : ι → ZMod 2) :
    signChangeAut hroot hindep ε ∈
      Subgroup.closure (Set.range fun j => coordinateSignChangeAut hroot hindep j) := by
  letI := Fintype.ofFinite ι
  let G := Subgroup.closure (Set.range fun j => coordinateSignChangeAut hroot hindep j)
  have hsingle : ∀ j, signChangeAut hroot hindep (Pi.single j (ε j)) ∈ G := by
    intro j
    have hpow : signChangeAut hroot hindep (Pi.single j (ε j)) =
        (coordinateSignChangeAut hroot hindep j) ^ (ε j).val := by
      apply (galoisGroupEquiv hroot hindep).injective
      rw [galoisGroupEquiv_signChangeAut, map_pow, coordinateSignChangeAut,
        galoisGroupEquiv_signChangeAut]
      rw [← ofAdd_nsmul]
      congr 1
      funext i
      by_cases hij : i = j
      · subst i
        simp
      · simp [Pi.single_eq_of_ne hij]
    rw [hpow]
    exact G.pow_mem (Subgroup.subset_closure ⟨j, rfl⟩) (ε j).val
  have hsum : ∀ s : Finset ι,
      signChangeAut hroot hindep (∑ j ∈ s, Pi.single j (ε j)) ∈ G := by
    intro s
    refine Finset.induction_on s ?_ ?_
    · simp [G]
    · intro j s hjs hs
      rw [Finset.sum_insert hjs, signChangeAut_add]
      exact G.mul_mem (hsingle j) hs
  convert hsum Finset.univ using 2
  funext i
  rw [Finset.sum_apply, Finset.sum_eq_single i]
  · simp
  · intro j _ hji
    simp [Pi.single_eq_of_ne hji.symm]
  · simp

/-- A coordinate sign-change automorphism has order dividing two. -/
@[simp] theorem coordinateSignChangeAut_mul_self
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i))
    (j : ι) [DecidableEq ι] :
    coordinateSignChangeAut hroot hindep j * coordinateSignChangeAut hroot hindep j = 1 := by
  rw [coordinateSignChangeAut]
  rw [← signChangeAut_add, ZModModule.add_self, signChangeAut_zero]

/-- Coordinate sign-change automorphisms commute. -/
theorem coordinateSignChangeAut_commute
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i))
    (i j : ι) [DecidableEq ι] :
    Commute (coordinateSignChangeAut hroot hindep i) (coordinateSignChangeAut hroot hindep j) :=
  aut_commute hroot _ _

end TauCeti.Multiquadratic
