/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Data.List.Chain
public import TauCeti.GroupTheory.Coxeter.BraidEquivalence
public import TauCeti.GroupTheory.Coxeter.Parabolic

/-!
# Rank-two standard parabolic subgroups, and Tits' lemma

Let `cs : CoxeterSystem M W` and let `i ≠ i'` be two indices. The standard parabolic subgroup
`cs.parabolic {i, i'}` is generated by the two involutions `s i` and `s i'`, so it is a dihedral
group, and the words that spell its elements are the **alternating words** of Mathlib's
`CoxeterSystem.alternatingWord`. This file proves that, and extracts from it **Tits' lemma**: an
element with two distinct left descents has a rank-two parabolic factor that is spelled by *both*
alternating words of its length.

Three steps carry the whole file.

* A reduced word has no two adjacent equal letters (`CoxeterSystem.IsReduced.isChain_ne`), because
  deleting such a pair shortens the word without changing its product. A list in two letters with
  no adjacent repetition is an alternating word
  (`CoxeterSystem.eq_alternatingWord_of_forall_mem_pair`), so a reduced word for an element of
  `cs.parabolic {i, i'}` is one of the two alternating words of its length.
* The two alternating words of a given length have the same product exactly when the rotation
  `s i * s i'` is killed by that length
  (`CoxeterSystem.wordProd_alternatingWord_eq_comm_iff`). This is a direct computation from
  `CoxeterSystem.prod_alternatingWord_eq_mul_pow`, and it is the only place the dihedral
  arithmetic enters.
* A left descent `i` of `w` turns a reduced word for `s i * w` into a reduced word for `w`
  beginning with `i`. If both `i` and `i'` are left descents of a parabolic `w`, that produces two
  reduced words for `w` with different first letters, hence — the two alternating words being the
  only candidates — *both* alternating words of length `ℓ w` spell `w`.

## The remaining gap to Matsumoto's theorem

Tits' lemma is classically stated with the Coxeter-matrix entry `M i i'` in place of the length of
the parabolic factor. What is proved here unconditionally is the divisibility half: the parabolic
factor `x` satisfies `(s i * s i') ^ ℓ x = 1`, and `ℓ x ≤ M i i'` whenever `M i i' ≠ 0`. Together
these give `ℓ x = M i i'` as soon as `orderOf (cs.simple i * cs.simple i') = M i i'`, which is why
the statements below that mention `M i i'` carry that equality as a hypothesis
(`CoxeterSystem.exists_wordProd_braidWord_mul_of_isLeftDescent_pair`). That the order of
`s i * s i'` is *exactly* `M i i'`, rather than merely a divisor of it
(`CoxeterSystem.simple_mul_simple_pow`), is Tits' theorem on the geometric representation; neither
Mathlib nor this repository has it, and it is the one input still separating this file from
Matsumoto's theorem. Everything else the induction step of Matsumoto needs is supplied here, in
`CoxeterSystem.exists_braidEquivalent_isReduced_of_isLeftDescent_pair`: two braid-equivalent
reduced words for `w`, one beginning with `i` and one beginning with `i'`.

## Main results

* `CoxeterSystem.IsReduced.isChain_ne`: a reduced word has no two adjacent equal letters.
* `CoxeterSystem.eq_alternatingWord_of_forall_mem_pair` and
  `CoxeterSystem.eq_alternatingWord_or_of_forall_mem_pair`: a list in two letters with no adjacent
  repetition is an alternating word.
* `CoxeterSystem.wordProd_alternatingWord_eq_of_mem_parabolic_pair`: **every element of a rank-two
  standard parabolic subgroup is spelled by an alternating word of its own length.**
* `CoxeterSystem.wordProd_alternatingWord_eq_comm_iff`: the two alternating words of length `m`
  have the same product exactly when `(s i * s i') ^ m = 1`.
* `CoxeterSystem.wordProd_alternatingWord_eq_of_isLeftDescent_pair`: **an element of a rank-two
  standard parabolic subgroup with two distinct left descents is spelled by both alternating words
  of its length**, hence `CoxeterSystem.pow_length_eq_one_of_isLeftDescent_pair` and
  `CoxeterSystem.length_le_of_isLeftDescent_pair`.
* `CoxeterSystem.exists_mem_parabolic_pair_mul_of_isLeftDescent_pair`: the rank-two parabolic
  factor of an element with two distinct left descents inherits both descents.
* `CoxeterSystem.exists_wordProd_alternatingWord_mul_of_isLeftDescent_pair`: **Tits' lemma.**
* `CoxeterSystem.exists_wordProd_braidWord_mul_of_isLeftDescent_pair` and
  `CoxeterSystem.exists_braidEquivalent_isReduced_of_isLeftDescent_pair`: the classical form of
  Tits' lemma, and the induction step of Matsumoto's theorem, under the order hypothesis discussed
  above.

## References

* A. Björner and F. Brenti, *Combinatorics of Coxeter Groups*, Springer GTM 231 (2005),
  Sections 2.2 and 3.3.
* J. E. Humphreys, *Reflection Groups and Coxeter Groups*, CUP (1990), Sections 1.9 and 5.12.
* [Root-systems roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/RootSystems/README.md),
  Layer 3, "Matsumoto's theorem".
-/

public section

namespace CoxeterSystem

variable {B W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W)

local prefix:100 "s " => cs.simple
local prefix:100 "π " => cs.wordProd
local prefix:100 "ℓ " => cs.length

/-! ### Words in two letters -/

/-- The inductive core of `CoxeterSystem.eq_alternatingWord_of_forall_mem_pair`, with the length
of the word made explicit so that the induction may exchange the two letters. -/
private theorem eq_alternatingWord_aux :
    ∀ (n : ℕ) (i i' : B) (ω : List B), ω.length = n → (∀ j ∈ ω, j = i ∨ j = i') →
      ω.IsChain (· ≠ ·) → (∀ j ∈ ω.getLast?, j = i') → ω = alternatingWord i i' n := by
  intro n
  induction n with
  | zero =>
      intro i i' ω hlen _ _ _
      rw [List.length_eq_zero_iff] at hlen
      simp [hlen, alternatingWord]
  | succ n ih =>
      intro i i' ω hlen hmem hchain hlast
      obtain rfl | ⟨σ, a, rfl⟩ := List.eq_nil_or_concat' ω
      · simp at hlen
      have ha : i' = a := (hlast a (by simp)).symm
      subst ha
      have hσlen : σ.length = n := by simpa using hlen
      obtain ⟨hσchain, -, hjoin⟩ := List.isChain_append.mp hchain
      have hσ : σ = alternatingWord i' i n := by
        refine ih i' i σ hσlen (fun j hj => (hmem j (by simp [hj])).symm) hσchain ?_
        intro j hj
        have hjne : j ≠ i' := hjoin j hj i' (by simp)
        have hjmem : j ∈ σ := List.mem_of_mem_getLast? hj
        exact (hmem j (by simp [hjmem])).resolve_right hjne
      rw [alternatingWord_succ, hσ]
      simp

/-- **A list in two letters with no adjacent repetition is an alternating word.** If every letter
of `ω` is `i` or `i'`, no two adjacent letters are equal, and the last letter is `i'`, then `ω` is
the alternating word of its own length ending in `i'`. -/
theorem eq_alternatingWord_of_forall_mem_pair {i i' : B} {ω : List B}
    (hmem : ∀ j ∈ ω, j = i ∨ j = i') (hchain : ω.IsChain (· ≠ ·))
    (hlast : ∀ j ∈ ω.getLast?, j = i') : ω = alternatingWord i i' ω.length :=
  eq_alternatingWord_aux ω.length i i' ω rfl hmem hchain hlast

/-- **A list in two letters with no adjacent repetition is one of the two alternating words of its
length.** Which of the two it is, is decided by its last letter. -/
theorem eq_alternatingWord_or_of_forall_mem_pair {i i' : B} {ω : List B}
    (hmem : ∀ j ∈ ω, j = i ∨ j = i') (hchain : ω.IsChain (· ≠ ·)) :
    ω = alternatingWord i i' ω.length ∨ ω = alternatingWord i' i ω.length := by
  rcases hgl : ω.getLast? with - | a
  · have hnil : ω = [] := List.getLast?_eq_none_iff.mp hgl
    subst hnil
    exact Or.inl (by simp [alternatingWord])
  · have hamem : a ∈ ω.getLast? := by simp [hgl]
    have hlast : ∀ j ∈ ω.getLast?, j = a := by
      intro j hj
      rw [hgl, Option.mem_some_iff] at hj
      exact hj.symm
    rcases hmem a (List.mem_of_mem_getLast? hamem) with rfl | rfl
    · exact Or.inr (eq_alternatingWord_of_forall_mem_pair (fun j hj => (hmem j hj).symm) hchain
        hlast)
    · exact Or.inl (eq_alternatingWord_of_forall_mem_pair hmem hchain hlast)

section

variable {cs}

/-- **A reduced word has no two adjacent equal letters.** Deleting such a pair leaves the product
unchanged and the word shorter, so the original word was not of minimal length. -/
theorem IsReduced.isChain_ne {ω : List B} (hω : cs.IsReduced ω) : ω.IsChain (· ≠ ·) := by
  revert hω
  induction ω with
  | nil => intro _; simp
  | cons a ρ ih =>
      cases ρ with
      | nil => intro _; simp
      | cons b τ =>
          intro hω
          have hρ : cs.IsReduced (b :: τ) := by simpa using hω.drop 1
          refine List.isChain_cons_cons.mpr ⟨?_, ih hρ⟩
          rintro rfl
          have hprod : π (a :: a :: τ) = π τ := by
            rw [cs.wordProd_cons, cs.wordProd_cons, cs.simple_mul_simple_cancel_left]
          have hle := cs.length_wordProd_le τ
          have heq := hω.eq
          rw [hprod] at heq
          simp only [List.length_cons] at heq
          omega

end

/-! ### Elements of a rank-two standard parabolic subgroup -/

/-- A reduced word all of whose letters are `i` or `i'` is one of the two alternating words of its
length. -/
theorem eq_alternatingWord_or_of_isReduced {i i' : B} {ω : List B} (hω : cs.IsReduced ω)
    (hmem : ∀ j ∈ ω, j = i ∨ j = i') :
    ω = alternatingWord i i' ω.length ∨ ω = alternatingWord i' i ω.length :=
  eq_alternatingWord_or_of_forall_mem_pair hmem hω.isChain_ne

/-- **Every element of a rank-two standard parabolic subgroup is spelled by an alternating word of
its own length.** Being of length `ℓ w`, that word is reduced. -/
theorem wordProd_alternatingWord_eq_of_mem_parabolic_pair {i i' : B} {w : W}
    (hw : w ∈ cs.parabolic {i, i'}) :
    π (alternatingWord i i' (ℓ w)) = w ∨ π (alternatingWord i' i (ℓ w)) = w := by
  obtain ⟨ω, hred, hωJ, rfl⟩ := cs.exists_isReduced_wordProd_eq_of_mem_parabolic hw
  have hmem : ∀ j ∈ ω, j = i ∨ j = i' := fun j hj => by simpa using hωJ j hj
  rw [hred.eq]
  rcases cs.eq_alternatingWord_or_of_isReduced hred hmem with h | h
  · exact Or.inl (by rw [← h])
  · exact Or.inr (by rw [← h])

/-- **The two alternating words of length `m` have the same product exactly when the rotation
`s i * s i'` is killed by `m`.** This is the dihedral arithmetic of a rank-two parabolic subgroup,
and the only computation in this file. -/
theorem wordProd_alternatingWord_eq_comm_iff (i i' : B) (m : ℕ) :
    π (alternatingWord i i' m) = π (alternatingWord i' i m) ↔ (s i * s i') ^ m = 1 := by
  have hinv : s i' * s i = (s i * s i')⁻¹ := by
    rw [mul_inv_rev, cs.inv_simple, cs.inv_simple]
  rw [cs.prod_alternatingWord_eq_mul_pow, cs.prod_alternatingWord_eq_mul_pow, hinv, inv_pow]
  rcases Nat.even_or_odd m with hm | hm
  · obtain ⟨p, hp⟩ := hm
    have hev : Even m := ⟨p, hp⟩
    have hdiv : m / 2 = p := by omega
    simp only [ite_eq_left hev, one_mul, hdiv]
    rw [eq_inv_iff_mul_eq_one, ← pow_add, show p + p = m from hp.symm]
  · obtain ⟨p, hp⟩ := hm
    have hnot : ¬Even m := by rw [hp]; simp [parity_simps]
    have hdiv : m / 2 = p := by omega
    simp only [ite_eq_right hnot, hdiv]
    rw [← inv_mul_eq_iff_eq_mul, cs.inv_simple, ← mul_assoc, ← pow_succ',
      eq_inv_iff_mul_eq_one, ← pow_add, show p + 1 + p = m from by omega]

/-! ### Two left descents -/

/-- A left descent of `w` turns a reduced word for `s i * w` into a reduced word for `w`. -/
theorem isReduced_cons_of_isLeftDescent {i : B} {w : W} (hd : cs.IsLeftDescent w i) {ω : List B}
    (hω : cs.IsReduced ω) (hprod : π ω = s i * w) : cs.IsReduced (i :: ω) := by
  have hw : π (i :: ω) = w := by
    rw [cs.wordProd_cons, hprod, cs.simple_mul_simple_cancel_left]
  have hlen : ℓ (s i * w) + 1 = ℓ w := cs.isLeftDescent_iff.mp hd
  rw [IsReduced, hw, List.length_cons, ← hω.eq, hprod, hlen]

/-- **An element of a rank-two standard parabolic subgroup with two distinct left descents is
spelled by both alternating words of its length.** The two descents produce two reduced words with
different first letters, and the two alternating words of that length are the only candidates. -/
theorem wordProd_alternatingWord_eq_of_isLeftDescent_pair {i i' : B} (hne : i ≠ i') {w : W}
    (hw : w ∈ cs.parabolic {i, i'}) (hd : cs.IsLeftDescent w i) (hd' : cs.IsLeftDescent w i') :
    π (alternatingWord i i' (ℓ w)) = w ∧ π (alternatingWord i' i (ℓ w)) = w := by
  -- a reduced word for `w` beginning with a given left descent, with letters in `{i, i'}`
  have key : ∀ j : B, j ∈ ({i, i'} : Set B) → cs.IsLeftDescent w j →
      ∃ ω : List B, cs.IsReduced ω ∧ (∀ a ∈ ω, a = i ∨ a = i') ∧ π ω = w ∧
        ω.length = ℓ w ∧ ω.head? = some j := by
    intro j hj hdj
    have hmem : s j * w ∈ cs.parabolic {i, i'} :=
      mul_mem (cs.simple_mem_parabolic_of_isLeftDescent hw hdj) hw
    obtain ⟨ω, hred, hωJ, hprod⟩ := cs.exists_isReduced_wordProd_eq_of_mem_parabolic hmem
    have hredj : cs.IsReduced (j :: ω) := cs.isReduced_cons_of_isLeftDescent hdj hred hprod
    have hwprod : π (j :: ω) = w := by
      rw [cs.wordProd_cons, hprod, cs.simple_mul_simple_cancel_left]
    refine ⟨j :: ω, hredj, ?_, hwprod, ?_, rfl⟩
    · intro a ha
      rcases List.mem_cons.mp ha with rfl | ha
      · simpa using hj
      · simpa using hωJ a ha
    · rw [← hwprod, hredj.eq]
  obtain ⟨ω, hredω, hmemω, hprodω, hlenω, hheadω⟩ := key i (by simp) hd
  obtain ⟨ω', hredω', hmemω', hprodω', hlenω', hheadω'⟩ := key i' (by simp) hd'
  have hωne : ω ≠ ω' := fun h => hne (by rw [← Option.some_inj, ← hheadω, h, hheadω'])
  have hA := cs.eq_alternatingWord_or_of_isReduced hredω hmemω
  have hB := cs.eq_alternatingWord_or_of_isReduced hredω' hmemω'
  rw [hlenω] at hA
  rw [hlenω'] at hB
  rcases hA with hA | hA <;> rcases hB with hB | hB
  · exact absurd (hA.trans hB.symm) hωne
  · exact ⟨hA ▸ hprodω, hB ▸ hprodω'⟩
  · exact ⟨hB ▸ hprodω', hA ▸ hprodω⟩
  · exact absurd (hA.trans hB.symm) hωne

/-- The rotation `s i * s i'` is killed by the length of an element of `cs.parabolic {i, i'}` with
two distinct left descents. -/
theorem pow_length_eq_one_of_isLeftDescent_pair {i i' : B} (hne : i ≠ i') {w : W}
    (hw : w ∈ cs.parabolic {i, i'}) (hd : cs.IsLeftDescent w i) (hd' : cs.IsLeftDescent w i') :
    (s i * s i') ^ (ℓ w) = 1 := by
  obtain ⟨h, h'⟩ := cs.wordProd_alternatingWord_eq_of_isLeftDescent_pair hne hw hd hd'
  exact (cs.wordProd_alternatingWord_eq_comm_iff i i' (ℓ w)).mp (by rw [h, h'])

/-- An element of `cs.parabolic {i, i'}` with two distinct left descents is no longer than the
Coxeter-matrix entry `M i i'`, which is the length above which the alternating words stop being
reduced. -/
theorem length_le_of_isLeftDescent_pair {i i' : B} (hne : i ≠ i') (hM : M i i' ≠ 0) {w : W}
    (hw : w ∈ cs.parabolic {i, i'}) (hd : cs.IsLeftDescent w i) (hd' : cs.IsLeftDescent w i') :
    ℓ w ≤ M i i' := by
  by_contra hlt
  refine cs.not_isReduced_alternatingWord i i' (m := ℓ w) hM (by omega) ?_
  rw [IsReduced, (cs.wordProd_alternatingWord_eq_of_isLeftDescent_pair hne hw hd hd').1,
    length_alternatingWord]

/-- **The rank-two parabolic factor of an element with two distinct left descents inherits both
descents.** The factorization is the one of `CoxeterSystem.existsUnique_mem_parabolic_mul`, whose
lengths add. -/
theorem exists_mem_parabolic_pair_mul_of_isLeftDescent_pair {i i' : B} {w : W}
    (hd : cs.IsLeftDescent w i) (hd' : cs.IsLeftDescent w i') :
    ∃ x v : W, x ∈ cs.parabolic {i, i'} ∧ cs.IsLeftDescent x i ∧ cs.IsLeftDescent x i' ∧
      w = x * v ∧ ℓ w = ℓ x + ℓ v := by
  obtain ⟨⟨x, v⟩, ⟨hx, hv, rfl⟩, -⟩ := cs.existsUnique_mem_parabolic_mul {i, i'} w
  have hadd : ∀ y ∈ cs.parabolic ({i, i'} : Set B), ℓ (y * v) = ℓ y + ℓ v := fun y hy =>
    cs.length_mul_of_forall_not_isLeftDescent hy hv
  have hdesc : ∀ j : B, j ∈ ({i, i'} : Set B) → cs.IsLeftDescent (x * v) j →
      cs.IsLeftDescent x j := by
    intro j hj hdj
    have hsx : s j * x ∈ cs.parabolic ({i, i'} : Set B) :=
      mul_mem (cs.simple_mem_parabolic hj) hx
    have h₁ : ℓ (s j * (x * v)) = ℓ (s j * x) + ℓ v := by
      rw [← mul_assoc]; exact hadd _ hsx
    rw [IsLeftDescent, h₁, hadd x hx] at hdj
    rw [IsLeftDescent]
    omega
  exact ⟨x, v, hx, hdesc i (by simp) hd, hdesc i' (by simp) hd', rfl, hadd x hx⟩

/-- **Tits' lemma.** If `i ≠ i'` are both left descents of `w`, then `w` splits as a rank-two
parabolic factor of some positive length `k` times a remainder, the lengths adding, and the
parabolic factor is spelled by *both* alternating words of length `k`. The rotation `s i * s i'`
is killed by `k`, and `k` is at most the Coxeter-matrix entry `M i i'`.

Classically `k` is `M i i'` on the nose; see the module docstring and
`CoxeterSystem.exists_wordProd_braidWord_mul_of_isLeftDescent_pair` for the extra input that
identifies the two. -/
theorem exists_wordProd_alternatingWord_mul_of_isLeftDescent_pair {i i' : B} (hne : i ≠ i')
    {w : W} (hd : cs.IsLeftDescent w i) (hd' : cs.IsLeftDescent w i') :
    ∃ (k : ℕ) (v : W), 0 < k ∧ (s i * s i') ^ k = 1 ∧ (M i i' ≠ 0 → k ≤ M i i') ∧
      w = π (alternatingWord i i' k) * v ∧ w = π (alternatingWord i' i k) * v ∧
      ℓ w = k + ℓ v := by
  obtain ⟨x, v, hx, hdx, hdx', rfl, hlen⟩ :=
    cs.exists_mem_parabolic_pair_mul_of_isLeftDescent_pair hd hd'
  obtain ⟨h, h'⟩ := cs.wordProd_alternatingWord_eq_of_isLeftDescent_pair hne hx hdx hdx'
  have hpos : 0 < ℓ x := by
    have hx1 := cs.isLeftDescent_iff.mp hdx
    omega
  exact ⟨ℓ x, v, hpos, cs.pow_length_eq_one_of_isLeftDescent_pair hne hx hdx hdx',
    fun hM => cs.length_le_of_isLeftDescent_pair hne hM hx hdx hdx',
    by rw [h], by rw [h'], hlen⟩

/-! ### The classical form, and the induction step of Matsumoto's theorem -/

/-- A braid word is an alternating word; this is the definition of
`CoxeterSystem.braidWord`, recorded so that the alternating-word API can be rewritten into it. -/
private theorem braidWord_eq (j j' : B) : braidWord M j j' = alternatingWord j j' (M j j') := rfl

/-- The length of a braid word is its Coxeter-matrix entry. -/
private theorem length_braidWord (j j' : B) : (braidWord M j j').length = M j j' := by
  rw [braidWord_eq, length_alternatingWord]

/-- The first letter of a braid word of positive length, read off through
`CoxeterSystem.alternatingWord_succ'`. -/
private theorem head?_braidWord_append {j j' : B} {m : ℕ} (hm : M j j' = m + 1) (β : List B) :
    (braidWord M j j' ++ β).head? = some (if Even m then j' else j) := by
  rw [braidWord_eq, hm, alternatingWord_succ']
  simp

/-- **Tits' lemma in its classical form**, under the hypothesis that the order of `s i * s i'` is
the Coxeter-matrix entry `M i i'`: an element with two distinct left descents `i` and `i'` is the
braid word in `i` and `i'` times a remainder, with lengths adding, and the bond `M i i'` is
finite.

Only the divisibility `orderOf (s i * s i') ∣ M i i'` is available in general
(`CoxeterSystem.simple_mul_simple_pow`); the reverse inequality is Tits' theorem on the geometric
representation, which is why it appears here as a hypothesis. -/
theorem exists_wordProd_braidWord_mul_of_isLeftDescent_pair {i i' : B} (hne : i ≠ i') {w : W}
    (hord : orderOf (s i * s i') = M i i') (hd : cs.IsLeftDescent w i)
    (hd' : cs.IsLeftDescent w i') :
    ∃ v : W, 0 < M i i' ∧ w = π (braidWord M i i') * v ∧ w = π (braidWord M i' i) * v ∧
      ℓ w = M i i' + ℓ v := by
  obtain ⟨k, v, hpos, hpow, hle, hwk, hwk', hlen⟩ :=
    cs.exists_wordProd_alternatingWord_mul_of_isLeftDescent_pair hne hd hd'
  have hdvd : M i i' ∣ k := hord ▸ orderOf_dvd_of_pow_eq_one hpow
  have hM : 0 < M i i' := by
    rcases Nat.eq_zero_or_pos (M i i') with h | h
    · rw [h, zero_dvd_iff] at hdvd
      omega
    · exact h
  have hk : k = M i i' := Nat.le_antisymm (hle (by omega)) (Nat.le_of_dvd hpos hdvd)
  subst hk
  refine ⟨v, hM, hwk, ?_, hlen⟩
  rw [braidWord_eq, M.symmetric i' i]
  exact hwk'

/-- **The induction step of Matsumoto's theorem**, under the same order hypothesis: an element `w`
with two distinct left descents `i` and `i'` has two *braid-equivalent* reduced words, one
beginning with `i` and one beginning with `i'`.

This is the step at which the classical induction on `ℓ w` splits, and it is the last thing that
proof needs beyond Mathlib's Coxeter API: two reduced words for `w` beginning with different
letters are each braid equivalent to one of these two, by the inductive hypothesis applied to the
shorter element obtained by deleting the common first letter. -/
theorem exists_braidEquivalent_isReduced_of_isLeftDescent_pair {i i' : B} (hne : i ≠ i') {w : W}
    (hord : orderOf (s i * s i') = M i i') (hd : cs.IsLeftDescent w i)
    (hd' : cs.IsLeftDescent w i') :
    ∃ ω ω' : List B, cs.IsReduced ω ∧ cs.IsReduced ω' ∧ π ω = w ∧ π ω' = w ∧
      ω.head? = some i ∧ ω'.head? = some i' ∧ BraidEquivalent M ω ω' := by
  obtain ⟨v, hM, hwv, hwv', hlen⟩ :=
    cs.exists_wordProd_braidWord_mul_of_isLeftDescent_pair hne hord hd hd'
  obtain ⟨β, hβ, rfl⟩ := cs.exists_isReduced v
  -- a braid word followed by a reduced word for the remainder is a reduced word for `w`
  have hred : ∀ j j' : B, w = π (braidWord M j j') * π β → M j j' = M i i' →
      cs.IsReduced (braidWord M j j' ++ β) ∧ π (braidWord M j j' ++ β) = w := by
    intro j j' hwjj hMj
    refine ⟨?_, by rw [cs.wordProd_append, ← hwjj]⟩
    rw [IsReduced, cs.wordProd_append, ← hwjj, List.length_append, length_braidWord, hMj, hlen,
      hβ.eq]
  obtain ⟨hredA, hprodA⟩ := hred i i' hwv rfl
  obtain ⟨hredB, hprodB⟩ := hred i' i hwv' (M.symmetric i' i)
  have hbraid : BraidEquivalent M (braidWord M i i' ++ β) (braidWord M i' i ++ β) :=
    (BraidEquivalent.braidWord i i').append_right β
  obtain ⟨m, hm⟩ : ∃ m, M i i' = m + 1 := ⟨M i i' - 1, by omega⟩
  have hheadA : (braidWord M i i' ++ β).head? = some (if Even m then i' else i) :=
    head?_braidWord_append hm β
  have hheadB : (braidWord M i' i ++ β).head? = some (if Even m then i else i') :=
    head?_braidWord_append ((M.symmetric i' i).trans hm) β
  by_cases hpar : Even m
  · exact ⟨braidWord M i' i ++ β, braidWord M i i' ++ β, hredB, hredA, hprodB, hprodA,
      by rw [hheadB]; simp [hpar], by rw [hheadA]; simp [hpar], hbraid.symm⟩
  · exact ⟨braidWord M i i' ++ β, braidWord M i' i ++ β, hredA, hredB, hprodA, hprodB,
      by rw [hheadA]; simp [hpar], by rw [hheadB]; simp [hpar], hbraid⟩

end CoxeterSystem
