/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.LocalField.Different
public import TauCeti.NumberTheory.LocalField.Norm.Basic

/-!
# The local discriminant of an extension of local fields

The different `𝔡(L/K)` of Mathlib is an ideal of `𝒪[L]`, the ring of integers of the *upper* field
of an extension `L/K` of nonarchimedean local fields. The discriminant `𝔩(L/K)` of the same
extension is an ideal of the *base* ring `𝒪[K]`: it is the norm image `N_{L/K}(𝔡(L/K))`. The two
ideals live in different rings and are not to be conflated: `TauCeti.differentExponent` reads the
exponent of `𝔡(L/K)` in the maximal ideal of `𝒪[L]`, and this file adds
`TauCeti.discriminantExponent K L`, the exponent `δ(L/K)` of the maximal ideal of `𝒪[K]` in
`𝔩(L/K)`.

A norm multiplies valuations by the residue degree, by `TauCeti.toAdd_normalizedValuation_norm`, so
`𝓂[K] ^ f(L/K)` generates the norm image of `𝓂[L]`
(`TauCeti.map_maximalIdeal_norm_eq_maximalIdeal_pow`). The discriminant ideal is then
`𝔩(L/K) = 𝓂[K] ^ δ(L/K)`, the ideal form of the product formula `δ(L/K) = f(L/K) · d(L/K)`
(`TauCeti.discriminantExponent_eq_inertiaDegree_mul_differentExponent`). Since
`TauCeti.differentExponent` is `0` exactly for unramified extensions, the discriminant inherits the
unramified criterion and the bound `e(L/K) - 1 ≤ δ(L/K)`.

## Main definitions

* `TauCeti.discriminantIdeal`: the local discriminant ideal `𝔩(L/K) = N_{L/K}(𝔡(L/K))`.
* `TauCeti.discriminantExponent`: the local discriminant exponent `δ(L/K)`, the multiplicity of
  `𝓂[K]` in `𝔩(L/K)`.

## Main results

* `TauCeti.discriminantIdeal_def`, `TauCeti.discriminantExponent_def`: the defining formulas.
* `TauCeti.map_span_singleton_norm_eq_span_singleton`: the norm image of a principal ideal of
  `𝒪[L]` is the principal ideal generated by the norm of its generator.
* `TauCeti.map_maximalIdeal_norm_eq_maximalIdeal_pow`: the norm of the maximal ideal of `𝒪[L]`
  generates the `f(L/K)`-th power of the maximal ideal of `𝒪[K]`, the ideal-theoretic form of
  `TauCeti.toAdd_normalizedValuation_norm`.
* `TauCeti.discriminantExponent_eq_inertiaDegree_mul_differentExponent`: the product formula
  `δ(L/K) = f(L/K) · d(L/K)`.
* `TauCeti.discriminantIdeal_eq_maximalIdeal_pow`: `𝔩(L/K) = 𝓂[K] ^ δ(L/K)`.
* `TauCeti.pow_dvd_discriminantIdeal_iff_le_discriminantExponent`: the characteristic property,
  `𝓂[K] ^ n ∣ 𝔩(L/K) ↔ n ≤ δ(L/K)`.
* `TauCeti.discriminantIdeal_eq_top_iff` and `TauCeti.discriminantExponent_eq_zero_iff`: the
  discriminant is trivial exactly when the extension is unramified.
* `TauCeti.ramificationIndex_sub_one_le_discriminantExponent`: the local discriminant bound.
* `TauCeti.discriminantExponent_eq_inertiaDegree_mul_ramificationIndex_sub_one_iff`: the tame
  value of the discriminant exponent.

## References

* [J.-P. Serre, *Corps Locaux*][serre1968], Chapter III, §6, Proposition 13.
* J. Neukirch, *Algebraic Number Theory*, Chapter II, §8.
-/

public section
noncomputable section

open ValuativeRel IsLocalRing

namespace TauCeti

variable (K L : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [Field L] [ValuativeRel L] [TopologicalSpace L]
  [IsNonarchimedeanLocalField L] [Algebra K L] [ValuativeExtension K L]

omit [TopologicalSpace K] [IsNonarchimedeanLocalField K] in
/-- The local discriminant ideal `𝔩(L/K) = N_{L/K}(𝔡(L/K))` of an extension `L/K` of
nonarchimedean local fields: the norm image of the different ideal, an ideal of the base ring
`𝒪[K]`. It is not the different ideal `𝔡(L/K)`, which is an ideal of `𝒪[L]`. -/
noncomputable def discriminantIdeal : Ideal 𝒪[K] :=
  (differentIdeal 𝒪[K] 𝒪[L]).map (Algebra.norm 𝒪[K])

omit [TopologicalSpace K] [IsNonarchimedeanLocalField K] in
/-- The defining formula of the local discriminant ideal. -/
theorem discriminantIdeal_def :
    discriminantIdeal K L = (differentIdeal 𝒪[K] 𝒪[L]).map (Algebra.norm 𝒪[K]) := (rfl)

omit [TopologicalSpace K] [IsNonarchimedeanLocalField K] [TopologicalSpace L]
  [IsNonarchimedeanLocalField L] in
/-- The norm image of a principal ideal of `𝒪[L]` is the principal ideal generated by the norm of
its generator: `N_{L/K}((x)) = (N_{L/K}(x))` for `x : 𝒪[L]`.

This is the ideal-theoretic form of the multiplicativity of the norm. It holds for a monoid
homomorphism, and is stated here because Mathlib's `Ideal.map_span` is restricted to ring
homomorphisms, while `Algebra.norm 𝒪[K]` is presented as a monoid homomorphism. -/
theorem map_span_singleton_norm_eq_span_singleton (x : 𝒪[L]) :
    (Ideal.span {x} : Ideal 𝒪[L]).map (Algebra.norm 𝒪[K])
      = Ideal.span {Algebra.norm 𝒪[K] x} := by
  have key : ((Algebra.norm 𝒪[K]) '' (↑(Ideal.span {x} : Ideal 𝒪[L]) : Set 𝒪[L]))
      ⊆ (Ideal.span {Algebra.norm 𝒪[K] x} : Ideal 𝒪[K]) := by
    rintro _ ⟨c, hc, rfl⟩
    obtain ⟨a, ha⟩ : ∃ a : 𝒪[L], a * x = c :=
      Ideal.mem_span_singleton'.mp (show c ∈ Ideal.span {x} from hc)
    subst ha
    rw [map_mul]
    exact Ideal.mem_span_singleton'.2 ⟨Algebra.norm 𝒪[K] a, rfl⟩
  refine le_antisymm ?_ ?_
  · rw [Ideal.map]
    exact Ideal.span_le.2 key
  · intro y hy
    rw [Ideal.mem_span_singleton] at hy
    obtain ⟨c, rfl⟩ := hy
    have hmem : Algebra.norm 𝒪[K] x
        ∈ ((Ideal.span {x} : Ideal 𝒪[L])).map (Algebra.norm 𝒪[K]) :=
      Ideal.mem_map_of_mem _ (Ideal.mem_span_singleton'.2 ⟨1, one_mul x⟩)
    simpa only [mul_comm] using
      ((Ideal.span {x} : Ideal 𝒪[L])).map (Algebra.norm 𝒪[K]) |>.mul_mem_left c hmem

/-- **The norm of the maximal ideal of `𝒪[L]` generates the residue-degree power of the maximal
ideal of `𝒪[K]`**: `N_{L/K}(𝓂[L]) = 𝓂[K] ^ f(L/K)`.

This is the ideal-theoretic form of `TauCeti.toAdd_normalizedValuation_norm`, the valuation of a
norm being `f(L/K)` times the valuation of its argument: a uniformizer of `𝒪[L]` is taken to an
element of `𝒪[K]` of normalized valuation `f(L/K)`, which generates `𝓂[K] ^ f(L/K)` in the discrete
valuation ring `𝒪[K]`. -/
theorem map_maximalIdeal_norm_eq_maximalIdeal_pow :
    𝓂[L].map (Algebra.norm 𝒪[K]) = 𝓂[K] ^ inertiaDegree K L := by
  let _ : FiniteDimensional K L := finite_of_valuativeExtension K L
  obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible 𝒪[K]
  obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible 𝒪[L]
  have hϖ' : (ϖ : L) ≠ 0 := fun h ↦ hϖ.ne_zero (Subtype.ext h)
  have hπ' : (π : K) ≠ 0 := fun h ↦ hπ.ne_zero (Subtype.ext h)
  -- the norm of the uniformizer of `L` has residue-degree valuation in `K`, and so does the
  -- residue-degree power of the uniformizer of `K`
  have hn' : (normalizedValuation K (Algebra.normUnits K (Units.mk0 (ϖ : L) hϖ'))).toAdd
      = (inertiaDegree K L : ℤ) := by
    have hn := toAdd_normalizedValuation_norm (K := K) (L := L) (Units.mk0 (ϖ : L) hϖ')
    simpa only [Units.val_mk0, normalizedValuation_irreducible hϖ, toAdd_ofAdd,
      nsmul_eq_mul, mul_one] using hn
  have hb : (normalizedValuation K (Units.mk0 (π : K) hπ' ^ inertiaDegree K L)).toAdd
      = (inertiaDegree K L : ℤ) := by
    rw [map_pow, toAdd_pow, normalizedValuation_irreducible hπ, toAdd_ofAdd,
      nsmul_eq_mul, mul_one]
  have hle : (normalizedValuation K (Units.mk0 (π : K) hπ' ^ inertiaDegree K L)).toAdd
      ≤ (normalizedValuation K (Algebra.normUnits K (Units.mk0 (ϖ : L) hϖ'))).toAdd :=
    by rw [hb, hn']
  have hle' : (normalizedValuation K (Algebra.normUnits K (Units.mk0 (ϖ : L) hϖ'))).toAdd
      ≤ (normalizedValuation K (Units.mk0 (π : K) hπ' ^ inertiaDegree K L)).toAdd :=
    by rw [hn', hb]
  -- in the discrete valuation ring `𝒪[K]`, divisibility is comparison of valuations
  have hA : ((Algebra.norm 𝒪[K] ϖ : 𝒪[K]) : K)
      = ((Algebra.normUnits K (Units.mk0 (ϖ : L) hϖ') : Kˣ) : K) := by
    rw [coe_norm_integerRing]
    exact (Algebra.coe_normUnits (R := K) (Units.mk0 (ϖ : L) hϖ')).symm
  have hB : ((π ^ inertiaDegree K L : 𝒪[K]) : K)
      = ((Units.mk0 (π : K) hπ' ^ inertiaDegree K L : Kˣ) : K) := by
    push_cast
    exact (Units.val_pow_eq_pow_val (Units.mk0 (π : K) hπ') (inertiaDegree K L)).symm
  have hco (y : 𝒪[K]) : ((y : 𝒪[K]) : K) = algebraMap 𝒪[K] K y := rfl
  have hval := Valuation.integer.integers (valuation K)
  have h₁ : (Algebra.norm 𝒪[K] ϖ) ∣ (π ^ inertiaDegree K L : 𝒪[K]) := by
    refine hval.dvd_iff_le.mpr ?_
    rw [← hco, ← hco, hB, hA]
    exact (toAdd_normalizedValuation_le_iff_valuation_le
      (Algebra.normUnits K (Units.mk0 (ϖ : L) hϖ'))
      (Units.mk0 (π : K) hπ' ^ inertiaDegree K L)).1 hle'
  have h₂ : (π ^ inertiaDegree K L : 𝒪[K]) ∣ (Algebra.norm 𝒪[K] ϖ) := by
    refine hval.dvd_iff_le.mpr ?_
    rw [← hco, ← hco, hB, hA]
    exact (toAdd_normalizedValuation_le_iff_valuation_le
      (Units.mk0 (π : K) hπ' ^ inertiaDegree K L)
      (Algebra.normUnits K (Units.mk0 (ϖ : L) hϖ'))).1 hle
  have hass : Associated (Algebra.norm 𝒪[K] ϖ) (π ^ inertiaDegree K L) :=
    associated_of_dvd_dvd h₁ h₂
  calc 𝓂[L].map (Algebra.norm 𝒪[K])
      = ((Ideal.span {↑ϖ} : Ideal 𝒪[L])).map (Algebra.norm 𝒪[K]) := by rw [hϖ.maximalIdeal_eq]
    _ = Ideal.span {Algebra.norm 𝒪[K] ϖ} :=
        map_span_singleton_norm_eq_span_singleton (K := K) (L := L) ϖ
    _ = Ideal.span {↑(π ^ inertiaDegree K L)} :=
        (Ideal.span_singleton_eq_span_singleton).2 hass
    _ = (Ideal.span {↑π} : Ideal 𝒪[K]) ^ inertiaDegree K L :=
        (Ideal.span_singleton_pow (π : 𝒪[K]) (inertiaDegree K L)).symm
    _ = 𝓂[K] ^ inertiaDegree K L := by rw [hπ.maximalIdeal_eq]

/-- The local discriminant exponent `δ(L/K)` of an extension of nonarchimedean local fields: the
multiplicity of the maximal ideal of `𝒪[K]` in the discriminant ideal `discriminantIdeal K L`.
For `L/K` separable the discriminant ideal is `𝓂[K] ^ δ(L/K)`, by
`discriminantIdeal_eq_maximalIdeal_pow`, and the exponent is the product `f(L/K) · d(L/K)`, by
`discriminantExponent_eq_inertiaDegree_mul_differentExponent`. -/
def discriminantExponent : ℕ :=
  multiplicity 𝓂[K] (discriminantIdeal K L)

/-- The defining formula of `discriminantExponent`. -/
theorem discriminantExponent_def :
    discriminantExponent K L = multiplicity 𝓂[K] (discriminantIdeal K L) := (rfl)

variable [Algebra.IsSeparable K L]

/-- The local discriminant ideal is the `f(L/K) · d(L/K)`-th power of the maximal ideal of the
base ring, the form in which the norm image of the different is computed before the discriminant
exponent is read off it. -/
private theorem discriminantIdeal_eq_maximalIdeal_pow_mul :
    discriminantIdeal K L = 𝓂[K] ^ (inertiaDegree K L * differentExponent K L) := by
  obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible 𝒪[L]
  calc discriminantIdeal K L = (𝓂[L] ^ differentExponent K L).map (Algebra.norm 𝒪[K]) := by
        rw [discriminantIdeal_def, differentIdeal_eq_maximalIdeal_pow (K := K) (L := L)]
    _ = ((Ideal.span {↑(ϖ ^ differentExponent K L)} : Ideal 𝒪[L])).map
        (Algebra.norm 𝒪[K]) := by
      rw [hϖ.maximalIdeal_eq,
        ← Ideal.span_singleton_pow (ϖ : 𝒪[L]) (differentExponent K L)]
    _ = Ideal.span {↑((Algebra.norm 𝒪[K] ϖ) ^ differentExponent K L)} := by
      simpa only [map_pow] using
        (map_span_singleton_norm_eq_span_singleton (K := K) (L := L)
          (ϖ ^ differentExponent K L))
    _ = ((𝓂[L].map (Algebra.norm 𝒪[K])) ^ differentExponent K L) := by
      rw [← Ideal.span_singleton_pow (Algebra.norm 𝒪[K] ϖ) (differentExponent K L),
        ← map_span_singleton_norm_eq_span_singleton (K := K) (L := L) ϖ,
        ← hϖ.maximalIdeal_eq]
    _ = (𝓂[K] ^ inertiaDegree K L) ^ differentExponent K L := by
      rw [map_maximalIdeal_norm_eq_maximalIdeal_pow (K := K) (L := L)]
    _ = 𝓂[K] ^ (inertiaDegree K L * differentExponent K L) := by rw [pow_mul]

/-- **The product formula for the local discriminant exponent**: `δ(L/K) = f(L/K) · d(L/K)`, for
`L/K` separable. The residue degree enters by
`TauCeti.map_maximalIdeal_norm_eq_maximalIdeal_pow`, the different exponent by
`TauCeti.differentIdeal_eq_maximalIdeal_pow`. -/
theorem discriminantExponent_eq_inertiaDegree_mul_differentExponent :
    discriminantExponent K L = inertiaDegree K L * differentExponent K L := by
  rw [discriminantExponent_def, discriminantIdeal_eq_maximalIdeal_pow_mul,
    multiplicity_pow_self_of_prime
      (Ideal.prime_of_isPrime (IsDiscreteValuationRing.not_a_field 𝒪[K]) inferInstance)]

/-- **The local discriminant ideal is the `δ(L/K)`-th power of the maximal ideal of `𝒪[K]`**:
`𝔩(L/K) = 𝓂[K] ^ δ(L/K)`, for `L/K` separable. -/
theorem discriminantIdeal_eq_maximalIdeal_pow :
    discriminantIdeal K L = 𝓂[K] ^ discriminantExponent K L := by
  rw [discriminantExponent_eq_inertiaDegree_mul_differentExponent,
    discriminantIdeal_eq_maximalIdeal_pow_mul]

/-- The local discriminant ideal of a separable extension of local fields is nonzero, being the
`δ(L/K)`-th power of the maximal ideal of the base ring. -/
theorem discriminantIdeal_ne_bot : discriminantIdeal K L ≠ ⊥ := by
  obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible 𝒪[K]
  rw [discriminantIdeal_eq_maximalIdeal_pow, hπ.maximalIdeal_eq]
  intro h
  have h' : (π : 𝒪[K]) ^ discriminantExponent K L = 0 := by
    refine Ideal.span_singleton_eq_bot.mp ?_
    rw [← Ideal.span_singleton_pow π (discriminantExponent K L), h]
  exact (pow_ne_zero (n := discriminantExponent K L) hπ.ne_zero) h'

/-- **The characteristic property of the local discriminant exponent**: the `n`-th power of the
maximal ideal of `𝒪[K]` divides the discriminant ideal exactly when `n ≤ δ(L/K)`. -/
@[simp]
theorem pow_dvd_discriminantIdeal_iff_le_discriminantExponent {n : ℕ} :
    𝓂[K] ^ n ∣ discriminantIdeal K L ↔ n ≤ discriminantExponent K L :=
  (FiniteMultiplicity.of_prime_left
    (Ideal.prime_of_isPrime (IsDiscreteValuationRing.not_a_field 𝒪[K]) inferInstance)
    (discriminantIdeal_ne_bot (K := K) (L := L))).pow_dvd_iff_le_multiplicity.trans
      (by rw [← discriminantExponent_def])

/-- **The first half of Dedekind's different theorem, for the discriminant**: the discriminant
exponent is at least `e(L/K) - 1`, by `ramificationIndex_sub_one_le_differentExponent` and
`inertiaDegree K L > 0`. -/
theorem ramificationIndex_sub_one_le_discriminantExponent :
    ramificationIndex K L - 1 ≤ discriminantExponent K L := by
  rw [discriminantExponent_eq_inertiaDegree_mul_differentExponent, Nat.mul_comm]
  exact (ramificationIndex_sub_one_le_differentExponent K L).trans
    (Nat.le_mul_of_pos_right _ (inertiaDegree_pos (K := K) (L := L)))

/-- **Dedekind's different theorem for the discriminant in the tame case**:
`δ(L/K) = f(L/K) · (e(L/K) - 1)` exactly when `L/K` is tamely ramified, by
`TauCeti.differentExponent_eq_ramificationIndex_sub_one_iff`. -/
@[simp]
theorem discriminantExponent_eq_inertiaDegree_mul_ramificationIndex_sub_one_iff :
    discriminantExponent K L = inertiaDegree K L * (ramificationIndex K L - 1) ↔
      IsTamelyRamified K L := by
  constructor
  · intro h
    have h1 : inertiaDegree K L * differentExponent K L
        = inertiaDegree K L * (ramificationIndex K L - 1) := by
      rw [← h, discriminantExponent_eq_inertiaDegree_mul_differentExponent]
    exact (differentExponent_eq_ramificationIndex_sub_one_iff (K := K) (L := L)).1
      (Nat.mul_left_cancel (inertiaDegree_pos (K := K) (L := L)) h1)
  · intro h
    rw [discriminantExponent_eq_inertiaDegree_mul_differentExponent,
      (differentExponent_eq_ramificationIndex_sub_one_iff (K := K) (L := L)).2 h]

/-- **The local discriminant exponent vanishes exactly for unramified extensions**:
`δ(L/K) = 0` if and only if `L/K` is unramified, by
`TauCeti.differentExponent_eq_zero_iff` and `inertiaDegree K L > 0`. -/
@[simp]
theorem discriminantExponent_eq_zero_iff :
    discriminantExponent K L = 0 ↔ IsUnramified K L := by
  constructor
  · intro h
    have h' : inertiaDegree K L * differentExponent K L = 0 := by
      rw [← discriminantExponent_eq_inertiaDegree_mul_differentExponent, h]
    rw [Nat.mul_eq_zero] at h'
    rcases h' with hf | hd
    · exact absurd hf (Nat.ne_of_gt (inertiaDegree_pos (K := K) (L := L)))
    · exact (differentExponent_eq_zero_iff (K := K) (L := L)).1 hd
  · intro h
    rw [discriminantExponent_eq_inertiaDegree_mul_differentExponent,
      (differentExponent_eq_zero_iff (K := K) (L := L)).2 h, Nat.mul_zero]

/-- **The discriminant of a local extension is trivial exactly when the extension is
unramified**: `𝔩(L/K) = 𝒪[K]` if and only if `L/K` is unramified. -/
@[simp]
theorem discriminantIdeal_eq_top_iff : discriminantIdeal K L = ⊤ ↔ IsUnramified K L := by
  rw [← discriminantExponent_eq_zero_iff, discriminantIdeal_eq_maximalIdeal_pow]
  refine ⟨fun h ↦ ?_, fun h ↦ by rw [h, pow_zero, Ideal.one_eq_top]⟩
  by_contra hd
  exact (maximalIdeal.isMaximal 𝒪[K]).ne_top (eq_top_mono (Ideal.pow_le_self hd) h)

end TauCeti
