/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.LocalField.ProP.Rank
public import TauCeti.Topology.Algebra.Group.Profinite.Generation

/-!
# The exact generator rank of a local absolute Galois group

Let `K` be a finite extension of `ℚ_p` and `N = [K : ℚ_p]`. This file proves that the absolute
Galois group `G_K` needs at least `N + 2` topological generators:

```text
N + 2 ≤ d(G_K).
```

When `μ_p ⊆ K` this is visible on the maximal pro-`p` quotient, whose generator rank is exactly
`N + 2`. When `μ_p ⊄ K` the maximal pro-`p` quotient only needs `N + 1` generators, and the bound
comes from the open subgroup `G_L` for `L = K(μ_p)`. With `m = [L : K]`, the field `L` contains
`μ_p`, so `d(G_L) ≥ d(G_L(p)) = [L : ℚ_p] + 2 = mN + 2`, while Schreier's bound for an open
subgroup of index `m` gives `d(G_L) ≤ 1 + m (d(G_K) - 1)`. Hence `m (d(G_K) - 1) > mN`, that is
`d(G_K) ≥ N + 2`. The argument with `L = K(μ_p)` covers both cases at once, with `m = 1` when
`μ_p ⊆ K`.

In the opposite direction, the file supplies the compactness passage from the finite quotients
`G_K ⧸ U` to the profinite group `G_K` (Step 5b–6 of the proof of NSW (7.4.1)), taking the
finite-level statement — every finite quotient is generated by an `(N + 2)`-tuple — as a
hypothesis:

* for each open normal `U ≤ G_K`, `TauCeti.generatingTuples p K U` is the closed set of
  `(N + 2)`-tuples of `G_K` whose images generate `G_K ⧸ U`;
* if every finite quotient `G_K ⧸ U` is generated by an `(N + 2)`-tuple, compactness of
  `G_K ^ (N + 2)` gives one tuple lying in every `generatingTuples p K U`;
* that common tuple generates `G_K` topologically, so `d(G_K) = N + 2`
  (`TauCeti.rank_absoluteGaloisGroup_of_forall_generating_tuple_quotient`).

## Main definitions and results

* `TauCeti.finrank_add_two_le_card_of_topologicalClosure_closure_eq_top_absoluteGaloisGroup`:
  every finite subset of `G_K` generating a dense subgroup has at least `[K : ℚ_p] + 2` elements.
* `TauCeti.le_topologicalGeneratorRankNat_absoluteGaloisGroup`: `[K : ℚ_p] + 2 ≤ d(G_K)`.
* `TauCeti.generatingTuples`: the closed set of `(N + 2)`-tuples generating `G_K ⧸ U`, with
  `isClosed_generatingTuples`, `generatingTuples_antitone`, and
  `generatingTuples_nonempty_of_exists_generating_tuple_quotient`.
* `TauCeti.not_forall_exists_finset_card_generating_quotient`: the `Finset`-cardinality form of
  the finite-level generation statement is false (`U = G_K` has trivial quotient); the statement
  must be about tuples, in which repetitions are allowed.
* `TauCeti.exists_tuple_topologicalClosure_closure_eq_top_of_forall_generating_tuple_quotient`:
  the compactness step — one tuple generating every finite quotient generates `G_K` itself.
* `TauCeti.isTopologicallyFinitelyGenerated_absoluteGaloisGroup_of_forall_generating_tuple_quotient`
  and `TauCeti.rank_absoluteGaloisGroup_of_forall_generating_tuple_quotient`: from `(N + 2)`-tuple
  generation of every finite quotient, `G_K` is topologically finitely generated of exact
  generator rank `[K : ℚ_p] + 2`.

## References

* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, 2nd ed., (7.4.1) and
  (7.5.11).
* M. Jarden and A. Shusterman, *The absolute Galois group of a `p`-adic field*, Theorem 2.1.
-/

public section

namespace TauCeti

universe u

variable (p : ℕ) [Fact p.Prime] (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [Algebra ℚ_[p] K] [ValuativeExtension ℚ_[p] K]

/-- **The lower bound for the generator rank of a local absolute Galois group.** For a finite
extension `K` of `ℚ_p`, the absolute Galois group `G_K` needs at least `[K : ℚ_p] + 2` topological
generators. The finite-generation witness is an argument, so that the natural-valued rank is only
read on a topologically finitely generated group. -/
theorem le_topologicalGeneratorRankNat_absoluteGaloisGroup
    (hG : IsTopologicallyFinitelyGenerated (Field.absoluteGaloisGroup K)) :
    Module.finrank ℚ_[p] K + 2 ≤
      topologicalGeneratorRankNat (Field.absoluteGaloisGroup K) hG := by
  -- The field `L = K(μ_p)`, with the local-field structure extending that of `K`.
  have : CharZero K := charZero_of_injective_algebraMap (algebraMap ℚ_[p] K).injective
  let L := CyclotomicField p K
  have : FiniteDimensional K L := IsCyclotomicExtension.finiteDimensional {p} K L
  let := finiteExtensionValuativeRel K L
  let := finiteExtensionNormedFieldTopology K L
  have := finiteExtension_isNonarchimedeanLocalField K L
  have := finiteExtension_valuativeExtension K L
  have := ValuativeExtension.trans ℚ_[p] K L
  have hmu : ∃ ζ : L, IsPrimitiveRoot ζ p :=
    ⟨IsCyclotomicExtension.zeta p K L, IsCyclotomicExtension.zeta_spec p K L⟩
  -- `G_L` is the open subgroup `U` of `G_K` of index `m = [L : K]`.
  let U := galoisSubgroup K L IsSepClosed.lift
  have hG' := (isTopologicallyFinitelyGenerated_congr (absoluteGaloisGroupRestrictEquiv K)).mp hG
  have hU := hG'.of_openSubgroup_of_finiteIndex U
  let e : Field.absoluteGaloisGroup L ≃ₜ* U.toSubgroup :=
    (absoluteGaloisGroupRestrictEquiv L).trans (galoisSubgroupEquiv K L IsSepClosed.lift)
  have hL := (isTopologicallyFinitelyGenerated_congr e).mpr hU
  -- Schreier: `d(G_L) ≤ 1 + m (d(G_K) - 1)`.
  have hschreier : topologicalGeneratorRankNat (Field.absoluteGaloisGroup L) hL ≤
      1 + Module.finrank K L *
        (topologicalGeneratorRankNat (Field.absoluteGaloisGroup K) hG - 1) := by
    rw [topologicalGeneratorRankNat_congr e hL, topologicalGeneratorRankNat_congr
      (absoluteGaloisGroupRestrictEquiv K) hG, ← galoisSubgroup_index K L IsSepClosed.lift]
    exact topologicalGeneratorRankNat_le_of_openSubgroup_of_finiteIndex hG' U
  -- `d(G_L(p)) = [L : ℚ_p] + 2 = Nm + 2` and `d(G_L(p)) ≤ d(G_L)`.
  have hpro := topologicalGeneratorRankNat_le_of_surjective
    (absoluteGaloisGroupProPQuotientMap p L).toMonoidHom
    (absoluteGaloisGroupProPQuotientMap p L).continuous QuotientGroup.mk_surjective hL
  rw [topologicalGeneratorRankNat_absoluteGaloisGroupProP_of_mu p L _ hmu,
    ← Module.finrank_mul_finrank ℚ_[p] K L] at hpro
  -- `Nm + 2 ≤ 1 + m (d(G_K) - 1)` forces `N + 2 ≤ d(G_K)`.
  by_contra! hlt
  have hsub : topologicalGeneratorRankNat (Field.absoluteGaloisGroup K) hG - 1 ≤
      Module.finrank ℚ_[p] K := by
    omega
  have := Nat.mul_le_mul_left (Module.finrank K L) hsub
  linarith [hpro.trans hschreier]

/-- **Every finite set topologically generating a local absolute Galois group has at least
`[K : ℚ_p] + 2` elements.** This is the lower half of the exact generator rank of `G_K`, stated
without assuming topological finite generation: a finite generating set is itself a witness. -/
theorem finrank_add_two_le_card_of_topologicalClosure_closure_eq_top_absoluteGaloisGroup
    (s : Finset (Field.absoluteGaloisGroup K))
    (hs : (Subgroup.closure (s : Set (Field.absoluteGaloisGroup K))).topologicalClosure = ⊤) :
    Module.finrank ℚ_[p] K + 2 ≤ s.card :=
  (le_topologicalGeneratorRankNat_absoluteGaloisGroup p K
    (isTopologicallyFinitelyGenerated_iff.mpr ⟨s, hs⟩)).trans (topologicalGeneratorRankNat_le _ hs)

/-! ### Generating tuples and the passage from finite quotients to `G_K` -/

omit [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [ValuativeExtension ℚ_[p] K] in
/-- **The finite-level generation statement with a `Finset` of cardinality `N + 2` is false**:
`U = G_K` is open and normal, its quotient is trivial, and a `Finset` in a subsingleton has at
most one element while `N + 2 ≥ 2`. Finite-level generation must therefore be stated for tuples
`Fin (N + 2) → G_K ⧸ U`, in which repetitions are allowed. -/
theorem not_forall_exists_finset_card_generating_quotient :
    ¬ ∀ U : OpenNormalSubgroup (Field.absoluteGaloisGroup K),
        ∃ s : Finset (Field.absoluteGaloisGroup K ⧸ U.toSubgroup),
          s.card = Module.finrank ℚ_[p] K + 2 ∧
            Subgroup.closure (s : Set (Field.absoluteGaloisGroup K ⧸ U.toSubgroup)) = ⊤ := by
  intro h
  obtain ⟨s, hs, -⟩ := h ⟨⟨⊤, isOpen_univ⟩, inferInstance⟩
  have : s.card ≤ 1 := @Finset.card_le_one_of_subsingleton _
    QuotientGroup.subsingleton_quotient_top s
  omega

/-- For an open normal subgroup `U` of `G_K`, the set `X_U` of `([K : ℚ_p] + 2)`-tuples of elements
of `G_K` whose images generate `G_K ⧸ U`. -/
def generatingTuples (U : OpenNormalSubgroup (Field.absoluteGaloisGroup K)) :
    Set (Fin (Module.finrank ℚ_[p] K + 2) → Field.absoluteGaloisGroup K) :=
  {x | Subgroup.closure (Set.range fun i ↦
    (QuotientGroup.mk (x i) : Field.absoluteGaloisGroup K ⧸ U.toSubgroup)) = ⊤}

omit [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [ValuativeExtension ℚ_[p] K] in
/-- Membership in `generatingTuples p K U` means that the image tuple generates `G_K ⧸ U`. -/
@[simp]
theorem mem_generatingTuples_iff {U : OpenNormalSubgroup (Field.absoluteGaloisGroup K)}
    {x : Fin (Module.finrank ℚ_[p] K + 2) → Field.absoluteGaloisGroup K} :
    x ∈ generatingTuples p K U ↔
      Subgroup.closure (Set.range fun i ↦
        (QuotientGroup.mk (x i) : Field.absoluteGaloisGroup K ⧸ U.toSubgroup)) = ⊤ :=
  Iff.rfl

omit [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [ValuativeExtension ℚ_[p] K] in
/-- **The set of generating tuples at level `U` is closed**: membership depends only on the image
in the discrete quotient `(G_K ⧸ U) ^ (N + 2)`, and the coordinatewise quotient map is
continuous. -/
theorem isClosed_generatingTuples (U : OpenNormalSubgroup (Field.absoluteGaloisGroup K)) :
    IsClosed (generatingTuples p K U) := by
  have hcont : Continuous (fun x : Fin (Module.finrank ℚ_[p] K + 2) → Field.absoluteGaloisGroup K ↦
      fun i ↦ (QuotientGroup.mk (x i) : Field.absoluteGaloisGroup K ⧸ U.toSubgroup)) :=
    continuous_pi fun i ↦
      (QuotientGroup.continuous_mk (N := U.toSubgroup)).comp (continuous_apply i)
  exact (isClosed_discrete
    {f : Fin (Module.finrank ℚ_[p] K + 2) → Field.absoluteGaloisGroup K ⧸ U.toSubgroup |
      Subgroup.closure (Set.range f) = ⊤}).preimage hcont

omit [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [ValuativeExtension ℚ_[p] K] in
/-- **A tuple generating `G_K ⧸ U` lifts to `generatingTuples p K U`.** -/
theorem generatingTuples_nonempty_of_exists_generating_tuple_quotient
    (U : OpenNormalSubgroup (Field.absoluteGaloisGroup K))
    (h : ∃ f : Fin (Module.finrank ℚ_[p] K + 2) → Field.absoluteGaloisGroup K ⧸ U.toSubgroup,
      Subgroup.closure (Set.range f) = ⊤) :
    (generatingTuples p K U).Nonempty := by
  obtain ⟨f, hf⟩ := h
  choose x hx using fun i ↦ QuotientGroup.mk_surjective (s := U.toSubgroup) (f i)
  refine ⟨x, ?_⟩
  rw [mem_generatingTuples_iff, funext hx]
  exact hf

omit [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [ValuativeExtension ℚ_[p] K] in
/-- **A tuple generating a finer quotient generates a coarser one**: `X_{U'} ⊆ X_U` for
`U' ≤ U`. -/
theorem generatingTuples_antitone {U U' : OpenNormalSubgroup (Field.absoluteGaloisGroup K)}
    (h : U' ≤ U) :
    generatingTuples p K U' ⊆ generatingTuples p K U := by
  intro x hx
  have hmap : (Subgroup.closure (Set.range fun i ↦
      (QuotientGroup.mk (x i) : Field.absoluteGaloisGroup K ⧸ U'.toSubgroup))).map
      (QuotientGroup.mapOfLE h) = ⊤ := by
    rw [hx]
    exact Subgroup.map_top_of_surjective _ (QuotientGroup.mapOfLE_surjective h)
  rw [MonoidHom.map_closure, ← Set.range_comp] at hmap
  simpa only [mem_generatingTuples_iff, Function.comp_def, QuotientGroup.mapOfLE_mk] using hmap

omit [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [ValuativeExtension ℚ_[p] K] in
/-- **Compactness for generating tuples.** If every finite quotient `G_K ⧸ U` is generated by an
`([K : ℚ_p] + 2)`-tuple, the closed sets `generatingTuples p K U` over the open normal `U` have
nonempty intersection: finitely many open normal subgroups intersect in another open normal
subgroup, and `G_K ^ (N + 2)` is compact. One tuple then generates every finite quotient at
once. -/
theorem exists_mem_generatingTuples_of_forall_generating_tuple_quotient
    (h : ∀ U : OpenNormalSubgroup (Field.absoluteGaloisGroup K),
        ∃ f : Fin (Module.finrank ℚ_[p] K + 2) → Field.absoluteGaloisGroup K ⧸ U.toSubgroup,
          Subgroup.closure (Set.range f) = ⊤) :
    ∃ x : Fin (Module.finrank ℚ_[p] K + 2) → Field.absoluteGaloisGroup K,
      ∀ U : OpenNormalSubgroup (Field.absoluteGaloisGroup K), x ∈ generatingTuples p K U := by
  have hne : Nonempty (OpenNormalSubgroup (Field.absoluteGaloisGroup K)) :=
    ⟨{ toOpenSubgroup := ⟨⊤, isOpen_univ⟩ }⟩
  have hdir : Directed (· ⊇ ·) (fun U : OpenNormalSubgroup (Field.absoluteGaloisGroup K) ↦
      generatingTuples p K U) := fun U V ↦
    ⟨U ⊓ V, generatingTuples_antitone p K inf_le_left,
      generatingTuples_antitone p K inf_le_right⟩
  obtain ⟨x, hx⟩ := IsCompact.nonempty_iInter_of_directed_nonempty_isCompact_isClosed
    (fun U : OpenNormalSubgroup (Field.absoluteGaloisGroup K) ↦ generatingTuples p K U) hdir
    (fun U ↦ generatingTuples_nonempty_of_exists_generating_tuple_quotient p K U (h U))
    (fun U ↦ (isClosed_generatingTuples p K U).isCompact)
    (fun U ↦ isClosed_generatingTuples p K U)
  exact ⟨x, fun U ↦ Set.mem_iInter.mp hx U⟩

omit [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [ValuativeExtension ℚ_[p] K] in
/-- **From finite-level tuple generation to topological generation of `G_K`.** A tuple lying in
every `generatingTuples p K U` generates every finite quotient, hence generates `G_K`
topologically: a closed subgroup mapping onto every quotient by an open normal subgroup is
everything. -/
theorem exists_tuple_topologicalClosure_closure_eq_top_of_forall_generating_tuple_quotient
    (h : ∀ U : OpenNormalSubgroup (Field.absoluteGaloisGroup K),
        ∃ f : Fin (Module.finrank ℚ_[p] K + 2) → Field.absoluteGaloisGroup K ⧸ U.toSubgroup,
          Subgroup.closure (Set.range f) = ⊤) :
    ∃ x : Fin (Module.finrank ℚ_[p] K + 2) → Field.absoluteGaloisGroup K,
      (Subgroup.closure (Set.range x)).topologicalClosure = ⊤ := by
  obtain ⟨x, hx⟩ := exists_mem_generatingTuples_of_forall_generating_tuple_quotient p K h
  refine ⟨x, topologicalClosure_closure_eq_top_iff.mpr fun U ↦ ?_⟩
  have hxU := (mem_generatingTuples_iff p K).1 (hx U)
  calc Subgroup.closure ((QuotientGroup.mk' U.toSubgroup) '' Set.range x) = ⊤ := by
        rw [← Set.range_comp' (fun g : Field.absoluteGaloisGroup K ↦
          ((QuotientGroup.mk' U.toSubgroup g : Field.absoluteGaloisGroup K ⧸ U.toSubgroup) :
            Field.absoluteGaloisGroup K ⧸ U.toSubgroup)) x]
        exact hxU

omit [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [ValuativeExtension ℚ_[p] K] in
/-- If every finite quotient of `G_K` is generated by an `([K : ℚ_p] + 2)`-tuple, then `G_K` is
topologically finitely generated. -/
theorem isTopologicallyFinitelyGenerated_absoluteGaloisGroup_of_forall_generating_tuple_quotient
    (h : ∀ U : OpenNormalSubgroup (Field.absoluteGaloisGroup K),
        ∃ f : Fin (Module.finrank ℚ_[p] K + 2) → Field.absoluteGaloisGroup K ⧸ U.toSubgroup,
          Subgroup.closure (Set.range f) = ⊤) :
    IsTopologicallyFinitelyGenerated (Field.absoluteGaloisGroup K) := by
  classical
  obtain ⟨x, hx⟩ :=
    exists_tuple_topologicalClosure_closure_eq_top_of_forall_generating_tuple_quotient p K h
  refine isTopologicallyFinitelyGenerated_iff.mpr ⟨Finset.univ.image x, ?_⟩
  rwa [Finset.coe_image, Finset.coe_univ, Set.image_univ]

omit [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [ValuativeExtension ℚ_[p] K] in
/-- **The upper bound `d(G_K) ≤ [K : ℚ_p] + 2`**, from `([K : ℚ_p] + 2)`-tuple generation of
every finite quotient. -/
theorem topologicalGeneratorRankNat_absoluteGaloisGroup_le_of_forall_generating_tuple_quotient
    (h : ∀ U : OpenNormalSubgroup (Field.absoluteGaloisGroup K),
        ∃ f : Fin (Module.finrank ℚ_[p] K + 2) → Field.absoluteGaloisGroup K ⧸ U.toSubgroup,
          Subgroup.closure (Set.range f) = ⊤) :
    topologicalGeneratorRankNat (Field.absoluteGaloisGroup K)
      (isTopologicallyFinitelyGenerated_absoluteGaloisGroup_of_forall_generating_tuple_quotient
        p K h) ≤ Module.finrank ℚ_[p] K + 2 := by
  classical
  obtain ⟨x, hx⟩ :=
    exists_tuple_topologicalClosure_closure_eq_top_of_forall_generating_tuple_quotient p K h
  have hx' : (Subgroup.closure ((Finset.univ.image x : Finset _) :
      Set (Field.absoluteGaloisGroup K))).topologicalClosure = ⊤ := by
    rwa [Finset.coe_image, Finset.coe_univ, Set.image_univ]
  exact (topologicalGeneratorRankNat_le _ hx').trans
    (Finset.card_image_le.trans_eq (by simp))

/-- **The exact generator rank of `G_K` from finite-level tuple generation**: if every finite
quotient `G_K ⧸ U` is generated by an `([K : ℚ_p] + 2)`-tuple, then
`d(G_K) = [K : ℚ_p] + 2`. -/
theorem topologicalGeneratorRankNat_absoluteGaloisGroup_eq_of_forall_generating_tuple_quotient
    (h : ∀ U : OpenNormalSubgroup (Field.absoluteGaloisGroup K),
        ∃ f : Fin (Module.finrank ℚ_[p] K + 2) → Field.absoluteGaloisGroup K ⧸ U.toSubgroup,
          Subgroup.closure (Set.range f) = ⊤) :
    topologicalGeneratorRankNat (Field.absoluteGaloisGroup K)
      (isTopologicallyFinitelyGenerated_absoluteGaloisGroup_of_forall_generating_tuple_quotient
        p K h) = Module.finrank ℚ_[p] K + 2 :=
  le_antisymm
    (topologicalGeneratorRankNat_absoluteGaloisGroup_le_of_forall_generating_tuple_quotient
      p K h)
    (le_topologicalGeneratorRankNat_absoluteGaloisGroup p K _)

/-- **The exact generator rank of `G_K` in `IsLeast` form**, from `([K : ℚ_p] + 2)`-tuple
generation of every finite quotient: `[K : ℚ_p] + 2` is the least cardinality of a finite subset
of `G_K` generating a dense subgroup. -/
theorem rank_absoluteGaloisGroup_of_forall_generating_tuple_quotient
    (h : ∀ U : OpenNormalSubgroup (Field.absoluteGaloisGroup K),
        ∃ f : Fin (Module.finrank ℚ_[p] K + 2) → Field.absoluteGaloisGroup K ⧸ U.toSubgroup,
          Subgroup.closure (Set.range f) = ⊤) :
    IsLeast
      {m : ℕ | ∃ s : Finset (Field.absoluteGaloisGroup K), s.card = m ∧
        (Subgroup.closure (s : Set (Field.absoluteGaloisGroup K))).topologicalClosure = ⊤}
      (Module.finrank ℚ_[p] K + 2) := by
  have hfg :
      IsTopologicallyFinitelyGenerated (Field.absoluteGaloisGroup K) :=
    isTopologicallyFinitelyGenerated_absoluteGaloisGroup_of_forall_generating_tuple_quotient
      p K h
  have hrank :
      topologicalGeneratorRankNat (Field.absoluteGaloisGroup K) hfg =
        Module.finrank ℚ_[p] K + 2 :=
    topologicalGeneratorRankNat_absoluteGaloisGroup_eq_of_forall_generating_tuple_quotient
      p K h
  refine ⟨?_, fun m hm ↦ ?_⟩
  · rw [← hrank]
    exact exists_finset_card_eq_topologicalGeneratorRankNat hfg
  · obtain ⟨s, rfl, hgen⟩ := hm
    exact finrank_add_two_le_card_of_topologicalClosure_closure_eq_top_absoluteGaloisGroup p K s
      hgen

end TauCeti
