/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.LocalField.IntegerRing
public import TauCeti.RingTheory.DiscreteValuationRing.Monogenic

/-!
# Integral generators of finite local-field extensions

The integer ring of a finite extension of nonarchimedean local fields is generated by one
integral element over the base integer ring. The same element generates the fraction-field
extension, and its powers form an integral basis. These forms let ramification and different
computations use a single generator without imposing a separate monogenicity hypothesis.

The proof specializes the discrete-valuation-ring monogenicity theorem of
`TauCeti.IsDiscreteValuationRing.exists_adjoin_eq_top`. The residue extension is separable because
the residue field of a local field is finite and hence perfect.

## References

* J.-P. Serre, *Corps Locaux*, Chapter III, §6, Proposition 12.
-/

public section
noncomputable section

open ValuativeRel IsLocalRing

namespace TauCeti

variable (K L : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [Field L] [ValuativeRel L] [TopologicalSpace L]
  [IsNonarchimedeanLocalField L] [Algebra K L] [ValuativeExtension K L]

/-- The integer ring of a finite extension of nonarchimedean local fields is generated as an
algebra over the base integer ring by one element. -/
theorem exists_integerRing_adjoin_eq_top :
    ∃ x : 𝒪[L], Algebra.adjoin 𝒪[K] {x} = ⊤ := by
  exact IsDiscreteValuationRing.exists_adjoin_eq_top (R := 𝒪[K]) (S := 𝒪[L])

/-- The integer ring of a finite local-field extension has an integral power basis whose
generator also generates the field extension. Its length is `[L : K]`. -/
theorem exists_integerRing_powerBasis_and_field_adjoin_eq_top :
    ∃ pb : PowerBasis 𝒪[K] 𝒪[L],
      IntermediateField.adjoin K {((pb.gen : 𝒪[L]) : L)} = ⊤ ∧
      pb.dim = Module.finrank K L := by
  obtain ⟨pb, hpb⟩ := IsDiscreteValuationRing.exists_powerBasis_intermediateField_adjoin_eq_top
    (R := 𝒪[K]) (S := 𝒪[L]) K L
  refine ⟨pb, hpb, ?_⟩
  rw [← pb.finrank, finrank_integerRing K L]

end TauCeti
