/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.LocalField.Unramified.Inertia
public import TauCeti.NumberTheory.LocalField.Uniformizer
import TauCeti.Algebra.CharP.LocalRing
import TauCeti.NumberTheory.LocalField.UnitsDecomposition

/-!
# The maximal tamely ramified extension and wild inertia

Let `K` be a nonarchimedean local field with residue field `𝓀[K]` of characteristic `p` and
cardinality `q`, and let `Ω` be an extension of `K`. This file defines the **maximal tamely
ramified extension**

`TauCeti.maximalTameExtension K Ω`,

the intermediate field `K^{t}` of `Ω / K` generated by the `m`-th roots of the nonzero elements of
`K`, for all `m` prime to `p`. It contains the maximal unramified extension `K^{ur}`, whose
generators are roots of unity of order prime to `p`, and it is Galois over `K` when `Ω` is
separably closed. For any uniformizer `π` of `K` it is the familiar

`K^{t} = K^{ur}(π^{1/m} : p ∤ m) = ⋃_{p ∤ m} K^{ur}(π^{1/m})`,

since for a unit `u` of `K` and `p ∤ m` the roots of `X^m − u` are unramified: `u` is a root of
unity of order prime to `p` times a principal unit, and principal units are `m`-th powers in `K`.

The **wild inertia subgroup** `P_K = TauCeti.wildInertiaSubgroup K` of the absolute Galois group
`G_K = Field.absoluteGaloisGroup K` is the fixing subgroup of `K^{t}` inside `K^{alg}`, which
`IntermediateField.fixingSubgroupEquiv` identifies with `Gal(K^{alg}/K^{t})`. It is a closed normal
subgroup of `G_K`, contained in the inertia subgroup `I_K = TauCeti.inertiaSubgroup K`.

## Main definitions

* `TauCeti.maximalTameExtension K Ω`: the maximal tamely ramified extension `K^{t}` of `K` in `Ω`.
* `TauCeti.wildInertiaSubgroup K`: the wild inertia subgroup `P_K` of `G_K`.

## Main results

* `TauCeti.maximalUnramifiedExtension_le_maximalTameExtension`: `K^{ur} ≤ K^{t}`.
* `TauCeti.isGalois_maximalTameExtension`: for `Ω` separably closed, `K^{t}` is Galois over `K`.
* `TauCeti.maximalTameExtension_eq_sup_adjoin`: for `Ω` separably closed and any uniformizer `π`,
  `K^{t} = K^{ur}(π^{1/m} : p ∤ m)`.
* `TauCeti.isClosed_wildInertiaSubgroup`, `TauCeti.wildInertiaSubgroup_normal`: `P_K` is closed and
  normal in `G_K`.
* `TauCeti.wildInertiaSubgroup_le_inertiaSubgroup`: `P_K ≤ I_K`.
* `TauCeti.mem_wildInertiaSubgroup_iff_of_isUniformizer`: `σ ∈ P_K` exactly when `σ ∈ I_K` and `σ`
  fixes every `m`-th root of a given uniformizer, for `p ∤ m`.

## References

* [J.-P. Serre, *Corps Locaux*][serre1968], Chapter IV, §2.
* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, Chapter VII, §5.
-/

public section

noncomputable section

open ValuativeRel Polynomial IntermediateField

namespace TauCeti

variable {K : Type*} [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-! ### The maximal tamely ramified extension -/

variable (K) (Ω : Type*) [Field Ω] [Algebra K Ω]

/-- **The maximal tamely ramified extension** `K^{t}` of a nonarchimedean local field `K` inside an
extension `Ω`: the intermediate field generated by the `m`-th roots of the nonzero elements of `K`,
for all `m` not divisible by the residue characteristic `p`. It contains the maximal unramified
extension, and for a uniformizer `π` of `K` and `Ω` separably closed it is `K^{ur}(π^{1/m} : p ∤ m)`
by `TauCeti.maximalTameExtension_eq_sup_adjoin`. -/
def maximalTameExtension : IntermediateField K Ω :=
  adjoin K {x : Ω | ∃ m : ℕ, ¬ ringChar 𝓀[K] ∣ m ∧ ∃ a : Kˣ, x ^ m = algebraMap K Ω a}

/-- The maximal tamely ramified extension is generated by the `m`-th roots of the nonzero elements
of `K`, for `m` prime to the residue characteristic. -/
theorem maximalTameExtension_def :
    maximalTameExtension K Ω =
      adjoin K {x : Ω | ∃ m : ℕ, ¬ ringChar 𝓀[K] ∣ m ∧ ∃ a : Kˣ, x ^ m = algebraMap K Ω a} :=
  -- `(rfl)`, not `rfl`: keep the body opaque while exporting this equation across modules.
  (rfl)

variable {K Ω} in
/-- An `m`-th root of a nonzero element of `K` lies in the maximal tamely ramified extension, when
the residue characteristic does not divide `m`. -/
theorem mem_maximalTameExtension_of_pow_eq {m : ℕ} (hm : ¬ ringChar 𝓀[K] ∣ m) (a : Kˣ) {x : Ω}
    (hx : x ^ m = algebraMap K Ω a) : x ∈ maximalTameExtension K Ω :=
  subset_adjoin _ _ ⟨m, hm, a, hx⟩

/-- **The maximal unramified extension is tamely ramified**: `K^{ur} ≤ K^{t}`, since `K^{ur}` is
generated by roots of unity of order `q ^ f − 1`, which is prime to the residue characteristic. -/
theorem maximalUnramifiedExtension_le_maximalTameExtension :
    maximalUnramifiedExtension K Ω ≤ maximalTameExtension K Ω := by
  rw [maximalUnramifiedExtension_eq_adjoin, adjoin_le_iff]
  rintro x ⟨f, hf, hx⟩
  rcases eq_or_ne x 0 with rfl | hx0
  · exact zero_mem _
  have hq := IsLocalRing.isUnit_natCast_iff_not_dvd.1 (isUnit_natCast_natCard_pow_sub_one K hf)
  refine mem_maximalTameExtension_of_pow_eq hq 1 ?_
  -- `x ^ (q ^ f - 1) = x ^ q ^ f / x = 1`.
  calc x ^ (Nat.card 𝓀[K] ^ f - 1) = x ^ Nat.card 𝓀[K] ^ f * (x ^ 1)⁻¹ :=
        pow_sub₀ x hx0 (Nat.one_le_iff_ne_zero.2 (pow_ne_zero _ Nat.card_pos.ne'))
    _ = algebraMap K Ω (1 : Kˣ) := by simp [hx, hx0]

/-- The maximal tamely ramified extension is the compositum of the fields generated by the roots of
the polynomials `X^m − a`, for `a ∈ Kˣ` and `m` prime to the residue characteristic. -/
private theorem maximalTameExtension_eq_iSup :
    maximalTameExtension K Ω =
      ⨆ i : {m : ℕ // ¬ ringChar 𝓀[K] ∣ m} × Kˣ,
        adjoin K ((X ^ (i.1 : ℕ) - C (i.2 : K)).rootSet Ω) := by
  rw [maximalTameExtension_def, ← adjoin_iUnion]
  congr 1
  ext x
  simp only [Set.mem_ofPred_eq, Set.mem_iUnion, Prod.exists, Subtype.exists, mem_rootSet, map_sub,
    map_pow, aeval_X, aeval_C, sub_eq_zero, exists_prop]
  refine ⟨fun ⟨m, hm, a, hx⟩ ↦ ⟨m, hm, a, X_pow_sub_C_ne_zero ?_ _, hx⟩,
    fun ⟨m, hm, a, _, hx⟩ ↦ ⟨m, hm, a, hx⟩⟩
  exact Nat.pos_of_ne_zero fun h ↦ hm (h ▸ dvd_zero _)

/-- **The maximal tamely ramified extension is Galois** over `K`, when `Ω` is separably closed: it
is the compositum of the splitting fields of the separable polynomials `X^m − a`, `a ∈ Kˣ`,
`p ∤ m`. -/
instance isGalois_maximalTameExtension [IsSepClosed Ω] :
    IsGalois K (maximalTameExtension K Ω) := by
  rw [maximalTameExtension_eq_iSup]
  have (i : {m : ℕ // ¬ ringChar 𝓀[K] ∣ m} × Kˣ) :
      IsGalois K (adjoin K ((X ^ (i.1 : ℕ) - C (i.2 : K)).rootSet Ω)) := by
    have hsep : (X ^ (i.1 : ℕ) - C (i.2 : K)).Separable := separable_X_pow_sub_C _
      (natCast_ne_zero_of_isUnit (IsLocalRing.isUnit_natCast_iff_not_dvd.2 i.1.2)) i.2.ne_zero
    have := adjoin_rootSet_isSplittingField
      (IsSepClosed.splits_codomain (f := algebraMap K Ω) _ hsep)
    exact IsGalois.of_separable_splitting_field hsep
  exact ⟨⟩

variable {K Ω} in
/-- **The maximal tamely ramified extension, through a uniformizer.** For `Ω` separably closed and
any uniformizer `π` of `K`, `K^{t}` is generated over the maximal unramified extension by the
`m`-th roots of `π`, for `m` prime to the residue characteristic:
`K^{t} = K^{ur}(π^{1/m} : p ∤ m)`. -/
theorem maximalTameExtension_eq_sup_adjoin [IsSepClosed Ω] {π : Kˣ} (hπ : IsUniformizer K π) :
    maximalTameExtension K Ω = maximalUnramifiedExtension K Ω ⊔
      adjoin K {x : Ω | ∃ m : ℕ, ¬ ringChar 𝓀[K] ∣ m ∧ x ^ m = algebraMap K Ω π} := by
  set E := maximalUnramifiedExtension K Ω ⊔
    adjoin K {x : Ω | ∃ m : ℕ, ¬ ringChar 𝓀[K] ∣ m ∧ x ^ m = algebraMap K Ω π}
  refine le_antisymm ?_ (sup_le (maximalUnramifiedExtension_le_maximalTameExtension K Ω)
    (adjoin_le_iff.2 fun x ⟨m, hm, hx⟩ ↦ mem_maximalTameExtension_of_pow_eq hm π hx))
  rw [maximalTameExtension_def, adjoin_le_iff]
  rintro x ⟨m, hm, a, hx⟩
  set A := algebraMap K Ω
  -- An `m`-th root `y` of `π` lies in `E`.
  have : NeZero (m : Ω) := ⟨by
    rw [← map_natCast A]
    exact (_root_.map_ne_zero _).2
      (natCast_ne_zero_of_isUnit (IsLocalRing.isUnit_natCast_iff_not_dvd.2 hm))⟩
  obtain ⟨y, hy⟩ := IsSepClosed.exists_pow_nat_eq (k := Ω) (A π) m
  have hyE : y ∈ E := (le_sup_right : _ ≤ E) (subset_adjoin _ _ ⟨m, hm, hy⟩)
  have hy0 : y ≠ 0 := by
    rintro rfl
    rw [zero_pow (fun h ↦ NeZero.ne (m : Ω) (by rw [h, Nat.cast_zero]))] at hy
    exact (_root_.map_ne_zero A).2 π.ne_zero hy.symm
  -- Write `a = π ^ k u` with `u` a unit of `𝒪[K]`; then `z = x / y ^ k` is an `m`-th root of `u`,
  -- hence unramified.
  obtain ⟨⟨k, u⟩, hau, -⟩ := existsUnique_eq_zpow_mul ((isUniformizer_def π).1 hπ) a
  set z := x * (y ^ k)⁻¹
  have hyk : (y ^ k) ^ m = A (π : K) ^ k := by
    rw [← hy]
    exact_mod_cast zpow_comm y k m
  have hzm : z ^ m = A ((u : Kˣ) : K) := calc
    z ^ m = A (a : K) / A (π : K) ^ k := by rw [mul_pow, inv_pow, hx, hyk, div_eq_mul_inv]
    _ = A ((π : K) ^ k) * A ((u : Kˣ) : K) / A (π : K) ^ k := by simp [hau]
    _ = A ((u : Kˣ) : K) := by
      rw [map_zpow₀]
      field_simp
  have hzE : z ∈ E := (le_sup_left : _ ≤ E) (mem_maximalUnramifiedExtension_of_pow_eq hm u.2 hzm)
  have hxz : x = z * y ^ k := by
    simp only [z]
    field_simp
  rw [hxz]
  exact mul_mem hzE (zpow_mem hyE k)

/-! ### The wild inertia subgroup -/

/-- **The wild inertia subgroup** `P_K` of the absolute Galois group of a nonarchimedean local
field `K`: the automorphisms of the algebraic closure fixing the maximal tamely ramified extension
`K^{t}`. Through `IntermediateField.fixingSubgroupEquiv` it is `Gal(K^{alg}/K^{t})`. -/
def wildInertiaSubgroup : Subgroup (Field.absoluteGaloisGroup K) :=
  (maximalTameExtension K (AlgebraicClosure K)).fixingSubgroup

/-- The wild inertia subgroup is the fixing subgroup of the maximal tamely ramified extension. -/
theorem wildInertiaSubgroup_def :
    wildInertiaSubgroup K = (maximalTameExtension K (AlgebraicClosure K)).fixingSubgroup :=
  -- `(rfl)`, not `rfl`: keep the body opaque while exporting this equation across modules.
  (rfl)

variable {K} in
/-- An automorphism lies in the wild inertia subgroup exactly when it fixes every element of the
maximal tamely ramified extension. -/
@[simp]
theorem mem_wildInertiaSubgroup_iff {σ : Field.absoluteGaloisGroup K} :
    σ ∈ wildInertiaSubgroup K ↔
      ∀ x ∈ maximalTameExtension K (AlgebraicClosure K),
        DFunLike.coe (F := Gal(AlgebraicClosure K/K)) σ x = x :=
  mem_fixingSubgroup_iff _ _

variable {K} in
/-- **Wild inertia, through radicals.** An automorphism of `K^{alg}` lies in the wild inertia
subgroup exactly when it fixes every `m`-th root of every nonzero element of `K`, for `m` prime to
the residue characteristic. -/
theorem mem_wildInertiaSubgroup_iff_pow_eq {σ : Field.absoluteGaloisGroup K} :
    σ ∈ wildInertiaSubgroup K ↔
      ∀ (m : ℕ), ¬ ringChar 𝓀[K] ∣ m → ∀ (a : Kˣ) (x : AlgebraicClosure K),
        x ^ m = algebraMap K (AlgebraicClosure K) a →
          DFunLike.coe (F := Gal(AlgebraicClosure K/K)) σ x = x := by
  rw [wildInertiaSubgroup_def, maximalTameExtension_def]
  refine ((mem_fixingSubgroup_iff _ σ).trans
    (forall_mem_adjoin_smul_eq_self_iff K (M := Gal(AlgebraicClosure K/K)) σ)).trans ?_
  exact ⟨fun h m hm a x hx ↦ h x ⟨m, hm, a, hx⟩, fun h x ⟨m, hm, a, hx⟩ ↦ h m hm a x hx⟩

/-- **The wild inertia subgroup is closed** in the Krull topology. -/
theorem isClosed_wildInertiaSubgroup :
    IsClosed (wildInertiaSubgroup K : Set (Field.absoluteGaloisGroup K)) :=
  fixingSubgroup_isClosed_of_isAlgebraic _

/-- **The wild inertia subgroup is normal**, since `K^{t}/K` is normal. -/
instance wildInertiaSubgroup_normal : (wildInertiaSubgroup K).Normal :=
  (maximalTameExtension K (AlgebraicClosure K)).fixingSubgroup_normal

/-- **Wild inertia lies in inertia**: `P_K ≤ I_K`, since `K^{ur} ≤ K^{t}`. -/
theorem wildInertiaSubgroup_le_inertiaSubgroup : wildInertiaSubgroup K ≤ inertiaSubgroup K := by
  rw [wildInertiaSubgroup_def, inertiaSubgroup_def]
  exact fixingSubgroup_le (maximalUnramifiedExtension_le_maximalTameExtension K _)

variable {K} in
/-- **Wild inertia, through a uniformizer.** For a uniformizer `π` of `K`, an automorphism of
`K^{alg}` lies in the wild inertia subgroup exactly when it lies in the inertia subgroup and fixes
every `m`-th root of `π`, for `m` prime to the residue characteristic. -/
theorem mem_wildInertiaSubgroup_iff_of_isUniformizer {π : Kˣ} (hπ : IsUniformizer K π)
    {σ : Field.absoluteGaloisGroup K} :
    σ ∈ wildInertiaSubgroup K ↔ σ ∈ inertiaSubgroup K ∧
      ∀ (m : ℕ), ¬ ringChar 𝓀[K] ∣ m → ∀ x : AlgebraicClosure K,
        x ^ m = algebraMap K (AlgebraicClosure K) π →
          DFunLike.coe (F := Gal(AlgebraicClosure K/K)) σ x = x := by
  set M := maximalUnramifiedExtension K (AlgebraicClosure K)
  set N := adjoin K {x : AlgebraicClosure K | ∃ m : ℕ, ¬ ringChar 𝓀[K] ∣ m ∧
    x ^ m = algebraMap K (AlgebraicClosure K) π}
  -- State the splitting of the fixing subgroup of `M ⊔ N` on `Gal(K^{alg}/K)`, whose group
  -- structure is not reducibly that of `Field.absoluteGaloisGroup K`.
  have hsup (τ : Gal(AlgebraicClosure K/K)) :
      τ ∈ (M ⊔ N).fixingSubgroup ↔ τ ∈ M.fixingSubgroup ∧ τ ∈ N.fixingSubgroup := by
    rw [fixingSubgroup_sup, Subgroup.mem_inf]
  rw [wildInertiaSubgroup_def, inertiaSubgroup_def, maximalTameExtension_eq_sup_adjoin hπ]
  refine (hsup σ).trans (and_congr_right fun _ ↦ ((mem_fixingSubgroup_iff _ σ).trans
    (forall_mem_adjoin_smul_eq_self_iff K (M := Gal(AlgebraicClosure K/K)) σ)).trans ?_)
  exact ⟨fun h m hm x hx ↦ h x ⟨m, hm, hx⟩, fun h x ⟨m, hm, hx⟩ ↦ h m hm x hx⟩

end TauCeti
