/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.Integral
public import TauCeti.RingTheory.Huber.Pair

import TauCeti.RingTheory.Huber.OpenIdeal

/-!
# Emptiness of the adic spectrum

For a Huber pair `(A, A⁺)`, Wedhorn Proposition 7.49(1) characterizes emptiness of the adic
spectrum by triviality of the separated quotient:

```text
Spa(A, A⁺) = ∅  ↔  A / closure {0} = 0.
```

Equivalently, the spectrum is empty exactly when `1` belongs to the closure of zero. If the
spectrum is empty, Proposition 7.52(1) first forces every element of `A` into `A⁺`, hence makes
every element power-bounded. The extended ideal of definition is open, so emptiness also forces
it to be the unit ideal. It is generated by topologically nilpotent elements; multiplying those
generators by arbitrary power-bounded coefficients and adding shows that `1` is topologically
nilpotent. The constant sequence of its powers then makes `0` and `1` topologically
indistinguishable.

For a Hausdorff Huber ring the closure of zero is zero, giving the familiar criterion that the
adic spectrum is empty exactly when the ring is trivial.

## Main results

* `TauCeti.ValuationSpectrum.spa_eq_empty_iff_one_mem_closure_zero`: the closure-of-zero form.
* `TauCeti.ValuationSpectrum.spa_eq_empty_iff_subsingleton_quotient_closure_zero`: the separated
  quotient form.
* `TauCeti.ValuationSpectrum.spa_eq_empty_iff_subsingleton`: the Hausdorff specialization.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Proposition 7.49(1).

## Provenance

The proof is assembled from the valuative criterion and Huber-ring infrastructure already in
Tau Ceti. No external formalization is followed.
-/

public section

namespace TauCeti.ValuationSpectrum

open Filter Topology TauCeti.Huber

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A] [IsHuberRing A]

/-- **The converse half of Wedhorn Proposition 7.49(1).** If the adic spectrum of a Huber pair
is empty, then `1` belongs to the closure of zero.

The ring-of-integral-elements hypothesis is essential: it supplies both the integral closedness
used by Proposition 7.52(1) and the power-boundedness needed to make the topologically nilpotent
elements absorb arbitrary coefficients. -/
theorem one_mem_closure_zero_of_spa_eq_empty (Aplus : Subring A)
    (hplus : IsRingOfIntegralElements Aplus) (hspa : spa Aplus = ∅) :
    (1 : A) ∈ closure ({0} : Set A) := by
  have hall_mem : ∀ a : A, a ∈ Aplus := by
    intro a
    let _ := hplus.isIntegrallyClosedIn
    apply mem_of_forall_vle_one hplus.isOpen
    intro v hv
    rw [hspa] at hv
    exact (Set.notMem_empty v hv).elim
  have hall_powerBounded : ∀ a : A, IsPowerBounded a := fun a ↦
    mem_powerBoundedSubring.mp (hplus.le_powerBoundedSubring (hall_mem a))
  let toPowerBounded : A →+* powerBoundedSubring A :=
    (RingHom.id A).codRestrict (powerBoundedSubring A) fun a ↦
      mem_powerBoundedSubring.mpr (hall_powerBounded a)
  let nilIdeal : Ideal A := (topologicallyNilpotentIdeal A).comap toPowerBounded
  let P : PairOfDefinition A := Classical.choice IsHuberRing.nonempty_pairOfDefinition
  have hopen : IsOpen (P.extendedIdealOfDefinition : Set A) :=
    (P.isOpen_iff_exists_pow_le P.extendedIdealOfDefinition).mpr ⟨1, by simp⟩
  have htop : P.extendedIdealOfDefinition = ⊤ :=
    eq_top_of_spa_eq_empty Aplus hopen hspa
  have hle : P.extendedIdealOfDefinition ≤ nilIdeal := by
    rw [P.extendedIdealOfDefinition_def]
    refine Ideal.map_le_iff_le_comap.mpr fun a ha ↦ ?_
    simpa [nilIdeal, toPowerBounded] using
      P.isTopologicallyNilpotent_of_mem_idealOfDefinition ha
  have hone_nil : IsTopologicallyNilpotent (1 : A) := by
    have hmem := hle (htop.symm ▸ (show (1 : A) ∈ (⊤ : Ideal A) from Submodule.mem_top))
    simpa [nilIdeal, toPowerBounded] using hmem
  rw [← specializes_iff_mem_closure, specializes_comm, specializes_iff_pure]
  have htend : Tendsto (fun _ : ℕ ↦ (1 : A)) atTop (nhds 0) := by
    simpa [IsTopologicallyNilpotent] using hone_nil
  change Filter.map (fun _ : ℕ ↦ (1 : A)) atTop ≤ nhds 0 at htend
  rwa [Filter.map_const] at htend

/-- **Wedhorn Proposition 7.49(1), closure form.** The adic spectrum of a Huber pair is empty
exactly when `1` belongs to the closure of zero. -/
theorem spa_eq_empty_iff_one_mem_closure_zero (Aplus : Subring A)
    (hplus : IsRingOfIntegralElements Aplus) :
    spa Aplus = ∅ ↔ (1 : A) ∈ closure ({0} : Set A) :=
  ⟨one_mem_closure_zero_of_spa_eq_empty Aplus hplus,
    spa_eq_empty_of_one_mem_closure_zero Aplus⟩

/-- **Wedhorn Proposition 7.49(1), separated-quotient form.** The adic spectrum of a Huber pair
is empty exactly when the quotient by the closure of zero is the zero ring. -/
theorem spa_eq_empty_iff_subsingleton_quotient_closure_zero (Aplus : Subring A)
    (hplus : IsRingOfIntegralElements Aplus) :
    spa Aplus = ∅ ↔ Subsingleton (A ⧸ Ideal.closure (⊥ : Ideal A)) := by
  rw [spa_eq_empty_iff_one_mem_closure_zero Aplus hplus, Ideal.Quotient.subsingleton_iff]
  have hcoe : ((Ideal.closure (⊥ : Ideal A) : Ideal A) : Set A) =
      closure ({0} : Set A) := by
    rw [Ideal.coe_closure, Submodule.bot_coe]
  rw [Ideal.eq_top_iff_one]
  change (1 : A) ∈ closure ({0} : Set A) ↔
    (1 : A) ∈ ((Ideal.closure (⊥ : Ideal A) : Ideal A) : Set A)
  rw [hcoe]

/-- For a Hausdorff Huber pair, the adic spectrum is empty exactly when the underlying ring is
trivial. -/
theorem spa_eq_empty_iff_subsingleton [T2Space A] (Aplus : Subring A)
    (hplus : IsRingOfIntegralElements Aplus) :
    spa Aplus = ∅ ↔ Subsingleton A := by
  rw [spa_eq_empty_iff_one_mem_closure_zero Aplus hplus, isClosed_singleton.closure_eq]
  simp only [Set.mem_singleton_iff]
  simpa only [eq_comm] using (subsingleton_iff_zero_eq_one (M₀ := A))

end TauCeti.ValuationSpectrum

end
