/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.CategoryTheory.ObjectProperty
public import TauCeti.CategoryTheory.Preadditive.MorphismIdeal.Basic

/-!
# The ideal of morphisms factoring through a class of objects

Given an object property `P` in a preadditive category, this file constructs the two-sided
morphism ideal generated by the maps that factor through a `P`-object. Taking the additive
closure is essential in an arbitrary preadditive category: a sum of two factorizations need not
itself have a single intermediate object.

When the category has binary biproducts and `P` is nonempty and closed under binary products,
every member of the generated ideal does factor through one `P`-object. The sum of factorizations
through `Q₁` and `Q₂` factors through `Q₁ ⊞ Q₂`; the zero and negation cases use zero morphisms
and negating one factor. In particular, this applies when `P` contains a zero object and is closed
under finite biproducts, as for the projective-injective objects used in stable categories.

## Main definitions

* `TauCeti.CategoryTheory.ObjectProperty.FactorsThrough P f`: the morphism `f` factors through an
  object satisfying `P`.
* `TauCeti.CategoryTheory.ObjectProperty.factorIdeal P`: the two-sided ideal additively generated
  by such maps.

## Main results

* `TauCeti.CategoryTheory.ObjectProperty.factorIdeal_le_iff`: the universal property of the
  generated ideal.
* `TauCeti.CategoryTheory.ObjectProperty.mem_factorIdeal_iff`: under the stated closure
  hypotheses, membership in the generated ideal is equivalent to a single factorization through
  a `P`-object.

## References

* M. Auslander, I. Reiten, S. Smalø, *Representation Theory of Artin Algebras*, Cambridge
  Studies in Advanced Mathematics 36, CUP (1995), Chapter IV, Section 1.
* D. Happel, *Triangulated Categories in the Representation Theory of Finite Dimensional
  Algebras*, LMS Lecture Note Series 119, CUP (1988), Chapter I, Section 2.
-/

public section

universe v u

namespace TauCeti

open CategoryTheory CategoryTheory.Limits

namespace CategoryTheory.ObjectProperty

variable {C : Type u} [Category.{v} C]

/-- A morphism factors through an object satisfying `P` if it is a composite whose intermediate
object satisfies `P`. -/
def FactorsThrough (P : ObjectProperty C) {X Y : C} (f : X ⟶ Y) : Prop :=
  ∃ Q : C, P Q ∧ ∃ i : X ⟶ Q, ∃ p : Q ⟶ Y, f = i ≫ p

/-- A composite through a `P`-object factors through a `P`-object. -/
theorem factorsThrough_comp (P : ObjectProperty C) {X Q Y : C} (hQ : P Q)
    (i : X ⟶ Q) (p : Q ⟶ Y) : FactorsThrough P (i ≫ p) :=
  ⟨Q, hQ, i, p, rfl⟩

namespace FactorsThrough

variable {P Q : ObjectProperty C} {W X Y Z : C} {f : X ⟶ Y}

/-- Enlarging the class of intermediate objects preserves factorization. -/
theorem mono (hf : FactorsThrough P f) (hPQ : P ≤ Q) : FactorsThrough Q f := by
  obtain ⟨A, hA, i, p, rfl⟩ := hf
  exact ⟨A, hPQ _ hA, i, p, rfl⟩

/-- Precomposing preserves factorization through a `P`-object. -/
theorem comp_left (hf : FactorsThrough P f) (g : W ⟶ X) : FactorsThrough P (g ≫ f) := by
  obtain ⟨A, hA, i, p, rfl⟩ := hf
  exact ⟨A, hA, g ≫ i, p, (Category.assoc _ _ _).symm⟩

/-- Postcomposing preserves factorization through a `P`-object. -/
theorem comp_right (hf : FactorsThrough P f) (g : Y ⟶ Z) : FactorsThrough P (f ≫ g) := by
  obtain ⟨A, hA, i, p, rfl⟩ := hf
  exact ⟨A, hA, i, p ≫ g, Category.assoc _ _ _⟩

/-- The zero morphism factors through a `P`-object when `P` is nonempty. -/
theorem zero [HasZeroMorphisms C] (P : ObjectProperty C) [P.Nonempty] (X Y : C) :
    FactorsThrough P (0 : X ⟶ Y) := by
  obtain ⟨Z, hZ⟩ := P.exists_prop_of_nonempty
  exact ⟨Z, hZ, 0, 0, Limits.zero_comp.symm⟩

variable [Preadditive C]
variable {P Q : ObjectProperty C} {X Y Z : C} {f : X ⟶ Y}

/-- Negating a morphism preserves factorization through a `P`-object. -/
theorem neg (hf : FactorsThrough P f) : FactorsThrough P (-f) := by
  obtain ⟨A, hA, i, p, rfl⟩ := hf
  exact ⟨A, hA, -i, p, (Preadditive.neg_comp _ _).symm⟩

/-- With binary biproducts, the sum of two factorizations through `P` factors through the
biproduct of their intermediate objects. -/
theorem add [HasBinaryBiproducts C] [P.IsClosedUnderBinaryProducts]
    {f g : X ⟶ Y} (hf : FactorsThrough P f) (hg : FactorsThrough P g) :
    FactorsThrough P (f + g) := by
  obtain ⟨A, hA, iA, pA, rfl⟩ := hf
  obtain ⟨B, hB, iB, pB, rfl⟩ := hg
  exact ⟨A ⊞ B, P.prop_biprod_of_isClosedUnderBinaryProducts hA hB,
    biprod.lift iA iB, biprod.desc pA pB, biprod.lift_desc.symm⟩

end FactorsThrough

variable [Preadditive C]
variable {P Q : ObjectProperty C} {X Y Z : C} {f : X ⟶ Y}

/-- The two-sided morphism ideal additively generated by maps factoring through objects
satisfying `P`. -/
def factorIdeal (P : ObjectProperty C) : MorphismIdeal C where
  hom X Y := AddSubgroup.closure {f : X ⟶ Y | FactorsThrough P f}
  comp_mem_left := by
    intro X Y Z f g hg
    induction hg using AddSubgroup.closure_induction with
    | mem g hg => exact AddSubgroup.subset_closure (hg.comp_left f)
    | zero => simp
    | add g h _ _ hg hh =>
        simpa only [Preadditive.comp_add] using AddSubgroup.add_mem _ hg hh
    | neg g _ hg => simpa only [Preadditive.comp_neg] using AddSubgroup.neg_mem _ hg
  comp_mem_right := by
    intro X Y Z f g hf
    induction hf using AddSubgroup.closure_induction with
    | mem f hf => exact AddSubgroup.subset_closure (hf.comp_right g)
    | zero => simp
    | add f h _ _ hf hh =>
        simpa only [Preadditive.add_comp] using AddSubgroup.add_mem _ hf hh
    | neg f _ hf => simpa only [Preadditive.neg_comp] using AddSubgroup.neg_mem _ hf

/-- A map factoring through a `P`-object belongs to the ideal generated by such maps. -/
theorem mem_factorIdeal_of_factorsThrough (hf : FactorsThrough P f) :
    f ∈ (factorIdeal P).hom X Y :=
  AddSubgroup.subset_closure hf

/-- A composite through a `P`-object belongs to `factorIdeal P`. -/
theorem comp_mem_factorIdeal (hZ : P Z) (i : X ⟶ Z) (p : Z ⟶ Y) :
    i ≫ p ∈ (factorIdeal P).hom X Y :=
  mem_factorIdeal_of_factorsThrough (factorsThrough_comp P hZ i p)

/-- The universal property of `factorIdeal P`: it is the least morphism ideal containing all
composites through `P`-objects. -/
@[simp]
theorem factorIdeal_le_iff {I : MorphismIdeal C} :
    factorIdeal P ≤ I ↔ ∀ {X Y Z : C} (_hZ : P Z) (i : X ⟶ Z) (p : Z ⟶ Y),
      i ≫ p ∈ I.hom X Y := by
  constructor
  · intro h X Y Z hZ i p
    exact MorphismIdeal.le_def.1 h (i ≫ p) (comp_mem_factorIdeal hZ i p)
  · intro h X Y f hf
    induction hf using AddSubgroup.closure_induction with
    | mem f hf =>
        obtain ⟨Z, hZ, i, p, rfl⟩ := hf
        exact h hZ i p
    | zero => exact AddSubgroup.zero_mem _
    | add f g _ _ hf hg => exact AddSubgroup.add_mem _ hf hg
    | neg f _ hf => exact AddSubgroup.neg_mem _ hf

/-- The ideal generated by factorizations is monotone in the class of allowed intermediate
objects. -/
theorem factorIdeal_mono (hPQ : P ≤ Q) : factorIdeal P ≤ factorIdeal Q :=
  factorIdeal_le_iff.2 fun hZ i p ↦ comp_mem_factorIdeal (hPQ _ hZ) i p

/-- If `P` is nonempty and closed under binary products, every member of `factorIdeal P` is a
single morphism factoring through a `P`-object. -/
theorem factorsThrough_of_mem_factorIdeal [HasBinaryBiproducts C] [P.Nonempty]
    [P.IsClosedUnderBinaryProducts]
    (hf : f ∈ (factorIdeal P).hom X Y) : FactorsThrough P f := by
  induction hf using AddSubgroup.closure_induction with
  | mem f hf => exact hf
  | zero => exact FactorsThrough.zero P X Y
  | add f g _ _ hf hg => exact hf.add hg
  | neg f _ hf => exact hf.neg

/-- Under the standard closure hypotheses on `P`, the additive closure in the definition of
`factorIdeal P` introduces no new kind of morphism: every member has one `P`-factorization. -/
@[simp]
theorem mem_factorIdeal_iff [HasBinaryBiproducts C] [P.Nonempty]
    [P.IsClosedUnderBinaryProducts] :
    f ∈ (factorIdeal P).hom X Y ↔ FactorsThrough P f :=
  ⟨factorsThrough_of_mem_factorIdeal, mem_factorIdeal_of_factorsThrough⟩

end CategoryTheory.ObjectProperty

end TauCeti
