/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Algebra.Operations
public import Mathlib.Algebra.Module.Torsion.Basic
public import Mathlib.GroupTheory.SpecificGroups.Cyclic
public import Mathlib.Topology.Instances.AddCircle.Defs

import TauCeti.Algebra.Module.Torsion.Basic

/-!
# Integrality and torsion in the circle group

A rational number reduces to zero in `ℚ/ℤ`, realized as `AddCircle (1 : ℚ)`, exactly when it
lies in `(1 : Submodule ℤ ℚ)`, the copy of `ℤ` inside `ℚ`. This bridges the two spellings of
integrality used by the discriminant-form theory: vanishing in the circle group and membership
in the unit `ℤ`-submodule.

The rest of the file describes the finite subgroups of `AddCircle p` for a positive period `p`
in a linearly ordered field. Mathlib already knows that the set of `n`-torsion points is finite
and that the point `p / n` has additive order exactly `n`; here the `n`-torsion is identified
with the subgroup generated by `p / n`, so that it is cyclic of order exactly `n`, and it is
shown to be the *only* subgroup of that order. Consequently `n ↦ (AddCircle p)[n]` is an order
embedding of the divisibility order on positive naturals into the subgroups of `AddCircle p`,
and every finite subgroup is one of these.

Taking `p = 1` over `ℚ` this is the classical description of the finite subgroups of `ℚ/ℤ`: for
each `n` there is exactly one subgroup of order `n`, namely the cyclic group generated by the
class of `1 / n`. That statement is what normalizes a class-field-theoretic invariant map: an
injective homomorphism from a finite group onto the `n`-torsion of `ℚ/ℤ` forces the group to be
cyclic of order `n` with a distinguished generator, the one of invariant `1 / n`.

## Main declarations

* `AddCircle.coe_eq_zero_iff_mem_one`: vanishing in `AddCircle (1 : ℚ)` is membership in
  `(1 : Submodule ℤ ℚ)`.
* `AddCircle.zsmul_coe_eq_zero`: an integer multiple of a rational number vanishes in
  `AddCircle (1 : ℚ)` once that multiple is an integer.
* `AddCircle.torsionBy_eq_zmultiples`: the `n`-torsion of `AddCircle p` is generated by the
  class of `p / n`.
* `AddCircle.natCard_torsionBy`: the `n`-torsion of `AddCircle p` has exactly `n` elements.
* `AddCircle.eq_torsionBy_of_natCard_eq`: a subgroup of `AddCircle p` with `n` elements is the
  `n`-torsion; equivalently, `AddCircle.exists_eq_torsionBy` writes every finite subgroup as a
  torsion subgroup.
* `AddCircle.torsionBy_le_torsionBy_iff` and `AddCircle.torsionBy_inj`: the torsion subgroups
  are ordered by divisibility, and pairwise distinct.
* `AddCircle.nsmul_coe_period_div`: multiplying the generator of the `n`-torsion by a divisor
  `d` of `n` produces the generator of the `n / d`-torsion.
* `AddCircle.natCard_eq_of_injective_of_range_eq_torsionBy`,
  `AddCircle.existsUnique_apply_eq_coe_period_div`,
  `AddCircle.exists_zsmul_eq_of_apply_eq_coe_period_div`,
  `AddCircle.isAddCyclic_of_injective_of_range_eq_torsionBy` and
  `AddCircle.zmodAddEquivOfInjectiveOfRangeEqTorsionBy`: an injective homomorphism from a group
  onto the `n`-torsion makes that group cyclic of order `n`, with a unique element of invariant
  `p / n` as a distinguished generator.
* `AddCircle.isAddTorsion_rat`: a rational circle is a torsion group, so its torsion subgroups
  exhaust it (`AddCircle.exists_mem_torsionBy_rat`).

## References

* E. Artin and J. Tate, *Class Field Theory*, Chapter XIV, §2: the invariant map of a class
  formation takes values in `ℚ/ℤ`, and on a layer of degree `n` its image is the unique subgroup
  of order `n`, in which the fundamental class is the element `1 / n`.
-/

public section

open AddSubgroup

namespace AddCircle

/-- A rational number reduces to zero in `ℚ/ℤ` exactly when it is an integer. -/
theorem coe_eq_zero_iff_mem_one (q : ℚ) :
    (q : AddCircle (1 : ℚ)) = 0 ↔ q ∈ (1 : Submodule ℤ ℚ) := by
  constructor
  · intro h
    obtain ⟨n, hn⟩ := (coe_eq_zero_iff (1 : ℚ)).mp h
    exact Submodule.mem_one.mpr ⟨n, by simpa using hn⟩
  · intro h
    obtain ⟨n, hn⟩ := Submodule.mem_one.mp h
    exact (coe_eq_zero_iff (1 : ℚ)).mpr ⟨n, by simpa using hn⟩

/-- The multiple `k • x` of a rational number vanishes in `ℚ/ℤ` as soon as it is the integer `c`.

This is the shape in which the torsion side conditions of the cyclic and Klein four presentations
of a finite quadratic module arise: the witness `c` is supplied explicitly and the remaining
arithmetic identity is a computation in `ℚ`. -/
theorem zsmul_coe_eq_zero {k c : ℤ} {x : ℚ} (h : (k : ℚ) * x = c) :
    k • ((x : ℚ) : AddCircle (1 : ℚ)) = 0 := by
  rw [← coe_zsmul, coe_eq_zero_iff_mem_one]
  refine Submodule.mem_one.mpr ⟨c, ?_⟩
  rw [zsmul_eq_mul, h]
  exact eq_intCast (algebraMap ℤ ℚ) c

section Finiteness

variable {𝕜 : Type*} [AddCommGroup 𝕜] [LinearOrder 𝕜] [IsOrderedAddMonoid 𝕜] (p : 𝕜) {n : ℕ}

/-- The `n`-torsion of `AddCircle p` is finite for positive `n`. -/
theorem finite_torsionBy (hn : 0 < n) : Finite ((AddCircle p)[(n : ℤ)]) :=
  ((finite_torsion p hn).subset fun _ hu ↦ torsionBy.nsmul_iff.mp hu).to_subtype

end Finiteness

section Torsion

variable {𝕜 : Type*} [Field 𝕜] [LinearOrder 𝕜] [IsStrictOrderedRing 𝕜] (p : 𝕜) [hp : Fact (0 < p)]
  {m n : ℕ}

/-- The class of `p / n` is killed by `n`. -/
theorem coe_period_div_mem_torsionBy (hn : 0 < n) :
    ((p / n : 𝕜) : AddCircle p) ∈ (AddCircle p)[(n : ℤ)] := by
  refine torsionBy.nsmul_iff.mpr ?_
  have h := addOrderOf_nsmul_eq_zero ((p / (n : ℕ) : 𝕜) : AddCircle p)
  rwa [addOrderOf_period_div (p := p) hn] at h

/-- The `n`-torsion of `AddCircle p` is the cyclic subgroup generated by the class of `p / n`. -/
theorem torsionBy_eq_zmultiples (hn : 0 < n) :
    (AddCircle p)[(n : ℤ)] = zmultiples ((p / n : 𝕜) : AddCircle p) := by
  refine le_antisymm (fun u hu ↦ ?_) ?_
  · obtain ⟨k, -, rfl⟩ := (AddCircle.nsmul_eq_zero_iff hn).mp (torsionBy.nsmul_iff.mp hu)
    rw [mem_zmultiples_iff]
    exact ⟨(k : ℤ), by rw [natCast_zsmul, natCast_div_mul_eq_nsmul]⟩
  · rw [zmultiples_le]
    exact coe_period_div_mem_torsionBy p hn

/-- Every point killed by `n` is an integer multiple of the class of `p / n`. -/
theorem exists_zsmul_eq_of_mem_torsionBy (hn : 0 < n) {u : AddCircle p}
    (hu : u ∈ (AddCircle p)[(n : ℤ)]) :
    ∃ k : ℤ, k • ((p / n : 𝕜) : AddCircle p) = u := by
  rwa [torsionBy_eq_zmultiples p hn, mem_zmultiples_iff] at hu

/-- The `n`-torsion of `AddCircle p` has exactly `n` elements. -/
theorem natCard_torsionBy (hn : 0 < n) : Nat.card ((AddCircle p)[(n : ℤ)]) = n := by
  rw [torsionBy_eq_zmultiples p hn, Nat.card_zmultiples, addOrderOf_period_div hn]

/-- The `n`-torsion of `AddCircle p` is cyclic; by `AddCircle.natCard_torsionBy` it is cyclic of
order exactly `n`. -/
theorem isAddCyclic_torsionBy (hn : 0 < n) : IsAddCyclic ((AddCircle p)[(n : ℤ)]) :=
  (AddSubgroup.isAddCyclic_iff_exists_zmultiples_eq_top _).mpr
    ⟨_, (torsionBy_eq_zmultiples p hn).symm⟩

/-- There is exactly one subgroup of `AddCircle p` of any given finite order: a subgroup with
`n` elements is the `n`-torsion. -/
theorem eq_torsionBy_of_natCard_eq (hn : 0 < n) {H : AddSubgroup (AddCircle p)}
    (hH : Nat.card H = n) : H = (AddCircle p)[(n : ℤ)] :=
  have := finite_torsionBy p hn
  AddSubgroup.eq_of_le_of_card_ge (AddSubgroup.le_torsionBy_of_natCard_eq hH)
    (by rw [natCard_torsionBy p hn, hH])

/-- Every finite subgroup of `AddCircle p` is a torsion subgroup. -/
theorem exists_eq_torsionBy {H : AddSubgroup (AddCircle p)} [Finite H] :
    ∃ n : ℕ, 0 < n ∧ H = (AddCircle p)[(n : ℤ)] :=
  ⟨Nat.card H, Nat.card_pos, eq_torsionBy_of_natCard_eq p Nat.card_pos rfl⟩

/-- The torsion subgroups of `AddCircle p` are ordered by divisibility. -/
theorem torsionBy_le_torsionBy_iff (hm : 0 < m) (hn : 0 < n) :
    (AddCircle p)[(m : ℤ)] ≤ (AddCircle p)[(n : ℤ)] ↔ m ∣ n := by
  refine ⟨fun h ↦ ?_, fun hd u hu ↦ ?_⟩
  · have := addOrderOf_dvd_of_mem_zmultiples
      ((torsionBy_eq_zmultiples p hn) ▸ h (coe_period_div_mem_torsionBy p hm))
    rwa [addOrderOf_period_div hm, addOrderOf_period_div hn] at this
  · exact Submodule.torsionBy_le_torsionBy_of_dvd (M := AddCircle p) _ _
      (Int.natCast_dvd_natCast.mpr hd) hu

/-- Distinct positive orders give distinct torsion subgroups of `AddCircle p`. -/
theorem torsionBy_inj (hm : 0 < m) (hn : 0 < n) :
    (AddCircle p)[(m : ℤ)] = (AddCircle p)[(n : ℤ)] ↔ m = n := by
  refine ⟨fun h ↦ ?_, fun h ↦ by rw [h]⟩
  rw [← natCard_torsionBy p hm, ← natCard_torsionBy p hn, h]

end Torsion

section PeriodDiv

variable {𝕜 : Type*} [Field 𝕜] [CharZero 𝕜] (p : 𝕜) {n : ℕ}

/-- Scaling the canonical generator of the `n`-torsion by a divisor `d` of `n` gives the
canonical generator of the `n / d`-torsion.

For `p = 1` over `ℚ` this reads `d • (1 / n) = 1 / (n / d)`, the arithmetic behind the way
restriction rescales a class-field-theoretic invariant. -/
@[simp]
theorem nsmul_coe_period_div {d : ℕ} (hd : d ∣ n) :
    d • ((p / n : 𝕜) : AddCircle p) = ((p / (n / d : ℕ) : 𝕜) : AddCircle p) := by
  rcases eq_or_ne n 0 with rfl | hn
  · simp
  have hd0 : d ≠ 0 := by rintro rfl; exact hn (Nat.zero_dvd.mp hd)
  have hn0 : (n : 𝕜) ≠ 0 := Nat.cast_ne_zero.mpr hn
  have hd0' : (d : 𝕜) ≠ 0 := Nat.cast_ne_zero.mpr hd0
  have key : (d : 𝕜) * (p / n) = p / ((n / d : ℕ) : 𝕜) := by
    rw [Nat.cast_div hd hd0']
    field_simp
  rw [← coe_nsmul, nsmul_eq_mul, key]

end PeriodDiv

section InvariantMap

variable {𝕜 : Type*} [Field 𝕜] [LinearOrder 𝕜] [IsStrictOrderedRing 𝕜] (p : 𝕜) [hp : Fact (0 < p)]
  {n : ℕ} {H : Type*} [AddGroup H] {f : H →+ AddCircle p}

/-! ### Groups normalized by an invariant map

An *invariant map* on a group `H` is an injective homomorphism `f : H →+ AddCircle p` whose
image is the `n`-torsion. The classification above turns such a map into a complete description
of `H`: it is cyclic of order `n` — in particular abelian — and the element of invariant `p / n`
is a distinguished generator. Over `ℚ` with `p = 1` this is the normalization that produces the
fundamental class of a class formation from its invariant map. -/

/-- A group with an invariant map onto the `n`-torsion has exactly `n` elements. -/
theorem natCard_eq_of_injective_of_range_eq_torsionBy (hn : 0 < n) (hf : Function.Injective f)
    (hr : Set.range f = ((AddCircle p)[(n : ℤ)] : Set (AddCircle p))) :
    Nat.card H = n := by
  have e : H ≃ ((AddCircle p)[(n : ℤ)]) := (Equiv.ofInjective f hf).trans (Set.equivOfEq hr)
  rw [Nat.card_congr e, natCard_torsionBy p hn]

/-- A group with an invariant map onto the `n`-torsion has a unique element of invariant
`p / n`. -/
theorem existsUnique_apply_eq_coe_period_div (hn : 0 < n) (hf : Function.Injective f)
    (hr : Set.range f = ((AddCircle p)[(n : ℤ)] : Set (AddCircle p))) :
    ∃! u : H, f u = ((p / n : 𝕜) : AddCircle p) := by
  obtain ⟨u, hu⟩ : ((p / n : 𝕜) : AddCircle p) ∈ Set.range f := by
    rw [hr]; exact coe_period_div_mem_torsionBy p hn
  exact ⟨u, hu, fun v hv ↦ hf (hv.trans hu.symm)⟩

/-- The element of invariant `p / n` generates a group carrying an invariant map onto the
`n`-torsion. -/
theorem exists_zsmul_eq_of_apply_eq_coe_period_div (hn : 0 < n)
    (hf : Function.Injective f) (hr : Set.range f = ((AddCircle p)[(n : ℤ)] : Set (AddCircle p)))
    {u : H} (hu : f u = ((p / n : 𝕜) : AddCircle p)) (x : H) : ∃ k : ℤ, k • u = x := by
  have hx : f x ∈ (AddCircle p)[(n : ℤ)] := by
    rw [← SetLike.mem_coe, ← hr]; exact Set.mem_range_self x
  obtain ⟨k, hk⟩ := exists_zsmul_eq_of_mem_torsionBy p hn hx
  exact ⟨k, hf (by rw [map_zsmul, hu, hk])⟩

/-- A group with an invariant map onto the `n`-torsion is cyclic. -/
theorem isAddCyclic_of_injective_of_range_eq_torsionBy (hn : 0 < n) (hf : Function.Injective f)
    (hr : Set.range f = ((AddCircle p)[(n : ℤ)] : Set (AddCircle p))) : IsAddCyclic H := by
  obtain ⟨u, hu, -⟩ := existsUnique_apply_eq_coe_period_div p hn hf hr
  exact ⟨u, fun x ↦ mem_zmultiples_iff.mpr
    (exists_zsmul_eq_of_apply_eq_coe_period_div p hn hf hr hu x)⟩

/-- A group with an invariant map onto the `n`-torsion is `ZMod n`, by an isomorphism sending
`1` to the element `u` of invariant `p / n`. -/
noncomputable def zmodAddEquivOfInjectiveOfRangeEqTorsionBy (hn : 0 < n) (hf : Function.Injective f)
    (hr : Set.range f = ((AddCircle p)[(n : ℤ)] : Set (AddCircle p)))
    {u : H} (hu : f u = ((p / n : 𝕜) : AddCircle p)) : ZMod n ≃+ H :=
  zmodAddEquivOfGenerator
    (fun x ↦ mem_zmultiples_iff.mpr
      (exists_zsmul_eq_of_apply_eq_coe_period_div p hn hf hr hu x))
    (natCard_eq_of_injective_of_range_eq_torsionBy p hn hf hr)

/-- The isomorphism `AddCircle.zmodAddEquivOfInjectiveOfRangeEqTorsionBy` sends the class of an
integer `i` to the multiple `i • u` of the element `u` of invariant `p / n`. -/
@[simp]
theorem zmodAddEquivOfInjectiveOfRangeEqTorsionBy_apply_intCast (hn : 0 < n)
    (hf : Function.Injective f)
    (hr : Set.range f = ((AddCircle p)[(n : ℤ)] : Set (AddCircle p)))
    {u : H} (hu : f u = ((p / n : 𝕜) : AddCircle p)) (i : ℤ) :
    zmodAddEquivOfInjectiveOfRangeEqTorsionBy p hn hf hr hu i = i • u :=
  zmodAddEquivOfGenerator_apply_intCast _ _ i

/-- The inverse of `AddCircle.zmodAddEquivOfInjectiveOfRangeEqTorsionBy` sends the multiple
`i • u` of the element `u` of invariant `p / n` to the class of the integer `i`. -/
@[simp]
theorem zmodAddEquivOfInjectiveOfRangeEqTorsionBy_symm_apply_zsmul (hn : 0 < n)
    (hf : Function.Injective f)
    (hr : Set.range f = ((AddCircle p)[(n : ℤ)] : Set (AddCircle p)))
    {u : H} (hu : f u = ((p / n : 𝕜) : AddCircle p)) (i : ℤ) :
    (zmodAddEquivOfInjectiveOfRangeEqTorsionBy p hn hf hr hu).symm (i • u) = i :=
  zmodAddEquivOfGenerator_symm_apply_zsmul _ _ i

/-- The isomorphism `AddCircle.zmodAddEquivOfInjectiveOfRangeEqTorsionBy` sends `1 : ZMod n` to the
element `u` of invariant `p / n`. -/
@[simp]
theorem zmodAddEquivOfInjectiveOfRangeEqTorsionBy_apply_one (hn : 0 < n) (hf : Function.Injective f)
    (hr : Set.range f = ((AddCircle p)[(n : ℤ)] : Set (AddCircle p)))
    {u : H} (hu : f u = ((p / n : 𝕜) : AddCircle p)) :
    zmodAddEquivOfInjectiveOfRangeEqTorsionBy p hn hf hr hu 1 = u :=
  zmodAddEquivOfGenerator_apply_one _ _

end InvariantMap

section Rat

variable {p : ℚ} [hp : Fact (0 < p)]

/-- Every element of a rational circle `ℚ ⧸ pℤ` has finite additive order: the class of `r` is
killed by the denominator of `r / p`. -/
theorem isOfFinAddOrder_rat (u : AddCircle p) : IsOfFinAddOrder u := by
  induction u using QuotientAddGroup.induction_on with
  | _ r => exact isOfFinAddOrder_iff_exists_rat_eq_div.mpr ⟨r / p, rfl⟩

/-- A rational circle `ℚ ⧸ pℤ` is a torsion group. -/
theorem isAddTorsion_rat : IsAddTorsion (AddCircle p) := isOfFinAddOrder_rat

/-- The torsion subgroups exhaust a rational circle: every element lies in `(ℚ ⧸ pℤ)[n]` for some
positive `n`. Together with `AddCircle.eq_torsionBy_of_natCard_eq` this describes `ℚ/ℤ` as the
union of its unique subgroups of each finite order, a family directed by divisibility rather than
by the order on `ℕ` (`AddCircle.torsionBy_le_torsionBy_iff`). -/
theorem exists_mem_torsionBy_rat (u : AddCircle p) :
    ∃ n : ℕ, 0 < n ∧ u ∈ (AddCircle p)[(n : ℤ)] :=
  ⟨addOrderOf u, (isOfFinAddOrder_rat u).addOrderOf_pos,
    torsionBy.nsmul_iff.mpr (addOrderOf_nsmul_eq_zero u)⟩

end Rat

end AddCircle
