/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Induction.Artin
import Mathlib.GroupTheory.SpecificGroups.Cyclic
import TauCeti.RepresentationTheory.CharacterTable.Determined
import TauCeti.RepresentationTheory.CharacterTable.Galois

/-!
# Artin's fixed-point corollary for rational representations

A rational representation of a finite group is determined by the dimensions of its fixed spaces
under cyclic subgroups.  In character language the invariant attached to `C ≤ G` is the raw sum

`∑ c : C, χ(c) = |C| · dim V^C`.

The proof recovers character values by induction on the order of a group element.  Within the
cyclic group generated by `g`, all generators have the same value under a rational character:
after base change to `AlgebraicClosure ℚ`, every coprime power map is realized by a Galois
automorphism.  All nongenerators have smaller order, so their values are already known.  Equality
of the total sums over `⟨g⟩` therefore isolates the common value on its generators.  Character
determination over `ℚ` then gives the representation isomorphism.

## Main result

* `TauCeti.rat_rep_iso_of_res_cyclic`: two rational representations with equal character sums on
  every cyclic subgroup are isomorphic.
* `TauCeti.subgroupCharacterSum`: the character sum over a finite subgroup, with the finite
  structure chosen canonically up to proof irrelevance.
* `TauCeti.rat_rep_iso_of_finrank_invariants_cyclic`: the equivalent fixed-space-dimension
  formulation.

## References

This is the "Artin's corollary (rational representations)" target in Layer 6 of
`TauCetiRoadmap/RepresentationTheory/InductionRestriction/README.md`.

See J.-P. Serre, *Linear Representations of Finite Groups*, Part II, §9.2.
-/

public section

namespace TauCeti

open scoped BigOperators

universe u

/-- The sum of a finite-group character over a subgroup. -/
noncomputable def subgroupCharacterSum {k : Type*} {G : Type u} [Field k] [Group G]
    [Fintype G] (X : FDRep k G) (C : Subgroup G) : k := by
  let _ : Fintype C := Fintype.ofFinite C
  exact ∑ c : C, X.character (c : G)

/-- The subgroup character sum is the sum over any supplied `Fintype` structure on the
subgroup. -/
theorem subgroupCharacterSum_eq_sum {k : Type*} {G : Type u} [Field k] [Group G]
    [Fintype G] (X : FDRep k G) (C : Subgroup G) [Fintype C] :
    subgroupCharacterSum X C = ∑ c : C, X.character (c : G) := by
  classical
  unfold subgroupCharacterSum
  apply Finset.sum_congr
  · ext
    simp
  · intro
    simp

/-- The character sum over `C` is `|C|` times the dimension of the fixed space of the restricted
representation. -/
theorem subgroupCharacterSum_eq_card_mul_finrank_invariants
    {k : Type*} {G : Type u} [Field k] [CharZero k] [Group G] [Fintype G]
    (X : FDRep k G) (C : Subgroup G) :
    subgroupCharacterSum X C =
      (Nat.card C : k) * Module.finrank k (_root_.Representation.invariants (resFDRep C X).ρ) := by
  classical
  let _ : Fintype C := Fintype.ofFinite C
  let _ : Invertible (Nat.card C : k) :=
    invertibleOfNonzero (Nat.cast_ne_zero.mpr Nat.card_pos.ne')
  have hav := FDRep.average_char_eq_finrank_invariants (resFDRep C X)
  rw [subgroupCharacterSum_eq_sum]
  simp_rw [character_resFDRep] at hav
  calc
    ∑ c : C, X.character (c : G) =
        (Nat.card C : k) * ((Nat.card C : k)⁻¹ * ∑ c : C, X.character (c : G)) := by
      rw [← mul_assoc, mul_inv_cancel₀ (Nat.cast_ne_zero.mpr Nat.card_pos.ne'), one_mul]
    _ = (Nat.card C : k) *
        Module.finrank k (_root_.Representation.invariants (resFDRep C X).ρ) := by rw [hav]

private noncomputable instance subgroupFintype {G : Type u} [Group G] [Fintype G]
    (C : Subgroup G) : Fintype C := Fintype.ofFinite C

/-- A rational character has the same value on two elements that generate the same cyclic
subgroup. -/
private theorem character_eq_of_zpowers_eq {G : Type u} [Group G] [Finite G]
    (X : FDRep ℚ G) {g x : G} (h : Subgroup.zpowers x = Subgroup.zpowers g) :
    X.character x = X.character g := by
  have hx : x ∈ Submonoid.powers g :=
    mem_powers_iff_mem_zpowers.mpr <| h.le (Subgroup.mem_zpowers x)
  obtain ⟨j, rfl⟩ := hx
  have hord : orderOf (g ^ j) = orderOf g := by
    rw [← Nat.card_zpowers, h, Nat.card_zpowers]
  have hcop : (orderOf g).Coprime j := by
    rw [orderOf_pow] at hord
    exact Nat.coprime_iff_gcd_eq_one.mpr <|
      (Nat.div_eq_self.mp hord).resolve_left (orderOf_pos g).ne'
  let _ : NeZero (orderOf g) := ⟨(orderOf_pos g).ne'⟩
  exact X.character_pow_eq_character_of_coprime (pow_orderOf_eq_one g) hcop

/-- **Artin's fixed-point corollary.** A rational representation of a finite group is determined
by the sums of its character over the cyclic subgroups. Equivalently, since the sum over `C` is
`|C|` times the dimension of the `C`-fixed space, it is determined by those fixed-space
dimensions. -/
theorem rat_rep_iso_of_res_cyclic {G : Type u} [Group G] [Fintype G] (V W : FDRep ℚ G)
    (h : ∀ C : Subgroup G, IsCyclic C →
      subgroupCharacterSum V C = subgroupCharacterSum W C) :
    Nonempty (V ≅ W) := by
  classical
  apply FDRep.nonempty_iso_of_character_eq V W
  funext g
  have hchar : ∀ n : ℕ, ∀ x : G, orderOf x = n → V.character x = W.character x := by
    intro n
    induction n using Nat.strong_induction_on with
    | h n ih =>
      intro x hx
      let C := Subgroup.zpowers x
      let generators : Finset C := Finset.univ.filter fun c ↦ orderOf (c : G) = n
      have hsum : ∑ c : C, (V.character (c : G) - W.character (c : G)) = 0 := by
        rw [Finset.sum_sub_distrib, ← subgroupCharacterSum_eq_sum,
          ← subgroupCharacterSum_eq_sum,
          h C (by change IsCyclic (Subgroup.zpowers x); infer_instance), sub_self]
      have hterm (c : C) : V.character (c : G) - W.character (c : G) =
          if orderOf (c : G) = n then V.character x - W.character x else 0 := by
        split_ifs with hc
        · have hzpowers : Subgroup.zpowers (c : G) = Subgroup.zpowers x := by
            have heq := Subgroup.eq_of_le_of_card_ge (Subgroup.zpowers_le.mpr c.property) (by
              rw [Nat.card_zpowers, Nat.card_zpowers, hc, hx])
            simpa [C] using heq
          rw [character_eq_of_zpowers_eq V hzpowers,
            character_eq_of_zpowers_eq W hzpowers]
        · have hlt : orderOf (c : G) < n := by
            apply lt_of_le_of_ne
            · rw [← hx]
              exact Nat.le_of_dvd (orderOf_pos x) (orderOf_dvd_of_mem_zpowers c.property)
            · exact hc
          rw [ih (orderOf (c : G)) hlt (c : G) rfl, sub_self]
      have hgen : (⟨x, Subgroup.mem_zpowers x⟩ : C) ∈ generators := by
        simp only [generators, Finset.mem_filter, Finset.mem_univ, true_and, hx]
      have hcard : generators.card ≠ 0 := Finset.card_ne_zero.mpr ⟨_, hgen⟩
      have hmul : (generators.card : ℚ) * (V.character x - W.character x) = 0 := by
        have hsum_eq :
            ∑ c : C, (V.character (c : G) - W.character (c : G)) =
              ∑ c : C, if orderOf (c : G) = n then
                V.character x - W.character x else 0 :=
          Finset.sum_congr rfl fun c _ ↦ hterm c
        have hfilter :
            (∑ c : C, if orderOf (c : G) = n then
                V.character x - W.character x else 0) =
              (generators.card : ℚ) * (V.character x - W.character x) := by
          rw [← Finset.sum_filter, Finset.sum_const, nsmul_eq_mul]
        rw [← hfilter, ← hsum_eq]
        exact hsum
      exact sub_eq_zero.mp <| (mul_eq_zero.mp hmul).resolve_left (Nat.cast_ne_zero.mpr hcard)
  exact hchar (orderOf g) g rfl

/-- **Artin's fixed-point corollary, in invariant-space form.** Two rational representations are
isomorphic when the dimensions of their fixed spaces agree on every cyclic subgroup. -/
theorem rat_rep_iso_of_finrank_invariants_cyclic {G : Type u} [Group G] [Finite G]
    (V W : FDRep ℚ G)
    (h : ∀ C : Subgroup G, IsCyclic C →
      Module.finrank ℚ (_root_.Representation.invariants (resFDRep C V).ρ) =
        Module.finrank ℚ (_root_.Representation.invariants (resFDRep C W).ρ)) :
    Nonempty (V ≅ W) := by
  let _ : Fintype G := Fintype.ofFinite G
  apply rat_rep_iso_of_res_cyclic V W
  intro C hC
  rw [subgroupCharacterSum_eq_card_mul_finrank_invariants,
    subgroupCharacterSum_eq_card_mul_finrank_invariants, h C hC]

end TauCeti
