/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.FunctionField.Different.Derivative
public import TauCeti.FieldTheory.Galois.Minpoly

/-!
# The different exponent of a monogenic Galois extension

Suppose the integral closure of the valuation ring at a place is generated by one element `x`.
For a finite Galois extension, the derivative of the minimal polynomial of `x` is the product of
the displacements `x - σ x` over the nonidentity automorphisms.  Taking the place order gives

`d(P' | P) = ∑_{σ ≠ 1} ord_{P'}(x - σ x)`.

This is the local form of Hilbert's different formula needed for explicit ramification
computations.  In particular, a generating uniformizer at a totally ramified place supplies the
monogenic hypothesis.

## References

* J.-P. Serre, *Local Fields*, Chapter IV, §1.
-/

public section

open Polynomial
open scoped IntermediateField

namespace TauCeti.Place

universe u u' v v'

variable {k : Type u} {k' : Type u'} {F : Type v} {F' : Type v'}
variable [Field k] [Field k'] [Field F] [Field F']
variable [Algebra k k'] [Algebra k F] [Algebra k' F'] [Algebra F F'] [Algebra k F']
variable [IsScalarTower k k' F'] [IsScalarTower k F F']
variable [FiniteDimensional F F'] [IsGalois F F']

attribute [local instance 10] algebraIntegersExtension isScalarTowerIntegersExtension

variable (k F) {P' : Place k' F'}

/-- If an element generates the integral closure of a valuation ring in a finite Galois
extension, the different exponent is the sum of the orders of its nontrivial Galois
displacements. -/
theorem differentExponent_eq_sum_ord_sub_aut_of_algebra_adjoin_eq_top
    [DecidableEq (F' ≃ₐ[F] F')]
    {x : integralClosure (P'.restrict k F).integers F'}
    (hx : Algebra.adjoin (P'.restrict k F).integers {x} = ⊤) :
    (differentExponent k F P' : ℤ) =
      ∑ σ ∈ (Finset.univ : Finset (F' ≃ₐ[F] F')).erase 1,
        P'.ord (algebraMap (integralClosure (P'.restrict k F).integers F') F' x -
          σ (algebraMap (integralClosure (P'.restrict k F).integers F') F' x)) := by
  classical
  let z : F' := algebraMap (integralClosure (P'.restrict k F).integers F') F' x
  have hzgen : F⟮z⟯ = ⊤ :=
    TauCeti.IntermediateField.adjoin_eq_top_of_algebra_adjoin_eq_top hx
  have hinj : Function.Injective fun σ : F' ≃ₐ[F] F' ↦ σ z := fun σ τ h ↦
    AlgEquiv.coe_toAlgHom_injective <| AlgHom.ext_of_adjoin_eq_top
      ((IntermediateField.adjoin_eq_top_iff_of_isAlgebraic
        fun y _ ↦ IsAlgebraic.of_finite F y).1 hzgen) (Set.eqOn_singleton.2 h)
  have hne : ∀ σ ∈ (Finset.univ : Finset (F' ≃ₐ[F] F')).erase 1, z - σ z ≠ 0 := by
    intro σ hσ hzero
    have hσ1 : σ = 1 := hinj (by simpa using (sub_eq_zero.mp hzero).symm)
    exact (Finset.ne_of_mem_erase hσ) hσ1
  rw [differentExponent_eq_ord_aeval_derivative_minpoly k F hx,
    TauCeti.aeval_derivative_minpoly_eq_prod_of_adjoin_eq_top hzgen,
    P'.ord_prod _ hne]

end TauCeti.Place
