/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.MvPolynomial.Monad
public import Mathlib.Basic.Sign.Defs
public import Mathlib.Logic.Equiv.Fin.Basic
public import Mathlib.MeasureTheory.SetAlgebra

/-!
# Semialgebraic sets

A subset of `σ → R`, for an ordered commutative ring `R`, is *semialgebraic* when it is a finite
Boolean combination of polynomial zero sets `{x | p(x) = 0}` and positivity sets
`{x | 0 < p(x)}`. We define `TauCeti.IsSemialgebraic` as membership in the algebra of sets
(`MeasureTheory.generateSetAlgebra`) generated by these basic sets. This is the intrinsic,
quantifier-free definition: closure under coordinate projection is the Tarski–Seidenberg theorem,
a consequence of cylindrical algebraic decomposition, and is not built into the definition.

Every closure property proved here follows directly from the definition:

* the Boolean operations, including finite unions and intersections;
* every polynomial sign condition, such as `{x | p(x) ≤ q(x)}` or `{x | sign p(x) = ε}`;
* inverse images under polynomial maps (`TauCeti.IsSemialgebraic.preimage_eval`), and hence
  under changes of coordinates, in particular coordinate permutations;
* products, in the form `σ ⊕ τ → R` and in the form `Fin (m + n) → R`;
* the sections `{x | Fin.cons t x ∈ s}` and `{t | Fin.cons t x ∈ s}` of a subset of
  `Fin (n + 1) → R`, which are the horizontal and vertical slices of a cylinder over `Fin n → R`
  with distinguished coordinate `0`.

## References

S. Basu, R. Pollack, and M.-F. Roy,
[Algorithms in Real Algebraic Geometry](https://doi.org/10.1007/3-540-33099-2),
second edition, Chapter 2, for semi-algebraic sets.
-/

public section

open MvPolynomial MeasureTheory Set

namespace TauCeti

variable {σ τ R : Type*} [CommRing R] [LinearOrder R]

/-- A set `s ⊆ σ → R` is *semialgebraic* if it belongs to the algebra of sets (closed under
complements and finite unions) generated by the polynomial zero sets `{x | p(x) = 0}` and the
positivity sets `{x | 0 < p(x)}`, for `p : MvPolynomial σ R`. -/
def IsSemialgebraic (s : Set (σ → R)) : Prop :=
  s ∈ generateSetAlgebra
    (range (fun p : MvPolynomial σ R => {x | eval x p = 0}) ∪
      range (fun p : MvPolynomial σ R => {x | 0 < eval x p}))

/-- The zero set of a polynomial is semialgebraic. -/
theorem isSemialgebraic_eval_eq_zero (p : MvPolynomial σ R) :
    IsSemialgebraic {x : σ → R | eval x p = 0} :=
  self_subset_generateSetAlgebra (Or.inl ⟨p, rfl⟩)

/-- The positivity set of a polynomial is semialgebraic. -/
theorem isSemialgebraic_eval_pos (p : MvPolynomial σ R) :
    IsSemialgebraic {x : σ → R | 0 < eval x p} :=
  self_subset_generateSetAlgebra (Or.inr ⟨p, rfl⟩)

/-- The semialgebraic sets form an algebra of sets. -/
theorem isSetAlgebra_setOf_isSemialgebraic :
    IsSetAlgebra {s : Set (σ → R) | IsSemialgebraic s} :=
  isSetAlgebra_generateSetAlgebra

/-- The semialgebraic sets form the smallest algebra of sets containing every polynomial zero set
and every polynomial positivity set. -/
theorem setOf_isSemialgebraic_subset {ℬ : Set (Set (σ → R))} (hℬ : IsSetAlgebra ℬ)
    (eq_zero : ∀ p : MvPolynomial σ R, {x | eval x p = 0} ∈ ℬ)
    (pos : ∀ p : MvPolynomial σ R, {x | 0 < eval x p} ∈ ℬ) :
    {s : Set (σ → R) | IsSemialgebraic s} ⊆ ℬ :=
  hℬ.generateSetAlgebra_subset <| union_subset (range_subset_iff.2 eq_zero)
    (range_subset_iff.2 pos)

/-- Induction principle for semialgebraic sets: a property of sets that holds for polynomial zero
sets, polynomial positivity sets and the empty set, and is preserved by complements and binary
unions, holds for every semialgebraic set. -/
@[elab_as_elim]
theorem IsSemialgebraic.induction {motive : Set (σ → R) → Prop}
    (eq_zero : ∀ p : MvPolynomial σ R, motive {x | eval x p = 0})
    (pos : ∀ p : MvPolynomial σ R, motive {x | 0 < eval x p})
    (empty : motive ∅) (compl : ∀ s, IsSemialgebraic s → motive s → motive sᶜ)
    (union : ∀ s t, IsSemialgebraic s → IsSemialgebraic t → motive s → motive t →
      motive (s ∪ t))
    {s : Set (σ → R)} (hs : IsSemialgebraic s) : motive s := by
  refine (setOf_isSemialgebraic_subset (ℬ := {s | IsSemialgebraic s ∧ motive s})
    ⟨⟨isSetAlgebra_setOf_isSemialgebraic.empty_mem, empty⟩, fun s hs => ?_,
      fun s t hs ht => ?_⟩
    (fun p => ⟨isSemialgebraic_eval_eq_zero p, eq_zero p⟩)
    (fun p => ⟨isSemialgebraic_eval_pos p, pos p⟩) hs).2
  · exact ⟨isSetAlgebra_setOf_isSemialgebraic.compl_mem hs.1, compl s hs.1 hs.2⟩
  · exact ⟨isSetAlgebra_setOf_isSemialgebraic.union_mem hs.1 ht.1, union s t hs.1 ht.1 hs.2 ht.2⟩

/-! ### Boolean operations -/

@[simp]
theorem isSemialgebraic_empty : IsSemialgebraic (∅ : Set (σ → R)) :=
  isSetAlgebra_setOf_isSemialgebraic.empty_mem

@[simp]
theorem isSemialgebraic_univ : IsSemialgebraic (univ : Set (σ → R)) :=
  isSetAlgebra_setOf_isSemialgebraic.univ_mem

theorem IsSemialgebraic.compl {s : Set (σ → R)} (hs : IsSemialgebraic s) :
    IsSemialgebraic sᶜ :=
  isSetAlgebra_setOf_isSemialgebraic.compl_mem hs

theorem IsSemialgebraic.of_compl {s : Set (σ → R)} (hs : IsSemialgebraic sᶜ) :
    IsSemialgebraic s :=
  compl_compl s ▸ hs.compl

@[simp]
theorem isSemialgebraic_compl_iff {s : Set (σ → R)} :
    IsSemialgebraic sᶜ ↔ IsSemialgebraic s :=
  ⟨.of_compl, .compl⟩

theorem IsSemialgebraic.union {s t : Set (σ → R)} (hs : IsSemialgebraic s)
    (ht : IsSemialgebraic t) : IsSemialgebraic (s ∪ t) :=
  isSetAlgebra_setOf_isSemialgebraic.union_mem hs ht

theorem IsSemialgebraic.inter {s t : Set (σ → R)} (hs : IsSemialgebraic s)
    (ht : IsSemialgebraic t) : IsSemialgebraic (s ∩ t) :=
  isSetAlgebra_setOf_isSemialgebraic.inter_mem hs ht

theorem IsSemialgebraic.sdiff {s t : Set (σ → R)} (hs : IsSemialgebraic s)
    (ht : IsSemialgebraic t) : IsSemialgebraic (s \ t) :=
  isSetAlgebra_setOf_isSemialgebraic.sdiff_mem hs ht

/-- A finite union of semialgebraic sets is semialgebraic. -/
theorem IsSemialgebraic.biUnion {ι : Type*} {S : Set ι} (hS : S.Finite)
    {s : ι → Set (σ → R)} (hs : ∀ i ∈ S, IsSemialgebraic (s i)) :
    IsSemialgebraic (⋃ i ∈ S, s i) := by
  simpa using isSetAlgebra_setOf_isSemialgebraic.biUnion_mem hS.toFinset (by simpa using hs)

/-- A finite intersection of semialgebraic sets is semialgebraic. -/
theorem IsSemialgebraic.biInter {ι : Type*} {S : Set ι} (hS : S.Finite)
    {s : ι → Set (σ → R)} (hs : ∀ i ∈ S, IsSemialgebraic (s i)) :
    IsSemialgebraic (⋂ i ∈ S, s i) := by
  simpa using isSetAlgebra_setOf_isSemialgebraic.biInter_mem hS.toFinset (by simpa using hs)

/-- A union of finitely many semialgebraic sets is semialgebraic. -/
theorem IsSemialgebraic.iUnion {ι : Type*} [Finite ι] {s : ι → Set (σ → R)}
    (hs : ∀ i, IsSemialgebraic (s i)) : IsSemialgebraic (⋃ i, s i) := by
  simpa using IsSemialgebraic.biUnion finite_univ fun i _ => hs i

/-- An intersection of finitely many semialgebraic sets is semialgebraic. -/
theorem IsSemialgebraic.iInter {ι : Type*} [Finite ι] {s : ι → Set (σ → R)}
    (hs : ∀ i, IsSemialgebraic (s i)) : IsSemialgebraic (⋂ i, s i) := by
  simpa using IsSemialgebraic.biInter finite_univ fun i _ => hs i

/-! ### Polynomial sign conditions -/

theorem isSemialgebraic_eval_ne_zero (p : MvPolynomial σ R) :
    IsSemialgebraic {x : σ → R | eval x p ≠ 0} := by
  simpa only [compl_ofPred] using (isSemialgebraic_eval_eq_zero p).compl

theorem isSemialgebraic_eval_eq (p q : MvPolynomial σ R) :
    IsSemialgebraic {x : σ → R | eval x p = eval x q} := by
  simpa [sub_eq_zero] using isSemialgebraic_eval_eq_zero (p - q)

theorem isSemialgebraic_eval_nonpos (p : MvPolynomial σ R) :
    IsSemialgebraic {x : σ → R | eval x p ≤ 0} := by
  simpa only [compl_ofPred, not_lt] using (isSemialgebraic_eval_pos p).compl

variable [IsOrderedRing R]

theorem isSemialgebraic_eval_neg (p : MvPolynomial σ R) :
    IsSemialgebraic {x : σ → R | eval x p < 0} := by
  simpa using isSemialgebraic_eval_pos (-p)

theorem isSemialgebraic_eval_nonneg (p : MvPolynomial σ R) :
    IsSemialgebraic {x : σ → R | 0 ≤ eval x p} := by
  simpa only [compl_ofPred, not_lt] using (isSemialgebraic_eval_neg p).compl

theorem isSemialgebraic_eval_lt (p q : MvPolynomial σ R) :
    IsSemialgebraic {x : σ → R | eval x p < eval x q} := by
  simpa using isSemialgebraic_eval_pos (q - p)

theorem isSemialgebraic_eval_le (p q : MvPolynomial σ R) :
    IsSemialgebraic {x : σ → R | eval x p ≤ eval x q} := by
  simpa only [compl_ofPred, not_lt] using (isSemialgebraic_eval_lt q p).compl

/-- The set where a polynomial has a prescribed sign is semialgebraic. -/
theorem isSemialgebraic_sign_eval_eq (p : MvPolynomial σ R) (ε : SignType) :
    IsSemialgebraic {x : σ → R | SignType.sign (eval x p) = ε} := by
  rcases ε with _ | _ | _
  · simpa only [SignType.zero_eq_zero, sign_eq_zero_iff] using isSemialgebraic_eval_eq_zero p
  · simpa only [SignType.neg_eq_neg_one, sign_eq_neg_one_iff] using isSemialgebraic_eval_neg p
  · simpa only [SignType.pos_eq_one, sign_eq_one_iff] using isSemialgebraic_eval_pos p

/-! ### Finite sets -/

omit [IsOrderedRing R] in
/-- In finitely many coordinates, a point is semialgebraic. -/
theorem isSemialgebraic_singleton [Finite σ] (a : σ → R) :
    IsSemialgebraic ({a} : Set (σ → R)) := by
  have : ({a} : Set (σ → R)) = ⋂ i, {x | eval x (X i - C (a i)) = 0} := by
    ext x
    simp [funext_iff, sub_eq_zero]
  rw [this]
  exact .iInter fun i => isSemialgebraic_eval_eq_zero _

omit [IsOrderedRing R] in
/-- In finitely many coordinates, a finite set is semialgebraic. -/
theorem _root_.Set.Finite.isSemialgebraic [Finite σ] {s : Set (σ → R)} (hs : s.Finite) :
    IsSemialgebraic s := by
  simpa using IsSemialgebraic.biUnion hs fun a _ => isSemialgebraic_singleton a

/-! ### Inverse images and products -/

omit [IsOrderedRing R]

/-- The inverse image of a semialgebraic set under a polynomial map is semialgebraic. -/
theorem IsSemialgebraic.preimage_eval {s : Set (τ → R)} (hs : IsSemialgebraic s)
    (f : τ → MvPolynomial σ R) :
    IsSemialgebraic ((fun x i => eval x (f i)) ⁻¹' s) := by
  have hbind (x : σ → R) (p : MvPolynomial τ R) :
      eval (fun i => eval x (f i)) p = eval x (bind₁ f p) := by
    simp only [← coe_aeval_eq_eval]
    exact (aeval_bind₁ x f p).symm
  refine setOf_isSemialgebraic_subset (ℬ := {t | IsSemialgebraic ((fun x i => eval x (f i)) ⁻¹' t)})
    ⟨by simp, fun t ht => ?_, fun t u ht hu => ?_⟩ (fun p => ?_) (fun p => ?_) hs
  · simpa using ht.compl
  · simpa using ht.union hu
  · simpa [hbind] using isSemialgebraic_eval_eq_zero (bind₁ f p)
  · simpa [hbind] using isSemialgebraic_eval_pos (bind₁ f p)

/-- The inverse image of a semialgebraic set under a change of coordinates `x ↦ x ∘ f` is
semialgebraic. -/
theorem IsSemialgebraic.preimage_comp {s : Set (τ → R)} (hs : IsSemialgebraic s) (f : τ → σ) :
    IsSemialgebraic ((fun x : σ → R => x ∘ f) ⁻¹' s) := by
  simpa [Function.comp_def] using hs.preimage_eval fun i => X (f i)

/-- Semialgebraicity is invariant under a bijective change of coordinates, such as a coordinate
permutation. -/
@[simp]
theorem isSemialgebraic_preimage_comp_equiv {s : Set (τ → R)} (e : τ ≃ σ) :
    IsSemialgebraic ((fun x : σ → R => x ∘ e) ⁻¹' s) ↔ IsSemialgebraic s := by
  refine ⟨fun hs => ?_, fun hs => hs.preimage_comp e⟩
  convert hs.preimage_comp e.symm
  ext x
  simp [Function.comp_def]

/-- The product of semialgebraic sets, as a subset of `σ ⊕ τ → R`, is semialgebraic. -/
theorem IsSemialgebraic.preimage_sumArrowEquivProdArrow_prod {s : Set (σ → R)}
    {t : Set (τ → R)} (hs : IsSemialgebraic s) (ht : IsSemialgebraic t) :
    IsSemialgebraic (Equiv.sumArrowEquivProdArrow σ τ R ⁻¹' s ×ˢ t) :=
  (hs.preimage_comp Sum.inl).inter (ht.preimage_comp Sum.inr)

/-- The product of semialgebraic sets, as a subset of `Fin (m + n) → R`, is semialgebraic. -/
theorem IsSemialgebraic.image_appendEquiv_prod {m n : ℕ} {s : Set (Fin m → R)}
    {t : Set (Fin n → R)} (hs : IsSemialgebraic s) (ht : IsSemialgebraic t) :
    IsSemialgebraic (Fin.appendEquiv m n '' s ×ˢ t) := by
  rw [Equiv.image_eq_preimage_symm]
  exact (hs.preimage_comp (Fin.castAdd n)).inter (ht.preimage_comp (Fin.natAdd m))

/-- The horizontal section at height `t` of a semialgebraic subset of `Fin (n + 1) → R`, whose
distinguished coordinate is `0`, is semialgebraic. -/
theorem IsSemialgebraic.preimage_cons_left {n : ℕ} {s : Set (Fin (n + 1) → R)}
    (hs : IsSemialgebraic s) (t : R) :
    IsSemialgebraic {x : Fin n → R | Fin.cons t x ∈ s} := by
  have hf : (fun x i => eval x ((Fin.cons (C t) X : Fin (n + 1) → MvPolynomial (Fin n) R) i)) =
      fun x : Fin n → R => (Fin.cons t x : Fin (n + 1) → R) := by
    funext x i
    cases i using Fin.cases <;> simp
  have h := hs.preimage_eval (Fin.cons (C t) X : Fin (n + 1) → MvPolynomial (Fin n) R)
  rw [hf] at h
  exact h

/-- The vertical section over a base point `x` of a semialgebraic subset of `Fin (n + 1) → R`,
whose distinguished coordinate is `0`, is semialgebraic as a subset of `Fin 1 → R`. -/
theorem IsSemialgebraic.preimage_cons_right {n : ℕ} {s : Set (Fin (n + 1) → R)}
    (hs : IsSemialgebraic s) (x : Fin n → R) :
    IsSemialgebraic {y : Fin 1 → R | Fin.cons (y 0) x ∈ s} := by
  have hf : (fun y i => eval y
      ((Fin.cons (X 0) fun j => C (x j) : Fin (n + 1) → MvPolynomial (Fin 1) R) i)) =
      fun y : Fin 1 → R => (Fin.cons (y 0) x : Fin (n + 1) → R) := by
    funext y i
    cases i using Fin.cases <;> simp
  have h := hs.preimage_eval
    (Fin.cons (X 0) fun j => C (x j) : Fin (n + 1) → MvPolynomial (Fin 1) R)
  rw [hf] at h
  exact h

end TauCeti
