#!/usr/bin/env bash
# mk_all.sh — keep the root aggregator `TauCeti.lean` importing every module under
# `TauCeti/`, in sorted order. This is the same job as Mathlib's `lake exe mk_all`,
# but a tiny self-contained script: it preserves our doc header and needs no build.
#
#   Scripts/mk_all.sh [--check] [root]
#
#   (default)  rewrite <root>/TauCeti.lean in place so it is canonical.
#   --check    exit 1 (printing a diff) if <root>/TauCeti.lean is not already canonical.
#   root       repository root to operate on (default: the current directory).
#
# CI (.github/workflows/mk-all.yml) runs this on every PR and auto-commits the fix;
# ci.yml runs `--check` on main as a backstop. Agents may just run it before pushing.
set -uo pipefail

CHECK=0
case "${1:-}" in --check) CHECK=1; shift;; esac
ROOT="${1:-.}"
TARGET="$ROOT/TauCeti.lean"

# The canonical file: a fixed doc header, then `import` lines for every module under
# TauCeti/, sorted by byte order (LC_ALL=C) for a stable, locale-independent result.
gen() {
  cat <<'EOF'
-- This is the AI-owned root of the TauCeti mathematics library.
--
-- Everything reachable from here must be sorry-free, and must not import
-- `TauCetiRoadmap` or `TauCetiReview` (both enforced in CI).
--
-- This import list is generated by `Scripts/mk_all.sh` (every `TauCeti/` module,
-- sorted); CI keeps it in sync. Do not edit it by hand.
EOF
  ( cd "$ROOT" && find TauCeti -type f -name '*.lean' \
      | sed -e 's#\.lean$##' -e 's#/#.#g' | LC_ALL=C sort | sed 's#^#import #' )
}

if [ "$CHECK" = 1 ]; then
  if diff -u "$TARGET" <(gen); then
    echo "TauCeti.lean is up to date."
  else
    echo "::error::TauCeti.lean is out of date — run \`Scripts/mk_all.sh\` to regenerate it"
    exit 1
  fi
else
  gen > "$TARGET"
  echo "wrote $TARGET"
fi
