/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Presentation.Finiteness
import Mathlib.Algebra.Group.TypeTags.Finite
import Mathlib.Data.Fin.VecNotation
import Mathlib.Data.ZMod.Basic

/-!
# Recognition of a presented group from a coset certificate

Generator images satisfying the transcribed relators define `GroupPresentation.toGroup`.
Its image is exactly the subgroup generated by those images.

A `GroupPresentation.CosetCertificate` for a finite subgroup supplies a finite upper bound
for the exact presented group. When the generated model has at least that many elements,
the presentation map is bijective. `CosetCertificate.mulEquiv` recognizes a model with
proved generation; `CosetCertificate.mulEquivRange` recognizes the generated image inside
an ambient group. Both equivalences retain the specified generator images.

These are the upper-bound/lower-bound bridges for CFSG basic properties P0. Relator
evaluation and a large image alone are not used to infer finiteness of the presentation.
-/

public section

namespace TauCeti.GroupPresentation

variable (P : GroupPresentation) {G : Type*} [_root_.Group G] (f : Fin P.generatorCount → G)
  (h : ∀ r ∈ P.transcribed, FreeGroup.lift f r.toFreeGroup = 1)

/-- Extend generator images satisfying the transcribed relators to the exact presented group. -/
def toGroup : P.Group →* G :=
  PresentedGroup.toGroup fun r hr ↦ by
    obtain ⟨t, ht, rfl⟩ := (P.mem_relatorSet_iff r).mp hr
    exact h t ht

/-- The presentation map has the specified generator images. -/
@[simp]
theorem toGroup_of (i : Fin P.generatorCount) :
    P.toGroup f h (PresentedGroup.of i) = f i :=
  PresentedGroup.toGroup.of _

/-- The image of the presentation map is precisely the subgroup generated by its generators. -/
theorem range_toGroup : (P.toGroup f h).range = Subgroup.closure (Set.range f) := by
  rw [← Subgroup.map_top, ← PresentedGroup.closure_range_of P.relatorSet,
    MonoidHom.map_closure, ← Set.range_comp]
  simp [Function.comp_def]

/-- Generation of a model is equivalent to surjectivity of the presentation map. -/
theorem surjective_toGroup_iff :
    Function.Surjective (P.toGroup f h) ↔ Subgroup.closure (Set.range f) = ⊤ := by
  rw [← MonoidHom.range_eq_top, P.range_toGroup f h]

namespace CosetCertificate

variable {P} {H : Subgroup P.Group} {k : ℕ} (C : P.CosetCertificate H k) [Finite H]
  (φ : P.Group →* G)

include C

/-- A generated model gives a lower bound once the certificate establishes finiteness. -/
theorem natCard_model_le (hφ : Function.Surjective φ) :
    Nat.card G ≤ Nat.card P.Group := by
  have := C.finite
  exact Nat.card_le_card_of_surjective _ hφ

/-- A surjective model map attaining the certified upper bound is an isomorphism.

For generator images, `GroupPresentation.surjective_toGroup_iff` supplies surjectivity
from generation. The map can also be any previously constructed presentation map. -/
noncomputable def mulEquiv (hφ : Function.Surjective φ)
    (hcard : Nat.card H * k ≤ Nat.card G) : P.Group ≃* G := by
  haveI := C.finite
  exact MulEquiv.ofBijective φ (hφ.bijective_of_nat_card_le (C.natCard_le.trans hcard))

/-- Recognition agrees with the supplied model map on every element. -/
@[simp]
theorem mulEquiv_apply (hφ : Function.Surjective φ)
    (hcard : Nat.card H * k ≤ Nat.card G) (x : P.Group) :
    C.mulEquiv φ hφ hcard x = φ x := by
  rw [mulEquiv]
  rfl

/-- Matching the model's lower bound certifies that the presentation map has trivial kernel. -/
theorem ker_eq_bot (hφ : Function.Surjective φ)
    (hcard : Nat.card H * k ≤ Nat.card G) : φ.ker = ⊥ := by
  apply φ.ker_eq_bot
  exact (C.mulEquiv φ hφ hcard).injective

/-- The order of the presented group equals the model's order after recognition. -/
theorem natCard_eq (hφ : Function.Surjective φ)
    (hcard : Nat.card H * k ≤ Nat.card G) : Nat.card P.Group = Nat.card G :=
  Nat.card_congr (C.mulEquiv φ hφ hcard).toEquiv

/-- Recognize the subgroup generated by the model generators inside any ambient group.

For `GroupPresentation.toGroup`, the range equals `Subgroup.closure (Set.range f)`
by `GroupPresentation.range_toGroup`. The ambient group need not be finite. -/
noncomputable def mulEquivRange
    (hcard : Nat.card H * k ≤ Nat.card φ.range) : P.Group ≃* φ.range :=
  C.mulEquiv φ.rangeRestrict φ.rangeRestrict_surjective hcard

/-- Recognition of the generated image retains the model map's values in the ambient group. -/
@[simp]
theorem coe_mulEquivRange_apply
    (hcard : Nat.card H * k ≤ Nat.card φ.range) (x : P.Group) :
    (C.mulEquivRange φ hcard x : G) = φ x := by
  simp [mulEquivRange]

end CosetCertificate

end TauCeti.GroupPresentation

end

/-! ### A complete two-row certificate

The presentation `⟨x | x² = 1⟩` is recognized as `Multiplicative (ZMod 2)`.
Removing the deductions makes the checker reject the certificate.
-/

namespace TauCeti.GroupPresentation


private abbrev involutionPresentation : GroupPresentation where
  generatorNames := ["x"]
  source := "Elementary cyclic presentation"
  sourceLocator := "One generator with its square as relator"
  generatorConvention := "x"
  transcriptionNotes := "No conversion"
  expectedGeneratorCount := 1
  expectedRelatorCount := 1
  transcribed := [.pow (.gen 0) 2]

private def involutionTable : CosetTable 2 2 where
  act := ![![1, 0], ![1, 0]]
  word := ![[], [0]]

private theorem involution_tableRelators :
    involutionPresentation.tableRelators = [[0, 0], [0, 1], [1, 0]] := by
  rw [tableRelators, relators_def]
  simp [involutionPresentation, PresentationWord.toTableWord, generatorCount, List.finRange_succ]

private def involutionCertificate :
    involutionPresentation.CosetCertificate ⊥ 2 where
  table := involutionTable
  subgroupWords := []
  deductions := [(0, [0, 0]), (0, [1, 0]), (1, [1, 0])]
  checked := by
    rw [involution_tableRelators]
    decide +kernel
  subgroupWords_mem := by simp

example : Finite involutionPresentation.Group :=
  involutionCertificate.finite

example : Nat.card involutionPresentation.Group ≤ 2 := by
  simpa using involutionCertificate.natCard_le

example : involutionTable.check involutionPresentation.tableRelators [] [] = false := by
  rw [involution_tableRelators]
  decide +kernel

private def involutionImages :
    Fin involutionPresentation.generatorCount → Multiplicative (ZMod 2) :=
  fun _ ↦ Multiplicative.ofAdd 1

private theorem involution_relations :
    ∀ r ∈ involutionPresentation.transcribed,
      FreeGroup.lift involutionImages r.toFreeGroup = 1 := by
  change ∀ r ∈ [Relator.pow (Relator.gen (0 : Fin 1)) 2], _ = 1
  simp only [List.mem_cons, List.not_mem_nil, or_false]
  rintro r rfl
  simp only [Relator.toFreeGroup_pow, Relator.toFreeGroup_gen, map_pow,
    FreeGroup.lift_apply_of]
  decide +kernel

private theorem involution_generation :
    Subgroup.closure (Set.range involutionImages) = ⊤ := by
  apply top_unique
  intro x _
  have hx : ∀ x : Multiplicative (ZMod 2), x = 1 ∨ x = involutionImages 0 := by
    decide +kernel
  rcases hx x with rfl | rfl
  · exact Subgroup.one_mem _
  · exact Subgroup.subset_closure ⟨0, rfl⟩

private noncomputable def involutionEquiv :
    involutionPresentation.Group ≃* Multiplicative (ZMod 2) :=
  involutionCertificate.mulEquiv
    (involutionPresentation.toGroup involutionImages involution_relations)
    ((involutionPresentation.surjective_toGroup_iff _ _).mpr involution_generation)
    (by simp [Nat.card_eq_fintype_card])

example : Nat.card involutionPresentation.Group = 2 := by
  simpa [Nat.card_eq_fintype_card] using Nat.card_congr involutionEquiv.toEquiv

example :
    involutionEquiv (PresentedGroup.of 0) = Multiplicative.ofAdd (1 : ZMod 2) := by
  simp [involutionEquiv, involutionImages]

example : (involutionPresentation.toGroup involutionImages involution_relations).ker = ⊥ :=
  involutionCertificate.ker_eq_bot _
    ((involutionPresentation.surjective_toGroup_iff _ _).mpr involution_generation)
    (by simp [Nat.card_eq_fintype_card])

end TauCeti.GroupPresentation
