/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Geometry.Manifold.Foliation.Basic
public import TauCeti.Geometry.Manifold.MFDeriv.Curve
public import Mathlib.Topology.Connected.PathConnected
import Mathlib.Analysis.Calculus.MeanValue
import Mathlib.Analysis.LocallyConvex.HahnBanach

/-!
# Leaves of a foliation

The leaves of a foliation of a real manifold are the maximal connected integral manifolds of its
tangent distribution. This file defines them through the curves tangent to the foliation: two
points lie on the same leaf when they are joined by a finite chain of curves, each `C¹` on a
compact interval, whose velocities lie in the tangent distribution. On a boundaryless real
manifold modelled on a finite-dimensional space the Frobenius theorem, which is not proved here,
supplies flat charts in which a curve tangent to the foliation has locally constant transverse
coordinates, so that this relation recovers the leaves in the chart sense; conversely, any two
points of a connected integral manifold are joined by such a chain inside it.

The leaves partition the manifold, and each leaf is path-connected. For the foliation of a real
normed space `E` by the translates of a finite-dimensional subspace `S`, the leaf through `x` is
the affine subspace `x + S`.

Leaves are the objects that tautness of a codimension-one foliation (a closed transversal meeting
every leaf) and the Euler-class bound on its leaves refer to.

## Main definitions

* `TauCeti.Foliation.JoinedByTangentCurve F x y`: some curve, `C¹` on `[0, 1]`, runs from `x` to
  `y` with velocity in the tangent distribution of `F` throughout.
* `TauCeti.Foliation.SameLeaf F`: the equivalence relation generated by `JoinedByTangentCurve F`.
* `TauCeti.Foliation.leaf F x`: the leaf of `F` through `x`.

## Main results

* `TauCeti.Foliation.sameLeaf_equivalence`: lying on the same leaf is an equivalence relation, and
  `TauCeti.Foliation.sameLeaf_le` says it is the least one relating the ends of tangent curves.
* `TauCeti.Foliation.sameLeaf_of_contMDiffOn`: a curve tangent to `F` on a compact interval stays
  in one leaf.
* `TauCeti.Foliation.leaf_eq_leaf_iff` and `TauCeti.Foliation.disjoint_leaf_iff`: two leaves are
  equal or disjoint.
* `TauCeti.Foliation.isPathConnected_leaf`: every leaf is path-connected.
* `TauCeti.Foliation.leaf_ofSubmodule`: the leaves of the foliation of `E` by the translates of `S`
  are these translates.

## References

* J. M. Lee, *Introduction to Smooth Manifolds*, 2nd ed., Springer GTM 218 (2013), Chapter 19
  (integral manifolds, the Frobenius theorem, and the leaves of a foliation).
* A. Candel, L. Conlon, *Foliations I*, AMS GSM 23 (2000), Chapter 1.
-/

public section

noncomputable section

open Set
open TauCeti.Manifold
open scoped Manifold ContDiff

namespace TauCeti

namespace Foliation

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H} {n : ℕ∞ω}
  {M : Type*} [TopologicalSpace M] [ChartedSpace H M] {k : ℕ} [IsManifold I (n + 1) M]
  (F : Foliation I n M k)

/-- The points `x` and `y` are the ends of a curve tangent to the foliation `F`: some curve `γ`,
`C¹` on `[0, 1]`, runs from `γ 0 = x` to `γ 1 = y`, and at every parameter of `[0, 1]` its velocity
within `[0, 1]` lies in the tangent space of `F`. -/
def JoinedByTangentCurve (x y : M) : Prop :=
  ∃ γ : ℝ → M, ContMDiffOn 𝓘(ℝ, ℝ) I 1 γ (Icc 0 1) ∧
    (∀ t ∈ Icc (0 : ℝ) 1, curveVelocityWithin I γ (Icc 0 1) t ∈ F.distribution (γ t)) ∧
    γ 0 = x ∧ γ 1 = y

/-- The points `x` and `y` lie on the same leaf of the foliation `F`: they are related by the
equivalence relation generated by `JoinedByTangentCurve F`, that is, joined by a finite chain of
curves tangent to `F`. -/
def SameLeaf (x y : M) : Prop :=
  Relation.EqvGen F.JoinedByTangentCurve x y

/-- The leaf of the foliation `F` through `x`: the points lying on the same leaf as `x`. -/
def leaf (x : M) : Set M :=
  {y | F.SameLeaf x y}

variable {F} {x y z : M}

/-- The ends of a curve tangent to `F` lie on the same leaf. -/
theorem JoinedByTangentCurve.sameLeaf (h : F.JoinedByTangentCurve x y) : F.SameLeaf x y :=
  .rel _ _ h

variable (F) in
/-- Lying on the same leaf of `F` is an equivalence relation. -/
theorem sameLeaf_equivalence : Equivalence F.SameLeaf :=
  Relation.EqvGen.is_equivalence _

/-- Lying on the same leaf of `F` is the least equivalence relation relating the ends of every curve
tangent to `F`. -/
theorem sameLeaf_le {r : M → M → Prop} (hr : Equivalence r) (h : F.JoinedByTangentCurve ≤ r) :
    F.SameLeaf ≤ r := by
  have := hr.isEquiv
  exact Relation.EqvGen.eqvGen_le h

variable (F) in
/-- Every point lies on its own leaf. -/
@[refl]
theorem SameLeaf.refl (x : M) : F.SameLeaf x x :=
  (sameLeaf_equivalence F).refl x

/-- Every point lies on its own leaf; `SameLeaf.refl` with the point implicit. -/
theorem SameLeaf.rfl : F.SameLeaf x x :=
  SameLeaf.refl F x

/-- Lying on the same leaf is symmetric. -/
@[symm]
theorem SameLeaf.symm (h : F.SameLeaf x y) : F.SameLeaf y x :=
  (sameLeaf_equivalence F).symm h

/-- Lying on the same leaf is transitive. -/
@[trans]
theorem SameLeaf.trans (hxy : F.SameLeaf x y) (hyz : F.SameLeaf y z) : F.SameLeaf x z :=
  (sameLeaf_equivalence F).trans hxy hyz

/-- Lying on the same leaf is symmetric, as an equivalence. -/
theorem sameLeaf_comm : F.SameLeaf x y ↔ F.SameLeaf y x :=
  ⟨SameLeaf.symm, SameLeaf.symm⟩

/-- The leaf through `x` consists of the points lying on the same leaf as `x`. -/
@[simp]
theorem mem_leaf : y ∈ F.leaf x ↔ F.SameLeaf x y :=
  Iff.rfl

variable (F) in
/-- Every point lies on the leaf through it. -/
theorem mem_leaf_self (x : M) : x ∈ F.leaf x :=
  SameLeaf.refl F x

/-- Two leaves are equal exactly when their base points lie on the same leaf. -/
theorem leaf_eq_leaf_iff : F.leaf x = F.leaf y ↔ F.SameLeaf x y := by
  refine ⟨fun h ↦ ?_, fun h ↦ Set.ext fun z ↦ ⟨h.symm.trans, h.trans⟩⟩
  rw [← mem_leaf, h]
  exact mem_leaf_self F y

/-- The leaf through any point of a leaf is that leaf. -/
theorem leaf_eq_of_mem (h : y ∈ F.leaf x) : F.leaf y = F.leaf x :=
  leaf_eq_leaf_iff.mpr h.symm

/-- Two leaves are disjoint exactly when their base points do not lie on the same leaf; so the
leaves of a foliation partition the manifold. -/
theorem disjoint_leaf_iff : Disjoint (F.leaf x) (F.leaf y) ↔ ¬ F.SameLeaf x y := by
  refine ⟨fun h hxy ↦ ?_, fun h ↦ Set.disjoint_left.mpr fun z hxz hyz ↦ h (hxz.trans hyz.symm)⟩
  exact Set.disjoint_left.mp h hxy (mem_leaf_self F y)

/-- A curve which is `C¹` on a compact interval `[a, b]` and tangent to `F` there stays in one leaf
of `F`. -/
theorem sameLeaf_of_contMDiffOn {γ : ℝ → M} {a b s t : ℝ}
    (hγ : ContMDiffOn 𝓘(ℝ, ℝ) I 1 γ (Icc a b))
    (htan : ∀ u ∈ Icc a b, curveVelocityWithin I γ (Icc a b) u ∈ F.distribution (γ u))
    (hs : s ∈ Icc a b) (ht : t ∈ Icc a b) : F.SameLeaf (γ s) (γ t) := by
  -- Each point `γ t` is joined to `γ a` by the reparametrization `γ (a + u (t - a))`, `u ∈ [0, 1]`.
  suffices key : ∀ t ∈ Icc a b, F.SameLeaf (γ a) (γ t) from (key s hs).symm.trans (key t ht)
  intro t ht
  set φ : ℝ → ℝ := fun u ↦ a + u * (t - a) with hφ_def
  have hmaps : MapsTo φ (Icc 0 1) (Icc a b) := by
    intro u hu
    simp only [hφ_def, mem_Icc] at hu ht ⊢
    constructor <;> nlinarith
  have hφ : ContDiff ℝ 1 φ := by fun_prop
  refine JoinedByTangentCurve.sameLeaf ⟨γ ∘ φ, hγ.comp hφ.contMDiff.contMDiffOn hmaps, ?_, ?_, ?_⟩
  · intro u hu
    have hderiv : HasDerivWithinAt φ (t - a) (Icc 0 1) u := by
      have := ((hasDerivAt_id u).mul_const (t - a)).const_add a
      rw [one_mul] at this
      exact this.hasDerivWithinAt
    rw [curveVelocityWithin_comp hderiv hmaps
      ((hγ.mdifferentiableOn one_ne_zero) (φ u) (hmaps hu))
      (uniqueDiffOn_Icc zero_lt_one u hu)]
    exact Submodule.smul_mem _ _ (htan (φ u) (hmaps hu))
  · simp [hφ_def]
  · simp [hφ_def]

variable (F) in
/-- Every leaf of a foliation is path-connected. -/
theorem isPathConnected_leaf (x : M) : IsPathConnected (F.leaf x) := by
  -- Each generating curve joins its ends inside the leaf it lies on, and joining is transported
  -- along the generated equivalence relation because equivalent points have the same leaf.
  suffices key : ∀ y z, F.SameLeaf y z → JoinedIn (F.leaf y) y z from
    ⟨x, mem_leaf_self F x, fun _ hy ↦ key _ _ hy⟩
  intro y z h
  induction h with
  | rel y z h =>
    obtain ⟨γ, hγ, htan, rfl, rfl⟩ := h
    refine JoinedIn.ofLine hγ.continuousOn rfl rfl ?_
    rintro _ ⟨t, ht, rfl⟩
    exact sameLeaf_of_contMDiffOn hγ htan (left_mem_Icc.mpr zero_le_one) ht
  | refl y => exact JoinedIn.refl (mem_leaf_self F y)
  | symm y z h ih =>
    rw [leaf_eq_of_mem h]
    exact ih.symm
  | trans y z w hyz _ ihyz ihzw =>
    rw [leaf_eq_of_mem hyz] at ihzw
    exact ihyz.trans ihzw

section ofSubmodule

variable (S : Submodule ℝ E) [FiniteDimensional ℝ S] (hn : 1 ≤ n) {x y : E}

/-- In the foliation of `E` by the translates of `S`, two points lie on the same leaf exactly when
their difference lies in `S`. -/
@[simp]
theorem sameLeaf_ofSubmodule_iff : (ofSubmodule S hn).SameLeaf x y ↔ y - x ∈ S := by
  constructor
  · -- A curve with velocity in `S` has constant image under a projection killing exactly `S`.
    obtain ⟨P, hP⟩ := Submodule.ClosedComplemented.of_finiteDimensional S
    set q : E →L[ℝ] E := ContinuousLinearMap.id ℝ E - S.subtypeL.comp P with hq_def
    have hq : ∀ v, q v = 0 ↔ v ∈ S := by
      intro v
      simp only [hq_def, FunLike.coe_sub, Pi.sub_apply, ContinuousLinearMap.id_apply,
        ContinuousLinearMap.comp_apply, Submodule.subtypeL_apply, sub_eq_zero]
      refine ⟨fun h ↦ h ▸ (P v).2, fun hv ↦ ?_⟩
      rw [hP ⟨v, hv⟩]
    have hr : Equivalence fun x y : E ↦ y - x ∈ S :=
      ⟨fun x ↦ by simp, fun h ↦ by simpa using S.neg_mem h,
        fun hxy hyz ↦ by simpa using S.add_mem hyz hxy⟩
    refine fun h ↦ sameLeaf_le hr (fun x y hxy ↦ ?_) x y h
    obtain ⟨γ, hγ, htan, rfl, rfl⟩ := hxy
    have hdiff : DifferentiableOn ℝ γ (Icc 0 1) :=
      (contMDiffOn_iff_contDiffOn.mp hγ).differentiableOn one_ne_zero
    have hconst := constant_of_derivWithin_zero (q.differentiable.comp_differentiableOn hdiff)
      (fun u hu ↦ ?_) 1 (right_mem_Icc.mpr zero_le_one)
    · rw [← hq, map_sub, sub_eq_zero]
      exact hconst
    · have hu' : u ∈ Icc (0 : ℝ) 1 := Ico_subset_Icc_self hu
      rw [(q.hasFDerivAt.comp_hasDerivWithinAt u
        ((hdiff u hu').hasDerivWithinAt)).derivWithin (uniqueDiffOn_Icc zero_lt_one u hu'),
        hq]
      have hmem := htan u hu'
      rw [curveVelocityWithin_eq_derivWithin, ofSubmodule_distribution] at hmem
      -- The tangent space of the model `𝓘(ℝ, E)` is `E` by definition.
      exact hmem
  · -- The straight segment from `x` to `y` has constant velocity `y - x ∈ S`.
    intro h
    refine JoinedByTangentCurve.sameLeaf ⟨fun t ↦ x + t • (y - x), ?_, fun t ht ↦ ?_, ?_, ?_⟩
    · exact (contDiff_const.add (contDiff_id.smul contDiff_const)).contMDiff.contMDiffOn
    · have hderiv : HasDerivWithinAt (fun t : ℝ ↦ x + t • (y - x)) (y - x) (Icc 0 1) t := by
        simpa using ((hasDerivAt_id t).smul_const (y - x)).const_add x |>.hasDerivWithinAt
      have := hderiv.derivWithin (uniqueDiffOn_Icc zero_lt_one t ht)
      rw [curveVelocityWithin_eq_derivWithin, this, ofSubmodule_distribution]
      -- The tangent space of the model `𝓘(ℝ, E)` is `E` by definition.
      exact h
    · simp
    · simp

/-- The leaf through `x` of the foliation of `E` by the translates of `S` is the translate
`x + S`. -/
@[simp]
theorem leaf_ofSubmodule (x : E) : (ofSubmodule S hn).leaf x = {y | y - x ∈ S} :=
  Set.ext fun _ ↦ sameLeaf_ofSubmodule_iff S hn

end ofSubmodule

end Foliation

end TauCeti
