/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Geometry.Convex.Cone.Alternative
public import TauCeti.Geometry.Toric.Algebraic.DualSemigroup.Face
public import TauCeti.Geometry.Toric.Algebraic.Fan.Basic

/-!
# The separation lemma for toric cones

Let `σ` and `τ` be lattice-rational cones meeting in a common face `σ ⊓ τ`, as any two cones of a
fan do. The *separation lemma* produces an integral character `m` that is nonnegative on `σ`,
nonpositive on `τ`, and vanishes on either cone exactly along `σ ⊓ τ`. Its proof applies Tucker's
theorem over the integers to the lattice generators of `σ` together with the negatives of those of
`τ`. The theorem gives a character nonnegative on this family and a relation among its members with
natural-number coefficients, where every generator on which the character vanishes has a positive
coefficient in the relation. The relation exhibits a vector of `σ ⊓ τ` as a positive combination
of all such generators of `σ`, so each of them lies in the face `σ ⊓ τ`, and likewise for `τ`.

Consequently the dual semigroup of `σ ⊓ τ` is generated by the dual semigroups of `σ` and `τ`: by
`TauCeti.Toric.dualSemigroup_inf_ker_eq_sup` it is obtained from that of `σ` by adjoining `-m`,
which lies in the dual semigroup of `τ`. In terms of affine toric charts, the chart of `σ ⊓ τ` is
cut out of the product of the charts of `σ` and `τ` by the relations among monomials. This is the
input for the separatedness of toric varieties and the Hausdorff property of their complex points.

## Main declarations

* `TauCeti.Toric.exists_mem_dualSemigroup_neg_mem_dualSemigroup_inf_ker_eq`: the separation
  lemma.
* `TauCeti.Toric.dualSemigroup_inf_eq_sup`: the dual semigroup of `σ ⊓ τ` is generated by those
  of `σ` and `τ`.
* `TauCeti.Toric.Fan.dualSemigroup_inf_eq_sup`: the same for two cones of a fan.

## References

* W. Fulton, *Introduction to Toric Varieties*, §1.2 (the separation lemma) and §1.4.
* D. Cox, J. Little and H. Schenck, *Toric Varieties*, §1.2 (the separation lemma) and §3.1.
* A. W. Tucker, *Dual systems of homogeneous linear relations*, in *Linear Inequalities and
  Related Systems*, Annals of Mathematics Studies 38, 1956.
-/

public section

namespace TauCeti.Toric

variable {N V : Type*} [AddCommGroup N] [AddCommGroup V] [Module ℝ V]
  {i : N →+ V} {σ τ : PointedCone ℝ V}

/-- One half of the separation lemma. Let `F` be a face of the cone generated by the lattice
vectors in `s`, and let `m` be a character nonnegative on `s` and vanishing on `F`. If some
combination of the generators with natural coefficients lies in `F`, with a positive coefficient
at every generator on which `m` vanishes, then `m` cuts out exactly `F`. -/
private theorem hull_inf_ker_eq_of_sum_nsmul_mem (hi : IsIntegralLattice i) {s : Finset N}
    {F : PointedCone ℝ V} (hF : F.IsFaceOf (PointedCone.hull ℝ (i '' s))) {m : N →+ ℤ}
    (hm : ∀ a ∈ s, 0 ≤ m a) (hmF : ∀ v ∈ F, hi.realCharacter m v = 0) (c : s → ℕ)
    (hc : ∑ a : s, c a • i a ∈ F) (hpos : ∀ a : s, m a = 0 → 0 < c a) :
    PointedCone.hull ℝ (i '' s) ⊓ PointedCone.ofSubmodule (LinearMap.ker (hi.realCharacter m)) =
      F := by
  refine PointedCone.inf_ker_eq_of_eq_hull rfl hF ?_ ?_
  · rintro _ ⟨a, ha, rfl⟩
    rw [hi.realCharacter_apply]
    exact_mod_cast hm a ha
  · rintro _ ⟨a, ha, rfl⟩
    refine ⟨fun h0 ↦ ?_, hmF _⟩
    rw [hi.realCharacter_apply, Int.cast_eq_zero] at h0
    refine hF.mem_of_sum_smul_mem
      (fun a : s ↦ PointedCone.subset_hull (Set.mem_image_of_mem i a.2))
      (fun _ ↦ Nat.cast_nonneg _) ?_ ⟨a, ha⟩ (Nat.cast_pos.2 (hpos ⟨a, ha⟩ h0))
    simpa only [Nat.cast_smul_eq_nsmul] using hc

/-- **The separation lemma.** Let `σ` and `τ` be lattice-rational cones whose intersection is a face
of each. There is an integral character `m`, nonnegative on `σ` and nonpositive on `τ`, whose
kernel cuts out the common face `σ ⊓ τ` from both cones. -/
theorem exists_mem_dualSemigroup_neg_mem_dualSemigroup_inf_ker_eq (hi : IsIntegralLattice i)
    (hσ : IsLatticeRational i σ) (hτ : IsLatticeRational i τ) (hστ : (σ ⊓ τ).IsFaceOf σ)
    (hτσ : (σ ⊓ τ).IsFaceOf τ) :
    ∃ m ∈ dualSemigroup hi σ, -m ∈ dualSemigroup hi τ ∧
      σ ⊓ PointedCone.ofSubmodule (LinearMap.ker (hi.realCharacter m)) = σ ⊓ τ ∧
      τ ⊓ PointedCone.ofSubmodule (LinearMap.ker (hi.realCharacter m)) = σ ⊓ τ := by
  have := hi.free
  have := hi.finite
  obtain ⟨s, rfl⟩ := isLatticeRational_iff.1 hσ
  obtain ⟨t, rfl⟩ := isLatticeRational_iff.1 hτ
  -- Tucker's theorem for the generators of `σ` and the negatives of the generators of `τ`.
  obtain ⟨x, m, hsum, hm, hpos⟩ :=
    exists_nat_sum_nsmul_eq_zero_and_forall_coeff_add_dual_pos
      (Sum.elim (fun a : s ↦ (a : N)) fun b : t ↦ -(b : N))
  simp only [Fintype.sum_sum_type, Sum.elim_inl, Sum.elim_inr, smul_neg, Finset.sum_neg_distrib,
    ← sub_eq_add_neg, sub_eq_zero] at hsum
  have hms : ∀ a ∈ s, 0 ≤ m a := fun a ha ↦ by simpa using hm (.inl ⟨a, ha⟩)
  have hmt : ∀ b ∈ t, 0 ≤ (-m) b := fun b hb ↦ by simpa using hm (.inr ⟨b, hb⟩)
  -- The character vanishes on the common face, being nonnegative on `σ` and nonpositive on `τ`.
  have hF : ∀ v ∈ PointedCone.hull ℝ (i '' s) ⊓ PointedCone.hull ℝ (i '' t),
      hi.realCharacter m v = 0 := fun v hv ↦ by
    have h₁ := (mem_dualSemigroup hi m).1 ((mem_dualSemigroup_hull_image hi _ m).2 hms) hv.1
    have h₂ := (mem_dualSemigroup hi (-m)).1 ((mem_dualSemigroup_hull_image hi _ _).2 hmt) hv.2
    rw [map_neg, LinearMap.neg_apply, neg_nonneg] at h₂
    exact le_antisymm h₂ h₁
  -- The vector `∑ x a • a = ∑ x b • b` lies in the common face.
  have heq : ∑ a : s, x (.inl a) • i a = ∑ b : t, x (.inr b) • i b := by
    simp only [← map_nsmul, ← map_sum, hsum]
  have hw : ∑ a : s, x (.inl a) • i a ∈
      PointedCone.hull ℝ (i '' s) ⊓ PointedCone.hull ℝ (i '' t) := by
    refine ⟨?_, heq ▸ ?_⟩ <;>
      exact Submodule.sum_mem _ fun a _ ↦
        nsmul_mem (PointedCone.subset_hull (Set.mem_image_of_mem i a.2)) _
  refine ⟨m, (mem_dualSemigroup_hull_image hi _ m).2 hms,
    (mem_dualSemigroup_hull_image hi _ _).2 hmt,
    hull_inf_ker_eq_of_sum_nsmul_mem hi hστ hms hF _ hw fun a ha ↦ by
      simpa [ha] using hpos (.inl a), ?_⟩
  rw [← LinearMap.ker_neg, ← map_neg]
  refine hull_inf_ker_eq_of_sum_nsmul_mem hi hτσ hmt (fun v hv ↦ ?_) _ (heq ▸ hw) fun b hb ↦ ?_
  · rw [map_neg, LinearMap.neg_apply, hF v hv, neg_zero]
  · simpa [neg_eq_zero.1 hb] using hpos (.inr b)

/-- Let `σ` and `τ` be lattice-rational cones whose intersection is a face of each. The dual
semigroup of `σ ⊓ τ` is generated by the dual semigroups of `σ` and `τ`: every character
nonnegative on the common face is a sum of one nonnegative on `σ` and one nonnegative on `τ`. -/
theorem dualSemigroup_inf_eq_sup (hi : IsIntegralLattice i) (hσ : IsLatticeRational i σ)
    (hτ : IsLatticeRational i τ) (hστ : (σ ⊓ τ).IsFaceOf σ) (hτσ : (σ ⊓ τ).IsFaceOf τ) :
    dualSemigroup hi (σ ⊓ τ) = dualSemigroup hi σ ⊔ dualSemigroup hi τ := by
  refine le_antisymm ?_ (sup_le (dualSemigroup_anti hi inf_le_left)
    (dualSemigroup_anti hi inf_le_right))
  obtain ⟨m, hm, hm', hσm, -⟩ :=
    exists_mem_dualSemigroup_neg_mem_dualSemigroup_inf_ker_eq hi hσ hτ hστ hτσ
  rw [← hσm, dualSemigroup_inf_ker_eq_sup hi hσ.fg hm]
  exact sup_le_sup_left (AddSubmonoid.closure_le.2 (Set.singleton_subset_iff.2 hm')) _

/-- The dual semigroup of the intersection of two cones of a fan is generated by the dual
semigroups of the two cones. -/
theorem Fan.dualSemigroup_inf_eq_sup (Φ : Fan i) (hσ : σ ∈ Φ.cones) (hτ : τ ∈ Φ.cones) :
    dualSemigroup Φ.lattice (σ ⊓ τ) = dualSemigroup Φ.lattice σ ⊔ dualSemigroup Φ.lattice τ :=
  TauCeti.Toric.dualSemigroup_inf_eq_sup Φ.lattice (Φ.isToricCone hσ).rational
    (Φ.isToricCone hτ).rational (Φ.inf_isFaceOf_left hσ hτ) (Φ.inf_isFaceOf_right hσ hτ)

end TauCeti.Toric
