/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Continuous.Integrated.Basic
public import Mathlib.Analysis.CStarAlgebra.ContinuousLinearMap
public import Mathlib.Topology.Algebra.StarSubalgebra
import Mathlib.Analysis.CStarAlgebra.Fuglede

/-!
# The algebra of an integrated unitary representation

For a strongly continuous unitary representation of an abelian group, the integrated operators
`π(f)`, for `f ∈ L¹(G)`, are commuting normal operators. Their closed unital star algebra is
therefore a commutative C⋆-algebra. Unlike the individual operators `π(g)`, the translates
`π(g) π(f)` vary continuously in operator norm and belong to this algebra.

This algebra makes the Gelfand representation available to strongly continuous representations.
The translated operators are used to recover continuous group characters from algebra characters
that do not vanish on all integrated operators. Unitality alone does not exclude characters that
vanish on every integrated operator; no such nonvanishing assertion is made here.

## References

* G. B. Folland, *A Course in Abstract Harmonic Analysis*, 2nd ed., CRC Press (2016),
  §§3.2 and 4.4.
-/

public section

open MeasureTheory

namespace TauCeti

section Normed

variable {𝕜 G E : Type*} [RCLike 𝕜] [AddCommGroup G] [TopologicalSpace G]
  [MeasurableSpace G] [OpensMeasurableSpace G] [MeasurableAdd₂ G] [MeasurableNeg G]
  [NormedAddCommGroup E] [NormedSpace 𝕜 E] [NormedSpace ℝ E] [SMulCommClass ℝ 𝕜 E]
  [CompleteSpace E] [SecondCountableTopologyEither G E]
  {μ : Measure G} [SFinite μ] [μ.IsAddLeftInvariant] [μ.IsNegInvariant]
  {π : ContRepresentation 𝕜 (Multiplicative G) E}
  {hcont : ∀ v, Continuous fun g : G ↦ π (.ofAdd g) v}
  {hbdd : ∃ C, ∀ g, ‖π g‖ ≤ C}

/-- Integrated operators of an abelian-group representation commute. -/
theorem _root_.ContRepresentation.commute_integratedOperatorL1 (f₁ f₂ : G →₁[μ] 𝕜) :
    Commute (π.integratedOperatorL1 hcont hbdd μ f₁)
      (π.integratedOperatorL1 hcont hbdd μ f₂) := by
  have hconv := convolution_symm (f := (f₁ : G → 𝕜)) (f' := (f₂ : G → 𝕜))
    (μ := μ) (ContinuousLinearMap.mul 𝕜 𝕜) (by ext; simp)
  have h₁ := L1.integrable_coeFn f₁
  have h₂ := L1.integrable_coeFn f₂
  have hL1 := (Integrable.toL1_eq_toL1_iff _ _
    (h₁.integrable_convolution (ContinuousLinearMap.mul 𝕜 𝕜) h₂)
    (h₂.integrable_convolution (ContinuousLinearMap.mul 𝕜 𝕜) h₁)).2
      (Filter.Eventually.of_forall (congrFun hconv))
  rw [commute_iff_eq, ContinuousLinearMap.mul_def, ContinuousLinearMap.mul_def]
  calc
    _ = π.integratedOperatorL1 hcont hbdd μ
        ((h₁.integrable_convolution (ContinuousLinearMap.mul 𝕜 𝕜) h₂).toL1 _) := by
      simpa only [Integrable.toL1_coeFn] using
        (π.integratedOperatorL1_convolution (hcont := hcont) (hbdd := hbdd) h₁ h₂).symm
    _ = π.integratedOperatorL1 hcont hbdd μ
        ((h₂.integrable_convolution (ContinuousLinearMap.mul 𝕜 𝕜) h₁).toL1 _) :=
      congrArg (π.integratedOperatorL1 hcont hbdd μ) hL1
    _ = _ := by
      simpa only [Integrable.toL1_coeFn] using
        π.integratedOperatorL1_convolution (hcont := hcont) (hbdd := hbdd) h₂ h₁

end Normed

section Unitary

variable {𝕜 G E : Type*} [RCLike 𝕜] [AddCommGroup G] [TopologicalSpace G]
  [MeasurableSpace G] [OpensMeasurableSpace G] [MeasurableAdd₂ G] [MeasurableNeg G]
  [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [NormedSpace ℝ E] [SMulCommClass ℝ 𝕜 E]
  [CompleteSpace E] [SecondCountableTopologyEither G E]
  {μ : Measure G} [SFinite μ] [μ.IsAddLeftInvariant] [μ.IsNegInvariant]
  {π : ContRepresentation 𝕜 (Multiplicative G) E}
  {hcont : ∀ v, Continuous fun g : G ↦ π (.ofAdd g) v}
  {hbdd : ∃ C, ∀ g, ‖π g‖ ≤ C}

/-- The integrated operators of a unitary abelian-group representation are normal. -/
theorem _root_.ContRepresentation.isStarNormal_integratedOperatorL1
    (hπ : ContRepresentation.IsUnitary π) (f : G →₁[μ] 𝕜) :
    IsStarNormal (π.integratedOperatorL1 hcont hbdd μ f) := by
  constructor
  rw [ContinuousLinearMap.star_eq_adjoint,
    ContRepresentation.adjoint_integratedOperatorL1 hπ]
  exact (π.commute_integratedOperatorL1
    (star (Lp.compMeasurePreserving Neg.neg (Measure.measurePreserving_neg μ) f)) f).eq

end Unitary

section Hilbert

variable {G H : Type*} [AddGroup G] [TopologicalSpace G] [MeasurableSpace G]
  [OpensMeasurableSpace G] [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H] [SecondCountableTopologyEither G H]
  (π : ContRepresentation ℂ (Multiplicative G) H)
  (hcont : ∀ v, Continuous fun g : G ↦ π (.ofAdd g) v)
  (hbdd : ∃ C, ∀ g, ‖π g‖ ≤ C) (μ : Measure G)

/-- The closed unital star algebra generated by the integrated operators of `π`. -/
noncomputable def _root_.ContRepresentation.integratedAlgebra :
    StarSubalgebra ℂ (H →L[ℂ] H) :=
  (StarAlgebra.adjoin ℂ (Set.range (π.integratedOperatorL1 hcont hbdd μ))).topologicalClosure

/-- The integrated algebra is the closure of the star algebra generated by the integrated form. -/
theorem _root_.ContRepresentation.integratedAlgebra_def :
    π.integratedAlgebra hcont hbdd μ =
      (StarAlgebra.adjoin ℂ
        (Set.range (π.integratedOperatorL1 hcont hbdd μ))).topologicalClosure :=
  (rfl)

/-- Every integrated operator belongs to the integrated algebra. -/
theorem _root_.ContRepresentation.integratedOperatorL1_mem_integratedAlgebra
    (f : G →₁[μ] ℂ) :
    π.integratedOperatorL1 hcont hbdd μ f ∈ π.integratedAlgebra hcont hbdd μ :=
  StarSubalgebra.le_topologicalClosure _ (StarAlgebra.subset_adjoin ℂ _ ⟨f, rfl⟩)

/-- The integrated form with values in its closed star algebra. -/
noncomputable def _root_.ContRepresentation.integratedOperatorL1ToAlgebra :
    (G →₁[μ] ℂ) →L[ℂ] π.integratedAlgebra hcont hbdd μ :=
  (π.integratedOperatorL1 hcont hbdd μ).codRestrict
    (π.integratedAlgebra hcont hbdd μ).toSubalgebra.toSubmodule
    (π.integratedOperatorL1_mem_integratedAlgebra hcont hbdd μ)

/-- Coercing the algebra-valued integrated form recovers the original integrated operator. -/
@[simp]
theorem _root_.ContRepresentation.coe_integratedOperatorL1ToAlgebra (f : G →₁[μ] ℂ) :
    (π.integratedOperatorL1ToAlgebra hcont hbdd μ f : H →L[ℂ] H) =
      π.integratedOperatorL1 hcont hbdd μ f :=
  (rfl)

/-- The integrated algebra is closed in the operator norm. -/
theorem _root_.ContRepresentation.isClosed_integratedAlgebra :
    IsClosed (π.integratedAlgebra hcont hbdd μ : Set (H →L[ℂ] H)) :=
  StarSubalgebra.isClosed_topologicalClosure _

/-- A closed star subalgebra contains the integrated algebra exactly when it contains every
integrated operator. -/
theorem _root_.ContRepresentation.integratedAlgebra_le_iff (B : StarSubalgebra ℂ (H →L[ℂ] H))
    (hB : IsClosed (B : Set (H →L[ℂ] H))) :
    π.integratedAlgebra hcont hbdd μ ≤ B ↔
      ∀ f : G →₁[μ] ℂ, π.integratedOperatorL1 hcont hbdd μ f ∈ B := by
  constructor
  · exact fun h f ↦ h (π.integratedOperatorL1_mem_integratedAlgebra hcont hbdd μ f)
  · intro h
    rw [ContRepresentation.integratedAlgebra_def]
    exact StarSubalgebra.topologicalClosure_minimal
      (StarAlgebra.adjoin_le (by rintro _ ⟨f, rfl⟩; exact h f)) hB

section Translation

variable [MeasurableAdd G] [μ.IsAddLeftInvariant]

/-- A group translate of an integrated operator still belongs to the integrated algebra. -/
theorem _root_.ContRepresentation.comp_integratedOperatorL1_mem_integratedAlgebra
    (g : G) (f : G →₁[μ] ℂ) :
    π (.ofAdd g) ∘L π.integratedOperatorL1 hcont hbdd μ f ∈
      π.integratedAlgebra hcont hbdd μ := by
  rw [ContRepresentation.comp_integratedOperatorL1]
  exact π.integratedOperatorL1_mem_integratedAlgebra hcont hbdd μ _

/-- Translated integrated operators, as elements of the integrated algebra. -/
noncomputable def _root_.ContRepresentation.translatedIntegratedOperatorL1
    (f : G →₁[μ] ℂ) (g : G) : π.integratedAlgebra hcont hbdd μ :=
  ⟨π (.ofAdd g) ∘L π.integratedOperatorL1 hcont hbdd μ f,
    π.comp_integratedOperatorL1_mem_integratedAlgebra hcont hbdd μ g f⟩

/-- The underlying operator of a translated integrated operator is `π(g) π(f)`. -/
@[simp]
theorem _root_.ContRepresentation.coe_translatedIntegratedOperatorL1
    (f : G →₁[μ] ℂ) (g : G) :
    (π.translatedIntegratedOperatorL1 hcont hbdd μ f g : H →L[ℂ] H) =
      π (.ofAdd g) ∘L π.integratedOperatorL1 hcont hbdd μ f :=
  (rfl)

/-- Translation by zero recovers the algebra-valued integrated form. -/
@[simp]
theorem _root_.ContRepresentation.translatedIntegratedOperatorL1_zero (f : G →₁[μ] ℂ) :
    π.translatedIntegratedOperatorL1 hcont hbdd μ f 0 =
      π.integratedOperatorL1ToAlgebra hcont hbdd μ f := by
  apply Subtype.ext
  simp [ContinuousLinearMap.one_def]

/-- Translated integrated operators depend continuously on the group element in the norm of the
integrated algebra. -/
theorem _root_.ContRepresentation.continuous_translatedIntegratedOperatorL1
    [IsTopologicalAddGroup G] [BorelSpace G] [μ.InnerRegularCompactLTTop]
    [IsLocallyFiniteMeasure μ] (f : G →₁[μ] ℂ) :
    Continuous (π.translatedIntegratedOperatorL1 hcont hbdd μ f) :=
  (π.continuous_comp_integratedOperatorL1 (hcont := hcont) (hbdd := hbdd) f).subtype_mk _

end Translation

end Hilbert

section Abelian

variable {G H : Type*} [AddCommGroup G] [TopologicalSpace G] [MeasurableSpace G]
  [OpensMeasurableSpace G] [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H] [SecondCountableTopologyEither G H]
  {π : ContRepresentation ℂ (Multiplicative G) H}
  {hcont : ∀ v, Continuous fun g : G ↦ π (.ofAdd g) v}
  {hbdd : ∃ C, ∀ g, ‖π g‖ ≤ C} {μ : Measure G}
  [MeasurableAdd₂ G] [MeasurableNeg G] [SFinite μ]
  [μ.IsAddLeftInvariant] [μ.IsNegInvariant]

/-- For a unitary abelian-group representation, the closed algebra of integrated operators is
commutative. -/
theorem _root_.ContRepresentation.isMulCommutative_integratedAlgebra
    (hπ : ContRepresentation.IsUnitary π) :
    IsMulCommutative (π.integratedAlgebra hcont hbdd μ) := by
  have : IsMulCommutative
      (StarAlgebra.adjoin ℂ (Set.range (π.integratedOperatorL1 hcont hbdd μ))) :=
    CStarAlgebra.isMulCommutative_adjoin
      (by rintro _ ⟨f, rfl⟩; exact π.isStarNormal_integratedOperatorL1 hπ f)
      (by rintro _ ⟨f₁, rfl⟩ _ ⟨f₂, rfl⟩ _; exact π.commute_integratedOperatorL1 f₁ f₂)
  rw [ContRepresentation.integratedAlgebra_def]
  infer_instance

variable (π hcont hbdd μ)

open scoped IsMulCommutative in
/-- The integrated algebra of a unitary abelian-group representation, with its commutative
C⋆-algebra structure. This is explicit because unitarity is a predicate, rather than a class. -/
@[instance_reducible]
noncomputable def _root_.ContRepresentation.integratedAlgebraCommCStarAlgebra
    (hπ : ContRepresentation.IsUnitary π) :
    CommCStarAlgebra (π.integratedAlgebra hcont hbdd μ) := by
  letI := π.isMulCommutative_integratedAlgebra (μ := μ) (hcont := hcont) (hbdd := hbdd) hπ
  letI := (π.isClosed_integratedAlgebra hcont hbdd μ).completeSpace_coe
  exact { }

end Abelian

end TauCeti
