/-
Copyright (c) 2026 Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Elementary
public import TauCeti.RepresentationTheory.Induction.Artin.Coefficient
public import TauCeti.RepresentationTheory.Induction.Spanning

/-!
# Artin's induction theorem

For a finite group `G`, the sharp Artin identity and the projection formula show that
`|G| • χ` is induced from virtual characters of cyclic subgroups for every virtual character `χ`.
The target is the canonical subgroup
`TauCeti.ClassFunction.indVirtualCharacters k G (fun C ↦ IsCyclic C)`, rather than a parallel
cyclic-specific construction.  When `Nat.card G` vanishes in `k`, this displayed multiple is zero;
the intended nonvacuous content is the characteristic-zero specialization.

The family-general direct-sum induction map bundled in
`TauCeti.RepresentationTheory.Induction.Ideal` is specialized here to the cyclic and elementary
families, where its rational scalar extension is proved surjective.  In positive characteristic the
target tensor product is zero; the usual nonvacuous rational formulation is the specialization to
a characteristic-zero algebraically closed splitting field.

The earlier spanning development also identifies the canonical target with
`TauCeti.ClassFunction.indCharacterSpanInt`, the finer subgroup generated by induced irreducible
characters, over an algebraically closed field in which the selected subgroup orders are
invertible.  Combining that comparison with the sharp canonical theorem gives the conventional
characteristic-zero induced-character-span endpoint.

The sharp identity is Artin's identity for fixed points, proved in
`TauCeti.RepresentationTheory.Induction.Artin.Coefficient` by Möbius inversion over the subgroup
lattice, read in `k`; the projection formula propagates it from the trivial character to every
virtual character.

## Main statements

* `TauCeti.ClassFunction.natCard_nsmul_mem_indVirtualCharacters_isCyclic`: **Artin's induction
  theorem, sharp form**, through the canonical induced-virtual-character API.
* `TauCeti.ClassFunction.natCard_nsmul_mem_indCharacterSpanInt_isCyclic`: the non-modular
  algebraically closed form, including characteristic zero, with the roadmap's literal
  induced-character-span target.
* `TauCeti.ClassFunction.natCard_nsmul_one_mem_indVirtualCharacters_isCyclic`: the sharp
  membership statement for the trivial character.
* `TauCeti.ClassFunction.indVirtualCharacterDirectSumBaseChangeRat_isCyclic_surjective`: rational
  surjectivity after extension of scalars from `ℤ` to `ℚ`, with the intended nonvacuous
  specialization at a characteristic-zero splitting field.
* `TauCeti.ClassFunction.indVirtualCharacterDirectSumBaseChangeRat_isElementary_surjective`: the
  corresponding rational-surjectivity theorem for elementary subgroups.
* `TauCeti.ClassFunction.natCard_nsmul_mem_indVirtualCharacters_isElementary`: the sharp theorem,
  read for the elementary subgroups.

## References

This proves both parts of the "Artin's induction theorem" item of Layer 6 in
`TauCetiRoadmap/RepresentationTheory/InductionRestriction/README.md`: rational surjectivity of the
direct-sum induction map and `ℤ`-membership of `|G| • χ` in the cyclic-induced subgroup.

* J.-P. Serre, *Linear Representations of Finite Groups*, Springer GTM 42 (1977), Section 9.2,
  Theorem 17 and its corollary.
* C. W. Curtis, I. Reiner, *Methods of Representation Theory, Vol. I*, Wiley (1981), Section 15.
-/

public section

namespace TauCeti

namespace ClassFunction

universe u v

variable {k : Type u} {G : Type v} [Field k] [Group G]
variable [Finite G]

/-! ### The sharp Artin identity -/

open scoped Classical in
/-- Weighting each subgroup containing `y` by its Artin coefficient gives `1`. This is the
integral identity `TauCeti.sum_artinCoeff_of_mem_eq_one` read in an arbitrary coefficient ring;
the subgroups missing `y` contribute zero, as do the non-cyclic ones. -/
private theorem sum_artinCoeff_containing_eq_one {R : Type*} [AddCommGroupWithOne R]
    [Fintype (Subgroup G)] (y : G) :
    (∑ C : Subgroup G, if _h : y ∈ C then (C.artinCoeff : R) else (0 : R)) = 1 := by
  classical
  have hcv : ∑ᶠ (C : Subgroup G) (_ : y ∈ C), C.artinCoeff
      = ∑ C ∈ Finset.univ.filter (fun C : Subgroup G => y ∈ C), C.artinCoeff :=
    finsum_cond_eq_sum_of_cond_iff _ (by simp)
  have hint : ∑ C ∈ Finset.univ.filter (fun C : Subgroup G => y ∈ C), C.artinCoeff = 1 := by
    rw [← hcv]
    exact sum_artinCoeff_of_mem_eq_one y
  calc (∑ C : Subgroup G, if _h : y ∈ C then (C.artinCoeff : R) else (0 : R))
      = ((∑ C ∈ Finset.univ.filter (fun C : Subgroup G => y ∈ C), C.artinCoeff : ℤ) : R) := by
        rw [Finset.sum_filter, Int.cast_sum]
        exact Finset.sum_congr rfl fun C _ => by split <;> simp
    _ = 1 := by rw [hint, Int.cast_one]

/-- **Artin induction for the trivial character.** The order of `G` times the trivial character
belongs to the subgroup generated by virtual characters induced from cyclic subgroups.  When
`Nat.card G` vanishes in `k`, the multiple is zero; the intended nonvacuous content is the
characteristic-zero specialization. -/
theorem natCard_nsmul_one_mem_indVirtualCharacters_isCyclic :
    Nat.card G • (1 : G → k) ∈ indVirtualCharacters k G (fun C ↦ IsCyclic C) := by
  -- Pointwise, subgroup order times an induced trivial character counts the conjugates of `g`
  -- lying in that subgroup, and the Artin coefficients of the subgroups containing a given
  -- conjugate sum to one.  A subgroup that is not cyclic has coefficient zero.
  classical
  let _ := Fintype.ofFinite G
  let _ := Fintype.ofFinite (Subgroup G)
  let α : Subgroup G → (G → k) := fun C ↦
    C.artinCoeff • (Nat.card C • indClassFun C (fun _ : C ↦ (1 : k)))
  have hα (C : Subgroup G) : α C ∈ indVirtualCharacters k G (fun C ↦ IsCyclic C) := by
    by_cases hC : IsCyclic C
    · exact AddSubgroup.zsmul_mem _ (AddSubgroup.nsmul_mem _
        (indClassFun_mem_indVirtualCharacters hC one_mem_virtualCharacters) _) _
    · simp [α, Subgroup.artinCoeff_eq_zero_of_not_isCyclic hC]
  suffices hsum : ∑ C, α C = Nat.card G • (1 : G → k) by
    rw [← hsum]
    exact AddSubgroup.sum_mem _ fun C _ ↦ hα C
  funext g
  simp only [α, Finset.sum_apply, Pi.smul_apply]
  have hnat (C : Subgroup G) :
      (Nat.card C : k) * indClassFun C (fun _ : C ↦ (1 : k)) g =
        ∑ x : G, if _h : x⁻¹ * g * x ∈ C then (1 : k) else 0 :=
    natCard_mul_indClassFun (ClassFunction.mem_iff.mpr fun _ _ ↦ rfl) g
  simp_rw [← Int.cast_smul_eq_zsmul k, ← Nat.cast_smul_eq_nsmul k,
    smul_eq_mul, hnat]
  simp_rw [Finset.mul_sum]
  rw [Finset.sum_comm]
  simp only [mul_dite, mul_one, mul_zero]
  simp_rw [sum_artinCoeff_containing_eq_one]
  simp

/-- **Artin's induction theorem, sharp form, through the canonical API.** For every virtual
character `f` of a finite group `G`, the explicit multiple `|G| • f` belongs to the subgroup
generated by virtual characters induced from cyclic subgroups.  When `Nat.card G` vanishes in `k`,
the multiple is zero; the intended nonvacuous content is the characteristic-zero specialization. -/
theorem natCard_nsmul_mem_indVirtualCharacters_isCyclic {f : G → k}
    (hf : f ∈ virtualCharacters k G) :
    Nat.card G • f ∈ indVirtualCharacters k G (fun C ↦ IsCyclic C) := by
  exact nsmul_mem_indVirtualCharacters_of_nsmul_one_mem
    (natCard_nsmul_one_mem_indVirtualCharacters_isCyclic (k := k) (G := G)) hf

/-- **Artin's induction theorem with its induced-character-span target.** Over a
algebraically closed field in which `|G|` is invertible (in particular, in characteristic zero),
`|G| • f` belongs to the additive subgroup generated by characters induced from irreducible
characters of cyclic subgroups. -/
theorem natCard_nsmul_mem_indCharacterSpanInt_isCyclic [IsAlgClosed k]
    [Invertible (Nat.card G : k)]
    {f : G → k} (hf : f ∈ virtualCharacters k G) :
    Nat.card G • f ∈ indCharacterSpanInt k G (fun C ↦ IsCyclic C) := by
  rw [← indVirtualCharacters_eq_indCharacterSpanInt fun C _ ↦
    isUnit_natCard_subgroup C (isUnit_of_invertible _)]
  exact natCard_nsmul_mem_indVirtualCharacters_isCyclic hf

/-! ### Rational surjectivity -/

/-- **Rational Artin induction in map form.** The scalar extension to `ℚ` of induction from cyclic
subgroups is surjective.  In positive characteristic the target is zero; specialization to a
characteristic-zero algebraically closed field gives the usual nonvacuous representation-ring
statement. -/
theorem indVirtualCharacterDirectSumBaseChangeRat_isCyclic_surjective :
    Function.Surjective
      (indVirtualCharacterDirectSumBaseChangeRat k G (fun C ↦ IsCyclic C)) :=
  indVirtualCharacterDirectSumBaseChangeRat_surjective_of_nsmul_one_mem
    (fun C ↦ IsCyclic C) (Nat.card G) Nat.card_pos.ne'
      natCard_nsmul_one_mem_indVirtualCharacters_isCyclic

/-! ### The cyclic and the elementary families -/

/-- Every cyclic subgroup is elementary, so a virtual character induced from a cyclic subgroup is
induced from an elementary one. -/
theorem indVirtualCharacters_isCyclic_le_indVirtualCharacters_isElementary :
    indVirtualCharacters k G (fun C => IsCyclic C) ≤
      indVirtualCharacters k G (fun E => IsElementary E) :=
  indVirtualCharacters_mono fun C hC => by
    have : IsCyclic C := hC
    exact isElementary_of_isCyclic

/-- **Artin's sharp induction theorem, read for the elementary subgroups.** Every cyclic subgroup
is elementary, so the sharp cyclic theorem gives the explicit multiplier `|G|` here too.

When `Nat.card G` vanishes in `k`, the multiple is zero; the intended nonvacuous content is the
characteristic-zero specialization.

This is *weaker* than Brauer's induction theorem, which asserts the same with multiplier `1`. By
`TauCeti.ClassFunction.indVirtualCharacters_eq_virtualCharacters_iff`, Brauer's theorem is
equivalent to `1` being induced from the elementary subgroups, which is not proved here. -/
theorem natCard_nsmul_mem_indVirtualCharacters_isElementary {f : G → k}
    (hf : f ∈ virtualCharacters k G) :
    Nat.card G • f ∈ indVirtualCharacters k G (fun E ↦ IsElementary E) :=
  indVirtualCharacters_isCyclic_le_indVirtualCharacters_isElementary
    (natCard_nsmul_mem_indVirtualCharacters_isCyclic hf)

/-- Rationalized induction from elementary subgroups is surjective. -/
theorem indVirtualCharacterDirectSumBaseChangeRat_isElementary_surjective :
    Function.Surjective
      (indVirtualCharacterDirectSumBaseChangeRat k G (fun E ↦ IsElementary E)) :=
  indVirtualCharacterDirectSumBaseChangeRat_surjective_of_nsmul_one_mem
    (fun E ↦ IsElementary E) (Nat.card G) Nat.card_pos.ne'
      (indVirtualCharacters_isCyclic_le_indVirtualCharacters_isElementary
        natCard_nsmul_one_mem_indVirtualCharacters_isCyclic)

end ClassFunction

end TauCeti
