/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
public import TauCeti.RepresentationTheory.ClassicalGroups.BrauerGenerators.Orthogonal
public import TauCeti.RepresentationTheory.Subrepresentation

/-!
# The harmonic tensors of the orthogonal tensor square, and the trace splitting

The cap `TauCeti.orthogonalCap` contracts the two factors of `V ⊗ V`, `V = kⁿ`, against the
coordinate dot product, and the cup `TauCeti.orthogonalCup` expands a scalar into
`∑ⱼ eⱼ ⊗ eⱼ`. Both are invariant under the diagonal action of the orthogonal group, so the
kernel of the cap and the image of the cup are subrepresentations of `V ⊗ V`: the **harmonic**
(traceless) tensors, and the span of the invariant form `∑ⱼ eⱼ ⊗ eⱼ` — the **trace line**, a line
once `n ≠ 0` and the zero subspace when `n = 0`. This file proves that the two are complementary
as soon as the loop value `n = dim V` is invertible, that the orthogonal group acts trivially on
the trace line, and that the harmonic tensors have codimension one.

So `V ⊗ V` splits as an orthogonal representation into the harmonic tensors and a trivial
summand, the summand generated by the invariant form. One half of the comparison with the
`GLₙ`-decomposition `V ⊗ V ≅ Sym²V ⊕ ⋀²V` of `TauCeti.RepresentationTheory.Tensor.Square` costs
nothing: the antisymmetrization `x - s · x` of any tensor is harmonic over any commutative ring,
and an antisymmetric tensor is harmonic as soon as `2` is regular. The decomposition into a
symmetric and an exterior square itself needs `2` invertible, though, so it is only where **both**
`n` and `2` are invertible that the trace splitting **refines** it into three pieces: the exterior
square is entirely harmonic, while the invariant form is symmetric, so the trace line cuts the
symmetric square into the traceless symmetric tensors and itself. For `n = 3` over such a `k` the
three pieces have dimensions `5 + 3 + 1 = 9`, the traceless symmetric, the antisymmetric, and the
trace; the two examples at the end of the file check the `8 = 9 - 1` half of that count, which is
the part visible without the symmetric/exterior splitting.

The splitting needs `n` invertible in `k` and not merely nonzero as a natural number: where
`(n : k) = 0` the cap kills the cup, so the Brauer generator `e = cup ∘ cap` squares to zero
instead of being a multiple of an idempotent, and the trace line lies **inside** the harmonic
tensors rather than complementing them. Both dimension counts survive there, because the cap is
surjective and the cup injective for purely combinatorial reasons: the cap sends `e₀ ⊗ e₀` to
`1`, and the `e₀ ⊗ e₀` coordinate of `cup c` is `c`.

## Main definitions

* `TauCeti.orthogonalHarmonicTensors`: the harmonic (traceless) tensors `ker (cap)`, as a
  subrepresentation of the tensor square of the standard orthogonal representation. Only the
  two-strand case is built here; contraction at an arbitrary pair of slots of a higher tensor
  power is not.
* `TauCeti.orthogonalTraceLine`: the image `range (cup)` of the cup, the other summand. It is a
  line exactly when `n ≠ 0`.
* `TauCeti.orthogonalTraceProjection`: the normalized Brauer generator `n⁻¹ • e`, defined where
  the loop value is invertible. It is the projection onto the trace line along the harmonic
  tensors.

## Main results

* `TauCeti.orthogonalCap_surjective` and `TauCeti.orthogonalCup_injective`: the cap is
  surjective and the cup injective for `n ≠ 0`, at any loop value.
* `TauCeti.isCompl_ker_orthogonalCap_range_orthogonalCup` and
  `TauCeti.isCompl_orthogonalHarmonicTensors_orthogonalTraceLine`: **the harmonic tensors and the
  trace line are complementary** when the loop value `n` is invertible in `k`, at the level of
  submodules and of subrepresentations. Combining the latter with
  `Subrepresentation.equivProdOfIsCompl` splits the tensor square as an orthogonal
  representation.
* `TauCeti.tensorPower_apply_of_mem_orthogonalTraceLine`: **the orthogonal group fixes the trace
  line pointwise**, so that summand is the trivial representation.
* `TauCeti.sub_permTensorAction_swap_mem_ker_orthogonalCap` and
  `TauCeti.mem_ker_orthogonalCap_of_permTensorAction_swap_eq_neg`: **antisymmetric tensors are
  harmonic**, the cap being symmetric.
* `TauCeti.ker_orthogonalCupCap` and `TauCeti.range_orthogonalCupCap`: the Brauer generator
  `e = cup ∘ cap` has the harmonic tensors as its kernel and the trace line as its image.
* `TauCeti.orthogonalTraceProjection_apply_of_mem_orthogonalHarmonicTensors`,
  `TauCeti.orthogonalTraceProjection_apply_of_mem_orthogonalTraceLine` and
  `TauCeti.isIdempotentElem_orthogonalTraceProjection`: **`n⁻¹ • e` is the projection onto the
  trace line along the harmonic tensors** — it kills the harmonic tensors, fixes the trace line
  pointwise, and is idempotent.
* `TauCeti.finrank_orthogonalHarmonicTensors`: **the harmonic tensors have codimension one**,
  `dim (harmonic) + 1 = n²`, and `TauCeti.finrank_orthogonalTraceLine`: for `n ≠ 0` the trace
  line is a line.

## References

* [R. Brauer, *On algebras which are connected with the semisimple continuous groups*][brauer1937],
  Annals of Mathematics 38 (1937), 857-872.
* R. Goodman and N. R. Wallach, *Symmetry, Representations, and Invariants*, Springer GTM 255
  (2009), Chapter 10, for the harmonic (traceless) tensors and the trace filtration.
-/

public section

open Matrix
open scoped TensorProduct

universe u

namespace TauCeti

variable (k : Type u) (n : ℕ)

section CommSemiring

variable [CommSemiring k]

/-- **The cap is surjective** once there is a coordinate to contract: it sends the pure tensor
`e₀ ⊗ e₀` of the first standard basis vector with itself to `1`. No invertibility of the loop
value is needed, which is why the codimension count below survives in every characteristic. -/
theorem orthogonalCap_surjective [NeZero n] : Function.Surjective (orthogonalCap k n) := by
  intro c
  refine ⟨c • PiTensorProduct.tprod k fun _ : Fin 2 => Pi.single (0 : Fin n) (1 : k), ?_⟩
  rw [map_smul, orthogonalCap_tprod]
  simp

/-- **The cup is injective** once there is a coordinate to expand into. No invertibility of the
loop value is needed either: the cap is not what detects `cup c`, the single coordinate `e₀ ⊗ e₀`
of it already is, and that coordinate is `c`. -/
theorem orthogonalCup_injective [NeZero n] : Function.Injective (orthogonalCup k n) := by
  -- Read off the `e₀ ⊗ e₀` coordinate, the product of the two `0`th coordinates.
  refine Function.LeftInverse.injective
    (g := PiTensorProduct.lift ((MultilinearMap.mkPiAlgebra k (Fin 2) k).compLinearMap
      fun _ : Fin 2 => LinearMap.proj (0 : Fin n))) fun c => ?_
  rw [orthogonalCup_apply, map_smul, map_sum]
  simp [Pi.single_apply, eq_comm, Finset.sum_ite_eq']

/-- The image of the cup is the **trace line**, the span of the invariant form `∑ⱼ eⱼ ⊗ eⱼ`. -/
theorem range_orthogonalCup :
    LinearMap.range (orthogonalCup k n) = Submodule.span k {orthogonalCup k n 1} := by
  have h : orthogonalCup k n =
      LinearMap.toSpanSingleton k (⨂[k]^2 (Fin n → k)) (orthogonalCup k n 1) :=
    LinearMap.ext_ring (by rw [LinearMap.toSpanSingleton_apply, one_smul])
  rw [← LinearMap.range_toSpanSingleton (R := k) (orthogonalCup k n 1), ← h]

end CommSemiring

section CommRing

variable [CommRing k]

/-! ### Antisymmetric tensors are harmonic -/

/-- **The antisymmetrization of a tensor is harmonic**: the cap is unchanged by the crossing,
because the coordinate dot product is symmetric. -/
theorem sub_permTensorAction_swap_mem_ker_orthogonalCap (x : ⨂[k]^2 (Fin n → k)) :
    x - permTensorAction k n 2 (Equiv.swap 0 1) x ∈ LinearMap.ker (orthogonalCap k n) := by
  have h : orthogonalCap k n (permTensorAction k n 2 (Equiv.swap 0 1) x) =
      orthogonalCap k n x :=
    LinearMap.congr_fun (orthogonalCap_comp_permTensorAction_swap k n) x
  rw [LinearMap.mem_ker, map_sub, h, sub_self]

/-- **An antisymmetric tensor is harmonic.** This is the exterior square sitting inside the
harmonic tensors; it needs `2` cancellable, the antisymmetric tensors being the `-1`-eigenspace of
the crossing only where `2` is regular. -/
theorem mem_ker_orthogonalCap_of_permTensorAction_swap_eq_neg (h2 : IsRegular (2 : k))
    {x : ⨂[k]^2 (Fin n → k)} (hx : permTensorAction k n 2 (Equiv.swap 0 1) x = -x) :
    x ∈ LinearMap.ker (orthogonalCap k n) := by
  have h := sub_permTensorAction_swap_mem_ker_orthogonalCap k n x
  rw [hx, sub_neg_eq_add, ← two_smul k x, LinearMap.mem_ker, map_smul, smul_eq_mul] at h
  exact LinearMap.mem_ker.2 (h2.left.mul_left_eq_zero_iff.mp h)

/-! ### The trace splitting -/

/-- **The harmonic tensors and the trace line are complementary** when the loop value `n` is
invertible in `k`. The splitting map is `n⁻¹ • (cup ∘ cap)`, the normalized Brauer generator. -/
theorem isCompl_ker_orthogonalCap_range_orthogonalCup (hn : IsUnit (n : k)) :
    IsCompl (LinearMap.ker (orthogonalCap k n)) (LinearMap.range (orthogonalCup k n)) := by
  obtain ⟨b, hb⟩ := isUnit_iff_exists_inv.mp hn
  refine ⟨Submodule.disjoint_def.2 fun x hx hx' => ?_, codisjoint_iff.2 (eq_top_iff.2 ?_)⟩
  · obtain ⟨c, rfl⟩ := hx'
    rw [LinearMap.mem_ker, orthogonalCap_comp_orthogonalCup_apply] at hx
    rw [hn.mul_right_eq_zero.mp hx, map_zero]
  · intro x _
    refine Submodule.mem_sup.2
      ⟨x - orthogonalCup k n (b * orthogonalCap k n x), ?_,
        orthogonalCup k n (b * orthogonalCap k n x), ⟨_, rfl⟩, by abel⟩
    rw [LinearMap.mem_ker, map_sub, orthogonalCap_comp_orthogonalCup_apply, ← mul_assoc, hb,
      one_mul, sub_self]

/-! ### The Brauer generator as a projection -/

/-- The kernel of the Brauer generator `e = cup ∘ cap` is the harmonic tensors, the cup being
injective. This needs no invertibility of the loop value: even where `(n : k) = 0`, so that `e`
squares to zero, its kernel is still exactly the harmonic tensors. Nor does it need `n ≠ 0`: for
`n = 0` the cap and the cup are both the zero map, and both kernels are everything. -/
theorem ker_orthogonalCupCap :
    LinearMap.ker (orthogonalCupCap k n) = LinearMap.ker (orthogonalCap k n) := by
  have hcomp : orthogonalCupCap k n = orthogonalCup k n ∘ₗ orthogonalCap k n :=
    LinearMap.ext (orthogonalCupCap_apply k n)
  obtain _ | m := n
  · have hcap : orthogonalCap k 0 = 0 := by
      refine PiTensorProduct.ext ?_
      ext v
      simp [dotProduct]
    have hcup : orthogonalCup k 0 = 0 := LinearMap.ext_ring (by simp)
    rw [hcomp, hcap, hcup, LinearMap.zero_comp, LinearMap.ker_zero, LinearMap.ker_zero]
  · rw [hcomp, LinearMap.ker_comp_of_ker_eq_bot _
      (LinearMap.ker_eq_bot_of_injective (orthogonalCup_injective k (m + 1)))]

/-- The image of the Brauer generator `e = cup ∘ cap` is the trace line, the cap being
surjective. For `n = 0` the cup is the zero map and both images are `⊥`. -/
theorem range_orthogonalCupCap :
    LinearMap.range (orthogonalCupCap k n) = LinearMap.range (orthogonalCup k n) := by
  have hcomp : orthogonalCupCap k n = orthogonalCup k n ∘ₗ orthogonalCap k n :=
    LinearMap.ext (orthogonalCupCap_apply k n)
  obtain _ | m := n
  · have hcup : orthogonalCup k 0 = 0 := LinearMap.ext_ring (by simp)
    rw [hcomp, hcup, LinearMap.zero_comp, LinearMap.range_zero, LinearMap.range_zero]
  · rw [hcomp, LinearMap.range_comp_of_range_eq_top _
      (LinearMap.range_eq_top_of_surjective _ (orthogonalCap_surjective k (m + 1)))]

/-! ### The two summands as subrepresentations -/

/-- **The harmonic (traceless) tensors** of the tensor square of the standard orthogonal
representation: the kernel of the cap, a subrepresentation because the cap is invariant. -/
noncomputable def orthogonalHarmonicTensors :
    Subrepresentation ((stdOrthogonalRep k n).tensorPower 2) where
  toSubmodule := LinearMap.ker (orthogonalCap k n)
  apply_mem_toSubmodule := by
    intro g x hx
    rw [LinearMap.mem_ker] at hx ⊢
    exact (LinearMap.congr_fun (orthogonalCap_comp_tensorPower k n g) x).trans hx

/-- **The trace subrepresentation** of the tensor square of the standard orthogonal
representation: the image of the cup, a subrepresentation because the cup is invariant. It is the
span of the invariant form `∑ⱼ eⱼ ⊗ eⱼ`, so it is a line exactly when `n ≠ 0` — see
`TauCeti.finrank_orthogonalTraceLine` — and the zero subspace when `n = 0`. -/
noncomputable def orthogonalTraceLine :
    Subrepresentation ((stdOrthogonalRep k n).tensorPower 2) where
  toSubmodule := LinearMap.range (orthogonalCup k n)
  apply_mem_toSubmodule := by
    intro g x hx
    obtain ⟨c, rfl⟩ := hx
    exact ⟨c, (LinearMap.congr_fun (tensorPower_comp_orthogonalCup k n g) c).symm⟩

@[simp]
theorem orthogonalHarmonicTensors_toSubmodule :
    (orthogonalHarmonicTensors k n).toSubmodule = LinearMap.ker (orthogonalCap k n) :=
  (rfl)

@[simp]
theorem orthogonalTraceLine_toSubmodule :
    (orthogonalTraceLine k n).toSubmodule = LinearMap.range (orthogonalCup k n) :=
  (rfl)

/-- A tensor is harmonic exactly when the cap kills it. -/
@[simp]
theorem mem_orthogonalHarmonicTensors_iff {x : ⨂[k]^2 (Fin n → k)} :
    x ∈ orthogonalHarmonicTensors k n ↔ orthogonalCap k n x = 0 := by
  rw [← Subrepresentation.mem_toSubmodule, orthogonalHarmonicTensors_toSubmodule,
    LinearMap.mem_ker]

/-- A tensor lies on the trace line exactly when it is a scalar multiple of the invariant
form. -/
@[simp]
theorem mem_orthogonalTraceLine_iff {x : ⨂[k]^2 (Fin n → k)} :
    x ∈ orthogonalTraceLine k n ↔ ∃ c : k, orthogonalCup k n c = x := by
  rw [← Subrepresentation.mem_toSubmodule, orthogonalTraceLine_toSubmodule, LinearMap.mem_range]

/-- **The orthogonal group fixes the trace line pointwise**: the trace summand of the tensor
square is the trivial representation. -/
theorem tensorPower_apply_of_mem_orthogonalTraceLine (g : Matrix.orthogonalGroup (Fin n) k)
    {x : ⨂[k]^2 (Fin n → k)} (hx : x ∈ orthogonalTraceLine k n) :
    (stdOrthogonalRep k n).tensorPower 2 g x = x := by
  obtain ⟨c, rfl⟩ := (mem_orthogonalTraceLine_iff k n).mp hx
  exact LinearMap.congr_fun (tensorPower_comp_orthogonalCup k n g) c

/-- **The trace splitting of the orthogonal tensor square.** When the loop value `n` is
invertible in `k`, the harmonic tensors and the trace line are complementary subrepresentations,
so `Subrepresentation.equivProdOfIsCompl` presents `V ⊗ V` as their direct sum. -/
theorem isCompl_orthogonalHarmonicTensors_orthogonalTraceLine (hn : IsUnit (n : k)) :
    IsCompl (orthogonalHarmonicTensors k n) (orthogonalTraceLine k n) :=
  Subrepresentation.isCompl_toSubmodule.mp <| by
    rw [orthogonalHarmonicTensors_toSubmodule, orthogonalTraceLine_toSubmodule]
    exact isCompl_ker_orthogonalCap_range_orthogonalCup k n hn

/-! ### The projection onto the trace line -/

/-- **The projection onto the trace line along the harmonic tensors**: the Brauer generator
`e = cup ∘ cap` normalized by the loop value. It takes the invertibility of `n` as an argument
rather than an inverse in `k`, because no projection exists where `(n : k) = 0`: there `e` squares
to zero. -/
noncomputable def orthogonalTraceProjection (hn : IsUnit (n : k)) :
    Module.End k (⨂[k]^2 (Fin n → k)) :=
  ((hn.unit⁻¹ : kˣ) : k) • orthogonalCupCap k n

theorem orthogonalTraceProjection_eq_smul (hn : IsUnit (n : k)) :
    orthogonalTraceProjection k n hn = ((hn.unit⁻¹ : kˣ) : k) • orthogonalCupCap k n :=
  (rfl)

@[simp]
theorem orthogonalTraceProjection_apply (hn : IsUnit (n : k)) (x : ⨂[k]^2 (Fin n → k)) :
    orthogonalTraceProjection k n hn x =
      ((hn.unit⁻¹ : kˣ) : k) • orthogonalCup k n (orthogonalCap k n x) := by
  rw [orthogonalTraceProjection_eq_smul, LinearMap.smul_apply, orthogonalCupCap_apply]

/-- **The projection kills the harmonic tensors**, they being the kernel of the cap. -/
theorem orthogonalTraceProjection_apply_of_mem_orthogonalHarmonicTensors (hn : IsUnit (n : k))
    {x : ⨂[k]^2 (Fin n → k)} (hx : x ∈ orthogonalHarmonicTensors k n) :
    orthogonalTraceProjection k n hn x = 0 := by
  rw [orthogonalTraceProjection_apply, (mem_orthogonalHarmonicTensors_iff k n).mp hx, map_zero,
    smul_zero]

/-- **The projection fixes the trace line pointwise**: the normalization `n⁻¹` is exactly what
cancels the loop value the cap reads off a cup. -/
theorem orthogonalTraceProjection_apply_of_mem_orthogonalTraceLine (hn : IsUnit (n : k))
    {x : ⨂[k]^2 (Fin n → k)} (hx : x ∈ orthogonalTraceLine k n) :
    orthogonalTraceProjection k n hn x = x := by
  obtain ⟨c, rfl⟩ := (mem_orthogonalTraceLine_iff k n).mp hx
  rw [orthogonalTraceProjection_apply, orthogonalCap_comp_orthogonalCup_apply, ← smul_eq_mul,
    map_smul, smul_smul, hn.val_inv_mul, one_smul]

/-- The projection lands in the trace line, the cup being what it ends with. -/
theorem orthogonalTraceProjection_apply_mem_orthogonalTraceLine (hn : IsUnit (n : k))
    (x : ⨂[k]^2 (Fin n → k)) :
    orthogonalTraceProjection k n hn x ∈ orthogonalTraceLine k n := by
  rw [mem_orthogonalTraceLine_iff, orthogonalTraceProjection_apply]
  exact ⟨((hn.unit⁻¹ : kˣ) : k) * orthogonalCap k n x, by rw [← smul_eq_mul, map_smul]⟩

/-- **The normalized Brauer generator is idempotent**: it lands in the trace line, which it fixes
pointwise. -/
theorem isIdempotentElem_orthogonalTraceProjection (hn : IsUnit (n : k)) :
    IsIdempotentElem (orthogonalTraceProjection k n hn) := by
  refine LinearMap.ext fun x => ?_
  rw [Module.End.mul_apply]
  exact orthogonalTraceProjection_apply_of_mem_orthogonalTraceLine k n hn
    (orthogonalTraceProjection_apply_mem_orthogonalTraceLine k n hn x)

end CommRing

section Field

variable [Field k]

/-- **The harmonic tensors have codimension one** in the tensor square: the cap is a surjection
onto `k` with them as its kernel. Stated additively rather than as `n ^ 2 - 1`, to keep truncated
subtraction out of the statement. -/
theorem finrank_orthogonalHarmonicTensors [NeZero n] :
    Module.finrank k (orthogonalHarmonicTensors k n).toSubmodule + 1 = n ^ 2 := by
  have h := LinearMap.finrank_range_add_finrank_ker (orthogonalCap k n)
  rw [LinearMap.range_eq_top.2 (orthogonalCap_surjective k n), finrank_top,
    Module.finrank_self, finrank_tensorPower] at h
  rw [orthogonalHarmonicTensors_toSubmodule]
  omega

/-- **The trace line is a line**, the cup being injective. -/
theorem finrank_orthogonalTraceLine [NeZero n] :
    Module.finrank k (orthogonalTraceLine k n).toSubmodule = 1 := by
  rw [orthogonalTraceLine_toSubmodule,
    LinearMap.finrank_range_of_inj (orthogonalCup_injective k n), Module.finrank_self]

end Field

-- On `(k³)^{⊗2}` the trace splitting is `8 + 1 = 9 = 3²`, the harmonic tensors being the
-- traceless symmetric `5` plus the antisymmetric `3`. Nothing below is special to `ℚ`.
example : Module.finrank ℚ (orthogonalHarmonicTensors ℚ 3).toSubmodule = 8 := by
  have h := finrank_orthogonalHarmonicTensors ℚ 3
  omega

example : Module.finrank ℚ (orthogonalTraceLine ℚ 3).toSubmodule = 1 :=
  finrank_orthogonalTraceLine ℚ 3

end TauCeti
