/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.Symplectic.DiagonalTorus.ClosedImmersion
public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.UpperTriangular.Basic
public import TauCeti.Algebra.AlgebraicGroup.Solvable.Basic
import TauCeti.LinearAlgebra.Matrix.GeneralLinearGroup.UpperTriangular.Solvable

/-!
# The standard complete isotropic flag subgroup of the symplectic group

In paired coordinates `e₀, …, eₘ₋₁, f₀, …, fₘ₋₁`, the standard complete isotropic flag
is spanned successively by `e₀`, by `e₀, e₁`, and so on. Its self-dual completion orders
the full basis as `e₀, …, eₘ₋₁, fₘ₋₁, …, f₀`. This file constructs the finite-type
closed subgroup of `Sp₂ₘ` whose matrices are upper triangular in this order. In the
original paired order these matrices have upper-triangular upper-left block,
lower-triangular lower-right block, and zero lower-left block.

The quotient Hopf algebra represents these matrices over every commutative algebra,
including nonreduced algebras and characteristic two. Its algebra-valued point groups
are solvable, and the diagonal symplectic torus factors through the closed subgroup.
These constructions provide the flag subgroup used in the standard symplectic pinning;
no smoothness, connectedness, or Borel maximality assertion is made here.

The construction uses `GeneralLinear.weightParabolicDefiningHopfIdeal`; the quotient
points and torus-factorization arguments follow
`TauCeti.Algebra.AlgebraicGroup.SpecialLinear.UpperTriangular.Basic` and
`TauCeti.Algebra.AlgebraicGroup.SpecialLinear.UpperTriangular.DiagonalTorus`.

## References

* J. S. Milne, *Algebraic Groups* (2017), §24.6 (symplectic groups and isotropic flags).
* B. Conrad, *Reductive Group Schemes* (2014), §5.1 (pinnings).
-/

public section

open CategoryTheory WithConv Matrix

namespace TauCeti.Symplectic.IsotropicFlag

universe u v w

variable (R : Type u) [CommRing R] (m : ℕ)

/-- The basis permutation giving the self-dual flag order: fix the `e` block and reverse
the `f` block. -/
def flagOrder : Equiv.Perm (Fin (m + m)) :=
  finSumFinEquiv.symm.trans ((Equiv.refl (Fin m)).sumCongr Fin.revPerm) |>.trans
    finSumFinEquiv

/-- The isotropic half of the basis keeps its standard order. -/
@[simp]
theorem flagOrder_castAdd (i : Fin m) : flagOrder m (i.castAdd m) = i.castAdd m := by
  simp [flagOrder]

/-- The dual half of the basis is reversed in the self-dual flag order. -/
@[simp]
theorem flagOrder_addNat (i : Fin m) :
    flagOrder m (i.addNat m) = i.rev.addNat m := by
  simp only [← Fin.natAdd_eq_addNat, flagOrder, Equiv.trans_apply,
    finSumFinEquiv_symm_apply_natAdd,
    Equiv.sumCongr_apply, Sum.map_inr, Fin.revPerm_apply, finSumFinEquiv_apply_right]

private def weights : Fin (m + m) → ℤ :=
  GeneralLinear.UpperTriangular.weights (m + m) ∘ flagOrder m

/-- The Hopf ideal cutting out the standard complete isotropic flag subgroup in `Sp₂ₘ`.
It is the image of the general-linear flag ideal under symplectic coordinate restriction. -/
noncomputable def definingHopfIdeal : HopfIdeal R (Symplectic.coordinateHopfAlgebra R m) :=
  (GeneralLinear.weightParabolicDefiningHopfIdeal R (weights m)).map
    (Symplectic.coordinateMap R m).hom

/-- The flag ideal is generated by the generic symplectic entries strictly below the
diagonal in the self-dual flag order. -/
theorem definingHopfIdeal_toIdeal :
    (definingHopfIdeal R m).toIdeal = Ideal.span
      {x | ∃ i j : Fin (m + m), flagOrder m j < flagOrder m i ∧
        x = (Symplectic.coordinateMap R m).hom
          (GeneralLinear.coordinateHopfAlgebraAlgEquiv R (m + m)
            (GeneralLinear.coordinateRingMap R (m + m) (MvPolynomial.X (i, j))))} := by
  rw [definingHopfIdeal, HopfIdeal.map_toIdeal,
    GeneralLinear.weightParabolicDefiningHopfIdeal_toIdeal, Ideal.map_span]
  congr 1
  ext x
  simp only [Set.mem_image, GeneralLinear.mem_weightParabolicRelationSet_iff,
    weights, Function.comp_apply, GeneralLinear.UpperTriangular.weights_lt_weights_iff,
    Set.mem_ofPred_eq]
  constructor
  · rintro ⟨_, ⟨i, j, hij, rfl⟩, rfl⟩
    exact ⟨i, j, hij, rfl⟩
  · rintro ⟨i, j, hij, rfl⟩
    exact ⟨_, ⟨i, j, hij, rfl⟩, rfl⟩

/-- The isotropic flag subgroup is defined by finitely many equations. -/
theorem definingHopfIdeal_toIdeal_fg : (definingHopfIdeal R m).toIdeal.FG := by
  rw [definingHopfIdeal_toIdeal]
  apply Submodule.fg_span
  refine (Set.finite_range fun p : Fin (m + m) × Fin (m + m) ↦
    (Symplectic.coordinateMap R m).hom
      (GeneralLinear.coordinateHopfAlgebraAlgEquiv R (m + m)
        (GeneralLinear.coordinateRingMap R (m + m) (MvPolynomial.X p)))).subset ?_
  rintro x ⟨i, j, _, rfl⟩
  exact ⟨(i, j), rfl⟩

/-- The coordinate Hopf algebra of the standard complete isotropic flag subgroup. -/
noncomputable abbrev coordinateHopfAlgebra : CommHopfAlgCat.{u} R :=
  CommHopfAlgCat.quotient (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)

/-- Coordinate restriction from the symplectic group to the isotropic flag subgroup. -/
noncomputable abbrev coordinateMap :
    Symplectic.coordinateHopfAlgebra R m ⟶ coordinateHopfAlgebra R m :=
  CommHopfAlgCat.mkQuotient (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)

/-- The isotropic flag subgroup has finite-type coordinate algebra. -/
instance instAlgebraFiniteTypeCoordinateHopfAlgebra :
    Algebra.FiniteType R (coordinateHopfAlgebra R m) :=
  Algebra.FiniteType.quotient R (definingHopfIdeal R m).toIdeal

/-- The affine group scheme of matrices preserving the standard complete isotropic flag. -/
noncomputable abbrev groupScheme :=
  CommHopfAlgCat.quotientSpec (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)

/-- The closed-subgroup inclusion of the isotropic flag subgroup into the symplectic group. -/
noncomputable abbrev inclusion :=
  CommHopfAlgCat.quotientSpecι (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)

section Points

variable {A : Type w} [CommRing A] [Algebra R A]

/-- A symplectic point belongs to the isotropic flag subgroup precisely when its matrix
is upper triangular after reversing the dual half of the basis. -/
@[simp]
theorem mem_definingPointsSubgroup_iff
    (g : HopfAlgebra.points (R := R) (H := Symplectic.coordinateHopfAlgebra R m)
      (CommAlgCat.of R A)) :
    g ∈ CommHopfAlgCat.quotientPointsSubgroup
        (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)
        (CommAlgCat.of R A) ↔
      (flagOrder m).reindexGL A (Symplectic.pointsMulEquiv R m (A := A) g).val ∈
        upperTriangularGroup (Fin (m + m)) A := by
  rw [definingHopfIdeal,
    CommHopfAlgCat.mem_quotientPointsSubgroup_map_iff_of_surjective
      (Symplectic.coordinateMap R m)
      (by
        rw [Symplectic.coordinateMap_def]
        exact CommHopfAlgCat.mkQuotient_surjective _ _),
    GeneralLinear.mem_weightParabolicDefiningPointsSubgroup_iff_blockTriangular,
    CommHopfAlgCat.mapPointsFunctor_app_apply, Symplectic.coordinateMap_def,
    ← CommHopfAlgCat.quotientPointsHom_apply
      (GeneralLinear.coordinateHopfAlgebra R (m + m)) (Symplectic.definingHopfIdeal R m)
      (CommAlgCat.of R A) g,
    Symplectic.pointsMulEquiv_coe, UpperTriangularGroup.mem_iff, Equiv.coe_reindexGL,
    Matrix.IsUpperTriangular, ← Matrix.reindex_apply, Matrix.blockTriangular_reindex_iff]
  simp only [Matrix.BlockTriangular, Function.comp_apply, OrderDual.toDual_lt_toDual,
    weights, GeneralLinear.UpperTriangular.weights_lt_weights_iff, id_eq]

/-- The matrix group represented by the isotropic flag coordinate algebra. -/
def matrixSubgroup : Subgroup (GLSymplecticFin m A) :=
  (upperTriangularGroup (Fin (m + m)) A).comap
    (((flagOrder m).reindexGL A).toMonoidHom.comp (GLSymplecticFin m A).subtype)

/-- In paired coordinates, the flag subgroup consists of matrices whose upper-left block
is upper triangular, whose lower-right block is lower triangular, and whose lower-left
block vanishes. -/
@[simp]
theorem mem_matrixSubgroup_iff (g : GLSymplecticFin m A) :
    g ∈ matrixSubgroup m (A := A) ↔
      (∀ i j : Fin m, j < i → (g.val : Matrix _ _ A) (i.castAdd m) (j.castAdd m) = 0) ∧
      (∀ i j : Fin m, i < j → (g.val : Matrix _ _ A) (i.addNat m) (j.addNat m) = 0) ∧
      (∀ i j : Fin m, (g.val : Matrix _ _ A) (i.addNat m) (j.castAdd m) = 0) := by
  have hmem : g ∈ matrixSubgroup m (A := A) ↔
      ∀ i j, flagOrder m j < flagOrder m i → (g.val : Matrix _ _ A) i j = 0 := by
    rw [matrixSubgroup, Subgroup.mem_comap, MonoidHom.comp_apply,
      Subgroup.subtype_apply, MulEquiv.coe_toMonoidHom, UpperTriangularGroup.mem_iff,
      Equiv.coe_reindexGL, Matrix.IsUpperTriangular, ← Matrix.reindex_apply,
      Matrix.blockTriangular_reindex_iff]
    rfl
  rw [hmem]
  constructor
  · intro h
    refine ⟨?_, ?_, ?_⟩
    · intro i j hij
      apply h
      simpa only [flagOrder_castAdd, Fin.lt_def, Fin.val_castAdd] using hij
    · intro i j hij
      apply h
      simp only [flagOrder_addNat, Fin.lt_def, Fin.val_addNat, Fin.val_rev]
      omega
    · intro i j
      apply h
      simp only [flagOrder_castAdd, flagOrder_addNat, Fin.lt_def,
        Fin.val_castAdd, Fin.val_addNat]
      omega
  · rintro ⟨hupper, hlower, hzero⟩ i j
    refine Fin.addCases (fun i ↦ ?_) (fun i ↦ ?_) i <;>
      refine Fin.addCases (fun j ↦ ?_) (fun j ↦ ?_) j
    · intro hij
      apply hupper
      simpa only [flagOrder_castAdd, Fin.lt_def, Fin.val_castAdd] using hij
    · simp only [Fin.natAdd_eq_addNat, flagOrder_castAdd, flagOrder_addNat, Fin.lt_def,
        Fin.val_castAdd, Fin.val_addNat]
      omega
    · intro _
      simpa only [Fin.natAdd_eq_addNat] using hzero i j
    · intro hij
      simp only [Fin.natAdd_eq_addNat] at hij ⊢
      apply hlower
      simp only [flagOrder_addNat, Fin.lt_def, Fin.val_addNat, Fin.val_rev] at hij
      omega

private noncomputable def definingPointsSubgroupMulEquiv :
    CommHopfAlgCat.quotientPointsSubgroup
        (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)
        (CommAlgCat.of R A) ≃* matrixSubgroup m (A := A) :=
  Subgroup.congrOfMapEq (Symplectic.pointsMulEquiv R m (A := A)) <| by
    ext g
    rw [← (Symplectic.pointsMulEquiv R m (A := A)).toMonoidHom_eq_coe,
      Subgroup.mem_map_equiv, mem_definingPointsSubgroup_iff, MulEquiv.apply_symm_apply]
    rfl

/-- The algebra-valued points of the isotropic flag subgroup are exactly the symplectic
matrices upper triangular in the self-dual flag order. -/
noncomputable def pointsMulEquiv :
    HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R m) (CommAlgCat.of R A) ≃*
      matrixSubgroup m (A := A) :=
  ((CommHopfAlgCat.quotientPointsSubgroupNatIso
      (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)).app
      (CommAlgCat.of R A)).groupIsoToMulEquiv.trans
    (definingPointsSubgroupMulEquiv R m)

/-- The quotient-point inclusion agrees with the inclusion of flag-preserving symplectic
matrices. -/
@[simp]
theorem pointsMulEquiv_coe
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R m) (CommAlgCat.of R A)) :
    Symplectic.pointsMulEquiv R m (A := A)
        (CommHopfAlgCat.quotientPointsHom
          (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)
          (CommAlgCat.of R A) f) =
      (pointsMulEquiv R m (A := A) f : GLSymplecticFin m A) := by
  have h := CommHopfAlgCat.quotientPointsSubgroupNatIso_hom_app_apply
    (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m) (CommAlgCat.of R A) f
  calc
    _ = Symplectic.pointsMulEquiv R m (A := A)
          (((CommHopfAlgCat.quotientPointsSubgroupNatIso
            (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)).app
            (CommAlgCat.of R A)).hom f).val :=
      (congrArg (fun g ↦ Symplectic.pointsMulEquiv R m (A := A) g.val) h).symm
    _ = _ := (Subgroup.coe_congrOfMapEq_apply _ _ _).symm

/-- The ambient point of a flag-preserving matrix is the symplectic point of that matrix. -/
@[simp]
theorem quotientPointsHom_pointsMulEquiv_symm (g : matrixSubgroup m (A := A)) :
    CommHopfAlgCat.quotientPointsHom
        (Symplectic.coordinateHopfAlgebra R m) (definingHopfIdeal R m)
        (CommAlgCat.of R A) ((pointsMulEquiv R m (A := A)).symm g) =
      (Symplectic.pointsMulEquiv R m (A := A)).symm g.val := by
  apply (Symplectic.pointsMulEquiv R m (A := A)).injective
  rw [pointsMulEquiv_coe, MulEquiv.apply_symm_apply, MulEquiv.apply_symm_apply]

variable {B : Type v} [CommRing B] [Algebra R B]

/-- The flag-subgroup point equivalence is natural in the value algebra, read on its
underlying symplectic matrix. -/
theorem pointsMulEquiv_mapValue (phi : A →ₐ[R] B)
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R m) (CommAlgCat.of R A)) :
    (pointsMulEquiv R m (A := B) (AlgHom.mapValue phi f) : GLSymplecticFin m B) =
      GLSymplecticFin.map m A phi.toRingHom (pointsMulEquiv R m (A := A) f) := by
  rw [← pointsMulEquiv_coe, ← CommHopfAlgCat.mapValue_quotientPointsHom,
    Symplectic.pointsMulEquiv_mapValue, pointsMulEquiv_coe]
  rfl

/-- Every algebra-valued point group of the isotropic flag subgroup is solvable. -/
theorem isSolvable_points :
    Group.IsSolvable
      (HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R m) (CommAlgCat.of R A)) := by
  let f : matrixSubgroup m (A := A) →* upperTriangularGroup (Fin (m + m)) A :=
    (((flagOrder m).reindexGL A).toMonoidHom.comp
      ((GLSymplecticFin m A).subtype.comp (Subgroup.subtype _))).codRestrict _ fun g ↦ g.property
  have hf : Function.Injective f := by
    intro g h hgh
    apply Subtype.ext
    apply Subtype.ext
    exact ((flagOrder m).reindexGL A).injective (congrArg Subtype.val hgh)
  exact Group.isSolvable_of_isSolvable_injective
    (f := f.comp (pointsMulEquiv R m (A := A)).toMonoidHom)
    (hf.comp (pointsMulEquiv R m (A := A)).injective)

end Points

/-- The isotropic flag subgroup has solvable geometric points over every field. -/
theorem geometricallySolvablePointsCommHopfAlgProperty_coordinateHopfAlgebra
    (k : Type u) [Field k] :
    geometricallySolvablePointsCommHopfAlgProperty k (coordinateHopfAlgebra k m) := by
  rw [geometricallySolvablePointsCommHopfAlgProperty_iff]
  exact isSolvable_points k m

/-- The diagonal symplectic torus lies in the standard isotropic flag subgroup.
The order of defining ideals reverses the inclusion of closed subgroups. -/
theorem definingHopfIdeal_le_diagonalTorusDefiningIdeal :
    definingHopfIdeal R m ≤ Symplectic.diagonalTorusDefiningIdeal R m := by
  rw [← HopfIdeal.toIdeal_le_toIdeal, definingHopfIdeal_toIdeal, Ideal.span_le]
  rintro x ⟨i, j, hij, rfl⟩
  rw [SetLike.mem_coe, HopfIdeal.mem_toIdeal, Symplectic.mem_diagonalTorusDefiningIdeal]
  exact Symplectic.coordinateMap_comp_diagonalTorusCoordinateMap_X_of_ne _ _
    (fun h ↦ hij.ne (congrArg (flagOrder m) h).symm)

/-- Restriction from the isotropic flag subgroup to its diagonal symplectic torus. -/
noncomputable def diagonalTorusCoordinateMap :
    coordinateHopfAlgebra R m ⟶
      (DiagonalizableGroup.coordinateRing R
        (SplitTorus.characterGroup (ULift.{u} (Fin m)))).obj :=
  CommHopfAlgCat.liftQuotient (definingHopfIdeal R m)
    (Symplectic.diagonalTorusCoordinateMap (R := R) (m := m)) (by
      intro x hx
      apply RingHom.mem_ker.mpr
      exact (Symplectic.mem_diagonalTorusDefiningIdeal R m x).mp
        (definingHopfIdeal_le_diagonalTorusDefiningIdeal R m hx))

/-- The factored torus restriction recovers the original restriction from the symplectic group. -/
@[reassoc (attr := simp)]
theorem coordinateMap_comp_diagonalTorusCoordinateMap :
    coordinateMap R m ≫ diagonalTorusCoordinateMap R m =
      Symplectic.diagonalTorusCoordinateMap (R := R) (m := m) :=
  CommHopfAlgCat.mkQuotient_comp_liftQuotient _ _ _

/-- The torus restriction from the isotropic flag subgroup is surjective. -/
theorem diagonalTorusCoordinateMap_surjective :
    Function.Surjective (diagonalTorusCoordinateMap R m).hom :=
  CommHopfAlgCat.liftQuotient_surjective_of_surjective _ _ _
    Symplectic.diagonalTorusCoordinateMap_surjective

end TauCeti.Symplectic.IsotropicFlag
