/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.QuadraticForm.Binary

/-!
# Chains of elementary equivalences between diagonal quadratic forms

This file defines the elementary steps in the chain theorem for diagonal quadratic forms. A
permutation step reorders the coefficients, while a binary step replaces two coefficients by an
equivalent binary form and leaves all other coefficients fixed. A diagonal chain is the reflexive
transitive closure of these two kinds of steps.

Permutation steps introduce no additional generators: every permutation is a chain of binary
steps, since a transposition of coefficients is itself a binary equivalence. The main result here
is the forward implication of the chain theorem: a diagonal chain induces an isometry between its
endpoint diagonal forms. The converse is the substantive Witt chain theorem.

## Main definitions

* `TauCeti.PermutationStep`: one permutation of a coefficient family.
* `TauCeti.BinaryStep`: one equivalent replacement of two coefficients.
* `TauCeti.DiagonalStep`: either kind of elementary step.
* `TauCeti.DiagonalChain`: a finite chain of elementary steps.

## Main results

* `TauCeti.PermutationStep.to_reflTransGen_binaryStep`: every permutation step is generated by
  binary steps.
* `TauCeti.DiagonalChain.equivalent`: the endpoint diagonal forms of a chain are isometric.

## References

* T. Y. Lam, *Introduction to Quadratic Forms over Fields*, Graduate Studies in Mathematics 67,
  American Mathematical Society (2005), Chapter I, Theorem 5.2.
-/

public section

open QuadraticMap

namespace TauCeti

universe u v

section Reindex

variable {R : Type u} [CommSemiring R] {ι : Type v} [Fintype ι] [DecidableEq ι]

omit [DecidableEq ι] in
/-- Permuting the coefficients of a diagonal form does not change its equivalence class. -/
theorem equivalent_weightedSumSquares_comp (w : ι → R) (σ : Equiv.Perm ι) :
    (weightedSumSquares R w).Equivalent (weightedSumSquares R (w ∘ σ)) := by
  refine ⟨{
    toLinearEquiv := LinearEquiv.funCongrLeft R R σ
    map_app' := fun x => ?_ }⟩
  simp only [weightedSumSquares_apply, Function.comp_apply, smul_eq_mul]
  simpa using (Equiv.sum_comp σ.symm (fun i => w (σ i) * (x (σ i) * x (σ i)))).symm

end Reindex

section PairExtension

variable {R : Type u} [CommSemiring R] {n : ℕ}
variable {w w' : Fin n → R} {i j : Fin n}

private def replacePair (f : (Fin 2 → R) → (Fin 2 → R)) (i j : Fin n)
    (x : Fin n → R) (k : Fin n) : R :=
  if k = i then f ![x i, x j] 0 else if k = j then f ![x i, x j] 1 else x k

private def pairLinearEquiv (hij : i ≠ j)
    (e : (weightedSumSquares R ![w i, w j]).IsometryEquiv
      (weightedSumSquares R ![w' i, w' j])) :
    (Fin n → R) ≃ₗ[R] (Fin n → R) where
  toFun := replacePair e i j
  invFun := replacePair e.symm i j
  left_inv x := by
    funext k
    by_cases hki : k = i
    · subst k
      simp only [replacePair]
      simp only [ite_true, hij.symm, ite_false]
      have hp : ![e ![x i, x j] 0, e ![x i, x j] 1] = e ![x i, x j] := by
        ext k
        fin_cases k <;> rfl
      rw [hp, e.symm_apply_apply]
      rfl
    by_cases hkj : k = j
    · subst k
      simp only [replacePair]
      simp only [hki, ite_false, ite_true, hij]
      have hp : ![e ![x i, x j] 0, e ![x i, x j] 1] = e ![x i, x j] := by
        ext k
        fin_cases k <;> rfl
      rw [hp, e.symm_apply_apply]
      rfl
    · simp [replacePair, hki, hkj]
  right_inv x := by
    funext k
    by_cases hki : k = i
    · subst k
      simp only [replacePair]
      simp only [ite_true, hij.symm, ite_false]
      have hp : ![e.symm ![x i, x j] 0, e.symm ![x i, x j] 1] = e.symm ![x i, x j] := by
        ext k
        fin_cases k <;> rfl
      rw [hp, e.apply_symm_apply]
      rfl
    by_cases hkj : k = j
    · subst k
      simp only [replacePair]
      simp only [hki, ite_false, ite_true, hij]
      have hp : ![e.symm ![x i, x j] 0, e.symm ![x i, x j] 1] = e.symm ![x i, x j] := by
        ext k
        fin_cases k <;> rfl
      rw [hp, e.apply_symm_apply]
      rfl
    · simp [replacePair, hki, hkj]
  map_add' x y := by
    funext k
    by_cases hki : k = i
    · subst k
      simpa [replacePair, hij, hij.symm] using
        congrFun (map_add e ![x i, x j] ![y i, y j]) 0
    by_cases hkj : k = j
    · subst k
      simpa [replacePair, hij, hij.symm] using
        congrFun (map_add e ![x i, x j] ![y i, y j]) 1
    · simp [replacePair, hki, hkj]
  map_smul' a x := by
    funext k
    by_cases hki : k = i
    · subst k
      simpa [replacePair, hij, hij.symm] using
        congrFun (map_smul e a ![x i, x j]) 0
    by_cases hkj : k = j
    · subst k
      simpa [replacePair, hij, hij.symm] using
        congrFun (map_smul e a ![x i, x j]) 1
    · simp [replacePair, hki, hkj]

private theorem sum_pair_add_rest (f : Fin n → R) (hij : i ≠ j) :
    ∑ k, f k = f i + f j + ∑ k ∈ (Finset.univ.erase i).erase j, f k := by
  calc
    ∑ k, f k = f i + ∑ k ∈ Finset.univ.erase i, f k :=
      (Finset.add_sum_erase Finset.univ f (Finset.mem_univ i)).symm
    _ = f i + (f j + ∑ k ∈ (Finset.univ.erase i).erase j, f k) := by
      rw [Finset.add_sum_erase (Finset.univ.erase i) f
        (Finset.mem_erase.mpr ⟨hij.symm, Finset.mem_univ j⟩)]
    _ = _ := by ac_rfl

private def pairIsometryEquiv (hij : i ≠ j)
    (e : (weightedSumSquares R ![w i, w j]).IsometryEquiv
      (weightedSumSquares R ![w' i, w' j]))
    (hrest : ∀ k, k ≠ i → k ≠ j → w k = w' k) :
    (weightedSumSquares R w).IsometryEquiv (weightedSumSquares R w') where
  toLinearEquiv := pairLinearEquiv hij e
  map_app' x := by
    simp only [weightedSumSquares_apply]
    rw [sum_pair_add_rest _ hij, sum_pair_add_rest _ hij]
    simp only [pairLinearEquiv]
    have hpair := e.map_app ![x i, x j]
    simp only [weightedSumSquares_apply, Fin.sum_univ_two, Matrix.cons_val_zero,
      Matrix.cons_val_one, smul_eq_mul] at hpair
    rw [show replacePair e i j x i = e ![x i, x j] 0 by simp [replacePair],
      show replacePair e i j x j = e ![x i, x j] 1 by simp [replacePair, hij.symm]]
    simp only [smul_eq_mul]
    rw [hpair]
    congr 1
    apply Finset.sum_congr rfl
    intro k hk
    have hki : k ≠ i := (Finset.mem_erase.mp (Finset.mem_erase.mp hk).2).1
    have hkj : k ≠ j := (Finset.mem_erase.mp hk).1
    simp [replacePair, hki, hkj, hrest k hki hkj]

/-- Replacing two distinct coefficients by an equivalent binary form, while fixing all other
coefficients, produces an equivalent diagonal form. -/
theorem equivalent_weightedSumSquares_of_pair (hij : i ≠ j)
    (hpair : (weightedSumSquares R ![w i, w j]).Equivalent
      (weightedSumSquares R ![w' i, w' j]))
    (hrest : ∀ k, k ≠ i → k ≠ j → w k = w' k) :
    (weightedSumSquares R w).Equivalent (weightedSumSquares R w') := by
  obtain ⟨e⟩ := hpair
  exact ⟨pairIsometryEquiv hij e hrest⟩

end PairExtension

section Steps

variable {R : Type u} [CommSemiring R] {n : ℕ}

/-- A permutation step reorders the unit coefficients of a regular diagonal quadratic form. -/
def PermutationStep (w w' : Fin n → Rˣ) : Prop :=
  ∃ σ : Equiv.Perm (Fin n), ∀ i, w' i = w (σ i)

/-- A binary step replaces two distinct unit coefficients by an equivalent binary form and fixes
all other coefficients. -/
def BinaryStep (w w' : Fin n → Rˣ) : Prop :=
  ∃ i j : Fin n, i ≠ j ∧
    (∀ k, k ≠ i → k ≠ j → w k = w' k) ∧
    (weightedSumSquares R ![(w i : R), (w j : R)]).Equivalent
      (weightedSumSquares R ![(w' i : R), (w' j : R)])

/-- An elementary step between diagonal coefficient families is either a permutation step or a
binary step. -/
def DiagonalStep (w w' : Fin n → Rˣ) : Prop :=
  PermutationStep w w' ∨ BinaryStep w w'

/-- A diagonal chain is a finite sequence of permutation or binary steps. -/
def DiagonalChain (w w' : Fin n → Rˣ) : Prop :=
  Relation.ReflTransGen DiagonalStep w w'

namespace PermutationStep

/-- Permutation steps may be reversed. -/
theorem symm {w w' : Fin n → Rˣ} (h : PermutationStep w w') : PermutationStep w' w := by
  obtain ⟨σ, hσ⟩ := h
  refine ⟨σ.symm, fun i => ?_⟩
  rw [hσ (σ.symm i), σ.apply_symm_apply]

/-- A transposition of two distinct coefficients is a binary step. -/
theorem swap_binaryStep (w : Fin n → Rˣ) {i j : Fin n} (hij : i ≠ j) :
    BinaryStep w (w ∘ Equiv.swap i j) := by
  refine ⟨i, j, hij, ?_, ?_⟩
  · intro k hki hkj
    simp [Function.comp_apply, Equiv.swap_apply_def, hki, hkj]
  · simpa [Function.comp_apply, Equiv.swap_apply_def, hij, hij.symm] using
      (equivalent_weightedSumSquares_comp ![(w i : R), (w j : R)] (Equiv.swap 0 1))

/-- Every permutation step is a reflexive-transitive chain of binary steps. Thus coefficient
permutations introduce no generators beyond binary equivalence. -/
theorem to_reflTransGen_binaryStep {w w' : Fin n → Rˣ} (h : PermutationStep w w') :
    Relation.ReflTransGen BinaryStep w w' := by
  obtain ⟨σ, hσ⟩ := h
  have hperm : ∀ (τ : Equiv.Perm (Fin n)) (v : Fin n → Rˣ),
      Relation.ReflTransGen BinaryStep v (v ∘ τ) := by
    intro τ
    induction τ using Equiv.Perm.swap_induction_on with
    | one =>
        intro v
        simpa using (Relation.ReflTransGen.refl :
          Relation.ReflTransGen BinaryStep v v)
    | swap_mul τ i j hij ih =>
        intro v
        refine (Relation.ReflTransGen.single (swap_binaryStep v hij)).trans ?_
        simpa [Function.comp_def] using ih (v ∘ Equiv.swap i j)
  convert hperm σ w using 1
  funext i
  exact hσ i

/-- A permutation step is a diagonal chain. -/
theorem to_diagonalChain {w w' : Fin n → Rˣ} (h : PermutationStep w w') :
    DiagonalChain w w' := by
  apply Relation.ReflTransGen.mono (r := BinaryStep) (p := DiagonalStep)
  · exact fun _ _ hbinary => Or.inr hbinary
  · exact h.to_reflTransGen_binaryStep

/-- The diagonal forms at the endpoints of a permutation step are equivalent. -/
theorem equivalent {w w' : Fin n → Rˣ} (h : PermutationStep w w') :
    (weightedSumSquares R fun i => (w i : R)).Equivalent
      (weightedSumSquares R fun i => (w' i : R)) := by
  obtain ⟨σ, hσ⟩ := h
  have hw : (fun i => (w' i : R)) = (fun i => (w i : R)) ∘ σ := by
    funext i
    exact congrArg Units.val (hσ i)
  rw [hw]
  exact equivalent_weightedSumSquares_comp (fun i => (w i : R)) σ

end PermutationStep

namespace BinaryStep

/-- Binary steps may be reversed. -/
theorem symm {w w' : Fin n → Rˣ} (h : BinaryStep w w') : BinaryStep w' w := by
  obtain ⟨i, j, hij, hrest, hpair⟩ := h
  exact ⟨i, j, hij, fun k hki hkj => (hrest k hki hkj).symm, hpair.symm⟩

/-- The diagonal forms at the endpoints of a binary step are equivalent. -/
theorem equivalent {w w' : Fin n → Rˣ} (h : BinaryStep w w') :
    (weightedSumSquares R fun i => (w i : R)).Equivalent
      (weightedSumSquares R fun i => (w' i : R)) := by
  obtain ⟨i, j, hij, hrest, hpair⟩ := h
  exact equivalent_weightedSumSquares_of_pair hij hpair fun k hki hkj =>
    congrArg Units.val (hrest k hki hkj)

end BinaryStep

namespace DiagonalStep

/-- Elementary diagonal steps may be reversed. -/
theorem symm {w w' : Fin n → Rˣ} (h : DiagonalStep w w') : DiagonalStep w' w :=
  h.elim (Or.inl ∘ PermutationStep.symm) (Or.inr ∘ BinaryStep.symm)

/-- The diagonal forms at the endpoints of an elementary diagonal step are equivalent. -/
theorem equivalent {w w' : Fin n → Rˣ} (h : DiagonalStep w w') :
    (weightedSumSquares R fun i => (w i : R)).Equivalent
      (weightedSumSquares R fun i => (w' i : R)) :=
  h.elim PermutationStep.equivalent BinaryStep.equivalent

end DiagonalStep

namespace DiagonalChain

/-- Every coefficient family is connected to itself by the empty diagonal chain. -/
theorem refl (w : Fin n → Rˣ) : DiagonalChain w w :=
  Relation.ReflTransGen.refl

/-- Diagonal chains compose. -/
theorem trans {w w' w'' : Fin n → Rˣ} (h : DiagonalChain w w')
    (h' : DiagonalChain w' w'') : DiagonalChain w w'' :=
  Relation.ReflTransGen.trans h h'

/-- Diagonal chains may be reversed. -/
theorem symm {w w' : Fin n → Rˣ} (h : DiagonalChain w w') : DiagonalChain w' w := by
  induction h with
  | refl => exact Relation.ReflTransGen.refl
  | tail hchain hstep ih =>
      exact (Relation.ReflTransGen.single hstep.symm).trans ih

/-- The diagonal forms at the endpoints of a diagonal chain are equivalent. This is the forward
implication of the Witt chain theorem. -/
theorem equivalent {w w' : Fin n → Rˣ} (h : DiagonalChain w w') :
    (weightedSumSquares R fun i => (w i : R)).Equivalent
      (weightedSumSquares R fun i => (w' i : R)) := by
  induction h using Relation.ReflTransGen.trans_induction_on with
  | refl => exact QuadraticMap.Equivalent.refl _
  | single hstep => exact hstep.equivalent
  | trans _ _ ih ih' => exact ih.trans ih'

end DiagonalChain

end Steps

end TauCeti
