/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Probability.Exchangeability.Arrays.AldousHoover.Basic
import Mathlib.Data.Sym.Sym2.Order
import TauCeti.MeasureTheory.Measure.Measurability
import TauCeti.Probability.Exchangeability.Arrays.Block.Basic
import TauCeti.Probability.Exchangeability.Arrays.Strip.Cell.OffDiagonalCoding
import TauCeti.Probability.Exchangeability.Arrays.Strip.VertexCoding
import TauCeti.Probability.Independence.InfinitePi
import TauCeti.Probability.Kernel.Randomization
import TauCeti.Probability.ProductMeasure

/-!
# The Aldous--Hoover representation of a jointly exchangeable array

**Aldous--Hoover theorem, joint form.** For every jointly exchangeable probability law `ρ` on
arrays `ℕ × ℕ → α` with values in a standard Borel space, there is a measurable
`F : I × I × I × I → α` such that `ρ` is the law of the array

```text
X i j = F(U, U_i, U_j, U_{i,j}),
```

where `U`, the vertex variables `U_i` and the variables `U_{i,j}` indexed by unordered pairs are
independent uniform variables. Together with
`TauCeti.Probability.AldousHoover.jointlyExchangeable_jointArray`, the converse, this characterizes
jointly exchangeable array laws as the laws of measurable joint Aldous--Hoover codings.

The vertex indices are split into three infinite classes: *hidden* vertices, a *reservoir*, and
*visible* vertices. The array read along the visible vertices has the law of the whole array. Its
entries are coded in three layers, from the outside in:

* the hidden square together with the reservoir vertex data is a random element of a standard
  Borel space, hence the image of the single global uniform variable `U`;
* given these, the data of each visible vertex — its strips against the hidden vertices in both
  orientations and its diagonal entry — are generated by one uniform variable per visible vertex
  (`JointlyExchangeable.exists_vertex_strip_diagonal_coding`);
* given all vertex data, both entries of every visible off-diagonal pair are generated from their
  square context and one uniform variable per unordered pair by a single common coding
  (`JointlyExchangeable.exists_common_offDiagonalArray_coding`).

In the last layer the common coding produces the pair `(x (i, j), x (j, i))` in a chosen
orientation, while `F` only sees the noise, not the indices. So `F` orients each pair by the order
of its two vertex variables, which are almost surely distinct, and reads the diagonal entry off the
vertex data when the two vertex variables coincide. Reversing the orientation of a pair does not
change its conditional law given its square context: joint exchangeability exchanges the two
vertices, so the common pair coding is equivariant in law under swapping its square context and its
output.

## Main results

* `TauCeti.Probability.JointlyExchangeable.exists_map_jointArray_eq` — every jointly exchangeable
  probability law on arrays is the law of a measurable joint Aldous--Hoover coding.
* `TauCeti.Probability.jointlyExchangeable_iff_exists_map_jointArray_eq` — an array process is
  jointly exchangeable if and only if its law is such a law.

## References

* D. Aldous, ["Representations for partially exchangeable arrays of random variables"]
  (https://doi.org/10.1016/0047-259X(81)90099-3), *Journal of Multivariate Analysis* 11
  (1981), 581--598.
* D. N. Hoover, "Relations on probability spaces and arrays of random variables", preprint,
  Institute for Advanced Study, Princeton, 1979.
* O. Kallenberg, [*Probabilistic Symmetries and Invariance Principles*]
  (https://doi.org/10.1007/0-387-28836-4), Springer, 2005, Chapter 7.

No material is adapted from `cameronfreer/exchangeability`, which treats sequences rather than
exchangeable arrays.
-/

public section

noncomputable section

open MeasureTheory ProbabilityTheory unitInterval

namespace TauCeti.Probability

namespace AldousHoover

/-- The noise of a joint Aldous--Hoover coding, sorted into the global variable, the vertex
variables, and the variables of the off-diagonal unordered pairs, indexed by the increasing
pairs. -/
private def splitJointNoise (u : NoiseIndex Unit (Sym2 ℕ) → I) :
    (I × (ℕ → I)) × ({t : ℕ × ℕ // t.1 < t.2} → I) :=
  ((u .global, fun k => u (.vertex () k)), fun t => u (.cell s(t.1.1, t.1.2)))

private theorem measurable_splitJointNoise : Measurable splitJointNoise :=
  ((measurable_pi_apply _).prodMk (Measurable.of_eval fun _ => measurable_pi_apply _)).prodMk
    (Measurable.of_eval fun _ => measurable_pi_apply _)

/-- The non-cell noise indices of a joint coding, read as `none` for the global index and `some k`
for the vertex index `k`. -/
private def jointVertexNoiseIndex : Option ℕ → NoiseIndex Unit (Sym2 ℕ)
  | none => .global
  | some k => .vertex () k

private theorem jointVertexNoiseIndex_injective : Function.Injective jointVertexNoiseIndex := by
  rintro (_ | _) (_ | _) h <;> simp_all [jointVertexNoiseIndex]

/-- **The joint-coding noise splits into independent pieces**: the global variable, the i.i.d.
vertex variables and the i.i.d. variables of the off-diagonal unordered pairs, indexed by the
increasing pairs, are independent uniform families. -/
private theorem map_splitJointNoise_noiseMeasure :
    (noiseMeasure Unit (Sym2 ℕ)).map splitJointNoise =
      ((volume : Measure I).prod (Measure.infinitePi fun _ : ℕ => (volume : Measure I))).prod
        (Measure.infinitePi fun _ : {t : ℕ × ℕ // t.1 < t.2} => (volume : Measure I)) := by
  set c : {t : ℕ × ℕ // t.1 < t.2} → NoiseIndex Unit (Sym2 ℕ) := fun t => .cell s(t.1.1, t.1.2)
  -- Increasing pairs are sorted, so `Sym2.mk` is injective on them.
  have hc : Function.Injective c := fun t t' h => by
    have := Sym2.sortEquiv.symm.injective (a₁ := ⟨t.1, t.2.le⟩) (a₂ := ⟨t'.1, t'.2.le⟩)
      (NoiseIndex.cell.inj h)
    exact Subtype.ext (Subtype.ext_iff.1 this :)
  have hdisj : Disjoint (Set.range jointVertexNoiseIndex) (Set.range c) := by
    rw [Set.disjoint_left]
    rintro _ ⟨(_ | _), rfl⟩ ⟨_, h⟩ <;> cases h
  -- Separate the cell noise, then the global variable from the vertex variables.
  set f₁ : (NoiseIndex Unit (Sym2 ℕ) → I) → (Option ℕ → I) × ({t : ℕ × ℕ // t.1 < t.2} → I) :=
    fun u => (fun o => u (jointVertexNoiseIndex o), fun t => u (c t))
  set f₂ : (Option ℕ → I) → I × (ℕ → I) := fun y => (y none, fun k => y (some k))
  have h₁ : Measurable f₁ := (Measurable.of_eval fun _ => measurable_pi_apply _).prodMk
    (Measurable.of_eval fun _ => measurable_pi_apply _)
  have h₂ : Measurable f₂ :=
    (measurable_pi_apply _).prodMk (Measurable.of_eval fun _ => measurable_pi_apply _)
  have hsplit : splitJointNoise = Prod.map f₂ id ∘ f₁ := by
    funext u
    simp [splitJointNoise, f₁, f₂, c, jointVertexNoiseIndex]
  rw [hsplit, ← Measure.map_map (h₂.prodMap measurable_id) h₁, noiseMeasure_def,
    infinitePi_map_pair_comp _ hc hdisj,
    Measure.map_infinitePi_infinitePi_of_inj jointVertexNoiseIndex_injective,
    ← Measure.map_prod_map _ _ h₂ measurable_id, Measure.map_id,
    TauCeti.MeasureTheory.Measure.infinitePi_map_none_some]

end AldousHoover

open AldousHoover

variable {α : Type*} [MeasurableSpace α]

/-! ## Square contexts read off vertex data -/

/-- The data of the vertex `k` relative to the hidden vertices `e`: its entries against every
hidden vertex in both orientations, and its diagonal entry. -/
private def vertexDatum (e : ℕ → ℕ) (x : ℕ × ℕ → α) (k : ℕ) : (ℕ → α × α) × α :=
  (fun b => (x (k, e b), x (e b, k)), x (k, k))

/-- The square context of an ordered pair of vertices, read off the hidden square `h` and the
vertex data `p` and `q` of the two vertices. -/
private def squareContextOfVertexData (h : ℕ × ℕ → α) (p q : (ℕ → α × α) × α) :
    ((((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α)) × (((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α))) × (α × α) :=
  ((((h, fun b => (p.1 b).1), fun a => (q.1 a).2), ((h, fun b => (q.1 b).1), fun a => (p.1 a).2)),
    (p.2, q.2))

private theorem measurable_squareContextOfVertexData :
    Measurable fun r : (ℕ × ℕ → α) × ((ℕ → α × α) × α) × ((ℕ → α × α) × α) =>
      squareContextOfVertexData r.1 r.2.1 r.2.2 := by
  unfold squareContextOfVertexData
  fun_prop

/-- The square context of the increasing pair `t` of visible vertices, read off the hidden square
and the visible vertex data. -/
private def visibleSquareContext (t : {t : ℕ × ℕ // t.1 < t.2})
    (r : ((ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α)) × (ℕ → (ℕ → α × α) × α)) :
    ((((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α)) × (((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α))) × (α × α) :=
  squareContextOfVertexData r.1.1 (r.2 t.1.1) (r.2 t.1.2)

private theorem measurable_visibleSquareContext (t : {t : ℕ × ℕ // t.1 < t.2}) :
    Measurable (visibleSquareContext (α := α) t) := by
  unfold visibleSquareContext squareContextOfVertexData
  fun_prop

omit [MeasurableSpace α] in
/-- Exchanging the two vertices swaps both the two directed contexts and the two diagonal entries
of the square context. -/
private theorem squareContextOfVertexData_swap (h : ℕ × ℕ → α) (p q : (ℕ → α × α) × α) :
    squareContextOfVertexData h q p =
      ((squareContextOfVertexData h p q).1.swap, (squareContextOfVertexData h p q).2.swap) :=
  rfl

omit [MeasurableSpace α] in
/-- The square context of a pair of vertices is read off the hidden square and the two vertex
data. -/
private theorem squareContextOfVertexData_vertexDatum (e : ℕ → ℕ) (x : ℕ × ℕ → α) (i j : ℕ) :
    squareContextOfVertexData (fun q => x (e q.1, e q.2)) (vertexDatum e x i) (vertexDatum e x j) =
      offDiagonalPairSquareContext e i j x := by
  simp [squareContextOfVertexData, vertexDatum, Prod.ext_iff, funext_iff]

/-- The data of all three vertex layers: the hidden square read along `e` with the reservoir vertex
data along `d`, together with the visible vertex data along `g`. -/
private def vertexLayerData (e d g : ℕ → ℕ) (x : ℕ × ℕ → α) :
    ((ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α)) × (ℕ → (ℕ → α × α) × α) :=
  ((fun q => x (e q.1, e q.2), fun k => vertexDatum e x (d k)), fun i => vertexDatum e x (g i))

private theorem measurable_vertexLayerData (e d g : ℕ → ℕ) :
    Measurable (vertexLayerData (α := α) e d g) := by
  unfold vertexLayerData vertexDatum
  fun_prop

omit [MeasurableSpace α] in
private theorem visibleSquareContext_vertexLayerData (e d g : ℕ → ℕ)
    (t : {t : ℕ × ℕ // t.1 < t.2}) (x : ℕ × ℕ → α) :
    visibleSquareContext t (vertexLayerData e d g x) =
      offDiagonalPairSquareContext e (g t.1.1) (g t.1.2) x :=
  squareContextOfVertexData_vertexDatum e x _ _

/-- The visible off-diagonal pairs `(x (g i, g j), x (g j, g i))` at the increasing pairs
`(i, j)`. -/
private def visiblePairs (g : ℕ → ℕ) (x : ℕ × ℕ → α) (t : {t : ℕ × ℕ // t.1 < t.2}) : α × α :=
  (x (g t.1.1, g t.1.2), x (g t.1.2, g t.1.1))

private theorem measurable_visiblePairs (g : ℕ → ℕ) : Measurable (visiblePairs (α := α) g) :=
  Measurable.of_eval fun _ => (measurable_pi_apply _).prodMk (measurable_pi_apply _)

/-- Coding every visible pair by a common pair coding `G` from its square context is measurable,
jointly with the vertex data. -/
private theorem measurable_visiblePairCoding
    {G : ((((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α)) × (((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α))) ×
      (α × α) → I → α × α} (hG : Measurable (Function.uncurry G)) :
    Measurable fun q : (((ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α)) × (ℕ → (ℕ → α × α) × α)) ×
        ({t : ℕ × ℕ // t.1 < t.2} → I) => (q.1, fun t => G (visibleSquareContext t q.1) (q.2 t)) :=
  measurable_fst.prodMk <| measurable_pi_uncurry_prod
    (f := fun t q s => G (visibleSquareContext t q) s) fun t =>
      hG.comp (((measurable_visibleSquareContext t).comp measurable_fst).prodMk measurable_snd)

/-! ## Assembling an array from vertex data and off-diagonal pairs -/

/-- The array whose diagonal entries are read off the vertex data `p` and whose off-diagonal
entries are read off the values `w t` at the increasing pairs `t`: in the orientation of `t` above
the diagonal and in the reverse orientation below it. -/
private def assembleArray (p : ℕ → (ℕ → α × α) × α) (w : {t : ℕ × ℕ // t.1 < t.2} → α × α) :
    ℕ × ℕ → α := fun q =>
  if h : q.1 < q.2 then (w ⟨q, h⟩).1 else if h' : q.2 < q.1 then (w ⟨q.swap, h'⟩).2 else (p q.1).2

private theorem measurable_assembleArray :
    Measurable fun r : (ℕ → (ℕ → α × α) × α) × ({t : ℕ × ℕ // t.1 < t.2} → α × α) =>
      assembleArray r.1 r.2 := by
  refine Measurable.of_eval fun q => ?_
  simp only [assembleArray]
  by_cases h : q.1 < q.2
  · simp only [h, ↓reduceDIte]
    exact measurable_fst.comp ((measurable_pi_apply _).comp measurable_snd)
  by_cases h' : q.2 < q.1
  · simp only [h, h', ↓reduceDIte]
    exact measurable_snd.comp ((measurable_pi_apply _).comp measurable_snd)
  · simp only [h, h', ↓reduceDIte]
    exact measurable_snd.comp ((measurable_pi_apply _).comp measurable_fst)

omit [MeasurableSpace α] in
/-- The array read along `g` is assembled from the visible vertex data and the visible pairs. -/
private theorem assembleArray_visiblePairs (e d g : ℕ → ℕ) (x : ℕ × ℕ → α) :
    assembleArray (vertexLayerData e d g x).2 (visiblePairs g x) = fun p => x (g p.1, g p.2) := by
  funext ⟨i, j⟩
  simp only [assembleArray]
  split_ifs with h h'
  · rfl
  · rfl
  · obtain rfl : i = j := le_antisymm (not_lt.1 h') (not_lt.1 h)
    rfl

/-! ## The coding function -/

/-- The joint Aldous--Hoover coding assembled from a coding `φ` of the hidden square and the
reservoir, a vertex coding `v` and a pair coding `g`. The pair `{i, j}` is oriented by the order of
the two vertex variables, and equal vertex variables produce the diagonal entry of the vertex. -/
private def jointCoding (φ : I → (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α))
    (v : (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α) → I → (ℕ → α × α) × α)
    (g : ((((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α)) × (((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α))) ×
      (α × α) → I → α × α) (t : I × I × I × I) : α :=
  if t.2.1 < t.2.2.1 then
    (g (squareContextOfVertexData (φ t.1).1 (v (φ t.1) t.2.1) (v (φ t.1) t.2.2.1)) t.2.2.2).1
  else if t.2.2.1 < t.2.1 then
    (g (squareContextOfVertexData (φ t.1).1 (v (φ t.1) t.2.2.1) (v (φ t.1) t.2.1)) t.2.2.2).2
  else (v (φ t.1) t.2.1).2

private theorem measurable_jointCoding {φ : I → (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α)}
    {v : (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α) → I → (ℕ → α × α) × α}
    {g : ((((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α)) × (((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α))) ×
      (α × α) → I → α × α}
    (hφ : Measurable φ) (hv : Measurable (Function.uncurry v))
    (hg : Measurable (Function.uncurry g)) : Measurable (jointCoding φ v g) := by
  have hφ₁ : Measurable fun t : I × I × I × I => φ t.1 := hφ.comp measurable_fst
  have hv₁ : Measurable fun t : I × I × I × I => v (φ t.1) t.2.1 :=
    hv.comp (hφ₁.prodMk (measurable_fst.comp measurable_snd))
  have hv₂ : Measurable fun t : I × I × I × I => v (φ t.1) t.2.2.1 :=
    hv.comp (hφ₁.prodMk (measurable_fst.comp (measurable_snd.comp measurable_snd)))
  have hs : Measurable fun t : I × I × I × I => t.2.2.2 :=
    measurable_snd.comp (measurable_snd.comp measurable_snd)
  have hpair {a b : I × I × I × I → (ℕ → α × α) × α} (ha : Measurable a) (hb : Measurable b) :
      Measurable fun t : I × I × I × I =>
        g (squareContextOfVertexData (φ t.1).1 (a t) (b t)) t.2.2.2 :=
    hg.comp ((measurable_squareContextOfVertexData.comp
      ((measurable_fst.comp hφ₁).prodMk (ha.prodMk hb))).prodMk hs)
  exact Measurable.ite (measurableSet_lt (measurable_fst.comp measurable_snd)
      (measurable_fst.comp (measurable_snd.comp measurable_snd))) (hpair hv₁ hv₂).fst
    (Measurable.ite (measurableSet_lt (measurable_fst.comp (measurable_snd.comp measurable_snd))
      (measurable_fst.comp measurable_snd)) (hpair hv₂ hv₁).snd hv₁.snd)

omit [MeasurableSpace α] in
private theorem jointCoding_of_lt {φ : I → (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α)}
    {v : (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α) → I → (ℕ → α × α) × α}
    {g : ((((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α)) × (((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α))) ×
      (α × α) → I → α × α} {a b c s : I} (h : b < c) :
    jointCoding φ v g (a, b, c, s) =
      (g (squareContextOfVertexData (φ a).1 (v (φ a) b) (v (φ a) c)) s).1 := by
  simp [jointCoding, h]

omit [MeasurableSpace α] in
private theorem jointCoding_of_gt {φ : I → (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α)}
    {v : (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α) → I → (ℕ → α × α) × α}
    {g : ((((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α)) × (((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α))) ×
      (α × α) → I → α × α} {a b c s : I} (h : c < b) :
    jointCoding φ v g (a, b, c, s) =
      (g (squareContextOfVertexData (φ a).1 (v (φ a) c) (v (φ a) b)) s).2 := by
  simp [jointCoding, h, h.not_gt]

omit [MeasurableSpace α] in
private theorem jointCoding_self {φ : I → (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α)}
    {v : (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α) → I → (ℕ → α × α) × α}
    {g : ((((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α)) × (((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α))) ×
      (α × α) → I → α × α} {a b s : I} :
    jointCoding φ v g (a, b, b, s) = (v (φ a) b).2 := by
  simp [jointCoding]

omit [MeasurableSpace α] in
/-- The joint coding, reassembled from the vertex data generated by the vertex variables and from
the pairs generated by the joint coding in both orders of the vertex variables. -/
private theorem jointArray_jointCoding (φ : I → (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α))
    (v : (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α) → I → (ℕ → α × α) × α)
    (g : ((((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α)) × (((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α))) ×
      (α × α) → I → α × α) (u : NoiseIndex Unit (Sym2 ℕ) → I) :
    (fun p => jointArray (jointCoding φ v g) p u) =
      assembleArray (fun k => v (φ (u .global)) (u (.vertex () k))) fun t =>
        (jointCoding φ v g (u .global, u (.vertex () t.1.1), u (.vertex () t.1.2),
            u (.cell s(t.1.1, t.1.2))),
          jointCoding φ v g (u .global, u (.vertex () t.1.2), u (.vertex () t.1.1),
            u (.cell s(t.1.1, t.1.2)))) := by
  funext ⟨i, j⟩
  simp only [jointArray_apply, assembleArray]
  split_ifs with h h'
  · rfl
  · rw [Sym2.eq_swap]
    rfl
  · obtain rfl : i = j := le_antisymm (not_lt.1 h') (not_lt.1 h)
    exact jointCoding_self

/-! ## Swapping the orientation of a pair -/

variable [StandardBorelSpace α] {ρ : Measure (ℕ × ℕ → α)}

/-- **The common pair coding is swap-equivariant in law.** Suppose `g` codes the pair
`(x (i, j), x (j, i))` from its square context and a uniform variable. Exchanging the vertices `i`
and `j` swaps the pair and both components of the square context, and preserves their joint law by
joint exchangeability. Hence for almost every square context `z`, swapping the output of `g` at the
swapped context has the law of `g` at `z`. -/
private theorem ae_map_swap_pairCoding_eq [IsFiniteMeasure ρ]
    (hρ : JointlyExchangeable ρ fun p x => x p) {e : ℕ → ℕ} {i j : ℕ} (hij : i ≠ j)
    (hi : i ∉ Set.range e) (hj : j ∉ Set.range e)
    {g : ((((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α)) × (((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α))) ×
      (α × α) → I → α × α} (hg : Measurable (Function.uncurry g))
    (hcode : ((ρ.map (offDiagonalPairSquareContext e i j)).prod (volume : Measure I)).map
        (fun p => (p.1, g p.1 p.2)) =
      ρ.map fun x => (offDiagonalPairSquareContext e i j x, (x (i, j), x (j, i)))) :
    ∀ᵐ z ∂ρ.map (offDiagonalPairSquareContext e i j),
      (volume : Measure I).map (fun s => (g (z.1.swap, z.2.swap) s).swap) =
        (volume : Measure I).map (g z) := by
  set C := offDiagonalPairSquareContext (α := α) e i j
  set L := ρ.map C
  have hC : Measurable C := measurable_offDiagonalPairSquareContext e i j
  have hP : Measurable fun x : ℕ × ℕ → α => (x (i, j), x (j, i)) :=
    (measurable_pi_apply _).prodMk (measurable_pi_apply _)
  set sw : ((((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α)) × (((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α))) ×
      (α × α) → _ := fun z => (z.1.swap, z.2.swap)
  have hsw : Measurable sw :=
    (measurable_swap.comp measurable_fst).prodMk (measurable_swap.comp measurable_snd)
  -- Exchanging `i` and `j` swaps the square context and the pair, and preserves their joint law.
  have hsym : (ρ.map fun x => (C x, (x (i, j), x (j, i)))).map (Prod.map sw Prod.swap) =
      ρ.map fun x => (C x, (x (i, j), x (j, i))) := by
    rw [Measure.map_map (hsw.prodMap measurable_swap) (hC.prodMk hP)]
    refine Eq.trans ?_ (hρ.map_offDiagonalPairSquareContext_entries_eq e hij hij.symm hi hj hj hi)
    congr 1
    funext x
    exact Prod.ext (offDiagonalPairSquareContext_swap e i j x).symm rfl
  have hfst : (ρ.map fun x => (C x, (x (i, j), x (j, i)))).map Prod.fst = L := by
    rw [Measure.map_map measurable_fst (hC.prodMk hP)]
    rfl
  have hL : L.map sw = L := by
    have := congrArg (Measure.map Prod.fst) hsym
    rw [Measure.map_map measurable_fst (hsw.prodMap measurable_swap), hfst] at this
    conv_rhs => rw [← this]
    rw [Prod.map_fst', ← Measure.map_map hsw measurable_fst, hfst]
  -- The swapped coding realizes the same joint law as the coding itself.
  have hg' : Measurable (Function.uncurry fun z s => (g (sw z) s).swap) :=
    measurable_swap.comp (hg.comp (hsw.prodMap measurable_id))
  have hcode' : (L.prod (volume : Measure I)).map (fun p => (p.1, (g (sw p.1) p.2).swap)) =
      (L.prod (volume : Measure I)).map (fun p => (p.1, g p.1 p.2)) := by
    -- Swapping the square context twice restores it.
    have hsw₂ (z) : sw (sw z) = z := by simp [sw]
    have hfun : (fun p : _ × I => (p.1, (g (sw p.1) p.2).swap)) ∘ Prod.map sw id =
        Prod.map sw Prod.swap ∘ fun p => (p.1, g p.1 p.2) := by
      funext p
      simp [hsw₂]
    have hF : Measurable fun p : _ × I => (p.1, g p.1 p.2) := measurable_fst.prodMk hg
    have hF' : Measurable fun p : _ × I => (p.1, (g (sw p.1) p.2).swap) :=
      measurable_fst.prodMk hg'
    conv_lhs => rw [← hL, ← Measure.map_id (μ := (volume : Measure I)),
      Measure.map_prod_map _ _ hsw measurable_id,
      Measure.map_map hF' (hsw.prodMap measurable_id), hfun,
      ← Measure.map_map (hsw.prodMap measurable_swap) hF, hcode, hsym, ← hcode]
  -- Equal joint laws with the square context have almost everywhere equal fibre laws.
  exact ae_map_eq_of_map_prod_eq _ hg' hg hcode'

/-- **Orienting a pair by its vertex variables does not change the law of its coding.** Let `G`
code the pair at `(i, j)` from its square context, and let the square context generated from the
global variable and the vertex variables `k ≠ l` have the law of the square context of `(i, j)`.
For almost every global and vertex noise, the pair that the joint coding produces at `(k, l)` and
`(l, k)` has the law of `G` at the generated square context. -/
private theorem ae_map_jointCoding_eq [IsFiniteMeasure ρ]
    (hρ : JointlyExchangeable ρ fun p x => x p) {e : ℕ → ℕ} {i j : ℕ} (hij : i ≠ j)
    (hi : i ∉ Set.range e) (hj : j ∉ Set.range e)
    {φ : I → (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α)}
    {v : (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α) → I → (ℕ → α × α) × α}
    {G : ((((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α)) × (((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α))) ×
      (α × α) → I → α × α}
    (hφ : Measurable φ) (hv : Measurable (Function.uncurry v))
    (hG : Measurable (Function.uncurry G))
    (hcode : ((ρ.map (offDiagonalPairSquareContext e i j)).prod (volume : Measure I)).map
        (fun p => (p.1, G p.1 p.2)) =
      ρ.map fun x => (offDiagonalPairSquareContext e i j x, (x (i, j), x (j, i))))
    {k l : ℕ} (hkl : k ≠ l)
    (hlaw : ((volume : Measure I).prod (Measure.infinitePi fun _ : ℕ => (volume : Measure I))).map
        (fun q => squareContextOfVertexData (φ q.1).1 (v (φ q.1) (q.2 k)) (v (φ q.1) (q.2 l))) =
      ρ.map (offDiagonalPairSquareContext e i j)) :
    ∀ᵐ q ∂(volume : Measure I).prod (Measure.infinitePi fun _ : ℕ => (volume : Measure I)),
      (volume : Measure I).map
          (G (squareContextOfVertexData (φ q.1).1 (v (φ q.1) (q.2 k)) (v (φ q.1) (q.2 l)))) =
        (volume : Measure I).map fun s =>
          (jointCoding φ v G (q.1, q.2 k, q.2 l, s), jointCoding φ v G (q.1, q.2 l, q.2 k, s)) := by
  have hφ₁ : Measurable fun q : I × (ℕ → I) => φ q.1 := hφ.comp measurable_fst
  have hvk (m : ℕ) : Measurable fun q : I × (ℕ → I) => v (φ q.1) (q.2 m) :=
    hv.comp (hφ₁.prodMk ((measurable_pi_apply m).comp measurable_snd))
  have hctx : Measurable fun q : I × (ℕ → I) =>
      squareContextOfVertexData (φ q.1).1 (v (φ q.1) (q.2 k)) (v (φ q.1) (q.2 l)) :=
    measurable_squareContextOfVertexData.comp
      ((measurable_fst.comp hφ₁).prodMk ((hvk k).prodMk (hvk l)))
  -- The two vertex variables are almost surely distinct.
  have hne : ∀ᵐ q ∂(volume : Measure I).prod
      (Measure.infinitePi fun _ : ℕ => (volume : Measure I)), q.2 k ≠ q.2 l := by
    refine ae_of_ae_map (p := fun u : ℕ → I => u k ≠ u l) measurable_snd.aemeasurable ?_
    rw [Measure.map_snd_prod, measure_univ, one_smul]
    exact ae_eval_ne_eval_infinitePi _ hkl
  -- At almost every generated square context, the reversed coding has the law of the coding.
  have hswap : ∀ᵐ q ∂(volume : Measure I).prod
      (Measure.infinitePi fun _ : ℕ => (volume : Measure I)),
      (volume : Measure I).map (fun s => (G (squareContextOfVertexData (φ q.1).1
          (v (φ q.1) (q.2 l)) (v (φ q.1) (q.2 k))) s).swap) =
        (volume : Measure I).map
          (G (squareContextOfVertexData (φ q.1).1 (v (φ q.1) (q.2 k)) (v (φ q.1) (q.2 l)))) := by
    have h := ae_of_ae_map (p := fun z => (volume : Measure I).map
      (fun s => (G (z.1.swap, z.2.swap) s).swap) = (volume : Measure I).map (G z))
      hctx.aemeasurable (by rw [hlaw]; exact ae_map_swap_pairCoding_eq hρ hij hi hj hG hcode)
    filter_upwards [h] with q hq
    rwa [squareContextOfVertexData_swap _ (v (φ q.1) (q.2 k))]
  -- The joint coding follows `G` when the vertex variables are increasing, and reverses it when
  -- they are decreasing.
  filter_upwards [hne, hswap] with q hq hq'
  rcases hq.lt_or_gt with h | h
  · refine congrArg (fun f => (volume : Measure I).map f) (funext fun s => ?_)
    rw [jointCoding_of_lt h, jointCoding_of_gt h]
  · refine hq'.symm.trans (congrArg (fun f => (volume : Measure I).map f) (funext fun s => ?_))
    rw [jointCoding_of_lt h, jointCoding_of_gt h, Prod.swap]

/-! ## The representation -/

/-- **The pair layer, read along visible vertices.** Hide the vertices in the range of `e` and read
the array along the strictly increasing enumeration `g` of visible vertices. One common pair coding
`G`, fed with the square contexts read off the hidden square and the vertex data, and with one
i.i.d. uniform variable per increasing pair, reproduces the joint law of the hidden square, the
reservoir data along `d`, the visible vertex data and all visible off-diagonal pairs. -/
private theorem exists_map_pairCoding_visible_eq [Nonempty α] [IsFiniteMeasure ρ]
    (hρ : JointlyExchangeable ρ fun p x => x p) {e d g : ℕ → ℕ} (he : (Set.range e).Infinite)
    (hg : StrictMono g) (hge : ∀ i, g i ∉ Set.range e) :
    ∃ G : ((((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α)) × (((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α))) ×
        (α × α) → I → α × α, Measurable (Function.uncurry G) ∧
      ((ρ.map (vertexLayerData e d g)).prod
          (Measure.infinitePi fun _ : {t : ℕ × ℕ // t.1 < t.2} => (volume : Measure I))).map
        (fun q => (q.1, fun t => G (visibleSquareContext t q.1) (q.2 t))) =
      ρ.map fun x => (vertexLayerData e d g x, visiblePairs g x) := by
  obtain ⟨G, hG, hP⟩ :=
    hρ.exists_common_offDiagonalArray_coding he
  refine ⟨G, hG, ?_⟩
  set H : Set (ℕ × ℕ) :=
    (Set.univ ×ˢ Set.range e) ∪ (Set.range e ×ˢ Set.univ) ∪ {p : ℕ × ℕ | p.1 = p.2}
  set V₂ : Set (ℕ × ℕ) := {p | p.1 ∉ Set.range e ∧ p.2 ∉ Set.range e ∧ p.1 < p.2}
  -- Every entry of the vertex data lies in a hidden row, a hidden column, or on the diagonal.
  have hrow (a b : ℕ) : (a, e b) ∈ H :=
    Or.inl (Or.inl ⟨Set.mem_univ _, Set.mem_range_self b⟩)
  have hcol (a b : ℕ) : (e b, a) ∈ H := Or.inl (Or.inr ⟨Set.mem_range_self b, Set.mem_univ _⟩)
  have hdiag (a : ℕ) : (a, a) ∈ H := Or.inr rfl
  set datum : (H → α) → ℕ → (ℕ → α × α) × α := fun y k =>
    (fun b => (y ⟨(k, e b), hrow k b⟩, y ⟨(e b, k), hcol k b⟩), y ⟨(k, k), hdiag k⟩)
  set read : (H → α) → ((ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α)) × (ℕ → (ℕ → α × α) × α) :=
    fun y => ((fun q => y ⟨(e q.1, e q.2), hrow _ _⟩, fun k => datum y (d k)),
      fun i => datum y (g i))
  have hdatum (k : ℕ) : Measurable fun y : H → α => datum y k :=
    (Measurable.of_eval fun _ => (measurable_pi_apply _).prodMk (measurable_pi_apply _)).prodMk
      (measurable_pi_apply _)
  have hread : Measurable read :=
    ((Measurable.of_eval fun _ => measurable_pi_apply _).prodMk
      (Measurable.of_eval fun k => hdatum (d k))).prodMk (Measurable.of_eval fun i => hdatum (g i))
  -- The visible increasing pairs, as visible off-diagonal pairs of the array.
  set ι : {t : ℕ × ℕ // t.1 < t.2} → V₂ := fun t => ⟨(g t.1.1, g t.1.2), hge _, hge _, hg t.2⟩
  have hι : Function.Injective ι := by
    intro t t' h
    have h' := congrArg Subtype.val h
    simp only [ι, Prod.mk.injEq] at h'
    exact Subtype.ext (Prod.ext (hg.injective h'.1) (hg.injective h'.2))
  set M : (H → α) × (V₂ → α × α) → _ := fun r => (read r.1, fun t => r.2 (ι t))
  have hM : Measurable M :=
    (hread.comp measurable_fst).prodMk (Measurable.of_eval fun _ =>
      (measurable_pi_apply _).comp measurable_snd)
  set Λ : (((ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α)) × (ℕ → (ℕ → α × α) × α)) ×
      ({t : ℕ × ℕ // t.1 < t.2} → I) → _ := fun q =>
    (q.1, fun t => G (visibleSquareContext t q.1) (q.2 t))
  have hΛ : Measurable Λ := measurable_visiblePairCoding hG
  have hV : Measurable fun x : ℕ × ℕ → α => read (H.domRestrict x) :=
    hread.comp (Set.measurable_restrict H)
  have hsel : Measurable fun (c : V₂ → I) (t : {t : ℕ × ℕ // t.1 < t.2}) => c (ι t) :=
    Measurable.of_eval fun _ => measurable_pi_apply _
  have hcodeP : Measurable fun q : (ℕ × ℕ → α) × (V₂ → I) =>
      (H.domRestrict q.1,
        fun p : V₂ => G (offDiagonalPairSquareContext e p.1.1 p.1.2 q.1) (q.2 p)) :=
    ((Set.measurable_restrict H).comp measurable_fst).prodMk (Measurable.of_eval fun p =>
      hG.comp (((measurable_offDiagonalPairSquareContext e p.1.1 p.1.2).comp
        measurable_fst).prodMk ((measurable_pi_apply p).comp measurable_snd)))
  have hpairs : Measurable fun x : ℕ × ℕ → α =>
      (H.domRestrict x, fun p : V₂ => (x p.1, x p.1.swap)) :=
    (Set.measurable_restrict H).prodMk (Measurable.of_eval fun p =>
      (measurable_pi_apply p.1).prodMk (measurable_pi_apply p.1.swap))
  -- Reading the vertex data and the visible pairs off the pair coding.
  have hfac : M ∘ (fun q : (ℕ × ℕ → α) × (V₂ → I) => (H.domRestrict q.1,
        fun p : V₂ => G (offDiagonalPairSquareContext e p.1.1 p.1.2 q.1) (q.2 p))) =
      Λ ∘ Prod.map (fun x => read (H.domRestrict x)) (fun c t => c (ι t)) := by
    funext q
    refine Prod.ext rfl (funext fun t => ?_)
    -- The data read off the hidden entries are the vertex data of the array.
    have hdatum (k : ℕ) : datum (H.domRestrict q.1) k = vertexDatum e q.1 k := by
      simp [datum, vertexDatum]
    simp only [Function.comp_apply, Prod.map, M, Λ, ι, read, visibleSquareContext, hdatum,
      Set.domRestrict_apply, squareContextOfVertexData_vertexDatum]
  have hunif : (Measure.infinitePi fun _ : V₂ => (volume : Measure I)).map (fun c t => c (ι t)) =
      Measure.infinitePi fun _ : {t : ℕ × ℕ // t.1 < t.2} => (volume : Measure I) :=
    Measure.map_infinitePi_infinitePi_of_inj hι
  have hP' := congrArg (Measure.map M) hP
  rw [Measure.map_map hM hcodeP, Measure.map_map hM hpairs, hfac,
    ← Measure.map_map hΛ (hV.prodMap hsel), ← Measure.map_prod_map _ _ hV hsel, hunif] at hP'
  exact hP'

omit [StandardBorelSpace α] in
/-- The coding of all visible pairs codes each visible pair `(g i, g j)`, `i < j`, from its own
square context. -/
private theorem map_pairCoding_visiblePair_eq [IsFiniteMeasure ρ] {e d g : ℕ → ℕ}
    {G : ((((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α)) × (((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α))) ×
      (α × α) → I → α × α} (hG : Measurable (Function.uncurry G))
    (hcode : ((ρ.map (vertexLayerData e d g)).prod
          (Measure.infinitePi fun _ : {t : ℕ × ℕ // t.1 < t.2} => (volume : Measure I))).map
        (fun q => (q.1, fun t => G (visibleSquareContext t q.1) (q.2 t))) =
      ρ.map fun x => (vertexLayerData e d g x, visiblePairs g x))
    (t : {t : ℕ × ℕ // t.1 < t.2}) :
    ((ρ.map (offDiagonalPairSquareContext e (g t.1.1) (g t.1.2))).prod (volume : Measure I)).map
        (fun p => (p.1, G p.1 p.2)) =
      ρ.map fun x => (offDiagonalPairSquareContext e (g t.1.1) (g t.1.2) x,
        (x (g t.1.1, g t.1.2), x (g t.1.2, g t.1.1))) := by
  have hR := measurable_vertexLayerData (α := α) e d g
  have hvsc := measurable_visibleSquareContext (α := α) t
  have hctx : visibleSquareContext (α := α) t ∘ vertexLayerData e d g =
      offDiagonalPairSquareContext e (g t.1.1) (g t.1.2) :=
    funext (visibleSquareContext_vertexLayerData e d g t)
  have heval : Measurable fun c : {t : ℕ × ℕ // t.1 < t.2} → I => c t := measurable_pi_apply _
  have hGp : Measurable fun p : _ × I => (p.1, G p.1 p.2) := measurable_fst.prodMk hG
  have hcod := measurable_visiblePairCoding hG
  -- Read the square context and the pair at `t` off both sides of the coding of all pairs.
  set π : (((ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α)) × (ℕ → (ℕ → α × α) × α)) ×
      ({t : ℕ × ℕ // t.1 < t.2} → α × α) → _ := fun r => (visibleSquareContext t r.1, r.2 t)
  have hπ : Measurable π := (hvsc.comp measurable_fst).prodMk
    ((measurable_pi_apply t).comp measurable_snd)
  -- Reading off the pair at `t` after coding all pairs codes the pair at `t` alone.
  have hπcod : π ∘ (fun q : _ × ({t : ℕ × ℕ // t.1 < t.2} → I) =>
        (q.1, fun t => G (visibleSquareContext t q.1) (q.2 t))) =
      (fun p => (p.1, G p.1 p.2)) ∘ Prod.map (visibleSquareContext t) fun c => c t := by
    funext q
    simp [π]
  have h := congrArg (Measure.map π) hcode
  rw [Measure.map_map hπ hcod, Measure.map_map hπ (hR.prodMk (measurable_visiblePairs g)), hπcod,
    ← Measure.map_map hGp (hvsc.prodMap heval), ← Measure.map_prod_map _ _ hvsc heval,
    Measure.infinitePi_map_eval, Measure.map_map hvsc hR, hctx] at h
  refine h.trans (congrArg (ρ.map ·) (funext fun x => ?_))
  exact Prod.ext (visibleSquareContext_vertexLayerData e d g t x) rfl

/-- **The vertex layers, coded by the global and the vertex variables.** The hidden square read
along `e` together with the reservoir vertex data along `d` is coded by the global variable through
`φ`, and given these the visible vertex data along `g` are coded by one uniform variable per visible
vertex through `v`. -/
private theorem exists_map_vertexLayerData_eq [Nonempty α] [IsProbabilityMeasure ρ]
    (hρ : JointlyExchangeable ρ fun p x => x p) {e d g : ℕ → ℕ} (he : Function.Injective e)
    (hd : Function.Injective d) (hg : Function.Injective g)
    (hed : Disjoint (Set.range e) (Set.range d)) (heg : Disjoint (Set.range e) (Set.range g))
    (hdg : Disjoint (Set.range d) (Set.range g)) :
    ∃ (φ : I → (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α))
      (v : (ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α) → I → (ℕ → α × α) × α),
      Measurable φ ∧ Measurable (Function.uncurry v) ∧
        ((volume : Measure I).prod (Measure.infinitePi fun _ : ℕ => (volume : Measure I))).map
            (fun q => (φ q.1, fun i => v (φ q.1) (q.2 i))) = ρ.map (vertexLayerData e d g) := by
  set R := vertexLayerData (α := α) e d g
  -- The outer layer: the hidden square and the reservoir data are coded by the global variable.
  set B : ProbabilityMeasure ((ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α)) :=
    ⟨ρ.map fun x => (R x).1, inferInstance⟩
  have hφ : Measurable (unitIntervalCoding _ B) := measurable_unitIntervalCoding B
  have hφB : (volume : Measure I).map (unitIntervalCoding _ B) = ρ.map fun x => (R x).1 :=
    map_volume_unitIntervalCoding B
  -- The middle layer: the visible vertex data are coded by the vertex variables.
  obtain ⟨v, hv, hvcode⟩ := hρ.exists_vertex_strip_diagonal_coding he hd hg hed heg hdg
  have hvcode' : ρ.map R = ((ρ.map fun x => (R x).1).prod
      (Measure.infinitePi fun _ : ℕ => (volume : Measure I))).map
        (fun p => (p.1, fun i => v p.1 (p.2 i))) := by
    simp only [R]
    unfold vertexLayerData vertexDatum
    exact hvcode
  have hV : Measurable fun p : ((ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α)) × (ℕ → I) =>
      (p.1, fun i => v p.1 (p.2 i)) :=
    measurable_fst.prodMk (measurable_pi_uncurry_prod fun _ => hv)
  refine ⟨unitIntervalCoding _ B, v, hφ, hv, ?_⟩
  -- Generating the vertex data from the coded hidden square and reservoir data.
  have hΘφ : (fun q : I × (ℕ → I) =>
        (unitIntervalCoding _ B q.1, fun i => v (unitIntervalCoding _ B q.1) (q.2 i))) =
      (fun p : _ × (ℕ → I) => (p.1, fun i => v p.1 (p.2 i))) ∘
        Prod.map (unitIntervalCoding _ B) id := by
    funext q
    simp
  rw [hΘφ, ← Measure.map_map hV (hφ.prodMap measurable_id),
    ← Measure.map_prod_map _ _ hφ measurable_id, Measure.map_id, hφB, hvcode']

/-- **The Aldous--Hoover representation of a jointly exchangeable array.** Every jointly
exchangeable probability law `ρ` on arrays with values in a standard Borel space is the law of a
measurable joint Aldous--Hoover coding: there is a measurable `F : I × I × I × I → α` with `ρ` the
law of `X i j = F(U, U_i, U_j, U_{i,j})` under independent uniform noise, where the cell variable
`U_{i,j}` is indexed by the unordered pair `{i, j}`. -/
theorem JointlyExchangeable.exists_map_jointArray_eq [IsProbabilityMeasure ρ]
    (hρ : JointlyExchangeable ρ fun p x => x p) :
    ∃ F : I × I × I × I → α, Measurable F ∧
      (noiseMeasure Unit (Sym2 ℕ)).map (fun u p => jointArray F p u) = ρ := by
  -- A probability law on arrays forces the value space to be nonempty.
  obtain ⟨x₀, -⟩ := nonempty_of_measure_ne_zero (μ := ρ) (s := Set.univ) (by simp)
  have : Nonempty α := ⟨x₀ (0, 0)⟩
  -- Hide the vertices `3 a`, keep the vertices `3 a + 1` as a reservoir, and read the array along
  -- the visible vertices `3 a + 2`.
  set e : ℕ → ℕ := fun a => 3 * a with he_def
  set d : ℕ → ℕ := fun a => 3 * a + 1 with hd_def
  set g : ℕ → ℕ := fun a => 3 * a + 2 with hg_def
  have he : Function.Injective e := fun a b h => by simp only [he_def] at h; omega
  have hd : Function.Injective d := fun a b h => by simp only [hd_def] at h; omega
  have hg : StrictMono g := fun a b h => by simp only [hg_def]; omega
  have hed : Disjoint (Set.range e) (Set.range d) := Set.disjoint_left.2 fun _ ⟨a, ha⟩ ⟨b, hb⟩ => by
    simp only [he_def, hd_def] at ha hb; omega
  have heg : Disjoint (Set.range e) (Set.range g) := Set.disjoint_left.2 fun _ ⟨a, ha⟩ ⟨b, hb⟩ => by
    simp only [he_def, hg_def] at ha hb; omega
  have hdg : Disjoint (Set.range d) (Set.range g) := Set.disjoint_left.2 fun _ ⟨a, ha⟩ ⟨b, hb⟩ => by
    simp only [hd_def, hg_def] at ha hb; omega
  have hge (i : ℕ) : g i ∉ Set.range e := fun h => Set.disjoint_left.1 heg h ⟨i, rfl⟩
  -- The outer two layers: the hidden square and the reservoir data are coded by the global
  -- variable, and the visible vertex data by the vertex variables.
  obtain ⟨φ, v, hφ, hv, hΘlaw⟩ :=
    exists_map_vertexLayerData_eq hρ he hd hg.injective hed heg hdg
  set R := vertexLayerData (α := α) e d g
  have hR : Measurable R := measurable_vertexLayerData e d g
  set Θ : I × (ℕ → I) → ((ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α)) × (ℕ → (ℕ → α × α) × α) :=
    fun q => (φ q.1, fun i => v (φ q.1) (q.2 i))
  have hΘ : Measurable Θ := (hφ.comp measurable_fst).prodMk
    ((measurable_pi_uncurry_prod fun _ => hv).comp (hφ.prodMap measurable_id))
  set μ₀ := (volume : Measure I).prod (Measure.infinitePi fun _ : ℕ => (volume : Measure I))
  -- The inner layer: the visible off-diagonal pairs are coded by the cell variables.
  obtain ⟨G, hG, hGcode⟩ :=
    exists_map_pairCoding_visible_eq hρ (Set.infinite_range_of_injective he) hg hge (d := d)
  refine ⟨jointCoding φ v G, measurable_jointCoding hφ hv hG, ?_⟩
  -- The codings of the pair at an increasing pair `t`, oriented by the order of its vertices and by
  -- the order of its vertex variables respectively, and the array assembled from them.
  set Gt : {t : ℕ × ℕ // t.1 < t.2} → I × (ℕ → I) → I → α × α :=
    fun t q s => G (visibleSquareContext t (Θ q)) s
  set Φt : {t : ℕ × ℕ // t.1 < t.2} → I × (ℕ → I) → I → α × α := fun t q s =>
    (jointCoding φ v G (q.1, q.2 t.1.1, q.2 t.1.2, s),
      jointCoding φ v G (q.1, q.2 t.1.2, q.2 t.1.1, s))
  have hGt (t) : Measurable (Function.uncurry (Gt t)) := hG.comp
    (((measurable_visibleSquareContext t).comp (hΘ.comp measurable_fst)).prodMk measurable_snd)
  have hΦt (t) : Measurable (Function.uncurry (Φt t)) := by
    have hF := measurable_jointCoding hφ hv hG
    have h₁ : Measurable fun r : (I × (ℕ → I)) × I => r.1.1 := measurable_fst.comp measurable_fst
    have hu (k : ℕ) : Measurable fun r : (I × (ℕ → I)) × I => r.1.2 k :=
      (measurable_pi_apply k).comp (measurable_snd.comp measurable_fst)
    exact (hF.comp (h₁.prodMk ((hu _).prodMk ((hu _).prodMk measurable_snd)))).prodMk
      (hF.comp (h₁.prodMk ((hu _).prodMk ((hu _).prodMk measurable_snd))))
  set A : (I × (ℕ → I)) × ({t : ℕ × ℕ // t.1 < t.2} → α × α) → ℕ × ℕ → α :=
    fun r => assembleArray (Θ r.1).2 r.2
  have hA : Measurable A := measurable_assembleArray.comp
    ((measurable_snd.comp (hΘ.comp measurable_fst)).prodMk measurable_snd)
  -- Orienting the pairs by their vertices codes the array read along the visible vertices, which
  -- has the law of the array.
  have hindex : (μ₀.prod (Measure.infinitePi fun _ : {t : ℕ × ℕ // t.1 < t.2} =>
      (volume : Measure I))).map (A ∘ fun r => (r.1, fun t => Gt t r.1 (r.2 t))) = ρ := by
    have hA' : Measurable fun r : (((ℕ × ℕ → α) × (ℕ → (ℕ → α × α) × α)) ×
        (ℕ → (ℕ → α × α) × α)) × ({t : ℕ × ℕ // t.1 < t.2} → α × α) => assembleArray r.1.2 r.2 :=
      measurable_assembleArray.comp ((measurable_snd.comp measurable_fst).prodMk measurable_snd)
    have hΛ := measurable_visiblePairCoding hG
    -- Coding the pairs from the generated vertex data factors through the vertex data.
    have hAΘ : A ∘ (fun r : _ × ({t : ℕ × ℕ // t.1 < t.2} → I) =>
          (r.1, fun t => Gt t r.1 (r.2 t))) =
        ((fun r : _ × ({t : ℕ × ℕ // t.1 < t.2} → α × α) => assembleArray r.1.2 r.2) ∘
          fun q : _ × ({t : ℕ × ℕ // t.1 < t.2} → I) =>
            (q.1, fun t => G (visibleSquareContext t q.1) (q.2 t))) ∘ Prod.map Θ id := by
      funext r
      simp [A, Gt]
    rw [hAΘ,
      ← Measure.map_map (hA'.comp hΛ) (hΘ.prodMap measurable_id),
      ← Measure.map_prod_map _ _ hΘ measurable_id, Measure.map_id, hΘlaw,
      ← Measure.map_map hA' hΛ, hGcode, Measure.map_map hA' (hR.prodMk (measurable_visiblePairs g))]
    exact (congrArg (ρ.map ·) (funext (assembleArray_visiblePairs e d g))).trans
      ((hρ.map_arrayBlock_diag_eq (fun p => (measurable_pi_apply p).aemeasurable)
        hg.injective).trans Measure.map_id')
  -- Orienting each pair by its vertex variables instead does not change the law of its coding.
  have hae (t : {t : ℕ × ℕ // t.1 < t.2}) :
      ∀ᵐ q ∂μ₀, (volume : Measure I).map (Gt t q) = (volume : Measure I).map (Φt t q) := by
    have hlaw : μ₀.map (visibleSquareContext t ∘ Θ) =
        ρ.map (offDiagonalPairSquareContext e (g t.1.1) (g t.1.2)) := by
      rw [← Measure.map_map (measurable_visibleSquareContext t) hΘ, hΘlaw,
        Measure.map_map (measurable_visibleSquareContext t) hR]
      exact congrArg (ρ.map ·) (funext (visibleSquareContext_vertexLayerData e d g t))
    exact ae_map_jointCoding_eq hρ (hg.injective.ne t.2.ne) (hge _) (hge _) hφ hv hG
      (map_pairCoding_visiblePair_eq hG hGcode t) t.2.ne hlaw
  -- The joint coding is the coding oriented by the vertex variables, read off the split noise.
  have hnoise : (fun (u : NoiseIndex Unit (Sym2 ℕ) → I) p => jointArray (jointCoding φ v G) p u) =
      (A ∘ fun r => (r.1, fun t => Φt t r.1 (r.2 t))) ∘ splitJointNoise :=
    funext (jointArray_jointCoding φ v G)
  have hΦ := measurable_fst.prodMk (measurable_pi_uncurry_prod hΦt)
  rw [hnoise, ← Measure.map_map (hA.comp hΦ) measurable_splitJointNoise,
    map_splitJointNoise_noiseMeasure, ← Measure.map_map hA hΦ,
    ← map_prod_infinitePi_eq_of_ae_map_eq (fun _ => (volume : Measure I)) hGt hΦt hae,
    Measure.map_map hA (measurable_fst.prodMk (measurable_pi_uncurry_prod hGt)), hindex]

/-- **Jointly exchangeable arrays are exactly the Aldous--Hoover codings in law.** An array process
with a.e.-measurable entries in a standard Borel space, on a probability space, is jointly
exchangeable if and only if its law is the law of a measurable joint Aldous--Hoover coding
`X i j = F(U, U_i, U_j, U_{i,j})` under independent uniform noise. -/
theorem jointlyExchangeable_iff_exists_map_jointArray_eq
    {Ω : Type*} [MeasurableSpace Ω] {μ : Measure Ω} [IsProbabilityMeasure μ]
    {X : ℕ × ℕ → Ω → α} (hX : ∀ p, AEMeasurable (X p) μ) :
    JointlyExchangeable μ X ↔ ∃ F : I × I × I × I → α, Measurable F ∧
      (noiseMeasure Unit (Sym2 ℕ)).map (fun u p => jointArray F p u) =
        μ.map fun ω p => X p ω := by
  refine ⟨fun h => ((jointlyExchangeable_map_iff hX).2 h).exists_map_jointArray_eq, ?_⟩
  rintro ⟨F, hF, hcode⟩
  rw [← jointlyExchangeable_map_iff hX, ← hcode]
  exact (jointlyExchangeable_map_iff fun p =>
    ((measurable_pi_apply p).comp (measurable_jointArray F hF)).aemeasurable).2
      (jointlyExchangeable_jointArray F hF)

end TauCeti.Probability

end

end
