/-
Copyright (c) 2026 Vincent Quenneville-Belair. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vincent Quenneville-Belair
-/
module

public import Mathlib.Analysis.Convex.Cone.Basic

/-!
# The cone hull of an open set

In a topological additive group with continuous translations and continuous constant
scalar multiplication, the convex cone generated by an open set is open.
-/

public section

open Set

open scoped Pointwise

namespace ConvexCone

variable {𝕜 : Type*} [Semifield 𝕜] [LinearOrder 𝕜]

/-- The cone hull of an open set is open. -/
lemma isOpen_hull {M : Type*} [AddCommGroup M] [TopologicalSpace M] [ContinuousAdd M] [Module 𝕜 M]
    [ContinuousConstSMul 𝕜 M] {s : Set M} (hs : IsOpen s) : IsOpen (hull 𝕜 s : Set M) := by
  let C : ConvexCone 𝕜 M :=
    { carrier := interior (hull 𝕜 s)
      smul_mem' c hc _ hx := interior_mono (smul_set_subset_iff.2 fun _ ↦ (hull 𝕜 s).smul_mem hc)
        ((interior_smul₀ hc.ne' (hull 𝕜 s : Set M)).ge (smul_mem_smul_set hx))
      add_mem' _ hx _ hy := interior_mono (add_subset_iff.2 fun _ h _ ↦ add_mem h)
        (subset_interior_add (add_mem_add hx hy)) }
  exact subset_interior_iff_isOpen.1 <| hull_min (C := C) <| hs.subset_interior_iff.2 subset_hull


end ConvexCone
