/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.Complex.Fuchsian.ProperAction
public import TauCeti.Analysis.Complex.UpperHalfPlane.Stabilizer
import TauCeti.Topology.Algebra.ConstMulAction

/-!
# Point stabilizers of Fuchsian groups

A discrete subgroup `Γ ≤ PSL(2, ℝ)` acts properly discontinuously on the upper half-plane, so its
point stabilizers are finite, and a finite point stabilizer of a subgroup of `PSL(2, ℝ)` is
cyclic (`Subgroup.isCyclic_stabilizer`). Hence the point stabilizers of a Fuchsian
group are finite cyclic: these are its elliptic stabilizers, generated by a transformation whose
derivative at the fixed point is a primitive root of unity of the stabilizer's order
(`Subgroup.exists_isPrimitiveRoot_stabilizerDeriv`).

## Main declarations

* `Subgroup.instIsCyclicStabilizer`: the point stabilizers of a discrete subgroup
  of `PSL(2, ℝ)` are cyclic.
* `Subgroup.exists_generator_stabilizer_of_discrete`: a point stabilizer has a generator whose
  order and derivative order equal the stabilizer order, with elliptic nontrivial representatives.

## References

* Alan Beardon, *The Geometry of Discrete Groups*, Graduate Texts in Mathematics 91,
  Springer, 1983, Chapter 8.
* Svetlana Katok, *Fuchsian Groups*, Chicago Lectures in Mathematics, University of
  Chicago Press, 1992, §2.4.
-/

public section

open MulAction UpperHalfPlane

open scoped MatrixGroups

namespace Subgroup

/-- **The point stabilizers of a Fuchsian group are cyclic**: for a discrete subgroup
`Γ ≤ PSL(2, ℝ)`, the stabilizer of every point of `ℍ` is cyclic. -/
instance instIsCyclicStabilizer (Γ : Subgroup PSL(2, ℝ)) [DiscreteTopology Γ] (z : ℍ) :
    IsCyclic (stabilizer Γ z) :=
  isCyclic_stabilizer Γ z

/-- Every point stabilizer in a discrete subgroup of `PSL(2, ℝ)` is finite cyclic. It has a
generator `g` whose order is the order of the stabilizer and of the derivative of `g` at the fixed
point, and if `g ≠ 1` then every `SL(2, ℝ)` representative of `g` is elliptic. -/
theorem exists_generator_stabilizer_of_discrete (G : Subgroup PSL(2, ℝ)) [DiscreteTopology G]
    (τ : ℍ) :
    Finite (stabilizer G τ) ∧ ∃ g : stabilizer G τ, (∀ x, x ∈ zpowers g) ∧
      orderOf g = Nat.card (stabilizer G τ) ∧
      orderOf (Matrix.ProjectiveSpecialLinearGroup.smulDeriv (g.1.1 : PSL(2, ℝ)) τ) =
        orderOf g ∧
      ∀ a : SL(2, ℝ), (a : PSL(2, ℝ)) = g.1.1 → g ≠ 1 →
        (Matrix.SpecialLinearGroup.mapGL ℝ a).IsElliptic := by
  obtain ⟨g, hg⟩ := (isCyclic_stabilizer G τ).exists_generator
  refine ⟨inferInstance, g, hg, orderOf_eq_card_of_forall_mem_zpowers hg,
    stabilizerDeriv_apply G τ g ▸ orderOf_stabilizerDeriv G τ g, fun a ha hne ↦ ?_⟩
  apply Matrix.SpecialLinearGroup.isElliptic_of_smul_eq_self_of_ne_one
  · have hfix : (a : PSL(2, ℝ)) • τ = τ := by
      rw [ha]
      exact g.property
    simpa only [UpperHalfPlane.pslMk_smul] using hfix
  · intro haone
    apply hne
    apply Subtype.ext
    apply Subtype.ext
    exact ha.symm.trans haone

end Subgroup
