/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.Matrix.CornerMinor
public import TauCeti.RingTheory.FittingIdeal.Determinant

/-!
# Fitting ideals of a doubly singular square presentation

Let `A` be a square matrix indexed by `Fin (n + 1)` over a commutative ring, annihilated on the
right by a column vector `u` and on the left by a row vector `w` whose last coordinates are units.
Then the last column of `A` is a combination of the others (by `u`) and the last row of `A` is a
combination of the others (by `w`), so `A` carries no more information than its *corner
submatrix* `A.submatrix Fin.castSucc Fin.castSucc`, obtained by deleting the last row and column.

This file makes that precise for minors. The column space of `A` is the image of the column space
of the corner submatrix under a linear map (the identity on the first `n` coordinates, followed by
the linear form read off from `w`), and conversely the column space of the corner submatrix is the
image of that of `A` under forgetting the last coordinate. Minors ideals only shrink under linear
maps, so the two column spaces have the same ideals of `p × p` minors for every `p`. In
particular the ideal of `n × n` minors of `A` is generated by the single corner minor, and the
Fitting ideals of the cokernel of `A` are those of the cokernel of its corner submatrix, shifted
by one.

The intended source of such a matrix is `burau b - 1` for a braid `b`, with `u` the all-ones
vector and `w` the geometric vector `(1, t, …, t ^ n)`; see
`TauCeti/KnotTheory/Burau/FittingIdeal.lean`.

## Main results

* `Matrix.minorsIdeal_range_mulVecLin_eq_submatrix_castSucc`: the minors ideals of the column
  space of `A` are those of its corner submatrix.
* `Matrix.minorsIdeal_range_mulVecLin_eq_span_det_submatrix_castSucc`: the `n × n` minors of `A`
  generate the principal ideal of the corner minor.
* `Matrix.fittingIdeal_coker_succ_eq_submatrix_castSucc`: `Fitt_{k + 1}` of the cokernel of `A` is
  `Fitt_k` of the cokernel of the corner submatrix.
* `Matrix.fittingIdeal_coker_one_eq_span_det_submatrix_castSucc`: `Fitt₁` of the cokernel of `A`
  is generated by the corner minor.

## References

* [Stacks Project, Tag 07Z6](https://stacks.math.columbia.edu/tag/07Z6) (Fitting ideals computed
  from a presentation matrix).
* R. H. Crowell, R. H. Fox, *Introduction to Knot Theory*, Ginn (1963), Chapter VII (deleting a
  redundant row and column of an Alexander matrix).
-/

public section

noncomputable section

open Module Submodule

namespace Matrix

variable {R : Type*} [CommRing R] {n : ℕ}

/-- The `(n + 1) × n` matrix that keeps the first `n` coordinates and appends the linear form
`z ↦ -c * ∑ i, w i * z i`. -/
private def snocRow (c : R) (w : Fin n → R) : Matrix (Fin (n + 1)) (Fin n) R :=
  Matrix.of fun i j =>
    Fin.lastCases (motive := fun _ => R) (-(c * w j)) (fun i => if i = j then 1 else 0) i

/-- A matrix annihilated on the left by `w`, with `w (Fin.last n)` a unit, is recovered from its
first `n` rows. -/
private theorem snocRow_mul_submatrix (A : Matrix (Fin (n + 1)) (Fin (n + 1)) R)
    {w : Fin (n + 1) → R} (hwA : w ᵥ* A = 0) (hw : IsUnit (w (Fin.last n))) :
    snocRow (↑hw.unit⁻¹ : R) (fun i => w i.castSucc) *
        A.submatrix Fin.castSucc Fin.castSucc =
      A.submatrix id Fin.castSucc := by
  ext i j
  induction i using Fin.lastCases with
  | last =>
    have h := congrFun hwA j.castSucc
    simp only [vecMul, dotProduct, Fin.sum_univ_castSucc, Pi.zero_apply] at h
    have hc : (↑hw.unit⁻¹ : R) * w (Fin.last n) = 1 := hw.val_inv_mul
    simp only [snocRow, mul_apply, of_apply, Fin.lastCases_last, submatrix_apply, id_eq, neg_mul,
      Finset.sum_neg_distrib, mul_assoc, ← Finset.mul_sum]
    rw [eq_neg_of_add_eq_zero_left h, mul_neg, neg_neg, ← mul_assoc, hc, one_mul]
  | cast i =>
    simp [snocRow, mul_apply]

/-- **The minors ideals of a doubly singular matrix are those of its corner submatrix.** If a square
matrix `A` is annihilated on the right by `u` and on the left by `w`, both with a unit in their
last coordinate, then for every `p` the ideal of `p × p` minors of the column space of `A` equals
that of the column space of `A.submatrix Fin.castSucc Fin.castSucc`. -/
theorem minorsIdeal_range_mulVecLin_eq_submatrix_castSucc
    (A : Matrix (Fin (n + 1)) (Fin (n + 1)) R) {u w : Fin (n + 1) → R} (hAu : A *ᵥ u = 0)
    (hwA : w ᵥ* A = 0) (hu : IsUnit (u (Fin.last n))) (hw : IsUnit (w (Fin.last n))) (p : ℕ) :
    (LinearMap.range A.mulVecLin).minorsIdeal p =
      (LinearMap.range (A.submatrix Fin.castSucc Fin.castSucc).mulVecLin).minorsIdeal p := by
  refine le_antisymm ?_ ?_
  · -- The column space of `A` is the image of that of the corner under `snocRow`.
    let L := snocRow (↑hw.unit⁻¹ : R) (fun i => w i.castSucc)
    refine (minorsIdeal_mono ?_ p).trans (minorsIdeal_map_le L.mulVecLin _ p)
    rintro _ ⟨x, rfl⟩
    -- Subtract a multiple of `u` from `x` to clear its last coordinate.
    let y := x - (x (Fin.last n) * ↑hu.unit⁻¹) • u
    have hy : y (Fin.last n) = 0 := by
      simp only [y, Pi.sub_apply, Pi.smul_apply, smul_eq_mul, mul_assoc, hu.val_inv_mul,
        mul_one, sub_self]
    refine ⟨(A.submatrix Fin.castSucc Fin.castSucc).mulVecLin (Fin.init y), ⟨_, rfl⟩, ?_⟩
    have hAy : A *ᵥ y = A *ᵥ x := by
      rw [mulVec_sub, mulVec_smul, hAu, smul_zero, sub_zero]
    rw [mulVecLin_apply, mulVecLin_apply, mulVecLin_apply, mulVec_mulVec,
      snocRow_mul_submatrix A hwA hw, ← mulVec_snoc_zero, ← hy, Fin.snoc_init_self, hAy]
  · -- The column space of the corner is the image of that of `A` under dropping the last
    -- coordinate.
    refine (minorsIdeal_mono ?_ p).trans
      (minorsIdeal_map_le (LinearMap.funLeft R R Fin.castSucc) _ p)
    rintro _ ⟨z, rfl⟩
    refine ⟨A *ᵥ Fin.snoc z 0, ⟨_, rfl⟩, ?_⟩
    ext i
    simp [mulVec_snoc_zero, mulVec, dotProduct]

/-- **The codimension-one minors of a doubly singular matrix are generated by its corner minor.**
If a square matrix `A` indexed by `Fin (n + 1)` is annihilated on the right by `u` and on the left
by `w`, both with a unit in their last coordinate, then the ideal of `n × n` minors of its column
space is generated by the determinant of `A.submatrix Fin.castSucc Fin.castSucc`. -/
theorem minorsIdeal_range_mulVecLin_eq_span_det_submatrix_castSucc
    (A : Matrix (Fin (n + 1)) (Fin (n + 1)) R) {u w : Fin (n + 1) → R} (hAu : A *ᵥ u = 0)
    (hwA : w ᵥ* A = 0) (hu : IsUnit (u (Fin.last n))) (hw : IsUnit (w (Fin.last n))) :
    (LinearMap.range A.mulVecLin).minorsIdeal n =
      Ideal.span {(A.submatrix Fin.castSucc Fin.castSucc).det} := by
  nontriviality R
  have h := (A.submatrix Fin.castSucc Fin.castSucc).mulVecLin.minorsIdeal_range_finrank_eq_span_det
  rw [finrank_fin_fun, ← toLin'_apply', LinearMap.det_toLin'] at h
  rw [A.minorsIdeal_range_mulVecLin_eq_submatrix_castSucc hAu hwA hu hw, ← toLin'_apply', h]

/-- **The Fitting ideals of a doubly singular presentation shift down to its corner.** If a square
matrix `A` indexed by `Fin (n + 1)` is annihilated on the right by `u` and on the left by `w`, both
with a unit in their last coordinate, then `Fitt_{k + 1}` of the cokernel of `A` is `Fitt_k` of the
cokernel of `A.submatrix Fin.castSucc Fin.castSucc`. -/
theorem fittingIdeal_coker_succ_eq_submatrix_castSucc
    (A : Matrix (Fin (n + 1)) (Fin (n + 1)) R) {u w : Fin (n + 1) → R} (hAu : A *ᵥ u = 0)
    (hwA : w ᵥ* A = 0) (hu : IsUnit (u (Fin.last n))) (hw : IsUnit (w (Fin.last n))) (k : ℕ) :
    TauCeti.fittingIdeal R ((Fin (n + 1) → R) ⧸ LinearMap.range A.mulVecLin) (k + 1) =
      TauCeti.fittingIdeal R
        ((Fin n → R) ⧸ LinearMap.range (A.submatrix Fin.castSucc Fin.castSucc).mulVecLin) k := by
  nontriviality R
  rw [TauCeti.fittingIdeal_eq_minorsIdeal_ker (mkQ_surjective _),
    TauCeti.fittingIdeal_eq_minorsIdeal_ker (mkQ_surjective _), ker_mkQ, ker_mkQ,
    finrank_fin_fun, finrank_fin_fun, Nat.add_sub_add_right,
    A.minorsIdeal_range_mulVecLin_eq_submatrix_castSucc hAu hwA hu hw]

/-- **The first Fitting ideal of a doubly singular presentation is generated by its corner
minor.** If a square matrix `A` indexed by `Fin (n + 1)` is annihilated on the right by `u` and on
the left by `w`, both with a unit in their last coordinate, then `Fitt₁` of the cokernel of `A` is
generated by the determinant of `A.submatrix Fin.castSucc Fin.castSucc`. -/
theorem fittingIdeal_coker_one_eq_span_det_submatrix_castSucc
    (A : Matrix (Fin (n + 1)) (Fin (n + 1)) R) {u w : Fin (n + 1) → R} (hAu : A *ᵥ u = 0)
    (hwA : w ᵥ* A = 0) (hu : IsUnit (u (Fin.last n))) (hw : IsUnit (w (Fin.last n))) :
    TauCeti.fittingIdeal R ((Fin (n + 1) → R) ⧸ LinearMap.range A.mulVecLin) 1 =
      Ideal.span {(A.submatrix Fin.castSucc Fin.castSucc).det} := by
  rw [A.fittingIdeal_coker_succ_eq_submatrix_castSucc hAu hwA hu hw 0,
    fittingIdeal_coker_zero_eq_span_det]

end Matrix
