/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Module.Torsion.Basic
public import Mathlib.Algebra.Module.Projective
public import Mathlib.Algebra.MonoidAlgebra.Module
public import Mathlib.NumberTheory.Padics.PadicIntegers
public import Mathlib.NumberTheory.Padics.RingHoms
public import Mathlib.RingTheory.Ideal.Quotient.Operations
import TauCeti.Algebra.Module.Projective.Quotient
import TauCeti.Algebra.MonoidAlgebra.Basic

/-!
# Reduction of `p`-adic group-algebra modules

Reduction of coefficients gives a surjective ring homomorphism
`ℤ_p[G] → 𝔽_p[G]`.  Its kernel is the ideal generated by `p`; hence it identifies the quotient
`ℤ_p[G] / (p)` with `𝔽_p[G]`.  Transporting scalars across this equivalence gives the quotient
`M / pM` of any `ℤ_p[G]`-module its canonical `𝔽_p[G]`-module structure.

This is the coefficient-reduction bridge needed to compare projective integral lattices with
modular representations in Swan's rational detection theorem.  The quotient map is packaged as a
semilinear map, and its scalar action and kernel are recorded explicitly.  Projectivity of the
reduction is the special case of `Module.Projective.quotient_smul_top` for coefficient reduction.

## Main results

* `TauCeti.padicMonoidAlgebraQuotientEquiv`: `ℤ_p[G] / (p) ≃+* 𝔽_p[G]`.
* `TauCeti.padicReductionModule`: the canonical `𝔽_p[G]`-module structure on `M / pM`.
* `TauCeti.padicReductionMk`: the quotient map, semilinear along coefficient reduction.
* `TauCeti.padicReduction_module_finite`: reduction preserves finite generation.
* `TauCeti.padicReduction_module_projective`: reduction preserves projectivity.

## References

* J.-P. Serre, *Linear Representations of Finite Groups*, Part III, §§14–16.
* R. G. Swan, *Induced representations and projective modules*, Ann. of Math. 71 (1960).
-/

public section

namespace TauCeti

open scoped Pointwise

universe u v

section

variable (p : ℕ) [Fact p.Prime] (G : Type u) [Monoid G]

local notation "A" => MonoidAlgebra ℤ_[p] G
local notation "kG" => MonoidAlgebra (ZMod p) G
local notation "I" => Ideal.span {(p : A)}
local notation "π" => MonoidAlgebra.mapRingHom G (PadicInt.toZMod (p := p))

/-- The kernel of coefficientwise reduction `ℤ_p[G] → 𝔽_p[G]` is the ideal generated by `p`. -/
theorem ker_padicMonoidAlgebraReduction : RingHom.ker π = I := by
  apply le_antisymm
  · intro x hx
    rw [RingHom.mem_ker, MonoidAlgebra.mapRingHom_eq_zero_iff, PadicInt.ker_toZMod,
      PadicInt.maximalIdeal_eq_span_p, Submodule.ideal_span_singleton_smul,
      Submodule.mem_smul_pointwise_iff_exists] at hx
    obtain ⟨y, -, rfl⟩ := hx
    rw [Nat.cast_smul_eq_nsmul, nsmul_eq_mul, Nat.cast_comm]
    exact Ideal.mul_mem_left _ _ (Ideal.mem_span_singleton_self _)
  · rw [Ideal.span_le]
    rintro x (rfl : x = (p : A))
    rw [SetLike.mem_coe, RingHom.mem_ker, map_natCast]
    ext g
    simp

/-- Coefficientwise reduction `ℤ_p[G] → 𝔽_p[G]` is surjective. -/
theorem padicMonoidAlgebraReduction_surjective : Function.Surjective π := by
  rw [MonoidAlgebra.coe_mapRingHom]
  exact MonoidAlgebra.map_surjective _ (ZMod.ringHom_surjective _)

/-- **The group algebra modulo `p` is the group algebra over `𝔽_p`.** -/
noncomputable def padicMonoidAlgebraQuotientEquiv : A ⧸ RingHom.ker π ≃+* kG :=
  RingHom.quotientKerEquivOfSurjective (padicMonoidAlgebraReduction_surjective p G)

@[simp]
theorem padicMonoidAlgebraQuotientEquiv_mk (x : A) :
    padicMonoidAlgebraQuotientEquiv p G (Ideal.Quotient.mk (RingHom.ker π) x) = π x :=
  RingHom.quotientKerEquivOfSurjective_apply_mk _ x

/-- The inverse of `padicMonoidAlgebraQuotientEquiv` sends the reduction of `x` to the class of
`x` modulo `p`. -/
@[simp]
theorem padicMonoidAlgebraQuotientEquiv_symm_apply (x : A) :
    (padicMonoidAlgebraQuotientEquiv p G).symm (π x) = Ideal.Quotient.mk (RingHom.ker π) x := by
  rw [RingEquiv.symm_apply_eq, padicMonoidAlgebraQuotientEquiv_mk]

variable (M : Type v) [AddCommGroup M] [Module (MonoidAlgebra ℤ_[p] G) M]

/-- **The canonical `𝔽_p[G]`-module structure on the reduction of a `ℤ_p[G]`-module.**
The action is transported from the natural `ℤ_p[G]/(p)`-action using
`padicMonoidAlgebraQuotientEquiv`. -/
@[instance_reducible]
noncomputable def padicReductionModule : Module kG (M ⧸ I • (⊤ : Submodule A M)) := by
  let Q := M ⧸ I • (⊤ : Submodule A M)
  have htor : Module.IsTorsionBySet A Q (RingHom.ker π) := by
    rw [ker_padicMonoidAlgebraReduction p G]
    exact Module.isTorsionBySet_quotient_ideal_smul M I
  let _ : Module (A ⧸ RingHom.ker π) Q := htor.module
  exact Module.compHom Q (padicMonoidAlgebraQuotientEquiv p G).symm.toRingHom

/-- The canonical reduction module structure, installed locally for the API below. -/
noncomputable local instance reductionModule :
    Module kG (M ⧸ I • (⊤ : Submodule A M)) := padicReductionModule p G M

/-- Scalar multiplication on the reduction is induced by coefficientwise reduction. -/
@[simp]
theorem padicReduction_smul (a : A) (q : M ⧸ I • (⊤ : Submodule A M)) :
    π a • q = a • q := by
  let Q := M ⧸ I • (⊤ : Submodule A M)
  have htor : Module.IsTorsionBySet A Q (RingHom.ker π) := by
    rw [ker_padicMonoidAlgebraReduction p G]
    exact Module.isTorsionBySet_quotient_ideal_smul M I
  let _ : Module (A ⧸ RingHom.ker π) Q := htor.module
  -- The action of `b : 𝔽_p[G]` is, by definition, that of its preimage in `ℤ_p[G] ⧸ ker π`.
  have hsmul (b : kG) (q : Q) : b • q = (padicMonoidAlgebraQuotientEquiv p G).symm b • q :=
    rfl
  rw [hsmul, padicMonoidAlgebraQuotientEquiv_symm_apply]
  exact htor.mk_smul a q

/-- The quotient map to the modular reduction, semilinear along coefficient reduction. -/
noncomputable def padicReductionMk :
    M →ₛₗ[π] M ⧸ I • (⊤ : Submodule A M) where
  toFun := Submodule.Quotient.mk
  map_add' _ _ := rfl
  map_smul' a x := by rw [padicReduction_smul, Submodule.Quotient.mk_smul]

@[simp]
theorem padicReductionMk_apply (x : M) :
    padicReductionMk p G M x = Submodule.Quotient.mk x := by
  rfl

/-- The modular reduction map is surjective. -/
theorem padicReductionMk_surjective : Function.Surjective (padicReductionMk p G M) :=
  Submodule.Quotient.mk_surjective _

/-- The modular reduction map vanishes exactly on `p • M`, the submodule generated by the ideal
`(p)`. -/
theorem padicReductionMk_eq_zero_iff (x : M) :
    padicReductionMk p G M x = 0 ↔ x ∈ I • (⊤ : Submodule A M) := by
  rw [padicReductionMk_apply, Submodule.Quotient.mk_eq_zero]

/-- Reduction of a finite group-algebra module is finite over the reduced group algebra. -/
theorem padicReduction_module_finite [Module.Finite A M] :
    Module.Finite kG (M ⧸ I • (⊤ : Submodule A M)) :=
  Module.Finite.of_surjective (padicReductionMk p G M) (padicReductionMk_surjective p G M)

/-- **Reduction modulo `p` preserves projectivity.** A projective `ℤ_p[G]`-module reduces to a
projective `𝔽_p[G]`-module. -/
theorem padicReduction_module_projective [Module.Projective A M] :
    Module.Projective kG (M ⧸ I • (⊤ : Submodule A M)) :=
  .quotient_smul_top π (padicMonoidAlgebraReduction_surjective p G)
    (ker_padicMonoidAlgebraReduction p G).ge (padicReduction_smul p G M)

end

end TauCeti
