/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.Orientation
public import TauCeti.Topology.Algebra.Group.Profinite.Free.CharacterKernel
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.RelationModule

/-!
# Labute's module of the procyclic normal forms: the kernel of the orientation and its generators

Labute's classification of Demushkin groups runs on the module `E = X ⧸ (X, X)`, where
`X = ker χ ≤ F` is the kernel, on the free pro-`p` group `F = ⟨x₁, …, x_n⟩`, of the orientation
character `χ` of the group `G = F ⧸ (r)` in normal form (Labute, §4 Definition, p. 121). The
module structure is over `Λ = ℤ_p[[Γ]]`, `Γ = F ⧸ X ≅ Im χ`, through conjugation
(`TauCeti.IsProP.completedGroupAlgebraModule`), and Labute's computations are read in the classes
`⟦y_i⟧ ∈ E` of the basis elements lying in `X`, which generate `E` over `Λ` once a second marked
generator, if any, is corrected by a power of the first.

This file establishes that generation for the two normal forms whose orientation has procyclic
image, so that `Λ` is the power-series ring `TauCeti.completedGroupAlgebra.powerSeriesCoordinate`:

* the `q ≠ 2` normal form `x₁^q (x₁, x₂) ⋯ (x_{n-1}, x_n)` with `q = p^f ≠ 2`, whose standard
  orientation `TauCeti.orientationNeTwo` takes `x₂` to `(1 - q)⁻¹` and kills every other generator.
  Read on `F`, this is a character trivial on all generators but `x₂`, and `(1 - q)⁻¹` has infinite
  order, so `X` is the closed normal closure of the `x_i`, `i ≠ 2`
  (`TauCeti.ker_orientationNeTwo_comp_mk`), and `E` is spanned over `Λ` by their classes, by
  `TauCeti.span_topologicalAbelianization_ker_orientationNeTwo_comp_mk_eq_top`.
  Together with the relator class `TauCeti.IsProP.ofMul_mk_demushkinWordNeTwo_ker`,
  `⟦r⟧ = (q - 1 + [x₂]⁻¹) • [x₁]`, this is the expression of the relator image in generators of `E`;
  the image `Γ = 1 + qℤ_p` is `TauCeti.range_orientationNeTwo_eq_unitsPrincipal`;
* the `q = 2`, `n` even normal form `x₁^{2+α} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (x_{n-1}, x_n)` in the
  branch `4 ∣ α`, `2^f ∤ α`, whose standard orientation `TauCeti.orientationTwoEven` takes `x₂` to
  `v = -(1 + α)⁻¹`, `x₄` to `u = (1 - 2^f)⁻¹` and kills every other generator, and has the
  procyclic image `U^[v₂(α)]` generated by `v`. Then `u` is a `2`-adic power `v^l`
  (`TauCeti.exists_padicPow_eq_of_not_dvd`), `X` is the closed normal closure of the `x_i`,
  `i ≠ 2, 4`, together with `x₄ x₂^{-l}` (`TauCeti.ker_orientationTwoEven_comp_mk`), and `E` is
  spanned over `Λ` by their classes, by
  `TauCeti.span_topologicalAbelianization_ker_orientationTwoEven_comp_mk_eq_top`.
  This is the branch of Labute's Theorem 5.

The remaining branch, `Im χ = {±1} × U^(f)` with two independent marked generators, has a
non-procyclic image and is not treated here.

## Main results

* `TauCeti.orientationNeTwo_comp_mk_freeProPGen_of_ne`,
  `TauCeti.orientationNeTwo_comp_mk_freeProPGen_one`,
  `TauCeti.orientationTwoEven_comp_mk_freeProPGen_of_ne`,
  `TauCeti.orientationTwoEven_comp_mk_freeProPGen_one`,
  `TauCeti.orientationTwoEven_comp_mk_freeProPGen_three`: the values of the orientations on the
  generators of the free pro-`p` group.
* `TauCeti.ker_orientationNeTwo_comp_mk`: **the kernel of the standard orientation of the `q ≠ 2`
  normal form on the free pro-`p` group is the closed normal closure of the generators other than
  `x₂`.**
* `TauCeti.span_topologicalAbelianization_ker_orientationNeTwo_comp_mk_eq_top`:
  **Labute's module `E` of the `q ≠ 2` normal form is spanned over `Λ` by the classes of the
  generators other than `x₂`.**
* `TauCeti.ker_orientationTwoEven_comp_mk` and
  `TauCeti.span_topologicalAbelianization_ker_orientationTwoEven_comp_mk_eq_top`:
  **in that branch, the kernel of the orientation on the free pro-`2` group is the closed normal
  closure of the generators other than `x₂`, `x₄` together with `x₄ x₂^{-l}`, and Labute's module
  `E` is spanned over `Λ` by their classes.**

## References

* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), 106–132, §4,
  pp. 121–122, and Theorem 5.
-/

public section

namespace TauCeti

/-! ### The `q ≠ 2` normal form -/

section NeTwo

variable {p : ℕ} [Fact p.Prime] (q n : ℕ) (u : ℤ_[p]ˣ) (hu : u ∈ unitsPrincipal p 1)

/-- Read on the free pro-`p` group, the orientation of the `q ≠ 2` normal form kills every
generator other than `x₂`. -/
theorem orientationNeTwo_comp_mk_freeProPGen_of_ne {i : ℕ} (hi : i ≠ 1) :
    (orientationNeTwo q n u hu).comp (presentedProP.mk p _) (freeProPGen p n i) = 1 := by
  rw [ContinuousMonoidHom.comp_toFun, presentedProP.mk_freeProPGen,
    orientationNeTwo_presentedProPGen_of_ne q n u hu hi]

/-- Read on the free pro-`p` group, the orientation of the `q ≠ 2` normal form takes `x₂` to its
marked value `u`. -/
theorem orientationNeTwo_comp_mk_freeProPGen_one (hn : 1 < n) :
    (orientationNeTwo q n u hu).comp (presentedProP.mk p _) (freeProPGen p n 1) = u := by
  rw [ContinuousMonoidHom.comp_toFun, presentedProP.mk_freeProPGen,
    orientationNeTwo_presentedProPGen_one q n u hu hn]

/-- **The kernel of the standard orientation of the `q ≠ 2` normal form on the free pro-`p`
group.** For `1 < n` and `q = p^f`, with `f ≥ 2` when `p = 2`, the kernel on
`F = freeProP p (Fin n)` of the character with `χ(x₂) = (1 - q)⁻¹` and `χ(x_i) = 1` otherwise is
the closed normal closure of the generators `x_i`, `i ≠ 2`: this is Labute's `X = ker χ`. -/
theorem ker_orientationNeTwo_comp_mk (hn : 1 < n) {f : ℕ} (hq : q = p ^ f) (hf₂ : p = 2 → 2 ≤ f)
    (hu' : (u : ℤ_[p]) * (1 - (q : ℤ_[p])) = 1) :
    ((orientationNeTwo q n u hu).comp (presentedProP.mk p _)).toMonoidHom.ker =
      (Subgroup.normalClosure (freeProPGen p n '' {i | i ≠ 1})).topologicalClosure := by
  subst hq
  push_cast at hu'
  refine freeProP.ker_eq_topologicalClosure_normalClosure_image_freeProPGen _
    ((orientationNeTwo _ n u hu).comp (presentedProP.mk p _)).isClosed_ker
    (fun i hi ↦ orientationNeTwo_comp_mk_freeProPGen_of_ne _ n u hu hi) ?_
  rw [ContinuousMonoidHom.coe_toMonoidHom, MonoidHom.coe_ofClass,
    orientationNeTwo_comp_mk_freeProPGen_one _ n u hu hn]
  exact not_isOfFinOrder_of_val_mul_one_sub_pow_eq_one hf₂ hu'

/-- **Labute's module `E` of the `q ≠ 2` normal form is spanned by the classes of the generators
other than `x₂`.** For `1 < n` and `q = p^f`, with `f ≥ 2` when `p = 2`, let `X` be the kernel on
`F = freeProP p (Fin n)` of the standard orientation, the character with
`χ(x₂) = (1 - q)⁻¹` and `χ(x_i) = 1` otherwise. Then `E = X^{ab}` is spanned over
`Λ = ℤ_p[[F ⧸ X]]`, for the module structure `TauCeti.IsProP.completedGroupAlgebraModule` through
conjugation, by the classes `⟦y_i⟧` of the generators `x_i`, `i ≠ 2`, the basis elements lying in
`X` (Labute, §4, p. 121). -/
theorem span_topologicalAbelianization_ker_orientationNeTwo_comp_mk_eq_top
    (hn : 1 < n) {f : ℕ} (hq : q = p ^ f) (hf₂ : p = 2 → 2 ≤ f)
    (hu' : (u : ℤ_[p]) * (1 - (q : ℤ_[p])) = 1) :
    haveI := ((orientationNeTwo q n u hu).comp (presentedProP.mk p _)).isClosed_ker
    letI := ((isProP_freeProP p (Fin n)).topologicalAbelianization
      ((orientationNeTwo q n u hu).comp (presentedProP.mk p _)).toMonoidHom.ker
        ).completedGroupAlgebraModule (freeProP p (Fin n) ⧸
          ((orientationNeTwo q n u hu).comp (presentedProP.mk p _)).toMonoidHom.ker)
    Submodule.span (completedGroupAlgebra ℤ_[p] (freeProP p (Fin n) ⧸
        ((orientationNeTwo q n u hu).comp (presentedProP.mk p _)).toMonoidHom.ker))
      (Additive.ofMul ''
        ((QuotientGroup.mk :
            ((orientationNeTwo q n u hu).comp (presentedProP.mk p _)).toMonoidHom.ker →
              TopologicalAbelianization
                ((orientationNeTwo q n u hu).comp (presentedProP.mk p _)).toMonoidHom.ker) ''
          (Subtype.val ⁻¹' (freeProPGen p n '' {i | i ≠ 1})))) = ⊤ :=
  (isProP_freeProP p (Fin n)).span_completedGroupAlgebraModule_topologicalAbelianization_eq_top _
    ((finite_range_freeProPGen p n).subset (Set.image_subset_range _ _))
    (ker_orientationNeTwo_comp_mk q n u hu hn hq hf₂ hu').symm

end NeTwo

/-! ### The `q = 2`, `n` even normal form with procyclic image -/

section TwoEven

variable (a f n : ℕ) (v u : ℤ_[2]ˣ)

/-- Read on the free pro-`2` group, the orientation of the `q = 2`, `n` even normal form kills every
generator other than `x₂` and `x₄`. -/
theorem orientationTwoEven_comp_mk_freeProPGen_of_ne {i : ℕ} (hi₁ : i ≠ 1) (hi₃ : i ≠ 3) :
    (orientationTwoEven a f n v u).comp (presentedProP.mk 2 _) (freeProPGen 2 n i) = 1 := by
  rw [ContinuousMonoidHom.comp_toFun, presentedProP.mk_freeProPGen,
    orientationTwoEven_presentedProPGen_of_ne a f n v u hi₁ hi₃]

/-- Read on the free pro-`2` group, the orientation of the `q = 2`, `n` even normal form takes
`x₂` to its marked value `v`. -/
theorem orientationTwoEven_comp_mk_freeProPGen_one (hn : 1 < n) :
    (orientationTwoEven a f n v u).comp (presentedProP.mk 2 _) (freeProPGen 2 n 1) = v := by
  rw [ContinuousMonoidHom.comp_toFun, presentedProP.mk_freeProPGen,
    orientationTwoEven_presentedProPGen_one a f n v u hn]

/-- Read on the free pro-`2` group, the orientation of the `q = 2`, `n` even normal form takes
`x₄` to its marked value `u`. -/
theorem orientationTwoEven_comp_mk_freeProPGen_three (hn : 3 < n) :
    (orientationTwoEven a f n v u).comp (presentedProP.mk 2 _) (freeProPGen 2 n 3) = u := by
  rw [ContinuousMonoidHom.comp_toFun, presentedProP.mk_freeProPGen,
    orientationTwoEven_presentedProPGen_three a f n v u hn]

/-- **The kernel of the orientation of the `q = 2`, `n` even normal form with procyclic image, on
the free pro-`2` group.** For `3 < n`, `4 ∣ α ≠ 0` and `χ(x₄) = χ(x₂)^l`, the kernel on
`F = freeProP 2 (Fin n)` of the character with `χ(x₂) = -(1 + α)⁻¹`, `χ(x₄) = u` and `χ(x_i) = 1`
otherwise is the closed normal closure of the generators `x_i`, `i ≠ 2, 4`, together with
`x₄ x₂^{-l}`: this is Labute's `X = ker χ` in the branch `Im χ = U^[v₂(α)]`. -/
theorem ker_orientationTwoEven_comp_mk (hn : 3 < n) (hv : (v : ℤ_[2]) * (1 + (a : ℤ_[2])) = -1)
    (ha₄ : 4 ∣ (a : ℤ_[2])) (ha : (a : ℤ_[2]) ≠ 0) {l : ℤ_[2]}
    (hl : isProP_units_padicInt_two.padicPow v l = u) :
    ((orientationTwoEven a f n v u).comp (presentedProP.mk 2 _)).toMonoidHom.ker =
      (Subgroup.normalClosure (insert
        (freeProPGen 2 n 3 * ((isProP_freeProP 2 (Fin n)).padicPow (freeProPGen 2 n 1) l)⁻¹)
        (freeProPGen 2 n '' {i | i ≠ 1 ∧ i ≠ 3}))).topologicalClosure := by
  refine freeProP.ker_eq_topologicalClosure_normalClosure_insert_image_freeProPGen _
    ((orientationTwoEven a f n v u).comp (presentedProP.mk 2 _)).isClosed_ker
    (fun i hi₁ hi₃ ↦ orientationTwoEven_comp_mk_freeProPGen_of_ne a f n v u hi₁ hi₃) ?_ ?_
  · rw [ContinuousMonoidHom.coe_toMonoidHom, MonoidHom.coe_ofClass,
      orientationTwoEven_comp_mk_freeProPGen_one a f n v u (by omega)]
    exact not_isOfFinOrder_of_val_mul_one_add_eq_neg_one hv ha₄ ha
  · have h := (isProP_freeProP 2 (Fin n)).map_padicPow isProP_units_padicInt_two
      ((orientationTwoEven a f n v u).comp (presentedProP.mk 2 _) : freeProP 2 (Fin n) →* ℤ_[2]ˣ)
      (map_continuous ((orientationTwoEven a f n v u).comp (presentedProP.mk 2 _)))
      (freeProPGen 2 n 1) l
    rw [MonoidHom.coe_ofClass] at h
    rw [ContinuousMonoidHom.coe_toMonoidHom, MonoidHom.coe_ofClass,
      orientationTwoEven_comp_mk_freeProPGen_three a f n v u hn, h,
      orientationTwoEven_comp_mk_freeProPGen_one a f n v u (by omega), hl]

/-- **Labute's module `E` of the `q = 2`, `n` even normal form with procyclic image is spanned by
the classes of the generators other than `x₂`, `x₄` and of `x₄ x₂^{-l}`.** For `3 < n`, `4 ∣ α ≠ 0`
and `χ(x₄) = χ(x₂)^l`, let `X` be the kernel on `F = freeProP 2 (Fin n)` of the character with
`χ(x₂) = -(1 + α)⁻¹`, `χ(x₄) = u` and `χ(x_i) = 1` otherwise. Then `E = X^{ab}` is spanned over
`Λ = ℤ_2[[F ⧸ X]]`, for the module structure `TauCeti.IsProP.completedGroupAlgebraModule` through
conjugation, by the classes of `x_i`, `i ≠ 2, 4`, and of `x₄ x₂^{-l}` (Labute, §4, p. 121, the
branch `Im χ = U^[v₂(α)]`). -/
theorem span_topologicalAbelianization_ker_orientationTwoEven_comp_mk_eq_top
    (hn : 3 < n) (hv : (v : ℤ_[2]) * (1 + (a : ℤ_[2])) = -1) (ha₄ : 4 ∣ (a : ℤ_[2]))
    (ha : (a : ℤ_[2]) ≠ 0) {l : ℤ_[2]} (hl : isProP_units_padicInt_two.padicPow v l = u) :
    haveI := ((orientationTwoEven a f n v u).comp (presentedProP.mk 2 _)).isClosed_ker
    letI := ((isProP_freeProP 2 (Fin n)).topologicalAbelianization
      ((orientationTwoEven a f n v u).comp (presentedProP.mk 2 _)).toMonoidHom.ker
        ).completedGroupAlgebraModule (freeProP 2 (Fin n) ⧸
          ((orientationTwoEven a f n v u).comp (presentedProP.mk 2 _)).toMonoidHom.ker)
    Submodule.span (completedGroupAlgebra ℤ_[2] (freeProP 2 (Fin n) ⧸
        ((orientationTwoEven a f n v u).comp (presentedProP.mk 2 _)).toMonoidHom.ker))
      (Additive.ofMul ''
        ((QuotientGroup.mk :
            ((orientationTwoEven a f n v u).comp (presentedProP.mk 2 _)).toMonoidHom.ker →
              TopologicalAbelianization
                ((orientationTwoEven a f n v u).comp (presentedProP.mk 2 _)).toMonoidHom.ker) ''
          (Subtype.val ⁻¹' insert
            (freeProPGen 2 n 3 * ((isProP_freeProP 2 (Fin n)).padicPow (freeProPGen 2 n 1) l)⁻¹)
            (freeProPGen 2 n '' {i | i ≠ 1 ∧ i ≠ 3})))) = ⊤ :=
  (isProP_freeProP 2 (Fin n)).span_completedGroupAlgebraModule_topologicalAbelianization_eq_top _
    (((finite_range_freeProPGen 2 n).subset (Set.image_subset_range _ _)).insert _)
    (ker_orientationTwoEven_comp_mk a f n v u hn hv ha₄ ha hl).symm

end TwoEven

end TauCeti
