/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.Profinite.CompletedGroupAlgebra.PowerSeries
public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.Orientation
public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.RelatorClass
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.BinomialSeries

/-!
# Factoring the dyadic normal-form relator when the orientation image is `{±1} × U^(f)`

Let `G` be a pro-`2` group, `χ : G →ₜ* ℤ_2ˣ` a continuous character, `X = ker χ`, and let
`E = X^{ab}` be the topological abelianization of `X`, a module over `Λ = ℤ_2[[G ⧸ X]]` through
the conjugation action `[g] • [x] = [g x g⁻¹]` (`TauCeti.IsProP.completedGroupAlgebraModule`).
For a tuple `x` with `χ (x_i) = 1` off the marked generators `x₂`, `x₄`, the class of the
`q = 2`, `n` even normal-form relator `x₁^{2+a} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (x_{n-1}, x_n)` in
`E` is

```text
(1 + a + [x₂]⁻¹) • [x₁] + (2^f - 1 + [x₄]⁻¹) • [x₃]
```

(`TauCeti.IsProP.ofMul_mk_demushkinWordTwoEven_ker`). In the branch `2^f ∣ a`, `f ≥ 2`, of the
classification the image of the standard orientation is `V^(f) = {±1} × U^(f)`
(`TauCeti.range_orientationTwoEven_eq_unitsPlusMinus_of_dvd`), which is not procyclic
(`TauCeti.not_exists_topologicalClosure_zpowers_eq_unitsPlusMinus`). Labute's Theorem 6 then
factors the relator class through two multipliers rather than one: for any `s` and `y` with
`χ(s) = -1` and `χ(y) = 1 - 2^f`,

```text
⟦r⟧ = (1 + [s]) • z₁ + (2^f - 1 + [y]) • z₃
```

for some `z₁, z₃ ∈ E` (`TauCeti.IsProP.exists_ofMul_mk_demushkinWordTwoEven_ker_eq_add_smul`).

The second coefficient is already of the required form, because `[x₄]⁻¹ = [y]` in `G ⧸ X`. For
the first, `1 + a` lies in `U^(f)`, which `1 - 2^f` topologically generates, so
`1 + a = (1 - 2^f) ^ l` for a `2`-adic exponent `l`. Since `G ⧸ X` embeds in `ℤ_2ˣ` through `χ`,
this gives `[x₂]⁻¹ = [s] [y] ^ l`. The binomial series `(1 + X) ^ l - (1 + a)` vanishes at
`X = -2^f`, so the division criterion makes `[y] ^ l - (1 + a)` a multiple `(2^f - 1 + [y]) φ`
(`TauCeti.completedGroupAlgebra.of_sub_algebraMap_dvd_algebraMap_add_of_padicPow`). Hence
`1 + a + [x₂]⁻¹` lies in the ideal generated by the two multipliers
(`TauCeti.IsProP.one_add_add_of_inv_mem_span_one_add_of_two_pow_sub_one_add_of`), explicitly

```text
1 + a + [x₂]⁻¹ = (1 + [s]) (1 + a) + (2^f - 1 + [y]) [s] φ.
```

After division by the unit `1 + a`, this is Labute's identity
`(1 + α + S (1 + T)^b)(1 + α)⁻¹ + (2^f + T) φ' = 1 + S` on p. 127, whose `φ'` is a multiple of
`S`. The tuple `x` need not generate `G`, and nothing is assumed about the image of `χ`. For the
standard orientation `TauCeti.orientationTwoEven` on the free pro-`2` group, `E` is Labute's
module, and the factorization holds in the branch `2^f ∣ a`
(`TauCeti.exists_ofMul_mk_demushkinWordTwoEven_ker_orientationTwoEven_comp_mk_eq_add_smul`).

**Conventions.** Labute lets `G ⧸ X` act by `[y] · [x] = [y⁻¹ x y]`, the inverse of the
conjugation action used here (`TopologicalAbelianization.mk_inv_smul_mk`). His multipliers
`1 + S` and `2^f + T`, with `S` the class of an element of character `-1` and `1 + T` the class
of an element of character `(1 - 2^f)⁻¹`, therefore read `1 + [s]` and `2^f - 1 + [y]` here.

## Main results

* `TauCeti.IsProP.one_add_add_of_inv_mem_span_one_add_of_two_pow_sub_one_add_of`: for `2 ≤ f`,
  `2^f ∣ a` and `χ(x) (1 + a) = -1`, `χ(s) = -1`, `χ(y) = 1 - 2^f`, the coefficient
  `1 + a + [x]⁻¹` lies in the ideal of `ℤ_2[[G ⧸ ker χ]]` generated by `1 + [s]` and
  `2^f - 1 + [y]`.
* `TauCeti.IsProP.exists_ofMul_mk_demushkinWordTwoEven_ker_eq_add_smul`: for `3 < n`, `2 ≤ f`,
  `2^f ∣ a` and marked values `χ(x₂) (1 + a) = -1`, `χ(x₄) (1 - 2^f) = 1`, the class of the
  `q = 2`, `n` even relator in `X^{ab}` is `(1 + [s]) • z₁ + (2^f - 1 + [y]) • z₃` for every
  `s`, `y` with `χ(s) = -1` and `χ(y) = 1 - 2^f`.
* `TauCeti.exists_ofMul_mk_demushkinWordTwoEven_ker_orientationTwoEven_comp_mk_eq_add_smul`: the
  same factorization in Labute's module of the standard orientation on the free pro-`2` group.

## References

* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), §4.2, p. 127,
  and Theorem 6.
-/

public section

namespace TauCeti

namespace IsProP

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G] [CompactSpace G]
  [TotallyDisconnectedSpace G] (hG : IsProP 2 G) (χ : G →ₜ* ℤ_[2]ˣ)
include hG

/-- **The first coefficient of the dyadic even-rank relator class in the branch `{±1} × U^(f)`.**
For a continuous character `χ` of a pro-`2` group `G` into `ℤ_2ˣ`, `2 ≤ f`, `2^f ∣ a`, and
elements `x`, `s`, `y` with `χ x (1 + a) = -1`, `χ s = -1` and `χ y = 1 - 2^f`, the element
`1 + a + [x]⁻¹` of `ℤ_2[[G ⧸ ker χ]]` lies in the ideal generated by `1 + [s]` and
`2^f - 1 + [y]`. -/
theorem one_add_add_of_inv_mem_span_one_add_of_two_pow_sub_one_add_of (a f : ℕ) (hf : 2 ≤ f)
    (ha : (2 : ℤ_[2]) ^ f ∣ (a : ℤ_[2])) {x s y : G} (hx : (χ x : ℤ_[2]) * (1 + a) = -1)
    (hs : χ s = -1) (hy : (χ y : ℤ_[2]) = 1 - 2 ^ f) :
    haveI := χ.isClosed_ker
    1 + (a : completedGroupAlgebra ℤ_[2] (G ⧸ χ.toMonoidHom.ker)) +
        completedGroupAlgebra.of ℤ_[2] (G ⧸ χ.toMonoidHom.ker) (x : G ⧸ χ.toMonoidHom.ker)⁻¹ ∈
      Ideal.span {(1 + completedGroupAlgebra.of ℤ_[2] (G ⧸ χ.toMonoidHom.ker)
          (s : G ⧸ χ.toMonoidHom.ker)),
        ((2 : completedGroupAlgebra ℤ_[2] (G ⧸ χ.toMonoidHom.ker)) ^ f - 1 +
          completedGroupAlgebra.of ℤ_[2] (G ⧸ χ.toMonoidHom.ker) (y : G ⧸ χ.toMonoidHom.ker))} := by
  have := χ.isClosed_ker
  have : IsMulCommutative (G ⧸ χ.toMonoidHom.ker) :=
    Subgroup.Normal.quotient_commutative_iff_commutator_le.mpr
      (Abelianization.commutator_subset_ker _)
  have hΓ := hG.quotient χ.toMonoidHom.ker
  -- `1 + a = -χ(x)⁻¹` lies in `U^(f)`, which `χ(y) = 1 - 2^f` topologically generates.
  have he : ((-(χ x)⁻¹ : ℤ_[2]ˣ) : ℤ_[2]) = 1 + a := by
    rw [Units.val_neg, Units.inv_eq_of_mul_eq_one_right (by rw [mul_neg, hx, neg_neg]), neg_neg]
  have hy₁ : (χ y : ℤ_[2]) - 1 = -2 ^ f := by
    rw [hy]
    ring
  have hgen : (Subgroup.zpowers (χ y)).topologicalClosure = unitsPrincipal 2 f :=
    topologicalClosure_zpowers_eq_unitsPrincipal (by omega) (fun _ ↦ hf)
      (by rw [mem_unitsPrincipal_iff, hy₁, Nat.cast_ofNat, dvd_neg])
      (by
        rw [mem_unitsPrincipal_iff, hy₁, Nat.cast_ofNat, dvd_neg,
          pow_dvd_pow_iff (by norm_num : (2 : ℤ_[2]) ≠ 0) PadicInt.p_nonunit]
        omega)
  obtain ⟨l, hl⟩ : ∃ l : ℤ_[2], isProP_units_padicInt_two.padicPow (χ y) l = -(χ x)⁻¹ := by
    refine isProP_units_padicInt_two.mem_topologicalClosure_closure_singleton_iff.mp ?_
    rw [← Subgroup.zpowers_eq_closure, hgen, mem_unitsPrincipal_iff, he, Nat.cast_ofNat,
      add_sub_cancel_left]
    exact ha
  -- The relation `χ(s⁻¹ x⁻¹) = χ(y) ^ l` descends to `[x]⁻¹ = [s] [y] ^ l` in `G ⧸ ker χ`.
  have hq : (x : G ⧸ χ.toMonoidHom.ker)⁻¹ =
      (s : G ⧸ χ.toMonoidHom.ker) * hΓ.padicPow (y : G ⧸ χ.toMonoidHom.ker) l := by
    have hsx : χ (s⁻¹ * x⁻¹) = isProP_units_padicInt_two.padicPow (χ y) l := by
      rw [hl, map_mul, map_inv, map_inv, hs, inv_neg, inv_one, neg_one_mul]
    rw [← hG.mk_eq_padicPow_mk_of_apply_eq_padicPow isProP_units_padicInt_two χ hsx,
      QuotientGroup.mk_mul, QuotientGroup.mk_inv, QuotientGroup.mk_inv, mul_inv_cancel_left]
  -- The binomial series `(1 + X) ^ l` takes the value `χ(y) ^ l = 1 + a` at `c = χ(y) - 1`.
  have hc : (2 : ℤ_[2]) ∣ (χ y : ℤ_[2]) - 1 :=
    TauCeti.Huber.PadicInt.isTopologicallyNilpotent_iff_dvd.mp (hG.hasEval_coe_apply_sub_one χ y)
  have hb : PowerSeries.aeval (TauCeti.Huber.PadicInt.isTopologicallyNilpotent_iff_dvd.mpr hc)
      (PowerSeries.binomialSeries ℤ_[2] l) = -(-(1 + a : ℤ_[2])) := by
    have hmap : χ (hG.padicPow y l) = isProP_units_padicInt_two.padicPow (χ y) l :=
      hG.map_padicPow isProP_units_padicInt_two (χ : G →* ℤ_[2]ˣ) χ.continuous y l
    rw [hG.aeval_binomialSeries χ y l, hmap, hl, he, neg_neg]
  -- Division by `X - c`, read in `ℤ_2[[G ⧸ ker χ]]` at `γ = [y]`, gives
  -- `[y] ^ l - (1 + a) = (2^f - 1 + [y]) φ`.
  obtain ⟨φ, hφ⟩ := completedGroupAlgebra.of_sub_algebraMap_dvd_algebraMap_add_of_padicPow hΓ
    (y : G ⧸ χ.toMonoidHom.ker) hc hb
  simp only [map_neg, map_add, map_one, map_natCast, add_sub_cancel, hy, map_sub, map_pow,
    map_ofNat] at hφ
  refine Ideal.mem_span_pair.mpr ⟨1 + a, completedGroupAlgebra.of ℤ_[2] (G ⧸ χ.toMonoidHom.ker)
    (s : G ⧸ χ.toMonoidHom.ker) * φ, ?_⟩
  rw [hq, map_mul]
  linear_combination -(completedGroupAlgebra.of ℤ_[2] (G ⧸ χ.toMonoidHom.ker)
    (s : G ⧸ χ.toMonoidHom.ker)) * hφ

/-- **Labute's factorization of the dyadic even-rank relator class in the branch
`{±1} × U^(f)`** (Labute, p. 127). Let `χ` be a continuous character of a pro-`2` group `G` into
`ℤ_2ˣ` and `x` a tuple with `χ (x i) = 1` for `i ≠ 1`, `i ≠ 3`, `i < 2 * (n / 2)`, whose marked
values satisfy `χ(x₂) (1 + a) = -1` and `χ(x₄) (1 - 2^f) = 1`, where `2 ≤ f` and `2^f ∣ a`. For
`3 < n` and any `s`, `y` with `χ(s) = -1` and `χ(y) = 1 - 2^f`, the class of
`x₁^{2+a} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (x_{n-1}, x_n)` in `X^{ab}`, `X = ker χ`, is
`(1 + [s]) • z₁ + (2^f - 1 + [y]) • z₃` over `ℤ_2[[G ⧸ X]]` for some `z₁`, `z₃`. -/
theorem exists_ofMul_mk_demushkinWordTwoEven_ker_eq_add_smul (a f : ℕ) {n : ℕ} (hn : 3 < n)
    (hf : 2 ≤ f) {x : ℕ → G} (hx : ∀ i, i ≠ 1 → i ≠ 3 → i < 2 * (n / 2) → χ (x i) = 1)
    (h₁ : (χ (x 1) : ℤ_[2]) * (1 + a) = -1) (h₃ : (χ (x 3) : ℤ_[2]) * (1 - 2 ^ f) = 1)
    (ha : (2 : ℤ_[2]) ^ f ∣ (a : ℤ_[2])) {s y : G} (hs : χ s = -1)
    (hy : (χ y : ℤ_[2]) = 1 - 2 ^ f) :
    haveI := χ.isClosed_ker
    letI := (hG.topologicalAbelianization χ.toMonoidHom.ker).completedGroupAlgebraModule
      (G ⧸ χ.toMonoidHom.ker)
    ∃ z₁ z₃ : Additive (TopologicalAbelianization χ.toMonoidHom.ker),
      Additive.ofMul ((⟨_, demushkinWordTwoEven_mem_ker χ.toMonoidHom a f n
          ((congrArg (· ^ (2 + a)) (hx 0 zero_ne_one (by decide) (by omega))).trans (one_pow _))
          ((congrArg (· ^ 2 ^ f) (hx 2 (by decide) (by decide) (by omega))).trans (one_pow _))⟩ :
            χ.toMonoidHom.ker) :
            TopologicalAbelianization χ.toMonoidHom.ker) =
        (1 + completedGroupAlgebra.of ℤ_[2] (G ⧸ χ.toMonoidHom.ker) (s : G ⧸ χ.toMonoidHom.ker)) •
            z₁ +
          ((2 : completedGroupAlgebra ℤ_[2] (G ⧸ χ.toMonoidHom.ker)) ^ f - 1 +
            completedGroupAlgebra.of ℤ_[2] (G ⧸ χ.toMonoidHom.ker) (y : G ⧸ χ.toMonoidHom.ker)) •
            z₃ := by
  have := χ.isClosed_ker
  have : IsMulCommutative (G ⧸ χ.toMonoidHom.ker) :=
    Subgroup.Normal.quotient_commutative_iff_commutator_le.mpr
      (Abelianization.commutator_subset_ker _)
  let _ := (hG.topologicalAbelianization χ.toMonoidHom.ker).completedGroupAlgebraModule
    (G ⧸ χ.toMonoidHom.ker)
  obtain ⟨c, d, hcd⟩ := Ideal.mem_span_pair.mp
    (hG.one_add_add_of_inv_mem_span_one_add_of_two_pow_sub_one_add_of χ a f hf ha h₁ hs hy)
  -- `[x₄]⁻¹ = [y]` in `G ⧸ ker χ`, since both have character value `1 - 2^f`.
  have hq₃ : (x 3 : G ⧸ χ.toMonoidHom.ker)⁻¹ = (y : G ⧸ χ.toMonoidHom.ker) := by
    rw [← QuotientGroup.mk_inv, QuotientGroup.eq, inv_inv, MonoidHom.mem_ker]
    simp only [ContinuousMonoidHom.coe_toMonoidHom, MonoidHom.coe_ofClass, map_mul,
      Units.ext_iff, Units.val_mul, hy, h₃, Units.val_one]
  refine ⟨c • Additive.ofMul ((⟨x 0, MonoidHom.mem_ker.mpr
      (hx 0 zero_ne_one (by decide) (by omega))⟩ : χ.toMonoidHom.ker) :
        TopologicalAbelianization χ.toMonoidHom.ker),
    d • Additive.ofMul ((⟨x 0, MonoidHom.mem_ker.mpr
        (hx 0 zero_ne_one (by decide) (by omega))⟩ : χ.toMonoidHom.ker) :
          TopologicalAbelianization χ.toMonoidHom.ker) +
      Additive.ofMul ((⟨x 2, MonoidHom.mem_ker.mpr (hx 2 (by decide) (by decide) (by omega))⟩ :
        χ.toMonoidHom.ker) : TopologicalAbelianization χ.toMonoidHom.ker), ?_⟩
  rw [hG.ofMul_mk_demushkinWordTwoEven_ker χ a f hn hx, ← hcd, hq₃, add_smul, mul_comm c,
    mul_comm d, mul_smul, mul_smul, smul_add, add_assoc]

end IsProP

/-- **Labute's factorization in his module of the standard orientation, branch
`{±1} × U^(f)`** (Labute, p. 127, and Theorem 6). Let `χ` be the standard orientation
`TauCeti.orientationTwoEven` of the `q = 2`, `n` even normal form, with marked values
`χ(x₂) = v`, `v (1 + a) = -1`, and `χ(x₄) = u`, `u (1 - 2^f) = 1`, pulled back to the free
pro-`2` group `F` on `x₁, …, x_n` along the quotient map, and let `E = X^{ab}`, `X = ker χ ≤ F`,
be Labute's module over `ℤ_2[[F ⧸ X]]`. For `3 < n`, `2 ≤ f` and `2^f ∣ a`, where the image of
`χ` is `{±1} × U^(f)`, the class of the relator `x₁^{2+a} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯` in `E` is
`(1 + [s]) • z₁ + (2^f - 1 + [y]) • z₃` for some `z₁`, `z₃`, for every `s`, `y ∈ F` with
`χ(s) = -1` and `χ(y) = 1 - 2^f`. -/
theorem exists_ofMul_mk_demushkinWordTwoEven_ker_orientationTwoEven_comp_mk_eq_add_smul (a f : ℕ)
    {n : ℕ} (hn : 3 < n) (hf : 2 ≤ f) (v u : ℤ_[2]ˣ) (hv : (v : ℤ_[2]) * (1 + (a : ℤ_[2])) = -1)
    (hu : (u : ℤ_[2]) * (1 - (2 : ℤ_[2]) ^ f) = 1) (ha : (2 : ℤ_[2]) ^ f ∣ (a : ℤ_[2]))
    {s y : freeProP 2 (Fin n)}
    (hs : (orientationTwoEven a f n v u).comp (presentedProP.mk 2 _) s = -1)
    (hy : ((orientationTwoEven a f n v u).comp (presentedProP.mk 2 _) y : ℤ_[2]) = 1 - 2 ^ f) :
    let χ := (orientationTwoEven a f n v u).comp (presentedProP.mk 2 _)
    haveI := χ.isClosed_ker
    letI := ((isProP_freeProP 2 (Fin n)).topologicalAbelianization
      χ.toMonoidHom.ker).completedGroupAlgebraModule (freeProP 2 (Fin n) ⧸ χ.toMonoidHom.ker)
    ∃ z₁ z₃ : Additive (TopologicalAbelianization χ.toMonoidHom.ker),
      Additive.ofMul ((⟨_, demushkinWordTwoEven_mem_ker χ.toMonoidHom a f n
          ((congrArg (· ^ (2 + a)) ((presentedProP.comp_mk_freeProPGen _ _ _ _ 0).trans
            (orientationTwoEven_presentedProPGen_of_ne a f n v u zero_ne_one
              (by decide)))).trans (one_pow _))
          ((congrArg (· ^ 2 ^ f) ((presentedProP.comp_mk_freeProPGen _ _ _ _ 2).trans
            (orientationTwoEven_presentedProPGen_of_ne a f n v u (by decide)
              (by decide)))).trans (one_pow _))⟩ : χ.toMonoidHom.ker) :
            TopologicalAbelianization χ.toMonoidHom.ker) =
        (1 + completedGroupAlgebra.of ℤ_[2] (freeProP 2 (Fin n) ⧸ χ.toMonoidHom.ker)
            (s : freeProP 2 (Fin n) ⧸ χ.toMonoidHom.ker)) • z₁ +
          ((2 : completedGroupAlgebra ℤ_[2] (freeProP 2 (Fin n) ⧸ χ.toMonoidHom.ker)) ^ f - 1 +
            completedGroupAlgebra.of ℤ_[2] (freeProP 2 (Fin n) ⧸ χ.toMonoidHom.ker)
              (y : freeProP 2 (Fin n) ⧸ χ.toMonoidHom.ker)) • z₃ := by
  intro χ
  have hx : ∀ i, i ≠ 1 → i ≠ 3 → i < 2 * (n / 2) → χ (freeProPGen 2 n i) = 1 := fun i hi₁ hi₃ _ ↦
    (presentedProP.comp_mk_freeProPGen _ _ _ _ i).trans
      (orientationTwoEven_presentedProPGen_of_ne a f n v u hi₁ hi₃)
  have h₁ : χ (freeProPGen 2 n 1) = v :=
    (presentedProP.comp_mk_freeProPGen _ _ _ _ 1).trans
      (orientationTwoEven_presentedProPGen_one a f n v u (by omega))
  have h₃ : χ (freeProPGen 2 n 3) = u :=
    (presentedProP.comp_mk_freeProPGen _ _ _ _ 3).trans
      (orientationTwoEven_presentedProPGen_three a f n v u hn)
  exact (isProP_freeProP 2 (Fin n)).exists_ofMul_mk_demushkinWordTwoEven_ker_eq_add_smul χ a f hn
    hf hx (h₁ ▸ hv) (h₃ ▸ hu) ha hs hy

end TauCeti
