/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.CategoryTheory.Exact.Stable.Shift
public import TauCeti.CategoryTheory.Exact.Stable.Cone
public import Mathlib.CategoryTheory.Triangulated.Pretriangulated

/-!
# Standard triangles in the stable category

This file gives the standard Happel triangles in the projective stable quotient of a
Frobenius exact category. A conflation is sent to a triangle in the stable category by the
quotient functor, its connecting map, and the comparison between the chosen suspension object and
the stable suspension. The cone of an arbitrary morphism is identified with the standard triangle
of its cone conflation.

The definitions here are deliberately separate from a `Pretriangulated` instance. In particular,
this file does not assert octahedrality: that is a separate Layer 1 obligation.
-/

public section

open CategoryTheory CategoryTheory.Limits

namespace TauCeti
namespace ExactStructure.IsFrobenius
universe v u
variable {C : Type u} [Category.{v} C] [Preadditive C] [HasZeroObject C] [HasBinaryBiproducts C]
variable {E : ExactStructure C} (hE : E.IsFrobenius)
/-- The stable image of a conflation, with its connecting map transported to the suspension
shift. -/
noncomputable def stableConflationTriangle (S : ShortComplex C) (hS : E.Conflation S) :
    letI := hE.stableHasShift
    CategoryTheory.Pretriangulated.Triangle E.ProjectiveStableCategory := by
  letI := hE.stableHasShift
  let q := E.projectiveStableFunctor
  let e := hE.stableShiftFunctorOneIso
  let bridge : q.obj (hE.suspensionObj S.X₁) = hE.stableSuspension.obj (q.obj S.X₁) :=
    (hE.stableSuspension_obj_projectiveStableFunctor_obj S.X₁).symm
  exact CategoryTheory.Pretriangulated.Triangle.mk (q.map S.f) (q.map S.g)
    (q.map (hE.connectingMap hS) ≫ eqToHom bridge ≫ e.symm.hom.app (q.obj S.X₁))
/-- The distinguished triangles generated by conflations, up to isomorphism. -/
noncomputable def stableDistinguishedTriangles :
    letI := hE.stableHasShift
    Set (CategoryTheory.Pretriangulated.Triangle E.ProjectiveStableCategory) :=
  letI := hE.stableHasShift
  { T | ∃ S : ShortComplex C, ∃ hS : E.Conflation S,
      Nonempty (T ≅ (hE.stableConflationTriangle S hS)) }
/-- A standard conflation triangle is distinguished. -/
theorem stableConflationTriangle_mem (S : ShortComplex C) (hS : E.Conflation S) :
    letI := hE.stableHasShift
    (hE.stableConflationTriangle S hS) ∈ (hE.stableDistinguishedTriangles) := by
  let := hE.stableHasShift
  exact ⟨S, hS, ⟨by rfl⟩⟩
/-- Distinguished triangles are closed under isomorphism in the stable category. -/
theorem stableDistinguishedTriangles_isomorphic
    {T₁ T₂ : (letI : HasShift E.ProjectiveStableCategory ℤ := hE.stableHasShift;
      CategoryTheory.Pretriangulated.Triangle E.ProjectiveStableCategory)}
    (hT₁ : (letI : HasShift E.ProjectiveStableCategory ℤ := hE.stableHasShift;
      T₁ ∈ hE.stableDistinguishedTriangles)) (e : T₁ ≅ T₂) :
    (letI : HasShift E.ProjectiveStableCategory ℤ := hE.stableHasShift;
      T₂ ∈ hE.stableDistinguishedTriangles) := by
  let := hE.stableHasShift
  rcases hT₁ with ⟨S, hS, ⟨iso⟩⟩
  exact ⟨S, hS, ⟨(iso.symm.trans e).symm⟩⟩

variable {X Y : C}

/-- The stable triangle associated to an arbitrary morphism through its cone. -/
noncomputable def stableConeTriangle (f : X ⟶ Y) :
    letI := hE.stableHasShift
    CategoryTheory.Pretriangulated.Triangle E.ProjectiveStableCategory := by
  letI := hE.stableHasShift
  let q := E.projectiveStableFunctor
  let e := hE.stableShiftFunctorOneIso
  let bridge : q.obj (hE.suspensionObj X) =
      hE.stableSuspension.obj (q.obj X) :=
    (hE.stableSuspension_obj_projectiveStableFunctor_obj X).symm
  exact CategoryTheory.Pretriangulated.Triangle.mk (q.map f)
    (q.map (hE.coneInclusion f))
    (q.map (hE.coneConnectingMap f) ≫ eqToHom bridge ≫
      e.symm.hom.app (q.obj X))


/-- The cone triangle is isomorphic to the standard triangle of the cone conflation. -/
noncomputable def stableConeTriangleIsoConflation (f : X ⟶ Y) :
    letI := hE.stableHasShift
    stableConeTriangle (hE := hE) f ≅
      hE.stableConflationTriangle
        (ShortComplex.mk (hE.coneInflation f) (hE.coneDeflation f)
          (hE.coneInflation_comp_coneDeflation f)) (hE.conflation_cone f) := by
  letI := hE.stableHasShift
  let e := hE.stableShiftFunctorOneIso
  let p := hE.suspensionInjective X
  let i := E.projectiveStableIsoBiprod (hE.isProjective_I (hE.suspensionPresentation X)) Y
  let bridge : E.projectiveStableFunctor.obj (hE.suspensionObj X) =
      hE.stableSuspension.obj (E.projectiveStableFunctor.obj X) :=
    (hE.stableSuspension_obj_projectiveStableFunctor_obj X).symm
  change CategoryTheory.Pretriangulated.Triangle.mk
      (E.projectiveStableFunctor.map f) (E.projectiveStableFunctor.map (hE.coneInclusion f))
      (E.projectiveStableFunctor.map (hE.coneConnectingMap f) ≫ eqToHom bridge ≫
        e.symm.hom.app (E.projectiveStableFunctor.obj X)) ≅
    CategoryTheory.Pretriangulated.Triangle.mk
      (E.projectiveStableFunctor.map (hE.coneInflation f))
      (E.projectiveStableFunctor.map (hE.coneDeflation f))
      (E.projectiveStableFunctor.map (hE.connectingMap (hE.conflation_cone f)) ≫
        eqToHom bridge ≫ e.symm.hom.app (E.projectiveStableFunctor.obj X))
  refine CategoryTheory.Pretriangulated.Triangle.isoMk _ _ (Iso.refl _) i (Iso.refl _) ?_ ?_ ?_
  · simp only [CategoryTheory.Pretriangulated.Triangle.mk_mor₁,
      CategoryTheory.Pretriangulated.Triangle.mk_mor₁, Iso.refl_hom, Category.id_comp]
    rw [hE.projectiveStableFunctor_map_coneInflation]
  · simp only [CategoryTheory.Pretriangulated.Triangle.mk_mor₂,
      CategoryTheory.Pretriangulated.Triangle.mk_obj₃, Iso.refl_hom, Category.comp_id]
    dsimp [i]
    simp only [E.projectiveStableIsoBiprod_hom]
    change E.projectiveStableFunctor.map (hE.coneInclusion f) =
      E.projectiveStableFunctor.map (biprod.inr (X := p) (Y := Y)) ≫
        E.projectiveStableFunctor.map (hE.coneDeflation f)
    rw [← Functor.map_comp]
    change E.projectiveStableFunctor.map (hE.coneInclusion f) =
      E.projectiveStableFunctor.map
        ((biprod.inr (X := p) (Y := Y) : Y ⟶ p ⊞ Y) ≫
          biprod.desc (hE.coneInjectiveMap f) (hE.coneInclusion f))
    rw [biprod.inr_desc]
  · simp only [CategoryTheory.Pretriangulated.Triangle.mk_mor₃,
      CategoryTheory.Pretriangulated.Triangle.mk_mor₃, Category.assoc, Iso.refl_hom]
    rw [hE.projectiveStableFunctor_map_connectingMap_cone]
    simp


/-- The cone triangle is distinguished. -/
theorem stableConeTriangle_mem (f : X ⟶ Y) :
    (letI : HasShift E.ProjectiveStableCategory ℤ := hE.stableHasShift;
      (hE.stableConeTriangle f) ∈ hE.stableDistinguishedTriangles) := by
  let := hE.stableHasShift
  exact ⟨_, hE.conflation_cone f, ⟨hE.stableConeTriangleIsoConflation f⟩⟩

end ExactStructure.IsFrobenius
end TauCeti
