/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.Calculus.Morse.Index
public import TauCeti.Analysis.Calculus.Morse.Linearization
public import TauCeti.Analysis.InnerProductSpace.Spectrum

/-!
# Spectral splitting at a Morse critical point

At a nondegenerate critical point on a finite-dimensional real Hilbert space, the Hessian is an
invertible self-adjoint operator. Its positive and negative spectral subspaces therefore give a
direct-sum decomposition of the tangent space. For the negative-gradient vector field, the
positive Hessian subspace is the stable linear subspace and the negative Hessian subspace is the
unstable linear subspace.

This file constructs those two subspaces, shows that both are invariant under the
negative-gradient linearization, and identifies the dimension of the unstable subspace with the
Morse index; the stable dimension and the Morse index therefore add up to the dimension of the
ambient space.

These are the linear data used by the local stable-manifold theorem. No local invariant manifold
is asserted here: that theorem additionally has to control the nonlinear remainder of the
negative-gradient field, supplied by
`TauCeti.IsNondegenerateCriticalPoint.neg_gradient_sub_linearization_isLittleO`.

## Main declarations

* `ContDiffAt.stableLinearSubspace`: the positive spectral subspace of the Hessian.
* `ContDiffAt.unstableLinearSubspace`: the negative spectral subspace of the Hessian.
* `ContDiffAt.map_neg_hessianOperator_stableLinearSubspace_le` and
  `ContDiffAt.map_neg_hessianOperator_unstableLinearSubspace_le`: both subspaces are invariant
  under the negative-gradient linearization `-hessianOperator f x`.
* `ContDiffAt.isCompl_unstableLinearSubspace_stableLinearSubspace`: when the Hessian is injective
  these subspaces are complementary, so the tangent space is their direct sum.
* `ContDiffAt.finrank_unstableLinearSubspace`: the unstable dimension is the Morse index.
* `ContDiffAt.finrank_stableLinearSubspace_add_morseIndex`: the stable dimension plus the Morse
  index is the ambient dimension.
* `TauCeti.IsNondegenerateCriticalPoint.isCompl_unstableLinearSubspace_stableLinearSubspace` and
  `TauCeti.IsNondegenerateCriticalPoint.finrank_stableLinearSubspace_add_morseIndex`: the same two
  results stated for a nondegenerate critical point, which supplies the Hessian injectivity.

## References

* M. Audin and M. Damian, *Morse Theory and Floer Homology*, Springer Universitext, 2014,
  Chapter 2.
* J. Milnor, *Morse Theory*, Princeton University Press, 1963, §2.
-/

public section

open InnerProductSpace Set

noncomputable section

namespace ContDiffAt

open TauCeti

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [FiniteDimensional ℝ E]
  {f : E → ℝ} {x : E}

/-- The stable linear subspace of the negative-gradient field at a `C²` point: the span of the
Hessian eigenvectors with positive eigenvalues. The linear flow generated by
`-hessianOperator f x` contracts these directions. -/
noncomputable def stableLinearSubspace (hf : ContDiffAt ℝ 2 f x) : Submodule ℝ E :=
  hf.isSelfAdjoint_hessianOperator.isSymmetric.positiveSpectralSubspace rfl

/-- The unstable linear subspace of the negative-gradient field at a `C²` point: the span of the
Hessian eigenvectors with negative eigenvalues. The linear flow generated by
`-hessianOperator f x` expands these directions in forward time. -/
noncomputable def unstableLinearSubspace (hf : ContDiffAt ℝ 2 f x) : Submodule ℝ E :=
  hf.isSelfAdjoint_hessianOperator.isSymmetric.negativeSpectralSubspace rfl

/-- A vector is stable exactly when its Hessian eigenbasis representation is supported on the
positive eigenvalues. -/
@[simp]
theorem mem_stableLinearSubspace_iff (hf : ContDiffAt ℝ 2 f x) {v : E} :
    v ∈ hf.stableLinearSubspace ↔
      ∀ i ∈ ((hf.isSelfAdjoint_hessianOperator.isSymmetric.eigenvectorBasis
        rfl).toBasis.repr v).support,
        0 < hf.isSelfAdjoint_hessianOperator.isSymmetric.eigenvalues rfl i := by
  rw [stableLinearSubspace,
    LinearMap.IsSymmetric.mem_positiveSpectralSubspace_iff]

/-- A vector is unstable exactly when its Hessian eigenbasis representation is supported on the
negative eigenvalues. -/
@[simp]
theorem mem_unstableLinearSubspace_iff (hf : ContDiffAt ℝ 2 f x) {v : E} :
    v ∈ hf.unstableLinearSubspace ↔
      ∀ i ∈ ((hf.isSelfAdjoint_hessianOperator.isSymmetric.eigenvectorBasis
        rfl).toBasis.repr v).support,
        hf.isSelfAdjoint_hessianOperator.isSymmetric.eigenvalues rfl i < 0 := by
  rw [unstableLinearSubspace,
    LinearMap.IsSymmetric.mem_negativeSpectralSubspace_iff]

/-- The Hessian preserves the stable linear subspace. -/
theorem map_hessianOperator_stableLinearSubspace_le (hf : ContDiffAt ℝ 2 f x) :
    Submodule.map (hessianOperator f x).toLinearMap hf.stableLinearSubspace ≤
      hf.stableLinearSubspace := by
  rw [stableLinearSubspace]
  exact hf.isSelfAdjoint_hessianOperator.isSymmetric.map_positiveSpectralSubspace_le rfl

/-- The Hessian preserves the unstable linear subspace. -/
theorem map_hessianOperator_unstableLinearSubspace_le (hf : ContDiffAt ℝ 2 f x) :
    Submodule.map (hessianOperator f x).toLinearMap hf.unstableLinearSubspace ≤
      hf.unstableLinearSubspace := by
  rw [unstableLinearSubspace]
  exact hf.isSelfAdjoint_hessianOperator.isSymmetric.map_negativeSpectralSubspace_le rfl

/-- The negative-gradient linearization preserves the stable linear subspace. It is
`-hessianOperator f x`, the derivative of `-∇ f` at `x` by
`ContDiffAt.hasFDerivAt_neg_gradient`. -/
theorem map_neg_hessianOperator_stableLinearSubspace_le (hf : ContDiffAt ℝ 2 f x) :
    Submodule.map (-hessianOperator f x).toLinearMap hf.stableLinearSubspace ≤
      hf.stableLinearSubspace := by
  rw [ContinuousLinearMap.toLinearMap_neg, Submodule.map_neg]
  exact hf.map_hessianOperator_stableLinearSubspace_le

/-- The negative-gradient linearization preserves the unstable linear subspace. It is
`-hessianOperator f x`, the derivative of `-∇ f` at `x` by
`ContDiffAt.hasFDerivAt_neg_gradient`. -/
theorem map_neg_hessianOperator_unstableLinearSubspace_le (hf : ContDiffAt ℝ 2 f x) :
    Submodule.map (-hessianOperator f x).toLinearMap hf.unstableLinearSubspace ≤
      hf.unstableLinearSubspace := by
  rw [ContinuousLinearMap.toLinearMap_neg, Submodule.map_neg]
  exact hf.map_hessianOperator_unstableLinearSubspace_le

/-- The stable and unstable linear subspaces at a `C²` point are disjoint. This does not require
nondegeneracy: the zero eigenspace belongs to neither subspace. -/
theorem disjoint_unstableLinearSubspace_stableLinearSubspace (hf : ContDiffAt ℝ 2 f x) :
    Disjoint hf.unstableLinearSubspace hf.stableLinearSubspace := by
  rw [unstableLinearSubspace, stableLinearSubspace]
  exact hf.isSelfAdjoint_hessianOperator.isSymmetric
    |>.disjoint_negativeSpectralSubspace_positiveSpectralSubspace rfl

/-- In the Hessian eigenbasis, the number of negative eigenvalues, counted with multiplicity, is
the Morse index. -/
theorem morseIndex_eq_ncard_hessianOperator_eigenvalues_neg (hf : ContDiffAt ℝ 2 f x) :
    morseIndex f x =
      {i | hf.isSelfAdjoint_hessianOperator.isSymmetric.eigenvalues rfl i < 0}.ncard := by
  let hT := hf.isSelfAdjoint_hessianOperator.isSymmetric
  let b := hT.eigenvectorBasis rfl
  have horth : (QuadraticMap.associated (hessianQuadraticForm f x)).IsOrthoᵢ b := by
    rw [LinearMap.isOrthoᵢ_def]
    intro i j hij
    rw [associated_hessianQuadraticForm hf, ContinuousLinearMap.toBilinForm_apply,
      ← inner_hessianOperator_left]
    have heigen : hessianOperator f x (b i) =
        (hT.eigenvalues rfl i : ℝ) • b i := by
      exact hT.apply_eigenvectorBasis rfl i
    rw [heigen, real_inner_smul_left, orthonormal_iff_ite.mp b.orthonormal i j]
    simp [hij]
  have hequiv : QuadraticMap.Equivalent (hessianQuadraticForm f x)
      (QuadraticMap.weightedSumSquares ℝ fun i ↦ hessianQuadraticForm f x (b i)) :=
    ⟨QuadraticForm.isometryEquivWeightedSumSquares (hessianQuadraticForm f x) b.toBasis horth⟩
  have hweights : (fun i ↦ hessianQuadraticForm f x (b i)) = hT.eigenvalues rfl := by
    funext i
    rw [hessianQuadraticForm_apply, ← inner_hessianOperator_left]
    have heigen : hessianOperator f x (b i) =
        (hT.eigenvalues rfl i : ℝ) • b i := by
      exact hT.apply_eigenvectorBasis rfl i
    rw [heigen, real_inner_smul_left, orthonormal_iff_ite.mp b.orthonormal i i]
    simp
  rw [hweights] at hequiv
  rw [morseIndex_def]
  simpa only [hT] using
    QuadraticForm.sigNeg_of_equiv_weightedSumSquares hequiv

/-- The dimension of the unstable linear subspace at a `C²` point is its Morse index. -/
@[simp]
theorem finrank_unstableLinearSubspace (hf : ContDiffAt ℝ 2 f x) :
    Module.finrank ℝ hf.unstableLinearSubspace = morseIndex f x := by
  rw [unstableLinearSubspace,
    hf.isSelfAdjoint_hessianOperator.isSymmetric.finrank_negativeSpectralSubspace,
    hf.morseIndex_eq_ncard_hessianOperator_eigenvalues_neg]

/-- When the Hessian is injective, the unstable and stable linear subspaces are complementary,
so the tangent space is their direct sum. Injectivity excludes the zero eigenspace; at a
nondegenerate critical point it comes from
`TauCeti.IsNondegenerateCriticalPoint.isInvertible_hessianOperator`. -/
theorem isCompl_unstableLinearSubspace_stableLinearSubspace (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) :
    IsCompl hf.unstableLinearSubspace hf.stableLinearSubspace := by
  rw [unstableLinearSubspace, stableLinearSubspace]
  exact hf.isSelfAdjoint_hessianOperator.isSymmetric
    |>.isCompl_negativeSpectralSubspace_positiveSpectralSubspace_of_ker_eq_bot rfl hker

/-- When the Hessian is injective, the dimension of the stable linear subspace plus the Morse
index is the dimension of the ambient tangent space. -/
theorem finrank_stableLinearSubspace_add_morseIndex (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) :
    Module.finrank ℝ hf.stableLinearSubspace + morseIndex f x = Module.finrank ℝ E := by
  rw [← hf.finrank_unstableLinearSubspace, add_comm]
  exact Submodule.finrank_add_eq_of_isCompl (hf.isCompl_unstableLinearSubspace_stableLinearSubspace
    hker)

end ContDiffAt

namespace TauCeti

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [FiniteDimensional ℝ E]
  {f : E → ℝ} {x : E}

/-- At a nondegenerate critical point the unstable and stable linear subspaces are complementary,
so the tangent space is their direct sum. -/
theorem IsNondegenerateCriticalPoint.isCompl_unstableLinearSubspace_stableLinearSubspace
    (h : IsNondegenerateCriticalPoint f x) :
    IsCompl h.contDiffAt.unstableLinearSubspace h.contDiffAt.stableLinearSubspace :=
  h.contDiffAt.isCompl_unstableLinearSubspace_stableLinearSubspace
    (LinearMap.ker_eq_bot.2 h.isInvertible_hessianOperator.injective)

/-- At a nondegenerate critical point the dimension of the stable linear subspace plus the Morse
index is the dimension of the ambient tangent space. -/
theorem IsNondegenerateCriticalPoint.finrank_stableLinearSubspace_add_morseIndex
    (h : IsNondegenerateCriticalPoint f x) :
    Module.finrank ℝ h.contDiffAt.stableLinearSubspace + morseIndex f x = Module.finrank ℝ E :=
  h.contDiffAt.finrank_stableLinearSubspace_add_morseIndex
    (LinearMap.ker_eq_bot.2 h.isInvertible_hessianOperator.injective)

end TauCeti

end
