/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.ClassicalGroups.WeylModule.Basic
public import TauCeti.RepresentationTheory.QuasiIdempotent
public import TauCeti.RepresentationTheory.Symmetric.Specht.Ideal.Idempotent
-- Private: `Subrepresentation.toSubmodule_bot` is used only inside a proof.
import TauCeti.RepresentationTheory.Subrepresentation

/-!
# Intertwiners from a Young-symmetrizer ideal and the Weyl module

The symmetric group `S_d` and the general linear group `GL n k` act on the tensor power
`(kⁿ)^{⊗d}`, and the two actions commute. Schur-Weyl duality decomposes the tensor power under
the product of the two groups as

`(kⁿ)^{⊗d} ≅ ⊕_μ S^μ ⊗ 𝕊^μ(kⁿ)`,

where `S^μ` is the Specht module and `𝕊^μ(kⁿ)` is the Weyl module. The standard route to that
decomposition splits it into two statements: the isotypic decomposition
`(kⁿ)^{⊗d} ≅ ⊕_μ S^μ ⊗ Hom_{S_d}(S^μ, (kⁿ)^{⊗d})` of a representation of the semisimple algebra
`k[S_d]`, and the identification of each Hom space `Hom_{S_d}(S^μ, (kⁿ)^{⊗d})` with the Weyl
module, `GL n k`-equivariantly. This file proves the latter identification, without assuming the
semisimplicity needed to interpret the Hom space as a multiplicity space, and with the Specht
module in its ideal presentation.

That presentation is the left ideal `k[S_d] c_t` generated by the Young symmetrizer of a
`μ`-tableau `t`; over `ℚ` it is `TauCeti.YoungTableau.spechtIdeal`, which is irreducible. The
Young symmetrizer is quasi-idempotent, `c_t * c_t = κ • c_t` with `κ` a nonzero rational
(`TauCeti.YoungTableau.youngSymmetrizerOver_sq`), so evaluation at `c_t` identifies the
`S_d`-intertwining maps `k[S_d] c_t → (kⁿ)^{⊗d}` with the image of `c_t`
(`Representation.spanSingletonHomEquivRange`), and that image *is* the Weyl module. The general
linear group acts on the space of intertwining maps by composing with `g^{⊗d}`, which commutes
with `S_d` (`TauCeti.tensorPowerIntertwiningRep`), and evaluation at `c_t` intertwines this action
with the action on the Weyl module: `TauCeti.YoungTableau.intertwiningMapEquivWeylModule`.

Two consequences are recorded: the intertwiner space has the dimension of the Weyl module, and it
is nonzero exactly when `μ` has at most `n` rows, by the vanishing criterion for the Weyl module
(`TauCeti.YoungTableau.weylModule_eq_bot_iff`). So the Young-symmetrizer ideal of a shape with
more than `n` rows admits no nonzero intertwining map into `(kⁿ)^{⊗d}`.

## Main definitions

* `TauCeti.YoungTableau.intertwiningMapEquivWeylModule`: **the intertwiner space from `k[S_d] c_t`
  to `(kⁿ)^{⊗d}` is the Weyl module**, as representations of `GL n k`.

## Main results

* `TauCeti.YoungTableau.finrank_intertwiningMap_eq_finrank_weylModule`: the intertwiner space
  has the dimension of the Weyl module.
* `TauCeti.YoungTableau.nontrivial_intertwiningMap_iff`: it is nonzero exactly when `μ` has at
  most `n` rows.

## References

* W. Fulton and J. Harris, *Representation Theory: A First Course* (1991), Lecture 6, where the
  Schur functor is the image of a Young symmetrizer and the decomposition of `V^{⊗d}` under
  `S_d × GL(V)` is proved.
* C. Procesi, *Lie Groups: An Approach through Invariants and Representations* (2007), Chapter 9.
-/

public section

open Module
open scoped TensorProduct

universe u

namespace TauCeti

variable {k : Type u} [CommRing k] {n : ℕ}

/-! ## The intertwiner space from a Young-symmetrizer ideal -/

namespace YoungTableau

variable [Algebra ℚ k] {μ : YoungDiagram}

/-- The representation of `S_d` on the left ideal `k[S_d] c_t` generated by the Young symmetrizer,
by left multiplication. Over `ℚ` this is the Specht module in its ideal presentation. -/
local notation "𝒮" t =>
  Representation.ofModule' (k := k) (G := Equiv.Perm (Fin μ.card))
    (Ideal.span {youngSymmetrizerOver k t} : Ideal (MonoidAlgebra k (Equiv.Perm (Fin μ.card))))

/-- The scalar of the essential idempotence of `c_t`, read in `k`, is a unit. -/
private theorem isUnit_youngSymmetrizerOver_sq_scalar (t : YoungTableau μ) :
    IsUnit (algebraMap ℚ k ((μ.card.factorial : ℚ) / (finrank ℚ (spechtIdeal t) : ℚ))) :=
  (isUnit_iff_ne_zero.mpr (div_ne_zero (Nat.cast_ne_zero.mpr μ.card.factorial_ne_zero)
    (Nat.cast_ne_zero.mpr (finrank_spechtIdeal_pos t).ne'))).map _

/-- The image of the Young symmetrizer acting through `permTensorAction` is the Weyl module. -/
private theorem range_asAlgebraHom_youngSymmetrizerOver (t : YoungTableau μ) :
    LinearMap.range ((permTensorAction k n μ.card).asAlgebraHom (youngSymmetrizerOver k t)) =
      (weylModule k n t).toSubmodule := by
  rw [weylModule_toSubmodule, permTensorActionAlgHom_def]

/-- **The intertwiner space from the Young-symmetrizer ideal is the Weyl module.** Evaluation at
the Young symmetrizer `c_t` identifies the `S_d`-intertwining maps from `k[S_d] c_t` into
`(kⁿ)^{⊗d}`, on which `GL n k` acts by composition with `g^{⊗d}`, with the Weyl module
`c_t · (kⁿ)^{⊗d}` of `t`, as representations of `GL n k`. -/
noncomputable def intertwiningMapEquivWeylModule (t : YoungTableau μ) :
    (tensorPowerIntertwiningRep (n := n) (𝒮 t)).Equiv (weylRep k n t) :=
  Representation.Equiv.mk
    ((Representation.spanSingletonHomEquivRange (permTensorAction k n μ.card)
        (isUnit_youngSymmetrizerOver_sq_scalar t) (youngSymmetrizerOver_sq k t)).trans
      (LinearEquiv.ofEq _ _ (range_asAlgebraHom_youngSymmetrizerOver t)))
    fun g => by
      ext f
      simp only [LinearMap.coe_comp, Function.comp_apply, LinearEquiv.coe_coe,
        LinearEquiv.trans_apply, LinearEquiv.coe_ofEq_apply, weylRep_apply_coe,
        Representation.coe_spanSingletonHomEquivRange_apply, tensorPowerIntertwiningRep_apply_apply]

/-- The identification evaluates an intertwining map at the Young symmetrizer. -/
@[simp]
theorem coe_intertwiningMapEquivWeylModule_apply (t : YoungTableau μ)
    (f : Representation.IntertwiningMap (𝒮 t) (permTensorAction k n μ.card)) :
    (intertwiningMapEquivWeylModule t f : ⨂[k]^μ.card (Fin n → k)) =
      f (spanSingletonGenerator (youngSymmetrizerOver k t)) :=
  Representation.coe_spanSingletonHomEquivRange_apply _ _ _ f

/-- The intertwining map attached to a vector `w` of the Weyl module sends the Young symmetrizer
to `w`. -/
@[simp]
theorem intertwiningMapEquivWeylModule_symm_apply_generator (t : YoungTableau μ)
    (w : (weylModule k n t).toSubmodule) :
    (intertwiningMapEquivWeylModule t).symm w (spanSingletonGenerator (youngSymmetrizerOver k t)) =
      w := by
  have h := congrArg Subtype.val ((intertwiningMapEquivWeylModule (n := n) t).apply_symm_apply w)
  rwa [coe_intertwiningMapEquivWeylModule_apply] at h

/-- **The intertwiner space has the dimension of the Weyl module.** -/
theorem finrank_intertwiningMap_eq_finrank_weylModule (t : YoungTableau μ) :
    finrank k (Representation.IntertwiningMap (𝒮 t) (permTensorAction k n μ.card)) =
      finrank k (weylModule k n t).toSubmodule :=
  (intertwiningMapEquivWeylModule t).toLinearEquiv.finrank_eq

/-- **The Young-symmetrizer ideal maps nontrivially into `(kⁿ)^{⊗d}` exactly when `μ` has at most
`n` rows**: the intertwiner space is nonzero exactly when the Weyl module is. -/
theorem nontrivial_intertwiningMap_iff [Nontrivial k] (t : YoungTableau μ) :
    Nontrivial (Representation.IntertwiningMap (𝒮 t) (permTensorAction k n μ.card)) ↔
      μ.colLen 0 ≤ n := by
  rw [(intertwiningMapEquivWeylModule t).toLinearEquiv.nontrivial_congr,
    Submodule.nontrivial_iff_ne_bot, ← not_lt, ← weylModule_eq_bot_iff (k := k) t,
    ← Subrepresentation.toSubmodule_bot (ρ := tensorPowerRep k n μ.card),
    Subrepresentation.toSubmodule_injective.ne_iff]

end YoungTableau

end TauCeti
