/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.CategoryTheory.Exact.Stable.Functor.Suspension
public import TauCeti.CategoryTheory.Exact.Stable.Shift
public import TauCeti.CategoryTheory.Shift.Intertwining

/-!
# Stable functors commute with the integral shift

An exact functor between Frobenius exact categories that preserves projective-injective objects
descends to the stable categories and carries suspension to suspension. Since suspension generates
the integral shift on each stable category, this comparison extends coherently to all shifts by
`ℤ`. Thus the descended functor has the `Functor.CommShift ℤ` structure required of a
triangulated functor.

## Main definitions

* `TauCeti.StableConflationExact.stableFunctorCommShift`: the coherent compatibility of the
  descended stable functor with all integral shifts.

## References

* Dieter Happel, *Triangulated Categories in the Representation Theory of Finite Dimensional
  Algebras*, Chapter I, Section 2.
-/

public section

universe v₁ v₂ u₁ u₂

namespace TauCeti.StableConflationExact

open CategoryTheory CategoryTheory.Limits

variable {C : Type u₁} {D : Type u₂}
variable [Category.{v₁} C] [Preadditive C] [HasZeroObject C] [HasBinaryBiproducts C]
variable [Category.{v₂} D] [Preadditive D] [HasZeroObject D] [HasBinaryBiproducts D]
variable {E : ExactStructure C} {E' : ExactStructure D}
variable {F : C ⥤ D} [F.Additive]

/-- The stable functor induced by a stable conflation-exact functor commutes coherently with the
integral shifts generated by suspension. -/
@[instance_reducible]
noncomputable def stableFunctorCommShift (hF : StableConflationExact E E' F)
    (hE : E.IsFrobenius) (hE' : E'.IsFrobenius) :
    letI := hE.stableHasShift
    letI := hE'.stableHasShift
    (hF.stableFunctor hE).CommShift ℤ :=
  CategoryTheory.Functor.commShiftOfIntertwining
    (hF.stableFunctor hE) hE.stableSuspension.asEquivalence
    hE'.stableSuspension.asEquivalence (hF.stableSuspensionCompStableFunctorIso hE hE')

end TauCeti.StableConflationExact
