/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Category.ModuleCat.Basic
public import Mathlib.Algebra.Homology.Double
public import Mathlib.LinearAlgebra.TensorProduct.Submodule
public import TauCeti.Algebra.Algebra.Frobenius.Casimir
public import TauCeti.Algebra.CentralSimple.Bimodule
public import TauCeti.RingTheory.PrimitiveIdempotent
public import TauCeti.RepresentationTheory.Quiver.Zigzag.Grading
public import TauCeti.RepresentationTheory.Quiver.Zigzag.Trace

/-!
# The braid complexes of a zigzag algebra

Let `Z` be the zigzag algebra of a finite simple graph with no isolated vertex, with vertex
idempotents `e_i`, arrows `a_d` and volume classes `x_i`. A `Z`-bimodule is a left module over the
enveloping algebra `Z ⊗[k] Zᵐᵒᵖ`, `x ⊗ y` acting by `m ↦ x m y`; `Z` itself is the bimodule
`TauCeti.Bimodule (AlgHom.id k Z)`. For a vertex `i`, the bimodule `P_i ⊗_k e_i Z`, where
`P_i = Z e_i`, is the cyclic left ideal of `Z ⊗[k] Zᵐᵒᵖ` generated by the idempotent `e_i ⊗ e_i`.

Khovanov and Seidel attach to `i` two two-term complexes of `Z`-bimodules:

```text
B_i  = [P_i ⊗_k e_i Z ⟶ Z],         x e_i ⊗ e_i y ↦ x e_i y,
B_i' = [Z ⟶ P_i ⊗_k e_i Z],         1 ↦ e_i ⊗ x_i + x_i ⊗ e_i + ∑_{d.fst = i} a_d ⊗ a_{d.symm}.
```

The first is in cohomological degrees `-1, 0` and its differential is multiplication, of internal
path-length degree `0`. The second is in cohomological degrees `0, 1`; its differential, the
coevaluation, raises internal degree by `2`, so with internal grading it is the map
`Z → (P_i ⊗_k e_i Z){-2}`. Tensoring with these complexes is how Khovanov--Seidel and
Huerfano--Khovanov let the braid group of the graph act on the homotopy category of graded
`Z`-modules; this file constructs the complexes and their gradings, not the braid relations.

The coevaluation is a map of bimodules because its value at `1` is the image of the **Casimir
element** `∑_b b ⊗ b^∨` of the symmetric Frobenius trace under `u ↦ u (e_i ⊗ e_i)`, with `b` running
over the vertex, arrow and volume basis and `b^∨` over its dual basis, and the Casimir element of a
trace commutes with the algebra (`TauCeti.sum_mul_tmul_eq_sum_tmul_mul`).

## Main definitions

* `TauCeti.zigzagBraidBimodule`: the bimodule `P_i ⊗_k e_i Z`.
* `TauCeti.zigzagBraidEvaluation`: the multiplication map `P_i ⊗_k e_i Z → Z`.
* `TauCeti.zigzagCasimir`: the Casimir element `∑_b b ⊗ b^∨` of the trace pairing.
* `TauCeti.zigzagBraidCoevaluation`: the coevaluation `Z → P_i ⊗_k e_i Z`.
* `TauCeti.zigzagBraidComplex`, `TauCeti.zigzagBraidInverseComplex`: the complexes `B_i` and
  `B_i'`, in `ModuleCat (Z ⊗[k] Zᵐᵒᵖ)`.
* `TauCeti.zigzagEnvelopingGrade`: the pieces of the path-length grading of `Z ⊗[k] Zᵐᵒᵖ`.

## Main results

* `TauCeti.tmul_one_mul_zigzagCasimir`: the Casimir element commutes with `Z`.
* `TauCeti.coe_zigzagBraidCoevaluation_of`: the explicit formula for the coevaluation.
* `TauCeti.zigzagBraidEvaluation_mem_zigzagGrade`: the evaluation has internal degree `0`.
* `TauCeti.coe_zigzagBraidCoevaluation_mem_zigzagEnvelopingGrade`: the coevaluation has internal
  degree `2`.

## References

* M. Khovanov and P. Seidel, *Quivers, Floer cohomology, and braid group actions*, J. Amer. Math.
  Soc. 15 (2002) (the complexes `R_i` and `R_i'` of the zigzag algebra `A_m`).
* R. S. Huerfano and M. Khovanov, *A category for the adjoint representation*, J. Algebra 246
  (2001) (zigzag algebras of arbitrary graphs and the same complexes).
-/

public section

namespace TauCeti

open PathAlgebra DoubledQuiver MulOpposite
open scoped TensorProduct

universe u w

variable (k : Type w) [CommRing k] {V : Type u} (G : SimpleGraph V)

/-- The zigzag algebra, in this file. -/
local notation "𝒵" => nonisolatedZigzagQuotient k G

/-- The enveloping algebra of the zigzag algebra, in this file. -/
local notation "𝒵ᵉ" => nonisolatedZigzagQuotient k G ⊗[k] (nonisolatedZigzagQuotient k G)ᵐᵒᵖ

/-! ### The bimodule `P_i ⊗_k e_i Z` and the evaluation -/

section Evaluation

variable [Finite V]

/-- **The bimodule `P_i ⊗_k e_i Z`**, the first term of the braid complex at `i`: the cyclic left
ideal of the enveloping algebra `Z ⊗[k] Zᵐᵒᵖ` generated by the idempotent `e_i ⊗ e_i`. Its elements
are the sums of the `x e_i ⊗ e_i y`. -/
noncomputable def zigzagBraidBimodule (i : V) : Ideal (𝒵ᵉ) :=
  Ideal.span {(zigzagMk k G (vertexIdempotent k (vertex G i)) ⊗ₜ[k]
    op (zigzagMk k G (vertexIdempotent k (vertex G i))) : 𝒵ᵉ)}

variable {k G}

/-- `e_i ⊗ e_i` is an idempotent of the enveloping algebra. -/
theorem isIdempotentElem_tmul_vertexIdempotent (i : V) :
    IsIdempotentElem (zigzagMk k G (vertexIdempotent k (vertex G i)) ⊗ₜ[k]
      op (zigzagMk k G (vertexIdempotent k (vertex G i)))) := by
  rw [IsIdempotentElem, Algebra.TensorProduct.tmul_mul_tmul, ← op_mul,
    zigzagMk_vertexIdempotent_mul_self]

/-- An element lies in `P_i ⊗_k e_i Z` exactly when it is fixed by right multiplication by the
idempotent `e_i ⊗ e_i`. -/
theorem mem_zigzagBraidBimodule_iff {i : V} {u : 𝒵ᵉ} :
    u ∈ zigzagBraidBimodule k G i ↔
      u * (zigzagMk k G (vertexIdempotent k (vertex G i)) ⊗ₜ[k]
        op (zigzagMk k G (vertexIdempotent k (vertex G i)))) = u :=
  mem_span_singleton_iff_mul_eq_self (isIdempotentElem_tmul_vertexIdempotent i)

/-- The pure tensor `x e_i ⊗ e_i y` lies in `P_i ⊗_k e_i Z`. -/
theorem tmul_mem_zigzagBraidBimodule (i : V) (x y : 𝒵) :
    (x * zigzagMk k G (vertexIdempotent k (vertex G i))) ⊗ₜ[k]
      op (zigzagMk k G (vertexIdempotent k (vertex G i)) * y) ∈ zigzagBraidBimodule k G i := by
  rw [op_mul, ← Algebra.TensorProduct.tmul_mul_tmul]
  exact Ideal.mul_mem_left _ _ (Ideal.mem_span_singleton_self _)

variable (k G)

/-- **The evaluation `P_i ⊗_k e_i Z → Z`**, the differential of the braid complex at `i`: the map
of bimodules `x e_i ⊗ e_i y ↦ x e_i y`, the restriction of the action of the enveloping algebra on
`1`. -/
noncomputable def zigzagBraidEvaluation (i : V) :
    zigzagBraidBimodule k G i →ₗ[𝒵ᵉ] Bimodule (AlgHom.id k 𝒵) :=
  LinearMap.toSpanSingleton (𝒵ᵉ) _ (Bimodule.of (AlgHom.id k 𝒵) 1) ∘ₗ
    (zigzagBraidBimodule k G i).subtype

variable {k G}

/-- The evaluation acts on `P_i ⊗_k e_i Z` as the enveloping algebra acts on `1`. -/
theorem zigzagBraidEvaluation_apply {i : V} (u : zigzagBraidBimodule k G i) :
    zigzagBraidEvaluation k G i u = (u : 𝒵ᵉ) • Bimodule.of (AlgHom.id k _) 1 := (rfl)

/-- **The evaluation is multiplication**: `x e_i ⊗ e_i y ↦ x e_i y`. -/
theorem zigzagBraidEvaluation_tmul (i : V) (x y : 𝒵) :
    zigzagBraidEvaluation k G i ⟨_, tmul_mem_zigzagBraidBimodule i x y⟩ =
      Bimodule.of (AlgHom.id k _) (x * zigzagMk k G (vertexIdempotent k (vertex G i)) * y) := by
  rw [zigzagBraidEvaluation_apply, Bimodule.smul_of, AlgHom.id_apply, unop_op, mul_one,
    ← mul_assoc, mul_assoc x, zigzagMk_vertexIdempotent_mul_self]

end Evaluation

/-! ### The Casimir element and the coevaluation -/

section Coevaluation

variable [Fintype V] [DecidableRel G.Adj]

/-- **The Casimir element of the zigzag algebra**, `∑_b b ⊗ b^∨` in `Z ⊗[k] Zᵐᵒᵖ`, with `b` running
over the vertex, arrow and volume basis and `b^∨` over its dual basis for the trace pairing,
indexed by `TauCeti.zigzagDualIndex`. -/
noncomputable def zigzagCasimir : 𝒵ᵉ :=
  ∑ b, zigzagBasisFun k G b ⊗ₜ[k] op (zigzagBasisFun k G (zigzagDualIndex G b))

variable {k G}

/-- **The Casimir element commutes with the zigzag algebra**: `(a ⊗ 1) C = (1 ⊗ a) C`, that is,
`a C = C a` for the bimodule structure of `Z ⊗[k] Zᵐᵒᵖ`. -/
theorem tmul_one_mul_zigzagCasimir (hns : ∀ i : V, ∃ j, G.Adj i j) (a : 𝒵) :
    (a ⊗ₜ[k] (1 : 𝒵ᵐᵒᵖ)) * zigzagCasimir k G = ((1 : 𝒵) ⊗ₜ[k] op a) * zigzagCasimir k G := by
  -- The basis and its dual basis are dual for the trace in the sense of the Casimir lemma.
  have hx (y : 𝒵) : ∑ b, zigzagTrace k G hns
      (y * zigzagBasisFun k G (zigzagDualIndex G b)) • zigzagBasisFun k G b = y := by
    conv_rhs => rw [← (zigzagBasis k G hns).sum_repr y]
    refine Finset.sum_congr rfl fun b _ => ?_
    rw [← zigzagTracePairing_apply, zigzagTracePairing_apply_zigzagBasisFun_zigzagDualIndex,
      zigzagBasis_apply]
  have hy (y : 𝒵) : ∑ b, zigzagTrace k G hns
      (zigzagBasisFun k G b * y) • zigzagBasisFun k G (zigzagDualIndex G b) = y := by
    rw [← Equiv.sum_comp (zigzagDualIndex_involutive G).toPerm]
    simp only [Function.Involutive.coe_toPerm, zigzagDualIndex_zigzagDualIndex]
    simp_rw [zigzagTrace_mul_comm k G hns _ y]
    exact hx y
  have key := sum_mul_tmul_eq_sum_tmul_mul (zigzagTrace k G hns) (zigzagTrace_mul_comm k G hns)
    hx hy a
  have := congrArg (TensorProduct.map LinearMap.id (opLinearEquiv k).toLinearMap) key
  simp only [map_sum, TensorProduct.map_tmul, LinearMap.id_coe, id_eq, LinearEquiv.coe_coe,
    coe_opLinearEquiv] at this
  rw [zigzagCasimir, Finset.mul_sum, Finset.mul_sum]
  simp only [Algebra.TensorProduct.tmul_mul_tmul, one_mul, ← op_mul]
  exact this

/-- The Casimir element cut down at `i` lies in `P_i ⊗_k e_i Z`. -/
theorem zigzagCasimir_mul_mem_zigzagBraidBimodule (i : V) :
    zigzagCasimir k G * (zigzagMk k G (vertexIdempotent k (vertex G i)) ⊗ₜ[k]
      op (zigzagMk k G (vertexIdempotent k (vertex G i)))) ∈ zigzagBraidBimodule k G i :=
  Ideal.mul_mem_left _ _ (Ideal.mem_span_singleton_self _)

variable (k G)

/-- **The coevaluation `Z → P_i ⊗_k e_i Z`**, the differential of the inverse braid complex at `i`:
the map of bimodules sending `1` to the Casimir element cut down at `i`,
`e_i ⊗ x_i + x_i ⊗ e_i + ∑_{d.fst = i} a_d ⊗ a_{d.symm}`. -/
noncomputable def zigzagBraidCoevaluation (hns : ∀ i : V, ∃ j, G.Adj i j) (i : V) :
    Bimodule (AlgHom.id k 𝒵) →ₗ[𝒵ᵉ] zigzagBraidBimodule k G i :=
  Bimodule.lift _ ⟨_, zigzagCasimir_mul_mem_zigzagBraidBimodule i⟩ fun b => Subtype.ext <| by
    simp only [SetLike.val_smul, smul_eq_mul, ← mul_assoc, AlgHom.id_apply,
      tmul_one_mul_zigzagCasimir hns]

variable {k G} [DecidableEq V]

/-- **The Casimir element cut down at a vertex**:
`C (e_i ⊗ e_i) = e_i ⊗ x_i + x_i ⊗ e_i + ∑_{d.fst = i} a_d ⊗ a_{d.symm}`. -/
theorem zigzagCasimir_mul_tmul_vertexIdempotent (i : V) :
    zigzagCasimir k G * (zigzagMk k G (vertexIdempotent k (vertex G i)) ⊗ₜ[k]
      op (zigzagMk k G (vertexIdempotent k (vertex G i)))) =
    zigzagMk k G (vertexIdempotent k (vertex G i)) ⊗ₜ[k] op (zigzagVolume k G i) +
      zigzagVolume k G i ⊗ₜ[k] op (zigzagMk k G (vertexIdempotent k (vertex G i))) +
      ∑ d ∈ Finset.univ.filter (fun d : G.Dart => d.fst = i),
        zigzagMk k G (ofArrow (arrow G d.adj)) ⊗ₜ[k]
          op (zigzagMk k G (ofArrow (arrow G d.symm.adj))) := by
  rw [zigzagCasimir, Finset.sum_mul, Fintype.sum_sum_type, Fintype.sum_sum_type]
  simp only [Algebra.TensorProduct.tmul_mul_tmul, ← op_mul, zigzagBasisFun_inl,
    zigzagBasisFun_inr_inl, zigzagBasisFun_inr_inr, zigzagDualIndex_inl, zigzagDualIndex_inr_inl,
    zigzagDualIndex_inr_inr]
  -- Only the summands based at `i` survive the idempotent on either side.
  have hvert (j : V) : (zigzagMk k G (vertexIdempotent k (vertex G j)) *
      zigzagMk k G (vertexIdempotent k (vertex G i))) ⊗ₜ[k]
        op (zigzagMk k G (vertexIdempotent k (vertex G i)) * zigzagVolume k G j) =
      if j = i then zigzagMk k G (vertexIdempotent k (vertex G i)) ⊗ₜ[k] op (zigzagVolume k G i)
        else 0 := by
    split_ifs with h
    · subst h
      rw [zigzagMk_vertexIdempotent_mul_self, zigzagMk_vertexIdempotent_mul_zigzagVolume]
    · rw [zigzagMk_vertexIdempotent_mul_vertexIdempotent_of_ne k G h, TensorProduct.zero_tmul]
  have hvol (j : V) : (zigzagVolume k G j * zigzagMk k G (vertexIdempotent k (vertex G i))) ⊗ₜ[k]
      op (zigzagMk k G (vertexIdempotent k (vertex G i)) *
        zigzagMk k G (vertexIdempotent k (vertex G j))) =
      if j = i then zigzagVolume k G i ⊗ₜ[k] op (zigzagMk k G (vertexIdempotent k (vertex G i)))
        else 0 := by
    split_ifs with h
    · subst h
      rw [zigzagMk_vertexIdempotent_mul_self, zigzagVolume_mul_zigzagMk_vertexIdempotent]
    · rw [zigzagVolume_mul_zigzagMk_vertexIdempotent_of_ne k G (Ne.symm h),
        TensorProduct.zero_tmul]
  have hdart (d : G.Dart) : (zigzagMk k G (ofArrow (arrow G d.adj)) *
      zigzagMk k G (vertexIdempotent k (vertex G i))) ⊗ₜ[k]
        op (zigzagMk k G (vertexIdempotent k (vertex G i)) *
          zigzagMk k G (ofArrow (arrow G d.symm.adj))) =
      if d.fst = i then zigzagMk k G (ofArrow (arrow G d.adj)) ⊗ₜ[k]
        op (zigzagMk k G (ofArrow (arrow G d.symm.adj))) else 0 := by
    split_ifs with h
    · subst h
      rw [zigzagMk_ofArrow_mul_vertexIdempotent]
      -- `d.symm.snd` is `d.fst` by definition of the reversed dart.
      have hsymm : zigzagMk k G (vertexIdempotent k (vertex G d.fst)) *
          zigzagMk k G (ofArrow (arrow G d.symm.adj)) =
          zigzagMk k G (ofArrow (arrow G d.symm.adj)) :=
        zigzagMk_vertexIdempotent_mul_ofArrow k G d.symm
      rw [hsymm]
    · rw [zigzagMk_ofArrow_mul_vertexIdempotent_of_ne k G d (Ne.symm h), TensorProduct.zero_tmul]
  simp_rw [hvert, hvol, hdart]
  simp only [Finset.sum_ite_eq', Finset.mem_univ, ite_true]
  rw [← Finset.sum_filter]
  abel

/-- **The coevaluation sends `x` to `x` times the Casimir element cut down at `i`**. -/
theorem coe_zigzagBraidCoevaluation_of (hns : ∀ i : V, ∃ j, G.Adj i j) (i : V) (x : 𝒵) :
    (zigzagBraidCoevaluation k G hns i (Bimodule.of _ x) : 𝒵ᵉ) =
      (x * zigzagMk k G (vertexIdempotent k (vertex G i))) ⊗ₜ[k] op (zigzagVolume k G i) +
        (x * zigzagVolume k G i) ⊗ₜ[k] op (zigzagMk k G (vertexIdempotent k (vertex G i))) +
        ∑ d ∈ Finset.univ.filter (fun d : G.Dart => d.fst = i),
          (x * zigzagMk k G (ofArrow (arrow G d.adj))) ⊗ₜ[k]
            op (zigzagMk k G (ofArrow (arrow G d.symm.adj))) := by
  rw [zigzagBraidCoevaluation, Bimodule.lift_of, SetLike.val_smul, smul_eq_mul, ← mul_assoc,
    ← tmul_one_mul_zigzagCasimir hns, mul_assoc, zigzagCasimir_mul_tmul_vertexIdempotent]
  simp only [mul_add, Finset.mul_sum, Algebra.TensorProduct.tmul_mul_tmul, one_mul]

/-- The coevaluation sends `1` to `e_i ⊗ x_i + x_i ⊗ e_i + ∑_{d.fst = i} a_d ⊗ a_{d.symm}`. -/
theorem coe_zigzagBraidCoevaluation_of_one (hns : ∀ i : V, ∃ j, G.Adj i j) (i : V) :
    (zigzagBraidCoevaluation k G hns i (Bimodule.of _ 1) : 𝒵ᵉ) =
      zigzagMk k G (vertexIdempotent k (vertex G i)) ⊗ₜ[k] op (zigzagVolume k G i) +
        zigzagVolume k G i ⊗ₜ[k] op (zigzagMk k G (vertexIdempotent k (vertex G i))) +
        ∑ d ∈ Finset.univ.filter (fun d : G.Dart => d.fst = i),
          zigzagMk k G (ofArrow (arrow G d.adj)) ⊗ₜ[k]
            op (zigzagMk k G (ofArrow (arrow G d.symm.adj))) := by
  simpa only [one_mul] using coe_zigzagBraidCoevaluation_of hns i 1

end Coevaluation

/-! ### The two braid complexes -/

section Complexes

variable [Fintype V] [DecidableRel G.Adj]

-- The `AddCommGroup` structure of `P_i ⊗_k e_i Z` is passed to `ModuleCat.ofHom` explicitly:
-- unification would have to discover it through the semiring of the tensor product algebra, which
-- exceeds the default instance-synthesis budget.

/-- **The braid complex `B_i = [P_i ⊗_k e_i Z ⟶ Z]`** of `Z`-bimodules, in cohomological degrees
`-1` and `0`, with the evaluation as differential. -/
noncomputable abbrev zigzagBraidComplex (i : V) :
    HomologicalComplex (ModuleCat.{max u w} (𝒵ᵉ)) (ComplexShape.up ℤ) :=
  HomologicalComplex.double
    (@ModuleCat.ofHom (𝒵ᵉ) _ (zigzagBraidBimodule k G i) (Bimodule (AlgHom.id k 𝒵))
      (Submodule.addCommGroup _) _ _ _ (zigzagBraidEvaluation k G i))
    (show (ComplexShape.up ℤ).Rel (-1) 0 by simp)

/-- **The inverse braid complex `B_i' = [Z ⟶ P_i ⊗_k e_i Z]`** of `Z`-bimodules, in cohomological
degrees `0` and `1`, with the coevaluation as differential. -/
noncomputable abbrev zigzagBraidInverseComplex (hns : ∀ i : V, ∃ j, G.Adj i j) (i : V) :
    HomologicalComplex (ModuleCat.{max u w} (𝒵ᵉ)) (ComplexShape.up ℤ) :=
  HomologicalComplex.double
    (@ModuleCat.ofHom (𝒵ᵉ) _ (Bimodule (AlgHom.id k 𝒵)) (zigzagBraidBimodule k G i)
      _ _ (Submodule.addCommGroup _) _ (zigzagBraidCoevaluation k G hns i))
    (show (ComplexShape.up ℤ).Rel 0 1 by simp)

end Complexes

/-! ### Internal degrees -/

section Grading

variable [Finite V]

/-- **The degree-`n` piece of the path-length grading of the enveloping algebra** `Z ⊗[k] Zᵐᵒᵖ`:
the span of the `x ⊗ y` with `x` and `y` homogeneous of path-length degrees adding up to `n`. -/
noncomputable def zigzagEnvelopingGrade (n : ℕ) : Submodule k (𝒵ᵉ) :=
  ⨆ pq ∈ Finset.antidiagonal n, Submodule.map₂ (TensorProduct.mk k _ _) (zigzagGrade k G pq.1)
    ((zigzagGrade k G pq.2).map (opLinearEquiv k).toLinearMap)

variable {k G}

/-- A pure tensor of homogeneous elements is homogeneous of the total degree. -/
theorem tmul_mem_zigzagEnvelopingGrade {p q : ℕ} {x y : 𝒵}
    (hx : x ∈ zigzagGrade k G p) (hy : y ∈ zigzagGrade k G q) :
    x ⊗ₜ[k] op y ∈ zigzagEnvelopingGrade k G (p + q) := by
  refine Submodule.mem_iSup_of_mem (p, q) (Submodule.mem_iSup_of_mem (by simp) ?_)
  exact Submodule.apply_mem_map₂ _ hx (Submodule.mem_map_of_mem hy)

/-- **The evaluation has internal degree `0`**: on the degree-`n` piece of `P_i ⊗_k e_i Z` it takes
values in degree `n`. -/
theorem zigzagBraidEvaluation_mem_zigzagGrade {i : V} {n : ℕ} {u : zigzagBraidBimodule k G i}
    (hu : (u : 𝒵ᵉ) ∈ zigzagEnvelopingGrade k G n) :
    (Bimodule.of _).symm (zigzagBraidEvaluation k G i u) ∈ zigzagGrade k G n := by
  -- The evaluation is `u ↦ u • 1`, a `k`-linear map on the whole enveloping algebra.
  let μ := LinearMap.applyₗ (R := k) (1 : 𝒵) ∘ₗ (Bimodule.toEnd (AlgHom.id k 𝒵)).toLinearMap
  have hμ : (Bimodule.of _).symm (zigzagBraidEvaluation k G i u) = μ u := by
    rw [zigzagBraidEvaluation_apply, Bimodule.smul_def, LinearEquiv.symm_apply_apply]
    simp [μ]
  have hle : zigzagEnvelopingGrade k G n ≤ (zigzagGrade k G n).comap μ := by
    refine iSup₂_le fun pq hpq => Submodule.map₂_le.mpr fun x hx y' hy' => ?_
    obtain ⟨y, hy, rfl⟩ := Submodule.mem_map.mp hy'
    rw [Finset.mem_antidiagonal] at hpq
    simp only [Submodule.mem_comap, TensorProduct.mk_apply, LinearMap.coe_comp,
      Function.comp_apply, LinearEquiv.coe_coe, coe_opLinearEquiv, μ, AlgHom.toLinearMap_apply,
      LinearMap.applyₗ_apply_apply, Bimodule.toEnd_tmul_apply, AlgHom.id_apply, unop_op, mul_one]
    exact hpq ▸ mul_mem_zigzagGrade k G hx hy
  rw [hμ]
  exact hle hu

/-- **The coevaluation has internal degree `2`**: it sends the degree-`n` piece of `Z` into the
degree-`n + 2` piece of `P_i ⊗_k e_i Z`. With internal grading it is therefore a degree-`0` map
`Z → (P_i ⊗_k e_i Z){-2}`. -/
theorem coe_zigzagBraidCoevaluation_mem_zigzagEnvelopingGrade [Fintype V] [DecidableRel G.Adj]
    (hns : ∀ i : V, ∃ j, G.Adj i j) (i : V) {n : ℕ} {x : 𝒵}
    (hx : x ∈ zigzagGrade k G n) :
    (zigzagBraidCoevaluation k G hns i (Bimodule.of _ x) : 𝒵ᵉ) ∈
      zigzagEnvelopingGrade k G (n + 2) := by
  classical
  have he : zigzagMk k G (vertexIdempotent k (vertex G i)) ∈ zigzagGrade k G 0 :=
    zigzagMk_mem_zigzagGrade k G (PathAlgebra.vertexIdempotent_mem_grade_zero _)
  have hvol : zigzagVolume k G i ∈ zigzagGrade k G 2 := by
    rw [zigzagGrade_two_eq_span_range_zigzagVolume]
    exact Submodule.subset_span ⟨i, rfl⟩
  have harrow (d : G.Dart) : zigzagMk k G (ofArrow (arrow G d.adj)) ∈ zigzagGrade k G 1 :=
    zigzagMk_mem_zigzagGrade k G (PathAlgebra.ofArrow_mem_grade_one _)
  rw [coe_zigzagBraidCoevaluation_of]
  refine add_mem (add_mem ?_ ?_) (sum_mem fun d _ => ?_)
  · simpa using tmul_mem_zigzagEnvelopingGrade (mul_mem_zigzagGrade k G hx he) hvol
  · simpa using tmul_mem_zigzagEnvelopingGrade (mul_mem_zigzagGrade k G hx hvol) he
  · simpa using tmul_mem_zigzagEnvelopingGrade (mul_mem_zigzagGrade k G hx (harrow d))
      (harrow d.symm)

end Grading

end TauCeti
