/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.PowerBasis
public import Mathlib.Algebra.GCDMonoid.IntegrallyClosed
public import Mathlib.FieldTheory.Minpoly.IsIntegrallyClosed
public import TauCeti.RingTheory.RootsOfUnity.Adjoin

/-!
# The constant coordinate of a power basis

An `R`-algebra `S` with a power basis `1, x, …, x ^ (d - 1)` retracts onto `R`: the coordinate
along `x ^ 0 = 1` is an `R`-linear map `S → R` sending `1` to `1`. So `R · 1` is a direct summand of
`S`, which is what it takes to descend a span over `S` back to a span over `R`
(`TauCeti.mem_of_mem_span_of_mem_closure`). Through `Algebra.adjoin.powerBasis'` this applies to
`ℤ[ζ]` for a root of unity `ζ` in a field of characteristic zero.

## Main statements

* `PowerBasis.exists_linearMap_apply_one`: an algebra with a power basis retracts onto its scalars.
* `TauCeti.exists_subring_retraction_of_primitiveRoot`: the subring generated by an integral
  primitive root of unity contains all roots of the same order and retracts additively onto `ℤ`.
-/

public section

/-- **An algebra with a power basis retracts onto its scalars**: the coordinate along
`pb.gen ^ 0 = 1` is an `R`-linear map `S → R` sending `1` to `1`. -/
theorem PowerBasis.exists_linearMap_apply_one {R S : Type*} [CommRing R] [Ring S] [Nontrivial S]
    [Algebra R S] (pb : PowerBasis R S) : ∃ t : S →ₗ[R] R, t 1 = 1 := by
  refine ⟨pb.basis.coord ⟨0, pb.dim_pos⟩, ?_⟩
  have h : pb.basis ⟨0, pb.dim_pos⟩ = 1 := by rw [pb.basis_eq_pow, pow_zero]
  rw [← h, Module.Basis.coord_apply, Module.Basis.repr_self, Finsupp.single_eq_same]

namespace TauCeti

/-- The subring generated by an integral primitive `n`-th root of unity contains every `n`-th
root of unity and admits an additive retraction onto `ℤ` that sends `1` to `1`. -/
theorem exists_subring_retraction_of_primitiveRoot {S : Type*} [Field S] [CharZero S]
    {n : ℕ} [NeZero n]
    {ζ : S} (hζ : IsPrimitiveRoot ζ n) (hζint : IsIntegral ℤ ζ) :
    ∃ A : Subring S, (∀ x : S, x ^ n = 1 → x ∈ A) ∧ ∃ t : A →+ ℤ, t 1 = 1 := by
  let _ : IsIntegrallyClosed ℤ := GCDMonoid.toIsIntegrallyClosed
  let B : Subalgebra ℤ S := Algebra.adjoin ℤ ({ζ} : Set S)
  let pb : PowerBasis ℤ B := Algebra.adjoin.powerBasis' hζint
  obtain ⟨t, ht⟩ := pb.exists_linearMap_apply_one
  refine ⟨B.toSubring, fun x hx ↦ Subalgebra.mem_toSubring.mpr
    (hζ.mem_algebraAdjoin_of_pow_eq_one hx), t.toAddMonoidHom, ?_⟩
  -- The carrier and additive structure of `B.toSubring` are definitionally those of `B`.
  exact ht

end TauCeti
