/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.ModularForms.HeckeSlash.Degeneracy
public import TauCeti.NumberTheory.ModularForms.Newforms.Basic

/-!
# Hecke stability of the old subspace

The old subspace `S_k(Γ₁(N))ᵒˡᵈ` is stable under the Hecke operator `Tₚ`, for a prime `p`
coprime to the level.

The old subspace is generated by the level-raises `V_d g` of cusp forms `g` of proper divisor
level, so stability is exactly the statement that `Tₚ` carries each such generator back into the
subspace — and that is `heckeTCuspNat_levelRaise`, which says `Tₚ` commutes with `V_d`. The
elimination rule `cuspFormsOld_le` turns that generator-wise statement into the stability of the
whole subspace.

This mirrors the diamond half, `diamondOpCusp_mem_cuspFormsOld`, which is proved the same way
from `CuspForm.diamondOpCusp_levelRaise`. Together they say the old subspace is stable under the
operators that act on `S_k(Γ₁(N))` away from the level.

## Main results

* `TauCeti.heckeTCuspNat_mem_cuspFormsOld`: `Tₚ` maps the old subspace into itself, for `p` prime
  and coprime to `N`.
* `TauCeti.cuspFormsOld_map_heckeTCuspNat_le`: the same in `Submodule.map` form.

## Why the coprimality hypothesis

It is inherited from `heckeTCuspNat_levelRaise`, where it is not decoration: at `p ∣ N` the
diamond term of `Tₚ` vanishes at level `N` but need not vanish at the divisor level `M`, so the
commutation argument that lemma runs no longer applies. That is a statement about the proof, not
a claim that `Tₚ` and `V_d` fail to commute at such `p` — this file says nothing either way about
that case.
-/

public section

open Matrix.SpecialLinearGroup UpperHalfPlane CongruenceSubgroup

open scoped MatrixGroups ModularForm

namespace TauCeti

variable {k : ℤ} {N p : ℕ}

/-- **The old subspace is Hecke-stable** at a prime `p` coprime to the level: `Tₚ` maps
`S_k(Γ₁(N))ᵒˡᵈ` into itself. -/
theorem heckeTCuspNat_mem_cuspFormsOld [NeZero N] (hp : p.Prime)
    (hpN : Nat.Coprime p N) {f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k}
    (hf : f ∈ cuspFormsOld N k) :
    haveI : NeZero p := ⟨hp.ne_zero⟩
    HeckeRing.GL2.heckeTCuspNat k p f ∈ cuspFormsOld N k := by
  have : NeZero p := ⟨hp.ne_zero⟩
  refine cuspFormsOld_le (V := (cuspFormsOld N k).comap (HeckeRing.GL2.heckeTCuspNat k p)) ?_ hf
  intro M d hdvd hM g
  have : NeZero M := NeZero.of_dvd (dvd_of_mul_left_dvd hdvd)
  rw [Submodule.mem_comap,
    HeckeRing.GL2.heckeTCuspNat_levelRaise (k := k) (d := d) (M := M) (p := p) hdvd hp hpN]
  exact levelRaise_mem_cuspFormsOld hdvd hM k _

/-- The old subspace is Hecke-stable, in the `Submodule.map` form. -/
theorem cuspFormsOld_map_heckeTCuspNat_le [NeZero N] (hp : p.Prime)
    (hpN : Nat.Coprime p N) (k : ℤ) :
    haveI : NeZero p := ⟨hp.ne_zero⟩
    (cuspFormsOld N k).map (HeckeRing.GL2.heckeTCuspNat k p) ≤ cuspFormsOld N k := by
  have : NeZero p := ⟨hp.ne_zero⟩
  rw [Submodule.map_le_iff_le_comap]
  exact fun _ hf ↦ heckeTCuspNat_mem_cuspFormsOld hp hpN hf

end TauCeti
