/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Homological.ContCohomology.Cup.ZModFourLift
public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.Equiv
import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.RankParity
import TauCeti.Topology.Algebra.Group.Profinite.ProP.ElementaryAbelian
import TauCeti.Topology.Algebra.Group.Profinite.Free.PadicInt
import TauCeti.Topology.Algebra.Group.Profinite.ProP.Procyclic

/-!
# `ℤ/2` is the unique Demushkin group of rank one

A Demushkin group of rank one is procyclic: it is topologically generated by a single element `a`.
If `a` has infinite order the group is `ℤ_p`, the free pro-`p` group on one generator, whose
`H²(-, 𝔽_p)` vanishes, so it is not Demushkin. Otherwise the group is a finite cyclic `p`-group
`ℤ/pᵏ`. The rank is odd, so `p = 2` by the parity constraint. For `k ≥ 2` the mod-`2` character
of `ℤ/2ᵏ` lifts to `ℤ/4`, so its cup square vanishes
(`ContinuousMonoidHom.cupFp_zmodFourReductionClass_self_eq_zero`); but in a Demushkin group of
rank one `H¹(G, 𝔽_p)` is a line, so nondegeneracy of the cup pairing forces the cup square of every
nonzero class to be nonzero. Hence `k = 1`, and the group is `ℤ/2`, which is Demushkin
(`TauCeti.isDemushkin_multiplicative_zmod_two`).

Along the way, a group topologically isomorphic to `ℤ/n` is shown not to be Demushkin at `p = 2`
whenever `4 ∣ n`; this covers the cyclic groups `ℤ/2ᵏ` with `k ≥ 2`.

## Main results

* `TauCeti.IsDemushkin.cupFp_self_ne_zero_of_demushkinRank_eq_one`: in a Demushkin group of rank
  one, every nonzero class of `H¹(G, 𝔽_p)` has nonzero cup square.
* `TauCeti.not_isDemushkin_of_four_dvd_of_continuousMulEquiv_multiplicative_zmod`: a group
  topologically isomorphic to `ℤ/n` is not Demushkin at `p = 2` when `4 ∣ n`.
* `TauCeti.IsDemushkin.eq_two_of_demushkinRank_eq_one`: a Demushkin group of rank one lives at
  `p = 2`.
* `TauCeti.IsDemushkin.nonempty_continuousMulEquiv_multiplicative_zmod_two_of_demushkinRank_eq_one`:
  **a Demushkin group of rank one is topologically isomorphic to `ℤ/2`.**
* `TauCeti.IsDemushkin.demushkinRank_eq_one_iff`: a Demushkin group has rank one exactly when it
  is topologically isomorphic to `ℤ/2`.

## References

* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), 106–132, p. 106
  and Remark 2.
* J.-P. Serre, *Galois Cohomology*, Springer (1997), Chapter I, §4.5.
* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, 2nd ed., Springer (2008),
  (3.9.10).
-/

public section

namespace TauCeti

universe u

variable {p : ℕ} [Fact p.Prime] {G : Type u} [Group G] [TopologicalSpace G]
  [IsTopologicalGroup G] [CompactSpace G] [TotallyDisconnectedSpace G]

/-- **In a Demushkin group of rank one, every nonzero class of `H¹(G, 𝔽_p)` has nonzero cup
square**: `H¹(G, 𝔽_p)` is a line, so the class pairing nontrivially with a nonzero `a` is a
multiple of `a`. -/
theorem IsDemushkin.cupFp_self_ne_zero_of_demushkinRank_eq_one (hG : IsDemushkin p G)
    (h : demushkinRank hG = 1) {a : cohomFp p G 1} (ha : a ≠ 0) : cupFp p G a a ≠ 0 := by
  have : Module.Finite (ZMod p) (cohomFp p G 1) := hG.finite_cohomFp_one
  obtain ⟨b, hb⟩ := hG.cup_separatingLeft a ha
  obtain ⟨c, rfl⟩ := (finrank_eq_one_iff_of_nonzero' a ha).1 (hG.finrank_cohomFp_one.trans h) b
  intro h0
  apply hb
  rw [map_smul, h0, smul_zero]

/-- A Demushkin group at `p = 2` admitting a continuous character to `ℤ/4` with an odd value does
not have rank one: the reduction modulo `2` of the character is a nonzero class of `H¹(G, 𝔽₂)`
with vanishing cup square. -/
theorem IsDemushkin.demushkinRank_ne_one_of_zmod_four_reduction_ne_zero (hG : IsDemushkin 2 G)
    (φ : G →ₜ* Multiplicative (ZMod 4)) {g : G}
    (hg : ZMod.castHom (by norm_num : (2 : ℕ) ∣ 4) (ZMod 2) (Multiplicative.toAdd (φ g)) ≠ 0) :
    demushkinRank hG ≠ 1 := fun h ↦
  hG.cupFp_self_ne_zero_of_demushkinRank_eq_one h (φ.zmodFourReductionClass_ne_zero hg)
    φ.cupFp_zmodFourReductionClass_self_eq_zero

/-- **A profinite group topologically isomorphic to `ℤ/n` with `4 ∣ n` is not Demushkin at
`p = 2`**: it has rank one, and its mod-`2` character lifts to `ℤ/4`. -/
theorem not_isDemushkin_of_four_dvd_of_continuousMulEquiv_multiplicative_zmod {n : ℕ} [NeZero n]
    (hn : 4 ∣ n) (e : G ≃ₜ* Multiplicative (ZMod n)) : ¬ IsDemushkin 2 G := fun hG ↦ by
  have hn1 : Fact (1 < n) := ⟨by
    obtain ⟨m, rfl⟩ := hn
    have := NeZero.ne (4 * m)
    omega⟩
  -- `G` is topologically generated by the image `b` of `1`.
  set b : G := e.symm (Multiplicative.ofAdd 1) with hb
  have hgen : Subgroup.zpowers b = ⊤ := by
    rw [eq_top_iff]
    intro g _
    rw [Subgroup.mem_zpowers_iff]
    refine ⟨((Multiplicative.toAdd (e g)).val : ℤ), ?_⟩
    rw [hb, ← map_zpow, ← ofAdd_zsmul, zsmul_one, Int.cast_natCast, ZMod.natCast_zmod_val,
      ofAdd_toAdd, e.symm_apply_apply]
  -- Hence `G` has rank one: it is generated by one element and is nontrivial.
  have hrank : demushkinRank hG = 1 := by
    apply le_antisymm
    · rw [demushkinRank_def]
      refine (topologicalGeneratorRankNat_le _ (s := {b}) ?_).trans_eq (Finset.card_singleton b)
      rw [Finset.coe_singleton, ← Subgroup.zpowers_eq_closure, hgen]
      exact top_unique (Subgroup.le_topologicalClosure ⊤)
    · rw [Nat.one_le_iff_ne_zero]
      intro h0
      have hcard := topologicalGeneratorRankNat_eq_topologicalGeneratorRank
        hG.isTopologicallyFinitelyGenerated
      rw [demushkinRank_def hG] at h0
      rw [h0, Nat.cast_zero, eq_comm, topologicalGeneratorRank_eq_zero_iff] at hcard
      exact not_subsingleton (Multiplicative (ZMod n)) (e.symm.toEquiv.subsingleton)
  -- The mod-`4` reduction of `e` is a character to `ℤ/4` with value `1` at `b`.
  let ψ : Multiplicative (ZMod n) →ₜ* Multiplicative (ZMod 4) :=
    { toMonoidHom := AddMonoidHom.toMultiplicative (ZMod.castHom hn (ZMod 4)).toAddMonoidHom
      continuous_toFun := continuous_of_discreteTopology }
  let φ : G →ₜ* Multiplicative (ZMod 4) := ψ.comp (ContinuousMonoidHom.toContinuousMonoidHom e)
  have hφ : Multiplicative.toAdd (φ b) = 1 := by
    simp [φ, ψ, hb, ZMod.cast_one hn]
  refine hG.demushkinRank_ne_one_of_zmod_four_reduction_ne_zero φ (g := b) ?_ hrank
  rw [hφ, map_one]
  exact one_ne_zero

/-- A Demushkin group of rank one lives at `p = 2`: at an odd prime the rank is even. -/
theorem IsDemushkin.eq_two_of_demushkinRank_eq_one (hG : IsDemushkin p G)
    (h : demushkinRank hG = 1) : p = 2 :=
  by_contra fun hp ↦ hG.demushkinRank_ne_one_of_ne_two hp h

/-- **`ℤ/2` is the unique Demushkin group of rank one**: a Demushkin group of rank one is
topologically isomorphic to `ℤ/2`. It is procyclic; a generator of infinite order would make it
free pro-`p` of rank one, whose `H²` vanishes; a generator of finite order makes it a finite cyclic
group `ℤ/2ᵏ`, and for `k ≥ 2` the mod-`2` character lifts to `ℤ/4`, so its cup square vanishes,
against the nondegeneracy of the cup pairing on the line `H¹(G, 𝔽₂)`. -/
theorem IsDemushkin.nonempty_continuousMulEquiv_multiplicative_zmod_two_of_demushkinRank_eq_one
    (hG : IsDemushkin p G) (h : demushkinRank hG = 1) :
    Nonempty (G ≃ₜ* Multiplicative (ZMod 2)) := by
  obtain rfl := hG.eq_two_of_demushkinRank_eq_one h
  -- A Demushkin group of rank one is topologically generated by a single element `a`.
  obtain ⟨s, hcard, hgen⟩ :=
    exists_finset_card_eq_topologicalGeneratorRankNat hG.isTopologicallyFinitelyGenerated
  have h1 := h
  rw [demushkinRank_def hG] at h1
  rw [h1, Finset.card_eq_one] at hcard
  obtain ⟨a, rfl⟩ := hcard
  rw [Finset.coe_singleton] at hgen
  by_cases hfin : IsOfFinOrder a
  · obtain ⟨k, e, -⟩ :=
      hG.isProP.exists_continuousMulEquiv_multiplicative_zmod_pow_of_isOfFinOrder hgen hfin
    rcases k with _ | _ | k
    · -- `k = 0`: the group would be trivial, of rank zero.
      exfalso
      rw [pow_zero] at e
      have : Subsingleton (ZMod 1) := ZMod.subsingleton_iff.2 rfl
      have hsub : Subsingleton G := (e.toEquiv.trans Multiplicative.toAdd).subsingleton
      have hcard := topologicalGeneratorRankNat_eq_topologicalGeneratorRank
        hG.isTopologicallyFinitelyGenerated
      rw [h1, topologicalGeneratorRank_eq_zero_iff.2 hsub, Nat.cast_one] at hcard
      exact one_ne_zero hcard
    · -- `k = 1`: the group is `ℤ/2`.
      exact ⟨e⟩
    · -- `k ≥ 2`: `4 ∣ 2ᵏ`, so the group is not Demushkin.
      exact (not_isDemushkin_of_four_dvd_of_continuousMulEquiv_multiplicative_zmod ⟨2 ^ k, by ring⟩
        e hG).elim
  · -- A generator of infinite order makes `G` free pro-`2` of rank one, which is not Demushkin.
    exfalso
    obtain ⟨e⟩ := freeProP.nonempty_continuousMulEquiv_of_not_isOfFinOrder (X := PUnit.{u + 1})
      hG.isProP hgen hfin
    exact not_isDemushkin_freeProP PUnit.{u + 1} (IsDemushkin.of_equiv 2 hG e)

/-- **A Demushkin group has rank one exactly when it is topologically isomorphic to `ℤ/2`.** -/
theorem IsDemushkin.demushkinRank_eq_one_iff (hG : IsDemushkin p G) :
    demushkinRank hG = 1 ↔ Nonempty (G ≃ₜ* Multiplicative (ZMod 2)) := by
  refine ⟨hG.nonempty_continuousMulEquiv_multiplicative_zmod_two_of_demushkinRank_eq_one,
    fun ⟨e⟩ ↦ ?_⟩
  rw [demushkinRank_def hG, topologicalGeneratorRankNat_congr e,
    topologicalGeneratorRankNat_multiplicative_zmod 2]

end TauCeti
